tweak(loadout): add subscription system
ChaoticOnyx/OnyxBay pull request #10045
Opened 2023-02-07 16:19 UTC by Doster-d

Все реализовано в соотвествии с иссуем.

close #10015 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Теперь патроны получают возможность арендовать предметы разной ценевой категории согласно решению сената.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-02-07 16:33 UTC, Epicus7 reviewed
Есть некритические предложения по улучшению качества кода.

2023-02-07 16:33 UTC, Epicus7 commented on code/modules/donations/donator.dm
> +/datum/donator_info/proc/patron_type_tier_discount_applied(price)
![image](https://user-images.githubusercontent.com/5204667/217304061-69440a10-c16b-4473-abbe-a0163c75216f.png)

Лучше было бы назвать как-то типа
is_item_available_as_for_patron

2023-02-07 16:33 UTC, Epicus7 commented on code/__defines/donations_defines.dm
> +#define PATREON_ASSISTANT_DISCOUNT 100
Плохо что тут дублируются названия тиров. Лучше бы сделать список с ключами (словарь) "тип патрона -> максимальная цена доступных предметов". Тогда в функции `patron_type_tier_discount_applied` можно будет избавиться от свитча, а делать тупо

```
if (price <= patreon_type_to_max_available_items_price[patron_type])
   ....
```

2023-02-07 16:34 UTC, Doster-d commented on code/__defines/donations_defines.dm
> +#define PATREON_ASSISTANT_DISCOUNT 100
Ну я хотел, чтобы даже не погромист мог изменять эти значения, а то со словарем люди могут ошибаться, но можно и словарь, словарь мне больше нравится.

2023-02-07 16:37 UTC, Doster-d commented on code/modules/donations/donator.dm
> +/datum/donator_info/proc/patron_type_tier_discount_applied(price)
Ну я называл по такому принципу:
Так, у нас тут некая скидка, как скидка на английском будет? Discount.
Так скидка кому дается? Патронам
По какому принципу? Тип подписки патрона (type tier)
Возвращаем мы булевое значения, применилось или нет, ну значит applied.

Ну ок, заменю.

2023-02-07 16:41 UTC, Epicus7 commented on code/modules/donations/donator.dm
> +/datum/donator_info/proc/patron_type_tier_discount_applied(price)
Но это не скидка. Скидка это когда предмет дешевле становится. Тут скорее "подписка" какая-то тогда уж. Subscription

2023-02-07 16:48 UTC, Doster-d commented on code/__defines/donations_defines.dm
> +#define PATREON_ASSISTANT_DISCOUNT 100
Исправлено.

2023-02-07 16:48 UTC, Doster-d commented on code/modules/donations/donator.dm
> +/datum/donator_info/proc/patron_type_tier_discount_applied(price)
Исправлено.

2023-02-12 11:29 UTC, kreeperHLC requested changes
Запятая лишняя

2023-02-12 11:29 UTC, kreeperHLC commented on code/modules/donations/donator.dm
> +		PATREON_ASSISTANT = 100,
```suggestion
		PATREON_ASSISTANT = 100
```

2023-02-12 11:31 UTC, kreeperHLC approved these changes
Ну не лишняя так не лишняя

2023-02-19 12:33 UTC, Tsurupeta approved these changes
Название функции, конечно, ужасное, но пойдёт.

2023-02-26 15:26 UTC, merged