rscadd(donat_shop): Loadout Upgrade
ChaoticOnyx/OnyxBay pull request #10053
Opened 2023-02-14 14:47 UTC by Medjic

По просьбе вышестоящего руководства разработки ООО Кхаотик Оникс, была добавлена новая одежда для космонавтов в компьютерную игру "Спейс статион тхёртин". Ресурсы взяты с конкурса спрайтов.
![image](https://user-images.githubusercontent.com/75128764/218770877-edacbd83-75e1-437a-a22a-d18e84cdec95.png)
https://github.com/ChaoticOnyx/OnyxBay/issues/3607

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавление новой одежды в билд.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-02-14 21:22 UTC, TobyThorne commented on code/game/objects/items/storage/backpack.dm
> +		)
это нахер тут

2023-02-14 21:23 UTC, TobyThorne commented on code/modules/clothing/glasses/glasses.dm
> +	icon_state = "magma_dual_glasses"
еол проёбан

2023-02-14 21:23 UTC, TobyThorne commented on code/modules/clothing/head/misc.dm
> +	armor = list(melee = 10, bullet = 10, laser = 5,energy = 0, bomb = 0, bio = 0)
и здесь

2023-02-14 21:24 UTC, TobyThorne commented
кринжанул с дескрипшонов, дизайн-войска в атаку

2023-02-14 21:25 UTC, Medjic commented on code/modules/clothing/head/misc.dm
> +	armor = list(melee = 10, bullet = 10, laser = 5,energy = 0, bomb = 0, bio = 0)
Меня попросили добавить в билд без допольнительного описания - я добавил в надежде на доработку от сторонних людей и впиливание всего этого в лодаут.

2023-02-14 21:27 UTC, Medjic commented
Дескпришенами не я должен заниматься...

2023-02-15 16:46 UTC, Tsurupeta commented on code/modules/clothing/head/misc.dm
> +	armor = list(melee = 10, bullet = 10, laser = 5,energy = 0, bomb = 0, bio = 0)
```suggestion
	armor = list(melee = 10, bullet = 10, laser = 5,energy = 0, bomb = 0, bio = 0)

```

2023-02-15 16:47 UTC, Tsurupeta commented on code/modules/clothing/spacesuits/void/misc.dm
> +	light_overlay = "helmet_light_dual"
```suggestion
	light_overlay = "helmet_light_dual"

```

2023-02-15 16:49 UTC, NefrNerf commented on code/game/objects/items/storage/backpack.dm
> +	desc = "It's a backpack visual as cpacecraft."
spacecraft

2023-02-15 16:49 UTC, NefrNerf commented on code/modules/clothing/head/misc.dm
> +	desc = "Edgy asia hat."
asian

2023-02-15 16:49 UTC, NefrNerf commented on code/modules/clothing/head/misc.dm
> +	desc = "Alien accesuar fron WetSkrell."
from

2023-02-15 16:51 UTC, Tsurupeta commented on code/modules/clothing/glasses/glasses.dm
> +	icon_state = "magma_dual_glasses"
```suggestion
	icon_state = "magma_dual_glasses"

```

2023-02-15 16:56 UTC, Tsurupeta commented on code/modules/clothing/glasses/glasses.dm
> +	desc = "Welding goggles made from more expensive materials, strangely smells like potatoes."
```suggestion
/obj/item/clothing/glasses/magma_dark_glasses
	name = "dark gar glasses"
	desc = "Stylish pair of dark-colored glasses made from expensive materials."
	icon_state = "magma_dark_glasses"

/obj/item/clothing/glasses/magma_red_glasses
	name = "red gar glasses"
	desc = "Stylish pair of red-colored glasses made from expensive materials."
	icon_state = "magma_red_glasses"

/obj/item/clothing/glasses/magma_dual_glasses
	name = "dual gar glasses"
	desc = "Stylish pair of dual-colored glasses made from expensive materials."
```

2023-02-17 09:41 UTC, kreeperHLC submitted a review, later dismissed

2023-02-26 17:32 UTC, PlinHost requested changes, later dismissed

2023-02-26 17:32 UTC, PlinHost commented on code/game/objects/items/storage/backpack.dm
> +	desc = "It's a backpack visual as spacecraft."
Ваш английский огорчает улиток

2023-03-05 13:01 UTC, PlinHost commented on code/modules/clothing/head/misc.dm
> +	desc = "Alien antennas made of plastic and reminiscent of almost forgotten science fiction."
```suggestion
	desc = "Alien antennae made of plastic and reminiscent of almost forgotten science fiction."
```

2023-03-05 14:52 UTC, Epicus7 commented on code/modules/clothing/head/misc.dm
> +	desc = "Alien antennas made of plastic and reminiscent of almost forgotten science fiction."
Я пофиксил

2023-03-05 16:42 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/222973754-6670df26-eaea-46fd-87c3-ac3957571ae3.png)
Зочем удалил?

2023-03-05 16:42 UTC, Doster-d commented
А, переназвла

2023-03-05 16:47 UTC, Doster-d approved these changes
I'm going to nut

2023-03-10 14:51 UTC, kreeperHLC approved these changes

2023-03-10 14:52 UTC, merged