fix(dropping): you can't disentigrate stuff through vents now
ChaoticOnyx/OnyxBay pull request #10054
Opened 2023-02-14 17:50 UTC by IvanDonFon

Предметы больше нельзя бросать в вентиляции, а значит проблемы с тем, что таким образом их дезинтегрируют, больше не будет.

resolve #9340 

<details>
<summary>Чейнджлог</summary>

```yml 
🆑 Donaldo_TH
bugfix: Больше нельзя бросать предметы в вентиляции
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-02-14 17:57 UTC, IvanDonFon commented
Да бля, этот иссуй сделать проще было, чем написать рабочий чейнджлог

2023-02-14 18:05 UTC, Tsurupeta commented
> Да бля, этот иссуй сделать проще было, чем написать рабочий чейнджлог

ну пофикси чейнджлог бота нам

2023-02-14 18:06 UTC, IvanDonFon commented
:^(

2023-02-14 18:07 UTC, Tsurupeta commented
Чел, я могу просто на кнопку дропа нажать, физически. В обход твоей проверки смешной.

2023-02-14 18:12 UTC, No-Tips commented on code/_onclick/hud/screen_objects.dm
> +					to_chat(L, "<span class='notice'>You can't drop items in the vent.</span>")
Спаны в макросы переделай

2023-02-14 18:13 UTC, IvanDonFon commented on code/_onclick/hud/screen_objects.dm
> +					to_chat(L, "<span class='notice'>You can't drop items in the vent.</span>")
Уже делаю

2023-02-14 18:14 UTC, No-Tips commented
Ну и да, как сказал ИЕ - оно фиксит лишь один способ, при нажатии на кнопку дропа, но не при нажатии Q или drop в вербах

2023-02-14 18:14 UTC, Tsurupeta commented
Это тоже не единственные способы заставить человека уронить предмет.

2023-02-14 18:17 UTC, Zert0X commented
Вы бы лучше просто сделали что если айтем падает в трубе он летит как мусор

2023-02-14 18:19 UTC, Tsurupeta commented
> Вы бы лучше просто сделали что если айтем падает в трубе он летит как мусор

Для атмос труб тоже мусор?

2023-02-14 18:20 UTC, Zert0X commented
> > Вы бы лучше просто сделали что если айтем падает в трубе он летит как мусор
> 
> Для атмос труб тоже мусор?

Для атмос труб МБ блочит трубу если размер >medium
и если меньше то пусть лежит в трубе и никому не мешает

2023-02-14 18:22 UTC, IvanDonFon commented
> Это тоже не единственные способы заставить человека уронить предмет.

При потере рук и прочем говне предметы и так выпадают из трубы

2023-02-14 21:53 UTC, TobyThorne commented on code/modules/mob/mob_movement.dm
> +		to_chat(usr, "<span class='notice'>You can't drop items in the vent.</span>")
```suggestion
		to_chat(usr, SPAN("warning", "You can't drop items in the vent."))
```

2023-02-15 16:49 UTC, Doster-d requested changes
Модифицируй drop_active_hand у /mob/living/carbon введя свою проверку. Убери у 77 (74) строки force = TRUE

2023-02-15 16:50 UTC, Doster-d commented
Еще лучше переместить проверку в can_unequip, но тогда сломается перемещение предметов в пределах инветаря, а это плохо как по мне.

2023-02-15 17:02 UTC, IvanDonFon commented
> Модифицируй drop_active_hand у /mob/living/carbon введя свою проверку. Убери у 77 (74) строки force = TRUE

Я не совсем понимаю твой ход мыслей. Прок, в котором сейчас лежит проверка есть только у /mob/living/carbon и подтипов и так. drop_active_hand(И похожие проки), если верить комментариям в файлике с ним лучше вообще не трогать, а только вызывать в рамках других функций. И я правда, не совсем понимаю, зачем нужно модифицировать именно его.

2023-02-15 17:11 UTC, Doster-d commented
В данный момент твой код покрывает только одну из дырок - вызов на хоткее.
Есть еще вызов через верб и на прямую из кода.
Мы должны исходить из того, что игрок хочет сломать нам игру (выбросить предмет в трубу, считай нулл спейс, вполне подходит под это) или погромист-дурачок своими корявыми ручками полез и в результате этого может сломать нам логику.
Если не нравится дроп актив хенд, то можно модифицировать /mob/living/carbon/drop добавив проверку на то, что мы в вентиляции.
А изначально я имел в виду создать переопределение этого прока (drop_active_hand) и там сделать проверку на то, что мы в вентиляции и удалить force = TRUE у drop_active_hand потому, что это не имеет смысла, мы уже сделали проверку.

2023-02-15 17:29 UTC, IvanDonFon commented
> В данный момент твой код покрывает только одну из дырок - вызов на хоткее. Есть еще вызов через верб и на прямую из кода. Мы должны исходить из того, что игрок хочет сломать нам игру (выбросить предмет в трубу, считай нулл спейс, вполне подходит под это) 

У карбонов и хуманов все способы броска предмета так или иначе вызывают прок хоткея, от которого потом идёт логика. Другие мобы либо не могут держать предметов в целом, либо не задуманы под то, что за них может играть человек, если не то и другое.
А переопределять эту функцию звучит скорее как спаггети код

2023-02-15 17:32 UTC, Doster-d commented
> У карбонов и хуманов все способы броска предмета так или иначе вызывают прок хоткея, от которого потом идёт логика. Другие мобы либо не могут держать предметов в целом, либо не задуманы под то, что за них может играть человек, если не то и другое. А переопределять эту функцию звучит скорее как спаггети код

Не совсем истина
![image](https://user-images.githubusercontent.com/63081538/219107628-a39981c8-e532-4a82-8420-c4ab81125a5f.png)

2023-02-15 17:37 UTC, IvanDonFon commented
Может тогда прописать просто ещё и вербу эту проверку? Ему, судя по комментарию, одиннадцать лет, а той функции наверное, уже двадцать

2023-03-07 20:21 UTC, IvanDonFon commented
Мне ивент делать надо, потом эту хрень исправлю

2023-03-07 20:21 UTC, closed without merging