feat(storyteller): adds weighted pick for antags depending on their zlevel
ChaoticOnyx/OnyxBay pull request #10060
Opened 2023-02-19 10:28 UTC by Tsurupeta

close #2469

<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Сторителлер теперь выдаёт роли людям вне станции с шансом в 2 раза ниже, чем людям на ней.
fix: Мобы, находящиеся на з-уровне ЦК больше не могут становиться антагонистами.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-02-19 14:45 UTC, Epicus7 requested changes

2023-02-19 14:45 UTC, Epicus7 commented on code/game/antagonist/antagonist.dm
> +		var/datum/mind/player = util_pick_weight(candidates)
А что будет, если все игроки на ЦК? Походу в `util_pick_weight` вызовется `rand(0, total)`, где `total == 0`. В итоге вернется null и мы попытаемся его вычесть из candidates, а потом драфтить как антагониста.

Я бы добавил тут где-то проверку на null, и нужно в этом случае возвращать 0, видимо, т.к. заспавнить не получилось.

2023-02-19 14:45 UTC, Epicus7 commented on code/game/antagonist/antagonist.dm
> +			candidates[player] = get_candidate_weight(player)
```suggestion
			candidates[player] = get_candidate_weight(player)
```
А так, разве, нельзя сделать? В одну строчку

2023-02-19 14:56 UTC, Tsurupeta commented on code/game/antagonist/antagonist.dm
> +		var/datum/mind/player = util_pick_weight(candidates)
В целом, можно просто не драфтить людей на ЦК и тут будет candidates.len == 0.

2023-02-19 15:01 UTC, Epicus7 commented on code/game/antagonist/antagonist.dm
>  			log_debug_verbose("[key_name(player)] is eligible to become a [role_text]")
Вот эту строчку тогда перенеси ниже

2023-02-19 15:01 UTC, Epicus7 commented on code/game/antagonist/antagonist.dm
> +		var/datum/mind/player = util_pick_weight(candidates)
Да, так лучше реально

2023-02-19 15:03 UTC, Tsurupeta commented on code/game/antagonist/antagonist.dm
>  			log_debug_verbose("[key_name(player)] is eligible to become a [role_text]")
Да, пропустил её.

2023-02-20 12:36 UTC, Epicus7 approved these changes

2023-02-20 12:53 UTC, Doster-d approved these changes

2023-02-26 15:16 UTC, merged