feat(emt_backpack): backpack for emt
ChaoticOnyx/OnyxBay pull request #10073
Opened 2023-03-12 11:31 UTC by Inv4de-R

В билде без дела лежат готовые текстурки под все бодитайпы для EMT (подпрофы парамедиков), поэтому добавил их в шкафчики парамедиков, а также в лодаут как дефолтные, если выбирать соответствующую профу.

![1](https://user-images.githubusercontent.com/80645058/224541643-557a493c-cb8e-45d7-ad77-6305baf54dcb.PNG)
![2](https://user-images.githubusercontent.com/80645058/224541665-c2e88e03-b680-48e5-a9cb-56c63efaaea5.PNG)

<details>
<summary>Чейнджлог</summary>

```yml
🆑 Inv4deR
rscadd: Добавлены несколько типов сумок для EMT.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-15 14:22 UTC, kreeperHLC requested changes

2023-03-15 14:22 UTC, kreeperHLC commented on code/datums/outfits/jobs/medical.dm
> +/decl/hierarchy/outfit/job/medical/paramedic/emt/New()
```suggestion
	uniform = /obj/item/clothing/under/rank/medical/paramedic

/decl/hierarchy/outfit/job/medical/paramedic/emt/New()
```

2023-03-16 08:38 UTC, kreeperHLC approved these changes

2023-03-25 12:04 UTC, Tsurupeta approved these changes

2023-03-25 12:15 UTC, merged