add custom item for incarnator
ChaoticOnyx/OnyxBay pull request #10097
Opened 2023-03-22 22:58 UTC by incatnator

Исправлено отсутствие накладных сисек в билде.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-22 23:03 UTC, Doster-d requested changes, later dismissed
![IMG_20230321_122035_632.jpg](https://user-images.githubusercontent.com/63081538/227057904-f21305a8-cc1b-4e9d-a78e-3e6a63c3bf50.jpg)

2023-03-22 23:03 UTC, Doster-d commented on code/modules/clothing/custom_clothing.dm
> +	H.update_underwear()
Нет ньюлайна

2023-03-22 23:04 UTC, incatnator commented on code/modules/clothing/custom_clothing.dm
> +	H.update_underwear()
![image](https://user-images.githubusercontent.com/61589111/227058030-fa140af8-2a36-434b-8e58-7a9050f39379.png)

2023-03-22 23:06 UTC, NoneOfYourBsns commented on code/modules/clothing/custom_clothing.dm
> +	var/mob/living/carbon/human/H = usr
```suggestion

	var/mob/living/carbon/human/H = usr
```

2023-03-22 23:06 UTC, Tsurupeta commented on code/modules/clothing/custom_clothing.dm
> +	H.update_underwear()
А ассерт тут при чем шиз

2023-03-23 07:29 UTC, Animesku commented
Ты че ебанутый?

2023-03-23 09:12 UTC, No-Tips commented
Он реально за кастомку сделал накладные бубсы. Проклято

2023-03-23 18:45 UTC, Doster-d reviewed
Вайб того как работала раньше дивизион у генки

2023-03-23 18:45 UTC, Doster-d commented on code/modules/clothing/custom_clothing.dm
> +			BB = new /datum/body_build/slim
```suggestion
	var/datum/species/S = = all_species[H.get_species()]
	if(!istype(S))
		return ..()
	switch(H.get_species())
		if(SPECIES_TAJARA)
			BB = S.body_builds[2] // slim alt tajaran
		if(SPECIES_UNATHI)
			BB = S.body_builds[1] // unathi
		else
			BB = S.body_builds[2] // slim for human and skrell
```

2023-03-23 19:00 UTC, Doster-d commented on code/modules/clothing/custom_clothing.dm
> +	var/datum/species/S = = all_species[H.get_species()]
compiler error
```suggestion
	var/datum/species/S = all_species[H.get_species()]
```

2023-03-23 19:01 UTC, NoneOfYourBsns commented on code/modules/clothing/custom_clothing.dm
> +/obj/item/underwear/top/silicone_top/RemoveUnderwear(mob/user)
```suggestion
/obj/item/underwear/top/silicone_top/RemoveUnderwear(mob/user, mob/living/carbon/human/H)
```

2023-03-23 19:01 UTC, Doster-d commented on code/modules/clothing/custom_clothing.dm
> +			BB = S.body_builds[2] // slim alt tajaran
Не знаю насколько это окей, я не нашел способ сделать лучше.

2023-03-23 19:07 UTC, NoneOfYourBsns commented on code/modules/clothing/custom_clothing.dm
> +
```suggestion
```

2023-03-23 19:07 UTC, NoneOfYourBsns commented on code/modules/clothing/custom_clothing.dm
> +/obj/item/underwear/top/silicone_top/ForceEquipUnderwear(mob/user)
```suggestion
/obj/item/underwear/top/silicone_top/ForceEquipUnderwear(mob/living/carbon/human/H, update_icons = TRUE)
```

Тут тоже потерял аргументы.

2023-03-23 19:07 UTC, NoneOfYourBsns commented on code/modules/clothing/custom_clothing.dm
> +
```suggestion
```

Убираем, ибо объект, на который надевается предмет уже подан в функцию. 'usr' - держащий в руке предмет субъект, в следствие чего спрайт будет меняться не только на желаемом персонаже, но и надевающем предмет на оного. Надеюсь, понятно объяснил.

2023-03-24 14:46 UTC, closed without merging