Экстренный фикс H/E труб.
ChaoticOnyx/OnyxBay pull request #10098
Opened 2023-03-23 13:56 UTC by Pl3aseJust3ndMySuffering

У ЕОСовцев сломалась карта из-за сломанного процессинга труб. Временный фикс, в дальнейшем привяжите это к atmos_init() у pipe_network.

Bob.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Heat Exchanger pipes no longer abide by network processing rules.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-23 15:57 UTC, Doster-d commented
чейнджлог пишется на русском языке

2023-03-23 15:59 UTC, Doster-d requested changes

2023-03-23 15:59 UTC, Doster-d commented on code/modules/atmospherics/he_pipes.dm
> +	START_PROCESSING(SSmachines, src)
Не является решением проблемы.
Проблема в конфликте /New и /Initialize

2023-03-24 21:00 UTC, Pl3aseJust3ndMySuffering commented
Хотя не, я отказываюсь в этом копаться. Разработка нуфазы продолжается.

2023-03-24 21:00 UTC, closed without merging