Adding a librarian's cart#4756
ChaoticOnyx/OnyxBay pull request #10092
Opened 2023-03-21 10:18 UTC by Terydd

Добавляется новый объект на основе тележки уборщика и шкафа для книг и его изображение. Изображение для упрощения ориентирования добавлено в дми для библиотеки

close #4756

```yml
🆑
rscadd: В билд добавлена тележка для библиотекаря.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-23 03:20 UTC, kreeperHLC requested changes
А ещё у тебя коммит с медалями затесался, его нужно убрать

2023-03-23 03:20 UTC, kreeperHLC commented on code/game/objects/structures/librarycart.dm
> +	var/amount_per_transfer_from_this = 5 //shit I dunno, adding this so syringes stop runtime erroring. --NeoFite
Не нужно

2023-03-23 03:20 UTC, kreeperHLC commented on code/game/objects/structures/librarycart.dm
> +/obj/structure/librarycart/New()
Почему пустое? И главное зачем.

2023-03-23 03:20 UTC, kreeperHLC commented on code/game/objects/structures/librarycart.dm
> +		if(3.0)
Вот тут циферки поменяй на дефайны

2023-03-23 10:52 UTC, Terydd commented on code/game/objects/structures/librarycart.dm
> +/obj/structure/librarycart/New()
У оригинала так было, я хз, как оно работало, решила не трогать

2023-03-23 10:53 UTC, Terydd commented on code/game/objects/structures/librarycart.dm
> +		if(3.0)
Что за дефайны?

2023-03-23 10:56 UTC, Terydd commented on code/game/objects/structures/librarycart.dm
> +	var/amount_per_transfer_from_this = 5 //shit I dunno, adding this so syringes stop runtime erroring. --NeoFite
Все четыре строчки или что-то конкретное?

2023-03-23 10:58 UTC, Tsurupeta commented on code/game/objects/structures/librarycart.dm
> +		if(3.0)
Лок не меняй, форсмув используй

2023-03-23 11:34 UTC, Terydd commented on code/game/objects/structures/librarycart.dm
> +		if(3.0)
Я попробую. А разница какая?

2023-03-23 13:44 UTC, Tsurupeta commented on code/game/objects/structures/librarycart.dm
> +		if(3.0)
очень большая

2023-03-23 14:30 UTC, NoneOfYourBsns commented on code/game/objects/structures/librarycart.dm
> +		var/title = input("Which book would you like to remove from the shelf?") as null|anything in titles
Так это тележка, можно копипасту исправить?

2023-03-23 14:35 UTC, NoneOfYourBsns commented
> Добавляется новый объект на основе тележки уборщика и шкафа для книг и его изображение. Изображение для упрощения ориентирования добавлено в дми для библиотеки

Полагаю, тогда стоит сделать мастер-объект тележку и от нее унаследовать тележку уборщика и библиотекаря, тем более автор пулла говорит в комментарии, что объект буквально копипаста.

> I'm almost not ashamed of the fact that this is a recycling of a cleaner's cart. I will try not to delete the old hints, suddenly they will be needed.

Комменты вообще не по делу, их бы просто стереть и все. Судя по коду, автор не читал вот [эту статью по правилам контрибутинга](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-23 14:48 UTC, Tsurupeta requested changes
у тебя ещё и медали протекли сюда, переделывай

2023-03-23 16:54 UTC, NoneOfYourBsns commented on code/game/objects/structures/librarycart.dm
> +	density = 1
Я только сейчас осознал, что тут проблема. Тут же принято, что нули и единицы, подразумевающие булевы значения заменяем на `FALSE` и `TRUE`.

2023-03-23 17:06 UTC, NoneOfYourBsns commented on code/game/objects/structures/librarycart.dm
> +		icon_state = "library_cart-4"
```suggestion
	icon_state = "library_cart-[clamp(contents.len, 0, 4)]"
```

2023-03-23 20:10 UTC, Terydd commented on code/game/objects/structures/librarycart.dm
> +		icon_state = "library_cart-4"
Можно для совсем тупых, как работает предлагаемое изменение?

2023-03-23 20:11 UTC, Tsurupeta commented on code/game/objects/structures/librarycart.dm
> +		icon_state = "library_cart-4"
https://www.byond.com/docs/ref/#/proc/clamp

2023-03-23 20:12 UTC, NoneOfYourBsns commented on code/game/objects/structures/librarycart.dm
> +		icon_state = "library_cart-4"
`0` - наименьшее значение, `4` - наибольшее, `contents.len` - твое значение. Подробнее [тут](https://www.byond.com/docs/ref/#/proc/clamp).

2023-03-25 10:30 UTC, kreeperHLC commented on code/game/objects/structures/librarycart.dm
> +	var/amount_per_transfer_from_this = 5 //shit I dunno, adding this so syringes stop runtime erroring. --NeoFite
fix(closets): remove ability to hack distant closet

2023-03-25 10:31 UTC, kreeperHLC commented on code/game/objects/structures/librarycart.dm
> +/obj/structure/librarycart/New()
В том то и дело, что оно ничего не делет

2023-03-28 14:59 UTC, Doster-d reviewed
Ничего не исправлено

2023-03-28 18:30 UTC, Terydd commented
Да, я пытаюсь разобраться, как сделать это правильно.

2023-04-03 10:44 UTC, Terydd commented
У меня мозг рака, пока не до конца понимаю, как нормально доставлять свою фигню на гитхаб. Закрываю для что бы разобраться и закинуть уже в нормальном виде, без сотни лишних изменений.

2023-04-03 10:44 UTC, closed without merging