feat(signaler): removes lack of modern ui for signaler
ChaoticOnyx/OnyxBay pull request #10117
Opened 2023-03-27 19:22 UTC by NoneOfYourBsns

Обновил сигналеры, теперь они используют современное, красивое и удобное для дебага TGUI.
![HWTkX91Apz](https://user-images.githubusercontent.com/118671019/228044649-49fb84bd-5d84-4fba-a060-5392a21c4c2e.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: обновлен интерфейс сигналера.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-27 19:26 UTC, Tsurupeta commented
и где кнопочки

2023-03-27 19:27 UTC, NoneOfYourBsns commented
Либо мышью тянешь вверх/вниз, либо напрямую вводишь нужное число. Число можно подгружать даже из буфера обмена(!).

2023-03-27 19:27 UTC, Tsurupeta commented
Тянуть мышкой вверх-вниз крайне неудобно, а количество кликов кнопочки легче запоминается

2023-03-27 19:29 UTC, NoneOfYourBsns commented
Тогда можно ввести напрямую. Кнопочки устарели.

2023-03-27 19:29 UTC, Tsurupeta commented
Значит вешаем геймдизайн

2023-03-27 19:30 UTC, NoneOfYourBsns commented
Он тут обязателен, все-таки это больше на фичу тянет.

2023-03-27 19:30 UTC, kreeperHLC submitted a review, later dismissed

2023-03-27 19:31 UTC, kreeperHLC commented
А какой у тебя ник в дискорде?

2023-03-28 10:12 UTC, igorsaux submitted a review, later dismissed

2023-03-28 14:40 UTC, NoneOfYourBsns commented
> А какой у тебя ник в дискорде?

Если свой дашь - могу добавиться в друзья. Я Дискорд только для личного общения использую.

2023-04-06 14:57 UTC, NoneOfYourBsns commented
@Zert0X , прошу прощения за чрезмерную наглость, но можешь еще данный проект посмотреть?

2023-04-06 15:17 UTC, Zert0X commented
> @Zert0X , прошу прощения за чрезмерную наглость, но можешь еще данный проект посмотреть?

ТГУИ конечно не у всех игроков работает, но похуй

2023-04-06 15:18 UTC, igorsaux commented
> > @Zert0X , прошу прощения за чрезмерную наглость, но можешь еще данный проект посмотреть?
> 
> ТГУИ конечно не у всех игроков работает, но похуй

:trollface:

2023-04-06 15:37 UTC, Zert0X commented
> @Zert0X , прошу прощения за чрезмерную наглость, но можешь еще данный проект посмотреть?

А бля, кнопочки +- нет. Не катит

2023-04-06 15:40 UTC, NoneOfYourBsns commented
@Zert0X , кнопочки были нужны, ибо ты не мог руками вводить. В новом УИ ты либо тянешь вверх/вниз, либо вводишь прямо с клавиатуры, что в сто раз удобнее.

2023-04-06 15:42 UTC, Tsurupeta commented
>тянешь вверх/вниз что в сто раз удобнее

:trollface:

2023-04-06 15:42 UTC, NoneOfYourBsns commented
Они просто не нужны с учетом предоставленного ТГУИ функционала.

2023-04-06 15:43 UTC, Zert0X commented
> @Zert0X , кнопочки были нужны, ибо ты не мог руками вводить. В новом УИ ты либо тянешь вверх/вниз, либо вводишь прямо с клавиатуры, что в сто раз удобнее.

нашлись нытики @Tsurupeta которым легче запомнить:
3 клика влево, чем частоту
также кнопочками быстро можно было смещать частоту на нужную
147,7 - клик - взрыв - +1 - повторять до удовлетворения.

Договаривайся с ним чтобы он не трахал мне мозги ибо он меня заебал.

2023-04-06 15:43 UTC, Tsurupeta commented
Предлагаю удалить нахер перетягивание ввер/вниз о котором ничего не подозревающий космонавт даже не догадается и просто вернуть кнопочки, что будет лучшим от двух миров, а не заменой одного говна на другое.

2023-04-06 15:45 UTC, NoneOfYourBsns commented
Я не вижу смысла возвращаться к старому концепту интерфейса, с учетом возможности ручного ввода. Функцию драга предоставляет ТГУИ из коробки, зачем костылями ее удалять, если лично Tsurapeta она не нужна.

2023-04-06 15:46 UTC, Zert0X commented
> Я не вижу смысла возвращаться к старому концепту интерфейса, с учетом возможности ручного ввода. Функцию драга предоставляет ТГУИ из коробки, зачем костылями ее удалять, если лично Tsurapeta она не нужна.

Ему просто не нравится, что:
1. Драг не интуитивен
2. Что нельзя быстро добавить/убавить частоту, код. Ибо он не может их запомнить и ввести с клавы

2023-04-06 15:48 UTC, Tsurupeta commented
Кнопочки плюса и минуса добавь со старого интерфейса заеб

2023-04-06 15:52 UTC, NoneOfYourBsns commented
Ты предлагаешь перегрузить интерфейс лишними кнопками т.к ты один не можешь запомнить частоту для своей же бомбы?

2023-04-06 15:53 UTC, Tsurupeta commented
Бомба никогда не была одной.

2023-04-06 16:00 UTC, NoneOfYourBsns commented
@Zert0X , возможность драга максимально интуитивна. Ты когда наводишь мышь на инпутбокс - иконка курсора меняется.

![изображение](https://user-images.githubusercontent.com/118671019/230433834-c1d4c78b-5eec-43a7-b094-cff24005a938.png)

2023-04-06 16:03 UTC, Tsurupeta commented
Максимально интуитивна и крайне не удобно, когда нужно делать мелкие изменения, а вводить четыре цифры и ОБЯЗАТЕЛЬНО ТОЧКУ, потому что система измерений английская - долговастенько

2023-04-06 16:04 UTC, Zert0X commented
> @Zert0X , возможность драга максимально интуитивна. Ты когда наводишь мышь на инпутбокс - иконка курсора меняется.
> 
> ![изображение](https://user-images.githubusercontent.com/118671019/230433834-c1d4c78b-5eec-43a7-b094-cff24005a938.png)

В общем мне тут надоело писать, окончательные требования:
1. Добавить кнопочки как раньше, драг не выключать
2. Починить ввод с клавы ибо он чувствителен к точке а запятую не воспринимает

2023-04-06 16:04 UTC, NoneOfYourBsns commented
Это в сто раз удобнее, чем двадцать раз по плюсику тыкать.

2023-04-06 16:04 UTC, Zert0X commented
> Это в сто раз удобнее, чем двадцать раз по плюсику тыкать.

никто не просит вырубать остальные две фичи(драк и клаву), просят добавить кнопки обратно

2023-04-06 16:05 UTC, Tsurupeta commented
Вводить с клавиатуры удобно на большие изменения, а по плюсику раз тыкнуть удобнее чем вводить с клавиатуры изменение на соседнюю частоту. Никто не просит удалить ввод с клавиатуры, но драг реально хуже чем простые плюсики для точных мелких действий.

2023-04-06 16:08 UTC, NoneOfYourBsns commented
> никто не просит вырубать остальные две фичи(драк и клаву), просят добавить кнопки обратно

Мне это прямым текстом говорит один из комментаторов под моим проектом. Хорошо, я готов пойти на уступку и добавить кнопки для смены частоты, код двузначный и ТАКОЙ ТОЧНОСТИ не требует, полагаю.

2023-04-06 16:10 UTC, Zert0X commented
> > никто не просит вырубать остальные две фичи(драк и клаву), просят добавить кнопки обратно
> 
> Мне это прямым текстом говорит один из комментаторов под моим проектом. Хорошо, я готов пойти на уступку и добавить кнопки для смены частоты, код двузначный и ТАКОЙ ТОЧНОСТИ не требует, полагаю.

Чтобы не гневить сердца стариков коду тоже нужны кнопки

2023-04-06 16:11 UTC, NoneOfYourBsns commented
Слушай, я все понимаю, но кнопки для изменения двузначного значения - перебор же.

2023-04-06 16:11 UTC, Zert0X commented
> Слушай, я все понимаю, но кнопки для изменения двузначного значения - перебор же.

Были? Были.

2023-04-06 16:12 UTC, Zert0X commented
> Слушай, я все понимаю, но кнопки для изменения двузначного значения - перебор же.

У одного криворукого не получилось драгом это сделать правильно

2023-04-06 16:12 UTC, NoneOfYourBsns commented
Пускай введет с клавиатуры, это всего две цифры, даже без точки.

2023-04-06 16:13 UTC, Tsurupeta commented
Ладно похуй на код уже, заебал конкретно выёбываться.

2023-04-06 16:14 UTC, NoneOfYourBsns commented
Немного не понимаю, зачем переходить на мат, культурно же общаемся.

2023-04-06 16:16 UTC, Zert0X commented
Заебали блять я ща просто закрою эту хуйню и будете сидеть тыкаться в старый интерфейс два дебила. Один блять орёт не нужны кнопки везде и что удобно и ЧТО ОН ИДЁТ НА УСТУПКУ ЕБАТЬ БАРИН. А второй орёт что нужны кнопки и что он криворукая горила с одной извилинной которая не может запомнить ебаную частоту.

ПОВТОРЮ ПЕРВЫЙ И ПОСЛЕДНИЙ РАЗ:

1. Добавить кнопочки как раньше, в том числе и для кода!
2. Драг не выключать, ввод с клавы тоже
2. Починить ввод с клавы ибо он чувствителен к точке а запятую не воспринимает

2023-04-06 16:16 UTC, Tsurupeta commented
Ну в целом я буду рад больше старому интерфейсу, чем новому текущей итерации ПРа. Как говорится, работает - не трожь.

2023-04-06 16:17 UTC, igorsaux commented
![image](https://user-images.githubusercontent.com/55196698/230437595-8c5bebbe-60ae-4bdd-9ae1-f365b7b0fba9.png)

Запилите такие крутилки как на рациях - одну для изменения числа до запятой, вторую - для числа после запятой :trollface:

2023-04-06 16:17 UTC, Tsurupeta commented
Но я не овнер, так что слушай ловлу лол.

2023-04-06 18:35 UTC, NoneOfYourBsns commented
@Zert0X , вот такой вариант устраивает? 
 
![wBWTxrU5x3](https://user-images.githubusercontent.com/118671019/230465719-492984cd-d682-48b4-9fb8-84c0cee86ff9.png)

![x1ekV3v4ZP](https://user-images.githubusercontent.com/118671019/230465741-6c42a0d8-f898-4944-a122-803b9c82d8b2.png)

2023-04-06 18:38 UTC, Zert0X commented
> 

Лучше конечно с точкой/запятой. Но если не можешь то пойдёт и так

2023-04-06 19:25 UTC, NoneOfYourBsns commented
@Zert0X , такой ввод определенно сделать можно, но придется добавлять лишнюю логику в УИ. Главное, что сейчас ты когда хочешь скопировать частоту - ты копируешь четырехзначное число, когда ты вставляешь оно принимается, так что можно упустить через запятую ввод, как мне кажется. 

Я еще немного подправил лейаут, такой вариант устраивает?

![изображение](https://user-images.githubusercontent.com/118671019/230475540-c37b1b79-eed7-4be3-b81f-30f001f99f97.png)

2023-04-06 19:28 UTC, Zert0X commented
> @Zert0X , такой ввод определенно сделать можно, но придется добавлять лишнюю логику в УИ. Главное, что сейчас ты когда хочешь скопировать частоту - ты копируешь четырехзначное число, когда ты вставляешь оно принимается, так что можно упустить через запятую ввод, как мне кажется.
> 
> Я еще немного подправил лейаут, такой вариант устраивает?
> 
> ![изображение](https://user-images.githubusercontent.com/118671019/230475540-c37b1b79-eed7-4be3-b81f-30f001f99f97.png)

Пойдёт.

2023-04-06 20:00 UTC, kreeperHLC submitted a review, later dismissed

2023-04-07 05:10 UTC, Doster-d requested changes

2023-04-07 05:10 UTC, Doster-d commented on code/modules/assembly/signaler.dm
> +				code = text2num(params["code"])
Код мин максится, никогда не доверяй клиентскому инпуту
```suggestion
				code = Clamp(text2num(params["code"]), 0, 100)
```

2023-04-07 05:10 UTC, Doster-d commented on code/modules/assembly/signaler.dm
> +				. = TRUE
Не проще ли ```. = TRUE``` переместить за ```switch(action)``` и выиграть 2 строчки?

2023-04-08 12:25 UTC, NoneOfYourBsns commented on code/modules/assembly/signaler.dm
> +				. = TRUE
Мысль отличная, в следующем коммите поправлю.

2023-04-16 01:08 UTC, kreeperHLC approved these changes

2023-04-17 15:31 UTC, Doster-d approved these changes

2023-04-17 20:17 UTC, merged