add custom item for incarnator
ChaoticOnyx/OnyxBay pull request #10118
Opened 2023-03-28 19:52 UTC by incatnator

Исправлено отсутствие накладных сисек в билде. Теперь точно.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-03-28 19:54 UTC, Zert0X approved these changes

2023-03-28 21:03 UTC, Moscowchief commented
![9b323e96266a2cbf1fa0b07a547418be](https://user-images.githubusercontent.com/63420573/228366384-a8a0baa3-9d1b-47a7-9210-d55db2de210f.svg)

2023-03-28 21:23 UTC, No-Tips commented
как же он ПЫТАЕТСЯ

2023-03-28 21:25 UTC, Zert0X commented
> как же он ПЫТАЕТСЯ

И ты не поверишь он кажись смог

2023-03-28 21:40 UTC, Animesku commented
Исправь отстуствие мозга у себя лучше.

2023-03-28 21:52 UTC, incatnator commented
> Исправь отстуствие мозга у себя лучше.

уже пофикшено, смотри CL

2023-03-28 21:57 UTC, NoneOfYourBsns commented
> уже пофикшено, смотри CL

CLа не обнаружено.

2023-03-28 22:31 UTC, incatnator commented
> > уже пофикшено, смотри CL
> 
> 
> 
> CLа не обнаружено.

Не приоритетно.

2023-04-04 20:33 UTC, Zert0X commented
Немного посоветовавшись, вносим правки:

1. Айтем становится не кастомкой, а тритор шмотом
2. Надо внести айтем в аплинк цена 3 тк

2023-04-04 20:33 UTC, Zert0X requested changes
Поправки геймдизайнеров^

2023-04-04 22:35 UTC, FloweYStyle commented
геймдизы опоздали на 4 дня

2023-04-04 23:46 UTC, Tsurupeta commented
Поправка овнеров, а не дизайнеров. Не надо тут.

2023-04-05 11:42 UTC, Animesku commented
Если в аплинк, то только в нюкерский.

2023-04-05 11:45 UTC, Oubi256 commented
> Немного посоветовавшись, вносим правки:
> 
> 1. Айтем становится не кастомкой, а тритор шмотом
> 2. Надо внести айтем в аплинк цена 3 тк

мне кажется отдельным ПР-ом нужно еще добавить и противоположный этому шмот
![image](https://user-images.githubusercontent.com/98897017/230070845-2c1b284a-34a3-4f7d-8677-e8a8775d66ef.png)

2023-04-06 20:03 UTC, kreeperHLC submitted a review, later dismissed

2023-04-12 22:10 UTC, TobyThorne reviewed
Курсед/10
![16811746975880](https://user-images.githubusercontent.com/45202681/231597264-fb9bbda1-ca02-4f6f-be66-487179c1d3fc.jpg)

2023-05-08 21:12 UTC, Zert0X approved these changes

2023-05-08 21:27 UTC, Doster-d approved these changes
Это, конечно, не возможно, но это игра и всем насрать, порадуем транссексуалов (осуждаем по законам РФ, одобряем по законам твича).

2023-05-08 21:59 UTC, merged