Chainsaw and doomslayer armor
ChaoticOnyx/OnyxBay pull request #10217
Opened 2023-05-08 14:55 UTC by Max1w2ll

- Теперь можно создать бензопилу!

Крафт:

1. Циркулярная пила
2. Подсоедините кабель (3 шт) к циркулярной пиле
3. Подключите конденсатор к циркулярной пиле
4. Сделайте каркас из пластали (5 шт) для циркулярной пилы
5. Сварите каркас сваркой
6. (Дополнительно) Для работы бензопилы подключите топливный баллон (Подойдёт тот, что вы использовали для сварки)

![2](https://user-images.githubusercontent.com/86688350/236853910-5bb0ad7d-353f-495a-9976-e52be244338d.png)

- Бензопилу можно приобрести в аплинке синдиката. Он находится в разделе "**Highly visible and dangerous weapons**"

![5](https://user-images.githubusercontent.com/86688350/236853959-d91bb125-85a6-462b-a3da-6bbb1f65593e.png)

- В заброшенных ящиках можно с маленьким шансом найти боевой скафандр doomslayer-a. 

![6](https://user-images.githubusercontent.com/86688350/236854407-e3350041-48e1-430a-a04e-4a1efdd41ae4.png)

![3](https://user-images.githubusercontent.com/86688350/236854592-d9b577bb-484e-44f1-b718-7fd892b47026.png)
![4](https://user-images.githubusercontent.com/86688350/236854601-255b68bb-a785-451f-83d4-85c61f15f6a5.png)

Дополнительно:

- При срубке деревьев (с помощью бензопилы или топора), теперь выпадают доски)

close #2394 

<details>
<summary>Чейнджлог</summary>

```yml
🆑BWJes
rscadd: Добавлена бензопила и броня думслеера.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-05-08 16:17 UTC, Nod404 commented
close #0000 вместо fix #0000 нужно

2023-05-08 16:21 UTC, Nod404 commented
и в чейнджлоге хуйню написал

2023-05-08 16:25 UTC, Nod404 commented
впрочем, я же могу редачить

2023-05-08 16:27 UTC, Tsurupeta commented
фикс тож подойдёт

2023-05-08 17:13 UTC, Max1w2ll commented
Убрал лишние "as" в методах. Теперь не ругается

2023-05-08 17:58 UTC, Max1w2ll commented
- Убран list в playsound (flora.dm)
- В крафте лишние проверки, заменены на условия с методом use() (surgery_tools.dm)
- Убрано лишнее описание в методах turnOn и turnOff, добавил туда обновление спрайтов (twohanded.dm)

2023-05-08 21:25 UTC, Doster-d requested changes

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +		if(get_fuel() >= 0.05)
Магическое число в соответствие с гайдалайном мы выводим в дефайны

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +			tank.reagents.remove_reagent(/datum/reagent/fuel, 0.05)
См. выше

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +		set_next_think(world.time + 1 SECOND)
Тут для меня окей, все понятно, но у других девелоперов может быть другой счет насчет полумагического значения одной секунды.

Ведь тогда придется умножать на 60 (или какое там число определено в секунде)

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +			to_chat(user, "Remove the current tank first.")
![image](https://user-images.githubusercontent.com/63081538/236936025-e0281f80-e538-438f-87ec-4c31f2b2182e.png)
У нас есть спаны для информирования, это не критично, но лучше выделить цветом сообщение.
В таких случаях в кодовой базе используется SPAN_DANGER или SPAN_NOTICE
P.S. можно использовать и макрос SPAN с указанием нужного класса.

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +			to_chat(user, "<span class='danger'>Stop sawing first!</span>")
У нас так не принято, мы используем макрос SPAN_DANGER или SPAN("danger", x)

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +			hitsound = list('sound/weapons/chainsaw_attack1.ogg', 'sound/weapons/chainsaw_attack2.ogg', 'sound/weapons/chainsaw_attack3.ogg')
Насколько я вижу по кодовой базе, нигде нет обработчика списка hitsound, а он сразу передается.
В билде реализован механизм получения рандомного звука удара через определение константы строкового типа по адресу: code\_global_vars\sfx.dm
Константы звука находится по адресу: code\__defines\sound.dm
Требуется заменить данный hitsound, чтобы была использована эта система.

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/weapons/surgery_tools.dm
> +		if(craft_step == 1)
Опять магическое значение.

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/weapons/surgery_tools.dm
> +		if(craft_step == 2)
Опять магическое значение.

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/items/weapons/surgery_tools.dm
> +		if(craft_step == 3)
Опять магическое значение.

2023-05-08 21:25 UTC, Doster-d commented on code/game/objects/structures/flora.dm
> +		if(do_after(usr, 5))
Опять магическое значение.

2023-05-08 21:50 UTC, Max1w2ll commented on code/game/objects/items/material/twohanded.dm
> +		if(get_fuel() >= 0.05)
> Магическое число в соответствие с гайдалайном мы выводим в дефайны

Я использовал аналогичный код, который есть в tools.dm, в сварке. У него тоже магическое число в методе think

![изображение](https://user-images.githubusercontent.com/86688350/236944257-e9075bf8-0475-4b16-bc61-f97261661d33.png)

Следует ли мне записать для бензопилы отдельную переменную, по типу spend_fuel и присвоить ему 0.05?
Аналогично с set_next_think, что ниже

2023-05-08 21:52 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +		if(get_fuel() >= 0.05)
Название `FUEL_CONSUMPTION` лучше подойдет, как мне кажется.

2023-05-08 21:54 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +		if(get_fuel() >= 0.05)
0.05 не понятно, что это такое и заставляет думать.
Задача человека, что создает код над котором в будущем могут работать другие люди сделать так, чтобы думать над тем, что тут имел в виду автор - не надо.

Ну да, ты нашел пример плохого похода, там тоже не понятно.

В твоем случае надо создать что-то типа CHAINSAW_SPEND_FUEL_AMOUNT, чтобы сразу было понятно, к чему это относится.

2023-05-08 21:57 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +		if(get_fuel() >= 0.05)
> Название `FUEL_CONSUMPTION` лучше подойдет, как мне кажется, а еще лучше сделать это через `#define`.

А так и надо делать через дефайн, иначе же никак не сделать... Если только через переменную, но мы тут давно и не думаю, что БВЖес не знает про дефайн.

2023-05-08 21:57 UTC, Max1w2ll commented on code/game/objects/items/material/twohanded.dm
> +			to_chat(user, "Remove the current tank first.")
Сделал коммит для с использованиеv SPAN_WARNING и SPAN_DANGER для to_chat методов

2023-05-08 21:58 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +			visible_message(SPAN_DANGER("warning", "[usr] starts the chainsaw!"))
Если ты хочешь сделать так, то надо сделать так:
SPAN("danger", x)

2023-05-08 22:13 UTC, Max1w2ll commented on code/game/objects/items/material/twohanded.dm
> +		if(get_fuel() >= 0.05)
> А так и надо делать через дефайн, иначе же никак не сделать... Если только через переменную, но мы тут давно и не думаю, что БВЖес не знает про дефайн.

Я знаком с дефайнами. Просто нашёл пример, который решил использовать. Если нужно сделать так, то сделаю
Коммит с дефайном сделал

2023-05-08 22:21 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +		to_chat(usr, SPAN_WARNING(No fuel in [src]!</span>"))
```suggestion
		to_chat(usr, SPAN_WARNING("No fuel in [src]!"))
```

2023-05-08 22:23 UTC, Max1w2ll commented on code/game/objects/structures/flora.dm
> +		if(do_after(usr, 5))
Нужен пример/совет, как лучше реализовать пошаговый крафт

2023-05-08 22:25 UTC, Doster-d commented on code/game/objects/structures/flora.dm
> +		if(do_after(usr, 5))
Ну тут так же делаешь дефайн на то, что сколько времени занимает кат дерева

2023-05-08 22:26 UTC, Doster-d commented on code/game/objects/items/weapons/surgery_tools.dm
> +		if(craft_step == 1)
А здесь просто так же, как ты выше с топливом сделать, создать дефайны кратко объясняющие, что делается на каждом шаге, например, CHAINSAW_CAPACITOR_INSTALL.

И не забудь в конце файла прописать #undef своих дефайнов, это хорошая практика.

2023-05-08 22:30 UTC, Max1w2ll commented on code/game/objects/structures/flora.dm
> +		if(do_after(usr, 5))
> Ну тут так же делаешь дефайн на то, что сколько времени занимает кат дерева

Не туда ответил. Магические значения для крафта. для craft_step сделать тоже дефаны, по типу:
CRAFT_COIL 0
CRAFT_CAPACITOR 1
CRAFT_PLASTEEL 2
CRAFT_WELDING 3

2023-05-08 22:33 UTC, Doster-d commented on code/game/objects/structures/flora.dm
> +		if(do_after(usr, 5))
Да.

2023-05-09 13:19 UTC, Max1w2ll commented on code/game/objects/items/material/twohanded.dm
> +		set_next_think(world.time + 1 SECOND)
Это достаточно понятно для любого. В билде на каждом шагу подобное объявление.

2023-05-09 20:00 UTC, Doster-d commented on code/game/objects/items/material/twohanded.dm
> +	hitsound = SFX_FIGHTING_SWING
Что это, где оно определено?

2023-05-10 17:20 UTC, Max1w2ll commented on code/game/objects/items/material/twohanded.dm
> +	hitsound = SFX_FIGHTING_SWING
force_divisor и unwielded_force_divisor это переменные, используемые в методе update_force
attack_verb это слова, используемые в логах оружия, при атаке (и которые меняются, если её запустить. Мы меняем слова, связанные на тупой урон на режущий, кромсающий)
hitsound - звуки от оружия. Он так же меняется при запуске пилы

2023-05-11 04:45 UTC, Doster-d submitted a review, later dismissed

2023-05-25 18:26 UTC, NoneOfYourBsns reviewed
Предлагаю следующие моменты поправить.

2023-05-25 18:26 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +	edge = 0
Это булевы переменные, используй дефайны.

2023-05-25 18:26 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +	unbreakable = 1
Аналогично комментарию выше.

2023-05-25 18:26 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +		set_next_think(world.time + 1 SECOND)
Лично я не люблю так называемый "нестинг" условий, предлагаю сделать следующее:
```suggestion
	if(!active)
		return
	if(get_fuel() >= FUEL_CONSUMPTION)
		tank.reagents.remove_reagent(/datum/reagent/fuel, FUEL_CONSUMPTION)
	else
		turnOff()
	set_next_think(world.time + 1 SECOND)
```

2023-05-25 18:26 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +		return
Зачем тут еще один `return`?

2023-05-25 18:26 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +		update_icon()
Бегло изучил как применяется `drop` в других кусках кода, предлагаю сделать как у везде:
```suggestion
		if(user.drop(W, src))
			tank = W
			user.visible_message("[user] slots \a [W] into \the [src].", "You slot \a [W] into \the [src].")
			update_icon()
```

2023-05-25 18:26 UTC, NoneOfYourBsns commented on code/game/objects/items/weapons/surgery_tools.dm
> +				new /obj/item/material/twohanded/chainsaw(src.loc)
```suggestion
				new /obj/item/material/twohanded/chainsaw(loc)
```

2023-06-02 06:30 UTC, Doster-d approved these changes

2023-06-06 21:53 UTC, igorsaux approved these changes
Давайте уже вмержанём быстрее, там у одного человека уже куча идеи на рефакторинг

2023-06-06 22:11 UTC, merged