tweak(spells): Makes disintegrate a hand spell
ChaoticOnyx/OnyxBay pull request #10267
Opened 2023-05-13 19:49 UTC by sephirothseeker

Заменяет выбор цели у заклинания гиба (ei'nath) с окошка на клик рукой по желаемой жертве.
Также перенёс это заклинание и заклинание mind_control, которое тоже работает через клик рукой, из папки targeted в соответствующую папку hand.

<details>
  <summary>Старое и неудобное окошко выбора цели</summary>
  
![spell-disintegrate-old](https://github.com/ChaoticOnyx/OnyxBay/assets/107106680/ba8609eb-7387-4678-9f1a-f152e0e1e4a0)

</details>
<details>
  <summary>Достаточно кликнуть рукой по жертве</summary>
  
![spell-disintegrate](https://github.com/ChaoticOnyx/OnyxBay/assets/107106680/b7c2b34f-b6c5-478d-83dd-1c68500fdfad)

</details>

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Для использования заклинания Ei'Nath магу теперь достаточно кликнуть по своей жертве.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-05-13 20:09 UTC, NoneOfYourBsns commented on code/modules/spells/classes/battlemage.dm
> +		SPELL_DATA(/datum/spell/hand/disintegrate,                 2),
Подровняй пробелами строку, а то выглядит странно.

2023-05-13 20:09 UTC, NoneOfYourBsns commented on code/modules/spells/hand/disintegrate.dm
> +	target.gib()
Где ньюлайн?

2023-05-13 20:09 UTC, NoneOfYourBsns commented on code/modules/spells/hand/disintegrate.dm
> +	return 1
Почему не макрос `TRUE`?

2023-05-13 20:15 UTC, Zert0X commented
Стоп а зачем эй натху вообще какие-то клики, если там грабнут надо

2023-05-13 20:16 UTC, sephirothseeker commented
> Стоп а зачем эй натху вообще какие-то клики, если там грабнут надо

Скрины смотри, там наглядно показано, через какое извращение надо было пройти, и как теперь всё будет просто

2023-05-13 20:20 UTC, Zert0X commented
Таки не, я не про это, прост гиб кликом немного имба.

Гиб грабом и спелом - уже норм.

Не отрицаю, что то что было раньше - рак раковый.

2023-05-13 20:23 UTC, sephirothseeker commented
> Таки не, я не про это, прост гиб кликом немного имба.
> 
> Гиб грабом и спелом - уже норм.
> 
> Не отрицаю, что то что было раньше - рак раковый.

Рейндж старым остался в 1 тайл, тебе при касте даётся в руку кулачок и им нужно ударить по цели.

2023-05-13 20:24 UTC, Zert0X commented
> > Таки не, я не про это, прост гиб кликом немного имба.
> > 
> > Гиб грабом и спелом - уже норм.
> > 
> > Не отрицаю, что то что было раньше - рак раковый.
> 
> Рейндж старым остался в 1 тайл, тебе при касте даётся в руку кулачок и им нужно ударить по цели. 

Рендж и при грабе будет 1, просто при грабе это становиться хоть как-то контрибельно.

А и да спрайта кулака на кукле не вижу

2023-05-13 20:30 UTC, sephirothseeker commented
> > > Таки не, я не про это, прост гиб кликом немного имба.
> > > Гиб грабом и спелом - уже норм.
> > > Не отрицаю, что то что было раньше - рак раковый.
> > 
> > 
> > Рейндж старым остался в 1 тайл, тебе при касте даётся в руку кулачок и им нужно ударить по цели.
> 
> Рендж и при грабе будет 1, просто при грабе это становиться хоть как-то контрибельно.
> 
> А и да спрайта кулака на кукле не вижу

Сейчас стащу с тг

2023-05-13 20:33 UTC, sephirothseeker commented
> > > Таки не, я не про это, прост гиб кликом немного имба.
> > > Гиб грабом и спелом - уже норм.
> > > Не отрицаю, что то что было раньше - рак раковый.
> > 
> > 
> > Рейндж старым остался в 1 тайл, тебе при касте даётся в руку кулачок и им нужно ударить по цели.
> 
> Рендж и при грабе будет 1, просто при грабе это становиться хоть как-то контрибельно.
> 
> А и да спрайта кулака на кукле не вижу

Маг и так дерьмо паршивое, куда его ещё нерфить? И граб кодить надо, в билде нет такого, только через hand

2023-05-13 20:34 UTC, Zert0X commented
> > > > Таки не, я не про это, прост гиб кликом немного имба.
> > > > Гиб грабом и спелом - уже норм.
> > > > Не отрицаю, что то что было раньше - рак раковый.
> > > 
> > > 
> > > Рейндж старым остался в 1 тайл, тебе при касте даётся в руку кулачок и им нужно ударить по цели.
> > 
> > Рендж и при грабе будет 1, просто при грабе это становиться хоть как-то контрибельно.
> > 
> > А и да спрайта кулака на кукле не вижу
> 
> Маг и так дерьмо паршивое, куда его ещё нерфить? И граб кодить надо, в билде нет такого, только через hand

Лол всмысле нет, у тебя буквально граб есть, бери получай и проверяй, 3-5 строк кода

2023-05-13 20:35 UTC, sephirothseeker commented
> > > > > Таки не, я не про это, прост гиб кликом немного имба.
> > > > > Гиб грабом и спелом - уже норм.
> > > > > Не отрицаю, что то что было раньше - рак раковый.
> > > > 
> > > > 
> > > > Рейндж старым остался в 1 тайл, тебе при касте даётся в руку кулачок и им нужно ударить по цели.
> > > 
> > > 
> > > Рендж и при грабе будет 1, просто при грабе это становиться хоть как-то контрибельно.
> > > А и да спрайта кулака на кукле не вижу
> > 
> > 
> > Маг и так дерьмо паршивое, куда его ещё нерфить? И граб кодить надо, в билде нет такого, только через hand
> 
> Лол всмысле нет, у тебя буквально граб есть, бери получай и проверяй, 3-5 строк кода

Тогда сделай это

2023-05-13 21:41 UTC, sephirothseeker commented
Добавил айтем стейты с тг
И для слим версий тоже, но по какой-то причине они не работают

2023-05-13 21:42 UTC, NoneOfYourBsns commented
@sephirothseeker , у тебя еще в двух файлах пробелы съехали, недопустимо!

2023-05-17 17:41 UTC, kreeperHLC submitted a review, later dismissed
Фикси слимов

2023-05-23 06:09 UTC, NefrNerf requested changes
Кроме перечисленных изменений, у тебя еще майндконтроль почему-то хэнд стал

2023-05-23 06:09 UTC, NefrNerf commented on code/modules/spells/hand/disintegrate.dm
> +	show_message = " puts his hand on target head, it's starting to glow brightly."
1) Отступ нужен?
2) his, а что если маг не мужчина а женщина или оно? Смени на что-то обезличенное по типу "Target`s head is starting to glow brightly". Только вот причем тут вообще свечение головы?

2023-05-23 06:09 UTC, NefrNerf commented on code/modules/spells/hand/disintegrate.dm
> -			playsound(user.loc, 'sound/misc/bangindonk.ogg', 50, 1)
А эта опция куда ушла?

2023-05-23 06:09 UTC, NefrNerf commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
Раньше метод в себя принимал список, а теперь один атом. Оставь метод с листом и сделай метод с одной целью, в методе с листом просто вызывай метод с одной целью, вообщем, вынеси общее.

2023-05-23 07:57 UTC, sephirothseeker commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
Зачем???

2023-05-23 08:04 UTC, sephirothseeker commented on code/modules/spells/hand/disintegrate.dm
> +	show_message = " puts his hand on target head, it's starting to glow brightly."
1. Не нужен
2. Show_message не позволяет учитывать такие моменты

2023-05-23 08:04 UTC, sephirothseeker commented on code/modules/spells/hand/disintegrate.dm
> -			playsound(user.loc, 'sound/misc/bangindonk.ogg', 50, 1)
Какая опция?

2023-05-23 08:06 UTC, NefrNerf commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
Потому что было до этого так. А что если дезинтегрейт нам нужен массовый? Если считаешь что в данном случае нужна только одна цель - не проблема, но не убирай метод, добавь новый

2023-05-23 08:16 UTC, sephirothseeker commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
Напиши и предложи к исправлению свой вариант изменений

2023-05-23 08:17 UTC, sephirothseeker commented
> Кроме перечисленных изменений, у тебя еще майндконтроль почему-то хэнд стал

Читай описание пра

2023-05-23 08:27 UTC, NefrNerf commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
Это ты взялся перепиливать дезинтигрейд и зачем-то спилил старый метод. Мое дело отревьювать и запросить правки

2023-05-23 08:30 UTC, sephirothseeker commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
Я не буду этого делать

2023-05-23 08:33 UTC, NefrNerf commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
¯\_(ツ)_/¯, Чр не сниму пока не сделаешь

2023-05-23 08:55 UTC, NefrNerf submitted a review, later dismissed

2023-05-23 12:20 UTC, No-Tips commented on code/modules/spells/hand/disintegrate.dm
> -/datum/spell/targeted/disintegrate/cast(list/targets, mob/user)
> Напиши и предложи к исправлению свой вариант изменений

Так просто же метод с листом, который бы перебирал этот лист и применял твой дизинтегрейт на каждый отдельный атом

2023-06-18 03:02 UTC, kreeperHLC approved these changes

2023-06-19 12:12 UTC, closed without merging