tweak(biohazard_outbreak) Turning off blob spawning
ChaoticOnyx/OnyxBay pull request #10276
Opened 2023-05-18 17:06 UTC by Moscowchief

Выключаем ивент со спавном блоба.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Отключен ивент со спавном Блоба.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-05-18 17:20 UTC, Tsurupeta commented
добавь в темплейт конфига значение

2023-05-18 17:20 UTC, Tsurupeta commented
Ещё у тебя с конфига не подгружается значение и не записывается в переменную, ты просто её ввёл и она никак не взаимодействует с конфигом.

2023-05-18 17:21 UTC, Tsurupeta requested changes
Надо было прошлым сообщением чр вешать

2023-05-18 18:54 UTC, Tsurupeta approved these changes

2023-05-25 14:26 UTC, kreeperHLC commented
Я против. Вместо попытки фикса или перебаланса ты просто хочешь отключить режим. У нас так малфа больше нет, так что это не дело.

2023-05-25 14:50 UTC, closed without merging