feat(lizards): add poison, breeding and behavior
ChaoticOnyx/OnyxBay pull request #10279
Opened 2023-05-19 09:17 UTC by kemperhun

Epic git fail.
close #221 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Теперь ящерицы (lizard) могут размножаться и отвечать на агрессию (чем их больше, тем выше шанс). Также они стали ядовитыми.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-05-19 12:54 UTC, Oubi256 commented
Я уже вижу как в медбее с помощью "добровольца" и ящерицы фармят яд) Или там доза слишком низкая? Код не читал

2023-05-19 14:19 UTC, Tsurupeta commented
ящерица с мутагеном? Ящерица с ядом который стопает сердце?

2023-05-19 14:46 UTC, AnimeshkaTvar commented
В исключения добавить особую ебанистику, либо шансы на определённый яд дописать и всё, база

2023-05-19 15:05 UTC, kemperhun commented
> Яды - разные кислоты и токсины, от политриника и форона до спейсдрагсов и сопорифика (но вот хлорку, нейротокс и зомбипорошок не надо, слишком имбово).

Особая ебанистика и так в исключениях. Накиньте тогда сюда какую-нибудь смешную плашку, чтоб геймдизайнеры пришли и расписали полный список допустимых ядов.

А яд, стопающий сердце, роняет одинокого анробаста с первого раза с шансом ~4-5%(3 юнита яда за укус, 15 юнитов до овердоза, 5-6 ящериц в начале, 30% шанс атаки за наступание на ящерку, 50% что ящерица вступится за брата), если ящерицы не успели размножиться. Если они успели размножиться, значит, игроки на станции проворонили оповещение, но даже в таком случае толстый биокостюм спасает от укусов. В итоге, **как мне кажется**, трупы, по которым ползают рептилии, будут достаточно редкими явлениями, при этом встреча с ящерицами сохранит хоть какую-то опасность, а не будет just another поводом сходить в медбей, спокойно перетыкав всех ящерок ломом. Поэтому этот яд, **как мне кажется**, надо оставить.

2023-05-19 15:07 UTC, Tsurupeta commented
Эту хуйню одобряли 4 года назад, всё равно надо через одобрение еще раз прогнать

2023-05-20 23:34 UTC, Moscowchief commented
На мой взгляд я вижу только одну проблему, что ядовитыми становятся абсолютно ВСЕ ящерки. Сделать бы по-хорошему отдельный вид Venomous lizard, который помимо имени будет отличаться еще и цветом, например желтым. И с некоторой вероятностью, допустим 50% спавнить вместо обычной ящерки Venomous вариант.

2023-05-21 10:06 UTC, AnimeshkaTvar commented
Можно добавить разнообразные цвета дефолтных ящериц, в рамках естественных, и тогда уж добавлять ядовитых, с мелкими вкраплениями/полным окрасом неестественного, кислотного цвета из желтой, зелёной или красной палитры, но чтобы имена у всех ящериц были одинаковыми. Космонавтики не должны знать, какая ящерка ядовитая. Эдакая игра со смертью, где решают твои глаза и внимательность

Даёшь ящерорез

2023-05-21 10:08 UTC, AnimeshkaTvar commented
Ну и у нас только ящерки и крабы не имеют разнообразия, в отличие от мышей и куриц. На крабов хуй можно забить, но вот ящерицы имеют куда больше особенностей кожного камуфляжа

2023-05-21 10:36 UTC, Moscowchief commented
> Можно добавить разнообразные цвета дефолтных ящериц, в рамках естественных, и тогда уж добавлять ядовитых, с мелкими вкраплениями/полным окрасом неестественного, кислотного цвета из желтой, зелёной или красной палитры, но чтобы имена у всех ящериц были одинаковыми. Космонавтики не должны знать, какая ящерка ядовитая. Эдакая игра со смертью, где решают твои глаза и внимательность
> 
> Даёшь ящерорез

Да, это база, и чтобы зависимость окраса от яда каждый раунд рандомилась.

Но понятно, что никто не будет это рисовать, поэтому я уж просто желтый цветофильтр зареквестировал и все.

2023-05-21 13:24 UTC, AnimeshkaTvar commented
Аче там рисовать-то. Ты главное вкодь такую фичу, а пару пикселей окраса добавить - не так и трудно

2023-05-21 13:26 UTC, Moscowchief commented
> Аче там рисовать-то. Ты главное вкодь такую фичу, а пару пикселей окраса добавить - не так и трудно

Вкодить хуйня, а вот кто окрас рисовать будет - уже хуй знает.

2023-05-21 17:48 UTC, AnimeshkaTvar commented
Да там делов хуйня, я чет набросал уже, но мне код нужен на расширенные вариации ящерок

2023-05-22 17:48 UTC, Moscowchief commented
В общем, финальная идея такая: каждый раунд должен генерироваться ассоциативный список ядов и случайных цветов. И при спавне ядовитой ящерки ей должен присваиваться цвет согласно списку.

2023-05-25 13:41 UTC, kemperhun commented
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/32513474/10e13c67-b1c0-4738-96a8-ef0299824fc0)
Теперь у ящериц разные цвета в зависимости от ядов, а содержание ядовитых ящеров в популяции сократилось в среднем на 50%

2023-05-25 14:29 UTC, kreeperHLC approved these changes

2023-05-25 14:31 UTC, kreeperHLC requested changes

2023-05-25 14:31 UTC, kreeperHLC commented on code/__defines/mobs.dm
> +									/datum/reagent/mindbreaker ,\
Ай, я не посмотрел на пробелы до запятой

2023-05-25 14:31 UTC, kreeperHLC commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +			break
Ты тут строку забыл

2023-05-25 14:31 UTC, kreeperHLC commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +			if(prob(25)) say("HSSSSS")
Мы локализацию для животных уже запилили, подстрой под неё

2023-05-25 14:37 UTC, AnimeshkaTvar commented
Привет, я бы вообще сам спрайт ящерицы немного переделал.

как минимум, по причине того, что хвост у неё должен лежать, а не стоять, как это видно с боковых спрайтов, ибо со спины он довольно широкий и лежит

2023-05-25 15:35 UTC, kemperhun commented
> Привет, я бы вообще сам спрайт ящерицы немного переделал.
>
> как минимум, по причине того, что хвост у неё должен лежать, а не стоять, как это видно с боковых спрайтов, ибо со спины он довольно широкий и лежит

Переделай. Я спрайтить не умею, а красивый хвост яды не балансит, так что его в любом случае отдельным пуллреквестом отправлять нужно.

2023-06-02 05:52 UTC, NefrNerf commented on code/__defines/mobs.dm
> +									/datum/reagent/toxin/fertilizer,\
Это конечно забавно, ящерка которое вкалывает говно при укусе

2023-06-02 05:52 UTC, NefrNerf commented on code/datums/events/infestation.dm
> -			max_number = 6
Почему стало 4 хотя было 6?

2023-06-02 05:52 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +	for(var/mob/living/simple_animal/lizard/L in view(vision_range, src))
По хорошему такую проверку на живых мобов определенного типа в пределах зрения вынести в отдельную функцию. Но не знаю насколько это хорошая идея в byond.

2023-06-02 05:52 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +	if(stat == DEAD)
И да, то что говорил про проверку на живых в поле зрения, касается и проверки на смерть. Какая-то поебота, что нужно каждый раз проверять статусы, но тут не сильно знаю код.

2023-06-02 06:19 UTC, kemperhun commented on code/datums/events/infestation.dm
> -			max_number = 6
Они (в большинстве случаев) попарно размножатся, и будет 6.

2023-06-02 06:19 UTC, kemperhun commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +	for(var/mob/living/simple_animal/lizard/L in view(vision_range, src))
А зачем? Проверка довольно специфичная. В большинстве случаев, которые я могу придумать для применения этой проверки, возвращаемый список будет не нужен, можно будет вызывать ту же view() и делать итерировать напрямую.

2023-06-02 06:19 UTC, kemperhun commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +	if(stat == DEAD)
Большинство проков симпл-энималов начинаются такой проверкой. Не знаю, с чем это связано. Возможно, мобконтроллер не обрабатывает мертвых отдельно, возможно, проки жизни выполняются достаточно долго, чтобы до перехода к следующему животное умерло, а совершать тысячу проверок на смерть в Life() некрасиво. Но лучше поставить по аналогии, чем мертвые размножающиеся ящерицы.

2023-06-02 06:26 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +	for(var/mob/living/simple_animal/lizard/L in view(vision_range, src))
Люблю когда можно переиспользовать код и не писать заново, если где-то еще пригодиться будет топово.

2023-06-02 06:27 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +	if(stat == DEAD)
Плохо конечно что с симплами так, ну раз ниче не поделать.

2023-06-02 14:37 UTC, kreeperHLC submitted a review, later dismissed

2023-06-02 15:15 UTC, AnimeshkaTvar commented
Да похую мне на pull request submitted, ты кто такой, чтобы мне на почту присылать письма, сука?

2023-06-02 18:09 UTC, Doster-d requested changes
У нас новые проки.

2023-06-02 18:09 UTC, Doster-d commented on code/modules/mob/living/simple_animal/friendly/lizard.dm
> +			if(L && L.stat != DEAD && L.panic_target == null && L.aggressive_target == null && L.isFertile())
```suggestion
			if(L && !L.is_ooc_dead() && L.panic_target == null && L.aggressive_target == null && L.isFertile())
```

2023-06-02 18:09 UTC, Doster-d requested changes
У нас новые проки.

2023-06-02 23:56 UTC, Doster-d approved these changes

2023-06-18 03:00 UTC, kreeperHLC approved these changes

2023-06-18 03:00 UTC, merged

2023-11-18 06:27 UTC, Primudash commented
Твоих рук дело? #10553