fix(proximity assembly): making it work
ChaoticOnyx/OnyxBay pull request #10287
Opened 2023-05-22 21:26 UTC by sephirothseeker

Исправляет ряд проблем, связанных с сенсором движения, а именно:
- Невозможность выставить обратный отсчёт активации
- Невозможность деактивировать сенсор
- Невозможность выставить радиус действия сенсора
Добавлен звук срабатывания сенсора.

Также убрана лишняя секунда отсчёта у таймера.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Исправлена некорректная работа сенсора движения.
soundadd: Добавлен звук срабатывания сенсора движения.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-05-24 05:50 UTC, NefrNerf reviewed
Вроде ничего плохого в коде не увидел

2023-05-24 09:16 UTC, sephirothseeker commented
> Вроде ничего плохого в коде не увидел

Мог бы и на локалке проверить, как работает код

2023-05-24 18:17 UTC, kreeperHLC approved these changes

2023-06-08 09:03 UTC, Doster-d requested changes

2023-06-08 09:03 UTC, Doster-d commented on code/modules/assembly/timer.dm
> +	set_next_think(world.time)
Иначе не активируется, я думаю.
```suggestion
	set_next_think(world.time+1)
```

2023-06-08 09:03 UTC, Doster-d commented on code/modules/assembly/proximity.dm
> +		set_next_think(world.time + 1 SECOND)
А почему бы не поместить некст синк в начало?
В чем подводные?

2023-06-08 09:03 UTC, Doster-d commented on code/modules/assembly/proximity.dm
> +	set_next_think(world.time)
```suggestion
	set_next_think(world.time+1)
```

2023-06-08 09:10 UTC, sephirothseeker commented on code/modules/assembly/proximity.dm
> +		set_next_think(world.time + 1 SECOND)
Так уже сделано в таймере. И не нужно обрабатывать таймер сенсора, если он выключен. Мы включим обработку, если пользователь включит таймер.

2023-06-08 09:10 UTC, sephirothseeker commented on code/modules/assembly/timer.dm
> +	set_next_think(world.time)
На локалке работало. А в чём проблема?

2023-06-08 09:14 UTC, Doster-d commented on code/modules/assembly/timer.dm
> +	set_next_think(world.time)
А, ну значит достаточно умно сделано, ок.

2023-06-08 09:14 UTC, Doster-d commented on code/modules/assembly/proximity.dm
> +		set_next_think(world.time + 1 SECOND)
Ну ладно, я тебе верю.

2023-06-08 09:14 UTC, Doster-d approved these changes

2023-06-08 17:03 UTC, merged