fix(robot): fix robot icon updates
ChaoticOnyx/OnyxBay pull request #10351
Opened 2023-06-04 14:27 UTC by NoneOfYourBsns

В условиях меняющегося непонятно где и как `stat` обновление иконки каждый тик - единственный быстрый способ исправить ошибку.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: исправлено обновление иконок у роботов.
/🆑
```

</details>

close #10346

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-06-08 09:01 UTC, Doster-d approved these changes

2023-06-11 13:17 UTC, Doster-d requested changes

2023-06-11 13:17 UTC, Doster-d commented on code/modules/mob/living/silicon/robot/life.dm
> +	update_icon()
Хуевая идея, производительность полетит в пизду, оно же каждый тик это будет делать, давай думать

Если думать больно, то таймер в update_icon на вызов update_icon через секунду будет круто

2023-06-11 13:18 UTC, Doster-d commented
Duality of man

2023-06-11 13:19 UTC, NoneOfYourBsns commented on code/modules/mob/living/silicon/robot/life.dm
> +	update_icon()
Я возвращаю как было.

2023-06-11 13:21 UTC, NoneOfYourBsns commented
Переписывать `Life` роботов - весело.

2023-06-11 13:21 UTC, closed without merging