fix(chainsaw) Pickup failure
ChaoticOnyx/OnyxBay pull request #10366
Opened 2023-06-08 14:09 UTC by Moscowchief

Теперь ее можно подобрать.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Исправлена невозможность взять бензопилу в руки.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-06-10 15:45 UTC, NoneOfYourBsns commented on code/game/objects/items/material/twohanded.dm
> +		..()
```suggestion
	return ..()
```

2023-06-12 11:42 UTC, Tsurupeta approved these changes, later dismissed

2023-06-18 02:43 UTC, kreeperHLC submitted a review, later dismissed

2023-06-19 12:55 UTC, Zert0X submitted a review, later dismissed

2023-06-21 15:12 UTC, TobyThorne requested changes

2023-06-21 15:12 UTC, TobyThorne commented on code/game/objects/items/material/twohanded.dm
> +	return ..()
```suggestion
		return
	return ..()
```

2023-06-21 15:45 UTC, TobyThorne approved these changes

2023-06-22 06:27 UTC, Doster-d approved these changes

2023-06-23 09:51 UTC, TobyThorne commented
Ну, перекрыто #10413.

2023-06-23 09:51 UTC, closed without merging