feat(borer): tweak borer husks, add painless ability
ChaoticOnyx/OnyxBay pull request #10372
Opened 2023-06-11 19:31 UTC by incatnator

- Добавлен No (Host) Pain хосту, пока борер сидит внутри, и хаску No (Self) Pain, при оживлении трупа борером. Из-за этого убран трамадол из котла химикатов борера, в угоду перидаксону.
- Оживлённым трупам убран постоянный синтез химикатов, приводивший к постоянному конфузу и туману у куклы, и вырезано переодическое сорение кривой кровью, не несущей за собой смысла.
- Бореру в статус добавлено отображение внутреннего пула химикатов. 
- Теперь бореры после поедания мозга могут использовать абилки, требующие химикаты.
- Теперь у инфицированного не остаётся роль такового после смерти борера.

close #6438 

<details>
<summary>Чейнджлог</summary>

```yml
🆑 incarnator
rscadd: Борерам добавлена возможность отключать восприятие боли телу на 30 секунд.
rscadd: Бореру в статус добавлено отображение внутреннего пула химикатов.
rscdel: Тела, чей мозг поглатил борер, теперь не синтезируют химикаты, не становятся хасками после поглащения и не плюются кровью.
bugfix: Теперь бореры после поедания мозга жертвы могут использовать способности, требующие химикаты.
bugfix: Теперь у жертвы борера не остаётся роль инфицированного после смерти борера.

/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-06-11 20:36 UTC, O0oMaximo0O commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> -	H.ChangeToHusk()
Это не лишнее? А то будет просто человек (по внешности), нет? Да и вытекающая из них кровь за то же отвечала.

2023-06-11 20:37 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	get_organ(BP_BRAIN).chemicals -= 100
```suggestion
	B.chemicals -= 100
```

2023-06-11 21:34 UTC, incatnator commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> -	H.ChangeToHusk()
Нет, раньше оно просто сорило кровью на пол с шансом 5 каждый вызов think'а, потом её беря, крася и переименовывая, при этом сама кровь не отнималась. А так да, внешне будет как хуман после регена. При этом, если на теле уже висел хаск, он не пропадёт.

2023-06-13 08:02 UTC, Doster-d requested changes
Нужно еще одобрение геймдизайна на изменение чемикалсов (пердаксон)

2023-06-13 08:02 UTC, Doster-d commented on code/modules/mob/living/carbon/carbon_powers.dm
> +	if(B && B.can_use_abilities("in_host") && B.chemicals >= 100)
Замени на дефайны, пожалуйста

2023-06-13 08:02 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human.dm
> +				stat("Chemicals: ", get_organ(BP_BRAIN):chemicals)
Блять это военное преступление по гайд ту контрибутинга, ты же его читал?
Явно задай тип мозга и уже оттуда получай свои чемикалс

2023-06-13 08:02 UTC, Doster-d commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	host.no_pain = TRUE
А если у хоста уже был no_pain от чего-то? Мб буфер реализовать?

2023-06-13 19:01 UTC, incatnator commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	host.no_pain = TRUE
не

2023-06-13 19:12 UTC, Doster-d requested changes
Ужк лучше

2023-06-13 19:12 UTC, Doster-d commented on code/__defines/borer.dm
> +#define BORER_STATUS_IN_HOST BORER_STATUS_IN_HOST
```suggestion
#define BORER_STATUS_IN_HOST "BORER_STATUS_IN_HOST"
```

??? Как это скомпилилось нахрен?

2023-06-13 19:12 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human.dm
> +				stat("Chemicals: ", B.chemicals)
```suggestion
				stat("Chemicals: ", B?.chemicals)
```
Если стат нормально нули воспринимает, то можно так сделать или через тернарный оператор прописать, что мозга нет, использовав istype

Если оставить так, то если каким-то чудом борер будет в теле без мозга (вытащили у роботеха), то эта штука не будет рантаймить

2023-06-13 19:12 UTC, Doster-d commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	var/obj/item/organ/external/E = H.get_organ(BP_HEAD)
А проверка на мозг есть тут где-то? Я чет не вижу :(

2023-06-13 19:12 UTC, Doster-d commented on code/modules/organs/internal/borer.dm
> -/obj/item/organ/internal/borer/think()
А думание куда переехало?

2023-06-13 19:12 UTC, Doster-d commented on code/__defines/borer.dm
> +#define BORER_STATUS_IN_HOST BORER_STATUS_IN_HOST
А там круче было)

2023-06-13 19:13 UTC, incatnator commented on code/modules/organs/internal/borer.dm
> -/obj/item/organ/internal/borer/think()
никуда, борерам думать не надо

2023-06-13 19:15 UTC, Doster-d commented
В коммите со смайлами ты правильное на неправильное поменял, зачем?

2023-06-13 19:16 UTC, Doster-d commented on code/modules/organs/internal/borer.dm
> -/obj/item/organ/internal/borer/think()
А куда тогда функционал отсюда распределился?

2023-06-13 19:19 UTC, incatnator commented
> В коммите со смайлами ты правильное на неправильное поменял, зачем?

комилятору не нравилось правильное

2023-06-13 19:19 UTC, incatnator commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	var/obj/item/organ/external/E = H.get_organ(BP_HEAD)
нет но щас будет

2023-06-13 19:21 UTC, Doster-d commented
Чзх, мб, у тебя там была опечатка, попробуй снова, он у себя должен тупо поменять на стринги при компиляции

2023-06-13 19:29 UTC, incatnator commented
> Чзх, мб, у тебя там была опечатка, попробуй снова, он у себя должен тупо поменять на стринги при компиляции

хз почему оно валило чеки, но сейчас вернул и всё прошло. очепяток вроде не было, но да ладно.

2023-07-02 17:05 UTC, Doster-d commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	var/obj/item/organ/external/E = H.get_organ(BP_HEAD)
А если мозг нет, то как мозговой паразит может управлять телом?

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/carbon/human/human.dm
> +			if(mind.special_role == "Borer Husk")
Имя роли странно задано. Есть другой способ?

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/carbon/human/human_powers.dm
> +/mob/living/carbon/human/proc/no_self_pain()
Это что за имя прока? Меняй название

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/mob/living/simple_animal/borer/B = has_brain_worms()
У тебя прок с именем has_brain_worm - возвращает борера, а имя будто проверяет наличие и возвращает булеву переменную

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	var/obj/item/organ/external/E = H.get_organ(BP_HEAD)
Он заменяет мозг, такой вариант тоже подходит

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +/mob/living/simple_animal/borer/verb/no_pain()
Переименую в no_host_pain_enable

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +/mob/living/simple_animal/borer/proc/pain_disable()
no_host_pain_disable

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +		to_chat(src, SPAN("warning", "Your host's pain receptors are already numb		!"))
Куда пробелы табы улетели?

2023-07-02 19:33 UTC, NefrNerf commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	host.no_pain = FALSE
У тебя переменная и метод называется похожими именами, так не должно быть.

2023-07-02 19:38 UTC, incatnator commented on code/modules/mob/living/simple_animal/borer/borer_powers.dm
> +	var/obj/item/organ/external/E = H.get_organ(BP_HEAD)
Йеп, паразит управлять не может, только заменять.

2023-07-02 19:40 UTC, incatnator commented on code/modules/mob/living/carbon/human/human_powers.dm
> +/mob/living/carbon/human/proc/no_self_pain()
А что не устраивает? У нас два прока ноупейн. Один для хоста, пока борер в нём, а второй для хоста, пока борер — он.

2023-07-02 19:40 UTC, incatnator commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/mob/living/simple_animal/borer/B = has_brain_worms()
Не я придумал, но переименую.

2023-07-02 19:49 UTC, NefrNerf commented on code/modules/mob/living/carbon/human/human_powers.dm
> +/mob/living/carbon/human/proc/no_self_pain()
no_self_pain - я сразу подумал что МОБУ БОРЕРА нопейн. Ко всему прочему, можно сделать один  прок ноупейн, а методами обертками вызывать его. Не должно быть так что код повторяет слишком много, если можно обобщать - обобщать

2023-07-04 12:58 UTC, incatnator commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/mob/living/simple_animal/borer/B = has_brain_worms()
Ну, короче, он проверяет наличие и возвращает фолс, если их нет. Но вместо тру при наличии возвращает самого червяка. Потому трогать не буду...

2023-07-04 16:17 UTC, intercepti0n approved these changes
По видеозвонку наблюдал за тестом, должно работать!

2023-07-04 16:26 UTC, Doster-d approved these changes

2023-07-06 02:01 UTC, igorsaux commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	no_pain = FALSE
Жесть, а одной функцией было сделать нельзя?

2023-07-06 02:01 UTC, igorsaux approved these changes

2023-07-06 19:52 UTC, TobyThorne requested changes

2023-07-06 19:52 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_powers.dm
> +/mob/living/carbon/human/proc/no_self_pain()
Нахер оно у хумана? Убери в борера. Только недавно от такого же говна у генок избавились.

2023-07-08 11:53 UTC, TobyThorne approved these changes
Ой, короче, похер. Как всегда, проще самому потом переписать.

2023-07-08 11:54 UTC, merged