feat(organ_printer): Add company selection option for robolimb printer
ChaoticOnyx/OnyxBay pull request #10387
Opened 2023-06-17 12:51 UTC by incatnator

Добавил выбор компании при печати протезов. Вызывается через ПКМ или вкладку Object.

<details>
<summary>Чейнджлог</summary>

```yml
🆑incarnator
rscadd: Теперь можно выбирать компанию протезам у робопринтера.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-06-17 12:53 UTC, Animesku commented
Откуда протезы других компаний в принтере НТ? Нужны тогда разные принтеры.

2023-06-17 12:57 UTC, incatnator commented
> Откуда протезы других компаний в принтере НТ? Нужны тогда разные принтеры.

Для обслуживания ППТ других компаний. Они всё равно работают с/на НТ. Учитывая то, что у нас с протезами НТ никто не ходит — резон х2.

2023-06-17 13:33 UTC, keepm4n commented
> Для обслуживания ППТ других компаний. Они всё равно работают с/на НТ. Учитывая то, что у нас с протезами НТ никто не ходит — резон х2.

За всех не говори, у меня на протезах НТ бегают пара синтетов. Мне нравится их грубый внешний вид.

2023-06-17 19:09 UTC, Terydd commented
> Откуда протезы других компаний в принтере НТ? Нужны тогда разные принтеры.
Протезы других корп в принтере оттуда же, откуда вещи других корп в протолате, например. И в меховской фигне. Нет?

2023-06-17 19:11 UTC, incatnator commented
> > Откуда протезы других компаний в принтере НТ? Нужны тогда разные принтеры.
> 
> Протезы других корп в принтере оттуда же, откуда вещи других корп в протолате, например. И в меховской фигне. Нет?

...И вооружение других корп в оружейке, оборудование меда практически всё — не НТ... Можно продолжать долго.

2023-06-17 19:15 UTC, Terydd commented
Изначальные вещи можно описать покупкой, но когда роботех собирает Одессей, а на нём уже сразу написано, что это мех вей-меда.

2023-06-18 02:33 UTC, kreeperHLC commented
> Изначальные вещи можно описать покупкой, но когда роботех собирает Одессей, а на нём уже сразу написано, что это мех вей-меда - это уровень.

Сказала бы, поменяли бы на то, что все собранные мехи принадлежат вей-медуTM.

2023-06-20 17:57 UTC, Doster-d requested changes, later dismissed

2023-06-20 17:57 UTC, Doster-d commented on code/game/machinery/bioprinter.dm
> +	if(!ishuman(usr))
А почему боргам нельзя, что за ущемление прав?

2023-06-25 15:17 UTC, incatnator commented on code/game/machinery/bioprinter.dm
> +	if(!ishuman(usr))
if(isanimal(usr)) подойдёт?

2023-06-28 13:23 UTC, kreeperHLC approved these changes

2023-07-02 15:51 UTC, Zert0X approved these changes

2023-07-02 15:52 UTC, NoneOfYourBsns approved these changes

2023-07-02 15:59 UTC, merged