Апдейт Сансета и поручней
ChaoticOnyx/OnyxBay pull request #10445
Opened 2023-06-29 23:25 UTC by kreeperHLC

Добавил ещё два типа поручней: Из дерева и темного дерева. Теперь все виды поручней можно создавать.
Обновил Сансет.
close #9892
close #9593
close #9560
close #9146
<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлены деревянные поручни и поручни из тёмного дерева.
rscadd: Поручни теперь можно сделать.
maptweak: Обновлён Сансет.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-06-30 06:22 UTC, TobyThorne commented on code/datums/supplypacks/materials.dm
> +	contains = list(/obj/item/stack/material/wood/fifty)
Выглядит как наебалово

2023-06-30 06:23 UTC, TobyThorne commented on code/game/objects/structures/railing.dm
> +	desc = "A standart railing. Prevents from human stupidity."
```suggestion
	desc = "A standard railing. Prevents human stupidity."
```

2023-06-30 06:25 UTC, TobyThorne commented on code/game/objects/structures/railing.dm
> +	desc = "A steel railing. Prevents from human stupidity."
```suggestion
	desc = "A steel railing. Prevents human stupidity."
```

2023-06-30 06:25 UTC, TobyThorne commented on code/game/objects/structures/railing.dm
> +	desc = "A wood railing. Prevents from human stupidity."
```suggestion
	desc = "A wooden railing. Prevents human stupidity."
```

2023-06-30 06:25 UTC, TobyThorne commented on code/game/objects/structures/railing.dm
> +	desc = "A darkwood railing. Prevents from human stupidity."
```suggestion
	desc = "A darkwood railing. Prevents human stupidity."
```

2023-06-30 06:27 UTC, TobyThorne commented on code/modules/materials/material_sheets.dm
> +	name = "darkwooden plank"
```suggestion
	name = "darkwood plank"
```

2023-06-30 08:52 UTC, kreeperHLC commented on code/datums/supplypacks/materials.dm
> +	contains = list(/obj/item/stack/material/wood/fifty)
```suggestion
	contains = list(/obj/item/stack/material/darkwood/fifty)
```

2023-07-04 16:18 UTC, intercepti0n requested changes

2023-07-04 16:18 UTC, intercepti0n commented on code/datums/supplypacks/materials.dm
> +	containername = "\improper Darkwooden planks crate"
```suggestion
	containername = "\improper Darkwood planks crate"
```

2023-07-04 16:18 UTC, intercepti0n commented on code/datums/supplypacks/materials.dm
> +	name = "50 darkwooden planks"
```suggestion
	name = "50 darkwood planks"
```

2023-07-04 16:27 UTC, Doster-d approved these changes

2023-07-04 16:32 UTC, intercepti0n approved these changes

2023-07-04 16:42 UTC, incatnator approved these changes

2023-07-04 17:52 UTC, igorsaux approved these changes

2023-07-05 18:56 UTC, merged