refact(mmi): make MMI organ, remove brain-MMI-posibrain code duplictation
ChaoticOnyx/OnyxBay pull request #10451
Opened 2023-07-02 14:48 UTC by intercepti0n

Переписал логику работы позитронок, ММИ и мозгов. Теперь все они являются органами и не требуют кривой прослойки между телом космонавта и собой в виде холдера. Общие проки и переменные вынес в объект-родитель. Предположительно исправил 90% багов ММИ.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
imageadd: обновлены спрайты позитронного мозга.
rsadd: обновлены спрайты ММИ, добавлен купол и лампочки для визуальной индикации состояний девайса и мозга внутри.
bugfix: исправлено большинство визуальных ошибок ММИ.
bugfix: ММИ синтетиков и боргов больше не пустые.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-07-02 17:27 UTC, TobyThorne reviewed
мастермайнд из 10

2023-07-05 08:03 UTC, Zert0X commented
Верни кубик Ирод.

2023-07-05 08:35 UTC, TobyThorne commented
чёт хуй знает, зачем вместо позитронки японский веер 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/b520de26-f075-4d4a-897f-2cb8e713ba52)

ещё и огромный, почти фуллтайл, тогда как кубик по размеру более-менее сходится с другими органами

2023-07-05 11:56 UTC, intercepti0n commented
- Removed herobrine.
- Removed chernika.

2023-07-07 19:57 UTC, Doster-d commented on code/modules/ghosttrap/trap.dm
> -	to_chat(target, "<b>As a synthetic intelligence, you answer to all crewmembers, as well as the AI.</b>")
куда угнал...

2023-07-07 19:57 UTC, Doster-d commented on code/modules/mob/living/carbon/brain/robot.dm
> -	name = "robotic intelligence circuit"
куда угнал сцуко

2023-07-07 20:17 UTC, intercepti0n commented on code/modules/mob/living/carbon/brain/robot.dm
> -	name = "robotic intelligence circuit"
У нас есть позитронный мозг, давайте не выдумывать велосипед.

2023-07-07 20:19 UTC, intercepti0n commented on code/modules/ghosttrap/trap.dm
> -	to_chat(target, "<b>As a synthetic intelligence, you answer to all crewmembers, as well as the AI.</b>")
Когда отрефакторю систему позесса, то можно вернуть, мне просто не очень хотелось эти тучаты тянуть в код позитронки, где им не место.

2023-07-07 21:05 UTC, Doster-d commented on code/modules/mob/living/carbon/brain/robot.dm
> -	name = "robotic intelligence circuit"
Я только ради этого одно время играл, а ты это удаляешь, не хорошо, еще нигде про это не написал

2023-07-07 21:06 UTC, Doster-d commented on code/modules/ghosttrap/trap.dm
> -	to_chat(target, "<b>As a synthetic intelligence, you answer to all crewmembers, as well as the AI.</b>")
То есть вырезал фичу и об этом нигде не написал, понял

2023-07-07 21:08 UTC, kreeperHLC requested changes

2023-07-07 21:08 UTC, kreeperHLC commented on code/datums/trading/goods.dm
> +								/obj/item/organ/internal/cerebrum/mmi							= TRADER_ALL,
Табы слетели

2023-07-07 21:08 UTC, kreeperHLC commented on code/datums/trading/goods.dm
> +								/obj/item/organ/internal/cerebrum/posibrain					= TRADER_THIS_TYPE,
И тут тоже

2023-07-07 21:08 UTC, kreeperHLC commented on code/modules/ghosttrap/trap.dm
> +	var/new_name = tgui_input_text(target, "Enter a name, or leave blank for the default name.", "Name Change", target.real_name, MAX_NAME_LEN)
А ТГуи импут санитайзится?

2023-07-07 21:08 UTC, kreeperHLC commented on code/modules/organs/internal/posibrain.dm
> +			brainmob:emp_damage += rand(0, 10)
Макросы для взрывов

2023-07-07 21:12 UTC, intercepti0n commented on code/modules/ghosttrap/trap.dm
> +	var/new_name = tgui_input_text(target, "Enter a name, or leave blank for the default name.", "Name Change", target.real_name, MAX_NAME_LEN)
Не через прок санитайза, но да.

2023-07-07 21:13 UTC, intercepti0n commented on code/modules/organs/internal/posibrain.dm
> +			brainmob:emp_damage += rand(0, 10)
Что?

2023-07-07 21:14 UTC, Doster-d requested changes

2023-07-07 21:14 UTC, Doster-d commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
Вас щас ебнут в живот.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/63081538/a8da6330-ee60-4f7a-a6d9-d2575fe48fa2)

2023-07-07 21:14 UTC, Doster-d commented on code/modules/organs/internal/man_machine_interface.dm
> +	brainmob:container = null
Вот прямо сейчас ебнут

2023-07-07 21:14 UTC, Doster-d commented on code/modules/organs/internal/posibrain.dm
> +			brainmob:emp_damage += rand(20, 30)
Уже близко, сейчас будет ебнуто

2023-07-07 21:14 UTC, Doster-d commented on code/modules/organs/internal/posibrain.dm
> +	brainmob:laws = given_lawset
Вас ебнули в живот

2023-07-07 21:27 UTC, kreeperHLC commented on code/modules/organs/internal/posibrain.dm
> +			brainmob:emp_damage += rand(0, 10)
У нас есть макросы вместо этих цифр, добавь их пожалуйста

2023-07-09 00:39 UTC, intercepti0n commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
В этом месте я чисто физически не могу иначе сделать так как у нас сущесвует brainmob и sil_brainmob, которые друг у друга половину кода и проков копируют. Я отдельным проектом сделаю менеджер законов компонентом и тогда можно будет от этого ужаса избавиться, идет??

2023-07-09 00:42 UTC, intercepti0n commented on code/modules/organs/internal/posibrain.dm
> +			brainmob:emp_damage += rand(0, 10)
Я немного покопался в коде, но макросов не нашел, плюс это не взрыв, а внутренняя переменная для моба в мозгу, благодаря которой тот начинает плохо разговаривать. Ничего поделать не могу!

2023-07-09 19:53 UTC, Doster-d commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
Делать istype на брейнмоб и создать вар?
Аналогично с сил_брейнмоб.

2023-07-09 19:54 UTC, TobyThorne approved these changes, later dismissed
звягин хуйни не сделает, в проде потестим

2023-07-09 19:54 UTC, intercepti0n commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
Ну это как-то странно.

2023-07-09 19:55 UTC, Doster-d commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
Так написано в гайдлайне

2023-07-09 20:24 UTC, intercepti0n commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
Ну я выше писал, что дважды кастить в конкретные типы внутри объекта-родителя из-за беекода, который я не трогал в этом проекте - стыд.

2023-07-09 20:33 UTC, Doster-d commented on code/modules/organs/internal/cerebrum.dm
> +	new_brainmob:container = src
```suggestion
	if(istype(new_brainmob, /mob/living/silicon/sil_brainmob))
		var/mob/living/silicon/sil_brainmob/SB = new_brainmob
		SB.container = src
	else if(istype(new_brainmob, /mob/living/brainmob))
		var/mob/living/brainmob/B = new_brainmob
		B.container = src
```

2023-07-09 20:37 UTC, intercepti0n commented on code/modules/organs/internal/cerebrum.dm
> +	else if(istype(new_brainmob, /mob/living/brainmob))
```suggestion
	else if(istype(new_brainmob, /mob/living/carbon/brain))
```

2023-07-09 20:37 UTC, Doster-d commented on code/modules/organs/internal/cerebrum.dm
> +	else if(istype(new_brainmob, /mob/living/brainmob))
спасибо

2023-07-09 20:39 UTC, Doster-d commented on code/modules/organs/internal/cerebrum.dm
> +		var/mob/living/brainmob/B = new_brainmob
```suggestion
		var/mob/living/carbon/brain/B = new_brainmob
```

2023-07-09 20:41 UTC, Doster-d approved these changes

2023-07-09 20:41 UTC, Doster-d commented
Похуй пляшем

2023-07-09 20:42 UTC, kreeperHLC approved these changes

2023-07-09 20:44 UTC, merged