feat(xenobio): after release improvments
ChaoticOnyx/OnyxBay pull request #10476
Opened 2023-07-04 22:10 UTC by Zert0X

- Опять исправлена путаница с серым и зелёным экстрактом
- Сканер в камерах теперь работает
- Добавлена иконка кнопке сброса позиции камеры
- Пофикшены имена големов они теперь более големные
- 1-й голем теперь всегда адамантовый
- Убраны гост роли из вкладочки работ в сетапе
- радужный метроид теперь снова может быть добыт(нужен 100% шанс мутации)
- добавлены следующие базовые взаимодействия:

1. Кровь - создаёт майнд трансфер поушн, позволяет ценой жизни своей куклы переселиться с знаниями языков в любого симпл моба
2. Плазма - создаёт случайного слайма
3. Метроид желе - создаёт слаймовую гранату которая спавнит кучу экстрактов и случайным образом их активирует(одним из возможных для них реагентов)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Опять исправлена путаница с серым и зелёным экстрактом
bugfix: Сканер в камерах теперь работает
bugfix: Добавлена иконка кнопке сброса позиции камеры
bugfix: Пофикшены имена големов они теперь более големные
balance: 1-й голем теперь всегда адамантовый
bugfix: Убраны гост роли из вкладочки работ в сетапе
tweak: Радужный метроид теперь снова может быть добыт(нужен 100% шанс мутации)
tweak: Добавлены базовые взаимодействия с радужным экстрактом(кровь, плазма, метроид желе)
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-07-04 22:40 UTC, intercepti0n commented on code/modules/mob/living/carbon/xenobiological/items.dm
> +	prompted = 1
Ну хоть бы макросы поправил емае.

2023-07-07 13:48 UTC, kreeperHLC approved these changes

2023-07-07 20:42 UTC, igorsaux commented on code/modules/mob/living/carbon/xenobiological/subtypes.dm
> +	if(src.mutation_chance>=100)
🥲

2023-07-07 20:43 UTC, igorsaux approved these changes

2023-07-07 20:45 UTC, intercepti0n requested changes
Обращения `src.` и отсутствие макросов, ну хоть глобальных переменных старого образца нет. Я бы на вашем месте запросил изменения... 😮‍💨

2023-07-08 11:45 UTC, merged