feat(sfx): add old announcers
ChaoticOnyx/OnyxBay pull request #10495
Opened 2023-07-08 15:30 UTC by igorsaux

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Добавлены старые анонсеры. Можно включить за символический донатный тир грузчика.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-07-08 16:09 UTC, TobyThorne approved these changes, later dismissed
благословляю драфт

2023-07-08 16:25 UTC, Nod404 commented
> Можно включить за символический донатный тир грузчика.

кекв

2023-07-09 19:44 UTC, igorsaux commented
готовченко

2023-07-09 19:51 UTC, Doster-d reviewed
Эээ, давай так

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +	ASSERT(A != null)
```suggestion
	ASSERT(!isnull(A))
```

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +	ASSERT(C != null && istype(C))
```suggestion
	ASSERT(!isnull(C) && istype(C))
```

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +	ASSERT(C != null && istype(C))
```suggestion
	ASSERT(!isnull(C) && istype(C))
```

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +	var/client/C = player
```suggestion
	var/client/C = player
	var/mob/M = player
```

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +	if(ismob(player))
```suggestion
	if(istype(M))
```

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +		C = player:client
```suggestion
		C = M.client
```

2023-07-09 19:51 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +	ASSERT(A != null && istype(A))
```suggestion
	ASSERT(!isnull(A) && istype(A))
```

2023-07-09 19:53 UTC, igorsaux commented
ок

2023-07-09 20:13 UTC, TobyThorne approved these changes, later dismissed
игорь хуйни не сделает

2023-07-09 20:16 UTC, kreeperHLC requested changes

2023-07-09 20:16 UTC, kreeperHLC commented on code/controllers/subsystems/announce.dm
> +		C = player:client
: тут

2023-07-09 20:17 UTC, Doster-d approved these changes, later dismissed

2023-07-09 20:18 UTC, Doster-d commented on code/controllers/subsystems/announce.dm
> +		C = player:client
```suggestion
		var/mob/M = player
		C = M.client
```

2023-07-09 20:19 UTC, TobyThorne commented on code/controllers/subsystems/announce.dm
> +		C = player:client
нет никаких :, тебе показалось

2023-07-09 20:19 UTC, Doster-d approved these changes

2023-07-09 20:19 UTC, TobyThorne approved these changes

2023-07-09 20:19 UTC, kreeperHLC approved these changes

2023-07-09 20:20 UTC, merged

2023-07-09 20:40 UTC, FloweYStyle commented
а давайте играть в опух за тир колдуна