fix(xenomorph): now can't open containers
ChaoticOnyx/OnyxBay pull request #10521
Opened 2023-07-12 21:20 UTC by Zert0X

А зачем это надо было вообще?
Если сами ксеносы не умеют с ними оперировать, а лярвы вообще черви.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Ксеносы разучились открывать контейнеры.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-07-12 21:25 UTC, intercepti0n requested changes
Это костыль, а не решение проблемы. Объясняю: мобы типа корги или лярв открывают контейнер и кликают, после чего их цепь атак приводит к пожиранию предмета. Нормальный фикс - запретить кусать еду, которая находится в контейнерах.
![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/137328283/ff55192c-9d9c-4d38-ad0d-504cd76863ae)

2023-07-12 21:26 UTC, Zert0X commented
> Это костыль, а не решение проблемы. Объясняю: мобы типа корги или лярв открывают контейнер и кликают, после чего их цепь атак приводит к пожиранию предмета. Нормальный фикс - запретить кусать еду, которая находится в контейнерах. ![изображение](https://user-images.githubusercontent.com/137328283/253104508-ff55192c-9d9c-4d38-ad0d-504cd76863ae.png)

справебыдло

2023-07-12 21:26 UTC, intercepti0n commented
Ну и если обрезаешь УИ контейнеров, то делай это всем симплам.

2023-07-12 21:32 UTC, Zert0X commented
> Ну и если обрезаешь УИ контейнеров, то делай это всем симплам.
> 

А вот тут спорно

2023-07-12 21:44 UTC, kreeperHLC approved these changes

2023-07-12 21:47 UTC, TobyThorne approved these changes
ёбнул с ружья по галке

2023-07-18 18:24 UTC, intercepti0n approved these changes
Мне стало все безразлично.

2023-07-18 18:35 UTC, merged