Removes lack of box skins
ChaoticOnyx/OnyxBay pull request #10531
Opened 2023-07-16 23:28 UTC by TobyThorne

Иконки для кучи коробок, юзающих плейсхолдер и всякие мелочи типа направления бликов на лампочках.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-07-17 00:27 UTC, kreeperHLC requested changes

2023-07-17 00:27 UTC, kreeperHLC commented on code/modules/hydroponics/seed_machines.dm
> +	desc = "A box of flora data disks, apparently.
```suggestion
	desc = "A box of flora data disks, apparently."
```

2023-07-17 12:26 UTC, kreeperHLC approved these changes

2023-07-18 12:59 UTC, Zert0X approved these changes

2023-07-18 13:02 UTC, merged