Date and time
ChaoticOnyx/OnyxBay pull request #10562
Opened 2023-08-22 09:41 UTC by IvanDonFon

Педалям добавлена кнопка Set Station Date, которая позволяет менять дату на станции, который отображается в статусе, и вроде бы где то ещё в форме ГОД-МЕСЯЦ-ДЕНЬ

![Screenshot_658](https://github.com/ChaoticOnyx/OnyxBay/assets/60175270/d5630483-dcc9-4c30-a41b-12b631948196)

<details>
<summary>Чейнджлог</summary>

```yml
🆑 Donaldo_TH
admin: Педали теперь могут сменять дату на станции
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-08-22 16:01 UTC, ilido commented
Протестировал, вроде норм.

2023-08-22 20:51 UTC, intercepti0n requested changes

2023-08-22 20:51 UTC, intercepti0n commented on code/modules/admin/verbs/randomverbs.dm
> +	var/admin_input = input(usr, "Enter new station date. \[YEAR]-\[MONTH]-\[DAY] (Year should be from 4 numbers, or like 0906, Month 2, Day too 2)", "Station Date")
ТГУИ ввод сделай.

2023-08-22 20:51 UTC, intercepti0n commented on code/modules/admin/verbs/randomverbs.dm
> +			station_date = admin_input
```suggestion
	if(!length(admin_input))
		return
		
	var/regex/sanitize_regex = regex("\[0-9]{4}-\[0-9]{2}-\[0-9]{2}")
	if(sanitize_regex.Find(admin_input))
		station_date = admin_input
```
Нестинг кода это плохо.

2023-08-23 11:55 UTC, IvanDonFon commented on code/modules/admin/verbs/randomverbs.dm
> +	var/admin_input = input(usr, "Enter new station date. \[YEAR]-\[MONTH]-\[DAY] (Year should be from 4 numbers, or like 0906, Month 2, Day too 2)", "Station Date")
Не

2023-08-25 18:35 UTC, intercepti0n commented on code/modules/admin/verbs/randomverbs.dm
> +	var/admin_input = input(usr, "Enter new station date. \[YEAR]-\[MONTH]-\[DAY] (Year should be from 4 numbers, or like 0906, Month 2, Day too 2)", "Station Date")
Это не вопрос.

2023-08-29 09:24 UTC, IvanDonFon commented on code/modules/admin/verbs/randomverbs.dm
> +	var/admin_input = input(usr, "Enter new station date. \[YEAR]-\[MONTH]-\[DAY] (Year should be from 4 numbers, or like 0906, Month 2, Day too 2)", "Station Date")
Зачем мне ТГУИ ввод для кнопки, которой будут пользоваться только педали

2023-08-29 19:05 UTC, intercepti0n commented on code/modules/admin/verbs/randomverbs.dm
> +	var/admin_input = input(usr, "Enter new station date. \[YEAR]-\[MONTH]-\[DAY] (Year should be from 4 numbers, or like 0906, Month 2, Day too 2)", "Station Date")
Назови хоть одну причину почему ему бы здесь не быть. Новеньким педаляторам будет приятнее видеть новую менюшку, а старики смогут в настройках включить бйондовский ввод и не страдать.

2023-08-29 19:06 UTC, IvanDonFon commented on code/modules/admin/verbs/randomverbs.dm
> +	var/admin_input = input(usr, "Enter new station date. \[YEAR]-\[MONTH]-\[DAY] (Year should be from 4 numbers, or like 0906, Month 2, Day too 2)", "Station Date")
Ненавижу новичков, хочу чтобы они страдали

2023-09-02 11:38 UTC, intercepti0n approved these changes

2023-09-02 12:01 UTC, Doster-d approved these changes

2023-09-02 12:04 UTC, merged