tweak(map_ent) Add random derelict spawners
ChaoticOnyx/OnyxBay pull request #10560
Opened 2023-08-20 10:45 UTC by ilido

Добавил случайно выбираемые дереликты для спавна на астероиде и map_ent для их спавна на карту Рубежа. Для добавления нового достаточно просто закинуть файл карты в derelicts/asteroid/you_map_name/you_map.dmm. 

<details>
<summary>Чейнджлог</summary>

```yml
🆑ilidoi
tweak: В маппинг добавлены спавнеры случайных дереликтов
maptweak: На астероиде Рубежа размещены случайно выбираемые дереликты
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-08-21 11:56 UTC, kreeperHLC commented on code/game/turfs/unsimulated/liquid_plasma.dm
> +	return 1
А это что?

2023-08-21 12:34 UTC, ilido commented on code/game/turfs/unsimulated/liquid_plasma.dm
> +	return 1
Исправил

2023-08-25 18:33 UTC, intercepti0n requested changes
Подробнее посмотрю код ближе к понедельнику, а пока получите придирки.

2023-08-25 18:33 UTC, intercepti0n commented on code/game/turfs/unsimulated/liquid_plasma.dm
> +// 		standard_dispenser_refill
Опять закомментированный код, уберите пожалуйста.

2023-08-25 18:33 UTC, intercepti0n commented on code/game/turfs/unsimulated/liquid_plasma.dm
> +	return 1
```suggestion
	return TRUE
```
Макросы это очень хорошо!

2023-08-25 18:33 UTC, intercepti0n commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +	// 	SSmapping.load_multi_z_derelicts(target_name)
Уберите пожалуйста нерабочий код, спасибо.

2023-08-25 20:43 UTC, ilido commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +	// 	SSmapping.load_multi_z_derelicts(target_name)
Убрано

2023-08-28 11:57 UTC, kreeperHLC submitted a review, later dismissed

2023-08-29 19:00 UTC, intercepti0n requested changes

2023-08-29 19:00 UTC, intercepti0n commented on maps/~mapsystem/maps.dm
> +
Либо доделай, либо убери пожалуйста.

2023-08-29 19:00 UTC, intercepti0n commented on maps/frontier/ent_biodome.dm
> +	// TODO: add check for target_biodome still not being picked, possibly force random
Что?

2023-08-29 19:00 UTC, intercepti0n commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +	if(!valid_map_templates.len)
Вместо `.len` мы используем `length()` так как при неинициализированном списке программа не выдаст рантаймит и прок вернет нолик.

2023-08-29 19:00 UTC, intercepti0n commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +// TODO: Make some multi-z derelicts
?

2023-08-29 19:00 UTC, intercepti0n commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +/obj/map_ent/func_load_map/derelict
Чисто мое ИМХО, но я бы назвал это спавнером руин.

2023-08-29 19:00 UTC, intercepti0n commented on code/controllers/subsystems/mapping.dm
> +	log_to_dd("Asteroid derelicts found: [derelict_folder_list.len]")
Не вижу смысла в логгировании данной информации.

2023-08-29 19:00 UTC, intercepti0n commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +			log_to_dd("[name] placed with invalid force_map path")
Предположу, что использование `CRASH` тут более уместно т.к выведется райнтайм в дебаг панель, а не просто строчка в каком-то конфиге.

2023-08-29 19:00 UTC, intercepti0n commented on code/controllers/subsystems/mapping.dm
> +		if(copytext("[derelict_folder]", -1) != "/") // skip if not a folder
Мне не очень нравится, что ты заставляешь меня создавать папки даже для единичных руин. Я не настаиваю, но обработка карт и внутри корневой папки с руинами была бы классной!

2023-08-29 19:53 UTC, ilido commented on maps/frontier/ent_biodome.dm
> +	// TODO: add check for target_biodome still not being picked, possibly force random
Если в конфиге не будет указан целевой биокупол, или конфиг по какой-то причине не будет загружен, то в центре карты будет дыра. Чтобы это исправить в будущем, оставил TODO

2023-08-29 19:57 UTC, ilido commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +/obj/map_ent/func_load_map/derelict
Оставлю как есть, дереликт переводится как заброшка. Вполне отражает смысл

2023-08-29 19:58 UTC, ilido commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +			log_to_dd("[name] placed with invalid force_map path")
Про это не знал, спасибо. Заменю на CRASH

2023-09-02 13:32 UTC, ilido commented on code/controllers/subsystems/mapping.dm
> +		if(copytext("[derelict_folder]", -1) != "/") // skip if not a folder
Исправил, теперь можно папку не создавать и скидывать так

2023-09-02 13:33 UTC, ilido commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +	if(!valid_map_templates.len)
У valid_map_templates нет length(), если его туда поставить, то это вызовет ошибку и билд не скомпилится

2023-09-02 15:09 UTC, intercepti0n commented on code/game/map_ent/func_load_asteroid_derelict.dm
> +		return
```suggestion
		return
		
```

2023-09-02 15:09 UTC, intercepti0n commented on code/controllers/subsystems/mapping.dm
> +
```suggestion
```

2023-09-02 15:26 UTC, intercepti0n approved these changes

2023-09-08 14:45 UTC, kreeperHLC approved these changes

2023-09-08 16:10 UTC, merged