refact(surgery): make surgery a bit less painful to modify
ChaoticOnyx/OnyxBay pull request #10689
Opened 2023-10-11 08:44 UTC by intercepti0n

Легкий рефактор хирургии, целью которой является повышение модифицируемости шагов и уменьшение копипасты.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-10-14 10:40 UTC, intercepti0n commented
С `surgery_step` закончил, начинаю переносить операции на новую систему.

2023-10-16 06:32 UTC, kreeperHLC commented on code/_helpers/surgery.dm
> +			var/datum/surgery_step/l = GLOB.surgery_steps[i]		//Fucking hate
Бегло смотрю. Комментарий мда.

2023-10-16 06:32 UTC, kreeperHLC commented on code/_helpers/surgery.dm
> +				swapped = 1
А почему не тру

2023-10-16 06:32 UTC, kreeperHLC commented on code/datums/surgery/surgery_step.dm
> +	if(ishuman(user) && prob(60))
В дефайн бы

2023-10-18 10:25 UTC, kreeperHLC requested changes
Веселись

2023-10-18 10:25 UTC, kreeperHLC commented on code/modules/integrated_electronics/subtypes/medical.dm
> +	check if tool is right or close enough and if this step is possible
```suggestion
	//check if tool is right or close enough and if this step is possible
```

2023-10-18 10:25 UTC, kreeperHLC commented on code/modules/integrated_electronics/subtypes/medical.dm
> +	 	return
Че это

2023-10-18 10:25 UTC, kreeperHLC commented on code/datums/surgery/surgery_step.dm
> +			. -= 0
Во это прикол конечно

2023-10-18 12:46 UTC, intercepti0n commented on code/datums/surgery/surgery_step.dm
> +	if(ishuman(user) && prob(60))
Смысл в дефайн сувать шанс, который за код всего в одном месте прокает?

2023-10-18 13:08 UTC, intercepti0n commented on code/modules/integrated_electronics/subtypes/medical.dm
> +	 	return
Это код, который я на скорую руку дважды отрубал, очевидно что его в итоговой версии проекта не будет.

2023-10-18 13:10 UTC, intercepti0n commented on code/datums/surgery/surgery_step.dm
> +			. -= 0
Очевидно, на Бее это сделали для того, чтобы при наличии стола не проверять тайл далее на содержание иных подходящих объектов.

2023-10-25 12:43 UTC, intercepti0n commented
Я сделяль.

2023-10-26 21:46 UTC, intercepti0n commented
Я победил чейнджлог. С десятой попытки...

2023-10-26 22:08 UTC, Doster-d submitted a review, later dismissed
Девелоперы никогда не врут в галках

2023-10-27 10:30 UTC, kreeperHLC requested changes, later dismissed
Куда лучше чем то нечитаемое говно, которое есть сейчас. Вот бы ещё дефайны для хирургических шагов.

2023-10-27 10:30 UTC, kreeperHLC commented on code/datums/surgery/steps/bone.dm
> +	return (..() && target_zone == BP_HEAD)
```suggestion
	return (..() && target_zone != BP_HEAD)
```

2023-10-27 10:30 UTC, kreeperHLC commented on code/datums/surgery/steps/face.dm
> +/datum/surgery_step/generic/cut_face
Почему тип generic тут

2023-10-27 10:30 UTC, kreeperHLC commented on code/datums/surgery/steps/face.dm
> +	duration = CUT_DURATION * 1.25
Урааа, магическое число

2023-10-27 10:30 UTC, kreeperHLC commented on code/datums/surgery/steps/internal.dm
> +		/obj/item/tape_roll = 20
Оно указано, но не проходит проверку ниже

2023-10-27 10:58 UTC, intercepti0n commented on code/datums/surgery/steps/face.dm
> +/datum/surgery_step/generic/cut_face
Предположу, что проверки были идентичны тем, что выполнялись в дженерик шаге.

2023-10-27 11:29 UTC, intercepti0n commented on code/datums/surgery/steps/internal.dm
> +		/obj/item/tape_roll = 20
Ок, я схему работы операций не менял, я просто уберу этот предмет.

2023-10-27 11:30 UTC, intercepti0n commented on code/datums/surgery/steps/face.dm
> +	duration = CUT_DURATION * 1.25
Но вот вынесу в дефайн и лапша из шагов станет в сто раз читабельнее.

2023-10-27 11:36 UTC, kreeperHLC commented
Ну теперь можно пускать в тестмерж

2023-10-29 15:05 UTC, Doster-d approved these changes

2023-10-29 15:07 UTC, TobyThorne commented on code/datums/surgery/_defines.dm
> +#define DETATCH_DURATION        52
какой нахуй DETA**T**CH

2023-10-29 15:07 UTC, intercepti0n commented on code/datums/surgery/_defines.dm
> +#define DETATCH_DURATION        52
Как же он издевается...

2023-10-29 15:19 UTC, Zert0X approved these changes
Мне сказали плеертест прошёл хорошо

2023-10-29 16:25 UTC, merged