Ревёрт радиации до старой системы
ChaoticOnyx/OnyxBay pull request #10743
Opened 2023-10-19 17:49 UTC by TimErmolt

Ревёрт "реалистичной" системы радиации до того, что было раньше. 
Костяк ревёртаемого составляют эти два ПРа:
#9279 
#9301

Ну и также все с ними связанные патчи, фиксы, твики и так далее:
#9402 
#9403
#9404
#9461
#9575
#9945
#10597 
#10654
#10716

closes #10076

Руку на сердце: нигде не нашёл багов, а какие нашёл, те исправил. Но, зная наш билд, что-нибудь да может вылезти, но едва ли что-то, что нельзя относительно легко пофиксить.

<details>
<summary>Чейнджлог</summary>

```yml
🆑TheUnknownOne
rscdel: Откат системы радиации до старого её вида. В двигательной вновь обязательны радкостюмы при работающем движке, а коллекторы собирают всю радиацию, а не только оную от сингулярности.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-10-19 22:07 UTC, intercepti0n commented on code/__defines/flags.dm
> +#define EFFECT_FLAG_RAD_SHIELDED (1 << 0)
Выноси дефайны радейки в отдельный файл и пиши комменты над ними через тройной слеш, дабы IDE могла описывать их предназначение при наведении.

2023-10-19 22:08 UTC, intercepti0n commented on code/__std/conv.dm
> +#define CONV_C2K(temp) (temp + 273.15)
Эти названия ужасны, используй имена Игоря, к примеру, `CONV_KELVIN_CELSIUS` вместо `CONV_K2C`.

2023-10-19 22:09 UTC, intercepti0n commented on code/_onclick/ghost.dm
> +			to_chat(user, SPAN_NOTICE("Radiation level: [rads ? rads : "0"] Bq."))
Куда потерялся `EXAMINE_BLOCK`?

2023-10-19 22:14 UTC, intercepti0n commented on code/game/objects/objs.dm
> -/obj/_examine_text(mob/user, infix, suffix)
Фича с возможностью посмотреть рад резист у предмета была крутой, может ее оставишь?

2023-10-19 22:15 UTC, intercepti0n commented on code/modules/clothing/masks/miscellaneous.dm
> +/obj/item/clothing/mask/pig
Это вообще как сюда попало?

2023-10-19 22:17 UTC, intercepti0n commented on code/modules/mob/living/carbon/human/life.dm
> +						to_chat(src, SPAN_WARNING("Your hair falls out."))
За што?..

2023-10-20 15:15 UTC, Tsurupeta commented
он не знает

2023-10-20 15:43 UTC, TimErmolt commented
Сука, как же заебало

2023-10-20 16:52 UTC, TimErmolt commented on code/__defines/flags.dm
> +#define EFFECT_FLAG_RAD_SHIELDED (1 << 0)
Сделал.

2023-10-20 16:52 UTC, TimErmolt commented on code/__std/conv.dm
> +#define CONV_C2K(temp) (temp + 273.15)
Сделал.

2023-10-20 16:52 UTC, TimErmolt commented on code/_onclick/ghost.dm
> +			to_chat(user, SPAN_NOTICE("Radiation level: [rads ? rads : "0"] Bq."))
Ладно...

2023-10-20 16:53 UTC, TimErmolt commented on code/game/objects/objs.dm
> -/obj/_examine_text(mob/user, infix, suffix)
Сделал. У шмоток с резистом от радиации он будет показываться в процентах.

2023-10-20 16:53 UTC, TimErmolt commented on code/modules/clothing/masks/miscellaneous.dm
> +/obj/item/clothing/mask/pig
Лишняя фигня завалялась, удалил.

2023-10-20 16:53 UTC, TimErmolt commented on code/modules/mob/living/carbon/human/life.dm
> +						to_chat(src, SPAN_WARNING("Your hair falls out."))
Ладно, вернул, не злись только.

2023-10-20 16:54 UTC, TimErmolt commented
Сделал правки по замечаниям Интерсепшена и автоматических проверок.

2023-10-20 16:57 UTC, TimErmolt commented
Блядь. Минуту.

2023-10-20 17:03 UTC, TimErmolt commented
Всё, ништяк.

2023-11-12 12:23 UTC, igorsaux requested changes
1) Никто не просил
2) Старый бейкод
3) ПР говно

2023-11-12 12:24 UTC, FloweYStyle commented
>1. Никто не просил

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/77331370/2a2c5059-cc30-4c30-8c8d-23196c77744c)

2023-11-12 12:24 UTC, TimErmolt commented
О новой радиации:
1. Никто не просил
2. Новый говнокод
3. ПРы говно

2023-11-13 11:38 UTC, igorsaux commented
поржали и хватит

2023-11-13 11:38 UTC, TobyThorne commented
ржака

2023-11-13 16:51 UTC, TimErmolt commented
Э куда.

2023-11-13 16:53 UTC, BaraBarax commented
Нахуя ты его закрыл

2023-11-14 08:55 UTC, igorsaux requested changes
Реверт половины билда ради невнятных изменении не пройдёт

2023-11-14 11:10 UTC, kreeperHLC commented
Самый главный тейк про новую радейку - тотальная недоработка взаимодействий с ней. 
Я согласен, что в таком виде она не нужна, поэтому:
- В течении недели ожидаю выкачи иссуев/Драфта по радейке, иначе - одобрение реверта;
- В течении месяца ожидаю готового Пра с улучшениями, иначе - одобрение реверта.

2023-11-16 14:15 UTC, TimErmolt commented
На выходных зарезолвлю.

2023-11-29 12:52 UTC, Zert0X commented
Бот момент

2023-12-08 23:28 UTC, intercepti0n commented
💀

2023-12-09 13:41 UTC, TimErmolt commented
Всё будет.

2024-01-03 22:29 UTC, intercepti0n commented
У ПРа уже месяц конфликты висят нерешенные, а автор ушел играть на Аврору. Закрываю.

2024-01-03 22:29 UTC, closed without merging

2024-01-04 12:24 UTC, TimErmolt commented
Не, ну закрыл не я, не я виноват буду.
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/60045066/43c7c191-b099-48f2-820e-b0c56770f5fe)

2024-01-04 12:55 UTC, Zert0X commented
Пизда после закрытия умерли кнопки на хабе