feat(xenos):skrell headtails styles
ChaoticOnyx/OnyxBay pull request #10821
Opened 2023-10-30 10:32 UTC by Ershovdi

Добавил скреллам стили хвостов. Короткие хвосты, длинные хвосты, волнистые хвосты, хвосты из хвостов, резинки и так далее. На картинках примерные стили, последняя - показываются все спрайты вообще.
![3ZEePghUn2](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/780bd571-e164-49f6-bd68-e1d42745bcf0)
![dreamseeker_BUDmo91OKi](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/15bd6314-fd1c-4197-9fb1-f15f3fe88005)
![dreamseeker_qNWWwjpbbx](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/b20181f3-95c6-4c8c-b446-8a3a193a4aa3)
![dreamseeker_qPWBmPxapC](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/b34a5f26-9b2a-4b05-9a9d-ab3b7bf1d4b8)
![dreamseeker_RMQxjAoyrF](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/b90974fa-6b83-44e1-be0e-324081c75e32)
![GsWUToc4Zf](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/960c4ec3-be88-42df-9b26-e4ce422a6411)
![ZD4PxHk3iQ](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/258d8c90-cc0b-48d9-94d4-8c977f2e4372)
![dreammaker_ESpUdviMAr](https://github.com/ChaoticOnyx/OnyxBay/assets/63337306/5d8dbcde-4b43-4089-a5ba-f8df28ac3f30)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
imageadd: Скреллы теперь могут завязывать хвосты и у них даже есть разная длина.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-10-30 10:40 UTC, kreeperHLC requested changes
> Long Emo Headtails

Мы никогда не вернёмся в 2507

2023-10-30 10:41 UTC, TobyThorne commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/de18825f-d130-4c91-b866-2f435c0dc0b6)
лягушку повесили на тентаклях шок 18+

2023-10-30 10:42 UTC, Zert0X commented
verylong_s (0)
skrell_both_behind_long (0)
skrell_straight_tuux_long (0)
verylong_s_dmg_l (0)
skrell_hair_f_dmg_l (0) 	
skrell_both_behind_long_dmg_r (0)
skrell_excited_long (0) - вообще вынести бы в эмоуты
skrell_insulted_long (0) - вообще вынести бы в эмоуты
skrell_hair_f (0)
skrell_excited (0)
skrell_hair_f_dmg_r (0)
skrell_both_behind_dmg_r (0)
skrell_both_behind_short (0)
skrell_long_tuux (0)
skrell_both_behind_dmg_l (0)
skrell_reserved_long (0) - хз блять это вообще как?
skrell_insulted (0)
veryshort_s (0)
skrell_straight_tuux (0)
skrell_hair_m (0)
skrell_both_behind (0)
skrell_mullet (0)
verylong_s_dmg_r (0)

2023-10-30 10:42 UTC, Zert0X commented
то что выглядит нормально
вопрос почти ко всем бехаиндам, там такое ощущение что тентакля не сзади, а тупо отрезана с хумана

2023-10-30 10:43 UTC, TobyThorne commented
>резинки
вот для кого var/has_secondary впиливал почему не юзается

2023-10-30 10:45 UTC, Ershovdi commented
> ![image](https://user-images.githubusercontent.com/45202681/279024747-de18825f-d130-4c91-b866-2f435c0dc0b6.png) лягушку повесили на тентаклях шок 18+

Эти "reserved", "excited" и etc. я планирую использовать позже, так что задел на будущее. Сейчас эти стайлы не используются.

2023-10-30 10:47 UTC, Ershovdi commented
> не сзади, а тупо отрезана с хумана
ну... Поэтому и behind, плечи закрывают хвосты, а сзади они болтаются.

2023-10-30 11:01 UTC, Zert0X commented
> > не сзади, а тупо отрезана с хумана
> 
> ну... Поэтому и behind, плечи закрывают хвосты, а сзади они болтаются.

![изображение](https://github.com/ChaoticOnyx/OnyxBay/assets/42303535/00846425-a8bb-4d76-ad65-947f1c066fbb)

2023-10-30 12:17 UTC, Ershovdi commented
> Тут плечо тупо отрезает левую тентаклю сзади 

As intended.

2023-10-30 12:21 UTC, Ershovdi commented
Короче, я ПОНЯТИЯ не имею, как мне нормально осветлить спрайты хвостов без необходимости заново их перегруппировывать или ещё какой-то такой херни. Возможно, стоит просто сделать скреллов как таковых темнее. Они сейчас слишком светлые и как итог цвет в Палитре не совпадает с результатом в самом Спрайте.

2023-10-30 13:43 UTC, Medjic commented
> Короче, я ПОНЯТИЯ не имею, как мне нормально осветлить спрайты хвостов без необходимости заново их перегруппировывать или ещё какой-то такой херни. Возможно, стоит просто сделать скреллов как таковых темнее. Они сейчас слишком светлые и как итог цвет в Палитре не совпадает с результатом в самом Спрайте.

В дрим-пеинте есть возможность заменять цвета инструментом, плюс есть прога для перегруппирования ДМИ. Png to Dmi.

2023-11-01 08:32 UTC, kreeperHLC approved these changes

2023-11-03 16:11 UTC, igorsaux approved these changes

2023-11-03 16:11 UTC, merged