fix(coconut): coconuts - are not dirt!
ChaoticOnyx/OnyxBay pull request #10871
Opened 2023-11-03 17:42 UTC by Primudash

Мылом, шваброй и боргами-уборщиками больше нельзя стирать с лица станции все, что связано с /obj/effect/overlay (кокосы, пальмы и блюспейс)

close #10772

<details>
<summary>Чейнджлог</summary>

```yml
🆑Primudash
bugfix: Кокосы больше не грязь
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute]

2023-11-03 17:43 UTC, Primudash commented
Все сломалось

2023-11-05 14:24 UTC, Primudash commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/73365286/fef92d98-fa85-4924-972e-97c6d9fdbfc2)

2023-11-07 07:36 UTC, kreeperHLC requested changes
Гниль на стенах нельзя будет стирать после этого ПРа, фикси

2023-11-18 22:08 UTC, Primudash commented
> Гниль на стенах нельзя будет стирать после этого ПРа, фикси

А её и так нельзя мыть мылом. Сначала разбирается стена.
Ладно, я понял, что от меня хотят, скоро добавлю в проверку грязь отдельно, место всех оверлеев
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/73365286/abc44516-7bd9-4a0f-bdcf-169241d8f4ff)

2023-11-23 08:46 UTC, kreeperHLC approved these changes

2023-12-01 08:22 UTC, kreeperHLC requested changes

2023-12-01 08:22 UTC, kreeperHLC commented on code/modules/mob/living/silicon/robot/robot.dm
> +						if(istype(A, /obj/effect/rune) || istype(A, /obj/effect/decal/cleanable))
А сюда не добавил

2023-12-02 15:50 UTC, Primudash commented on code/modules/mob/living/silicon/robot/robot.dm
> +						if(istype(A, /obj/effect/rune) || istype(A, /obj/effect/decal/cleanable))
Так это же мытье боргами полов при перемещении или нет? Они не могут на стены залезть все равно

2023-12-05 12:54 UTC, closed without merging