remove(VR): remove unused and unfixed bunch of legacy shitcode
ChaoticOnyx/OnyxBay pull request #10877
Opened 2023-11-03 22:54 UTC by Filatelele

Выпилил свое легаси гавно которое каким-то боком оказалось тут, флешбек из 2018 года. Виар нам совершенно не нужен, он не подходит по концепции и им никто не пользуется. Кроме того, виар сломан к хуям и никто это не будет фиксить. 

Тут вообще нужен чейнджлог?

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscdel: удалил неиспользуемый VR.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-11-03 23:22 UTC, intercepti0n requested changes
Если удаляешь что-то из игры - убирай спрайты, дабы те не висели мертвым грузом.

2023-11-03 23:28 UTC, Filatelele commented
> Если удаляешь что-то из игры - убирай спрайты, дабы те не висели мертвым грузом.

Точно, у этого говна же еще спрайты есть. Спасибо, вырезал

2023-11-03 23:34 UTC, intercepti0n commented
Так, теперь все отлично выглядит, молодец.

2023-11-03 23:42 UTC, Doster-d approved these changes
А мне всегда казалась, что это Эпикусовая идея.

2023-11-03 23:43 UTC, Filatelele commented
> А мне всегда казалась, что это Эпикусовая идея.

Я не думаю что он способен написать такое говно.

https://github.com/GammaStation/Gamma-Station/pull/118

2023-11-05 12:36 UTC, TobyThorne approved these changes

2023-11-05 12:36 UTC, merged