Removes yet some more bugs
ChaoticOnyx/OnyxBay pull request #10983
Opened 2023-11-19 00:16 UTC by TobyThorne

```yml
🆑
bugfix: И ещё куча рандомных фиксов.
/🆑
```

чудесным образом обрезание оверлеев при удалении атмов починило ещё кучу хардделов
не найти слов чтоб выразить моё, блять, удивление

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-11-19 02:38 UTC, igorsaux submitted a review, later dismissed

2023-11-20 11:34 UTC, Doster-d requested changes
Один таб и ты ошибся

2023-11-20 11:34 UTC, Doster-d commented on code/game/objects/structures/gas_stand.dm
> +		visible_message(SPAN("notice", "The mask rapidly retracts just before \the [src] is destroyed!"))
```suggestion
			visible_message(SPAN("notice", "The mask rapidly retracts just before \the [src] is destroyed!"))
```

2023-11-20 11:36 UTC, TobyThorne commented on code/game/objects/structures/gas_stand.dm
> +		visible_message(SPAN("notice", "The mask rapidly retracts just before \the [src] is destroyed!"))
cum meat ед

2023-11-20 11:38 UTC, Doster-d approved these changes

2023-11-20 11:44 UTC, igorsaux approved these changes

2023-11-20 11:45 UTC, merged