add: custom items(sansandertale)
ChaoticOnyx/OnyxBay pull request #11019
Opened 2023-11-22 13:53 UTC by PikadorISGood

Кастомки sansandertale

Верхний текст 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-11-22 13:55 UTC, PikadorISGood commented
Я когда не уметь делать ревёрты коммитов

2023-11-22 13:59 UTC, TobyThorne commented on code/modules/clothing/custom_clothing.dm
> +	desc = "A very old revolver, based on the remington new model army. Uses .44 magnum rounds. There are 7 nothces on this revolver"
>remington new model army

что здесь написано

>nothces

без комментариев

>er"

точки для лохов увожаю

2023-11-22 14:00 UTC, kreeperHLC commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/14943437/f5c8549e-811e-4163-b0d1-f4a96cf70fb2)
Нет.

2023-11-22 14:05 UTC, PikadorISGood commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/55062248/21c74563-5167-4a9a-b7a7-3e89087db2d2)

Мы живём

2023-11-22 14:26 UTC, PikadorISGood commented
Если б вы знали какой я классный ПРщик, вы бы расплакались...

2023-11-22 14:39 UTC, PikadorISGood commented
Ну вроде как всё что было неправильно пофиксил?

2023-11-22 15:26 UTC, Doster-d commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/63081538/f906ced0-ccbb-441c-89df-4c7d48adfe31)

Это что за эризация билда?

2023-11-22 17:33 UTC, PikadorISGood commented
Укуси меня пчела

2023-11-25 17:40 UTC, PikadorISGood commented
Ну таищи ревьюеры, что ещё не так?

2023-11-25 17:43 UTC, Zert0X commented
> Ну таищи ревьюеры, что ещё не так?

Всего два вопроса, а за что кастомки то?

2023-11-25 17:44 UTC, PikadorISGood commented
За тир патрона, сказано же можно любые 2

2023-11-25 17:45 UTC, PikadorISGood commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/55062248/b603a626-c577-4053-9ed0-c1661b1174e4)

2023-11-25 17:46 UTC, Zert0X commented
> ![image](https://private-user-images.githubusercontent.com/55062248/285607375-b603a626-c577-4053-9ed0-c1661b1174e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzQ2MjQsIm5iZiI6MTcwMDkzNDMyNCwicGF0aCI6Ii81NTA2MjI0OC8yODU2MDczNzUtYjYwM2E2MjYtYzU3Ny00MDUzLTllZDAtYzE2NjFiMTE3NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE3NDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjQzNGY5Njg4NjliODgyYjI1NGI4YTQ5NTA4MmY3NjhhOWYxY2U5NmEwZDU5NWQ2ZWYzM2NiNDc0ZmU1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._470ZlshzdspydSPmSVkgcBn4D1_UApIhmyOr4rLwtw)

прост это важно когда их будут в конфиг добавлять

2023-11-25 17:46 UTC, PikadorISGood commented
Ну я всё через модкит сделал, как дозволено.

2023-11-25 18:06 UTC, FloweYStyle commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/77331370/9396eb0d-b42f-40b7-bad9-3a2d9d8cff81)
🥹

2023-11-25 19:45 UTC, Doster-d requested changes
У пушек все еще сломаны их исконный наименования спрайтов

2023-11-25 23:14 UTC, PikadorISGood commented
> У пушек все еще сломаны их исконный наименования спрайтов

Окей, вот тут я в замешательстве. Raw файл показывает мне всё ок, локалка билда говорит-ок. Но мёрдж говорит не ок? Как бы на чьей стороне ошибка если при загрузке файла нет её? Твой предыдущий скрин так вообще показывает как я понимаю, что с твоей стороны названия сломаны если 1 колонна-оригинал 2ая-мой dmi.

2023-12-01 18:53 UTC, closed without merging