Add(map, obj): blood fridge and filled variant
ChaoticOnyx/OnyxBay pull request #11044
Opened 2023-11-25 23:51 UTC by k4m3rn

Добавил холодильник с кровью на замену шкафу, который срёт содержимым на пол. Присутствует версия filled, которая инициализируется при спавне, что накидывает в холодос стандартный набор крови и два пустых пакета. Использовал уже имеющиеся текстуры.

close #9598

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлен холодильник для крови. Также добавлена версия, которая сразу имеет пакеты с кровью внутри.
maptweak: Exodus: шкаф с кровью заменён на холодильник.
maptweak: Frontier: шкаф с кровью заменён на холодильник.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-11-26 12:36 UTC, TobyThorne commented on code/game/machinery/kitchen/smartfridge.dm
> +		/obj/item/reagent_containers/ivbag/blood/OMinus = 1,
```suggestion
	var/list/starts_with = list(
		/obj/item/reagent_containers/ivbag/blood/OPlus = 1,
		/obj/item/reagent_containers/ivbag/blood/OMinus = 1,
```

2023-11-26 12:36 UTC, k4m3rn commented on code/game/machinery/kitchen/smartfridge.dm
> +		/obj/item/reagent_containers/ivbag/blood/OMinus = 1,
А бля, точно, забыл.

2023-11-26 12:37 UTC, TobyThorne requested changes

2023-11-26 12:37 UTC, TobyThorne commented on code/game/machinery/kitchen/smartfridge.dm
> +	return 0
```suggestion
/obj/machinery/smartfridge/secure/blood/accept_check(obj/item/O)
	if(istype(O, /obj/item/reagent_containers/ivbag))
		return TRUE
	return FALSE
```

2023-11-26 12:37 UTC, k4m3rn commented on code/game/machinery/kitchen/smartfridge.dm
> +	return 0
Там остальные холодосы имеют 1 и 0, точно стоит менять?

2023-11-26 12:40 UTC, TobyThorne commented on code/game/machinery/kitchen/smartfridge.dm
> +	return 0
это макросы для 1 и 0 соответственно
когда-нибудь какой-нибудь хороший человек поменяет по всему билду, не будем добавлять ему работы

2023-11-26 12:47 UTC, k4m3rn commented
Линтеры сдохли. @TobyThorne

2023-11-26 13:02 UTC, TobyThorne approved these changes
да и хер бы с линтером

2023-11-28 09:54 UTC, kreeperHLC approved these changes

2023-11-28 12:41 UTC, Filatelele requested changes
А я вот против, да. 

Логика следующая. Из обычного ящика кровь можно достать всегда. Холодильник же при отключении электричества пошлет всех космонавтиков нахер. 
Вариант А - считаем что так и надо, пускай космонавты страдают без света и крови. Вешаем плашку геймдизайн и мержим as is. 
Вариант Б - добавляем холодосу с кровью какой-то механ резервного питания, что-то чтобы достать кровь без света.

2023-11-28 12:51 UTC, Filatelele approved these changes
Ладно, не скрытнопуш баланса, а фича.

2023-11-29 09:05 UTC, TobyThorne commented
Дизайн-хуяйн, иссуй-то одобрен, ещё и с приоритетом.
https://github.com/ChaoticOnyx/OnyxBay/issues/9598

2023-11-29 09:06 UTC, merged