tweak(traitor.dm): новые условия для боргов и немного хуманам
ChaoticOnyx/OnyxBay pull request #11093
Opened 2023-11-28 14:48 UTC by hack-wrench

По многочисленному фидбеку по боргам, твикнуты условия антажничества, в том числе немного и хуманам. Теперь у борга три заданиа (вместо двух), первые два с равной вероятностью распределят убийство и защита конкретного человека (новый обжектив для боргов), но возможно и оба типа сразу; последний займет как обычно выживание, либо с 10% вероятностью блокирование отбытия органикам. У хуманов все как и раньше, контракт + эскейп, но с 1%  вероятностью эскейп будет заменен на хиджак (на шаттле должен улететь только владелец задания).

<details>
<summary>Чейнджлог</summary>

```yml
🆑 HentaiStorm
tweak: обновлены условия выдачи триторства
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-11-28 14:54 UTC, Filatelele requested changes
Чейнджлог бы поменять и описать что именно поменялось...

2023-11-28 14:54 UTC, Filatelele commented on code/game/antagonist/station/traitor.dm
> +		// Генерим боргам два случайных задания: убийство или защита, возможно оба сразу и на одних и тех же людей
Здесь и в других местах комменты на русском. Убрать.

2023-11-28 14:54 UTC, Filatelele commented on .gitignore
> +.timetracker
а в гитигнор зачем накакал?

2023-11-28 15:01 UTC, hack-wrench commented
Готово

2023-11-28 15:02 UTC, Filatelele commented
Коммиты на русском джойпейн

2023-11-28 15:02 UTC, hack-wrench commented
русофобы итиже посатиже

2023-11-28 15:09 UTC, Filatelele requested changes

2023-11-28 15:09 UTC, Filatelele commented on code/game/antagonist/station/traitor.dm
> +		for(var/i=1, i <= 2, i++)
Пробелы бы мм....

2023-11-28 15:11 UTC, Filatelele commented on code/game/antagonist/station/traitor.dm
> +		for(var/i=1, i <= 2, i++)
можно вообще по идее заменить на for(var/i = 1 to 2) например да

2023-11-29 13:32 UTC, Doster-d approved these changes

2023-11-29 13:35 UTC, Filatelele approved these changes
Увлажняемые люди одобрили - я тоже одобрю, ладно.

2023-12-01 07:50 UTC, merged