feat(prefs): add become midround antag pref
ChaoticOnyx/OnyxBay pull request #11106
Opened 2023-11-29 16:37 UTC by No-Tips

Я заебался смотреть на предложения "вы хотите стать борером" в гостах, поэтому исходя из иссуя и предложения в оном Голиафа - впиливаю преф, который позволяет включить/выключить становление мидраунд антагом будучи живым или в гостоте.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлен новый преф, позволяющий указать, желает ли игрок становиться мидраунд антагом.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-11-29 18:53 UTC, TobyThorne requested changes

2023-11-29 18:53 UTC, TobyThorne commented on code/game/antagonist/antagonist.dm
> +		log_debug_verbose("[key_name(player)] set their preference to disable becoming midround antag!")
и зачем мне копипаста этой строчки от половины игроков в дебаг логах

2023-11-30 11:50 UTC, TobyThorne approved these changes
а в принципе поебать почему меня это вообще волнует

2023-11-30 18:33 UTC, Filatelele approved these changes
Ну будет спамить в логи педалям и будет, че бухтеть то.

2023-11-30 19:33 UTC, No-Tips commented
Педалям кстати не будет, в педалям как я понял спамит лишь debug_log, куда пишется вербос я хз, мб лишь в файлик куда-то...

2023-12-01 07:43 UTC, merged