Немного разных фиксов и фич
ChaoticOnyx/OnyxBay pull request #1121
Opened 2020-01-01 23:33 UTC by kreeperHLC

- Фикс спрайта разрушенного меха
- Космос в редакторе теперь не белое пятно
- Мокрый пол дольше остаётся мокрым
- Удар током теперь стал опаснее, если напряжение в сети большое
- Трейторы клоуны теперь могут стрелять из пушек
- Пофиксил лееры флоры и земли
- Код кожурки переместил к ней
close #1118, #1023, #276

2020-01-01 23:41 UTC, kreeperHLC commented
![image](https://user-images.githubusercontent.com/14943437/71647516-45f71e00-2d09-11ea-9897-17936dd3b964.png)
Убью любого, кто это примет до решения совета

2020-01-02 03:03 UTC, PlinHost reviewed
Ну это просто мда, взял и проебал проверку на тип.

2020-01-02 03:03 UTC, PlinHost commented on code/modules/hydroponics/grown_inedible.dm
> +	M.slip("the [src.name]",3)
Оно же на любой объект срабатывает, рантаймов нет если не моб?

2020-01-02 08:41 UTC, TermService requested changes

2020-01-02 08:41 UTC, TermService commented on code/game/mecha/combat/marauder.dm
>  	..()
. = ..()

2020-01-02 08:41 UTC, TermService commented on code/game/mecha/combat/marauder.dm
>  	..()//Let it equip whatever is needed.
. = ..()

2020-01-02 08:41 UTC, TermService commented on code/game/mecha/combat/phazon.dm
>  	..()
ну короче везде так надо как выше, да

2020-01-02 18:51 UTC, mattroks101 commented on code/game/mecha/mecha.dm
>  	..()
. = .. ()

2020-01-03 16:39 UTC, TobyThorne commented
>Трейторы клоуны теперь могут стрелять из пушек

![how](https://user-images.githubusercontent.com/45202681/71735922-eff5b800-2e79-11ea-8a23-a88f41479848.png)

2020-01-08 23:13 UTC, Epicus7 approved these changes

2020-01-08 23:13 UTC, Epicus7 commented
> Убью любого, кто это примет до решения совета

Решение совета было

2020-01-08 23:13 UTC, merged

2020-01-10 10:47 UTC, TermService approved these changes