Added Surstromming
ChaoticOnyx/OnyxBay pull request #11248
Opened 2023-12-19 16:11 UTC by k4m3rn

Добавил Сюрстрёмминг.
![image-2_2023-12-19](https://github.com/ChaoticOnyx/OnyxBay/assets/61733704/c4af20d6-7a28-4e59-be7c-ecae3c8a1d8e)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавил Сюрстрёмминг.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-12-19 16:43 UTC, Filatelele requested changes

2023-12-19 16:43 UTC, Filatelele commented on code/modules/reagents/reagent_containers/food/packaged.dm
> +	get_mobs_and_objs_in_view_fast(get_turf(src),3, mobs, objs, 0)
Пробелы потерялись
```suggestion
	get_mobs_and_objs_in_view_fast(get_turf(src), 3, mobs, objs, 0)
```

2023-12-19 16:43 UTC, Filatelele commented on code/modules/reagents/reagent_containers/food/packaged.dm
> +	return ..()
Тут по идее надо вызывать сначала родителя, а потом уже проверять is_open_container()

2023-12-19 16:55 UTC, k4m3rn commented on code/modules/reagents/reagent_containers/food/packaged.dm
> +	return ..()
Работает да и хуй с ним.

2023-12-19 22:24 UTC, TobyThorne commented
какой-то непонятный русскому человеку юмор, норм квашенная селёдка
блюют на видосах те же люди, для которых сухарики - собачий корм, холодец - jello из соплей и сало - испорченный бекон

короче нужна проверка на 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/dfd6bac4-22ce-4e33-97d8-7186b4a30f25)

2023-12-20 10:50 UTC, k4m3rn commented
> короче нужна проверка на ![image](https://private-user-images.githubusercontent.com/45202681/291728756-dfd6bac4-22ce-4e33-97d8-7186b4a30f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjk2MjIsIm5iZiI6MTcwMzA2OTMyMiwicGF0aCI6Ii80NTIwMjY4MS8yOTE3Mjg3NTYtZGZkNmJhYzQtMjJjZS00ZTMzLTk3ZDgtNzE4NmI0YTMwZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwNDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYWE0YjE4MmVmOWY5OWMwN2MwNzhmNzAxZWQ1MjY5NzgxOTIxOTkyZWRmNTVmNmM1MTQzOTljYTI2YmEyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nB1wc2u9nkNvC_DBJumhnIUbou81nvgipGvX5dcnNQ0)

а база так-то ревёртаю в драфт до замены

2023-12-20 10:55 UTC, k4m3rn commented
хотя надо ещё чуток подумать, подраскинуть мозгами, мб ещё что прикрутить

2023-12-20 21:50 UTC, k4m3rn commented
Посидел, подумал, покакал, ребаланснул вомит, задержка выше, есть время на реакцию. Магнитогорские мужики всё ещё будут блевать, ибо нехуй. Вкинул из полезных свойств капельку трезвящего говна в контентс.

2023-12-20 22:00 UTC, k4m3rn commented on code/modules/reagents/reagent_containers/food/packaged.dm
> +	return ..()
Родителя вызывать больно, оверрайдится всё к хуям, а если убрать НЕ перед _is_open_container()_, то идёт по пизде вся заглушка, становится возможно спамить вомитом с помощью _attack_self_'а. От этого и спасает данная пиздопляска. Писать что-то более крупное для простоты понимания/красоты не могу, ещё слишком зелёный. Лучше потом как-нибудь переработаю и вынесу консервы в новый тип еды.

2023-12-20 22:29 UTC, Filatelele approved these changes

2023-12-20 22:29 UTC, Filatelele commented on code/modules/reagents/reagent_containers/food/packaged.dm
> +	return ..()
Я подумал и пришел к выводу - не хуй. Меняй.

2023-12-22 23:13 UTC, Nod404 commented
🕯️

2023-12-22 23:23 UTC, igorsaux approved these changes

2023-12-23 14:26 UTC, merged