tweak(centcomm): no music
ChaoticOnyx/OnyxBay pull request #11317
Opened 2024-01-01 07:40 UTC by ArmolitskiyCarpoeb

Теперь на центкомме не играет музыка.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
sounddel: Удалена музыка с ЦентКомма
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-01-01 18:47 UTC, intercepti0n requested changes
Не комментируй, а удаляй код.

2024-01-03 02:21 UTC, Filatelele requested changes

2024-01-03 02:21 UTC, Filatelele commented on code/game/area/Space Station 13 areas.dm
> +//	ambient_music_tags = list(MUSIC_TAG_CENTCOMM)
```suggestion
```

2024-01-03 09:17 UTC, Zert0X commented
ПР говна, давайте включать музыку только при раундэнде

2024-01-05 15:42 UTC, Filatelele approved these changes

2024-01-05 15:43 UTC, intercepti0n approved these changes

2024-01-05 15:52 UTC, merged