feat(shutters): becoming a craftable
ChaoticOnyx/OnyxBay pull request #11316
Opened 2023-12-31 22:09 UTC by BaraBarax

Сделал крафт створок.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Створки теперь можно собрать.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-12-31 22:10 UTC, BaraBarax commented
Жду пока мне нарисуют пару спрайтов человечек, код уже можно ревьювать

2023-12-31 23:59 UTC, Filatelele requested changes

2023-12-31 23:59 UTC, Filatelele commented on code/game/machinery/doors/blast_door.dm
> +		return 0
После return, continue, break и.т.д. лучше ставить ньюлайны. Очень помогает читабельности. 

Плюс - мы стараемся заменять 0 и 1 на FALSE и TRUE cоответственно.

2023-12-31 23:59 UTC, Filatelele commented on code/game/machinery/doors/blast_door.dm
> +		return 0
Ньюлайн, return FALSE - как выше.

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +	anchored = 0
Опять же меняем 0 на дефайн
```suggestion
	anchored = FALSE
```

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +	density = 1
А здесь на тру.
```suggestion
	density = TRUE
```

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +	var/state = 0
Стейты лучше вынести в дефайн файла. Так будет понятнее, чем какие-то арбитрарные state == 0 

В начале файла дефайним по типу
`#define STATE_UNASSEMBLED 0 
#define STATE_ASSEMBLED 1`

В конце - желательно каждый дефайн андефайнуть. Делается типа такого
`#undef YOUR_DEFINE_NAME`
Это желательно делать чтобы дефайн оставался только в файле и не был глобальным.

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +/obj/structure/shutters_assembly/Initialize()
Здесь лишнее переопределение /Initialize(), оно ничего не делает.

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +			if(!src) return
Я не уверен насколько у нас с точки зрения кодстайла такое одобряется
Думаю лучше поменять на
```suggestion
			if(!src) 
				return
```

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +			to_chat(user, "<span class='warning'>You need one length of coil to wire the shutters assembly.</span>")
Вместо "<span class='warning'> мы используем макрос SPAN_WARNING или же макрос SPAN("warning", "text)

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +			new /obj/item/stack/cable_coil(src.loc, 1)
Можно не писать src.loc, а просто loc. 
SRC тут лишнее.

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +			if(!src) return
```suggestion
			if(!src) 
				return
```

2023-12-31 23:59 UTC, Filatelele commented on code/game/objects/structures/shutters_assembly.dm
> +			src.state = 0
src лишний

2024-01-01 19:11 UTC, intercepti0n commented on code/game/objects/structures/shutters_assembly.dm
> +			new /obj/machinery/door/blast/shutters(src.loc, code, frequency, usr.dir)
```suggestion
			new /obj/machinery/door/blast/shutters(loc,  signaler?.code,  signaler?.frequency, dir)
```

2024-01-01 19:31 UTC, BaraBarax commented
чичас будут правки

2024-01-03 01:38 UTC, Filatelele approved these changes

2024-01-03 09:27 UTC, Zert0X commented
Эххх без собираемых кнопок, имеет мало смысла.
Т.к. даже если ты восстановишь разрушенные шатерсы/бластдоры, то пользоваться нормально ими никто не сможет.

2024-01-05 15:54 UTC, intercepti0n approved these changes

2024-01-05 15:54 UTC, merged