feat(reagent grinder): adds radial menu to grinder
ChaoticOnyx/OnyxBay pull request #11335
Opened 2024-01-06 22:03 UTC by intercepti0n

Реджект бровзер, гоу бек ту радиал меню. Да, я знаю что браузер появился раньше радиальных меню, но звучит смешнее.

![dreamseeker_bPqSgqk38M](https://github.com/ChaoticOnyx/OnyxBay/assets/137328283/d4f2a715-3a3a-40a5-be55-b690445c8cbf)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлено радиальное меню для гриндера реагентов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-01-06 22:10 UTC, Filatelele requested changes

2024-01-06 22:10 UTC, Filatelele commented on code/modules/reagents/Chemistry-Machinery.dm
> +	if (!length(holdingitems))
У него есть сладкий пробелик 

```suggestion
	if(!length(holdingitems))
```

2024-01-06 22:26 UTC, intercepti0n commented on code/modules/reagents/Chemistry-Machinery.dm
> +	if (!length(holdingitems))
Уээээ

2024-01-07 22:04 UTC, Zert0X commented
Код пахнет пропавшим детачем

2024-01-07 22:05 UTC, intercepti0n commented
Не-а, все есть.

2024-01-07 22:07 UTC, Zert0X submitted a review, later dismissed
Нихера нет, ты эджект и детач объединил.
Разъединяй обратно

2024-01-07 22:07 UTC, intercepti0n commented
Не, не буду.

2024-01-08 06:58 UTC, Zert0X commented
Галя отмена

2024-01-10 16:57 UTC, Doster-d approved these changes

2024-01-11 12:15 UTC, Filatelele approved these changes

2024-01-11 12:18 UTC, merged