refact(megaphone): now works a bit better
ChaoticOnyx/OnyxBay pull request #11357
Opened 2024-01-11 21:10 UTC by intercepti0n

Разработчик поиграл на СБ и увидел проблемы. Мегафон в текущей реализации ужасен, а появление рунчата его еще сильнее поломало. Исправил большинство багов, которые были с ним связаны и немного изменил его механику работы. Мегафон слушает речь держащего и делает ее громче, а не считывает текст из инпут окошка как араньше.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: На транслированные через мегафон сообщенияможно прыгнуть призракам.
bugfix: Транслированные через мегафон ообщения отображаются над головой правильного персонажа, а не наблюдателя.
rscadd: Добавлена возможность включать и выключать мегафон.
/🆑
```

</details>

close #8782
close #8486

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-01-11 22:52 UTC, Filatelele requested changes

2024-01-11 22:52 UTC, Filatelele commented on code/game/objects/items/devices/megaphone.dm
> +	for(var/mob/O in viewers(talker))
У тебя тут сначала собираются viewers(), а потом view() 
Можно попытаться сэкономить и использовать get_mobs_and_objs_in_view_fast() 
Но вот действительно ли это будет быстрее - без понятия, надо тестить и замерять.

2024-01-11 22:52 UTC, Filatelele commented on code/game/objects/items/devices/megaphone.dm
> +	insults_left = rand(1, 3)
Тут должен быть return TRUE. Да. Все настолько плохо.

```/obj/item/card/emag/resolve_attackby(atom/A, mob/user)
	var/used_uses = A.emag_act(uses, user, src)
	if(used_uses == NO_EMAG_ACT)
		return ..(A, user)

	uses -= used_uses```

2024-01-12 13:51 UTC, Filatelele submitted a review, later dismissed

2024-01-12 14:25 UTC, Filatelele approved these changes

2024-01-15 14:36 UTC, Zert0X approved these changes

2024-01-15 14:42 UTC, merged