feat(blast doors): crafting
ChaoticOnyx/OnyxBay pull request #11379
Opened 2024-01-16 18:05 UTC by BaraBarax

Бласт дуры теперь тоже собирать можно

```yml
🆑BaraBara
feat: Blast doors теперь можно собирать.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-01-17 16:35 UTC, BaraBarax commented
Ыыыы, можно ревувать

2024-01-17 20:52 UTC, intercepti0n commented
Опиши пожалуйста нормально проект, код завтра посмотрю.

2024-01-19 07:57 UTC, kreeperHLC requested changes, later dismissed

2024-01-19 07:57 UTC, kreeperHLC commented on code/game/machinery/doors/blast_door.dm
>  				src.repair()
```suggestion
				repair()
```

2024-01-20 19:33 UTC, intercepti0n commented on code/game/objects/structures/secure_door_assembly.dm
> +/obj/structure/secure_door/wrench_floor_bolts(mob/user, delay = 40)
Это что такое вообще? Открой файл по пути `code/game/objects/structures/barricade/security.dm` и посмотри как там сделано. Почему у тебя этот прок вызывается из этого файла, когда это хендлится на уровне атакбая атома?

2024-01-22 00:09 UTC, intercepti0n commented on code/game/machinery/doors/blast_door.dm
> +	var/obj/structure/secure_door/A =  new assembly_path(get_turf(src))
Опять личное мнение, но я советую его придерживаться. Ты создавай объект, проводи все действия над ним (проставь определенные свойства, вызови проки) и лишь потом переходи к следующему действию. Кстати, если гнаться за максимальной производительностью, то советую создать переменную `var/turf/T = get_turf(src)` и ее передавать в нью. Сейчас ты дважды прок вызываешь, что не очень хорошо.

2024-01-23 14:56 UTC, intercepti0n submitted a review, later dismissed
Терпимо.

2024-01-23 14:57 UTC, Filatelele requested changes

2024-01-23 14:57 UTC, Filatelele commented on code/game/machinery/doors/blast_door.dm
> +	A.state = 2
Сюда очень просится дефайн.

2024-01-23 15:00 UTC, intercepti0n commented on code/game/machinery/doors/blast_door.dm
> +	A.state = 2
Не просится, в личке отписался почему.

2024-01-23 15:00 UTC, Filatelele commented on code/game/machinery/doors/blast_door.dm
> +	A.state = 2
Просится, в личке отписал почему.

2024-01-23 15:03 UTC, intercepti0n commented on code/game/machinery/doors/blast_door.dm
> +	A.state = 2
Если для тебя создание глобального дефайна ради одной строчки в контролируемом дизмантле норм практика - я умываю руки. Тут уже мало что поможет.

2024-01-23 15:25 UTC, BaraBarax commented on code/game/machinery/doors/blast_door.dm
> +	A.state = 2
гена на

2024-01-23 15:34 UTC, BaraBarax commented on code/game/objects/structures/secure_door_assembly.dm
> +/obj/structure/secure_door_assembly/update_icon()
```suggestion
/obj/structure/secure_door_assembly/on_update_icon()
```

2024-01-23 15:38 UTC, intercepti0n approved these changes

2024-01-23 19:56 UTC, Filatelele approved these changes

2024-01-23 19:56 UTC, merged