tweak(mecha): crab walking (strafe mod)
ChaoticOnyx/OnyxBay pull request #11439
Opened 2024-01-27 14:40 UTC by BaraBarax

Сделал возможность мехам ходить боком и задом, а так же в меха сесть перетаскиванием куклы

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
tweak: Мехи теперь могут ходить боком и задом
tweak: Теперь в меха можно сесть перетаскиванием куклы
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-01-27 14:50 UTC, Filatelele requested changes

2024-01-27 14:50 UTC, Filatelele commented on code/game/mecha/mecha.dm
> +	if(usr != src.occupant)
Лишний src

2024-01-27 14:50 UTC, Filatelele commented on code/game/mecha/mecha.dm
> +	src.occupant_message("Strafing mod [strafe? "on":"off"].")
Лишний src

2024-01-27 14:50 UTC, Filatelele commented on code/game/mecha/mecha.dm
> +	if(user.stat || !ishuman(user))
Вместо user.stat мы используем is_ic_dead()

2024-01-27 14:50 UTC, Filatelele commented on code/game/mecha/mecha.dm
> +	else if(src.dir!=direction && !strafe)
```suggestion
	else if(src.dir != direction && !strafe)
```

2024-01-27 14:50 UTC, Filatelele commented on code/game/mecha/mecha.dm
>  		return 0
раз уж взялся ньюлайны добавлять - го 0/1 заменим на FALSE/TRUE соответственно

2024-01-29 06:38 UTC, kreeperHLC approved these changes, later dismissed
Ну вродь норм

2024-01-29 11:57 UTC, Filatelele requested changes

2024-01-29 11:57 UTC, Filatelele commented on code/game/mecha/mecha.dm
> +	else if(src.dir != direction && !strafe)
Точно src.dir нужен?

```suggestion
	else if(dir != direction && !strafe)
```

2024-01-29 11:59 UTC, Filatelele approved these changes

2024-01-29 12:01 UTC, igorsaux approved these changes

2024-01-29 12:03 UTC, merged