ТВики
ChaoticOnyx/OnyxBay pull request #11482
Opened 2024-01-31 15:00 UTC by kreeperHLC

ЭТО ШАБЛОН PULL REQUEST. Внимательно прочитайте его и напишите описание Pull Request в соответствии с ним. Каждое отклонение от шаблона увеличивает время приема Pull Request-а вплоть до бесконечности!
Подробнее про то, как создавать Pull Request-ы смотрите в нашем [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

ТЕКСТ ВЫШЕ НУЖНО УДАЛИТЬ.

ЗДЕСЬ должно быть **подробное описание** того, что происходит в Pull Request и зачем это нужно. Pull Request не должен содержать изменений, о которых здесь ничего не сказано. ЭТОТ ПУНКТ НАДО ЗАМЕНИТЬ ОПИСАНИЕМ, А ЕГО УДАЛИТЬ.

ЗДЕСЬ нужно **привязать иссуи**, которые относятся к Pull Request-у в формате `close #1234`, `fix #1234` или что-то типа `Затрагивает #1234, но не фиксит его`, если вы просто хотите упоминуть иссуи, но не закрывать его вместе с ПРом. ЭТОТ ПУНКТ НАДО ЗАМЕНИТЬ ЛИНКАМИ НА ИССУИ, А ЕГО УДАЛИТЬ.

ЗДЕСЬ нужно **расписать изменения** которые попадут в **чейнджлог**, формат - `prefix: description`, пример:

<details>
<summary>Чейнджлог</summary>

```yml
🆑
prefix: A summary of changes made.
/🆑
```

</details>

После символа 🆑 на той же строке можно написать никнейм, который будет отображён в чейнджлогах вместо никнейма автора ПРа.

Вместо `prefix` подставляете одну из доступных строк:

- bugfix
- balance
- tweak
- soundadd
- sounddel
- rscadd
- rscdel
- imageadd
- imagedel
- maptweak
- spellcheck
- experiment
- admin

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим x внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над ПРом. ЭТУ СТРОЧКУ НУЖНО УДАЛИТЬ.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-01-31 15:07 UTC, intercepti0n commented on code/modules/multiz/_stubs.dm
> +//HasAbove(z)
Что?

2024-01-31 16:18 UTC, kreeperHLC commented on code/modules/multiz/_stubs.dm
> +//HasAbove(z)
Эта вещь не должна была использоваться в принципе, это пример проков которые не закомментили

2024-01-31 17:28 UTC, BaraBarax commented on code/modules/multiz/structures.dm
> +			return
Ньюлайнчик бы

2024-01-31 22:41 UTC, kreeperHLC commented on code/modules/multiz/structures.dm
> +		A.forceMove(target)
```suggestion
			return

		A.forceMove(target)
```

2024-01-31 22:50 UTC, kreeperHLC commented on code/modules/multiz/movement.dm
> +	handle_fall_effect(landing)
```suggestion
	handle_fall_effect(landing)
```
Злой фембой требует выпилить.

2024-02-01 11:12 UTC, Filatelele approved these changes

2024-02-01 11:50 UTC, Filatelele requested changes

2024-02-01 11:50 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +			to_chat(A, SPAN("warning", "The stairs cut off."))
Я не уверен что это стоит выводить в чат. 
Во-первых, будет засирать чат. 
Во-вторых, есть неироничный шанс это не увидеть ибо первый пункт.

Может, попробуем через сплэш выводить?

2024-02-01 11:50 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +			playsound(source, 'sound/effects/stairs_step.ogg', 50)
Я думаю стоит это закатать в дейфайны SFX'ов и проигрывать SFX_STAIRS_STEP  какой-нибудь

2024-02-01 11:50 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +		to_chat(A, SPAN("notice", "There is nothing of interest in this direction."))
Аналогично с остальными тучатами. Сплэшиков хочется.

2024-02-01 11:50 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +		A.forceMove(target)
Меня все еще корежит с того, что для спуска вниз тебе нужно перейти на второй тайл лестницы. А для подъема наверх нужно пройти два тайла и потыкаться в стенку перед тобой. 
Я на локалке не сразу понял что так и должно быть, что уж говорить о среднестатистических игроках которые это воспримут за баг (И скорее будут правы, чем нет - на мой взгляд логика подъема вверх и вниз должна быть одинаковой.)

2024-02-01 11:52 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +		A.forceMove(target)
Вот видео с пояснением. Чтобы подняться вверх мне надо упереться в турф после конца лестницы и сделать в него шаг. Это ну очень неинтуитивно. 

Это как запилить дверь, ну обычную такую дверь - как у каждого в квартире - и впилить ей разный механ открытия/закрытия. Выглядит неинтуитивно и странно.

https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/316211e3-d883-45bb-938c-805b95676811

2024-02-01 17:12 UTC, Doster-d approved these changes, later dismissed

2024-02-02 09:57 UTC, Filatelele requested changes

2024-02-02 09:57 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +			show_splash_text(A, "The stairs cut off.")
```suggestion
			show_splash_text(A, "the stairs cut off")
```

2024-02-02 09:57 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +		show_splash_text(A, "There is nothing of interest in this direction.")
```suggestion
		show_splash_text(A, "nothing of interest in this direction")
```

2024-02-02 09:57 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +			show_splash_text(A, "The stairs cut off.")
```suggestion
			show_splash_text(A, "the stairs cut off")
```

2024-02-02 09:57 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +		show_splash_text(A, "There is nothing of interest in this direction.")
```suggestion
		show_splash_text(A, "nothing of interest in this direction")
```

2024-02-02 09:57 UTC, Filatelele commented on code/modules/multiz/structures.dm
> +			show_splash_text(A, "Something blocks the path.")
```suggestion
			show_splash_text(A, "something blocks the path")
```

2024-02-02 10:03 UTC, Filatelele approved these changes

2024-02-02 10:23 UTC, igorsaux approved these changes

2024-02-02 10:24 UTC, merged