Сглаживание стен на ЦК
ChaoticOnyx/OnyxBay pull request #11505
Opened 2024-02-02 14:52 UTC by kreeperHLC

Чутка потырил с Фронтира оборудование телепортной, сгладил везде стены.
Некоторые стены перетащил в новую папку стен.
<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
maptweak: На Фронтире и Исходе на ЦК сглажены стены.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-02 14:57 UTC, intercepti0n requested changes, later dismissed
Какие-то странные названия стейтов у иконок и максимально костыльное решение с проставлением иконок стенам в карте, я не беду это одобрять.

2024-02-02 14:59 UTC, kreeperHLC commented
> Какие-то странные названия стейтов у иконок

Стейты иконок обозначают формы. Также, как и было с стенами шаттлов.

> костыльное решение с проставлением иконок стенам в карте
Зато никакой дополнительной инициализации

> я не беду это одобрять
Не одобряй, ЧР снимаю по причине инвалид

2024-02-02 15:23 UTC, igorsaux submitted a review, later dismissed
гильдия камнетёсов одобряет

2024-02-02 20:14 UTC, TobyThorne approved these changes, later dismissed
вкусный конфликт

2024-02-03 16:12 UTC, Doster-d approved these changes, later dismissed

2024-02-03 16:16 UTC, intercepti0n approved these changes

2024-02-03 16:18 UTC, Filatelele approved these changes

2024-02-03 16:19 UTC, merged