feat(plasticflaps): adding craft of plastic flaps
ChaoticOnyx/OnyxBay pull request #11562
Opened 2024-02-08 11:19 UTC by BaraBarax

Крафт и разборка пластиковых... Закрылок? Не ебу как это называется

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
rscadd: Plastic flaps теперь можно собрать и разобрать.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-08 11:37 UTC, kreeperHLC commented
Есть проблемка - их невозможно разрушить. Без этой фичи твою к сожалению принимать нельзя.

2024-02-08 18:42 UTC, intercepti0n commented
> Есть проблемка - их невозможно разрушить. Без этой фичи твою к сожалению принимать нельзя.

Голиаф, ты впилишь? Ты не впилишь, а так станция станет на один шаг ближе к полной деконструкции.

2024-02-08 19:27 UTC, intercepti0n requested changes

2024-02-08 19:27 UTC, intercepti0n commented on code/game/objects/structures/plasticflaps.dm
> +/obj/structure/plasticflaps/proc/take_damage(force)
Уберите этот насер пожалуйста, спасибо.

2024-02-09 15:12 UTC, intercepti0n commented on code/game/objects/structures/plasticflaps.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-02-09 15:30 UTC, BaraBarax commented on code/game/objects/structures/plasticflaps.dm
> +	if(isWrench(O))
```suggestion
	if(isWrench(O))
	playsound(loc, 'sound/items/Ratchet.ogg', 100, 1)
```

2024-02-09 15:32 UTC, BaraBarax commented on code/game/objects/structures/plasticflaps.dm
> +		if(do_after(user, 30, src))
```suggestion
		playsound(loc, 'sound/items/Ratchet.ogg', 100, 1)
		if(do_after(user, 30, src))
```

2024-02-09 15:35 UTC, BaraBarax commented on code/game/objects/structures/plasticflaps.dm
> +		playsound(loc, 'sound/items/Ratchet.ogg', 100, 1)
```suggestion
		playsound(loc, 'sound/items/Ratchet.ogg', 100, 1)
		show_splash_text(user, "deconstructing...")
```

2024-02-09 15:37 UTC, intercepti0n approved these changes
Нормас.

2024-02-14 16:52 UTC, Filatelele approved these changes

2024-02-14 16:52 UTC, merged