add(suit): deimosen's custom item
ChaoticOnyx/OnyxBay pull request #11588
Opened 2024-02-11 17:44 UTC by Animesku

Добавляет fieldcoat_unprotected и удаляет сообщения по типу 'You aren't sure you'll fit in this fascist cloth...' из билда.

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/48406301/d26c7a4a-dbd6-4c3b-bf26-0bcdbe92c351)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-11 17:57 UTC, BaraBarax commented
А чего ченджлох на английском... Да и нужен ли он?

2024-02-11 18:45 UTC, Animesku commented
ок, убрал чейнджлог

2024-02-11 20:14 UTC, Filatelele commented on code/modules/clothing/custom_clothing.dm
> -/obj/item/clothing/suit/armor/hos/jensen/fieldcoat/mob_can_equip(mob/user)
Вообще по хорошему надо разные изменения разными ПРами ебашить, это кнеш не дело кастомку и твики одной пачкой завозить. Атомизация все дела, но уже похуй. 

Ты тестил? Спрайты нормально на тонких сидят?

2024-02-11 20:17 UTC, Animesku commented on code/modules/clothing/custom_clothing.dm
> -/obj/item/clothing/suit/armor/hos/jensen/fieldcoat/mob_can_equip(mob/user)
Как и раньше сидели - не особо. (Там рестрикт на женщин, а не на тонкие бодибилды)

2024-02-11 20:21 UTC, intercepti0n commented on code/modules/clothing/custom_clothing.dm
> -/obj/item/clothing/suit/armor/hos/jensen/fieldcoat/mob_can_equip(mob/user)
Почему вообще ты в ПРе на впил кастомки трогаешь другие предметы?

2024-02-11 20:31 UTC, Animesku commented on code/modules/clothing/custom_clothing.dm
> -/obj/item/clothing/suit/armor/hos/jensen/fieldcoat/mob_can_equip(mob/user)
> Почему вообще ты в ПРе на впил кастомки трогаешь другие предметы?
Предмет деймоса точно такой же, что и далека

2024-02-11 20:33 UTC, Animesku commented on code/modules/clothing/custom_clothing.dm
> -/obj/item/clothing/suit/armor/hos/jensen/fieldcoat/mob_can_equip(mob/user)
Нелогично, что один и тот же предмет надевается, а другой нет.

2024-02-11 20:33 UTC, intercepti0n requested changes
Прошу автора не трогать другие предметы и сделать кастомку Деймосяна не через наследование от кастомки Далека или кого-либо еще. Это финальное решение.

2024-02-12 17:07 UTC, TobyThorne commented
https://github.com/ChaoticOnyx/OnyxBay/pull/11590

2024-02-12 17:07 UTC, closed without merging