feat(exodus): conference room, fixed bugs, better mapping
ChaoticOnyx/OnyxBay pull request #11622
Opened 2024-02-16 20:14 UTC by FloweYStyle

* Исправлен баг с мулботом, который не мог перевозить груз по отметке Bridge
* Исправлен баг с невозможностью затемненить окна у ХоПа
* Исправлен баг с мусорными трубами, что вели в никуда
* Исправлен баг с шлюзом ко входу в карго, который не пропускал грузчиков
* Трубы и провода проложены на порядок лучше и меньше напоминают спагетти
* Комнате конференций был возвращён деревянный ламповый интерьер
* Стёкла по центру мостика теперь соединены с передним большим окном, так выглядит лучше

* Стеклянная дверь, ведущая к комнате конференций теперь имеет доступ Квартирмейстера
Изменение обусловлено слишком простой возможностью подслушивать важные разговоры глав. Я считаю нужным добавить доступ, чтобы мимолётным ассистентам пришлось применять хоть какое-то усилие для подслушивания. Доступ Квартирмейстера был выдан для доступа к нему мулботам.

Общие изменения приложены в виде скриншотов в игре под комментариями До/После

close #11615
fix #11616

<details>
<summary>Чейнджлог</summary>

```yml
🆑FloweYStyle
maptweak: Исправлены баги после ремаппинга частей Исхода, возвращён деревянный интерьер комнаты конференций
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-16 20:16 UTC, FloweYStyle commented
Комната конференций до:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/77331370/aa2fc9b2-393d-4af9-b044-b1b0b05d625a)

После:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/77331370/3f9275d0-e1d3-4841-821e-53bdc7053949)


Мостик до:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/77331370/9d331afc-b974-41bd-b0c1-8f271e5e52db)

После:
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/77331370/fbadf148-fb5f-4dc4-acb3-8d1965a03554)

2024-02-16 20:16 UTC, FloweYStyle commented
Поставил драфт, потому что Волк выкатил очередную кучу багов, постараюсь исправить в том же темпе

2024-02-16 21:48 UTC, BooJ1K requested changes
Нет камер в кабинете ГП
Нет интеркома в кабинете ГП

Нет камер в подстанции командования

Требуется камера слепая зона без камер в коридоре шахтёрский вход – кабинет КМа 

Отсутствуют камеры в конферент зале для глав
Нет голопада в конферент зале для глав

2024-02-17 11:32 UTC, FloweYStyle commented
разработка, а нахуя вы мержите ПР Тоби который вышел после этого ПРа и который лишь частично решает нытье игроков? Найс конфликты блять

2024-02-17 12:44 UTC, closed without merging