feat(exodus): better bridge and conference room
ChaoticOnyx/OnyxBay pull request #11633
Opened 2024-02-17 12:59 UTC by FloweYStyle

#11622, а именно комната конференций, мостик и проводка с трубами.

<details>
<summary>Чейнджлог</summary>

```yml
🆑FloweYStyle
maptweak: Комната конференций вернула свой элегантный стиль, немного переделан мостик.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-18 19:43 UTC, Filatelele submitted a review, later dismissed

2024-02-19 20:07 UTC, BooJ1K requested changes
Забыл заменить 1 таил плитки на шлюзе 
120 121 2

![120 121 2](https://github.com/ChaoticOnyx/OnyxBay/assets/47336771/221ddbce-2064-4a6a-8d99-eb095c1b50a1)

2024-02-20 06:10 UTC, kreeperHLC commented
Жду замены

2024-02-20 19:34 UTC, FloweYStyle commented
ну

2024-02-20 19:36 UTC, intercepti0n approved these changes
Ок, только больше в чистилище не обзывайся, мне обидно.

2024-02-26 09:52 UTC, kreeperHLC approved these changes

2024-02-26 09:52 UTC, merged