feat(intercom): adding craft of intercoms
ChaoticOnyx/OnyxBay pull request #11649
Opened 2024-02-21 16:50 UTC by BaraBarax

Добавил крафт интеркомов. 

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
rscadd: Интеркомы теперь можно собрать и разобрать.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-21 17:26 UTC, BaraBarax commented on code/game/objects/items/devices/radio/intercom.dm
> +				return
```suggestion
				return
				
```

2024-02-21 17:32 UTC, BaraBarax commented
уэээ, надо логику в отдельный объект сунуть

2024-02-24 20:10 UTC, Filatelele requested changes

2024-02-24 20:10 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +		pixel_x = (dir & (NORTH|SOUTH))? 0 : (dir == EAST ? -22 : 22)
Magic numbers?

2024-02-25 10:24 UTC, BaraBarax commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +		pixel_x = (dir & (NORTH|SOUTH))? 0 : (dir == EAST ? -22 : 22)
магическое смещение на 22 пикселя

2024-02-26 11:02 UTC, intercepti0n commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +		pixel_x = (dir & (NORTH|SOUTH))? 0 : (dir == EAST ? -22 : 22)
Сделай локальный дефайн с назанием `INTERCOM_OFFSET` и добавляй к нему минус, где требуется.

2024-02-28 11:47 UTC, Filatelele approved these changes

2024-02-28 11:48 UTC, intercepti0n commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +
```suggestion
```

2024-02-28 11:49 UTC, Filatelele requested changes

2024-02-28 11:49 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +/obj/item/intercom_frame/New(loc, dir, atom/frame)
Так стоп, почему тут New вместо Initialize?

2024-02-28 11:49 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom.dm
> +/obj/item/device/radio/intercom/New(loc, dir)
Опять же должен быть Initialize(mapload, loc, dir)

2024-02-28 11:51 UTC, TobyThorne requested changes
два отдельных предмета /obj/item/frame/intercom и /obj/item/intercom_frame
с одинаковыми названиями name = "intercom frame"

это троллинг или чё

2024-02-28 11:53 UTC, TobyThorne commented on code/game/objects/items/devices/radio/intercom.dm
> +/obj/item/device/radio/intercom/New(loc, dir)
> Опять же должен быть Initialize(mapload, loc, dir)

какой Initialize(mapload, loc, dir)
Initialize(mapload, dir) и в нём уже дёргать loc ака src.loc если нужно

2024-02-28 14:45 UTC, Filatelele approved these changes

2024-03-01 17:07 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +	..(loc)
Еб твою мать что я нааппрувал

2024-03-01 17:07 UTC, intercepti0n commented on code/game/objects/items/devices/radio/intercom.dm
> +
```suggestion
```

2024-03-01 17:07 UTC, Filatelele requested changes

2024-03-01 17:07 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +	..(loc)
```suggestion
	. = ..()
```

2024-03-01 17:07 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom.dm
> +	..(loc)
```suggestion
	. = ..()
```

2024-03-01 17:10 UTC, intercepti0n commented on code/game/objects/items/devices/radio/intercom.dm
> +	show_splash_text(user, "unscrewing [src]...")
```suggestion
	show_splash_text(user, "unscrewing...")
```

2024-03-01 17:10 UTC, Filatelele requested changes

2024-03-01 17:10 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +		if (C.use(1))
```suggestion
		if(C.use(1))
```

2024-03-01 17:10 UTC, Filatelele commented on code/game/objects/items/devices/radio/intercom_frame.dm
> +	if (C.get_amount() < 1)
```suggestion
	if(C.get_amount() < 1)
```

2024-03-01 17:11 UTC, intercepti0n approved these changes

2024-03-01 17:11 UTC, Filatelele approved these changes

2024-03-01 17:12 UTC, Filatelele commented
С богом.

2024-03-01 18:15 UTC, BaraBarax commented
Ахуеть, за меня пулл реквест дописали

2024-03-03 18:18 UTC, TobyThorne approved these changes
когда-нибудь маленькая инди-компания из гаража добавит кнопку снять чр

2024-03-03 18:32 UTC, merged