feat(bedsheets): adds new bedsheets
ChaoticOnyx/OnyxBay pull request #11656
Opened 2024-02-22 11:34 UTC by kreeperHLC

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавление различных одеялок.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-02-22 12:26 UTC, TobyThorne requested changes
итем стейты где (вхере)

2024-02-22 12:29 UTC, kreeperHLC commented
> итем стейты где (вхере)

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/14943437/9b50212c-50a3-4362-bea0-b91d3baefe22)
Поддерживаю нездоровую традицию (Единственный спрайт в inv_slots)

2024-02-22 12:31 UTC, TobyThorne commented
> > итем стейты где (вхере)
> 
> ![image](https://private-user-images.githubusercontent.com/14943437/306994121-9b50212c-50a3-4362-bea0-b91d3baefe22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDUzMDYsIm5iZiI6MTcwODYwNTAwNiwicGF0aCI6Ii8xNDk0MzQzNy8zMDY5OTQxMjEtOWI1MDIxMmMtNTBhMy00MzYyLWJlYTAtYjkxZDNiYWVmZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEyMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyN2ZmMzE1NTkxZTJlZmQxYzRhNmRiZDY5MGI0OWZiZDFhYzY2MmRhYjlkNzFkOGQ5N2Y1YmUzMWY5NjgzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lg5SffwNRMpoVktYHC6QPSHJdEDp4Y70qrzEJlL_uC8) Поддерживаю нездоровую традицию (Единственный спрайт в inv_slots)

чел ты 
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/88338551-b183-4a63-b412-3e79549ffdee)

2024-02-22 12:31 UTC, kreeperHLC commented
> > > итем стейты где (вхере)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/14943437/306994121-9b50212c-50a3-4362-bea0-b91d3baefe22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDUzMDYsIm5iZiI6MTcwODYwNTAwNiwicGF0aCI6Ii8xNDk0MzQzNy8zMDY5OTQxMjEtOWI1MDIxMmMtNTBhMy00MzYyLWJlYTAtYjkxZDNiYWVmZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEyMzAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyN2ZmMzE1NTkxZTJlZmQxYzRhNmRiZDY5MGI0OWZiZDFhYzY2MmRhYjlkNzFkOGQ5N2Y1YmUzMWY5NjgzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lg5SffwNRMpoVktYHC6QPSHJdEDp4Y70qrzEJlL_uC8) Поддерживаю нездоровую традицию (Единственный спрайт в inv_slots)
> 
> чел ты ![image](https://private-user-images.githubusercontent.com/45202681/306994548-88338551-b183-4a63-b412-3e79549ffdee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDUzNjcsIm5iZiI6MTcwODYwNTA2NywicGF0aCI6Ii80NTIwMjY4MS8zMDY5OTQ1NDgtODgzMzg1NTEtYjE4My00YTYzLWI0MTItM2U3OTU0OWZmZGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEyMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMDcyMzFlNzdkZjY4YjUxYzI3NWI5NWRlNzBlZTJjMzEyZDI5NjgxOWEyNzVkNzZkNzRiNmQ4ODliYzgyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rjXwgvpc4nReElR1lx6WG5fn8N_1Y0Dnx4-t_0fzxJs)

😢

2024-02-24 14:17 UTC, Filatelele approved these changes

2024-02-24 14:18 UTC, Filatelele submitted a review, later dismissed
Где итем стейты?

2024-02-26 10:46 UTC, intercepti0n approved these changes

2024-02-26 17:33 UTC, TobyThorne approved these changes
буква ю

2024-02-27 07:08 UTC, merged