feat(exodus): fixes decal layout
ChaoticOnyx/OnyxBay pull request #11704
Opened 2024-03-02 19:23 UTC by FloweYStyle

Декали плитки в конференц руме больше не перекрывают декали, которые должны отображаться поверх них.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-03-02 19:27 UTC, intercepti0n requested changes
Ты забыл еще убрать стеклянную дверь, которая сломала пасфандинг мулботам в комнате для конференций.

2024-03-03 18:02 UTC, FloweYStyle commented
Иссуй с подробным описанием проблемы есть? Мне ничего не говорит сломанный патфайндинг, у меня всё работало

2024-03-03 19:03 UTC, intercepti0n commented
Декали тоже нормально рисовались? 🤔

2024-03-04 10:28 UTC, FloweYStyle commented
На декали я внимание не обращал, мне было важно первоначально проверить, работает ли маршрут карго-мостик у мулбота. Декали этот ПР фиксит, а мулбот у меня работал

2024-03-05 12:56 UTC, intercepti0n commented
ЧР я энивей без этой правки не сниму.

2024-03-06 08:32 UTC, FloweYStyle commented
ок

2024-03-06 08:51 UTC, kreeperHLC approved these changes

2024-03-06 11:43 UTC, Filatelele commented
Автор не может кодербас поможет.

2024-03-06 11:43 UTC, closed without merging