tweak(clothing): resprite flannel shirt
ChaoticOnyx/OnyxBay pull request #11782
Opened 2024-03-09 21:19 UTC by i1yadobr

Изменил спрайт фланнельной рубашки на более мягкие цвета, и немного пофиксил спрайты
<details><summary>Старое</summary> 
![Old](https://github.com/ChaoticOnyx/OnyxBay/assets/155672646/a89f66ee-1822-47df-a98b-ae43558a8f65)
![Old1](https://github.com/ChaoticOnyx/OnyxBay/assets/155672646/1993061d-8645-4fb2-8063-1cb27033b802)
</details>
<details><summary>Новое</summary> ![New](https://github.com/ChaoticOnyx/OnyxBay/assets/155672646/a5292877-b285-4353-b0fd-020c585894fd
![New1](https://github.com/ChaoticOnyx/OnyxBay/assets/155672646/8bb993e1-523d-4dbc-a9a1-1bedd9aa4bc1)
</details>

<details>
<summary>Чейнджлог</summary>

```yml
🆑 ilyadobr
imageadd: Респрайт фланнельной рубашки
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-03-11 23:32 UTC, Filatelele requested changes

2024-03-11 23:32 UTC, Filatelele commented on code/modules/client/preference_setup/loadout/lists/clothing.dm
> +	flannel["comfy flannel"] = /obj/item/clothing/accessory/toggleable/flannel
Пробельчик нужен

```suggestion
	flannel["comfy flannel"] = /obj/item/clothing/accessory/toggleable/flannel

```

2024-03-11 23:32 UTC, Filatelele commented on code/modules/client/preference_setup/loadout/lists/clothing.dm
> +	flannel["soft flannel"] = /obj/item/clothing/accessory/toggleable/flannel/alt
Аналогично нужен про бел

```suggestion
	flannel["soft flannel"] = /obj/item/clothing/accessory/toggleable/flannel/alt

```

2024-03-11 23:49 UTC, i1yadobr commented on code/modules/client/preference_setup/loadout/lists/clothing.dm
> +	flannel["soft flannel"] = /obj/item/clothing/accessory/toggleable/flannel/alt
Я сейчас сделаю, но не совсем понимаю, к чему эти пробелы, если аналогичная гавайка сделана без них

![356363562542](https://github.com/ChaoticOnyx/OnyxBay/assets/155672646/2a1475bd-c7cd-4e16-9c7e-bf3325f61062)

2024-03-12 00:15 UTC, intercepti0n commented on code/modules/client/preference_setup/loadout/lists/clothing.dm
> +	flannel["soft flannel"] = /obj/item/clothing/accessory/toggleable/flannel/alt
Данный код был скорее всего написан много лет назад. В те времена за опрятностью кода не особо следили, но времена изменились.

2024-03-12 00:41 UTC, Filatelele approved these changes, later dismissed

2024-03-12 00:41 UTC, Filatelele commented
Я там немного не туда сагг воткнул
Но похуй

2024-03-12 04:27 UTC, TobyThorne requested changes

2024-03-12 04:27 UTC, TobyThorne commented on code/modules/clothing/under/accessories/clothing.dm
> +	name = "flannel comfy shirt"
```suggestion
	name = "comfy flannel shirt"
```
оценочные прилагательные идут до качественных

2024-03-12 04:27 UTC, TobyThorne commented on code/modules/clothing/under/accessories/clothing.dm
> +	name = "flannel soft shirt"
```suggestion
	name = "soft flannel shirt"
```
аналогичное

2024-03-12 08:02 UTC, Filatelele commented on code/modules/client/preference_setup/loadout/lists/clothing.dm
> +	gear_tweaks += new /datum/gear_tweak/path(flannel)
```suggestion
	flannel["comfy flannel"] = /obj/item/clothing/accessory/toggleable/flannel
	flannel["soft flannel"] = /obj/item/clothing/accessory/toggleable/flannel/alt
	gear_tweaks += new /datum/gear_tweak/path(flannel)
```

2024-03-12 08:04 UTC, TobyThorne approved these changes
фиксирую угон ПРа

2024-03-12 08:06 UTC, Filatelele approved these changes
Произошел рейдерский захват ПРа.

2024-03-12 08:06 UTC, merged