tweak(rotation): reject verbs, go to altclick
ChaoticOnyx/OnyxBay pull request #11894
Opened 2024-03-21 12:08 UTC by BaraBarax

Убрал большинство вербов и переизобретение кручения говна, поставил кручение на альтклик, 

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
tweak: Трубы, эмиттеры и прочие вертящиеся предметы теперь крутятся на альтклик вместо контекстного меню
/🆑
```

</details>

<details>
<summary>Предупреждение</summary>

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/96526791/e8689365-284f-4370-a685-a9e598f76275)

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-03-21 12:42 UTC, TobyThorne commented
а в чём проблема сделать и альклик и вёрб

2024-03-21 12:43 UTC, Filatelele commented
А нахуй вербы нужны, в 2к24 живем же

2024-03-21 12:44 UTC, TobyThorne commented
> А нахуй вербы нужны, в 2к24 живем же

а нахуй их убирать, если они есть
ебал я этот пиксельхантинг, особенно если труба по Y лежит и сверху хуман стоит

2024-03-21 12:47 UTC, BaraBarax commented
Альтклик по турфу и там вертишь

2024-03-21 12:55 UTC, Zert0X commented
> Альтклик по турфу и там вертишь

ебать оверинжиниринг... ведь чтобы прокрутить в альтклике по турфу надо альткликать в альтклике

2024-03-21 12:55 UTC, BaraBarax commented
Ну искать кнопку в контекстном меню веселее, не спорю

2024-03-21 13:00 UTC, BaraBarax commented
Причём если тебе нужно повернуть хуйню больше чем один раз, контекстное меню нужно открывать каждый ебучий раз

2024-03-21 14:42 UTC, BaraBarax commented
Вроде всё

2024-03-22 18:15 UTC, TobyThorne requested changes

2024-03-22 18:15 UTC, TobyThorne commented on code/game/objects/structures/window.dm
> +		show_splash_text(user, "unfasten it first!")
```suggestion
		show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor therefore you can't rotate it!")
```

2024-03-24 16:41 UTC, BaraBarax commented
Переделываю реализацию

2024-03-25 13:48 UTC, BaraBarax commented
да за что блять

2024-03-25 13:50 UTC, BaraBarax commented
победа, предоставляю ебало к осмотру

2024-03-25 13:57 UTC, BaraBarax commented on code/game/machinery/pipe/construction.dm
> +
```suggestion
```

2024-03-25 18:41 UTC, BaraBarax commented on code/game/machinery/pipe/construction.dm
> +	//src.pipe_set_dir(get_pipe_dir())
```suggestion
```

2024-03-25 23:09 UTC, Filatelele commented on code/datums/elements/simple_rotation.dm
> +		show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor therefore you can't rotate it!")
Нахуевертил чет сложную конструкцию, у нас тут не academic writing

```suggestion
		show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor and can not be rotated !")
```

2024-03-25 23:12 UTC, TobyThorne commented on code/datums/elements/simple_rotation.dm
> +		show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor therefore you can't rotate it!")
> Нахуевертил чет сложную конструкцию, у нас тут не academic writing

show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor and can't be rotated!")

2024-03-25 23:14 UTC, Filatelele requested changes
Есть пара замечаний. 

В Initialize() мы используем ``. = ..()`` а не ``..()``, запомни. Если не понятно почему - велком в дискорд ко мне или интерсепшну. Это важно. 

Ну а так вроде все, весьма достойный код.

2024-03-25 23:14 UTC, Filatelele commented on code/game/machinery/pipe/construction.dm
> +		if(dir==2)
А че не дефайны и где пробелы?

2024-03-25 23:14 UTC, Filatelele commented on code/game/objects/structures/secure_door_assembly.dm
> +	..()
```suggestion
	. = ..()
```

2024-03-25 23:14 UTC, Filatelele commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	..()
```suggestion
	. = ..()
```

2024-03-25 23:14 UTC, Filatelele commented on code/modules/mining/mine_items.dm
> +	..()
```suggestion
	. = ..()
```

2024-03-25 23:14 UTC, Filatelele commented on code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
> +	..()
```suggestion
	. = ..()
```

2024-03-25 23:14 UTC, Filatelele commented on code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
> +	..()
```suggestion
	. = ..()
```

2024-03-25 23:14 UTC, Filatelele commented on code/game/objects/structures/windoor_assembly.dm
> +		update_nearby_tiles(need_rebuild=1) //Compel updates before
Плюс не понял комментарий соре

```suggestion
		update_nearby_tiles(need_rebuild = 1) //Compel updates before
```

2024-03-25 23:14 UTC, Filatelele commented on code/game/objects/structures/windoor_assembly.dm
> +		update_nearby_tiles(need_rebuild=1)
```suggestion
		update_nearby_tiles(need_rebuild = 1)
```

2024-03-25 23:14 UTC, Filatelele commented on code/datums/elements/simple_rotation.dm
> +		show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor therefore you can't rotate it!")
Как и предыдущий сагг

2024-03-25 23:14 UTC, intercepti0n commented on code/game/objects/structures/windoor_assembly.dm
> +		update_nearby_tiles(need_rebuild=1)
Сразу бы и тру прописал шоле...

2024-03-25 23:15 UTC, Filatelele commented on code/datums/elements/simple_rotation.dm
> +		show_splash_text(user, "unfasten it first!", "\The [src] is fastened to the floor therefore you can't rotate it!")
>Доебался до того что у нас тут не академик райтинг
>Сам написал can not вместо can't 
>Канцеляризм головного мозга

Сука я позорник.

2024-03-25 23:15 UTC, TobyThorne commented on code/datums/elements/simple_rotation.dm
> +	set hidden = TRUE
```suggestion
```

2024-03-25 23:16 UTC, Filatelele commented on code/datums/elements/simple_rotation.dm
> +	set hidden = TRUE
Да го спрячем вербы для шлимазлов

2024-03-25 23:16 UTC, intercepti0n commented on code/datums/elements/simple_rotation.dm
> +	set hidden = TRUE
А это разве не сделает верб всегда видимым?

2024-03-25 23:17 UTC, Filatelele commented on code/datums/elements/simple_rotation.dm
> +	set hidden = TRUE
Бтв это прок по идее нет

2024-03-25 23:18 UTC, TobyThorne commented on code/datums/elements/simple_rotation.dm
> +	set hidden = TRUE
> А это разве не сделает верб всегда видимым?

так он добавляется ток при прикручивании элемента, не?

2024-03-26 10:29 UTC, BaraBarax commented on code/game/objects/structures/windoor_assembly.dm
> +		update_nearby_tiles(need_rebuild=1) //Compel updates before
"Принудительно обновляем перед"
Предполагаю что обновляет перед прокруткой на всякий

2024-03-26 13:38 UTC, Filatelele approved these changes, later dismissed

2024-03-26 14:39 UTC, intercepti0n submitted a review, later dismissed
Я надеюсь, что автор все протестировал.

2024-03-26 15:52 UTC, Filatelele approved these changes, later dismissed
Автор сказал что все протестировал. Пожалуй, поверим ему.

2024-03-26 15:59 UTC, BaraBarax commented
Я пиздабол

2024-03-26 16:01 UTC, intercepti0n commented on code/modules/power/pedal_gen.dm
> +			buckled_mob.buckled = null //Temporary, so Move() succeeds.
Что?

2024-03-26 16:04 UTC, BaraBarax commented on code/modules/power/pedal_gen.dm
> +			buckled_mob.buckled = null //Temporary, so Move() succeeds.
Я не вчитывался в чужой код

2024-03-26 16:06 UTC, intercepti0n commented on code/modules/power/pedal_gen.dm
> +			buckled_mob.buckled = null //Temporary, so Move() succeeds.
Ну тогда осмысли и напиши нормально, это какой-то анекдот.

2024-03-26 16:11 UTC, BaraBarax commented on code/modules/power/pedal_gen.dm
> +			buckled_mob.buckled = null //Temporary, so Move() succeeds.
Знать бы, что здесь происходит...

2024-03-28 13:06 UTC, BaraBarax commented on code/modules/power/pedal_gen.dm
> +			buckled_mob.buckled = null //Temporary, so Move() succeeds.
Жёстко переосмыслил

2024-03-28 13:08 UTC, Filatelele approved these changes, later dismissed

2024-03-28 13:08 UTC, intercepti0n submitted a review, later dismissed

2024-03-28 13:38 UTC, TobyThorne commented
вербы всё ещё не работают

2024-03-28 13:45 UTC, TobyThorne commented on code/datums/elements/simple_rotation.dm
> +
```suggestion
	set name = "Rotate Counterclockwise"
	set category = "Object"
```

2024-03-28 13:45 UTC, TobyThorne commented on code/datums/elements/simple_rotation.dm
> +	set name = "Rotate Clockwise"
```suggestion
	set name = "Rotate Clockwise"
	set category = "Object"
```

2024-03-30 13:13 UTC, BaraBarax commented
Ахуеть, спасибо папаша

2024-03-30 13:55 UTC, Filatelele approved these changes, later dismissed

2024-03-30 14:10 UTC, intercepti0n approved these changes, later dismissed

2024-03-30 15:19 UTC, TobyThorne commented
вербов во вкладке обжект всё ещё нет + при альклике с кручением открывается вкладка турф

2024-03-30 15:29 UTC, BaraBarax commented
Блять, вчера же было..

2024-03-30 15:31 UTC, Filatelele commented
Увы вербы в статпанели больше не появляются если предмет не в руках

2024-03-30 15:33 UTC, BaraBarax commented
А насчёт второго это пиздёж

2024-03-30 15:39 UTC, BaraBarax commented
Я неправильно прочитал

2024-03-30 15:39 UTC, BaraBarax commented
as intended

2024-03-30 15:49 UTC, TobyThorne commented
> А насчёт второго это пиздёж

https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/ddd93bbe-5b65-4b24-ab1f-12ac89563dd8

2024-03-30 15:50 UTC, BaraBarax commented
Я уже сказал что я дислексик

2024-03-30 15:54 UTC, BaraBarax commented
Пусть открывается, в чём проблема?

2024-03-30 15:55 UTC, TobyThorne commented
> Пусть открывается, в чём проблема?

в том, что ни у одного другого предмета с взаимодействием на альтклик оно не открывается

2024-03-30 16:16 UTC, BaraBarax commented
бывает

2024-03-31 18:58 UTC, AnimeshkaTvar commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-03-31 19:07 UTC, BaraBarax commented
Ахуеть, спасибо папаша

2024-03-31 19:08 UTC, BaraBarax commented
Лан, если завтра не закончу с этой хуйнëй - закрою.

2024-03-31 19:33 UTC, Filatelele approved these changes

2024-03-31 19:34 UTC, Filatelele approved these changes
Нет оснований не доверять интерцепшну. Если все сломается - вы знаете кого бить палкой.

2024-03-31 20:15 UTC, TobyThorne approved these changes
похуй, добейте уже этот кусок говна

2024-03-31 20:15 UTC, merged