Upgrade(Eclipse) Holodeck and CentComm upgrades
ChaoticOnyx/OnyxBay pull request #11891
Opened 2024-03-20 21:22 UTC by Rampoch

Улучшение карты к последним обновам билда.
close #11681 
close #11680 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
maptweak: Эклипс: Приведение карты к обнове голодека;
maptweak: Эклипс: Обновление баз антагов на ЦК улучшениями Крипера;
maptweak: Эклипс: Фикс рантаймов;
maptweak: Эклипс: Прочие улучшения декора.

/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-03-20 21:29 UTC, Filatelele submitted a review, later dismissed

2024-03-21 13:20 UTC, intercepti0n approved these changes

2024-03-21 13:20 UTC, intercepti0n requested changes
Ты забыл старые зоны удалить.

2024-03-23 15:25 UTC, intercepti0n approved these changes

2024-03-25 09:11 UTC, kreeperHLC approved these changes

2024-03-25 23:04 UTC, merged