feat(uniforms): new skirts
ChaoticOnyx/OnyxBay pull request #11939
Opened 2024-03-25 18:00 UTC by BaraBarax

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara and Ilyadobr
rscadd: Добавлены новые виды юбок в лодаут
/🆑
```

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим x внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над ПРом. ЭТУ СТРОЧКУ НУЖНО УДАЛИТЬ.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-03-25 18:01 UTC, BaraBarax commented
Ahuenno

2024-03-25 18:01 UTC, BaraBarax commented
Спрайты пока на доработке

2024-03-26 07:28 UTC, TobyThorne commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/e334a628-d759-4890-808c-70a07268d424)

2024-03-30 12:06 UTC, Filatelele commented
Как доделаешь - закинь в превью скриншоты, предпочтительно из игры

2024-03-30 12:10 UTC, BaraBarax commented
Пон

2024-03-31 19:48 UTC, Filatelele approved these changes

2024-03-31 19:56 UTC, Filatelele commented
А НЕТ СТОП, мы не принимаем новые спрайты без айтемстейтов в руках.

2024-03-31 19:57 UTC, Filatelele requested changes
Нужны айтемстейты в руках, до.

2024-03-31 20:02 UTC, Filatelele approved these changes, later dismissed
Ihnahnd спрайты есть, аппрув. 

Прости боже.

2024-03-31 20:02 UTC, intercepti0n commented
Я тебя шлангом от чахи придушу.

2024-03-31 20:29 UTC, BaraBarax commented
Давааай, ебаааашь

2024-03-31 20:48 UTC, TobyThorne requested changes, later dismissed
контур из 2к20, из-под этой хуйни трусы торчат

не для этого спрайты фиксим

2024-03-31 20:51 UTC, BaraBarax commented
Откуда торчат?

2024-03-31 20:54 UTC, TobyThorne commented
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/1311c3fa-588f-49d6-a2f4-b6cb87451e83)

2024-03-31 21:00 UTC, BaraBarax commented
нужно выше поднять?

2024-03-31 21:07 UTC, BaraBarax commented
Юбку.

2024-04-01 12:20 UTC, BaraBarax commented
Ой, блять...

2024-04-01 14:40 UTC, Filatelele approved these changes
Да простят меня боги, билд и Тоби.

2024-04-04 19:12 UTC, Filatelele approved these changes

2024-04-04 19:23 UTC, igorsaux approved these changes

2024-04-04 19:23 UTC, Filatelele commented
Пока не мержим, нужно поставить ограничение в выборе цвета иначе будет кукож.

2024-04-05 01:56 UTC, BaraBarax commented
Какое ещë ограничение, нахуя...

2024-04-05 03:58 UTC, BaraBarax commented
Ставьте тогда ограничения на всё лодаутные шмотки, лол

2024-04-05 18:29 UTC, merged