fix(xenobio): bunch of variable fixes
ChaoticOnyx/OnyxBay pull request #11978
Opened 2024-03-29 18:45 UTC by Zert0X

close #11556
close #11743
close #11843
close #11916
close #11951
# Tasks
- [x] Сделать regenerate_limbs восстановление не всех конечностей сразу, а выборочно. `уже было сделано но выбора нет, он просто лечит по возможности всё что может`
- [x] Canibalize body должен сначала есть ступни/ладони, потом крупные конечности
## Slimeperson
- [x] Название решили оставить.
- [ ] Баланс сранья клонами.
## Luminescent
- [x] Grey Minor – превращает в человека без спрайта.
- [x] Grey Major – превращает в человека без спрайта, должен давать выбор на превращения в другой подвид промитев.

- [x] Metal Major – спавнит железные слитки, вместо стальных листов – не адаптировали под наш билд?

- [x] Purple Minor – даёт нутриты и кровь. Кровь невозможно потерять её всегда 600. Предлагаю заменить кровь на metroidjelly.

- [ ] Yellow Minor – загорается, но сразу гаснет, нет кд, должна переключаться?

- [x] Red Minor – даёт inaprovaline при этом пишет: "You start feeling fast" Заменить на гиперзин или другой вид спидов?

- [x] Blue Major – Теперь пена спавнится.

- [x] Green Major – спавнит серого метроида. Заменить на зелёного.

- [x] Black Major – Было решено сделать превращение в вампира и смену спешиса на любой кроме прометея

- [x] Adamantine Major – превращает в человека без спрайта. Должно в голема адамантитового.

- [x] Pyrite Minor – не работает. Должен спавнить рандомный мелок.

- [x] Сerulean Minor – не имеет смысла. Теперь заправляет балон, который ты держишь в руках

## Stargazer

- [x]  Slime Link -> Stargazer Link?

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Фикс различных багов ксенобио.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-03-29 18:58 UTC, Filatelele submitted a review, later dismissed
Хуже уже не будет

2024-03-30 12:40 UTC, Filatelele requested changes

2024-03-30 12:40 UTC, Filatelele commented on code/__defines/species.dm
> +#define SPECIES_FLAG_NO_MINOR_CUT        (1<<1) // Can step on broken glass with no ill-effects. Either thick skin (diona/vox), cut resistant (metroids) or incorporeal (shadows)
Ну сделай ты комменты через тройной слеш, тыж не Тоби и вскодом пользуешься, ну бля

2024-03-30 12:40 UTC, Filatelele commented on code/_global_vars/bitfields.dm
> -	"FLAG_NO_TANGLE" = SPECIES_FLAG_NO_TANGLE,
А куда ты флаг NO_TANGLE дел?

2024-03-30 12:40 UTC, Filatelele commented on code/modules/materials/material_sheets.dm
> +	apply_colour = 1
Этож буль

```suggestion
	apply_colour = TRUE
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/materials/materials.dm
> +	stack_origin_tech = list(TECH_MATERIAL = 6, TECH_ARCANE = 1)
Насколько я понял у нас этот TECH_ARCANE вообще не используется, го уберем отсюда его тогда

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/23741266/2945a9e7-9e96-478f-bbf5-655a215566d4)

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/prometheans.dm
> +	if(H.has_organ(BP_L_FOOT)||H.has_organ(BP_R_FOOT)) //Feets go before legs
```suggestion
	if(H.has_organ(BP_L_FOOT) || H.has_organ(BP_R_FOOT)) //Feets go before legs
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/prometheans.dm
> +	if(H.has_organ(BP_L_LEG)||H.has_organ(BP_R_LEG)) //Legs go before Hands
```suggestion
	if(H.has_organ(BP_L_LEG) || H.has_organ(BP_R_LEG)) //Legs go before Hands
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/prometheans.dm
> +	if(H.has_organ(BP_L_HAND)||H.has_organ(BP_R_HAND)) //Hands go before arms
```suggestion
	if(H.has_organ(BP_L_HAND) || H.has_organ(BP_R_HAND)) //Hands go before arms
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/prometheans.dm
> +	else if(jelly_volume > BLOOD_VOLUME_BAD+25)//We can partially heal some limbs
```suggestion
	else if(jelly_volume > BLOOD_VOLUME_BAD + 25)//We can partially heal some limbs
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/prometheans.dm
> +		while(jelly_volume >= BLOOD_VOLUME_BAD+25)
```suggestion
		while(jelly_volume >= BLOOD_VOLUME_BAD + 25)
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/slime.dm
> +	if(LAZYLEN(BS.bodies)>=MAX_BODY_COUNT)
```suggestion
	if(LAZYLEN(BS.bodies) >= MAX_BODY_COUNT)
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/human/species/station/prometheans/slime.dm
> +	spare_jelly_vessel.remove_jelly(H.species.blood_volume*(BLOOD_VOLUME_SLIME_SPLIT/100))
```suggestion
	spare_jelly_vessel.remove_jelly(H.species.blood_volume * (BLOOD_VOLUME_SLIME_SPLIT / 100))
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/crossbreeding/_clothing.dm
> +			set_next_think(world.time+cooldown)
```suggestion
			set_next_think(world.time + cooldown)
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/crossbreeding/_clothing.dm
> +	set_next_think(world.time+cooldown)
```suggestion
	set_next_think(world.time + cooldown)
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/extracts.dm
> +			user.reagents.add_reagent(/datum/reagent/hyperzine,5)
```suggestion
			user.reagents.add_reagent(/datum/reagent/hyperzine, 5)
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/extracts.dm
> +			FS.set_up(20 , get_turf(user), user.reagents)
```suggestion
			FS.set_up(20, get_turf(user), user.reagents)
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/extracts.dm
> +				to_chat(user, SPAN_NOTICE("You need to hold something capable to hold gases!"))
Меняй везде to_chat на show_splash_text()
Тем более что у сплешиков сладких теперь есть преф выводить сплеш или тучат для динозавров

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/extracts.dm
> +			GM.adjust_gas("oxygen", (ONE_ATMOSPHERE*tank.volume/(R_IDEAL_GAS_EQUATION*(30 CELSIUS))))
```suggestion
			GM.adjust_gas("oxygen", (ONE_ATMOSPHERE*tank.volume / (R_IDEAL_GAS_EQUATION * (30 CELSIUS))))
```

2024-03-30 12:40 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/extracts.dm
> +			to_chat(user, SPAN_NOTICE("You're feeling some dizziness, and decided to stop!"))
Сплееешики

2024-03-30 12:48 UTC, Zert0X commented on code/_global_vars/bitfields.dm
> -	"FLAG_NO_TANGLE" = SPECIES_FLAG_NO_TANGLE,
Куда куда выше читай, на 3 строчки.

2024-03-30 13:08 UTC, Filatelele requested changes

2024-03-30 13:08 UTC, Filatelele commented on code/__defines/species.dm
> +#define SPECIES_FLAG_NO_MINOR_CUT        (1<<1)  /// Can step on broken glass with no ill-effects. Either thick skin (diona/vox), cut resistant (metroids) or incorporeal (shadows)
```suggestion
/// Can step on broken glass with no ill-effects. Either thick skin (diona/vox), cut resistant (metroids) or incorporeal (shadows)
#define SPECIES_FLAG_NO_MINOR_CUT        (1<<1)
```

2024-03-30 13:08 UTC, Filatelele commented on code/datums/components/mind_linker.dm
> +	//desc = "Link someone's mind to your Stargazer Link, allowing them to communicate telepathically with other linked minds."
А нахуя вообще закоменченный код оставлять

2024-03-30 13:31 UTC, Filatelele requested changes

2024-03-30 13:31 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/crossbreeding/_clothing.dm
> +	var/cooldown = 30 SECOND
```suggestion
	var/cooldown = 30 SECONDS
```

2024-03-30 13:31 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/crossbreeding/_clothing.dm
> +	var/cooldown = 30 SECOND
А лучше го дефайн

2024-03-30 13:33 UTC, Filatelele requested changes
НЬЮЛАЙНСССССССС

2024-03-30 13:33 UTC, Filatelele commented on code/modules/mob/living/carbon/xenobiological/crossbreeding/_clothing.dm
> +#define FLOWER_COOLDOWN 30 SECONDS
```suggestion

#define FLOWER_COOLDOWN 30 SECONDS

```

2024-03-30 13:34 UTC, Filatelele approved these changes

2024-03-30 13:35 UTC, intercepti0n approved these changes

2024-03-30 13:35 UTC, merged