Event "nightmare future"
ChaoticOnyx/OnyxBay pull request #11986
Opened 2024-03-30 12:43 UTC by Devyashka

Ивенточный ПР на разок.
P.S Можно было и ООПешнее, но ничего сервер положить не должно.

2024-03-30 13:03 UTC, Filatelele commented
Весьма качественно написанный код, проблем не увидел. 

~~проде точно пиздец~~

2024-03-30 14:05 UTC, TobyThorne requested changes
![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/1cb76fd5-3f64-4a39-b841-687b7da30783)
втф

и коробку нахрен убивать, бахни отдельную карту

2024-03-30 14:22 UTC, Zert0X commented
Напомню что это ивент на один раунд литерали, а не ввод в игру нового типа ивента

2024-03-31 19:30 UTC, Filatelele requested changes
Вы просили ревью? Получайте. И это я просто пробежался глазами и зацепился за очевидное.

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +	return 1
Мы используем дефайны TRUE/FALSE, а не возвращаем единички и нулики когда функция должна возвращать булевое значение.

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 1
TRUE

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 0
FALSE

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +	return 0
FALSE

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 0
FALSE

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 0
FALSE

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 0
А еще после ретурнов мы делаем ньюлайны

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 0
А еще после ретурнов мы делаем ньюлайны

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 1
А еще после ретурнов мы делаем ньюлайны

2024-03-31 19:30 UTC, Filatelele commented on code/_onclick/click.dm
> +		return 0
А еще после ретурнов мы делаем ньюлайны

2024-03-31 19:30 UTC, Filatelele commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Вы - квалифицированный доктор.")
Русский язык в коде запрещен, тут нужен тритмент, аналогичный лавгиверу.

2024-03-31 19:30 UTC, Filatelele commented on code/datums/helper_datums/teleport.dm
> +	spawn(4)
Мы не используем спавны, слипы и иное говно. 
INVOKE_ASYNC all the way

2024-03-31 19:30 UTC, Filatelele commented on code/datums/helper_datums/teleport.dm
> +	var/new_z = M.z > 2 ? M.z - 2 : M.z + 2
Вот этот великий телепорт между уровнями карт просто ужасен. 

Получай как-то нормально уровни, а не вот это вот.

2024-03-31 19:30 UTC, Filatelele commented on code/datums/outfits/outfit.dm
> +			H.equip_to_slot_or_del(new U(H),slot_w_uniform)
Здесь и далее - потерян пробел после запятой.

2024-03-31 19:30 UTC, Filatelele commented on code/game/machinery/doors/firedoor.dm
> +	opacity = 1
TRUE

2024-03-31 19:30 UTC, Filatelele commented on code/game/machinery/doors/firedoor.dm
> +	density = 1
TRUE

2024-03-31 19:30 UTC, Filatelele commented on code/game/objects/items/stacks/telecrystal.dm
> +	user.visible_message(SPAN_WARNING("[user] crushes [src]!"), SPAN_DANGER("You crush [src]!"))
Переносим второй аргумент (Тот который SPAN_DANGER) на следующую строку иначе это нечитаемо

2024-03-31 19:30 UTC, Filatelele commented on code/game/objects/items/weapons/potato.dm
> +/obj/item/potato/attack_self(mob/user as mob)
Ну а вот и копипаста. Мы не используем as в аргументах функции

2024-03-31 19:30 UTC, Filatelele commented on code/game/objects/items/weapons/potato.dm
> +/obj/item/potato/Crossed(AM as mob|obj)
Ну а вот и копипаста. Мы не используем as в аргументах функции

2024-03-31 19:30 UTC, Filatelele commented on code/game/objects/items/weapons/potato.dm
> +			spawn(0)
spawn(0) а за ним кудель. Красивое...

2024-03-31 19:30 UTC, Filatelele commented on code/game/objects/items/weapons/potato.dm
> +				"<span class='danger'>[L] steps on \the [src].</span>",
Ну и очередная копипаста, юзаем макросы типа SPAN_NAME вместо <span class>

2024-03-31 19:30 UTC, Filatelele commented on code/modules/admin/verbs/adminjump.dm
> +	for(var/mob/M in GLOB.player_list)
Душевный прок который переносит даже гостов.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/admin/verbs/adminjump.dm
> +		if(M.z < 3)
Опять же вместо арбитрарных значений переменной z надо как-то нормально получать станционный уровень.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/admin/verbs/adminjump.dm
> +/client/proc/DownAllUsers()
А еще у нас запрещен паскаль кейс в названиях проков.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/awaymissions/corpse.dm
> +	if (bullet)
Пробел лишний, у нас это не принято и порицается. if(bullet) и точка.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/awaymissions/corpse.dm
> +	if (damage > 0)
Пробел лишний, у нас это не принято и порицается. if(bullet) и точка.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/awaymissions/corpse.dm
> +	M.dir = rand(1, 4) * 2
Что это за конструкция? 

pick(GLOB.cornerdirs)

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/silicon/robot/preset.dm
> +	var/list/wizardy_spells = list(/datum/spell/targeted/say/standart_medbot, /datum/spell/targeted/say/target_medbot, /datum/spell/targeted/say/after_heal_medbot, /datum/spell/targeted/say/dead_pacient
Во первых это надо делать экшнами (как у пук-пауков), одно дело мы работаем с легаси-кодом типа волшебника/генокрота, а другое дело мы работаем с новым кодом.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	hide_on_manifest = 1
ТРУФОЛС БЛЯДЬ, дальше комментов про это не будет ибо заебало

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	src.modules += new /obj/item/crowbar(src)
Опять гнойная копипаста. Тут src. не нужен!

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	var/obj/item/stack/medical/advanced/ointment/O = new /obj/item/stack/medical/advanced/ointment(src)
Ну ты хоть по порядку это делай, иначе читать невозможно просто

```var/penis = new()
penis.grow(5)
modules += penis
zaloopa = new()
zaloopa.grow(15)
modules += zaloopa```

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +		new /obj/effect/decal/cleanable/blood/gibs(src.loc)
Очередная копипаста, ну какой срц.лок)

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/event_mob.dm
> +	var/list/wizardy_spells = list(/datum/spell/toggled/transform, /datum/spell/toggled/thermal, /datum/spell/toggled/sting_paralize)
Аналогично как с прошлым, el gringe. 

К тому же это надо глобальным листом делать, ну.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
Что это вообще делает?

2024-03-31 19:30 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	..()
А зачем родителя вызываешь?

2024-03-31 19:30 UTC, Filatelele commented on code/modules/power/lighting.dm
> +		if(T.z == 3 || T.z == 4)
Получаем Z уровень нормально, а не через арбитрарные циферки

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/targeted/heal_slug.dm
> +		if(do_after(user, 50, H))
После дуафтера надо выполнять проверки на QDELETED

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/targeted/pumping_out_blood.dm
> +		if (H.stat == DEAD)
is_ic_dead()

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/targeted/pumping_out_blood.dm
> +			to_chat(user, "<span class='warning'>That was not so bright of you.</span>")
Да ты издеваешься что ли?

Выше - нормальное использование макроса SPAN

Здесь - "<span class='warning'>

Это какой-то копипаст в котором ты сам не разобрался толком.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/targeted/pumping_out_blood.dm
> +		if(do_after(user, 150, H))
После дуафтера проверки QDELETED...

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	charge_counter = mana_max
Этот спел вообще не использует chrage_counter

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	mana_current = mana_max
У тебя уже mana_current = 100 на 10 строчке, зачем это?

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +/datum/spell/toggled/sting_paralize/check_charge(skipcharge, mob/user)
Это вообще не нужно...

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
А зочем тут это все если родитель сам проверяет ману и все такое...

```
. = ..()
if(!.)
    return
/paste ur code here/
```

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +		return
Ты хоть сам понял что написал?

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
Зачем то еще один некст тинк поставил, а вот это реально может думатель убить.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
ТБХ думатель убить сложно, Игорь все таки не идиот, но вот рантаймить точно будет

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
Можно просто вызывать родителя который делает это все сам

Но ты зачем-то скопипастил код родителя и испоганил его. Это уже личное оскорбление какое-то!

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/thermal.dm
> +/datum/spell/toggled/thermal/New()
New() который ничего не делает. Все нормально? Не думаю.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/thermal.dm
> +	if(!..())
А вот здесь внезапно нормально сделал, в отличие от прошлого тогглд спела.

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/transform.dm
> +	charge_counter = mana_max
Где то выше я уже писал комментарии по этому поводу...

2024-03-31 19:30 UTC, Filatelele commented on code/modules/spells/toggled/transform.dm
> +	if(mana_current < mana_max)
https://youtu.be/wdfLr97nblE

2024-03-31 21:16 UTC, Devyashka commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Вы - квалифицированный доктор.")
Не баг, а фича. Здесь ему было необходимо иметь русскоязычные законы, чтобы на время ивента никто не дрочился с переводчиком, пытаясь понять шутку в законах.

2024-03-31 21:17 UTC, Devyashka commented on code/datums/helper_datums/teleport.dm
> +	var/new_z = M.z > 2 ? M.z - 2 : M.z + 2
"Как-то нормально" - это как?
По названию карты?

2024-03-31 21:17 UTC, Filatelele commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Вы - квалифицированный доктор.")
Ты хотел ревью? Ты его получил. Русский язык З А П Р Е Щ Е Н правилами репозитория. Запрещен, и точка.

2024-03-31 21:18 UTC, Devyashka commented on code/datums/helper_datums/teleport.dm
> +	spawn(4)
Буду знать

2024-03-31 21:23 UTC, Devyashka commented on code/game/objects/items/weapons/potato.dm
> +/obj/item/potato/attack_self(mob/user as mob)
В примерах, которые тут есть - используют. Буду знать, что так впредь не делают

2024-03-31 21:24 UTC, Devyashka commented on code/game/objects/items/weapons/potato.dm
> +				"<span class='danger'>[L] steps on \the [src].</span>",
Буду знать

2024-03-31 21:24 UTC, Devyashka commented on code/game/objects/items/weapons/potato.dm
> +/obj/item/potato/Crossed(AM as mob|obj)
Буду знать

2024-03-31 21:26 UTC, Devyashka commented on code/modules/admin/verbs/adminjump.dm
> +	for(var/mob/M in GLOB.player_list)
Ну так в этом и смысл..

2024-03-31 21:27 UTC, Devyashka commented on code/modules/awaymissions/corpse.dm
> +	if (bullet)
Буду знать

2024-03-31 21:27 UTC, Filatelele commented on code/game/objects/items/weapons/potato.dm
> +/obj/item/potato/attack_self(mob/user as mob)
В примерах которые тут есть - да, учитывая что эти примеры скорее всего уже просроченные, сгнившие, и разложившиеся на плесень и липовый мед. Читайте гайд по контрибутингу.

2024-03-31 21:28 UTC, Devyashka commented on code/modules/awaymissions/corpse.dm
> +	M.dir = rand(1, 4) * 2
Буду знать

2024-03-31 21:28 UTC, Filatelele commented on code/datums/helper_datums/teleport.dm
> +	var/new_z = M.z > 2 ? M.z - 2 : M.z + 2
GLOB.using_map.get_levels_with_trait(ZTRAIT_CENTCOM)

Вот намек

2024-03-31 21:37 UTC, Devyashka commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	var/obj/item/stack/medical/advanced/ointment/O = new /obj/item/stack/medical/advanced/ointment(src)
Это буквально код борга выше. Мне копипастнуть нужный кусок кода с паком модулей, а потом пересобирать строки, чтобы было красивее?

2024-03-31 21:39 UTC, Devyashka commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	src.modules += new /obj/item/crowbar(src)
Да, это просто копипаста существующего кода.
Я просто беру и копирую кусок кода, который мне нужен.
Если этот код неправильный, то и замечание должно быть таким:
убрать ненужный src. и тут и в оригинале, чтобы никто больше не плодил эту ошибку

2024-03-31 21:45 UTC, Filatelele commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	src.modules += new /obj/item/crowbar(src)
У нас действительно ничего не написано про https://ru.wikipedia.org/wiki/Программирование_методом_копирования-вставки

Воистину очевидностей не существует и надо прописывать даже такое.

Копипастить код НЕ НАДО!

2024-03-31 21:48 UTC, Devyashka commented on code/modules/mob/living/simple_animal/hostile/event_mob.dm
> +	var/list/wizardy_spells = list(/datum/spell/toggled/transform, /datum/spell/toggled/thermal, /datum/spell/toggled/sting_paralize)
Глобальным листом?
У моба визарда это реализовано так, зачем выносить конкретные спеллы для конкретного моба в какой-то глобальный список?

2024-03-31 21:51 UTC, Devyashka commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
Назначает объекту его индивидуальный номер согласно текущему тику раунда. Таким образом у каждого заспавненого объекта педалью будет разный номер.

2024-03-31 21:52 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
А если в один тик заспавнятся два таких объекта? Все пиздец приехали?
Есть гораздо более безопасные способы получить индивидуальный номер, например - \ref

2024-03-31 21:54 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
Плюс нейминг переменной неочевидный. 

И на будущее - мы над дефайном переменной через тройной слэш (///) пишем комментарий, который ВСкод автоматически цепляет и показывает если навестись на переменную.

2024-03-31 21:59 UTC, Devyashka commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	..()
Была более сложная реализация с разными видами меток.
Разные виды сократились до одного, а это осталось как рудимент

баг

2024-03-31 22:09 UTC, Devyashka commented on code/modules/power/lighting.dm
> +		if(T.z == 3 || T.z == 4)
Могу спросить как именно считается нормальным?

2024-03-31 22:10 UTC, Devyashka commented on code/modules/spells/targeted/heal_slug.dm
> +		if(do_after(user, 50, H))
Буду знать

2024-03-31 22:11 UTC, Filatelele commented on code/modules/power/lighting.dm
> +		if(T.z == 3 || T.z == 4)
Короче в дефайнах карты у нас есть такая штука как

/datum/space_level

Мы делаем новый трейт условно ZTRAIT_FUTURE_EXODUS

И делаем проверку формата ``if(T.z in GLOB.using_map.get_levels_with_trait(ZTRAIT_FUTURE_EXODUS)``

2024-03-31 22:14 UTC, Devyashka commented on code/modules/spells/targeted/pumping_out_blood.dm
> +			to_chat(user, "<span class='warning'>That was not so bright of you.</span>")
А почему мне надо считать верхнее нормальным, а нижнее тупым копипастом? А вдруг наоборот? А вдруг оба правильно?
А как мне разобраться? Выискивать ПР, с комментарием на тему того как вы решили делать?

2024-03-31 22:14 UTC, Devyashka commented on code/game/machinery/doors/firedoor.dm
> +	density = 1
На вики 1

2024-03-31 22:15 UTC, Devyashka commented on code/game/machinery/doors/firedoor.dm
> +	opacity = 1
На вики 1

2024-03-31 22:20 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	mana_current = mana_max
Потому что после спавна моба шёл откат спелла.
Методом тыка за анимацию отката спелла отвечает charge_counter
Это тут не нужно

2024-03-31 22:20 UTC, Filatelele commented on code/game/machinery/doors/firedoor.dm
> +	density = 1
На какой вики? 
Это булевые переменные...

2024-03-31 22:20 UTC, Filatelele commented on code/game/machinery/doors/firedoor.dm
> +	opacity = 1
Это булевые переменные...

2024-03-31 22:20 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	charge_counter = mana_max
Спелл нет, а анимация отката да

2024-03-31 22:21 UTC, Filatelele commented on code/game/machinery/doors/firedoor.dm
> +	opacity = 1
Если скинешь ссылку где оно на вики так - будет круто, исправлю

2024-03-31 22:21 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +/datum/spell/toggled/sting_paralize/check_charge(skipcharge, mob/user)
Соглашусь

2024-03-31 22:22 UTC, Filatelele commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	var/obj/item/stack/medical/advanced/ointment/O = new /obj/item/stack/medical/advanced/ointment(src)
Нет, нужно не копипастить нужный кусок кода, а писать самому.

2024-03-31 22:23 UTC, Filatelele commented on code/modules/spells/targeted/pumping_out_blood.dm
> +			to_chat(user, "<span class='warning'>That was not so bright of you.</span>")
А как тебе разобраться? Открыть guide to contributing...

2024-03-31 22:23 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	mana_current = mana_max
Этот спелл вообще не предназначен для использования с анимацией отката, боже...

2024-03-31 22:23 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
Потому что в родителе mana_drain_per_tick = FALSE всегда. И из-за той проверки мы всегда проваливались в return

2024-03-31 22:24 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
Думатель должен запускаться после деактивации, чтобы отсчитывать откат спелла до следующего использования

2024-03-31 22:26 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
Ещё один? Он всего тут один

2024-03-31 22:26 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
Что значит в родителе эта переменная = FALSE всегда?
Если ты ее изменишь в своем классе то все будет работать.

Вывод - ты не понимаешь основы ООП, советую попробовать начать с нуля, писать небольшие проекты. Причем писать их вдумчиво, разбираясь что, зачем и для чего. А не бездумно копировать чужой код до тех пор, пока не заработает. Последнее, конечно, тоже работает - но это тупиковый путь, ведущий в никуда.

2024-03-31 22:27 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +		return
Да, если деактивация провалилась, то ретёрн. Остальная часть кода не выполняется.
А дальше и нет кода, поэтому рудимент на удаление

2024-03-31 22:27 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
А что, вызов родителя не считается?

2024-03-31 22:28 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
Ну и опять же ты не разобрался как работает /toggled/ спелл. Он вообще не перестает думать никогда)
У него одна точка входа в думанье - New(), если есть mana_drain_per_tick

2024-03-31 22:29 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
Из-за того что в родителе всегда mana_drain_per_tick = FALSE, родитель мне будет отключать абилку.
А у меня должна быть mana_drain_per_tick = FALSE, потому что включённая абилка не должна тратить ману.

2024-03-31 22:29 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/event_mob.dm
> +	var/list/wizardy_spells = list(/datum/spell/toggled/transform, /datum/spell/toggled/thermal, /datum/spell/toggled/sting_paralize)
Как минимум var/list/global 
Для экономии памяти. Зачем нам на каждого моба создавать свой лист, если можно сделать его общим для всех экземпляров данного класса?

2024-03-31 22:29 UTC, Devyashka commented on code/modules/spells/toggled/thermal.dm
> +/datum/spell/toggled/thermal/New()
New() в родителе запускает think. Мне он не нужен при создании. Поэтому пусто

2024-03-31 22:30 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +		return
Return куда? Return чего? 
У тебя дальше нет никакого кода и ретурн ничего не возвращает.

2024-03-31 22:32 UTC, Filatelele commented on code/modules/spells/toggled/thermal.dm
> +/datum/spell/toggled/thermal/New()
Это НЕ нормально. Мы не можем такое проворачивать с New(), это инициализация объекта. 

То есть если у родителя родителя будет какой-то важный код, то он просто не запустится. Bruh.

2024-03-31 22:35 UTC, Devyashka commented on code/modules/spells/toggled/thermal.dm
> +	if(!..())
А я сейчас не понимаю как он работает, если родитель всегда вернёт FALSE, потому что mana_drain_per_tick = FALSE...

2024-03-31 22:36 UTC, Devyashka commented on code/modules/spells/toggled/transform.dm
> +	charge_counter = mana_max
charge_counter нужен чтобы не делать откат спелла при спавне моба. Он используется для отображения в UI

2024-03-31 22:39 UTC, Filatelele commented on code/modules/spells/toggled/thermal.dm
> +	if(!..())
var/mana_drain_per_tick ничего не возвращает, это - переменная, если ты об этом.

Родитель же вернет тру, вот его код. 

```
	if(mana_drain_per_tick && (mana_current - mana_drain_per_tick <= 0))
		toggled = FALSE
		return FALSE
	if(text_activate)
		to_chat(holder, SPAN("notice", text_activate))
	return TRUE```

2024-03-31 22:40 UTC, Devyashka commented on code/modules/mob/living/silicon/robot/preset.dm
> +	var/list/wizardy_spells = list(/datum/spell/targeted/say/standart_medbot, /datum/spell/targeted/say/target_medbot, /datum/spell/targeted/say/after_heal_medbot, /datum/spell/targeted/say/dead_pacient
У пауков есть спеллы с ячейками в UI?
Крутые. Изучу как они устроены

2024-03-31 22:45 UTC, Devyashka commented on code/modules/mob/living/simple_animal/hostile/event_mob.dm
> +	var/list/wizardy_spells = list(/datum/spell/toggled/transform, /datum/spell/toggled/thermal, /datum/spell/toggled/sting_paralize)
Это и правда полезно. Не приходилось задумываться, что каждый экземпляр объекта хранит в себе все переменные, а не тупо обращается к оригинальному объекту в коде.

Хотя можно было и догадаться, так как каждому экземпляру индивидуально можно изменить через VV переменную.

2024-03-31 22:51 UTC, Devyashka commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
Дело в том что индивидуальный номер должен быть по возрастанию.
ref - это огромная текстовая строка, которую нужно сравнивать.
А тик - это максимум пятизначное число за 2 часа игры, которое сравнить удобно.

Ну будет такое чудо, что админ создаст два target_hunt одновременно в разных частях экрана.
Моб тот что первый увидит, к тому и побежит, вероятнее всего к тому, кто ближе к 0:0 координатам. Не сильно критично, думаю

2024-03-31 22:51 UTC, Devyashka commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
Нейминг да, комментарий буду знать

2024-03-31 22:52 UTC, Devyashka commented on code/modules/power/lighting.dm
> +		if(T.z == 3 || T.z == 4)
Спасибо, буду знать

2024-03-31 22:55 UTC, Filatelele commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	number_target = world.time
Чего? Ты вручную что ли эту переменную сравниваешь? 

Я уже написал что world.time не является ни адекватным, ни безопасным "уникальным" идентификатором объекта. 

Надо писать безопасный код чтобы не выстрелить себе в колено потом.

2024-03-31 23:02 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
Я понимаю ООП и третий раз соглашусь, что нужно было просто сделать новый подвид спелла.
Здесь ошибка заключается в том что я сначала делаю спелл на базе существующего, а потом костылями пытаюсь, исправить "баги". И мне следовало изначально понять что я хочу от своего спелла и как именно работает этот.

Этот умеет вкл/выкл? Он мне подошёл и потому был исковеркан.

2024-03-31 23:04 UTC, Filatelele commented on code/modules/spells/toggled/sting_paralize.dm
> +	if(mana_current < mana_max)
Ну и зачем мне ревьювать код было если ты "понимаешь ООП"?)

"Понимай" дальше.

2024-03-31 23:04 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +	set_next_think(world.time + 1 SECOND)
Так вызова родителя нет
New() пустой. В этом и смысл, чтобы думанье включалось только при отключении

2024-03-31 23:05 UTC, Devyashka commented on code/modules/spells/toggled/sting_paralize.dm
> +		return
поэтому рудимент)

2024-04-01 05:41 UTC, closed without merging