refact(clothing): makes accessories lazy
ChaoticOnyx/OnyxBay pull request #12089
Opened 2024-04-03 21:38 UTC by Filatelele

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-04-03 21:44 UTC, TobyThorne approved these changes, later dismissed

2024-04-04 06:20 UTC, intercepti0n requested changes

2024-04-04 06:20 UTC, intercepti0n commented on code/modules/clothing/clothing.dm
> +		if(LAZYLEN(accessories) > ties.len)
Захвати сразу еще и галстуки, они, к слову, в недавних рантаймах вылезали из-за `.len`.

2024-04-04 06:20 UTC, intercepti0n commented on code/modules/clothing/clothing_accessories.dm
> +	if(LAZYLEN(accessories) && restricted_accessory_slots && (A.slot in restricted_accessory_slots))
Чуть правее переведи `restricted_accessory_slots` на `LAZYISIN`.

2024-04-04 09:33 UTC, Filatelele commented on code/modules/clothing/clothing.dm
> +		if(LAZYLEN(accessories) > ties.len)
Done!

2024-04-04 09:35 UTC, Filatelele commented on code/modules/clothing/clothing_accessories.dm
> +	if(LAZYLEN(accessories) && restricted_accessory_slots && (A.slot in restricted_accessory_slots))
Done!

2024-04-04 11:26 UTC, igorsaux approved these changes

2024-04-04 11:29 UTC, intercepti0n approved these changes

2024-04-04 11:29 UTC, merged