bwoink
ChaoticOnyx/OnyxBay pull request #12124
Opened 2024-04-05 21:03 UTC by TobyThorne

![image](https://github.com/ChaoticOnyx/OnyxBay/assets/45202681/146783b8-5a81-4d34-9fdd-c44e90b26b5a)

```yml
🆑
rscadd: В лодаут добавлены значки. Пока что в наличии значок НТ, свинной значок и значок с черепом для эджи боев. И ещё парочка. Список ещё будет пополняться.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-04-05 21:07 UTC, igorsaux approved these changes, later dismissed

2024-04-05 21:09 UTC, intercepti0n submitted a review, later dismissed

2024-04-05 21:12 UTC, Zert0X approved these changes
Прайд пины, православная версия

2024-04-05 21:13 UTC, Zert0X commented
```
        prides["rainbow pin"]           = /obj/item/clothing/accessory/pin/rainbow
	prides["bisexual pride pin"]    = /obj/item/clothing/accessory/pin/bi
	prides["pansexual pride pin"]   = /obj/item/clothing/accessory/pin/pan
	prides["asexual pride pin"]     = /obj/item/clothing/accessory/pin/ace
	prides["non-binary pride pin"]  = /obj/item/clothing/accessory/pin/enby
	prides["transgender pride pin"] = /obj/item/clothing/accessory/pin/trans
	prides["intersex pride pin"]    = /obj/item/clothing/accessory/pin/intersex
	prides["lesbian pride pin"]     = /obj/item/clothing/accessory/pin/lesbian
```
:trollface:

2024-04-05 21:15 UTC, Zert0X requested changes, later dismissed

2024-04-05 21:15 UTC, Zert0X commented on code/modules/clothing/under/accessories/pins.dm
> +	icon_state = "pride_bi"
```suggestion
	icon_state = "skull"
```

2024-04-05 21:15 UTC, Zert0X commented on code/modules/clothing/under/accessories/pins.dm
> +	icon_state = "pride_bi"
```suggestion
	icon_state = "pig"
```

2024-04-06 10:16 UTC, intercepti0n commented on code/modules/client/preference_setup/loadout/lists/accessories.dm
> +/datum/gear/accessory/pride_pin/New()
```suggestion
/datum/gear/accessory/pin/New()
```

Вроде так надо, иначе лодаут сдохнет.

2024-04-06 11:51 UTC, intercepti0n submitted a review, later dismissed

2024-04-06 12:14 UTC, igorsaux approved these changes

2024-04-06 18:07 UTC, intercepti0n approved these changes

2024-04-08 17:21 UTC, merged