Добавления макроса для создания полов
ChaoticOnyx/OnyxBay pull request #12155
Opened 2024-04-09 10:47 UTC by kreeperHLC

Добавления макроса для создания полов. Вместо 4 строк в 4 файлах можно прописать всё в 1.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-04-09 10:49 UTC, intercepti0n requested changes

2024-04-09 10:49 UTC, intercepti0n commented on code/_macros.dm
> +/**
Выноси в отдельный файл, помойку в файле макросов надо разгребать, а не усугублять.

2024-04-09 10:56 UTC, kreeperHLC commented on code/_macros.dm
> +/**
Вынес, хз, может локу сменить надо будет

2024-04-09 11:05 UTC, intercepti0n commented
Этот файл должен уехать в папку `__defines`, ему нет места в директории для абстрактных макросов.

2024-04-15 15:48 UTC, intercepti0n requested changes
Для мержа данного проекта требуется получить разрешение от следующих контрибуторов GoonStation:

- [ ] Adharainspace
- [ ] ZeWaka
- [ ] pali6
- [ ] Sovexe
- [ ] MarkNais
- [ ] PrimeNumb
- [ ] moonlol

2024-04-18 15:51 UTC, Filatelele commented
Просто нет.

2024-04-18 15:51 UTC, closed without merging