fix(firedoor): opening for mecha
ChaoticOnyx/OnyxBay pull request #12439
Opened 2024-05-15 14:32 UTC by BaraBarax

Уэээм... Сделал для открытия-закрытия отдельный прок для файрдур, теперь мехи могут их открывать

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Мехи научились открывать аварийные створки
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал(-а) все свои изменения и багов в них не нашёл(-ла).
- [ ] Я запускал(-а) сервер со своими изменениями локально и все протестировал(-а).
- [x] Я ознакомился(-ась) c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-05-15 14:34 UTC, intercepti0n commented
Не все галочки проставил, не мержим.

2024-05-15 14:35 UTC, BaraBarax commented
Ладно, на самом деле я тестил

2024-05-15 14:43 UTC, BaraBarax commented
Я пиздабол, увы.

2024-05-15 14:44 UTC, intercepti0n requested changes
Автор идёт тестировать свой код...

2024-05-16 12:19 UTC, Filatelele approved these changes
Вроде бы да

2024-05-16 12:22 UTC, TobyThorne approved these changes
ревертнуть и обложить опа хуями всегда успеем

2024-05-16 12:38 UTC, intercepti0n approved these changes

2024-05-16 12:40 UTC, merged