fix(advtool): removing necessary parents
ChaoticOnyx/OnyxBay pull request #12858
Opened 2024-09-28 19:39 UTC by BaraBarax

Создавать целый отдельный подтип инструментов ради одного крутого мультитула это конечно круто, но почему бы просто не засунуть его в сыновья обычного для меньшей мозгоёбки?

close #12856
close #12044

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
bugfix: Продвинутый мультитул теперь может взаимодействовать с телекоммами.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал(-а) все свои изменения и багов в них не нашёл(-ла).
- [x] Я запускал(-а) сервер со своими изменениями локально и все протестировал(-а).
- [x] Я ознакомился(-ась) c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-09-28 20:24 UTC, TobyThorne requested changes
ОП не осилил факт, что смысл тула - в переключении между мультитулом, отвёрткой и кусачками.

2024-09-28 20:30 UTC, BaraBarax commented
А он потерял эту возможность? Он в первую очередь мультитул в хуйня для тыканья в проводки, к которому приделали отвёртку и кусачки

2024-09-28 20:40 UTC, Filatelele commented
Честно? Проблема не в коде адвтула. И решаться должна не так.

```
/obj/machinery/telecomms/attack_hand(mob/user)

	if(stat & (BROKEN|NOPOWER))
		return TRUE

	var/obj/item/device/multitool/P = get_multitool(user)

	if(!P)
		return TRUE

```


```// TO-DO: find a better place for this proc.
/proc/get_multitool(mob/user)
	var/obj/item/device/multitool/MT = null
	if(!issilicon(user))
		if(isMultitool(user.get_active_hand()))
			MT = user.get_active_hand()
	else if(isAI(user))
		var/mob/living/silicon/ai/AI = user
		MT = AI.aiMulti
	else if(isrobot(user))
		if(isMultitool(user.get_active_hand()))
			MT = user.get_active_hand()
	return MT
```

Здесь нахуй что-то не то, потому что ``get_multitool()`` возвращает *любой* айтем у которого тул бихейвиор == TOOL_MULTITOOL

Но только device/multitool умеет в get_buffer() и аналогичное

И адекватным решением будет перевод поведения мультитула на компонент, что во-первых позволяет делать ну совсем продвинутую ржаку типа бесконтактных мультитулов, а во вторых - уменьшает количество говна в кодбазе.

2024-09-28 20:44 UTC, BaraBarax commented
Ну я рвать жопу ради того чтобы тыкнуть более крутым мультитулом в телекоммы не собираюсь (может быть, когда-нибудь, наверно, возможно займусь этим потом), ну и если по этой причине ПР не принимается, то я его закрываю просто

2024-09-28 20:49 UTC, Filatelele requested changes

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	if(!src.contents.len)
```suggestion
	if(!contents.len)
```

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	..()
Мы не вызываем родителя у ```on_update_icon()```

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	return
Тут не нужен ``return``, мы ничего не возвращаем.

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	return
здесь не нужен ``return``

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	var/choice = input(user, "What would you like to remove from the [src]?") as null|anything in src.contents
Заменить input() на tgui_input, мы в 2024, а не в 2012.

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	if(!choice || !(choice in src.contents))
```src.``` убрать здесь и далее. Дальше отмечать не буду, сам пробегись.

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +	return
Я хз мы ничего тут не возвращаем зачем тут ретурн, редундант, убрать.

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +			contents += SD
Не обязательно делать. Если ты вызываешь user.drop(SD, src), то SD, очевидно, окажется в контентсах src (анлесс drop() не сломается)

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +			screwdriver = SD
Не обязательно. На будущее. Есть крутое решение, чтобы не ебаться с присвоением переменных когда чет дропаешь в атом. 

Переопределяешь Entered() и когда чет попадает внутрь - смотришь по изтайпу и присваиваешь в нужную переменную. Аналогично с Exited() - обнуляешь ссылки.

Позволяет держать логику присвоения ссылок на хуйню в атоме в одном месте, а значит - меньше шансов проебаться где-то. В кофеварке емнип такая штука у меня, если интересно - посмотри.

2024-09-28 20:49 UTC, Filatelele commented on code/game/objects/items/devices/multitool.dm
> +			contents += WC
сэйм щит как и предыдущее, не надо в контентсы добавлять ручками.

2024-09-28 20:51 UTC, Filatelele commented
А нахуя я ревью делал если автор все закрыл? 
Сука.

2024-09-28 20:52 UTC, BaraBarax commented
Уэээ, ну я подумал что если все молчат то так и будет

2024-09-28 20:59 UTC, Filatelele commented
> Уэээ, ну я подумал что если все молчат то так и будет

Ну решение очевидно субоптимальное но я хз того рот ебал 
Пусть Игорь решает мне впадлу думать ревув кода я дал
Но компонент с сигналами это сто строк кода не более

2025-03-28 09:36 UTC, FelixArzt commented
Протухает = закрываем.

2025-03-28 09:36 UTC, closed without merging