feat(bureaucracy): new trade licence and new opportunities
ChaoticOnyx/OnyxBay pull request #12852
Opened 2024-09-25 16:14 UTC by i1yadobr

<details>
<summary>Чейнджлог</summary>

```yml
🆑ilyadobr
rscadd: Добавлены печати: Торгового объединения, Торгового отдела Нанотрейзен.
rscadd: Теперь с помощью [station] можно обозначать текущую станцию в документации/записях.
tweak: Лицензия торговца обновилась, теперь меньше шанс получить просроченную лицензию, немного увеличен шанс на редкие категории разрешённых товаров.
tweak: Большинство того, что связано с бюрократией, получило спрайты в руке космонавтиков.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал(-а) все свои изменения и багов в них не нашёл(-ла).
- [x] Я запускал(-а) сервер со своими изменениями локально и все протестировал(-а).
- [x] Я ознакомился(-ась) c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2024-09-25 19:50 UTC, Zert0X requested changes

2024-09-25 19:50 UTC, Zert0X commented on code/modules/paperwork/misc.dm
> +	var/date = list("day" = rand(1,30), "month" = rand(1,12), "year" = rand(2564,2566), "dur" = rand(3,5))
Предлагаю немного по другому.
Пойди посмотри как мы получаем текущую дату и делай рандом
Текущий год -2, текущий год +1

2024-09-25 19:50 UTC, Zert0X commented on code/modules/paperwork/misc.dm
> +	"Взрывчатые или сильногорючие вещества, гранаты, в том числе нестандартного действия" = 1)
А НЕ ЖИРНО ЛИ?

2024-09-25 20:02 UTC, Filatelele commented on code/modules/paperwork/misc.dm
> +	"Взрывчатые или сильногорючие вещества, гранаты, в том числе нестандартного действия" = 1)
На торговца и так всем поебать чуть более чем полностью
Ну дай мальчик порадует себя хз

2024-09-25 20:03 UTC, Filatelele commented on code/modules/paperwork/misc.dm
> +	"Взрывчатые или сильногорючие вещества, гранаты, в том числе нестандартного действия" = 1)
Эта лицензия что совой об пень что пнем об сову
Все равно никому нахуй не нужен торговец увы

2024-09-26 04:15 UTC, i1yadobr commented on code/modules/paperwork/misc.dm
> +	"Взрывчатые или сильногорючие вещества, гранаты, в том числе нестандартного действия" = 1)
Я очень много времени наиграл на мерчантах, чтобы с уверенностью сказать что ни в одном раунде я не видел, чтобы эти три категории находились в списке доступных для продажи вещей. Так свет хотя бы сможет увидеть их, надеюсь.

2024-09-26 07:11 UTC, i1yadobr commented on code/modules/paperwork/misc.dm
> +	var/date = list("day" = rand(1,30), "month" = rand(1,12), "year" = rand(2564,2566), "dur" = rand(3,5))
Если добавить +1 год, у нас получиться документ из будущего. Я немного сделал по-другому.

2024-09-27 19:42 UTC, Zert0X approved these changes, later dismissed

2024-10-06 08:34 UTC, i1yadobr commented
@igorsaux Можно замёржить данный ПР, пожалуйста?
Две недели ПРу, возражений/дополнений вроде как никто не имеет.

2024-10-06 10:52 UTC, merged