ai_hud(icons): Hud for ai
ChaoticOnyx/OnyxBay pull request #1555
Opened 2020-02-21 12:02 UTC by kreeperHLC

Добавлен Худ для ИИ. В будущем (как мне кто-то наспрайтит иконки) будет дополнен.
https://cdn.discordapp.com/attachments/334426757673385984/680079959510745151/unknown.png

2020-02-21 12:08 UTC, TermService requested changes

2020-02-21 12:08 UTC, TermService commented on code/_onclick/hud/ai.dm
> +	src.adding = list()
зачем src.?

2020-02-21 12:08 UTC, TermService commented on code/_onclick/hud/ai.dm
> +	src.adding += using
тут тоже

2020-02-21 12:08 UTC, TermService commented on code/_onclick/hud/ai.dm
> +	mymob.client.screen += src.adding + src.other
выше все src не нужны и тут тоже

2020-02-21 12:08 UTC, TermService commented on code/_onclick/hud/screen_objects.dm
> +				usr:view_core()
надо приводить к типу, : не используем

2020-02-21 12:08 UTC, TermService commented on code/_onclick/hud/screen_objects.dm
> +				usr:view_core()
usr лучше не использовать.... Понимаю выше также, но лучше везде убрать как и :

2020-02-21 12:08 UTC, TermService commented on code/_onclick/hud/screen_objects.dm
> +				usr:ai_goto_location(cam_loc)
привел к типу и всё равно используешь usr:

2020-02-21 12:09 UTC, TermService commented
@TapKo4eB

2020-02-21 18:08 UTC, TapKo4eB commented
- [ ] Я не уверен что список камер должен быть настолько короток, что в нём есть только список коридоров.
 ![image](https://user-images.githubusercontent.com/48761132/75058733-99594180-54ec-11ea-9026-d8675410ce5f.png)
- [ ] Медхуд не работает.
![image](https://user-images.githubusercontent.com/48761132/75058870-e4735480-54ec-11ea-875d-cd685606f921.png)

2020-02-24 05:44 UTC, Epicus7 commented
Какие иконки нужны то? Надо бы записать отдельным иссуем.

close #1138

2020-02-25 14:50 UTC, kreeperHLC commented
Всё вроде исправил. Заодно исправил и в других файлах.

2020-02-25 14:52 UTC, TapKo4eB commented
надеюсь успею затестить later

2020-02-25 15:51 UTC, TermService approved these changes
Код стал короче и чище, ставлю класс

2020-02-26 14:12 UTC, TapKo4eB commented
починил кнопочку как она должна работать

2020-02-26 14:12 UTC, TapKo4eB commented
а мля не надо ещё это убрать
![image](https://user-images.githubusercontent.com/48761132/75352667-2ddfed00-58bb-11ea-9ae5-d09a384b64b4.png)

2020-02-26 14:19 UTC, TapKo4eB commented
хатофа

2020-02-26 16:30 UTC, quardbreak requested changes

2020-02-26 16:30 UTC, quardbreak commented on code/_onclick/hud/ai.dm
> +	adding += using
Дубликат

2020-02-28 05:54 UTC, Epicus7 approved these changes
Вроде норм, ток по мелочам вопросы есть.

2020-02-28 05:54 UTC, Epicus7 commented on code/_onclick/hud/robot.dm
> +	if(!isrobot(mymob))
Тут лучше ASSERT поставить, так как если эта проверка не пройдет, то это очевидный баг.

Тут же не должно быть не робота, правильно? ASSERT тогда крашнет с рантаймом и мы сможем потом пофиксить.

2020-02-28 05:54 UTC, Epicus7 commented on code/_onclick/hud/screen_objects.dm
> +			if(isAI(usr))
Вот все такие проверки лучше делать через ASSERT, имхо. Да, увидел, что так оно было до тебя, но я думаю лучше исправить.

Заодно можно будет запустить на локалке и чекнуть логи рантаймов. Если в них ничего нового не появится - значит все круто :)

А если появится - значит твой интерфейс ИИшный почему-то есть еще у какой-то хуйни, которая не ИИ.

2020-02-28 05:54 UTC, Epicus7 commented on code/modules/paperwork/silicon_photography.dm
> +/obj/item/device/camera/siliconcam/ai_camera/proc/take_image()
В этом проке usr используется, не уверен что это норм. Спросил в дискорде.

2020-03-07 20:33 UTC, TermService commented
@Epicus7 чего ждём

2020-03-12 14:25 UTC, Epicus7 commented
@TermService, ждем реакцию @kreeperHLC на комментарии, конечно же.

2020-05-22 18:13 UTC, TapKo4eB commented
закрываю ибо сделано

2020-05-22 18:13 UTC, closed without merging