Лицензия торговцам
ChaoticOnyx/OnyxBay pull request #165
Opened 2018-09-02 04:58 UTC by Epicus7

Добавил новый класс бумаг, которые при создании берут свой контент из .html файлов.

Техническая часть:

Возникла проблема с отображением html в бумагах. В обычном браузере он ведет себя довольно странно - два переноса строки превращается в один <br>, а один перенос строки игнорируется. Последовательность "\r\n\r\n" Бьонд категорически принимать отказался, так что я зафорсил в папке с описанием документов LF-стиль для окончаний, чтобы в конце строк всегда были \n вместо \r\n.

Ну не знаю. В принципе, работает. Можно было бы регексы воткнуть, но чет не очень хочется.

Дизайн:

Лицензия выглядит так:
![image](https://user-images.githubusercontent.com/5204667/44952334-9fd1a480-ae85-11e8-8743-2369be532095.png)

Видимо, я еще добавлю рандомную генерацию для различных полей лицензии (имя, дата, срок, компания, категории товаров, список станций и кораблей, которые можно посещать).

Категории товаров надо бы продумать, не знаю какие стоит выделить.

issue #46

2018-09-02 05:00 UTC, Epicus7 commented
ПР пока чисто для обсуждения, принимать не надо - лицензия выглядит уныленько.

2018-09-04 15:41 UTC, Cinericius commented
Какие надо рандомизированные поля:
1) Большая солидная печать НаноТрейзен (нарисую в нескольких вариантах, соответственно правильным в каждом конкретном раунде будет только 1) 
2) Название выдававшего отделения (варианты для рандомизации: NanoTrasen Supply Department; NanoTrasen Trading Department; NanoTrasen External Affairs Department; NanoTrasen Trading Affairs Department; NanoTrasen External Trading Department; NanoTrasen Supply Affairs Department).
3) Код выдававшего отделения, тупа набор циферок и дефисов, чот типа 8-800-5553535.
4) Имя выдававшего (генерится штук 10 "правильных" обычным генератором имен, типа работники департамента).
5) Дата и срок. Тут все понятно и просто, но надо не забыть про ограничения на рандом и ошибки. Ну, чтобы это все выглядело осмысленно. 
6) Название торговой организации. (варианты для рандома: Salis & Mercury Trading Company; Milky Way Trade Union; Ben-Perzman Tradeband; SteelGoose Supplies)
7) Код торговой организации в классификаторе NanoTrasen. Еще тоже номер с дефисами, но мб покороче, типа 13-66613.
8) Корабли и станции, которые можно посещать. Помимо обязательно присутствующего в неподдельной лицензии NSS Exodus, могут быть следующие рандомные варианты (взято с вики, из старой статьи про NanoTrasen, с правками): NSV Caduceus, NSV Luna, NTV Sierra Otago, NTV Millenium, NTV Duke, NTV Verum, NHV Savior, NSV Preserver, NSS Avalon, NSS Orion, NSS Ontigo, NSS Redemption, NSS Zagreus).
9) Категории товаров. Тут ошибок быть не может, но есть начальная рандомгенерация. Собственно, разные категории последовательно добавляются в лицензию с разной вероятностью:
p=1  (эти категории точно есть в лицензии):
*Продовольствие.
*Предметы одежды.
*Сырье и материалы.
p=0.9
*Медикаменты.
*Личные вещи и аксессуары, разрешенные внутренним законодательством NanoTrasen.
p=0.75
*Инженерное оборудование для работы в пределах станции.
*Медицинское оборудование для работы в пределах станции.
*Исследовательское оборудование.
p=0.5
*Скафандры и иное оборудование, предназначенное для проведения работ в открытом космосе.
*Антиквариат.
*Домашние питомцы, лабораторные животные и иные инопланетные организмы.
p=0.05
*Мелкокалиберное огнестрельное или слабое энергетическое оружие.
p=0.001 (эти категории почти никогда не попадают в лицензию)
*Крупнокалиберное огнестрельное или мощное энергетическое оружие.
*Взрывчатые или сильногорючие вещества, гранаты, в том числе нестандартного действия.
10) Прямоугольная печать NanoTrasen. Будет 2-3 варианта.
11) Прямоугольная печать торговой организации. Будет 2-3 варианта на каждую организацию.

Механизм генерации:
1) Генерится "правильный" набор вариантов, кодов, печатей.
2) Правильные параметры (какие департаменты существуют и могут выдавать торговые лицензии, какие у них номера и кто в них работает, какие печати есть у НТ и т.д.) генерятся и помещаются в консольку/ПДА/мозг АВД.
3) Генерится торговая лицензия с правильным набором всего.
4) Кидается прок на фальшивость лицензии (что-нибудь порядка 15%)
5) Кидается прок, определяющий в какой строчке будет ошибка.
6) В строчку вносится ошибка (повнимательнее с датой и сроком, да).
7) Кидается еще один прок, который с вероятностью 5% внесет еще одну ошибку.
8) Повторяются пункты 4-5.
9) Торговец, если он есть, получает предупреждение жирными буквами, что его деятельность на КСН "Исход" не очень законна и он может получить пизды (возможно, стоит конкретно указывать причину, типа истекший срок, отсутствие Исхода в списке разрешенных для посещения объектов, поддельные данные и т.д.).
10) ?????
11) ПРОФИТ

2018-09-04 16:34 UTC, Epicus7 commented
В рамках этого ПРа сделаю параметры и нормальную генерацию валидной лицензии. Ошибки потом другим ПРом вносить будем, а то много всего.

Ты главное печати нарисуй, пока я поля эти генерирую, да. А то получается мы ПР не закроем этот без них.

2018-09-04 17:53 UTC, Cinericius commented
Печати в процессе.
Прямоугольные будут 32х64, большая будет 96х96 наверное.

2018-09-04 17:53 UTC, Cinericius commented
Да, они будут сильно пиксельные, шоб не выбиваться из стиля.

2018-09-04 21:02 UTC, Cinericius commented
Вкинул спрайтики в дискорд и запинил их в контрибутерке.

2018-09-18 13:50 UTC, Cinericius commented
Бамп.

2018-11-06 02:29 UTC, BlakeCrazy commented
че, сделали?

2018-12-20 20:13 UTC, ZerlGray commented
Сколько лет оно будет лежать?

2018-12-20 21:42 UTC, PlinHost commented
Пока Эпикус не вернется, очевидно.

2018-12-20 21:44 UTC, blakecrazy13 commented
пусть лежит, я так сказать, продолжу дело Эпикуса...

2019-02-19 21:38 UTC, Cinericius commented
@BlakeCrazy если ты жив и легитимный президент, то давай я вышлю тебе dmiшки с печатями и айтемом лицензии.

2019-06-14 08:43 UTC, ZerlGray commented
Ну все, пизда билду.

2019-06-14 10:47 UTC, Cinericius commented
На швятое покусились

2019-06-14 10:50 UTC, Epicus7 commented
Ушла эпоха

2019-06-14 11:03 UTC, Vmihey commented
Бранчу не выкидываю, коммиты потом оттуда вытянем.

2019-12-31 06:16 UTC, vekotov commented
^ труп выше

2020-01-09 04:45 UTC, vekotov commented
Точно билд загнётся теперь

2020-01-09 06:19 UTC, Cinericius commented
Кощунство

2020-01-09 19:09 UTC, Cinericius commented
На работу!

2020-05-05 01:26 UTC, Cinericius commented
К О Г Д А ?
О
Г
Д
А
?

2020-08-28 14:34 UTC, jammer312 requested changes

2020-08-28 14:34 UTC, jammer312 commented on code/modules/paperwork/paper_fromhtml.dm
> +	info = russian_to_utf8(file2text(html_path), prepare_to_browser = TRUE)
Мне не нравится, что оно забивает на предыдущие реализации New() и то, что оно не пользует info_links (а оно показывается, если прожать по бумаге ручкой).

2020-08-28 14:38 UTC, jammer312 commented
Когда (если) вмержат #3257, можно будет запилить через функционал апгрейднутой бумаги (без явного пользования штмля).
Запилить темплейт с именованными полями и его читать из файла (если это вообще нужно), в New() после выполнения прежней реализации (..()) прописывать в именованные поля рандомно сгенерированные параметры, затем make_readonly().

Ну и оно явно еще не готово, пусть повисит драфтом.

2020-10-26 12:54 UTC, Epicus7 commented
Этот ПР уже неактуален и его надо переделывать чуть более чем полностью. Особенно после обновления бумаг от Джаммера. Думаю пришло время его закрыть.

2020-10-26 12:54 UTC, closed without merging

2020-10-26 12:55 UTC, kreeperHLC commented
🎉