fix(Тобибоёвочка, бумажные лёгкие и смешные падения)
ChaoticOnyx/OnyxBay pull request #2186
Opened 2020-04-26 22:25 UTC by TobyThorne

1. Уменьшено время падения от сквозняка (15 секунд -> 9 секунд). Сквозняк больше не обновляет время стана у лежачих. Бесконечный сквозняк всё ещё будет ронять кучу раз подряд, но у космонавтика будет время на включение магбутов или приседание на стул.
2. Уменьшено время падения от **внезапного** появления гравитации (18 -> 9 и 9 -> 3 секунд при беге/ходьбе соответственно). Может быть, нерфоцирк, но споткнуться и упасть дольше, чем от попадания тазера - это какое-то говно.
3. Изменена механика разрыва лёгких от слишком низкого/высокого давления. Раньше каждый вдох имел шанс (5% и 2.5% у обычных и механических) насмерть порвать лёгкие, из-за чего секундное нахождение без воздуха могло сделать фраг. Теперь - вместо этого с таким же шансом лёгкие ловят урон, и если лёгкие достаточно повреждены - рвёт. Как негативный эффект - порванные лёгкие продолжат получать урон от давления и могут убиться намертво.
4. Пофиксил забытый кусок своей боёвочки и теперь броня действительно даёт хоть какую-то защиту от рвущихся артерий и застревающей шрапнели. Если в цифрах - минимальный шанс (с бронёй, превышающей урон+проникновение пули) порвать/застрять при попадании обычной пули был 12,5%. Теперь - 2,5%. Например, для минимизации убивания артерии пулей 9мм необходимо иметь 38,5 брони. Пули из матебы - 90. Изменение затрагивает только высокие показатели брони. 
5. Значительно уменьшен шанс разрыва артерий/застревания у резиновых пулек и бинбэгов.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute]
- [x] Как и обещал год назад, пытаюсь фиксить свою боёвочку.

2020-04-26 22:50 UTC, Ruforce commented
А я только тебя вспоминал, няша!

2020-04-26 22:58 UTC, PlinHost commented on code/modules/organs/internal/lungs.dm
> +				take_internal_damage(5)
Оно точно должно дамажить когда орган уже bruised? Старый код не дамажил больше.

2020-04-26 22:58 UTC, PlinHost commented on code/modules/organs/internal/lungs.dm
> +				if(!is_bruised() && damage > min_bruised_damage) //only rupture if NOT already ruptured and lungs are damaged
https://github.com/ChaoticOnyx/OnyxBay/blob/25818f3640ed9cebfa703cb1a36116b1c873bd04/code/modules/organs/internal/_internal.dm#L120-L121
Интересная проверка.

2020-04-26 23:03 UTC, TobyThorne commented on code/modules/organs/internal/lungs.dm
> +				take_internal_damage(5)
бу дезигн

Замена единоразового "вжух ты порвался" на продолжительный дамаг.

2020-04-26 23:04 UTC, TobyThorne commented on code/modules/organs/internal/lungs.dm
> +				if(!is_bruised() && damage > min_bruised_damage) //only rupture if NOT already ruptured and lungs are damaged
Ну это да это косяк чет я выдал

2020-04-26 23:05 UTC, PlinHost commented on code/modules/organs/internal/lungs.dm
> +				take_internal_damage(5)
Но там вжух ты порвался и больше не дамажит, а тут до смерти органа хуярить будет.

2020-04-26 23:12 UTC, TobyThorne commented on code/modules/organs/internal/lungs.dm
> +				take_internal_damage(5)
Ну тип реализм. Несколько минут дышишь вакуумом - лёгкие превращаются в какаху.

2020-04-26 23:12 UTC, PlinHost commented on code/modules/organs/internal/lungs.dm
> +		if(breath.total_moles == 0)
Иф уехал, не компилица.

2020-04-27 12:46 UTC, dnivji commented
Аппрув!

2020-04-28 10:00 UTC, dnivji commented
@TobyThorne может, имеет смысл снизить до 3 время стана от сквозняка?

2020-04-28 10:49 UTC, Moscowchief commented
Все хорошо, только стан от ветерка уменьшить бы до трех и от гравитации при беге и ходьбе уравнять тоже до трех.

2020-04-28 12:46 UTC, TapKo4eB commented
![image](https://user-images.githubusercontent.com/48761132/80488684-65c0ea80-8967-11ea-8cac-cf828610ea68.png)
это ок да что бинбенги начали дамажить сильнее красных?
левая нога - красные
правая нога - бинбенги

2020-04-28 12:56 UTC, TapKo4eB submitted a review, later dismissed
пострелял, побегал, мне понравилось. вроде даже ничё не сломано
а смысла и дальше нёрфить падение от ветерка я не вижу к слову в принципе ибо конечно да, хуйня, но таков ветерок
~~а ну и ещё если ты чё запушишь то аппрув слетит ага мда~~

2020-04-28 15:38 UTC, TobyThorne commented
Эпикус, а чего от автора требуется? Всё таки до трёх обрезать? Можно, конечно. Но не слишком нерфоцирк будет?

2020-04-28 15:39 UTC, Epicus7 commented
@TobyThorne, ну смотри, чтобы ПР прошел, его должны аппрувнуть 2 из 3 геймдизайнеров. Соответственно тебе надо ответить на их вопросы и либо изменить как они хотят, либо объяснить им почему они не правы и убедить их, что все зашибись.

2020-04-28 15:40 UTC, Epicus7 commented
Геймдизы, если что - это Днивжи, Москоучиф и Родиал. Надо бы это где-то написать...

2020-04-28 15:54 UTC, TobyThorne commented
@dnivji @Moscowchief @Rodial-Admiral @TapKo4eB 
Сравнял падение от гравитации до 3 секунд при любом раскладе.
Падение от ветерка обрезал до 6, а то 3 - всё-таки слишком радикально выходит. 
Узнали? Согласны?

2020-04-28 17:16 UTC, TapKo4eB submitted a review, later dismissed
да бляб опять аппруват

2020-04-28 18:48 UTC, Moscowchief commented
>Падение от ветерка обрезал до 6, а то 3 - всё-таки слишком радикально выходит.

Я все же настаиваю на 3.

2020-04-28 19:47 UTC, TobyThorne commented
@Moscowchief 
Хозяин - барин.

2020-04-28 21:48 UTC, TapKo4eB submitted a review, later dismissed
оаоааааооаоаоооамммммммм
The Saga of TobyThorne the Buffer

2020-04-28 21:49 UTC, TobyThorne commented
> оаоааааооаоаоооамммммммм
> The Saga of TobyThorne the Nerfer

Абидна ващет. Я ж болонам урон из пятёрки вытащил.

2020-04-29 05:48 UTC, TapKo4eB commented
Ммм.... хотя в принципе если посмотреть со стороны это можно расценивать как бафф

2020-05-02 11:42 UTC, TermService requested changes

2020-05-02 11:42 UTC, TermService commented on code/modules/ZAS/Airflow.dm
> +	to_chat(src, "<span class='warning'>The sudden rush of air knocks you over!</span>")
SPAN_WARNING

2020-05-02 11:42 UTC, TermService commented on code/game/area/areas.dm
> +		to_chat(mob, "<span class='warning'>The sudden appearance of gravity makes you fall to the floor!</span>")
SPAN_WARNING

2020-05-02 18:52 UTC, TobyThorne commented on code/game/area/areas.dm
> +		to_chat(mob, "<span class='warning'>The sudden appearance of gravity makes you fall to the floor!</span>")
Не понимаю, зачем использовать это говно и лишний раз срать скобочками, когда в 90% билда используется старое-доброе <span class=''>, но да похуй.

2020-05-02 19:10 UTC, Rodial-Admiral commented
По пунктам 3-5 вопросов нет.
Касаемо пункта 2 - тоже без возражений, гравитация слишком мемная, трех секунд достаточно.

По первому пункту - почему всего три секунды? Тут главное, как мне кажется, починить перманентное опрокидывание ветерком, а не совсем в хламину его занерфать.
Выходит, если я, положим, РЦД разберу пол в отсеке с нормальным давлением, то резкой разгерметизацией людей хлопнет всего на три секунды? 
С другой стороны - у нас и от легкого ветерка падения происходят.
Может, сделать рандомное время в каком-то интервале?
Положим, от 3 до 6 секунд.

2020-05-02 19:49 UTC, Moscowchief commented
В таком случае, надо делать упор не на замедление игры тупыми станами от дуновения ветерка, а на дамаг атмоса, только не на дамаг по легким с полувдоха, а просто на дамаг по телу. 
Впрочем, рандомность звучит неплохо, будет получше выглядеть, если все персонажи не будут одновременно подскакивать, а с некоторым разбросом. Можно вообще заморочиться и сделать зависимость стана от возраста персонажа.

2020-05-02 20:31 UTC, MrMagick2104 commented
> Можно вообще заморочиться и сделать зависимость стана от возраста персонажа.

А ещё от пола, роста, бодибилда, трейтов на пониженное ХП и далее-далее-далее.
Одним только возрастом это определять - такое себе, а делать вообще всё - плохая идея, по очевидным причинам: выйдет лишний код, который, по-факту, будет лишь занимать сервер ненужными проверками и хуже работать, скорее всего.
> В таком случае, надо делать упор не на замедление игры тупыми станами от дуновения ветерка, а на дамаг атмоса, только не на дамаг по легким с полувдоха, а просто на дамаг по телу.

Вообще, в случае с вакуумом, можно было бы использовать не только дамаг-брут, а понижение температуры, относительно случайное облучение (в открытом космосе), etc. Разрывание людей внутренним давлением за тридцать секунд звучит смешно.

2020-05-02 20:55 UTC, TobyThorne commented
>Одним только возрастом это определять - такое себе, а делать вообще всё - плохая идея, по очевидным причинам: выйдет лишний код, который, по-факту, будет лишь занимать сервер ненужными проверками и хуже работать, скорее всего.

^this

В общем, дезигнеры, придумайте какую-нибудь идеальную циферку и я её вкручу. А то заебался уже туда-сюда теребить переменную.

2020-05-04 10:45 UTC, Moscowchief commented
Короче мы сошлись на рандоме от 3 до 6.

2020-05-04 11:28 UTC, TobyThorne commented
Granted

2020-05-05 07:36 UTC, TapKo4eB submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/48761132/81044090-4f151900-8ebc-11ea-9507-a5abaed0fa39.png)

2020-05-08 07:31 UTC, TobyThorne commented
Ожидает Автора/Одобрено
ПР Шрёдингера

2020-05-08 07:32 UTC, TermService requested changes

2020-05-08 07:32 UTC, TermService commented on code/modules/ZAS/Airflow.dm
> +		return 0 // Chudo-code
//chudo-opisanie
Убрать бы

2020-05-08 07:32 UTC, TermService commented on code/modules/ZAS/Airflow.dm
> +		return 0 // Chudo-code
```suggestion
		return 0
```

2020-05-08 07:39 UTC, TapKo4eB commented on code/modules/ZAS/Airflow.dm
> +		return 0 // Chudo-code
поч этож наставление будущим кодерам

2020-05-08 07:44 UTC, TermService commented on code/modules/ZAS/Airflow.dm
> +		return 0 // Chudo-code
это не несет пояснительного характера, не понятно ровным счетам ничего, чудо-код, супер. И вообще, можешь не принимать :)

2020-05-08 09:08 UTC, TapKo4eB approved these changes
какой раз это уже диссмисд я сбился со счёта

2020-05-08 09:10 UTC, TermService approved these changes

2020-05-08 09:13 UTC, merged