fix(brainmob movement)
ChaoticOnyx/OnyxBay pull request #2188
Opened 2020-04-27 01:12 UTC by Shirlineyn

Мув и форсмув мозгомоба был перенесен на его хранилище, чтобы избежать ситуаций с телепортом мозгомагом из ММИ и подобных им(теперь магомозг телепортируется вместе с ММИ)

closes #891

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-04-28 14:01 UTC, Epicus7 requested changes

2020-04-28 14:01 UTC, Epicus7 commented on code/modules/mob/living/carbon/brain/brain.dm
> +	ASSERT(istype(container))
Это фатальная ситуация, когда что-то пытается передвинуть мозг, а он не в контейнере? Кажется нет, мозг может быть и не в контейнере. В таком случае ASSERT тут избыточен.

Мне кажется тут нужно просто условие.

2020-04-28 17:39 UTC, PlinHost commented on code/modules/mob/living/carbon/brain/brain.dm
> +	ASSERT(istype(container))
Это не мозг, а брейнмоб, который всегда привязан к какому-то объекту, будь то орган мозга или мми. Но там все очень грустно и контейнер действительно не всегда есть.

2020-06-20 06:47 UTC, HonkyDonky commented
Смешной баг, но автора похоже похитили волшебники из магической федерации два месяца назад.

Закрываю.

2020-06-20 06:47 UTC, closed without merging

2026-02-19 16:48 UTC, Accoll1 commented
Уже долгое время тыкаю, вот что пока что нащупал.

Заклинание Teleport как я понял старается переместить моба в заданное место всеми силами. По скольку мозг находится в контейнере ММИ то обычным методом Move() у нее не получается, и она делает это через ForceMove() из-за чего игра перемещает сам мозг которым можно управлять. 

При этом для игры в мми все еще находится мозг, а в VV мозга числится, что он находится в контейнере. Когда из ММИ вынимается мозг, то мозг под управлением игрока перемещается на тайл ММИ и теряет управление.

Сама игра же считает, что в ММИ все еще находится оригинальный мозг, мозг же который находится под управлением игрока так же считается оригинальным который находится в ММИ (хотя это не так) со всеми вытекающими для мозга в ММИ(импланты на радио из-за чего мозг дубликат может разговаривать). 

Думаю, это происходит из-за ForceMove(), но почему именно еще не понимаю. В целом не совсем понимаю с какой стороны стоит подходить к фиксу(Фиксить абилку, мозг или ММИ или вообще ForceMove()). Иссуй помечен как легкий, но чет дается тяжко.
<img width="1166" height="808" alt="Снимок экрана 2026-02-19 193114" src="https://github.com/user-attachments/assets/47c8094c-9dd1-40f5-bc6c-0ac347bcf635" />

2026-02-19 16:49 UTC, Accoll1 commented
И дополнительно скажу, что использование спелов ВНЕ тела мага является так же багом, а не фичей. Телепортирование ВНЕ тела мага позволяет только заклинание no clothes, возможно мне стоит посмотреть и этот спелл