Ещё Тобибоёвочка
ChaoticOnyx/OnyxBay pull request #2287
Opened 2020-05-06 08:55 UTC by TobyThorne

Как показывает практика, механика блоков оказалась слишком слабой. В смысле, **СЛИШКОМ** слабой. До уровня полной бесполезности. Необходимость каждый раз нажимать на кнопку вкупе с замедлением передвижения не позволяет эффективно играть в оборону - такая тактика с огромным отрывом отстает от активного нападения. А ещё лучевое оружие работает через жопу, так что отражение лучей есвордами и энергощитами в какой-то момент сломалось. Так что выкадываю значительный бафф блоков, посмотрим, как будет работать.
- Активный блок больше не прерывается при успешном блокировании;
- Как компенсация, активный блок ещё сильнее замедляет восстановление пойза;
- Лучевое оружие (лазеры, шок, etc.) теперь может успешно блокироваться световыми мечами и энергощитами. В отличие от обычных выстрелов, они именно блокируются, а не отражаются, аки молнии силы в SW.
- Добавлен хоткей для блока - на клавишу 'С';
- Ёмкость лазерного карабина увеличена до 12 выстрелов;
- Ёмкость лазерной пушки увеличена 8 выстрелов;
- Лазерным карабинам и пушкам добавлен второй режим стрельбы - slug. В этом режиме вместо лучшей они стреляют лазерными "пулями" (как старые лазеры). Они действуют, как обычные пули - медленнее и не пролетают сквозь окна, но имеют немного больше урона, повышенное пробитие брони и дополнительный небольшой урон болью.
- Перерисован спрайт лазерного карабина. За основу был нынешний спрайт, беевский спрайт и старый-добрый буллпап. Попутно сделал альтернативную расцветку, надо придумать, как использовать.

![lasguns](https://user-images.githubusercontent.com/45202681/81158286-a47b2400-8fa9-11ea-8521-4f52ae4e9600.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-05-06 09:11 UTC, koronoshka commented
Когда парирования, рипосты и кувырки

2020-05-06 09:44 UTC, TobyThorne commented
Парирования уже давно есть.

2020-05-06 09:46 UTC, koronoshka commented
тогда бэкстэбы

2020-05-06 12:27 UTC, Wuattt commented
![image](https://user-images.githubusercontent.com/34631419/81176665-22412e80-8fae-11ea-840b-ff3cb7d1cd52.png)

2020-05-06 18:31 UTC, dnivji commented
аппрув

2020-05-06 19:14 UTC, xmaebx commented
>Попутно сделал альтернативную расцветку, надо придумать, как использовать.

Как вариант, кинуть на ЦК или ЕРТшникам. Либо запихать в аплинк для триторов, нюкеров.

2020-05-06 21:25 UTC, Rodial-Admiral commented
Геймдезигнерский аппрув

2020-05-08 12:42 UTC, TapKo4eB commented
пара придирок
это ок что блок выстрелов (именно выстрелов не ближнего боя) любыми есвордами и энергощитами **не снимают** пойз в принципе?
а может это фича кстати я хз но смешно
![gif3](https://user-images.githubusercontent.com/48761132/81406373-1c7c5200-9142-11ea-8a54-e294acfad53a.gif)

по моему функция блок свитча поломалась, ибо при смене на пустую руку с мейном ты всё равно продолжаешь блочить пули (касается не ток есвордов)

2020-05-08 12:45 UTC, TobyThorne commented
> пара придирок
> это ок что блок выстрелов (именно выстрелов не ближнего боя) любыми есвордами и энергощитами **не снимают** пойз в принципе?
> а может это фича кстати я хз но смешно
> ![gif3](https://user-images.githubusercontent.com/48761132/81406373-1c7c5200-9142-11ea-8a54-e294acfad53a.gif)
> 
> по моему функция блок свитча поломалась, ибо при смене на пустую руку с мейном ты всё равно продолжаешь блочить пули (касается не ток есвордов)

Неснимаемый при отражении пойз - бай дезайн.
Лор-вайз, выстрел же не передаёт импульс, а убивается об чудо-меч.
Баланс-вайз, есворд дорогой, как пол-станции, да бесполезный против пулялок. Если будет практически полностью контрить пулялки и вынуждать идти в ближний бой/закидывать гренками, то появится смысл косплеить ситха.

2020-05-08 12:46 UTC, TapKo4eB commented
>Если будет практически полностью контрить пулялки

бать он уже контрит, даже **пули** не снимают пойз
хотя это как по мне тоже клёво

2020-05-08 12:50 UTC, TapKo4eB commented
>Блок автоматом выбирает руку, в которой есть что-то подходящее для блокирования. Если в главной руке щит, но выставлен оффхенд - будет использоваться щит. И наоборот.

так дело в том что у меня выбран мейн на блоксвитче, в правой руке щит, а выбрана ща левая пустая
но я продолжаю блочить пули как ни в чём не бывало
тогда зачем оффхенд спрашивается

2020-05-08 12:57 UTC, TobyThorne commented
бля сложно
![Loading_Cat](https://user-images.githubusercontent.com/45202681/81407709-ac7bc500-915d-11ea-81b4-ba1933492de1.jpg)
пойду потестю

2020-05-08 13:09 UTC, TobyThorne commented
@TapKo4eB 
Кароч, потестил свой же чудокод.
В мили работает как надо. Какая рука выставлена - той и блокирует. Исключение - если выставлен offhand, а он пустой; тогда используется предмет в основной руке.
При блоке выстрелов используется лучший для этого предмет в руках:
Есворд, ещилд, прокачанный щит мага -> риот-щилд, обычный щит мага -> дверка от шкафа

2020-05-08 13:13 UTC, TapKo4eB commented
оке тогда преколы судя по всему распространяются ток на пули/лазеры понятно

2020-05-08 13:16 UTC, TapKo4eB submitted a review, later dismissed
ну в принципе больше не вижу к чему придраться

2020-05-09 11:21 UTC, TermService requested changes
В целом если ты обновляешь код хорошим тоном будет заменить классические спан классы на макросы, надо что-то придумать с цифрами, в дальнейшем это вызовет кучу боли если опять будут переделки

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
> +				visible_message("<span class='warning'>\The [user] dissolves [P] with their [src.name]!</span>")
SPAN_WARNING()

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
>  		if(src.mod_shield >= 2.5)
зачем src.

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
> +				H.poise -= P.damage/(src.mod_shield*2.0)
зачем src.

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
>  					visible_message("<span class='warning'>[H] falls down, unable to keep balance !</span>")
SPAN_WARNING()

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
>  			visible_message("<span class='warning'>\The [user] blocks [P] with their [src.name]!</span>")
SPAN_WARNING, зачем src.

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
>  		else if(src.mod_shield >= 1.3)
тут тоже какая-то дичь с src.

2020-05-09 11:21 UTC, TermService commented on code/game/objects/items.dm
> +				H.poise -= P.damage/(src.mod_shield*2.0)
Наверное все таки лучше поставить дефайн на цифру, этот баланс умножением очень тяжело потом будет отследить

2020-05-09 11:21 UTC, TermService commented on code/modules/mob/living/carbon/human/human_defense.dm
>  							src.visible_message("<span class='danger'>[pick("[src] was sent flying backward!", "[src] staggers back from the impact!")]</span>")
зачем src.

2020-05-09 11:21 UTC, TermService commented on code/modules/mob/living/carbon/human/human_defense.dm
> +							src.apply_effect(effective_force * 0.4, WEAKEN, (blocked/2))
зачем src.

2020-05-09 11:21 UTC, TermService commented on code/modules/mob/living/carbon/human/human_defense.dm
>  							src.visible_message("<span class='danger'>[src] bumps into \the [T]!</span>")
зачем src. SPAN_DANGER

2020-05-09 11:21 UTC, TermService commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			//defender.useblock_off()
если не нужно удаляй, этот кусок вряд ли нам нужен будет

2020-05-09 11:21 UTC, TermService commented on code/modules/mob/living/carbon/human/human_defense.dm
>  				visible_message("<span class='warning'>[defender] falls down, unable to keep balance!</span>")
SPAN_WARNING

2020-05-09 11:21 UTC, TermService commented on code/modules/mob/living/carbon/human/human_defense.dm
>  				visible_message("<span class='warning'>[defender]'s [w_def.name] flies off!</span>")
SPAN_WARNING

2020-05-09 12:11 UTC, TobyThorne commented on code/game/objects/items.dm
> +				H.poise -= P.damage/(src.mod_shield*2.0)
src для читаемости кода, ибо перед ним идёт P.damage и H.poise.

Ставить дефайн куда?
Если на mod_shield - то эта переменная отвечает ещё и за уменьшение урона по пойзу от блока в ближнем бою и меняется у разных итемов. Делать дефайны на все варианты от 1.0 до 2.5?
Если на 2.0 - то чёт вообще смешно.
Оба варианта - 
![670206689416445963](https://user-images.githubusercontent.com/45202681/81473447-69365a80-9220-11ea-9fae-a653fc936e62.png)

2020-05-09 12:19 UTC, TobyThorne commented
src для читаемости, ибо там в функциях используется хуева гора объектов и думать, от чего там mod_statname - такое себе удовольствие. 
SPAN_WARNING - говно из под коня, которое используется в билде в 5% случаев и только делает код уродливее. Соре, я этим говном и дальше уродовать билд не буду. И так уже насрали охуенными рефакторами с таймерами в дверях, которые спамят сотнями рантаймов при отключении света.

2020-05-09 12:29 UTC, TapKo4eB commented
похоже реально придётся кодить макро мультиспан

2020-05-09 12:45 UTC, TobyThorne commented
> похоже мне реально придётся кодить макро мультиспан

Ну, выглядел бы макрос хоть как-то адекватно и выполнял бы хоть какую-то функцию, кроме, собственно, его создания для имитации бурной деятельности - ещё бы ладно. Или если бы на моменте его создания билд пропарсился и везде спаны бы заменились этой хренью.

Функцию никакую не выполняет, код не сокращает, выглядит по уебански из-за двойной скобочки в конце. Фу.

2020-05-11 15:52 UTC, TobyThorne commented
Заменил все спаны в items.dm и human_defense.dm на новые макросы от ТапКо4еВа.

2020-05-13 22:08 UTC, Epicus7 commented
![image](https://user-images.githubusercontent.com/5204667/81870773-4046fa00-957f-11ea-8450-4d0ef1f36097.png)

Что здесь происходит, откуда столько левых коммитов? Куча изменений левых затесалось, я хз как это ревьювать и хз как это смержится. Можешь, пожалуйста, пофиксить и сделать так, чтобы в ПРе были чисто твои изменения?

2020-05-14 04:58 UTC, TobyThorne commented
> Что здесь происходит, откуда столько левых коммитов? Куча изменений левых затесалось, я хз как это ревьювать и хз как это смержится. Можешь, пожалуйста, пофиксить и сделать так, чтобы в ПРе были чисто твои изменения?

Попросили ребейзнуть после добавления новых макросов. Получилось смешное.

2020-05-14 05:03 UTC, Epicus7 commented
Ты кажется не то ребейзнул) Надо было свои изменения на дев, а не дев на твою ветку.

2020-05-14 09:04 UTC, TobyThorne commented
> Ты кажется не то ребейзнул) Надо было свои изменения на дев, а не дев на твою ветку.

Гит делает меня плакать. Сложно. Короче, сейчас нормальный ПР сделаю.

2020-05-14 09:04 UTC, closed without merging