Make Botanics Great Again
ChaoticOnyx/OnyxBay pull request #2329
Opened 2020-05-10 06:11 UTC by TobyThorne

Огромная куча всякой всячины для увеселения жизни ботаников.

**Добавлены/изменены следующие растения:**
* Томат-убийца (killer tomato). Старый-добрый томат убийца, исчезнувший из-за смешных переименований растений. В итоге вместо "tomatokiller" в мутациях стояло "killer" и нихрена не работало.
Мутирует из: bloody tomato
Мутирует в: N/A
* Томак (Tomacco). Съедобные сигареты! 
Мутирует из: tomato
Мутирует в: N/A
* Нанокровавый Томат (Nanoblood Tomato). Как кровавый томат, только с нанокровью.
Мутирует из: blood tomato
Мутирует в: automato
* АвТомат (Automato). Содержит наниты! Пик томатной селекции.
Мутирует из: nanoblood tomato
Мутирует в: N/A
* Баклажан (Eggplant). Возвращена старая мутация.
Мутирует из: N/A
Мутирует в: egg plant
* Яичное растение (Egg plant). Несёт цветные яйца. Почему нет?
Мутирует из: eggplant
Мутирует в: N/A
* Красные яблоки (Red apples). Бывшие обычные яблоки. Содержит яблочный сок.
Мутирует из: yellow apples, green apples
Мутирует в: yellow apples, green apples, poison apples
* Жёлтые яблоки (Yellow apples). Тоже содержат яблочный сок.
Мутирует из: red apples, green apples
Мутирует в: red apples, green apples, golden apples
* Зелёные яблоки (Green apples). Как ни странно, сок.
Мутирует из: red apples, yellow apples
Мутирует в: red apples, yellow apples, radioactive apples
* Ядовитые яблоки (Poison apples). Не отличаются от обычных красных яблок, содержат цианид.
Мутирует из: red apples
Мутирует в: N/A
* Золотые яблоки (Golden apples). Содержат золото. Блестят.
Мутирует из: yellow apples
Мутирует в: N/A
* Радиоактивные яблоки (Radioactive apples). Содержат радий. Избавляют от необходимости постоянно бегать к химикам.
Мутирует из: green apples
Мутирует в: N/A
* Подлунник (Moonflower). Содержит самогон.
Мутирует из: sunflower
Мутитрует в: N/A
* Банан (Banana). Добавлены мутации.
Мутирует из: N/A
Мутирует в: lubanana, bunana
* Бунан (Bunana). Большой, круглый банан. Похож на булочку.
Мутирует из: banana
Мутирует в: N/A
* Любанан (Lubanana). Содержит смазку. Мечта клоуна. Или ЕРПшника. 
Мутирует из: banana
Мутирует в: BANana
* БАНан (BANana). При применении обсепечивает мгновенный сердечный приступ всем игрокам в зоне видимости.
Мутирует из: lubanana
Мутирует в: N/A
* Картоха (Potato). Добавлена мутация.
Мутирует из: N/A
Мутирует в: electric potato
* Электрокартоха (Electric potato). Производит готовые картофельные батарейки.
Мутирует из: potato
Мутирует в: N/A
* Кокос (Coconut). Источник кокосового молока. Вкусно.
Мутирует из: N/A
Мутирует в: cowcownut
* Кокорова (Cowcownut). Самая ужасная игра слов, на которую меня хватило. Кокосовую коровку, внезапно, можно доить ради кокосового молока.
* Диона (Diona). Добавлена лучшая мутация.
Мутирует из: N/A
Мутирует в: maneater
* Людоед (Maneater). Зубастая ебака, которую сложно получить из-за склонности растущей дионы умирать от радиации и сложно размножить из-за отсутствия семян. Зато можно создать личную цветочную гвардию и дать по сосать всем в радиусе одной станции. После сбора с грядки в течение пяти секунд приходит в себя, в это время можно скормить людоеду кусок мяса - покормившего космонавтика оно атаковать не будет. Дружит с томатами-убийцами.
Мутирует из: diona
Мутирует в: N/A

**Следующих мобов теперь можно перехватывать, играя призраком:**
- Ходячие грибочки (Walking Mushrooms). Безвредны, но могут распространять свои споры. И вообще милашки. 
- Томаты-убийцы (Killer Tomatoes). Не слишком опасные, зато милые. Джвесять лет ждал возможности поотыгрывать помидор.
- Людоеды (Maneaters). Получить их достаточно сложно, так что почему бы не дать гостоте возможность устроить кровавую баньку?

**Прочие изменения:**
- Наниты возвращены из состояния кастрированного плейсхолдера. В маленьких дозах действуют как очень мощная версия трика, залечивая ожоги и брут. При передозе (5+ единиц) с некоторым шансом превращают космонавтика в борга, раскидывая слабую плоть повсюду в радиусе некоторых метров. Как это и было раньше, в общем-то.
- Большая часть спрайтов растений заменена на гуновские, охрененно красивые.
- Пофикшена куча мелких недочётов у растений: отвалившийся цвет у зелёного винограда, спрайт-плейсхолдер у чеснока и лука, etc.
- Добавлены кокосовое молоко (надо будет потом добавить рецепты вроде пина колады, но сейчас лень) и яблочный сок (немножко лечебный, с рецептами то же самое).

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-05-10 06:49 UTC, Pos13 commented
HYPE

2020-05-10 07:19 UTC, TapKo4eB commented on code/game/objects/items/toys.dm
> +/obj/item/toy/banbanana/attack_self(mob/user as mob)
as mob не нужен же

2020-05-10 07:19 UTC, TapKo4eB commented on code/modules/hydroponics/seed_storage.dm
> +		/obj/item/seeds/whitebeetseed 			= 30
![image](https://user-images.githubusercontent.com/48761132/81493244-882bff80-92a7-11ea-819e-61d3167137e7.png)
![image](https://user-images.githubusercontent.com/48761132/81493233-79454d00-92a7-11ea-9ffc-0fba24874210.png)

[выранивание табами аааа](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D1%82%D0%B0%D0%B1%D1%8B-vs-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D1%8B)

2020-05-10 07:41 UTC, TobyThorne commented on code/modules/hydroponics/seed_storage.dm
> +		/obj/item/seeds/whitebeetseed 			= 30
блет гит хуб за што :(

2020-05-10 07:46 UTC, TobyThorne commented on code/game/objects/items/toys.dm
> +/obj/item/toy/banbanana/attack_self(mob/user as mob)
Скопипастил кокойто легаси. Упс.

2020-05-10 08:05 UTC, TapKo4eB commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +/mob/living/simple_animal/hostile/maneater/attackby(obj/item/O as obj, mob/user as mob)
ищё тут

2020-05-10 08:05 UTC, TapKo4eB commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
>  /mob/living/simple_animal/cow/attack_hand(mob/living/carbon/M as mob)
тут

2020-05-10 08:05 UTC, TapKo4eB commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
>  /mob/living/simple_animal/cow/attackby(obj/item/O as obj, mob/user as mob)
и тут

2020-05-10 09:44 UTC, TapKo4eB commented
![image](https://user-images.githubusercontent.com/48761132/81495840-e367ed00-92bb-11ea-9403-2ac939c7529f.png)
я надеюсь пакет семян бунаны так и должен выглядеть?

2020-05-10 09:59 UTC, TapKo4eB requested changes

2020-05-10 09:59 UTC, TapKo4eB commented on code/modules/hydroponics/seed_datums.dm
> +	mutants = ("banbanana")
```suggestion
	mutants = list("banbanana")
```
э сюка сломал блеать прок `get_mutant_variant()` вот именно банбанане чёртовы кодеры кодят а потом люди фичей воспользоваться не смогут

2020-05-10 10:26 UTC, TobyThorne commented on code/modules/hydroponics/seed_datums.dm
> +	mutants = ("banbanana")
не баг а фича инфа сотка 💯💯💯

2020-05-10 10:52 UTC, ArmenianOnyx commented
Скорее принимайте, жирный плюсик.

2020-05-10 11:27 UTC, dnivji commented
Я геймдиз простой, вижу ПР Тоби, ставлю аппрув.

2020-05-10 12:03 UTC, TobyThorne commented
Добавил перенос реагентов при размазывании фрукта. И любананы теперь ещё и сами по себе скользкие.

2020-05-10 15:45 UTC, TapKo4eB approved these changes

2020-05-10 15:45 UTC, TapKo4eB commented on code/modules/hydroponics/seed_datums.dm
> +	mutants = ("banbanana")
![image](https://user-images.githubusercontent.com/48761132/81503812-69049080-92ee-11ea-9327-3bf0bb2b7d78.png)
зачем ты добавляешь в код то что нельзя будет получить игровым путём

2020-05-10 15:46 UTC, TapKo4eB requested changes
блять я аппрувнул

2020-05-10 15:54 UTC, TobyThorne commented on code/modules/hydroponics/seed_datums.dm
> +	mutants = ("banbanana")
бля нахуй код ночью писать, тупо говна попил %(

2020-05-10 15:56 UTC, Moscowchief commented
Аппрув!

2020-05-10 16:21 UTC, Epicus7 commented
Да это же платный иссуй #1216

2020-05-10 17:05 UTC, TapKo4eB submitted a review, later dismissed
реальн кстати платный

2020-05-13 21:08 UTC, Epicus7 requested changes

2020-05-13 21:08 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			L.visible_message("<span class='danger'>\The [src] knocks down \the [L]!</span>")
Maneater-а на локалке кто-нибудь проверял как работает?

2020-05-13 21:09 UTC, Epicus7 commented
Чот у меня сомнения есть, тестировал ли это нормально автор и насколько это тестировал Тапок. Если Тапок нормально протестировал (явно напишет), то ок.

2020-05-13 21:15 UTC, PlinHost commented on code/game/objects/items/toys.dm
> +	qdel(src)
> Почему всем игрокам пишется, что они "banned", но звук только у того проигрывается, кто активировал?

Звук проигрывается на турфе с дефолтным радиусом, что не так?

2020-05-13 21:47 UTC, Epicus7 commented on code/game/objects/items/toys.dm
> +	qdel(src)
А ну да, тогда со звуком все норм. Но остальные вопросы остаются.

2020-05-14 04:36 UTC, TobyThorne commented on code/game/objects/items/toys.dm
> +	qdel(src)
>Кажется тут явно не сердечный приступ, а просто слепота? Если оно вообще работает.

У персонажей - секундная слепота, у игроков - сердечный приступ. :smekalo4ka:

>Может быть это и смешно, но если будут часто абузить - хзхз.

Ну-с, его ещё нужно получить через мутации, растёт он медленно и плодоносит одной штукой за раз. Мутаген имеет шанс вовсе убить yield. Да и размножить их через плоды не получится, только отрезать сэмплы. И фича, в общем-то, не настолько смешная чтобы прям дико абузить.

2020-05-14 04:41 UTC, TobyThorne commented on code/modules/hydroponics/grown.dm
> +		else if(W.sharp && !istype(W,/obj/item/weapon/reagent_containers/syringe))
Ну, тут проблема не столько в нарезании шприцом (шприцем?), сколько в невозможности вколоть им реагенты в нарезаемые фрукты. Нарезание же всякими отвёртками - скорее фича, чем баг.

2020-05-14 04:47 UTC, Epicus7 commented on code/modules/hydroponics/grown.dm
> +		else if(W.sharp && !istype(W,/obj/item/weapon/reagent_containers/syringe))
Чот такая себе фича. Давай вообще проверку уберем и будем jackboots-ами нарезать, еще смешнее будет

2020-05-14 04:51 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			L.visible_message("<span class='danger'>\The [src] knocks down \the [L]!</span>")
Сто тыщ раз проверил, пока делал ПР, ибо сделать ему приручение оказалось задачей довольно таки нетривиальной. В целом, положение такое:
1. Робастный, шо пиздец, один на один без огнестрела или брони победить - это надо быть Соляром. Хотя и слабее, чем на Гунах.
2. Приручение работает надёжно как швейцарские часы. Можно успешно делать ферму ксеномяса. Всех остальных, за исключением других мобов из фракции "creatures" (томаты-убийцы и не-культовые зелёные кусаки) идёт разбирать на атомы. 
3. Первые пять секунд жизни, во время которых можно приручить, стоит и аутирует.
4. Если не собрать вручную с грядки - соберётся через какое-то время сам.
5. Ghost Possess работает.

2020-05-14 04:53 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			L.visible_message("<span class='danger'>\The [src] knocks down \the [L]!</span>")
Ну и кормление бесполезно, если его поссессят, да. Управляющий им игрок может грызть, кого хочет. Это уже особо никак не исправить. Разве что впилить ему интерфейс, показывающий друга, но это уже нужно много кода.

2020-05-14 04:55 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			L.visible_message("<span class='danger'>\The [src] knocks down \the [L]!</span>")
Оппа, а может убрать ghost-possess, если приручили? А то неоч получается, ты приручал-приручал, а тут госты приходят и все обламывают.

2020-05-14 04:56 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			L.visible_message("<span class='danger'>\The [src] knocks down \the [L]!</span>")
И первые пять секунд тоже, чтобы нельзя было перехватить до приручения.

2020-05-14 05:12 UTC, TobyThorne commented on code/modules/hydroponics/grown.dm
> +		else if(W.sharp && !istype(W,/obj/item/weapon/reagent_containers/syringe))
Ну хз-хз. Могу изменить, в общем-то. Хозяин - барин.

2020-05-14 05:13 UTC, Epicus7 commented on code/modules/hydroponics/grown.dm
> +		else if(W.sharp && !istype(W,/obj/item/weapon/reagent_containers/syringe))
Да я не геймдиз, а им пофиг. Смотри сам как хочешь.

2020-05-14 05:18 UTC, Epicus7 submitted a review, later dismissed

2020-05-14 05:20 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			L.visible_message("<span class='danger'>\The [src] knocks down \the [L]!</span>")
Сделяль.

2020-05-14 06:11 UTC, TapKo4eB commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			controllable = TRUE
чтобы ты понимал на стадии /mob/living/Initialize() сканируется на контроллабл и добавляется в список поссеса. Своим изменением контроллабла после вызова родича ты сломал весь поссес))0

2020-05-14 06:17 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/maneater.dm
> +			controllable = TRUE
У блят. Ладно, чёнить придумаю.

2020-05-14 07:13 UTC, TobyThorne commented
Убрал возможность поссессить людоедов. В общем-то, раз уж их можно приручать, то давать их игрокам - перебор. Да и слишком робастные. Если под контролем более-менее рукастого космонавтика будет стрейфить и доджить выстрелы - так можно пол-станции вырезать.

2020-05-14 07:16 UTC, ArmenianOnyx commented
Мне кажется людоедов лучше оставить. Робастных мобов на станции нема.

2020-05-14 07:18 UTC, TapKo4eB commented
> 
> 
> Мне кажется людоедов лучше оставить. Робастных мобов на станции нема.

а кто сказал что их удалили

2020-05-14 07:19 UTC, ArmenianOnyx commented
> Убрал возможность поссессить людоедов. В общем-то, раз уж их можно приручать, то давать их игрокам - перебор. Да и слишком робастные. Если под контролем более-менее рукастого космонавтика будет стрейфить и доджить выстрелы - так можно пол-станции вырезать.

А это шо?

2020-05-14 07:20 UTC, ArmenianOnyx commented
Бля, неправильно прочитал. Посеять и поссесить

2020-05-14 07:21 UTC, TapKo4eB approved these changes
короче прикольно

2020-05-14 09:01 UTC, Epicus7 approved these changes

2020-05-14 09:04 UTC, merged