Блоки и Лазеры
ChaoticOnyx/OnyxBay pull request #2372
Opened 2020-05-14 10:56 UTC by TobyThorne

Как показывает практика, механика блоков оказалась слишком слабой. В смысле, **СЛИШКОМ** слабой. До уровня полной бесполезности. Необходимость каждый раз нажимать на кнопку вкупе с замедлением передвижения не позволяет эффективно играть в оборону - такая тактика с огромным отрывом отстает от активного нападения. А ещё лучевое оружие работает через жопу, так что отражение лучей есвордами и энергощитами в какой-то момент сломалось. Так что выкатываю значительный бафф блоков, посмотрим, как будет работать.
- Активный блок больше не прерывается при успешном блокировании;
- Как компенсация, активный блок ещё сильнее замедляет восстановление пойза;
- Лучевое оружие (лазеры, шок, etc.) теперь может успешно блокироваться световыми мечами и энергощитами. В отличие от обычных выстрелов, они именно блокируются, а не отражаются, аки молнии силы в SW.
- Добавлен хоткей для блока - на клавишу 'С';
- Ёмкость лазерного карабина увеличена до 12 выстрелов;
- Ёмкость лазерной пушки увеличена 8 выстрелов;
- Лазерным карабинам и пушкам добавлен второй режим стрельбы - slug. В этом режиме вместо лучей они стреляют лазерными "пулями" (как старые лазеры). Они действуют, как обычные пули - медленнее и не пролетают сквозь окна, но имеют немного больше урона, повышенное пробитие брони и дополнительный небольшой урон болью.
- Борговский тазер получил ещё один режим стрельбы - стасферки. Для компенсации 6 выстрелов вместо 5 и наличия мочелучей, эти стансферки чутка слабее, чем в СБшном тазере.
- Перерисован спрайт лазерного карабина. За основу был нынешний спрайт, беевский спрайт и старый-добрый буллпап. Попутно сделал альтернативную расцветку, надо придумать, как использовать.
- Перерисованы спрайты лазерного карабина, тазера и батона для боргов. Теперь они более... борговые.

![lasguns](https://user-images.githubusercontent.com/45202681/81158286-a47b2400-8fa9-11ea-8521-4f52ae4e9600.png)
![borgweapons](https://user-images.githubusercontent.com/45202681/81926461-c6a51f80-9603-11ea-83fc-334da8c9def2.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-05-14 11:15 UTC, Animesku commented
Дежа вю

2020-05-14 11:17 UTC, TapKo4eB commented on code/modules/projectiles/guns/energy/stun.dm
>  	use_external_power = 1
впиши projectile_type = /obj/item/projectile/energy/electrode оно при спавне с выбранной сферой стреляет мочелучами нахуй

2020-05-14 11:56 UTC, TapKo4eB approved these changes
окей симс лежит

2020-05-19 16:45 UTC, TobyThorne commented
@Moscowchief @Rodial-Admiral @dnivji
Recheck?

2020-05-20 04:55 UTC, Epicus7 requested changes
Вроде все норм, воспросы только по изменениям, описания которых не увидел в ОПе.

2020-05-20 04:55 UTC, Epicus7 commented on interface/skin.dmf
> -		background-color = none
Это что за изменения? В описании ПРа не вижу ничего про это.

2020-05-20 04:55 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +						apply_effect((I.mod_weight*15), PARALYZE, (blocked/2))
Тут какие-то изменения непонятные, зачем блок в два раза меньше используется теперь?

2020-05-20 08:10 UTC, TobyThorne commented on interface/skin.dmf
> -		background-color = none
Это бульонд автоматом меняет. Видимо, в прошлый раз skin.dmf трогали давным давно.

2020-05-20 08:21 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +						apply_effect((I.mod_weight*15), PARALYZE, (blocked/2))
Забыл про этот кусок, ибо он должен был в отдельный ПР идти. Но раз уж затесался - ладно.
Вырубание ударами в данный момент смешное. Оно не может длиться дольше 12 секунд, но может длиться меньше. Если на голове шлем - космонавтик вовсе вырубится на вдвое меньшее время. 
Так что прикрутил время вырубания к весу оружия, а не к урону (болоном вырубать людей логичнее, чем циркуляркой или есвордом) и снял кап.  И влияние брони уменьшил.
Петушитель вырубит голую голову примерно на минуту. В шлеме - секунд на сорок. На шанс пососать влияет не так сильно: и сейчас, если уж повалили, вырубили и начали забивать - то сам уже не спасёшься в любом случае. Зато появляется возможность эффективно оглушать космонавтиков и ретироваться/тихо утаскивать их в глубину гетто.

2020-05-20 08:35 UTC, Pos13 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +						apply_effect((I.mod_weight*15), PARALYZE, (blocked/2))
> Петушитель вырубит голую голову примерно на минуту.
А это не слишком робастно? Огнетушитель достать легко, а эффект выглядит гораздо сильнее слиптоксина или трейторской ручки.

2020-05-20 08:50 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +						apply_effect((I.mod_weight*15), PARALYZE, (blocked/2))
Вообще странная механика, кажется шлем должен спасать от "вырубания" в принципе. Особенно риот-шлем. Иначе зачем они вообще нужны.

Но да ладно, это все геймдиз уже.

2020-05-20 08:50 UTC, Epicus7 approved these changes

2020-05-20 08:51 UTC, Epicus7 commented
Алсо у нас тут новые фичи: @ChaoticOnyx/game-designers

2020-05-20 17:01 UTC, Rodial-Admiral commented
Да, все годно. Потом дополнительно пошуршу, может еще чего отпишу.

2020-05-21 10:30 UTC, dnivji commented
Аппрув.

2020-05-21 11:15 UTC, Moscowchief commented
> Лучевое оружие (лазеры, шок, etc.) теперь может успешно блокироваться световыми мечами и энергощитами. В отличие от обычных выстрелов, они именно блокируются, а не отражаются, аки молнии силы в SW.

Я бы сделал мечам именно отражение.

2020-05-21 11:16 UTC, TobyThorne commented
> Я бы сделал мечам именно отражение.

И я бы сделал. Но в коде рикошетов лучей такой спагетти-код, что мне страшно туда лезть.

2020-05-21 11:47 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +						apply_effect((I.mod_weight*15), PARALYZE, (blocked/2))
Чтобы вырубить космонавтика ударом, у него должен быть низкий пойз, а оружие желательно должно быть тяжёлым, хотя при большом желании можно и отвёрткой (но быстрее помрёт от урона).

В общем, у РИОТ-шлема 70 защиты от мили.
Следовательно, от прямого урона он даёт защиту в 3.5 + 70%, а от урона по пойзу - 70%. Следовательно, мало того, что урон по пойзу снижается втрое, стоит учитывать ещё и его реген. Так что, грубо говоря, уронить/вырубить человека в РИОТ-шлеме сложнее, чем голого, где-то в три с половиной раза, если он стоит и ловит удары по КД и раз в пять-шесть, если уверенно маневрирует. 
Но если уже упал и ловит тяжёленьким по голове - вырубается хоть и на меньшее время, чем без шлема, но всё равно надолго.

2020-05-21 14:21 UTC, Moscowchief commented
Андерстендбл.

2020-05-21 16:09 UTC, merged