Выпил размерных трейтов
ChaoticOnyx/OnyxBay pull request #2558
Opened 2020-05-31 00:37 UTC by TobyThorne

Трейты, влияющие на размер работают через жопу. 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-05-31 00:40 UTC, PlinHost commented
Также можно выпилить модификаторы размера, `icon_scale_percent` и связанную с ним логику, энивей иконки будут скейлиться через жопу.

2020-05-31 07:55 UTC, Voldirs commented
Поддерживаю, ресайз спрайтов это была худшая идея. Надо только чтобы сетапы у людей не наебенились.

2020-05-31 09:12 UTC, dnivji commented
Блять, ну нет.

2020-05-31 09:16 UTC, Animesku commented
Ну реально ж жопа

2020-05-31 10:09 UTC, TobyThorne commented
> Поддерживаю, ресайз спрайтов это была худшая идея. Надо только чтобы сетапы у людей не наебенились.

Не наебенятся. К счастью, трейты написаны более-менее адекватно.

2020-05-31 14:52 UTC, Epicus7 commented
Модификаторы эти хранятся же в сейвах? Надо проверить, что будет если сохранить персонажа с трейтом, выпилить трейты, запустить сервер и попробовать загрузить персонажа.

Возможно наебенится сейф и это очень плохо. Надо убедиться, что этого не происходит.

2020-05-31 14:52 UTC, Epicus7 requested changes
Нужно проверить, что корректно работает с сейв-файлами.

2020-05-31 15:07 UTC, TobyThorne commented
> Нужно проверить, что корректно работает с сейв-файлами.

Проверил несколько раз. Нормально работает, персонаж теряет трейт и больше не меняет размер. Продолжает ли оно храниться в сейвфайле в качестве мусорной переменной - это уже другой вопрос.

2020-05-31 15:28 UTC, Epicus7 approved these changes
Нуок, если проверил.

2020-05-31 20:23 UTC, TapKo4eB commented
![изображение](https://user-images.githubusercontent.com/48761132/83361902-ab713880-a395-11ea-9994-6e0b1873fd28.png)

2020-06-02 10:42 UTC, TapKo4eB approved these changes
проверил, невидимых челиков нету

2020-06-02 10:42 UTC, merged