Armorcleanup
ChaoticOnyx/OnyxBay pull request #2687
Opened 2020-06-10 10:51 UTC by TobyThorne

Вычищаем мусор из билда, делаем капитана полезным, баффаем оставшуюся броню.

- Переработана броня капитана. Теперь она - войдсьют и имеет свой, новый шлем. Старый шлем остался, но уже больше не космический, но с отличной защитой. Исправлены дырки на месте рук, из-за которых при надевании брони показывались голые руки (ибо перчатки скрываются). Спрайт чутка отредактирован, в особенности - у тонколюдей.
![image](https://user-images.githubusercontent.com/45202681/84257796-bbc4a880-ab37-11ea-924f-ab7c2bf28ac1.png) 
![image](https://user-images.githubusercontent.com/45202681/84258763-48239b00-ab39-11ea-846d-bd8b6d580140.png)
- Переделан спрайт РИГа СБ. Старый - какое-то жуткое месиво, перерисовывать его для тонколюдей не осилил. В итоге собрал заново по кусочкам, адекватно поделил на раздельные части, отрисовал под тонколюдей. От старого почти не отличается.
![image](https://user-images.githubusercontent.com/45202681/84258008-0e9e6000-ab38-11ea-8bd6-8ea0ab50df6d.png)
- Стандартизированы спрайты основных шлемов. Помимо этого, у них теперь есть визор, переключаемый тыком в руке. Функций кроме декоративной не имеет. Для модников.
![image](https://user-images.githubusercontent.com/45202681/84258709-32ae7100-ab39-11ea-9deb-c42954a4d310.png)
- Нахуй выкинуты жилеты со встроенными кармашками. Уже есть модульная система, позволяющая вешать кармашки на обычные жилеты/керриеры.
- Нахуй выкинута тактическая броня. Логики в её присутствии нет - болотный камуфляж в условиях космической станции. С точки зрения геймплея - тоже тупость какая-то, лёгкий бафф обычной брони. 
- Нахуй смержены дублирующиеся жилетики в armor и armor/vest.
- Нахуй выкинуты броньки/наклейки/etc. несуществующих в нынешнем бэке шарашек.
- Нахуй выкинуты тонны неиспользуемых спрайтов из раздела suits, остальное чутка потрогал, но полностью чистить пока что сил не хватит.
- Нахуй выкинуты mirania-шмотки, чем бы они не были.
- Нахуй выкинуты синие варианты СБшной униформы. Это ж не Советы в 2013, ей-богу.
- Пофикшены тонкоспрайты для тяжёлого РИГа Синдиката и коричневого тренча (имелся встроенный галстук, которого нет у обычного спрайта).
- Оба варианта плаща детектива переименованы в "detective's trenchcoat", обновлено описание.
- Изменены лодаутные плащи. Используют старые названия, новое описание и ничтожные показатели брони. Нынешние 50 мили-защиты из лодаута - как-то не очень.
- Куски кода брони более-менее отсортированы в соответствующие файлы из разных зажопных местечек.
- Содержимое ящиков СБ, детектива, вардена, ХоСа, ХоПа и капитана отсортировано по типам.

Попутно откалиброваны показатели брони в сторону стандартизации. И полезности специализированной брони из оружейки.
Формат: MELEE, BULLET, LASER.
- Обычная броня (и средняя плитка): 35, 35, 35
- Тяжёлая плитка: 60, 60, 60
- Плащ детектива: 40, 40, 40
- Плащ вардена: 50, 50, 50
- Шмот ХоСа: 65, 65, 65
- Скафандр СБ: 60, 40, 40
- Скафандр ХоСа: 70, 50, 50
- Скафандр капитана: 75, 60, 60
- РИОТ-броня: 80, 35, 35
- Баллистическая броня: 35, 85, 35
- Абляционная броня: 35, 35, 85
Последние три наконец стали полезными, ибо дают почти полную защиту от соответствующего типа урона. Ну и стандартную - от остальных.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [?] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-06-10 11:07 UTC, kokokobold commented
>Нахуй выкинуты синие варианты СБшной униформы. Это ж не Советы в 2013, ей-богу.

Ужасно.

2020-06-10 11:12 UTC, MrMagick2104 commented
> Плащ детектива: 40, 40, 40

Не жирно давать детективу бронежилет ++ вместо плаща? Лучше бы как обычный бронежилет его сделать, имхо. Детективу он нужен для защиты, а не как улучшенная броня СБ, нет?

2020-06-11 06:56 UTC, TobyThorne commented
- Дефективское пальто снижено до уровня обычного жилета (35, 35, 35)
- У обычных скафандров убрано замедление, давая им преимущество перед войдсьютами.
- Замедление аварийных скафандров снижено с 4 до 3. Учитывая замедления от всяких ранок и прочего, использовать их практически невозможно.

2020-06-11 08:33 UTC, MrMagick2104 commented
> У обычных скафандров убрано замедление, давая им преимущество перед войдсьютами.

Обычные скафандры - это кто?
Софтсьюты?

2020-06-11 22:37 UTC, PlinHost commented
Линк на иссуй автоматически закроет иссуй при принятии ПРа, спасибо, гитхаб.

2020-06-16 11:34 UTC, TapKo4eB commented
напоминаю
![изображение](https://user-images.githubusercontent.com/48761132/84769337-57459580-afde-11ea-991c-b1ee8a5e475e.png)

2020-06-21 11:45 UTC, PlinHost commented
virgin броня детектива:
UPPER_TORSO|LOWER_TORSO
melee = 35, bullet = 35, laser = 35, energy = 15, bomb = 25, bio = 0, rad = 0

chad пальто детектива:
slots = 2, slot_size = 2
UPPER_TORSO|LOWER_TORSO|ARMS
melee = 35, bullet = 35, laser = 35, energy = 20, bomb = 25, bio = 0, rad = 0

2020-07-17 10:44 UTC, TobyThorne commented
ПР обновлён.
Броня жилетика поднята до 40/40/40, детективский плащ остался с 35/35/35, добавил лампочек и выключателей туда, где их не хватало.

2020-07-19 07:38 UTC, kokokobold commented
>Нахуй выкинуты синие варианты СБшной униформы. Это ж не Советы в 2013, ей-богу.

Категорически против. Цвет хороший, зачем выпиливать?

>/obj/item/clothing/suit/storage/toggle/forensics/customred //Custom item

Тоже кастомка Булата вообще-то.
А так изменения хорошие во многом, одобряю!

2020-07-19 08:11 UTC, TobyThorne commented
> Категорически против. Цвет хороший, зачем выпиливать?

Потому что не используется, а только захламляет билд. Если вдруг кто-то захочет полностью перекрасить СБ в синий - нарисовать/найти униформу будет не самой сложной проблемой.

> Тоже кастомка Булата вообще-то.

Да блядь. Когда уже подписывать научатся.

2020-07-19 10:35 UTC, TobyThorne commented
- Добавлен пол под окна в техах у отбытия.

2020-07-21 13:10 UTC, TapKo4eB requested changes

2020-07-21 13:10 UTC, TapKo4eB commented on code/modules/clothing/under/jobs/security.dm
> +	icon_state = "jensen"
`item_state = "jensen"` забыл
![изображение](https://user-images.githubusercontent.com/48761132/88058145-bcefe900-cb6b-11ea-8026-2b155e215be5.png)

2020-07-21 13:10 UTC, TapKo4eB commented on code/modules/mob/living/bot/ed209bot.dm
> +			if(istype(W, /obj/item/clothing/suit/storage/vest) || istype(W, /obj/item/clothing/suit/armor/pcarrier) || istype(W, /obj/item/clothing/accessory/armorplate))
удалил весты но почему-то кучу связанного кода с ним (`/obj/item/clothing/suit/storage/vest`) оставил.
/obj/item/clothing/suit/armor/vest/old на /obj/item/clothing/suit/armor/vest мб

2020-07-21 15:12 UTC, TobyThorne commented on code/modules/clothing/custom_clothing.dm
> +		return 0
Это чужой кастомный чудокод, не хочу его трогать.

2020-07-21 15:14 UTC, TobyThorne commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/nt
Оно давным-давно в таком состоянии, всем норм вроде. Другое дело - зачем вообще нужны дебильные нашлемные тряпки.

2020-07-21 15:23 UTC, TobyThorne commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/hos/jensen/custom
Не был уверен, что это именно опухшая кастомка.

2020-07-21 15:40 UTC, TobyThorne commented on code/modules/clothing/custom_clothing.dm
> +		return 0
Скорее всего, проверяет на каждый слот.

2020-07-21 16:36 UTC, TobyThorne commented on code/modules/clothing/custom_clothing.dm
> +	icon_state = "helmet_police"
Поправил.

2020-07-21 16:36 UTC, TobyThorne commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/hos/german
Поправил.

2020-07-21 16:36 UTC, TobyThorne commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/swat/officer
Исправил.

2020-07-21 16:36 UTC, TobyThorne commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/hos/jensen/custom
Переместил.

2020-07-21 16:37 UTC, TobyThorne commented on code/modules/clothing/under/jobs/security.dm
> +	icon_state = "jensen"
Добавил item_state_slots = list(slot_hand_str = "jensen")

2020-07-21 16:42 UTC, TobyThorne commented on code/modules/mob/living/bot/ed209bot.dm
> +			if(istype(W, /obj/item/clothing/suit/storage/vest) || istype(W, /obj/item/clothing/suit/armor/pcarrier) || istype(W, /obj/item/clothing/accessory/armorplate))
Сторажи почистил, vest/old вроде и так нигде не остался.

2020-07-22 13:05 UTC, TapKo4eB submitted a review, later dismissed
ну вроде приколов больше по коду не нашёл

2020-07-22 13:26 UTC, Ruforce commented
В чём прикол желания выпиливать ВСЁ? 
Пиздец какой-то, лучше бы баги шёл фиксить

2020-07-22 13:28 UTC, Ruforce commented
Кастомный жилет татарина не вижу. Который vest/police.

Шлем есть, плитника нет.

2020-07-22 14:54 UTC, TapKo4eB commented on code/modules/clothing/suits/armor.dm
> -	armor = list(melee = 40, bullet = 40, laser = 45, energy = 15, bomb = 30, bio = 0, rad = 0)
кастомки в кустах

2020-07-22 15:04 UTC, TapKo4eB commented
подожди-ка секунду

>Нахуй выкинуты жилеты со встроенными кармашками. Уже есть модульная система, позволяющая вешать кармашки на **обычные жилеты**/керриеры.

мб ты имеешь под жилетами ввиду джапсьюты а может быть ты немного ошибаешься т.к.
```
/obj/item/clothing/suit/armor/vest
	name = "armor"
	desc = "An armored vest that protects against some damage."
	icon_state = "onyxvest"
	(...)
	armor = list(melee = 40, bullet = 40, laser = 40, energy = 15, bomb = 25, bio = 0, rad = 0)
	valid_accessory_slots = list(ACCESSORY_SLOT_INSIGNIA) <<<========
```

2020-07-22 15:55 UTC, Ruforce commented
И карманы кастомке верни. Что за мода пошла - выпиливать все карманы?

2020-07-22 16:06 UTC, TapKo4eB commented
их там две штуки

2020-07-23 12:59 UTC, TapKo4eB approved these changes
ладно потом докачаем допилы

2020-07-23 13:10 UTC, Epicus7 approved these changes

2020-07-25 13:24 UTC, merged