Интеграция с вики
ChaoticOnyx/OnyxBay pull request #2834
Opened 2020-06-27 01:48 UTC by Pos13

**Внимание! Для корректной работы в файле конфигурации _config\config.txt_ должен быть прописан параметр WIKIURL:**
`## Wiki URL`
`WIKIURL https://wiki.ss13.ru`
Именно в таком виде, без слэша в конце.

### Изменения в игре
1. **Библиотекарь получает возможность распечатывать некоторые статьи из вики.**
Данная возможность работает по аналогии с печатью обычных книг: сначала консоль печатает "бумагу", которая играет роль заготовки для будущей книги; потом переплётная машина позволяет превратить её в "книгу". Статьи, доступные для печати, регулируются вне кода, вот этим списком: [Available in library](https://wiki.ss13.ru/index.php?title=Категория:Available_in_library).
_Заготовка:_
![image](https://user-images.githubusercontent.com/64479446/85908299-3a4e6500-b81d-11ea-9111-ff2c286ce03f.png)
_Готовая книга:_
![image](https://user-images.githubusercontent.com/64479446/85908311-44706380-b81d-11ea-9ba7-ab593d0da584.png)
Вы могли не знать, но, если расположить переплётную машину рядом с консолью, то обычные книги будут печататься сразу в ней, мгновенно. Это правило выполняется и при распечатке статей из вики.

2. **Емагнутая консоль открывает доступ к дополнительным статьям.**
Если быть точным, то к статьям из этого списка: [Available in hacked library](https://wiki.ss13.ru/index.php?title=Категория:Available_in_hacked_library).
Более того, содержимое некоторых статей будет расширено. (Точнее, содержимое некоторых статей, распечатанных на _невзломанном_ компьютере, будет частично скрыто. Подробности ниже, в разделе "Изменения в вики")

3. **Владельцы ноутбуков и планшетов тоже получают возможность печатать статьи, но с оговорками.**
Можно скачать программу "Knowledge base", аналогичную программе на компьютере библиотекаря. Но, при печати с помощью встроенного принтера (если он есть), получается неудобная для чтения заготовка. Её можно превратить в полноценную книгу только в переплётной машине.
Как вариант, владелец портативного компьютера может просто встать рядом с переплётной машиной - книги сразу будут печататься в ней.
Емагнутые портативные компьютеры работают с программой аналогично емагнутой консоли.
![image](https://user-images.githubusercontent.com/64479446/85908930-04f74680-b820-11ea-805e-7ea877114aaa.png)
4. **Отдельный класс для вики-книг.**
Хотите создать инструкцию для ~~бес~~толковых работников? Нет ничего проще:
`/obj/item/weapon/book/wiki/alarms`
       **`topic = "Standard Operating Procedure"`**
       `title = "What to do then everything is bad and you are the boss"`
       `icon_state = "bookSolGolLaw"`
Такая книга при открытии автоматически загрузит содержимое статьи "Standard Operating Procedure".

"Книжное представление" вики-статьи не содержит никаких ссылок, вообще. Все элементы вики-интерфейса срезаны. Так что "сидеть в интернете через спейслоу" больше не выйдет. Дополнительный бонус: все загрузки и парсинг осуществляются на клиенте, с помощью _javascript_ и _MediaWiki API_.
![image](https://user-images.githubusercontent.com/64479446/85909676-b21f8e00-b823-11ea-8257-8cf7288e53b4.png)

5. **Заменены встроенные в код мануалы.**
Вместо устаревших англоязычных мануалов с захардкоженным текстом теперь книги, подгружающие соответствующий контент из вики. Иконки, заголовки и описания не пострадали, внешне всё по-прежнему. В основном замены достаточно прямолинейные (вроде _Barman Recipes_, открывающего [Guide to Drinks](https://wiki.ss13.ru/index.php?title=Guide_to_Drinks)). Вот некоторые особенные случаи:

- Для мануалов, не имеющих аналогов, созданы соответствующие статьи на вики (см. [Diona Harvest](https://wiki.ss13.ru/index.php?title=Diona_Harvest) и [Brief Chemist Guide](https://wiki.ss13.ru/index.php?title=Brief_Chemist_Guide));
- Мануалы о клонировании и криосне вырезаны;
- Россыпь бесполезных микро-книг на высшем ~~эльфийском~~ английском о перспективах и прикладных применениях науки исследования аномалий заменена на [Guide to Xenoarchaeology](https://wiki.ss13.ru/index.php?title=Guide_to_Xenoarchaeology).

### Изменения в вики
1. **Категория статей, доступных для печати в игре:  [Available in library](https://wiki.ss13.ru/index.php?title=Категория:Available_in_library).**
Добавление или удаление статьи из этой категории автоматически разрешит или запретит её печать в игре.
Для регулирования статей, доступных для печати с емагнутой консоли, есть категория [Available in hacked library](https://wiki.ss13.ru/index.php?title=Категория:Available_in_hacked_library).
Чтобы добавить статью в категорию, откройте её на вики, нажмите "править" и добавьте в конец текста [[Category:Available in library]].
2. **Шаблон {{Ingame}}.**
![image](https://user-images.githubusercontent.com/64479446/85910505-eac16680-b827-11ea-88f0-84094357f016.png)
- Название книги, заданное в плашке, переносится в игру (применяется при первом открытии книги);
- Весь текст, расположенный выше плашки, вырезается. Это позволяет скрыть нежелательные части (другие плашки или вступительные слова вроде "Не стоит пытаться играть завхозом, не приобретя для начала опыт работы грузчиком, иначе у вас есть шанс запороть раунд.");
- Плашка просто побуждает редакторов осторожнее выбирать выражения.

_Примечание_: в коде предусмотрена, но выключена возможность запретить просмотр страниц, не помеченных такой плашкой.

Более подробно использование этой плашки описано в её статье: [Шаблон:Ingame](https://wiki.ss13.ru/index.php?title=Шаблон:Ingame).

3. **Шаблон {{NT Censorship|}}**
![image](https://user-images.githubusercontent.com/64479446/85911190-5279b080-b82c-11ea-8e5e-23384d773d6f.png)
В такой шаблон включается всё, что должно избежать взгляда верного корпоративного работника. Содержимое становится видимым только при печати со взломанного компьютера. Рамочку, впрочем, видят все - пусть игроки видят, что здесь прячется что-то интересное!
![image](https://user-images.githubusercontent.com/64479446/85911300-2579cd80-b82d-11ea-9ec8-3ca5c59f165b.png)

Более подробно использование этой плашки описано в её статье: [Шаблон:NT_Censorship](https://wiki.ss13.ru/index.php?title=Шаблон:NT_Censorship).

Всё.

close #2674 #2799 #2780

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-06-27 01:53 UTC, Doster-d commented
Хочу, хочу, хочу! Это мастхев!

2020-06-27 02:37 UTC, ArmolitskiyCarpoeb commented
Просто. Ахуенно. Отличная работа!

2020-07-01 15:39 UTC, Doster-d commented
Дорогие старые друзья, помните этот ПР

2020-07-02 20:01 UTC, Epicus7 requested changes

2020-07-02 20:01 UTC, Epicus7 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +		if(istype(nano_host(), /obj/item/modular_computer) && !nano_host():nano_printer)
И тут двоеточие.

2020-07-03 00:21 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +/obj/item/weapon/book/wiki/Initialize(mapload, ntopic, ncensored, nstyle)
> Что это за странная n в начале аргументов?

Чтобы избежать путаницы. Я уже видел такое где-то в коде.

> Алсо что это вообще такое, откуда вызывается Initialize и откуда берутся аргументы?

Я просто следовал [рекомендации из Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D0%B9%D1%82%D0%B5-initialize-%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%BE-new-%D0%B4%D0%BB%D1%8F-atom-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%89%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B5). Аргументы вполне корректно передаются при вызове _new_. Объекты, изначально размещённые на карте, тоже выглядели созданными верно.

2020-07-03 00:23 UTC, Epicus7 commented on code/modules/library/lib_items.dm
> +/obj/item/weapon/book/wiki/Initialize(mapload, ntopic, ncensored, nstyle)
Покажи, пожалуйста, место, где ты создаешь книги с этими четыремя аргументами. Я не нашел.

2020-07-03 00:34 UTC, Pos13 commented on code/modules/library/manuals.dm
> +// -----
Сверху - заранее описанные в коде книги, которые предназначены для размещения на карте. С прописанным заголовком, автором, собственной иконкой.
Снизу - книги, у которых нет отличительных черт, но для которых после печати желательно поменять параметры - ширину окна или стиль текста. Для читаемости.
Для книг, не имеющих особенностей, подклассы не требуются.

2020-07-03 00:42 UTC, Pos13 commented on code/modules/library/lib_machines.dm
> +		book.layer = src.layer + 0.01 // Prevents spawning under bookbinder
Все машины в библиотеке, включая переплётную машину, консоль и даже мусорку, лежат на слое OBJ_LAYER (layer=3). Вообще, если ткнуть на станции в случайную машину, она, скорее всего, лежит на слое 3. Короче, я не менял слой переплётной машины по-умолчанию, так как не знаю, почему для всех **/obj/machinery** он равен 3.

2020-07-03 00:43 UTC, Pos13 commented on code/modules/library/lib_machines.dm
> +		book.layer = src.layer + 0.01 // Prevents spawning under bookbinder
Можно сразу прописать **layer = BELOW_OBJ_LAYER** либо для всех машин, либо только для переплётной. Но я не знаю, не сломается ли что-нибудь.

2020-07-03 00:44 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +					new_book.desc = current_book["author"]+", "+current_book["title"]+", "+"USBN "+current_book["id"]
Копипаста.

2020-07-03 00:51 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +/obj/item/weapon/book/wiki/Initialize(mapload, ntopic, ncensored, nstyle)
**lib_machines.dm**:
`/obj/machinery/bookbinder/proc/print_wiki(topic, censorship)`
`      var/obj/item/weapon/book/wiki/book`
`      if(topic in GLOB.premade_manuals)`
`            var/manual_type = GLOB.premade_manuals[topic]`
**`            book = new manual_type(src.loc, topic, censorship)`**
`      else`
**`            book = new /obj/item/weapon/book/wiki(src.loc, topic, censorship, WIKI_MINI)`**
`            book.icon_state = "book[rand(1,7)]"`
`      if(book.layer <= src.layer)`
`            book.layer = src.layer + 0.01 // Prevents spawning under bookbinder`
`      return book`
**library.dm**:
`/datum/nano_module/wiki/Topic(href, href_list)`
...
`// Regular print (creates book template)`
`if(istype(nano_host(), /obj/item/modular_computer) && !nano_host():nano_printer)`
`      to_chat(usr, SPAN_DANGER("Error: No printer detected. Unable to print document."))`
`      return 1`
**`new /obj/item/weapon/book/wiki/template(get_turf(nano_host()), href_list["topic"], emagged ? 0 : 1)`**
`return 1`

2020-07-03 00:57 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +	var/emagged = host && (istype(host, /obj/item/modular_computer) || istype(host, /datum/computer_file/program)) ? host:computer_emagged : 0
> Какой-то синтаксический ад. Во-первых, host ты выше используешь, так что он не может быть null, иначе у тебя рантайм раньше случится.

Уберу проверку.

> Во-вторых, опять ты используешь запрещенный оператор : .

Его использование оправдано. У **/obj/item/modular_computer** и **/datum/computer_file/program** есть переменная с одинаковым названием **computer_emagged**, играющая одну и ту же функцию.

> В-третьих, вместо 0 должен быть FALSE здесь.

Переменная затем используется в коде на javascript. Я хочу быть точно уверен, что там 0 или не 0.

2020-07-03 10:32 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +	var/width = 650
Сделал

2020-07-03 10:33 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +		user << browse(dat, "window=book_[title];size=[width]x650")
Теперь по дефолту **title = "Untitled"**

2020-07-03 10:33 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +		M << browse(dat, "window=book_[title];size=[width]x650")
Теперь по дефолту **title = "Untitled"**

2020-07-03 10:39 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +/obj/item/weapon/book/wiki/Initialize(mapload, ntopic, ncensored, nstyle)
Кстати, попробовал использовать **src.censored = censored** вместо использования **ncensored**, но получил странное поведение. Что было не так - не знаю, упорствовать не стал.

2020-07-03 10:40 UTC, Pos13 commented on code/modules/library/lib_machines.dm
> +			print_wiki(O:topic, O:censored)
Убрал. **O:info**, кстати, было в старом коде.

2020-07-03 10:42 UTC, Pos13 commented on code/modules/library/lib_machines.dm
> +		book.layer = src.layer + 0.01 // Prevents spawning under bookbinder
Короче, задал всем машинам по дефолту **layer = BELOW_OBJ_LAYER**, не стал мелочиться. На вид всё нормально, мусорки из экрана в лицо не выпрыгивают.

2020-07-03 10:42 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +#define WIKI_HACKED_CATEGORY "Available_in_hacked_library"
Сделал.

2020-07-03 10:44 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +	var/emagged = host && (istype(host, /obj/item/modular_computer) || istype(host, /datum/computer_file/program)) ? host:computer_emagged : 0
Исправил.
Заменил одну красивую строчку на семь обычных.
Грустное двоеточие не любит тавтологию и грустит -> **:(**

2020-07-03 10:44 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +		var/emagged = host && (istype(host, /obj/item/modular_computer) || istype(host, /datum/computer_file/program)) ? host:computer_emagged : 0
Исправил

2020-07-03 10:45 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +		if(istype(nano_host(), /obj/item/modular_computer) && !nano_host():nano_printer)
Исправил

2020-07-05 10:21 UTC, Epicus7 commented on code/modules/library/lib_items.dm
> +/obj/item/weapon/book/wiki/Initialize(mapload, ntopic, ncensored, nstyle)
Прикольно, Initialize вызывается из New со всеми аргументами. Я даже не знал про это.

Ладно, пофиг.

2020-07-05 10:30 UTC, Epicus7 submitted a review, later dismissed

2020-07-08 23:21 UTC, MemoryDreams commented
Это большая ошибка. Не надо. Не делайте этого. Давайте сделаем нормальные гайды, нв которые игроки смогут ссылаться в диалогах, а не вики странички, которые никто и никогда не будет открывать в игре.
Одумайтесь. Ими никто, никогда не пользовался. Это большая ошибка. Особенно с учётом того, что сента принял решение об ограничении информации на вики. Это просто не имеет смысла.
Это большая ошибка и я хочу наложить на это вето.

2020-07-09 20:56 UTC, Pos13 commented
> Это большая ошибка. Не надо. Не делайте этого. Давайте сделаем нормальные гайды, нв которые игроки смогут ссылаться в диалогах, а не вики странички, которые никто и никогда не будет открывать в игре.
> Одумайтесь. Ими никто, никогда не пользовался. Это большая ошибка. Особенно с учётом того, что сента принял решение об ограничении информации на вики. Это просто не имеет смысла.
> Это большая ошибка и я хочу наложить на это вето.

Нормальные гайды теперь можно будеть писать с помощью вики. Не нужно будет быть кодером, чтобы поменять или внести текст своей книги (как было раньше с захардкоженными руководствами)
К тому же, содержимое таких вики-книг не похоже на интернет-страницу, и её название можно регулировать через плашку {{Ingame}}. Короче, нет проблемы упомянуть такую в разговоре.

2020-07-10 08:53 UTC, MemoryDreams commented
> > Это большая ошибка. Не надо. Не делайте этого. Давайте сделаем нормальные гайды, нв которые игроки смогут ссылаться в диалогах, а не вики странички, которые никто и никогда не будет открывать в игре.
> > Одумайтесь. Ими никто, никогда не пользовался. Это большая ошибка. Особенно с учётом того, что сента принял решение об ограничении информации на вики. Это просто не имеет смысла.
> > Это большая ошибка и я хочу наложить на это вето.
> 
> Нормальные гайды теперь можно будеть писать с помощью вики. Не нужно будет быть кодером, чтобы поменять или внести текст своей книги (как было раньше с захардкоженными руководствами)
> К тому же, содержимое таких вики-книг не похоже на интернет-страницу, и её название можно регулировать через плашку {{Ingame}}. Короче, нет проблемы упомянуть такую в разговоре.

Внутреигровые книги и гайды на вики написаны на разных языках. Их нельзя мешать. Это будет ломать атмосферу.

2020-07-10 09:33 UTC, MrMagick2104 commented
> Внутреигровые книги и гайды на вики написаны на разных языках. Их нельзя мешать. Это будет ломать атмосферу.

Те статьи, что попадают в игру, должны быть изначально переделаны и на них должна быть плашка {{Ingame}}.
При этом, ООЦ-материалы из статьи, если помечены, в книге показываться _не будут_, но в интернет-статье видны _будут_. В чём проблема-то?

2020-07-10 10:03 UTC, MemoryDreams commented
Это большая ошибка.

2020-07-10 10:04 UTC, MrMagick2104 commented
Аргументируй.

2020-07-10 10:42 UTC, MemoryDreams commented
It feels wrong. Идеальным решением было бы склонить игроков к написанию собственных гайдов, сильно ограниченных по полноте информации, но дающие разные перспективы на разные проблемы. Унифицированные гайды убирают всякую нужду в разбирательстве что и как работает. Я считаю, что на вики должна быть только информация об управлении и всяких условностях, которые просто нельзя рассказать непосредственно в игре. 
Унифицированные гайды это от лукавого и я против такого решения.

2020-07-10 10:44 UTC, TobyThorne commented
> склонить игроков к написанию собственных гайдов

Аха. У нас половина игроков и три слова без ошибок написать не могут, а ты про запиливание гайдов.

2020-07-10 10:49 UTC, MemoryDreams commented
> Аха. У нас половина игроков и три слова без ошибок написать не может, а ты про запиливание гайдов.

Пока есть игроки, которые готовы заниматься вики, гайды писать будет кому.

2020-07-10 11:02 UTC, MrMagick2104 commented
> склонить игроков к написанию собственных гайдов

Игроки это никогда не будут делать. Почему? Да просто потому, что они в любом случае создают небольшие или большие объединения по знаниям и обмениваются ими, неизбежно. Или берут идеи от других. Или ещё что-то.
И делают они без гайдов. Просто потому что обмен информации в игре или ООЦ - намного быстрее и проще, к нужным людям, а писать гайды никому не приелось, кроме особых людей - викиврайтеров. Не могу их судить, зачем они это делают, но, однозначно, это - полезно, если информация в них верная **И** гайды написаны максимально общим языком.
Такой гайд понадобится в виде книжки уборщику, который решил настроить суперматирию сам или что-то такое, просто чтобы станция не сидела без света, а он - единственный, кто может это сделать, хотя он и не умеет это делать ни в ООЦ, ни в ИС, возможно.
И гайд с вики ему _должен_ помочь в этом, потому что это - задача гайда с вики - помогать новичкам, как ИЦ, так и ООЦ.
А если гайды будут писать игроки, то выйдет херня в любом случае:
-Они не будут писать гайды, это раз, т.к. если бы писали, то и на вики бы у нас тоже активности было больше, чем от трёх людей максимум
-Какой гайд положить рядом с суперматерией, чтобы уборщик мог прийти, прочитать, кое-ка настроить? Чьего авторства? Он должен быть максимально простой, понятный и эффективный.
Если всем вместе решать, то тогда это будет избыточность, ведь можно просто подлатать статью на вики так, чтобы она удовлетворяла условиям для гайда выше, после чего портировать её на станцию.
-Даже если вот эту конкретную фичу запилят, что мешает игрокам пилить гайды в IC, либо пилить их в OOC на вики, создавая новые книжки, доступные игрокам? Я думаю, если в сента пропихнуть идею, то можно вполне себе добавить возможность создания таких "коммьюнити-мейд" гайдов, с некоторой цензурой со стороны сената/хедвики (которого у нас нет?)
-Продолжая случай с суперматерией: большинство инженеров, если и будут, то будут делать гайды _непонятными_ простому уборщику или новичку, из-за чего он материю может настроить _неправильно_, вместо среднего гайда.
-Если говорить о том, что унифицированные гайды - плохо, потому что игроки будут тупо следовать по нему, то это будет ложью. Большинство тех же инженеров от самого начала и до самого конца забивало на гайд суперматерии, где ни слова не было сказано ни о коллекторах в реакторе, ни о фороне, etc.
Все так всё равно делали, даже несмотря на в своё время 'outdated' гайд по суперматерии.
Зачастую, такие гайды для новичков, а не для большинства.


В чём проблема давать возможность давать игрокам общие гайды, хорошо реализованные как тут, в IC и OOC, а также дать им возможность писать свои гайды (которая уже есть, ага)?
Только тут будет преимущество в том, что уборщик будет тупить не в браузер в альт-табе, а в книжку в игре, что лучше, как минимум, по двум причинам:
-Это логичнее с точки зрения игрового мира, знания у уборщика не появляются от Аллаха, а из книжки.
-Альттабаться неудобно в любом случае, если у человека не два монитора, то он полностью отстраняется от мира вокруг.

А ещё это уже закожено и имплиментировано, потому, почему нет? От этого только плюсы ведь.

> Пока есть игроки, которые готовы заниматься вики, гайды писать будет кому.

А ты можешь сказать, сколько людей занимается вики сейчас, в сравнении с ежедневным онлайном? А ещё, кто у нас хедвики?

2020-07-10 13:01 UTC, MemoryDreams commented
> А если гайды будут писать игроки, то выйдет херня в любом случае

О чём ты говоришь? Их всегда писали и пишут до сих пор игроки. 
Проблема стены текста, которую ты написал в том, что ты всё время ссылаешься на пример с суперматерией, тогда как она является скорее исключением (даже в правилах уборщик настраивающий суперматерию вынесен как исключение). Нет ни одного случая кроме суперматерии, когда такие гайды будут к месту, потому что ни один гайд кроме суперматерии не является необходимым для обеспечения нормальной работы станции. Возьмём, к примеру, химию или ксенобиологию. Максимум информации, который можно поместить в такой гайд для этих отделов, это описания, какие аппараты для чего нужны. Но вот вопрос, если игрок вступает в раунд химиком или ксенобиологом, не зная, что гриндер нужен для измельчения твёрдых вещей, например, то возникает вопрос, а что он забыл на этой профессии? В то же самое время, любой другой член экипажа, ассистент, например, просто ничего не сможет сделать без знаний конкретных рецептов. Ну и зачем это нужно, спрашивается? 

Да и даже в случае с материей, этими гайдами просто не будут пользоваться. Вспомни себя в первые недели игры. Ты эти книжки либо не замечал, либо открывал единожды и со словами "Ага, это кусочек вики. Пойду лучше полную версию открою" закрывал её, больше никогда не вспоминая о такой фичи. 

> Даже если вот эту конкретную фичу запилят, что мешает игрокам пилить гайды в IC, либо пилить их в OOC на вики, создавая новые книжки, доступные игрокам?

А зачем им пилить гайды, когда уже есть "золотой стандарт" в виде официальных гайдов? Такие вещи очень демотивируют заниматься и без того не самым благодарным занятием. Что нужно сделать, так это завлечь игроков к тому, чтобы они делились опытом. Провести какой-нибудь конкурс или вроде того. Но никак не заменять всё бездушным копированием вики.

2020-07-10 18:56 UTC, MrMagick2104 commented
> Нет ни одного случая кроме суперматерии, когда такие гайды будут к месту, потому что ни один гайд кроме суперматерии не является необходимым для обеспечения нормальной работы станции.

Да, но:
-Во-первых, это уже в _тысячи_ раз лучше, чем то, что есть сейчас. Это - удобная система для создания гайдов внутри игры без необходимости хардкодить их в игру, тем самым позволяя легко модифицировать их.
Куда проще сделать саму статью на вики при помощи удобного викидота или что у вас там, добавить картиночки, подогнать под шаблон, после посмотреть на результат, а только уже потом добавлять в игру, при этом без необходимости поднимать локалочку и качать гитхаб десктоп или бранч каждый раз, чтобы посмотреть на все изменения в процессе создания статьи, а потом просто добавить шесть строчек и гайд в билде.
Не обязательно даже портировать гайды в игру. Сама по себе система от ОП-а намного проще и удобнее для большинства пользователей и людей, которые будут делать гайды в будущем.
-Во-вторых, если есть прямая интеграция с вики, то это уже удобно для пользователя. Ему не нужно идти в браузер, открывать вики и искать там материал, когда он вполне себе может взять книжку из отдела и посмотреть нужный ему предмет.
Бывают просто такие ситуации, что забыл последовательность действий, допустим, сбора меха на робототехнике, либо её ещё не выучил, либо какого-нибудь другого предмета, где нужна чёткая последовательность действий.
Куда удобнее открыть книжку, валяющуюся рядом, в случае с робототехником, нежели искать гайд ту роботикс в интернете.

> Вспомни себя в первые недели игры. Ты эти книжки либо не замечал, либо открывал единожды и со словами "Ага, это кусочек вики. Пойду лучше полную версию открою" закрывал её, больше никогда не вспоминая о такой фичи.

В первый раз я материю сам настраивал с каким-то таким же гением, по книжке, а не по вики. 
И гайды по робототехнике той же, на первых неделях, я читал не только на вики, но и в книжках. Удивительно, но там тогда информации было больше, чем на вики.
Аргумент - инвалид.

> Возьмём, к примеру, химию или ксенобиологию. Максимум информации, который можно поместить в такой гайд для этих отделов, это описания, какие аппараты для чего нужны.

Мне нравится пример ксенобиологии. Внезапно, туда можно поместить таблицу слаймов с вики, потому что почему нет?
Ксенобиология же у нас филиал слаймренчера, а не отдел по исследованию неизвестных форм жизни. В особенности когда каждый второй ксенобиолог выводит слаймов по памяти, либо пользуется таблицей с вики.
Почему бы новичкам не упростить изучение ксенобиологии, добавив гайд прямо в игру, а тем, кто уже является адептом данной науки не добавить удобства в виде отсутствия необходимости лезть на вики?

Другой пример из этой же оперы - ксеноархеология. Опять же, личный опыт, но мне вот было крайне неудобно постоянно альттабаться, чтобы смотреть нужные вещи. Куда проще в книжке глянуть.

> А зачем им пилить гайды, когда уже есть "золотой стандарт" в виде официальных гайдов? Такие вещи очень демотивируют заниматься и без того не самым благодарным занятием. Что нужно сделать, так это завлечь игроков к тому, чтобы они делились опытом. Провести какой-нибудь конкурс или вроде того. Но никак не заменять всё бездушным копированием вики.

Чем эти гайды от коммьюнити лучше, чем "официальные" гайды с вики?
Кроме того, а почему бы не использовать удобную систему от ОП-а для интеграции гайдов от игроков? 

> Что нужно сделать, так это завлечь игроков к тому, чтобы они делились опытом. 

Как я уже писал в стене текста, игроки _уже_ делятся опытом друг с другом. Не знаю как остальные, но я вот каждый раунд, когда вижу в инженерном отделе как кто-то, кто делает что-то не по известным мне стандартам, спрашиваю, что он делает.
И не раз я брал небольшую команду из ассистентов (3 человека, считая меня) за инженера и показывал им разные вещи, связанные с инженерией (а также заставлял таскать баки с фороном). 
И во многих сферах так, новичков принимают довольно радушно в большинстве мест, по, опять же, моему опыту.
Люди хотят делиться опытом, это видно.
Но даже если я - человек, который хочет делиться опытом, то гайды я бы писать не стал. Почему?
Проблема, мне кажется, в том, что гайды, тем более ИЦ-гайды должны быть в крайне формальном стиле, сдерживаемом в общении. И, к тому же, намного сложнее донести суть без возможности сделать ООЦ-помарок в ЛООКе, например.
Передавать знания, отличные от базовых гайдами дико сложно из-за особенностей билда (🐛).

2020-07-10 21:32 UTC, pushpushmergerebase commented
В кои-то веки на ониксе завезли хорошую, красивую, грамотную фичу, а Мемори залупается. Не надо так.

2020-07-11 01:36 UTC, Pos13 commented
@MemoryDreams 
Я добавлю от себя несколько пояснений:
> Идеальным решением было бы склонить игроков к написанию собственных гайдов, сильно ограниченных по полноте информации, но дающие разные перспективы на разные проблемы. Унифицированные гайды убирают всякую нужду в разбирательстве что и как работает.

Теперь внедрить свой собственный гайд станет гораздо проще. Раньше для этого нужно было сделать форк, создать собственную книгу в коде и сделать Pull Request - вот это действительно _"демотивало заниматься и без того не самым благодарным занятием"_. Теперь можно будет просто создать/отредактировать статью на вики. Ты даже можешь заняться этим сам, все инструменты готовы и описаны в шапке. Если не нравится "унифицированный" гайд, можно исключить его из категории доступных для игры статей, а взамен включить другой, "урезанный".

> Внутреигровые книги и гайды на вики написаны на разных языках. Их нельзя мешать. Это будет ломать атмосферу.

Поздравляю! Теперь они будут написаны на одном языке и больше не будут ломать атмосферу!
Серьёзно, ты вообще заглядывал в эти старинные мануалы? Мало того, что эти кусочки английского текста были на сервере совершенно неуместны. Многие из них вдобавок были бессмысленны, неактуальны и практически бесполезны.

> Я считаю, что на вики должна быть только информация об управлении и всяких условностях, которые просто нельзя рассказать непосредственно в игре.

>  Но вот вопрос, если игрок вступает в раунд химиком или ксенобиологом, не зная, что гриндер нужен для измельчения твёрдых вещей, например, то возникает вопрос, а что он забыл на этой профессии?

Если новичку не хватает информации для игры, нужно ему помочь, а не бить ссанными тряпками.


И последнее - с интеграцией или без, игрок всегда может открыть вики в браузере во время игры. Мы не можем это ему запретить. Но мы можем создать условия, чтобы это не требовалось. Чтобы воспользоваться внитриигровой книгой было проще и интереснее. А уже над содержанием книг у нас будет полный контроль.

2020-07-19 07:56 UTC, kokokobold commented
Вещь хорошая, одобряю.

2020-07-20 07:14 UTC, PlinHost commented
> Давайте сделаем нормальные гайды, нв которые игроки смогут ссылаться в диалогах, а не вики странички, которые никто и никогда не будет открывать в игре.

Одно другому не мешает. Фича не заставляет использовать только гайды с вики, их можно вообще отключить.

2020-07-20 09:46 UTC, PlinHost reviewed
Жс, карту и спрайты не смотрел.

2020-07-20 09:46 UTC, PlinHost commented on code/modules/library/lib_items.dm
> +			var/obj/choice = contents[titles.Find(title)]
А нельзя здесь использовать ассоциативный список вместо индексов? Индекс может, например, устареть, пока ожидается `input`. И, я думаю, доставать должно быть можно только книги.

2020-07-20 09:46 UTC, PlinHost commented on code/modules/library/lib_items.dm
> +	desc = "Bunch of unbinded paper pieces."
```suggestion
	desc = "Bunch of unbound paper pieces."
```

2020-07-20 09:46 UTC, PlinHost commented on code/modules/library/lib_machines.dm
> +			..()
Почему родитель вызывается только если `operable()`? Он сам может проверить, если нужно.

2020-07-20 09:46 UTC, PlinHost commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +				bndr.print_wiki(href_list["topic"], emagged ? 0 : 1)
В топик могут напихать любой фигни, и я даже не знаю, как его проверить, потому что на сервере нет списка валидных статей.

2020-07-20 09:46 UTC, PlinHost commented on config/example/config.txt
> +WIKIURL https://wiki.ss13.ru
Лучше закомментированным оставить, мы же остальные юрл в примере конфига на свои не меняем.

2020-07-21 09:17 UTC, Pos13 commented on code/modules/library/lib_items.dm
> +			var/obj/choice = contents[titles.Find(title)]
~~Ассоциативный список нельзя, на полке может быть несколько книг с одинаковым названием.~~ Я не смог заставить input() выводить одинаковые названия, поэтому всё равно сделал ассоциативный список. Добавил проверку на случай, если полку сожрёт Нар-Си, пока игрок выбирает, что почитать.
> И, я думаю, доставать должно быть можно только книги.

Мало ли, что там потомки выдумают. Может, в contents будет хранится контрабанда.

2020-07-21 09:18 UTC, Pos13 commented on code/modules/library/lib_machines.dm
> +			..()
Исправил.

2020-07-21 09:18 UTC, Pos13 commented on code/modules/modular_computers/file_system/programs/generic/library.dm
> +				bndr.print_wiki(href_list["topic"], emagged ? 0 : 1)
Раскомментировал проверку на шаблон {{Ingame}} в JS. Теперь попытка открыть статью без шаблона будет заканчиваться вот таким сообщением: 
![image](https://user-images.githubusercontent.com/64479446/88035118-54dcdb00-cb4a-11ea-88fe-4704f6f1f0a6.png)
А попытка открыть несуществующую статью - сообщением "The page you specified doesn't exist".

2020-07-21 09:18 UTC, Pos13 commented on config/example/config.txt
> +WIKIURL https://wiki.ss13.ru
Исправил. Главное, чтобы на сервере не забыли поменять.

2020-07-21 10:18 UTC, Pos13 commented
Я смержил карты, но гит всё ещё говорит, что нет.

2020-07-21 10:23 UTC, Pos13 commented
После мапмержа теперь не получается скомпилировать билд, т. к. на карте есть объекты, отсутствующие в этом ПР.

2020-07-21 12:04 UTC, Pos13 commented
Конфликт карт разрешён.

2020-07-28 09:51 UTC, merged