Запрещаем инвестить поинты визардам находясь на не станционных Z-уровнях.
ChaoticOnyx/OnyxBay pull request #3041
Opened 2020-08-01 13:54 UTC by TapKo4eB

Некоторые особо умные игроки умудряются сидеть весь раунд у себя на базе, фармя себе поинты.

- Инвест нельзя прожать находясь не на станции.
- Инвест автоматически прерывается если спеллбук оказывается за пределами станции. С возвращением очков.

Напомню ещё раз, ПР не аффектит никакие другие системы спеллбука за исключением инвеста поинтов.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-01 14:17 UTC, TobyThorne commented on code/modules/spells/spellbook.dm
> +			src.visible_message(SPAN_WARNING("<b>\The [src]</b> emits a cranky chime."))
>SPAN_WARNING

Педик.

2020-08-01 14:19 UTC, PlinHost commented on code/modules/spells/spellbook.dm
> +			src.visible_message(SPAN_WARNING("<b>\The [src]</b> emits a cranky chime."))
нет ты

2020-08-06 13:04 UTC, TapKo4eB commented
Спеллбук хотя бы найти можно будет и спиздить.

2020-08-19 01:11 UTC, Epicus7 requested changes

2020-08-19 01:11 UTC, Epicus7 commented on code/modules/spells/spellbook.dm
> +				spellbook.max_uses = uses
```suggestion
			if(uses < spellbook.max_uses)
				uses++
```

2020-08-19 01:12 UTC, Epicus7 commented
> А что мешает спрятать спеллбук на станции, а самому отсиживаться?

За такой механодроч уже и забанить можно, за выход из роли. Щас бы выкинуть книжку на станции и куда-то съебаться. Зачем магу такое делать?

2020-08-21 04:22 UTC, Epicus7 approved these changes

2020-08-28 14:56 UTC, jammer312 approved these changes
Похоже на правду

2020-09-15 11:18 UTC, merged