Soap nerf'o'buff
ChaoticOnyx/OnyxBay pull request #3072
Opened 2020-08-04 13:56 UTC by TobyThorne

- Мыло теперь накидывает не 3, а 4 штуки стана;
- Мыло не накидывает стан, если цель лежит. На самом деле до сих пор можно катать на мыле, ибо обновление лежания - то ещё говно. Но есть шанс включить магбутсы, например.
- Мыло теперь может раздавиться при наступании с определённым шансом.
- Обычное мыло: 50%
- НТ-мыло: 50%
- Секурити-мыло: 50%
- Элитное мыло (aka кэпское): 20%
- Синдимыло: 25%
- ЗоЛоТоЕ мЫлО: 5%

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-04 15:56 UTC, Ershovdi commented
В землю занёрфили, сделайте пониже проценты.

2020-08-04 17:07 UTC, ArmenianOnyx commented
пошел нахуй, лицо набью не смей

2020-08-05 11:52 UTC, Pos13 submitted a review, later dismissed

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/effects/decals/Cleanable/misc.dm
> +		M.slip("the [src.name]", 4)
Я думаю, надо добавить проверку на бег/шаг. На обычном мыле, наверное, можно подскользнуться и шагом, а вот на раздавленной мыльной куче - вряд ли.

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You need to take that [target.name] off before cleaning it."))
```suggestion
		to_chat(user, SPAN_NOTICE("You need to take that [target.name] off before cleaning it."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You scrub \the [target.name] out."))
```suggestion
		to_chat(user, SPAN_NOTICE("You scrub \the [target.name] out."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You scrub \the [target.name] out."))
```suggestion
		to_chat(user, SPAN_NOTICE("You scrub \the [target.name] out."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You scrub \the [target.name] clean."))
```suggestion
		to_chat(user, SPAN_NOTICE("You scrub \the [target.name] clean."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You wet \the [src] in the sink."))
```suggestion
		to_chat(user, SPAN_NOTICE("You wet \the [src] in the sink."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You clean \the [target.name]."))
```suggestion
		to_chat(user, SPAN_NOTICE("You clean \the [target.name]."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +	var/durability = 50
```suggestion
	var/durability = 50 // consider 100 as maximum possible durability
```
Предлагаю оставить небольшой комментарий, чтобы создателям нового мыла было проще брать цифры с потолка для _durability_.

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +		user.visible_message(SPAN("danger", "\The [user] washes \the [target]'s mouth out with soap!"))
```suggestion
		user.visible_message(SPAN_DANGER("\The [user] washes \the [target]'s mouth out with soap!"))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +			to_chat(user, SPAN("notice", "You imprint \the [I] into \the [src]."))
```suggestion
			to_chat(user, SPAN_NOTICE("You imprint \the [I] into \the [src]."))
```

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +				visible_message(SPAN("danger", "[M] smudges \the [src]!"))
```suggestion
				M.visible_message(SPAN_WARNING("[M] smudges \the [src]!"), SPAN_WARNING("You smudge \the [src]!"))
```
Думаю, SPAN_DANGER - это сообщение уровня непосредственной опасности, вроде пистолетного выстрела.

2020-08-05 11:52 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +			to_chat(user, SPAN("notice", "You imprint \the [I] into \the [src]."))
Мне лень дальше писать замены _SPAN("warning", _ на _SPAN_WARNING(_, ты и так меня понял.

2020-08-05 12:02 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You scrub \the [target.name] clean."))
Пососёшь.

2020-08-05 12:02 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You clean \the [target.name]."))
Пососёшь.

2020-08-05 12:02 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +		user.visible_message(SPAN("danger", "\The [user] washes \the [target]'s mouth out with soap!"))
Пососёшь.

2020-08-05 12:02 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +			to_chat(user, SPAN("notice", "You imprint \the [I] into \the [src]."))
Пососёшь.

2020-08-05 12:03 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You wet \the [src] in the sink."))
Пососёшь.

2020-08-05 12:03 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +		to_chat(user, SPAN("notice", "You scrub \the [target.name] out."))
По*кхем*.

2020-08-05 12:04 UTC, TobyThorne commented on code/game/objects/effects/decals/Cleanable/misc.dm
> +		M.slip("the [src.name]", 4)
Ты дев, а не геймдизайнер.

2020-08-05 12:10 UTC, Pos13 commented on code/game/objects/effects/decals/Cleanable/misc.dm
> +		M.slip("the [src.name]", 4)
Тем не менее, я могу высказать обоснованное сомнение как игрок. Не нужно быть лицензированным поваром, чтобы оценить вкус еды.

2020-08-05 12:22 UTC, Pos13 commented on code/game/objects/items/weapons/soap.dm
> +			to_chat(user, SPAN("notice", "You imprint \the [I] into \the [src]."))
Хрюкнул. Теперь иди исправлять.

2020-08-05 12:25 UTC, TobyThorne commented on code/game/objects/items/weapons/soap.dm
> +			to_chat(user, SPAN("notice", "You imprint \the [I] into \the [src]."))
Громче. Если хочешь - сам меняй нормальные макросы на эту нечитаемую капсовую хуиту, после того как примут (если, да).

2020-10-06 20:59 UTC, TobyThorne commented
* На банановой кожуре теперь нельзя подскользнуться, если мув интент - шаг, а не бег. 
* Пофиксил конфликты.

2020-10-06 21:02 UTC, TobyThorne commented
Обновлены шансы раздавливания:
Обычное мыло: 35%
НТ-мыло: 35%
Секурити-мыло: 35%
Элитное мыло (aka кэпское): 15%
Синдимыло: 25%
ЗоЛоТоЕ мЫлО: 5%

2020-10-07 06:34 UTC, Voldirs commented
![image](https://user-images.githubusercontent.com/4889771/95295711-42885880-0880-11eb-9b6f-16eca0fc905d.png)

2020-10-11 16:50 UTC, Epicus7 requested changes

2020-10-11 16:50 UTC, Epicus7 commented on code/game/objects/effects/decals/Cleanable/misc.dm
> +/obj/effect/decal/cleanable/soap_smudge/Crossed(AM as mob|obj)
```suggestion
/obj/effect/decal/cleanable/soap_smudge/Crossed(atom/movable/AM)
```

2020-10-11 16:50 UTC, Epicus7 commented on code/game/objects/items/weapons/soap.dm
> +	var/durability = 65 // consider 100 as the maximum possible durability
```suggestion
	var/smash_chance = 65
```

Вот так лучше назвать переменную и не нужен будет стремный коммент.

2020-10-11 16:59 UTC, PlinHost commented
У нас нет вообще никакого способа получения мыла (кроме синдимыла), с такими шансами все мыло на станции тупо закончится.
Я считаю, достаточно убрать стан по лежачим. Кожуру легко подобрать, так что нет смысла убирать подскальзывание на шаге.

2020-10-11 17:53 UTC, TobyThorne commented
> У нас нет вообще никакого способа получения мыла (кроме синдимыла), с такими шансами все мыло на станции тупо закончится.
> Я считаю, достаточно убрать стан по лежачим. Кожуру легко подобрать, так что нет смысла убирать подскальзывание на шаге.

Так пусть заканчивается, не? Если использовать по назначению - то не закончится, если использовать его в боёвке - то логично, что это должен быть расходник, а не батон на максималках.

Стан по лежачим и так убрал, но это не работает от слова совсем. Космонавтик встаёт не мгновенно, даже когда weakened уже равно нолю. Вот этого времени достаточно чтобы всё равно с помощью пулла вечно держать в стане.

2020-10-11 17:57 UTC, MrMagick2104 commented
> Так пусть заканчивается, не?

Проблема в том, что восполнить запасы сложно.
Нужно тогда добавить в карго ящик с мылом, на брусков пять.

2020-10-11 18:23 UTC, TobyThorne commented
- Шанс раздавливания обычного и НТшного мыла снова увеличен до 50%;
- В карго добавлен ящик с пятью брусками мыла за 15 очков;

2020-10-12 00:08 UTC, Epicus7 approved these changes, later dismissed

2020-10-12 00:08 UTC, Epicus7 commented
Короче хороший ПР, мне нравится. По геймдизу тоже одобрил.

2020-10-12 00:11 UTC, Epicus7 commented
Алсо этот ПР закрывает #2117

2020-10-12 00:45 UTC, MorJams commented
раздавливание не нужно, со станбатоном и так достаточно различий, мыло - столб классической боёвки, лучше как Плин сказал делайте

поменьше стана, убирание станлока во время тасканий и всё

2020-10-28 12:20 UTC, Destrolaric commented
> Полностью всё переделал. Всё вышеописанное можно забыть, что есть теперь:
> 
> * Лежачие космонавтики не подскальзываются (проблема та же, что и раньше - подскользнуться можно непосредственно во время вставания);
> * Подскальзывание на мыле/банане теперь отбрасывает и космонавтика, и мыло/банан в разные стороны. Инерция, хуё-моё.
> * Раньше мыло сохло только от правильного использования. Теперь сохнет и от подскальзываний. По умолчанию в мыле 15 единиц клинера, мытьём в раковине можно поднять до 30 единиц, подскальзывание тратит 3 единицы. На сухом мыле покататься нельзя.
> * Банановые кожурки не подскальзывают при ходьбе, только при беге.
Подскальзывание в стену тестил?

2020-10-28 12:52 UTC, Epicus7 submitted a review, later dismissed

2020-10-28 20:07 UTC, jammer312 approved these changes

2020-10-29 01:15 UTC, Epicus7 approved these changes

2020-10-31 23:03 UTC, merged