Фиксим прометеев. Парт 1.
ChaoticOnyx/OnyxBay pull request #3074
Opened 2020-08-04 16:25 UTC by TapKo4eB

там ещё чинить и чинить, но по крайней мере они не выглядят как говно на данный момент.

- Починил прозрачную грудь. А говорили сложно. close #1036
- Добавил абилку смены бодибилда.
- Добавил ту_чат проверкам в абилках.
- Закомментил абилку смену волос. Она не работала, а починить у меня так и не получилось из-за рестрикта волос по расам.
- Выпилил из смены пола плюрал и нейзер чтобы не ломали бодибилды. Жесткой мир победил.
- Выпилил из трансформации расы дион и мартых:
![bruh](https://user-images.githubusercontent.com/48761132/89318217-28b37500-d687-11ea-846a-abce5a0bc902.png)

потом ещё попытаюсь дальше потыкать, ибо осталась проблема с белыми хуманами не меняющими цвет

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-04 16:27 UTC, koronoshka commented
cum man

2020-08-13 21:46 UTC, Pos13 submitted a review, later dismissed
Смена расы не учитывает текущий бодибилд.
1. Выбираем расу хумана;
2. Меняем бодибилд на слим или слимальт;
3. Выбираем расу унати, где этого бодибилда нет.

Результат: 
![image](https://user-images.githubusercontent.com/64479446/90189375-bc8eea80-ddc5-11ea-9137-6e085c5aeb00.png)

2020-08-13 21:46 UTC, Pos13 commented on code/modules/mob/living/carbon/human/species/species_shapeshift.dm
> +		change_body_build(new_body_build)
Если нажать 'Cancel', то будет вызван **change_body_build(null)**. Результат - человек-невидимка:
![image](https://user-images.githubusercontent.com/64479446/90189011-2064e380-ddc5-11ea-822f-6505b113a4bd.png)

2020-08-13 21:46 UTC, Pos13 commented on code/modules/mob/living/carbon/human/species/species_shapeshift.dm
> +		change_body_build(new_body_build)
В остальных похожих местах стоит что-то вроде
```byond
if(!new_body_build)
		return
```

2020-08-13 21:46 UTC, Pos13 commented on code/modules/mob/living/carbon/human/species/station/prometheans.dm
>  		/mob/living/carbon/human/proc/shapeshifter_select_colour,
Может, это и не совсем часть ПРа, но абилка **Select Body Colour** не отображается в списке абилок. По крайней мере у меня.

2020-08-13 21:50 UTC, TapKo4eB commented on code/modules/mob/living/carbon/human/species/station/prometheans.dm
>  		/mob/living/carbon/human/proc/shapeshifter_select_colour,
она отбирается при трансформации слаймтоксином, я это трогать не буду ибо это ещё один геймдизайн
![изображение](https://user-images.githubusercontent.com/48761132/90190666-1ee8ea80-ddc8-11ea-951a-81024bbc19da.png)

2020-08-13 21:53 UTC, Pos13 commented on code/modules/mob/living/carbon/human/species/station/prometheans.dm
>  		/mob/living/carbon/human/proc/shapeshifter_select_colour,
А, понял, проглядел.

2020-08-14 20:10 UTC, TapKo4eB commented
по мере дебага я узнал что почему-то мужикослим отображается с грудью при превращении в мейла
я не знаю почему это происходит, пофикшу когда нибудь потом

2020-08-14 20:17 UTC, Doster-d commented
> по мере дебага я узнал что почему-то мужикослим отображается с грудью при превращении в мейла
> я не знаю почему это происходит, пофикшу когда нибудь потом

Не баг, а фича, наконец-то могу отыграть транса на гармонах!

2020-10-03 18:36 UTC, TobyThorne submitted a review, later dismissed

2020-10-12 00:39 UTC, Epicus7 requested changes
Короче эти шейпшифтеры какой-то лютый говнокод. Пофиг что в них происходит.

Меня только смущают изменения которые вылезли за пределы их файликов.

2020-10-12 00:39 UTC, Epicus7 commented on code/modules/organs/external/unbreakable.dm
> +	limb_flags = ORGAN_FLAG_GENDERED_ICON
Что это такое?

2020-10-12 00:39 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/appearance.dm
> +			regenerate_icons()
Ты тут замаскировал два разных прока в одном. Можно отдельный прок сделать, если так надо? Желательно где-то в файликах этих шейпшифтеров, чтобы никто не видел.

2020-10-12 16:52 UTC, TapKo4eB commented on code/modules/organs/external/unbreakable.dm
> +	limb_flags = ORGAN_FLAG_GENDERED_ICON
Флаг части тела отвечающий за установку в айкон-стейте буковок `_m/_f`, или проще говоря гендерных префиксов. Т.к. у хумановских честов и гроина нет иконок где эти префиксы не фигурируют, в отличии от ручек и ножек, то без наличия этого флага мы получаем прозрачное тело. Более подробно об этом в `/obj/item/organ/external/update_icon`. Сами иконочки в `icons/mob/human_races/r_human.dmi`.
![please-stop-hurting-me](https://user-images.githubusercontent.com/48761132/95771794-5a1e7180-0cc4-11eb-9eec-0352c8099ee1.png)

2020-10-12 16:55 UTC, TapKo4eB commented on code/modules/mob/living/carbon/human/appearance.dm
> +			regenerate_icons()
Хрен его знает, надо будет ещё раз код прочитать чтобы понять что с этим делать. Я вроде пытался это впихнуть всем и сразу, дабы не возникало приколов каких-либо, но раз уж на то пошло, то подумаю.

2020-10-13 01:53 UTC, Epicus7 commented on code/modules/organs/external/unbreakable.dm
> +	limb_flags = ORGAN_FLAG_GENDERED_ICON
А ORGAN_FLAG_HEALS_OVERKILL тут не нужен, случайно? Этот флаг есть у `/obj/item/organ/external/chest`

2020-10-13 11:10 UTC, TapKo4eB commented on code/modules/organs/external/unbreakable.dm
> +	limb_flags = ORGAN_FLAG_GENDERED_ICON
А это уже совершенно другая сфера деятельности, где из изначального фикса спрайтов ты предлагаешь трогать медицину. А трогать медицину вместе со спрайтами в текущий момент мне нахуй не сдалось, и думать над этим надо отдельно.

2020-10-13 12:45 UTC, TapKo4eB commented on code/modules/mob/living/carbon/human/appearance.dm
> +			regenerate_icons()
Попилил.

2020-10-13 12:50 UTC, TapKo4eB commented
- Попилил нормально санитайз тела у прометеев.
- Наконец исправил этот смешной момент с не подчиняющимся спрайтами тела (где **тело** - upper body & groin) к полу персонажа. Как оказалось, по какой-то неизвестной причине (наверное беедауны) не было предусмотрено обновление ДНК всех органов хумана при вызове `update_dna()` (который используется в проке смене пола), в отличии от него самого. А т.к. иконка тела генерируется за счёт информации из ДНК то мы получали какую-ту хуйню которая блять работать не хотела я на это проебал два месяца су-

2020-10-13 12:52 UTC, Epicus7 approved these changes

2020-10-30 18:43 UTC, TobyThorne approved these changes

2020-10-30 18:43 UTC, TobyThorne commented
Вроде как, готово к мержу. Но трогать не буду, вдруг тут ещё ГеЙмДиЗаЙн нужен.

2020-11-01 23:28 UTC, merged

2020-11-01 23:28 UTC, TobyThorne commented
Ну похуй, геймдизайн не вылез.