Id edit upd
ChaoticOnyx/OnyxBay pull request #3092
Opened 2020-08-06 03:35 UTC by Doster-d

Добавил поля в программу модификации карты, теперь можно нормально регистрировать мирнома... Возвращать утерянные карты экипажу.
Добавил возможность по одной кнопке загрузить из манифеста все необходимые параметры на карточку.

close #2433 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-08 18:10 UTC, Doster-d commented
Плашку "Нужны ревью", пожалуйста.

2020-08-11 17:02 UTC, Doster-d commented on code/modules/modular_computers/file_system/programs/command/card.dm
> +				else if(href_list["load_data"])
Разработчики, рекомендую уделить особое внимание ~~говно~~коду ниже, там возможно __много bugs__

2020-08-20 15:25 UTC, Doster-d commented on code/modules/modular_computers/file_system/programs/command/card.dm
> +						id_card.side = photo
Я взял за основу Crew Records, там тоже не написано.
Как Вы предлагаете подсказать игрокам, что нужно держать фото человека для загрузки?

2020-08-20 16:44 UTC, Doster-d commented on nano/templates/identification_computer.tmpl
>  	  <div class='itemLabel'>
Ок

2020-08-20 16:45 UTC, Doster-d commented on code/modules/modular_computers/file_system/programs/command/card.dm
> +						id_card.side = photo
Ладно, сам решил, надеюсь Вам понравиться.

2020-08-20 16:48 UTC, Doster-d commented on code/modules/modular_computers/file_system/programs/command/card.dm
> +				else if(href_list["load_data"])
Я хотел написать что-то самопонижающие оценку, но я слишком глуп для этого.

2020-08-24 15:41 UTC, Doster-d commented
Забыл сказать, что исправил по ревью.

2020-08-25 06:18 UTC, TapKo4eB approved these changes

2020-08-27 12:28 UTC, Doster-d commented
Минорное обновление, ничего не изменилось... Почти.

2020-08-29 16:51 UTC, TapKo4eB approved these changes

2020-08-30 16:07 UTC, jammer312 approved these changes
Я бы добавил дополнительные проверки ввода (что пол адекватный, возраст положительный и тоже адекватный, хэши хотя бы длиной похожи на хэши). Но, может, оно и не нужно.
В остальном вроде все работает.

2020-08-30 16:12 UTC, Doster-d commented
> Я бы добавил дополнительные проверки ввода (что пол адекватный, возраст положительный и тоже адекватный, хэши хотя бы длиной похожи на хэши). Но, может, оно и не нужно.

Пол это ~~лава~~ фича, а остальное действительно можно добавить.

2020-08-30 16:41 UTC, Doster-d commented
Пусть хеши будут на совести ХоПов~~, вторженцев, нюкеров~~.

2020-08-31 11:34 UTC, jammer312 approved these changes

2020-08-31 12:01 UTC, jammer312 approved these changes

2020-08-31 12:13 UTC, jammer312 requested changes
Нужно больше проверок ввода

2020-08-31 13:00 UTC, Doster-d commented
Есть больше проверок.

2020-08-31 15:48 UTC, jammer312 approved these changes

2020-08-31 16:13 UTC, jammer312 approved these changes

2020-08-31 16:13 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/91741904-1103d980-ebbe-11ea-808e-b4b5c0bc432e.png)

2020-09-15 11:37 UTC, Doster-d commented
Там ревью раздают...

2020-09-15 11:44 UTC, TobyThorne approved these changes
Пробежался, в коде критических смешнявок не нашёл. Тестить это я, конечно же, не буду.

2020-09-15 11:45 UTC, Doster-d commented
Кворум набран, спасибо.

2020-09-15 14:29 UTC, merged