Simple animals health update
ChaoticOnyx/OnyxBay pull request #3167
Opened 2020-08-18 01:47 UTC by TobyThorne

Simple animals теперь умирают сразу же, как кончается здоровье, а не на следующем тике. Больше никаких кусающих после удара есвордом мышек и расстрелянных хедкрабов, убегающих в вентиляцию.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-18 07:06 UTC, HonkyDonky commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		death()
Спрячь лучше под `/mob/living/simple_animal/updatehealth()`, чтоб не вызывать везде один и тот же кусок кода.

2020-08-18 08:48 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		death()
Чёт писать функцию в три строки чтобы дважды написать одну строку вместо двух - такое. 
Может быть потом, когда поосновательнее потрогаю симплживотных, там много чего перекраивать надо.

2020-08-18 09:23 UTC, HonkyDonky commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		death()
Ну вообще-т у тебя эти две строчки ещё два раза в ПРе появляются, получается шесть строчек, которые можно уместить в четыре. Здорово правда?

2020-08-25 06:12 UTC, TapKo4eB commented
вы мышей сломали
![изображение](https://user-images.githubusercontent.com/48761132/91129675-13909b80-e6b3-11ea-8eae-65bcc0f68bc2.png)

2020-08-28 15:40 UTC, jammer312 commented
Хз, почему, но после того, как долбанешь мыш рукой, мастер контроллер совершает суицид на этапе процессинга мобов.

2020-08-28 15:54 UTC, jammer312 requested changes
adjustBruteLoss зовет updatehealth, тот зовет death, death зовет adjustBruteLoss уж чтоб наверняка.
И весь этот цирк намертво вешает контроллер. Хз, почему оно по рекурсиям не умирает.

2020-09-18 20:36 UTC, TobyThorne commented
Переделываю боёвку с симпл_животными более основательно, так что этот ПР закрою.

2020-09-18 20:36 UTC, closed without merging