Кастеты на карту и в аплинк
ChaoticOnyx/OnyxBay pull request #3204
Opened 2020-08-20 07:48 UTC by ArmolitskiyCarpoeb

Теперь кастет может появиться с определённым шансом на точках спавна нелегальных вещей. Ещё я добавил кастет в аплинк за 6 ТК во вкладку громкого и опасного оружия.
По поводу шанса на появление (поставил 50): запускал 2 раунда, в обсёрве летал по техтоннелям и гетто - не нашёл ни одного кастета. Скорее всего, появление кастета будет редким событием. Наверное.

close #2808 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-20 07:50 UTC, ArmolitskiyCarpoeb commented
Так как я полный лох в мастерстве кодинга на языке булонда, то и настроить нормально урон кастету не смог. Его урон зависит от материала, сейчас стандартный материал для кастета - это сталь. И урон у кастета приличный, оружие довольно опасное, поэтому я не добавлял кастет в список рецептов из материалов и в список изделий автолата.

2020-08-20 08:00 UTC, TobyThorne commented on code/game/objects/random/random.dm
> +				/obj/item/weapon/material/brass_knuckle = 50,
Хуя шанс выставил. Не жирновато?

2020-08-20 08:01 UTC, TobyThorne commented on code/game/objects/random/random.dm
> +				/obj/item/weapon/material/brass_knuckle = 50,
Не нашёл потому что точек с контрабандой на карте - раз, два и обчёлся. Зато на них всегда будут спавниться кастеты, с мизерным шансом на что-то другое.

2020-08-20 08:13 UTC, ArmolitskiyCarpoeb commented on code/game/objects/random/random.dm
> +				/obj/item/weapon/material/brass_knuckle = 50,
У контрабанды и так мизерный шанс, я например стероиды всего лишь один раз за всё время находил на складе карго. А так, 1-2 кастета на карте - очень мало. Но могу снизить до 20-30

2020-08-20 09:33 UTC, PlinHost commented
Зачем кастет в аплинке? Агенты синдиката это не гопники, они используют серьезное оружие.

2020-08-20 09:40 UTC, ArmolitskiyCarpoeb commented
> Зачем кастет в аплинке? Агенты синдиката это не гопники, они используют серьезное оружие.

Ладно, удаляю.

2020-08-20 10:04 UTC, ArmolitskiyCarpoeb commented
обновлено

2020-08-20 13:08 UTC, Judge1987 commented
> Зачем кастет в аплинке? Агенты синдиката это не гопники, они используют серьезное оружие.

И при этом там есть шарик.

2020-08-20 13:19 UTC, Vanner0 commented
В разделе **badass**ery, что намекает. В аплинке есть трость с ножом. Можно было бы добавить похожий скрытный прототип кастета, но это совсем другая история.

2020-08-21 04:00 UTC, ArmolitskiyCarpoeb commented
в ожидании ревью

2020-10-03 18:37 UTC, TobyThorne approved these changes
Смешного в коде нет. Остальное на совести гейдизайнеров.

2020-10-06 09:34 UTC, ArmolitskiyCarpoeb commented
фух, осталось подождать еще 3 месяца и ПР будет принят

2020-10-12 01:03 UTC, Epicus7 requested changes

2020-10-12 01:03 UTC, Epicus7 commented on code/game/machinery/autolathe_datums.dm
> +	resources = list(MATERIAL_STEEL = 1000)
Такой строчки нет больше ни у одного рецепта, лол.

Ее нужно убрать и добавить в объект `/obj/item/weapon/material/brass_knuckle` инфу из каких материалов он состоит.

Например у объекта `/obj/item/weapon/reagent_containers/glass/bucket` это выглядит так:
`matter = list(MATERIAL_STEEL = 280)`.

И соответственно стоимость производства становится 280 * EXTRA_COST_FACTOR = 280 * 1.25

2020-11-13 10:05 UTC, closed without merging