rework(fake_crew_announcement): improve traitor experience
ChaoticOnyx/OnyxBay pull request #3224
Opened 2020-08-22 05:57 UTC by HentaiStorm

Список изменений:
1) Добавлен _verb_ переключения режима на оглашение/не оглашение аннонса
2) Добавлен звук аннонса (Чуть тише обычного)
3) fix #2828 
4) Оглашает ЛЮБУЮ джобку (Раньше только из тех, что есть в occupation)

:white_check_mark: Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
:white_check_mark: Я внимательно прочитал все свои изменения и багов в них не нашел.
:white_check_mark: Я запускал сервер со своими изменениями локально и все протестировал.
:white_check_mark: Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-26 15:24 UTC, HentaiStorm commented
Все требования выполнены

2020-10-03 10:35 UTC, TobyThorne requested changes

2020-10-03 10:35 UTC, TobyThorne commented on code/datums/uplink/services.dm
> +		to_chat(usr, "<span class='notice'>Device will announce your visit!</span>")
Страшные спаны, надо SPAN("notice", "Device will announce your visit!")

2020-10-12 01:13 UTC, Epicus7 requested changes

2020-10-12 01:13 UTC, Epicus7 commented on code/datums/uplink/services.dm
> +	var/mode = 1
Лучше назвать переменную более значащим названием "does_announce_visit" или чот такое. Все эти моды абсолютно непонятны когда просто смотришь на них в коде.

2020-10-12 01:13 UTC, Epicus7 commented on code/datums/uplink/services.dm
> +
А нельзя написать общую функцию, которая будет использоваться и в `/mob/new_player/proc/AttemptLateSpawn(datum/job/job, spawning_at)`, и здесь?

А то кто-то где-то чот поменяет и поведение опять разъедется. Потом будем еще 2 года фиксить.

2020-10-12 05:47 UTC, HentaiStorm commented on code/datums/uplink/services.dm
> +
Общий аннонс прибытия?

2020-10-13 02:15 UTC, Epicus7 commented on code/datums/uplink/services.dm
> +
Общую фукнцию, которая:

1. Воспроизводит всем звук прибытия
2. Отправляет сообщение AnnounceArrivalSimple.
3. Отправляет сообщение AnnounceArrivalSimple в дополнительный канал.

Чтобы этот код не приходилось дважды поддерживать в коде прибытия и в этом твоем фейк анноунсере.

2020-10-26 09:19 UTC, HentaiStorm commented
Внес поправки:
1) Для сохранения карты фейк крю аннонса нужно провести по нему
2) Добавил Hands up для роли капитана (Пасхалка, оно в два раза громче)
3) Общий аннонсер добавлю чуть позже

2020-10-28 07:19 UTC, HentaiStorm commented on code/datums/uplink/services.dm
> +
![изображение](https://user-images.githubusercontent.com/60922927/97404278-a8b04a80-1917-11eb-9cef-af630ccc4a31.png)
Добавил от себя еще озвучивание расы, оставить или убрать? Если оставлять, то придется еще и агентскую карту редачить, по причине показанной на фотке.

2020-10-29 03:34 UTC, HentaiStorm commented
Ладно, раз не ответили по приписки расы к аннонсу, тогда я его уберу.

2020-11-12 15:20 UTC, kreeperHLC approved these changes

2020-11-12 17:06 UTC, Destrolaric commented on code/datums/uplink/services.dm
> +		to_chat(usr, "<span class='notice'>Device will announce your visit!</span>")
А что за история с данными спанами?

2020-11-12 17:12 UTC, HentaiStorm commented on code/datums/uplink/services.dm
> +		to_chat(usr, "<span class='notice'>Device will announce your visit!</span>")
Контроля больше.

2020-11-23 11:11 UTC, Epicus7 submitted a review, later dismissed
Гораздо лучше уже. Надеюсь ты потестил все.

2020-12-01 11:46 UTC, Doster-d approved these changes

2020-12-08 16:54 UTC, TobyThorne approved these changes
Похуй, Эпикус аппрувнул.

2020-12-08 16:59 UTC, HonkyDonky commented
У вас тут usr'ы в проках. Потом опять будет как с попугаем.

2020-12-08 17:02 UTC, kreeperHLC requested changes

2020-12-08 17:02 UTC, kreeperHLC commented on code/datums/uplink/services.dm
> +/obj/item/device/uplink_service/fake_crew_announcement/attackby(obj/item/I, mob/user = usr)
> mob/user = usr

2020-12-08 17:02 UTC, kreeperHLC commented on code/datums/uplink/services.dm
> +		to_chat(usr, SPAN("notice", "Card saved!"))
При этом тут ещё и usr

2020-12-08 17:02 UTC, kreeperHLC commented on code/datums/uplink/services.dm
> +		to_chat(usr, SPAN("notice", "You have to swipe a card!"))
Не user

2020-12-08 17:02 UTC, kreeperHLC commented on code/datums/uplink/services.dm
>  /obj/item/device/uplink_service/fake_crew_announcement/enable(mob/user = usr)
Ага и тут

2021-01-13 00:08 UTC, TobyThorne commented on code/datums/uplink/services.dm
>  /obj/item/device/uplink_service/fake_crew_announcement/enable(mob/user = usr)
Там вёрб же, он не получает user'а.

2021-01-13 00:10 UTC, TobyThorne commented
Поправил за Хентая, а то уже больше месяца висит.

2021-01-14 10:18 UTC, kreeperHLC approved these changes

2021-02-25 04:52 UTC, Doster-d approved these changes
Ничего плохого не может случится, так ведь?

2021-02-25 04:52 UTC, Doster-d requested changes
А случилось, конфликты.

2021-02-25 06:05 UTC, Doster-d approved these changes

2021-02-25 17:31 UTC, kreeperHLC approved these changes

2021-02-26 19:10 UTC, merged