Починка infest'а у хедкраба
ChaoticOnyx/OnyxBay pull request #3232
Opened 2020-08-22 16:55 UTC by HonkyDonky

Иногда, в редких случаях, у хедкраба пропадала его биоструктура, из-за чего при Infest'e игрок не мог перенестись в новое тело. Почему пропадает биоструктура - вопрос на который трудно ответить, ибо это ДедФилькин код.

fix #2163 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-25 09:33 UTC, PlinHost commented
Не, давай ты зафиксишь пропадающую биоструктуру, а не костыли втыкать будешь.

2020-08-25 16:24 UTC, HonkyDonky commented
Почему ты только это ДедФиле не сказал? Твой же билд. 

А вообще я не могу обнаружить при каких условиях пропадает биоструктура, даже с той инструкцией в иссуе. Создание новой биостуктуры не грозит чем-либо серьёзным, как я погляжу, да и проёб старой тоже, в ней не хранится что-то важное.

2020-09-15 11:40 UTC, TobyThorne approved these changes
Лучше костыль, чем критический баг.

2020-09-18 10:22 UTC, Epicus7 requested changes
Так баг остается, просто мы его прячем под ковер. И он просто выстрелит в другом месте.

2020-10-23 20:55 UTC, Epicus7 commented
Короче не пойдет такой фикс.

2020-10-23 20:55 UTC, closed without merging