Возможность автоджоббана АВД + апгрейд бюрократии. [WIP]
ChaoticOnyx/OnyxBay pull request #3257
Opened 2020-08-28 08:50 UTC by jammer312

Реализует #997
Факс теперь умеет печатать пачку жалоб, особый предмет, который содержит главную форму-жалобу и может спавнить и содержать дополнительные формы-подтверждения. Заполненная жалоба с прикрепленными подтверждениями может быть отправлена на ЦК, и, если она проходит проверки и содержит достаточное кол-во жалоб, с помощью админов или без нее (все согласно иссую) цели жалобы выдается джобка (отдельная от обычных джобок) на неделю.
Из существенных отличий от иссуя - чуть больше ограничений (нужны подтверждения от разных игроков, не просто от разных персонажей), несколько иная структура БД, иное взаимодействие с папкой (если использовать в руке, можно посмотреть главную форму, если использовать пустой рукой, пока она в другой руке - можно доставать новые или существующие формы, если ткнуть в нее ручкой, откроется меню редактирования главной формы), иной интерфейс для админов (выводится не вся БД, а только 10 результатов на страницу (или все активные), в списке показываются не все поля, а только самые важные, при клике по ИДу жалобы можно открыть окно специально для этой жалобы, где есть вся инфа по ней и можно менять ее статус).

Фича основывается на апгрейде бюрократии, конкретно бумаги и некоторых зависимых от нее механизмов и предметов.
Суть апгрейда:
- Изменена система полей, теперь зависимость сложности операций с бумагой от количества полей линейная, а не квадратичная. Убран явный лимит на количество полей на одну бумажку, теперь вместо него явный лимит на количество добавленных полей за операцию. Изменена функция просчета оставшегося места на бумажке, она реализует неявный лимит на количество полей на одну бумажку.
- Добавлены поля для подписи, которые при редактировании выглядят как ссылка (sign here), при нажатии на которую автоматически поставится подпись.
- Добавлены именованные поля и поля для подписи, они могут быть созданы только при инициализации (юзеры создать не могут, да и бесполезны они им), подпись в именованном поле можно ловить через топик, содержимое именованных полей можно достать через функцию parse_named_fields.
- Добавлены новые параметры бумаги, readonly (можно ли на ней писать) и appendable (можно ли дописывать в конец)
- Добавлены теги центрирования текста ([left] [/left] и [right] [/right]), а также тег завершения [end], который убирает поле, в которое прописан.
- Бумаге добавлены функции copy и recolorize, которые используются для копирования и для перекраски (потеря насыщенности и/или перевод в грейскейл) соответственно; перекраска умнее той, что была в ксероксе, конкретно она умеет работать с цветами, а не только с грейскейлом, и умеет уменьшать насыщенность в разной степени. Помимо этого она также умеет (в некоторой степени) то же самое делать со штампами. В частности, теперь тот же ксерокс (который, к слову, все еще черно-белый) выдает гораздо лучше смотрящиеся копии, которые всегда чутка блеклее (или заметно блеклее, если тонера мало) оригинала, при этом изначально разные цвета различимы (например, на копии бывший красный будет блеклее бывшего черного), и последовательное копирование прослеживается (если скопировать копию, она будет еще более блеклая), ну и явно видна разница между результатом копирования и написанным уже после копирования. Ксерокс и копирка подправлены, чтобы использовали эти функции вместо дублированного кода. Попутно выпилен _тот самый эксплоит_ с копированием.

Попутно добавляет сошки в гитигнор.

Мне влом править историю коммитов, ибо там много и раскидано, просто сквашните при мерже.

closes #997 

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-08-28 08:56 UTC, jammer312 commented
Теперь по галочкам.
Я **не тестил** почти ничего, начиная с добавления верификации факсов и взаимодействия с БД, ибо тестирование этого нетривиально. Бумага должна работать, взаимодействие с папкой и формами жалобы (кроме верификации) должно работать. У меня есть смутное подозрение, что там где-то что-то в редакторе бумаги в ПДА сломалось, но когда я последний раз туда глядел (давно это было) у меня возникло стойкое подозрение, что оно и до меня нихера не работало. Редактор в ПДА еще гляну, верификацию и взаимодействие с БД пощупаю, если получится (но в идеале это надо делать на сервере с несколькими игроками).

Ну и да, пока писал ПР, вспомнил, что забыл непосредственно проверку джобок прикрутить, ща займусь.

2020-08-28 08:57 UTC, jammer312 commented
А, ну да, дополнительные структуры БД прописаны в sql/migrate, при запуске БД в докере по докерфайлу, что лежит рядом, БД автоматом настроится.

2020-08-28 13:51 UTC, jammer312 commented
Вроде все пофиксил

2020-08-28 15:59 UTC, YouBro commented
Идея говно, какой автоджоббан на АВД. Вы что, совсем?

2020-08-28 16:04 UTC, Doster-d commented
Может пока как эксперимент дадим просто возможность с помощью педали долбоеба отсранить?

2020-08-28 16:05 UTC, jammer312 commented
Типа без автоаппрувов или что?

2020-08-28 16:05 UTC, HentaiStorm commented
Нарушает концепцию метагейма, перенося события прошлых раундов в текущий.

2020-08-28 16:06 UTC, Doster-d commented
> Типа без автоаппрувов или что?

Без автоаппрувово, просто с подписями и педалями.

2020-08-28 16:13 UTC, ArmenianOnyx commented
Норм идея, что не нравится?

2020-08-28 16:16 UTC, YouBro commented
Мне не нравится, что ингейм роль агента внутренних дел ИГРЫ переносят в ООС план. По иссую авд может писать жалобу ингейм на человека, чтобы ему забанили роль. Когда он имеет ахелп, может уволить его в игре. Ты хочешь сказать, что идея правда норм?

2020-08-28 16:18 UTC, ArmenianOnyx commented
> Мне не нравится, что ингейм роль агента внутренних дел ИГРЫ переносят в ООС план. По иссую авд может писать жалобу ингейм на человека, чтобы ему забанили роль. Когда он имеет ахелп, может уволить его в игре. Ты хочешь сказать, что идея правда норм?

Внутри игры АВД никак не может уволить. Только схватить пушечку и свергнуть. Как по мне это придаст больше смысла в жизни, к нашему бесполезному агенту, а так же страх глав перед ним.

2020-08-28 16:20 UTC, YouBro commented
Нормальный авд, который знает как нужно себя вести всегда сможет уволить кого надо, вызвать отряд реагирования с цк и прочее. Это отговорка для тех, кто не умеет в диалог. Тем более забанив игроку роль ты его в раунде не лишишь её. В чем смысл? АВД не бесполезен, просто играть нужно уметь на нем, что написали еще на вики, мол это не самая легкая роль. Нужно быть настоящей крысой, общаться, подбивать людей, предлагать им выгоду, а не прост закрываться у себя в кабинетике и строчить на цк жалобы.

2020-08-30 14:10 UTC, jammer312 commented
Теперь авд баны разнорабочих банируют всех, кроме разнорабочих (согласно иссую) (разнорабочих т.е. из гражданского, сервисного или отдела снабжения).
Попутно пофиксил цирк вокруг альтернативных названий работ (кто и зачем эту дичь вообще придумал), пофиксил сломанные аппрувы жалоб и добавил дополнительную попытку угадать сикей банируемого к моменту подписания основной формы (на деле к моменту, когда папка обнаружит, что она подписана). По сути теперь сикей запоминается почти в начале написания жалобы (если не получилось, то еще раз попробует в конце), поэтому шанс того, что вся работа по сбору подписей уйдет в никуда из-за того, что банируемый куда-то протерялся, намного ниже.
Ну и еще запилил иное отображение банов авд в меню настройки профессий, теперь оно там отображается как [RESTRICTED]

2020-08-31 03:25 UTC, vekotov commented
Однозначно одобряю, буду делать жалобы на капитана и ходить по ассистентам за подписями, ибо нехуй не слушать авд.

2020-09-02 19:17 UTC, Epicus7 commented
1. Когда тыкаешь жалобу в факс - персонаж одновременно его еще и бьет.

>You insert Complaint #7b1fdf into the fax machine.
> The fax machine has been hit by Captain MucDuck with Complaint #7b1fdf.

2. Заголовки колонок в списке жалоб слишком блеклые, надо бы выделить жирным:

![image](https://user-images.githubusercontent.com/5204667/92024170-7abee780-ed66-11ea-90a8-4c77a51c33f8.png)

3. В окошке просмотры жалобы поле Reason заполнено почему-то игроком, который инициировал жалобу:
![image](https://user-images.githubusercontent.com/5204667/92024328-ba85cf00-ed66-11ea-8630-b8adfea848f8.png)

4. При резолве нет сообщения в ADMIN LOG. И вообще, надо бы на все действия напихать логирования в ADMIN LOG, плюс в логи. Там функция есть специальная для этого - log_and_message_admins. На все действия - это отправка успешной жалобы, апрувы педалей, отмена джобки педалями и подобное.

5. При получении жалобы админами нужно добавить кнопочку, чтобы можно было сразу попасть в интерфейс жалоб и апрувнуть/дизапрувнуть. Сейчас таких кнопочек нет - можно только текст жалобы прочитать:
![image](https://user-images.githubusercontent.com/5204667/92025082-b27a5f00-ed67-11ea-8548-b80ff6fe2af4.png)

6. Когда выпадает ошибка о дубликате `ADMIN LOG: IAAJ fakeid collision. Possible duplicate?`, жалоба не удаляется из принтера, но при этом пропадает из интерфейса. А игрок не получает никакого фидбека. Предлагаю добавить явный фидбек игроку типа "Похоже вы уже отправляли эту жалобу".

7. Почему-то отклоненная жалоба продолжает висеть в окошке активных жалоб:
![image](https://user-images.githubusercontent.com/5204667/92025991-f91c8900-ed68-11ea-83c7-3f9039445eac.png)

В БД тоже что-то непонятное случилось. Почему-то она Denied, при этом есть дата окончания:
![image](https://user-images.githubusercontent.com/5204667/92026379-9d063480-ed69-11ea-8738-6f6039366b43.png)

8. Несмотря на бан за Ботаника я все равно смог за него зайти. Алсо в лобби при выборе работы не было указано, что профессия забанена.


----
Тестировать ПР очень легко, если у тебя есть нормальная база + если временно убрать проверку подписей вот так:
![image](https://user-images.githubusercontent.com/5204667/92026633-f8d0bd80-ed69-11ea-86df-59b1f08f4e47.png)

Еще лайфхак - можно сделать два аккаунта BYOND себе. Зайти сначала на локалку одним аккаунтом, потом перелогиниться в BYOND и зайти вторым. Тогда у тебя будет два аккаунта на сервере и ты можешь одним аккаунтом удобно банить другой.

2020-09-02 19:18 UTC, Epicus7 commented
Короче поверхностно протестировал чот пока все очень сыро. То что баны не работают в принципе - это совсем печально, мда.

Постараюсь сегодня еще по коду посмотреть.

2020-09-02 21:15 UTC, jammer312 commented
1. Теперь ксерокс (и факс, который тоже ксерокс) нормально ест бумагу и прочие документы (без удара)
2. Теперь у таблицы есть границы меж ячейками, и ее первая строка жирная
3. Поправил форматирование и добавил пояснение к этому полю
4. Добавил логирование всех операций с БД (добавление жалобы и изменение ее статуса)
5. ^ во всех логах есть кликабельная ссылка, при нажатии на которую откроется inspect соответствующей жалобы
6. Не актуально
7. Поправил
8. Не актуально, но поменял логику, теперь разнорабочие банят только глав, не-главы из отдела банят (помимо себя) глав из соответствующего отдела. Заодно пофиксил лажу с интерфейсом.

2020-09-04 15:48 UTC, Epicus7 requested changes
Короче на изменениях бумаги я уже все. Пипец гигантский ПР конечно.

Архитектурно конечно, не очень получилось. Я там написал, что окошки не очень и общая архитектура, то что все это можно было сделать в виде подсистемы и получилось бы симпатичнее. Но это довольно большие изменения, так что можешь забить на них. Отписал просто на будущее тебе про них.

Ну и кучу мелочей всяких отметил, в том числе баги и уязвимости нашел. Это надо пофиксить конечно.

Что там поменялось в бумагах я уже сквозь пальцы посмотрел, надеюсь там ничего критичного не проморгал. Если что, потом найдем и пофиксим.

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +/obj/item/weapon/complaint_folder/attack_self(mob/living/user as mob)
```suggestion
/obj/item/weapon/complaint_folder/attack_self(mob/living/user)
```

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +			to_chat(user, SPAN_WARNING("Sign [src] first!")) //how did they get complaint form tho?
> how did they get complaint form tho?

Взяли от другой жалобы? В таком случае лучше вывести, что ID не совпадают.

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +		else //???
???

Какой-то лишний комментарий. 

Если тут подразумевается, что это недостигаемая ветка, то лучше написать EXCEPTION("Unexpected significance")

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +		return //no need to alert the crew
Опять же, что за странный комментарий ??? ?

Если это недостижимый случай, то ASSERT надо вставить.

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +				return "Verification software error"
EXCEPTION может быть?

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +		return "Already finished"
ASSERT ?

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +			return "Signed form with no ckey bound found"
Опять стремный комментарий

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +		return "Sender has no mind"
ASSERT

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/complaint.dm
> +		return "Already finished"
ASSERT

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/faxmachine.dm
> +		dat += "<a href ='byond://?src=\ref[src];print_complaint=1'>Print complaint kit</a><br>"
byond:// тут зачем?

```suggestion
		dat += "<a href ='?src=\ref[src];print_complaint=1'>Print complaint kit</a><br>"
```

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/faxmachine.dm
> +			return
```suggestion
		ASSERT(id)
```

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/photocopier.dm
> +		return
Интересно, а почему ты таких проверок в факс не напихал?

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/photocopier.dm
> +				break
И таких вот тоже

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/paper.dm
> +/obj/item/weapon/paper/proc/get_signature(obj/item/weapon/pen/P, mob/user as mob, signfield)
```suggestion
/obj/item/weapon/paper/proc/get_signature(obj/item/weapon/pen/P, mob/user, signfield)
```

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/faxmachine.dm
> +	if(href_list["print_complaint"])
Сюда бы ограничений добавить каких-нибудь тоже, а то можно наспавнить бесконечное число папочек и уронить сервер.

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/paperwork/faxmachine.dm
>  /obj/machinery/photocopier/faxmachine/Topic(href, href_list)
Здесь в Топике не хватает проверок элементарных, например, на расстояние до user. Я могу открыть вставить ID из другого конца станции. Могу печатать папочки из другого конца станции. Могу короче все нажимать из другого конца станции.

Правда после нажатий окошко не обновляется, но легче от этого не становится. Папочки отлично печатаются, ID отлично исчезает и телепортируется в факс :)

Таких же проверок походу нет и в ксероксе (photocopier).

2020-09-04 15:48 UTC, Epicus7 commented on code/modules/admin/banjob_iaa.dm
> +GLOBAL_LIST_EMPTY(IAA_approved_list)
Вот эти все переменные и функции, которые начинаются на IAA_, они тебя совсем не смущают?)

Вот эти вот IAA_ - это объект, описанный в стиле Си. Типо когда у тебя есть логический объект, но описать его как объект ты не можешь, поэтому описываешь его кучей разрозненных функций с общим префиксом.

Но в BYOND-е есть объекты, так почему бы их не использовать когда у тебя куча функций и переменных логически объединяются в один объект?

Этот ПР уже и так пипец какой большой, так что можешь тут конечно это не исправлять уже, пофиг. Но вообще  всю эту логику надо было писать новой подсистемой (subsystem). Соответственно все эти переменные и методы IAA_ прикреплять к этой подсистеме. Туда же пихать все топики и формы (не захламляя, например, /datum/admin/Topic).

То есть у тебя была бы подсистема отдельная, которая бы на старте игры загружала из БД все что там ей нужно и хранила бы в себе. Обрабатывала бы все твои Топики, рисовала бы все окошки.

И выглядело бы это все более консистентно. Например, можешь посмотреть как мы писали систему донатов. Тут в принципе все тоже самое можно было бы сделать.

Но можем оставить это до лучших времен. Ты тут столько кода понаписал, что сейчас переписывать это уже довольно трудоемко..

2020-09-04 15:56 UTC, jammer312 commented on code/modules/admin/banjob.dm
> +			return FALSE
В дискорде уже писал, эта функция не только для банов профессий пользуется, но еще для всякой фигни вроде ахелпа, антагов и appearance. Посему здесь assert неуместен.

2020-09-04 16:02 UTC, jammer312 commented on code/modules/admin/banjob_iaa.dm
> +#define IAA_FAKE_ID_UPPER_LIMIT     16777215
256^3 - 1, максимальное шестизначное в шестнадцатеричной СС число, ибо в иссуе было про 6значный номер жалобы. Могу заменить на это, но вряд ли это сделает константу сильно понятнее.

2020-09-04 17:58 UTC, Doster-d commented on code/modules/admin/banjob_iaa.dm
> +#define IAA_FAKE_ID_UPPER_LIMIT     16777215
Мне кажется Эпикус имел в виду комментарий к данному числу

2020-09-05 11:59 UTC, Epicus7 commented on code/modules/admin/banjob_iaa.dm
> +#define IAA_FAKE_ID_UPPER_LIMIT     16777215
Предлагаю комментарий добавить, что это максимальное шестиричное число с 6 знаками.

2020-09-06 14:04 UTC, jammer312 commented on code/modules/paperwork/faxmachine.dm
> +		dat += "<a href ='byond://?src=\ref[src];print_complaint=1'>Print complaint kit</a><br>"
Для согласованности с тем, что уже есть. Можно, конечно, прогнать автозамену по всему файлу, чтобы выпилить все упоминания протоколов, но нужно ли оно?

2020-09-06 14:06 UTC, jammer312 commented on code/modules/paperwork/photocopier.dm
> +				break
Такие там уже есть

2020-09-06 18:50 UTC, jammer312 commented on code/modules/paperwork/complaint.dm
> +/obj/item/weapon/complaint_folder/New(loc, id, noinit = FALSE)
Папка не должна присутствовать на карте, *почти* ничего медленного при создании не делает, и для ее работы необходима созданная форма и прописанный айди. Потому Initialize тут не необходим, а может даже вреден

2020-09-17 19:54 UTC, Epicus7 approved these changes

2020-09-17 20:00 UTC, merged