tweak(flash_powder): static stun time, to dynamic
ChaoticOnyx/OnyxBay pull request #3259
Opened 2020-08-28 10:20 UTC by HentaiStorm

Динамический Stun и Weaken, в зависимости от количества реагентов.
Текущая формула:
- От 0 до 3 тайлов дистанции:
  Weaken(количество вещества / 5)
- От 4 до 5 тайло дистанции:
  Stun(количество вещества / 16)

При том, что теперь создается 2 порошка на крафт

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c Guide to Contribute.

2020-08-28 10:40 UTC, jammer312 commented
Почему 16, а не 15?

2020-08-28 10:49 UTC, HentaiStorm commented
Вот, теперь правильно. Поясняю: при создании порошка в обычной мензурке 60u, мы получаем те же результаты, что были бы и при статичном вычислении, в котором, мощность порошка не зависела от количества реагентов.

2020-08-28 10:57 UTC, jammer312 commented
Ну, у меня претензия не к балансу была, а к тому, что ты поменял соотношения времени weaken и stun (было 3 к 1, стало 5 к 16).
По балансу тут скорее на гранаты смотреть надо (если они вообще на реагентах, а на захардкожены), чтобы ванильные флешбенги бахали так же, как и до изменения.
И, может, зависимость не линейную надо, а логарифмическую или корневую (квадратный или кубический корень). Ибо (опять же, если гранаты на реагентах тут работают через мерж двух сосудов) в гранату можно пихнуть две больших банки (они тут есть? вроде должны быть на 120), суммарно получая 240 емкости, что даст 4хкратный эффект, что, на мой взгляд, весьма имбово. Квадратный корень хорошо впишется в 2дшность станции, ну и с ним будет 2хкратный эффект, что тоже мощно, но уже более приемлемо.
Ну и еще, возможно, имеет смысл сделать такого же рода зависимость и для дальности действия эффекта.

2020-08-28 11:00 UTC, HentaiStorm commented
Можно по глазкам хармить при овермощности, оставляя приемлимый стан и викен.

2020-08-28 11:00 UTC, HentaiStorm commented
Флешбенги останутся как и раньше, они вообще отдельно работают от порошка.

2020-10-03 10:31 UTC, TobyThorne commented
This branch has conflicts that must be resolved

2020-12-08 11:13 UTC, kreeperHLC requested changes

2020-12-08 11:13 UTC, kreeperHLC commented on code/modules/reagents/Chemistry-Recipes.dm
> +		if(hasvar(M, "glasses") && istype(M:glasses, /obj/item/clothing/glasses/sunglasses))
![image](https://user-images.githubusercontent.com/14943437/101476890-7d316e80-395f-11eb-8639-f31af0f0795b.png)

2020-12-16 06:06 UTC, TobyThorne commented
Два с половиной месяца ожидает автора.

2020-12-16 06:06 UTC, closed without merging