rework(syndie_kit/cigarette): add new cigarettes and fix bug
ChaoticOnyx/OnyxBay pull request #3261
Opened 2020-08-28 11:15 UTC by HentaiStorm

close #2048 также заменяется одна пачка флеша на форон, и пачка смоука на нейротоксин.
Сейчас флеш поудер юзлесс и не может в дозировку, потому сиги бы станили на 15/5. Лечится с ним  #3259 

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-02 21:32 UTC, TobyThorne requested changes
cigs_lighters.dm больше не существует в билде.

2020-11-13 17:43 UTC, kreeperHLC approved these changes

2020-11-23 11:17 UTC, Epicus7 commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	fill_cigarre_package(pack, list(/datum/reagent/toxin/phoron = 40))
А не слишком ли много 40 юнитов форона в сигаретах? Это же целый стакан.

2020-11-23 11:17 UTC, Epicus7 commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +		C.reagents.maximum_volume = 5
Здесь вообще не понял что происходит. Ты сначала расширяешь maximum_volume, набиваешь сигарету реагентами, а потом уменьшаешь его до 5. У тебя не получается так, что реагентов в сигарете 40 юнитов, что сильно больше максимума в 5 юнитов?

2020-11-23 11:17 UTC, Epicus7 commented
Плашку геймдизайна добавил, так как 40 форона в пачке сигарет - это что-то геймдизайнерское.

2020-12-16 06:15 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	fill_cigarre_package(pack, list(/datum/reagent/toxin/phoron = 40))
Это не в каждую пачку, а делится на все сигареты, емнип. Хотя цифры всё равно какие-то странные, надо всё это основательнее переделывать.

2021-01-13 07:59 UTC, closed without merging