optimization(movement_delay)
ChaoticOnyx/OnyxBay pull request #3267
Opened 2020-08-29 05:35 UTC by HentaiStorm

Изменения:
- Заменены местами и отсортированы по приоритетам почти все блоки
- Итерации списков теперь в одном блоке
- Ретурнящие конструкции подняты к верху
- stance_damage перенесен из общего блока в элс коляски

close #1956

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-06 08:27 UTC, PlinHost commented
Оно до сих пор каждый мув пересчитывает замедление, иссуй не исправлен.

2020-09-06 09:23 UTC, HentaiStorm commented
Ну а как, если на мув влияют куча параметров? Перед каждым изменением параметра изменять слоудаун?

2020-09-06 09:29 UTC, PlinHost commented
После каждого изменения параметра, да. Не обязательно делать это для всех, можно часть оставить, если там что-то сложное.

2020-09-06 09:32 UTC, HentaiStorm commented
Ну-с, можно заменять параметры при ударах, отрывах конечностей. Но итерацию мутаций, модификаторов и чем эффекта оставить.

2020-09-06 09:32 UTC, HentaiStorm commented
Сюда же температура тела, а вот тот же блок/аим также в статичное вычисление.

2020-09-06 09:37 UTC, PlinHost commented
Хотелось бы избавиться как раз от итераций. Особенно для мутаций, которые редко изменяются.

2020-09-06 09:43 UTC, HentaiStorm commented
Дык что он там итерировать будет, если он пустой?

2020-09-06 09:44 UTC, HentaiStorm commented
Это абсолютно не затратно, ну, в нормальных ЯПах, возможно у бьеонда другое мнение на этот счет)

2020-09-06 09:45 UTC, PlinHost commented
А если не пустой?

2020-09-06 09:46 UTC, HentaiStorm commented
Да он все равно return(-ит) минус один при mRun. А ФАТ никогда не падает.

2020-10-03 10:40 UTC, TobyThorne approved these changes
Нихуя не фиксит, но сортировка круто.

2020-10-23 21:05 UTC, Epicus7 requested changes

2020-10-23 21:05 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				return 1
Здесь было -1

2020-10-26 12:38 UTC, HentaiStorm commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				return config.human_delay
Убрать чтоли хуман делай?

2020-10-26 12:41 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				return config.human_delay
Лучше human_delay использовать в каком-то одном месте в функции. Чтобы у тебя не было двух мест, где одна и та же логика написана "вернуть human_delay". В одном месте ее поменяют, а в другом забудут.

2020-10-26 12:47 UTC, HentaiStorm commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				return config.human_delay
Так, ладно, один хрен менять логику кардинально буду. Это не соответствует условию все равно иссуя. Талли будет для каждого органа отдельный и в мувемент делай он будет итерироваться по ним. Изменяться талли будет от ударов/хиллов.

2020-11-23 11:38 UTC, Epicus7 approved these changes
Ну да, это уже гораздо больше похоже на оптимизацию. Такое даже принять можно.

Но вообще можно оптимизировать еще лучше и сделать код более надежным. Например, было бы неплохо добавить мобам систему бафов скорости. Когда изменяется всякая херня - она дает мобу датум "баф скорости", который хранит внутри себя это значение. Когда меняется обратно - отбирает этот баф.

А моб внутри себя просто отслеживает получение/снятие бафов, меняет переменную и больше вообще ничего в Лайфе не обновляет никогда.

Плюс пропадет этот стремный код с постоянными +=/-=, с которыми можно легко накосячить. Забытые баффы, в отличие от забытого -=, можно отслеживать ассертами (например при смерти персонажа проверять, что с него все баффы снялись и мы ничего не забыли).

Но ладно, это так, варианты для будущего улучшения. В принципе уже неплохая оптимизация.

2020-11-23 11:38 UTC, Epicus7 commented on code/modules/organs/external/_external.dm
> +	var/broken_tally      = 3          // 1.5 tally if limb broken
Переменные, которые не меняются, лучше объявлять через макросы или const.

2020-12-07 09:23 UTC, kreeperHLC approved these changes

2020-12-07 09:24 UTC, kreeperHLC requested changes
Да какого, я же видел что конфликтов нет

2020-12-14 12:53 UTC, TobyThorne commented
Перезалил с исправлениями конфликтов и всплывшего бага с магбутсами.

2020-12-14 12:53 UTC, closed without merging