Fix(new_player.dm) ЖИЗНЬ ДАЛЬТОНИКАМ
ChaoticOnyx/OnyxBay pull request #3288
Opened 2020-09-01 11:15 UTC by BadRyuner

Добавление трейтов выносим в самый конец создания персонажа, т.к, когда трейт на дальтонизм тригерит update_client_color(), у хуманов доходит до 109 строки (helpers.dm) и какого-то хуя if(!client) возвращает true и в итоге не происходит обновления цветов, а у железяк наоборот, if(!client) возвращает false и цвета обновляются.
Также добавил в начало создания персонажа animate(client, color = null, time = 10), чтобы при перерождении не накладывались старые цвета.

Fix #593 

- [x ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел. 
P.S Вроде все работает нормально, но это не точно.
- [ x] Я запускал сервер со своими изменениями локально и все протестировал.
- [ x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-01 16:40 UTC, Doster-d commented
Ебать, что тут с diffом...

2020-09-01 16:42 UTC, BadRyuner commented
Чтож поделаешь, когда ты рукожоп

2020-09-01 17:23 UTC, jammer312 requested changes

2020-09-01 17:23 UTC, jammer312 commented on code/modules/mob/new_player/new_player.dm
> +	animate(client, color = null, time = 10) // delete all old special color shaders
Зачем оно здесь, если ниже зовется create_character, и в него ты эту строку тоже добавил?

2020-09-01 17:23 UTC, jammer312 commented on code/modules/mob/new_player/new_player.dm
> +	if (character.mind.assigned_role != "AI" && character.mind.assigned_role != "Cyborg")
То же самое, что и выше

2020-09-01 17:24 UTC, jammer312 commented
Еще мне чет не нравится, как оно реализовано (трейты с изменением переменных клиента). Если перелогиниться, дальтонизм остается? (да, мне влом самому запускать и проверять)

2020-09-01 17:41 UTC, BadRyuner commented on code/modules/mob/new_player/new_player.dm
> +	animate(client, color = null, time = 10) // delete all old special color shaders
Жирный костыль. Когда тестил, при респавне за киборга не ресетился цвет

2020-09-01 17:47 UTC, BadRyuner commented
Я у себя в helpers.dm запихнул много логов и заходил за человека, а потом за киборга и смотрел до куда доходил код. За человека client был равен false, за киборга наоборот. Решил спустить вниз и оно заработало как надо. Потом впилил через проверку на роль защиту от дальтонизма для роботов. Ну и в начало ресет цвета, чтобы не было проблем, когда ты респавнишься за робота, а у тебя сохранился дальтонизм.

2020-09-03 11:52 UTC, BadRyuner commented
Да еб, че за бред опять с диффами

2020-09-03 15:41 UTC, jammer312 approved these changes

2020-09-06 12:26 UTC, TapKo4eB approved these changes
смешной вайтспейс

2020-09-06 12:27 UTC, merged