Обновление иконок у предметов из фабрикатора.
ChaoticOnyx/OnyxBay pull request #3291
Opened 2020-09-01 16:33 UTC by Doster-d

В текущий версии билда фабрикатор просто создается предмет, без обновление его иконки ( к примеру батарея ), данный ПР решает это недоразумение.

Я не нашел иссуи, которые ссылаются на проблему описанную в данном ПРе.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-01 16:59 UTC, jammer312 requested changes
<https://discordapp.com/channels/414832443384659968/447559366237880341/750399068005597344>

2020-09-01 17:03 UTC, Doster-d commented
done.

2020-09-01 18:43 UTC, jammer312 approved these changes

2020-09-04 06:45 UTC, TobyThorne commented
Как-то костыльно. Отдельные подтипы пустых батареек.

2020-09-04 07:02 UTC, Doster-d commented
> Как-то костыльно. Отдельные подтипы пустых батареек. 

А лучше при создание изменять запас энергии и обновлять иконку?

2020-09-06 08:58 UTC, PlinHost commented
> Как-то костыльно. Отдельные подтипы пустых батареек.

Они в любом случае уже есть и используются в других местах.

2020-09-06 08:59 UTC, PlinHost approved these changes

2020-09-06 11:33 UTC, Doster-d commented
Кворум набран

2020-09-06 12:16 UTC, merged