rework & fix datum/objective
ChaoticOnyx/OnyxBay pull request #3305
Opened 2020-09-05 20:07 UTC by HentaiStorm

Зафикшен баг, при котором не выполнялся обжектив на десятиминутный арест. Проблема заключалась в криворукости программистов, что сделали сие творение таковым, что is_brigged "запускался" и вычислялся только в конце игры. Исправлено введением нового прока для обжективов, что выполняется каждый игровой тик для каждого моба что имеет обжектив. Практически не затратно и затрагивает на данный момент только арест ревы и триторов. В идеале создает новую платформу для обжективов, что могут в потиковое вычисление.

close #3303 

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
~ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-05 23:59 UTC, Epicus7 requested changes

2020-09-05 23:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> +			if(target.is_brigged(10 * 60))
```suggestion
			if(target.is_brigged(10 MINUTES))
```

2020-09-05 23:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> +			if(target.is_brigged(10 * 60))
```suggestion
			if(target.is_brigged(10 MINUTES))
```

2020-09-05 23:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> -			if(target.current.stat == DEAD)
А эта проверка куда подевалась? Мы теперь проверяем трупы на то, сидят ли они в тюрьме?

2020-09-05 23:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> +			if(target.is_brigged(10 * 60))
У тебя тут кстати сейчас 1 минута вместо 10.

10 * 60 * 10 раньше было т.к. в бьонде обычно время считается в децисекундах.

2020-09-05 23:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
>  		return 0
Зачем в process_currently чот возвращать? Ты не обрабатываешь результат. Давай уберем ретурны.

2020-09-05 23:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> +	process_currently()
Давай переименуем в `update`? А то какое-то "обработать сейчашнее".

2020-09-06 04:24 UTC, HentaiStorm commented
Готово

2020-09-18 10:12 UTC, Epicus7 approved these changes

2020-09-26 00:09 UTC, merged