tweak(changelling_revive) add toggle button for auto revive changelling.
ChaoticOnyx/OnyxBay pull request #3341
Opened 2020-09-13 17:24 UTC by Doster-d

Добавил кнопку для работы, должно удовлетворять условиям стелс генок, так же отлично будет работать решение и для проблемы с вербами, проверил, вроде работает.

Единственное, что здесь плохо как по мне, это строка:
```
addtimer(CALLBACK(src, .changeling_revive), 0 SECONDS)
```
( Нужна помощь, не смог вызвать проц через известные мне способы :-( )

~~Ну еще и английский, ну это так, мелочи.~~

close #3325 , close #1575 , close #624 .

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-13 22:10 UTC, jammer312 approved these changes
С английским да, беда, остальное вроде норм

2020-09-13 22:32 UTC, Doster-d commented
Так зачем аппрув? Надо исправлять английский, есть советы по изменению текста?

2020-09-18 01:39 UTC, Epicus7 requested changes
Эм.. А как стелсогенокрады встанут после отказа? Видимо никак?

2020-09-18 09:33 UTC, jammer312 commented
Можно сделать, чтобы при включении авторевайва сразу ревайв прожимался (если генка в стазисе).
Но имхо лучше таки убрать цирк с добавлением/забиранием верба и повесить весь функционал на стазис (вне стазиса кладет в стазис: в стазисе, если генка готов ревайнвуться, ревайвает) (и выпилить авторевайв)

2020-09-18 09:35 UTC, Doster-d commented
> Можно сделать, чтобы при включении авторевайва сразу ревайв прожимался (если генка в стазисе).
> Но имхо лучше таки убрать цирк с добавлением/забиранием верба и повесить весь функционал на стазис (вне стазиса кладет в стазис: в стазисе, если генка готов ревайнвуться, ревайвает) (и выпилить авторевайв)

Вот это я сделаю.

2020-09-19 04:52 UTC, Doster-d commented
Готово.

2020-09-19 05:55 UTC, jammer312 commented on code/game/gamemodes/changeling/changeling_powers.dm
> +		verbs -= /mob/living/carbon/human/proc/changeling_fakedeath
Зачем?

2020-09-19 05:56 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +		verbs -= /mob/living/carbon/human/proc/changeling_fakedeath
Просто что бы быть уверенным, что не будет двух одинаковых проков?

2020-09-19 06:01 UTC, jammer312 commented on code/game/gamemodes/changeling/changeling_powers.dm
> +		verbs -= /mob/living/carbon/human/proc/changeling_fakedeath
Вместо добавления дополнительного выпиливания и добавления верба (тот же цирк, который предлагалось выпилить), нужно либо переписать прок добавления вербов, чтобы он не трогал лишний раз верб ревайва.
Или, что лучше, запилить (отдельным проком) проверку типа "может ли генка пользоваться силами", которая фейлится по крайней мере в стазисе, и пихнуть ее в каждый верб генки (и не трогать вербы при входе в стазис и при ревайве)

2020-09-19 06:02 UTC, jammer312 commented
Я бы еще добавил сообщение про готовность к ревайву в /Login()

2020-09-19 06:05 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +		verbs -= /mob/living/carbon/human/proc/changeling_fakedeath
Понял

2020-09-19 17:12 UTC, Doster-d commented
Готово.

2020-09-19 17:24 UTC, jammer312 requested changes

2020-09-19 17:24 UTC, jammer312 commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(status_flags & FAKEDEATH)
Мне не нравится то, что у тебя везде понатыканы вот эти две строки. Писал же, запили отдельный прок, который проверяет это, и пользуйся им. Т.е. вместо `if (status_flags & FAKEDEATH)` `if(is_regenerating())` или `if(!can_use_powers())` или еще что.

2020-09-19 17:24 UTC, jammer312 commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(status_flags & FAKEDEATH)
Зачем? Затем, чтобы если вдруг условия проверки поменяются, не нужно было искать по всему коду вот эти проверки и руками их править.
К слову, хз, как тут, но на ТГ есть химикат, который вызывает оную FAKEDEATH, возможно, стоит глянуть, нет ли тут такого, и допилить проверку, чтобы она не включала в себя действие этого химиката.

2020-09-19 17:24 UTC, jammer312 commented on code/modules/mob/living/login.dm
> +	if(mind.changeling.is_revive_ready)
А `mind.changeling` у не-генок есть? Я бы на всякий случай использовал бы здесь `?.` вместо `.`
Т.е. `mind.changeling?.is_revive_ready`

2020-09-19 17:28 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(status_flags & FAKEDEATH)
Так оно и есть, может это как фичу поставить?

2020-09-19 17:28 UTC, Doster-d commented on code/modules/mob/living/login.dm
> +	if(mind.changeling.is_revive_ready)
Так если там null, то не пойдет дальше (по условию), верно?

2020-09-19 17:47 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(status_flags & FAKEDEATH)
Я имею в виду фичу с реагентом, который выдает FAKEDEATH, типо организм генки принял этот препарат за стазис?

2020-09-19 17:50 UTC, Doster-d commented
Алсо, я починил, то что указано было

2020-09-19 17:59 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(status_flags & FAKEDEATH)
К тому же такая же проверка есть и в текущем ревайве, поэтому я думаю это фича скорее, чем баг.

2020-09-19 20:12 UTC, jammer312 approved these changes
Теперь вроде норм

2020-09-20 01:28 UTC, Epicus7 approved these changes

2020-09-20 01:31 UTC, merged