ТобиБоёвочка (simple_animals edition)
ChaoticOnyx/OnyxBay pull request #3380
Opened 2020-09-22 15:51 UTC by TobyThorne

tl;dr удары простых_животных можно блокировать, парирования проще, мобы дохнут от урона без задержки

- Добавлена возможность блокировать атаки мобов. Урон по пойзу зависит от урона моба, а так же от длины и удобства оружия (выше значения - меньше урона).
- Проверка на закончившееся здоровье происходит при каждом получении мобом урона. Так что больше не будет задержки перед смертью. 
- Враждебные мобы получили 25% сопротивление урону от выстрелов. 
- Длительность окна парирования увеличена на 50% (i.e. с 0.8 до 1.2 секунд у монтировки). 
- Действия с полом теперь работают только при интенте HELP. Так что теперь во время драк монтировки не будут раскидывать в стороны плитку, отвёртки не будут скручивать паркет, а плиточки - укладываться.
- Порог пойза для выбивания предмета из рук во время блока снижен с 30% до 25%.
- Выбитые из рук во время блока предметы теперь не просто падают под космонавтика, а отлетают в сторону. Если предмет просто выбит - то на 1-2 тайла, если космонавтик упал (очень низкий пойз) - то на 1-3 тайла.
- Ребаланс генкомобов: 
*урон генкорук и генконог уменьшен с 15-20 до 7.5-12.5 урона
*урон генкоголовы увеличен с 15-20 до 17.5-22.5 урона
*урон генкотела остаётся прежним (15-20)
*урон хэдкраба уменьшен до 5.0-7.5 урона
*здоровье хэдкраба уменьшено с 50 до 40 хп
*все генкомобы кроме тела теперь не могут пуллить больших мобов (i.e. людей)
*как и остальные враждебные мобы, генкомобы получили 25% сопротивления урону от выстрелов
- Исправлена слишком высокая скорость у предметов, выбитых из рук выстрелом. Раньше они отлетали со скоростью 30, из-за чего могли запросто гиббнуть конечность того, кому не повезло оказаться рядом.

Внутреннее, не затрагивающее геймплей:
- Блоки и парирования теперь процессятся на стороне защищающегося, а не атакующего;
- Выбивание предметов из рук ударами (во время блока/парирования) вынесено в отдельную функцию. Чуть меньше _качественной копипасты_™;

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-22 16:17 UTC, Ruforce commented
Что ты подразумеваешь под термином "урон от выстрела"?

2020-09-22 17:26 UTC, TobyThorne commented
> Что ты подразумеваешь под термином "урон от выстрела"?

Урон от, как ни странно, выстрела. Всё, что нанесено проджектайлом, а не атакой.

2020-09-22 17:45 UTC, TapKo4eB commented
ааа типо, зачем нужно это? разве это не усложнит к примеру убийство шахтёрам мобов на астероиде или тех же конечностей лазерами и т.д.?

2020-09-22 17:55 UTC, TobyThorne commented
> ааа типо, зачем нужно это? разве это не усложнит к примеру убийство шахтёрам мобов на астероиде или тех же конечностей лазерами и т.д.?

Чтобы сложнее было убивать из дальнобойного оружия. В ПвП от огнестрела можно уворачиваться, а вот в ПвЕ огнестрел в тысячу миллионов раз эффективнее, чем мили. Те же генкомобы в мили могут загрызть и через РИОТ-броньку, но гарантированно помирают всей стаей от одного стрелка с лазером.

2020-10-14 05:21 UTC, Epicus7 commented
А может это пофиксим заодно?

#1907

2020-10-21 19:00 UTC, TobyThorne commented
Update floor_attackby.dm
(теперь попытка ударить пол теперь будет срать сообщениями)

2020-10-24 17:41 UTC, Epicus7 requested changes

2020-10-24 17:41 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
Раз уж залез, нельзя здесь нормально переменные назвать?

user -> attacker,
w_atk -> weapon

2020-10-24 17:41 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_block_weapon(mob/living/user, obj/item/w_atk)
И тут

2020-10-24 17:41 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			if(defender.poise <= 10.0)
Это чо такое? В бьонде все числа с плавающей точкой. 10 == 10.0, по идее.

2020-10-24 17:41 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_block_normal(mob/living/user, atk_dmg = 5.0)
Тоже переменные бы переименовать

2020-10-24 18:06 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
Низя. Для удобства названо w_atk, а не weapon, ибо дальше есть ещё w_def.
User и так позже становится attackerом, когда удостоверяемся, что он валидный нападатель.

2020-10-24 18:08 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
attacker_weapon в таком случае.

w_def и user ничего не говорят. Это хуевые названия, не надо так называть переменные.

2020-10-24 18:08 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			if(defender.poise <= 10.0)
Таки привычка. Могу и обратно на 10 перекинуть, но как-то не очень смотрится, когда по соседству всякие 2.5, 7.5, etc.

2020-10-24 18:08 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
У тебя функция "обработать уклонение". И аргумент ПОЛЬЗОВАТЕЛЬ. Пользователь обработки уклонения? Ват?

2020-10-24 18:12 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
Лучше короткие w_atk и w_def, про которые ещё и сказано в комменте, чем растягивать код на километры в ширину со всякими attacker_weapon и defender_weapon, с которыми ещё можно сделать typo и потом долго материться. У меня клавиатуры и суставы не деревьях не растут.

2020-10-24 18:13 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
>У тебя функция "обработать уклонение". И аргумент ПОЛЬЗОВАТЕЛЬ. Пользователь обработки уклонения? Ват?
Ну ладно, это считается, пох. Есть идеи, на шо заменить?

2020-10-24 18:15 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
defender?

2020-10-24 18:16 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
У тебя код получается нечитабельный. С твоими user-ами ты сам путаешься, из-за чего и был косяк в коде, который ты исправил.

А w_atk вообще непонятно что значит. Я тупо читаю код и не понимаю что в нем происходит. Читабельность кода важнее, чем экономия буковок.

Чтобы не набирать много буковок можно использовать автодополнение, да.

Алсо про все это есть соответствующий раздел в гайде ту контрибут:
https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9

> Имена должны передавать намерения программиста

user не передает смысл переменной

> Избегайте сокращений, старайтесь выбирать удобопроизносимые имена

w_atk - это нечитаемое сокращение, которое невозможно понять без дополнительных комментариев.

2020-10-24 18:17 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
attacker?

2020-10-24 18:19 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
> Ну ладно, это считается, пох. Есть идеи, на шо заменить?

Так attacker же.

2020-10-24 18:33 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
>attacker 
Какой нахуй attacker, если attacker позже используется. Его мне во что переименовать тогда и нахуя?

2020-10-24 18:45 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
attacker_usr?

2020-10-24 18:55 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
А почему у тебя user этот вообще типа /mob/living, если в проке эта переменная используется только с типом human? Ты можешь сразу аргументом написать /mob/living/carbon/human/attacker

2020-10-24 18:56 UTC, TobyThorne commented
Переименовал userов в attacker_mobов, w_atk/w_def в weapon_atk/weapon_def соответственно. Если гипотетический ваннаби кодерок не сможет понять, что это оружие атакующего и оружие защищающегося - проблема не в названии, а в долбоёбе.

2020-10-24 18:57 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> +/mob/living/carbon/human/proc/handle_parry(mob/living/user, obj/item/w_atk)
Потому что не всё сразу. Вот щас мобов в боёвку добавил, через годик ещё боргов подвезу.

2020-10-25 23:54 UTC, Epicus7 approved these changes

2020-10-26 18:26 UTC, TatarTheBuilder approved these changes
пишу ченить с умным видом

2020-10-26 18:32 UTC, merged