Мелкофикс баллонок
ChaoticOnyx/OnyxBay pull request #3382
Opened 2020-09-24 10:28 UTC by sweden-moose

Исправил изменение спрайта баллонок при откручивании или прикручивании различных частей.
Фикс [#1786](https://github.com/ChaoticOnyx/OnyxBay/issues/1786)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-24 12:45 UTC, TapKo4eB commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
![kdnm](https://user-images.githubusercontent.com/48761132/94146688-f7804580-fe7c-11ea-823c-75cb75c60dc2.png)

2020-09-24 13:15 UTC, sweden-moose commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
Гитхуб десктоп, помянем

2020-09-24 17:17 UTC, jammer312 commented on code/game/objects/items/weapons/tanks/tanks.dm
> -	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
![image](https://user-images.githubusercontent.com/3525275/94177875-f9f59600-fea2-11ea-90f2-7acc64705252.png)

2020-09-24 17:19 UTC, Doster-d commented on code/game/objects/items/weapons/tanks/tanks.dm
> -	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
А что тут поменялось?

2020-09-24 17:20 UTC, jammer312 commented on code/game/objects/items/weapons/tanks/tanks.dm
> -	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
Вот именно

2020-09-24 17:29 UTC, jammer312 requested changes

2020-09-24 17:29 UTC, jammer312 commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	update_icon(1)
Здесь и ниже должно быть `TRUE` вместо `1`

2020-09-24 17:29 UTC, jammer312 commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	update_icon(1)
Это мне совсем не нравится.

2020-09-24 17:29 UTC, jammer312 commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	tank.update_icon(1)
Это тоже

2020-09-24 17:39 UTC, jammer312 commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	update_icon(1)
На случай, если причина доеба неочевидна, ты заставляешь `update_icon` каждый тик удалять все оверлеи и клеить их заново. **Каждый тик** для **всех** баллонов на станции. Там этот `override` не просто так пихнут, чтобы постоянно его пользовать. Состояние газа он смотрит сам и без оверрайда. Единственная ситуация, когда оверрайд нужен - когда ты извне с баллоном что-то сделал (приляпал провода etc).

2020-09-24 17:40 UTC, sweden-moose commented on code/game/objects/items/weapons/tanks/tanks.dm
> +	update_icon(1)
Причина доёба очевидна, я так и думал. Не хватило смелости спросить в школьном автобусе.

2020-09-24 17:50 UTC, jammer312 approved these changes
Теперь вроде норм (за вычетом той строки, в которой нихера не поменялось, но которая все равно отображается в диффе)

2020-09-24 17:54 UTC, Doster-d commented on code/game/objects/items/weapons/tanks/tanks.dm
> -	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
Кодировка поменялась, поэтому дифф, мое мнение.

2020-09-25 18:46 UTC, sweden-moose commented on code/game/objects/items/weapons/tanks/tanks.dm
> -	Each tank is fitted with an emergency relief valve. This relief valve will open if the tank is pressurised to over ~3000kPa or heated to over 173�C. \
VS Code шалит

2020-09-26 00:04 UTC, Epicus7 approved these changes

2020-09-26 00:08 UTC, merged