Базы данных для медиков и СБ.
ChaoticOnyx/OnyxBay pull request #3413
Opened 2020-09-28 14:46 UTC by jammer312

Дополняет текущие /record_field/, добавляя два флага контекста, которые задают, в каком контексте можно смотреть и изменять соответствующую запись, попутно, меняет контексты у некоторых имеющихся флагов. Например, отпечатки пальцев видны везде (как и раньше), но редактировать их можно только в контексте СБ.
Пока что три контекста, crew (в нем все, что имеющая прога рекордсов показывает), медицинский и СБшный.
Дает имеющейся проге рекордсов контекст crew, добавляет два наследника этой проги, которые работают в медицинском и СБшном контексте.
Реализует СБшного наследника согласно #1020.
Медицинский наследник пока не готов, будет реализован по #1172.

Размер проги уменьшен для удобства тестирования, потом верну обратно.
Выкладываю чисто ради предварительных ревью, если вдруг кто соберется.

closes #1020, closes #1172

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-09-29 21:57 UTC, PlinHost reviewed
Новые проги и темплейты к ним пока не смотрел.

2020-09-29 21:57 UTC, PlinHost commented on code/modules/modular_computers/file_system/crew_record.dm
> +var/const/record_field_context_universal   = ~record_field_context_none
Наверное лучше было бы дефайнами сделать, но не критично.

2020-09-29 21:57 UTC, PlinHost commented on code/modules/modular_computers/file_system/crew_record.dm
> +/record_field/status_mental/acccess_edit = access_medical
Здесь и выше осталось определение, вместо которого новый дефайн. Алсо, два макроса на строке плохо читаются, может разнести?

2020-09-29 21:57 UTC, PlinHost commented on code/modules/modular_computers/file_system/crew_record.dm
> +#define CONTEXT(KEY) record_field_context_##KEY
Почему не поставить `CONTEXT()` в макросы выше вместо того, чтобы каждый раз оборачивать аргумент?

2020-09-30 08:43 UTC, jammer312 commented on code/modules/modular_computers/file_system/crew_record.dm
> +#define CONTEXT(KEY) record_field_context_##KEY
Для того, чтобы можно было их битовыми операциями клеить.

2020-10-01 20:37 UTC, Doster-d commented
Может добавить Security Records в раздел Security?

2020-10-01 20:49 UTC, Doster-d commented on code/modules/modular_computers/file_system/crew_record.dm
> +GLOBAL_LIST_INIT(mental_statuses, list("Stable", "*Watch*", "*Unstable*", "*Insane*"))
А точно нужны \*слово\*?
А то выглядит так (не очень как по мне):
![problem](https://user-images.githubusercontent.com/63081538/94861302-f7b1af80-043f-11eb-85d9-79ce474e55bf.png)

2020-10-06 13:25 UTC, jammer312 commented on code/modules/modular_computers/file_system/crew_record.dm
> +GLOBAL_LIST_INIT(mental_statuses, list("Stable", "*Watch*", "*Unstable*", "*Insane*"))
Окэй, поменял

2020-10-06 13:36 UTC, jammer312 commented
> Может добавить Security Records в раздел Security?

А смысл? Сейчас все три проги в одном разделе (и по сути они делают одно и то же). Если утаскивать секрекорды в раздел security, то по идее нужно то же самое с медицинскими делать, что по сути означает создание еще одного раздела под одну программу (вроде там еще монитор датчиков есть, но он в разделе мониторинга, можно его вытащить в медицинский, но тогда зачем нужен раздел мониторинга? если это делать, по идее нужно вообще категории перерабатывать тем или иным образом, но мне малость влом).
Tldr; из соображений консистентности пусть пока будет в офисном.

2020-10-27 00:47 UTC, Epicus7 commented
0. В следующий раз, пожалуйста, добавляй скриншоты на все окошки, которые ты сделал.

1. Надо бы добавить Security Records в раздел программ СБ. Медицинские тоже бы куда-то пихнуть, мб раздел для медицинских программ сделать?

![image](https://user-images.githubusercontent.com/5204667/97242276-8679d800-1804-11eb-9e54-efc9cf4bad33.png)

2. Вот эта кнопка вообще внезапная. Я неожидал что она сделает то, что сделала. А можешь сделать отдельную секцию "Recent Records", которая будет состоять из кнопки "Archivate current status" и соответственно старых записей?

![image](https://user-images.githubusercontent.com/5204667/97242558-40714400-1805-11eb-9162-c5bee84105fe.png)

3. Тут, кстати, картинка поломалась. По идее должна быть вторая картинка, где персонаж повернут в сторону. Кстати, почему Generic? Мб General?

![image](https://user-images.githubusercontent.com/5204667/97242761-bf667c80-1805-11eb-8e88-47bea36aa22b.png)

4. В очках очень не хватает отображения всех текущих записей (без архива):

![image](https://user-images.githubusercontent.com/5204667/97243038-75ca6180-1806-11eb-9156-45e39b4adfe3.png)

Но это я забыл добавить в иссуй. Будет неплохо если сделаешь, но это не обязательно для закрытия ПРа и награды, да. Тоже самое, кстати, с медицинскими записями.

5. Получается у нас Warrant Assistant никак не синхронизируется с Security Records. Я думаю нет смысла пилить им синхронизацию какую-то и Warrant Assistant можно просто выпилить. Потом мб какой-то функционал из него добавим в Security Records, если будет такой.

2020-10-27 01:02 UTC, Epicus7 commented
6. Было бы неплохо цвета добавить статусам Службы Безопасности при отображении в интерфейсах.

7. Из Crew manifest куда-то потерялся статус СБ. Он там должен быть read-only.

2020-10-27 01:03 UTC, Epicus7 requested changes
По коду нормально, accccess только пофиксить бы.

2020-11-02 21:17 UTC, jammer312 commented
![image](https://user-images.githubusercontent.com/3525275/97920084-f854a300-1d69-11eb-8593-72f8edb53551.png)

2020-11-02 21:24 UTC, jammer312 commented
![Uploading image.png…]()

2020-11-02 21:26 UTC, jammer312 commented
![image](https://user-images.githubusercontent.com/3525275/97920912-3b634600-1d6b-11eb-9834-82c5431beb5b.png)

2020-11-02 21:31 UTC, jammer312 commented
Для щиткурионского хада тоже запилено.
Generic ибо он в проге-родителе generic, тут я ничего не менял.
Warrant Assistant не трогал, мне кажется, он выполняет свою отдельную функцию (выписку ордеров), и выпиливать его не стоит. Имхо он и не должен совсем синхронизироваться с секрекордами.
Цвета кнопке пока не запилил, ща, может, гляну еще.

2020-11-02 21:51 UTC, jammer312 commented
![image](https://user-images.githubusercontent.com/3525275/97923143-98143000-1d6e-11eb-8072-e05b48169425.png)
¯\\\_(ツ)_/¯

2020-11-17 12:33 UTC, Epicus7 approved these changes

2020-11-22 14:30 UTC, PlinHost approved these changes

2020-11-23 11:40 UTC, merged