Чиним ревайв генокрада, версия 2.
ChaoticOnyx/OnyxBay pull request #3435
Opened 2020-10-01 22:06 UTC by Doster-d

Надеюсь, что исправил баг со структурой, я сделал вызов того же прока "возрождения" биоструктуры, ~~оставил язвительный комментарий по поводу рук того, кто это кодил до меня~~, что было до моего влезания в код.

Еще поменял местами подтверждение ревайва и проверки на регенерацию, что бы не вызывало лишних вопросов у игроков.

У меня тоже растут руки не из того места.

close #3433 close #3402

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-01 22:06 UTC, Doster-d commented
Пока еще ищу решения для #1917, это может быть связано с проблемой этого ПРа.

2020-10-01 23:04 UTC, Doster-d commented
Моя победить бульон. Моя устать :(

2020-10-02 01:23 UTC, Epicus7 requested changes

2020-10-02 01:23 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/species/species.dm
> +		H.internal_organs_by_name[BIO.organ_tag] = BIO // just to be sure we actually add changeling internal organ
Не надо тащить код генокрадов в код человеков, пожалуйста. И орган пересоздавать - тоже плохая идея.

Добавь во все органы новую переменную `foreign`, которая будет означать, что это чужеродный орган, который должен оставаться в человеке после revive-а.

В начале этой функции, в условии
```
	for(var/obj/item/organ/organ in H.contents)
		if((organ in H.organs) || (organ in H.internal_organs))
			qdel(organ)
```

Проверяй, если organ.foreign == TRUE. В таком случае не удаляем этот орган, а пихаем его во временный локальный список foreign_organs.

В конце прока добавляем эти foreign_organs на место.

2020-10-02 17:27 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/species.dm
> +		H.internal_organs_by_name[BIO.organ_tag] = BIO // just to be sure we actually add changeling internal organ
Я долго не понимал как это сделать, а потом я понял.

2020-10-02 17:57 UTC, Doster-d commented
Известные баги:
stack после ревайва не вызывается robotize(), из-за этого может быть гниение.
в контентс добавляются лишние конечности, последствия мне неизвестны.

2020-10-02 18:59 UTC, Doster-d commented
Я не понимаю как это починить, помогите.

2020-10-03 23:24 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/species.dm
> +		H.internal_organs_by_name[BIO.organ_tag] = BIO // just to be sure we actually add changeling internal organ
К сожалению, предложенный Вами метод (добавление органа в исключение при удаление), ломается из-за одного места в _external, метод Destroy():
```
	if(internal_organs)
		for(var/obj/item/organ/O in internal_organs)
			qdel(O)
```
\- по остальному я прислушался и исправил.

2020-10-06 05:05 UTC, Doster-d commented
When review?

2020-10-12 10:06 UTC, Doster-d commented
Тем времени на иссуе есть приоритет, а у генок жопа боль...

2020-10-13 02:12 UTC, Epicus7 requested changes

2020-10-13 02:12 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/species/species.dm
>  			qdel(organ)
Это можно сделать в одном цикле.

2020-10-13 02:12 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/species/species.dm
> +		var/obj/item/organ/O = new organ(H)
Пересоздавать орган плохо. Мы не можем переиспользовать тот же, что был? Просто сначала его вытаскиваем из списка, а потом обратно тот же орган запихиваем?

Проблема в том, что если орган хранит в себе какую-то информацию о текущем состоянии, то эта инфа будет стираться. Это очень неожиданное поведение будет.

2020-10-13 04:42 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/species.dm
>  			qdel(organ)
Нельзя, если первым будет external орган, то он его удалит (флага-то нет), а следом удалит и все internal органы

2020-10-13 04:45 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/species.dm
> +		var/obj/item/organ/O = new organ(H)
Можно, конечно, полезть в код удаления органов из external и там прописать о том, что бы не удалять потомков если у них есть флаг.
Вопрос - стоит ли код свеч?

2020-10-13 06:03 UTC, Doster-d commented
Сделал.

2020-10-14 17:27 UTC, Epicus7 approved these changes

2020-10-20 22:42 UTC, jammer312 requested changes

2020-10-20 22:42 UTC, jammer312 commented on code/modules/organs/organ.dm
> +	var/foreign = FALSE 			  // special organ tag, that says species.create_organs() to don't delete it.
```suggestion
	var/foreign = FALSE 			  // if TRUE, /datum/species/create_organs() won't delete it
```

2020-10-20 22:42 UTC, jammer312 commented on code/modules/mob/living/carbon/human/species/species.dm
> +		for(var/obj/item/organ/internal/O in E.internal_organs)
Почему здесь оно выдергивает их из внешних органов...

2020-10-20 22:42 UTC, jammer312 commented on code/modules/mob/living/carbon/human/species/species.dm
> +		H.internal_organs_by_name[organ.organ_tag] = organ
...но потом запихивает в внутренние?

2020-10-20 22:42 UTC, jammer312 commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(is_regenerating())
Добавь сообщение вроде "мы уже регенерируем, но еще не готовы встать"

2020-10-20 22:42 UTC, jammer312 commented on code/game/gamemodes/changeling/changeling_powers.dm
> +		make_changeling()
Чего это добивается?  Точно ли этого добиваться ровно через это?
Раньше же вроде обсуждали, что жонглирование вербами без причины - херовый ход.

2020-10-20 22:59 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/species.dm
> +		H.internal_organs_by_name[organ.organ_tag] = organ
Потому что там только external органы, а я просто скопировал данные с проверки?

2020-10-20 22:59 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(is_regenerating())
How? Мой ангельский ужасный. @TobyThorne помоги, пожалуйста.

2020-10-20 23:00 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +		make_changeling()
Костыль, что бы уж наверняка, все равно новые вербы не добавляет...

2020-10-20 23:27 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_powers.dm
> +	if(is_regenerating())
Ну сделал что-то

2020-10-20 23:48 UTC, jammer312 submitted a review, later dismissed

2020-10-21 00:03 UTC, jammer312 approved these changes

2020-10-23 20:47 UTC, Epicus7 approved these changes

2020-10-23 20:50 UTC, merged