Огнетушительное
ChaoticOnyx/OnyxBay pull request #3436
Opened 2020-10-01 22:15 UTC by TobyThorne

- Заправка огнетушителей теперь работает логичнее. Один клик полностью восполнит запас (если есть, чем). Пустые баки/полные огнетушители выдают соответствующее сообщение.
- Огнетушители теперь используют пожарную пену вместо воды. 
- Добавлена пожарная пена. Относительно пожаров работает как вода, но не мочит полы. Всё ещё наносит урон слизням (из соображений баланса).
- Увеличено удобство огнетушителей (атака быстрее, тратит меньше пойза, etc.) дабы скомпенсировать невозможность мочить полы.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-01 22:17 UTC, Doster-d commented
> Огнетушители теперь используют пожарную пену вместо воды.

Ты чево наделал...
![image](https://user-images.githubusercontent.com/63081538/94868999-fd61c200-044c-11eb-8335-e534cf7cf538.png)

2020-10-01 22:21 UTC, Vanner0 commented
![kotwithknife](https://user-images.githubusercontent.com/64439984/94869209-8bd64380-044d-11eb-8333-726a53caac89.jpg)

2020-10-06 08:40 UTC, PlinHost approved these changes, later dismissed
Меняем костыли на новые.

2020-10-27 01:06 UTC, Epicus7 commented
> баки с пеной будут когда-нибудь позже

Я думаю не стоит этого делать..

2020-10-27 01:12 UTC, Epicus7 requested changes

2020-10-27 01:12 UTC, Epicus7 commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +/datum/reagent/firefoam/affect_touch(mob/living/carbon/M, alien, removed)
Чтобы такой копипасты не было древние программисты изобрели наследование. Жаль в BYOND его нет... или.. ох черт, оно есть! А почему не используем?

Надо пену просто от воды унаследовать с единственным отличием, что оно полы не мочит. И все.

2020-10-27 01:12 UTC, Epicus7 commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
> +/datum/reagent/firefoam/affect_touch(mob/living/carbon/M, alien, removed)
Это один из вариантов как пофиксить. Копипаста энивей не нужна, ибо когда будут слизней менять, у воды поменяют ее эффект на слизней, а у пены забудут поменять.

2020-10-27 20:14 UTC, TobyThorne commented
- Обновил огнетушители для мехов под пену, нормальное наполнение, etc;
- Пена теперь наследуется от воды. Хотел бы на эту тему устроить срач, но воистину похуй уже.

2020-10-27 20:18 UTC, Epicus7 approved these changes
Чо срач то, лучше же код сейчас стал.

2020-10-27 20:25 UTC, jammer312 approved these changes
Вроде норм. Не совсем понятно, почему теперь расход наполнителя огнетушителем в почти два раза выше, но да хер с ним.

2020-10-27 20:27 UTC, TobyThorne commented
> Не совсем понятно, почему теперь расход наполнителя огнетушителем в почти два раза выше

Шоб примерно соответствовать расходу у обычных огнетухов. А то обычный огнетух выплёвывает 120 единиц, а меховский - 25. Смешное.

2020-10-27 21:48 UTC, merged