feat(cargo supply) plasma cutte comeback
ChaoticOnyx/OnyxBay pull request #3437
Opened 2020-10-01 23:11 UTC by Doster-d

Преамбула:
_Геймдизайну - цену за резак.
Народу - долгожданный резак._

Этот ПР добавляет еще один способ получение резака - через карго.
Я установил цену в 75 в ожидание того, что медианная поставка в карго дает - 400 поинтов, а шахтеров обычно - 3, поэтому я решил, что +2 будет в запасы на свои нужды. Геймдизайну предстоит решить - существовать ли этому способу и за какую цену, иль нет.

Оставляю первый пункт открытым до решения геймдизайнеров.
- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-02 18:50 UTC, TobyThorne requested changes
![image](https://user-images.githubusercontent.com/45202681/94959123-770fb380-0512-11eb-95f4-8a0e5ccd0163.png)

2020-10-02 18:57 UTC, TobyThorne approved these changes
![image](https://user-images.githubusercontent.com/45202681/94959667-63b11800-0513-11eb-9c36-4c969ca4c23e.png)

2020-10-02 18:58 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/94959744-5a678180-04fa-11eb-934e-93130d17ab85.png)

2020-10-12 01:36 UTC, Epicus7 commented
Хз зачем. Лучше бы РнД занялся.

Иссуя нет, значит народу не надо ничего. Ты нас обманываешь.

2020-10-12 03:09 UTC, Doster-d commented
> Хз зачем. Лучше бы РнД занялся.
> 
> Иссуя нет, значит народу не надо ничего. Ты нас обманываешь.

https://github.com/ChaoticOnyx/OnyxBay/issues/2792#issuecomment-647340634

2020-10-12 09:51 UTC, PlinHost commented
> [#2792 (comment)](https://github.com/ChaoticOnyx/OnyxBay/issues/2792#issuecomment-647340634)

Не знал, что MrMagick2104 является геймдизайнером.

2020-10-12 09:52 UTC, closed without merging

2020-10-12 09:55 UTC, Doster-d commented
Ну я пытался...

2020-10-12 11:59 UTC, MrMagick2104 commented
> Иссуя нет, значит народу не надо ничего. Ты нас обманываешь.

![123](https://user-images.githubusercontent.com/58848742/95743735-e2881c80-0c9a-11eb-953a-8f6257187d8b.PNG)

> >  52

> народу не надо ничего

Никто никого не обманывает. Иссуй - #2796.