Мелкофикс световых мечей
ChaoticOnyx/OnyxBay pull request #3500
Opened 2020-10-14 12:45 UTC by sweden-moose

close #2461

Теперь нельзя просрать saber/dualsaber при соединении с dualsaber

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-17 22:03 UTC, PlinHost commented
Все еще можно просрать пиратскую саблю и bogsword, чем бы он ни был. Я уже предлагал решение:
>Раз у нас столько подтипов энергомеча, хорошо было бы вынести "обычный" ака триторский тоже в подтип.

https://github.com/ChaoticOnyx/OnyxBay/pull/2481#pullrequestreview-417835293 https://github.com/ChaoticOnyx/OnyxBay/pull/2546#issuecomment-636393262

2020-10-18 11:13 UTC, kreeperHLC approved these changes

2020-10-18 11:15 UTC, sweden-moose commented
не надо аппрувать пираты сломали билд

2020-10-18 11:15 UTC, kreeperHLC requested changes
А тьфу, посмотрел на код, но не заметил что Травису плохо.

2020-10-18 11:44 UTC, sweden-moose commented
Fixed

2020-10-18 11:58 UTC, kreeperHLC submitted a review, later dismissed

2020-10-18 12:21 UTC, 4310V343k requested changes

2020-10-18 12:21 UTC, 4310V343k commented on maps/exodus/exodus-3.dmm
> +"mDS" = (/obj/structure/closet/crate,/obj/item/weapon/implanter/freedom,/obj/item/weapon/implantcase/freedom,/obj/item/weapon/implanter/explosive,/obj/item/weapon/implantcase/explosive,/obj/item/weap
Было два, а остался один

2020-10-18 12:24 UTC, sweden-moose commented on maps/exodus/exodus-3.dmm
> +"mDS" = (/obj/structure/closet/crate,/obj/item/weapon/implanter/freedom,/obj/item/weapon/implantcase/freedom,/obj/item/weapon/implanter/explosive,/obj/item/weapon/implantcase/explosive,/obj/item/weap
Исправил

2020-10-18 20:41 UTC, PlinHost commented
Как-то много копипасты вышло. Я предлагал сделать новый подтип для триторских, а не вынести все остальные из него. Хотя если потом потвикать характеристики, что нужно бы, потому что сабля, отличающаяся от меча только иконкой - неоч, не так уж и много будет.

2020-10-19 04:29 UTC, sweden-moose commented
Плин, нарисуй в пейнте схему, пожалуйста.

2020-10-19 06:51 UTC, sweden-moose commented
Не надо схем, я всё понял.

2020-10-19 08:52 UTC, TapKo4eB commented
ждём когда допоймёшь

2020-10-19 14:10 UTC, sweden-moose commented
Вроде теперь всё нормально. Если я правильно понял идею Плина.

2020-10-19 19:33 UTC, PlinHost commented on code/game/machinery/doors/airlock.dm
> +	else if(istype(item,/obj/item/weapon/melee/energy/blade) || istype(item,/obj/item/weapon/melee/energy/sword/one_hand))
Я думаю, двери должно быть можно ломать любым энергомечом.

2020-10-19 19:33 UTC, PlinHost commented on code/game/objects/items/weapons/melee/energy.dm
> +	return
Это переопределение все еще нужно?

2020-10-19 19:33 UTC, PlinHost commented on code/game/objects/structures/crates_lockers/closets/gimmick.dm
> +		/obj/item/weapon/melee/energy/sword/one_hand = 3,
Раз уж трогаем, можно поставить мечи цвета команд.

2020-10-19 19:33 UTC, PlinHost commented on code/modules/clothing/spacesuits/alien.dm
> +	allowed = list(/obj/item/weapon/gun,/obj/item/ammo_magazine,/obj/item/ammo_casing,/obj/item/weapon/melee/baton,/obj/item/weapon/melee/energy/sword/one_hand,/obj/item/weapon/handcuffs,/obj/item/weapo
Воксы используют пиратские сабли. Вообще, энергомечи примерно одинаковые, так что можно разрешить любые здесь и в синдискафандрах.

2020-10-19 20:18 UTC, sweden-moose commented
Ну теперь точно всё

2020-10-19 20:22 UTC, PlinHost commented on code/game/machinery/doors/airlock.dm
> +	else if(istype(item,/obj/item/weapon/melee/energy/blade) || istype(item,/obj/item/weapon/melee/energy/sword/))
Слэш остался.

2020-10-19 20:27 UTC, sweden-moose commented
Ну теперь точно всё

2020-10-27 01:26 UTC, Epicus7 requested changes
Забыл поменять пути красным мечам на картах alpha/alpha-4 и prison/prison-3.

2020-11-02 08:14 UTC, sweden-moose commented
Пофиксиль

2020-11-12 01:28 UTC, TobyThorne commented
Не совсем понимаю, зачем выносить одноручный меч в отдельный подтип, когда можно было просто добавить одну переменную и проверять её при соединении.

2020-11-12 11:13 UTC, sweden-moose commented
> Не совсем понимаю, зачем выносить одноручный меч в отдельный подтип, когда можно было просто добавить одну переменную и проверять её при соединении.


Ето рекуест ченжес или совет?

2020-11-12 14:58 UTC, kreeperHLC approved these changes

2020-12-01 11:39 UTC, Doster-d commented on code/game/objects/items/weapons/melee/energy.dm
> -	name = "energy sword"
Что? Почему? Зачем? Чем оно мешало? Я не понял :-(

2020-12-01 11:40 UTC, PlinHost approved these changes

2020-12-01 11:40 UTC, sweden-moose commented on code/game/objects/items/weapons/melee/energy.dm
> -	name = "energy sword"
Зачем это в родителе хранить? Всё в /obj/item/weapon/melee/energy/sword/one_hand

2020-12-01 11:44 UTC, Doster-d commented on code/game/objects/items/weapons/melee/energy.dm
> -	name = "energy sword"
Доеб отклонен.

2020-12-01 11:44 UTC, Doster-d approved these changes

2020-12-07 07:16 UTC, sweden-moose commented
Всем привет дайте мерж

2020-12-07 07:57 UTC, Epicus7 approved these changes

2020-12-07 07:57 UTC, Epicus7 commented
Конфликты приехали :(

2020-12-07 09:17 UTC, merged