удаляем мерков
ChaoticOnyx/OnyxBay pull request #3501
Opened 2020-10-14 14:51 UTC by TapKo4eB

меняем их на синдикатовцев во всём коде
описания пути конфиг ваще всё

бэйцы зачем-то в половине всех мест поменяли слово синдикатовцы на оперативников
но мы то хотим нормальный синдикат в конце концов то ёпта

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-14 15:16 UTC, Epicus7 commented
Какие-то изменения ради изменений, да еще и противоречащие текущему беку. В текущем беке нет единого синдиката, который отправляет элитные отряды синдикатовцев.

2020-10-14 15:17 UTC, TapKo4eB commented
у нас текущего бека вообще нет

2020-10-14 15:18 UTC, Epicus7 commented
Да ты что?
https://wiki.ss13.ru/index.php?title=Chaotic_Onyx_Backstory

2020-10-18 19:04 UTC, TobyThorne commented on code/__defines/machinery.dm
> +#define NETWORK_SYNDICATE           "MercurialNet"
Какой MercurialNet, где SyndieNet

2020-10-19 09:11 UTC, TapKo4eB commented on code/__defines/machinery.dm
> +#define NETWORK_SYNDICATE           "MercurialNet"
goog point
```suggestion
#define NETWORK_SYNDICATE           "SyndieNet"
```

2020-10-20 15:32 UTC, TobyThorne submitted a review, later dismissed
нравица

2020-11-12 14:32 UTC, kreeperHLC commented on code/datums/uplink/grenades.dm
>  	path = /obj/item/weapon/storage/box/supermatters
Попался! Нет пустой строки в конце файла

2020-11-12 14:34 UTC, kreeperHLC commented on code/modules/economy/Events_Mundane.dm
> +	"Woodchuck stops counting how many times he�s chucked 'Never again'.",\
Юникоду плохо

2020-11-12 14:35 UTC, kreeperHLC commented on code/modules/economy/Events_Mundane.dm
> +	"Clone accused of posing for other clones�s school photo.",\
И тут

2020-11-12 14:35 UTC, kreeperHLC commented on code/modules/economy/Events_Mundane.dm
> +	"Clone accused of stealing other clones�s employee of the month award.",\
И тут

2020-11-12 14:35 UTC, kreeperHLC commented on code/modules/modular_computers/file_system/programs/antagonist/hacked_camera.dm
>  	return networks
Новая строка

2020-11-12 14:36 UTC, kreeperHLC commented on maps/exodus/exodus_shuttles.dm
> +// syndi
Большую букву потерял

2020-11-12 14:37 UTC, kreeperHLC requested changes
Доделывай короче

2020-11-24 16:17 UTC, TapKo4eB commented on code/datums/uplink/grenades.dm
>  	path = /obj/item/weapon/storage/box/supermatters
fuck

2020-11-24 16:17 UTC, TapKo4eB commented on code/modules/economy/Events_Mundane.dm
> +	"Woodchuck stops counting how many times he�s chucked 'Never again'.",\
fuck

2020-11-24 16:17 UTC, TapKo4eB commented on code/modules/economy/Events_Mundane.dm
> +	"Clone accused of posing for other clones�s school photo.",\
fuck

2020-11-24 16:17 UTC, TapKo4eB commented on code/modules/economy/Events_Mundane.dm
> +	"Clone accused of stealing other clones�s employee of the month award.",\
fuck

2020-11-24 16:17 UTC, TapKo4eB commented on code/modules/modular_computers/file_system/programs/antagonist/hacked_camera.dm
>  	return networks
fuck

2020-11-24 16:17 UTC, TapKo4eB commented on maps/exodus/exodus_shuttles.dm
> +// syndi
fuck

2020-11-24 17:11 UTC, 4310V343k commented
fuck

2020-11-24 17:30 UTC, TobyThorne commented on code/modules/clothing/spacesuits/void/syndi.dm
>  	. = ..()
fuck

2020-11-25 14:35 UTC, kreeperHLC submitted a review, later dismissed

2020-12-06 17:31 UTC, TobyThorne commented on code/modules/clothing/spacesuits/void/syndi.dm
>  	. = ..()
хз в чем тут фак был я уже не помню похуй

2020-12-06 17:34 UTC, TobyThorne commented on code/__defines/gamemode.dm
> +#define MODE_SYNDICATE "syndicate"
чёт есть предположение, что должно быть всё таки MODE_NUKE, ибо иначе кринж получается:
![image](https://user-images.githubusercontent.com/45202681/101287638-a2b55f80-381b-11eb-8d1b-4251fb8883bb.png)

2020-12-06 18:39 UTC, TapKo4eB commented on code/__defines/gamemode.dm
> +#define MODE_SYNDICATE "syndicate"
и в правду

2020-12-16 06:03 UTC, TobyThorne approved these changes
ну чё народ погнали нахуй

2020-12-16 10:54 UTC, kreeperHLC approved these changes

2020-12-16 14:21 UTC, Doster-d approved these changes

2020-12-16 17:08 UTC, merged