feat(blob_disable) add admin button to disable blob
ChaoticOnyx/OnyxBay pull request #3504
Opened 2020-10-14 18:35 UTC by Doster-d

Добавил значение в конфиг, что бы блоб, если прокнет его ивент - не появился.
Добавил кнопку, что бы можно было изменить значения на ~~УБИТЬ МС~~ включить блоба.

Тут будет иссуй Булата на эту кнопку.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-17 21:59 UTC, jammer312 requested changes
При отключении ивонта убирай блоба из списка ивонтов, чтобы он не мешал остальным ивонтам.
При изначальном создании списка ивонтов не добавляй туда блоба, если он отключен.

2020-10-17 21:59 UTC, jammer312 commented on code/modules/events/blob_outbreak.dm
> +		kill()
Хз про остальное, но вот это мне точно не нравится.
Отключенный ивонт не должен отбирать вероятность срабатывания у других ивонтов.

2020-10-17 23:59 UTC, Doster-d commented on code/modules/events/blob_outbreak.dm
> +		kill()
Чего? Отключенный ивент (блоб) убивает себя, если его контроллер вызывает.

2020-10-18 00:00 UTC, Doster-d commented
> При отключении ивонта убирай блоба из списка ивонтов, чтобы он не мешал остальным ивонтам.

Это точно нужно?

> При изначальном создании списка ивонтов не добавляй туда блоба, если он отключен.

Не вижу способа добавить его после включения, при реализации первого варианта второй не будет иметь смысла.

2020-10-18 00:06 UTC, 4310V343k commented
> Я запускал сервер со своими изменениями локально и все протестировал.

Если ты выключаешь блоба, то вообще убери его из списка ивентов, а при нажатии на кнопку добавляй/удаляй заново

При том, что сейчас ты пытаешься сделать, ивент блоба с каким-то шансом НЕ будет запускаться(ура, правильно), но сможет впустую занять слот мейджор ивента, тем самым запоров какой-то другой ивент, который мог произойти вместо него

2020-10-18 00:10 UTC, 4310V343k requested changes

2020-10-18 00:10 UTC, 4310V343k commented on code/controllers/configuration.dm
> +					config.blob_disable = 1
```suggestion
					config.blob_disable = TRUE
```

2020-10-18 00:10 UTC, 4310V343k commented on code/modules/events/blob_outbreak.dm
> +		kill()
Если ты выключаешь блоба, то вообще убери его из списка ивентов, а при нажатии на кнопку добавляй/удаляй заново

При том, что сейчас ты пытаешься сделать, ивент блоба с каким-то шансом НЕ будет запускаться(ура, правильно), но сможет впустую занять слот мейджор ивента, тем самым запоров какой-то другой ивент, который мог произойти вместо него

2020-10-18 00:10 UTC, Doster-d commented
> Если ты выключаешь блоба, то вообще убери его из списка ивентов, а при нажатии на кнопку добавляй/удаляй заново

Ты же понимаешь как работает эвент контроллер, да?

2020-10-18 00:19 UTC, 4310V343k commented
Да. И я знаю, что можно прилично сделать то же самое, что делается через ивент менеджер, только через одну кнопку
Посмотри `code\controllers\subsystems\event.dm @ 308`

2020-10-18 00:20 UTC, Doster-d commented on code/controllers/configuration.dm
> +					config.blob_disable = 1
Я делаю по аналогии с другими значениям, считаю данное изменение излишним.

2020-10-18 00:21 UTC, 4310V343k commented on code/controllers/configuration.dm
> +					config.blob_disable = 1
Если это где-то сделано плохо - не значит, что надо продолжать делать плохо.

2020-10-18 00:28 UTC, Doster-d commented on code/controllers/configuration.dm
> +					config.blob_disable = 1
Справедливо, но я ленивый человек, поэтому буду защищать свою позицию до смерти (следующего коммита).

2020-10-18 09:22 UTC, Shabat-Sholom commented
Вопрос один. Зачем кнопка вторая кнопка на выключение блоба?

2020-10-18 09:34 UTC, Doster-d commented
> Вопрос один. Зачем кнопка вторая кнопка на выключение блоба?

Что?

2020-10-18 12:08 UTC, Doster-d commented
Ну нахуй это дерьмо, пусть кто-то у кого прямые руки это сделает.

2020-10-18 12:08 UTC, closed without merging