Починил всё, что связано со смертью спайдерботов
ChaoticOnyx/OnyxBay pull request #3513
Opened 2020-10-14 22:39 UTC by 4310V343k

Боты могут умереть
Боты - боты, в них микросхемы, а не мясо
Починил рантайм, который циклично пытался вытащить из бота вещь, которой в нём нет. (Это и была причина бессмертия)

Fixes #2165

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-16 14:48 UTC, TapKo4eB submitted a review, later dismissed
храни душу беедауна

2020-10-17 21:52 UTC, PlinHost commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Эта строка точно не нужна? Я бы оставил или переместил в `Destroy`.

2020-10-17 23:03 UTC, 4310V343k commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Не знаю, зачем ты выделил две строки и сказал про одну строку, но да, вторая строка не нужна из-за qdel'а

2020-10-17 23:05 UTC, PlinHost commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Гитхаб показывает строки выше для контекста.
`qdel` не зануляет `held_item`. Чтобы он это делал, нужно перенести строку в `Destroy`, о чем я писал выше.

2020-10-17 23:08 UTC, 4310V343k commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Зачем его вообще занулять?

2020-10-17 23:10 UTC, PlinHost commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Чтобы не осталась висеть ссылка, если вдруг бот не удалится. Особенности сборки мусора в билде с некачественным кодом.

2020-10-17 23:16 UTC, 4310V343k commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Почему у него два New()   ..?

2020-10-17 23:20 UTC, PlinHost commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	held_item = null
Так исторически сложилось. Было бы неплохо объединить в один и вынести в `Initialize` что можно. Вроде можно вообще всё вынести, но это не точно.

2020-10-18 00:26 UTC, 4310V343k commented
Фикс бага превратился в геймдизайн фичу, требую ревьюверов

2020-10-27 01:36 UTC, Epicus7 requested changes

2020-10-27 01:36 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +	return INITIALIZE_HINT_NORMAL
```suggestion
/mob/living/simple_animal/spiderbot/Initialize()
	. = ..()

	add_language(LANGUAGE_GALCOM)
	default_language = all_languages[LANGUAGE_GALCOM]

	verbs |= /mob/living/proc/ventcrawl
	verbs |= /mob/living/proc/hide
```

Если ты явно не хочешь переопределить возвращаемое значение, то лучше вернуть то, что тебе вернул родитель `. = ..()`.

2020-10-27 01:36 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> -	camera.replace_networks(list("SS13"))
А куда все это добро подевалось?

2020-11-15 21:44 UTC, kreeperHLC approved these changes

2020-11-15 21:45 UTC, kreeperHLC requested changes
Ай, не заметил что реквесты Эпикуса до сих пор не сделали

2020-11-16 09:00 UTC, 4310V343k commented
Я пока не много умер, DNM

2020-12-02 05:48 UTC, 4310V343k commented
#3869

2020-12-02 09:24 UTC, TobyThorne commented
ПР доделывает многое помимо кривой смерти, исправленной в #3869. 
В идеале бы обновить.

2020-12-02 12:40 UTC, 4310V343k commented
Всмысле? Что сделат-то нада

2020-12-06 22:20 UTC, kreeperHLC commented
> Всмысле? Что сделат-то нада

>Боты - боты, в них микросхемы, а не мясо
Небольшой рефактор
Теперь бот активирует гранату не только при дропе, но и при уничтожении

Это скорее всего

2020-12-14 09:46 UTC, TobyThorne commented
Ладно, вряд ли автор собирается доделывать. В случае чего - всегда можно переоткрыть.

2020-12-14 09:46 UTC, closed without merging