Батарея, голова в принтере. Исправления бага с полуорганиками-полусинтами.
ChaoticOnyx/OnyxBay pull request #3515
Opened 2020-10-15 02:37 UTC by Doster-d

Добавил батарею и голову в принтер органов робототехников, написал код для корректной печати головы в принтере.
Вероятно исправил баг с органическими частями тела и органами, теперь части тела роботизируются правильно (вместо 1 - "Unbranded")

close #545 , close #3401 , close #3311

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-20 17:37 UTC, TobyThorne commented on code/game/machinery/bioprinter.dm
> +			externalOrgan.robotize("Hephaestus Industries", just_printed = TRUE)
Воткни всем Unbranded (а лучше - NanoTrasen), пожалуйста. Хер его знает, благодаря кому принтер решил, что должен печатать Гефесты, но это кринж.

2020-10-20 20:54 UTC, Doster-d commented on code/game/machinery/bioprinter.dm
> +			externalOrgan.robotize("Hephaestus Industries", just_printed = TRUE)
Там нет иконки, вроде, сейчас пришлю изображение...

2020-10-20 21:35 UTC, Doster-d commented on code/game/machinery/bioprinter.dm
> +			externalOrgan.robotize("Hephaestus Industries", just_printed = TRUE)
![image](https://user-images.githubusercontent.com/63081538/96646761-4f538480-1335-11eb-878a-163360aa4851.png)
![image](https://user-images.githubusercontent.com/63081538/96646774-54183880-1335-11eb-9022-06c690b491bd.png)
Вот так выглядят они, норм?

2020-10-20 21:49 UTC, Doster-d commented on code/game/machinery/bioprinter.dm
> +			externalOrgan.robotize("Hephaestus Industries", just_printed = TRUE)
Ну поставил.

2020-10-21 14:06 UTC, TobyThorne requested changes

2020-10-21 14:06 UTC, TobyThorne commented on code/game/machinery/bioprinter.dm
> +	products.Add(BP_CELL = list(/obj/item/organ/internal/cell, 25), BP_HEAD = list(/obj/item/organ/external/head, 65))
ОП, а в чём мем добавлять продукты в /New()?
есть же в самом начале спискота 
![image](https://user-images.githubusercontent.com/45202681/96731322-f3423c00-13d8-11eb-9ac0-e79c3b2811dc.png)

2020-10-21 14:11 UTC, PlinHost commented
Протез головы, как и сундука, не нужен. Вам дали ФБП.

2020-10-21 14:16 UTC, Doster-d commented on code/game/machinery/bioprinter.dm
> +	products.Add(BP_CELL = list(/obj/item/organ/internal/cell, 25), BP_HEAD = list(/obj/item/organ/external/head, 65))
Вы хотели бы иметь в принтере органическую голову и синтовскую органическую батарею?
Потому что этот список использует и биопринтер.

2020-10-21 14:17 UTC, Doster-d commented
> Протез головы, как и сундука, не нужен. Вам дали ФБП.

Сундука нету, тут есть батарейка, геймдиз говорит, что добыча из ФБП батареек и головы - баг, я этот баг исправляю.

2020-10-21 14:18 UTC, TobyThorne commented on code/game/machinery/bioprinter.dm
> +	products.Add(BP_CELL = list(/obj/item/organ/internal/cell, 25), BP_HEAD = list(/obj/item/organ/external/head, 65))
печать голов и органических батареек - звучит круто

2020-10-21 14:18 UTC, TobyThorne reviewed
короче норм же вроде че докопались

2020-10-21 14:19 UTC, TobyThorne approved these changes

2020-10-21 14:19 UTC, TapKo4eB commented
протез сундука не вижу но вот протез головы реальн не нужен

2020-10-21 14:20 UTC, Doster-d commented
> протез сундука не вижу но вот протез головы реальн не нужен

У нас тут ПР есть с выбрасыванием ММИ, уверены?

2020-10-21 14:21 UTC, kreeperHLC commented
Ну так научись разделять фиксы и фичи

2020-10-21 14:21 UTC, TobyThorne commented
> У нас тут ПР есть с выбрасыванием ММИ, уверены?

Больше нету.

2020-10-21 14:25 UTC, Doster-d commented
> > У нас тут ПР есть с выбрасыванием ММИ, уверены?
> 
> Больше нету.

Че Вы мою аутистическую душенку-синтобляди расстраиваете? :cat_cry:

2020-10-21 14:27 UTC, Doster-d commented
> протез сундука не вижу но вот протез головы реальн не нужен

Не нужен, так не нужен.

2020-10-27 11:52 UTC, Epicus7 requested changes
Ну описание тогда поменяй плиз, раз ты убрал половину ПРа.

Насчет протеза головы кажется я чот говорил, но уже забыл что и где. Возможно это стоит в дискордике обсудить, я не помню. В любом случае было бы неплохо ссылочку на предыдущее обсуждение прикладывать.

2020-10-28 05:47 UTC, Doster-d commented
> Ну описание тогда поменяй плиз, раз ты убрал половину ПРа.

Убрано.

> Насчет протеза головы кажется я чот говорил, но уже забыл что и где. Возможно это стоит в дискордике обсудить, я не помню. В любом случае было бы неплохо ссылочку на предыдущее обсуждение прикладывать.

https://github.com/ChaoticOnyx/OnyxBay/issues/3401 - голову не одобрили геймдизайнеры, батарея на данном этапе под вопросом.
https://github.com/ChaoticOnyx/OnyxBay/issues/3311 - геймдизайн одобрил создания батареи через принтер органов

2020-11-12 01:21 UTC, TobyThorne approved these changes

2020-11-12 14:41 UTC, kreeperHLC approved these changes

2020-11-12 15:11 UTC, TatarTheBuilder approved these changes

2020-11-12 18:24 UTC, Doster-d commented
Merge?

2020-11-12 18:34 UTC, kreeperHLC commented
Ждём хоть кого-то, кто может принять ПР

2020-11-13 00:51 UTC, TobyThorne commented
> Ждём хоть кого-то, кто может принять ПР

А точнее - Эпикуса, ибо он реквестнул ченжес.

2020-11-13 00:53 UTC, Doster-d commented
Так я сделал, что он хотел, поменял описание...

2020-11-17 08:52 UTC, Epicus7 approved these changes

2020-11-17 12:40 UTC, Doster-d commented
Merge request

2020-11-23 11:42 UTC, merged