Htmlparse
ChaoticOnyx/OnyxBay pull request #3519
Opened 2020-10-15 13:18 UTC by 4310V343k

Теперь при создании листочка можно дать аргумент notpencode = 1, что бы вместе с пенкодами (`[br]`) обрабатывались ещё и HTML-коды (`<br>`). 
Немного изменён код печати крюрекордса для красоты, в код его печати и печати бодисканера добавлен аргумент notpencode = 1.

Fixes #3495 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-15 15:35 UTC, MrPersival commented
Вроде ещё карго консоль не починили.

2020-10-15 16:51 UTC, 4310V343k commented
> Вроде ещё карго консоль не починили.

![image](https://user-images.githubusercontent.com/56449763/96161318-c9dc6880-0f1f-11eb-881b-9b639990e9af.png)

2020-10-17 21:58 UTC, PlinHost commented on code/game/gamemodes/events/holidays/Christmas.dm
> +		"Why doesn�t Santa have any children?\n\n<i>Because he only comes down the chimney.</i>"),
Кривой редактор потерял юникод.

2020-10-17 23:03 UTC, 4310V343k commented on code/game/gamemodes/events/holidays/Christmas.dm
> +		"Why doesn�t Santa have any children?\n\n<i>Because he only comes down the chimney.</i>"),
блять

2020-10-27 01:39 UTC, Epicus7 commented
> Немного изменён код печати крюрекордса для красоты, в код его печати и печати бодисканера добавлен аргумент notpencode = 1.

Так тут же конфликт будет с https://github.com/ChaoticOnyx/OnyxBay/pull/3413 скорее всего.

2020-10-27 10:56 UTC, jammer312 requested changes
Лажа и в том, что аргумент не того типа, и в том, что создание бумажки происходит до составления ее содержимого.

2020-10-27 10:56 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +			slip = new /obj/item/weapon/paper/manifest(A, info, notpencode = TRUE)
Тут лажа

2020-10-27 10:56 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
Зачем выпиливать тег списка?

2020-10-27 11:31 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			slip = new /obj/item/weapon/paper/manifest(A, info, notpencode = TRUE)
Да

2020-10-27 11:40 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
А зачем он там нужен?
![image](https://user-images.githubusercontent.com/56449763/97296914-5f51f380-1862-11eb-97ea-1b47264ffa20.png)

2020-10-27 11:48 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
Затем, что он задает границы списка?
Вот этого 
![image](https://user-images.githubusercontent.com/3525275/97297706-6e857100-1863-11eb-88be-f6dfb3828a70.png)

2020-10-27 11:48 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
Скрин выше без <ul>, если что. Не вижу, где он пригождается

2020-10-27 11:49 UTC, jammer312 commented
Помимо всего прочего, по-моему название переменной неудачное. Я бы назвал `html` или `raw_html` или как-то в этом роде.

2020-10-27 11:50 UTC, 4310V343k commented
> Помимо всего прочего, по-моему название переменной неудачное. Я бы назвал `html` или `raw_html` или как-то в этом роде.

as you say

2020-10-27 11:53 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
Если не ошибаюсь, по стандарту тег li вне ul или ol не имеет смысла.
То, что у тебя работает кривая структура, не значит, что она будет работать у всех и всегда.

2020-10-27 11:55 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
![image](https://user-images.githubusercontent.com/56449763/97298464-7b569480-1864-11eb-835f-7db4553a1638.png)

2020-10-27 12:03 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
![image](https://user-images.githubusercontent.com/3525275/97299083-75ad7e80-1865-11eb-9392-ea416a800c70.png)
https://validator.w3.org/#validate_by_input

2020-10-27 12:04 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
ok

2020-10-27 12:05 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			info +="CONTENTS:<br>"
В таком случае добавил закрывающий тег ниже после списка

2020-11-02 22:41 UTC, jammer312 submitted a review, later dismissed
Три скользких места, в остальном вроде норм.
Тестировать я это, конечно же, не буду.

2020-11-02 22:41 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +//			info +="[shoppinglist.len] PACKAGES IN THIS SHIPMENT<br>"
Это точно надо выпиливать?

2020-11-02 22:41 UTC, jammer312 commented on code/modules/modular_computers/file_system/crew_record.dm
> +			dat += "<tr><td><b>[F.name]</b></td>"
По-моему оно тут лишнее. Т.е. закрывающий тег как бы нужен, но его можно опустить, и тут повально они опускаются. И тут внезапно ты решил один из тегов таки закрыть.
Но да ладно

2020-11-02 22:41 UTC, jammer312 commented on code/controllers/subsystems/supply.dm
> +			var/info = null
Я бы инициализировал это "", а не null'ом
Полагаю, ты это тестил и оно работает, но таки прибавление строки к null'у - операция не столь очевидная.

2020-11-03 10:31 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +//			info +="[shoppinglist.len] PACKAGES IN THIS SHIPMENT<br>"
Оно точно работает как надо? Если да, то скажите почему. Я же говорю, что нет, и чинить в ЭТОМ ПРе не собираюсь

2020-11-03 10:31 UTC, 4310V343k commented on code/modules/modular_computers/file_system/crew_record.dm
> +			dat += "<tr><td><b>[F.name]</b></td>"
Тестил специально, без именно этого тега почему-то не работает, иначе нормально

2020-11-03 10:31 UTC, 4310V343k commented on code/controllers/subsystems/supply.dm
> +			var/info = null
```suggestion
			var/info = ""
```

2020-11-12 14:54 UTC, kreeperHLC approved these changes, later dismissed

2020-11-18 06:56 UTC, jammer312 submitted a review, later dismissed

2020-11-23 11:43 UTC, Epicus7 submitted a review, later dismissed

2020-11-23 11:44 UTC, Epicus7 commented
@4310V343k, конфликты вылезли

2020-11-25 11:49 UTC, Epicus7 approved these changes

2020-11-28 11:24 UTC, jammer312 approved these changes

2020-11-29 22:56 UTC, Doster-d commented
Боюсь, у нас тут два аппрува.

2020-12-03 20:14 UTC, TobyThorne commented
Ну, в принципе, Эпикус и Жаммер чекнули. Ничего сломаться не должно, наверное.

2020-12-03 20:16 UTC, merged