fix(map):waste disposal now not blocked by shuttle
ChaoticOnyx/OnyxBay pull request #3525
Opened 2020-10-16 07:19 UTC by 4310V343k

= title
= all instance variables are now in alphabetical order

fixes #1868

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-16 07:27 UTC, TatarTheBuilder commented
ай
![Screenshot_7](https://user-images.githubusercontent.com/51989098/96225487-d0a7c180-0f99-11eb-8e03-c683d963bb78.png)

Лучше уж сразу весь мусоросброс на тайл сдвинуть. И я не вижу трубы к выходу сброса, она там есть?

2020-10-16 08:25 UTC, 4310V343k commented
Как минимум я помню, что ставил её туда.

2020-10-24 15:41 UTC, TobyThorne commented
конфликт подкрался

2020-10-24 15:52 UTC, 4310V343k commented
При чём подкрался незаметно, сучка

2020-10-24 16:03 UTC, 4310V343k commented
На этом мои полномочия всё

2020-10-27 12:22 UTC, Epicus7 requested changes
Что здесь вообще происходит? В ПРе гораздо больше кода, чем написано в описании. Не порядок.

Алсо конфликты вылезли.

2020-10-27 12:39 UTC, 4310V343k commented
> Что здесь вообще происходит? В ПРе гораздо больше кода, чем написано в описании. Не порядок.

Писал в теле ПРа

> Алсо конфликты вылезли.

Я как-то очень криво вмержил dev сюда, закрою от греха подальше

2020-10-27 12:39 UTC, closed without merging