Починка пожирания
ChaoticOnyx/OnyxBay pull request #3563
Opened 2020-10-20 21:36 UTC by kemperhun

Оказалось, что содержимое желудков космонавтов находится на нулевом Z-уровне, а симплмобы не умирают и вообще не обрабатываются, пока на их Z-уровне нет игрока, оттого и вечное существование без переваривания. Кроме того, пробить желудок изнутри можно было только с предметом в руках. Это починено.
Мобов через маску кушать теперь нельзя, мелки тоже. Вилку я съесть не смог.

В процессе тестирования обнаружилось, что съедение не мешает мышам кусать обжору за ноги, но я без понятия, как это фиксить. Впрочем, мыши-ИИ не кусаются, а игрок успеет немногое до переваривания, так что, думаю, не страшно.

close #2176

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-21 17:43 UTC, Judge1987 commented
> Оказалось, что содержимое желудков космонавтов находится на нулевом Z-уровне

Прошу прощения. Это как, блять, работает?

2020-10-21 17:49 UTC, MACTEP-ABATAP commented
Чудобилд, но уже лучше чем было.

2020-10-22 19:58 UTC, sweden-moose commented
С мелками фича же. Клован так может обедать не теряя своего образа.

2020-10-30 18:59 UTC, TobyThorne requested changes

2020-10-30 18:59 UTC, TobyThorne commented on code/modules/mob/living/carbon/carbon.dm
> +				src.take_organ_damage(d)
зачем тут src

2020-10-30 18:59 UTC, TobyThorne commented on code/modules/mob/living/carbon/carbon.dm
> +			if(prob(src.getBruteLoss() - 50))
и тут зачем src

2020-10-30 18:59 UTC, TobyThorne commented on code/modules/mob/living/carbon/carbon.dm
> +				src.gib()
и тут

2020-10-30 18:59 UTC, TobyThorne commented on code/modules/mob/living/carbon/carbon.dm
> +			var/d = (I && I.force) ? rand(round(I.force / 4), I.force) : rand(1, 6) //give a chance to creatures without hands
d - какое-то хуёвое название для переменной, почему бы не сделать какой-нибудь damage или хоть dmg

2020-10-31 05:07 UTC, kemperhun commented on code/modules/mob/living/carbon/carbon.dm
> +				src.take_organ_damage(d)
Там по всему коду src. Но раз тут не надо, то ладно

2020-10-31 05:07 UTC, kemperhun commented on code/modules/mob/living/carbon/carbon.dm
> +			if(prob(src.getBruteLoss() - 50))
и тут

2020-10-31 05:07 UTC, kemperhun commented on code/modules/mob/living/carbon/carbon.dm
> +				src.gib()
и тут

2020-10-31 05:08 UTC, kemperhun commented on code/modules/mob/living/carbon/carbon.dm
> +			var/d = (I && I.force) ? rand(round(I.force / 4), I.force) : rand(1, 6) //give a chance to creatures without hands
Поменяно.

2020-10-31 10:02 UTC, TobyThorne approved these changes

2020-10-31 10:03 UTC, TobyThorne commented
Ебучий полярный гитхаб, не могу свой же ченжреквест дисмисснуть. Ааааа.

2020-11-10 12:02 UTC, TobyThorne commented
Не знаю, зачем тут геймдиз. Бесконечно переваривающиеся мышки, дающие бесконечные нитро менты - это очевидный баг. Как и поедание чего-либо через маски.

2020-11-12 14:46 UTC, kreeperHLC approved these changes

2020-11-13 18:21 UTC, TatarTheBuilder approved these changes

2020-11-14 08:01 UTC, merged