Больше вкусняшек
ChaoticOnyx/OnyxBay pull request #3578
Opened 2020-10-22 23:33 UTC by TobyThorne

- Добавлен подтип /obj/item/weapon/reagent_containers/food/snacks - "packaged"; эти снэки требуется открывать перед употреблением, и они меняют спрайт после двух укусов;
- Добавлены новые _packaged_-снэки - Tweakers bar, Sweetroid bar, SugarMatter bar, Jellaw's Jellybaton, protein nutrition bar;
- Следующие снэки теперь _packaged_ - chips, sosjerky, 4no Raisins, Cheesie Honkers, Hema-2-Gen;
- Удалены protein bar (заменён на protein nutrition bar везде, где использовался), candy (заменён на 4 новых вида конфет), Donor Candy (не использовались нигде);

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-22 23:41 UTC, ArmolitskiyCarpoeb commented
зачем

2020-10-22 23:43 UTC, TobyThorne commented
> зачем

![image](https://user-images.githubusercontent.com/45202681/96940858-9aff5d00-14f2-11eb-812e-46a36f652eb9.png)

2020-11-01 23:37 UTC, TobyThorne commented
Зарезолвил конфликты.

2020-11-12 06:59 UTC, TobyThorne commented
- Bread tubes, SkrellSnax и Syndi-Cakes теперь packaged;

2020-11-12 14:24 UTC, kreeperHLC submitted a review, later dismissed

2020-11-15 21:16 UTC, kreeperHLC requested changes

2020-11-15 21:16 UTC, kreeperHLC commented on code/game/machinery/vending.dm
> +					/obj/item/weapon/reagent_containers/food/snacks/packaged/chips =6,
```suggestion
					/obj/item/weapon/reagent_containers/food/snacks/packaged/chips = 6,
```

2020-11-15 21:16 UTC, kreeperHLC commented on code/game/machinery/vending.dm
> +					/obj/item/weapon/reagent_containers/food/snacks/packaged/chips =6,
```suggestion
					/obj/item/weapon/reagent_containers/food/snacks/packaged/chips = 6,
```

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/tweakers/New()
/obj/item/weapon/reagent_containers/food/snacks/packaged/tweakers/Initialize()

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/sweetroid/New()
/obj/item/weapon/reagent_containers/food/snacks/packaged/sweetroid/Initialize()

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/sugarmatter/New()
/obj/item/weapon/reagent_containers/food/snacks/packaged/sugarmatter/Initialize()

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/jellaws/New()
Ну ты понял

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/nutribar/New()
Да, и тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/chips/New()
И тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/sosjerky/New()
И тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/no_raisin/New()
И тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/cheesiehonkers/New()
И тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/hematogen/New()
И тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/tastybread/New()
И тут

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/skrellsnacks/New()
Когда же это закончится...

2020-11-15 21:16 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/syndicake/New()
Ну, видно сейчас

2020-11-16 02:08 UTC, TobyThorne commented on code/modules/reagents/reagent_containers/food/snacks/packaged.dm
> +/obj/item/weapon/reagent_containers/food/snacks/packaged/syndicake/New()
Как-нибудь потом, вместе со всей остальной едой.

2020-11-21 11:01 UTC, TapKo4eB approved these changes
зарежу если в следующей еде не поменяешь на инишиалайзы
и ещё звуки прикрути открытия еды потом

2020-11-21 11:04 UTC, TatarTheBuilder approved these changes

2020-11-21 11:16 UTC, merged