Чиним ревайв генокрада, версия N
ChaoticOnyx/OnyxBay pull request #3587
Opened 2020-10-24 01:06 UTC by Doster-d

В результате тестирования багов генокрада, был обнаружен баг в моем смерженом ПРе.
Я удалил нейронить из списка органов, которые не надо удалять, в скором времени, надеюсь, смогу побороть его.
Добавил оповещение о начале ревайва генокрада.
Добавил специальный прок для обработки всех **специальных** органов, туда записал биоструктуру, теперь она работает корректно.

~~Надеюсь багов не будет... Пожалуйста?~~

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-27 02:22 UTC, Epicus7 requested changes

2020-10-27 02:22 UTC, Epicus7 commented on code/modules/mob/living/carbon/human/human.dm
> +
Это плохой код, потому что ты в код человека тащишь логику биоструктуры. Человек ничего не должен знать о биоструктурах - это отдельная часть билда.

Гораздо лучше было бы добавить функцию, например, `/obj/item/organ/proc/after_create_organs()`, которая ничего не будет делать у обычных органов, а для биоструктуры будет делать то, что ты собственно здесь написал. Соответственно её надо будет вызвать в цикле для всех органов в конце create_organ.

2020-10-27 06:59 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human.dm
> +
Да, так действительно лучше будет. Исправил.

2020-10-27 12:54 UTC, Epicus7 requested changes

2020-10-27 12:54 UTC, Epicus7 commented on code/modules/organs/organ.dm
> +	return TRUE
```suggestion
/obj/item/organ/proc/after_organ_creation()
	return
```

2020-10-27 12:54 UTC, Epicus7 commented on code/modules/organs/internal/_internal.dm
> +	var/foreign = FALSE 			  // if TRUE, /datum/species/create_organs() won't delete it. Also see proc/foreign_organs_handler()
```suggestion
	var/foreign = FALSE 			  // foreign organs shouldn't be removed or recreated on revive
```

2020-10-27 13:03 UTC, Doster-d commented on code/modules/organs/organ.dm
> +	return TRUE
А смысл?

2020-10-27 13:35 UTC, Epicus7 commented on code/modules/organs/organ.dm
> +	return TRUE
А какой смысл возвращать TRUE? Тут наоборот нужны причины чтобы лишний код писать.

2020-10-27 13:36 UTC, Epicus7 commented on code/modules/organs/organ.dm
> +	return TRUE
Я вижу TRUE и ожидаю, что он где-то будет использоваться. Иду искать.. и разочаровываюсь, ибо он не используется, а я зря время потратил. И так будет делать каждый кодер.

2020-10-27 13:37 UTC, Epicus7 commented on code/modules/organs/organ.dm
> +	return TRUE
Да и чисто логически, твой прок не представляет собой вопроса.. Ну то есть во ты читаешь название "after_organ_creation" и что по-твоему должен подразумевать возвращаемый TRUE/FALSE?

Я вернул TRUE - что это значит? А если FALSE? Какая разница?

2020-10-27 13:38 UTC, Epicus7 submitted a review, later dismissed

2020-10-27 13:43 UTC, Doster-d commented on code/modules/organs/organ.dm
> +	return TRUE
Успех/не успех операции по действиям в проке? Я думал, что будущие программисты увидят, что этот прок что-то возвращает, захотят завязать на этом логику и т.д.
Ну не нужно так не нужно, логику я понял.

2020-11-04 19:07 UTC, jammer312 approved these changes

2020-11-12 14:21 UTC, kreeperHLC approved these changes

2020-11-24 08:25 UTC, Judge1987 commented
> Надеюсь багов не будет... Пожалуйста?

Нет.

2020-11-24 08:25 UTC, Epicus7 approved these changes

2020-11-24 08:26 UTC, merged