fixed admin fax duplication
ChaoticOnyx/OnyxBay pull request #3592
Opened 2020-10-24 20:02 UTC by Destrolaric

Я пытался разобраться с тем, почему админ факс дублирует вводимый текст, ответом оказалось то, что он каким-то образом вызывает generateinfolinks таким видом, что текст и endtag прилетает два раза. Вот быстрофикс

`fix #3583`

- [* ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ *] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ *] Я запускал сервер со своими изменениями локально и все протестировал.
- [*] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-24 20:46 UTC, MorJams commented
я конечно не эксперт но

> generateinfolinks таким видом, что текст и endtag прилетает два раза.

так может этот прок фиксить надо? если это прок, конечно....

Просто может оказаться что твой фикс это костыль, а та хуйня как была сломанной так и будет, и сломает билд через 1001 лет

2020-10-24 20:51 UTC, jammer312 requested changes
Решение плохое, ибо:
- Не исправлена причина возникновения проблемы
- Теряется смысл переменной `appendable` (в данном случае ее значение выставляется уже после инициализации, хотя использоваться она должна только при инициализации; назначение ее - разрешать/запрещать дописывание в конец бумаги, при этом из-за некорректного использования получается, что дописывать в конец как бы нельзя, но на деле можно)

Tldr; в ПРе костыль, мержить не советую.
Верным (хз, что у автора ПРа не получилось в его реализации, у меня оно корректно работает; верно оно хотя бы идейно) решением является выпил вызова `generateinfolinks` из `/obj/item/weapon/paper/admin/proc/adminbrowse()`

2020-10-24 20:54 UTC, Destrolaric commented
Отправил новый фикс, причиной проблемы оказался лишний вызов функции generateinfolinks

2020-10-24 20:55 UTC, jammer312 approved these changes

2020-10-27 02:58 UTC, Epicus7 approved these changes

2020-10-27 02:59 UTC, merged