Кобура с пушкой. Исправляем
ChaoticOnyx/OnyxBay pull request #3596
Opened 2020-10-25 02:31 UTC by Doster-d

Изменил прок получения строки одежды для экзамайна, теперь можно отключить отображение аксессуаров.
Добавил флаг для отключения возможности просмотра аксессуаров на костюме к "большим костюмом".

close 1197

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-25 20:08 UTC, 4310V343k commented
не `close 1197`. а `close #1197`

2020-10-25 20:09 UTC, Doster-d commented
> не `close 1197`. а `close #1197`

Да, я знаю, я тогда пьян был

2020-10-25 20:11 UTC, 4310V343k commented on code/modules/mob/living/carbon/human/examine.dm
> +	var/skipskipjumpsuitaccessories = FALSE
Боюсь спросить, почему `skipskip`?

2020-10-25 21:10 UTC, Doster-d commented on code/modules/mob/living/carbon/human/examine.dm
> +	var/skipskipjumpsuitaccessories = FALSE
А это мешает? Ну ctrl+c/ctrl+v поработал тут...

2020-10-27 14:00 UTC, Doster-d commented on code/modules/mob/living/carbon/human/examine.dm
> +	var/skipskipjumpsuitaccessories = FALSE
Ну исправил

2020-11-03 12:26 UTC, TapKo4eB reviewed
Ревью по маркапу, пр не тестил.

2020-11-03 12:26 UTC, TapKo4eB commented on code/__defines/items_clothing.dm
> +#define HIDEJUMPSUITACCESSORISS    0x12 // Used to hide accessoriss
1. Кто тебя учил в битфлаги, ты своим 0x12 занимаешь сразу два числа ухте иди убейсо.
Меняй на 0x20 и попользуйся http://bitwisecmd.com, может поймёшь.
2. Не знаешь как пишется, гугли. Accessori**es**.
```suggestion
#define HIDEJUMPSUITACCESSORIES 0x20
```

2020-11-03 12:37 UTC, Doster-d commented on code/__defines/items_clothing.dm
> +#define HIDEJUMPSUITACCESSORISS    0x12 // Used to hide accessoriss
Спасибо, я понял, я еблан.

2020-11-03 12:41 UTC, Doster-d commented on code/__defines/items_clothing.dm
> +#define HIDEJUMPSUITACCESSORISS    0x12 // Used to hide accessoriss
Пофиксил

2020-12-05 15:38 UTC, TobyThorne requested changes

2020-12-05 15:38 UTC, TobyThorne commented on code/__defines/items_clothing.dm
> +#define HIDEJUMPSUITACCESSORISS 0x20
ACCESSORIES

2020-12-05 15:40 UTC, Doster-d commented on code/__defines/items_clothing.dm
> +#define HIDEJUMPSUITACCESSORISS 0x20
```suggestion
#define HIDEJUMPSUITACCESSORIES 0x20
```

2020-12-05 15:42 UTC, TobyThorne commented on code/modules/clothing/suits/storage.dm
> +	flags_inv += HIDEJUMPSUITACCESSORISS
accessories

2020-12-05 15:42 UTC, TobyThorne commented on code/modules/clothing/suits/storage.dm
> +		flags_inv += HIDEJUMPSUITACCESSORISS
aCcEsSoRiEs

2020-12-05 15:42 UTC, TobyThorne commented on code/modules/clothing/suits/storage.dm
> +		flags_inv -= HIDEJUMPSUITACCESSORISS
AcCeSsOrIeS

2020-12-05 15:43 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/examine.dm
> +		skipjumpsuitaccessories = wear_suit.flags_inv & HIDEJUMPSUITACCESSORISS
sǝᴉɹossǝɔɔɐ

2020-12-05 15:44 UTC, Doster-d reviewed
Я долбоеб

2020-12-05 15:44 UTC, Doster-d commented on code/modules/clothing/suits/storage.dm
> +	flags_inv += HIDEJUMPSUITACCESSORISS
```suggestion
	flags_inv += HIDEJUMPSUITACCESSORIES
```

2020-12-05 15:44 UTC, Doster-d commented on code/modules/clothing/suits/storage.dm
> +		flags_inv += HIDEJUMPSUITACCESSORISS
```suggestion
		flags_inv += HIDEJUMPSUITACCESSORIES
```

2020-12-05 15:44 UTC, Doster-d commented on code/modules/clothing/suits/storage.dm
> +		flags_inv -= HIDEJUMPSUITACCESSORISS
```suggestion
		flags_inv -= HIDEJUMPSUITACCESSORIES
```

2020-12-05 15:44 UTC, Doster-d commented on code/modules/mob/living/carbon/human/examine.dm
> +		skipjumpsuitaccessories = wear_suit.flags_inv & HIDEJUMPSUITACCESSORISS
```suggestion
		skipjumpsuitaccessories = wear_suit.flags_inv & HIDEJUMPSUITACCESSORIES
```

2020-12-05 15:49 UTC, TobyThorne commented on code/modules/clothing/suits/storage.dm
> +		flags_inv += HIDEJUMPSUITACCESSORIES
```suggestion
		flags_inv |= HIDEJUMPSUITACCESSORIES
```

2020-12-05 15:50 UTC, TobyThorne commented on code/modules/clothing/suits/storage.dm
> +		flags_inv -= HIDEJUMPSUITACCESSORIES
```suggestion
		flags_inv &= HIDEJUMPSUITACCESSORIES
```

2020-12-06 22:13 UTC, kreeperHLC commented
Мне кажется, или это не работает для скафандров?

2020-12-06 22:13 UTC, kreeperHLC commented
А, понял

2020-12-06 22:13 UTC, kreeperHLC approved these changes

2020-12-16 06:09 UTC, TobyThorne approved these changes
гейдизно заревертить всегда успеем

2021-01-10 01:28 UTC, TobyThorne requested changes

2021-01-10 01:28 UTC, TobyThorne commented on code/modules/clothing/suits/storage.dm
> +	flags_inv += HIDEJUMPSUITACCESSORIES
А зачем оно по дефолту включено, если большинство suit/storage изначально в открытом состоянии.

2021-01-10 01:33 UTC, Doster-d commented on code/modules/clothing/suits/storage.dm
> +	flags_inv += HIDEJUMPSUITACCESSORIES
Окц, сделаю по другому.

2021-01-10 16:24 UTC, TobyThorne commented
Да мог бы, в общем-то, просто по дефолту всё сделать открытым. Ну да ладно.

2021-01-25 06:49 UTC, TobyThorne approved these changes

2021-03-11 21:06 UTC, kreeperHLC approved these changes

2021-03-11 21:09 UTC, merged