Фикс абуза с лестницами
ChaoticOnyx/OnyxBay pull request #3598
Opened 2020-10-25 12:15 UTC by Destrolaric

Один из тех случаев, когда легаси оказался слегка лучше текущего решения. Вкратце полностью отсутствовала проверка на density тайла за перилами. В итоге это приводила к рофлянке. Переделал решение из легаси комментариев, адаптировал. 
fix #3573

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-25 20:07 UTC, 4310V343k requested changes

2020-10-25 20:07 UTC, 4310V343k commented on code/game/objects/structures/railing.dm
> +				to_chat(usr, "<span class='danger'>There's \a [T] in the way1.</span>")
Дебаг циферки1

2020-10-25 20:07 UTC, 4310V343k commented on code/game/objects/structures/railing.dm
> +					to_chat(usr, "<span class='danger'>There's [O] \a  in the way2.</span>")
Дебаг циферки2

2020-10-25 20:07 UTC, 4310V343k commented on code/game/objects/structures/railing.dm
> +				to_chat(usr, "<span class='danger'>There's [OT] \a in the way3.</span>")
Дебаг циферки3

2020-10-25 20:07 UTC, 4310V343k commented on code/game/objects/structures/railing.dm
> +					to_chat(usr, "<span class='danger'>There's \a [O] in the way4.</span>")
Дебаг циферки4

2020-10-25 20:35 UTC, Destrolaric commented on code/game/objects/structures/railing.dm
> +					to_chat(usr, "<span class='danger'>There's \a [O] in the way4.</span>")
Вроде бы я их убирал...

2020-10-25 20:46 UTC, Destrolaric commented
Отправил версию с удалёнными цифрами

2020-10-26 15:30 UTC, Epicus7 requested changes
Ну такие себе изменения. Кажется мы тут внесли больше багов, чем было.

Я предлагаю все-таки откатить обратно и просто добавить проверочку на содержимое тайла с другой стороны от перил. Полностью переписывать прок я бы не стал, ибо там другая логика есть, которую ты теряешь, например, логика проверки что ты не лезешь еще куда-то.

2020-10-26 15:30 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
> +
Давай снесем его. Старый код не поддерживается, теряет актуальность и перестает работать. Разбираться потом с этим никто не будет.

2020-10-26 15:30 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
> +		return 1
Копипаста лютая. В одном месте код поменяют, а в другом забудут. Не надо так писать, пожалуйста. Нужно как-то свести к единственной реализации в одном месте.

2020-10-26 15:30 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
>  /obj/structure/railing/can_climb(mob/living/user, post_climb_check=0)
post_climb_check раньше использовался, так как проверку вызывали дважды. У тебя остается логика что проверка вызывается дважды, но разницы в коде функции никакой нет.

На самом деле у тебя тут баг. Раньше были проверки на то, что ты УЖЕ куда-то лезешь. И соответственно если ты лезешь, то второй раз лезть еще куда-то ты не можешь. А у тебя получается можно лезть сразу на несколько перил одновременно.

2020-10-26 15:30 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
> +				to_chat(usr, "<span class='danger'>There's \a [T] in the way.</span>")
SPAN_DANGER надо использовать здесь вместо явных спанов.

https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B9%D1%82%D0%B5-%D0%BC%D0%B0%D0%BA%D1%80%D0%BE%D1%81%D1%8B-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0-span_notice-span_warning-span_danger-%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5

2020-10-26 15:46 UTC, Destrolaric commented on code/game/objects/structures/railing.dm
> +
откат не работает, я тестил этот код. Куча косячков

2020-10-26 17:11 UTC, Destrolaric commented on code/game/objects/structures/railing.dm
>  /obj/structure/railing/can_climb(mob/living/user, post_climb_check=0)
post_climb_check, видимо уже не имеет смысла в использовании, даже предыдущая версия кода не работала с ним

2020-10-26 17:50 UTC, Destrolaric commented
Скинул фикс на большинство просьб изменений. добавил дополнительную проверку

2020-10-27 01:54 UTC, Epicus7 requested changes
Так основные проблемы остались те же, ты ничего не исправил.

1. Копипаста 20 строк.
2. Возможность поставить рядом две периллы и начать лезть сразу на две.

2020-10-27 01:54 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
> +	atom_flags = ATOM_FLAG_CHECKS_BORDER | ATOM_FLAG_CLIMBABLE
Опять комментарий лишний.

Кстати что это и зачем тут?

2020-10-27 01:54 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
> +	var/turf/UT = get_turf(usr)
Это ты зря сделал, верни обратно.

2020-10-27 01:56 UTC, Epicus7 commented on code/game/objects/structures/railing.dm
>  /obj/structure/railing/can_climb(mob/living/user, post_climb_check=0)
Он нужен был, чтобы проверять не лезешь ли ты уже на какую-то другую периллу.

> На самом деле у тебя тут баг. Раньше были проверки на то, что ты УЖЕ куда-то лезешь. И соответственно если ты лезешь, то второй раз лезть еще куда-то ты не можешь. А у тебя получается можно лезть сразу на несколько перил одновременно.

2020-10-27 17:28 UTC, Destrolaric commented on code/game/objects/structures/railing.dm
> +	atom_flags = ATOM_FLAG_CHECKS_BORDER | ATOM_FLAG_CLIMBABLE
Оставил на всякий пожарный, там не по формату до этого написано было, не мог понять почему одна из функций не работала конкретно на перила. Оказалось, что автор кода решил atom_flags назвать  по своему, из-за этого функция его не видела

2020-10-27 17:32 UTC, Destrolaric commented on code/game/objects/structures/railing.dm
> +	var/turf/UT = get_turf(usr)
> Так основные проблемы остались те же, ты ничего не исправил.
> 
> 1. Копипаста 20 строк.
> 2. Возможность поставить рядом две периллы и начать лезть сразу на две.

Касательно двойного залезания, из-за нового подходу к тайлам, залазить на перила можно только с блока перил, или с блока, на который перила указывают. Я тестил залезания на несколько перил, залезание на стол во время этого, по моему там никаких отклонений в поведении

2020-10-27 17:33 UTC, Destrolaric commented
> Так основные проблемы остались те же, ты ничего не исправил.
> 
> 1. Копипаста 20 строк.
> 2. Возможность поставить рядом две периллы и начать лезть сразу на две.

Касательно двойного залезания, из-за нового подходу к тайлам, залазить на перила можно только с блока перил, или с блока, на который перила указывают. Я тестил залезания на несколько перил, залезание на стол во время этого, по моему там никаких отклонений в поведении

2020-10-27 19:37 UTC, Destrolaric commented
Я кажись слегка заруинил этот пулл, закрываю, чтобы снова открыть без коммитов от неудачного ребейза

2020-10-27 19:37 UTC, closed without merging