Пельмени
ChaoticOnyx/OnyxBay pull request #3599
Opened 2020-10-25 12:21 UTC by sweden-moose

Пельмени
resolves #3554

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-25 12:28 UTC, kemperhun commented
Пулл-реквест не закрывает иссуй в полной мере: эчпочмак не реализован. Пожалуйста, добавьте эчпочмак.

2020-10-25 12:36 UTC, Destrolaric commented
Считаю, нужно дополнить, есть крупные пельмени называются Манты, надо реализовать

2020-10-25 12:36 UTC, sweden-moose commented
Исправил описание :sunglasses:

2020-10-25 12:51 UTC, ArmolitskiyCarpoeb commented
мда, даже автора не указал

2020-10-25 12:55 UTC, sweden-moose commented
Указал

2020-10-25 20:04 UTC, 4310V343k requested changes

2020-10-25 20:04 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +obj/item/weapon/reagent_containers/food/snacks/pelmeny
```suggestion
/obj/item/weapon/reagent_containers/food/snacks/pelmeny
```

2020-10-25 20:04 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +obj/item/weapon/reagent_containers/food/snacks/boiledpelmeny
```suggestion
/obj/item/weapon/reagent_containers/food/snacks/boiledpelmeny
```

2020-10-25 20:04 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		bitesize = 2
Вынеси отдельно

2020-10-25 20:04 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		bitesize = 3
Вынеси отдельно

2020-10-25 20:04 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		qdel(W)
Один пельмень из целого куска теста? Напомню, что из него можно сделать три(3) тако

2020-10-25 20:07 UTC, sweden-moose commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		qdel(W)
Ну так на тако еще сыр нужон

2020-10-25 20:07 UTC, TobyThorne commented
"pelmeny" - это кринж какой-то
либо dumplings, либо pelmeni

2020-10-25 20:08 UTC, sweden-moose commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		qdel(W)
Да и уходит на него больше времени, ведь нужно жарить котлеты

2020-10-25 20:10 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		qdel(W)
Я про размер. Разве что из него делается пельмень 10х10 см, но тогда и мяса больше надо

2020-10-25 20:11 UTC, sweden-moose commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		qdel(W)
Но тесто же пластичное :thinking:

2020-10-25 20:13 UTC, sweden-moose commented
> "pelmeny" - это кринж какой-то
> либо dumplings, либо pelmeni

pelmeny.net
Шах и мат

2020-10-25 20:26 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		qdel(W)
убейте меня об стенку, там же 7 пельменей получается, а не один

2020-10-25 20:37 UTC, TatarTheBuilder commented
> "You make a pelmeny."

чет хуево как-то, действие завершенное, пельмени - множественное, имхо, лучше будет "You made some pelmeny."
хотя, как тут уже отметили, транслит это чет кринж лютый сам по себе, пельмени вполне себе переводятся

2020-10-25 20:39 UTC, sweden-moose commented
Это копипаста со спагетти. Там тоже "You make a spagetti"

2020-10-26 15:07 UTC, MrMagick2104 commented
> You made some pelmeny.

"You have made some..." ещё лучше было бы, я думаю.

2020-10-26 15:15 UTC, Epicus7 requested changes
Пельмени на английской вики:
https://en.wikipedia.org/wiki/Pelmeni

Пофикси плиз название. И "You have made some pelmeni".

2020-10-26 15:16 UTC, PlinHost commented
> "You have made some pelmeni".

Там настоящее время должно быть.

2020-10-26 15:20 UTC, Animesku commented
А have made это тоже настоящее

2020-10-26 15:21 UTC, MrMagick2104 commented
> Там настоящее время должно быть.

Так это и есть настоящее. Только перфектное.
А настоящее обычное так себе звучит - "Ты сделать пельмени", - хотя допустимо.

2020-10-26 15:21 UTC, PlinHost commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Raw meat and dough."
Такое себе описание, непонятно что мясо в тесте.

2020-10-26 15:21 UTC, PlinHost commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Hello from Neorussia!"
Не надо никакой неороссии, плс. Можно сибирь, наверное, у нас уже отсылка в ушанке.

2020-10-26 15:22 UTC, sweden-moose commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Hello from Neorussia!"
Neosiberia?

2020-10-26 15:24 UTC, PlinHost commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Hello from Neorussia!"
![кот](https://user-images.githubusercontent.com/8840325/97191940-70dec100-17b8-11eb-854d-241147cd614e.png)

2020-10-26 15:29 UTC, sweden-moose commented
Всё как просили

2020-10-27 01:58 UTC, Epicus7 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Hello from Neorussia!"
"We don't know what was Siberia, but these tasty pelmeni definitely arrived from there."

2020-10-27 02:01 UTC, Epicus7 requested changes

2020-10-27 02:01 UTC, Epicus7 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Hello from Siberia!"
Отсылки на Землю, которые намекают, что персонаж что-то о ней знает, наверное, неоч. Я там выше предложил смешное описание, можно что-то в этом духе написать, я думаю.

2020-10-27 11:15 UTC, sweden-moose commented
Ну теперь точно всё

2020-10-27 12:48 UTC, Epicus7 approved these changes

2020-10-30 19:22 UTC, TobyThorne approved these changes
Нутриментов можно было бы больше пихнуть, pelmeni же. Но хуй с ним, это на совести дизайнеров.

2020-11-01 23:15 UTC, merged