Дереликт, хуё-моё
ChaoticOnyx/OnyxBay pull request #3600
Opened 2020-10-25 14:18 UTC by TobyThorne

- Вернул Гитару в нормальный вид вместо говна из обычных стенок
![image](https://user-images.githubusercontent.com/45202681/97109719-00279e00-16ff-11eb-9b42-a449edcda972.png)
- Вернул точную копию старого дереликта (за вычетом мелочей, ибо у нас билд-инвалид)
![image](https://user-images.githubusercontent.com/45202681/97109745-2a795b80-16ff-11eb-88e2-bacf88d91205.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-25 14:31 UTC, MalinaGirl commented
апрувов не будет пока не появится карта капитана на мостике

2020-10-25 16:27 UTC, Destrolaric commented
@MalinaGirl Пока не будет синди мыла

2020-10-25 19:59 UTC, 4310V343k commented on code/game/turfs/flooring/flooring_decals.dm
> +	name = "derelict12"
Эти имена точно должны быть такими?

2020-10-25 19:59 UTC, 4310V343k commented on code/game/turfs/flooring/flooring_decals.dm
> +	name = "derelict13"
Эти имена точно должны быть такими?

2020-10-25 19:59 UTC, 4310V343k commented on code/game/turfs/flooring/flooring_decals.dm
> +	name = "derelict14"
Эти имена точно должны быть такими?

2020-10-25 19:59 UTC, 4310V343k commented on code/game/turfs/flooring/flooring_decals.dm
> +	name = "derelict15"
Эти имена точно должны быть такими?

2020-10-25 19:59 UTC, 4310V343k commented on code/game/turfs/flooring/flooring_decals.dm
> +	name = "derelict16"
Эти имена точно должны быть такими?

2020-10-27 01:47 UTC, Epicus7 approved these changes
Попасть то на них можно?

2020-10-27 01:50 UTC, Epicus7 requested changes
А, стоп. В ПРе меняется `maps/away/derelict/derelict-station.dmm`, а в описании ничего об этом не сказано.

2020-11-01 02:57 UTC, TobyThorne commented
> А, стоп. В ПРе меняется `maps/away/derelict/derelict-station.dmm`, а в описании ничего об этом не сказано.

Она не меняется, это из-за зон вылезло. В любом случае, эта штука не используется, можно вообще вырезать.

2020-11-01 23:45 UTC, TobyThorne commented
Хуй с ним, вовсе откатил и больше не трогал тот поломанный дереликт. Энивей при следующем открытии переделается.

2020-11-05 07:42 UTC, TatarTheBuilder submitted a review, later dismissed
по карте всё нормально

2020-11-12 14:18 UTC, kreeperHLC approved these changes

2020-11-14 05:27 UTC, TapKo4eB commented
ебучие углы у гитары светятся
![suka](https://user-images.githubusercontent.com/48761132/99140444-32b81d00-2653-11eb-9aa4-468f46654000.png)

2020-11-14 05:30 UTC, TapKo4eB commented
а и я не в курсе насчёт реализации этого но обесточть на дереликте космической станции все апц раундстартом, а то там телепорт и всё такое.

2020-11-14 07:46 UTC, TobyThorne commented
Убрал светящиеся уголки и обсточил АПЦ. Наверное, так лучше.

2020-11-14 08:14 UTC, TapKo4eB approved these changes
ок

2020-11-14 08:26 UTC, Epicus7 reviewed
Снимаю чейнжреквест

2020-11-14 08:27 UTC, TatarTheBuilder approved these changes

2020-11-14 08:33 UTC, Epicus7 approved these changes

2020-11-14 08:35 UTC, merged