H.O.N.K. is back
ChaoticOnyx/OnyxBay pull request #3602
Opened 2020-10-25 23:03 UTC by TobyThorne

Никто его не ждал, но он вернулся.
Бананиум not included и детали не изготовить, но в остальном всё работает. Машину глобального раздражения можно собрать, облетав космос и нарыв себе клованский доступ.

- Вернул хонкер;
- Вернул банановую мортиру, мышеловную мортиру и мехагудок;
- Вооружение хонкера добавлено в клованский шаттл;
- Добавлена новая мини-локация в космосе, с рабочим Х.О.Н.К.ом (без вооружения), клованскими шмотками и спессщукой;

Сборка Х.О.Н.К.а чутка отличается от старой (потому что у нас сеrвеr rолевой):
Отвёрка, провода, кусачки, центральная плата, отвёртка, периферийная плата, отвёртка, плата наведения, отвёртка, сталь, гаечный ключ, сварка, пласталь, гаечный ключ, сварка, клованские ботинки, гудок, маска клована.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-28 20:47 UTC, Destrolaric commented
Молодой, у вас конфликт. Тайм ту фикс

2020-10-28 21:24 UTC, TobyThorne commented
Зарезолвлено. А Тревис пидор ленивый.

2020-11-15 21:29 UTC, kreeperHLC requested changes
Ух. Ну а так прикольно

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +	damage_absorption = list("brute"=1.2,"fire"=1.5,"bullet"=1,"laser"=1,"energy"=1,"bomb"=1)
```suggestion
	damage_absorption = list("brute"=1.2, "fire"=1.5, "bullet"=1, "laser"=1, "energy"=1, "bomb"=1)
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +*/
А может удалить, чем оставлять?
```suggestion
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +		step_away(target,src,15)
```suggestion
		step_away(target, src, 15)
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +	var/result = step(src,direction)
```suggestion
	var/result = step(src, direction)
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +	for(var/i=0;i<6;i++)
```suggestion
	for(var/i in 0 to 5)
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	New()
Ай. Ну и вместо New Initialize
```suggestion
/obj/item/mecha_parts/chassis/honker/New()
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	name="H.O.N.K. Head"
```suggestion
	name = "H.O.N.K. Head"
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	name="H.O.N.K. Torso"
```suggestion
	name = "H.O.N.K. Torso"
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	desc="A torso part of Odysseus. Contains power unit, processing core and life support systems."
```suggestion
	desc = "A torso part of Odysseus. Contains power unit, processing core and life support systems."
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	desc="An Odysseus left arm. Data and power sockets are compatible with most exosuit tools."
```suggestion
	name = "H.O.N.K. Left Arm"
	desc = "An Odysseus left arm. Data and power sockets are compatible with most exosuit tools."
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	desc="An Odysseus right arm. Data and power sockets are compatible with most exosuit tools."
```suggestion
	name = "H.O.N.K. Right Arm"
	desc = "An Odysseus right arm. Data and power sockets are compatible with most exosuit tools."
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	desc="An Odysseus left leg. Contains somewhat complex servodrives and balance maintaining systems."
```suggestion
	name = "H.O.N.K. Left Leg"
	desc = "An Odysseus left leg. Contains somewhat complex servodrives and balance maintaining systems."
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	desc="A Odysseus right leg. Contains somewhat complex servodrives and balance maintaining systems."
```suggestion
	name = "H.O.N.K. Right Leg"
	desc = "A Odysseus right leg. Contains somewhat complex servodrives and balance maintaining systems."
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_wreckage.dm
> +	New()
Вместо Нью я уже выше писал что
```suggestion
/obj/effect/decal/mecha_wreckage/honker/New()
```

2020-11-15 21:29 UTC, kreeperHLC commented on code/game/mecha/mecha_wreckage.dm
> +		return
```suggestion
		return

```

2020-11-16 01:51 UTC, TobyThorne commented on code/game/mecha/combat/honker.dm
> +*/
Легаси-комментарий, без него билд сломается.

2020-12-01 11:25 UTC, Doster-d commented on code/game/mecha/mecha_wreckage.dm
> +	New()
А не лучше ли использовать Initialize()?

2020-12-01 11:27 UTC, Doster-d requested changes

2020-12-01 11:27 UTC, Doster-d commented on code/game/mecha/mecha_parts.dm
> +	New()
```suggestion
	/obj/item/mecha_parts/chassis/honker/Initialize()
```

2020-12-01 11:27 UTC, Doster-d commented on code/game/mecha/mecha_wreckage.dm
> +	New()
```suggestion
	/obj/effect/decal/mecha_wreckage/honker/Initialize()
```

2020-12-05 15:36 UTC, TobyThorne commented on code/game/mecha/mecha_parts.dm
> +	New()
Это нужно переделывать всех мехов на инишалайз, а это никому нахуй не нужно, ибо ни на что не влияет, их раундстартом штуки четыре на картах.

2020-12-05 15:38 UTC, Doster-d approved these changes, later dismissed
Ну если на Инитиалайз плевать, то и мне плевать.

2020-12-06 22:09 UTC, kreeperHLC requested changes
Дотыкивай реквесты короче

2020-12-06 22:09 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +*/
![image](https://user-images.githubusercontent.com/14943437/101294491-a6031800-3828-11eb-8773-e6e28a94919b.png)

2020-12-06 22:09 UTC, kreeperHLC commented on code/game/mecha/mecha_parts.dm
> +	New()
Давай дотыкивай, я же сам всё написал

2020-12-06 22:09 UTC, kreeperHLC commented on code/game/mecha/mecha_wreckage.dm
> +	New()
И тут дотыкивай, всё за тебя написано

2020-12-07 02:17 UTC, Doster-d commented on code/game/mecha/mecha_wreckage.dm
> +	New()
А полный путь хотя бы можно?

2020-12-07 02:17 UTC, Doster-d commented on code/game/mecha/mecha_parts.dm
> +	New()
А полный путь хотя бы можно?

2020-12-07 10:02 UTC, TobyThorne commented on code/game/mecha/combat/honker.dm
> +*/
Как ты заебал, а.

2020-12-07 10:04 UTC, kreeperHLC commented on code/game/mecha/combat/honker.dm
> +*/
Я за тебя все сагги сделал. Тыкай и не жалуйся

2020-12-07 10:19 UTC, TobyThorne commented
голиаф отъебись пожалуйста всё вычистил к хуям

2020-12-07 10:28 UTC, kreeperHLC commented
> голиаф отъебись пожалуйста всё вычистил к хуям

Тебе нью сложно дописать?

2020-12-07 10:39 UTC, kreeperHLC approved these changes

2020-12-07 10:44 UTC, Doster-d approved these changes

2020-12-07 10:52 UTC, merged