Логирование рантаймов в БД
ChaoticOnyx/OnyxBay pull request #3609
Opened 2020-10-26 20:13 UTC by 4310V343k

Все рантаймы, которые пишутся локально в data/logs теперь попадают в БД в таком виде
![image](https://user-images.githubusercontent.com/56449763/97222783-ead67080-17df-11eb-9caa-ec19c1729169.png)
ID | date | game_id | revision(коммит) | file | line | call stack

Саму БД не трогал, всё так же как и в ишшуе

Из-за того, что у бота нет доступа к основному БД, все рантаймы пишутся во вторую БД, которую по-хорошему надо оторвать от подсистемы донатов
![image](https://user-images.githubusercontent.com/56449763/97223169-7223e400-17e0-11eb-983b-9cc7cb5b91f2.png)

closes #1509

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-26 21:14 UTC, jammer312 requested changes
Советую прочитать [это](https://habr.com/ru/post/148151/) или что-то в этом роде.
Еще советую подумать, зачем я впиливал ту самую функцию, которая собирает запрос по шаблону и списку аргументов, и зачем тебе эпикус о ней сказал.

2020-10-26 21:14 UTC, jammer312 commented on code/modules/error_handler/error_handler.dm
> +	var/DBQuery/query = SSdonations.dbconnection.NewQuery("INSERT INTO runtimes (date, game_id, build_version, file, line, body) VALUES (NOW(), '[game_id]', '[revdata.revision]', '[E.file]', '[E.line]',
![nogodplsno](https://media.tenor.com/images/4d7955758b3991f061c44819f7702b5d/tenor.gif)

2020-10-26 21:19 UTC, 4310V343k commented
> Советую прочитать [это](https://habr.com/ru/post/148151/) или что-то в этом роде.
> Еще советую подумать, зачем я впиливал ту самую функцию, которая собирает запрос по шаблону и списку аргументов, и зачем тебе эпикус о ней сказал.

И я писал там же. Эта функция тыкает главную БД, а не донатную, для донатной такой альтернативы нет

2020-10-26 21:24 UTC, jammer312 commented on code/modules/error_handler/error_handler.dm
> +	var/DBQuery/query = SSdonations.dbconnection.NewQuery("INSERT INTO runtimes (date, game_id, build_version, file, line, body) VALUES (NOW(), '[game_id]', '[revdata.revision]', '[E.file]', '[E.line]',
Кстати, у тебя непосредственно сообщение об ошибке в БД не добавляется. Т.е. то, что '[E]'.

2020-10-26 21:27 UTC, jammer312 commented on code/modules/error_handler/error_handler.dm
> +	var/DBQuery/query = SSdonations.dbconnection.NewQuery("INSERT INTO runtimes (date, game_id, build_version, file, line, body) VALUES (NOW(), '[game_id]', '[revdata.revision]', '[E.file]', '[E.line]',
А, или добавляется. Чет странно оно логируется. Т.е. тот логгер, что уже есть, логирует сначала `"\[[time_stamp()]] Runtime in [E.file],[E.line]: [E]"`, затем все из `desclines`. Влом проверять, но мне таки кажется, что что-то ты таки забываешь писать в БД.

2020-10-26 21:29 UTC, 4310V343k commented on code/modules/error_handler/error_handler.dm
> +	var/DBQuery/query = SSdonations.dbconnection.NewQuery("INSERT INTO runtimes (date, game_id, build_version, file, line, body) VALUES (NOW(), '[game_id]', '[revdata.revision]', '[E.file]', '[E.line]',
> Влом проверять, но мне таки кажется, что что-то ты таки забываешь писать в БД.

Ты прав

2020-10-26 21:32 UTC, jammer312 commented
> Эта функция тыкает главную БД, а не донатную, для донатной такой альтернативы нет

А, ну ок, тогда кодить серьезные уязвимости в билд можно.
А вообще, тебе эпикус вроде сказал, как можно ее достаточно просто поменять, чтобы она была пригодна и для твоих нужд.

2020-10-26 23:58 UTC, Epicus7 requested changes
Не, ну конечно уязвимости в билде нам не нужны. Надо все-таки использовать функцию Джаммера, изменив ее так, чтобы она могла работать с обеими БД.

Также твоя запись рантаймов не работает когда отключена система донатов. Это конечно тоже не пойдет. Нужно базу таки открутить от системы донатов, чтобы рантаймы от нее не зависели.

2020-10-27 09:20 UTC, jammer312 requested changes
Из того, к чему претензии были, ничего не исправил + сломал sql_query

2020-10-27 09:21 UTC, 4310V343k commented
> Из того, к чему претензии были, ничего не исправил + сломал sql_query

Объясни, почему сломал?

2020-10-27 09:21 UTC, jammer312 commented
Хотя нет, неполное логирование поправил, но это не было основной претензией.

2020-10-27 09:25 UTC, jammer312 commented
> Претензия была к тому, что нет санитайза - исправил, теперь рантаймы логируются через sql_query

Нихера ты не исправил, у тебя как лились данные в БД без санитайза, так и продолжают литься.

> Объясни, почему сломал?

Потому что она теперь некорректно обрабатывает позиционные аргументы и вообще не обрабатывает ассоциативные (через список). Ты ее хотя бы пытался тестить после своих изменений?

2020-10-27 09:33 UTC, 4310V343k commented
> > Претензия была к тому, что нет санитайза - исправил, теперь рантаймы логируются через sql_query
> 
> Нихера ты не исправил, у тебя как лились данные в БД без санитайза, так и продолжают литься.
> 
> > Объясни, почему сломал?
> 
> Потому что она теперь некорректно обрабатывает позиционные аргументы и вообще не обрабатывает ассоциативные (через список). Ты ее хотя бы пытался тестить после своих изменений?

Галочку видишь?

2020-11-18 06:39 UTC, jammer312 requested changes
Я до сих пор не уверен, хочу ли я это аппрувать (после исправления указанных косяков), но вот пока что реджект.

2020-11-18 06:39 UTC, jammer312 commented on code/_global_vars/sensitive.dm
> +GLOBAL_REAL_VAR(sqldonaddres)= "localhost"
> sqldonaddres

2020-11-18 06:39 UTC, jammer312 commented on code/game/world.dm
> +		world.log << "SQL disabled. Your server will not use Donations database."
`log_to_dd()`?

2020-11-18 06:39 UTC, jammer312 commented on code/controllers/configuration.dm
> +			if ("disabledondbconfig")
Оно точно таким должно быть?
Ну типа какой смысл конфигом *вырубать* конфиги дб? Не логичнее определять это по наличию/отсутствию соответствующих значений в конфиге (включать, если есть все необходимые, в противном случае выключать)? Или хотя бы *включать* дб через конфиги, а не наоборот?

2020-11-18 06:39 UTC, jammer312 commented on code/controllers/configuration.dm
> +			if ("disabledondbconfig")
Хотя тут скорее название неправильное. Оно не для выключения конфигов БД, оно для выбора иного способа задания этих конфигов. И текущее название никак этот смысл не передает.
Зачем тебе другой способ задания этих конфигов - хз. Имхо он лишний (ибо конфигов более чем достаточно, да и нечего лишний раз плодить сущности). Но, может, я чего-то не понимаю, и тут имеют место некоторые соображения безопасности, из-за которых лучше не использовать конфиги (хотя что-то мне подсказывает, что таки нет).

2020-11-18 06:39 UTC, jammer312 commented on code/modules/donations/donations.dm
> +	var/DBQuery/query = dbcon_don.NewQuery("INSERT IGNORE INTO players(ckey) VALUES (\"[player.ckey]\")")
Тут вроде возможности инъекции нет, но, может, стоит здесь тоже использовать обертку (хотя бы для того, чтоб тот, кто потом будет кодить "по образу и подобию", использовал обертку, и не делал потенциально небезопасные запросы)

2020-11-18 06:39 UTC, jammer312 commented on code/modules/donations/donations.dm
> +	var/DBQuery/query = dbcon_don.NewQuery("INSERT IGNORE INTO players(ckey) VALUES (\"[player.ckey]\")")
И ниже тоже

2020-11-18 06:39 UTC, jammer312 commented on code/modules/donations/donations.dm
> +	var/DBQuery/query = dbcon_don.NewQuery({"
Вот здесь точно стоит заменить на обертку

2020-11-18 06:39 UTC, jammer312 commented on code/modules/donations/donations.dm
>  	type = sql_sanitize_text(type)
А эти две строки выпилить

2020-11-18 06:48 UTC, jammer312 commented
К слову, предлагаю из репы выпилить `sql_sanitize_text` (во-первых, использовать самопальную реализацию - почти всегда плохая идея, лучше отдать эту задачу драйверу БД, который умеет корректно санитайзить текст для этой конкретной реализации БД; во-вторых, это - плохая реализация, и ее точно надо либо выпиливать, чтоб неповадно было, либо фиксить (что не стоит того ибо первый пункт))

2020-11-18 11:48 UTC, 4310V343k commented on code/_global_vars/sensitive.dm
> +GLOBAL_REAL_VAR(sqldonaddres)= "localhost"
my bad

2020-11-18 11:48 UTC, 4310V343k commented on code/game/world.dm
> +		world.log << "SQL disabled. Your server will not use Donations database."
ok

2020-11-18 11:49 UTC, 4310V343k commented on code/controllers/configuration.dm
> +			if ("disabledondbconfig")
Раньше другой способ использовался из-за проблем с хостингом.

Лучше скажи, мне вообще выпилить старый способ, или поменять название переменной?

2020-11-18 11:50 UTC, 4310V343k commented on code/modules/donations/donations.dm
> +	var/DBQuery/query = dbcon_don.NewQuery("INSERT IGNORE INTO players(ckey) VALUES (\"[player.ckey]\")")
![image](https://user-images.githubusercontent.com/56449763/99527119-565dc900-29ad-11eb-90ec-96bc0a4c2214.png)
Поменяю

2020-11-18 11:50 UTC, 4310V343k commented on code/modules/donations/donations.dm
> +	var/DBQuery/query = dbcon_don.NewQuery({"
ok

2020-11-18 11:50 UTC, 4310V343k commented on code/modules/donations/donations.dm
>  	type = sql_sanitize_text(type)
Вместе с проком `sql_sanitize_text()`

2020-11-18 13:26 UTC, jammer312 commented on code/controllers/configuration.dm
> +			if ("disabledondbconfig")
С подобными вопросами к эпикусу. Я бы выпилил (то, что отдельно от конфигов), раз теперь хостинг нормальный

2020-12-01 09:37 UTC, 4310V343k commented
C одной стороны выпил ненужного прока не скоуп этого ПРа. А с другой вроде как полезно будет. @jammer312, может я всё-таки создам отдельный ПР с выпилом sql_sanitize_text(), а этот уже вмержить?

2020-12-01 10:36 UTC, 4310V343k commented on code/modules/donations/donations.dm
>  	type = sql_sanitize_text(type)
Но в другом ПРе

2020-12-30 21:19 UTC, 4310V343k commented
Если я скажу что ПР с выпилом ненужного прока и некоторые фиксы с этим связанные уже готов, сюда накидают аппрувов?

2021-04-15 19:38 UTC, 4310V343k commented
Тут уже и конфликты понабежали блин...

2021-04-16 18:00 UTC, 4310V343k commented
Конфликты закончились, оп всё ещё живой

2021-04-21 22:30 UTC, kreeperHLC commented
> Конфликты закончились, оп всё ещё живой

А людей которые отважатся это проверять всё ещё нет

2021-04-22 12:28 UTC, 4310V343k commented
Жалко

2021-05-19 19:01 UTC, 4310V343k commented
Опять конфликты ಠಗಠ

2021-05-20 07:38 UTC, Doster-d requested changes

2021-05-20 07:38 UTC, Doster-d commented on code/_helpers/sql.dm
> +//	sql_query_adv(template, db, arg1, arg2...)
Че за комментированный код?

2021-05-20 08:52 UTC, Doster-d commented on code/_helpers/sql.dm
> +//	sql_query_adv(template, db, arg1, arg2...)
А ое

2021-05-20 08:52 UTC, Doster-d submitted a review, later dismissed

2021-05-20 09:39 UTC, Doster-d submitted a review, later dismissed

2021-05-20 09:52 UTC, 4310V343k commented
Твой ревью *не пройдеееет*
С телефона на свежую голову намного легче находить очепятки

2021-05-20 11:04 UTC, Epicus7 requested changes
VV_hidden надо пофиксить, а то у нас утекает адрес БД, что неоч хорошо.

Остальные комменты не критические, можно оставить на будущее.

2021-05-20 11:04 UTC, Epicus7 commented on code/game/world.dm
> +	if(failed_don_db_connections > FAILED_DB_CONNECTION_CUTOFF)	//If it failed to establish a connection more than 5 times in a row, don't bother attempting to connect anymore.
Можно еще добавить комментарий
// if you don't know what this line do, read a comment before

Комментарии, которые описывают что делает код - не нужны) Переменные хорошо названы, так что тут и без комментария понятно. Ниже в этой функции еще пачка комментов от капитана очевидности.

Такие комменты плохи тем, что они усложняют восприятие кода. Ты думаешь что там что-то важное, начинаешь вчитываться и пытаться разобраться, а оказывается, что это просто тот же самый код переписанный с Бьонда на инглиш.

2021-05-20 11:04 UTC, Epicus7 commented on code/game/world.dm
> +		SSdonations.UpdateAllClients()
А тут можно было бы хук сделать, а то абстракция нарушается. Непонятно зачем логика подключения к БД лезет подсистемы трогать. Обычно делают какой-то хук/ивент, который просто сигнализирует, что у нас подключение к БД произошло, а на него уже подсистема подписывается и по событию чот там делает сама.

2021-05-20 11:06 UTC, Epicus7 commented
Надо потестить локально, что БД донатов не отваливается после этих изменений.

2021-05-20 13:39 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
> +		sql_query("INSERT INTO erro_ban(`id`,`bantime`,`serverip`,`bantype`,`reason`,`job`,`duration`,`rounds`,`expiration_time`,`ckey`,`computerid`,`ip`,`a_ckey`,`a_computerid`,`a_ip`,`who`,`adminwho`,`ed
![image](https://user-images.githubusercontent.com/56449763/118988600-02e32c80-b98a-11eb-9317-a013ac06f815.png)

2021-05-20 13:42 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
> +		sql = {"SELECT ckey, server_id FROM erro_ban WHERE id = $id"}
Не знаю, видимо надо было
![image](https://user-images.githubusercontent.com/56449763/118989052-653c2d00-b98a-11eb-88b6-ffcd313008b2.png)
Уберу

2021-05-20 13:55 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
> +		sql_query("INSERT INTO erro_ban(`id`,`bantime`,`serverip`,`bantype`,`reason`,`job`,`duration`,`rounds`,`expiration_time`,`ckey`,`computerid`,`ip`,`a_ckey`,`a_computerid`,`a_ip`,`who`,`adminwho`,`ed
Я уже и не помню, зачем вообще трогал баны

2021-05-20 14:00 UTC, 4310V343k commented on code/game/world.dm
> +		SSdonations.UpdateAllClients()
Что произойдёт быстрее - подключение к БД, или инициализация донатов?

2021-05-21 03:00 UTC, Epicus7 commented on code/game/world.dm
> +		SSdonations.UpdateAllClients()
Хрен его знает, надо смотреть по коду где что вызывается. Я думаю с последними изменениями норм должно все быть.

2021-05-21 03:01 UTC, Epicus7 commented
Сейчас, вроде, все норм. Постараюсь найти время потестить это локально и потом можно будет принять.

2021-05-21 03:01 UTC, Epicus7 approved these changes

2021-05-21 04:21 UTC, Doster-d approved these changes
Кек ор кринж: кек.

2021-05-21 20:28 UTC, Epicus7 commented
Проверили какие-то основные вещи вместе с @4310V343k, можно принимать

2021-05-21 20:31 UTC, merged