Записка о проводах в шлюзах.
ChaoticOnyx/OnyxBay pull request #3614
Opened 2020-10-27 12:53 UTC by Doster-d

Добавил инженерам (и СЕ в том числе) записку о проводах шлюзов на станции.

Вместо того, что бы поставить записку на карту, я выдаю её каждому инженеру. ~~Помогите мне, я не умею впиливать в карту предметы :(~~

close #2880

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-27 12:54 UTC, TatarTheBuilder commented
> Вместо того, что бы поставить записку на карту, я выдаю её каждому инженеру.

зачем

не добавляй тогда вообще никуда, я закину на карту в следующем пре с ней

2020-10-27 13:35 UTC, Doster-d commented
> > Вместо того, что бы поставить записку на карту, я выдаю её каждому инженеру.
> 
> зачем
> 
> не добавляй тогда вообще никуда, я закину на карту в следующем пре с ней

Впилил.

2020-10-28 23:28 UTC, Doster-d commented
Я тут карту трогаю, да.

2020-11-02 04:40 UTC, Doster-d commented
Конфликты, мои конфликты...

2020-11-02 18:05 UTC, Doster-d commented
Починил тег [end], а точнее избавился от него и использовал функцию make_readonly(), исправил конфликты с картой.

2020-11-10 14:18 UTC, TatarTheBuilder commented
> There're some information about standart airlock wires

There is some information

Кроме этого вроде норм

2020-11-10 14:21 UTC, Doster-d commented
Done

2020-11-10 17:17 UTC, TobyThorne requested changes

2020-11-10 17:17 UTC, TobyThorne commented on code/modules/paperwork/misc.dm
> +	qdel(wire_to_wire_purpose_list)
Не понял, что за прикол тут с qdel(). Пытался найти скрытый смысл и не смог, оно просто выдаёт два рантайма и дальше нормально работает.

2020-11-10 17:18 UTC, Doster-d commented on code/modules/paperwork/misc.dm
> +	qdel(wire_to_wire_purpose_list)
Я тут хотел память освободить, но видимо я слишком клоун :(

2020-11-10 18:15 UTC, Doster-d commented on code/modules/paperwork/misc.dm
> +	qdel(wire_to_wire_purpose_list)
Починил

2020-11-10 21:48 UTC, TobyThorne commented on code/modules/paperwork/misc.dm
> +	make_readonly()
У вас конец файла таки еврейский.

2020-11-10 21:52 UTC, Doster-d commented on code/modules/paperwork/misc.dm
> +	make_readonly()
Теперь ариец.

2020-11-12 01:36 UTC, TobyThorne approved these changes

2020-11-12 10:36 UTC, kreeperHLC approved these changes

2020-11-12 10:43 UTC, TatarTheBuilder approved these changes

2020-11-12 10:52 UTC, Doster-d commented
Merge?

2020-11-12 11:10 UTC, merged