Пересоздание сломанного пул реквеста(фикс лестниц)
ChaoticOnyx/OnyxBay pull request #3617
Opened 2020-10-27 19:39 UTC by Destrolaric

Сломал прошлый пул реквест кривым ребейзом. Фикс прохода через стены с помощью перил. 

fix #3573

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-15 21:36 UTC, kreeperHLC requested changes

2020-11-15 21:36 UTC, kreeperHLC commented on code/game/objects/structures/railing.dm
> +		return check_tile(user,OT)
```suggestion
	if (OT == UT)
		return check_tile(user, T)
	else if (T == UT)
		return check_tile(user, OT)
```

2020-12-01 11:23 UTC, Doster-d approved these changes
Выглядит хорошо.

2020-12-01 11:50 UTC, kreeperHLC approved these changes

2020-12-13 23:54 UTC, merged