Фиксы-фиксы-фиксы
ChaoticOnyx/OnyxBay pull request #3626
Opened 2020-10-28 16:38 UTC by sweden-moose

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-10-28 16:42 UTC, TobyThorne commented
Описание отличное, переменные тоже.

2020-10-28 16:51 UTC, Epicus7 requested changes
Описание хорошее, но переменную конечно лучше переименовать. И содержимое окошка собирать на месте лучше, а в списке хранить только нужные переменные, а не целые собранные строчки.

2020-10-28 20:52 UTC, Epicus7 requested changes

2020-10-28 20:52 UTC, Epicus7 commented on code/modules/onyxchat/browserOutput.dm
> +				GLOB.cookie_match_history += list(key_name(src.owner),found["ckey"])
Лучше именованный список, чтобы не нужно было по индексам обращаться.

2020-10-28 20:52 UTC, Epicus7 commented on code/modules/onyxchat/browserOutput.dm
> +GLOBAL_LIST_EMPTY(cookie_match_history) // cache for fuckers with a history of playing on a banned account
Я думаю с таким названием тут и без комментария все понятно.

2020-10-28 21:18 UTC, sweden-moose commented
Done

2020-10-29 02:07 UTC, Epicus7 approved these changes

2020-10-29 11:20 UTC, PlinHost approved these changes

2020-11-04 22:36 UTC, TobyThorne approved these changes

2020-11-04 22:37 UTC, merged