Species languages
ChaoticOnyx/OnyxBay pull request #3679
Opened 2020-11-04 09:13 UTC by Ayuska

action(tweak): Языки разделены по расам, больше никаких ассистентов общающихся на языке воксов.

resolves #3675

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим x внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над ПРом. ЭТУ СТРОЧКУ НУЖНО УДАЛИТЬ.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-04 10:46 UTC, Doster-d requested changes
Ну, я затестил, таяра работает, а остальные расы сломались (нет языка).

2020-11-04 11:35 UTC, Ayuska commented
> Ну, я затестил, таяра работает, а остальные расы сломались (нет языка).
Все работает, зайди в игру и проверь список языков.

2020-11-04 12:09 UTC, Doster-d commented
Да, напиздел, языки есть, просто для меня это было не очевидно

2020-11-05 13:24 UTC, TapKo4eB approved these changes
вроде норм

2020-11-10 16:56 UTC, TobyThorne commented
Абсолютно не нравится. Воксовский - ладно, бог с ним. У нас, как-никак, воксы - исключительно антаги, в НТ они не работают. С обезьянами тоже понятно, у них вообще своя лингвистическая атмосфера.

Но почему языки присутствующих на станции рас полностью недоступны для остальных - это для меня загадка. На самом деле, как и обязательное владение языком своей расы. А может игрок хочет быть скреллом-журналистом, работавшим на Адомае с таяранами? Или унатхом-сиротой, выросшим в детском доме среди людей?

Какой-нибудь скрелльский можно было сделать по принципу Encoded Audio Language - чтобы другие расы могли понимать, если владеют, но говорить на нём могли только скреллы.

В общем, я против текущей реализации, она ничего не привносит, только обрезает возможности отыгрыша.

2020-11-10 17:51 UTC, MrMagick2104 commented
> Или унатхом-сиротой, выросшим в детском доме среди людей?

Он может просто не использовать язык, если его персонаж не знает его.

2020-12-01 11:56 UTC, kreeperHLC approved these changes
По коду всё верно, но надо проверять на локалке

2020-12-01 11:57 UTC, Doster-d reviewed
Аналогично Тоби текущая реализация меня не удовлетворяет, прошу автора сделать как предлагает Тоби.

2020-12-01 11:58 UTC, Doster-d approved these changes

2020-12-01 12:08 UTC, Doster-d commented
Ладно, по коду норм, принять можно ~~, но не нужно~~

2020-12-01 12:22 UTC, closed without merging