Апгрейд медицинской системы
ChaoticOnyx/OnyxBay pull request #3715
Opened 2020-11-09 12:54 UTC by kcalbCube

1. Изменения в технике.
1.1 UI Боди сканнера был перенесен с tgui на nanoui.
1.2 Теперь в раздатчиках NanoMED Plus находится одна банка с таблетками глюкозы.

2. Перефирийные изменения.
2.1 До ПР при повреждениях мозга могла произойти боль в любой части тела с силой 10.
Теперь она может произойти в разных степенях, в зависимости от повреждений мозга.
2.2 При повреждениях мозга могут появится галлюцинации.
2.3 Банка с таблетками глюкозы содержит не 21, а 10 пилюль.
2.4 Был изменен вес(\modules\item_worth\reagents.dm) некоторых реагентов
2.5 Передозировка никотином теперь больше изменяет пульс, так же немного вызывает гипоксию(BREATHLOSS)
2.6 Был случайно проведен микрорефакторинг некоторых файлов в некоторых местах(span class обернут в SPAN, отформатирован код и все в таком духе.)
2.7 Инапровалин имеет небольшое противоэпилептическое воздействие(с.м. 3.6)
2.8 Noexcutite имеет небольшое противоэпилептическое воздействие(с.м. 3.6)

3. Основные изменения.
3.1 Теперь активность мозга отделена от его статуса. Активность повышается в основном из-за боли, ослепления, как овердоз препаратов. Возможно добавить больше источников.
3.2 При зашкаливающих значениях активности мозга человек впадает в эпилепсию. Это состояние достаточно быстро угнетает мозг. Так же есть промежуточные состояние эпилепсии, дающие тряску и прочее.
3.3 Дизабилити EPILEPSY снижает порог для попадания в состояние эпилепсии.
3.4 Добавлен дизабилити SCHIZOPHRENIA, дающий переодические галлюцинации.
3.5 Теперь, если повреждения мозга перейдут через 95% пациент получит случайный дизабитилити из списка(на данный момент) {EPILEPSY, TOURETTES, NERVOUS, SCHIZOPHRENIA}
3.6 Добавлен псилоксон - противоэпилептический препарат. Ускоряет стабилизацию мозговой активности(в обе стороны). Изготавливается из 1 части алкизина, 1 части noexcutite, 2 частей сопорифика. Из побочных эффектов седативный эффект. При передозе вызывает сильный седативный эффект и временный паралич.

close #3708
close #3685
ЗДЕСЬ нужно **привязать иссуи**, которые относятся к Pull Request-у в формате `close #1234`, `fix #1234` или что-то типа `Затрагивает #1234, но не фиксит его`, если вы просто хотите упоминуть иссуи, но не закрывать его вместе с ПРом. ЭТОТ ПУНКТ НАДО ЗАМЕНИТЬ ЛИНКАМИ НА ИССУИ, А ЕГО УДАЛИТЬ.

offtop:
Не очень разобрался в коммитах, прошу не бить граблями.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-09 12:56 UTC, Ruforce commented
Выглядит классно. Но зачем ты поменял ТГУИ на наноУИ? (дада я знаю, что они лучше в плане надежности работы и всё такое).

2020-11-09 12:57 UTC, kcalbCube commented
> Выглядит классно. Но зачем ты поменял ТГУИ на наноУИ? (дада я знаю, что они лучше в плане надежности работы и всё такое).

Я никак не разобрался как работать с тгуи. Спросил на сервере - оказывается никто не знает как. Пришлось переписать.

2020-11-09 13:54 UTC, 4310V343k commented
> (дада я знаю, что они лучше в плане надежности работы и всё такое).

Зачем говорить если не знаешь(
ТГУИ во всём превосходит наноуи, его за тем и [портировали](https://github.com/ChaoticOnyx/OnyxBay/pull/782) даже на опух, но никто не умеет им пользоваться и его постепенно выпиливают обратно. Зачем? Потому что

2020-11-09 14:27 UTC, 4310V343k reviewed
Всё

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +	return "bad"
В одном месте сделал с большой буквы, делай везде так

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +	return "bad"
В одном месте сделал с большой буквы, делай везде так

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +	return "good"
В одном месте сделал с большой буквы, делай везде так

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
>  	var/mob/living/carbon/human/H = src
Че за приколы?

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +			data["brain_activity"]    = brain.get_activity()
Опять пробелы

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +		data["brain_activity_status"] = src.get_brain_activity_status()
Опять src.

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +		data["brain_status"]          = get_brain_status(100-brain_damage_procents)
Опять пробелы
```suggestion
		var/brain_damage_procents = 100 * (brain.damage / brain.max_damage)
		data["brain_damage"] = 100 - brain_damage_procents
		data["brain_status"] = get_brain_status(100 - brain_damage_procents)
```

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +			data["pulse_status"] = "bad"
В одном месте сделал с большой буквы, делай везде так

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +		{
Эти скобки тут откуда

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +			var/pulse     = text2num(H.get_pulse(1))
Проблелы

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +			organ_data += list("Significant")
Мне кажется тут перепутано

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +	return
```suggestion
	return

```

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +	ASSERT(user)
Разве не моб может может тыкнуть рукой?

2020-11-09 14:27 UTC, 4310V343k commented on code/game/machinery/adv_med.dm
> +	var/ui_key = "adv_med"
Нужно ли это?

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/item_worth/reagents.dm
> +	value = 3.5
```suggestion
	value = 3.5

```

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/maps/swapmaps.dm
> +	return list(x, y, z)
Немного не понял зачем оно в этом ПРе

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/mob/living/carbon/carbon.dm
> +	src.internal_organs_by_name[BP_BRAIN].relative_activity += activity
```suggestion
	src.internal_organs_by_name[BP_BRAIN].relative_activity += activity

```

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +		var/feedback = list("<span class='notice'>There are noises of movement</span>")
Гений. Ещё и галочку что протестил поставил. Убири

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/organs/internal/brain.dm
>  	icon_state = "chitin"
ОПЯТЬ ПРОБЕЛЫ

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/organs/internal/brain.dm
> +	max_damage         = species? (species.total_health/2) : 100
И тут пробел

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/organs/internal/brain.dm
> +	min_broken_damage  = max_damage*0.75
И тут тоже

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents.dm
> +	. = ..()
```suggestion
	. = ..()

```

2020-11-09 14:27 UTC, 4310V343k commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +	update_icon()
```suggestion
	update_icon()

```

2020-11-09 14:27 UTC, 4310V343k commented on nano/templates/adv_med.tmpl
> +     TODO: Move this to external file
Да?

2020-11-09 14:29 UTC, sweden-moose commented on code/modules/organs/internal/brain.dm
>  	icon_state = "chitin"
Ты не понимаешь!! Это для читабельности!!

2020-11-09 14:33 UTC, kcalbCube commented on code/game/machinery/adv_med.dm
>  	var/mob/living/carbon/human/H = src
Приколы оригинального кода

2020-11-09 14:34 UTC, kcalbCube commented on code/game/machinery/adv_med.dm
> +	var/ui_key = "adv_med"
Были моменты в дебаге.

2020-11-09 14:47 UTC, kcalbCube commented on code/game/machinery/adv_med.dm
> -	tg_ui_interact(user)
Очевидно, перенесено

2020-11-09 15:22 UTC, PlinHost commented
>ТГУИ во всём превосходит наноуи

нет

2020-11-09 15:35 UTC, 4310V343k commented
> > ТГУИ во всём превосходит наноуи
> 
> нет

Ладно

2020-11-09 22:39 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/98604895-b948c380-230e-11eb-84ce-abe03f81dd1b.png)
весь ПР в ехидных красных таблетках

2020-11-10 12:04 UTC, Destrolaric commented
#3691
Я предлагаю добавить автору пула решение на это предложение

2020-11-10 12:28 UTC, sweden-moose commented on code/game/objects/items/devices/flash.dm
> +					C.add_brain_activity(20)
Класс, только вот у нас есть еще настенные флешеры и флешбенги, с ними что?

2020-11-10 12:28 UTC, sweden-moose commented on code/game/objects/items/devices/flash.dm
> +					C.add_brain_activity(20)
Да и судя по всему, можно убить человека эпилепсией за 5 кликов, если я не прав, то поправь.

2020-11-10 12:28 UTC, sweden-moose commented on code/modules/reagents/Chemistry-Reagents.dm
> -	. = ..()
куда

2020-11-10 12:28 UTC, sweden-moose commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	else if(M.bodytemperature <= 310)
зачем?

2020-11-10 12:59 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	else if(M.bodytemperature <= 310)
Надо

2020-11-10 12:59 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents.dm
> -	. = ..()
куда

2020-11-11 07:00 UTC, kcalbCube commented
Слишком много отвратительных коммитов. Я закрою этот ПР и вскоре переоткрою: коммиты с названием "commit" и "really final" слишком сильно испортят историю коммитов. Скорее всего из-за этого ПР закроют, так что лучше сделаю это самостоятельно.

2020-11-11 07:04 UTC, Destrolaric commented
F

2020-11-11 07:06 UTC, Doster-d commented
Держу в курсе, в гите есть такая штучка как скуаш коммитов, что преобразует 1000 твоих коммитов в один красивый.

2020-11-11 07:07 UTC, Animesku commented
https://htmlacademy.ru/blog/boost/tools/how-to-squash-commits-and-why-it-is-needed

2020-11-11 09:13 UTC, stylemistake commented
ОП видимо не осилил документацию

2020-11-12 04:57 UTC, kcalbCube commented
Оказывается при слиянии пуш реквеста можно все коммиты объединить в один. @Doster-d @Animesku спасибо что подсказали!

2020-11-12 11:27 UTC, kcalbCube commented
> #3691
> Я предлагаю добавить автору пула решение на это предложение
> 

Возможно добавлю кальциксон или подобное в ближайшие дни.

2020-11-13 13:24 UTC, kcalbCube commented on code/game/objects/items/devices/flash.dm
> +					C.add_brain_activity(20)
Исправлено

2020-11-13 13:27 UTC, sweden-moose commented on code/game/objects/items/devices/flash.dm
> +					C.add_brain_activity(20)
> Класс, только вот у нас есть еще настенные флешеры и флешбенги, с ними что?

Это точно не исправлено

2020-11-14 05:32 UTC, kcalbCube commented on code/game/objects/items/devices/flash.dm
> +					C.add_brain_activity(20)
Исправлено

2020-11-14 06:31 UTC, TapKo4eB reviewed
ревью кода

2020-11-14 06:31 UTC, TapKo4eB commented on code/__defines/dna.dm
> +#define DEPRESSION    64
а чем тебе не понравились старые бит флаги

2020-11-14 06:31 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +/proc/get_brain_status(var/brain_damage_procents)
удоляй пока не зарезал
```suggestion
/proc/get_brain_status(brain_damage_procents)
```

2020-11-14 06:31 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +/proc/get_blood_status(var/procents)
зарежу удаляй пока не
```suggestion
/proc/get_blood_status(procents)
```

2020-11-14 06:31 UTC, TapKo4eB commented on code/modules/reagents/Chemistry-Reagents.dm
> -	. = ..()
верни . = ..() иначе куделить нормально не будет

2020-11-14 06:31 UTC, TapKo4eB commented on code/modules/surgery/surgery.dm
> -
если удаляешь использование то и дефайн листа удали из датума операций

2020-11-14 06:36 UTC, kcalbCube commented on code/modules/surgery/surgery.dm
> -
Не понял

2020-11-14 06:39 UTC, TapKo4eB reviewed
ревью кодстайла

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +
```suggestion

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +			data["brain_activity"]    = 0
```suggestion
			data["brain_activity"] = 0
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +			data["brain_activity"]    = brain.get_activity()
```suggestion
			data["brain_activity"] = brain.get_activity()
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +		data["brain_damage"]     	  = 100-brain_damage_procents
```suggestion
		data["brain_damage"] = 100-brain_damage_procents
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +		data["brain_status"]          = get_brain_status(100-brain_damage_procents)
```suggestion
		data["brain_status"] = get_brain_status(100-brain_damage_procents)
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +
```suggestion

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +			var/pulse     = text2num(H.get_pulse(1))
```suggestion
			var/pulse = text2num(H.get_pulse(1))
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +
```suggestion

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/flasher.dm
> +
```suggestion

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/item_worth/reagents.dm
> +	value = 3.5
```suggestion
	value = 3.5

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/maps/swapmaps.dm
> +		S  =new
```suggestion
		S = new
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/mob/living/carbon/carbon.dm
> +	src.internal_organs_by_name[BP_BRAIN].relative_activity += activity
```suggestion
	src.internal_organs_by_name[BP_BRAIN].relative_activity += activity

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/organs/internal/brain.dm
> +	max_damage         = species? (species.total_health/2) : 100
```suggestion
	max_damage = species? (species.total_health/2) : 100
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/organs/internal/brain.dm
> +	min_broken_damage  = max_damage*0.75
```suggestion
	min_broken_damage = max_damage*0.75
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/organs/internal/brain.dm
> +											  SPAN_WARNING("You feel extremely [pick("dizzy","woozy","faint")]..."))
```suggestion
					SPAN_WARNING("You feel extremely [pick("dizzy","woozy","faint")]..."))
```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/reagents/Chemistry-Reagents.dm
> +	holder = null
```suggestion
	holder = null

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +			E.update_damstate()
```suggestion
			E.update_damstate()

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/reagents/Chemistry-Recipes.dm
> +	result_amount = 2
```suggestion
	result_amount = 2

```

2020-11-14 06:39 UTC, TapKo4eB commented on nano/templates/adv_med.tmpl
> +</div>
```suggestion
</div>

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/modules/organs/internal/brain.dm
> +
```suggestion

```

2020-11-14 06:39 UTC, TapKo4eB commented on code/game/machinery/adv_med.dm
> +
```suggestion
```

2020-11-14 06:43 UTC, kcalbCube commented on nano/templates/adv_med.tmpl
> + </div>
???

2020-11-14 06:47 UTC, TapKo4eB commented on nano/templates/adv_med.tmpl
> + </div>
каждый <div> должен иметь класс итем
а на деле только первый

2020-11-14 07:12 UTC, kcalbCube commented on nano/templates/adv_med.tmpl
> + </div>
Да вроде все нормально.

2020-11-14 07:38 UTC, TapKo4eB commented on nano/templates/adv_med.tmpl
> + </div>
ладно похрен и так работает

2020-11-14 12:37 UTC, kcalbCube commented
@TobyThorne ready to review

2020-11-14 12:40 UTC, TobyThorne commented
а можно пожалуйста ещё больше разных фич в ПР

2020-11-14 12:44 UTC, TobyThorne commented on code/modules/item_worth/reagents.dm
> +	value = 3.5
Почему слиптоксин стал дороже хлорки, зачем потрогано вино, почему сахар стоит две тыщи рублей за килограмм, нихуя не понимаю.

2020-11-14 12:47 UTC, kcalbCube commented on code/modules/item_worth/reagents.dm
> +	value = 3.5
Ладно, хуйню здесь сделал.

2020-11-14 12:47 UTC, kcalbCube commented
А надо?

2020-11-14 12:49 UTC, kcalbCube commented on code/modules/item_worth/reagents.dm
> +	value = 3.5
Как убрать 🤔🤔🤔

2020-11-14 12:57 UTC, kcalbCube commented on code/modules/item_worth/reagents.dm
> +	value = 3.5
Удалил

2020-11-14 12:59 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +		owner.custom_pain("Your feel a lot of pain.", 40)
т.е. за один тик космонавтик с 50+ дамага в мозге может с определённым шансом получить в чат
Your feel pain.
Your feel strong pain.
Your feel a lot of pain.
Одновременно. "Your feel". Без индикации, что болит именно голова.

2020-11-14 13:01 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	M.add_chemical_effect(CE_BREATHLOSS, 2)
Зачем обычному передозу никотином удушение на уровне героина с водкой?

2020-11-14 13:04 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	description = "Psyloxon is a antiepileptical drug. Stabilizes brain activity."
name = "Calciumxon"
description = "Psyloxon is a antiepileptical drug.

2020-11-14 13:07 UTC, TobyThorne commented on code/modules/surgery/surgery.dm
>  	var/list/disallowed_species = null
allowed_species удалил
@ 
disallowed_species оставил на память

2020-11-14 13:11 UTC, TobyThorne commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +	update_icon()
🚫

2020-11-14 13:11 UTC, kcalbCube commented on code/modules/surgery/surgery.dm
>  	var/list/disallowed_species = null
Какой то баг. Наверное ctrl z лишний раз нажал

2020-11-14 13:12 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +			E.update_damstate()
Как это вообще в теории должно убрать перелом?

2020-11-14 13:14 UTC, kcalbCube commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +			E.update_damstate()
Перелом реализован как сломанный орган с пометкой о том что это перелом. Орган лечится и пометка обновляется - перелом уходит.

2020-11-14 13:15 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	M.add_chemical_effect(CE_BREATHLOSS, 10)
Замедление до уровня статичного объекта и мгновенные десятки оксидамага с передоза. Нашли новую хлорку на максималках.

2020-11-14 13:16 UTC, kcalbCube commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	M.add_chemical_effect(CE_BREATHLOSS, 2)
Ну, в жизни если ты покурил восемь пачек то удушье точно появится

2020-11-14 13:17 UTC, kcalbCube commented on code/modules/organs/internal/brain.dm
> +		owner.custom_pain("Your feel a lot of pain.", 40)
Болит не голова, болит случайная часть тела

2020-11-14 13:18 UTC, kcalbCube commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	M.add_chemical_effect(CE_BREATHLOSS, 10)
Окей, повышу шанс на развитие депрессии и уберу это.

2020-11-14 13:23 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +				to_chat(owner, SPAN_WARNING("[pick("You feel a sad", "You lost", "Where has happiness gone?")]"))
a sad


bashar

2020-11-14 13:44 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +	if(get_activity() <= 30 && prob(1) && owner.get_active_hand())
Десять миллиардов вызовов get_activity у каждого человечка каждый тик. Выглядит надёжно.

2020-11-14 13:45 UTC, TobyThorne requested changes
Короче, ставлю на то, что это вообще не тестилось.

2020-11-14 13:47 UTC, TobyThorne commented
> #3691
> Я предлагаю добавить автору пула решение на это предложение

С такими идеями больше не приходи, пожалуйста.

2020-11-14 13:59 UTC, kcalbCube commented
> Короче, ставлю на то, что это вообще не тестилось.

Ну, я долго тестировал (7 часов наберётся) такая себе в view variables различные варианты. Это не считается?

2020-11-22 02:01 UTC, kcalbCube commented
Проиграл не тот кто упал, проиграл тот кто не поднялся. @TobyThorne ready for review

2020-11-23 10:24 UTC, Destrolaric commented
Here we go again

2020-11-23 12:36 UTC, kcalbCube commented
@TobyThorne жду разьеба по коду, уже джва дня.

2020-11-23 12:48 UTC, TobyThorne commented on code/modules/mob/living/carbon/carbon.dm
> +	src.internal_organs_by_name[BP_BRAIN].relative_activity += activity
зачем 'src.'

2020-11-23 12:49 UTC, TobyThorne commented on code/modules/mob/living/carbon/life.dm
> +			H.handle_psychiatry()
зачем это в life карбонов с проверкой, когда можно просто засунуть в life хуманов

2020-11-23 12:50 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +#define DISABILITY_GIVE_DELAY 2*60*10
магические цыферки

2020-11-23 12:51 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +// in procents
что такое procents

2020-11-23 12:53 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +	icon 	   = 'icons/mob/alien.dmi'
что это вообще такое

2020-11-23 12:54 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +	min_broken_damage  = max_damage*0.75
шо за пробел

2020-11-23 12:57 UTC, TobyThorne commented on code/modules/organs/internal/brain.dm
> +						to_chat(owner, SPAN_WARNING("You feel [pick("dizzy","woozy","faint")]..."))
сейчас бы менять нормальные макросы на эту укрохуйню

2020-11-23 13:01 UTC, kcalbCube commented on code/modules/organs/internal/brain.dm
> +						to_chat(owner, SPAN_WARNING("You feel [pick("dizzy","woozy","faint")]..."))
??? Чем плох SPAN_WARNING?

2020-11-23 13:11 UTC, 4310V343k commented on code/modules/organs/internal/brain.dm
> +	icon 	   = 'icons/mob/alien.dmi'
Везде так. Я уже вроде проходился по этому пиздецу

2020-11-23 13:30 UTC, TobyThorne commented
В хер всё это, короче. Проверю код целиком, если остальные геймдизы аппрувнут. Я голосую против (по крайней мере, в том состоянии, в котором оно находится в данный момент), ибо:
- Усложнения ради усложнений. Медбей в каждом первом раунде и так напоминает рынок в чёрную пятницу.
- Из расстройств хоть какой-то интерес для геймплея представляет разве что шизофрения. Если бы добавил ещё что-то смешное вроде туретта, нарушений речи, каких-нибудь тиков с рандомным выбрасыванием удерживаемого предмета, телепатию/разговоры с призраками (с мизерным шансом, ессесна) и всякого прочего, что хоть как-то влияет на раунд - я бы, наверое, аппрувал не глядя. Но выборка из галюнов, рандомных убивающих станов и спама в чатике - какая-то хуйня из-под коня.
- Расстройства должны даваться хотя бы с каким-то шансом, а не гарантированно. Желательно - чтоб меньше 1:1. А то любое ЧП - и станция полна шизиков.
- Должен быть способ перманентно лечить расстройства. Какие-нибудь мозговые импланты из РнД, артефакты с шахты, вытяжки из малиновых в крапинку слаймов (хоть для чего-то были бы нужны), отвары из форона, мухоморов и мочи розовой таяры. 26 век, ёптыть.
- Огромная куча разношёрстных изменений в ПРе. Тот же душащий покруче петли передоз никотином - это хуерга какая-то. Или реагент, который должен лечить кости. Те же кости надо отдельно реворкать, а не приделывать к ним нерабочий костыль (иронично, однако).

2020-11-23 21:46 UTC, kcalbCube commented
Вас понял.

2020-11-24 13:55 UTC, Destrolaric commented
![AAAc2iwZy6ib7ssty5IB-SjFqcBXmcr7i5jgIlx4cWCILiEQivqYiUFlRrqwreV4hhueHtkGrU6ghf0XLDK51YRp-24](https://user-images.githubusercontent.com/20579256/100103386-e13f3780-2e75-11eb-83d0-79550f1d54d5.jpg)
ПР не болей

2020-11-25 12:16 UTC, kcalbCube commented
> ![AAAc2iwZy6ib7ssty5IB-SjFqcBXmcr7i5jgIlx4cWCILiEQivqYiUFlRrqwreV4hhueHtkGrU6ghf0XLDK51YRp-24](https://user-images.githubusercontent.com/20579256/100103386-e13f3780-2e75-11eb-83d0-79550f1d54d5.jpg)
> ПР не болей
> 

Приложу через 7 часов, вдруг поможет.

2020-12-02 08:59 UTC, YouBro commented
Слишком много лишних нововведений. Не трогай медицину.

2020-12-05 23:34 UTC, kcalbCube commented
Исходный код был случайно удален. Нужна реорганизация.

2020-12-05 23:34 UTC, closed without merging

2020-12-06 17:07 UTC, Destrolaric commented
lol

2021-05-16 12:09 UTC, kcalbCube commented
жалко девочку.

2021-09-06 08:06 UTC, kcalbCube commented
@Doster-d 
> > ты чё еблан, нахуя ты мыслишь уже той самой знакомой с лысым из бразерс
> 
> Чё? Понял хоть сам что сказал?
> 
> > все эти правила они абстрактные, они создают представление про идеальный код.
> 
> Ну да, и мой код не нарушает эти правила.
> 
> > любая лишняя вложенность это +1 символ на строку, и -4 символа к пространству для просмотра, редактирования и написания кода.
> 
> Ты читать умеешь? Где ебать эта хуйня мешает тебе редактировать/просматривать говнокод, если там ебать ВСЕГО ОДНА ВЛОЖЕННОСТЬ НА ИФЕ?!
> 
> > а по поводу комментариев... ты мне говорил что комментарий урод, что он из детдома с лошадимым рылом, и вообще оникс девелопер, а теперь включаешь заднюю. так не делается
> 
> Ты еблан, мне было бы абсолютно похуй на комментарии, хоть ты бы писал их арабскими символами, если бы это не было бы в провер очках.
> 
> Если тебе это не нравится, го энд билд юр гейм оф зе дрим виз гитхаб рулез оф зе дрим.

ты хочешь сказать что ты заменял собой работу какой то там машины, и не представлял более никакой ценности?

2021-12-28 01:08 UTC, kcalbCube commented
так у нас есть флешка с потерянными сорсами, покс которого не существует, две тысячи терминов, экспонента от минус пи, убивающий за полчаса порез от бумаги, тридцать видов наркотиков, тромб пятки, спидран по остановке жопы в сердце.
этого больше нет на ониксе и я прошу выдать семибоярщине временный разбан что бы мы смогли увидится со старыми друзьяшками

2021-12-28 01:18 UTC, Doster-d commented
Вы ошиблись репой, пожалуйста, не пишите сюда больше, от вас спиртом воняет :)

2021-12-28 02:10 UTC, DarkHunter7756 commented
Тридцать видов наркотиков даже я не против увидеть 😼

2022-01-06 08:08 UTC, kcalbCube commented
> Тридцать видов наркотиков даже я не против увидеть smirk_cat

ты мое приглашение отклонил

2022-03-11 20:23 UTC, kcalbCubeFork commented
я бросил, в том числе кринж парады, хочу исполнить долг перед обществом. подскажите что вам нужно накодить.

2022-03-11 21:59 UTC, Doster-d commented
> я бросил, в том числе кринж парады, хочу исполнить долг перед обществом. подскажите что вам нужно накодить.

"Я наплевал вам в колодец, Вы закрыли от меня колодец, и я прошу дать мне снова подойти к колодцу"

2022-03-11 22:12 UTC, kcalbCubeFork commented
> > я бросил, в том числе кринж парады, хочу исполнить долг перед обществом. подскажите что вам нужно накодить.
> 
> "Я наплевал вам в колодец, Вы закрыли от меня колодец, и я прошу дать мне снова подойти к колодцу"

на твоем месте я бы так не говорил, я ведь знаю что ты есть на кубоконфе, я сам тебя пригласил.
кстати не закрыли мне колодец, мне нужно чем-то закрыть появившиеся пробелы в жизни.

2022-03-12 06:59 UTC, Doster-d commented
Ой, ой, ой, я потеряю доступ к конфе человека, который плюет в колодцы, как это жалко! Неужели мне надо вести диалог с автором ВЕЛИКОЙ кубомедициной как с МУЗОЙ?!
А что ты тогда с мультиакка сидишь, дорогой, если тебе не закрыли доступ к нашему колодцу?
Говоришь ты нормально, только ты не понимаешь, что ты тут юродивый для всех из-за твоих действий в прошлом, и это тебе, вероятно, никогда не забудут.

Хочешь попытаться изменить такое отношения? Фикси баги. Причем много тебе надо будет пофиксить, чтобы ты хотя бы стал рукопожатым.

2022-03-12 07:49 UTC, kcalbCubeFork commented
Достер, всё будет хорошо.

2022-03-12 07:50 UTC, No-Tips commented
Впили реплеи и мы в расчете

2022-03-12 08:25 UTC, Zert0X commented
> Впили реплеи и мы в расчете

так курва, не трогать мой хлеб

2022-03-12 08:49 UTC, Nod404 commented
> Говоришь ты нормально, только ты не понимаешь, что ты тут юродивый для всех из-за твоих действий в прошлом

я люблю куба

2022-03-12 10:52 UTC, NefrNerf commented
Если хочешь помогать, то окей, из большого:
Культ, портировать часовщиков или лучше допилить наш до адекватного (портировать и почистить)
Вампиры, допилить до нормального состояние(сделать их неживыми и так далее)
Можешь какого антага на мидгейм портануть, а так баги всегда есть.

2022-03-12 11:21 UTC, kcalbCubeFork commented
> Если хочешь помогать, то окей, из большого: Культ, портировать часовщиков или лучше допилить наш до адекватного (портировать и почистить) Вампиры, допилить до нормального состояние(сделать их неживыми и так далее) Можешь какого антага на мидгейм портануть, а так баги всегда есть.

подожду разработчиков.

2022-03-12 11:24 UTC, Zert0X commented
> > Если хочешь помогать, то окей, из большого: Культ, портировать часовщиков или лучше допилить наш до адекватного (портировать и почистить) Вампиры, допилить до нормального состояние(сделать их неживыми и так далее) Можешь какого антага на мидгейм портануть, а так баги всегда есть.
> 
> подожду разработчиков.

А чё нас ждать? Вкладочка иссуи с гитхаба никуда не пропала.

2022-03-12 11:25 UTC, Zert0X commented
> Вампиры, допилить до нормального состояние(сделать их неживыми и так далее)
Where is issue?!

2022-03-12 11:30 UTC, kcalbCubeFork commented
> > > Если хочешь помогать, то окей, из большого: Культ, портировать часовщиков или лучше допилить наш до адекватного (портировать и почистить) Вампиры, допилить до нормального состояние(сделать их неживыми и так далее) Можешь какого антага на мидгейм портануть, а так баги всегда есть.
> > 
> > 
> > подожду разработчиков.
> 
> А чё нас ждать? Вкладочка иссуи с гитхаба никуда не пропала.

будто ты не знаешь что я имею в виду.

2022-03-12 12:16 UTC, TobyThorne commented
хули вы тут чатик устроили