Shield update
ChaoticOnyx/OnyxBay pull request #3722
Opened 2020-11-10 16:18 UTC by Destrolaric

На данный момент реализовал рабочий дамаг по щиту, ауру взял от другого предмета, предварительно модифицировав. 
Есть два предмета Experemental shield belt и Syndicate shield belt. Отличие на данный момент не доделано, заключается в возможности регена заряда последнего. Первый доступен в РНД, второй через аплинк. 
Что не реализовано и требует помощи:
- Спрайты щитов, требуется для включенного, выключенного. А также для экспериментального необходимо добавить разобранность(вынутую батарейку)
Что не реализовано и пока не требует помощи:
- Блок стрельбы игрока из под щита
- Реген щита 
- Вынимание и вставление батарейку пока не завершено

close #3696
- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-10 17:50 UTC, MrMagick2104 commented
На бейстейшоне же есть [персональные щиты](https://github.com/Baystation12/Baystation12/blob/dev/code/game/objects/items/devices/personal_shield.dm), можно оттуда покопипастить или спрайты взять, по надобности.

2020-11-10 20:13 UTC, Destrolaric commented
Обновление, добавлена регенерация щита, замена батарейки. На данный момент не хватает ограничения на невозможность использования, если не надет(в руках). И ограничения стрельбы. Иконки с бея я посмотрел, они не подходят под тему пояса + там нужно два вида

2020-11-10 21:55 UTC, Destrolaric commented
Вопрос, я пытался найти способ реализовать то, что ты не можешь выпускать projectile, если у тебя включен щит. Но подобного функционала не нашёл, есть идеи?

2020-11-11 11:21 UTC, MrMagick2104 commented
> Вопрос, я пытался найти способ реализовать то, что ты не можешь выпускать projectile, если у тебя включен щит. Но подобного функционала не нашёл, есть идеи?

Может, удалять прожектайл при выстреле с включённым щитом, нанося урон по ХП щита соответственно дамагу прожектайла?
> Иконки с бея я посмотрел, они не подходят под тему пояса + там нужно два вида

Спроси ```@artist ``` в конфе дискорда

2020-11-12 06:31 UTC, Destrolaric commented
Добавлен весь функционал, кроме спрайтов. Мне бы помощь с ними

2020-11-13 12:38 UTC, Destrolaric commented
Закинул иконки,  написал комментарии к основному коду. Жду предложения по балансу и минорными изменениям. Реквест открыт для мёрджа

2020-11-13 17:59 UTC, kreeperHLC requested changes
Такое чувство, что тебе пробелов недодали. Поставь везде где забыл, пробельный еврей.

2020-11-13 17:59 UTC, kreeperHLC commented on code/datums/uplink/highly_visible_and_dangerous_weapons.dm
>  /datum/uplink_item/item/badassery/money_cannon
Это такая шутка что пустых строк нет иль просто забаговался гит?

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
>  	return ..()
Строка в конце файла

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src,/obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
Зачем эта огромная куча проверок, когда можно сделать переменную base_sprite и с помощью неё апдейтить? "[base_sprite]_on", "[base_sprite]_off" и т.д.

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		if (current_power > 300&&!shield)
> 300&&!shield

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			current_power-=300
> power-=300

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(user.get_inventory_slot(src)== slot_belt)
> slot(src)== slot_belt

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	current_power=current_power-P.damage*10
> current_power=current_power-P.damage*10

2020-11-13 17:59 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		if(bcell.checked_use(current_power-P.damage*10))
> bcell.checked_use(current_power-P.damage*10))

2020-11-13 18:21 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src,/obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
Так там 8 различных спрайтов, поэтому и выглядит раздутым

2020-11-13 18:24 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	bcell = /obj/item/weapon/cell/high
У щита учёных до тонны дебафов, чтобы это компенсить. Щит синдиката батарейку всегда имеет Null

2020-11-13 18:26 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src,/obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
Не отменяет того, что вместо дополнительных проверок на синдикатский и ученый тип можно было просто через base_sprite слепить

2020-11-13 18:27 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	bcell = /obj/item/weapon/cell/high
Можно будет эту батарейку так фармить, я про это. Уверен, что она ещё и заряженная там

2020-11-13 18:31 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	bcell = /obj/item/weapon/cell/high
Он стоит как чёртов вортекс, а батарейка там самая помойная на 1000

2020-11-13 18:36 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src,/obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
Тут вопрос память или процессорное время. Проверка типа не очень дорогая операция

2020-11-13 18:40 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	bcell = /obj/item/weapon/cell/high
У нас целый ПР был насчет того, чтобы батарейки изготавливались разряженными, так что думаю пусть спавнится пустым.

2020-11-13 18:41 UTC, kreeperHLC requested changes
Уже лучше, но не до конца

2020-11-13 18:41 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			current_power-=300
Ммм, хорошо пофиксил

2020-11-13 18:41 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		if (current_power > 300&&!shield)
Аналогично и тут

2020-11-13 18:41 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	current_power = current_power-P.damage * 10
current_power-P.damage

2020-11-13 18:42 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
> +/obj/aura/shields/New(mob/living/user)
Тут бы строками тоже отделить кстати

2020-11-13 19:25 UTC, kreeperHLC requested changes
Исправляй. Опять

2020-11-13 19:25 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
> +	..()
Пустые строки где?

2020-11-13 19:25 UTC, kreeperHLC commented on code/modules/research/designs/protolathe/dp-weapons.dm
>  /datum/design/item/weapon/anti_photon
Пустые строки

2020-11-13 20:41 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	item_state="utility"
Пробел

2020-11-13 20:42 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src,/obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
src,/obj

2020-11-13 20:43 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			switch(round(bcell.charge/bcell.maxcharge * 100))
charge/bcell

2020-11-13 20:43 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +				if(bcell.charge<300)
(bcell.charge<300

2020-11-13 20:44 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +					icon_state="science_shield_belt_empty"
te="sc

2020-11-13 20:44 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	shield = new(user,src)
user,src)

2020-11-13 20:44 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +/obj/item/weapon/shield/shield_belt/dropped(var/mob/user)
Может я конечно чего-то не знаю, но зачем тут var/mob/user?

2020-11-13 20:45 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +/obj/item/weapon/shield/shield_belt/equipped(var/mov/user,var/slot)
user,var

2020-11-13 20:46 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			turn_off()
Может сначала отключать, а потом уже дропать батарейку?

2020-11-13 20:50 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(current_power < 0)
А если равно нулю, то он без сообщения сдохнет, не? Если вообще сдохнет.

2020-11-13 20:50 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		to_chat(loc,SPAN_DANGER("The [src] begins to spark as it turns off!</span>"))
loc,SPAN

2020-11-13 20:50 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			to_chat(loc,SPAN_DANGER("The [src] begins to spark as it turns off!"))
loc,SPAN_

2020-11-13 20:51 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	current_power=max(current_power / (2 * severity), max_power/(4 * severity))
Пробелы пробельчики

2020-11-13 20:51 UTC, kreeperHLC commented on code/modules/projectiles/projectile.dm
> +		if (istype(O,/obj/aura/shields/shield_belt))
O,/obj

2020-11-13 20:51 UTC, kreeperHLC commented on code/modules/projectiles/projectile.dm
> +/obj/item/projectile/proc/launch_from_gun(atom/target, mob/living/user, obj/item/weapon/gun/launcher, target_zone, x_offset=0, y_offset=0)
x_offset=0, y_offset=0

2020-11-13 20:51 UTC, kreeperHLC commented on code/modules/research/designs/protolathe/dp-weapons.dm
> +	req_tech= list(TECH_MATERIAL = 4, TECH_MAGNET = 6, TECH_POWER = 5,TECH_COMBAT = 5)
5,TECH

2020-11-13 20:52 UTC, kreeperHLC commented on code/modules/research/designs/protolathe/dp-weapons.dm
> +	materials = list(MATERIAL_STEEL = 5000, MATERIAL_GLASS = 2000, MATERIAL_GOLD = 750,MATERIAL_URANIUM = 750, MATERIAL_DIAMOND = 1500)
750,MATERIAL

2020-11-13 21:32 UTC, kreeperHLC requested changes

2020-11-13 21:32 UTC, kreeperHLC commented on code/game/objects/items/devices/personal_shield.dm
> +		to_chat(loc,SPAN_DANGER("\The [src] begins to spark as it breaks"))
loc,SPAN

2020-11-13 21:32 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src,/obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
Всё ещё не исправил

2020-11-13 21:32 UTC, kreeperHLC commented on code/modules/projectiles/projectile.dm
> +/obj/item/projectile/proc/launch_from_gun(atom/target, mob/living/user, obj/item/weapon/gun/launcher, target_zone, x_offset=0, y_offset=0)
Не исправлено

2020-11-13 22:11 UTC, kreeperHLC requested changes

2020-11-13 22:11 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
> +	to_chat(user,SPAN_NOTICE("You feel your body prickle as \the [src] comes online."))
Вот

2020-11-15 21:03 UTC, kreeperHLC requested changes
Ты конечно прости меня, но....

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			to_chat(loc,SPAN_DANGER("The [src] has no energy!"))
>to_chat(loc,SPAN

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		to_chat(loc,SPAN_DANGER("\The [src] must be weared at belt to be used"))
>to_chat(loc,SPAN

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +				to_chat(loc,SPAN_DANGER("The [src] has no energy!"))
>to_chat(loc,SPAN

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			to_chat(loc,SPAN_DANGER("\The [src] has no battery!"))
>to_chat(loc,SPAN

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		to_chat(loc,SPAN_DANGER("\The [src] must be weared at belt to be used"))
>to_chat(loc,SPAN

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	current_power=max(current_power / (2 * severity), max_power / (4 * severity))
>power=max

2020-11-15 21:03 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +//BOOM
Бесполезный коммент

2020-11-18 12:20 UTC, TatarTheBuilder commented
Потестил на локалке, думал что будет хуже. 

Первое - описание хуйни при экзамине в стремном порядке.
![Screenshot_10](https://user-images.githubusercontent.com/51989098/99529026-d5500300-29a7-11eb-9947-c7a39aa2b3b3.png)
Очевидно, что сначала должно идти описание предмета, и потом уже заряд и прочее.

Синдищит держит семь выстрелов из лазкарабина, восьмой уже проходит по телу, и 13 дробинок из мехдробовика - т.е. три залпа, и одну дробинку из четвертого.
РнДщит с адвансет и супириор батарейками держит один выстрел лазкарабина, с максимальной батарейкой - 2, с блюспейс - 5. Броски не блочит, удары тоже. Более-менее нормально.

Можно выключать щит, стрелять, и вновь включать, такое себе, лучше впили делей на включение/выключение.
В РнДщите еще на ходу можно менять батарейки, для смены достаточно всего два клика, лучше тоже впилить делей.

2020-11-18 13:55 UTC, jammer312 requested changes
Некорректно доопределяешь экзамайн. Глянул бы хотя бы, как у других предметов сделано

2020-11-18 13:55 UTC, jammer312 commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	to_chat(user, "The internal capacitor currently has [round(current_power/max_power * 100)]% charge.")
Убейся ап стену

2020-11-18 13:55 UTC, jammer312 commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		to_chat(user, "There is \a [bcell] in \the [src].")
Здесь и ниже тоже

2020-11-18 14:02 UTC, jammer312 commented
На случай, если неочевидно, экзамайны теперь собирают весь вывод в строку, и единожды отсылают ее чату. Ты же отдельно выводишь чат каждый кусок описания, причем до того, как результат экзамайна используется. В частности, из-за этого у тебя кривой порядок вывода, на который тебе указал татарин

2020-11-18 14:56 UTC, Destrolaric commented
> Потестил на локалке, думал что будет хуже.
> 
> Первое - описание хуйни при экзамине в стремном порядке.
> ![Screenshot_10](https://user-images.githubusercontent.com/51989098/99529026-d5500300-29a7-11eb-9947-c7a39aa2b3b3.png)
> Очевидно, что сначала должно идти описание предмета, и потом уже заряд и прочее.
> 
> Синдищит держит семь выстрелов из лазкарабина, восьмой уже проходит по телу, и 13 дробинок из мехдробовика - т.е. три залпа, и одну дробинку из четвертого.
> РнДщит с адвансет и супириор батарейками держит один выстрел лазкарабина, с максимальной батарейкой - 2, с блюспейс - 5. Броски не блочит, удары тоже. Более-менее нормально.
> 
> Можно выключать щит, стрелять, и вновь включать, такое себе, лучше впили делей на включение/выключение.
> В РнДщите еще на ходу можно менять батарейки, для смены достаточно всего два клика, лучше тоже впилить делей.
> 
> Не совсем понял, почему в аплинке щит называется "СТРАННЫЙ поясной щит", это же аплинк, лучше заменить "strange" на какое-нибудь "combat", а у самого предмета уже пусть будет странный.

Звучит так, что достаточно одного делея - На включение. Касательно того, почему синдищит танканул настолько много, как тестил? Множеством выстрелов одновременно или стрелял с определённым промежутком? С экзамином разберусь в пятницу

2020-11-18 18:08 UTC, MrMagick2104 commented
> В РнДщите еще на ходу можно менять батарейки, для смены достаточно всего два клика, лучше тоже впилить делей.

Можно было бы сделать вынимание с использованием отвёртки, так как у нас 80% предметов требуют её для изъятия батарейки.

2020-11-18 18:25 UTC, TatarTheBuilder commented
> Можно было бы сделать вынимание с использованием отвёртки

Оно отверткой и вынимается.

2020-11-23 09:54 UTC, Destrolaric commented
@TatarTheBuilder Отредачил, теперь есть sleep(20) при попытке включить пояс, examine отрефакторил, теперь красиво. взрыв от эми решил оставить, ибо не отрубить щит увидя, что у сбшника эми винтовка/пистолет косяк игрока.

2020-11-24 15:17 UTC, kreeperHLC submitted a review, later dismissed
Ну, если не считать беды с пробелами, всё даже выглядит нормально

2020-11-25 05:14 UTC, sweden-moose approved these changes

2020-11-29 11:04 UTC, TatarTheBuilder commented
По ощущениям от локалки каким-то оверпаверд говном оно совсем не ощущается, я бы даже сказал, что где-то на грани между ситуативным и тратой очков, но тазеры танчит и ладно, в случае чего можно будет подкрутить цифры. Помимо смешного гиба юзера претензий по геймдизайну у меня нет.

2020-11-30 10:55 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	attack_verb = "Bashed"
почему аттак_верб с заглавной буквы и вообще не лист

2020-11-30 10:57 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if (shield)
пробел

2020-11-30 10:58 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src, /obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
до сих пор почему в общем update_icon_state() обрабатываются оба наследника
что мешает сделать раздельные процессы для обоих чтобы в будущем ничего не поломалось к херам

2020-11-30 10:59 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	usr.update_inv_belt()
откуда тут вообще берётся usr, если в аргументы функции он не передаётся

2020-11-30 10:59 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +/obj/item/weapon/shield/shield_belt/equipped(var/mov/user, var/slot)
var/mo**v**/user

2020-11-30 11:01 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +obj/item/weapon/shield/shield_belt/experimental_shield_belt/get_mob_overlay(mob/user_mob, slot)
почему вообще функции наследников experimental_shield_belt и syndicate_shield_belt находятся под родителем, а не под ними самими

2020-11-30 11:01 UTC, Epicus7 commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	usr.update_inv_belt()
usr, как и src - встроенная переменная бьонда, которая есть во всех проках и ссылается на моба-юзера прока.

Если прок вызывается из какого-нибудь таймера (без юзера соответственно), то тут будет рантайм. Поэтому в проках лучше не использовать usr, а явно передавать user. Странно, что этого нет в контрибутинг гайде, надо добавить.

2020-11-30 11:01 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +/obj/item/weapon/shield/shield_belt/syndicate_shield_belt
зачем вообще такие анальные пути с shield_belt/syndicate_shield_belt и shield_belt/experimental_shield_belt
почему не shield_belt/syndicate и shield_belt/experimental

2020-11-30 11:02 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	bcell = /obj/item/weapon/cell/high/empty
почему он по умолчанию с батарейкой

2020-11-30 11:04 UTC, TobyThorne commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		bcell.emp_act(severity)
неиронично сначала батарейка может удалиться, ибо удаляется щит, а потом у неё будут вызывать emp_act()
то же самое с самим щитом, у которого после удаления дёргают update_icon_state()
где return, лебовски?

2020-11-30 11:05 UTC, TobyThorne commented on code/modules/projectiles/projectile.dm
> +		if (istype(O, /obj/aura/shields/shield_belt))
пробелы in your area

2020-11-30 11:05 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	usr.update_inv_belt()
usr, не передаётся через функции, а по своей сути тот, кто вызвал. Хотел в своё время добавить в функцию /mob/user но понял, что там обьём рефактора слишком велик

2020-11-30 11:06 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +obj/item/weapon/shield/shield_belt/experimental_shield_belt/get_mob_overlay(mob/user_mob, slot)
Ибо не пришло в голову -__-

2020-11-30 11:07 UTC, TobyThorne commented
А ещё нет никакой индикации, что юзер использует щит. В том же Римворлде вокруг пользователя появляется здоровенный пузырь, чем и объясняется невозможность стрелять. 
![image](https://user-images.githubusercontent.com/45202681/100602739-80f53d80-332e-11eb-9373-94c4ff9c3510.png)

2020-11-30 11:07 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	bcell = /obj/item/weapon/cell/high/empty
Ибо,
 1) Она разряжена
 2)Почему бы и нет?

2020-11-30 11:08 UTC, Destrolaric commented on code/modules/projectiles/projectile.dm
> +		if (istype(O, /obj/aura/shields/shield_belt))
Я уже с голиафом пытался это форматить, всегда находятся новые косяки с пробелами

2020-11-30 11:08 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +/obj/item/weapon/shield/shield_belt/syndicate_shield_belt
Не пришло в голову раньше, лениво рефакторить теперь

2020-11-30 11:16 UTC, Destrolaric commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if(istype(src, /obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
```
/obj/item/weapon/shield/shield_belt/proc/turn_on(var/mob/user)
	shield = new(user, src)
	update_icon_state()
```
Причина, вызывается из функции родителя

2020-11-30 11:19 UTC, kreeperHLC commented
> А ещё нет никакой индикации, что юзер использует щит. В том же Римворлде вокруг пользователя появляется здоровенный пузырь, чем и объясняется невозможность стрелять.

Там же оверлей щита появляется, нет?

2020-11-30 20:29 UTC, kreeperHLC requested changes
Братишка, я тебе покушать принёс.

2020-11-30 20:29 UTC, kreeperHLC commented on code/modules/research/designs/protolathe/dp-weapons.dm
> +	req_tech= list(TECH_MATERIAL = 4, TECH_MAGNET = 6, TECH_POWER = 5, TECH_COMBAT = 5)
```suggestion
	req_tech = list(TECH_MATERIAL = 4, TECH_MAGNET = 6, TECH_POWER = 5, TECH_COMBAT = 5)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/modules/projectiles/projectile.dm
> +		if (istype(O, /obj/aura/shields/shield_belt))
```suggestion
	for(var/obj/O in user.get_auras())
		if(istype(O, /obj/aura/shields/shield_belt))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			to_chat(loc,SPAN_DANGER("\The [src] must be weared at belt to be used"))
```suggestion
			to_chat(loc, SPAN_DANGER("\The [src] must be weared at belt to be used"))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +				to_chat(loc,SPAN_DANGER("\The [src] has no battery!"))
```suggestion
				to_chat(loc, SPAN_DANGER("\The [src] has no battery!"))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +					to_chat(loc,SPAN_DANGER("The [src] has no energy!"))
```suggestion
					to_chat(loc, SPAN_DANGER("The [src] has no energy!"))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +				if (!shield && bcell.checked_use(300))
```suggestion
				if(!shield && bcell.checked_use(300))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		to_chat(loc,SPAN_NOTICE("The [user] touches the button on belt!"))
```suggestion
		to_chat(loc, SPAN_NOTICE("The [user] touches the button on belt!"))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	current_power=max(current_power / (2 * severity), max_power / (4 * severity))
```suggestion
	current_power = max(current_power / (2 * severity), max_power / (4 * severity))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if (!shield)
```suggestion
	if(!shield)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			to_chat(loc,SPAN_DANGER("\The [src] must be weared at belt to be used"))
```suggestion
			to_chat(loc, SPAN_DANGER("\The [src] must be weared at belt to be used"))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +				to_chat(loc,SPAN_DANGER("The [src] has no energy!"))
```suggestion
				to_chat(loc, SPAN_DANGER("The [src] has no energy!"))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +			if (current_power > 300 && !shield)
```suggestion
			if(current_power > 300 && !shield)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if (not_being_turned)
```suggestion
	if(not_being_turned)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if (shield)
```suggestion
	if(shield)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +	if (istype(src, /obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
```suggestion
	if(istype(src, /obj/item/weapon/shield/shield_belt/syndicate_shield_belt))
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
> +	playsound(user, 'sound/mecha/internaldmgalarm.ogg',25,1)
```suggestion
	playsound(user, 'sound/mecha/internaldmgalarm.ogg', 25, 1)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
> +	playsound(user, 'sound/effects/basscannon.ogg',35,1)
```suggestion
	playsound(user, 'sound/effects/basscannon.ogg', 35, 1)
```

2020-11-30 20:29 UTC, kreeperHLC commented on code/game/objects/auras/personal_shields/personal_shield.dm
>  	playsound(user,'sound/weapons/flash.ogg',35,1)
```suggestion
	playsound(user,'sound/weapons/flash.ogg', 35, 1)
```

2021-01-08 18:55 UTC, Destrolaric commented
Добавил бубль, больше не буду рисовать пиксельарт
**Помогите**

2021-01-11 18:51 UTC, Destrolaric commented
# Я ПРИЗЫВАЮ ГЕЙМДИЗАЙНЕРОВ ПРИДИТИТЕ И НАСЛАДИТЕСЬ!

2021-01-11 19:07 UTC, Doster-d commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		sleep(20)
![image](https://user-images.githubusercontent.com/63081538/104226615-27b61900-5459-11eb-9d44-d6b1d35cc2af.png)
Пожалуйста, сделай на таймерах,

2021-01-11 19:09 UTC, Doster-d commented on code/game/objects/items/weapons/shield/shield_belt.dm
> +		sleep(20)
У тебя есть схожий код в еще одном месте, может переделаешь то, что ниже в proc?

2021-01-11 20:27 UTC, Doster-d commented
Спрайты кукож.

2021-01-29 10:13 UTC, Destrolaric commented
Конфликт на поясе, кто его менял?

2021-01-29 21:26 UTC, Shootnik01 commented
Wait, was it always Rimworld?

2021-01-29 21:26 UTC, Shootnik01 commented
Always has been

2021-02-08 06:39 UTC, Destrolaric commented
У меня предложение, я убираю убогий спрайт анимации щита, принимаем пулл. И когда уже докинут хороший dmi с анимацией я вставлю её. А то обед по этому пулреквесту продолжается слишком долго.

2021-02-26 19:08 UTC, kreeperHLC approved these changes

2021-03-06 08:41 UTC, kreeperHLC approved these changes

2021-04-07 09:30 UTC, MrPersival commented
Брат, держись, вместе мы победим разработОЧКУ.

2021-04-17 05:51 UTC, TobyThorne commented
Долгое время висит с конфликтами, пока что закрываю. Если автор оживёт - пусть переоткроет/слапнет в дискорде.

2021-04-17 05:51 UTC, closed without merging