tweak(cooking): батин суп
ChaoticOnyx/OnyxBay pull request #3744
Opened 2020-11-15 20:26 UTC by Animesku

Добавляет рецепт батиного супа. В нем содержится немного термита, который легко можно достать. Даст возможность поварам при должном старании сделать себе достаточно термита и разварить какую-нибудь стенку.

![image](https://user-images.githubusercontent.com/48406301/99195940-05c25200-279a-11eb-9aa1-b5328f921951.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-15 20:46 UTC, kreeperHLC requested changes
Исправляй

2020-11-15 20:46 UTC, kreeperHLC commented on code/game/objects/items/trash.dm
> +
Пробел лишний

2020-11-15 20:46 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	New()
/obj/item/weapon/reagent_containers/food/snacks/fathersoup/New() чтобы полностью прописать путь и не быть дауном. + вместо New() используй Initialize()

2020-11-15 20:48 UTC, kreeperHLC commented
А сковородка среди мусора спавнится?

2020-11-16 02:18 UTC, TobyThorne commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Hell's dish"
Точку забыл. Да и вообще "hell's dish" sounds kinda off. Лучше что-то вроде "Hellish meal.", "Forbidden soup.", "Ooh, blyad...", etc.

2020-11-16 02:23 UTC, TobyThorne commented
От мемности обои с репозитория поотклеивались.
Но, в принципе, у нас есть мутация чили, которая содержит топливо. Вот такой перчик бы в рецепт добавить и можно будет аппрувать.

2020-11-16 05:59 UTC, Animesku commented
Все, что хотели, выполнил.

2020-11-16 06:08 UTC, TobyThorne commented
В code\modules\hydroponics\seed_datums.dm надо добавить kitchen_tag = "flamechili" на 43 строку шоб работало.

2020-11-16 12:41 UTC, Animesku commented
Все, готово

2020-11-16 16:25 UTC, kreeperHLC requested changes

2020-11-16 16:25 UTC, kreeperHLC commented on code/modules/food/recipes_microwave.dm
> +	fruit = list("garlic" = 1, "flamechili" = 1, "tomato" = 1, )
```suggestion
	fruit = list("garlic" = 1, "flamechili" = 1, "tomato" = 1)
```

2020-11-16 16:28 UTC, kreeperHLC submitted a review, later dismissed

2020-11-21 22:37 UTC, kreeperHLC submitted a review, later dismissed

2020-11-22 08:37 UTC, TobyThorne commented
Нравится, аппруваю.

2020-11-22 12:49 UTC, TapKo4eB commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +
меня инит на нью и убирай смешной прок я ебал этот код в рот
```suggestion
/obj/item/weapon/reagent_containers/food/snacks/fathersoup/New()
	..()
	reagents.add_reagent(/datum/reagent/nutriment/protein, 8)
	reagents.add_reagent(/datum/reagent/water, 10)
	reagents.add_reagent(/datum/reagent/thermite, 2)
	reagents.add_reagent(/datum/reagent/capsaicin, 5)
```

2020-11-22 14:19 UTC, Animesku commented
![1606032291](https://user-images.githubusercontent.com/48406301/99906202-d609d180-2ce6-11eb-9830-11c05f6e30f7.jpg)

2020-11-22 16:21 UTC, TapKo4eB commented on code/modules/reagents/reagent_containers/food/snacks.dm
>  /obj/item/weapon/reagent_containers/food/snacks/slimesoup
о нет пробел потерян

2020-11-22 18:48 UTC, TapKo4eB approved these changes
niet

2020-11-22 18:57 UTC, TobyThorne approved these changes
norm

2020-11-22 19:31 UTC, merged