add(radial): Add radial choices
ChaoticOnyx/OnyxBay pull request #3781
Opened 2020-11-23 15:00 UTC by kreeperHLC

Добавляет новый вид интерфейса - круговые выборы, которые позволяют избавиться от окон в две-три строки и сделать более удобным выбор из списка. 
В качестве теста было сделано для микроволновки: ![image](https://user-images.githubusercontent.com/14943437/99977445-b4c3e680-2db5-11eb-915d-8010ebab4f41.png)
И для диспенсеров танков:  ![image](https://user-images.githubusercontent.com/14943437/99977528-d02ef180-2db5-11eb-8d8a-28f672d88279.png)

- [ х ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ х ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ х ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ х ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-23 16:10 UTC, Destrolaric reviewed
Кажись забрыл убрать карты с дебага

2020-11-23 16:10 UTC, Destrolaric commented on baystation12.dme
> -#include "maps\exodus\exodus.dm"
Это точно от дебага не осталось?

2020-11-23 16:10 UTC, Destrolaric commented on baystation12.dme
> -#include "maps\exodus\exodus_define.dm"
Хмм

2020-11-29 10:54 UTC, TobyThorne commented
чёт мне не нравится
у нас и так хуева гора раных УИ
обычный браузер, фейк наноУИ, наноУИ, тгУИ

2020-11-29 11:57 UTC, kreeperHLC commented
> у нас и так хуева гора раных УИ
Эта штука облегчает кодерам работу, ибо по сути обычный список и тебе не нужно разбираться как создавать интерфейс через УИшки + как раз таки может заменить все варианты со списком в один удобный интерфейс. Вот тот же пример с хирургией. Куда приятнее вытаскивать орган не выбирая из списка, а просто тыкая на его изображение. Так же с диспенсерами и микроволновкой.
> обычный браузер
Потому что никто до НаноУИ обновить не хочет
> фейк наноУИ
Как я помню, они на расстоянии юзаются
> тгУИ
Они мало того что очень устарели, так ещё и всего на 1 аппарате, который даже не их юзает, а Нексты

Так что такая туча УИшек объясняется банальной ленью обновлять/унифицировать интерфейсы.

2020-11-29 22:44 UTC, TobyThorne commented
> Эта штука облегчает кодерам работу, ибо по сути обычный список и тебе не нужно разбираться как создавать интерфейс через УИшки + как раз таки может заменить все варианты со списком в один удобный интерфейс. Вот тот же пример с хирургией. Куда приятнее вытаскивать орган не выбирая из списка, а просто тыкая на его изображение. Так же с диспенсерами и микроволновкой.

Ну вот закодь сразу хотя бы ту же хирургию, тогда аппрувну. А то будет как всегда висеть обрубок фичи с двумя использованиями на весь билд. 

> Как я помню, они на расстоянии юзаются

Не юзаются, если кодер не быдло и нормально настраивает топики. 
 
> Они мало того что очень устарели, так ещё и всего на 1 аппарате, который даже не их юзает, а Нексты

Не один, а два. Сканнеры и ресиверы. А два - ровно столько же, сколько сейчас есть в этом ПРе. 

> Так что такая туча УИшек объясняется банальной ленью обновлять/унифицировать интерфейсы.

Ну вот если бы кому-то стало не похуй и всё подогналось под наноУИ, фейкнаноУИ и вот эти вот радиальные менюшки - был бы билд победы.

2020-11-29 22:49 UTC, kreeperHLC commented
> Ну вот закодь сразу хотя бы ту же хирургию, тогда аппрувну. А то будет как всегда висеть обрубок фичи с двумя использованиями на весь билд.

Я и хотел продолжить в этом ПРе обновлять другие вещи, но кто тогда вообще будет читать ПР с кучей измененных интерфейсов для механизмов? Я в любом случае продолжил бы запил таких интерфейсов, но если хирургия - одна из базовых вещей для принятия ПРа, то я готов сделать её сейчас.

2020-12-03 20:28 UTC, kreeperHLC commented
Добавлена хирургия. Обновил описание ПРа вместе с этим.

2020-12-03 20:43 UTC, kreeperHLC commented
Тревис живи

2020-12-03 21:49 UTC, kreeperHLC commented
Впихнул лестницу, обновил описание.

2020-12-19 21:02 UTC, TobyThorne commented on code/modules/multiz/structures.dm
> +/obj/structure/ladder/attack_ai(mob/user as mob)
Зачем попихал везде as mob?

2020-12-19 21:06 UTC, TobyThorne commented
В общем, потестил. Чё могу сказать? Пока что мне нравится только использование для хирургии. С хранилищами болонов - нейтрально, что есть, что нет - как-то не сильно на что-то влияет. Микроволновка не нравится, лучше оставить для всякой машинерии один вариант использования - через окошко, дабы избежать лишней путаницы.
Вот органы - да, пожалуй, радиальные меню - максимально лаконичный способ реализовать вырезание органов. Предлагаю для аналогичных штук радиальное меню и использовать - заменять им богомерзкий input со списком.

По поводу кода - есть смешное с операциями. Если при открытом меню выкинуть инструмент, положить его куда-нибудь, 
 взять другой инструмент, етц., а потом выбрать пункт - операция успешно начнёт проводиться первым инструментом, где бы он не находился.

2020-12-19 21:07 UTC, TobyThorne requested changes
В общем, РЧ.

2021-01-14 08:06 UTC, kreeperHLC commented
> В общем, РЧ.

Готово. Вырезал микроволновку, пофиксил хирургию, но там другой смех вылез. Из-за кривизны кода хирургии ретёрн всё ещё что-то пытается делать. Желательно исправить тому, кто будет хирургию трогать. Баг не из-за меня, он в принципе общий.

2021-01-14 08:08 UTC, HonkyDonky commented
> Баг не из-за меня, он в принципе общий.

:kek-1:

2021-01-14 08:09 UTC, kreeperHLC commented
> > Баг не из-за меня, он в принципе общий.
> 
> :kek-1:

Я в хирургию для фикса этого лезть боюсь

2021-01-14 15:32 UTC, Doster-d approved these changes, later dismissed
Вот по моей информации, из которой есть информация, вообще информация - все окей.

2021-01-15 21:36 UTC, TobyThorne commented
> > > Баг не из-за меня, он в принципе общий.
> > 
> > 
> > :kek-1:
> 
> Я в хирургию для фикса этого лезть боюсь

Ладно, хрен с ним, пусть остаётся как есть. Между накатыванием ПРа и обновлением потрогаю сам, наверное.
Щас будем тестить.

2021-01-19 00:59 UTC, Shootnik01 commented
Эта хрень только у хирургии будет?

2021-01-19 07:25 UTC, kreeperHLC commented
> Эта хрень только у хирургии будет?

Нет конечно. Завезём на всё что можно

2021-01-28 19:46 UTC, TobyThorne submitted a review, later dismissed
хуй с ним, сломается - ревертнем

2021-01-28 19:49 UTC, Doster-d approved these changes
Давно пора.

2021-01-29 11:03 UTC, kcalbCube commented
Ебать коррупция

2021-01-29 15:56 UTC, Doster-d requested changes
Ой, тултипы все еще есть.

2021-01-30 06:18 UTC, TobyThorne commented on code/__defines/_planes+layers.dm
> +#define ABOVE_HUD_PLANE					8
хорошая табуляция красивая

2021-01-30 16:34 UTC, Doster-d approved these changes

2021-01-31 05:46 UTC, TobyThorne approved these changes
похуй погнали

2021-01-31 20:33 UTC, merged