Добавил часть спрайтов из конкурса спрайтов
ChaoticOnyx/OnyxBay pull request #3851
Opened 2020-11-30 12:32 UTC by sweden-moose

Реализует часть #3607.
А точнее, пункты 1-6

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-30 12:37 UTC, kreeperHLC approved these changes

2020-11-30 12:37 UTC, TobyThorne requested changes
нет спрайтов для тонкомальчиков

2020-11-30 12:58 UTC, sweden-moose commented
> нет спрайтов для тонкомальчиков

Пофиксил и добавил скриншот

2020-11-30 20:07 UTC, kreeperHLC approved these changes

2020-12-01 12:14 UTC, Doster-d approved these changes

2020-12-03 20:20 UTC, Doster-d requested changes
Ай, конфликты...

2020-12-04 10:21 UTC, sweden-moose commented
Конфликты всё

2020-12-05 16:24 UTC, kreeperHLC approved these changes

2020-12-30 09:49 UTC, closed without merging