Спрайт разлитого компоста
ChaoticOnyx/OnyxBay pull request #3852
Opened 2020-11-30 15:42 UTC by sweden-moose

Один скрин вместо тысячи слов

![shit](https://user-images.githubusercontent.com/63788778/100630025-11397f80-333b-11eb-899f-7c85f8fb7549.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-30 18:39 UTC, Ershovdi commented
недостаточно коричневый

2020-11-30 20:12 UTC, kreeperHLC requested changes
Серьёзно, как можно было умудриться забыть тут то пробелы. А так ну такооое. Лучше бы что-то посмешнее говна придумал.

2020-11-30 20:12 UTC, kreeperHLC commented on code/game/objects/random/random.dm
> +				/obj/effect/decal/cleanable/shit=0.1)
```suggestion
				/obj/effect/decal/cleanable/shit = 0.1)
```

2020-11-30 20:13 UTC, sweden-moose commented on code/game/objects/random/random.dm
> +				/obj/effect/decal/cleanable/shit=0.1)
Исправил этот ужас

2020-11-30 20:17 UTC, kreeperHLC commented
У вас Тревис сдох
![image](https://user-images.githubusercontent.com/14943437/100659849-41484900-3362-11eb-963f-6072c3858d0a.png)

2020-11-30 21:00 UTC, TobyThorne commented
почему оно в форме свастона

2020-11-30 21:17 UTC, TatarTheBuilder commented
> почему оно в форме свастона

а почему бы и нет

2020-12-13 23:41 UTC, kreeperHLC approved these changes
По коду конечно нормально, но спрайт такое говно...

2020-12-14 09:45 UTC, TobyThorne commented
Чёто такое. Вместо костылей лучше бы вообще с каких-нибудь гунов стащить механ луж для всех жидкостей.

2020-12-29 14:01 UTC, closed without merging