Нерф вортекса
ChaoticOnyx/OnyxBay pull request #3853
Opened 2020-11-30 18:27 UTC by sweden-moose

Больно смотреть на возможность скакать по локациям без ограничений, поэтому выпилил возможность вставить блюспейс батарейку. Что будет если соединить две экспериментальные технологии? В случае с двумя бохами - синга. В случае с вортексом и блюспейс батарейкой - взрыв. Взамен я предлагаю использовать улучшенную батарею на 1000 заряда (10 прыжков по маякам, вместо 100 с блюспейс батарейкой).

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-30 19:22 UTC, Judge1987 commented
не стукайте вортекс, им же и так нечасто пользуются...

2020-12-02 21:55 UTC, Destrolaric commented
ты чево наделал...

2020-12-02 21:57 UTC, Destrolaric requested changes
Please no, don't do it. Пожалуйста нинадо.

2020-12-02 21:58 UTC, Doster-d commented on code/game/objects/items/weapons/teleportation.dm
> +			if(istype(vcell, /obj/item/weapon/cell/quantum))
Может лучше с некоторым шансом пусть это делает, а то в говнино это дерьмо превращаем?

2020-12-02 22:00 UTC, sweden-moose commented on code/game/objects/items/weapons/teleportation.dm
> +			if(istype(vcell, /obj/item/weapon/cell/quantum))
Совет геймдизайнеров решил так

2020-12-02 22:00 UTC, Doster-d commented on code/game/objects/items/weapons/teleportation.dm
> +	user.forceMove(get_turf(quacell.partner))
Или лучше вот сюда проверку на вероятность засунуть, а то слишком уж нерф.

2020-12-02 22:01 UTC, Doster-d commented on code/game/objects/items/weapons/teleportation.dm
> +			if(istype(vcell, /obj/item/weapon/cell/quantum))
А можно увидеть сообщение, где они такое решили?

2020-12-03 09:14 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/100988662-2819e500-357a-11eb-9db4-776a7181083e.png)
когда кинул блюспейс батарейку и телепортируешься к ней

2020-12-03 09:34 UTC, TobyThorne commented on code/game/objects/items/weapons/teleportation.dm
> +		localteleport(get_turf(user), 1)
Го вместо localteleport(get_turf(user), 1) те ржаки с картошкой
а так збс, реквест выполнил

2020-12-03 09:38 UTC, sweden-moose commented on code/game/objects/items/weapons/teleportation.dm
> +		localteleport(get_turf(user), 1)
expotato?

2020-12-03 09:39 UTC, TobyThorne commented on code/game/objects/items/weapons/teleportation.dm
> +		localteleport(get_turf(user), 1)
да можно в принципе и expotato, и potato, и карпов

2020-12-03 09:44 UTC, sweden-moose commented on code/game/objects/items/weapons/teleportation.dm
> +		localteleport(get_turf(user), 1)
Вставил potato

2020-12-03 10:02 UTC, TobyThorne commented
Как оказалось, если блюспейс-батарейка уничтожается, а вторая вставлена в вортекс - она не уничтожится вместе с первой. Скорее фича, чем чем, блюспейс же. 
В таком случае вортекс реально телепортирует в нулл. И это, чёрт возьми, мне ещё больше нравится. Хотя в будущем можно будет сделать какое-нибудь БлЮсПеЙс-ИзМеРеНиЕ и посылать туда.

2020-12-03 10:02 UTC, TobyThorne approved these changes
Одобряемо.

2020-12-03 10:03 UTC, TobyThorne commented
Вот только описание ПРа обнови.

2020-12-03 10:05 UTC, sweden-moose commented
Обновил

2020-12-03 10:25 UTC, TobyThorne requested changes

2020-12-03 10:25 UTC, TobyThorne commented on code/game/objects/items/weapons/teleportation.dm
> +		user.visible_message(SPAN_WARNING("The Vortex Manipulator turns into potato!"))
turns into a potato

2020-12-03 10:27 UTC, sweden-moose commented on code/game/objects/items/weapons/teleportation.dm
> +		user.visible_message(SPAN_WARNING("The Vortex Manipulator turns into potato!"))
a patota

2020-12-03 10:28 UTC, TobyThorne approved these changes
a

2020-12-03 11:03 UTC, Doster-d approved these changes
Ну отправка космонавтика НАВСЕГДА в null пространство за вортекс - одобряем.

2020-12-03 11:11 UTC, HonkyDonky commented
Не забудьте ещё запретить писать в админхелп будучи в нулле.

2020-12-03 12:15 UTC, Destrolaric commented
Кстати, а что по поводу null, там возможно юзать предметы?

2020-12-03 19:44 UTC, merged