хеккоч тупой пидарас
ChaoticOnyx/OnyxBay pull request #3854
Opened 2020-11-30 19:24 UTC by TobyThorne

- Реверт раз #1796 
- Реверт два #1597 

Второе не совсем ревертнуто, оставил поломку коллекторов от температуры, ибо ставить их в 10к градусов - как-то не смешно. 
Вот только коллекторы радиации, взрывающиеся от радиации - ещё несмешнее.
А штатное оборудование, которое рандомно нахуй выкидывает в быдлодереликты, которые хуй знает зачем вообще подгружаются.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-11-30 19:34 UTC, TapKo4eB commented
а чё хеккоч то, пидорас мемори или кто их там одобривал

2020-11-30 19:35 UTC, TobyThorne commented
> а чё хеккоч то, пидорас мемори или кто их там одобривал

ну мемори не пидорас но конкретно в этом случае чутка пидорас

2020-11-30 19:38 UTC, TapKo4eB submitted a review, later dismissed
math hard

2020-11-30 19:58 UTC, TatarTheBuilder submitted a review, later dismissed

2020-11-30 20:03 UTC, kreeperHLC requested changes
Всё отлично кроме двух мест с пробелами. Но лучше бы муху вернул вместо удаления калибровки.

2020-11-30 20:03 UTC, kreeperHLC commented on code/modules/power/singularity/collector.dm
> +			P.air_contents.adjust_gas("phoron", -0.001*drainratio)
```suggestion
			P.air_contents.adjust_gas("phoron", -0.001 * drainratio)
```

2020-11-30 20:03 UTC, kreeperHLC commented on code/modules/power/singularity/collector.dm
> +		power_produced = P.air_contents.gas["phoron"]*pulse_strength*20
```suggestion
		power_produced = P.air_contents.gas["phoron"] * pulse_strength * 20
```

2020-11-30 20:09 UTC, kreeperHLC commented
Тревис сдох кстати

2020-11-30 20:12 UTC, TatarTheBuilder approved these changes
8=====D~~

2020-11-30 20:12 UTC, TapKo4eB approved these changes
ъ

2020-11-30 20:13 UTC, kreeperHLC commented on code/game/machinery/teleporter.dm
>  	if (!R)	return null
```suggestion
	if(!R)	
		return null
```

2020-11-30 20:14 UTC, TobyThorne commented on code/game/machinery/teleporter.dm
>  	if (!R)	return null
ой отлюбись это я не трогал оно там довно вообще ниче не знаю ляляляля

2020-11-30 20:14 UTC, kreeperHLC approved these changes

2020-11-30 20:15 UTC, kreeperHLC commented on code/game/machinery/teleporter.dm
>  	if (!R)	return null
Но при этом другие пробелы потрогал же

2020-11-30 22:18 UTC, Epicus7 requested changes
Название ПРа не соответствует содержанию.

2020-11-30 22:21 UTC, TobyThorne commented
> Название ПРа не соответствует содержанию.

Исправлено.

2020-11-30 22:24 UTC, Doster-d commented on code/game/machinery/teleporter.dm
>  	if (!R)	return null
А разве не надо вызывать ASSERT в таком случае?

2020-12-01 01:22 UTC, Epicus7 approved these changes
Изменения пока не смотрел, просто сброшу чейнж реквест.

2020-12-01 07:34 UTC, TapKo4eB commented
![s](https://user-images.githubusercontent.com/48761132/100710435-c3675a80-33c0-11eb-8653-03b40ee18f77.png)

2020-12-01 07:36 UTC, kreeperHLC commented
Но аппрува даже так три

2020-12-01 07:37 UTC, TapKo4eB commented
два зелёных

2020-12-01 07:37 UTC, kreeperHLC commented
> два зелёных

Да там обновиться не успело, поэтому показывалось три зелёных

2020-12-01 07:38 UTC, kreeperHLC commented
Лучше бы кстати другие ПРы проверял над Эпикусом потешался

2020-12-01 07:39 UTC, TapKo4eB commented
у меня физика

2020-12-02 08:55 UTC, YouBro commented
Согласен с первыми тремя словами в заголовке иссуя. Действительно, нахуя вы таких кодеров дырявых приглашаете, еще и одобряете этот высер, когда вам кричат НЕ НАДО. А теперь ревертаем) Смех да и только.

2020-12-02 09:04 UTC, merged