fix(reagent_container): replace all New's with Initialize's
ChaoticOnyx/OnyxBay pull request #3857
Opened 2020-12-01 01:20 UTC by Epicus7

У всех reagent_container заменил New на Initialize, чтобы поправить порядок инициализации, который раньше перемешивался из-за одновременных использований и New, и Initialize в иерархии наследования.

Заодно прописал прокам полные пути.

close #3817

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-01 11:03 UTC, Doster-d reviewed
Заметил пару спорных моментов, прошу отписать, если я не прав и в этом действительно есть смысл.

2020-12-01 11:08 UTC, Epicus7 commented on code/game/gamemodes/godmode/form_items/narsie_items.dm
>  	reagents.add_reagent(/datum/reagent/toxin/zombie,120)
Это конец файла

2020-12-01 11:09 UTC, Epicus7 commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +				to_chat(user, "<span class='notice'>You lock the assembly.</span>")
Я ток отступы тут везде трогал. Если начать еще чот менять - это потеряется в куче изменений.

2020-12-01 11:11 UTC, Doster-d commented on code/game/gamemodes/godmode/form_items/narsie_items.dm
>  	reagents.add_reagent(/datum/reagent/toxin/zombie,120)
Обычно добавляют вайтспейс в конец.

2020-12-01 11:11 UTC, Epicus7 commented on code/modules/detectivework/tools/luminol.dm
>  	reagents.add_reagent(/datum/reagent/luminol, 250)
Какой вайтспейс? Чо не так?

2020-12-01 11:12 UTC, Doster-d commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +				to_chat(user, "<span class='notice'>You lock the assembly.</span>")
Ну, это не критично, но в соответствие с гайдом по контробитунгу желательно заменить.

2020-12-01 11:13 UTC, Epicus7 commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +/obj/item/weapon/grenade/chem_grenade/Initialize()
В New не было ..() - я сохранил логику.

Если добавить . = ..(), то логика изменится, я бы не стал менять ибо итак много чего трогается в этом ПРе.

2020-12-01 11:14 UTC, Epicus7 commented on code/game/machinery/kitchen/icecream.dm
> +/obj/item/weapon/reagent_containers/food/snacks/icecream/Initialize()
Ниже ответил

2020-12-01 11:14 UTC, Epicus7 commented on code/game/objects/items/weapons/ecigs.dm
> +/obj/item/weapon/reagent_containers/ecig_cartridge/Initialize()
Ниже ответил

2020-12-01 11:14 UTC, Epicus7 commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +/obj/item/weapon/grenade/chem_grenade/Initialize()
Ниже ответил

2020-12-01 11:17 UTC, Doster-d commented on code/modules/detectivework/tools/luminol.dm
>  	reagents.add_reagent(/datum/reagent/luminol, 250)
Необходимо добавить пустое место, я указал это из-за того, что Тоби указывал на это.

2020-12-01 11:18 UTC, Doster-d commented on code/modules/detectivework/tools/luminol.dm
>  	reagents.add_reagent(/datum/reagent/luminol, 250)
Просто Enter прожать в конце файла.

2020-12-01 11:24 UTC, kreeperHLC requested changes
Успешно просмотрено. Жду исправлений.

2020-12-01 11:24 UTC, kreeperHLC commented on code/game/gamemodes/godmode/form_items/narsie_items.dm
>  	reagents.add_reagent(/datum/reagent/toxin/zombie,120)
```suggestion
	reagents.add_reagent(/datum/reagent/toxin/zombie,120)

```
![image](https://user-images.githubusercontent.com/14943437/100733759-b9a11f80-33df-11eb-98d1-09b71f24613a.png)
Эпикус, читать научиться совсем не сложно

2020-12-01 11:24 UTC, kreeperHLC commented on code/game/objects/items/weapons/ecigs.dm
>  	reagents.add_reagent(/datum/reagent/drink/coffee, 5)
```suggestion
	reagents.add_reagent(/datum/reagent/drink/coffee, 5)

```

2020-12-01 11:24 UTC, kreeperHLC commented on code/game/objects/items/weapons/paint.dm
> +	. = ..()
```suggestion
	. = ..()

```
Да вообще то не норм

2020-12-01 11:24 UTC, kreeperHLC commented on code/modules/detectivework/tools/luminol.dm
>  	reagents.add_reagent(/datum/reagent/luminol, 250)
```suggestion
	reagents.add_reagent(/datum/reagent/luminol, 250)

```

2020-12-01 11:24 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/cans.dm
>  	reagents.add_reagent(/datum/reagent/ethanol/cider/apple, 40)
```suggestion
	reagents.add_reagent(/datum/reagent/ethanol/cider/apple, 40)

```

2020-12-01 11:24 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/drinks.dm
> +/obj/item/weapon/reagent_containers/food/drinks/ice/Initialize()
Вот тут причем строку не добавил

2020-12-01 11:24 UTC, kreeperHLC commented on code/modules/reagents/reagent_containers/food/snacks/meat.dm
> +	src.bitesize = 3
А надо ли src.?

2020-12-01 11:59 UTC, HonkyDonky approved these changes

2020-12-02 00:56 UTC, Epicus7 commented on code/game/gamemodes/godmode/form_items/narsie_items.dm
>  	reagents.add_reagent(/datum/reagent/toxin/zombie,120)
Ну это же было так, я не менял вайтспейсы в этом ПРе. И строчку даже не трогал эту.

ПР не относится к вайтспейсам.

2020-12-02 00:57 UTC, Epicus7 commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +				to_chat(user, "<span class='notice'>You lock the assembly.</span>")
Эти изменения не будет видно в ПРе, он очень большой. Это плохая идея менять код, когда ты тупо отступ изменил.

2020-12-02 00:59 UTC, Epicus7 commented on code/modules/detectivework/tools/luminol.dm
>  	reagents.add_reagent(/datum/reagent/luminol, 250)
Опять же, последнюю строчку файла я не трогал.

2020-12-02 01:00 UTC, Epicus7 commented on code/game/gamemodes/godmode/form_items/narsie_items.dm
>  	reagents.add_reagent(/datum/reagent/toxin/zombie,120)
Можно без оскорблений? Я умею читать.

Последнюю строчку файла я не трогал, поэтому там нет переноса строки, очевидно. Если ты не заметил, то ПР довольно большой и сделан регексом.

2020-12-02 01:02 UTC, Epicus7 commented on code/modules/reagents/reagent_containers/food/snacks/meat.dm
> +	src.bitesize = 3
Я не менял код, который был в ПРе в принципе. Нигде и никакой, если это не вызывало рантаймы.

Лишние изменения потеряются в 3к строках диффов.

2020-12-02 11:59 UTC, kreeperHLC approved these changes

2020-12-03 02:36 UTC, Doster-d approved these changes

2020-12-03 09:17 UTC, TobyThorne approved these changes
эпикус умный эпикус ниче не сломает

2020-12-03 09:18 UTC, merged