Лицензия торговцам
ChaoticOnyx/OnyxBay pull request #3862
Opened 2020-12-01 15:43 UTC by sweden-moose

close #46
Нужна доработка. Не имеет смысл вводить до мержа #3519. Возможно, стоит вынести все названия в конфиг.

- [] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-01 15:56 UTC, kreeperHLC commented
Ты чево наделал...

2020-12-01 15:58 UTC, kreeperHLC requested changes

2020-12-01 15:58 UTC, kreeperHLC commented on code/modules/paperwork/misc.dm
> +	var/possible_mis = list("nt_code","org_code","date", "dest","department")
```suggestion
	var/possible_mis = list("nt_code", "org_code", "date", "dest", "department")
```

2020-12-01 15:58 UTC, kreeperHLC commented on code/modules/paperwork/misc.dm
> +				date = list("day" = rand(1,37), "month" = rand(1,13), "year" = rand(2565), "dur" = rand(3,10))
```suggestion
				date = list("day" = rand(1, 37), "month" = rand(1, 13), "year" = rand(2565), "dur" = rand(3, 10))
```

2020-12-01 17:35 UTC, 4310V343k commented
А че а при чем тут мой пр не понял

2020-12-01 17:36 UTC, sweden-moose commented
Бумаги в говне (тегах)

2020-12-01 17:38 UTC, 4310V343k commented
Разве я трогал прок set_content() в своем ПРе? Ты именно через него делаешь наполнение бумажки, а не через new()

2020-12-01 17:38 UTC, Doster-d commented
> Бумаги в говне (тегах)

Для того, что бы они были не говно надо их правильно составлять, я делал бумагу для инженеров и все с ней нормально.

2020-12-01 17:43 UTC, 4310V343k commented on code/modules/paperwork/misc.dm
> +	set_content(message)
```suggestion
	set_content(message, rawhtml = TRUE)
```

2020-12-01 17:54 UTC, sweden-moose commented
Никак не связано

2020-12-02 01:32 UTC, Epicus7 requested changes
Вообще конечно ресурсы (названия, текст) в идеале надо хранить в отдельных от кода файлах. К сожалению у нас нет нормальной системы ресурсов, так что вариантов тут довольно много как это лучше сделать.

Но ладно, в принципе пока файлик такой маленький, это можно пережить. Только отформатируй хотя бы получше чуть-чуть. Длинные списки лучше выравнивать по одному значению на строчку.

2020-12-02 01:32 UTC, Epicus7 commented on code/modules/paperwork/misc.dm
> +	"Предметы одежды" = 100, "Сырье и материалы" = 100,\
А можешь это выравнять как-то получше? Желательно, чтобы это было два столбика - название и стоимость. Две пары на одной строке лучше не писать - ибо они теряются.

Выше тоже список надо бы выравнять и не писать по 2 значения на одной строке, чтобы все значения были на одном уровне отступа и сразу в глаза бросались.

2020-12-02 01:32 UTC, Epicus7 commented on code/modules/paperwork/paper.dm
> +		return
Может добавить в бумажку новую переменную "dynamic_icon"? Поставим её в FALSE талисманам и лицензии.

Это неоч хорошо, что у нас логика лицензий вылезает в общую логику бумажек.

2020-12-02 08:48 UTC, TobyThorne commented on code/modules/paperwork/misc.dm
> +	 "Snail Lovers Union")
одобряю

2020-12-03 07:03 UTC, Doster-d requested changes
По коду нормально, но по геймдизайнерскому сообщению есть вопросы:
```
Правильные параметры (какие департаменты существуют и могут выдавать торговые лицензии, какие у них номера и кто в них работает, какие печати есть у НТ и т.д.) генерятся и помещаются в консольку/ПДА/мозг АВД.
```
```
Торговец, если он есть, получает предупреждение жирными буквами, что его деятельность на КСН "Исход" не очень законна и он может получить пизды (возможно, стоит конкретно указывать причину, типа истекший срок, отсутствие Исхода в списке разрешенных для посещения объектов, поддельные данные и т.д.).
```
```
Прямоугольная печать NanoTrasen. Будет 2-3 варианта.
Прямоугольная печать торговой организации. Будет 2-3 варианта на каждую организацию.
```
Где реализовано?

Ревью написанно в соответствие с планом реализации, описанный ОПом в его сообщение.

2020-12-03 11:33 UTC, sweden-moose commented
Печати конечно прикольно, но те пиксельные печати что рисовал Панч не подходят. Пока без печатей, но это
> Торговец, если он есть, получает предупреждение жирными буквами, что его деятельность на КСН "Исход" не очень законна и он может получить пизды (возможно, стоит конкретно указывать причину, типа истекший срок, отсутствие Исхода в списке разрешенных для посещения объектов, поддельные данные и т.д.).

> Правильные параметры (какие департаменты существуют и могут выдавать торговые лицензии, какие у них номера и кто в них работает, какие печати есть у НТ и т.д.) генерятся и помещаются в консольку/ПДА/мозг АВД.

сегодня сделаю

2020-12-03 11:34 UTC, Doster-d commented
> Правильные параметры (какие департаменты существуют и могут выдавать торговые лицензии, какие у них номера и кто в них работает, какие печати есть у НТ и т.д.) генерятся и помещаются в консольку/ПДА/мозг АВД.

Лично я голосую за мозг АВД

2020-12-03 13:32 UTC, sweden-moose commented
Добавил предупреждение и дал чемодан с темплейтом лицензии АВД

2020-12-03 13:59 UTC, kreeperHLC commented on code/modules/paperwork/misc.dm
> +	 "Snail Lovers Union")
Не чувствую Голиафов. Не одобряю.

2020-12-03 19:39 UTC, Doster-d commented on code/modules/paperwork/misc.dm
> +/obj/item/weapon/paper/trade_lic/trade_guide/New()
Лучше используй Initialize().

2020-12-03 19:40 UTC, Doster-d requested changes
У Вас листок сломан
![image](https://user-images.githubusercontent.com/63081538/101079466-941b3e00-35b8-11eb-84da-927c60f746ca.png)

2020-12-03 19:41 UTC, sweden-moose commented on code/modules/paperwork/misc.dm
> +/obj/item/weapon/paper/trade_lic/trade_guide/New()
Спасибо огромное за совет, только вот если спавнить его, то вся бумага будет в тегах.

2020-12-03 19:41 UTC, Doster-d commented on code/modules/paperwork/misc.dm
> +/obj/item/weapon/paper/trade_lic/trade_guide/New()
Ну тогда используй New

2020-12-03 20:23 UTC, Doster-d commented
Решение в дискорде.

2020-12-03 20:50 UTC, sweden-moose commented
С божьей помощью (@Doster-d) исправлено кривое отображение при спавне

2020-12-03 20:58 UTC, Doster-d approved these changes
Я доверяю ОПу и надеюсь, что это не ложь:
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2020-12-03 21:00 UTC, sweden-moose commented
В мапдифе говно вылезло, куда аппруваешь?

2020-12-03 21:51 UTC, Doster-d approved these changes
Я по коду смотрел, ниче не знаю про ваши мапдифы)

2020-12-04 14:04 UTC, kreeperHLC approved these changes

2020-12-04 15:09 UTC, Epicus7 approved these changes

2020-12-05 00:02 UTC, Doster-d commented on code/modules/paperwork/misc.dm
> +	 "Do Star Tradeband",\
Мне так-то похуй, но если можно, то поставьте
```
"Toster Intergated Systems"
```

2020-12-05 00:02 UTC, Doster-d approved these changes
Нормально.

2020-12-05 05:23 UTC, sweden-moose commented
Хеккоч сделает круче

2020-12-05 15:54 UTC, TobyThorne commented on code/modules/paperwork/misc.dm
> +	  "NSV Luna",\
сука с луны до слёз(((((((((

2020-12-05 16:01 UTC, TobyThorne commented
Я ничё не проверял, ПР одобрен EpicSeven Supply Company и Do Star Tradeband.

2020-12-05 16:02 UTC, merged

2020-12-06 00:02 UTC, TobyThorne commented
ПР убил бумагу кривым Initialize(). 
![image](https://user-images.githubusercontent.com/45202681/101267926-65ec5880-3788-11eb-8171-d37e1eda2583.png)
![image](https://user-images.githubusercontent.com/45202681/101267950-8e745280-3788-11eb-901d-237062a4874a.png)
![image](https://user-images.githubusercontent.com/45202681/101267961-97652400-3788-11eb-914b-2dbf7d79666f.png)

2020-12-06 12:32 UTC, Destrolaric commented
Откатываем пацаны