Горстка фиксов
ChaoticOnyx/OnyxBay pull request #3869
Opened 2020-12-02 00:16 UTC by TobyThorne

- Исправлен рантайм при смерти спайдерботов;
- Исправлен рантайм в с null.status_flags в take_external_damage;
- Исправлен Rejuvenate для simple_animals;
- Исправлен бесконечный вызов Death() у simple_animals;
- Исправлены рантаймы у грабов - тут надо отметить, что грабы - один большой пиздец. Их нужно основательно доделывать, я только чутка присыпал их здравым смыслом.
- Перевод турфов с New на Initialize - всё ради Эпикуса;
- Поправлена куча кривого форматирования;
- Исправлен просачивающийся через шлюзы (и не только) свет, скрины ниже;

До:
![image](https://user-images.githubusercontent.com/45202681/100811719-71c4db80-3465-11eb-8725-fc13a5846c78.png)
![image](https://user-images.githubusercontent.com/45202681/100811739-7ab5ad00-3465-11eb-9605-dabf31a3dd82.png)
![image](https://user-images.githubusercontent.com/45202681/100811750-82755180-3465-11eb-84fe-023352e908c0.png)
После:
![image](https://user-images.githubusercontent.com/45202681/100811760-8a34f600-3465-11eb-88a0-bb5e9bcec0e0.png)
![image](https://user-images.githubusercontent.com/45202681/100811769-902ad700-3465-11eb-88ee-2ef592a1ad84.png)
![image](https://user-images.githubusercontent.com/45202681/100811790-9e78f300-3465-11eb-9824-e78491ffd51f.png)
При открытии, ясное дело, всё обновляется:
![image](https://user-images.githubusercontent.com/45202681/100811853-ccf6ce00-3465-11eb-82c7-0d58875d8e59.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-02 03:53 UTC, sweden-moose commented
> Исправлен рантайм при смерти спайдерботов

Вот это закрыть надо будет #3513

2020-12-02 22:20 UTC, Doster-d reviewed
Круто сделано, тут есть пару моментов, которые я бы хотел обсудить, а так аппрув.

2020-12-03 08:52 UTC, TobyThorne commented on code/modules/lighting/lighting_turf.dm
> -
Не съели, а добавили. Смотри справа, а не слева.
![image](https://user-images.githubusercontent.com/45202681/100986227-1edb4900-3577-11eb-945f-cd4371a14c9a.png)

2020-12-03 08:52 UTC, TobyThorne commented on code/game/turfs/turf_changing.dm
> +	if(!N)
Впихнул ЖОПАОБР

2020-12-03 10:59 UTC, Doster-d commented on code/modules/lighting/lighting_turf.dm
> -
Согласен, зря быканул.

2020-12-03 11:00 UTC, Doster-d commented on code/modules/lighting/lighting_turf.dm
> -
Ну ладно...
![image](https://user-images.githubusercontent.com/63081538/101001227-e71cd300-356f-11eb-8753-7f02e5634c4f.png)

2020-12-03 11:00 UTC, Doster-d submitted a review, later dismissed

2020-12-03 13:26 UTC, kreeperHLC requested changes

2020-12-03 13:26 UTC, kreeperHLC commented on code/modules/mob/living/carbon/human/death.dm
> +		I.throw_at(get_edge_target_turf(src, pick(GLOB.alldirs)), rand(1, 3), round(30/I.w_class))
```suggestion
		I.throw_at(get_edge_target_turf(src, pick(GLOB.alldirs)), rand(1, 3), round(30 / I.w_class))
```

2020-12-03 13:26 UTC, kreeperHLC commented on code/game/turfs/turf_changing.dm
> +		if(istype(W,/turf/simulated/floor))
```suggestion
		if(istype(W, /turf/simulated/floor))
```

2020-12-03 13:57 UTC, kreeperHLC approved these changes

2020-12-03 19:32 UTC, Doster-d approved these changes

2020-12-04 11:29 UTC, TatarTheBuilder approved these changes
![image](https://user-images.githubusercontent.com/51989098/101158626-b0f55700-3634-11eb-9353-95a3c5cd650c.png)

2020-12-04 11:32 UTC, merged