Пинпоинтер и диск
ChaoticOnyx/OnyxBay pull request #3872
Opened 2020-12-02 09:01 UTC by igorsaux

3173e1e - похоже что локейт находит старый, еще не до конца удаленный, диск (а он удаляется долго). Изменил локейт на выбор из списка актуальных дисков.
b69d55c - теперь для спавна выбирается случайная зона по типу и предикатам.

fix #3214
fix #2788

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-02 12:49 UTC, Destrolaric commented
Не фиксит проблему, допустим в апплинке тритора есть бомбы. К этим бомбам привязан детонатор. Угадай, что происходит, если бомбу выбросить в мусорку?

2020-12-02 12:50 UTC, Destrolaric commented
Судя по всему, мусорка удаляет обьект полностью, и поэтому ломает и диск и связь бомбы с зажигалкой

2020-12-06 22:26 UTC, kreeperHLC requested changes
Исправляй. А ещё ответь на коммент выше.

2020-12-06 22:26 UTC, kreeperHLC commented on code/_helpers/areas.dm
> +		if (istype(a, areatype) && all_predicates_true(list(a), predicates))
```suggestion
	for(var/area/a)
		if(istype(a, areatype) && all_predicates_true(list(a), predicates))
```

2020-12-07 11:15 UTC, igorsaux commented
Исправил. Мусорка это уже другая история, посмотрю как-нибудь.

2020-12-07 11:15 UTC, kreeperHLC submitted a review, later dismissed

2020-12-08 09:59 UTC, Doster-d approved these changes

2020-12-08 11:20 UTC, Epicus7 requested changes

2020-12-08 11:20 UTC, Epicus7 commented on code/_helpers/areas.dm
>  		return pick(turfs)
Этот прок используется в трех местах. В двух местах в первый аргумент пихается объект типа /area, а в одном месте пихается тип.

И ты сейчас сломал этот прок, так что он начал работать в 1 месте, но не работает в 2 местах.

Вообще по названию функции мне кажется первым аргументом должна быть именно /area/A, а не areatype, ибо функция называется "найти турф зоны", а не "найти турф всех зон, которые подходят по предикату"

Еще есть такое забавное место:
`	return pick_area_turf(A, turf_predicates)`

И ты применяешь предикаты ТУРФОВ к ЗОНАМ? Ну это вообще косяк и проеб типов. Нельзя так делать.

2020-12-08 11:20 UTC, Epicus7 commented on code/_helpers/areas.dm
>  		return pick(turfs)
Короче тут надо аргумент переименовать из areatype в /area/A и фиксить код, с нюкодиском, который почему-то вместо зоны пихает тип зоны, хотя в остальных местах пихаются конкретно зоны.

2020-12-08 11:24 UTC, Epicus7 commented on code/_helpers/areas.dm
> +	for(var/area/a)
Это вообще что такое, лол. a == null сначала, так что в цикл даже не зайдет.

2020-12-08 11:24 UTC, Epicus7 commented on code/_helpers/areas.dm
> +	for(var/area/a)
![image](https://user-images.githubusercontent.com/5204667/101478035-2036b800-3961-11eb-96d5-f095eae9f4bd.png)

2020-12-08 11:26 UTC, Epicus7 commented on code/_helpers/areas.dm
> +	for(var/area/a)
Плин сказал, что это, оказывается, имплисит "in world". Не надо так писать, пожалуйста, сделай явно поиск по миру тогда уж.

2020-12-08 11:37 UTC, Doster-d requested changes
я еблан, че за хуйню я аппрувнул.

2020-12-08 11:39 UTC, igorsaux commented on code/_helpers/areas.dm
>  		return pick(turfs)
> он начал работать в 1 месте, но не работает в 2 местах

А тут иначе никак. Придётся проверять работу и в других случаях использования функции.

2020-12-08 11:41 UTC, Epicus7 commented on code/_helpers/areas.dm
>  		return pick(turfs)
Всмысле никак. Просто не используй этот прок там, где он не подходит. Напиши другой, обертку над этим проком, который будет брать предикаты зон и предикаты турфов отдельно. Сначала искать зоны, а потом в зонах турфы.

2020-12-08 16:47 UTC, kreeperHLC commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
А не лучше искать в глобальном списке арен?

2020-12-08 17:00 UTC, igorsaux commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Да кто этот ваш глобальный список арен, я просто сделал максимально похоже с кодом рядом.

2020-12-08 17:03 UTC, kreeperHLC commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
![image](https://user-images.githubusercontent.com/14943437/101516313-67886d00-3990-11eb-80d2-7a02175e0a91.png)

2020-12-08 17:07 UTC, kreeperHLC commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Ладно смешное, похоже у нас нет глобального списка зон. Лучшим вариантом конечно же будет его добавить.

2020-12-08 17:09 UTC, kreeperHLC commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
![image](https://user-images.githubusercontent.com/14943437/101516998-3bb9b700-3991-11eb-8085-94ac763f3bd8.png)
Похоже нашел таки

2020-12-08 17:11 UTC, igorsaux commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
> Лучшим вариантом конечно же будет его добавить.

Да тут лучшим вариантом будет половину билда переделать...

2020-12-08 17:12 UTC, kreeperHLC commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Я целый год тебя для этого ждал, залетай в дискорд

2020-12-08 17:13 UTC, igorsaux commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Я там всегда был и есть

2020-12-16 11:09 UTC, kreeperHLC commented
Ожидаем автора

2020-12-16 11:19 UTC, igorsaux commented
Ожидаем ревьюверов

2021-01-02 15:59 UTC, igorsaux commented
Уже 2021 год а ревьюверов всё нет

2021-01-14 10:15 UTC, kreeperHLC approved these changes

2021-01-28 07:09 UTC, Doster-d commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Там скинули зон лист для проверки is_station_but_not_space_or_shuttle_area, может стоит использовать его?

2021-01-28 07:10 UTC, Doster-d reviewed
Meh

2021-01-28 09:19 UTC, igorsaux commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Это не зон лист

2021-01-28 09:22 UTC, Doster-d commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Ну так создай зон лист, полезно будет

2021-01-28 09:23 UTC, Doster-d commented on code/_helpers/areas.dm
> +	for(var/area/A in world)
Ну так сделай, полезная же штука.

2021-01-31 01:05 UTC, kcalbCube commented
Пачка сигарет в моем кармане заставляет меня жить этот день. Я возьму телефон, позвоню плину, плин почему я хочу умереть?

2021-02-09 14:12 UTC, Doster-d approved these changes

2021-03-11 20:32 UTC, Epicus7 approved these changes

2021-03-11 20:34 UTC, merged