Ремаппинг Токсинов
ChaoticOnyx/OnyxBay pull request #3889
Opened 2020-12-03 17:49 UTC by No-Tips

Легкая переделка токсинов. Укрепленные стены заменены на боросиликатные стекла (стильно и прочно, и космонавтики сгорать не будут). Перемещены пустые канистры вниз комнаты токсинов. Вместо канистр стоят два стеллажа с вещами, которые до этого лежали в куче на столе. Теха смещены ниже на два тайла. Спрятал плюшевого робота. Ассистенты теперь могут из техов смотреть на прекрасный огонь в камере сгорания. Апц и лестница в техах южнее ксеноботаники поменял места в связи со смещением верхних техов.

**Новый вид:**
![Toxins](https://user-images.githubusercontent.com/75416333/101067515-4db9e500-35a0-11eb-8ef2-99ac0df0cb53.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute].

2020-12-03 20:42 UTC, Doster-d approved these changes
Выглядит хорошо, у АПЦ есть провода.

2020-12-03 21:01 UTC, No-Tips commented
А еще мусорные трубы нормально проложены. Можно за это второй апрув?

2020-12-03 22:05 UTC, Doster-d requested changes
В ПРе незапланированные изменения - матеба вернулась обратно к ХоСу.

2020-12-04 10:37 UTC, No-Tips commented
> В ПРе незапланированные изменения - матеба вернулась обратно к ХоСу.


Ничего не знаю, после обновления коммитов из дев ветки в пулле ничего не изменилось, а значит и репушить нечего

2020-12-04 10:43 UTC, sweden-moose commented
Можешь посмотреть дифф [тут](https://camo.githubusercontent.com/28d028b2637adabe808c07e0b92f58cc9c1b674cb88feade3a5bf670c82e949d/68747470733a2f2f6d64622e616666656374656461726330372e636f2e756b2f46696c65732f3134323933353038372f313439343633393933342f312f646966662e706e67)

![bruh](https://user-images.githubusercontent.com/63788778/101154355-af2c9300-3636-11eb-889e-31fffc9f3630.png)

2020-12-04 10:47 UTC, No-Tips commented
Bruh, wait a second

2020-12-04 14:02 UTC, kreeperHLC approved these changes

2020-12-05 00:00 UTC, Doster-d requested changes
Куда аппруваете конфликты?

2020-12-06 21:57 UTC, MalinaGirl commented
а зачем аквариум у бочек нижних

2020-12-06 22:00 UTC, kreeperHLC commented
Конфликты кстати

2020-12-14 09:43 UTC, TobyThorne commented
Не особо понимаю смысл окошка из техов. Разве что сжигать оттуда токсины, простреливая окошки лазером.

2020-12-24 14:44 UTC, sweden-moose commented
Автор умер.....

2021-01-01 21:51 UTC, TobyThorne commented
Месяц в конфликтоте. Закрываю. Если автор оживёт - может переоткрыть.

2021-01-01 21:51 UTC, closed without merging