Evidencebag fix
ChaoticOnyx/OnyxBay pull request #3895
Opened 2020-12-04 03:51 UTC by Doster-d

Починил контейнер для улик.
Добавил в модуль модификации охранного киборга, а именно детективный модуль модификации, а именно в "контейнер детектива" возможность брать контейнер для улик.
Увеличил количество хранимого в "контейнере детектива" с 8 до 12.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-04 09:40 UTC, kreeperHLC requested changes
Скрины бы ещё нового отображения предметов в нём

2020-12-04 09:40 UTC, kreeperHLC commented on code/modules/detectivework/tools/evidencebag.dm
> +	var/image/img = image(I.icon, I.icon_state, layer=FLOAT_LAYER)	//take a snapshot. (necessary to stop the underlays appearing under our inventory-HUD slots ~Carn
```suggestion
	var/image/img = image(I.icon, I.icon_state, layer = FLOAT_LAYER)	//take a snapshot. (necessary to stop the underlays appearing under our inventory-HUD slots ~Carn
```

2020-12-04 13:13 UTC, Doster-d commented
Ну во первых, оно хотя бы работает, в отличие от текущего варианта, но ладно, добавлю картинку

2020-12-04 13:49 UTC, kreeperHLC commented
> Ну во первых, оно хотя бы работает, в отличие от текущего варианта, но ладно, добавлю картинку

А ещё и плашку геймдиза, раз Боргу добавил это

2020-12-05 01:04 UTC, Doster-d commented
Ну сделал.

2020-12-05 06:51 UTC, kreeperHLC commented
![Uploading image.png…]()

2020-12-05 07:08 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/101236385-e0ae6880-36e1-11eb-800c-e51e5c6cda2e.png)

2020-12-05 15:07 UTC, TobyThorne commented
Смысл пакетиков в том, что можно не брать предмет в руки, а сразу пихнуть в пакет, не оставляя лишних отпечатков. Невозможность запихнуть туда какую-нибудь пачку сигарет - тоже такое.

2020-12-05 15:08 UTC, Doster-d commented
> Смысл пакетиков в том, что можно не брать предмет в руки, а сразу пихнуть в пакет, не оставляя лишних отпечатков. Невозможность запихнуть туда какую-нибудь пачку сигарет - тоже такое.
> 
> Но ресайз предмета - круто, да, выглядит хорошо.

Так сейчас перчатки выполняют эту функцию, не?

2020-12-06 21:51 UTC, kreeperHLC commented
> > Смысл пакетиков в том, что можно не брать предмет в руки, а сразу пихнуть в пакет, не оставляя лишних отпечатков. Невозможность запихнуть туда какую-нибудь пачку сигарет - тоже такое.
> 
> Так сейчас перчатки выполняют эту функцию, не?

Перчатки оставляют волокна

2020-12-14 09:50 UTC, TobyThorne commented
Ну-с, почему бы и нет. В общем-то, работает удобнее, чем неочевидное перетаскивание мешочка на предмет.

2020-12-16 00:10 UTC, kreeperHLC approved these changes

2020-12-19 17:41 UTC, TobyThorne approved these changes
![image](https://user-images.githubusercontent.com/45202681/102695776-a9989500-4253-11eb-9bf1-02691b16f7c6.png)
Будем верить.

2020-12-19 17:44 UTC, Doster-d commented
Труст ми, ай эм эн инженер.

2020-12-19 17:44 UTC, merged