Take Me To Church
ChaoticOnyx/OnyxBay pull request #3909
Opened 2020-12-05 08:34 UTC by MalinaGirl

я думал что этот пр еще месяц назад сделал. но оказалось, что делаю только сейчас. Собственно, перепилил церковь и отбытие. Вроде оно работает. По крайней мере месяц назад точно работало.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-05 08:39 UTC, Doster-d commented
А зона для заключенных?

2020-12-05 08:40 UTC, Ruforce commented
а их можно в космос

2020-12-05 08:42 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/101238103-e494b780-36ee-11eb-8b46-b11e1e772eaf.png)
А это нормально?

2020-12-05 08:42 UTC, MalinaGirl commented
> 
> 
> А зона для заключенных?
![Screenshot_13](https://user-images.githubusercontent.com/25246802/101238085-5c270e80-3710-11eb-8e95-eb18b04a371b.png)
два стула с двумя красивыми пунктирными красными декалями тебе хватит

2020-12-05 08:43 UTC, MalinaGirl commented
> 
> 
> А это нормально?

а прикол забыл

2020-12-05 08:46 UTC, TatarTheBuilder commented
![Screenshot_1](https://user-images.githubusercontent.com/51989098/101238186-2e799f80-36e7-11eb-8695-fee9460c9c1c.png)

2020-12-05 08:53 UTC, kreeperHLC commented
![image](https://user-images.githubusercontent.com/14943437/101238311-78b34e80-36f0-11eb-81c2-5657c826dc5b.png)
Неплохо

2020-12-05 09:15 UTC, MalinaGirl commented
> 
> 
> ![image](https://user-images.githubusercontent.com/63081538/101238103-e494b780-36ee-11eb-8b46-b11e1e772eaf.png)
> А это нормально?



> 
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/51989098/101238186-2e799f80-36e7-11eb-8695-fee9460c9c1c.png)

Исправил

2020-12-05 09:49 UTC, TatarTheBuilder commented
> че

В шлюзах венты не законнекчены ни к чему.

![Screenshot_4](https://user-images.githubusercontent.com/51989098/101239374-cc716800-36ef-11eb-890a-a74783f0bc2b.png)
![Screenshot_3](https://user-images.githubusercontent.com/51989098/101239377-ce3b2b80-36ef-11eb-847c-6558ab71976a.png)
У этих двух камер тэг из бара

![Screenshot_6](https://user-images.githubusercontent.com/51989098/101239384-d72bfd00-36ef-11eb-918b-320c98e7ea02.png)
Мем1

![Screenshot_7](https://user-images.githubusercontent.com/51989098/101239388-dc894780-36ef-11eb-91da-5ef00b46d270.png)
Мем2

Еще у кнопки массдрайвера нет доступа

2020-12-05 11:05 UTC, MrPersival commented
В отбытии была независимая атмосфера. Ну, вентиляция к двум балонам подключена, чтобы ехидный ИИ форон и туда не пустил.

2020-12-05 11:08 UTC, TobyThorne commented
> В отбытии была независимая атмосфера. Ну, вентиляция к двум балонам подключена, чтобы ехидный ИИ форон и туда не пустил.

Чё. Баки с воздухом в соседних техах стоят для работы со шлюзами.

2020-12-05 11:09 UTC, MrPersival commented
А, да, я обосралься.

2020-12-05 11:14 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/101241071-4cfa8d80-371d-11eb-90d0-b274b3507616.png)
Из робототехники спиздили раковину.

2020-12-05 12:24 UTC, MalinaGirl commented
фиксанул все что мог и даже больше

> Еще у кнопки массдрайвера нет доступа

так и раньше так было

2020-12-05 12:47 UTC, TatarTheBuilder commented
Потестил на локалке сброс - разгермой и правда не ебет.

Еще немного хуйни, но это со старой версии, мож пофиксил уже
![Screenshot_11](https://user-images.githubusercontent.com/51989098/101243372-81b01a00-3708-11eb-954f-5b08881351da.png)
нет аварийной створки

![Screenshot_12](https://user-images.githubusercontent.com/51989098/101243380-8a085500-3708-11eb-9d2c-9a13c5d4690a.png)
интерком стремный

![Screenshot_8](https://user-images.githubusercontent.com/51989098/101243382-91c7f980-3708-11eb-9a15-39e6256b9fe4.png)
![Screenshot_9](https://user-images.githubusercontent.com/51989098/101243383-92f92680-3708-11eb-9bdd-025fafa73c91.png)
разные названия шторок, и на тайле с верхней шторкой нет аварийной створки

еще хотелось бы атмос в комнате священника и крематории, отдельные зоны же

2020-12-05 14:49 UTC, TobyThorne commented
> Потестил на локалке сброс - разгермой и правда не ебет.

А почему не ебёт? Надо исправить чтоб ебал.

2020-12-05 15:19 UTC, TobyThorne commented
Гейдизно нравится, выглядит круто. 
Карту надо смотреть, там какие-то кеки.

2020-12-06 10:54 UTC, MalinaGirl commented
Прочекал все еще раз на трезвую голову, теперь-то точно все технические шоколадки устранены. Готов принять ваши аппрувы в дар

2020-12-06 11:05 UTC, TatarTheBuilder commented
че ты вентиляцию священнику зажал

2020-12-06 11:13 UTC, MalinaGirl commented
еще и в крематории зажал да сука

2020-12-06 11:29 UTC, MalinaGirl commented
но сейчас точно...

2020-12-06 11:35 UTC, TatarTheBuilder approved these changes

2020-12-06 11:54 UTC, kreeperHLC requested changes
Ну кроме этого в коде вроде ничего

2020-12-06 11:54 UTC, kreeperHLC commented on code/game/objects/structures/pew.dm
> +	base_icon = "chair_pewchapel_middle"
```suggestion
	base_icon = "chair_pewchapel_middle"

```

2020-12-06 12:01 UTC, kreeperHLC submitted a review, later dismissed

2020-12-06 12:17 UTC, TatarTheBuilder submitted a review, later dismissed
jopa

2020-12-06 12:19 UTC, sweden-moose approved these changes
татарин грит малаца

2020-12-06 12:36 UTC, Doster-d approved these changes
Ну красива получается.

2020-12-06 13:12 UTC, MalinaGirl commented
спасибо всем тем кто был со мной в это нелегкое время без вас этого бы не состоялось. отдельная благодарность моему отцу и матери без них бы тоже ничего не получилось

2020-12-06 13:12 UTC, MalinaGirl commented
дайте мерж
![maxresdefault](https://user-images.githubusercontent.com/25246802/101281019-54926300-37ff-11eb-97a1-8e20ceef497a.jpg)

2020-12-06 13:53 UTC, TobyThorne requested changes
Так, пока не мержить, сейчас потестирую.

2020-12-06 15:43 UTC, TatarTheBuilder approved these changes
jopa x2

2020-12-06 15:44 UTC, sweden-moose approved these changes
татарин грит малаца x2

2020-12-06 15:52 UTC, TobyThorne approved these changes
ну вроде работает наверное да или может нет я хз в общем ну наверное норм да

2020-12-06 15:54 UTC, merged