tweak(loadout): add donate items (8, 22, 23 of SC)
ChaoticOnyx/OnyxBay pull request #3918
Opened 2020-12-05 17:19 UTC by Animesku

Пополняем донатный лодаут 13-ю вещичками.

Вообще его как-то систематизировать надо будет, а то такой огроменный лист ни к чему.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-05 20:11 UTC, sweden-moose reviewed
![eof](https://user-images.githubusercontent.com/63788778/101262327-e0988200-374e-11eb-8ba7-0c6850968404.png)

А так всё норм

2020-12-05 20:11 UTC, sweden-moose commented on code/modules/client/preference_setup/loadout/lists/uniforms.dm
> +	price = 5
![eof](https://user-images.githubusercontent.com/63788778/101262327-e0988200-374e-11eb-8ba7-0c6850968404.png)

2020-12-05 20:11 UTC, sweden-moose commented on code/modules/client/preference_setup/loadout/lists/storage.dm
> +	price = 15
![eof](https://user-images.githubusercontent.com/63788778/101262327-e0988200-374e-11eb-8ba7-0c6850968404.png)

2020-12-05 20:11 UTC, sweden-moose commented on code/modules/client/preference_setup/loadout/lists/headwear.dm
> +	allowed_roles = COMMAND_ROLES
![eof](https://user-images.githubusercontent.com/63788778/101262327-e0988200-374e-11eb-8ba7-0c6850968404.png)

2020-12-05 20:11 UTC, sweden-moose commented on code/modules/client/preference_setup/loadout/lists/gloves.dm
> +	flags = GEAR_HAS_COLOR_SELECTION
![eof](https://user-images.githubusercontent.com/63788778/101262327-e0988200-374e-11eb-8ba7-0c6850968404.png)

2020-12-05 23:57 UTC, Doster-d requested changes

2020-12-05 23:57 UTC, Doster-d commented on code/modules/client/preference_setup/loadout/lists/gloves.dm
> +	flags = GEAR_HAS_COLOR_SELECTION
```suggestion
	flags = GEAR_HAS_COLOR_SELECTION
	
```

2020-12-05 23:57 UTC, Doster-d commented on code/modules/client/preference_setup/loadout/lists/headwear.dm
> +	allowed_roles = COMMAND_ROLES
```suggestion
	allowed_roles = COMMAND_ROLES
	
```

2020-12-05 23:57 UTC, Doster-d commented on code/modules/client/preference_setup/loadout/lists/storage.dm
> +	price = 15
```suggestion
	price = 15
	
```

2020-12-05 23:57 UTC, Doster-d commented on code/modules/client/preference_setup/loadout/lists/uniforms.dm
> +	price = 5
```suggestion
	price = 5
	
```

2020-12-06 04:21 UTC, Animesku commented
Как скажете

2020-12-06 22:23 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/uniforms.dm
> +	allowed_roles = COMMAND_ROLES
А случайно не капитанскую роль надо завезти? Было бы странно иметь капитанский наряд не на Капитане

2020-12-06 22:23 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/uniforms.dm
> +	allowed_roles = COMMAND_ROLES
Ну и тут

2020-12-06 22:23 UTC, kreeperHLC commented
Заодно в иссуе том отметь что за предметы ты добавил

2020-12-07 18:56 UTC, Animesku commented
Раз уж вещь за опиксы, то можно и не такой строгий рестрикт, я думаю. 

А тот иссуй... Он разве не про добавление предметов именно в билд? Просто я-то только в лодаут добавил.

2020-12-07 19:55 UTC, kreeperHLC commented
> Раз уж вещь за опиксы, то можно и не такой строгий рестрикт, я думаю.

Ну такое, лучше строгий сделать.
> А тот иссуй... Он разве не про добавление предметов именно в билд? Просто я-то только в лодаут добавил.

Да, моя ошибка.

2020-12-07 20:26 UTC, Animesku commented
Ладно, теперь только капитану.

2020-12-07 21:57 UTC, kreeperHLC submitted a review, later dismissed

2020-12-08 04:18 UTC, Doster-d submitted a review, later dismissed

2020-12-09 13:58 UTC, Rodial-Admiral commented
ПР был аппрувнут Сенатом. Это оверрайдит тег "геймдизайн" в части одобрений?..

2020-12-09 14:02 UTC, Doster-d commented
> ПР был аппрувнут Сенатом. Это оверрайдит тег "геймдизайн" в части одобрений?..

Это фича, а значит должна быть аппрувната геймдизайнерами, про сенатский аппрув ничего не было сказано в Гуаде ту Контрибутинг и Иссуе Процессинг.

2020-12-09 14:07 UTC, Rodial-Admiral commented
> > ПР был аппрувнут Сенатом. Это оверрайдит тег "геймдизайн" в части одобрений?..
> 
> Это фича, а значит должна быть аппрувната геймдизайнерами, про сенатский аппрув ничего не было сказано в Гуаде ту Контрибутинг и Иссуе Процессинг.

По идее-то да, только решения Сената перекрывают локальные правила. Де-юре. 
Энивей, пну геймдезигнеров сейчас.

2020-12-09 14:11 UTC, Rodial-Admiral commented
Геймдезигнеры возражений не имеют.

2020-12-09 14:37 UTC, Doster-d approved these changes

2020-12-13 19:53 UTC, TatarTheBuilder approved these changes

2020-12-13 23:42 UTC, kreeperHLC commented
Ну ты бы хоть в описание написал, что залил. Эх...

2020-12-13 23:50 UTC, merged