tweak(nanopaste) fix battle cyborg heal
ChaoticOnyx/OnyxBay pull request #3925
Opened 2020-12-06 16:17 UTC by Doster-d

Исправлю возможность научным киборгам делать on-going ремонт.
Да-да, это работает прямо во время битвы.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-06 16:59 UTC, MrMagick2104 commented
Лучше бы сделать задержку при применении нанопасты на себя за киборга, а ремонт в бою мехов/боргов/синтов - фича же, которая позволяет чинить лёгкие повреждения прямо в бою, а тяжёлые с разборкой уже.

2020-12-06 17:27 UTC, TobyThorne approved these changes

2020-12-06 17:27 UTC, TobyThorne requested changes

2020-12-06 17:27 UTC, TobyThorne commented on code/game/objects/items/stacks/nanopaste.dm
> +			if (R.getBruteLoss() || R.getFireLoss() )
а не, не аппрув, тут пробелы уродливые

2020-12-06 21:58 UTC, kreeperHLC commented
Ну такое, лучше задержку сделать если на себя, но при этом с минимальной/без на других.

2020-12-06 22:21 UTC, kreeperHLC requested changes
Исправляй

2020-12-06 22:21 UTC, kreeperHLC commented on code/game/objects/items/stacks/nanopaste.dm
> +			if (R.getBruteLoss() || R.getFireLoss() )
```suggestion
			if(R.getBruteLoss() || R.getFireLoss())
```

2020-12-08 11:36 UTC, Doster-d commented
Исправил.

2020-12-14 09:53 UTC, TobyThorne approved these changes
Пойдёт.

2020-12-14 10:03 UTC, kreeperHLC approved these changes

2020-12-14 10:11 UTC, HonkyDonky approved these changes

2020-12-16 15:33 UTC, TobyThorne approved these changes
выглядит гуд пусть боргов ебут

2020-12-16 15:35 UTC, merged