Крабовое
ChaoticOnyx/OnyxBay pull request #3969
Opened 2020-12-13 16:50 UTC by TobyThorne

- Крабы переработаны, теперь они убегают при наступании, в них можно вселиться за призрака, их можно взять в руки и положить на голову;
- Обновлены спрайты крабов (честно спизжены с ТГ и слегка переработаны);
- При рандомном ивенте помимо мышей, ящериц и паучков теперь могут заспавниться и крабы;
- Уменьшена скорость, с которой мобы вроде мышей убегают от наступившего на них;
- Добавлена анимация ходьбы для мышей и куриц (спизжено с ТГ);
- Исправлен отсутствующий наголовный спрайт у мёртвых ящериц;

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-13 23:37 UTC, kreeperHLC commented on code/_global_vars/lists/flavor.dm
> +	"Crab Rave" = 'sound/music/crab.ogg'
Не, ну это точно нет спасибо

2020-12-25 18:26 UTC, sweden-moose commented on code/modules/mob/living/simple_animal/friendly/crab.dm
> +		to_chat(M, "<span class='warning'>\icon[src] [pick("Click", "Clack")]!</span>")
разрешите додолбаться

2020-12-25 18:27 UTC, sweden-moose commented
Круто, только тут конфликт

2020-12-25 19:45 UTC, Doster-d requested changes
Конфликты, сер.

2020-12-25 21:19 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/crab.dm
> +		to_chat(M, "<span class='warning'>\icon[src] [pick("Click", "Clack")]!</span>")
Поправил.

2020-12-25 21:21 UTC, sweden-moose approved these changes

2020-12-25 21:22 UTC, Doster-d approved these changes

2020-12-25 21:23 UTC, merged