Лодаутное
ChaoticOnyx/OnyxBay pull request #3972
Opened 2020-12-13 19:10 UTC by TobyThorne

Недавно тут проскользнуло высказывание о том, что игрокам не хватает в лодауте очков на декоративные шмоточки, ибо всё тратится на более утилитарные вещи. Посовещавшись, мы поняли, что дело и впрямь ужасное. Надо решать.

Теперь очков точно хватит на все шляпки-костюмчики, какие душе угодно!

- Категория "Tactical Equipment" переименована в "Security Equipment", содержимое теперь доступно только СБ, капитану и ХоПу;
- Фляги перемещены из "General" в "Food and Drinks";
- "vacuum-flask" в лодауте переименована в "vacuum flask";
- Тактическая и тактикульная униформы перемещены из "Tactical" в "Uniforms";
- Балаклава перемещена из "Tactical" в "Masks";
- Бандольер перемещён из "Storage" в "Security Equipment";
- Унатховский чехол с ножами теперь доступен только унатхам;
- Кольца теперь стоят 1 очко;
- Все очки теперь стоят минимум 2 очка;
- Зиппо теперь стоит 2 очка;
- Кармашки теперь стоят 4 очка;
- Нашлемники и тэги на броню теперь стоят по 1 очку;
- В выбор плитников добавлена стандартная версия;
- Пончо доступны только для соответствующих им профессий;
- Берцы заменены на бюджетную версию, по характеристикам соответствующую обычным ботинкам;
- Каски и сварочные маски теперь доступны только техническим профессиям;
- Из лодаута удалён iPatch - это родитель для ХУДов-повязок и вообще не должен использоваться в игре;
- Из лодаута удалены: солнцезащитные очки, ХУДы, разгрузки, танковая шапка, противогаз (донатный всё ещё есть), стетоскоп, карманный ножик, защитные наушники, кармашки для брони, ботанические перчатки, рабочие перчатки, латексные и нитриловые перчатки;

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-13 19:24 UTC, MrMagick2104 commented
Зачем ХУДы удалять, если они профам выдаются раундстартом всё равно, а в лоадауте варианты просто? Вроде для тех, что для слабовидящих.
Танковая шапка чем не угодила?
> латексные и нитриловые перчатки

Лучше бы ограничение на профессии впилить - учёных и медиков. Как и с рабочими и ботаническими перчатками. Они же, кроме рабочих, бесполезные, практически.
> Из лодаута удалены: солнцезащитные очки

Надо было как с берцами - "бюджетную" версию сделать. Самый стильный элемент одежды же.

> Кармашки теперь стоят 4 очка;

> Из лодаута удалены: кармашки для брони

Так удалены или нет?


Ноутбуки спилить бы ещё.

2020-12-13 19:28 UTC, MrMagick2104 commented
> Берцы заменены на бюджетную версию, по характеристикам соответствующую обычным ботинкам;

Если уж нерфанул, то и цену до единицы снизить бы.

2020-12-13 19:29 UTC, TobyThorne commented
> > Берцы заменены на бюджетную версию, по характеристикам соответствующую обычным ботинкам;
> 
> Если уж нерфанул, то и цену до единицы снизить бы.

Не, у них модность повышенная (((и ножик можно в них засунуть только тсс)))

2020-12-13 23:30 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/eyegear.dm
> +	glasses["crimson glasses"] = /obj/item/clothing/glasses/sunglasses/redglasses
> /obj/item/clothing/glasses/sunglasses/redglasses

Получается секретные очки таки остались?

2020-12-13 23:30 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/eyegear.dm
>  	glasses["scanning goggles"] = /obj/item/clothing/glasses/regular/scanners
А это что за сканирующие очки?

2020-12-13 23:30 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/footwear.dm
> -	boots += /obj/item/clothing/shoes/workboots
За выпил рабочих ботинок моё неуважение

2020-12-13 23:30 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/utility.dm
> -	display_name = "stethoscope (medical)"
А стетоскоп кому мешал?

2020-12-14 05:40 UTC, MrMagick2104 commented on code/modules/client/preference_setup/loadout/lists/eyegear.dm
>  	glasses["scanning goggles"] = /obj/item/clothing/glasses/regular/scanners
Просто футуристичные очки, которые работают как очки по рецепту, т.е. зрение восстанавливают.

2020-12-14 08:44 UTC, TobyThorne commented on code/modules/client/preference_setup/loadout/lists/eyegear.dm
> +	glasses["crimson glasses"] = /obj/item/clothing/glasses/sunglasses/redglasses
Больше нет

2020-12-16 00:04 UTC, kreeperHLC requested changes
Ты либо добавляй удаление рабочих ботинок в чейнджлог, либо добавляй этот странный аналог в лодаут.

2020-12-16 00:04 UTC, kreeperHLC commented on code/modules/clothing/shoes/jobs.dm
> +	name = "budget workboots"
А когда рабочие сапоги для Унатхов стали бюджетными? И если они бюджетные, тогда почему ты их не добавил в лодаут вместе с Берцами?

2020-12-16 00:57 UTC, TobyThorne commented on code/modules/clothing/shoes/jobs.dm
> +	name = "budget workboots"
Чёт я не понял, как случилось это переименование. Магия какая-то.

2020-12-16 11:55 UTC, No-Tips commented
Так, возвращай худы, куда убрал? Я слабовидящих не смогу отыгрывать, потому что такие очки не спавнятся на станции, только с лоадаута брать. +У них и так ограничения на профу. Можешь оставить только prescription варианты, но не выпиливать полностью

2020-12-16 12:06 UTC, BreddySome commented
Ну давай разберем по часятм тобою замерженное))) Складывается ощущение, что человек не играл за assистента....
В чем смысл-то от этого мержа-апдейта-или как оно, если игрокам не хватает поинтов в лодауте на косметические вещи, это не значит что надо выпилить все то, что косметическим не является и увеличить цену на все... Омг...  Выпил худов помешает тем, кто играет с need glasses персонажами, ибо персипшн худы не спавнятся на карте и их там надо в рнд исследовать да-а.... Прикольные штуки, которые теперь будут доступны только проффесиям нужны и ассистоте, да и не только ассистоте, а почти всем. Удаление и замена всего, что может защитить или увеличить урон ( берцы, нож, танковая шапка ) тоже не особо понятно зачем нужжно, складывается ощущение, чтоб ассистенты не могли взять крутые шмотки и пойти нагибать сб)))) Пж не мержите это в билд!!!!

2020-12-16 15:02 UTC, TobyThorne commented
- Очки с диоптриями теперь ухудшают зрение, если их надевает человек без близорукости. Как и было раньше.
- СекХУДы с диоптриями возвращены в лодаут, рестрикт на СБ.
- Мезоны с диоптриями возвращены в лодаут, рестрикт на технические роли.
- МедХУДы с диоптриями возвращены в лодаут, рестрикт на медиков.

2020-12-16 15:12 UTC, Doster-d approved these changes
Сойдет.

2020-12-16 17:05 UTC, TobyThorne commented
- В лодаут добавлена бюджетная версия воркбутсов.

2020-12-16 17:07 UTC, kreeperHLC approved these changes

2020-12-16 17:14 UTC, Doster-d approved these changes

2020-12-16 19:00 UTC, merged