Вирусное
ChaoticOnyx/OnyxBay pull request #4099
Opened 2020-12-25 21:37 UTC by kemperhun

* Система работы дишинкубатора была изменена. Теперь для получения радиации в него необходимо заливать радий. Также перенос любого вещества из бикера теперь происходит не автоматически, а по нажатию кнопки
* Симптомы вируса теперь сортируются по стадиям.
* Бодисканер теперь может определить не только наличие, но и стадию вируса. Если вирусов несколько, бодисканер показывает самую большую стадию. Это нужно для облегчения работы с вирусами, имеющими адаптации(см. ниже).
* Шанс спонтанной мутации в облученном организме увеличен.
* Добавлены новые симптомы:
"Facial Hypertrichosis" - Вызывает у больного рост бороды.
"Forced Freedom Syndrome" - С больного спадают наручники и стяжки.
"Gas Synthesis" - Больной выделяет определенный газ.
"Bee Infestation" - Больной кашляет пчелами. Если его рот прикрыт - получает урон по легким.
"Uncontrollable Actions" - Больной непроизвольно хватает предметы, использует машины, стреляет из пушек...
"Radioactivity Increase" - Больной излучает радиацию. В том числе на окружающих.
"Loyalty Syndrome" - Нулевой пациент становится Мастером. Все, кого он заразит, будут чувствовать боль, если не находятся с ним рядом, получают небольшой прирост пойза, если находятся и получают большой урон по мозгу, если Мастер погибнет.
"Limb Rejection" - Конечности больного отрываются аки у генокрада, к тому же их укусы разносят заразу дальше.
"Unstable Nucleotide" - В больном развивается новый вирус. В нем могут появиться более сильные симптомы, чем в обычных случайных болезнях.
"Honking Syndrome" - Больной периодически непроизвольно хонкает.
"Voice Changer Syndrome" - Больные получают голос нулевого пациента.
"Space AIDS" - Иммунитет больного уменьшается. Вирус с этим эффектом особенно заразен.
"Uncontrolable Agression" - Интент больного произвольно меняется на HARM.
"Pacifist Syndrome" - Интент больного произвольно меняется на HELP.
"Disorder of Consciousness" - Больной испытывает галлюцинации.
"Unified Appearance Syndrome" - Все больные получают одну и ту же случайную прическу.
"Cure-All Syndrome" - Исцеляет все вирусы, которыми больной заражен.
* Адаптации - особый вид симптомов. Они убирают у вируса антиген, тем самым не позволяя получить иммунитет к повторному заражению. Вылечить вирус все еще можно с помощью антибиотиков или с помощью специальных для каждой адаптации действий, однако эти действия необходимо предпринимать после достижения вирусом стадии адаптации. В этом ПРе их добавлено 4:
"[Chemical]-intolerant Adaptation" - Вирус можно вылечить введением в кровь пациента соответствующего вещества в нужном количестве.
"Hurt-intolerant Adaptation" - Вирус можно вылечить нанесением урона по какой-либо части тела пациента.
"Radiation-intolerant Adaptation" - Вирус можно вылечить облучением.
"Psyсhokinetic Connection" - С вирусом связан определенный человек. Вирус будет вылечен при его смерти.
* Все эффекты были разнесены по файлам в зависимости от их частоты. Складировать все в полтора - неудобно.
* Мутации - Новый способ получать симптомы с меньшим рандомом. Работает аналагично мутациям у растений - есть заранее известный список эффектов, в которые определенный эффект может мутировать. Чтобы произвести мутацию, необходимо добавить в дишинкубатор мутаген, заполнив соответствующую шкалу более, чем на 50%. В вирусе должен иметься хотя бы один симптом, способный к мутации, и находиться он должен на стадии, большей или равной минимальной стадии эффекта, в который он мутирует.
Схема мутаций на текущий момент:
![diagram](https://user-images.githubusercontent.com/32513474/103142090-65fcca00-4730-11eb-9260-2d976d96fec3.png)
* С помощью токсинов теперь можно сделать сдвиг стадий вируса. Стадия каждого эффекта увеличится на 1, последний симптом(если он был максимальной стадии) удалится, а на первое место встанет один из самых слабых эффектов. Это ослабляет вирус, но может быть использовано для увеличения стадии эффекта, если вирусолог хочет мутировать его во что-то с большой минимальной стадией.
* Вирусфудом можно восстановить заразительность вируса до 50. Для этого нужно продолжать кормить вирус в инкубаторе после достижения им полного роста.
* "Automated Sleeping Syndrome" теперь не будет кидать людей в вечную кому.
* Всякие мелкофиксы вещей, которые никто не замечал и не заметит.
close #3346
close #1997
close #1478
Затрагивает #2738

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.(Не тестировал старые симптомы, новые тестировал только на мейлхумане, мог пропустить что-то мелкое)
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-26 07:45 UTC, HonkyDonky commented
Тут некоторые вирусы связанны с нулевым пациентом, так что я тебя предупрежу, что у нас у каждой мышки со своим определенным шансом появляется свой новый [вирус](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/modules/mob/living/simple_animal/friendly/mouse.dm#L77) со своими симптомами, вплоть до экзотических. Так что не забудь продумать этот момент.

2020-12-26 07:48 UTC, kcalbCube commented
Было бы эффектнее сделать в каждую стадию по несколько симптомов.

2020-12-26 10:09 UTC, kemperhun commented
> Тут некоторые вирусы связанны с нулевым пациентом, так что я тебя предупрежу, что у нас у каждой мышки со своим определенным шансом появляется свой новый [вирус](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/modules/mob/living/simple_animal/friendly/mouse.dm#L77) со своими симптомами, вплоть до экзотических. Так что не забудь продумать этот момент.

Сейчас нулевой пациент определяется при первой активации симптома, поэтому мышка, как и чашка или сопля, никак нулевым пациентом стать не может. Единственное, что если она столь крута, что покусает нескольких человек, то у вируса будет несколько нулевых пациентов, каждый из которых будет распространять свою версию болезни, но я не уверен, что это должно работать как-то иначе.

2020-12-26 18:25 UTC, YouBro commented
Удивительно нормальный ПР. Давно пора заняться вирусами, молодец.

2021-01-02 04:43 UTC, kemperhun commented
Синтез газов обновлен под реалии  #4092.

2021-01-08 05:01 UTC, kcalbCube commented
@kemperhun зови ревьюверов, ПР нужно отстаивать

2021-01-09 13:20 UTC, kreeperHLC requested changes
Ну тут это..

2021-01-09 13:20 UTC, kreeperHLC commented on code/modules/virus2/effects/mild.dm
> +
![image](https://user-images.githubusercontent.com/14943437/104092671-841d0b00-5296-11eb-9c4e-a3fa46784d27.png)

2021-01-09 13:56 UTC, kemperhun commented on code/modules/virus2/effects/mild.dm
> +
Ладно...

2021-01-09 15:38 UTC, kreeperHLC approved these changes

2021-01-12 06:54 UTC, kcalbCube commented
@TobyThorne

2021-02-06 00:13 UTC, Shootnik01 commented
Уже в финальном виде фича, или еще в работе?

2021-02-13 00:35 UTC, Kexilex commented
Так близко и так далеко

2021-02-25 23:10 UTC, Doster-d approved these changes
Вроде все окей, автор обещал исправлять, если будет плохо.

2021-02-26 02:34 UTC, kcalbCube commented
Смешно то, что конфликтов нет

2021-02-26 19:01 UTC, merged