Обнова интегральных плат, номер 2.
ChaoticOnyx/OnyxBay pull request #4121
Opened 2020-12-28 22:14 UTC by Doster-d

Или "Интегральное".
Это продолжение идеи #709.
Очень нужна помощь в тестирование этого ПРа, физически и идейно не могу проверить все новые интегралки.

~~Я ебнулся.~~

[Тут будет описание всех фич, которые появится после этого обновление]
- Были добавлены новые службы функции и дефайны для улучшения кода и жизни игроков Хаотичного Оникса/ЕОС.
- ~~Появился новый раздел для работы с атмосферой у интегральных плат, форон флуд выходит на новый уровень!~~
- Появился новый раздел для работы с шахтой, теперь Вы сможете создать интегрального борга для шахтеров
- Появился новый раздел питание (что хотелось добавить автору в #709), теперь Вы можете заряжать сеть/строить бюджетную сосалку сети.
- Проведен рефакторинг всего кода интегральных схем.
- ~~Пофиксил~~ Убрал сохранение цвета интегралки.
- Добавлены новые платы, которые не указаны выше, постараюсь дать описание чуть позже.

close #3971, close #4044, close #2316, close #2144, close #2143

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-28 22:19 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/103246148-afe1ec00-498c-11eb-84f7-f2fdf5ebcef0.png)
![image](https://user-images.githubusercontent.com/45202681/103246272-149d4680-498d-11eb-9348-908a784e5cd0.png)

2020-12-30 08:06 UTC, Doster-d commented
Чуть уменьшил, немного багов пофиксил, скоро будет очень круто.

2021-01-02 14:42 UTC, Doster-d commented
И года не прошло, а ПР уже готов к ре... Как это прошел?

2021-01-02 15:16 UTC, Doster-d commented
В этот раз атмосферных плат не будет.

2021-01-02 18:21 UTC, Doster-d commented
Сделал список изменений, указал все, кроме мелких изменений в логике по типу более лучших проверок чисел.

2021-01-03 16:56 UTC, Scadouge commented
Pulling claw перестал работать вообще

2021-01-04 11:55 UTC, Scadouge commented
Не знаю было ли так задумано, но mining drill не может ломать huge rock и rocky debris.
![rock](https://user-images.githubusercontent.com/22453846/103532628-a846a980-4e9c-11eb-901e-f31f855be37b.png)

2021-01-04 12:00 UTC, Doster-d commented
> Не знаю было ли так задумано, но mining drill не может ломать huge rock и rocky debris.
> ![rock](https://user-images.githubusercontent.com/22453846/103532628-a846a980-4e9c-11eb-901e-f31f855be37b.png)

Ну естественно, он ломает только турфы с минералами, а надо ли что бы ломало их?

2021-01-04 12:05 UTC, Scadouge commented
Ну камней очень много, если делать что-то простое автономное, то они станут проблемой. На счет платы не знаю, но с ручного бура с тайла может выпасть rocky debris, который тоже заблокирует проход. Просто если обычный бур может их добывать/ломать, то почему бы и плате не дать такое?

2021-01-04 12:16 UTC, Doster-d commented
> Ну камней очень много, если делать что-то простое автономное, то они станут проблемой. На счет платы не знаю, но с ручного бура с тайла может выпасть rocky debris, который тоже заблокирует проход. Просто если обычный бур может их добывать/ломать, то почему бы и плате не дать такое?

Хорошо, сделаю, если есть какие-то вопросы или пожелания, то лучше обратитесь в личку дискорда ```Architector#4543```, тут могу не заметить.

2021-01-09 21:24 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/104108960-48645e80-52f3-11eb-8b68-3089acf2bce2.png)
Эти спрайты точно должны быть удалены? Почему должны быть удалены? Где упоминание в описании ПРа? Где квента на 1200 слов?

2021-01-09 21:30 UTC, Doster-d commented
> ![image](https://user-images.githubusercontent.com/45202681/104108960-48645e80-52f3-11eb-8b68-3089acf2bce2.png)
> Эти спрайты точно должны быть удалены? Почему должны быть удалены? Где упоминание в описании ПРа? Где квента на 1200 слов?

[Использует силу] Вы ничего не видели.

2021-01-09 21:32 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/104109078-5f578080-52f4-11eb-89a3-5a7a54a8629a.png)
Эти спрайты точно должны быть удалены? Почему должны быть удалены? Где упоминание в описании ПРа? Где квента на 1200 слов?

2021-01-09 21:36 UTC, Doster-d commented
> ![image](https://user-images.githubusercontent.com/45202681/104109078-5f578080-52f4-11eb-89a3-5a7a54a8629a.png)
> Эти спрайты точно должны быть удалены? Почему должны быть удалены? Где упоминание в описании ПРа? Где квента на 1200 слов?

Первые две интегралки были удалены еще на ТГ, я с ними солидарен, не нужно.
Охлаждения/нагрев реагентов удален из билда давно, соответственно удалены и спрайты
Два спрайта для интегралок, которые были заменены действием с инструментами.
Интерактор никогда не был использован, соответственно удалено.

2021-01-09 21:36 UTC, TobyThorne commented
>Убрал сохранение цвета интегралки.

Чё это значит? Интегралки нельзя красить? Ничего не понятно.

2021-01-09 21:38 UTC, Doster-d commented
> > Убрал сохранение цвета интегралки.
> 
> Чё это значит? Интегралки нельзя красить? Ничего не понятно.

У нас есть такой инструмент, который называется анализатор, он позволяет сохранять код интегралки, раньше он сохранял цвет, теперь не сохраняет из-за жопоболи связанное с этим действием, красить их все еще можно, я бы написал, иначе если бы удалил изменения цвета интегралок.

2021-01-09 22:12 UTC, TobyThorne commented
Ладно, доверюсь описанию и воткну дизайнерский плюсик. 
А код - какой-то блять роман (судя по объему) со сранными платами. Не буду это читать.

2021-01-10 00:38 UTC, Doster-d commented
> А код - какой-то блять роман (судя по объему) со сранными платами. Не буду это читать.

Намного меньше, чем в #709.

2021-01-13 21:31 UTC, TobyThorne submitted a review, later dismissed
Бегло почитал, критического вроде бы не должно быть.
Если всё поломается и ничего не будет работать - слапайте Достера в дискорде. Прям наверняка. Шоб пылынькало без остановок.

2021-01-14 17:17 UTC, kreeperHLC submitted a review, later dismissed

2021-01-14 17:20 UTC, Doster-d commented
Не принимайте.

2021-01-14 17:24 UTC, kreeperHLC commented
> Не принимайте.

Внутривенно иль снаружи?

2021-01-14 17:31 UTC, Doster-d commented
> Внутривенно иль снаружи?

Интегрально

2021-01-14 19:54 UTC, MACTEP-ABATAP commented
Нужно написать бота, который выбранного человека будет без остановок слапать.

2021-01-15 07:29 UTC, kreeperHLC approved these changes, later dismissed

2021-01-15 18:51 UTC, sweden-moose approved these changes, later dismissed

2021-01-16 02:36 UTC, HonkyDonky commented
Тут изменений на 3500 строчек, а вы двумя ревьювами хотите сказать, что ничего кринжового не нашли? Rlly?

2021-01-16 03:33 UTC, kreeperHLC commented
> Тут изменений на 3500 строчек, а вы двумя ревьювами хотите сказать, что ничего кринжового не нашли? Rlly?

Так это же порт, проще просто посмотреть иссуи с билда, с которого покрали. Ну и глазами пробежался чтобы не было бекдоров

2021-01-16 07:37 UTC, HonkyDonky commented
> Так это же порт

Тебе ли не знать, что порт может быть сломанным? 

К тому же автор отсебятины добавил. И может даже бекдуры, которые вы пропустили.

2021-01-18 07:53 UTC, Doster-d commented
Произошел сброс аппрувов вот, что изменилось:
- Исправил странную ошибку с двойным инитиалайзом, теперь он один.
- Добавил прок GetAccess, теперь с помощью интегралки можно открывать двери и делать прикольные вещи
- Починил новую интегральный компонент из серии "реагенты" "огнетушитель", теперь она работает.
- Починил "scanner", если там было указано, что PUT DOWN равен FALSE, то он все равно забирал себе предмет, теперь такое не наблюдается.
- Добавлено уведомление о сканирование карты в кард ридер, добавлена новая-старая интегралка, которая меняет допуск на интегралки при помощи passkey
- Исправил неправильную логику работы одного из хелпера, не существенно.

2021-01-19 07:59 UTC, Doster-d commented
Принимайте.

2021-01-22 19:05 UTC, Doster-d commented
Блять, конфликтный чел, депрессивный.

2021-01-22 19:47 UTC, Doster-d commented
Блять, не конфликтный чел, веселый (gay).

2021-01-25 07:57 UTC, TobyThorne commented on code/modules/integrated_electronics/core/analyzer.dm
> +			user << browse(saved, "window=circuit_scan;size=500x600;border=1;can_resize=1;can_close=1;can_minimize=1")
почему

2021-01-25 08:01 UTC, TobyThorne commented on code/modules/integrated_electronics/subtypes/memory.dm
> +	..()
почему

2021-01-27 11:56 UTC, DeltaEpsilon7787 requested changes

2021-01-27 11:56 UTC, DeltaEpsilon7787 commented on code/modules/integrated_electronics/core/helpers.dm
> +		r += ascii2text(text2ascii(string,i) ^ text2ascii(key,((i-1)%length(string))+1))
length(string) явно должен быть length(key), иначе смысла от этого никакого нет. Иначе строки длиной больше чем key будет вызывать выход за пределы строки.

2021-01-27 12:43 UTC, Doster-d commented on code/modules/integrated_electronics/core/helpers.dm
> +		r += ascii2text(text2ascii(string,i) ^ text2ascii(key,((i-1)%length(string))+1))
Ладно.

2021-01-27 15:06 UTC, Doster-d commented on code/modules/integrated_electronics/core/analyzer.dm
> +			user << browse(saved, "window=circuit_scan;size=500x600;border=1;can_resize=1;can_close=1;can_minimize=1")
Потому, исправил.

2021-01-27 15:07 UTC, Doster-d commented on code/modules/integrated_electronics/subtypes/memory.dm
> +	..()
Моча в голову ударило, поэтому и изменил (так было на ТГ)

2021-01-27 15:07 UTC, Doster-d commented on code/modules/integrated_electronics/core/helpers.dm
> +		r += ascii2text(text2ascii(string,i) ^ text2ascii(key,((i-1)%length(string))+1))
Исправил.

2021-01-27 20:18 UTC, Doster-d commented
- Увеличил лимиты у платы соединения текста в 2 раза
- Пофиксил фейковое сообщение об пожирания стали принтером
- Граббер теперь забирает  предмет, только если он на земле (предыдущие проверки сохранены).

2021-01-31 05:45 UTC, TobyThorne approved these changes, later dismissed

2021-01-31 05:54 UTC, Doster-d commented
1 есть, остался еще 1, таким темпами я не смогу закончить свой смежный проект (шутка)

2021-02-03 12:43 UTC, TobyThorne approved these changes
каемся и молимся

2021-02-03 13:22 UTC, kreeperHLC approved these changes

2021-02-03 13:26 UTC, TobyThorne commented
ой пиздец

2021-02-03 13:28 UTC, merged