Дионовое
ChaoticOnyx/OnyxBay pull request #4135
Opened 2020-12-31 00:22 UTC by TobyThorne

- Исправлена регенерация нимф. Урон больше не будет уходить в отрицалово.
- Исправлен выбор имени у дион. Теперь маленькая диона не будет оставаться рядом с повзрослевшей собой же, пока та не выберет имя.
- Добавлена возможность выбора имени после использования способности Split.
- Добавлены кнопки для выплёвывания предмета и снятия шапки во вкладку Abilities. 
- Исправлен голод у дион. Теперь он не будет стабильно доходить до критического объедания, замедляющего деревянных инвалидов ещё сильнее.
- Респрайт взрослых дион. Теперь они больше похожи на своих братьев меньших.
- Интерфейс у нимф теперь использует уникальные иконки вместо алиумовских. В будущем, конечно, надо будет ещё доработать.
- Дионы без игрока теперь чаще перемещаются и эмоутят.

![diona](https://user-images.githubusercontent.com/45202681/103387888-6cc07e00-4b30-11eb-9624-c66e1d27c952.png)
![image](https://user-images.githubusercontent.com/45202681/103387898-7c3fc700-4b30-11eb-8b12-5ca0640ca3f2.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2020-12-31 00:26 UTC, Doster-d submitted a review, later dismissed
По коду нормально.

2021-01-02 01:38 UTC, kreeperHLC requested changes

2021-01-02 01:38 UTC, kreeperHLC commented on code/_onclick/hud/diona_nymph.dm
> +	mymob.client.screen += list( mymob.healths, mymob.fire)
```suggestion
	mymob.client.screen += list(mymob.healths, mymob.fire)
```

2021-01-02 09:47 UTC, Doster-d approved these changes
Все еще нормально.

2021-01-03 21:28 UTC, kreeperHLC approved these changes

2021-01-03 21:30 UTC, merged