Еще один смешной фикс бумаги
ChaoticOnyx/OnyxBay pull request #4156
Opened 2021-01-02 23:31 UTC by PlinHost

Хтмл есть, а параметра нет.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-01-03 00:06 UTC, TobyThorne approved these changes

2021-01-03 19:49 UTC, 4310V343k commented
Ноуп
![image](https://user-images.githubusercontent.com/56449763/103487382-f795c700-4e15-11eb-8ae2-2caf52a6d07a.png)

2021-01-03 19:50 UTC, 4310V343k requested changes
![image](https://user-images.githubusercontent.com/56449763/103487385-067c7980-4e16-11eb-9f9d-6ad4a0975bdf.png)

2021-01-12 14:55 UTC, HonkyDonky commented
>PlinHost
 :ballot_box_with_check: Я запускал сервер со своими изменениями локально и все протестировал.
 
 **~~???~~**

2021-01-12 15:56 UTC, PlinHost commented
> > PlinHost
> > ballot_box_with_check Я запускал сервер со своими изменениями локально и все протестировал.
> 
> **~???~**

Пофиксил.

2021-01-12 16:52 UTC, HonkyDonky approved these changes
вот теперь нормально

2021-01-12 23:20 UTC, merged