tweak(crew records) security updates
ChaoticOnyx/OnyxBay pull request #4228
Opened 2021-01-09 17:10 UTC by Doster-d

Добавил санитайза.

close #4227

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-01-09 17:27 UTC, kreeperHLC submitted a review, later dismissed

2021-01-09 21:06 UTC, kcalbCube approved these changes
Даже не знаю куда влепить жука

2021-01-10 19:55 UTC, HonkyDonky requested changes
И всё же не поленись быстро проверить свои изменения на локалке, брух.

2021-01-10 19:55 UTC, HonkyDonky commented on code/modules/modular_computers/file_system/crew_record.dm
> +		return F.set_value(sanitize(html_decode(value)))
Зачем тут, если можно в `set_value()`?

2021-01-10 19:55 UTC, HonkyDonky commented on code/modules/modular_computers/file_system/crew_record.dm
> +	newval = sanitize(html_decode(newval))
Убери `html_decode()`. Он и так по дефолту вызывается в `sanitize()`.

2021-01-10 19:58 UTC, Doster-d commented on code/modules/modular_computers/file_system/crew_record.dm
> +	newval = sanitize(html_decode(newval))
![image](https://user-images.githubusercontent.com/63081538/104133880-64214080-5397-11eb-9832-f1b79f5bcf16.png)
Где?

2021-01-10 20:01 UTC, HonkyDonky commented on code/modules/modular_computers/file_system/crew_record.dm
> +	newval = sanitize(html_decode(newval))
А.

2021-01-10 20:15 UTC, No-Tips commented
Ха-ха, да, не принимайте фиксы, да!

2021-01-10 20:17 UTC, HonkyDonky commented
> Ха-ха, да, не принимайте фиксы, да!

Мы решили, что возможность включить порнхаб на модулярном компьютере - отличная фича. Потому санитайза не будет.

2021-01-10 20:33 UTC, No-Tips commented
Тогда уж перенесите это на серверсайд, чтобы можно было устроить всестанционный просмотр фурри ебли

2021-01-11 02:39 UTC, HonkyDonky approved these changes
всё ок человек протестировал ошибок быть не может верим на слово мы тут люди честные без вранья и лжи

2021-01-12 20:49 UTC, TobyThorne approved these changes

2021-01-12 20:50 UTC, merged

2021-01-12 21:46 UTC, No-Tips commented
😢 Больше без смешного в крю манифесте, будем искать дальше