tweak(medical cyborgs) surgery model merged into medical model
ChaoticOnyx/OnyxBay pull request #4243
Opened 2021-01-12 05:29 UTC by Doster-d

Была удалена хирургическая модель киборга.
Были перемещены модули с хирургического модели на медицинский модель.
Добавлен новый инструмент для медицинских киборгов, которые заменяет им целый набор хирургических инструментов.

close #3464

Нужен спрайт для нового инструмента.
После мержа было бы классно впилить радиальное меню выбора хирургического инструмента (#3781)
- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-01-12 21:08 UTC, eckff commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	to_chat(user, SPAN_NOTICE("You select to use [selected_tool ? selected_tool : "nothing"]"))
Подсоблю кодом который можно будет использовать после мержа радиалов:
```suggestion
	var/list/options = list()
	for(var/atom/movable/AM in surgery_items)
		var/image/radial_button = image(icon = AM.icon, icon_state = AM.icon_state)
		radial_button.name = AM.name
		options[AM] = radial_button

	selected_tool = show_radial_menu(user, src, options, radius = 42, require_near = TRUE, tooltips = TRUE)
	to_chat(user, SPAN_NOTICE("You select to use [selected_tool ? selected_tool : "nothing"]."))
```

2021-01-12 21:10 UTC, Doster-d commented
Нашел прикольный спрайт для этого инструмента.

2021-01-12 21:11 UTC, Doster-d commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	to_chat(user, SPAN_NOTICE("You select to use [selected_tool ? selected_tool : "nothing"]"))
Можно сразу определять /obj/item/weapon, а не использовать atom/movable.

2021-01-12 21:12 UTC, TobyThorne commented on code/_global_vars/lists/flavor.dm
>  	"Research"
Ну будь человеком, ну выровняй список.

2021-01-12 21:13 UTC, TobyThorne commented
Аппруваю по-гейски. А код потом по тестю.

2021-01-12 21:16 UTC, eckff commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	to_chat(user, SPAN_NOTICE("You select to use [selected_tool ? selected_tool : "nothing"]"))
Сорян, я использовал немного модифицированный код на базе твоего, где путя /device вообще нет.
Но согласен, можно было просто /obj/item вставить и всё было бы круто.

2021-01-12 21:18 UTC, Doster-d commented on code/_global_vars/lists/flavor.dm
>  	"Research"
Я не человек, как это сделать?

2021-01-12 21:21 UTC, eckff commented on code/_global_vars/lists/flavor.dm
>  	"Research"
```suggestion
	"Standard", 
	"Engineering", 
	"Medical",
	"Miner",    
	"Janitor",     
	"Service", 
	"Security",
	"Research"
```

2021-01-12 21:22 UTC, eckff commented on code/_global_vars/lists/flavor.dm
>  	"Research"
Плодить строки умеем!

2021-01-12 21:23 UTC, Doster-d commented on code/_global_vars/lists/flavor.dm
>  	"Research"
Сделал.

2021-01-12 21:23 UTC, Doster-d commented on code/_global_vars/lists/flavor.dm
>  	"Research"
Сделал

2021-01-12 21:25 UTC, Doster-d commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	to_chat(user, SPAN_NOTICE("You select to use [selected_tool ? selected_tool : "nothing"]"))
Ну это потом Голиаф сделает в своем ПРе, после мержа моего.

2021-01-16 13:52 UTC, HonkyDonky commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	. += "\nThe selected tool is [selected_tool ? selected_tool : "nothing"]!"
Это копипаст? У нас же вроде не так экзамайн работает.

2021-01-16 20:41 UTC, Doster-d commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	. += "\nThe selected tool is [selected_tool ? selected_tool : "nothing"]!"
Я спиздил идею этого с экзамайна хуманов, оно работает.

2021-01-16 20:44 UTC, MACTEP-ABATAP commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	. += "\nThe selected tool is [selected_tool ? selected_tool : "nothing"]!"
> Я спиздил идею этого с экзамайна хуманов, оно работает.

It just work
It just work

2021-01-21 19:28 UTC, HonkyDonky approved these changes

2021-01-24 21:57 UTC, TobyThorne requested changes
В общем-то, на удивление хорошо. Мне нравится.
Однако, невозможность бить выбранным инструментом по объектам - такое. Хочу нарезать пиццу скальпелем и выпиливать окошки пилой.

Ну и принимать стоит вместе с радиальными меню, а то нынешний выбор кукожный.

2021-01-24 21:57 UTC, TobyThorne commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	name = "Surgery tool selector"
```suggestion
	name = "surgery tools selector"
```

2021-01-24 22:00 UTC, Doster-d commented
> Ну и принимать стоит вместе с радиальными меню, а то нынешний выбор кукожный.

Планировалось, что при принятие этого ПРа будет +1 причина принять радиальное меню (с заменой выбора инструмента, естественно)

2021-01-24 22:12 UTC, Doster-d commented
Сделал, теперь можно бить стекло и ~~казнить таяр~~ проводить операции.

2021-01-31 20:34 UTC, TobyThorne commented
Радиальные меню накачены, можно обновлять ПР.

2021-01-31 20:35 UTC, Doster-d commented
> Радиальные меню накачены, можно обновлять ПР.

готе ит

2021-01-31 23:46 UTC, Doster-d commented
Пора.
- Добавил новую переменную для радиального меню, которое убирает это меню, если объект покидает поле видимости персонажа.
- Добавил новый прок для предметов, что бы они возвращали реальный предмет, если src является "виртуальным" предметом.
- Немного изменил способ активации списка инструментов, теперь можно кликнуть по себе для вывода списка, через attack_self оставил

2021-02-02 07:05 UTC, TobyThorne approved these changes
пральна
@
пральна блять

2021-02-02 07:09 UTC, kreeperHLC approved these changes

2021-02-02 07:12 UTC, merged