Changelog 13/01/21
ChaoticOnyx/OnyxBay pull request #4261
Opened 2021-01-13 20:38 UTC by TobyThorne

2021-01-13 20:41 UTC, TatarTheBuilder approved these changes

2021-01-13 20:43 UTC, kreeperHLC approved these changes

2021-01-13 20:47 UTC, kcalbCube requested changes
Выглядит прикольно, можно и аппрувнуть

2021-01-13 20:47 UTC, kcalbCube commented on html/changelog.html
> +				<li class="bugfix">Призраки больше не могут взаимодействовать с РАСТами.</li>
шо такое РАСТы? Это на них плыть?

2021-01-13 20:47 UTC, kcalbCube commented on html/changelog.html
> +				<li class="bugfix">Исправлена вставка html в Crew Records.</li>
Может, правильно будет "исправлен баг позволяющий вставлять html в Crew Records"? А то звучит будто это фичу сделали.

2021-01-13 21:14 UTC, merged

2021-01-14 12:19 UTC, MrMagick2104 commented on html/changelog.html
> +				<li class="bugfix">Призраки больше не могут взаимодействовать с РАСТами.</li>
РАСТ - это тип реактора. На вики есть, если что.