Барсигное
ChaoticOnyx/OnyxBay pull request #4267
Opened 2021-01-14 10:08 UTC by kreeperHLC

Добавляет новые таблички для выбора в Бар. Вот они слева направо не учитывая первую:
![image](https://user-images.githubusercontent.com/14943437/104576490-4b4fae00-5669-11eb-976c-1e794bacd186.png)
Три из них, а именно The Syndi Cat, Vlad's Salad Bar и Combo Cafe доступны только трейторам. Заодно для этого создал прок на проверку человека для трейтора по аналогии с культистким. Может когда-нить пригодится.

- [ ч ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [  ч] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ч ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ч] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-01-15 21:32 UTC, TobyThorne commented
[Ч]ёт не понял, почему два Maltese Falcon'а.

2021-01-15 22:49 UTC, N1ght1ngal3 commented
У вас луфчанка..

2021-01-16 03:30 UTC, kreeperHLC commented
> [Ч]ёт не понял, почему два Maltese Falcon'а.

По той же причине, почему в оригинальном дми два карпа. РаЗнОоБрАзИе.

2021-01-16 03:31 UTC, kreeperHLC commented
> У вас луфчанка..

Этот спрайт на всех остальных билдах (Ну кроме Торча, там ничего нет) есть. Да, я три билда вскрывал ради этой обновы.

2021-01-22 07:19 UTC, TapKo4eB commented
Имхо с логической точки зрения лучше было бы анлокать триторские спрайты через емаг вывески, а не по тому что оп имеет рольку, банально по той причине что емагом можно ломать все.

2021-01-26 13:48 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/105852227-67126700-600e-11eb-9180-3ff14a8e6903.png)
вот эту хуиту убери пожалуйста, она торчать будет

![image](https://user-images.githubusercontent.com/45202681/105852953-53b3cb80-600f-11eb-8705-8f03c3463e8e.png)
и вот эта ебота наверное на рандоме не должна выпадать

2021-01-26 13:52 UTC, kreeperHLC commented
> ![image](https://user-images.githubusercontent.com/45202681/105852227-67126700-600e-11eb-9180-3ff14a8e6903.png)
> вот эту хуиту убери пожалуйста, она торчать будет
> 
> ![image](https://user-images.githubusercontent.com/45202681/105852953-53b3cb80-600f-11eb-8705-8f03c3463e8e.png)
> и вот эта ебота наверное на рандоме не должна выпадать

Первое проверил ингейм. Торчит, да, но торчит нормально. Могу просто из рандома убрать, любители трапов сами выставлять пусть будут. А второе да, пофикшу.

2021-01-27 17:55 UTC, kreeperHLC commented
Добавил взлом через емаг, добавил ??? в список емагнутых, добавил переменную для раундстартовой проверки, из раундстратового пулла выпилил фею.

2021-01-27 17:57 UTC, HonkyDonky commented
Прок неиспользуемый стереть не забудь.

2021-01-27 17:59 UTC, kreeperHLC commented
> Прок неиспользуемый стереть не забудь.
А надо ли? Может пригодится кому

2021-01-27 18:00 UTC, HonkyDonky commented
Если кому-то и вправду надо будет - он его сделает.

2021-01-27 18:01 UTC, kreeperHLC commented
> Если кому-то и вправду надо будет - он его сделает.

Убрал

2021-01-27 18:15 UTC, HonkyDonky requested changes

2021-01-27 18:15 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +/obj/structure/sign/double/barsign/proc/get_valid_states(initial=1, mob/living/user = null, var/roundstart = FALSE)
> var/roundstart = FALSE

> [ч] Я ознакомился c Guide to Contribute.

2021-01-27 18:15 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +	icon_state = pick(get_valid_states(roundstart = TRUE))
Инициализация вызывается не только при раундстарте, если что.

Используй `mapload` в своих целях. Примеры найдёшь в коде.

2021-01-27 18:15 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +		to_chat(user, "<span class='notice'>You overload the access verification system and open access to special propaganda.</span>")
Используй макросы для спанов.

2021-01-27 18:15 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +		if(!sign_type)
Сюда бы ещё куда-нибудь проверку на то, что находится ли пользователь возле вывески. А то-ж он может открыть менюшку с выбором, отойти на край света и сменить вывеску.

2021-01-27 18:15 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +		to_chat(user, "<span class='notice'>You change the barsign.</span>")
Спаны.

2021-01-27 18:15 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +		return
Я не уверен, но здесь кажется нужно вернуть TRUE, чтобы использовался заряд у емага. Посмотри сам.

2021-01-27 18:22 UTC, kreeperHLC commented on code/game/objects/structures/barsign.dm
> +	icon_state = pick(get_valid_states(roundstart = TRUE))
Да оно просто не должно рандомно выбираться при создании. Перепишу чтоб понятно было

2021-01-28 05:50 UTC, kreeperHLC commented on code/game/objects/structures/barsign.dm
> +		return
В машинерии используется emag_act для взлома и траты заряда. Табличка, к сожалению, не машинерия

2021-02-28 19:45 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/109431260-c90c2500-7a2f-11eb-84f1-84210b8deadc.png)
повороты где повороты запили

2021-03-27 00:21 UTC, TobyThorne requested changes
где диры сделай диры!!!

2021-04-17 05:49 UTC, TobyThorne commented
С 1 марта никакой активности. Пока закрываю, если что - всегда можно переоткрыть.

2021-04-21 13:18 UTC, kreeperHLC commented
Вернул диры. Также совместил два хармбатона в один.
![image](https://user-images.githubusercontent.com/14943437/115560401-382e2900-a2bd-11eb-875d-791ce881c168.png)

2021-04-22 12:29 UTC, TobyThorne commented
А зачем у The Bark красивое свечение убрал?

2021-04-22 12:46 UTC, kreeperHLC commented
> А зачем у The Bark красивое свечение убрал?

Одинаковое для 90% табличек свечение* 
А так хотя бы какое-то разнообразие среди таких штук.

2021-04-23 11:16 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/115863631-8ecf6a80-a457-11eb-8086-27dfccfde92c.png)
а что тут со стейтами, почему оно такое

2021-04-23 11:21 UTC, Doster-d commented
> ![image](https://user-images.githubusercontent.com/45202681/115863631-8ecf6a80-a457-11eb-8086-27dfccfde92c.png)
> а что тут со стейтами, почему оно такое

У меня все нормально...

2021-04-23 11:26 UTC, TobyThorne approved these changes
Проверил сам .dmi, таки всё нормально. ИконДиф гонит.

2021-04-23 11:28 UTC, Doster-d approved these changes
Тоби

2021-04-23 15:16 UTC, HonkyDonky requested changes

2021-04-23 15:16 UTC, HonkyDonky commented on code/game/objects/structures/barsign.dm
> +	if(istype(I, /obj/item/weapon/card/emag) && !emagged)
Здесь нет проверки на количество оставшихся зарядов у емага, т.е. получается, что можно пустым емагом провести и у того заряд в минус улетит.

2021-05-06 01:01 UTC, kreeperHLC commented
Переписан код на емаг акт и добавлен емп акт

2021-05-13 08:10 UTC, HonkyDonky approved these changes

2021-05-14 09:25 UTC, igorsaux approved these changes

2021-05-14 11:00 UTC, TobyThorne requested changes
Всё ещё жду диры и выпил табличек, которых не было на момент гей-аппрува

2021-05-23 13:40 UTC, TobyThorne commented
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2021-05-26 13:50 UTC, kreeperHLC commented
Всё исправлено

2021-05-29 20:13 UTC, TobyThorne approved these changes

2021-05-31 20:24 UTC, HonkyDonky approved these changes

2021-06-01 14:05 UTC, Doster-d approved these changes

2021-06-18 20:49 UTC, TobyThorne approved these changes

2021-06-18 20:50 UTC, merged