Шизард-клирик рефаfuckторинг
ChaoticOnyx/OnyxBay pull request #4348
Opened 2021-01-27 14:59 UTC by Destrolaric

Переделка клириков под текущий билд, фикс бага с неработающим лечением, ребаланс некоторых заклинаниев
close #4311 

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-06 00:11 UTC, Shootnik01 commented
Пулл умер?

2021-02-07 15:24 UTC, Destrolaric commented
Не, я словил Warframe, скоро вернусь. Может быть...

2021-02-09 17:00 UTC, Shootnik01 commented
Ждем

2021-02-09 17:01 UTC, Destrolaric commented
Все запрошенное кроме mind control
Делаем его?

2021-02-09 17:03 UTC, Shootnik01 commented
Сколько по времени займет?

2021-02-09 17:07 UTC, Destrolaric commented
НУ как сказать... Не уверен, вероятно денёчек.

2021-02-09 17:25 UTC, Shootnik01 commented
Тогда, лучше доделать

2021-02-10 09:19 UTC, Destrolaric commented
Осталось иконки дорисовать и почистить пробелы в коде.

2021-02-10 11:26 UTC, Shootnik01 commented
Круть! Ждем

2021-02-11 20:29 UTC, Shootnik01 commented
Алло. Ну как там с клириком?

2021-02-11 21:02 UTC, Destrolaric commented
Всё кроме текстурок так-то готово...

2021-02-18 17:15 UTC, Doster-d commented
Буду ревьювить после одобрения от геймдизайнеров.

2021-02-23 15:54 UTC, TobyThorne commented
Геймдизно выглядит балдёжно, но код трогать я ебу.

2021-02-23 15:55 UTC, TobyThorne commented on code/game/gamemodes/wizard/wizard_heals.dm
> +	to_chat(src, "[src] is beign healed")
beign 
![image](https://user-images.githubusercontent.com/45202681/108869915-da18f880-7621-11eb-87f0-4b3a4f6186fb.png)

2021-02-23 15:56 UTC, TobyThorne commented
Да, точно ебал смотреть код. Кто всё же будет - подоёбывайтесь к лишним пробелам в ифах и форах и всякому такому.

2021-02-23 16:47 UTC, Destrolaric commented on code/game/gamemodes/wizard/wizard_heals.dm
> +	to_chat(src, "[src] is beign healed")
Опа, дебаг to_chat забыл.

2021-02-23 17:17 UTC, Doster-d requested changes
Излишний код.

2021-02-23 17:17 UTC, Doster-d commented on code/game/gamemodes/wizard/wizard_heals.dm
> +		if(E.status & ORGAN_BROKEN && heal.heal_bones) // some calcium
Излишний комментарий

2021-02-23 17:17 UTC, Doster-d commented on code/game/gamemodes/wizard/wizard_heals.dm
> +/mob/living/carbon/human/proc/wizard_heal(spell/targeted/heal)
Не хватает проверки на то, что heal вообще соответствует типу, и что он вообще есть.

2021-02-23 17:17 UTC, Doster-d commented on code/modules/spells/hand/hand.dm
> +	var/spell_cast_delay
Зачем эта переменная? Ее никто не назначает...

2021-02-23 17:48 UTC, Destrolaric commented on code/modules/spells/hand/hand_item.dm
> -	if(user.a_intent == I_HELP)
Ибо, смысла в этом в крайне мало, зачастую мешает больше

2021-02-23 17:49 UTC, Destrolaric commented on code/modules/spells/targeted/mind_control.dm
> +/obj/item/weapon/implant/magical_imprint/Process()
Иначе наплодится много копипасты, прям совсем.

2021-02-23 17:50 UTC, Doster-d commented on code/modules/spells/targeted/mind_control.dm
> +/obj/item/weapon/implant/magical_imprint/Process()
Так просто дай менюшку для изменения законов в спелле, держи этот имплант в заклинание, а потом вставляй в человека, не?

2021-02-25 17:45 UTC, kreeperHLC requested changes
Чейндж реквест го брррр

2021-02-25 17:45 UTC, kreeperHLC commented on code/game/gamemodes/wizard/wizard_heals.dm
> +	if (!heal)
```suggestion
	if(!heal)
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/game/gamemodes/wizard/wizard_heals.dm
> +	for (var/A in organs)
```suggestion
	for(var/A in organs)
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/hand/hand_item.dm
> +		if (hand_spell.spell_cast_delay)
```suggestion
		if(hand_spell.spell_cast_delay)
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/hand/hand_item.dm
> +			if (do_after(user, hand_spell.spell_cast_delay, M))
```suggestion
			if(do_after(user, hand_spell.spell_cast_delay, M))
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/cleric_spells.dm
> +	if (!heal_bones)
```suggestion
	if(!heal_bones)
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	var/list/instructions = list("Serve the Wizard Federation!.")
```suggestion
	var/list/instructions = list("Serve the Wizard Federation!")
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	if (target == user)
```suggestion
	if(target == user)
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	var/mob/living/target = a
```suggestion
/spell/hand/mind_control/cast_hand(atom/A, mob/user)
	var/mob/living/target = A
```
Но вообще лучше сразу к нужному типу привести, а то неоч.

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +		to_chat(user,SPAN_DANGER("You tried to control yourself, thankfully spell didn't worked!"))
```suggestion
		to_chat(user, SPAN_DANGER("You tried to control yourself, thankfully spell didn't worked!"))
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	if (href_list["add"])
```suggestion
	if(href_list["add"])
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	if (href_list["edit"])
```suggestion
	if(href_list["edit"])
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	if (href_list["del"])
```suggestion
	if(href_list["del"])
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	if (imp_in.reagents.has_reagent(/datum/reagent/water/holywater))
```suggestion
	if(imp_in.reagents.has_reagent(/datum/reagent/water/holywater))
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +		if (imp_in.mind)
```suggestion
		if(imp_in.mind)
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/mind_control.dm
> +	if (ishuman(M))
```suggestion
	if(ishuman(M))
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/shapeshift.dm
> +	)
А можно тут и первый элемент с новой строки?

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/shapeshift.dm
> +	/mob/living/simple_animal/hostile/asteroid/goliath/alpha)
А тут скобка не ушла вниз.

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/targeted.dm
> +	var/heal_bones = 0 //give you healthy dose of calcium to fix you bones
```suggestion
	var/heals_internal_bleeding = 0
	var/heals_external_bleeding = 0
	var/heal_bones = 0
```

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/targeted.dm
> +	to_chat(user, targets)
А это для чего?

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/targeted.dm
> +	to_chat(target, "sda")
Это ты выпилить забыл как я понял?

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/targeted.dm
> +		//H.regenerate_blood(amt_blood)
Ммм, закомментим код чтобы потом о нём забыть.

2021-02-25 17:45 UTC, kreeperHLC commented on code/modules/spells/targeted/targeted.dm
> +		//H.radiation += min(H.radiation, amt_radiation)
И тут да.

2021-02-25 18:07 UTC, kreeperHLC commented on code/modules/spells/targeted/shapeshift.dm
> +	possible_transformations = list (
```suggestion
	possible_transformations = list(
```

2021-02-25 18:21 UTC, Destrolaric commented
Чёртов трэвис, опять прилёг на бочок.

2021-02-26 18:50 UTC, kreeperHLC submitted a review, later dismissed

2021-03-04 09:36 UTC, Doster-d approved these changes
Ладно

2021-03-04 17:27 UTC, Doster-d requested changes
Имплант - говно.

2021-03-05 11:21 UTC, Doster-d requested changes
Не

2021-03-05 11:21 UTC, Doster-d commented on code/modules/spells/targeted/mind_control.dm
> +	STOP_PROCESSING(SSobj, src)
Вы не обьекты

2021-03-05 11:21 UTC, Doster-d commented on code/modules/spells/targeted/mind_control.dm
> +	START_PROCESSING(SSobj, src)
Вы не обьекты

2021-03-05 11:21 UTC, Doster-d commented on code/modules/spells/targeted/mind_control.dm
> +	var/mob/living/carbon/human/imp_in
implanted_in лучше

2021-03-05 15:36 UTC, Doster-d approved these changes
Не вижу проблем в ПРе.

2021-03-05 17:40 UTC, kreeperHLC approved these changes

2021-03-05 17:50 UTC, merged