Обновление интегралок, 2.5
ChaoticOnyx/OnyxBay pull request #4393
Opened 2021-02-04 20:04 UTC by Doster-d

- Была возвращена менюшка, где были все кнопочки и т.д.
- Был добавлен переключатель между УИ через список (который сейчас) и на новый старый.
- Была исправлена логическая ошибка при определение урона у улучшенного медицинского сканера.
- Добавлен кулдаун для перевода энергии из батареи в устройства, должно помочь исправить [УДАЛЕНО].

close #4389

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-05 23:32 UTC, Doster-d commented
Добавлено радиальное меню для первого UI.
За спрайты спасибо @Animesku 
![image](https://user-images.githubusercontent.com/63081538/107099669-5d191100-6823-11eb-8411-17f379d3727e.png)

2021-02-06 00:09 UTC, Shootnik01 commented
- This is обнова интегралок
- Dear God!
- There is more
- No...



https://youtu.be/JmSqorj-EC0

2021-02-06 21:27 UTC, Doster-d commented
![суета](https://user-images.githubusercontent.com/63081538/107130067-4cc46d00-68db-11eb-8968-677895a3c8e8.png)

2021-02-07 21:15 UTC, Doster-d commented
Исправил суету.

2021-02-09 14:08 UTC, kreeperHLC submitted a review, later dismissed

2021-02-09 14:09 UTC, Doster-d commented
Еще в разработке, обнаружил много приколов.

2021-02-13 14:10 UTC, Doster-d commented
- Добавлена плата для итерация списка
- Добавлена плата получения дубликатов из списка
- Добавлена плата получения всех предметов с определенным типом (выполнено через ref к плате фильтра) в радиусе поле зрения интегральной схемы
- Добавлено количество всей руды в шахтерской сумке
- Мелкие исправления

2021-02-14 01:00 UTC, Doster-d commented
В принципе, осталось добавить анальное логирования ко всем действиям и можно ревьювать

2021-02-14 19:56 UTC, Kexilex commented
когда же когда

2021-02-17 20:09 UTC, Doster-d commented
- Починил интегралки для киборгов.
- Добавил больше логирования.

Можно ревьювать.

2021-02-17 22:06 UTC, Shootnik01 commented
Так запрашивай

2021-02-23 16:08 UTC, TobyThorne approved these changes
тостер ебашб мы в тебя верим

2021-02-25 18:05 UTC, kreeperHLC requested changes
Приколы закончились, дальше только фиксы

2021-02-25 18:05 UTC, kreeperHLC commented on code/modules/integrated_electronics/subtypes/input.dm
> +// Hi, Doster-d components retractor script. How are you?
Ну ты пчел

2021-02-25 18:05 UTC, kreeperHLC commented on code/modules/integrated_electronics/subtypes/input.dm
> +	set_pin_data(IC_OUTPUT, 1, )
Это такой сложный прикол, который я не в состоянии понять?

2021-02-25 18:05 UTC, kreeperHLC commented on code/modules/integrated_electronics/subtypes/input.dm
> +		if (istype(com, /obj/machinery/computer/teleporter) && com.locked && !com.one_time_use && com.operable())
```suggestion
		if(istype(com, /obj/machinery/computer/teleporter) && com.locked && !com.one_time_use && com.operable())
```

2021-02-25 18:08 UTC, Doster-d commented on code/modules/integrated_electronics/subtypes/input.dm
> +// Hi, Doster-d components retractor script. How are you?
Не трогай, иначе билд сломается

2021-02-25 18:21 UTC, kreeperHLC approved these changes

2021-03-12 11:51 UTC, DarkHunter7756 commented
Ждем, надеемся, мечтаем, стареем, умираем

2021-03-20 14:30 UTC, kreeperHLC approved these changes

2021-03-20 14:46 UTC, HonkyDonky commented on code/modules/integrated_electronics/core/printer.dm
> +	return CanUseTopic(user) && (get_dist(src, user) < 2)
Эту проверку как раз таки нужно затолкать в CanUseTopic

2021-03-20 14:46 UTC, HonkyDonky commented on code/modules/integrated_electronics/subtypes/mining.dm
> +	qdel(box)
`QDEL_NULL(box)` тогда уж

2021-03-20 14:46 UTC, HonkyDonky commented on code/modules/integrated_electronics/subtypes/input.dm
> +		new_input = sanitize(new_input)
Санитайзь сразу же у `input()`, типа `sanitize(input())`
И `as text|null` у `input()` введи, а затем проверку `istext()` что чуть ниже замени на `if(new_input && ...)`

2021-03-20 14:46 UTC, HonkyDonky commented on code/modules/integrated_electronics/subtypes/input.dm
> +		var/new_input = input(user, "Enter a number, please.", displayed_name)
`as num|null`

2021-03-20 14:59 UTC, Doster-d commented on code/modules/integrated_electronics/core/printer.dm
> +	return CanUseTopic(user) && (get_dist(src, user) < 2)
Данная проверка никак не связана с топиком, а связано как раз с объектом, поэтому считаю, что проверка на нужном месте.

2021-03-20 15:01 UTC, HonkyDonky approved these changes

2021-03-20 15:01 UTC, kreeperHLC approved these changes

2021-03-20 15:50 UTC, merged