Сделать столовые приборы из стали более заметными и менее серыми.
ChaoticOnyx/OnyxBay pull request #4449
Opened 2021-02-12 06:46 UTC by Artemonim

`close #4217`

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-12 06:59 UTC, Doster-d requested changes
Спрайты кукож.

2021-02-12 07:29 UTC, Artemonim commented
> Спрайты кукож.

Чо?

2021-02-12 16:35 UTC, kreeperHLC commented
> > Спрайты кукож.
> 
> Чо? Не понял правки

Спрайты сами по себе не очень, слишком мелкие чтобы кликать да и выглядят странно в сравнении с другими. Типо этой заточкой кого-то убивать? Ну чтож, геймдизы решат.

2021-02-12 16:55 UTC, MrMagick2104 commented
Спрайты такие себе, имхо. У ложки слишком маленькая ручка, больше похожа на чайную.
У вилки вообще два зубчика, камертон какой-то, а не вилка, ручка тоже маленькая.
> Типо этой заточкой кого-то убивать

Ну так и столовый ножик и должен быть просто для резки, а не убийства, у него и урон низенький очень. По-моему, он выглядит самым нормальным из трёх.

В чём проблема изначально была, кстати, неясно. Спрайты такие себе были, но размер у них - наименьший недочёт, как мне кажется.

Нажимать на спрайты не будет сложно? Маленькие.
> ```close #4217```

А оно так работать будет, иссуй автозакроет? По-моему, если в маркдауне выделить что-то левым косым слэшем или тремя апострофами, то функционал меняется на цитирование 1 в 1.

2021-02-12 17:02 UTC, kcalbCube commented
@MrMagick2104 спасибо что всегда пишешь длинные и развёрнутые комментарии! Нам, разработчикам очень важно и мы очень благодарны тебе за все!

2021-02-12 17:03 UTC, kreeperHLC commented
> @MrMagick2104 спасибо что всегда пишешь длинные и развёрнутые комментарии! Нам, разработчикам очень важно и мы очень благодарны тебе за все!

> Нам

Кек
> Нам, разработчикам

Кек х2

2021-02-12 17:04 UTC, kcalbCube commented
> > @MrMagick2104 спасибо что всегда пишешь длинные и развёрнутые комментарии! Нам, разработчикам очень важно и мы очень благодарны тебе за все!
> 
> > Нам
> 
> Кек
> > Нам, разработчикам
> 
> Кек х2

"да заткнись уже(((" кринж момент

2021-02-12 19:13 UTC, Artemonim commented
> В чём проблема изначально была, кстати, неясно.

Обводку нарисовать забыли. Подумал заодно и размер поменять, так как вилка была похожа на огромную поварскую лопатку, ложка на половник, ножик на мачете. Да и прогрессия нож-ножище-топорик теперь заметнее.

Двузубые вилки существуют, хоть и специфичны. По лору можно оправдать остервенелой экономией на рабочих. А по графике тупо не знаю как нарисовать в таком размере третий зубец, не превратив в ложку. Попробовал полупрозрачностью показать, что дырка по центру не совсем дырка.

2021-02-12 19:49 UTC, TobyThorne commented
![01_03-1](https://user-images.githubusercontent.com/45202681/107815560-be9a2c00-6d9d-11eb-8475-54c5907eb788.jpg)

2021-02-13 15:14 UTC, Artemonim commented
![2021-02-13_17-45-53](https://user-images.githubusercontent.com/36363466/107853461-48daa280-6e27-11eb-9507-f3763a20b9eb.png)

2021-02-13 15:16 UTC, Doster-d commented
В чем проблемы контуры оригинального спрайта сделать черными?

2021-02-13 15:19 UTC, Artemonim commented
> В чем проблемы контуры оригинального спрайта сделать черными?

>> Подумал заодно и размер поменять, так как вилка была похожа на огромную поварскую лопатку, ложка на половник, ножик на мачете.

Если все против, могу оставить лишь обводку.

2021-02-13 21:32 UTC, Shootnik01 commented
Оставь только обводку. Не прыгай через свою голову)

2021-02-14 02:32 UTC, kcalbCube commented
> Оставь только обводку. Не прыгай через свою голову)

Никогда не говори такого разработчикам

2021-02-20 19:04 UTC, Artemonim commented
![2021-02-20_22-03-20](https://user-images.githubusercontent.com/36363466/108605800-8ad78b80-73c7-11eb-905e-102b43755cbc.png)

2021-02-23 16:15 UTC, closed without merging

2021-02-23 16:15 UTC, TatarTheBuilder commented
Страшно вырубай