Научные очки за исследования
ChaoticOnyx/OnyxBay pull request #4465
Opened 2021-02-15 07:00 UTC by kcalbCube

close #4058 
Добавлены очки ReSc(Research Score, глобальные очки исследований), а так же DiReSc(Direct ReSc, очки исследований направлений).
ReSc с деструкцией каждого предмета дает 2^(средний уровень технологий предмета) * 10 * k
DiReSc с деструкцией каждого предмета дает 2^(уровень технологии) * 10 * k
Ничего особо не прокожил, ибо нужны правки @sweden-moose 
[[SP заменил на ReSc ибо более научно звучит и название этой скоры для направлений не превращается в DSP, данный кусок кандидат на удаление]]
- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-15 07:09 UTC, kreeperHLC commented
Вообще там есть в дискорде отдельный канал для науки, или долбись чтобы тебе туда доступ выдали.

2021-02-15 07:57 UTC, kcalbCube commented
> Вообще там есть в дискорде отдельный канал для науки, иди долбись чтобы тебе туда доступ выдали.

Кому

2021-02-15 08:06 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
Аффтор что с спанами?

2021-02-15 08:25 UTC, kcalbCube commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
Не хотелось перекапывать весь код, ибо макрос неорганично вписывается в экосистему. Опять же, я жду аппрува и корректировок @sweden-moose, код пока не шлифовался вообще

2021-02-15 08:27 UTC, sweden-moose commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
Я не гейдиз

2021-02-15 08:33 UTC, kcalbCube commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
> Я не гейдиз

Я имею ввиду аппрува как от автора идеи. Правки там внеси...

2021-02-15 08:35 UTC, sweden-moose commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
Я не автор идеи....

2021-02-15 08:50 UTC, kcalbCube commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
а бля

2021-02-15 08:52 UTC, kcalbCube commented
@Shirlineyn призываю тебя

2021-02-15 08:57 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
Чел, ты...
![Screenshot_20210215-115622-01.jpeg](https://user-images.githubusercontent.com/63081538/107925017-eb5c6800-6f84-11eb-8234-e186e4ae24f5.jpeg)

2021-02-15 08:58 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
![Screenshot_20210215-115740-01.jpeg](https://user-images.githubusercontent.com/63081538/107925142-134bcb80-6f85-11eb-9eba-281454d13848.jpeg)

2021-02-15 09:03 UTC, kcalbCube commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
я не хотел лопатить код до аппрува автора идеи

2021-02-15 09:05 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
> я не хотел лопатить код до аппрува автора идеи

Ты это уже сделал создав ПР и сделав эту строчку, если ты ставишь галку, что исполняешь требования гайд ту контрибутинг, то изволь, пожалуйста, его исполнять, тем более это не так сложно.

2021-02-15 09:10 UTC, kcalbCube commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
для того что бы SPAN_WARNING не смотрелся как рояль в лесу нужно его пилить во всем коде, а мне это делать не хочется, ведь что-то может изменится. я первую и третью галочки не поставил.

2021-02-15 09:53 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +			to_chat(user, "<span class='notice'>This item is already researched totally.</span>")
> для того что бы SPAN_WARNING не смотрелся как рояль в лесу нужно его пилить во всем коде, а мне это делать не хочется, ведь что-то может изменится. я первую и третью галочки не поставил.

Как признанный стандарт, а тем более макрос может быть роялем в кустах?
Это просто обертка для избавление от писание class = '...', это не сложная функция.

2021-02-16 13:13 UTC, Doster-d requested changes
Мне не понравилось.

2021-02-16 13:13 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +		if(linked_console.files.researched_items[I.name] >= 3)
Когда ты обращаешься к предмету, например, I, то он сразу тебе дает I.name. конкретное указание - излишние, и я рекомендую смотреть не имя объекта, а тип предмета, вызвав I.type.
Определение в /obj/item/weapon излишние в предложенном и в текущем варианте.
Вы запрещаете уничтожать вещи, если они уже достаточно улучшены, что не логично, лучше перенести всю эту проверку в прок разрушения предмета, и уже там выдавать нуль очков за исследования, тем более это фичу убивает.

2021-02-16 13:27 UTC, kcalbCube commented on code/modules/research/destructive_analyzer.dm
> +		if(linked_console.files.researched_items[I.name] >= 3)
Так как автор не отвечает то прислушаюсь.

2021-02-16 13:28 UTC, kcalbCube commented
Понравится.

2021-02-16 21:41 UTC, Doster-d commented on code/modules/research/destructive_analyzer.dm
> +		if(linked_console.files.researched_items[I.name] >= 3)
Только автор не отвечает за код, отвечают разработчики, тебе говорят как сделать круто, ну так сделай круто.

2021-02-23 16:24 UTC, closed without merging