update gunshot forensic
ChaoticOnyx/OnyxBay pull request #4489
Opened 2021-02-20 07:57 UTC by HentaiStorm

Заменяет пороховой след на список, позволяя отслеживать сразу несколько пороховых отметин. Также добавляет след на униформу.

❌ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
❌ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-23 14:04 UTC, TobyThorne requested changes

2021-02-23 14:04 UTC, TobyThorne commented on code/modules/detectivework/microscope/microscope.dm
> +				report.info += "* [caliber] bullet detected."
куда проебалось redisue from a, почему на униформе детектятся сами пули а не следв

2021-02-28 20:00 UTC, TobyThorne commented
Надо добавить какой-то лимит на количество следов. А то после пары магазинов из ПП перчато4ки выдадут Войну и Мир.

А лучше при наличии большого количества разных следов выводить что-то вроде "It's all covered in GSR."

2021-03-23 11:00 UTC, PlinHost commented
Иссуй обновлен, ждем приведения ПРа в соответствие.

2021-04-06 03:32 UTC, closed without merging