add vortex suppressor
ChaoticOnyx/OnyxBay pull request #4492
Opened 2021-02-20 13:13 UTC by HentaiStorm

Добавляет мод к щитам, запрещающий пользоваться вортексом на всем радиусе покрытия

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-20 13:20 UTC, HentaiStorm commented
Потребление энергии подавителем:
163 KWh = Ядро ИИ (Радиус - 4)
7.8 MWh = Бриг (Радиус - 28)
144 MWh = Станция (Радиус - 120)
650 MWh = Лимит щитов (Радиус - 255)

2021-02-20 13:29 UTC, Doster-d commented
Было бы круто разрешить путешествовать с вортексом на другие z-левелы, независимо от щитов и когда вортексодебил попытается вернуться на станции, а там стоит блокировка, то он не сможет переместиться.

2021-02-20 13:30 UTC, HentaiStorm commented
Это фича, что вортекс работает внутрь покрытия, но не из него.

2021-02-20 13:30 UTC, HentaiStorm commented
Зайти можно, выйти нельзя.

2021-02-20 13:31 UTC, No-Tips commented
144 Мегаватт? А не дохера ли. Я, конечно, понимаю, что это блокировка вортекса, но сейчас такой выработки достичь фактически невозможно. Мать с коллекторами вплотную вырабатывает до 100Мегаватт, если я не ошибаюсь. То есть, чтобы поддерживать вортекс блокиратор мне нужно будет поставить две матери?

2021-02-20 13:31 UTC, No-Tips commented
Или я где-то туплю?

2021-02-20 13:31 UTC, Doster-d commented
> 144 Мегаватт? А не дохера ли. Я, конечно, понимаю, что это блокировка вортекса, но сейчас такой выработки достичь фактически невозможно. Мать с коллекторами вплотную вырабатывает до 100Мегаватт, если я не ошибаюсь. То есть, чтобы поддерживать вортекс блокиратор мне нужно будет поставить две матери?

А что Вы не можете построить коллекторы у генератора гравитации?

2021-02-20 13:32 UTC, HentaiStorm commented
Оно и рассчитывалось на локальное использование, покрывать ею всю станцию нет смысла. Бриг/Ядро - пожалуйста, имхо конечно, думаю геймдизы подправят где считают нужным, если вообще это нужно.

2021-02-20 13:32 UTC, No-Tips commented
Гравген вырабатывает 30 беккерелей. Мать вплотную - больше ста.

2021-02-20 13:32 UTC, Doster-d commented
> Это фича, что вортекс работает внутрь покрытия, но не из него.

Добавь еще, что бы войти было нельзя, если щиты стоят.

2021-02-20 13:34 UTC, No-Tips commented
> Оно и рассчитывалось на локальное использование, покрывать ею всю станцию нет смысла. Бриг/Ядро - пожалуйста, имхо конечно, думаю геймдизы подправят где считают нужным, если вообще это нужно.

Ну, разве что так. Но опять же, тогда придется пускать условные восемь мегаватт в обход смесов, убивая каждого, кто захочет потрогать провод.

2021-02-20 13:35 UTC, No-Tips commented
В общем, циферки нужно потвикать, чтобы было реально поставить это.

2021-02-20 13:36 UTC, HentaiStorm commented
Можно строить локальные материи/стеныурана в отсеках. И кстати, воид шифт ниндзи работает по той же схеме, что и вортекс - войти можно, выйти нельзя.

2021-02-20 13:37 UTC, No-Tips commented
Эх... Зачем мы тогда Пейна заджоббанили... Он ведь просто готовился к этому пулреквесту...

2021-02-20 13:38 UTC, HentaiStorm commented
Пейн занимался говноебством, строя их в барах/медбеях.

2021-02-20 13:38 UTC, No-Tips commented
А может, он хотел в баре\медбее поставить вортекс блокатор, А?

2021-02-20 14:02 UTC, Destrolaric commented
Предложение, сделать это возможным, только для прокачанных щитов.

2021-02-20 14:11 UTC, MrMagick2104 reviewed
Имхо, стоит не только на вортекс ограничения пилить, а вообще на любой блюспейс (хэндтеле, БоХи, етц.), тогда уж. А то не слишком логично, хотя и по балансу нормально.
Только при емаге бы сделать, либо, хотя бы, только при взломе через проводки, по-моему, лучше.

2021-02-20 14:11 UTC, MrMagick2104 commented on code/game/objects/items/weapons/teleportation.dm
> +						to_chat(usr, SPAN_WARNING("Your manipulator does not work in this area!"))
Мне кажется, сообщение в чат выглядит слабовато. Может, лучше кидать малфанкшн при попытке использования, если есть заряд в батарейке?

2021-02-20 14:11 UTC, MrMagick2104 commented on code/modules/shield_generators/modes.dm
> +	multiplier = 1
```suggestion
	multiplier = 1
	hacked_only = 1
```

2021-02-20 22:04 UTC, kcalbCube commented
> 144 Мегаватт? А не дохера ли. Я, конечно, понимаю, что это блокировка вортекса, но сейчас такой выработки достичь фактически невозможно. Мать с коллекторами вплотную вырабатывает до 100Мегаватт, если я не ошибаюсь. То есть, чтобы поддерживать вортекс блокиратор мне нужно будет поставить две матери?

От твоих слов в гробу пейн начал крутиться и выработал 16 Мегаватт

2021-02-21 17:32 UTC, Rodial-Admiral commented
Код, конечно, странный.
Ты используешь проверку на радиус:
`if(T.z == SG_turf.z)
if(T.x in SG_turf.x - SG.field_radius to SG_turf.x + SG.field_radius)
if(T.y in SG_turf.y - SG.field_radius to SG_turf.y + SG.field_radius)`
Которая не учитывает:
1) Возможность подрубания щитов в мультизет
2) Hull shielding, в котором подавление телепортации, по идее, вообще не должно работать, поскольку щит не замкнут. 
С механо-точки зрения это смешно еще и потому, что на з-уровне по типу астероида ты можешь выкрутить радиус в 255, врубив халлщилдинг, и наслаждаться вырубленными по всему з-уровню щитами при минимальных энергозатратах. На станции, в принципе, все то же - с определенного момента радиус в режиме халл щилдинга перестает сильно влиять на энергопотребление, потому что станция заканчивается.

По поводу энергопотребления: оно разумно, если исходить из предпосылки, что "подавление вортекса" должно применяться только на небольших радиусах.
Подавлять наивысшую РнДшную технологию дженерик-настройкой с низким энергопотреблением по всему з-уровню было бы странно.

2021-02-21 17:37 UTC, Rodial-Admiral commented
Логику "впускать, но не выпускать" не понял. Зачем оно тогда надо? Влетел в арсенал/копетонскую вортексом, обратно вылетел хендтелепортером. В целом, получается, что ты можешь влететь ВНУТРЬ защищаемой зоны, где находится генератор, обеспечивающий защиту от вортексов. Который ты можешь выключить, влетев в нее вортексом. 
??????????

2021-02-21 19:05 UTC, HentaiStorm commented
1. Поправимо.
2. Потребление подавителя всегда постоянно, оно зависит только от радиуса покрытия.
3. Логика "вошел, не вышел" - поправима.

2021-02-21 19:37 UTC, Rodial-Admiral commented
А. Т.е., по сути получается, что "подавитель" - это не функционал щитов, это, фактически, дополнительный девайс внутри щитов, от самих щитов никак особо не зависящий, кроме как по энергии.
Зачем его тогда вообще делать настройкой щитов, а не отдельным девайсом?

2021-02-22 05:07 UTC, HentaiStorm commented
Думал над этим вопросом с самого начала, нужно спрайтить отдельный девайс/структуру, окошко настройки. Хотя, думаю можно украсть этот же щит, оставить окно, переписать потребление энерджи, вписать отдельные моды incoming/outgoing flow. Так и сделаю.

2021-02-22 10:44 UTC, HentaiStorm commented
Итого:
- Отдельная машина с:
* 15 проводов
* subspace filter
* subspace crystal
* СМЕС-провод
- Дает:
* 3 BLUESPACE, 3 POWER, 3 ENGINEERING
- Необходимо для разблокировки в РнД:
* 4 BLUESPACE, 4 POWER, 4 ENGINEERING
- Имеет: Два мода для блокировки исходящего и входящего вортекса. И также 500 MJ энергии.
- Доступен в карго, в офицерской категории за 100 очков.
- Также блокирует ВОИД ниндзи
- Собственный спрайт

2021-02-22 11:31 UTC, ArmenianOnyx commented
ПАХПАХАПХ, ну вы зачем так нинзю нагинаете?

2021-02-22 11:33 UTC, kcalbCube commented
ПХАХАХАХ, заходит такой ниндзя, а там щиты заспидранили. Уже вижу его слезы. И ведь не подьебешь, роль проиграна, суицид только

2021-02-22 11:36 UTC, ArmenianOnyx commented
надо было выкладывать обнову до нерфа вортекса рнд

2021-02-22 11:43 UTC, HentaiStorm commented
А какой спидран может быть? Залочить станцию - 140 мегаватт. Данным девайсом можно разве что ядро защищать и арсенал (~150 киловатт). Для локального пользования.

2021-02-22 11:45 UTC, kcalbCube commented
Пейна позвать. Можно успеть кристаллов заказать, пока ниндзя минут 15 в ссдшке

2021-02-22 11:45 UTC, HentaiStorm commented
Потребление энергии подавителем (С двумя режимами, по отдельности затрачивают лишь половину из списка):
163 KWh = Ядро ИИ (Радиус - 4)
7.8 MWh = Бриг (Радиус - 28)
144 MWh = Станция (Радиус - 120)
650 MWh = Лимит щитов (Радиус - 255)

2021-02-22 11:46 UTC, HentaiStorm commented
А) Откуда ты знаешь про ниндзю Б) Откуда они знают про его телепорт

2021-02-22 11:47 UTC, HentaiStorm commented
В) Ниндзя может попросту перехватить подавитель из карго Д) Сломать сервера РнД с чертежом

2021-02-22 11:48 UTC, MalinaGirl commented
апрув будет только после коммита с инвиз сапресором

2021-02-22 11:50 UTC, HentaiStorm commented
Хотя, вот наличие его в карго уже намекает на то, что им нужно защищаться от чего-то с телепортом. Считаю метой.

2021-02-22 12:39 UTC, ArmenianOnyx commented
> А какой спидран может быть? Залочить станцию - 140 мегаватт. Данным девайсом можно разве что ядро защищать и арсенал (~150 киловатт). Для локального пользования.

— Эй, Пейн, чем мы будем заниматься сегодня вечером? 
— Тем же, чем и всегда, Армениан, захуярим реактор в баре.

2021-02-22 12:55 UTC, No-Tips commented
Блядь. Только не это. Это можно сделать и без ваших ебанутых материй.

2021-02-22 12:56 UTC, No-Tips commented
И такой щит можно заспидранить за 15 минут вдвоем.

2021-02-22 12:58 UTC, MrMagick2104 commented
Я бы предложил запилить запрет для телепортера мехов (если ещё не) и обычного хэндтеле, а потом данную машинерию в блюспейс суппрессор переименовать. Ибо хэндтеле смешной тоже бывает.
И "вортекс суппрессор" - не звучит, с логической точки зрения, по-моему. Они же все на магическом блюспейсе работают, как-никак, чего бы этому суппрессору всё остальное не блокировать?
Либо вообще впилить настройки того, что блокировать, а что нет, с увеличением потребления энергии соответственно уровню блокируемого предмета.

2021-02-22 13:11 UTC, ArmenianOnyx commented
да кстати, пусть и все другие виды телепортов блокирует. А это пр выглядит чисто ради поржать над нинзей

2021-02-22 13:34 UTC, Destrolaric commented on code/game/objects/items/weapons/teleportation.dm
> +						to_chat(usr, SPAN_WARNING("Your manipulator does not work in this area!"))
Сама строка немного мем, if if if лучше не надо, && намного более приятен глазу.

2021-02-22 15:31 UTC, Rodial-Admiral commented
Вортекс-манипулятор работает с вортексом, а не с блуспейсом. Не надо тут фандомы путать!
Я ему тут артронную энергию почти закодил, да..

А по теме - каргоящики действительно не нужны были. 
Что касается "блуспейс-подавителя" - почему бы не назвать приблуду "пространственным стабилизатором"? Это бы объяснило блокировку принципиально разных видов телепортов, и меньше проблем было бы с метой, поскольку открывается-то оно раньше, чем воркекс.

2021-02-22 15:54 UTC, Doster-d commented
Ого, ого, да тут у нас есть ЯРСдупнутый юмопереможный рагулевортанутый стабилизационный пескарь!

2021-02-22 16:56 UTC, MrMagick2104 commented
> пространственным стабилизатором

Предлагаю также альтернативное название - "Якорь реальности".

2021-02-22 16:57 UTC, Doster-d commented
> > пространственным стабилизатором
>
> Предлагаю также альтернативное название - "Якорь реальности".

Так уже использовано в ЯРС.

2021-02-22 17:01 UTC, kreeperHLC commented
> > пространственным стабилизатором
> 
> Предлагаю также альтернативное название - "Якорь реальности".

А область в которой он находится будет подгружена даже когда игрок уйдет от неё?

2021-02-22 18:19 UTC, HentaiStorm commented
> объяснило блокировку принципиально разных видов телепортов, и меньше проблем было бы с метой, поскольку открывается-то оно раньше, чем воркекс.
В данный момент он открывается одинаково с вортексом.

2021-02-22 18:22 UTC, HentaiStorm commented
>да кстати, пусть и все другие виды телепортов блокирует. А это пр выглядит чисто ради поржать над нинзей

А) Эта приблуда изучается одновременно с вортексом Б) У нее пиздецкое энергопотребление В) Ей нужны компоненты из шахтерских ресурсов
Я уже не говорю о том, что ниндзя может спокойно вычтать каждый из пунктов украв ресурсы/сломав сервер/инженерку или банально перехватив плату с подавителем.

2021-02-22 18:37 UTC, Rodial-Admiral commented
> в данный момент он открывается одинаково с вортексом

Требования по техам для машины из твоего кода: 
req_tech = list(TECH_BLUESPACE = 5, TECH_POWER = 5, TECH_ENGINEERING = 5)

Требования по техам для вортекса: 
req_tech = list(TECH_MATERIAL = 8, **TECH_BLUESPACE = 5**, TECH_MAGNET = 7, **TECH_POWER = 8**, TECH_DATA = 5, **TECH_ENGINEERING = 8**)
Жирным выделил то, что присутствует в машине - совпадает только блуспесс. Плюс еще сверху накинуты три других теха.

Мне кажется, /немного/ неодинаково.

2021-02-22 18:37 UTC, HentaiStorm commented
Суть то в блуспейсе

2021-02-22 18:38 UTC, HentaiStorm commented
Что у него один с вортексом уровень по голубому.

2021-02-22 20:23 UTC, MrMagick2104 commented
Блюспейс 5 можно и без ресурсов вкачать же.
> сломав сервер

Ломание сервера к стиранию уже напечатанных плат и уровней из консоли не приводит.

> ниндзя может спокойно вычесть каждый

Если ниндзя превентивно всю научку не вырезает вместе с СБ, то, в большинстве случаев, не может. Ему не приходит СМС от клана Паука, или на кого он там работает, сообщающая о том, что где-то строят или собираются построить (изучили) ЯРС.

2021-02-22 22:11 UTC, kcalbCube commented on code/modules/vortex_suppressor/obj/machinery.dm
> +	upkeep_power_usage += round(((((suppressor_radius * 2) ** 2) / 2) * ENERGY_UPKEEP_SUPPRESSOR * 50) * upkeep_multiplier)
```suggestion
	upkeep_power_usage += round((suppressor_radius * 2) ** 2 * ENERGY_UPKEEP_SUPPRESSOR * 25 * upkeep_multiplier)
```

2021-02-22 22:11 UTC, kcalbCube commented on code/modules/vortex_suppressor/obj/machinery.dm
> +/obj/machinery/power/vortex_suppressor/attackby(obj/item/O as obj, mob/user as mob)
Убери

2021-02-24 07:43 UTC, HentaiStorm commented
> Блюспейс 5 можно и без ресурсов вкачать же.
Но для постройки вортекса требуются ресурсные компоненты

> Ломание сервера к стиранию уже напечатанных плат и уровней из консоли не приводит.
Отвертка + лом по серверу, в консоли Settings ->Reset RD databse (если не ошибаюсь)

2021-02-24 11:09 UTC, MrMagick2104 commented
> Отвертка + лом по серверу, в консоли Settings ->Reset RD databse (если не ошибаюсь)

Это ресетает данные сервера. Больше оно ничего не ресетает, разве нет?

2021-02-24 11:26 UTC, HentaiStorm commented
Конкретно оно ресетит данные консоли. Ресетнуть сервер невозможно из-за древнего гриф протекта (который по хорошему бы спилить).

2021-03-12 14:10 UTC, Vallat requested changes
Исправить пару мелочей для улучшения читаемости, из критичного - цикл по всему миру

2021-03-12 14:10 UTC, Vallat commented on code/modules/vortex_suppressor/obj/machinery.dm
> +	ui_interact(user)
Открываем интерфейс и, если вскрыты провода, открываем еще и панельку с ними? Не лучше ли разделить эти два процесса? Например, так
```
    if(!panel_open)
        ui_interact(user)
    else
        wires.Interact(user)
```

2021-03-12 14:10 UTC, Vallat commented on code/modules/vortex_suppressor/obj/machinery.dm
> +/obj/machinery/power/vortex_suppressor/New()
```suggestion
/obj/machinery/power/vortex_suppressor/Initialize()
```

2021-03-12 14:10 UTC, Vallat commented on code/modules/vortex_suppressor/obj/machinery.dm
> +	..()
```suggestion
	. = ..()
```

2021-03-12 14:10 UTC, Vallat commented on code/modules/vortex_suppressor/obj/turf.dm
> +	for(var/obj/machinery/power/vortex_suppressor/VS in world)
Ужасно, пожалуйста, никогда не делай так. Если уж сильно не хочется создавать список с нужными тебе объектами, есть же лист со всей машинерией
```suggestion
	for(var/obj/machinery/power/vortex_suppressor/VS in SSmachines.machinery)
```
Особенно учитывая то, как часто этот процесс будет вызываться, искать объекты по всему миру - смерть в лучах лагов.

2021-03-12 17:49 UTC, MrMagick2104 commented on code/modules/vortex_suppressor/obj/machinery.dm
> +	ui_interact(user)
Разве типичная машинерия (вендоматы, те же щиты, другие штуки) не действует по такой логике одновременного открытия?
По-моему, как раз таки действует, для постоянства менять не стоит, имхо.



Ну и банально удобнее, если сразу оба меню открываются, т.к. иначе придётся закручивать панель, если случайно нажал на крестик или нужно обновить главное меню.

2021-03-13 03:41 UTC, Vallat commented on code/modules/vortex_suppressor/obj/machinery.dm
> +	ui_interact(user)
> Разве типичная машинерия (вендоматы, те же щиты, другие штуки) не действует по такой логике одновременного открытия?
> По-моему, как раз таки действует, для постоянства менять не стоит, имхо.

Если так, то ладно. С логикой того как работает игра пусть геймдизайнеры разбираются

2021-03-18 11:01 UTC, TobyThorne commented
Так и не понял, в чём смысл. Огромная куча когда чтобы контрить один-единственный вортекс. Он и так уже сильно занёрфлен, если сравнивать с первоначальным видом.

2021-03-23 11:02 UTC, PlinHost commented
> Так и не понял, в чём смысл. Огромная куча когда чтобы контрить один-единственный вортекс. Он и так уже сильно занёрфлен, если сравнивать с первоначальным видом.

Выше вон предлагают заблокировать все телепорты и блюспейс, тогда вортекс будет не единственный.

2021-12-07 16:15 UTC, HentaiStorm commented
Завалялся патч к фиче годовалой давности. Вроде готово.

2021-12-07 16:17 UTC, HentaiStorm commented
Но только для вортекса, когда-то в планах было еще отключить работу БоХов, но руки так и не дошли. Думаю вы и сами закодить сможете? Там проки подавителей по турфам.

2021-12-12 06:41 UTC, Doster-d approved these changes
Круто.

2022-01-27 14:48 UTC, kreeperHLC commented
Почти год прошёл, появились конфликты

2022-02-05 07:03 UTC, closed without merging