feat(datum/seed) add ckey for admins' purpose.
ChaoticOnyx/OnyxBay pull request #4499
Opened 2021-02-21 21:46 UTC by Doster-d

фингерпринтласт, не всегда доступен, вкидывание сикей человека, что посадил данное растение - идеальное решение

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-23 13:58 UTC, TobyThorne commented
можно не называть переменную ckey пажаста, а то чую в будущем за жопу укусит

2021-02-23 14:00 UTC, Doster-d commented
> можно не называть переменную ckey пажаста, а то чую в будущем за жопу укусит

а как еще обозначить ckey игрока который посадил это растение?

2021-02-25 05:12 UTC, Tsurupeta commented
planter_key?

2021-02-25 05:37 UTC, Tsurupeta requested changes

2021-02-25 05:37 UTC, Tsurupeta commented on code/modules/hydroponics/trays/tray.dm
> +	seed.ckey = user.ckey
Тут тоже поменять надо, лол

2021-02-25 18:23 UTC, kreeperHLC submitted a review, later dismissed

2021-02-28 19:54 UTC, TobyThorne commented on code/modules/hydroponics/trays/tray.dm
> +	S.seed.planter_ckey = user.ckey
а зачем оно дважды???

2021-03-01 00:55 UTC, Doster-d commented on code/modules/hydroponics/trays/tray.dm
> +	S.seed.planter_ckey = user.ckey
Одну на копию, другое на оригинал.

2021-03-01 02:41 UTC, TobyThorne commented on code/modules/hydroponics/trays/tray.dm
> +	S.seed.planter_ckey = user.ckey
чё)

2021-03-04 16:49 UTC, kreeperHLC approved these changes

2021-03-04 16:55 UTC, Tsurupeta approved these changes

2021-03-05 19:33 UTC, HonkyDonky approved these changes
ех

2021-03-05 21:10 UTC, merged