update ablative armor
ChaoticOnyx/OnyxBay pull request #4513
Opened 2021-02-24 09:19 UTC by HentaiStorm

Увеличивает шанс на рефлект луча/пучка брони почти в два раза
Формула нового шанса: (100 - урон)%
Старая: (40 - урон/3)%

- Пример лазерного карабина с лучевым режимом:
По новой формуле: 100 - 50 = 50%
По старой формуле: 40 - 50/3 = 23% 
- Пример лазерного карабина с режимом пучка:
По новой формуле: 100 - 60 = 40%
По старой формуле: 40 - 60/3 = 20% 

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-02-24 09:25 UTC, kreeperHLC commented
А можно узнать шанс рефлекта пушек, у которых меньше 50 урона?

2021-02-24 09:27 UTC, HentaiStorm commented
Формула представлена. И да, это шанс на рефлект по груди и гроину. В остальные части тела шанс на два делится.

2021-02-25 17:48 UTC, kreeperHLC commented
> Формула представлена. И да, это шанс на рефлект по груди и гроину. В остальные части тела шанс на два делится.

Ну получается, что лазер с условными 10 урона попадать будет в 1 случае из 10?

2021-02-25 17:48 UTC, kreeperHLC approved these changes
Ну а с кодом всё хорошо

2021-02-28 19:53 UTC, TobyThorne commented
Такое. Абляционка и так режет дамаг от лазеров в дохуя раз.

2021-03-13 14:46 UTC, PlinHost commented
> Такое. Абляционка и так режет дамаг от лазеров в дохуя раз.

Можно уменьшить броню пропорционально увеличению шанса отражения. Рефлекты весело.

2021-03-13 15:01 UTC, Vallat requested changes

2021-03-13 15:01 UTC, Vallat commented on code/modules/clothing/suits/armor.dm
> +
```suggestion
    if(ishuman(user))
```
Добавить проверку для блока кода ниже, а именно для
```
		var/mob/living/carbon/human/H = user
		if(H && istype(H.head, /obj/item/clothing/head/helmet/ablative))
			def_list += BP_HEAD
```
В ином случае если юзер внезапно не будет хуманом (например, обезьяной) - случится рантайм эррор

2021-04-06 03:31 UTC, closed without merging