changelog 25/02/21
ChaoticOnyx/OnyxBay pull request #4515
Opened 2021-02-25 11:22 UTC by TapKo4eB

кто там чейнжлог просил
если кто не доволен будет чем-то правьте сами, не тупые

2021-02-25 11:23 UTC, TatarTheBuilder submitted a review, later dismissed

2021-02-25 11:33 UTC, kreeperHLC submitted a review, later dismissed

2021-02-25 18:21 UTC, Doster-d requested changes
changelog не соотвествует текущему количеству коммитов в ветке /dev/

2021-02-25 18:41 UTC, Doster-d approved these changes
Теперь cool.

2021-02-25 18:42 UTC, TatarTheBuilder submitted a review, later dismissed

2021-02-26 23:40 UTC, Doster-d submitted a review, later dismissed

2021-02-27 00:37 UTC, Doster-d approved these changes

2021-02-27 05:24 UTC, TapKo4eB commented
хули вы творите, замержите уже подходящий чейнжлог и запуште в релиз уже все что не дальше этого коммита
опоздавшее говно в следующем обновлении догонит

2021-02-28 19:38 UTC, TobyThorne approved these changes

2021-02-28 19:39 UTC, merged