Добавляем динамичную стрельбу
ChaoticOnyx/OnyxBay pull request #4574
Opened 2021-03-05 15:15 UTC by HentaiStorm

Добавляет стрельбу в движении, а также наведение мышью при зажиме.

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-05 17:31 UTC, MrMagick2104 commented
Слоудаун бы в 0.2 при стрельбе.

2021-03-05 17:37 UTC, Destrolaric requested changes
Чистим код.

2021-03-05 17:37 UTC, Destrolaric commented on code/modules/projectiles/gun.dm
> +	//user.setMoveCooldown(shoot_time) //no moving while shooting either
Опять легаси комменты, плохая практика.

2021-03-05 17:37 UTC, Destrolaric commented on code/modules/projectiles/gun.dm
> +	//user.setClickCooldown(shoot_time) //no clicking on things while shooting
Опять легаси комменты, плохая практика.

2021-03-05 17:37 UTC, Destrolaric commented on code/modules/projectiles/gun.dm
> +	//user.setClickCooldown(DEFAULT_QUICK_COOLDOWN)
Тут тоже

2021-03-05 17:37 UTC, Destrolaric commented on code/modules/projectiles/gun.dm
> +	//user.setMoveCooldown(move_delay)
И тут

2021-03-05 17:37 UTC, Destrolaric commented on code/modules/projectiles/gun.dm
>  	for(var/i in 1 to burst)
Проверку на last_mouse_target, мало ли.

2021-03-05 19:27 UTC, TobyThorne commented
Как бы я не пытался, я так и не понял, зачем это вообще нужно. Не говоря уже о том, что нихуя не понял из описания ПРа.

2021-03-06 05:01 UTC, HentaiStorm commented
> 
> 
> Как бы я не пытался, я так и не понял, зачем это вообще нужно. Не говоря уже о том, что нихуя не понял из описания ПРа.

https://cdn.discordapp.com/attachments/414839549877813251/817360098623881216/OnyxBay_-_NSS_Exodus_2021-03-05_16-32-13_Trim_2.mp4

2021-03-06 05:04 UTC, HentaiStorm commented
Космонавты могут передвигать при стрельбе очередями, также во время этого града наводиться курсором мыши, а не просто перекликивать цель.

2021-03-06 05:05 UTC, HentaiStorm commented
В текущем варианте, персонажа столбит в пол, а переключить цель во время очереди не представляется возможным.

2021-03-06 05:08 UTC, HentaiStorm commented
https://user-images.githubusercontent.com/60922927/110196066-d7a97080-7e63-11eb-9573-97a38d95e3f9.mp4

Вот тоже как пример очереди из пулемета (с немного подкрученной подачей для скорости)

2021-03-06 05:13 UTC, ArmenianOnyx commented
На всех нормальных билдах такое всегда было, вот теперь и у нас появилось.

2021-03-08 06:58 UTC, HentaiStorm commented
Вынес в отдельный модуль, чтобы не кучковать это все по дебрям.

2021-03-15 04:58 UTC, TapKo4eB reviewed
лучший QoL апдейт ай хев эвер син как его еще не замержили

пр я конечно же не тестил

2021-03-15 04:58 UTC, TapKo4eB commented on code/modules/mob/living/living_defines.dm
> +	var/controllable = FALSE // If ghosts can possess a mob without permissions
а гд е конец

2021-03-15 04:58 UTC, TapKo4eB commented on code/modules/projectiles/aim.dm
> +			L.last_mouse_target = src
де

2021-03-15 05:08 UTC, Shootnik01 commented
> лучший QoL апдейт ай хев эвер син как его еще не замержили
> 
> пр я конечно же не тестил

Соу, ит вуд си

2021-04-06 03:31 UTC, closed without merging