tweak(changelog) new changelog data
ChaoticOnyx/OnyxBay pull request #4584
Opened 2021-03-06 15:21 UTC by Doster-d

Ченджлог.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-06 15:45 UTC, Destrolaric commented on html/changelog.html
> +				<li class="tweak">+8 очков в книгу клирика.</li>
8 очков теперь норма

2021-03-06 16:36 UTC, kreeperHLC requested changes

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="rscadd">Заклинание наручников теперь может быть улучшены для перехода из системы зарядов на обычную перезарядку.</li>
```suggestion
				<li class="rscadd">Заклинание наручников теперь может быть улучшено для перехода из системы зарядов на обычную перезарядку.</li>
```

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="rscadd">Новое заклинание Mind Control: работает как имплант, с кастомными законами. Человечка можно освободить от него святой водой.</li>
```suggestion
				<li class="rscadd">Новое заклинание Mind Control: работает как имплант, с кастомными законами. Возможно священник сможет помочь вам от него избавиться.</li>
```

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="tweak">На скафандре мага теперь можно носить предметы мага (книги с заклинаниями, контракты и прочие артефакты);.
```suggestion
				<li class="tweak">На скафандре мага теперь можно носить предметы мага (книги с заклинаниями, контракты и прочие артефакты).
```

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="tweak">Скафандр мага больше не замедляет носителя;.
```suggestion
				<li class="tweak">Скафандр мага больше не замедляет носителя.
```

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="rscadd">Добавлены магические магбуты - рескин магбутов с уникальными сообщениями и считающийся за обувь мага;.
```suggestion
				<li class="rscadd">Добавлены магические магбуты - рескин магбутов с уникальными сообщениями и считающийся за обувь мага.
```

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="tweak">В комплекте скафандра мага сандалии заменены на магические магбуты;.
```suggestion
				<li class="tweak">В комплекте скафандра мага сандалии заменены на магические магбуты.
```

2021-03-06 16:36 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="tweak">В комплект скафандра мага добавлен кислородный баллон;.
```suggestion
				<li class="tweak">В комплект скафандра мага добавлен кислородный баллон.
```

2021-03-06 16:41 UTC, kreeperHLC submitted a review, later dismissed

2021-03-10 17:14 UTC, kreeperHLC approved these changes

2021-03-11 20:03 UTC, HonkyDonky approved these changes

2021-03-11 21:11 UTC, kreeperHLC requested changes

2021-03-11 21:11 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="rscadd">Теперь стулья можно крутить призракам, но их нельзя крутить в священной зоне</li>
```suggestion
				<li class="rscadd">Теперь стулья можно крутить призракам, но их нельзя крутить в священной зоне.</li>
```

2021-03-11 21:11 UTC, kreeperHLC commented on html/changelog.html
> +				<li class="rcsadd">Добавление поддержки SpacemanDMM в репозиторий, а точнее специальный файл-конфигурацию для пользователей с данным расширением и несколько полезных макросов для его работы</li>
```suggestion
				<li class="rcsadd">Добавление поддержки SpacemanDMM в репозиторий, а точнее специальный файл-конфигурацию для пользователей с данным расширением и несколько полезных макросов для его работы.</li>
```

2021-03-13 13:19 UTC, Epicus7 approved these changes

2021-03-13 13:33 UTC, kreeperHLC approved these changes

2021-03-13 13:34 UTC, merged