Старый-Новый худ с гунов
ChaoticOnyx/OnyxBay pull request #4619
Opened 2021-03-09 21:02 UTC by igorsaux

Осталось добавить отсутствующие иконки и готово.
![image](https://user-images.githubusercontent.com/55196698/110537448-bd0d1b00-8133-11eb-856f-f8e6dd3f74a3.png)

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-09 21:09 UTC, TobyThorne commented
Выглядит приятно.

2021-03-10 08:37 UTC, Tsurupeta commented
Я же менял руки местами, в чём проблема???

2021-03-10 08:40 UTC, kcalbCube commented
Иконки интеракта говна

2021-03-10 09:55 UTC, Doster-d commented
> Иконки интеракта говна

Ты говно.

2021-03-10 15:56 UTC, Shootnik01 commented
А зачем это все вообще?

2021-03-10 15:57 UTC, Shootnik01 commented
Ни красивее, ни хуже выглядеть не стало. Просто по-другому. Но ладно..

2021-03-10 15:58 UTC, igorsaux commented
Можно мержить

2021-03-10 16:32 UTC, MrMagick2104 commented
> Можно мержить

Пробел под режимом ходьбы на скрине выглядит довольно странно. Так и задумано?
![run](https://user-images.githubusercontent.com/58848742/110662968-137f6580-81d7-11eb-88b6-788379a16070.png)

2021-03-10 16:40 UTC, igorsaux commented
> > Можно мержить
> 
> Пробел под режимом ходьбы на скрине выглядит довольно странно. Так и задумано?
> ![run](https://user-images.githubusercontent.com/58848742/110662968-137f6580-81d7-11eb-88b6-788379a16070.png)
> 
> Но если в целом, то крайне приятно смотреть на такой интерфейс, имхо.

Квадратной иконки нет а их расположение у всех худов одинаковое

2021-03-10 16:43 UTC, HentaiStorm commented
Выглядит очень приятно, но текущая кукла получше будет. Имхо.

2021-03-10 18:24 UTC, kreeperHLC approved these changes, later dismissed

2021-03-11 08:55 UTC, Doster-d requested changes
![image](https://user-images.githubusercontent.com/63081538/110761228-8aad0c00-8260-11eb-842f-0d79202bae05.png)
Нет спрайта для выбора руки для защиты.

2021-03-11 09:22 UTC, igorsaux commented
> ![image](https://user-images.githubusercontent.com/63081538/110761228-8aad0c00-8260-11eb-842f-0d79202bae05.png)
> Нет спрайта для выбора руки для защиты.

Теперь есть

2021-03-11 09:24 UTC, Doster-d commented
Может еще название изменишь? New, ну такое себе название...

2021-03-11 09:26 UTC, Doster-d submitted a review, later dismissed
Теперь клево

2021-03-11 09:32 UTC, igorsaux commented
> Может еще название изменишь? New, ну такое себе название...

Как у них и называется, но можно переименовать и в "Goon".

2021-03-11 09:34 UTC, Doster-d commented
Ну сделай "Goon", такое название лучше, чем "New"

2021-03-11 10:20 UTC, Doster-d approved these changes

2021-03-11 20:00 UTC, kreeperHLC approved these changes

2021-03-11 20:04 UTC, merged