Пища для гурманов 2.0
ChaoticOnyx/OnyxBay pull request #4630
Opened 2021-03-11 22:06 UTC by Doster-d

![image](https://user-images.githubusercontent.com/63081538/110861267-f928b300-82ce-11eb-94b2-547c2ae64736.png)

Теперь у нас не создается продукт-орган, а используется продукт-орган внутри, для internal это продукт-орган, а для external это человеческое мясо.
При поедание головы Вы обгладываете голову до гиба и черепа.
Для external органов доступна готовка еды, как из мяса.
Теперь если конечность покусанная, то не предлагается "подавить каннибализм", а сразу человек начинает поедать орган.
Добавлен в examine количество надкусов.

close #1193

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-11 22:16 UTC, Shootnik01 commented
Ммм. Ассистентики..

2021-03-12 02:20 UTC, Tsurupeta commented
Ещё накинь возможность продавать тому самому торговцу не только мясо человека и самого человека, но и человеческие части и органы. Либо добавь возможность мит спайк делать из стали.

2021-03-12 03:27 UTC, Vallat requested changes
В целом всё неплохо, рекомендую только подправить отмеченные моменты

2021-03-12 03:27 UTC, Vallat commented on code/datums/recipe.dm
>  			for(var/i = 1; i < checklist.len+1; i++)
```suggestion
			for(var/i in 1 to length(checklist))
```
Лучше привыкать писать так. Итераций будет столько же, но быстрее
Понимаю, что это было и до этого коммита, но по возможности рекомендую изменять такой код на предложенный

2021-03-12 03:27 UTC, Vallat commented on code/datums/recipe.dm
>  	if (items && items.len)
```suggestion
	if (length(items))
```

2021-03-12 03:27 UTC, Vallat commented on code/modules/organs/external/_external.dm
> +			qdel(stump_check)
Зачем здесь это? Проходя по циклу переменной с типом ты уже совершаешь istype проверки по каждому элементу, код можно заменить на
```
    for(var/obj/item/organ/external/stump/stump in children)
        qdel(stump)
```

2021-03-12 03:27 UTC, Vallat commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		data["total_volume"] = 0 // no reagents detected, can't obtain total_volume.
Почему в двух следующих подряд строчках в одном месте FALSE, а в другом 0? Нужна хоть какая-то стандартизация, либо обе переменных FALSE, либо обе 0.
Да и в целом этот кусок кода с проверками можно заменить двумя строчками, функции выполняться будут те же
```
	data["reagents"] = data["item"]?.reagents
	data["total_volume"] = data["reagents"]?.total_volume
```

2021-03-12 03:27 UTC, Vallat commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +			O.organ_eated(M)
src здесь нигде не нужно кроме последующего делита
```
    if(istype(loc, /obj/item/organ))
		var/obj/item/organ/O = loc
		O.organ_eated(M)
```

2021-03-12 05:04 UTC, Doster-d commented on code/datums/recipe.dm
>  			for(var/i = 1; i < checklist.len+1; i++)
Это не мое, но ладно...

2021-03-12 05:05 UTC, Doster-d commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		data["total_volume"] = 0 // no reagents detected, can't obtain total_volume.
Это булевое значение, другое число, я вроде это в комменте и написал.

2021-03-12 15:41 UTC, Doster-d commented
Сделано.

2021-03-13 03:45 UTC, Vallat submitted a review, later dismissed

2021-03-13 10:31 UTC, PlinHost commented on code/datums/recipe.dm
> +			for(var/i in 1 to length(checklist))
```suggestion
			for(var/i = 1; i <= length(checklist); ++i))
```
> The main difference is that unlike in a for loop proc, the values of Step and End are calculated at the beginning and never change after that, so an expression like list.len that might be subject to change will not be read again.

2021-03-13 10:45 UTC, PlinHost commented on code/datums/recipe.dm
> +			for(var/i in 1 to length(checklist))
похуй валлат не попался

2021-03-13 11:47 UTC, Shootnik01 commented
А в миксер-то органы теперь суются?

2021-03-13 12:06 UTC, Doster-d commented
> А в миксер-то органы теперь суются?

Всегда сувались.

2021-03-13 12:07 UTC, Shootnik01 commented
> > А в миксер-то органы теперь суются?
> 
> Всегда сувались.

Я имел ввиду конечности(сори, ошибся)

2021-03-13 12:07 UTC, Doster-d commented
> > > А в миксер-то органы теперь суются?
> > 
> > 
> > Всегда сувались.
> 
> Я имел ввиду конечности(сори, ошибся)

Я на правой ноге проверил, работает, всегда работало. 20 анимал протеин дает.

2021-03-13 12:08 UTC, Shootnik01 commented
А то, помню, хотел труп спрятать, а ручки-то - не засовываются в миксер

2021-03-13 12:09 UTC, Shootnik01 commented
Проверь, пожалуйста, на локалке части тела. Может, я слишком давно на поваре играл..

2021-03-13 12:10 UTC, Doster-d commented
> Проверь, пожалуйста, на локалке части тела. Может, я слишком давно на поваре играл..

Я только что проверил, работает, миксер я не трогал, он принимает конечности.

2021-03-13 12:10 UTC, Shootnik01 commented
Все, тогда норм, спасибо

2021-03-13 14:00 UTC, Shootnik01 commented
Аппувните, хочу опробовать))

2021-03-13 15:25 UTC, Shootnik01 commented
Проверил - внутренние органы не лезут в блендер

2021-03-13 15:25 UTC, Shootnik01 commented
По крайней мере - большая часть

2021-03-13 17:24 UTC, Shootnik01 commented
Сможешь докинуть возможность перемалывать органы в блендере и делать конфеты из частей?) Если не в напряг.

2021-03-21 07:35 UTC, TobyThorne requested changes
А занулять food_organ при удалении части тела кто будет?
И eaten, не eated.

2021-03-27 07:40 UTC, Doster-d commented
> А занулять food_organ при удалении части тела кто будет?
> И eaten, не eated.

И недели не прошло, исправлено.

2021-04-02 21:11 UTC, Doster-d commented
Прошла неделя...

2021-04-17 06:09 UTC, TobyThorne commented
Вот бы ещё возможность порезать часть тела на мясо.

2021-04-20 18:47 UTC, Doster-d commented
> Вот бы ещё возможность порезать часть тела на мясо.

Сделал.

2021-04-25 22:33 UTC, Doster-d commented
Теперь не получится очень быстро убивать космонавтика.

2021-04-25 22:34 UTC, HonkyDonky commented
Ты прав, не получится

![image](https://user-images.githubusercontent.com/59123747/116011810-947fa880-a62f-11eb-872d-6cfcd88f891a.png)

2021-04-25 22:36 UTC, Doster-d commented
> Ты прав, не получится
> 
> ![image](https://user-images.githubusercontent.com/59123747/116011810-947fa880-a62f-11eb-872d-6cfcd88f891a.png)

Нет билда, нет проблемы.
![image](https://user-images.githubusercontent.com/63081538/116011853-bf69fc80-a62f-11eb-8857-0d7f0ca59fc0.png)

2021-04-25 22:37 UTC, Doster-d commented
Починил.

2021-05-11 06:19 UTC, TobyThorne requested changes
не то ткнул >:()

2021-05-11 06:48 UTC, Doster-d commented
> Ещё и вот это вот 
> ![image](https://user-images.githubusercontent.com/45202681/117770277-90ba6b80-b256-11eb-856d-889c2db0b2ae.png)
> 

Да откуда блять, у меня на локалке этого нет

2021-05-12 09:16 UTC, igorsaux requested changes

2021-05-12 09:16 UTC, igorsaux commented on code/modules/organs/external/_external.dm
>  						user.visible_message("<span class='danger'><b>[user]</b> fishes around fruitlessly in [src] with [W].</span>")
Добавил бы спаны

2021-05-12 09:16 UTC, igorsaux commented on code/modules/organs/external/_external.dm
> +						user.visible_message("<span class='danger'><b>[user]</b> rips the skin off [src] with [W], revealing a skull and meat.</span>")
И здесь спаны

2021-05-12 09:16 UTC, igorsaux commented on code/modules/organs/external/_external.dm
>  					user.visible_message("<span class='danger'><b>[user]</b> extracts [removing] from [src] with [W]!</span>")
И здесь спаны

2021-05-12 09:16 UTC, igorsaux commented on code/modules/organs/external/_external.dm
>  			. += "\n<span class='danger'>There is \a [I] sticking out of it.</span>"
И здесь спаны

2021-05-21 18:54 UTC, Doster-d commented
> Ещё и вот это вот
> ![image](https://user-images.githubusercontent.com/45202681/117770277-90ba6b80-b256-11eb-856d-889c2db0b2ae.png)

Подтверди, пожалуйста, что баг актуальный.

2021-05-21 18:55 UTC, TobyThorne commented
> Подтверди, пожалуйста, что баг актуальный.

ща потестю

2021-05-22 05:52 UTC, TobyThorne commented
На первый взгляд - всё работает. Если что-то сломается - заслапаю до крита :kek:

2021-05-22 06:01 UTC, TobyThorne requested changes

2021-05-23 11:41 UTC, TobyThorne commented on code/modules/organs/organ.dm
>  	owner = null
А почему в дестрое не обнуляется food_organ? От organ_eaten() можно вообще избавиться.

2021-05-23 12:32 UTC, Doster-d commented on code/modules/organs/organ.dm
>  	owner = null
Почему лучше перенести?

2021-05-23 12:56 UTC, TobyThorne commented on code/modules/organs/organ.dm
>  	owner = null
Так орган может дестройнуться и без поедания. И останется где-то в нуллспейсе его мясо.

2021-05-29 18:53 UTC, Doster-d commented
Ревью вхен?

2021-07-07 22:43 UTC, igorsaux approved these changes

2021-07-07 22:53 UTC, TobyThorne commented on code/modules/organs/external/_external.dm
> +						user.put_in_hands(removing)
А это точно тут нужно? Может лучше внутренние органы оставлять на турфе с частью тела, а не пихать в руки?

2021-07-07 22:55 UTC, TobyThorne commented on code/modules/organs/external/head.dm
> +	gibs(user.loc)
Ну и гиббсы тут не нужны, наверное, раз уж юзер обглодал голову до черепушки.

2021-07-07 22:57 UTC, TobyThorne commented on code/modules/organs/organ.dm
> +	target.attackby(src.return_item(), user)
```suggestion
	target.attackby(return_item(), user)
```

2021-07-07 23:03 UTC, TobyThorne approved these changes
если что-то поломается - достер пофиксит все баги генокрадов и вампиров

2021-07-07 23:04 UTC, igorsaux approved these changes

2021-07-07 23:05 UTC, merged