patch(mage)
ChaoticOnyx/OnyxBay pull request #4648
Opened 2021-03-14 16:11 UTC by Destrolaric

Я немного криво реализовал регенерацию органов, плюс описание у апгрейда наручников отсутствовало.

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-14 16:14 UTC, Doster-d approved these changes
Ок.

2021-03-14 16:14 UTC, Doster-d requested changes
Не та кнопочка.
code/game/gamemodes/wizard/wizard_heals.dm:24:error: regen_organ.status: undefined var

2021-03-15 12:05 UTC, Doster-d commented on code/game/gamemodes/wizard/wizard_heals.dm
> -	adjustToxLoss(heal.amt_dam_tox)
А это за что убрал?

2021-03-18 14:30 UTC, Destrolaric commented on code/game/gamemodes/wizard/wizard_heals.dm
> -	adjustToxLoss(heal.amt_dam_tox)
Обьясню, там оно в коде уже вызывается, поэтому был лишний вызов

2021-03-19 03:34 UTC, Doster-d approved these changes

2021-03-20 14:35 UTC, kreeperHLC approved these changes

2021-03-20 14:37 UTC, merged