Звуки
ChaoticOnyx/OnyxBay pull request #4651
Opened 2021-03-15 12:58 UTC by igorsaux

- Добавлены звуки аркадного автомата
- Добавлены звуки поджигания и взрыв топлива
- Добавлены звуки смесам, турбинам, слиперами, крио камерам, операционному столу
- Добавлен звук диктофону
- Добавлен звук тревоги при переключении шлюзов на откачку
- Добавлены звуки при передвижении в тех туннелях с небольшим шансом
- Добавлен звук сигналеру, сканерам атмосферы/ботаника, РнД консоли, включение/выключение модульных компьютеров, серверу сообщении, анализатору артефактов, голоподу
- Добавлены звуки кашля и чихания
- Добавлены эмбиенты к тех туннелям, ии, инженерам, научке

#4586

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-15 13:14 UTC, ArmenianOnyx commented
Добавьте звук смеха пожалуйста

2021-03-15 13:16 UTC, DarkHunter7756 commented
Что насчет звука крика?

2021-03-15 13:17 UTC, igorsaux commented
> Что насчет звука крика?

А что с ними?

2021-03-15 13:18 UTC, DarkHunter7756 commented
А он есть? 
> А что с ними?

2021-03-15 13:40 UTC, Artemonim commented
close #3154, close #2200, close #1396

2021-03-15 14:48 UTC, igorsaux commented
> А он есть?
> 
> > А что с ними?

Добавил 29 более протяжных криков во время горения. Нормально?

2021-03-15 14:49 UTC, Shootnik01 commented
Если еще озвучивание эмоутов сделаешь - будето вообще огонь. Но можешь и в другом пр-е

2021-03-15 14:50 UTC, Shootnik01 commented
По типу хлопания, смеха

2021-03-15 14:51 UTC, igorsaux commented
> Если еще озвучивание эмоутов сделаешь - будето вообще огонь. Но можешь и в другом пр-е

? Эмоуты же и озвучиваются
А так если найду - и другие добавлю

2021-03-15 14:52 UTC, Shootnik01 commented
> > Если еще озвучивание эмоутов сделаешь - будето вообще огонь. Но можешь и в другом пр-е
> 
> ? Эмоуты же и озвучиваются
> А так если найду - и другие добавлю

Только крик вроде озвучивался

2021-03-15 14:55 UTC, igorsaux commented
Озвучивается всё что в sound\effects\emotes есть

2021-03-15 16:50 UTC, Vallat commented on code/game/turfs/simulated/footsteps.dm
> +			return
```suggestion
			continue
```
Не лучше ли будет заменить return на continue чтобы продолжать итерацию по игрокам дальше? Иначе в 99% случаев этот код будет бесполезным. Для кода ниже справедливо тоже самое

2021-03-15 16:53 UTC, igorsaux commented on code/game/turfs/simulated/footsteps.dm
> +			return
Лол, ну да

2021-03-15 22:18 UTC, kcalbCube commented
Подробности потеряли

2021-03-16 13:19 UTC, HonkyDonky commented
Звук абсолютной тишины тоже добавить не забудь

2021-03-16 17:28 UTC, Artemonim commented
Разве данный ПР не close #3154, close #2200, close #1396 ?
По коммитам выглядит как-будто бы да.

2021-03-16 18:02 UTC, igorsaux commented
> Разве данный ПР не close #3154, close #2200, close #1396 ?
> По коммитам выглядит как-будто бы да.

Добавил

2021-03-17 20:25 UTC, kreeperHLC requested changes
Чтобы сыграть психически нездорового, убитого депрессией человека, Голиаф несколько часов проверял 440 файлов этого ПРа.

2021-03-17 20:25 UTC, kreeperHLC commented on code/modules/emotes/definitions/audible.dm
>  /decl/emote/audible/grunt
Строку пропустить забыл

2021-03-20 14:33 UTC, kreeperHLC approved these changes

2021-03-20 15:03 UTC, Doster-d approved these changes
По битам прочитал .ogg файлы, нашел эксплоты.

2021-03-20 15:56 UTC, merged

2021-03-29 14:53 UTC, Epicus7 commented
Пролезло мимо геймдизайнеров