Убрал рест у киборгов
ChaoticOnyx/OnyxBay pull request #4703
Opened 2021-03-23 14:28 UTC by HonkyDonky

Убрал возможность рестить за боргов, потому что эта хуйня кидает их в вечный стан, который решается только педально
fix #4544 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-23 14:29 UTC, Vallat requested changes

2021-03-23 14:29 UTC, Vallat commented on code/modules/mob/living/silicon/robot/robot.dm
> +	set category = null
```suggestion
	return
```
Че за костыли изобретаешь, это вот так убирается

2021-03-24 21:26 UTC, kreeperHLC approved these changes

2021-03-26 23:47 UTC, TobyThorne approved these changes

2021-03-27 14:11 UTC, merged