experimental(auxtools): adds auxtools support
ChaoticOnyx/OnyxBay pull request #4714
Opened 2021-03-25 04:36 UTC by eckff

nuff said

Имплементирует поддержку [auxtools](https://github.com/willox/auxtools) которая будет полезна для отладки в VSC с помощью SpaceDMM.
Работает при запуске F5 при скомпилированном билде. На живом сервере использоваться, собственно, не будет.

Он уже ловит ошибки которые "приостанавливают" игру, так что не удивляйтесь если ваша игра зависнет. Вам просто надо нажать на кнопочку продолжить в вискоде.

Список текущих ошибок которые выявились с начала локального раунда.
```
Debug Server: "Pausing execution (reason: Runtime(\"code/modules/admin/banjob_iaa.dm:178:Assertion Failed: establish_db_connection()\"))"
Debug Server: "Pausing execution (reason: Runtime(\"Shuttle \\\"Creaker\\\" could not find its starting location.\"))"
Debug Server: "Pausing execution (reason: Runtime(\"bad client\"))"
```
Текущий список фич найдёте по ссылке выше в [описании](https://github.com/willox/auxtools#features).

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-27 14:03 UTC, kreeperHLC requested changes

2021-03-27 14:03 UTC, kreeperHLC commented on .vscode/launch.json
> +}
![image](https://user-images.githubusercontent.com/14943437/112723197-6454c500-8f1e-11eb-8657-5993f7d816e9.png)

2021-03-29 07:08 UTC, eckff commented on .vscode/launch.json
> +}
```suggestion
}

```

2021-03-29 07:09 UTC, eckff commented on .vscode/launch.json
> +}
Ладно

2021-03-29 10:22 UTC, igorsaux approved these changes

2021-03-29 11:21 UTC, Doster-d approved these changes
Инструменты - круто

2021-03-31 20:53 UTC, kreeperHLC approved these changes

2021-04-02 16:38 UTC, merged