Update contributing.md
ChaoticOnyx/OnyxBay pull request #4719
Opened 2021-03-26 14:50 UTC by Vallat

Добавил пару хороших фишек!

Иссуев нет.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-26 15:13 UTC, Shootnik01 commented
Каких например?

2021-03-26 15:46 UTC, Vallat commented
> Каких например?

Так прочитай в измененных файлах...

2021-03-27 06:44 UTC, Epicus7 requested changes

2021-03-27 06:44 UTC, Epicus7 commented on docs/contributing.md
> +Вместо `for(var/turf/T in range(N, src))` и подобного лучше написать `for(var/turf/T in block(locate(x-N, y-N, z), locate(x+N, y+N, z)))`
`for(var/turf/T in block(locate(x-N, y-N, z), locate(x+N, y+N, z)))`

Тут же будет проверка типа для каждого T

2021-03-27 06:44 UTC, Epicus7 commented on docs/contributing.md
> +Вместо `for(var/turf/T in range(N, src))` и подобного лучше написать `for(var/turf/T in block(locate(x-N, y-N, z), locate(x+N, y+N, z)))`
Алсо, может хелпер напишешь?)

block_range(B, src) какой-нибудь. А то выглядит страшно сейчас и ошибиться легко, где-нибудь x с y перепутать.

2021-03-27 06:44 UTC, Epicus7 commented on docs/contributing.md
> +Можно с легкостью заменить на `#define GIVE_SUM(a, b) (a + b)`
Фигня полная. Дефайны очень сильно усложняют дебаг, особенно когда их много.

Не любые короткие функции надо заменять на дефайны, а только те короткие функции, которые очень часто вызываются в каких-нибудь циклах важных. А это оценить довольно сложно - надо брать профайлер и считать. На простенький и очевидный совет не тянет, эту секцию вообще лучше убрать.

2021-03-27 06:44 UTC, Epicus7 commented on docs/contributing.md
> +```
Работающий код для случая выше выглядит так:

```DM
var/variable = 1
switch(variable)
	if(1)
		world.log << "FIRST CASE"
	if(2 to 5)
		world.log << "SECOND CASE"
	if(5 to 10)
		world.log << "THIRD CASE"
```

Один и тот же вариант в двух кейсах - это баг. Зачем вообще так делать? Если не пытаться пихать один и тот же вариант в два кейса, то и совет не нужен. Не вижу смысла это добавлять в гайд.

2021-03-27 06:49 UTC, Vallat commented on docs/contributing.md
> +Вместо `for(var/turf/T in range(N, src))` и подобного лучше написать `for(var/turf/T in block(locate(x-N, y-N, z), locate(x+N, y+N, z)))`
У вас уже есть RANGE_TURFS для этого, как оказалось. Можно в целом заменить на это. А проверка на тип нужна будет если проходишься не по обычным турфам, а, условно по стенам. Но очевидно, да, что в представленном случае лучше будет добавить as()

2021-03-27 07:02 UTC, closed without merging