Changelog redesign
ChaoticOnyx/OnyxBay pull request #4720
Opened 2021-03-26 18:08 UTC by igorsaux

Немного поигрался с шрифтами.

<details>
<summary>До</summary>
<img width="342" alt="before1" src="https://user-images.githubusercontent.com/55196698/112674584-29e41d00-8e77-11eb-80d9-63c608b578c7.png">
</details>

<details>
<summary>После</summary>
<img width="348" alt="after3" src="https://user-images.githubusercontent.com/55196698/112674637-34061b80-8e77-11eb-92ca-1015719aa7b2.png">
<img width="343" alt="after2" src="https://user-images.githubusercontent.com/55196698/112674633-34061b80-8e77-11eb-8d78-59d04ca7a342.png">
<img width="342" alt="after1" src="https://user-images.githubusercontent.com/55196698/112674628-336d8500-8e77-11eb-800e-a10a7ac31b72.png">
</details>

Также обновил Font Awesome
RIP иконки

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-27 14:05 UTC, kreeperHLC requested changes

2021-03-27 14:05 UTC, kreeperHLC commented on html/templates/header.html
> +		<div class="commit font-huge">
![image](https://user-images.githubusercontent.com/14943437/112723267-aa118d80-8f1e-11eb-842f-83f56ebb7704.png)

2021-03-27 14:16 UTC, igorsaux commented on html/templates/header.html
> +		<div class="commit font-huge">
Так и надо

2021-03-27 14:17 UTC, kreeperHLC submitted a review, later dismissed

2021-04-14 05:05 UTC, HonkyDonky submitted a review, later dismissed
ХЗ, вроде норм.

2021-04-14 05:05 UTC, HonkyDonky commented
а блять тут конфликт сука

2021-04-21 14:06 UTC, kreeperHLC commented on html/changelog.css
> +}
Ха попался

2021-04-21 14:06 UTC, kreeperHLC commented on html/templates/header.html
> +		<div class="commit font-huge">
И тут

2021-04-21 14:15 UTC, igorsaux commented on html/templates/header.html
> +		<div class="commit font-huge">
Так и надо x2

2021-04-21 14:19 UTC, kreeperHLC approved these changes

2021-04-21 14:22 UTC, kreeperHLC submitted a review, later dismissed

2021-04-21 14:29 UTC, Doster-d approved these changes

2021-04-25 22:31 UTC, TobyThorne approved these changes
![image](https://user-images.githubusercontent.com/45202681/116011726-3ad7a800-a648-11eb-9d7f-f7eaad5ea124.png)
всяко где-то бэкдоры

2021-04-25 22:32 UTC, HonkyDonky approved these changes
Так вот почему Оникс падает, всё из-за бэкдуров Игоря

2021-04-29 00:03 UTC, merged