Syndicate Cigarettes rework
ChaoticOnyx/OnyxBay pull request #4726
Opened 2021-03-27 19:08 UTC by Zert0X

1. Создан новый вид сигарет syndi_cigs с увеличенным chem_amount с 5 до 15 для хороших реакций(возможно изменение для баланса)
2. Создана ./syndi_cigs/flash. Сигарета флешка при закуривании(задержка до первой затяжки)и поджигании станит ~5 секунд(возможен ребаланс)
3. Создана ./syndi_cigs/smoke. Сигарета дымовуха при закуривании и поджигании создаёт пук дыма вокруг игрока общей(очень не плотный подойдёт при побеге в техах, закурил и в шкаф залез)
4. Создана ./syndi_cigs/mind_breaker. Сигарета наркоманов при закуривании и недлительном курении(хватает пару затяжек) начинаются глюки.
5. Создана ./syndi_cigs/tricordrazine. Сигарета лечилка, действует как tricordrazine...
6. В связи с моей кривозадостью созданы пачки для данных сигарет они абсолютно одинаковы кроме содержимого и описания(окончания)
7. Добавлен флаг ATOM_FLAG_NO_REACT для сигарет flash, smoke. Связано с тем что сразу при покупке сигарет они срабатывали
8. Дополнен обработчик зажигания сигарет согласно 7-му пункту. А точнее проверка на syndi_cigs и установка стандартного числа в поле "atom_flags"(было взято с других сигарет, проверялось через view variables)
9. Переделана покупка кита в аплинке
Примечания:
1. Все сигареты забиты под завязку

close #2048

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-27 19:14 UTC, igorsaux requested changes

2021-03-27 19:14 UTC, igorsaux commented on code/game/objects/items/weapons/smokables/smokables.dm
> +			atom_flags=48
Нужный отступы

2021-03-27 19:14 UTC, igorsaux commented on code/game/objects/items/weapons/storage/fancy.dm
> +	startswith= list(/obj/item/clothing/mask/smokable/cigarette/syndi_cigs/tricordrazine = 10)
И тут отступы

2021-03-27 19:16 UTC, Zert0X commented on code/game/objects/items/weapons/storage/fancy.dm
> +	startswith= list(/obj/item/clothing/mask/smokable/cigarette/syndi_cigs/tricordrazine = 10)
немного тупой скажи, что не так более точно, пожалуйста

2021-03-27 19:25 UTC, Doster-d commented on code/game/objects/items/weapons/storage/fancy.dm
> +	startswith= list(/obj/item/clothing/mask/smokable/cigarette/syndi_cigs/tricordrazine = 10)
На 250 между знаком ```=``` стоит по два пробела, сделай так же и тут, и выше.

2021-03-27 19:25 UTC, Doster-d commented on code/game/objects/items/weapons/smokables/smokables.dm
> +			atom_flags=48
Тут тоже самое.

2021-03-27 19:26 UTC, Doster-d requested changes

2021-03-27 19:26 UTC, Doster-d commented on code/game/objects/items/weapons/smokables/cigarettes.dm
> +/obj/item/clothing/mask/smokable/cigarette/syndi_cigs/
Убери / на конце, глазам больно
```suggestion
/obj/item/clothing/mask/smokable/cigarette/syndi_cigs
```

2021-03-27 20:09 UTC, igorsaux requested changes

2021-03-27 20:09 UTC, igorsaux commented on code/game/objects/items/weapons/smokables/smokables.dm
>  		src.lit = 1
```suggestion
  if(src.lit)
      return
    
  src.lit = 1
```

2021-03-27 20:11 UTC, Zert0X commented on code/game/objects/items/weapons/smokables/smokables.dm
>  		src.lit = 1
а как же код взрыва который внутри этого ифа? Или тут ретурн не прерывает код?

2021-03-27 20:13 UTC, Doster-d commented on code/game/objects/items/weapons/smokables/smokables.dm
>  		src.lit = 1
Не прерывает, первый случай, когда ты запустил реакцию, lit = FALSE, после всех процедур и реакция пойдет и иф не нужен будет в таком случае.

2021-03-27 20:24 UTC, igorsaux approved these changes

2021-03-27 20:33 UTC, igorsaux approved these changes

2021-03-27 20:35 UTC, Doster-d submitted a review, later dismissed

2021-03-28 18:32 UTC, TobyThorne requested changes

2021-03-28 18:32 UTC, TobyThorne commented on code/game/objects/items/weapons/smokables/cigarettes.dm
> +	filling = list(/datum/reagent/tricordrazine = 15)
А можно ньюлайны пожалуйста.

2021-03-28 20:27 UTC, Zert0X commented on code/game/objects/items/weapons/smokables/cigarettes.dm
> +	filling = list(/datum/reagent/tricordrazine = 15)
тоби вернись я всё прощу, самое главное зелень поставь

2021-03-28 20:39 UTC, TobyThorne approved these changes

2021-03-28 20:40 UTC, Doster-d approved these changes

2021-03-28 20:41 UTC, igorsaux approved these changes

2021-03-29 20:47 UTC, merged