Позволяем пневмопушке кормить людей
ChaoticOnyx/OnyxBay pull request #4737
Opened 2021-03-29 23:30 UTC by HonkyDonky

Надоели тощие трапы? Хотите отыграть бабушку, что насильно кормит своих вымышленных внучат? Или же может желаете накормить всю станцию тем странным радиоактивным йогуртом из научного отсека? Не беда! Теперь пневмопушка поможет вам в этом.

Пневмопушка теперь может насильно накормить любого члена экипажа с **двойной эффективностью**.  Пневмопушка  кормит только в том случае, если пользователь нацелился на голову или же рот. Пневмопушка не может кормить людей с прикрытым ртом. 

Вроде бы всё.

close #2818

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-30 00:04 UTC, TobyThorne requested changes
"thrown", не "throwed"

2021-03-30 01:06 UTC, HonkyDonky commented
> "thrown", не "throwed"

Это единственное замечание к этому ПРу? Может ещё что-то есть? Спрашиваю, чтобы сразу сделать.

2021-03-30 01:10 UTC, TobyThorne commented
Ещё бы оставить прок только при прицеле в рот, без головы.
А так - ещё не нашёл ничего, к чему бы доебаться. Но у меня сейчас глаз замылился.

2021-03-30 07:02 UTC, Shootnik01 commented
После стольких лет..

2021-03-30 10:21 UTC, TobyThorne submitted a review, later dismissed
Я ещё найду до чего доебаться. Или не найду.

2021-03-30 13:26 UTC, Doster-d requested changes
Я нашел.

2021-03-30 13:26 UTC, Doster-d commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	if(!istype(H) || !istype(thrown_with, /obj/item/weapon/gun/launcher) || target_zone != BP_MOUTH || !reagents.total_volume || !is_open_container() || !H.check_has_mouth() || H.check_mouth_coverage())
Нет проверки, что fullness человека меньше 550

2021-03-30 13:26 UTC, Doster-d commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	On_Consume(H)
Может между 133 и 134 поставишь update_icon()?

2021-03-30 13:42 UTC, Doster-d commented on code/game/atoms_movable.dm
> +		throw_impact(get_turf(src),speed)
Пробел забыл.

2021-03-30 15:05 UTC, HonkyDonky commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	if(!istype(H) || !istype(thrown_with, /obj/item/weapon/gun/launcher) || target_zone != BP_MOUTH || !reagents.total_volume || !is_open_container() || !H.check_has_mouth() || H.check_mouth_coverage())
Блин, я хотел, чтобы это было фичей. Типа насильно впихивать прямо в глотку, несмотря на то, что персонаж уже вдоволь нажрался. Ну ладно.

2021-03-30 15:07 UTC, HonkyDonky commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	On_Consume(H)
Вроде ставил, а его нет. Поставлю.

2021-03-30 15:08 UTC, HonkyDonky commented on code/game/atoms_movable.dm
> +/atom/movable/proc/throw_at(atom/target, range, speed, thrower, thrown_with, target_zone)
Да, тут похуй.

2021-03-30 15:11 UTC, Doster-d commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	if(!istype(H) || !istype(thrown_with, /obj/item/weapon/gun/launcher) || target_zone != BP_MOUTH || !reagents.total_volume || !is_open_container() || !H.check_has_mouth() || H.check_mouth_coverage())
Ну так напиши это в описание ПРа, и пусть геймдиз решит.

2021-03-30 16:33 UTC, Doster-d approved these changes

2021-04-02 15:58 UTC, TobyThorne approved these changes
Вроде кудел(ССмастер) нету, тестить это я конечно же не буду.
Доверюсь 
![image](https://user-images.githubusercontent.com/45202681/113432039-82c72e80-93fe-11eb-9053-6bccd07f6194.png)
и галочке Тостера.

2021-04-02 15:59 UTC, merged