Вас посетил стайлкоп 2
ChaoticOnyx/OnyxBay pull request #4754
Opened 2021-03-31 11:56 UTC by igorsaux

Убрал относительные пути, добавил отступы у операторов деления и слэшы в начале путей

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-31 12:08 UTC, TobyThorne commented
стильный окоп пощади как это ревьювать

2021-04-02 16:53 UTC, kreeperHLC requested changes
![image](https://user-images.githubusercontent.com/14943437/113436262-142da500-93ed-11eb-8d72-8cf54482fe4f.png)

2021-04-02 16:55 UTC, TobyThorne commented
Первая часть Стайлокопа заcumфликтила эту.

2021-04-02 17:08 UTC, TobyThorne commented
ой бля пиздец какой он огромный((((((
оставлю на завтра

2021-04-04 15:21 UTC, HonkyDonky approved these changes
Глянул с начала до конца быстренько, бэкдуров не нашёл.

2021-04-21 12:38 UTC, kreeperHLC commented
Ооо, опять конфликты

2021-05-02 17:41 UTC, closed without merging