fix(arithrazine): prothesis damage from arithrazine
ChaoticOnyx/OnyxBay pull request #4764
Opened 2021-03-31 20:32 UTC by vekotov

Добавил новый прок для human'ов, который позволяет нанести дамаг рандомной органической конечности (не протезу). Также добавил этот прок в метаболизм аритразина, чтобы он не наносил дамаг протезам. Фолбэк к mob/living/carbon на всякий случай оставил.

![Screenshot_6](https://user-images.githubusercontent.com/38394905/113207429-ce60c780-929a-11eb-9b2e-a9c667d3e0aa.png)

fix #4731

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-03-31 20:41 UTC, igorsaux submitted a review, later dismissed

2021-03-31 20:43 UTC, Doster-d approved these changes

2021-04-02 15:50 UTC, TobyThorne requested changes

2021-04-02 15:50 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +		if(istype(M, /mob/living/carbon/human))
```suggestion
		if(ishuman(M))
```

2021-04-02 16:25 UTC, Doster-d approved these changes

2021-04-02 16:25 UTC, TobyThorne approved these changes

2021-04-02 16:26 UTC, merged