fixes(borgs, drones and resleevers)
ChaoticOnyx/OnyxBay pull request #4820
Opened 2021-04-03 13:40 UTC by Shirlineyn

Разрезолвил несколько иссуев:
- в ресливер теперь можно класть штуки (мартышки еее) драг'н'дропом
- сервис грипперы теперь могут в кухонные машинки
- грипперы теперь могут вставлять батарейки в PSUшки
- дропперы теперь нельзя перемолоть в гриндере
- дроны теперь могут в надувные стены
- и самое вкусное: киборгов-триторов теперь нельзя емагнуть, но они могут емагнуть себя сами, используя соответствующий верб.

closes #2325
closes #3831 
closes #3030
closes #2798
closes #3444

-[x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-03 13:46 UTC, DarkHunter7756 commented
Боже храни разраба. Однако у боргов есть еще тонна проблем с манипуляторами. По типу невозможности подбора дисков вирусов или деталей ботов

2021-04-03 13:49 UTC, MrMagick2104 commented
> и самое вкусное: киборгов-триторов теперь нельзя емагнуть

Зачем убирать такую возможность? Очень забавно же за киборга-тритора совершать эпичные предательства под конец.

Лучше бы убрать смешной шанс с емага киборга и заменить на что-нибудь более нормальное, по типу обнуления зарядов у емага или банального каста в пару секунд, чтобы нельзя было лолемагнуть.

2021-04-03 13:52 UTC, Doster-d requested changes
В целом неплохо.

2021-04-03 13:52 UTC, Doster-d commented on code/game/antagonist/antagonist_create.dm
> +	to_chat(R, "<span class='notice'>ATTENTION! Your safety protocols are still active, override is avaliable.</span>")
Замени на спаны

2021-04-03 13:52 UTC, Doster-d commented on code/game/machinery/resleever.dm
> +		to_chat(user, "<span class='notice'>\The [src] is in use.</span>")
Замени на спаны

2021-04-03 13:52 UTC, Doster-d commented on code/modules/mob/living/silicon/robot/robot.dm
> +		src.verbs |= /mob/living/silicon/robot/proc/ResetSecurityCodes
Если робот находится в контейнере, то возможно у него не будут вербы, лучше просто сделай проверку на то, что робот может емагнуть себя в самом проке.

2021-04-03 13:52 UTC, DarkHunter7756 commented
> Зачем убирать такую возможность? Очень забавно же за киборга-тритора совершать эпичные предательства под конец.

Вероятность, что тебя емагнет тритор, на которого у тебя цель крайне мала. А вот дополнительный модуль уже тритор-боргу будет хорошо помогать. Научный борг-роботех начнет обращать железную армию, сервисный отравит цель и так далее

2021-04-03 13:54 UTC, Shirlineyn commented on code/game/antagonist/antagonist_create.dm
> +	to_chat(R, "<span class='notice'>ATTENTION! Your safety protocols are still active, override is avaliable.</span>")
в чем разница?

2021-04-03 13:54 UTC, MrMagick2104 commented
> Вероятность, что тебя емагнет тритор, на которого у тебя цель крайне мала.

Ле епик гринтекст не обязателен для убийства.

> А вот дополнительный модуль уже тритор-боргу будет хорошо помогать. Научный борг-роботех начнет обращать железную армию, сервисный отравит цель и так далее

Возможность самоемага - это круто, да, но я о том, что хорошо было бы не убирать возможность хотя бы визуально законы менять при емаге тритором, без обнаружения роли у киборга и отсутствия взаимодействия.

2021-04-03 13:57 UTC, Doster-d commented on code/game/antagonist/antagonist_create.dm
> +	to_chat(R, "<span class='notice'>ATTENTION! Your safety protocols are still active, override is avaliable.</span>")
Мой вариант не нарушает гайд ту девеломпент, твой нарушает.

2021-04-03 13:58 UTC, DarkHunter7756 commented
> не убирать возможность хотя бы визуально законы менять при емаге тритором

Визуальное изменение и есть изменение? Я знатно так кекал, когда мне, тритору, меняли законы с убийства на подчинение убийце в убийстве. 
Достаточно простого сообщения _Вас емагают_

2021-04-03 14:24 UTC, Shirlineyn commented
Окей, тогда оставляем возможность емагать боргов-триторов с законами и прочей еботенью, но даем им возможность сменить себе мастера на самого себя(влияет на мастера в законах, если будешь потом ломать других боргов) с помощью того же верба.

2021-04-03 14:24 UTC, Doster-d approved these changes

2021-04-04 15:08 UTC, HonkyDonky requested changes
это конечно же ещё не одобрено, но всё же

2021-04-04 15:08 UTC, HonkyDonky commented on code/game/antagonist/antagonist_create.dm
> +	R.add_robot_verbs()
Сюда или ещё куда-нибудь проверку на `isrobot()`, иначе рантаймы будут, потому что будет вызываться у людей, у которых нет этого прока.

2021-04-07 16:15 UTC, Shirlineyn commented on code/game/antagonist/antagonist_create.dm
> +	R.add_robot_verbs()
done

2021-04-09 11:19 UTC, TobyThorne requested changes

2021-04-09 11:19 UTC, TobyThorne commented on code/modules/mob/living/silicon/robot/robot.dm
> +	set desc = "Scrambles your security and identification codes and resets your current buffers. Unlocks you and but permenantly severs you from your AI and the robotics console and will deactivate you
and but

2021-04-09 20:24 UTC, Shirlineyn commented on code/modules/mob/living/silicon/robot/robot.dm
> +	set desc = "Scrambles your security and identification codes and resets your current buffers. Unlocks you and but permenantly severs you from your AI and the robotics console and will deactivate you
but and

2021-04-14 02:00 UTC, TobyThorne requested changes

2021-04-21 13:24 UTC, kreeperHLC approved these changes

2021-05-23 11:50 UTC, TobyThorne requested changes

2021-05-23 11:50 UTC, TobyThorne commented on code/game/machinery/resleever.dm
> +		if(!target || !(target in range(2,src)))
```suggestion
		if(!target || !(target in range(2, src)))
```

2021-05-23 11:50 UTC, TobyThorne commented on code/modules/mob/living/silicon/robot/robot.dm
> +		if (LC)
```suggestion
		if(LC)
```

2021-06-18 20:48 UTC, TobyThorne commented
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 2 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2021-06-23 21:11 UTC, Doster-d commented
Аффтар, напиши ченджлог

2021-06-23 21:28 UTC, Doster-d commented
Бот, ты пьян, иди нахуй.

2021-06-23 21:34 UTC, Shirlineyn commented
![makkonahi-nervno-kurit-photo-big.png](https://user-images.githubusercontent.com/26092405/123171069-fc157100-d483-11eb-95f5-bccaa0d76c3e.png)

2021-06-23 21:38 UTC, Doster-d commented
Победа человеческого разума над ченджлогом

2021-06-28 23:49 UTC, TobyThorne approved these changes
Вроде, компилируется.

2021-06-29 00:00 UTC, Doster-d approved these changes

2021-06-29 00:01 UTC, merged