Сообщение с ЦК о подозрительных типах
ChaoticOnyx/OnyxBay pull request #4841
Opened 2021-04-07 06:11 UTC by HonkyDonky

**Attention, enemy communication intercepted. Security level elevated.**

Возвращаем старую фичу, которая создавала доклад о подозрительных типах, что возможно работают на синдикат.

**Фиче нужна проработка геймдизайнеров**. В иссуе не было подробно сказано про то, как конкретно нужно делать, так что я поставил то, что посчитал наилучшим вариантом.

Как оно сейчас работает:
- В начале раунда запускается таймер со случайным значением от 10 до 30 минут. За это время, по идеи, антаги должны подготовиться. 
- По истечению этого времени запускается `send_intercept()`, тот сначала собирает список подозрительных типов из списка всех гуманоидов в таком порядке:

1. Антаг ли? Если да - спавнится ли он на станции? Если нет - не включать в список вообще (для исключения магов, мерков, ниндзей и т.п.). Если да - добавить в список с шансом `suspicion_chance`, который равняется у трейтора = 40%, у культяпки - 30%, у остальных - 50%.
2. Игрок не антаг, но у него резко отрицательное отношение к НТ - добавить с шансом в 50%. Просто же отрицательное отношение - 20%.
3. В остальных случаях - добавить с 10% шансом.

- Получив список sus'ов - тот записывает их в доклад либо просто указав должность (Someone with the job of **Assistant**), либо напрямую указав имя вместе с должностью (**Honky**, the **Assistant**). Шанс в 51% на то, что будет просто должность. У каждого sus'а свой шанс на тип доноса.
- После этого он начинает искать исправные модулярные консоли с новой деталькой, которую я решил обозвать как `interceptor`. Деталька может быть вставлена только в консоли. Деталь используется в качестве основного признака того, куда же нужно скидывать доклад. Пресет консоли с такой деталью я поставил прямо на мостик. Ещё одна такая деталь лежит в хранилище телекомов. Также её можно сделать в рнд без особого труда. 
- В случае, если доклад был успешно отправлен хотя бы на одну консоль - поднять уровень до синего, если тот всё ещё зеленый. 
- В этом же случае, если sus из доклада и вправду антаг - выдать ему предупреждение о том, что он попал в доклад. Если же он ещё и татор, у которого есть скрытый аплинк - докинуть 20 телекристаллов.

Всё!
Я не уверен касательно шансов, они все взяты с Вайта 2014.
Я не уверен касательно того, как правильно передавать сам доклад, так что воспользовался деталькой. Почему не просто ландмарк, на которой бы спавнился доклад? Ну, потому что консоль за это могут снести/сломать/взорвать, ну вы поняли.
Я также не уверен касательно названия доклада и того, как оформлен текст в нём. 

<details>
  <summary>Вот картиночка с доклада:</summary>
  
  ![image](https://user-images.githubusercontent.com/59123747/113818021-d9769480-977f-11eb-9d5e-b5ff0b99c498.png)
</details>
close #2968 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-07 06:53 UTC, kcalbCube commented on code/game/gamemodes/game_mode.dm
> +	var/const/waittime_l = 10 MINUTES        //lower bound on time before intercept arrives
Десять минут маловато, не? Обычно в это время только-только щиты устанавливают.

2021-04-07 07:09 UTC, HonkyDonky commented on code/game/gamemodes/game_mode.dm
> +	var/const/waittime_l = 10 MINUTES        //lower bound on time before intercept arrives
А вот не знаю
Пускай геймдизы скажут как лучше

2021-04-07 07:21 UTC, kcalbCube approved these changes
четко.

2021-04-07 10:34 UTC, Ershovdi commented
Давайте ещё боёвку с ТГ возьмем, будем МОДНЫМИ. Короче, нет. Это не нужно и превратит игру в ролькохант, каким и является... тгстанция

2021-04-07 14:47 UTC, Doster-d requested changes

2021-04-07 14:47 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/living/carbon/human/H in GLOB.player_list)
```suggestion
	for(var/mob/living/carbon/human/H in GLOB.human_mob_list)
```

2021-04-07 14:47 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	if(!length(suspects))
Может чуть выше переместить?

2021-04-07 14:47 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/M in GLOB.player_list)
```suggestion
	for(var/mob/M in GLOB.human_mob_list)
```

2021-04-07 14:47 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	var/sound/S = security_level_changed ? sound('sound/AI/intercept_level.ogg') : sound('sound/AI/intercept.ogg')
Зачем этот звук?
Зачем ты его запускаешь в тот же момент, когда идет звук обновления кода?

2021-04-07 14:47 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +			to_chat(M, SPAN("danger", "They are on to you!"))
С фразой что-то не так, а что я не понимаю, можешь ее преобразовать как-то, пожалуйста?

2021-04-07 14:47 UTC, Doster-d commented on code/modules/modular_computers/computers/subtypes/dev_console.dm
> +	GLOB.modular_consoles |= src
```suggestion
	GLOB.modular_consoles.Add(src)
```

2021-04-07 14:47 UTC, Doster-d commented on code/modules/modular_computers/computers/subtypes/dev_console.dm
> +	GLOB.modular_consoles -= src
```suggestion
	GLOB.modular_consoles.Remove(src)
```

2021-04-07 15:35 UTC, HonkyDonky commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/M in GLOB.player_list)
Здесь как раз таки нужен `GLOB.player_list`, чтобы отправить сообщение всем живым и неживым игрокам. А в твоём случае он отправит звук только людям.

2021-04-07 15:37 UTC, HonkyDonky commented on code/game/gamemodes/game_mode.dm
> +	var/sound/S = security_level_changed ? sound('sound/AI/intercept_level.ogg') : sound('sound/AI/intercept.ogg')
Здесь создаётся датум звука, который будет отправлен игроку. Если же уровень был сменен - выбирается звук с частью, в которой про это и говорится. 
Потом же этот датум отправляется игроку.

2021-04-07 15:37 UTC, HonkyDonky commented on code/game/gamemodes/game_mode.dm
> +			to_chat(M, SPAN("danger", "They are on to you!"))
Да, не так. Я написал про это в описании. Пускай геймдизы решат как тут лучше. И нужно ли это сообщение вообще.

2021-04-07 15:37 UTC, HonkyDonky commented on code/modules/modular_computers/computers/subtypes/dev_console.dm
> +	GLOB.modular_consoles |= src
Мои варианты короче и работают точно так же. Так что оставлю.

2021-04-07 15:49 UTC, HonkyDonky commented
> Давайте ещё боёвку с ТГ возьмем, будем МОДНЫМИ. Короче, нет. Это не нужно и превратит игру в ролькохант, каким и является... тгстанция

Пчел, ты. Хоть бы удосужился подробно расписать причины, по которым не нужно делать подобное. А так, мнение вроде "Короче, нет, удаляйте" - можешь смыть у себя в толчке.

2021-04-07 15:53 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +			to_chat(M, SPAN("danger", "They are on to you!"))
_They are on to you!_ как по мне коряво написано, а что не так я не могу сказать. Сама идеи фразы хорошая, но вот запись мне не нравится, можно как-то преобразовать, к примеру, _Nanotrasen' employees have information about you._

2021-04-07 15:53 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	var/sound/S = security_level_changed ? sound('sound/AI/intercept_level.ogg') : sound('sound/AI/intercept.ogg')
У тебя разве звук не накладывается?

2021-04-07 15:54 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/M in GLOB.player_list)
А зачем new_playerам этот звук?

2021-04-07 15:56 UTC, HonkyDonky commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/M in GLOB.player_list)
А их нет в этом списке.
Смотри `_global_vars/mods.dm`
`GLOBAL_LIST_EMPTY(player_list)      //List of all mobs **with clients attached**. Excludes /mob/new_player`

2021-04-07 15:56 UTC, HonkyDonky commented on code/game/gamemodes/game_mode.dm
> +	var/sound/S = security_level_changed ? sound('sound/AI/intercept_level.ogg') : sound('sound/AI/intercept.ogg')
Нет, я всё тестил.

2021-04-07 15:59 UTC, igorsaux approved these changes

2021-04-07 16:14 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/M in GLOB.player_list)
Жопой читал строкой я, окей.

2021-04-08 00:08 UTC, HonkyDonky commented
Поправлено с учётом геймдизайнерских решений.

2021-04-08 03:09 UTC, kcalbCube commented
> Давайте ещё боёвку с ТГ возьмем, будем МОДНЫМИ. Короче, нет. Это не нужно и превратит игру в ролькохант, каким и является... тгстанция

На тау сети рп больше будет чем в типичном ченджлинге оникса

2021-04-08 03:14 UTC, kreeperHLC commented
> > Давайте ещё боёвку с ТГ возьмем, будем МОДНЫМИ. Короче, нет. Это не нужно и превратит игру в ролькохант, каким и является... тгстанция
> 
> На тау сети рп больше будет чем в типичном ченджлинге оникса

Напомните мне, зачем мы всё ещё Кубика не забанили?

2021-04-08 03:16 UTC, Doster-d commented
> На тау сети рп больше будет чем в типичном ченджлинге оникса

Ну и в чем смысл этого сообщения в данном ПРе?

2021-04-08 03:31 UTC, Ershovdi commented
Скорое будет эссе от одного из активистов Кодеранска.
Во-первых, кто спрашивал и кто просил эту ФИЧУ, нагло украденную и Ониксу ненужную. 
Во-вторых, вы там совсем *****? Минимальное время ПЯТЬ минут для палева трейтора? Ещё учитывая то, что на бумажке пишется должность чувачка. А ещё с меньшим шансом и его имя. Я вам обещаю, начнётся *тупой* ролькохант от офицеров.
Ну и вот возьмем условного ХоПа. Сидит он себе, придумывает план. И тут на, в консоли на мостике прилетает документик о том, что ХоП, сука, антаг. Его же сразу пойдут проверять и палить. Ну ладно, контрится это удалением перехватчика на консоли, НО ЭТО ТОЖЕ МОЖНО СПАЛИТЬ, если знать как! Позовут детектива, ХоПу придется играть в Бэтмена, только плохого. Буквально в первые пять-пятнадцать минут будет начинаться хаос, который должен набирать обороты ПОСТЕПЕННО. 
На горящей жопе выразил своё отношение к недальновидности кодера, которого никто не просил это делать.

2021-04-08 03:34 UTC, Ershovdi commented
В любом случае, убери хотя бы шанс на имя, а также палево единичной должности по типу бармена или кловна.

2021-04-08 04:09 UTC, kreeperHLC commented
Так там же будет не только имя условного ХоПа, а ещё и четверо других рандомов, которых тоже нужно будет проверить

2021-04-08 11:18 UTC, TheUnknownOneGH commented
Я - активист Кодеранска, и я несу вам сказ про то, почему эта идея плохая, говоря приличным языком.
Здесь нет придирок к коду или к конкретным личностям. На обоих сайтах одинаковые версии, читайте где кому удобнее.
https://pastebin.com/ZRXrN1ZT
https://ghostbin.co/paste/u7hn

2021-04-08 11:59 UTC, kemperhun commented
Большинства описанных в пасте проблем можно избежать, привязав бумажку к сторителлеру. Если антаги ничего не делают, соответственно, не дают улик - бумажка прилетает, начиная движ. Если антаги налутали гринтекст за пять минут и теперь готовят бомбы для спидрана - бумажка прилетает с целью им помешать. Если антаги и СБ играют в свои игрища и без бумажки - бумажка не прилетает.

2021-04-08 12:42 UTC, TheUnknownOneGH commented
Тоже хороший вариант, на самом деле, о котором я не подумал, возможно даже чем-то лучше того, что предложил я.
Переназначить эту систему создателем движухи при её отсутствии - точно лучше чем просто палево части антагов в начале каждого раунда.
Здесь, правда, встаёт вопрос: каким именно образом в логике вычислять, когда прилетает бумажка? Сторителлер, насколько я понимаю, сейчас работает, высчитывая "уровень опасности" по имеющимся антагам и простанционным ролям (охрана и ЕРТ в частности) и, если он слишком низкий, добавляет соответствующее количество ролей.
Здесь же нужно учитывать не только количество ролей, но и их активность и реакцию простанционных на эту активность. Не знаю, есть ли какой-нибудь уже существующий надёжный способ это определять, но как-то сделать наверняка можно.

2021-04-08 13:38 UTC, MrMagick2104 commented
> Здесь, правда, встаёт вопрос: каким именно образом в логике вычислять, когда прилетает бумажка?

После выдачи n дополнительных антагов, где n - часть от общего числа антагов (выданных и невыданных сторителлером).
Это было бы логично: появился большой уровень новой угрозы (не раундстартовой), появилось оповещение об этой угрозе, желательно минут через 5-15 после появления этой самой угрозы.
Условно часть выданных антагов сторителлером от общего числа для триггера бумажки может быть, например, 1/3 или 1/4, в зависимости от режима.

Если это совместить с возможностью отмены аннонса, например, отключением телекоммов (временно откладывает аннонс) или трейторскими вещами за условные 40 ТК за исключение себя из аннонса и 70 ТК за отсутствие аннонса вообще, то было бы неплохо, по-моему.

2021-04-18 13:36 UTC, Doster-d commented on code/game/gamemodes/game_mode.dm
> +	for(var/mob/M in GLOB.player_list)
![image](https://user-images.githubusercontent.com/63081538/115147564-3b7aa800-a064-11eb-9e52-145091ca5def.png)
АХАХХАХА

2021-05-10 18:57 UTC, closed without merging