Fixes
ChaoticOnyx/OnyxBay pull request #4863
Opened 2021-04-10 21:01 UTC by igorsaux

- Добавлена задержка на звук при переключении камеры.
- Убраны звуки у телеком машин.
- Немного оптимизировано время исполнения handle_footsteps - с 0.025 на 10к вызовов до 0.015 на 10к вызовов (раньше было 0.014)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-12 03:45 UTC, HonkyDonky commented on code/game/mecha/mecha.dm
> +/obj/mecha/proc/do_after(delay as num)
А можно, раз уж ты трогал, сделать по-нормальному?

2021-04-12 03:45 UTC, HonkyDonky commented on code/modules/modular_computers/file_system/programs/generic/camera.dm
> +		if (world.time > last_sound + 2 SECONDS)
И может перевернешь всё же...

2021-04-15 11:11 UTC, TobyThorne approved these changes

2021-04-16 07:07 UTC, HonkyDonky approved these changes

2021-04-16 07:07 UTC, HonkyDonky commented on code/game/mecha/mecha.dm
> +
Меня эта хуйня так смущает, но ладно

2021-04-16 07:10 UTC, Doster-d requested changes

2021-04-16 07:10 UTC, Doster-d commented on code/game/mecha/mecha.dm
> +		return 1
```suggestion
		return TRUE
```

2021-04-16 07:10 UTC, Doster-d commented on code/game/mecha/mecha.dm
> +	return 0
```suggestion
	return FALSE
```

2021-04-16 07:15 UTC, Doster-d approved these changes
Сказали, что не смешно.

2021-04-16 07:20 UTC, merged