fix(tobygun)
ChaoticOnyx/OnyxBay pull request #4864
Opened 2021-04-10 21:18 UTC by Tsurupeta

https://www.youtube.com/watch?v=rtizjDbvIRU

- [*] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [*] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [*] Я запускал сервер со своими изменениями локально и все протестировал.
- [*] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-10 21:28 UTC, Doster-d requested changes

2021-04-10 21:28 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
Зачем два пробела, почему нет проверки на то, есть ли chambered?
```suggestion
	if(bcell && chambered && chambered.BB)
```

2021-04-10 21:35 UTC, igorsaux commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
`if(bcell &&  chambered?.BB)`

2021-04-10 21:36 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
Два пробела потому что не заметил один. А проверка на чемберед... Хз, оно выдаёт null. Зачем проверка на это, если будет null всегда кроме случая, когда chambered.BB = true?

2021-04-10 21:36 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
> `if(bcell && chambered?.BB)`

У Вас тут не православный оператор

2021-04-10 21:37 UTC, igorsaux commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
Чо в нём не православного

2021-04-10 21:37 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
> Два пробела потому что не заметил один. А проверка на чемберед... Хз, оно выдаёт null. Зачем проверка на это, если будет null всегда кроме случая, когда chambered.BB = true?

Рантаймить будет, если чамберед нулл.

2021-04-10 21:38 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
> Чо в нём не православного

Потому что он легкий, надо чтобы было сложно, всегда на Руси все было сложно.

2021-04-10 21:40 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
А вот не рантаймит!

2021-04-10 21:41 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
![image](https://user-images.githubusercontent.com/41485301/114285262-9c035700-9a5e-11eb-9846-89f2e08306aa.png)

2021-04-10 21:42 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/revolver.dm
> +	if(bcell &&  chambered.BB)
Ладно, рантаймит.

2021-04-10 21:42 UTC, Tsurupeta commented
Я доверюсь Игорю, который никогда раньше не ломал билд и последую его рекомендации.

2021-04-11 23:28 UTC, Doster-d approved these changes

2021-04-12 03:07 UTC, TobyThorne approved these changes

2021-04-12 03:08 UTC, merged