Uplink contacts
ChaoticOnyx/OnyxBay pull request #4873
Opened 2021-04-11 06:14 UTC by Doster-d

Основной код был спортирован с Эриса.
На контрактах есть причина почему он существует, были введены некоторый фракции в Синдикате, добавлены пары причин, открыт для расширения данных причин.
Контракты:
- Убийство члена экипажа;
- Имплантирование члена экипажа;
- Кража ~~трусов~~ различных предметов;
- Кража образцов днк через кровь;
~~- Посадить человека в бриг~~

Проведен рефакторинг кода заданий, добавлено задание на завершения n контрактов.

close #2471

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-11 07:26 UTC, Voldirs commented
Оооооо, закинь скринов

2021-04-11 10:52 UTC, Doster-d commented
Все вернул.

2021-04-11 10:55 UTC, igorsaux commented
Не знаю кто делал табличку с контрактами в аплинке - но выглядит очень кринжово

2021-04-11 13:42 UTC, DarkHunter7756 commented
> Не знаю кто делал табличку с контрактами в аплинке - но выглядит очень кринжово

Сделано на подобие карго контрактов, в чем кринж?

2021-04-11 13:49 UTC, igorsaux commented
> > Не знаю кто делал табличку с контрактами в аплинке - но выглядит очень кринжово
> 
> Сделано на подобие карго контрактов, в чем кринж?

Title в отличии от других заголовков - не жирный.
Странный салатовый фон у строк в таблице - к чему он тут вообще?
Где отступы текста от границ таблицы???
Почему текст в столбцах Title и Reward так странно выравнен.
Почему нет красной строки у описания??
Я исправил и скинул достеру нормальную версию:
![unknown](https://user-images.githubusercontent.com/55196698/114306806-b59bb180-9ae5-11eb-908f-c7e41e384b8f.png)

2021-04-17 22:18 UTC, Doster-d commented
Блять, я себя захуярил.

2021-04-17 22:49 UTC, Doster-d commented
Блять, я себя раззахуярил.

2021-04-17 23:14 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/115129139-daaf8900-9feb-11eb-82bf-20aa7f54bdbf.png)

2021-04-17 23:19 UTC, Wuattt commented
там опечатка в слова contract

2021-04-17 23:23 UTC, Doster-d commented
> contract

гот ит

2021-04-17 23:39 UTC, Doster-d commented
Добавил поясняющие надписи, шутку-минутку для ST~~T~~D, исправил очепятку, увеличил необходимый уровень исследования для объектов кражи из научки до 3.

2021-04-18 07:03 UTC, TobyThorne commented on code/game/gamemodes/objective.dm
> +	amount = rand(2, 5)
Я бы от 3 до 5 поставил.
В будущем бы, конечно, к сторителлеру как-нибудь прикрутить надо будет.

2021-04-18 07:04 UTC, TobyThorne commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Complete at least [amount] contracts"
```suggestion
	explanation_text = "Complete at least [amount] contracts."
```

2021-04-20 07:48 UTC, TatarTheBuilder commented on code/game/objects/items/weapons/storage/briefcase.dm
> +	desc = "It's a old looking briefcase but has some high-tech marks. It has a label on it that says, \"WORKS ONLY NEAR SPACE\""
```suggestion
	desc = "It's an old looking briefcase with some high-tech markings. It has a label on it that says, \"WORKS ONLY NEAR SPACE\""
```

2021-04-20 07:52 UTC, TatarTheBuilder commented on code/datums/uplink/devices and tools.dm
> +	desc = "A litteraly worm in bed... I mean wormhole for in space teleportation, yeah, space teleportation, just try to put your uplink device in it for authorization."
```suggestion
	desc = "Litteraly a worm in bed... I mean wormhole for space teleportation, yeah, space teleportation, just try to put your uplink device in it for authorization."
```

2021-04-22 12:09 UTC, Doster-d commented
Обновил STD, теперь STD не называется STTD

2021-04-23 14:22 UTC, TobyThorne requested changes

2021-04-23 14:22 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("send blood samples of [count] different people in separate containers via STTD.")
тут до сих пор STTD осталось

2021-04-23 14:22 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		if(!data || data["species"] != SPECIES_HUMAN || (data["blood_DNA"] in samples))
тут помимо хуманов можно и каджитов, аргонианцев и скреллов впихнуть, чё бы нет

2021-04-23 14:22 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		create_explain_text("assasinate [target_mind.current.real_name] and send [gender_datums[target_mind.current.get_gender()].his] [target.name] via STTD as a proof.")
тоже sttd

2021-04-23 14:22 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		if(!istype(H) || H.stat == DEAD || !is_station_turf(get_turf(H)))
ассасинейт на других трейторов лучше если не выпилить, то шанс хотя бы сделать крайне маленьким

2021-04-23 14:22 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +	desc = "Used for spying purposes. It has a small label \"Use your uplink on it for authorization\""
запятую/двоеточкие перед ковычками забыл
и точку в конце

2021-04-23 14:22 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +	desc = "It has a small label \"Use your uplink on it for authorization\""
и тут тоже

2021-04-23 14:22 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +		to_chat(user, SPAN_NOTICE("You connect [I]'s uplink to implant auth subsystem"))
и тут точку

2021-04-23 14:22 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/briefcase.dm
> +	desc = "It's an old looking briefcase with some high-tech markings. It has a label on it that says, \"WORKS ONLY NEAR SPACE\""
тоже точка

2021-04-23 14:23 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +	Your mission [prob(25) ? ", should you choose to accept it, is to" : "is to"] [target_and_task] The reward for closing this contract is [reward] TC"
Не забыл, точки стоят в target_and_desc

2021-04-23 14:24 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +		if(GLOB.traitors.is_antagonist(target_mind) && prob(75))
Зачем? Это даст возможность трейторам шизу

2021-04-23 14:39 UTC, TobyThorne commented
В целом норм, гей-плюсик воткну.

В будущем можно будет доработать. Я не так давно пилил для трейторов миссии, но сделал не так много, да и теперь допиливать смысла нет. Зато некоторые концепты можно использовать. Сейчас впиливать не обязательно, так, на будущее:
- Впилить счётчик проваленных миссий. Например, цель для имплантирования погибла, либо цель для убийства ушла в крио. Чем больше провалов - тем ниже награды за следующие миссии и выше шанс, что на тритора-неудачника прилетит контракт. После N провалов тритор считается предателем (каламбур), теряет доступ к аплинку и все остальные трейторы получают на него контракт с наградой в виде всех его телекристаллов.
- Добавить кнопочку для подтверждения убийства без отсылки головы. Например, на случай, если кинул цель в материю. При нажатии пойдёт проверка на минут ~10. Если цель действительно мертва - либо контракт успешно выполнится, либо с некоторым шансом придёт "не получилось подтвердить выполнение" и он отменится, без выполнения и награды. Если же цель жива - либо провал миссии (с двойной прибавкой к счётчику провалов по причине "напиздел"), либо с маленьким шансом "не удалось подтвердить", либо с ОЧЕНЬ маленьким - засчитывает выполнение.
- Миссии на похищение. Вместо STD выбирается локация, где откроется синдипортал. Открывается либо по кнопочке из аплинка, либо с помощью того же STD. Портал существует где-то минуту. Открыть можно дважды (во второй раз локация сменится), запросить смену локации - один раз. Если цель доставлена мёртвой, либо порталы израсходованы - миссия провалена. Похищенная через портал целька теряет вещи попадает в тюрьму синдиката, где может или сидеть и ждать таких же бедолаг (а возможно - пробиться толпой через NPC/туррельки и попасть обратно на станцию), или задеспавниться через слипер.

2021-04-23 14:43 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	Your mission [prob(25) ? ", should you choose to accept it, is to" : "is to"] [target_and_task] The reward for closing this contract is [reward] TC"
Спагетти какое-то. Ну да похуй.

2021-04-23 16:12 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +		if(!data || data["species"] != SPECIES_HUMAN || (data["blood_DNA"] in samples))
Люди лучше, чем ксеносы, но ладно, звучит логично.

2021-04-24 14:58 UTC, Doster-d commented
Теперь контракты на трейтора, не отображается в его меню, но он все еще может их выполнить.
Добавлен контракт Recon, суть его в разведке местности используя новые spying sensors

2021-04-24 15:00 UTC, DarkHunter7756 commented
> Добавлен контракт Recon, суть его в разведке местности используя новые spying sensors

Какова логическая нагрузка сего задания, если синдикат может либо посмотреть по взломанным камерам, либо украсть чертежи станции?

2021-04-24 15:03 UTC, Doster-d commented
> > Добавлен контракт Recon, суть его в разведке местности используя новые spying sensors
> 
> Какова логическая нагрузка сего задания, если синдикат может либо посмотреть по взломанным камерам, либо украсть чертежи станции?

У компании нет возможности для того, чтобы купить доступ к взломанным камерам, либо украсть чертежи, поэтому они используют дешевый способ разведки.
+ есть локации, где нет камер.

2021-04-24 15:07 UTC, DarkHunter7756 commented
> У компании нет возможности для того, чтобы купить доступ к взломанным камерам

Учитывая стоимость агентов синдиката и их качества, могу это понять ( ͡ᵔ ͜ʖ ͡ᵔ )

2021-04-25 22:29 UTC, HonkyDonky approved these changes

2021-04-28 01:46 UTC, Doster-d commented
Получил отзывы по ПРу и начал по ним работать.
Добавил в некоторые контракты больше ясности.
Переписал spy sensors на spy bug, теперь игрок еще сможет подслушивать под зоной, что повысит использование данного девайса.
Исправил баг невозможности отправить STD.

2021-04-29 15:27 UTC, Doster-d commented
Добавил контракт на похищение ИИ, првоерил, работает.
Изменил способы создание контрактов, добавил новую сущность - организацию, в которой и хранится контракт.
Сущность организация имеет свой "интент" (какие контракты она предпочитает), и если у контракта отсуствует интент организации, то с вероятностью 75 процентов, что данный контракт отклонят.

2021-04-30 00:17 UTC, Doster-d commented
Все! Починил, расширил описание, можно ревьювить.

2021-04-30 07:01 UTC, Shootnik01 commented
Аплинк все еще нужно внутрь класть?

2021-04-30 15:19 UTC, Doster-d commented
> Аплинк все еще нужно внутрь класть?

Да, но теперь там невозможно его потерять, он не удаляется, если человек забыл вытащить.

2021-05-03 19:39 UTC, TobyThorne requested changes
Почекал только грамматику, на код сил уже нет.

2021-05-03 19:39 UTC, TobyThorne commented on code/datums/uplink/devices and tools.dm
> +	desc = "It's contain an unstable wormhole, that used to teleport all items inside to our base, on complete of teleportation sequances the device self destroyed to safety reasons, just try to put you
```suggestion
	desc = "It utilizes a local wormhole generator to teleport the stored items to our base. Upon successful teleportation, the device self-destructs for safety reasons. To use it, briefly put your uplink device inside for authorization, place the items you need to transport inside, and follow the instructions indicated on the STD."
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	// 		avaliable_contracts.Add(contract)
Если код не нужен - не оставляй его в таком виде.

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The Trauma Team Interspace"
```suggestion
	name = "Trauma Team Interspace"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The MiliSpace"
```suggestion
	name = "MiliSpace"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The Biospacenica"
```suggestion
	name = "Biospacenica"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The Kang Too"
```suggestion
	name = "Kang Too"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The NovaPlasma"
```suggestion
	name = "NovaPlasma"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The Dynamoon Technologies"
```suggestion
	name = "Dynamoon Technologies"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	name = "\The NanoSaka"
```suggestion
	name = "NanoSaka"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/devices/spy_bug.dm
> +		to_chat(uplink.uplink_owner.current, SPAN_NOTICE("It's seems your spy network ([english_list(active_recon_areas_list, and_text = " or ")]) are disabled, please check avability of bugs, your current
```suggestion
		to_chat(uplink.uplink_owner.current, SPAN_NOTICE("It looks like there are problems with your spy network in one the following areas:\n[english_list(active_recon_areas_list, and_text = "\n")]\nBugs maintenance required. Your current progress has been zeroed out."))
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/devices/spy_bug.dm
> +		to_chat(usr, SPAN_NOTICE("It's seams like spy network are located in [english_list(active_recon_areas_list, and_text = " or ")] and active.\nYou can deactivate the network by picking up camera bugs
```suggestion
		to_chat(usr, SPAN_NOTICE("Active spy network detected in the following areas:\n[english_list(active_recon_areas_list, and_text = "\n")]\nYou can deactivate the network by picking up the camera bugs."))
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/devices/spy_bug.dm
> +			messages += "Camera bug ([S.camera.name]) are not located on floor."
```suggestion
			messages += "Camera bug ([S.camera.name]) is not located on floor."
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/devices/spy_bug.dm
> +			messages += "Another camera bug in proximity prevents activation. (current bug: ([S.camera.name]), confilct bug: [AS.camera.name])"
```suggestion
			messages += "Another camera bug in proximity prevents activation. (current bug: ([S.camera.name]), conflicting bug: [AS.camera.name])"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/devices/spy_bug.dm
> +			messages += "Data collection initialization failure, not enough bugs."
```suggestion
			messages += "Data collection initialization failed:\Not enough bugs."
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/devices/spy_bug.dm
> +		to_chat(usr, SPAN_WARNING("Data collection initialization failed, there're some reasons: [english_list(messages, and_text = " or ")]"))
```suggestion
		to_chat(usr, SPAN_WARNING("Data collection initialization failed:\n[english_list(messages, and_text = "\n")]"))
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +	name = "implanter-spy"
```suggestion
	name = "implanter (S)"
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +	desc = "Used for spying purposes. It has a small label: \"Use your uplink on it for authorization\"."
Тут пометка про аплинк не нужна, активируется-то имплантер, а не сам имплант.

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +	desc = "It has a small label \"Use your uplink on it for authorization\"."
```suggestion
	desc = "It has a small label: \"Use your uplink for authorization\"."
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/implants/implants/spy.dm
> +		to_chat(user, SPAN_NOTICE("You connect [I]'s uplink to implant auth subsystem."))
```suggestion
		to_chat(user, SPAN("notice", "You authorize the [src] with \the [I]."))
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/briefcase.dm
> +	name = "unknown briefcase"
```suggestion
	name = "briefcase"
```
Во имя хоть какой-то стелсовости.

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/briefcase.dm
> +	desc = "It's an old looking briefcase with some high-tech markings. It has a label on it that says, \"WORKS ONLY NEAR SPACE\"."
```suggestion
	desc = "It's an old-looking briefcase with some high-tech markings. It has a label on it, which reads: \"ONLY WORKS NEAR SPACE\"."
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/briefcase.dm
> +		src.visible_message("\The [src] blinks green!")
```suggestion
		visible_message("\The [src] blinks green!")
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/briefcase.dm
> +		audible_message("[src] blinks red.")
```suggestion
		audible_message("\The [src] blinks red.")
```

2021-05-03 19:39 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/briefcase.dm
> +				to_chat(loc, SPAN_NOTICE("[src] flickers away in a brief flash of light."))
```suggestion
				to_chat(loc, SPAN("notice", "\The [src] fades away in a brief flash of light."))
```

2021-05-03 19:50 UTC, Doster-d commented on code/game/objects/items/weapons/storage/briefcase.dm
> +	name = "unknown briefcase"
Сделал лучше, убрал нейм, теперь используется родительский.

2021-05-03 19:50 UTC, Doster-d commented on code/game/gamemodes/traitor/fixer.dm
> +	// 		avaliable_contracts.Add(contract)
Я забыл его удалить.

2021-05-03 19:51 UTC, Doster-d commented on code/__defines/contracts.dm
> +#define CONTRACT_IMPACT_SOCIAL		0x8 // used when contract is designed to solve in rOlEpLaY way, e.g. blood collecting, steal research disk
Ок.

2021-05-03 19:54 UTC, Doster-d commented on code/game/objects/items/devices/spy_bug.dm
> +			messages += "Data collection initialization failure, not enough bugs."
Оставил только ```Not enough bugs.```
Кек или кринж?

2021-05-03 19:55 UTC, Doster-d commented
Ну, по ревью Тоби готово.

2021-05-03 20:03 UTC, TobyThorne requested changes

2021-05-03 20:03 UTC, TobyThorne commented on nano/templates/std.tmpl
> +		<b>Reward will be paid to</b>:
```suggestion
		<b>The reward will be issued to</b>:
```

2021-05-03 20:03 UTC, TobyThorne commented on nano/templates/std.tmpl
> +<b>Glad to hear you, {{:data.owner}}. I am {{:data.fixer}}, there are currentrly known contracts, that will be closed by send STD:</b>
```suggestion
<b>Glad to hear you, {{:data.owner}}. I am {{:data.fixer}}. These are the currently active contracts:</b>
```

2021-05-03 20:19 UTC, Doster-d commented
Готово.

2021-05-03 20:27 UTC, TobyThorne requested changes

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	"an ablative armor vest" = 							list(CONTRACT_STEAL_MILITARY, /obj/item/clothing/suit/armor/laserproof)
Тут тоже убийственные выравнивания.

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	desc = "My client is [organization.name], [reason]. They have information the target is located on [GLOB.using_map.station_name]. \
```suggestion
	desc = "My client is [organization.name], [reason]. They have information that the target is located somwhere aboard [GLOB.using_map.station_name]. \
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	Your mission[prob(25) ? ", should you choose to accept it, is to" : " is to"] [target_and_task] The reward for closing this contract is [reward] TC"
```suggestion
	Your mission[prob(25) ? ", should you choose to accept it, is to" : " is to"] [target_and_task] The reward for closing this contract is [reward] TC."
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +			to_chat(M.current, SPAN_NOTICE("Contract completed: [name] ([reward] TC). Nice work, [M.current]."))
```suggestion
			to_chat(M.current, SPAN("notice", "Contract completed: [name] ([reward] TC). [pick("Nice work", "Good job", "Great job", "Well done", "Nicely done")], [M.current]."))
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +					reason = "they want to check the target's loylity to the Syndicate"
```suggestion
					reason = "they want to make sure of the target's loyalty to the Syndicate"
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("implant [H.real_name] with a spying implant (don't forget to link it).")
```suggestion
	create_explain_text("implant [H.real_name] with a spying implant (don't forget to authorize it first).")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("steal [target_desc] and send it via STD (find out in Devices and Tools).")
```suggestion
	create_explain_text("steal <b>[target_desc]</b> and send it via STD (found in <b>Devices and Tools</b>).")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to execute intelligence virus on main [GLOB.using_map.company_name]'s AI using local AI core")
```suggestion
		reason = pick("they want to spread a virus on [GLOB.using_map.company_name]'s systems using a local AI core")
```
Вообще не понял, что тут имелось в виду. Сделал что-то более-менее похожее.

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("steal [target_desc] and send it via STD (find out in Devices and Tools).")
```suggestion
	create_explain_text("steal <b>[target_desc]<b> and send it via STD (found in <b>Devices and Tools</b>).")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to research the NT employee genome")
```suggestion
		reason = pick("they want to research a NanoTrasen employee's genome")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("send blood samples of [count] different people in separate containers via STD (find out in Devices and Tools).")
```suggestion
	create_explain_text("send blood samples of <b>[count]<b> different people in separate containers via STD (found in <b>Devices and Tools</b>).")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +					reason = "they want to check the target's loylity to the Syndicate"
Тут вообще копипаста из имплантов.
Вероятность бы где-то до 10% срезать.
И сообщение на хрен знает на что, ибо ассасинейт на другого агента - в принципе какая-то шиза.
Наверное, что-то вроде reason = "the target has possibly double-crossed us".

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("assasinate [H.real_name] and send [T.his] [target.name] via STD (find out in Devices and Tools) as a proof.")
```suggestion
	create_explain_text("assasinate <b>[H.real_name]</b> and send <b>[T.his] [target.name]</b> via STD (found in <b>Devices and Tools</b>) as a proof.")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("extract a sum of [sum] credits from [GLOB.using_map.company_name] economy and send it via STD (find out in Devices and Tools).")
```suggestion
	create_explain_text("extract a sum of <b>[sum] credits</b> from [GLOB.using_map.company_name] economics and send it via STD (found in <b>Devices and Tools</b>).")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("send a fabricator data disk with one of the following designs via STD (find out in Devices and Tools):<br>[english_list(targets_name, and_text = " or ")].")
```suggestion
	create_explain_text("send a <b>fabricator data disk</b> with one of the following designs via STD (found in <b>Devices and Tools</b>):<br><i>[english_list(targets_name, and_text = " or ")]</i>.")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to know what objects located in this area")
```suggestion
		reason = pick("they want to know what objects are located in this area")
```

2021-05-03 20:27 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("activate 3 spy bug by spy monitor (Bug kit) in one of the following locations: [english_list(targets, and_text = " or ")] and let them work without interruption for 10 minutes."
```suggestion
	create_explain_text("activate <b>3 spy bugs</b> with a <b>Bug kit</b> and ensure they work without interruption for 10 minutes in one of the following locations:<br><i>[english_list(targets, and_text = " or ")]</i>.")
```

2021-05-03 20:31 UTC, TobyThorne commented
С контрактами на других антагов вообще надо больше проверок.
Какие-нибудь культисты, ревы и генки - вообще не надо снижать шансы.
Всякие ниндзи, визорды, ксеноморфы и иже с ними - не должны выпадать целями в принципе. 
С триторами и нюкерами надо подумать.

2021-05-03 20:31 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to execute intelligence virus on main [GLOB.using_map.company_name]'s AI using local AI core")
Ну в моем лоре, НТ имеет главный супер ИИ, который отдает указания "локальным ИИ" и проверяет их целостность, по моему лору такой контракт объясняет каким образом Синдикату удается взламывать ИИ.

2021-05-03 20:35 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to execute intelligence virus on main [GLOB.using_map.company_name]'s AI using local AI core")
Чёт такое. Если бы каждый краденный ИИ позволял бы хакать "супер-главный-ИИ" - НаноСракены уже давно бы звездой накрылись.

2021-05-03 20:37 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to execute intelligence virus on main [GLOB.using_map.company_name]'s AI using local AI core")
Ну так у нас не каждый раунд ИИ сбоит, у главного ИИ есть защита от массового такого, тут 1-2 штуки за кластер локальных ИИ может хакнуть и отключить от главного компьютера.

2021-05-03 22:39 UTC, Doster-d commented
Добавил проков для обработки антагов.
В assasinate добавил кучу условий выполнений.

2021-05-04 20:35 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("assasinate <b>[target_real_name]</b> and send <b>[T.his] [target.name]</b> or <b></b>, but you get less TC via STD (found in <b>Devices and Tools</b>) as a proof. You must make
```suggestion
	create_explain_text("assasinate <b>[target_real_name]</b> and send <b>[T.his] [target.name]</b> (or <b></b>, but your reward will get reduced) via STD (found in <b>Devices and Tools</b>) as a proof. You must make sure that the target is completely, irreversibly dead.")
```

И, кажется, в между болдами что-то должно быть, но я не уверен.

2021-05-05 05:58 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +	create_explain_text("assasinate <b>[target_real_name]</b> and send <b>[T.his] [target.name]</b> or <b></b>, but you get less TC via STD (found in <b>Devices and Tools</b>) as a proof. You must make
Да, я там потерял штуку, теперь нашел.

2021-05-05 06:02 UTC, Doster-d commented
Добавлена меню для редактирования контрактов.
Полностью исправлены контракты на имплантирования и убийства, теперь убийства можно закрыть используя: карточку цели, мозг цели, ММИ цели (за предыдущие пункты половину награды), голову.

2021-05-05 13:46 UTC, TobyThorne commented on code/game/gamemodes/traitor/fixer.dm
> +	set desc = "Add/remove/redact traitor contracts"
```suggestion
	set desc = "Add/remove/edit traitor contracts"
```

2021-05-05 16:58 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		alternative_message = " <b>[alternative_target], [target_real_name] brain in MMI, [target_real_name] brain</b>"
```suggestion
		alternative_message = " <b>[alternative_target], [target_real_name]'s brain in MMI, [target_real_name]'s brain</b>"
```

2021-05-05 17:02 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +	name = "Steal active AI"
```suggestion
	name = "Steal an active AI"
```

2021-05-05 17:04 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		reason = pick("they want to spread virus to the main [GLOB.using_map.company_name]'s AI module responsible for creating a personality for new AI core using the AI ​​you stole")
```suggestion
		reason = pick("they want to spread a virus to the main [GLOB.using_map.company_name]'s AI module responsible for creating new AI personalities using the AI ​​you will steal")
```

2021-05-06 20:43 UTC, TobyThorne commented on code/game/gamemodes/traitor/contracts.dm
> +		reward = reward * 1.5
О, уже костыли. Одобряю. 
![image](https://user-images.githubusercontent.com/45202681/117363126-f799f680-aedd-11eb-9012-5d48957d0324.png)

2021-05-06 20:45 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +		reward = reward * 1.5
Ну код же уже написано, затем писать два раза)

2021-05-06 21:10 UTC, Doster-d commented
Добавил ченджлог.

2021-05-06 21:42 UTC, Shootnik01 commented
А все украденные отправляются в Бразил, или все-таки на ЦК?

2021-05-06 21:43 UTC, Shootnik01 commented
> А все украденные отправляются в Бразил, или все-таки на ЦК?

Было бы круто тэпать их куда-нибудь, вместо убийства. И игроку не грустно, и педальки скучающие могут им пощитспавнить

2021-05-06 22:38 UTC, Doster-d commented
> А все украденные отправляются в Бразил, или все-таки на ЦК?

В госты.

2021-05-06 22:57 UTC, Shootnik01 commented
> > А все украденные отправляются в Бразил, или все-таки на ЦК?
> 
> В госты.

Ну вот. А идея с отправкой на ЦК как тебе?

2021-05-06 23:01 UTC, hard-res3t commented
Отправлять синдикатовские шмотки на ЦК?
> Великолепный план Уолтер! Просто ахуеный, если я правильно понимаю. Надёжный блядь как швейцарские часы!

2021-05-08 20:55 UTC, Doster-d commented
Не смотря на дикие размеры, все работает.

2021-05-08 20:55 UTC, Doster-d commented
Не туда :(

2021-05-10 13:42 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +	return !!name && !!desc
Два ! приводят любую переменную к TRUE или FALSE

2021-05-10 13:43 UTC, Doster-d commented on code/game/gamemodes/traitor/fixer.dm
> +	while(--count)
Почему?
Если так сделать, то при 1, не пойдет цикл, насколько я помню.

2021-05-10 13:43 UTC, igorsaux commented on code/game/gamemodes/traitor/fixer.dm
> +	while(--count)
Сейчас при 1 как раз не идёт цикл

2021-05-10 13:43 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +			reasonn = pick("they want to use this item for their spy operation on [GLOB.using_map.company_name]'s stations", "they want to use this item to confuse loyal [GLOB.using_map.company_name]'s employ
Напомни, как это сделать.

2021-05-10 13:47 UTC, igorsaux commented on code/game/gamemodes/traitor/contracts.dm
> +			reasonn = pick("they want to use this item for their spy operation on [GLOB.using_map.company_name]'s stations", "they want to use this item to confuse loyal [GLOB.using_map.company_name]'s employ
типа  `else CRASH(s_type)`

2021-05-12 09:47 UTC, igorsaux requested changes

2021-05-12 09:47 UTC, igorsaux commented on code/game/gamemodes/traitor/fixer.dm
> +/datum/contract_organization/New(datum/contract_organization/CO)
`datum/contract_fixer/CO`?

2021-05-12 09:47 UTC, igorsaux commented on code/game/gamemodes/traitor/fixer.dm
> +	intents = CONTRACT_IMPACT_SOCIAL & CONTRACT_IMPACT_OPERATION
Здесь и ниже вместо `&` поставить `|`

2021-05-12 09:50 UTC, igorsaux commented on code/game/gamemodes/traitor/contracts.dm
> +	intent = CONTRACT_IMPACT_OPERATION & CONTRACT_IMPACT_SOCIAL
Тоже заменить на `|`

2021-05-12 09:54 UTC, igorsaux commented on code/game/gamemodes/traitor/contracts.dm
> +	ASSERT(intent)
Ассерт перенеси в `/datum/antag_contract/New(...)`

2021-05-12 13:41 UTC, Doster-d commented
Пофиксил

2021-05-23 20:21 UTC, igorsaux approved these changes

2021-05-23 20:28 UTC, TobyThorne approved these changes
достер сказал, что если что-то сломается - он перефиксит все баги Оникса, инфа соточка, так и было

2021-05-23 20:30 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/119275617-c845f200-bc1e-11eb-9a87-14ab565f0485.png)

2021-05-23 20:33 UTC, merged

2021-05-23 20:35 UTC, Doster-d commented
Это произошло.