feat(add) Ballistic headphones
ChaoticOnyx/OnyxBay pull request #4886
Opened 2021-04-12 11:31 UTC by Tsurupeta

Тактические Earmuffs. С радио внутри. А ещё немного рефакторинга кода со вводом прока get_ear_protection, чтобы не плодить проверку на наличие шлема или earmuffs. Добавлена просто переменная ear_protection и прок у моба get_ear_protection.

Наушники для модников, которые не хотят бегать в шлеме, но хотят иметь доступ к радио и выглядеть стильными, имея защиту от громких штук шлема. Дефолтные earmuffs всё ещё 2 раза лучше. Изменения тестил, всё работает, рантаймов не выводило.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-14 05:20 UTC, HonkyDonky commented on code/modules/clothing/ears/earmuffs.dm
> +	ear_protection = 2
Мне так-то пофиг, но к тебе приебутся другие, а я апрув поставить хочу
Тут строка потеряна

2021-04-14 05:20 UTC, HonkyDonky commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
Здесь тоже

2021-04-14 05:20 UTC, HonkyDonky commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			. += C.ear_protection
Может переменную `ear_protection` всё же перенести к одежде? Не хочешь? Просто я не знаю такой `obj/item`, который бы можно было надеть на голову/уши.

2021-04-15 10:59 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			. += C.ear_protection
>Просто я не знаю такой obj/item, который бы можно было надеть на голову/уши.
наушники - не clothing же, а /obj/item/device/radio/4etotam

2021-04-15 12:51 UTC, HonkyDonky commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			. += C.ear_protection
Это всё объясняет

2021-04-15 13:58 UTC, TobyThorne commented on code/modules/clothing/ears/earmuffs.dm
> +	ear_protection = 2
Вставляю свой приёб.

2021-04-15 13:58 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
здесь тоже

2021-04-16 15:11 UTC, Tsurupeta commented
Наконец-то

2021-04-17 02:55 UTC, TobyThorne commented on code/game/objects/items/devices/radio/headset.dm
> +	name = "Tactical earmuffs"
```suggestion
	name = "tactical headset"
```

Го как-нибудь так.

2021-04-21 13:49 UTC, HonkyDonky submitted a review, later dismissed
Хотел дефайны, но ИЕ сказал, что пошёл я нахуй

2021-04-21 13:49 UTC, HonkyDonky commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
Эту часть можно было опустить, кстати. 

http://www.byond.com/docs/ref/#/proc/return
"Stop execution of the current proc and return the value of E to the caller. If no value is specified, the value of `.` will be returned, which defaults to null."

2021-04-21 22:06 UTC, Tsurupeta commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
Тебе мешает return .? Обязательно return написать?

2021-04-21 22:07 UTC, kreeperHLC requested changes
Ай за что

2021-04-21 22:07 UTC, kreeperHLC commented on code/datums/supplypacks/security.dm
> +					/obj/item/device/radio/headset/tactical =2)
```suggestion
					/obj/item/clothing/head/helmet = 2,
					/obj/item/device/radio/headset/tactical = 2)
```

2021-04-21 22:08 UTC, HonkyDonky commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
нет, смысле, ты эту строку с `return .` можешь просто-напросто убрать и всё будет ок

2021-04-21 22:09 UTC, Tsurupeta commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
Ладно, завтра уберу точку, проверю и всё.

2021-04-21 22:09 UTC, HonkyDonky commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return .
Это необязательно вообще, я просто предложил

2021-04-21 22:09 UTC, HonkyDonky approved these changes

2021-04-22 13:18 UTC, kreeperHLC approved these changes

2021-04-23 11:07 UTC, merged