Chameleon fast change
ChaoticOnyx/OnyxBay pull request #4924
Opened 2021-04-16 13:21 UTC by Zert0X

1)Сделана прока узнающая работу, стартовый Outfit, и заменяющее одежду
2) В случае если стандартной одежды нет, в чатик выводится "No standart suit for [название профы]"
![изображение](https://user-images.githubusercontent.com/42303535/115027456-692ce900-9ecc-11eb-90b7-e2098dd5ca51.png)
3)Видосик теста с разными профессиями(в конце показано что т.к. у карты нет профы ничего и не просходит)
![Видосик](https://user-images.githubusercontent.com/42303535/115030395-b6f72080-9ecf-11eb-8adc-ce19d23702de.mp4)
close #4923 

- ✅  Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- ✖️  Я внимательно прочитал все свои изменения и багов в них не нашел.
- ✅  Я запускал сервер со своими изменениями локально и все протестировал.
- ✅  Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-16 13:58 UTC, Tsurupeta requested changes
StandarD

2021-04-16 15:38 UTC, Tsurupeta reviewed
Мне аппрувать нельзя. Но больше буква Т не режет глаза.

2021-04-16 15:54 UTC, Tsurupeta reviewed
В общем. Пересмотрел. Код крайне качественный. Могу прокомментировать как качественное добавление в кодбазу ониксбея.

2021-04-16 16:43 UTC, HonkyDonky approved these changes

2021-04-16 16:52 UTC, Tsurupeta submitted a review, later dismissed

2021-04-16 20:14 UTC, kreeperHLC requested changes
Ай пробелы в глаза попали. Ну а так нормально, идей как свич на что-то более универсальное перевести у меня не появилось.

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +	var/decl/hierarchy/outfit/outfit = job.get_outfit(user ,job)
```suggestion
	var/decl/hierarchy/outfit/outfit = job.get_outfit(user, job)
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.uniform ? disguise(outfit.uniform, user) : to_chat(user, "No standard uniform for [W.assignment ]")
```suggestion
			outfit.uniform ? disguise(outfit.uniform, user) : to_chat(user, "No standard uniform for [W.assignment]")
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.suit ? disguise(outfit.suit, user) : to_chat(user, "No standard suit for [W.assignment ]")
```suggestion
			outfit.suit ? disguise(outfit.suit, user) : to_chat(user, "No standard suit for [W.assignment]")
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.gloves ? disguise(outfit.gloves, user) : to_chat(user, "No standard gloves for [W.assignment ]")
```suggestion
			outfit.gloves ? disguise(outfit.gloves, user) : to_chat(user, "No standard gloves for [W.assignment]")
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.shoes ? disguise(outfit.shoes, user) : to_chat(user, "No standard shoes for [W.assignment ]")
```suggestion
			outfit.shoes ? disguise(outfit.shoes, user) : to_chat(user, "No standard shoes for [W.assignment]")
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.mask ? disguise(outfit.mask, user) : to_chat(user, "No standard mask for [W.assignment ]")
```suggestion
			outfit.mask ? disguise(outfit.mask, user) : to_chat(user, "No standard mask for [W.assignment]")
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.head ? disguise(outfit.head, user) : to_chat(user, "No standard hat for [W.assignment ]")
```suggestion
			outfit.head ? disguise(outfit.head, user) : to_chat(user, "No standard hat for [W.assignment]")
```

2021-04-16 20:14 UTC, kreeperHLC commented on code/modules/clothing/chameleon.dm
> +			outfit.glasses ? disguise(outfit.glasses, user) : to_chat(user, "No standard glasses for [W.assignment ]")
```suggestion
			outfit.glasses ? disguise(outfit.glasses, user) : to_chat(user, "No standard glasses for [W.assignment]")
```

2021-04-16 20:22 UTC, kreeperHLC approved these changes

2021-04-17 02:43 UTC, TobyThorne approved these changes

2021-04-17 02:49 UTC, merged