Removes lack of vat-growns
ChaoticOnyx/OnyxBay pull request #4930
Opened 2021-04-17 14:54 UTC by TobyThorne

Нейролейсы и ресливерная сейчас практически бесполезны, ибо практически единственный вариант использования - запихивание в макаку.

- В карго-заказы добавлены два варианта ящиков с vat-grown-телами, мужским и женским. Стоят 300 очков, находятся в категории Medical;

Наверное, в будущем стоит придумать более интересную систему для создания для ватгровнов, но пока что - чё бы нет.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-17 15:02 UTC, DarkHunter7756 commented
Ого, продолжение проекта Видоизмененного Углерода. Круто!
Осталось сделать возможность собрать нового космонавтика на особом 3д принтере

2021-04-17 15:24 UTC, Doster-d approved these changes

2021-04-17 15:29 UTC, Doster-d commented
[![forthebadge](https://forthebadge.com/images/badges/makes-people-smile.svg)](https://forthebadge.com)
[![forthebadge](https://forthebadge.com/images/badges/it-works-why.svg)](https://forthebadge.com)

2021-04-17 15:39 UTC, GusevDuhast commented
> Осталось сделать возможность собрать нового космонавтика на особом 3д принтере

Любого типа, а так же конструктор из ног таяры, головы унатха, и всего остального от человека, прям идеально

2021-04-17 16:14 UTC, Zert0X commented
Предлагаю уже делать как раз таки по проекту "Видоизмененного Углерода" там сказано что:"Такое тело может заказать капитан с ЦК по большой цене." предлагаю заменить капитана, на глав (КМ не глава :3)

2021-04-17 16:22 UTC, Doster-d reviewed
Может по доступу глав дадим возможность заказать?

2021-04-17 16:22 UTC, Doster-d commented on code/datums/supplypacks/medical.dm
> +	containertype = /obj/structure/largecrate/animal/vatgrownbody/male
```suggestion
	containertype = /obj/structure/largecrate/animal/vatgrownbody/male
	access = access_heads
```

2021-04-17 16:22 UTC, Doster-d commented on code/datums/supplypacks/medical.dm
> +	containertype = /obj/structure/largecrate/animal/vatgrownbody/female
```suggestion
	containertype = /obj/structure/largecrate/animal/vatgrownbody/female
	access = access_heads
```

2021-04-17 16:23 UTC, Zert0X commented
> 
> 
> Может по доступу глав дадим возможность заказать?

об этом я и веду речь

2021-04-17 16:41 UTC, Doster-d approved these changes

2021-04-21 13:58 UTC, Doster-d requested changes

2021-04-21 13:58 UTC, Doster-d commented on code/game/objects/items/cryobag.dm
> +/obj/structure/closet/body_bag/cryobag/vatgrownbody/male/New()
```suggestion
/obj/structure/closet/body_bag/cryobag/vatgrownbody/male/Initialize()
```

2021-04-21 13:58 UTC, Doster-d commented on code/game/objects/items/cryobag.dm
> +/obj/structure/closet/body_bag/cryobag/vatgrownbody/female/New()
```suggestion
/obj/structure/closet/body_bag/cryobag/vatgrownbody/female/Initialize()
```

2021-04-21 23:26 UTC, TobyThorne commented
Перепилил.

2021-04-21 23:33 UTC, Doster-d approved these changes

2021-04-22 12:52 UTC, Doster-d approved these changes

2021-04-23 20:23 UTC, TobyThorne commented
конфликтс резолвд

2021-04-24 10:21 UTC, HonkyDonky approved these changes

2021-04-24 12:04 UTC, Doster-d approved these changes

2021-04-24 12:13 UTC, merged