Removes code unreachablenessity grab_normal.dm
ChaoticOnyx/OnyxBay pull request #4932
Opened 2021-04-17 17:08 UTC by TobyThorne

Ой щас бы грабы ещё сильнее не забаговывать

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-17 17:11 UTC, Doster-d requested changes

2021-04-17 17:11 UTC, Doster-d commented on code/modules/mob/grab/normal/grab_normal.dm
> +			return 0
```suggestion
			return FALSE
```

2021-04-17 17:11 UTC, Doster-d commented on code/modules/mob/grab/normal/grab_normal.dm
> +				return 0
```suggestion
				return FALSE
```

2021-04-17 17:12 UTC, TobyThorne commented on code/modules/mob/grab/normal/grab_normal.dm
> +			return 0
не, будет inconsistency с остальным кодом

2021-04-17 17:12 UTC, Doster-d commented on code/modules/mob/grab/normal/grab_normal.dm
> +			return 0
Ладно.

2021-04-17 17:14 UTC, Doster-d approved these changes
на локалку не заходил, компилятор говорит шо все заебись, анализатор кода - мозг Doster-d, также сообщает шо все заебись

2021-04-21 01:39 UTC, HonkyDonky approved these changes

2021-04-21 05:13 UTC, merged