Removes lack of xenomorphs
ChaoticOnyx/OnyxBay pull request #4949
Opened 2021-04-20 12:29 UTC by TobyThorne

Ксеноморфы в том виде, в каком они должны быть на бее.

- Добавлены лицехваты:
Появляются из яиц. Достать лицехвата вручную можно раньше, чем он вылупится сам.
Обнаружив человека, они пытаются подойти ближе, после чего прыгают, срывая шлемы и маски. Защитить могут герметичные шлемы. После промаха несколько секунд приходят в себя, готовясь к новому прыжку.
При большом желании и наличии открытого пространства от прыжка можно увернуться.
Если же лицехват присосался к лицу - жертва на какое-то время теряет сознание, а лицехват вживляет в жертву эмбрион ксеноморфа.
Лицехватов можно прилеплять к людям вручную, после небольшой задержки.

- Добавлены эмбрионы ксеноморфов:
Появляются в людях после изнасилования лицехватом. Удаляются из груди как обычные органы.
Если не удалить за четыре минуты - эмбрион разорвёт космонавтика на части и наружу вылезет грудолом.

- Грудоломы (larva) ксеноморфов:
У них почти ничего не изменилось. После появления грудолома призраки получают в чат уведомление, через которое могут занять грудолома.
Помимо сообщения в чате вселиться можно простым кликом ЛКМ.

- Ксеноморфы ксеноморфов:
- Теперь используют оригинальные спрайты вместо "выпрямленных".
- Больше не могут поднимать предметы (за исключением мобов).
- Больше не могут использовать технику.
- Теперь ксеноморфы видят над космонавтиком значок, если в нём находится эмбрион.
- Конечности больше не ломаются. 
- Все ксеноморфы теперь "нейтрального" пола.
- Теперь видят в темноте.
- Очень сильно увеличено лечение на ксеноморфовской слизи или в атмосфере с плазмой. Защитники восстанавливаются в полтора раза быстрее, королавы - вдвое. Лежание (через Rest) ускоряет лечение втрое.
- Потерянные конечности и разрушенные внутренние органы теперь могут восстанавливаться, если находиться на слизи/в плазме. Срабатывает только если на остальных органах не осталось урона. Шанс - 1% за тик, если лежать - 10% за тик.
- Ксеноморфы теперь получают соответствующую роль. Уникальные задачи в данный момент ещё не назначены.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-20 15:18 UTC, TobyThorne commented
компилируйся сука

2021-04-20 15:28 UTC, Zert0X commented on code/game/objects/effects/aliens.dm
> +		new/mob/living/simple_animal/hostile/facehugger(get_turf(src))
А чё так можно было?

2021-04-20 15:29 UTC, Doster-d commented on code/game/objects/effects/aliens.dm
> +		new/mob/living/simple_animal/hostile/facehugger(get_turf(src))
Нельзя

2021-04-20 16:42 UTC, TobyThorne commented
Ламарр вернулась в кабинет РД!

2021-04-21 11:08 UTC, TapKo4eB commented
привет тестер тут
- фейсхаггеры проходят сквозь стены
- фейсхаггеры не прыгают на спящих
- фейсхаггеры повторно прыгают за заражённых
- лярвы спавнятся чистыми и становятся красными к 150/200 прогресса (должно быть наоборот?)
- лярвы медленные
- лярвы медленно заползают в вентиляцию
- лярвы не могут проползать под дверьми на лкм
- венты не видно под резиной
- алиены могут атаковать друг-друга
- алиены не могут атаковать клозеты
- резин мембраны и стены сносятся с одного удараа алиена
- резин двери не сносятся на харме
- трава не растёт под мусорками
- алиены не ускоряются на резине
- спрайт резин-дверей значительно отличается от стен и мембран
- плейсхолдеры на кнопках здоровья, блока и реста
- недоиконка в индикаторе огня у лярвы (нету у других алиенов), не хватает некоторых других (пикрелейтед)
- сломан регургигейт
- сломан верб коррозив эсид, работает не на клике
- сломан такл, работает не на клике
- сломан лип, работает не на клике
- сломан спит, не в той категории, работает не на клике
- тоггл асид спит хуй пойми как работает
- сломан трансфер плазма, в селекте есть хуманы и не работает проверка расстояния
- дарквижн не включен по дефолту
- асид ниже по слою чем дверь
- вскрытие болтированной двери руками не учитывается при отображении в чат
- нету *hiss
- *scream у алиенов на звук как крики трапа
- ломание двери сопровождается каким-то не тем звуком который должен быть
- вскрытие сломанной двери идёт без сообщений и звука
- вместо вскрытия алиены бьют обесточенную дверь
- жижа наноботов превращает алиенов(фи4а?)
- 
- алиены спавнятся с фулл плазмой(?)
- несты не ускоряют прогресс эмбриона(?)
- первый заражающий фейсхаггер не кнокает моба, каждый последующий успешно кнокает(?)
- фейсхаггеры детектят хуманов через стены(?)

![picrelated](https://user-images.githubusercontent.com/48761132/115544200-f8f6dc80-a2aa-11eb-92ce-09bf1f6b0719.png)

2021-04-21 17:27 UTC, TobyThorne commented
Пачка фиксов номер раз:
- При ломании шлюзов, камер и лампочек теперь используется правильный звук ('slash");
- Улучшено взаимодействие ксеноморфов со шлюзами. Теперь выводятся сообщения о болтах/заваренных шлюзах, обесточенные шлюзы открываются без необходимости в предварительном избиении и всякое по мелочи;
- Ксеноморфы больше не полчают сразу два сообщения о lack dexterity при взаимодействии с закрытыми шкафчиками;
- Лицехваты больше не проходят через твёрдые объекты, **если те не пропускают воздух**. Если объект не герметичный - лицехват сможет на него запрыгнуть, но перед следующим прыжком будет кулдаун как при промахе;
- Лицехваты больше не прыгают на уже заражённых существ. Фича спорная, надо будет тщательнее обдумать;
- Ксеноморфы больше не кричат женскими голосами. Собственно, вообще никто с полом NEUTER не орёт женскими голосами. Только женщины;

2021-04-21 18:19 UTC, TobyThorne commented
Ещё фиксов:
- Лицехваты больше не могут прыгать через тонкие окошки и виндуры;
- Лицехваты теперь правильно вырубают космонавтиков;
- Исправлен спам по уже разбитым лампочкам;

2021-04-21 19:50 UTC, TobyThorne commented
Траво-резиновое:
- Временно изменены спрайты конструкций и травы ксеноморфов. На классическе, но перекрашенные в более тёмный оттенок. В будущем, скорее всего, верну современные, но сейчас это решает кучу проблем. 
- Исправлено распространение травы, теперь она проникает повсюду, где могут проходить газы (следовательно, всякие закрытые шлюзы, окна и надувные стенки всё ещё блокируют рост);

Надо будет полностью переписать код травы, но уже в отдельном ПРе, наверное. А то этот и так блоутится как пиздец.
![image](https://user-images.githubusercontent.com/45202681/115610815-2f644400-a30b-11eb-9671-e766ea5ae20d.png)

2021-04-22 11:00 UTC, TobyThorne commented
- Окончательно пофикшена возможность лицехватов прыгать через окна по диагонали. Возможно. В теории, под определённым углом баг всё ещё может воспроизвестись, но вероятность крайне мала.
- Слегка улучшено взаимодействие ксенотравы с окнами. В некоторых случаях она всё ещё может прорасти, но с нынешней реализацией - едва ли я могу это хоть как-то поправить. Исправлю в будущем ПРе с переписыванием травы from scratch.

2021-04-22 15:48 UTC, TobyThorne commented
800 строк? А может лучше 1100?
- Изменена работа способностей ксеноморфов. Теперь помимо вёрбов для непосредственного их использования есть вёрбы по типу "Set Tackle", устанавливающие выбранную способность как активную. Активная способность отображается во вкладке Status и может применяться выбранным в префе "Special Ability Activation Key" способом (по умолчанию - колёсико мыши). Поддерживаемые в данный момент способности - Tackle, Leap, Neurotoxic Spit, Acid Spit;
- Старые вёрбы для использования способностей через выбор из списка оставлены. Мало ли, может кому-то так удобнее;
- Аналогичный функционал теперь используют и воксы, для способности Leap;
- Добавлен вёрб "Disable Abilities", сбрасывающий активную способность. Может быть полено для тех, у кого модули РИГа и способности установлены на одну и ту же кнопку;
- Королевам ксеноморфов добавлены способности Tackle и Gut;
- Стоимость плевка увеличена с 20 до 25 плазмы;
- Урон от кислотного плевка увеличен с 30 до 45;
- Урон токсинами от нейротоксичного плевка увеличен с 5 до 10;
- Transfer Plasma теперь проверяет на наличие рабочего плазмаоргана у цели;

2021-04-22 16:08 UTC, TobyThorne commented
Измененения в здоровье и броне ксеноморфов:
- Раньше у всех типов были модификаторы к получаемому урону в 50% для брута и 200% для бёрна, стало:
- Дроны: 85% и 175%;
- Охотники: 75% и 165%;
- Стражи: 65% и 155%;
- Королева: 50% и 125%;
- Попутно увеличено количество здоровья у частей тел;

2021-04-22 16:14 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/115747900-7f98e000-a3b7-11eb-9f48-0cca4d096145.png)
Думаю, на этом можно пока что остановиться и ревьювать. Состояние, в общем-то, достаточно играбельное.

Что осталось сделать:
- Переписать код травы. Нынешний - рабочий, но уж больно страшный. И оставляет гипотетическую возможность роста травы через окна под некоторыми углами. Но это уже в отдельном ПРе, со свежей головой и всякое такое.
- Что-то придумать с применением способностей через вёрбы. Сейчас они выдают полный список мобов/объектов поблизости. В лоб это не решается. Впрочем, это не особо мешает, ибо всё можно применять либо через контекстное меню, либо с помощью хоткея для способностей.
- Потестить всё с игроками и добалансировать всякие магические циферки.

2021-04-22 16:39 UTC, Doster-d requested changes
Ну, вот и ревью.

2021-04-22 16:39 UTC, Doster-d commented on code/game/objects/items.dm
> +			return 1
```suggestion
			return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/game/objects/items.dm
> +	return canremove ? 1 : 0
```suggestion
	return canremove ? TRUE : FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human.dm
>  		return 1
```suggestion
		return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human.dm
>  	return 0
```suggestion
	return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	return 1
```suggestion
	return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
>  	return 1
```suggestion
	return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
>  		return 1
```suggestion
		return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +	return 1
```suggestion
	return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +		return 1
```suggestion
		return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/organs/external/xenos.dm
>  	return 1
```suggestion
	return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/organs/external/xenos.dm
> +		return 1
```suggestion
		return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +			return 1
```suggestion
			return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +	return 1
```suggestion
	return TRUE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/alien/alien.dm
>  	return 0
```suggestion
	return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/carbon.dm
> +	return 0
```suggestion
	return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +			return 0
```suggestion
			return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
>  		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
>  			return 0
```suggestion
			return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
>  	return 0
```suggestion
	return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
>  	return 0
```suggestion
	return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +			return 0
```suggestion
			return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +	return 0
```suggestion
	return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
>  		return 0
```suggestion
		return FALSE
```

2021-04-22 16:39 UTC, Doster-d commented on code/modules/organs/external/xenos.dm
>  	if(!..()) return 0
```suggestion
	ASSERT(..())
```

2021-04-22 16:41 UTC, TobyThorne commented on code/modules/organs/external/xenos.dm
>  	if(!..()) return 0
тут ассерт нахуй не нужен, оно где-то там легально может нолик выдать

2021-04-22 16:43 UTC, TobyThorne commented
привет ты чё охуел

2021-04-22 16:45 UTC, Doster-d commented on code/modules/organs/external/xenos.dm
>  	if(!..()) return 0
Окей, тогда так.

2021-04-22 16:49 UTC, TobyThorne commented on code/modules/organs/external/xenos.dm
>  	if(!..()) return 0
![image](https://user-images.githubusercontent.com/45202681/115753395-fa182e80-a3bc-11eb-9e20-fb484f81ac87.png)

2021-04-22 17:18 UTC, Doster-d submitted a review, later dismissed

2021-04-24 13:25 UTC, TobyThorne commented
- Время для роста из грудолома во взрослого ксеноморфа уменьшено с 200 секунд до 180;
- Кулдаун плевков увеличен с 1 секунды до 2;
- Ксеноморфы больше не могут спавниться с установленным нейролейсом (касается только кривого админспавна);
- Лица ксеноморфов больше не могут быть изуродованы до неузнаваемости уроном. Unknown-ксеноморфы - это какой-то метамодерн;
- Урон токсинами у плевка нейротоксинами уменьшен с 10 до 5;

2021-04-24 17:17 UTC, Doster-d approved these changes, later dismissed
Ну я смотрел, локалку запускал, людей загонял, все норм.

2021-04-24 20:17 UTC, BooJ1K commented
Нашли пару приколов разной степени смешнявости:

- Фэйсхенгеры Всё ещё могут прыгать сквозь стекло, но так даже лучше
- Можно заражать взрослых Дион. По таймеру, они рассыпаются на мелких и высерают Лавру
- Можно заражать себя лицехватами и своих сородичей, взяв их в руки и ткнув по себе.
- Можно высаживать растения, будучи в вентиляции. 
- Невозможно регенить ожоги, в которых есть заражение. 
- Спутано цена (описание цены) за абилки Set acid spit Требует 50 тратит 25

![Кислоты](https://user-images.githubusercontent.com/47336771/115971649-dc40fa00-a573-11eb-8ffd-1e068b9eea19.png)

2021-04-24 20:20 UTC, TobyThorne commented
> * Спутано цена (описание цены) за абилки Set acid spit Требует 50 тратит 25
> 
> ![Кислоты](https://user-images.githubusercontent.com/47336771/115971649-dc40fa00-a573-11eb-8ffd-1e068b9eea19.png)

50 - трата на подготовку к плевкам, сами плевки тратят по 25, как и указано рядом со Spit.
Остальное сейчас пофикшу, да.

2021-04-25 00:46 UTC, TobyThorne commented
- Исправлена скорость передвижения лицехватов;
- ФБП и дионы больше не могут быть заражены эмбрионом, но лицехваты всё равно будут пытаться;
- Ксеноморфы больше не могут быть заражены эмбрионом;
- Люди с вживлённым hivemind node ксеноморфа больше не атакуются лицехватами, а в случае случайного прыжка - не заражаются эмбрионом, но могут быть заражены им, если лицехвата посадить вручную;
- Грудоломы теперь видят в темноте;
- Способности вроде создания травы и кладки яиц теперь не могут быть применены из труб, шкафчиков, etc.
- Окончательно исправлено взаимодействие лицехватов и окон. Всё ещё есть один единственный случай, в котором лицехват может пройти через стекло, но с этим я уже ничего не могу поделать - это общая проблема взаимодействия окон и projectile'ов.

2021-04-25 19:26 UTC, TobyThorne commented
- Гнёзда теперь показывают оверлей поверх приклеенных жертв;
- ХП ксеноморфских дверей уменьшено до 200 (было 1500);
- Ксеноморфские двери теперь могут открывать только ксеноморфы и люди с вживлённым hivemind node;
- Ксеноморфы теперь ломают собственные постройки только на харме;
- Урон когтей и укусов ксеноморфов увеличен с 10 до 12.5;

- Добавлены особые ксеноморфы, получающиеся с помощью заражения определённых рас. Грудоломы, появившиеся из них всё ещё могут превратиться в любую касту, но имеют улучшенные варианты:
- Скрелл - может превратиться в Vile Drone вместо обычного. Имеет улучшенную регенерацию плазмы на траве и может плеваться кислотой;
- Унатх - может превратиться в Primal Sentinel вместо обычного. Имеет улучшенную регенерацию здоровья на траве и повышенную защиту от бёрна;
- Таяра - может превратиться в Feral Hunter вместо обычного. Имеет значительно повышенный урон от когтей (однако, урон от укусов остаётся прежним);
![alien_types](https://user-images.githubusercontent.com/45202681/116006765-79606900-a62e-11eb-9b62-e6daedcb3752.png)

2021-04-25 19:46 UTC, Shootnik01 commented
Крутяк какой!

2021-04-25 21:51 UTC, TobyThorne commented
- Добавлен рандомный ивент "Stray Facehugger". Один лицехват спавнится в рандомной технической зоне.
- Добавлен рандомный ивент "Xenomorph Infestation". Спавнит грудоломов в определённых зонах. Количество зависит от онлайна, меньше 20 игроков - 1 грудолом, меньше 40 - два грудолома, иначе - три.

2021-04-25 21:52 UTC, TobyThorne commented
Теперь точно пора ревувать, да.

2021-04-25 22:05 UTC, Shootnik01 commented
Если лавру извлекают хирургически - она извлекается живой? Как хедкраб?

2021-04-25 22:09 UTC, TobyThorne commented
> Если лавру извлекают хирургически - она извлекается живой? Как хедкраб?

Извлекается не ларва, а эмбрион. При желании можно пересадить в кого-нибудь - мало ли, кто-нибудь вживит себе hivemind node и решит создать подконтрольную колонию ксеноморфов чтобы астероид зачищали.

2021-04-26 06:17 UTC, Shootnik01 commented
> > Если лавру извлекают хирургически - она извлекается живой? Как хедкраб?
> 
>мало ли, кто-нибудь вживит себе hivemind node и решит создать подконтрольную колонию ксеноморфов чтобы астероид зачищали.

Что за хайвмайнд нод?

2021-04-27 13:07 UTC, Doster-d commented on code/modules/organs/external/xenos.dm
> +process_sec_hud
Что это такое? Почему оно работает?

2021-04-27 13:08 UTC, Doster-d commented
cumфликты

2021-04-27 13:09 UTC, TobyThorne commented on code/modules/organs/external/xenos.dm
> +process_sec_hud
![image](https://user-images.githubusercontent.com/45202681/116246836-21d80f80-a78c-11eb-9eef-32ffbcda3054.png)
не знаю о чем ты

2021-04-27 13:11 UTC, Doster-d requested changes
Все проверил, но cumфликт есть, после исправления будет зеленая галка.

2021-04-27 13:17 UTC, TobyThorne commented
> Все проверил, но cumфликт есть, после исправления будет зеленая галка.

Cumфликты resolvлены.

2021-04-27 18:50 UTC, Doster-d approved these changes, later dismissed
Ну, вроде хорошо, даже локалку запускали под тесты.

2021-04-28 14:58 UTC, Shootnik01 commented
У тебя, походу. хедкрабы в вакууме дохнут

2021-04-28 15:28 UTC, Shootnik01 commented
Еще блоком от аллиенов на раз-два защититься, они его не пробивают

2021-04-28 15:54 UTC, hard-res3t commented
Нельзя снимать шлемы за алиенов.
Можно делать CPR людям, но говорят что фича.

2021-04-28 17:22 UTC, TobyThorne commented
Короче
- Лицехваты больше не умирают в вакууме;
- Лицехваты могут снимать герметичные шлемы, но только при надевании вручную;
- Лицехваты могут повторно заражать людей эмбрионом, если нынешний мёртв;

2021-04-28 17:31 UTC, Shootnik01 commented
Баг: Аллиены не ломают баррикады
Фича: кидать лицехватов в лицо врагам

2021-04-28 17:34 UTC, Shootnik01 commented
Еще момент: при росте из лавры в венте - ты появляешься под ней

2021-04-28 17:35 UTC, Shootnik01 commented
А еще они поинт ту не делают, что печально

2021-04-28 17:55 UTC, TobyThorne commented
- Убрал фон из-под индикатора здоровья ксеноморфов, а то заебали репортить;
- Ксеноморфы теперь могут ломать баррикады. Но барьеры СБ не могут, ибо нехуй;
- При эволюции внутри труб/шкафчиков/etc. моб не будет автоматически из них вылезать;

2021-04-28 18:01 UTC, Shootnik01 commented
Должны ли быть способности у хантера? Если да - то их не видно. если нет - зачем запас плазмы?
![image](https://user-images.githubusercontent.com/75479005/116451153-ce85c000-a864-11eb-94af-0c5aeaad82c2.png)

2021-04-28 18:11 UTC, Shootnik01 commented
Предложение: дать аллиенам возможность ломать обычные(не укрепленные) стены, ибо когти делают хрясь-хрясь

2021-04-28 18:12 UTC, TobyThorne commented
> Предложение: дать аллиенам возможность ломать обычные(не укрепленные) стены, ибо когти делают хрясь-хрясь

Нет

2021-04-28 18:12 UTC, TobyThorne commented
- Больше нельзя эволюционировать в трубах, ибо слишком проблемно. В шкафчиках-моргах-мешках - всё ещё можно.

2021-04-28 18:16 UTC, Shootnik01 commented
Кстати, лично мной не замеченное, но у пацанов вроде подтверждалось: человек с вживленным хранилищем плазмы не может его пополнять на траве(да и вообще). Может и фича, но тут хз.

2021-04-28 19:22 UTC, TobyThorne commented
- Исправлены обжективы у ксеноморфов. Теперь выполнение должно правильно засчитываться;

2021-04-28 19:23 UTC, TobyThorne commented
> Кстати, лично мной не замеченное, но у пацанов вроде подтверждалось: человек с вживленным хранилищем плазмы не может его пополнять на траве(да и вообще). Может и фича, но тут хз.

Фича. Хранить-то хранит, а всасывать нечем, нужно алиумотело.

2021-04-28 23:07 UTC, Doster-d approved these changes
Несколько раз гоняли на локалках, чуть в карты не поиграли, но ксеноморфы побили.
От себя хочу добавить, что если добавлять какой-то из режимов связанный с ксеноморфами, то стоит рассмотреть вариант: таторов + алиумов.

2021-04-28 23:35 UTC, kreeperHLC approved these changes
!!! ПР НЕ ПРОВЕРЯЛСЯ, ТОБИ ВЫПРОСИЛ ГАЛКУ ЧТОБЫ ФИКСИТЬ ВСЁ НА ХОДУ. ЕСЛИ ЧТО, ВИНИТЕ ТОБИ ВО ВСЕХ СМЕРТНЫХ ГРЕХАХ ПРА !!!

2021-04-28 23:39 UTC, TobyThorne commented
Короче, платный иссуй пока отлепляю отсюда. Закроем его вручную, когда убедимся, что всё работает как те самые часы.
А эта херня разрослась до гигантских размеров и грозит конфликтами. Остальные фичи и фиксы, если нужны будут, залью отдельно.

2021-04-28 23:40 UTC, merged

2021-04-28 23:41 UTC, kreeperHLC commented
Обкончал весь #github
![image](https://user-images.githubusercontent.com/14943437/116485665-71a1fe00-a894-11eb-9641-6a8129282d4f.png)
![image](https://user-images.githubusercontent.com/14943437/116485678-7666b200-a894-11eb-888c-5182566f105b.png)