Plastic bags
ChaoticOnyx/OnyxBay pull request #4955
Opened 2021-04-20 22:09 UTC by Zert0X

1)Добавлены спрайты пакета как маски(перевёрнутый пакет в руке)
2)Добавлено две маски:
   2.1)Просто пакет на голове(ограничивает зрение)
   2.2)Пакет с куском изоленты(дополнительно душит)
3)Добавлены спрайты отображения на персонаже для тонкотрапок и обычных людей
4)При активации пакета в руке из него всё выпадает и тот становится маской(2.1)
5)Гифка теста
![2021-04-21 00-59-36](https://user-images.githubusercontent.com/42303535/115469910-20fc2680-a23e-11eb-8f29-11f80992f0cf.gif)
close #1146 
- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-20 22:10 UTC, Zert0X commented
Гифка решила что быть на ониксе вредно и решила не загружаться. Вот видосик
https://user-images.githubusercontent.com/42303535/115470036-5b65c380-a23e-11eb-9360-6a0546b767cd.mp4

2021-04-20 22:23 UTC, DarkHunter7756 commented
Reject humanity
Return to plastic
![image](https://user-images.githubusercontent.com/76823962/115471117-235f8000-a240-11eb-9662-9ea664443d0f.png)

2021-04-21 06:52 UTC, Doster-d requested changes

2021-04-21 06:52 UTC, Doster-d commented on code/modules/clothing/masks/gasmask.dm
> +	say_verbs = list("mumbles", "says")
![image](https://user-images.githubusercontent.com/63081538/115509449-1e71ef00-a287-11eb-9a2b-5a73d14371ae.png)

2021-04-21 06:52 UTC, Doster-d commented on code/modules/clothing/masks/miscellaneous.dm
> +		to_chat(user, "You attach [W] piece to [src]!")
```suggestion
		to_chat(user, "You attach piece of [W] to [src]!")
```

2021-04-21 06:56 UTC, TobyThorne commented on code/modules/clothing/masks/miscellaneous.dm
> +		to_chat(user, "You attach [W] piece to [src]!")
'a' забыл

2021-04-21 13:48 UTC, Doster-d requested changes

2021-04-21 13:48 UTC, Doster-d commented on code/game/objects/items/weapons/storage/bags.dm
> +	user.put_in_hands(new /obj/item/clothing/mask/plasticbag)
```suggestion
	user.put_in_any_hand_if_possible(new /obj/item/clothing/mask/plasticbag)
```

2021-04-21 13:48 UTC, Doster-d commented on code/modules/clothing/masks/gasmask.dm
> +	say_verbs = list("mumbles", "says")
```suggestion
	say_verbs = list("mumbles")
```
"Mmfph!", "Mmmf mrrfff!", "Mmmf mnnf!" не очень похоже на разговор.

2021-04-21 13:48 UTC, Doster-d commented on code/modules/clothing/masks/gasmask.dm
> +	item_flags = null
```suggestion
	item_flags = ITEM_FLAG_BLOCK_GAS_SMOKE_EFFECT & ITEM_FLAG_THICKMATERIAL
```
Ты как задыхаешься, воздух нет, а дым все равно можешь сосать - не логично.
Врачи также не могут пробить пакет шприцем, у нас они хорошего качества.

2021-04-21 14:28 UTC, Doster-d approved these changes
Ну вроде ок

2021-04-21 15:24 UTC, kreeperHLC approved these changes

2021-04-22 11:28 UTC, HonkyDonky commented on code/game/objects/items/weapons/storage/bags.dm
> +/obj/item/weapon/storage/bag/plasticbag/attack_self(mob/user as mob)
может хватит пихать асы в аргументы уже а

2021-04-22 11:41 UTC, Doster-d commented on code/game/objects/items/weapons/storage/bags.dm
> +/obj/item/weapon/storage/bag/plasticbag/attack_self(mob/user as mob)
Как я это пропустил...

2021-04-22 11:42 UTC, Doster-d requested changes
as

2021-04-22 12:20 UTC, Zert0X commented on code/game/objects/items/weapons/storage/bags.dm
> +/obj/item/weapon/storage/bag/plasticbag/attack_self(mob/user as mob)
ука

2021-04-23 15:12 UTC, HonkyDonky approved these changes

2021-04-23 15:13 UTC, Doster-d approved these changes

2021-04-27 12:55 UTC, merged

2021-04-27 16:23 UTC, Zert0X commented
ураааа

2021-04-30 09:59 UTC, Epicus7 commented
Награда выдана.