Метроидное
ChaoticOnyx/OnyxBay pull request #4960
Opened 2021-04-21 16:59 UTC by kreeperHLC

Это наконец случилось! Метроиды снова с нами. Бекдоры конечно же вшиты, проверяйте. 

Заодно пофиксил баг с спрайтами теперь уже метроидной еды.
А ещё изменение спрайта теперь уже метроида когда он просто стоит и когда он ест.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-21 17:50 UTC, TobyThorne commented on code/game/objects/items/devices/scanners.dm
> +		user.show_message("<span class='notice'>metroid scan result for \the [T]:</span>")
Заглавную букву проебал

2021-04-21 17:52 UTC, TobyThorne commented on code/modules/integrated_electronics/subtypes/input.dm
> +	desc = "A very small version of the xenobio analyser. This allows the machine to know every needed properties of metroid. Output mutation list is non-associative."
a metroid, как со слизью теперь не получится

2021-04-21 17:55 UTC, TobyThorne commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	nutriment_desc = list("metroid" = 2, "soy" = 2)
не думаю, что тут есть смысл менять "слизь" на "метроида"

2021-04-21 17:56 UTC, TobyThorne commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	nutriment_desc = list("cake" = 10, "sweetness" = 10, "metroid" = 15)
и тут тоже

2021-04-21 18:23 UTC, kreeperHLC commented
Всё исправлено

2021-04-24 16:38 UTC, TobyThorne approved these changes, later dismissed
Пробежался, вроде ничего не сломалось.

2021-04-24 16:38 UTC, TobyThorne commented on code/modules/client/preference_setup/traits/trait_defines.dm
> -	desc = "Slimes are quite dangerous, but just the aspect of something being slimey is uncomfortable."
Вот тут теперь не очень сос мыслом.
Но да похуй, всё равно закомментированный код. Оставим на совести тех, кто захочет это впилить.

2021-04-29 00:32 UTC, TobyThorne commented
Конфликтнулись.

2021-05-06 01:18 UTC, kreeperHLC commented
На будущее ребяткам из канала Гитбота: Никогда не пытайтесь фиксить код в четыре часа ночи. Лучше начинать с утра говно разгребать.

2021-05-23 13:39 UTC, TobyThorne commented
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2021-05-29 20:05 UTC, TobyThorne submitted a review, later dismissed

2021-05-31 22:47 UTC, Doster-d submitted a review, later dismissed
Ничего плохого не заметил.

2021-06-08 15:38 UTC, igorsaux requested changes
Конфликты

2021-06-08 18:48 UTC, kreeperHLC commented
Скоро Метроиды смогут посоревноваться с Козлами

2021-06-08 18:51 UTC, kreeperHLC commented
Убейте стайлкопа, он не мои строчки проверяет

2021-06-08 18:52 UTC, igorsaux approved these changes

2021-06-08 18:53 UTC, Zert0X approved these changes
Что может пойти не так?

2021-06-08 20:32 UTC, TobyThorne commented
Товарищи выше галочки повесили, умываю руки.

2021-06-08 20:32 UTC, merged