Dreamchecker: missing keyword args
ChaoticOnyx/OnyxBay pull request #4972
Opened 2021-04-22 12:09 UTC by HonkyDonky

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-22 12:13 UTC, Doster-d requested changes

2021-04-22 12:13 UTC, Doster-d commented on code/game/mecha/equipment/weapons/weapons.dm
> +	Bump(atom/A, forced = FALSE)
```suggestion
/obj/item/projectile/beam/pulse/heavy/Bump(atom/A, forced = FALSE)
```
Давай еще вот так сделаем.

2021-04-22 12:13 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +	Bump(atom/A, forced = FALSE)
```suggestion
/obj/item/projectile/meteor/Bump(atom/A, forced = FALSE)
```

2021-04-22 12:14 UTC, HonkyDonky commented on code/game/mecha/equipment/weapons/weapons.dm
> +	Bump(atom/A, forced = FALSE)
Это должно быть в другом ПРе.

2021-04-22 12:15 UTC, Doster-d commented on code/game/mecha/equipment/weapons/weapons.dm
> +	Bump(atom/A, forced = FALSE)
![image](https://user-images.githubusercontent.com/63081538/115712544-93275500-a37d-11eb-8256-bdc705c17869.png)

2021-04-22 12:16 UTC, HonkyDonky commented on code/game/mecha/equipment/weapons/weapons.dm
> +	Bump(atom/A, forced = FALSE)
Только там ещё ниже кучу всего нужно будет потрогать, а я этого не хочу, ибо этот ПР про другое.

2021-04-22 12:26 UTC, Doster-d commented on code/game/mecha/equipment/weapons/weapons.dm
> +	Bump(atom/A, forced = FALSE)
Ладно.

2021-04-22 12:26 UTC, Doster-d approved these changes

2021-04-30 18:12 UTC, TobyThorne approved these changes
Будем надеяться, что ничего не поломается.

2021-04-30 18:12 UTC, merged