Chicken cube
ChaoticOnyx/OnyxBay pull request #5008
Opened 2021-04-28 19:52 UTC by MaxFreemen

Что сделано:
- Завернутый куриный куб
- Развернутый куриный куб
- Эффект от проглатывания куба

Работает новый предмет как обезьяний куб (monkey cube) т.е надо развернуть и добавить воды, чтоб появилась рандомная курица.

https://user-images.githubusercontent.com/47484306/116464257-6c34bb80-a874-11eb-95af-9e38cc309c9b.mp4

close #3939

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-28 20:05 UTC, Zert0X reviewed
Вроде говна не обнаружено

2021-04-28 20:21 UTC, kreeperHLC approved these changes
Напрягает конечно что копипаста с куба мартышек. Можно было бы вывести кубы в один тип и мыртышечные с куриными как подтипы прописать, но да ладно

2021-04-28 20:31 UTC, Zert0X commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		Expand()
Выходит что даже завёрнутый в водопулеогневетроустойчивую упаковку кубик будет вылуплять курочек.

2021-04-29 04:12 UTC, MemoryDreams commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		Expand()
Манкикубы точно так же работают.

2021-05-01 11:46 UTC, Zert0X commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		Expand()
> 
> 
> Манкикубы точно так же работают.

баг 😏

2021-05-03 13:47 UTC, TobyThorne requested changes
Не очень понятно, зачем вся копипаста. Достаточно унаследовать /obj/item/weapon/reagent_containers/food/snacks/monkeycube и присвоить monkey_type = /mob/living/simple_animal/chicken.
Да и спрайт кубиков симпотный, но слишком уж огромный в сравнении с теми же манкикубами.

2021-05-03 13:52 UTC, TobyThorne commented
Я бы предложил использовать chickcubewrap в качестве коробки для этих кубиков. А сами кубики перекрасить из обезьяних в более "куриный" цвет.

2021-05-13 14:00 UTC, bosslobster commented
Зумеры открыли Галину Бланку

2021-05-17 03:28 UTC, TobyThorne commented
В нынешнем виде - совсем не канает, а автора больше двух недель не видно. Если вернётся и решит доделать - пусть стучит в дискорд, переоткроем.

2021-05-17 12:24 UTC, MemoryDreams commented
Я там скинул автору маленькие кубики для курицы буквально вчера. Сказал, сделает их вместо больших, а большой использует как коробку.

2021-05-17 12:24 UTC, MemoryDreams commented
Рано закрыли!

2021-05-17 12:29 UTC, PlinHost commented
Вам дали яйца, а вы какой-то фигней занимаетесь.

2021-05-17 19:38 UTC, TobyThorne commented
К слову, да. Достаточно покормить курицу пшеницей и она будет нести фертильные яйца, из которых вылупляются цыплята.

2021-05-17 19:40 UTC, DarkHunter7756 commented
А если курица нужна ЗДЕСЬ И СЕЙЧАС? ( ͡° ͜ʖ ͡°)

2021-05-17 19:47 UTC, TobyThorne commented
> А если курица нужна ЗДЕСЬ И СЕЙЧАС...

...то существует карго.

2021-05-18 04:22 UTC, MemoryDreams commented
> > А если курица нужна ЗДЕСЬ И СЕЙЧАС...
> 
> ...то существует карго.

Карго это от лукавого. Отсылки на Галина Бланка круто. Открывай пр.

2021-05-18 18:39 UTC, MaxFreemen commented
> В нынешнем виде - совсем не канает, а автора больше двух недель не видно. Если вернётся и решит доделать - пусть стучит в дискорд, переоткроем.

Автор пришел - открывайте ветку. Добавил новые спарйты для кубика и коробки, код переписал так, что теперь куб является дочерним "monkeycube", коробку добавил для них, как было сказано ранее. Баг, о котором говорил Zert0X я в этом проекте исправлять не буду - думаю, что лучше отдельной веткой эту проблему решить.

2021-05-18 18:40 UTC, Doster-d commented
Так ты сам мог.

2021-05-31 05:30 UTC, TobyThorne approved these changes
Раз конфликты - можно и аппрувать.

2021-06-18 20:47 UTC, TobyThorne commented
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 2 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2021-06-20 19:43 UTC, TobyThorne commented
Три недели конфликтов, автор снова пропал.

2021-06-20 19:43 UTC, closed without merging