Bord sheet loader to autolathe fix
ChaoticOnyx/OnyxBay pull request #5013
Opened 2021-04-29 09:17 UTC by Zert0X

Собственно говоря как у нас работает АВТОЛАТ, он проверяет может ли user, дропнуть/положить куда-то то, что у него в руке, т.к. в руке у борга не листы метала а sheet loader то соответственно ничего не происходит ибо дропнуть и сложить он его не может АВТОЛАТ ругается, что Вы такое положить не можете
Так что была сделана проверка на то что моб является карбоном

fix #5009

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-29 09:26 UTC, kreeperHLC commented
Так проблема не решилась, ты всё ещё не сможешь класть листы в автолат. Он просто не даст боргам вообще что либо класть в автолат

2021-04-29 09:27 UTC, Zert0X commented
> 
> 
> Так проблема не решилась, ты всё ещё не сможешь класть листы в автолат. Он просто не даст боргам вообще что либо класть в автолат

решилась

2021-04-29 09:40 UTC, Zert0X commented
https://user-images.githubusercontent.com/42303535/116531595-06821700-a8e8-11eb-8c41-e694b7a6ede5.mp4

для особо неверующих

2021-04-29 13:13 UTC, O0oMaximo0O commented
Ага, т.е. моё предложение сработало). Ещё момент, стоит проверить, что инженерный киборг не может заливать в автолат свои листы, т.к. у них тип `/obj/item/stack/material/cyborg/`, а там в автолате дальше есть
...
```c#
if(istype(eating,/obj/item/stack))
```
...
`is_robot_module()` не учитывает листы материалов, которые в модулях киборгов. Либо добавить туда
```c#
if (!thing || !istype(thing.loc, /obj/item/stack/material/cyborg))
		return 0
```
Либо ёщё как-то проверять, если это на что-то важное влияет.
Вряд ли это корректно с точки зрения баланса будет. Его тогда все будут пинать чтобы он автолаты все наполнял. Но это моё личное мнение.

2021-04-29 14:47 UTC, Zert0X commented
> 
> 
> Ага, т.е. моё предложение сработало). Ещё момент, стоит проверить, что инженерный киборг не может заливать в автолат свои листы, т.к. у них тип `/obj/item/stack/material/cyborg/`, а там в автолате дальше есть
> ...
> 
> ```cs
> if(istype(eating,/obj/item/stack))
> ```
> 
> ...
> `is_robot_module()` не учитывает листы материалов, которые в модулях киборгов. Либо добавить туда
> 
> ```cs
> if (!istype(thing.loc, /obj/item/stack/material/cyborg))
> 	return 0
> ```
> 
> Либо ёщё как-то проверять, если это на что-то важное влияет.
> Вряд ли это корректно с точки зрения баланса будет. Его тогда все будут пинать чтобы он автолаты все наполнял. Но это моё личное мнение.
> 
> Upd:
> 
> > инженерный киборг не может заливать в автолат свои листы
> 
> Хм, а в протолат может?

ну я не геймдизайнер но есть два момента:
1) А зачем инженерному боргу в протолат/автолат лезть
2)Он может это делать через магнетик грипер, разобрав окно/что-то металлическое из своих ресов

2021-04-29 14:55 UTC, O0oMaximo0O commented
Может. Но это дольше,чем просто нажать на автолат/протолат. Я сейчас в игре попробую проверить на протолате.

2021-04-29 14:59 UTC, Zert0X commented
> 
> 
> Может. Но это дольше,чем просто нажать на автолат/протолат. Я сейчас в игре попробую проверить на протолате.

Инж борг свои встроенные ресурсы не может кидать ни в протолат, ни в автолат. Но откровенно говоря оно ему и ненадо

2021-04-29 15:01 UTC, O0oMaximo0O commented
> > Может. Но это дольше,чем просто нажать на автолат/протолат. Я сейчас в игре попробую проверить на протолате.
> 
> Инж борг свои встроенные ресурсы не может кидать ни в протолат, ни в автолат. Но откровенно говоря оно ему и ненадо

А, хорошо тогда.

2021-04-29 16:28 UTC, No-Tips commented
Надеюсь, мейнтейнс дроны не могут кидать листы в автолат?

2021-04-29 16:56 UTC, Zert0X commented
> 
> 
> Надеюсь, мейнтейнс дроны не могут кидать листы в автолат?

GOOD QUESTION

2021-04-29 17:12 UTC, No-Tips commented
Я тебя разочарую - им нужно вырезать возможность пихать сталь в автолат. Уж не проще будет сделать проверку наличия в активной руке этого гриппера стали/стекла?

2021-04-29 19:35 UTC, O0oMaximo0O commented
Выпилить не в плане же запретить использовать -_-.
Если ты про это

> Я тебя разочарую - им нужно вырезать возможность пихать сталь в автолат. Уж не проще будет сделать проверку наличия в активной руке этого гриппера стали/стекла?
> В ином случае можно будет ждать всплытия очень странных багов.

то моё предложение решает это. Ну, если я правильно код написал, ибо я 2-й день только в это погружён). СВОЮ сталь они не будут пихать. Только манипуляторами.

2021-04-29 19:37 UTC, Zert0X commented
> 
> 
> Выпилить не в плане же запретить использовать -_-.
> Если ты про это
> 
> > Я тебя разочарую - им нужно вырезать возможность пихать сталь в автолат. Уж не проще будет сделать проверку наличия в активной руке этого гриппера стали/стекла?
> > В ином случае можно будет ждать всплытия очень странных багов.
> 
> то моё предложение решает это. Ну, если я правильно код написал, ибо я 2-й день только в это погружён). СВОЮ сталь они не будут пихать. Только манипуляторами.

Они и сейчас не могут этого делать

2021-04-30 17:59 UTC, TobyThorne requested changes
Не понял, что это и зачем это. Это просто ломает проверку и в автолат теперь можно пихать всякие насадки от сварочного рюкзака.

edit: А, мля. Это же iscarbon.

2021-05-03 14:02 UTC, TobyThorne approved these changes
Ладно, пойдёт.

2021-05-03 16:30 UTC, HonkyDonky approved these changes

2021-05-03 16:36 UTC, igorsaux approved these changes

2021-05-03 16:46 UTC, merged