Name that Ian!
ChaoticOnyx/OnyxBay pull request #5021
Opened 2021-04-30 16:02 UTC by MaxFreemen

Что добавлено:
- Яна/Иэна(?) можно переименовать, если игрок находится в радиусе трех клеток(?) от него.

close #3890

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-04-30 16:34 UTC, eckff requested changes
Желательно перенести это в функцио и добавлять её если у моба есть переменная `renameable = TRUE`, но это так, опционально.

2021-04-30 16:34 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +		src.rename()
Зачем тут src? Можно и без него.

2021-04-30 16:34 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +		return
В else return тут нет смысла, верб ничего не возвращает.

2021-04-30 16:34 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	var/mob/M = usr //user as mob interacts with corgi
Делать переменную ради to_chat() не имеет смысла, можно просто сделать `to_chat(usr, "blabla")`

2021-04-30 16:34 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(src && input)
Предлагаю:
`if(!QDELETED(src) && input && (get_dist(usr, src) <= 3))`

QDELETED - проверяет удалён ли объект или помещён ли он в мусорщик, заменяет `!src`
`get_dist` вытаскивает дальность между первым и вторым (например 3 или 2). В конечном итоге если радиус больше после введения импута - новое имя не присуждается.

2021-04-30 16:34 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	var/input = sanitize(input("How do you want to name this pet?", "Rename", src.name) as null|text)
`sanitize(input("How do you want to name this pet?", "Rename \the [src]", name) as null|text)`
Убираем `src.` там где name. Опционально можно добавить в тайтлт окошка `Rename \the [src]"` чтобы он показывал текущее имя моба.

2021-04-30 16:34 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(src in range(3))
`if(get_dist(usr, src) <= 3)`

2021-04-30 16:40 UTC, MaxFreemen commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(src in range(3))
> `if(get_dist(usr, src) <= 3)`

Хм... Действительно, так даже лучше. Спасибо.

2021-04-30 16:43 UTC, eckff commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	var/mob/M = usr //user as mob interacts with corgi
Опционально можно поставить if(!usr на случай если какая-то гадость вызовет без юзера.

2021-04-30 16:52 UTC, MaxFreemen commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	var/mob/M = usr //user as mob interacts with corgi
> Опционально можно поставить if(!usr) на случай если какая-то гадость вызовет без юзера.

А как вообще такое быть может? Я недавно пишу на этом языке, поэтому еще не все знаю.

2021-04-30 17:10 UTC, MrMagick2104 commented
Имхо, радиус в три клетки - такое себе.

Сидит Ян на стуле мостика, а мимопроходящий ассистент переименовывает его в "Хос - хуесос".

Лучше бы добавить возможность переименования только тогда, когда он в руках (ну или на тайле с игроком), а также ограничить переименования до одного раза.

2021-04-30 17:15 UTC, MaxFreemen commented
> Имхо, радиус в три клетки - такое себе.
> 
> Сидит Ян на стуле мостика, а мимопроходящий ассистент переименовывает его в "Хос - хуесос".
> 
> Лучше бы добавить возможность переименования только тогда, когда он в руках (ну или на тайле с игроком), а также ограничить переименования до одного раза.

Можно тогда просто радиус до двух клеток сбросить.

2021-04-30 17:19 UTC, TatarTheBuilder commented
В иссуе сказано про всех корги, а не только про Яна.

Но даже если так, то радиус для переименования не нужен. Желательно запилить как уже предложил и выше - переименовать можно только держа собаку в руке, и только один раз.

2021-04-30 17:21 UTC, MaxFreemen commented
> В иссуе сказано про всех корги, а не только про Яна.
> 
> Но даже если так, то радиус для переименования не нужен. Желательно запилить как уже предложил и выше - переименовать можно только держа собаку в руке, и только один раз.

А если я распространю этот кусок кода на всех животных? Будет забавно, если для переименования коровы надо в руки ее взять.

2021-04-30 17:26 UTC, Wuattt commented
так может просто сделаете чтоб на расстоянии в один тайл можно было переименовать?

2021-04-30 17:28 UTC, MaxFreemen commented
> так может просто сделаете чтоб на расстоянии в один тайл можно было переименовать?

Я вот тоже думаю, что так лучше всего сделать.

2021-04-30 17:31 UTC, TatarTheBuilder commented
> так может просто сделаете чтоб на расстоянии в один тайл можно было переименовать

1. Собаки бегают туда-сюда, могут легко отбежать на тайл дальше пока ты возишься с контекстным меню.
2. Можно будет переименовывать сквозь тонкие стекла/виндуры/етц.

2021-04-30 17:45 UTC, MaxFreemen commented
> > так может просто сделаете чтоб на расстоянии в один тайл можно было переименовать
> 
> 1. Собаки бегают туда-сюда, могут легко отбежать на тайл дальше пока ты возишься с контекстным меню.
> 2. Можно будет переименовывать сквозь тонкие стекла/виндуры/етц.

Ты прав - исправляю.

2021-04-30 19:01 UTC, MrMagick2104 commented
> Собаки бегают туда-сюда, могут легко отбежать на тайл дальше пока ты возишься с контекстным меню.

Собаку можно и на руки взять.

> Можно будет переименовывать сквозь тонкие стекла/виндуры/етц.

По-моему, у нас есть проверка, называется как-то по типу "аджастенд", она эти случаи учитывает.

2021-04-30 19:03 UTC, MaxFreemen commented
> > так может просто сделаете чтоб на расстоянии в один тайл можно было переименовать
> 
> 1. Собаки бегают туда-сюда, могут легко отбежать на тайл дальше пока ты возишься с контекстным меню.
> 2. Можно будет переименовывать сквозь тонкие стекла/виндуры/етц.

Ну, теперь всех корги можно переименовать, но есть еще ряд проблем. Т.к я работаю с Byond недавно - я многого не знаю, и возникла проблема. Я могу добавить взаимодействие "Name pet" для корги, которого взяли на руки, но вот вызвать функцию переименования так, чтоб она работала,  у меня не получается.

2021-04-30 19:19 UTC, Zert0X commented
> 
> 
> > > так может просто сделаете чтоб на расстоянии в один тайл можно было переименовать
> > 
> > 
> > 
> > 1. Собаки бегают туда-сюда, могут легко отбежать на тайл дальше пока ты возишься с контекстным меню.
> > 2. Можно будет переименовывать сквозь тонкие стекла/виндуры/етц.
> 
> Ну, теперь всех корги можно переименовать, но есть еще ряд проблем. Т.к я работаю с Byond недавно - я многого не знаю, и возникла проблема. Я могу добавить взаимодействие "Name pet" для корги, которого взяли на руки, но вот вызвать функцию переименования так, чтоб она работала, у меня не получается.

![изображение](https://user-images.githubusercontent.com/42303535/116743768-1261fc00-aa02-11eb-911c-094a1aa5e11e.png)
Ибо в руке это не животное, а нечто другое

2021-05-17 03:23 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(get_dist(usr, src) <= 1)
```suggestion
	if(Adjacent(usr))
```

2021-05-17 03:23 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(!QDELETED(src) && input && (get_dist(usr, src) <= 1))
```suggestion
	if(!QDELETED(src) && input && Adjacent(usr))
```

2021-05-17 03:24 UTC, TobyThorne commented
Ещё надо "именным" собакенам (Йэн и Лиза) убрать возможность переименования.

2021-05-18 11:11 UTC, MaxFreemen commented
> Ещё надо "именным" собакенам (Йэн и Лиза) убрать возможность переименования.

Вас понял, сегодня все исправлю.

2021-05-22 06:28 UTC, TobyThorne commented on code/modules/mob/holder.dm
> +		if(istype(M, /mob/living/simple_animal/corgi/Ian) || istype(M, /mob/living/simple_animal/corgi/Lisa))
Такие себе проверки. Можно сделать проще - сделать корги переменную типа "can_be_renamed = TRUE" и её проверять. Яну и Лизе поставить FALSE, обычным собакам при первом переименовании тоже выставлять FALSE.

2021-06-18 20:46 UTC, TobyThorne commented
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 2 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2021-06-20 19:45 UTC, TobyThorne commented
haha PR goes stale

2021-06-20 19:45 UTC, closed without merging