чеиниииижжлох [4/5]
ChaoticOnyx/OnyxBay pull request #5036
Opened 2021-05-02 17:28 UTC by TapKo4eB

не доделал, остались коммиты с 9ab5a347370996bf8362647b2b091ac50971bfd8 по head
кто доделает тот крутой

2021-05-02 17:35 UTC, Doster-d approved these changes

2021-05-02 20:03 UTC, TobyThorne commented on html/changelog.html
> +				<li class="green"><i class="fas fa-bug"></i>Дополнена работа кастомок для киборгов.</li>
Разве я там что-то добавлял? :thonk:
Вроде только свою кастомку впилил

2021-05-02 20:04 UTC, TobyThorne commented on html/changelog.html
> +				<li class="green"><i class="fas fa-bug"></i>Исправлен макрос на вывод звука.</li>
Вот это в лог не надо, это фикс хуйни, которую сделал парой коммитов выше.

2021-05-03 16:31 UTC, Doster-d approved these changes
Вроде норм, сойдет.

2021-05-04 14:52 UTC, Doster-d commented
fas fa-tweak
![image](https://user-images.githubusercontent.com/63081538/117023098-771e9e80-ad01-11eb-9e9f-9eecd7f7ec23.png)

2021-05-04 14:52 UTC, Doster-d requested changes
Нет такой иконки, мб одну из этих
https://fontawesome.com/icons/tools?style=solid
https://fontawesome.com/icons/balance-scale?style=solid

2021-05-04 15:04 UTC, igorsaux commented
> Не работает, см. коммент выше, хз как исправить.

Нет такой иконки, мб одну из этих:
https://fontawesome.com/icons/tools?style=solid
https://fontawesome.com/icons/balance-scale?style=solid

2021-05-04 15:17 UTC, Doster-d commented
> > Не работает, см. коммент выше, хз как исправить.
> 
> Нет такой иконки, мб одну из этих:
> https://fontawesome.com/icons/tools?style=solid
> https://fontawesome.com/icons/balance-scale?style=solid

fas fa-balance, чтобы вторую выбрать, да?

2021-05-04 15:18 UTC, Doster-d commented
А все, вижу.

2021-05-04 15:18 UTC, igorsaux commented
> > > Не работает, см. коммент выше, хз как исправить.
> > 
> > 
> > Нет такой иконки, мб одну из этих:
> > https://fontawesome.com/icons/tools?style=solid
> > https://fontawesome.com/icons/balance-scale?style=solid
> 
> fas fa-balance, чтобы вторую выбрать, да?

да

2021-05-04 15:20 UTC, Doster-d submitted a review, later dismissed

2021-05-04 16:57 UTC, Doster-d submitted a review, later dismissed

2021-05-05 23:50 UTC, Doster-d approved these changes

2021-05-05 23:50 UTC, igorsaux submitted a review, later dismissed

2021-05-06 00:10 UTC, igorsaux approved these changes

2021-05-06 00:11 UTC, igorsaux approved these changes

2021-05-06 00:27 UTC, Doster-d approved these changes

2021-05-06 20:30 UTC, closed without merging