Removes lack of immersive pills and syringes
ChaoticOnyx/OnyxBay pull request #5079
Opened 2021-05-08 01:25 UTC by TobyThorne

- Исправлена возможность использовать сломанные шприцы в шприцемёте.
- Теперь от пресетовых шприцов и банок с таблетками можно оторвать этикетку (Remove Label), убрав название препарата.
- Пресетовые банки с таблетками теперь имеют цветовую индикацию на спрайте.
- Теперь таблетки можно глотать (и скармливать другим) напрямую из банок. При этом таблетка выбирается случайно.
- Пресетовые шприцы теперь появляются в упаковках. Перед использованием, что очевидно, их нужно открывать.
- Слегка отредактирован спрайт банок с таблетками.
- Вместимость банок с таблетками уменьшена с 21 до 14. 1260 реагентов в одной маленькой баночке - это перебор.
- Удалены таблетки и банки с таблетками типа antitox - они дублировали тип dylovene.

<details>
<summary>Чейнджлог</summary>
🆑
bugfix: Исправлена возможность использовать сломанные шприцы в шприцемёте.
tweak: Теперь от пресетовых шприцов и банок с таблетками можно оторвать этикетку (Remove Label), убрав название препарата.
tweak: Пресетовые банки с таблетками теперь имеют цветовую индикацию на спрайте.
tweak: Теперь таблетки можно глотать (и скармливать другим) напрямую из банок. При этом таблетка выбирается случайно.
tweak: Пресетовые шприцы теперь появляются в упаковках. Перед использованием, что очевидно, их нужно открывать.
imageadd: Слегка отредактирован спрайт банок с таблетками.
tweak: Вместимость банок с таблетками уменьшена с 21 до 14. 1260 реагентов в одной маленькой баночке - это перебор.
/🆑
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-09 01:29 UTC, Doster-d approved these changes, later dismissed

2021-05-10 12:39 UTC, igorsaux requested changes

2021-05-10 12:39 UTC, igorsaux commented on code/datums/extensions/label.dm
> +	if(user)
А `user?.visible_message(...)` работать не будет?

2021-05-10 12:39 UTC, igorsaux commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		if(pill?.loc != src)
проверка на null была же выше

2021-05-10 12:39 UTC, igorsaux commented on code/modules/projectiles/guns/launcher/syringe_gun.dm
> +		if(S.mode == "broken")
строку надо заменить на дефайны

2021-05-10 12:39 UTC, igorsaux commented on code/modules/projectiles/guns/launcher/syringe_gun.dm
> +		if(S.mode == "packaged")
строку надо заменить на дефайны

2021-05-10 12:39 UTC, igorsaux commented on code/modules/reagents/reagent_containers/syringes.dm
> +#define SYRINGE_DRAW "draw"
В `code\modules\mob\living\silicon\robot\robot_modules.dm` и `code\modules\hydroponics\trays\tray.dm` надо обновить проверки, там вместо дефайнов цифры.

2021-05-10 12:39 UTC, igorsaux commented on code/modules/reagents/reagent_containers/syringes.dm
> +		overlays += injoverlay
нет проверки на нулл

2021-05-10 18:30 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/firstaid.dm
> +		if(pill?.loc != src)
Так тут ещё do_mob с баночкой выше. За это время таблетка может куда-то деться.

2021-05-10 18:51 UTC, igorsaux submitted a review, later dismissed

2021-05-12 16:12 UTC, TobyThorne commented
Расконфликчено.

2021-05-13 08:03 UTC, igorsaux approved these changes

2021-05-13 14:56 UTC, Doster-d approved these changes

2021-05-13 14:58 UTC, merged