Removes absence of poise on-screen meter
ChaoticOnyx/OnyxBay pull request #5094
Opened 2021-05-10 23:24 UTC by TobyThorne

🆑
tweak: В интерфейс добавлен показатель пойза у персонажа.
/🆑

![image](https://user-images.githubusercontent.com/45202681/117736278-0bfd2c80-b219-11eb-982d-1c5dff9e466a.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-10 23:54 UTC, igorsaux requested changes

2021-05-10 23:54 UTC, igorsaux commented on code/_onclick/hud/human.dm
> +		mymob.poise_icon = new/obj/screen()
:joy:

2021-05-10 23:56 UTC, TobyThorne commented
Вылечил new, сделал иконки чуть симпотнее и добавил обновление иконки при каждом уроне по пойзу.

2021-05-11 00:03 UTC, igorsaux approved these changes

2021-05-12 08:47 UTC, igorsaux approved these changes
Как мне кажется - лучше ещё сдвинуть на пару пикселей влево.

2021-05-12 08:50 UTC, TobyThorne commented
> Как мне кажется - лучше ещё сдвинуть на пару пикселей влево.

Пробовал, слишком сильно прилегает к здоровью.

2021-05-13 14:58 UTC, Doster-d approved these changes

2021-05-13 14:59 UTC, merged