Doors can be interacted with by clicking on turf
ChaoticOnyx/OnyxBay pull request #5122
Opened 2021-05-13 11:47 UTC by ITCups

Двери можно открыть кликая на турф а не на иконку двери

<details>
<summary>Чейнджлог</summary>

```yml
🆑 [your_name]
rscadd: Двери теперь можно открывать кликая на тайл где находится дверь.
/🆑
```
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-13 11:53 UTC, Zert0X commented on code/_onclick/ai.dm
> +	return ..()
ньюлайны

2021-05-13 11:53 UTC, Zert0X commented on code/_onclick/cyborg.dm
> +	AIShiftClick(user)
аналогично

2021-05-13 12:31 UTC, Doster-d commented
[your name] убери, и ньюлайны.

2021-05-14 09:26 UTC, igorsaux requested changes

2021-05-14 09:26 UTC, igorsaux commented on code/_onclick/ai.dm
> +//QOL feature, clicking on turf can toogle doors
```suggestion
// QOL feature, clicking on turf can toogle doors
```

2021-05-14 09:26 UTC, igorsaux commented on code/_onclick/ai.dm
> +	//QOL feature, clicking on turf can toogle doors
```suggestion
	// QOL feature, clicking on turf can toogle doors
```

2021-05-14 09:26 UTC, igorsaux commented on code/_onclick/cyborg.dm
> +//QOL feature, clicking on turf can toogle doors
```suggestion
// QOL feature, clicking on turf can toogle doors
```

2021-05-14 09:26 UTC, igorsaux commented on code/game/turfs/turf.dm
> +	//QOL feature, clicking on turf can toogle doors
```suggestion
	// QOL feature, clicking on turf can toogle doors
```

2021-05-14 11:36 UTC, ITCups commented
Также этот ПР

2021-05-14 14:01 UTC, ITCups commented
Если тут нечего исправлять кроме комментариев то принимайте ПР

2021-05-14 14:14 UTC, kreeperHLC commented
Плашку геймдиза видишь? Как только они одобрят, тогда и сможем принять

2021-05-15 06:47 UTC, ITCups commented
> 
> 
> Плашку геймдиза видишь? Как только они одобрят, тогда и сможем принять

Если честно я не понимаю как этот ПР является геймдизом когда возможность открывать двери в игре уже есть, я всего лишь добавляю QOL фичу которая облегчает это делать.
Это же касается и другого моего ПРа с указыванием.

2021-05-15 06:59 UTC, Doster-d commented
Логика простая - касается игрового опыта (ты его улучшаешь, правильно делаешь) надо пройти через геймдизайн.
Если это не понятно, то можно еще проще: фикс бага - не геймдизайн, новая фича (твой случай) - геймдизайн

2021-05-20 09:41 UTC, ITCups commented
где ваши ленивые геймдизы

2021-05-23 13:30 UTC, TobyThorne requested changes
This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +/turf/AICtrlClick(var/mob/user)
```suggestion
/turf/AICtrlClick(mob/user)
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +	var/obj/machinery/door/firedoor/FD = locate(/obj/machinery/door/firedoor) in src.contents
```suggestion
	var/obj/machinery/door/firedoor/FD = locate(/obj/machinery/door/firedoor) in contents
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in src.contents
```suggestion
	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in contents
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in src.contents
```suggestion
	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in contents
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +/turf/AIAltClick(var/mob/user)
```suggestion
/turf/AIAltClick(mob/user)
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in src.contents
```suggestion
	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in contents
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +/turf/AIShiftClick(var/mob/user)
```suggestion
/turf/AIShiftClick(mob/user)
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/ai.dm
> +	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in src.contents
```suggestion
	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in contents
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/cyborg.dm
> +/turf/BorgCtrlClick(var/mob/living/silicon/robot/user)
```suggestion
/turf/BorgCtrlClick(mob/living/silicon/robot/user)
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/cyborg.dm
> +/turf/BorgAltClick(var/mob/living/silicon/robot/user)
```suggestion
/turf/BorgAltClick(mob/living/silicon/robot/user)
```

2021-05-23 13:30 UTC, TobyThorne commented on code/_onclick/cyborg.dm
> +/turf/BorgShiftClick(var/mob/living/silicon/robot/user)
```suggestion
/turf/BorgShiftClick(mob/living/silicon/robot/user)
```

2021-05-23 13:30 UTC, TobyThorne commented on code/game/turfs/turf.dm
> +	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in src.contents
```suggestion
	var/obj/machinery/door/airlock/AL = locate(/obj/machinery/door/airlock) in contents
```

2021-05-23 13:30 UTC, TobyThorne commented on code/game/turfs/turf.dm
> +	var/obj/machinery/door/firedoor/FD = locate(/obj/machinery/door/firedoor) in src.contents
```suggestion
	var/obj/machinery/door/firedoor/FD = locate(/obj/machinery/door/firedoor) in contents
```

2021-05-29 20:29 UTC, ITCups commented
Давайте пацаны, последний ПР остался.

2021-05-29 20:42 UTC, TobyThorne approved these changes
похуй

2021-05-31 07:45 UTC, igorsaux approved these changes

2021-05-31 10:40 UTC, merged