Ballistics SFX extended
ChaoticOnyx/OnyxBay pull request #5200
Opened 2021-05-19 16:57 UTC by Tsurupeta

Добавил звуков пушечкам, пофиксил воспроизведение звуков выпадения гильз, изменил звуки выстрелов некоторого оружия и добавил немного анимаций к выпадающим патронам.

<details>
<summary>Чейнджлог</summary>

```yml
🆑 [Tsurupeta]
soundadd: Передёргивание затвора 14.5мм АМке и немного изменённый звук выстрела.
soundadd: Звуки открытия и закрытия затвора пулемёта L6 SAW вместе с новым звуком выстрела.
soundadd: Добавлены пара звуков для падающих гильз.
soundadd: Добавлены новые звуки выстрела из винтовки калибра 5.56.
soundadd: Добавлены новые звуки выстрела для револьверов калибра .38
soundadd: Добавлены звуки выпадающим патронам из дробовика и их правильная обработка.
soundadd: Добавлены новые звуки выстрела из винтовки калибра 7.62.
soundadd: Добавлены (переработаны) звуки выстрела для пистолетов калибра 9мм.
soundadd: Добавлен нормальный звук кручения барабана револьвера (он был в билдне, но не использовался).
soundadd: Добавлен щелчок огнестрельному оружию при отсутствии патронов (теперь там не click.ogg, а нормальный звук)
tweak: Гильзы при вылете из оружия теперь вместо падения под ноги отлетают на 1 тайл и крутятся.
tweak: Пофикшен один из звуков приглушённой стрельбы.
tweak: Большая часть звуков огнестрела перемещена из sound/weapons в sound/effect/weapons, потому что иметь звуки билда в разных сука папках - очень весело.
bugfix: Теперь гильзы, вылетая из оружия, действительно издают звуки при падении. Чудо. Магия. Игорь.
/🆑
```
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-19 17:00 UTC, Doster-d commented
[Tsurupeta] надо писать, если ты хочешь изменить имя отображаемое в ченджлоге (например изменить имя с гитхабовского на IE33), в данном случае его можно опустить

2021-05-19 17:00 UTC, Tsurupeta commented
Мне его удалить?

2021-05-19 17:00 UTC, Doster-d submitted a review, later dismissed

2021-05-19 17:01 UTC, Doster-d commented
> Мне его удалить?

Да, если ты, конечно же, не хочешь иметь имя в ченджлоге отличное от твоего имени в гитхабе.

2021-05-19 17:02 UTC, igorsaux approved these changes

2021-05-19 20:33 UTC, TobyThorne commented
Послушал новые звуки. Всё что могу сказать - крайне приятные. Особенно - звуки перезарядки для снайперки и пулемёта.
Единственное, что не зашло - sound/effects/weapons/gun/gun_empty.ogg. Слишком уж он тихий и похожий на клик мышки.
Вот тут нашёл более-менее годный: https://www.youtube.com/watch?v=IdcjQAAcLio

2021-05-19 21:44 UTC, igorsaux commented
fire_shotgun.ogg какой-то тоже приглушённый.

2021-05-19 21:59 UTC, igorsaux requested changes
![image](https://user-images.githubusercontent.com/55196698/118889902-7d6a6880-b906-11eb-827b-724ae210985c.png)

> gun/fire8.ogg

wtf такого файла нет (и кстати забыл нумерацию исправить)

![image](https://user-images.githubusercontent.com/55196698/118890030-abe84380-b906-11eb-8cf6-49791f25e76f.png)

2021-05-20 08:08 UTC, Tsurupeta commented
> vp78, MK .45, VP78 Wood, C45Sec и /sec/wood стреляют старым ганшотом, VP78 tactical - нормальным звуком

Они стреляют таким звуком потому что идёт оверрайд звуком ГАНШОТ.ОГГ у станпатронов. Ну и пофикшу, да. Забыл.

2021-05-20 09:40 UTC, Doster-d approved these changes

2021-05-20 12:55 UTC, igorsaux approved these changes

2021-05-21 15:36 UTC, closed without merging