Вернул Ghost обратно на место
ChaoticOnyx/OnyxBay pull request #5202
Opened 2021-05-19 20:29 UTC by HonkyDonky

***wycc1984 -> Adminhelp: админ гибни пожалуйста***

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Верб 'Ghost' вернулся обратно во вкладку OOC с некоторыми ограничениями. 
rscadd: Simple-animal и мозги (включая ММИ и позитронки) могут свободно гостаться.
rscadd: Люди же могут гостануться при условии достаточного урона в бессознательном состоянии (как и при Succumb), либо же находясь в крио. 
rscadd: ФБП также могут гостануться при условии, что у них села батарейка.
rscadd: Киборги могут гостануться при условии, что у них отсутствует/села/сломана батарейка, либо же находясь в хранилище для роботов.
rscdel: Убран скрытый верб 'Sucсumb'.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-19 20:41 UTC, TobyThorne commented on code/modules/mob/observer/ghost/ghost.dm
> +		to_world("cell yest")
cell njet

2021-05-19 20:44 UTC, TobyThorne commented
мне нра, но выпил суккумба - не нра
выбор между драматичным помиранием на руках у медиков и оставлением после себя овощного тела - круто
только проверки надо в нормальный вид у него привести, а то там кринж какой-то

2021-05-19 22:33 UTC, Wuattt commented
наконецто

2021-05-20 06:50 UTC, Shootnik01 commented
> мне нра, но выпил суккумба - не нра
> выбор между драматичным помиранием на руках у медиков и оставлением после себя овощного тела - круто
> только проверки надо в нормальный вид у него привести, а то там кринж какой-то

Можно же добавить верб суккумба

2021-05-20 07:13 UTC, TobyThorne commented
А у ИИ случаем гхост не вылезет? У них для этого есть Мув2Сторадж.

2021-05-20 07:22 UTC, HonkyDonky commented
> А у ИИ случаем гхост не вылезет? У них для этого есть Мув2Сторадж.

Не-а, не вылезет. У него этот прок [отнимается](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/code/modules/mob/living/silicon/ai/ai.dm#L111) до момента смерти.

2021-05-23 03:11 UTC, Doster-d submitted a review, later dismissed

2021-05-23 12:08 UTC, HonkyDonky commented
Поправил как попросили. Проверил локально - всё ок.

2021-05-29 14:40 UTC, MemoryDreams commented
А зачем? Гост же не просто так выпилили.

2021-05-29 14:42 UTC, kokokobold commented
Почитай ченжлог, он вернулся с удобными для всех ограничениями.

2021-05-31 11:53 UTC, Epicus7 requested changes
Ну и чейнжлог не соответствует действительности:

> rscadd: Верб 'Ghost' вернулся обратно во вкладку OOC с некоторыми ограничениями.

Он и раньше был там, с теми же ограничениями. Просто раньше ограничения убирали верб, а сейчас верб висит всегда, но из-за ограничений он перестает работать.

> rscadd: Люди же могут гостануться при условии достаточного урона в бессознательном состоянии (как и при Succumb), либо же находясь в крио.

Это не поменялось, оно и раньше так было.

Возможно свистопляска с добавлением/удалением верба не работала в каких-то условиях? Мб в крио? Ну тогда надо написать про пофикшенные баги, не про новый функционал..

2021-05-31 11:53 UTC, Epicus7 commented on code/modules/mob/living/living.dm
> +		verbs |= /mob/living/proc/ghost
А мертвым верб госта не нужен? Почему здесь только живым добавляется? Тут удалить строчку эту надо было, наверное?

2021-05-31 11:53 UTC, Epicus7 commented on code/modules/mob/living/silicon/pai/pai.dm
> +/mob/living/silicon/pai/Initialize(mapload, obj/item/device/paicard)
Как эти изменения связаны с ПРом?

2021-05-31 11:53 UTC, Epicus7 commented on code/modules/mob/observer/ghost/ghost.dm
> +			return TRUE
Может сделать верб 
/obj/item/organ/internal/brain/is_seriously_damaged

Или чот такое, чтобы всю эту магию с циферками внутри мозга держать? А не в каком-то левом коде ghost-а.

2021-05-31 11:57 UTC, HonkyDonky commented on code/modules/mob/living/living.dm
> +		verbs |= /mob/living/proc/ghost
Согласен, пропустил момент

2021-05-31 11:59 UTC, HonkyDonky commented on code/modules/mob/living/silicon/pai/pai.dm
> +/mob/living/silicon/pai/Initialize(mapload, obj/item/device/paicard)
Там немного смешная тема с тем, что у ПИИ свой аналог госта, потому у него и убирается Ghost, но выдача прока происходит в `mob/living/Initialize()`, а забираем то мы в `New()`. Но вообще это хрень, просто добавлю переменную, по которой будем смотреть, нужно ли вообще выдавать этот прок при инициализации.

2021-05-31 11:59 UTC, HonkyDonky commented on code/modules/mob/observer/ghost/ghost.dm
> +			return TRUE
ок

2021-05-31 12:56 UTC, Epicus7 approved these changes

2021-05-31 12:56 UTC, Epicus7 requested changes
Чейнжлог все еще не соответствует ПРу, я там выше писал конкретнее.

2021-05-31 17:21 UTC, Epicus7 approved these changes
Обновил чейнжлог

2021-05-31 17:25 UTC, TobyThorne approved these changes
репикус аппрувнул значит всё норм

2021-05-31 17:26 UTC, merged

2021-05-31 17:27 UTC, PlinHost commented on code/modules/mob/living/carbon/human/human.dm
> +	set hidden = 1
```suggestion
	set hidden = TRUE
```