Minor fixes
ChaoticOnyx/OnyxBay pull request #5203
Opened 2021-05-19 20:31 UTC by Zert0X

1)каттлпрод теперь можно врубить с стандарт девайс батарейкой(на 25 заряда)
2)из шахтёрского автомата нельзя забрать ID-карту с далёкого расстояния
3)д100 починен, и теперь выдаёт десятки от 0 до 90
4)ЛЮБОЙ пояс из лодаута теперь не сносит пда/стандартный рабочий пояс
close #2744
close #3987
close #4635
close #2376
<details>
<summary>Чейнджлог</summary>

```yml
🆑 Lovla aka Zert0X
bugfix: Каттлпрод теперь можно врубить с стандарт девайс батарейкой(на 25 заряда).
bugfix: Из шахтёрского автомата нельзя забрать ID-карту с далёкого расстояния.
bugfix: Д100 починен, и теперь выдаёт десятки от 0 до 90.
bugfix: Чемпионский пояс из лодаута теперь не сносит пда/стандартный рабочий пояс.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-21 13:46 UTC, TobyThorne requested changes

2021-05-21 13:46 UTC, TobyThorne commented on code/modules/mining/machine_vending.dm
> +					to_chat(usr, "<span class='warning'>You can't reach it.</span>")
```suggestion
					to_chat(usr, SPAN("warning", "You can't reach it."))
```

2021-05-22 08:20 UTC, igorsaux approved these changes

2021-05-23 12:58 UTC, TobyThorne approved these changes

2021-05-23 13:07 UTC, merged