Ballistics SFX extended - take 2
ChaoticOnyx/OnyxBay pull request #5229
Opened 2021-05-21 15:49 UTC by Tsurupeta

Добавил звуков пушечкам, пофиксил воспроизведение звуков выпадения гильз, изменил звуки выстрелов некоторого оружия и добавил немного анимаций к выпадающим патронам.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
soundadd: Передёргивание затвора 14.5мм АМке и немного изменённый звук выстрела.
soundadd: Звуки открытия и закрытия затвора пулемёта L6 SAW вместе с новым звуком выстрела.
soundadd: Добавлены пара звуков для падающих гильз.
soundadd: Добавлены новые звуки выстрела из винтовки калибра 5.56.
soundadd: Добавлены новые звуки выстрела для револьверов калибра .38
soundadd: Добавлены звуки выпадающим патронам из дробовика и их правильная обработка.
soundadd: Добавлены новые звуки выстрела из винтовки калибра 7.62.
soundadd: Добавлены (переработаны) звуки выстрела для пистолетов калибра 9мм.
soundadd: Добавлены новые звуки выстрела для 10мм ПП.
soundadd: Добавлен нормальный звук кручения барабана револьвера (он был в билдне, но не использовался).
soundadd: Добавлен щелчок огнестрельному оружию при отсутствии патронов (теперь там не click.ogg, а нормальный звук)
soundadd: Добавлены кастомные звуки вставки и вынимания магазина пистолетам, автоматам и пулемёту, а также звуки вынимания гильз из револьвера/дробовика и снайперской винтовки.
tweak: Гильзы при вылете из оружия теперь вместо падения под ноги отлетают на 1 тайл и крутятся.
tweak: Пофикшен один из звуков приглушённой стрельбы.
tweak: Большая часть звуков огнестрела перемещена из sound/weapons в sound/effect/weapons, потому что иметь звуки билда в разных сука папках - очень весело.
bugfix: Теперь гильзы, вылетая из оружия, действительно издают звуки при падении. Чудо. Магия. Игорь.
/🆑
```
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-21 15:55 UTC, Tsurupeta commented
Сбились пара вещей, сейчас снова фиксы пойдут.

2021-05-21 17:56 UTC, Tsurupeta commented
https://youtu.be/Yli_QglAbLc

2021-05-21 18:07 UTC, Tsurupeta commented
Ну и что с чейнджлогом, сука?

2021-05-21 18:28 UTC, TobyThorne commented
фиксирую конфликты

2021-05-21 18:39 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	burst_delay = 2
Вот эти штуки принадлежали базовому automatic и наследовались остальными.

2021-05-21 18:41 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/automatic.dm
> -/obj/item/weapon/gun/projectile/automatic/machine_pistol
Вот это зря, лучше пусть остаётся machine_pistol или prototype. Базовый automatic лучше сделать чисто техническим, для наследования от него переменных.

2021-05-21 18:43 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol
Тут тоже лучше сделать pistol чисто техническим, не для использования.

2021-05-21 18:43 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol/sec/vp78/tactical
ньюлайн

2021-05-21 18:44 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol/sec/vp78
Раз уж vp78 - подтип pistol, то лучше бы убрать sec в середине.

2021-05-21 18:49 UTC, TobyThorne commented on maps/overmap_example/bearcat/bearcat_loadouts.dm
>  	gear_tweaks += new /datum/gear_tweak/path(guns)
```suggestion
	gear_tweaks += new /datum/gear_tweak/path(guns)

```

2021-05-21 19:29 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol
Кольт остаётся кольтом, я просто переместил немного.

2021-05-21 22:10 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/automatic.dm
> -/obj/item/weapon/gun/projectile/automatic/machine_pistol
Сделал...

2021-05-21 22:10 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol
Кольт и пистол - разные пистолеты.

2021-05-22 04:52 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol
Так я и не про кольт, а про /obj/item/weapon/gun/projectile/pistol, ака .45 pistol, ака GP Mk5. Его надо бы вынести в отдельный тип (/pistol/c45 или что-то в этом духе), а сам /pistol оставить чисто техническим.

Как минимум потому что у него есть 
![image](https://user-images.githubusercontent.com/45202681/119214839-9f711000-baeb-11eb-9b79-90bfaf3f9edd.png)
а у его наследников - 
![image](https://user-images.githubusercontent.com/45202681/119214845-a9930e80-baeb-11eb-91fa-0ece32b4221a.png)

В итоге получаются смешные вещи. Тот же VP78 будет в update_icon() два раза менять иконку.

2021-05-22 10:38 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/pistol.dm
> +/obj/item/weapon/gun/projectile/pistol
Ок

2021-05-22 14:45 UTC, TobyThorne commented on code/modules/projectiles/guns/projectile/automatic.dm
> -	mod_handy = 1.0
Вот эти штуки лучше оставлять все вместе чтобы потом путаницы не было.

2021-05-22 15:15 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/automatic.dm
> -	mod_handy = 1.0
Вернул.

2021-05-22 15:43 UTC, TobyThorne requested changes

2021-05-22 15:43 UTC, TobyThorne commented on code/datums/trading/weaponry.dm
> +								/obj/item/clothing/accessory/holster									= TRADER_ALL)
Верни человеческие пробелы, табуляция в разных средах себя по-разному ведёт.

2021-05-22 16:02 UTC, Tsurupeta commented on code/datums/trading/weaponry.dm
> +								/obj/item/clothing/accessory/holster									= TRADER_ALL)
В других местах там были табы, это единственное место с пробелами. Действительн надо вернуть?

2021-05-22 16:05 UTC, TobyThorne commented on code/datums/trading/weaponry.dm
> +								/obj/item/clothing/accessory/holster									= TRADER_ALL)
В идеале - заменить бы все табы на пробелы. Уже три года этим занимаемся, а ещё много где осталось.

2021-05-23 02:30 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/revolver.dm
> -	fire_sound = 'sound/weapons/gun_revolversmall.ogg'
Это точно надо удалять?

2021-05-23 02:33 UTC, Doster-d commented on code/modules/projectiles/guns/projectile.dm
> +					if(istype(C, /obj/item/ammo_casing/shotgun))
Этот код можно переместить в ejectCasing добавив в этот прок поддержку выкидывания пуль.

2021-05-23 02:34 UTC, Doster-d approved these changes
Мне ок, но можно улучшить.

2021-05-23 08:23 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/revolver.dm
> -	fire_sound = 'sound/weapons/gun_revolversmall.ogg'
Точно. Оно наследует звук выстрела у revolver/detective.

2021-05-23 08:24 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile.dm
> +					if(istype(C, /obj/item/ammo_casing/shotgun))
Нет, нельзя, это два разных кода. EjectCasing выкидывает патрон из chambered, это опустошает просто оружие в целом.

2021-05-23 17:39 UTC, TobyThorne commented on code/datums/supplypacks/security.dm
> +	contains = list(/obj/item/weapon/gun/projectile/pistol/vp78 = 4)
о, вот за это - отдельное спасибо

2021-05-23 17:52 UTC, TobyThorne approved these changes
пробежался в который раз по коду, ничего что крашнуло бы сервер не заметил

2021-05-23 19:40 UTC, merged