Ещё один редизайн
ChaoticOnyx/OnyxBay pull request #5236
Opened 2021-05-21 20:03 UTC by igorsaux

<details>
<summary>Чейнджлог</summary>

```yml
🆑
imageadd: Редизайн интерфейса интегралок
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-22 06:11 UTC, TobyThorne approved these changes
код страшный, но результат красивый

2021-05-23 01:04 UTC, Doster-d requested changes
![image](https://user-images.githubusercontent.com/63081538/119244726-f8888480-bb7b-11eb-8617-fd0a3ce6c6ed.png)
Нет скролл бара для правой части (раньше он был), еще добавь скролл бар для левой части.

2021-05-23 01:08 UTC, Doster-d commented
Кнопки криво выделяются, кстати.

2021-05-23 15:52 UTC, Doster-d approved these changes
Игорь - крутой.

2021-05-23 20:20 UTC, TobyThorne approved these changes
код пролистал, бэкдоры оценил

очень сложный для восприятия хтмл, но да чёрт с ним, всё равно в обозримом будущем едва ли кто-то будет в корне переделывать интегралки

2021-05-23 20:22 UTC, igorsaux commented
> код пролистал, бэкдоры оценил
> 
> очень сложный для восприятия хтмл, но да чёрт с ним, всё равно в обозримом будущем едва ли кто-то будет в корне переделывать интегралки

ну надо будет на наноуи переписать

2021-05-23 20:22 UTC, merged