refactor(db)
ChaoticOnyx/OnyxBay pull request #5247
Opened 2021-05-22 23:55 UTC by 4310V343k

Легче всего ревувить по одному коммиту, но мазохистам разрешено смотреть изменения все сразу
1. Почти все запросы, а это все большие скл-запросы приведены к красивому виду. Никакой логики я *вроде как* не изменял
2. establish_[db|don_db|old_db]_connection() теперь учитывает конфиги при попытке проверки подключения, а значит не будет пытаться подключиться к несуществующим базам данных в обход конфига
3. Прок из п. выше расставлен во все места, где используются базы данных. Рантаймов о неподключенных БД больше не должно быть(их и не было, базы-то были)
2. Все DBConnection.NewQuery() заменены на sql_query()
3. Забудьте про sql_sanitize_text(), sanitizeSQL() и прочую лабуду, её я тоже заменил на sql_query()
4. Одиночные кавычки из скл-запросов убраны, что бы легче было читать код
5. ЭКСПЕРИМЕНТАЛЬНО: убраны decode_from_db() и encode_for_db() за не особой надобностью. Все бд и так в юникоде

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-23 15:17 UTC, Doster-d commented on code/game/jobs/whitelist.dm
> +	if(!establish_old_db_connection())
Может еще сообщение отправишь в log_to_dd?

2021-05-23 15:53 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
> +			[isnull(config.server_id) ? "" : " AND server_id = '$config.server_id'"]
```suggestion
			[isnull(config.server_id) ? "" : " AND server_id = '$server_id'"]
```

2021-05-23 15:57 UTC, 4310V343k commented on code/game/jobs/whitelist.dm
> +	if(!establish_old_db_connection())
```suggestion
	if(!establish_old_db_connection())
		error("Failed to connect to database in load_alienwhitelistSQL(). Reverting to legacy system.")
		log_misc("Failed to connect to database in load_alienwhitelistSQL(). Reverting to legacy system.")
		config.usealienwhitelistSQL = 0
		load_alienwhitelist()
		return
```

2021-05-23 15:58 UTC, 4310V343k commented on code/game/jobs/whitelist.dm
> +	if(!establish_old_db_connection())
```suggestion
	if(!establish_old_db_connection())
		error("Failed to connect to database in load_alienwhitelistSQL(). Reverting to legacy system.")
		log_misc("Failed to connect to database in load_alienwhitelistSQL(). Reverting to legacy system.")
		config.usealienwhitelistSQL = 0
		load_alienwhitelist()
		return
```

2021-05-23 15:58 UTC, 4310V343k commented on code/game/jobs/whitelist.dm
> +	if(!establish_old_db_connection())
Можно так сделать в таком случае, как и во всех остальных (админы, баны) "конфиглоадерах"

2021-05-23 16:38 UTC, Epicus7 submitted a review, later dismissed

2021-05-23 16:46 UTC, Epicus7 commented
Нужно потестировать локально

2021-05-26 08:22 UTC, Zert0X requested changes

2021-05-26 08:22 UTC, Zert0X commented on code/modules/admin/DB ban/functions.dm
BRUH, запрос в базу не отправляется если выбрать галочку match, из-за чего невозможно находить любой параметр польностью его не зная

2021-05-26 09:44 UTC, PlinHost commented on code/game/jobs/whitelist.dm
> +/proc/load_alienwhitelistSQL()	if(!establish_old_db_connection())
```suggestion
/proc/load_alienwhitelistSQL()
```

2021-05-26 11:07 UTC, 4310V343k commented on code/game/jobs/whitelist.dm
> +/proc/load_alienwhitelistSQL()	if(!establish_old_db_connection())
Пожилые быстрофиксы

2021-05-26 11:26 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
Не понял предъявы

2021-05-26 11:28 UTC, Doster-d commented on code/modules/admin/DB ban/functions.dm
Ты не можешь по базе искать по сикею, не можешь разбанивать

2021-05-26 12:11 UTC, Zert0X commented on code/modules/admin/DB ban/functions.dm
По сикею можешь, но по полному, если поставить галочку match, то нихера не можешь

2021-05-26 15:39 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
Да, ошибку понял. Вечером исправлю

2021-05-26 21:17 UTC, Zert0X commented on code/modules/admin/DB ban/functions.dm
> +				query_arg_list = list(playerckey = "%" + playerckey + "%", adminckey = "%" + adminckey + "%", playerip = "%" + playerip + "%", playercid = "%" + playercid + "%")
Непойму зачем дважды % приписывать, и одного в конце достаточно должно быть

2021-05-26 22:08 UTC, 4310V343k commented on code/modules/admin/DB ban/functions.dm
> +				query_arg_list = list(playerckey = "%" + playerckey + "%", adminckey = "%" + adminckey + "%", playerip = "%" + playerip + "%", playercid = "%" + playercid + "%")
% в MariaDB как .* в regex
https://mariadb.com/kb/en/like/
Любое кол-во любых символов в начале и то же самое в конце, раньше же было только в конце

2021-05-26 22:12 UTC, Epicus7 approved these changes

2021-05-26 22:17 UTC, Doster-d approved these changes
Ну, вроде, кукожа нет.

2021-05-26 23:50 UTC, Zert0X approved these changes

2021-05-26 23:50 UTC, Zert0X commented
Умирать так с песней

2021-05-27 04:38 UTC, merged