Removes ugly outdated lighting
ChaoticOnyx/OnyxBay pull request #5316
Opened 2021-05-30 00:52 UTC by TobyThorne

Порт нового освещения с Бея. Больше настроек, отключение софтдарка, все дела.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-30 00:58 UTC, TobyThorne commented
Тёмные страшные места ещё более тёмные и страшные.
![image](https://user-images.githubusercontent.com/45202681/120088625-63a20000-c114-11eb-898d-c5503abbdd5d.png)
![image](https://user-images.githubusercontent.com/45202681/120088629-68ff4a80-c114-11eb-8eb2-b8474b8fb809.png)

2021-05-30 01:00 UTC, DarkHunter7756 commented
RTX on

2021-05-30 01:24 UTC, Doster-d commented on code/game/gamemodes/cult/cult_structures.dm
>  	spawnable=list(
```suggestion
	spawnable = list(
```

2021-05-30 01:24 UTC, Doster-d commented on code/game/gamemodes/cult/cult_structures.dm
>  	spawnable=list(
```suggestion
	spawnable = list(
```

2021-05-30 12:12 UTC, Wuattt commented
темнота стала лучше, только свет через стены всё равно остался

2021-05-30 12:15 UTC, TobyThorne commented
Попробую портировать освещение с ТГ. Оно и выглядит лучше, и позволяет делать очень много весёлых штук вроде направленного света, и даёт ОГРОМНЫЙ буст производительности. 
Если не получится - придётся остановиться на этом.

2021-05-30 13:11 UTC, TobyThorne commented
Короче, порт ТГсвета - работа на очень долгое время. Объём работы гигантский. Когда-нибудь я это всё же проверну, но пока что лучше это, чем ничего. Сам ПР ещё немного потвикаю чтобы смотрелось приятнее.

2021-05-30 16:24 UTC, TobyThorne commented
Вручную подкрутил кучу значений, выглядит приятно.
Если вкратце:
- Никакого софтдарка, ходящий в полной темноте персонаж не видит абсолютно ничего и может ориентироваться только на ощупь (через ПКМ);
- Мелкие источники света типа ПДА и зажигалок позволяют с хоть каким-то комфортом ходить по темноте, но полноценный обзор не дают;
- В шахтах без света проще сразу повеситься;
- Цветное освещение работает великолепно, диско-машина в баре coming soon;

2021-05-30 16:28 UTC, MACTEP-ABATAP commented
А ПКМ на какую дистанцию работает?
Или он так же на весь экран?

2021-05-30 16:31 UTC, TobyThorne commented
> А ПКМ на какую дистанцию работает?
> Или он так же на весь экран?

Как и сейчас. В полной темноте - на один тайл вокруг персонажа.

2021-05-31 17:09 UTC, igorsaux approved these changes, later dismissed
Вроде работает

2021-05-31 17:13 UTC, Doster-d requested changes

2021-05-31 17:13 UTC, Doster-d commented on code/game/objects/items/weapons/candle.dm
> +		visible_message("<span class='notice'>\The [user] lights the [name].</span>")
СПАН.

2021-05-31 17:14 UTC, TobyThorne commented on code/game/objects/items/weapons/candle.dm
> +		visible_message("<span class='notice'>\The [user] lights the [name].</span>")
```suggestion
		visible_message(SPAN("notice", "\The [user] lights the [name]."))
```

2021-05-31 17:28 UTC, HonkyDonky approved these changes
Что может произойти плохого?

2021-05-31 17:30 UTC, Doster-d approved these changes
Что может пойти так?

2021-05-31 17:30 UTC, TobyThorne commented
Пезда всему.

2021-05-31 17:31 UTC, merged