fix(wizard) Teleportation spell
ChaoticOnyx/OnyxBay pull request #5330
Opened 2021-05-30 18:15 UTC by Zert0X

Маги <del>заново</del> открыли магию телепортации
<details>
<summary>Чейнджлог</summary>

```yml
🆑 Lovla aka Zert0X
bugfix: Маг теперь может телепортироваться через спелл телепорта
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-05-30 19:06 UTC, TobyThorne requested changes

2021-05-30 19:06 UTC, TobyThorne commented on code/modules/spells/spell_code.dm
> +
а можно пожалуйста просто оверрайднуть check_valid_targets() у /spell/area_teleport, а не городить вот это вот всё пожалуйста спасибо

2021-05-30 19:07 UTC, Zert0X commented on code/modules/spells/spell_code.dm
> +
бля а ведь идея

2021-05-31 16:23 UTC, TobyThorne approved these changes
ну пох главное чтоб работало

2021-05-31 16:34 UTC, HonkyDonky approved these changes

2021-05-31 17:03 UTC, merged