Removes as much changeling-related issues as I can find
ChaoticOnyx/OnyxBay pull request #5358
Opened 2021-06-01 17:19 UTC by TobyThorne

Ёбаный рот этого казино.

После открытия ПРа можно накатывать это и без ревью, ибо невозможно сделать код Фили хуже, чем он есть.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-01 17:20 UTC, Doster-d commented
Ебать! Это почти дохуя!

2021-06-01 17:20 UTC, TobyThorne commented
Fuck! This is fucking

2021-06-01 17:23 UTC, DarkHunter7756 commented
Ебать! Це майже дохуя!

2021-06-01 17:39 UTC, kreeperHLC commented
Cazzo! Questo è quasi un casino!

2021-06-01 17:39 UTC, kreeperHLC approved these changes, later dismissed

2021-06-01 17:42 UTC, Doster-d commented
Классно драфт аппруваем
:kek:

2021-06-01 17:44 UTC, kreeperHLC commented
> Классно драфт аппруваем
> :kek:

Так в этом и смысл

2021-06-02 09:41 UTC, TobyThorne commented
Хрен его знает, вроде уже выглядит более-менее. Что чинится, а что чинится **в теории** - перечислять не буду. Сам уже забыл. Но, по крайней мере, это говно теперь хоть как-то отсортировано, порезано количество копипасты и в целом если что-то сломается - это будет проще чинить.

2021-06-02 10:05 UTC, igorsaux requested changes

2021-06-02 10:05 UTC, igorsaux commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
Третьим аргументом у `visible_message` должен быть рендж

2021-06-02 10:05 UTC, igorsaux commented on code/game/gamemodes/changeling/helpcode.dm
> +	"<span class='italics'>You hear organic matter ripping and tearing!</span>")
И здесь

2021-06-02 10:07 UTC, TobyThorne commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
Не-а, у мобов он переназначен.
![image](https://user-images.githubusercontent.com/45202681/120462316-a1c14d00-c3bc-11eb-843d-e24417ab5943.png)

2021-06-02 10:10 UTC, igorsaux commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
А прок вызывается не у моба

2021-06-02 10:11 UTC, igorsaux commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
![image](https://user-images.githubusercontent.com/55196698/120462962-176cef00-c3a4-11eb-92ad-3f5c167eeea6.png)

2021-06-02 10:12 UTC, TobyThorne commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
А дедфилю рот ебал. Сейчас поправлю.

2021-06-02 10:12 UTC, igorsaux commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
Ну и голые спаны на макросы мб поменять

2021-06-02 10:26 UTC, TobyThorne commented on code/game/gamemodes/changeling/helpcode.dm
> +		"<span class='italics'>You hear organic matter ripping and tearing!</span>")
поп равил

2021-06-02 13:59 UTC, TobyThorne commented
Исправил отращивание генками протезов. Revive() и rejuvenate() - огромная куча лапши, надо будет в будущем зарефакторить. Но пока - работает и ладно.

2021-06-02 15:56 UTC, igorsaux requested changes
В стазисе можно полетать гостом

2021-06-02 15:56 UTC, igorsaux commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +			if(E.organ_tag == BP_R_HAND || E.organ_tag == BP_L_HAND || E.organ_tag == BP_R_FOOT || E.organ_tag == BP_L_FOOT || E.is_stump())
Проверку бы на протезы сюда...

2021-06-02 16:42 UTC, TobyThorne commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +			if(E.organ_tag == BP_R_HAND || E.organ_tag == BP_L_HAND || E.organ_tag == BP_R_FOOT || E.organ_tag == BP_L_FOOT || E.is_stump())
ща воткнём

2021-06-02 21:33 UTC, TobyThorne commented
- Добавлена проверка на протезы при перемещении биоструктуры;
- Исправлено появление мозгом в космосе при попытке перезайти в тело после смерти биоструктуры;
- Исправлен баг, не позволявший превратиться в хэдкраба, если биоструктура была выдрана из отрезанной конечности. Исправлено крайне костыльным способом, но я испробовал абсолютно все адекватные способы, что мог придумать. В определённых условиях буонд попросту отказывается нормально обновлять вёрбы.

2021-06-03 11:59 UTC, MrMagick2104 commented
К слову, до обновления у генокрадов точно некорректно работала пассивная регенерация (aka changeling_rapid_heal()): если случилась такая ситуация, что у человека полное здоровье (например, при включении заранее), то регенерация не лечила полученный далее урон, при этом не завершаясь (т.е. её можно выключить вёрбом тоггла) и не уведомляя игрока о том, что регенерация завершилась.

2021-06-03 18:14 UTC, igorsaux approved these changes

2021-06-03 18:15 UTC, Doster-d approved these changes

2021-06-03 18:16 UTC, merged