Rust
ChaoticOnyx/OnyxBay pull request #5382
Opened 2021-06-03 02:56 UTC by Pl3aseJust3ndMySuffering

Почти полный порт поля с бея, подчистил за собой говно и увеличил энерговыработку реактора(1 мегаватт на предельной температуре - смешно за такую цену по компонента и исследованиям), гиротрон теперь можно собрать(Почему им можно а нам нельзя?)

<details>
<summary>Чейнджлог</summary>

```yml
🆑 [Pl3aseJust3ndMyPain]
bugfix: У реактора RUST теперь есть видимое поле, гиротрон теперь можно собрать. Так же увеличена энерговыработка.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-03 03:00 UTC, Pl3aseJust3ndMySuffering commented
Кхм, подлива вышла.

2021-06-03 03:22 UTC, Pl3aseJust3ndMySuffering commented
![image](https://user-images.githubusercontent.com/82706228/120581797-184d6180-c434-11eb-9249-c3e7dd779fe4.png)

2021-06-03 05:16 UTC, TobyThorne requested changes

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +			var/temp_mod = ((plasma_temperature-5000)/20000)
```suggestion
			var/temp_mod = (plasma_temperature - 5000) / 20000
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +			use_range = light_min_range + ceil((light_max_range-light_min_range)*temp_mod)
```suggestion
			use_range = light_min_range + ceil((light_max_range - light_min_range) * temp_mod)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +			use_power = light_min_power + ceil((light_max_power-light_min_power)*temp_mod)
```suggestion
			use_power = light_min_power + ceil((light_max_power - light_min_power) * temp_mod)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/ChangeFieldStrength(var/new_strength)
```suggestion
/obj/effect/fusion_em_field/proc/ChangeFieldStrength(new_strength)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/AddEnergy(var/a_energy, var/a_plasma_temperature)
```suggestion
/obj/effect/fusion_em_field/proc/AddEnergy(a_energy, a_plasma_temperature)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/AddParticles(var/name, var/quantity = 1)
```suggestion
/obj/effect/fusion_em_field/proc/AddParticles(name, quantity = 1)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/RadiateAll(var/ratio_lost = 1)
```suggestion
/obj/effect/fusion_em_field/proc/RadiateAll(ratio_lost = 1)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/change_size(var/newsize = 1)
```suggestion
/obj/effect/fusion_em_field/proc/change_size(newsize = 1)
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
>  	if( ((newsize-1)%2==0) && (newsize<=13) )
```suggestion
	if(((newsize - 1) % 2 == 0) && (newsize <= 13))
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +		var/list/produced_reactants = new/list
```suggestion
		var/list/produced_reactants = list()
```

2021-06-03 05:16 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/bullet_act(var/obj/item/projectile/Proj)
```suggestion
/obj/effect/fusion_em_field/bullet_act(obj/item/projectile/Proj)
```

2021-06-03 05:21 UTC, Doster-d requested changes

2021-06-03 05:21 UTC, Doster-d commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/update_light_colors()
Проверку на то, что объект существует.

2021-06-03 06:47 UTC, Pl3aseJust3ndMySuffering commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/update_light_colors()
@Doster-d
Подскажи, как это сделать. Или просто предложи код как сделал Тоби.

2021-06-03 10:29 UTC, igorsaux requested changes
![image](https://user-images.githubusercontent.com/55196698/120630399-7a778800-c46f-11eb-912a-46927a4e5e53.png)
13 и 21

2021-06-03 14:31 UTC, Doster-d commented on code/modules/power/fusion/core/core_field.dm
> +/obj/effect/fusion_em_field/proc/update_light_colors()
```suggestion
/obj/effect/fusion_em_field/proc/update_light_colors()
	if(QDELETED(src))
		return
```

2021-06-12 13:27 UTC, kreeperHLC commented on code/modules/power/fusion/core/core_field.dm
> +			var/list/possible_reactions
var/list/produced_reactants = list() 
Буквально строкой выше

2021-06-16 11:34 UTC, Kexilex commented
А то я ищу-ищу этот гиротрон, а его в билде нет

2021-06-19 11:11 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +	var/light_max_range = 18
Светит дальше, чем за полный экран? Чего-то перебор.

2021-06-26 10:39 UTC, Pl3aseJust3ndMySuffering commented on code/modules/power/fusion/core/core_field.dm
> +	var/light_max_range = 18
Ладно.

2021-06-26 10:40 UTC, Pl3aseJust3ndMySuffering commented
@TobyThorne @kreeperHLC 
Ревью

2021-06-26 11:04 UTC, Doster-d commented
На

2021-06-26 20:53 UTC, TobyThorne commented on code/modules/power/fusion/core/core_field.dm
> +	var/light_max_range = 18
^ всё ещё this

2021-09-09 01:41 UTC, kcalbCube requested changes
поправь

2021-09-09 01:41 UTC, kcalbCube commented on code/modules/power/fusion/core/core_field.dm
> +	var/light_max_range = 18
ярко светит же

2021-09-09 01:41 UTC, kcalbCube commented on code/modules/power/fusion/core/core_field.dm
> +		set_light(min(use_power, 1), use_range / 6, use_range) //cap first arg at 1 to avoid breaking lighting stuff.
```suggestion
		set_light(min(use_power, 1), use_range / 6, use_range) // Cap first arg at 1 to avoid breaking lighting stuff.
```

2021-09-09 01:41 UTC, kcalbCube commented on code/modules/power/fusion/core/core_field.dm
> +			use_range = light_min_range + ceil((light_max_range - light_min_range) * temp_mod)
```
ceil((light_max_range - light_min_range) * temp_mod)
```
повторяется дважды в двух идущих подряд строчках кода.
вынеси.

2021-09-09 01:41 UTC, kcalbCube commented on code/modules/power/fusion/core/_core.dm
> +#define POWER_MODIFIER 5000
добавь #undef
и замени на FUSION_POWER_MODIFIER

2021-09-09 01:41 UTC, kcalbCube commented on code/modules/power/fusion/core/core_field.dm
> -#undef FUSION_HEAT_CAP
а это зачем

2021-10-17 13:12 UTC, Pl3aseJust3ndMySuffering commented
Автор проебал бранч с изменениями.

2021-10-17 13:12 UTC, closed without merging