Кубошприцераздающее
ChaoticOnyx/OnyxBay pull request #5383
Opened 2021-06-03 05:18 UTC by kcalbCube

Давно не хватало данной фичи, теперь можно делать шприцы с определенной дозировкой намного проще.

_к тому же это будет очень кстати при кубомедицине_

ChemMaster 3000 теперь может расфасовывать реагенты в шприцы с определенным количеством реагента. 
Холодильник  теперь может хранить в себе шприцы.
<details>
<summary>Чейнджлог</summary>

```yml
🆑 KcalbCube
tweak: ChemMaster 3000 now can dispense a syringes
tweak: Refrigerated Medicine Storage now can storage syringes
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-03 05:30 UTC, TobyThorne requested changes

2021-06-03 05:30 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Machinery.dm
> +				S.name = "[name] syringe"
```suggestion
				S.attach_label(null, null, name)
```

2021-06-03 05:30 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Machinery.dm
> +			var/name = sanitizeSafe(input(usr,"Name:", "Name your syringe!", "[reagents.get_master_reagent_name()] ([amount]u)"), MAX_NAME_LEN)
```suggestion
			var/name = sanitizeSafe(input(usr, "Name:", "Name your syringe!", "[reagents.get_master_reagent_name()] ([amount]u)"), MAX_NAME_LEN)
```

2021-06-03 05:30 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Machinery.dm
> +		else if (href_list["createsyrignes"])
```suggestion
		else if(href_list["createsyrignes"])
```

2021-06-03 06:57 UTC, Kexilex commented
Почему шприцы, когда есть инжекторы? Хлорку и с шприца можно ввести на харме, а кастомные инжекторы юнитов в 30 были бы очень кстати.

2021-06-03 07:48 UTC, kcalbCube commented
> Почему шприцы, когда есть инжекторы? Хлорку и с шприца можно ввести на харме, а кастомные инжекторы юнитов в 30 были бы очень кстати.

может ещё еган ассистентам в рюкзаке спавнить?

2021-06-04 07:14 UTC, kcalbCube commented
> Почему шприцы, когда есть инжекторы? Хлорку и с шприца можно ввести на харме, а кастомные инжекторы юнитов в 30 были бы очень кстати.

автоиньекторы можно через сьюты мгновенно колоть.

2021-06-21 06:21 UTC, kcalbCube commented
@TobyThorne уже 18 дней висит дизапрув

2021-06-21 10:56 UTC, PlinHost commented
Спавнилка шприцей не нужна.

2021-06-21 10:56 UTC, closed without merging