Кубоинфекции
ChaoticOnyx/OnyxBay pull request #5391
Opened 2021-06-03 17:10 UTC by kcalbCube

_И как, по данной нам благодати, имеем различные дарования, то, имеешь ли пророчество, пророчествуй по мере веры; имеешь ли служение, пребывай в служении; учитель ли, – в учении; увещатель ли, увещевай; раздаватель ли, раздавай в простоте; начальник ли, начальствуй с усердием; благотворитель ли, благотвори с радушием._

close #1024

Данный кубоПР разнерфивает инфекции, даже бафает.
Всё расписано в CL.

<details>
<summary>Чейнджлог</summary>

```yml
🆑KcalbCube
tweak: Изменены стадии инфекций: стадии стали намного короче, добавлена четвертая стадия(гангрена).
tweak: Каждая рана в отдельности заражает часть тела. Скорость заражения зависит от вида раны. Если хоть как-то продезинфицировать рану, то заражение прекратится.
tweak: Изменён алгоритм заражения внутренних органов заражённой частью тела: теперь в предпочтении инфицируется наименее заражённый орган, таким образом инфекция поражает больше органов, хоть и с меньшей силой.
bugfix: Убраны приколы с температурой 90 градусов у космонавтов, связанные с инфекцией.
tweak: Плюсы в наименованиях инфекции в сканнере изменены(было: Acute Infection+ стало: Acute Infection II)
tweak: Добавлена возможность прижечь часть тела для удаления части инфицированной ткани ценой ожогов.
tweak: Добавлены эффекты органам от инфекции: Инфицирование желудка будет показывать себя как несварение, инфицирование лёгких заставит вас кашлять и харкать кровью, инфицирование печени будет подавать звоночки в виде зуда и рвоты, сердце будет слишком быстро биться, глаза слепнуть, а мозг галлюцинировать и падать в оцепенение.
tweak: Инфекция лёгких и печени будет наносить им урон.
balance: Слегка ослаблены мыши, они дают достаточно сильную инфекцию и в теории могут привести к неприятному.
/🆑
```

</details>

Инфекции теперь опасны и будут досаждать ассистентам, ходящим с распоротым желудком. Может убить, если не оказать помощь в течении ~10-30 минут, в зависимости от ран.
Антибиотики все влияют на инфекции линейно. Это означает что эффект в чёткой зависимости от количества реагента. Для купирования гангрен и сепсиса всех органов часто будет требоваться вливать много спейсацилина.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-03 17:10 UTC, kcalbCube commented
ну чё пацаны, с богом.

2021-06-03 17:56 UTC, Shootnik01 commented
Звучит интересно, но посмотрим, что геймлиз скажет

2021-06-03 18:06 UTC, Doster-d requested changes
В целом неплохо.
Но бля, пиздец.

2021-06-03 18:06 UTC, Doster-d commented on code/modules/organs/external/_external.dm
> +		if (parent.germ_level < germ_level && !BP_IS_ROBOTIC(parent))
```suggestion
		if(parent.germ_level < germ_level && !BP_IS_ROBOTIC(parent))
```

2021-06-03 18:06 UTC, Doster-d commented on code/modules/organs/external/_external.dm
> +			if (parent.germ_level < INFECTION_LEVEL_ONE * 2 || prob(30 - antibiotics))
```suggestion
			if(parent.germ_level < INFECTION_LEVEL_ONE * 2 || prob(30 - antibiotics))
```

2021-06-03 18:06 UTC, Doster-d commented on code/modules/organs/organ.dm
> +	if (germ_level > 0 && germ_level < INFECTION_LEVEL_ONE/2 && prob(virus_immunity * 0.3))
```suggestion
	if(germ_level > 0 && germ_level < INFECTION_LEVEL_ONE/2 && prob(virus_immunity * 0.3))
```

2021-06-03 18:06 UTC, Doster-d commented on code/modules/organs/external/_external.dm
> +			if (W.germ_level > germ_level && prob(Interpolate(5, 100, 1 - antibiotics / 15)))
```suggestion
			if(W.germ_level > germ_level && prob(Interpolate(5, 100, 1 - antibiotics / 15)))
```

2021-06-03 18:06 UTC, Doster-d commented on code/modules/organs/external/_external.dm
> +	if (antibiotics < 15)
```suggestion
	if(antibiotics < 15)
```

2021-06-03 18:19 UTC, kcalbCube commented on code/modules/organs/organ.dm
> +
она есть в Process(), с робоорганами проки просчета инфекций не вызываются.

2021-06-04 11:49 UTC, kcalbCube commented
@Doster-d @TobyThorne ревью?

2021-06-04 12:53 UTC, kreeperHLC commented
> @Doster-d @TobyThorne ревью?

![image](https://user-images.githubusercontent.com/14943437/120804071-e5e35780-c54c-11eb-8578-9c587c0929f9.png)
Ждём, когда геймдизайнеры отклонят

2021-06-04 12:59 UTC, kcalbCube commented
А с чего бы им закрывать? #1024
Максимум поправят скорость инфекции.

2021-06-04 13:02 UTC, kreeperHLC commented
> А с чего бы им закрывать? #1024
> Максимум поправят скорость инфекции.

> _И как, по данной нам благодати, имеем различные дарования, то, имеешь ли пророчество, пророчествуй по мере веры; имеешь ли служение, пребывай в служении; учитель ли, – в учении; увещатель ли, увещевай; раздаватель ли, раздавай в простоте; начальник ли, начальствуй с усердием; благотворитель ли, благотвори с радушием._

^ 
Либо просто в козлов ПР превратится

2021-06-04 13:04 UTC, Doster-d commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
Проблема не решена.

2021-06-04 13:04 UTC, Doster-d commented on code/modules/organs/organ.dm
Проблема решена

2021-06-04 13:15 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
`
/obj/item/organ/external/proc/update_germs()

	if(BP_IS_ROBOTIC(src) || (owner.species && owner.species.species_flags & SPECIES_FLAG_IS_PLANT)) //Robotic limbs shouldn't be infected, nor should nonexistant limbs.
		germ_level = 0
		return

	if(owner.bodytemperature >= 170)	//cryo stops germs from moving and doing their bad stuffs
		//** Syncing germ levels with external wounds
		handle_germ_sync()

		//** Handle antibiotics and curing infections
		handle_antibiotics()

		//** Handle the effects of infections
		handle_germ_effects()

/obj/item/organ/external/proc/handle_germ_sync()
`

handle_germ_sync не будет вызван с неорганическим органом

2021-06-04 13:16 UTC, Doster-d commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
Are you sure in our build?

2021-06-04 13:23 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
Оно так было в исходном коде и не ломалось. Да и разве может что-то произойти во время работы проков? byond же однопоточный

2021-06-04 13:23 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
Было бы багом - сломалось бы давно.

2021-06-04 13:24 UTC, kcalbCube commented
> > А с чего бы им закрывать? #1024
> > Максимум поправят скорость инфекции.
> 
> > _И как, по данной нам благодати, имеем различные дарования, то, имеешь ли пророчество, пророчествуй по мере веры; имеешь ли служение, пребывай в служении; учитель ли, – в учении; увещатель ли, увещевай; раздаватель ли, раздавай в простоте; начальник ли, начальствуй с усердием; благотворитель ли, благотвори с радушием._
> 
> ^
> Либо просто в козлов ПР превратится

библейские цитаты теперь признак кубоПРа, в который куб влаживал душу.

2021-06-04 13:25 UTC, Doster-d commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
Все равно добавь, безопасность наше все.
Я уже так поверил каперхуну, в итоге ты сам видишь, что произошло.

2021-06-04 13:31 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
добавил защиту

2021-06-04 13:31 UTC, Doster-d commented on code/modules/organs/external/_external.dm
>  /obj/item/organ/external/proc/handle_germ_sync()
Все, теперь я доволен.

2021-06-04 13:32 UTC, Doster-d approved these changes
Кринжа не заметил.
С первым нормальным ПРом!

2021-06-04 13:33 UTC, kcalbCube commented
![image](https://user-images.githubusercontent.com/43304650/120809307-42666700-c58d-11eb-9a03-febbda89579b.png)

2021-06-04 13:34 UTC, Doster-d requested changes
Мда, рано аппрувнул, кодстайл.

2021-06-04 14:20 UTC, kcalbCube commented
шизофренические выкрики бота устранены

2021-06-04 14:22 UTC, Doster-d approved these changes
![image](https://user-images.githubusercontent.com/63081538/120816422-6445f680-c559-11eb-95a3-6a8cf963c288.png)

2021-06-04 14:25 UTC, Doster-d approved these changes

2021-06-16 11:39 UTC, Kexilex commented
Отсутствие или долгая загрязнённость перчаток и курение влияют на заражение при операции?

2021-06-16 18:53 UTC, kcalbCube commented
> Отсутствие или долгая загрязнённость перчаток и курение влияют на заражение при операции?

загрязнённость перчаток как и раньше увеличивает их germ_level, т.е. количество микробов. Курение как связано?

2021-06-16 19:05 UTC, kcalbCube commented
@TobyThorne 
![image](https://user-images.githubusercontent.com/43304650/122277751-94ae6d00-cf29-11eb-986d-24e3759e11c2.png)

2021-06-16 19:06 UTC, TobyThorne commented
кто там
![image](https://user-images.githubusercontent.com/45202681/122277972-4b015a80-cf08-11eb-82c5-ddc961e8423c.png)

2021-06-16 19:14 UTC, kcalbCube commented
![image](https://user-images.githubusercontent.com/43304650/122279028-f0c5c100-cf2a-11eb-9418-7b50c36895d9.png)

2021-06-29 20:44 UTC, TobyThorne commented on code/modules/organs/external/_external.dm
> +			if(W.germ_level > germ_level && prob(Interpolate(5, 100, 1 - antibiotics / 15)))
```suggestion
			prob(Interpolate(your_ass))
```

Ничего не понятно, строк в ченжлоге - куча, конкретики - ноль. Можно хоть какие-то примеры, что делают все эти матемагические вычисления?

2021-06-29 20:49 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
> +			if(W.germ_level > germ_level && prob(Interpolate(5, 100, 1 - antibiotics / 15)))
Interpolate(5, 100, 1 - antibiotics / 15), очевидно, при уровне антибиотиков 15 будет 5, при 0 - 100, и все линейно с серыми зонами.

2021-06-29 20:51 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
> +			if(W.germ_level > germ_level && prob(Interpolate(5, 100, 1 - antibiotics / 15)))
max(5, 100 * (1 - antibiotics / 15)) почти то же самое, только будет разница когда antibiotics > 15

2021-06-30 04:48 UTC, kcalbCube commented
удалил две строчки из CL

2021-07-05 18:58 UTC, kcalbCube commented
Убрал почти все строки из CL

2021-07-05 19:07 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
> +			if(W.germ_level > germ_level && prob(Interpolate(5, 100, 1 - antibiotics / 15)))
я не хочу интерполировать my ass

2021-07-11 06:41 UTC, kcalbCube commented
здрась, педрилы. сепсис ждет.

2021-07-11 06:54 UTC, kcalbCube commented
@TobyThorne сепсис ждёт говорю.

2021-07-11 23:26 UTC, kcalbCube commented
а мастер-иссуй то с приоритетом
![image](https://user-images.githubusercontent.com/43304650/125212811-2fb12180-e2f3-11eb-8dee-9d7992f74fea.png)

2021-07-17 08:03 UTC, kcalbCube commented
@TobyThorne 43 дня прошло

2021-07-17 08:51 UTC, TobyThorne commented
> @TobyThorne 43 дня прошло

И? Жди ревью от геймдизайнеров.

2021-07-17 09:09 UTC, kcalbCube commented
> > @TobyThorne 43 дня прошло
> 
> И? Жди ревью от геймдизайнеров.

геймдизайнеры сказали что иссуй уже одобрен и нужно ждать ревью кодеров

2021-07-23 05:30 UTC, kcalbCube commented
@TobyThorne

2021-07-26 15:16 UTC, closed without merging

2021-07-26 15:20 UTC, HonkyDonky commented
Геймдизы закрыли ПР на проплаченный и одобренный иссуй. Что?

2021-07-28 12:23 UTC, kcalbCube commented
кубик бессмертен, тоби.

а про отсебятину пиздёж.

2021-08-01 01:16 UTC, kcalbCube commented
геймдизы, чё вам не нравится, я инфекции баффнул и адаптировал под игру
как я понимаю проблема в следующем:
- Добавлены эффекты органам от инфекции, инфекция лёгких и печени будет наносить им урон.
- Добавлена возможность прижечь часть тела для удаления части инфицированной ткани ценой ожогов.

если чё можно убрать, базара нет