Removes insanity from uplinks
ChaoticOnyx/OnyxBay pull request #5396
Opened 2021-06-03 22:35 UTC by TobyThorne

tl;dr Возвращаем старый аплинк на 12 кристаллов, перерабатываем арсенал.

- Запас кристаллов в аплинке понижен со 130 до классического значения в 12 штук. В теории, 130 штук дают большую гибкость при настройке цен, на практике же - делают эту самую настройку практически нереальной, уследить за всеми цифрами - тот ещё геморрой. Да и всякое мыло и галоши с патронами по 1-2 кристалла превращают всё в идиотию;
- Выбор большого аплинка (не встроенного в ПДА/радио) теперь не отнимает 10% от запаса ТК, а даёт три штуки бонусом. Почему штука, которую с собой таскать - занятие КРАЙНЕ палевное ещё и жрала ТК - я теряюсь в догадках;
- Цены предметов в аплинке изменены в соответствии с новым (на самом деле, старым) запасом. В среднем, всё стало дороже, ибо кристаллы теперь можно зарабатывать с помощью выполнения контрактов;
- Большая часть пушек в аплинке теперь доступна только нюкерам. У трейторов остаются: дартган, лазер для Рипли, мини-еган, денежная пушка, ионный пистолет, обрез, 9мм пистолет с глушителем, арбалет, .357 револьвер и С20р (за 12 кристаллов);
- Подредактированы награды за контракты. Они приносят меньше ТК, ибо сами ТК стали гораздо более ценными.

В целом, какую ситуацию имеем? Начальных кристаллов хватит на покупку любого предмета из аплинка. Но вот чтобы собрать себе какой-нибудь имбовый набор из флешдарка, термалов и двойного меча - придётся сначала фармить контракты.

Что ещё надо сделать до открытия ПРа:
- Привести цены к более-менее окончательному виду;
- Добавить новые предметы в аплинк (возможно, запилю job-specific шмоточки, но это не точно);
- Подкрутить цифры ТК в карго;

Что надо сделать в будущем:
- **Точно** добавить job-specific шмоточки;
- Возможно, добавить уникальные награды за контракты;
- Придумать что-то с СТД. Его покупка за ТК - что-то из разряда костылей;

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-04 04:42 UTC, DarkHunter7756 commented
> name = "Assassinate"	
reward = 2 // This is how expensive your life is, fellow NT employee

Не слишком ли мало? Учитывая трудозатраты на нормальное отыгранное убийство (а не тупой выпил пистолетиком) получить 2 ТК так себе. И почему кража крови стоит дороже, чем убийство? Получить образец крови можно банально диалогом. Может поднять до 3 ТК? Там уже более менее ценные предметы начинаются. 

В остальном весьма сбалансированный ПР, наконец-то превращающий трейторов из нюкеров 0.5 в именно что агентов.

2021-06-04 05:10 UTC, TobyThorne commented
> Не слишком ли мало? Учитывая трудозатраты на нормальное отыгранное убийство (а не тупой выпил пистолетиком) получить 2 ТК так себе.

Двоечка - награда за кривое убийство. Если отослать голову - будет уже 4.

> И почему кража крови стоит дороже, чем убийство? Получить образец крови можно банально диалогом. Может поднять до 3 ТК? Там уже более менее ценные предметы начинаются.

Получить нужно аж от трёх до шести образцов. В окружении ролькохантеров это провернуть - задача сложнее, чем убийство.

Хотя циферки ещё будут подкручиваться. Но всё же - стимул для трейторов выполнять задачи помимо убийств, если нужны лишние ТК.

2021-06-04 18:28 UTC, TobyThorne commented
Добавлены следующие предметы:
- Шарик-улиточка, 12 ТК.
- Синди-лента, вместо обычной изоленты. Стоит 1 ТК, гораздо быстрее заклеивает рты и глаза (пол-секунды против трёх у обычной).
- Энерго-барьер. Маленькое одноразовое устройство, при активации раскладывающееся в неподвижный, непроходимый барьер. Сложить обратно невозможно, только разрушить. При разрушении очень слабо взрывается. Стоит 1 ТК.
- Бомба-хамелеон. Работает схожим образом с хамелеон-голограммой. После сканирования предмета, облик которого примет бомба и активации кликом бомбу остаётся положить куда-нибудь, после чего взаимодействовать без взрыва с ней будет уже нельзя. При попытке поднятия она взорвётся через одну секунду, практически наверняка гиббнув поднявшего. Стоит 6 ТК.
- Граната с мэнхаками. Стоит 3 ТК, при активации спавнит пять мэнхаков. Они не лояльны к трейтору и будут пытаться порезать всё живое, что попадётся под руку.
- Сыворотка воскрешения. Стоит весь запас кристаллов аплинка, доступна только нюкерам. Воскрешает любого мёртвого моба. Одноразовая. 
- Энергетический кинжал. В обычном состоянии являет собой ручку и делает всё, что делает ручка - пишет, лежит за ухом, сидит в ПДА. В активном состоянии - мини-версия есворда, с половиной его урона и невозможностью блокировать выстрелы, но значительно повышенной скоростью атаки. Стоит 6 ТК (3 ТК для нюкеров).

Попутно добавил кучу описаний для предметов в аплинке.
А ещё перерисовал спрайты двойных есвордов в руках, теперь они используют те же цвета, что и одноручные.

2021-06-04 20:58 UTC, TobyThorne commented
- В аплинк добавлены **робастные** перчатки-хамелеоны. Значительно увеличивают урон от харма и урон по пойзу от дизарма при атаках без оружия. Стоят 4 ТК (2 ТК у нюкеров).
- Красным скафандрам убрано замедление. У обычных софтсьютов его нет, у нюкерских скафандров - нет. Значит и у этих его быть не должно.
- Синди-покеты в подогретом состоянии теперь содержат ещё и 5 единиц трика. 
- Награда за контракт на шпионаж уменьшена с 5 ТК до 3 ТК. Одного набора за 2 ТК достаточно для выполнения таких контрактов, так что он может принести 4 ТК прибыли.

2021-06-04 21:43 UTC, Shootnik01 commented
Может, коробочку с цианидом за 6 ТК?

2021-06-13 14:25 UTC, Pl3aseJust3ndMySuffering commented
Тоби, прекращай возвращать "Олдскул" и "Во всех билдах так и у нас пусть". Ты убиваешь уникальность билда, хватит. Вон лучше, мой ПР заревьювай

2021-06-13 15:00 UTC, TobyThorne commented
> Ты убиваешь уникальность билда.

Убиваем уникальность в виде гениальных фич от идиотов с бея? Не думаю, что это что-то плохое.

2021-06-16 07:14 UTC, TobyThorne commented
бот ты чё охуел

2021-06-18 13:37 UTC, Epicus7 submitted a review, later dismissed
Ребаланс, новые фичи и перенос файлов - это все лучше бы делать отдельными ПРами, а то получается помойка. В перенесенных файлах теперь никто никогда не узнает какие там были изменения.

2021-06-18 13:45 UTC, Doster-d requested changes

2021-06-18 13:45 UTC, Doster-d commented on code/datums/uplink/categories/ammunition.dm
> -	item_cost = 4
Не сломаем ли мы? Ты проверял эту штуку?

2021-06-18 13:45 UTC, Doster-d commented on code/datums/uplink/categories/devices and tools.dm
>  /datum/uplink_item/item/tools/std/buy(obj/item/device/uplink/U)
А это переместить

2021-06-18 14:11 UTC, TobyThorne commented on code/datums/uplink/categories/ammunition.dm
> -	item_cost = 4
А что ломать? У всех патронов теперь оно отдельно прописано, так надёжнее.

2021-06-18 14:13 UTC, TobyThorne commented on code/datums/uplink/categories/devices and tools.dm
>  /datum/uplink_item/item/tools/std/buy(obj/item/device/uplink/U)
Специально оставил над самим STD, дабы не перебивать идущие подряд датумы проками.

2021-06-18 14:23 UTC, Doster-d commented on code/datums/uplink/categories/ammunition.dm
> -	item_cost = 4
Аммо (именно этот датум) не бесплатным становится, верно?

2021-06-18 14:23 UTC, Doster-d commented on code/datums/uplink/categories/ammunition.dm
> -	item_cost = 4
Он не существует для выбора, верно?

2021-06-18 14:56 UTC, TobyThorne commented on code/datums/uplink/categories/ammunition.dm
> -	item_cost = 4
Он не существует для выбора, верно.

2021-06-18 14:57 UTC, igorsaux requested changes

2021-06-18 14:57 UTC, igorsaux commented on code/datums/uplink/categories/ammunition.dm
> -	item_cost = 4
Если эта переменная в конструкторе не инициализируется - тогда туда нужно ассерт поставить.

2021-06-18 16:45 UTC, igorsaux submitted a review, later dismissed

2021-06-18 16:46 UTC, Doster-d approved these changes

2021-06-18 20:17 UTC, igorsaux approved these changes
Эпикус хуйни не апрувнит

2021-06-18 20:18 UTC, merged