Прогрессбарное
ChaoticOnyx/OnyxBay pull request #5406
Opened 2021-06-04 09:24 UTC by kcalbCube

Данный ПР сдвигает прогрессбары вверх, когда они применяются к одному атому.
Например когда медик спамит гелем по всему телу, он увидит не один прогрессбар, а несколько.
Так же прогрессбары стали более плавными и смешной progessbar.dmi переименован в progressbar.dmi

<details>
<summary>Чейнджлог</summary>

```yml
🆑KcalbCube
tweak: Прогрессбары теперь сдвигаются вверх, когда они применены к одному объекту.
tweak: Прогрессбары теперь в два раза плавнее.
/🆑
```

</details>

Если два космонавта одновременно начнут что-то делать с одним объектом, то их прогрессбары будут всё равно сдвинуты вверх, из-за того что счётчик прогрессбара общий для всех прогрессбаров объекта.
Делать счётчик приватным для каждого космонавта мне показалось оверхедом, но если это понадобиться то я пофикшу.

![image](https://user-images.githubusercontent.com/43304650/120779219-35844c00-c56a-11eb-80d2-743d860ce036.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-04 09:42 UTC, kreeperHLC commented
Неужели это ПЕРВЫЙ НОРМАЛЬНЫЙ ПР ОТ КУБА?! Так и до аппрува козлов доберёмся

2021-06-04 09:47 UTC, kcalbCube commented
А как же мои три ПРа которые я в последние два дня выложил?

2021-06-04 15:40 UTC, Doster-d approved these changes

2021-06-04 17:09 UTC, TobyThorne commented
А не логичнее было бы привязать этажи прогрессбаров не к объектам, а к клиенту, который их видит?

2021-06-04 18:21 UTC, kcalbCube commented
да, так будет лучше.
@Doster-d @TobyThorne

2021-06-04 18:29 UTC, Doster-d approved these changes

2021-06-04 18:29 UTC, Doster-d commented on code/datums/progressbar.dm
> +/client/
```suggestion
/client
```

2021-06-04 18:29 UTC, Doster-d requested changes
Не та кнопка.

2021-06-04 18:30 UTC, Doster-d commented on code/datums/progressbar.dm
> +/client/
А вообще можно так сделать.
```suggestion
var/client/numProgressbars = 0
```

2021-06-04 18:30 UTC, Doster-d approved these changes

2021-06-12 13:06 UTC, kreeperHLC approved these changes

2021-06-12 13:31 UTC, merged