Removes lack of broken status bars in #5455
ChaoticOnyx/OnyxBay pull request #5476
Opened 2021-06-07 23:04 UTC by TobyThorne

#5455, но с легаси-статусбаром.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-07 23:14 UTC, Doster-d requested changes

2021-06-07 23:14 UTC, Doster-d commented on code/modules/client/client_procs.dm
>  	if (asset_cache_job && (asset_cache_job in completed_asset_jobs))
```suggestion
	if(asset_cache_job && (asset_cache_job in completed_asset_jobs))
```

2021-06-07 23:14 UTC, Doster-d commented on code/modules/client/client_procs.dm
>  			message_admins("<span class='adminnotice'>Panic Bunker: ([key] | age [player_age]) - attempted to connect. Redirected to [config.panic_server_name ? config.panic_server_name : config.panic_address
```suggestion
			message_admins(SPAN("adminnotice", "Panic Bunker: ([key] | age [player_age]) - attempted to connect. Redirected to [config.panic_server_name ? config.panic_server_name : config.panic_address]"))
```

2021-06-07 23:14 UTC, Doster-d commented on code/modules/mob/login.dm
> +	if (hotkey_mode == GLOB.PREF_YES)
```suggestion
	if(hotkey_mode == GLOB.PREF_YES)
```

2021-06-08 09:08 UTC, Zert0X requested changes
CodeStyle cop

2021-06-08 09:08 UTC, Zert0X commented on code/modules/mob/login.dm
>  	//set macro to normal incase it was overriden (like cyborg currently does)
```suggestion
	// set macro to normal incase it was overriden (like cyborg currently does)
```

2021-06-08 09:08 UTC, Zert0X commented on code/modules/client/client_procs.dm
>  		if(!holder && received_irc_pm < world.time - 6000) //Worse they can do is spam IRC for 10 minutes
```suggestion
		if(!holder && received_irc_pm < world.time - 6000) // Worse they can do is spam IRC for 10 minutes
```

2021-06-08 09:08 UTC, Zert0X commented on code/modules/client/client_procs.dm
>  	//search the href for script injection
```suggestion
	// search the href for script injection
```

2021-06-08 09:08 UTC, Zert0X commented on code/modules/client/client_procs.dm
> +			if(minute != topiclimiter[ADMINSWARNED_AT]) //only one admin message per-minute. (if they spam the admins can just boot/ban them)
```suggestion
			if(minute != topiclimiter[ADMINSWARNED_AT]) // only one admin message per-minute. (if they spam the admins can just boot/ban them)
```

2021-06-08 09:08 UTC, Zert0X commented on code/modules/client/client_procs.dm
>  		log_debug("## NanoUI, Subject [src]: " + html_decode(href_list["nano_err"]))//NANO DEBUG HOOK
```suggestion
		log_debug("## NanoUI, Subject [src]: " + html_decode(href_list["nano_err"])) // NANO DEBUG HOOK
```

2021-06-08 09:11 UTC, TobyThorne commented on code/modules/mob/login.dm
>  	//set macro to normal incase it was overriden (like cyborg currently does)
Когда-нибудь этот

2021-06-08 09:11 UTC, TobyThorne commented on code/modules/client/client_procs.dm
>  		if(!holder && received_irc_pm < world.time - 6000) //Worse they can do is spam IRC for 10 minutes
ёбаный линтер перестанет

2021-06-08 09:12 UTC, TobyThorne commented on code/modules/client/client_procs.dm
>  	//search the href for script injection
чекать то

2021-06-08 18:54 UTC, igorsaux approved these changes

2021-06-08 18:54 UTC, Doster-d approved these changes

2021-06-08 18:55 UTC, Zert0X approved these changes

2021-06-08 18:56 UTC, merged