feat(storyteller): add more roles to storyteller
ChaoticOnyx/OnyxBay pull request #5500
Opened 2021-06-10 02:21 UTC by Epicus7

Добавляем больше ролей в сторителлера. Поправил рантайм при переключении вклад панели управления сторителлером.

При спавне борера, мага и ниндзи сторителлер опрашивает гостов и игроков в лобби с соответствующим префенсом, хотят ли они быть ролью. Если игрок отклоняет или не отвечает в течение 10 секунд, то опрашивается следующий игрок.

Нужно еще допилить борерам перенос тушки КУДА-ТО - пока не придумал где их спавнить можно.

Еще при спавне из лобби остается висеть окно Declare из-за баги #5499.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавил сторителлеру возможность спавнить бореров, магов, ниндзю и вампиров.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-10 02:27 UTC, Epicus7 commented
DreamChecker-у не нравятся мои умные хаки :(

2021-06-17 09:18 UTC, Doster-d approved these changes

2021-06-18 20:35 UTC, TobyThorne commented on code/_helpers/input.dm
> +	spawn(timeout) del(src) // make this proc die if src dies
```suggestion
	spawn(timeout)
		del(src) // make this proc die if src dies
```

2021-06-18 20:35 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	if(!initial) request_player()
```suggestion
	if(!initial)
		request_player()
```

2021-06-18 20:36 UTC, Doster-d commented on code/_helpers/input.dm
> +	spawn(timeout) del(src) // make this proc die if src dies
А не лучше как сейчас?

2021-06-18 20:36 UTC, TobyThorne commented on code/modules/storyteller/characters/support.dm
> +		while(!result && triggers.len)
Охренеть, в буонде есть ду-вайлы?

2021-06-18 20:37 UTC, TobyThorne commented on code/_helpers/input.dm
> +	spawn(timeout) del(src) // make this proc die if src dies
Хз, код в одну строчку подкукоживает.

2021-06-18 20:39 UTC, Doster-d commented on code/_helpers/input.dm
> +	spawn(timeout) del(src) // make this proc die if src dies
Когда одна инструкция, то можно :wholesomecat:

2021-06-18 20:39 UTC, igorsaux commented on code/_helpers/input.dm
> +	spawn(timeout) del(src) // make this proc die if src dies
На одной строчке выглядит как вызов двух функции лол

2021-06-23 21:10 UTC, Doster-d requested changes

2021-06-23 21:10 UTC, Doster-d commented on code/modules/storyteller/characters/support.dm
> +		while(!result && triggers.len)
```suggestion
		while(!result && length(triggers))
```

2021-06-28 23:44 UTC, TobyThorne approved these changes
похуй

2021-07-03 13:39 UTC, igorsaux approved these changes
Бэкдоров не нашёл

2021-07-03 14:45 UTC, Doster-d approved these changes

2021-07-03 16:03 UTC, merged