Add objectives to vampire
ChaoticOnyx/OnyxBay pull request #5528
Opened 2021-06-11 15:38 UTC by Zert0X

1. Вампиру теперь выпадают задания;
2. Добавлены два новых задания:
    2.1 Вампиризировать человека;
    2.2 Создать N-e число гулей на станции;
3. Вампиру и было больно от святой воды;
 
<details>
<summary>Чейнджлог</summary>

```yml
🆑 Lovla aka Zert0X
rscadd: Вампиру теперь выпадают задания;
rscadd: Добавлено пару заданий специально для вампиров;
/🆑
```
</details>

close #5460

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-11 16:59 UTC, Epicus7 requested changes

2021-06-11 16:59 UTC, Epicus7 commented on code/game/antagonist/station/vampire.dm
> +			kill = 1
TRUE

2021-06-11 16:59 UTC, Epicus7 commented on code/game/antagonist/station/vampire.dm
> +	return
return лишний

2021-06-11 16:59 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> +// Vampire objectives
А го может вместо комментария в отдельный файл перенесем? code/game/gamemodes/vampire/vampire_objectives.dm

2021-06-11 17:01 UTC, Zert0X commented on code/game/gamemodes/objective.dm
> +// Vampire objectives
А го рефактор кода обжективов? Они у нас все сейчас в одном файле

2021-06-11 17:02 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +// Vampire objectives
Давай! Работай!

2021-06-11 17:02 UTC, Zert0X commented on code/game/gamemodes/objective.dm
> +// Vampire objectives
Отдельным ПРом:kek:

2021-06-11 17:03 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +// Vampire objectives
Этим и точка.

2021-06-11 17:09 UTC, Epicus7 commented on code/game/gamemodes/objective.dm
> +// Vampire objectives
Старые - давай отдельным ПРом. А новый код нет нужны в старую свалку сваливать

2021-06-11 18:13 UTC, Shootnik01 commented
Ву-ху!

2021-06-11 18:34 UTC, Epicus7 approved these changes

2021-06-11 18:51 UTC, igorsaux submitted a review, later dismissed

2021-06-12 07:38 UTC, TobyThorne commented on code/game/antagonist/station/thrall.dm
> +		return 0
```suggestion
		return FALSE
```

2021-06-12 07:38 UTC, TobyThorne commented on code/game/antagonist/station/thrall.dm
> +		return 1
```suggestion
		return TRUE
```

2021-06-12 13:07 UTC, kreeperHLC requested changes

2021-06-12 13:07 UTC, kreeperHLC commented on code/game/antagonist/station/vampire.dm
> +	switch(rand(1,100))
![image](https://user-images.githubusercontent.com/14943437/121776927-333c7600-cb98-11eb-9849-28a856c2b153.png)
Гений

2021-06-12 13:12 UTC, Zert0X commented on code/game/antagonist/station/vampire.dm
> +	switch(rand(1,100))
Обожаю код стайл

2021-06-15 15:52 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_objectives.dm
> +	if(GLOB.thralls.current_antagonists.len >= amount)
Имхо вампиров слишком много в режиме спавнится, по хорошему бы его переделать в мидраунд антага и закидывать по одному. Ибо два вампира которые друг другу никто, дичь. А обращённый тобою вампир может и помочь вай нот?

2021-06-15 15:53 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_objectives.dm
> +	if(GLOB.thralls.current_antagonists.len >= amount)
Плюс уже есть соответствующий иссуй
https://github.com/ChaoticOnyx/OnyxBay/issues/5471

2021-06-15 15:53 UTC, Doster-d commented on code/game/gamemodes/vampire/vampire_objectives.dm
> +	if(GLOB.thralls.current_antagonists.len >= amount)
Ну ок, если геймдизайнерам ок, то и мне ок.

2021-06-15 15:54 UTC, Doster-d approved these changes

2021-06-15 15:55 UTC, igorsaux approved these changes
Можно тестить в проде

2021-06-17 09:17 UTC, Doster-d commented
Merge

2021-06-17 18:34 UTC, kreeperHLC approved these changes

2021-06-18 20:20 UTC, merged