Medical improvments for vampires
ChaoticOnyx/OnyxBay pull request #5543
Opened 2021-06-12 18:09 UTC by Zert0X

1. Вампиры теперь могут отключать дыхание
2. Блад хил теперь лечит вирусы
<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Вампиры теперь могут отключать дыхание;
tweak: Блад хил теперь лечит вирусы;
/🆑
```

</details>

close #5463 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-12 18:13 UTC, igorsaux commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	set desc = "You choose whether or not to breathe."
И зачем это в проке

2021-06-12 18:55 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	set desc = "You choose whether or not to breathe."
![изображение](https://user-images.githubusercontent.com/42303535/121786505-ea50e580-cbc8-11eb-9051-59b5ee9262c3.png)
Ибо без этого выходит смешное

2021-06-15 15:41 UTC, Doster-d requested changes

2021-06-15 15:41 UTC, Doster-d commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		virus2 = list()
Проходи по вирусам в этом листе и вызывай .Cure

2021-06-15 16:03 UTC, Doster-d approved these changes

2021-06-15 16:04 UTC, igorsaux approved these changes

2021-06-17 09:17 UTC, Doster-d commented
Merge

2021-06-18 20:20 UTC, merged