Правильное название экстрактов в контрактах
ChaoticOnyx/OnyxBay pull request #5551
Opened 2021-06-13 09:53 UTC by Pl3aseJust3ndMySuffering

close #5492
<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak:Ядра метроидов в контрактах теперь называются правильно.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-13 09:56 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
>  	"the [station_name()] blueprints" =                 list(CONTRACT_STEAL_OPERATION, /obj/item/blueprints),
Пофикси еще это, поищи GLOB.using_map.что-то там в этом коде, найдешь правильное название мапыь

2021-06-13 10:02 UTC, Pl3aseJust3ndMySuffering commented on code/game/gamemodes/traitor/contracts.dm
>  	"the [station_name()] blueprints" =                 list(CONTRACT_STEAL_OPERATION, /obj/item/blueprints),
Хорошо, займусь

2021-06-13 10:46 UTC, Doster-d requested changes
Фиксь

2021-06-13 10:46 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
>  	"the [station_name()] blueprints" =                 list(CONTRACT_STEAL_OPERATION, /obj/item/blueprints),
```suggestion
 	"the [GLOB.using_map.station_name()] blueprints" =                 list(CONTRACT_STEAL_OPERATION, /obj/item/blueprints),
```

2021-06-13 11:25 UTC, kreeperHLC requested changes
![image](https://user-images.githubusercontent.com/14943437/121805266-292b7d80-cc53-11eb-8b4f-bf72a0107960.png)
Вряд ли так должно быть

2021-06-13 11:26 UTC, Doster-d commented
> ![image](https://user-images.githubusercontent.com/14943437/121805266-292b7d80-cc53-11eb-8b4f-bf72a0107960.png)
> Вряд ли так должно быть

Это телефон, табы в помощь

2021-06-13 14:16 UTC, Pl3aseJust3ndMySuffering commented
@kreeperHLC @Doster-d Ревьюваем

2021-06-15 17:12 UTC, Doster-d approved these changes

2021-06-18 20:43 UTC, kreeperHLC approved these changes

2021-06-18 20:44 UTC, merged