fix(progressbars)
ChaoticOnyx/OnyxBay pull request #5574
Opened 2021-06-14 11:59 UTC by kcalbCube

Добавляет проверку на наличие клиента прогрессбарам.
(Бипски теперь смогут наручивать без рантаймов)

<details>
<summary>Чейнджлог</summary>

```yml
🆑KcalbCube
bugfix: Теперь мобы без клиента при использовании прогрессбаров не будут создавать рантаймы
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-14 11:59 UTC, kcalbCube commented
геймдизы не нужны

2021-06-14 12:19 UTC, Doster-d requested changes

2021-06-14 12:19 UTC, Doster-d commented on code/datums/progressbar.dm
> +	if(user.client)
```suggestion
	if(user?.client)
```

2021-06-14 16:09 UTC, Doster-d approved these changes

2021-06-15 15:16 UTC, igorsaux requested changes

2021-06-15 15:16 UTC, igorsaux commented on code/datums/progressbar.dm
>  	client.numProgressbars++
Почему нет проверки на nullable у client

2021-06-15 15:16 UTC, igorsaux commented on code/datums/progressbar.dm
> +	if(user?.client)
Зачем вешать прогрессбар не на игроков?
Тогда просто поставить ассерт user.client

2021-06-15 15:27 UTC, Doster-d requested changes

2021-06-15 15:27 UTC, Doster-d commented on code/datums/progressbar.dm
>  	client.numProgressbars++
```suggestion
 	client?.numProgressbars++
```

2021-06-15 15:33 UTC, igorsaux commented
Вообще какая-то шиза выходит. Надо или убрать флаг на прогрессбар в do_after или делать проверку на клиент и не добавлять его

2021-06-15 15:34 UTC, Doster-d commented
> Вообще какая-то шиза выходит. Надо или убрать флаг на прогрессбар в do_after или делать проверку на клиент и не добавлять его

Там не обнуляется количество прогресс баров.

2021-06-15 16:44 UTC, kcalbCube commented
пацаны всё исправил

2021-06-16 03:34 UTC, TobyThorne commented
>Теперь прогрессбары не будут сдвигаться при применении к нескольким объектам.

а у чём бля смысл

2021-06-16 04:03 UTC, kcalbCube commented
> > Теперь прогрессбары не будут сдвигаться при применении к нескольким объектам.
> 
> а у чём бля смысл

карголобби жалуется
шахтёрить неудобно

2021-06-16 06:04 UTC, TobyThorne commented
> карголобби жалуется
> шахтёрить неудобно

Неудобно видеть прогресс на каждом из тайлов? Какой-то мазохизм

2021-06-16 13:52 UTC, kcalbCube commented
> > карголобби жалуется
> > шахтёрить неудобно
> 
> Неудобно видеть прогресс на каждом из тайлов? Какой-то мазохизм

не-не, просто счётчик был один на клиента для всех атомов, из-за чего прогрессбары ставились выше чем должны при применении на нескольких атомах.

2021-06-16 13:55 UTC, Doster-d commented on code/datums/progressbar.dm
> +GLOBAL_VAR_INIT(progressbar_counter, 0)
Зачем это? Где это используется?

2021-06-16 14:23 UTC, kcalbCube commented on code/datums/progressbar.dm
> +GLOBAL_VAR_INIT(progressbar_counter, 0)
хохлы попортили.

2021-06-16 14:39 UTC, Doster-d approved these changes

2021-06-17 11:21 UTC, TobyThorne approved these changes
Чую, мы лезем в жопу.

2021-06-17 11:37 UTC, kcalbCube commented
@igorsaux игорь не порть статистику

2021-06-17 12:52 UTC, igorsaux approved these changes
Мы лезем в жопу, чую.

2021-06-18 20:29 UTC, merged