Разбираем-собираем: медбей
ChaoticOnyx/OnyxBay pull request #5589
Opened 2021-06-15 15:00 UTC by Doster-d

Теперь медбей можно полностью разобрать.
Теперь можно создать свою частную клинику.

Боди сканер стоит:
- хеилз анал икс 1
- сканнин модуль икс 3
- манипулятор икс 4

Операционный стол стоит:
- манипулятор икс 4

Крио камера:
- хеилз анал икс 1
- маттер бин икс 1
- сканнинг модуль икс 1
- манипулятор икс 3
- консоль скрин икс 1

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлены почти все платы для восстановления медбея.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-15 15:05 UTC, kreeperHLC commented
Фу говно, улучшений не завёз

2021-06-15 15:06 UTC, Doster-d commented
> Фу говно, улучшений не завёз

Тогда бы ПР назывался: разбираем-собираем-медбей.

2021-06-15 16:45 UTC, Doster-d commented
> Фу говно, улучшений не завёз

Исправил.
Теперь при улучшения операционного стола время раздевания может быть уменьшено до 1 секунды.

2021-06-15 16:46 UTC, kcalbCube commented
а карго?

2021-06-26 20:23 UTC, TobyThorne commented on code/game/machinery/OpTable.dm
> +	time_to_strip = clamp(default_strip - rating, 1 SECONDS, 5 SECONDS)
Го хотя бы до двух, а то жопа какая-то.

2021-06-26 20:34 UTC, Doster-d commented on code/game/machinery/OpTable.dm
> +	time_to_strip = clamp(default_strip - rating, 1 SECONDS, 5 SECONDS)
```suggestion
	time_to_strip = clamp(default_strip - rating, 2 SECONDS, 5 SECONDS)
```

2021-06-26 20:35 UTC, Doster-d commented on code/game/machinery/OpTable.dm
> +	time_to_strip = clamp(default_strip - rating, 1 SECONDS, 5 SECONDS)
Ок

2021-06-29 22:30 UTC, kreeperHLC requested changes
![image](https://user-images.githubusercontent.com/14943437/123875631-b4d72680-d942-11eb-9498-92c74426375e.png)

2021-07-02 15:07 UTC, TermService commented
а где зависимости от новых запчастей? А если ученые захотят улучшить?

2021-07-02 15:08 UTC, DarkHunter7756 commented
> а где зависимости от новых запчастей? А если ученые захотят улучшить?

Тем временем ресливер можно построить, но нельзя улучшить

2021-07-02 15:09 UTC, TermService requested changes

2021-07-02 15:09 UTC, TermService commented on code/game/machinery/adv_med.dm
> +				src.connected = null
а как мне привязать консольку к сканеру ингейм? Мне надо помнить в каком порядке их собирать чтобы это все прошло? непойдет.................

2021-07-02 15:38 UTC, Doster-d commented on code/game/machinery/adv_med.dm
> +				src.connected = null
Почему? Логично собрать машинерию, а потом консоль.

2021-07-02 16:42 UTC, Doster-d commented
Исправил.

2021-07-03 19:16 UTC, Doster-d commented
Добавлена химия.

2021-07-09 00:38 UTC, kcalbCube requested changes

2021-07-09 00:38 UTC, kcalbCube commented on .vscode/settings.json
> +	},
эт че

2021-07-09 00:38 UTC, kcalbCube commented on code/game/objects/items/weapons/circuitboards/machinery/medical.dm
> +							/obj/item/weapon/stock_parts/manipulator = 4,
чё так высоко

2021-07-09 00:43 UTC, Doster-d commented on .vscode/settings.json
> +	},
Это ущемление прав тех, кто использует инсайдерскую версию.

2021-07-09 00:44 UTC, Doster-d commented on code/game/objects/items/weapons/circuitboards/machinery/medical.dm
> +							/obj/item/weapon/stock_parts/manipulator = 4,
Не твое дело.

2021-07-09 00:46 UTC, Doster-d commented on .vscode/settings.json
> +	},
не инсайдерскую*

2021-07-09 00:51 UTC, kcalbCube commented on .vscode/settings.json
> +	"workbench.editorAssociations": [
хули вообще в разбираем-собираем изменения вскода

2021-07-09 00:52 UTC, Doster-d commented on .vscode/settings.json
> +	"workbench.editorAssociations": [
Пошел нахуй

2021-07-09 00:53 UTC, kcalbCube commented on .vscode/settings.json
> +	"workbench.editorAssociations": [
слёзки кап кап

2021-07-09 00:54 UTC, kcalbCube submitted a review, later dismissed

2021-07-23 14:02 UTC, Doster-d commented on code/modules/reagents/Chemistry-Machinery.dm
> +		beaker.forceMove(get_turf(src))
```suggestion
		beaker.forceMove(get_turf(src))
		beaker = null
```

2021-07-23 14:02 UTC, Doster-d commented on code/game/machinery/adv_med.dm
> +		connected.BSC = null
```suggestion
		connected.BSC = null
		connected = null
```

2021-07-23 14:19 UTC, Doster-d commented on code/game/machinery/adv_med.dm
> +		BSC.connected = null
```suggestion
		BSC.connected = null
		BSC = null
```

2021-07-23 14:19 UTC, Doster-d commented on code/game/machinery/OpTable.dm
> +				computer = null
```suggestion
```

2021-07-23 14:19 UTC, Doster-d commented on code/game/machinery/OpTable.dm
> +			if(computer.table)
```suggestion
			if(computer?.table)
```

2021-07-23 14:19 UTC, Doster-d commented on code/game/machinery/computer/Operating.dm
> +				table = null
```suggestion

```

2021-07-23 14:19 UTC, Doster-d commented on code/game/machinery/computer/Operating.dm
> +			if(table.computer)
```suggestion
			if(table?.computer)
```

2021-07-23 14:33 UTC, Doster-d reviewed
checkie check

2021-07-23 14:33 UTC, Doster-d commented on code/game/machinery/OpTable.dm
> +		if(computer?.table)
```suggestion
		if(!computer || computer?.table)
```

2021-07-23 14:33 UTC, Doster-d commented on code/game/machinery/adv_med.dm
> +		if(console?.connected)
```suggestion
		if(!console || console?.connected)
```

2021-07-23 14:33 UTC, Doster-d commented on code/game/machinery/computer/Operating.dm
> +		if(table?.computer)
```suggestion
		if(!table || table?.computer)
```

2021-07-23 14:38 UTC, HonkyDonky submitted a review, later dismissed

2021-07-23 20:35 UTC, TermService approved these changes

2021-07-23 20:35 UTC, TermService commented on code/game/machinery/adv_med.dm
> +/obj/machinery/bodyscanner/attackby(obj/item/W, mob/user as mob)
```suggestion
/obj/machinery/bodyscanner/attackby(obj/item/W, mob/user)
```

2021-07-23 20:35 UTC, TermService commented on code/game/machinery/adv_med.dm
> +/obj/machinery/body_scanconsole/attackby(obj/item/W, mob/user as mob)
```suggestion
/obj/machinery/body_scanconsole/attackby(obj/item/W, mob/user)
```

2021-07-23 20:35 UTC, TermService commented
В следующий раз пожалуйста обновляй кодстайл в файлах которых работаешь

2021-07-23 20:36 UTC, Doster-d commented on code/game/machinery/adv_med.dm
> +/obj/machinery/body_scanconsole/attackby(obj/item/W, mob/user as mob)
No!

2021-07-23 20:37 UTC, TermService approved these changes

2021-07-23 20:40 UTC, kreeperHLC approved these changes

2021-07-23 20:53 UTC, merged