Fix nullrod decultify of floor and reinforced walls
ChaoticOnyx/OnyxBay pull request #5627
Opened 2021-06-17 17:38 UTC by NefrNerf

- Удалил код который вообще не был использован, добавил возможность декультифицировать полы.
- Теперь после удара нуллродом по укрепленной стене культа она становиться обычной укрепленной, раньше превращалась в обычную.
- Для удобства перенес нуллрод в отдельный файл

#4978

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь нуллрод священника превращает укрепленные стены культистов в обычные укрепленные стены
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-19 11:15 UTC, TobyThorne requested changes

2021-06-19 11:15 UTC, TobyThorne commented on code/game/objects/items/weapons/melee/nullrod.dm
> +/obj/item/weapon/nullrod/attack(mob/M as mob, mob/living/user as mob)
```suggestion
/obj/item/weapon/nullrod/attack(mob/M, mob/living/user)
```

2021-06-19 11:17 UTC, TobyThorne commented
За исключением упомянутого выше - вроде норм. Хотя в идеале, конечно, было бы неплохо сохранять в культостенах и культополах оригинальные типы.

2021-06-19 11:22 UTC, NefrNerf commented
Пока не сильно понимаю как это сделать. Добавить в культостену переменную которая сохранит тип старой стены и при декультификации ее возвращать?

2021-06-20 06:49 UTC, NefrNerf commented
Блять, случайно удалил ветку, не знал что и пр закроется

2021-06-20 07:07 UTC, NefrNerf commented
Нет, похоже зафакапил полностью, лучше уже по нормальному сделаю и открою новый ПР

2021-06-20 07:07 UTC, closed without merging