Removes game-breaking bug from #5551
ChaoticOnyx/OnyxBay pull request #5642
Opened 2021-06-18 21:06 UTC by TobyThorne

#5551 двумя строчками наглухо убил билд. Очередной урок, что даже самые крошечные и незначительные на первый взгляд изменения (в особенности - от First Time Contributor Gang) надо тестировать.
![image](https://user-images.githubusercontent.com/45202681/122615912-314c4880-d0ab-11eb-9401-59f6bd0b8f91.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-18 21:07 UTC, igorsaux submitted a review, later dismissed

2021-06-18 21:08 UTC, Doster-d submitted a review, later dismissed

2021-06-18 21:11 UTC, igorsaux submitted a review, later dismissed

2021-06-18 21:12 UTC, Doster-d requested changes

2021-06-18 21:12 UTC, Doster-d commented on code/game/gamemodes/traitor/contracts.dm
> +	"a sample of slime extract" =                       list(CONTRACT_STEAL_SCIENCE, /obj/item/metroid_extract),
```suggestion
	"a sample of metroid extract" =                       list(CONTRACT_STEAL_SCIENCE, /obj/item/metroid_extract),
```

2021-06-18 21:12 UTC, igorsaux approved these changes

2021-06-18 21:12 UTC, Doster-d approved these changes

2021-06-18 21:14 UTC, merged

2021-06-19 22:18 UTC, kcalbCube commented
ничего себе уровень бекдуров