fix(adminpaper): fixes user access to admin fax
ChaoticOnyx/OnyxBay pull request #5669
Opened 2021-06-20 13:53 UTC by NefrNerf

Немного поправил копирование бумаги. Теперь отправленная по факсу бумага будет обычной а не админской.

fixes #5393 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь пользователь не может вызвать админский факс через редактирования письма с ЦК
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-20 15:30 UTC, kcalbCube reviewed
спасибо что поменял 0 на FALSE, 1 на TRUE и ничего об этом не сказал
а свою строчку кода одобряю, багов быть не должно

2021-06-23 20:42 UTC, kreeperHLC approved these changes

2021-06-23 20:46 UTC, Doster-d requested changes

2021-06-23 20:46 UTC, Doster-d commented on code/modules/paperwork/paper.dm
> +			spam_flag = FALSE
```suggestion
			spam_flag = TRUE
```

2021-06-23 20:46 UTC, Doster-d commented on code/modules/paperwork/paper.dm
> +				spam_flag = TRUE
```suggestion
				spam_flag = FALSE
```

2021-06-23 20:48 UTC, Doster-d requested changes

2021-06-23 20:48 UTC, Doster-d commented on code/modules/paperwork/paper.dm
> +		if(spam_flag == FALSE)
```suggestion
		if(!spam_flag)
```

2021-06-23 20:59 UTC, NefrNerf commented on code/modules/paperwork/paper.dm
> +		if(spam_flag == FALSE)
Исправил

2021-06-23 21:02 UTC, kreeperHLC approved these changes

2021-06-23 21:12 UTC, Doster-d approved these changes

2021-06-26 21:29 UTC, merged