Кличковое
ChaoticOnyx/OnyxBay pull request #5681
Opened 2021-06-21 02:44 UTC by MaxFreemen

Отныне любого корги, кроме Яна и Лизы, можно переименовать единожды, если взять животное на руки и выбрать команду "Name pet".

<details>
<summary>Чейнджлог</summary>

```yml
🆑MaxDornan
rscadd: Любому корги, кроме Яна и Лизы, можно дать кличку, взяв на руки и нажав опцию "Name pet".
/🆑
```

close #3890

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-21 03:14 UTC, kcalbCube requested changes
пиздец

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +
спасибо что удалил пробелы

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/holder.dm
> +/obj/item/weapon/holder/corgi/proc/rename()
почему прок опрашивает пользователя, а не верб? Может админ захочет через proc call переименовать?
сделай rename(new_name), а всё что ты тут понаписал в name_pet

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/holder.dm
>  /obj/item/weapon/holder/corgi
я всё же считаю что эту функцию нужно для всех симплов вводить.

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/holder.dm
> +			M.wasrenamed = 1
```suggestion
			M.wasrenamed = TRUE
```

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	renamable = 1
```suggestion
	renamable = TRUE
```

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	var/renamable
```suggestion
	var/renamable = FALSE
```

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	var/wasrenamed
```suggestion
	var/wasrenamed = FALSE
```

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	renamable = 1
```suggestion
```
не нужно

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	renamable = 0
```suggestion
	renamable = FALSE
```

2021-06-21 03:14 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	renamable = 0
```suggestion
	renamable = FALSE
```

2021-06-21 14:14 UTC, TobyThorne commented on code/modules/mob/holder.dm
> +			M.wasrenamed = 1
а зачем вообще переменная wasrenamed, если можно просто remamable = FALSE седалть

2021-06-21 18:27 UTC, Zert0X commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +
Такие иногда автоматически происходит

2021-07-12 23:12 UTC, MaxFreemen commented
Все сломалось, пересоздаю проект.

2021-07-12 23:12 UTC, closed without merging