Make goats great again v2.0
ChaoticOnyx/OnyxBay pull request #5683
Opened 2021-06-21 16:21 UTC by Zert0X

Возродил #4211
Все права принадлежат @MrPersival от награды за иссуй отказываюсь  

1. Добавлен шанс сбить с ног.
2. Если дать козлу перец, он впадет в рейджмод, в который, правда, и так может впасть время от времени. Задержка есть и так, за её время можно убежать.
3. Словарный запас увеличен.
4. Теперь с козла выпадает шкура при разделывании. В шкуре можно прорезать дырку для головы, и носить.
5. Доение уже было, не трогал.
6. Друиду в Monster Manual добавлен новый фамильяр - козел. Сбивает с ног с помощью magic missle, не сбивает при атаках.
<details>
<summary>Чейнджлог</summary>

```yml
🆑 MrPersival
rscadd: Козлы теперь могу сбивать с ног.
rscadd: Если дать козлу перец то произойдёт интересное.
rscadd: Козлы выучили пару новых слов.
rscadd: Добавлена шкура козла
rscadd: Козёл теперь есть как фамильяр у мага.
/🆑
```

</details>
close #1426

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-21 17:18 UTC, Doster-d approved these changes
Вроде неплохо, хорошая работа, Ловла

2021-06-21 17:21 UTC, Zert0X commented
та погоди куда, спрайтов для альтслимов ещё нет:kek:

2021-06-21 17:23 UTC, Doster-d commented
Спрайты для лохов, русские создают картинку в голове из описание.

2021-06-21 17:23 UTC, Doster-d requested changes
Спайты.

2021-06-24 18:25 UTC, Zert0X commented
Призываю своих собратьев по чулкокодерскому ордену!

2021-06-24 18:27 UTC, DarkHunter7756 commented
> Призываю своих собратьев по чулкокодерскому ордену!

Тебе никогда не получится замержить козлов. Иссуй проклят. Этот иссуй проложен козлами и козлы хранят его. Иссуй проклят.

2021-06-24 18:28 UTC, Zert0X commented
> 
> 
> > Призываю своих собратьев по чулкокодерскому ордену!
> 
> Тебе никогда не получится замержить козлов. Иссуй проклят. Этот иссуй проложен козлами и козлы хранят его. Иссуй проклят.

Это пр :kek:
Кому нужен тот иссуй если есть ПР!

2021-06-24 18:34 UTC, Doster-d commented
![Screenshot_20210624-213334-01.jpeg](https://user-images.githubusercontent.com/63081538/123315021-ea8ba200-d533-11eb-96ed-6ef1e4a71f53.jpeg)
Видимо это и есть та проблема с козлами

2021-06-24 18:41 UTC, Zert0X commented
Я твой рот труба шаталь
![H1fj](https://user-images.githubusercontent.com/42303535/123315849-da27f700-d534-11eb-8b70-cc9103af3a73.gif)

2021-07-02 15:17 UTC, TermService requested changes

2021-07-02 15:17 UTC, TermService commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 25, bullet = 10, laser = 0, energy = 40, bomb = 0, bio = 10, rad = 0)
energy=40
Защита уровня скафандров и некоторых РИГов ЕРТ, непойдет, но если геймдизайнеры не против то ладно

2021-07-02 15:17 UTC, TermService commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 25, bullet = 10, laser = 0, energy = 40, bomb = 0, bio = 10, rad = 0)
тоже самое что и выше

2021-07-02 15:55 UTC, Zert0X commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 25, bullet = 10, laser = 0, energy = 40, bomb = 0, bio = 10, rad = 0)
Отказано, иди читай оригинальный ПР, там сами гейдизы выставили такое значение

2021-07-31 16:20 UTC, Zert0X commented
![изображение](https://user-images.githubusercontent.com/42303535/127746063-c1d5bff6-e312-4345-8fbf-6be44b0e1c8a.png)
упс я дурной, я сломал...

2021-07-31 16:25 UTC, closed without merging