feat(trash): add dish stacks feature and refactoring
ChaoticOnyx/OnyxBay pull request #5684
Opened 2021-06-21 16:51 UTC by Oubifx

Добавил возможность стакать тарелки, глубокие тарелки, противни и лотки. Для них был создан базовый класс, по этому в любой момен можно добавить люблю посуду которую можно будет стакать (пока что до 5-ти, по нужде базовую функцию можно будет переделать). Исправил все пути для этой посуды, а так же изменил им имена на правильные: `snack_bowl > bowl`, `waffles > baking sheet`
![unknown](https://user-images.githubusercontent.com/24242919/122799104-025fed80-d2ca-11eb-8e62-7c897d5f4969.png)

close #5595 

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
rscadd: Добавлена возможность стакать тарелки и их разновидности 
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-21 17:04 UTC, kreeperHLC requested changes
В код особо не вглядывался, исправь сначала вот это

2021-06-21 17:04 UTC, kreeperHLC commented on code/game/objects/items/trash.dm
> +	var/obj/item/trash/dishes/old_icon_state = copytext("[icon_state]",1,-1) // suitable for different name lengths
```suggestion
	var/obj/item/trash/dishes/old_icon_state = copytext("[icon_state]", 1, -1) // suitable for different name lengths
```

2021-06-21 17:04 UTC, kreeperHLC commented on code/game/objects/items/trash.dm
> +		if((length(stack)+1) + length(dishestoadd) <= 5)
```suggestion
		if((length(stack) + 1) + length(dishestoadd) <= 5)
```

2021-06-21 17:04 UTC, kreeperHLC commented on code/game/objects/items/trash.dm
> +/obj/item/trash/dishes/attack_hand( mob/user as mob )
```suggestion
/obj/item/trash/dishes/attack_hand(mob/user as mob)
```

2021-06-21 17:04 UTC, kreeperHLC commented on code/game/objects/items/trash.dm
> +		if( user.get_inactive_hand() != src )
```suggestion
		if(user.get_inactive_hand() != src)
```

2021-06-21 17:04 UTC, kreeperHLC commented on code/game/objects/items/trash.dm
> +	..()
![image](https://user-images.githubusercontent.com/14943437/122800560-c037ab80-d2cb-11eb-9db6-51c89d7fe957.png)

2021-06-21 17:13 UTC, Doster-d requested changes

2021-06-21 17:13 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +	var/obj/item/trash/dishes/old_icon_state = copytext("[icon_state]",1,-1) // suitable for different name lengths
```suggestion
	var/old_icon_state = copytext(icon_state, 1, length(icon_state)-1) // suitable for different name lengths
```

2021-06-21 17:13 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +			dish.loc = src
```suggestion
			dish.forceMove(src)
```

2021-06-21 17:13 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +			to_chat(user, "<span class='warning'>The stack is too high!</span>")
```suggestion
			to_chat(user, SPAN("warning", "The stack is too high!"))
```

2021-06-21 17:13 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +		to_chat(user, "<span class='warning'>You remove the topmost [src] from your hand.</span>")
```suggestion
		to_chat(user, SPAN("warning", "You remove the topmost \the [src] from your hand."))
```

2021-06-21 17:16 UTC, Doster-d requested changes

2021-06-21 17:16 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +/obj/item/trash/dishes/attack_hand( mob/user as mob )
```suggestion
/obj/item/trash/dishes/attack_hand(mob/user)
```

2021-06-21 19:11 UTC, Oubifx commented on code/game/objects/items/trash.dm
> +	var/obj/item/trash/dishes/old_icon_state = copytext("[icon_state]",1,-1) // suitable for different name lengths
Не вижу смысла ``-1`` заменять ``length(icon_state)-1`` .  Всё уже предусмотренно самой процедурой:
> If the start or end position is negative, it counts backwards from the end of the string.

Если в этом есть подводные камни, то был бы рад услышать подробности

2021-06-21 19:17 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +	var/obj/item/trash/dishes/old_icon_state = copytext("[icon_state]",1,-1) // suitable for different name lengths
Это разработчики бьенда, от них можно ожидать все что угодно

https://www.reddit.com/r/SS13/comments/5oplxp/comment/dclbu1a

2021-06-22 07:11 UTC, kcalbCube requested changes
ну плюс минус...

2021-06-22 07:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +			src.stack.Add(dishestoadd)
```suggestion
			stack.Add(dishestoadd)
```

или вообще
```suggestion
			stack += dishestoadd
```

2021-06-22 07:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +		if((length(stack) + 1) + length(dishestoadd) <= 5)
```suggestion
		if(length(stack) + length(dishestoadd) <= 4)
```

2021-06-22 07:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +		to_chat(user, SPAN("warning", "You remove the topmost [src] from your hand."))
```suggestion
		to_chat(user, SPAN("warning", "You have removed the topmost [src] from your hand."))
```

2021-06-22 07:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +
ньюлайны

2021-06-22 07:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	var/list/stack = list()
```suggestion
	/obj/item/trash/dishes/var/list/stack = list()
```

2021-06-22 07:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	if(length(stack) > 0)
```suggestion
	if(length(stack) > 0 && user.get_inactive_hand() == src)
```

2021-06-22 07:59 UTC, Oubifx commented on code/game/objects/items/trash.dm
> +			dish.stack = list()
Не понимаю какая цель преследуется этим исправлением. В других исправлениях мы уходим от процедур и возвращаемся к операторам, а здесь всё наоборот, уходим от оператора ``=`` и возвращаемся к процедуре. Если этому есть объяснение, то буду рад услышать подробности на будущее ПР-ы

2021-06-22 08:23 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +			dish.stack = list()
присваивая список ты создаёшь новый обьект и удаляешь старый.
Cut() же просто очищает список. 
Да и просто так принято

2021-06-22 08:36 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +			dish.stack = list()
> присваивая список ты создаёшь новый обьект и удаляешь старый.
> Cut() же просто очищает список. 
> Да и просто так принято

Да.

2021-06-23 20:26 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +	if(I.type == src.type) // We add only objects of our own type
```suggestion
	if(I.type == type) // We add only objects of our own type
```

2021-06-26 23:11 UTC, kcalbCube requested changes
В пизду лезем

2021-06-26 23:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	/obj/item/trash/dishes/var/list/stack = list()
Ебать, это компилится вообще?

2021-06-26 23:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +		return
```suggestion
    else
		..()
```

2021-06-26 23:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +
```suggestion
```

2021-06-26 23:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +		return
```suggestion
    else
        ..()
```

2021-06-26 23:11 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	..()
```suggestion
```
Ну или return оставить и это убрать

2021-06-26 23:41 UTC, Oubifx commented on code/game/objects/items/trash.dm
> +	..()
Пожалуй так и сделаю, return как-то более часто встречается в других языках

2021-06-26 23:45 UTC, Oubifx commented on code/game/objects/items/trash.dm
> +	/obj/item/trash/dishes/var/list/stack = list()
В одном из коммитов вылез прикол.. Но да ладно, поправил

2021-06-27 16:41 UTC, kcalbCube requested changes

2021-06-27 16:41 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	return
```suggestion
	    return
```
Таб потерял

2021-06-27 16:41 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	return
Аналогично

2021-06-27 16:41 UTC, kcalbCube commented on code/game/objects/items/trash.dm
>  			return
```suggestion
            ..() 
			return
```
Ты бля

2021-06-27 16:41 UTC, kcalbCube commented on code/game/objects/items/trash.dm
>  		if(user.get_inactive_hand() != src)
Ты строчкой выше уже проверил

2021-06-28 08:36 UTC, Oubifx commented on code/game/objects/items/trash.dm
>  		if(user.get_inactive_hand() != src)
Опять мистика, в предыдущих коммитах этой проверки не было

2021-06-30 16:13 UTC, Oubifx commented
Алё. Ну как там с ПР-ом?

2021-06-30 21:48 UTC, kcalbCube requested changes
давай-давай старайся

2021-06-30 21:48 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +		return
зачем здесь return?

2021-06-30 21:48 UTC, kcalbCube commented on code/game/objects/items/trash.dm
> +	return
return убери, ставит реакты тут.

2021-07-01 15:28 UTC, Oubifx commented on code/game/objects/items/trash.dm
> +		return
А ведь действительно, это же уже конец функции

2021-07-02 15:22 UTC, TermService approved these changes

2021-07-08 19:42 UTC, Oubifx commented
@TatarTheBuilder унатхам и так не платят, так еще пять раз приходится к мусорке тарелки носить вместо одного. Только в твоих силах это исправить, не одобряй НТ. В знак протеста против НТ можешь одобрить иссуй и ПР. Сделаем унатхов снова великими!! @_@

2021-07-08 19:52 UTC, igorsaux requested changes

2021-07-08 19:52 UTC, igorsaux commented on code/game/objects/items/trash.dm
> +	icon_state = "[old_icon_state][length(stack)]"
```suggestion
	icon_state = "[initial(icon_state)][length(stack)]"
```

2021-07-08 19:52 UTC, igorsaux commented on code/game/objects/items/trash.dm
> +	if(I.type == type) // We add only objects of our own type
```suggestion
	if(I.type == type)
```

2021-07-08 19:52 UTC, igorsaux commented on code/game/objects/items/trash.dm
> +/obj/item/trash/dishes
```suggestion
/obj/item/trash/dish
```
Почему тип вдруг во множественном числе

2021-07-08 19:55 UTC, Doster-d commented on code/game/objects/items/trash.dm
> +	icon_state = "baking_sheet0"
Если принимать вариант Игоря, то надо сделать так во все типы:
```suggestion
	icon_state = "baking_sheet"
```

2021-07-09 22:30 UTC, Oubifx commented on code/game/objects/items/trash.dm
> +/obj/item/trash/dishes
Исправлю, почему-то думал что образец вируса уже обозван как ``dish``

2021-07-10 09:10 UTC, igorsaux commented on baystation12.dme
> -#include "code\game\objects\items\devices\debugger.dm"
А его за что

2021-07-10 09:15 UTC, Oubifx commented on baystation12.dme
> -#include "code\game\objects\items\devices\debugger.dm"
Вопрос конечно интересный, сам хз

2021-07-10 09:30 UTC, Oubifx commented
Работяга дебагер получил шальной миссклик, вернул его в строй

2021-07-21 14:43 UTC, Oubifx commented
@TobyThorne конфликты решены. Надеюсь merge не за горами

2021-07-24 10:16 UTC, Oubifx commented
@HonkyDonky можешь убирать плашку конфликта, он исправлен

2021-07-24 12:07 UTC, igorsaux requested changes
![image](https://user-images.githubusercontent.com/55196698/126867950-55505dc9-bc95-4b2d-92f3-7b81f89849de.png)

2021-07-24 12:24 UTC, Oubifx commented
Название последнего коммита говорит само за себя. Спасибо VSC что она есть.

2021-07-24 13:39 UTC, TermService submitted a review, later dismissed

2021-07-24 13:53 UTC, Doster-d approved these changes

2021-07-24 19:55 UTC, igorsaux requested changes

2021-07-24 19:55 UTC, igorsaux commented on code/game/objects/items/trash.dm
> +		if((length(stack) + length(dishestoadd)) <= 4)
Какие-то магические числа. Лучше будет в виде переменной, так хоть можно будет разным видам тарелок задавать разный максимальный стак.

2021-07-24 19:55 UTC, igorsaux commented on code/game/objects/items/trash.dm
> +	to_chat(user, SPAN("warning", "You have removed the topmost [src] from your hand."))
Сообщение на каждое удаление/добавление в стак да и ещё красным цветом как-то слишком мусорно.

2021-07-26 17:48 UTC, igorsaux approved these changes

2021-07-26 18:25 UTC, kreeperHLC approved these changes
Все знают что стак равен 64 блокам.

2021-08-01 14:25 UTC, TobyThorne commented
Если всё сломается - обвинять зелёногалочников.

2021-08-01 14:26 UTC, merged