fix(crates): add specific material to crates and some refactoring
ChaoticOnyx/OnyxBay pull request #5689
Opened 2021-06-22 12:15 UTC by NefrNerf

Добавил контейнерам переменную материала, теперь можно настроить во что разбирается каждый тип контейнера. Немного рефакторинга.

close #5624
#5625 - Это, как сказал Татар - не баг, тут ничего не менял

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Пластиковый ящик при разборе больше не дает стальной лист
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-22 14:26 UTC, NefrNerf commented
Еще бы понять, что тут не так...

2021-06-22 19:46 UTC, TobyThorne requested changes

2021-06-22 19:46 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> -	var/open_delay = 0
Здесь зачем? Тут не булка, а конкретное числовое значение. 
![image](https://user-images.githubusercontent.com/45202681/122989165-518a4900-d3c4-11eb-9529-11b5f590609e.png)

2021-06-22 19:46 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +		user.visible_message(SPAN_WARNING("[user] [locked?"locks":"unlocks"] [name] with a multitool."), SPAN_WARNING("I [locked?"enable":"disable"] the locking modules."))
```suggestion
		user.visible_message(SPAN_WARNING("[user] [locked ? "locks" : "unlocks"] [name] with a multitool."), SPAN_WARNING("I [locked ? "enable" : "disable"] the locking modules."))
```

2021-06-22 19:46 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +	new src.material(src.loc)
```suggestion
	new material(loc)
```

2021-06-22 19:46 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +	new src.material(src.loc)
Ещё и проверку бы воткнуть, что material не null.

2021-06-23 17:54 UTC, NefrNerf commented
Обновил, сразу не заметил, что задержка - не булевая

2021-06-23 20:22 UTC, TobyThorne approved these changes
сойдёт

2021-06-23 20:28 UTC, kreeperHLC commented
Может тогда исправишь это, поменяв название?
> в меню сварки пласталевых листов он называется metal crate, но в меню сварки стальных листов ящик из металлических листов отсутствует.

2021-06-23 20:32 UTC, NefrNerf commented
Да, завтра уже добавлю. Правда не совсем понимаю, почему нет возможности делать из стали обычные ящики, из-за карго наверное, ну да ладно.

2021-06-24 19:28 UTC, kreeperHLC requested changes

2021-06-24 19:28 UTC, kreeperHLC commented on code/game/objects/structures/crates_lockers/crates.dm
> +	desc = "Handame crate made of plasteel, looks like it lost plastic properties"
ХАНДАМЕ
Ну и лучше бы к старому описанию прибавил бы пункт о том, что из-за ассистентской сборки он потерял свои укреплённые свойства

2021-06-24 19:56 UTC, NefrNerf commented
Все, вроде пляски с описанием закончил

2021-06-30 19:08 UTC, kreeperHLC submitted a review, later dismissed

2021-07-03 14:07 UTC, igorsaux submitted a review, later dismissed
вроде ок

2021-07-03 14:07 UTC, TobyThorne requested changes

2021-07-03 14:07 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> -				user.visible_message(SPAN("notice", "[user] unscrewed [cdoor] from [src]."))
А нормальные спаны зачем на кринж менять?

2021-07-03 14:07 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> -		to_chat(user, SPAN("warning", "You can't do this right now."))
И здесь.

2021-07-03 14:11 UTC, NefrNerf commented on code/game/objects/structures/crates_lockers/closets.dm
> -				user.visible_message(SPAN("notice", "[user] unscrewed [cdoor] from [src]."))
Тогда еще не знал, что не стоит эти спаны - не стоит ставить, да и в них же разницы никакой нет?

2021-07-03 14:17 UTC, NefrNerf commented
Вернул нормальные спаны

2021-07-03 14:31 UTC, TobyThorne requested changes

2021-07-03 14:31 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/crates.dm
> +	name = "Plastic crate"
А зачем капиталайз?

2021-07-03 14:31 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/crates.dm
> +	name = "Handmade crate"
И тутой.

2021-07-03 14:35 UTC, NefrNerf commented
Бес попутал, больше не будет

2021-07-03 14:37 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +	visible_message(SPAN_DANGER("<span class='danger'>\The [escapee] successfully broke out of \the [src]!"))
А это шо такое.

2021-07-03 14:39 UTC, NefrNerf commented
Может оставим эти спаны, у меня они там везде? Дальше буду нормальный делать

2021-07-03 14:40 UTC, TobyThorne commented
> Может оставим эти спаны, у меня они там везде? Дальше буду нормальный делать

Да бога ради, но "

2021-07-03 14:40 UTC, TobyThorne commented
Блет мисскликнул >:(

2021-07-03 14:41 UTC, TobyThorne commented
> Может оставим эти спаны, у меня они там везде? Дальше буду нормальный делать

...но visible_message(SPAN_DANGER("<span class='danger'> - это мем какой-то

2021-07-03 14:45 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +	visible_message(SPAN_DANGER("<span class='danger'>\The [escapee] successfully broke out of \the [src]!"))
```suggestion
	visible_message(SPAN_DANGER("\The [escapee] successfully broke out of \the [src]!"))
```

2021-07-03 15:26 UTC, TobyThorne approved these changes
ну допустим скомпилируется наверное

2021-07-07 07:50 UTC, kreeperHLC approved these changes

2021-07-07 22:18 UTC, merged