Return corgi hats
ChaoticOnyx/OnyxBay pull request #5698
Opened 2021-06-22 17:03 UTC by No-Tips

Вернул шапки для корги на их законное место - голову собакам.

Вернул возможность одевать специальные шапки на корги. Конечно же, сами шапки тоже прописал и вернул в билд. На карту не добавлял, сделаем отдельным пром.

close #2942

<details>
<summary>Чейнджлог</summary>

```yml
🆑
imageadd: Возвращены шапки для корги.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-22 19:48 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +			to_chat(user, SPAN_WARNING("\The [src] is already wearing \the [hat]."))
```suggestion
			to_chat(user, SPAN_WARNING("[name] is already wearing \the [hat]."))
```

2021-06-22 19:48 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +		user.visible_message(SPAN_WARNING("\The [user] puts \the [O] on \the [src]."))
```suggestion
		user.visible_message(SPAN_WARNING("\The [user] puts \the [O] on [name]."))
```

2021-06-22 19:49 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +					M.show_message(SPAN_WARNING("[user] baps [name] on the nose with the rolled up [O]"))
```suggestion
					M.show_message(SPAN_WARNING("[user] baps [name] on the nose with the rolled up [O]!"))
```

2021-06-22 19:50 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	var hat_offset_y = -7
```suggestion
	var/hat_offset_x = 1 		//preseting offsets to north and south
	var/hat_offset_y = -7
```

Как это вообще компилируется?

2021-06-22 19:52 UTC, TobyThorne requested changes

2021-06-22 19:52 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	overlays |= get_hat_icon(hat, hat_offset_x, hat_offset_y)
Зачем здесь вообще весь этот код, если у корги шляпы теперь в собственном файле лежат? 
Надо или давать возможность цеплять на них все шапки, хватая спрайты из обычного файла и используя вот эту магию, либо отрисовывать для них шапки сразу с оффсетами и вот этим всем не заниматься.

2021-06-22 19:54 UTC, No-Tips commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	overlays |= get_hat_icon(hat, hat_offset_x, hat_offset_y)
Я просто не спрайтер, так что решаю тем путем, который есть у меня. Я то могу с этим разобраться, но это нужно тыкаться в спрайтики, менять их.

2021-06-22 19:55 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	overlays |= get_hat_icon(hat, hat_offset_x, hat_offset_y)
Тогда зачем им отдельные шапки и отдельный файл со спрайтами? Пусть надеваются любые, как с дронами.

2021-06-22 21:04 UTC, No-Tips commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	overlays |= get_hat_icon(hat, hat_offset_x, hat_offset_y)
Хмм.... А что, можно. Правда, некоторые шляпы все же будут смотреться. Но если это отбросить - можно сделать и так. Параллельно заметил проблему с тем, что шапка апдейтится не сразу же, а через определенное  время. Нужны идеи фиксов!
![изображение](https://user-images.githubusercontent.com/75416333/122998987-5e07a500-d3b6-11eb-8094-ff82a1898112.png)

2021-06-23 04:28 UTC, MrMagick2104 commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	overlays |= get_hat_icon(hat, hat_offset_x, hat_offset_y)
udpate_icon() попробуй использовать при необходимости сразу же обновить спрайт.

2021-06-23 09:51 UTC, TobyThorne requested changes

2021-06-23 09:51 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	old_dir = src.dir
```suggestion
	old_dir = dir
```

2021-06-23 09:51 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(old_dir == src.dir) //We do not need to update hat, if we did not change dir
```suggestion
	if(old_dir == dir) // We do not need to update hat, if we did not change dir
```

2021-06-23 09:51 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	var/hat_offset_x = 1 		//preseting offsets to north and south
```suggestion
	var/hat_offset_x = 1 		// preseting offsets to north and south
```

2021-06-23 09:51 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	if(src.dir == 4)			//Setting offset for east and west to properly render hats
```suggestion
	if(dir == 4)			// Setting offset for east and west to properly render hats
```

2021-06-23 09:51 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	else if(src.dir == 8)
```suggestion
	else if(dir == 8)
```

2021-06-24 11:25 UTC, Doster-d requested changes

2021-06-24 11:25 UTC, Doster-d commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +/mob/living/simple_animal/corgi/attackby(obj/item/O as obj, mob/user as mob)  // Marker -Agouri
```suggestion
/mob/living/simple_animal/corgi/attackby(obj/item/O, mob/user)  // Marker -Agouri
```

2021-06-26 20:21 UTC, TobyThorne approved these changes
наверное сервер не уронит

2021-06-29 16:23 UTC, Doster-d approved these changes

2021-06-29 19:57 UTC, merged