fix(water_ballon): w_size approximation & fulfillment from dispensers
ChaoticOnyx/OnyxBay pull request #5709
Opened 2021-06-23 11:04 UTC by TapKo4eB

close #5679
ура фикс размеров шариков
алсо теперь можно наполнять не только из ватертанков

<details>
<summary>cheenglox</summary>

```yml
🆑
bugfix: Водяные шарики теперь приобрели ожидаемый малый размер и научились менять его при наполнении.
bugfix: Водяные шарики теперь можно наполнять не только из водяных баков.
/🆑
```
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

да я знаю что из раковины хрен наполнишь но мне влом пихать костыли

2021-06-23 11:32 UTC, Doster-d commented on code/game/objects/items/toys.dm
> +	if (istype(A, /obj/structure/reagent_dispensers) && get_dist(src,A) <= 1)
Получается, что можно наполнить шарик кислотой, не?

2021-06-23 11:35 UTC, DarkHunter7756 commented on code/game/objects/items/toys.dm
> +	if (istype(A, /obj/structure/reagent_dispensers) && get_dist(src,A) <= 1)
> Получается, что можно наполнить шарик кислотой, не?

Некоторые виды резины более устойчивы к коррозийному воздействию кислот. Да и выглядит как фича. Бросаемые шарики с кислотой.

2021-06-23 11:35 UTC, TapKo4eB commented on code/game/objects/items/toys.dm
> +	if (istype(A, /obj/structure/reagent_dispensers) && get_dist(src,A) <= 1)
серной да политринником нет я логику не трогал да и раньше можно было через стаканы

2021-06-23 20:51 UTC, kreeperHLC submitted a review, later dismissed

2021-06-26 21:01 UTC, TobyThorne requested changes

2021-06-26 21:01 UTC, TobyThorne commented on code/game/objects/items/toys.dm
> +	if (istype(A, /obj/structure/reagent_dispensers) && get_dist(src,A) <= 1)
```suggestion
	if(istype(A, /obj/structure/reagent_dispensers) && Adjacent(A))
```

2021-06-29 15:18 UTC, TobyThorne approved these changes

2021-06-29 15:22 UTC, igorsaux approved these changes

2021-06-29 16:16 UTC, merged