Fixes "everything" on "Exodus"
ChaoticOnyx/OnyxBay pull request #5739
Opened 2021-06-24 13:30 UTC by MaxFreemen

Небольшой набор фиксов и обновлений для "Исхода" .

Исправление кабины пилота на эвакуационном шаттле "Исхода"
![dreammaker_MVX2O2jS64](https://user-images.githubusercontent.com/47484306/123271925-f7939b80-d509-11eb-8048-b680a51d126b.png)

Шаттл шахтеров:
![dreammaker_d79G3gDDmA](https://user-images.githubusercontent.com/47484306/123308114-f2dfdf00-d52b-11eb-9697-888bb71cdaa1.png)

Новые кресла:
![NVIDIA_Share_DDxA7pU9Aa](https://user-images.githubusercontent.com/47484306/123308156-fecba100-d52b-11eb-8249-009a99e6bfda.png)

Измененная кабина пилота на корабле синдиката.
![dreammaker_nZsvAl8fnj](https://user-images.githubusercontent.com/47484306/123273078-fe6ede00-d50a-11eb-9ebf-248ecdb82772.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑MaxDornan
maptweak: Удалена документация "Психоскопа" с "Исхода".
maptweak: Обновлен эвакуационный шаттл "Исхода" - удален стол из-под консоли, заменены некоторые клетки пола.
maptweak: Добавлен органфиксер воксам и синдикатовцам.
maptweak: Обновлен шаттл шахтеров - стулья заменены на новые кресла.
maptweak: Обновлен шаттл синдиката - стулья заменены на кресла, исправлена планировка кабины пилота.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-24 16:00 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/123295463-8d91eb00-d537-11eb-95e9-ade10004a85a.png)
вот это точно не нужно

2021-06-24 17:06 UTC, MaxFreemen commented
> ![image](https://user-images.githubusercontent.com/45202681/123295463-8d91eb00-d537-11eb-95e9-ade10004a85a.png)
> вот это точно не нужно

Ладно.

2021-06-24 17:48 UTC, TatarTheBuilder submitted a review, later dismissed
по мапдиффам вроде нормально, в проде потестим

2021-06-24 19:11 UTC, TobyThorne requested changes
Где _over и _armrest для новых кресел?

2021-06-24 20:59 UTC, MaxFreemen commented
> Где _over и _armrest для новых кресел?

У красного нет, поэтому зачем это для черного делать? Плюс мое кресло - дочернее. Если надо, то унаследует его от отца.

2021-06-24 21:06 UTC, TobyThorne commented
> У красного нет

Чего у него нет?
shuttle_chaired_over:
![image](https://user-images.githubusercontent.com/45202681/123332392-410fd500-d562-11eb-9271-4eaed9369898.png)
shuttle_chaired_armrest:
![image](https://user-images.githubusercontent.com/45202681/123332424-4b31d380-d562-11eb-85e1-9057d7b9fcff.png)

2021-06-25 22:51 UTC, MaxFreemen commented
> > У красного нет
> 
> Чего у него нет?
> shuttle_chaired_over:
> ![image](https://user-images.githubusercontent.com/45202681/123332392-410fd500-d562-11eb-9271-4eaed9369898.png)
> shuttle_chaired_armrest:
> ![image](https://user-images.githubusercontent.com/45202681/123332424-4b31d380-d562-11eb-85e1-9057d7b9fcff.png)

Дело сделано.

2021-06-26 07:11 UTC, TatarTheBuilder approved these changes

2021-06-26 07:22 UTC, Doster-d approved these changes

2021-06-26 08:40 UTC, wadangel commented
А почему кресла-то грязные и покрытые ржавыми (?) пятнами? Это, прости господи, ОТСЫЛКА НА ЛУЙФВЕБ?

2021-06-26 16:28 UTC, MaxFreemen commented
> А почему кресла-то грязные и покрытые ржавыми (?) пятнами? Это, прости господи, ОТСЫЛКА НА ЛУЙФВЕБ?

Не, просто шахтеры руки не моют и маски не носят, вот сиденья и попачкались.

2021-06-26 20:12 UTC, TobyThorne approved these changes

2021-06-26 20:15 UTC, merged