fix(twohanded): fix display of two-handed weapons on the back
ChaoticOnyx/OnyxBay pull request #5771
Opened 2021-06-26 17:01 UTC by Oubifx

Исправил отображение копья и биты на спине. Раньше они отображались лишь тогда, когда во время перемещения на спину вторая рука была занята.

fix #5756

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
bugfix: Исправлено отображение копья и биты на спине
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-26 19:23 UTC, Doster-d reviewed
http://www.byond.com/docs/ref/#/var/tmp

Это не то, как применяется tmp

2021-06-26 19:23 UTC, Doster-d commented on code/game/objects/items/weapons/material/twohanded.dm
> +	var/tmp/new_item_state = "[base_icon][wielded]"
```suggestion
	var/new_item_state = "[base_icon][wielded]"
```

2021-06-30 08:06 UTC, TobyThorne approved these changes
Вроде, работает. Для бит надо будет нарисовать наспинный спрайт.

2021-06-30 08:08 UTC, TobyThorne requested changes
А нет, не работает. У бит есть спрайт, но он не отображается.

2021-06-30 08:08 UTC, TobyThorne approved these changes
А нет, всё же отображается.

2021-06-30 12:23 UTC, TobyThorne approved these changes
Всё ещё работает.

2021-07-02 14:57 UTC, TermService approved these changes

2021-07-07 22:19 UTC, merged