Выпил wheelchairs с карты.
ChaoticOnyx/OnyxBay pull request #5816
Opened 2021-06-29 12:38 UTC by Doster-d

Также закомментировал спавн их, когда нет ног у человека.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscdel: Спавн wheelchair, если у Вас нет ноги временно отключен.
maptweak: Со всех карт удалены wheelchairs
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-29 12:39 UTC, MaxFreemen commented
И что делать людям без ног теперь? Ползти до ближайшего офисного стула, чтоб на нем кататься?

2021-06-29 12:39 UTC, Doster-d commented
> И что делать людям без ног теперь? Ползти до ближайшего офисного стула, чтоб на нем кататься?

Да.

2021-06-29 12:41 UTC, MaxFreemen commented
> > И что делать людям без ног теперь? Ползти до ближайшего офисного стула, чтоб на нем кататься?
> 
> Да.

Тогда задам еще один вопрос. Примерно через сколько коляски починят и вернут?

2021-06-29 12:43 UTC, Doster-d commented
> Примерно через сколько коляски починят и вернут?

А я откуда знаю?

2021-06-29 12:44 UTC, MaxFreemen commented
> > Примерно через сколько коляски починят и вернут?
> 
> А я откуда знаю?

Ну, помянем тогда всех безногих.

2021-06-29 12:45 UTC, DarkHunter7756 commented
> Спавн wheelchair, если у Вас нет ноги временно отключен.

Инвалид без ног легко отцепляется от коляски и буллится до скончания веков. Особенно если это офицер. Поэтому уж лучше оставить. Инвалидов не то, чтобы много, а благодаря вашему убер херовому апдейту с закрытием дверей по клику на тайл перемещаться на на стульях практически НЕВОЗМОЖНО

2021-06-29 12:45 UTC, Doster-d commented
Это давно исправили, Дарк, держу в курсе.

2021-06-29 12:46 UTC, DarkHunter7756 commented
> Это давно исправили, Дарк, держу в курсе.

А, ну тогда пихуй. Будем закликивать карту до дыр

2021-06-29 12:48 UTC, Doster-d commented
> > Это давно исправили, Дарк, держу в курсе.
> 
> А, ну тогда пихуй. Будем закликивать карту до дыр

Нормальные люди перемещаются стрелочками/WASD

2021-06-29 13:34 UTC, TobyThorne commented
импрув нот ремув

2021-06-29 13:44 UTC, Zert0X commented
Может не надо? Абузеров колясочников итак избивают без особых проблем, да и самих абузеров по пальцам руки токаря левши можно пересчитать

2021-06-29 22:26 UTC, kcalbCube requested changes

2021-06-29 22:26 UTC, kcalbCube commented on maps/exodus/exodus-1.dmm
> +"aLv" = (/obj/effect/floor_decal/corner/paleblue{dir = 4},/turf/simulated/floor/tiled/white,/area/medical/medbay3/underground)
не задокументировал на что поменял.

2021-06-29 22:26 UTC, kcalbCube commented on code/game/jobs/job_controller.dm
> +		*/
ну и что безногим делать? пусть хоть у них будет коляска. а педали будут играть в детективов по поиску бедной украденной коляски.

2021-06-30 14:42 UTC, Doster-d commented on maps/exodus/exodus-1.dmm
> +"aLv" = (/obj/effect/floor_decal/corner/paleblue{dir = 4},/turf/simulated/floor/tiled/white,/area/medical/medbay3/underground)
Я все задокументировал, ~~пидор ебанный~~

2021-06-30 14:42 UTC, Doster-d commented on code/game/jobs/job_controller.dm
> +		*/
К Вадангелу.

2021-07-01 11:09 UTC, NefrNerf commented
Почему бы просто не отключить ей боевое применение, если человек сидит на коляске то у него заняты руки(как он ещё будет ехать?)

2021-07-26 15:42 UTC, TobyThorne commented
Импрув нот ремув.

2021-07-26 17:33 UTC, Doster-d commented
Дикие приколы убиты, можно закрыть.

2021-07-26 17:33 UTC, closed without merging