fix labels on deliveries
ChaoticOnyx/OnyxBay pull request #5834
Opened 2021-06-30 01:10 UTC by Artemonim

close #5753

Есть стойкое ощущение, что логика должна быть только в handlabeler.dm иначе нанесение новых заголовков и описаний дополняет, а не заменяет старые надписи.

<details>
<summary>Чейнджлог</summary>

```yml
🆑 Artemonim
bugfix: Fixed adding labels using a hand labeler
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-30 07:25 UTC, TobyThorne commented
Абсолютно нихрена не понял. В чём баг, что делает ПР, зачем ужасные костыли с проверкой иконстейтов?

2021-06-30 07:29 UTC, TobyThorne requested changes

2021-06-30 07:29 UTC, TobyThorne commented on code/modules/recycling/sortingmachinery.dm
> +				"You hear the sound of a small printer.")
Тридцать строчек чистейшей копипасты кода сверху. Не пойдёт.

2021-06-30 12:03 UTC, Artemonim commented on code/modules/recycling/sortingmachinery.dm
> +				"You hear the sound of a small printer.")
переписал по-нормальному в следующем коммите

2021-06-30 12:19 UTC, kcalbCube requested changes
Нихуя не понял

2021-06-30 12:19 UTC, kcalbCube commented on code/modules/paperwork/handlabeler.dm
> +
А просто в строке deliverycrate искать не? И вообще не понятен смысл

2021-06-30 12:19 UTC, kcalbCube commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] titles \the [src] with \a [W], marking down: \"[str]\"",\
Вы тоже можете сразу понять что человек пишет только по виду?

2021-06-30 13:16 UTC, Artemonim commented on code/modules/paperwork/handlabeler.dm
> +
Поправил, спасибо!

2021-06-30 19:26 UTC, TobyThorne requested changes

2021-06-30 19:26 UTC, TobyThorne commented on code/modules/paperwork/handlabeler.dm
> +		return
Всё ещё критически-дебильная проверка. Что мешает сделать istype(A, /obj/structure/bigDelivery)?

2021-06-30 20:54 UTC, Artemonim commented on code/modules/paperwork/handlabeler.dm
> +		return
Незнание DM ☉.☉

2021-07-02 14:56 UTC, TermService approved these changes

2021-07-07 17:37 UTC, NefrNerf requested changes

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You title \the [src]: \"[str]\"</span>",\
```suggestion
					SPAN("notice", You title \the [src]: \"[str]\"),\
```

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You label \the [src]: \"[examtext]\"</span>",\
```suggestion
					SPAN("notice", "You label \the [src]: \"[examtext]\""),\

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You label \the [src]: \"[examtext]\"</span>",\
```suggestion
					SPAN("notice", "You label \the [src]: \"[examtext]\""),\
```

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You title \the [src]: \"[str]\"</span>",\
```suggestion
					SPAN("notice", You title \the [src]: \"[str]\"),\
```

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You title \the [src]: \"[str]\"</span>",\
```suggestion
					SPAN("notice", You title \the [src]: \"[str]\"),\
```

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You label \the [src]: \"[examtext]\"</span>",\
```suggestion
					SPAN("notice", "You label \the [src]: \"[examtext]\""),\
```

2021-07-07 17:37 UTC, NefrNerf commented on code/modules/recycling/sortingmachinery.dm
> +					"<span class='notice'>You label \the [src]: \"[examtext]\"</span>",\
```suggestion
					SPAN("notice", "You label \the [src]: \"[examtext]\""),\
```

2021-07-07 19:01 UTC, igorsaux requested changes

2021-07-07 19:01 UTC, igorsaux commented on code/modules/recycling/sortingmachinery.dm
> +					"You hear the sound of a small printer.")
```suggestion
					user.visible_message("\The [user] titles \the [src] with \a [W], marking down: \"[str]\"",
					                     SPAN("notice", "You title \the [src]: \"[str]\""),
					                     "You hear someone scribbling a note.")
				else
					user.visible_message("\The [user] titles \the [src] with \a [W]: \"[str]\"",
					                     SPAN("notice", "You title \the [src]: \"[str]\""),
					                     "You hear the sound of a small printer.")
```

2021-07-07 19:01 UTC, igorsaux commented on code/modules/recycling/sortingmachinery.dm
> +					"You hear the sound of a small printer.")
```suggestion
					user.visible_message("\The [user] labels \the [src] with \a [W], scribbling down: \"[examtext]\"",
					                     SPAN("notice", "You label \the [src]: \"[examtext]\""),
					                     "You hear someone scribbling a note.")
				else
					user.visible_message("\The [user] labels \the [src] with \a [W]: \"[examtext]\"",
					                     SPAN("notice", "You label \the [src]: \"[examtext]\""),
					                     "You hear the sound of a small printer.")
```

2021-07-07 19:01 UTC, igorsaux commented on code/modules/recycling/sortingmachinery.dm
> +					"You hear the sound of a small printer.")
```suggestion
					user.visible_message("\The [user] titles \the [src] with \a [W], marking down: \"[str]\"",
					                     SPAN("notice", "You title \the [src]: \"[str]\""),
					                     "You hear someone scribbling a note.")
				else
					user.visible_message("\The [user] titles \the [src] with \a [W]: \"[str]\"",
					                     SPAN("notice", "You title \the [src]: \"[str]\""),
					                     "You hear the sound of a small printer.")
```

2021-07-07 19:01 UTC, igorsaux commented on code/modules/recycling/sortingmachinery.dm
> +					"You hear the sound of a small printer.")
```suggestion
					user.visible_message("\The [user] labels \the [src] with \a [W], scribbling down: \"[examtext]\"",
					                     SPAN("notice", "You label \the [src]: \"[examtext]\""),
					                     "You hear someone scribbling a note.")
				else
					user.visible_message("\The [user] labels \the [src] with \a [W]: \"[examtext]\"",
					                     SPAN("notice", "You label \the [src]: \"[examtext]\""),
					                     "You hear the sound of a small printer.")
```

2021-07-07 19:19 UTC, Artemonim commented on code/modules/recycling/sortingmachinery.dm
> +					"You hear the sound of a small printer.")
Большое спасибо за скорую поддержку, но заметил, когда сам уже поправил ^^7

2021-07-12 10:20 UTC, Zert0X requested changes
По аналогии с претензией кубика, ты не можешь увидеть прямо так сразу не разглядывая, что там накалякал персонаж, все изменения примерны писал с телефона очень не удобно. Но суть понятна.

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] titles \the [src] with \a [W], marking down: \"[str]\"",\
```suggestion
					user.visible_message("\The [user] titles \the [src] with \a [W]",\
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] titles \the [src] with \a [W]: \"[str]\"",\
```suggestion
					user.visible_message("\The [user] titles \the [src] with \a [W]",\
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] labels \the [src] with \a [W], scribbling down: \"[examtext]\"",
```suggestion
					user.visible_message("\The [user] labels \the [src] with \a [W], scribbling something down",
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] labels \the [src] with \a [W]: \"[examtext]\"",
```suggestion
					user.visible_message("\The [user] labels \the [src] with \a [W]",
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] titles \the [src] with \a [W], marking down: \"[str]\"",\
```suggestion
					user.visible_message("\The [user] titles \the [src] with \a [W]",\
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] titles \the [src] with \a [W]: \"[str]\"",\
```suggestion
					user.visible_message("\The [user] titles \the [src] with \a [W]:",\
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] labels \the [src] with \a [W], scribbling down: \"[examtext]\"",
```suggestion
					user.visible_message("\The [user] labels \the [src] with \a [W], scribbling something down",
```

2021-07-12 10:20 UTC, Zert0X commented on code/modules/recycling/sortingmachinery.dm
> +					user.visible_message("\The [user] labels \the [src] with \a [W]: \"[examtext]\"",
```suggestion
					user.visible_message("\The [user] labels \the [src] with \a [W]",
```

2021-07-20 06:24 UTC, TobyThorne approved these changes

2021-08-01 20:12 UTC, Artemonim commented
Мисскликнул...

2021-08-06 14:44 UTC, TermService approved these changes

2021-08-06 15:19 UTC, igorsaux approved these changes

2021-08-06 15:21 UTC, NefrNerf approved these changes

2021-08-10 05:59 UTC, Zert0X approved these changes

2021-08-13 16:49 UTC, kreeperHLC approved these changes
Ну раз все аппрувнули то и я тоже аппрувну

2021-08-13 16:51 UTC, merged