Чиним нерабочие заклинания мага.
ChaoticOnyx/OnyxBay pull request #5848
Opened 2021-06-30 19:51 UTC by NefrNerf

Одной строчкой поправил действие Knock указав что шлюз открывается насильно, как монтировкой.
Парой строк поправил действия скиллов которые влияют на ученика мага. Теперь ученик телепортируется К МАГУ, а не наоборот. Область действия скиллов больше не ограниченна областью видимости. 

close #5693
close #5656

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Кнок мага открывает обесточенные шлюзы.
bugfix: Починил заклинания взаимодействия мага с учениками.
tweak: Ученик телепортируется к магу, было наоборот.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-06-30 20:09 UTC, Zert0X submitted a review, later dismissed
Тревис не орёт значит можно мержить

2021-06-30 21:23 UTC, TobyThorne requested changes

2021-06-30 21:23 UTC, TobyThorne commented on code/_macros.dm
> +
```suggestion
```

2021-06-30 21:23 UTC, TobyThorne commented on code/modules/spells/general/contract_spells.dm
> +	to_chat(target, SPAN_INFO("You feel great!"))
```suggestion
	to_chat(target, SPAN("info", "You feel great!"))
```

2021-06-30 21:26 UTC, NefrNerf commented on code/modules/spells/general/contract_spells.dm
> +	to_chat(target, SPAN_INFO("You feel great!"))
Лучше не добавлять новый макрос? Я несколько раз встречал класс '''info'''

2021-06-30 21:27 UTC, TobyThorne commented on code/modules/spells/general/contract_spells.dm
> +	to_chat(target, SPAN_INFO("You feel great!"))
Эти макросы вообще неизвестно зачем существуют, когда есть нормальный SPAN("span", "text")

2021-06-30 21:29 UTC, TobyThorne commented on code/_macros.dm
> -
Куда ньюлайн потерялся

2021-06-30 21:39 UTC, NefrNerf commented on code/_macros.dm
> -
Смешно, нажал с телефона commit changes

2021-06-30 21:48 UTC, NefrNerf commented
Готово, оказывается не стоит делать коммиты с телефона

2021-07-01 14:10 UTC, TermService approved these changes

2021-07-01 14:11 UTC, Zert0X approved these changes
Ну вроде всё ОК

2021-07-01 21:47 UTC, TobyThorne approved these changes

2021-07-01 21:49 UTC, merged