Various floor light changes
ChaoticOnyx/OnyxBay pull request #5864
Opened 2021-07-01 20:16 UTC by Artemonim

close #4552
close #5862

<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Не закрытый полом электрический терминал возле APC больше не отображается поверх светящегося пола.
tweak: Общее освещение и светящийся пол в APC теперь в разных группах. Можно устраивать танцпол. 
tweak: Теперь светящемуся полу нужно прямое подключение к электросети. **WIP**
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-01 20:52 UTC, MrMagick2104 commented
> Теперь светящемуся полу нужно прямое подключение к электросети.

Зачем это делать?

2021-07-01 21:16 UTC, Artemonim commented
> > Теперь светящемуся полу нужно прямое подключение к электросети.
> 
> Зачем это делать?

Сейчас его слишком просто крепить. Раз уж закидываю в группу "Оборудование", то чёб не усложнить установку.
Если геймдизам не понравится - откачу.

2021-07-01 21:20 UTC, MrMagick2104 commented
> Сейчас его слишком просто крепить. 

Обычно, ты устанавливаешь много тайлов светопола. 3х3, 5х5, 7х7.
Под каждый проводить проводку - адская боль, которая не нужна. У нас всё на беспроводном электричестве, где подключать напрямую нужно только генераторы и мощные потребители. И, внезапно, светопол нужно вручную монтировать. Почему? Он же потребляет всего 20 ватт.

2021-07-01 21:22 UTC, Artemonim commented
> напрямую нужно только генераторы и мощные потребители.

Звучит логично. Убираю.

2021-07-15 20:37 UTC, TobyThorne commented
Зачем фиксированное количество ударов? Нужно ХП, как у тех же окошек.

2021-08-06 18:33 UTC, MaxFreemen commented
Помогу-ка я автору. @TatarTheBuilder , @TobyThorne , @PlinHost , прошу прощения за беспокойство, нужно ревью ваше.

2021-09-03 05:44 UTC, kcalbCube requested changes
---

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	else if((!powered(power_channel) || ((glow && !on) || (glow && (broken() || !anchored)))))
нихуя не понял

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	if(anchored)
```suggestion
	layer = anchored ? TURF_LAYER : ABOVE_TILE_LAYER
```

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +				switch(intensity_choice)
ты размазал копипасту на три ветки свича.
убери свитч, а light_intensity уже свичай

а с мессаджом просто заверни
visible_message(SPAN("notice", "\The [user] change \the [src] intensity to [intensity_choice]."))

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +		return
не нужно

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
>  			return
не нужно

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	else
убери else, он здесь просто лесенку создает.

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	else overlays.Cut()
```suggestion
	else 
	    overlays.Cut()
```

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +		var/crack
это зачем, можно во внутрь цикла перенести

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +		while(cracks < damaged)
for никак?

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +			var/image/I = image("damaged[crack]")
а оно работает? иконку не нужно прописывать разве

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	if(glow)
```suggestion
	if(!glow)
	    return
```
лесенка

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +		if(!broken())
```suggestion
		if(broken())
		    return
```
лесенка

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +			switch(light_intensity)
если бы само слово хранил то можно бы было код упростить

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	if(health <= shield)
```suggestion
	return health <= shield
```

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	if(isnull(light_colour))
```suggestion
	if(light_colour)
            return light_colour
```

2021-09-03 05:44 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +/obj/machinery/floor_light/proc/layers_check()
смешное

2021-09-03 18:31 UTC, TermService commented
как бы смешно не было но куб правильно расписал

2021-09-06 16:54 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +				switch(intensity_choice)
Первый свитч нужен для радиального меню

2021-09-07 03:28 UTC, kcalbCube requested changes
всё ещё плохо

2021-09-07 03:28 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +				switch(intensity_choice)
..
```
					switch(intensity_choice)
						...
					visible_message(SPAN("notice", "\The [user] change \the [src] intensity to [intensity_choice]."))
					update_brightness()
					playsound(src.loc, "button", 50, 1)
```
это заменит весь свитч

2021-09-07 03:28 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +				return
```suggestion
```

2021-09-07 03:28 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +				return
```suggestion
```

2021-09-07 03:28 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +				return
```suggestion
```

2021-10-04 00:59 UTC, HonkyDonky commented
Одобрено, но в текущем виде его тяжело будет принять. Нужны поправки. К тому же тут конфликты. Последняя активность автора в этом ПРе было 1 июля.
Закрываю.

2021-10-04 01:05 UTC, DarkHunter7756 commented
Зачем закрывать одобренный ПР? Его нужно чинить, а не закрывать.

2021-10-04 01:08 UTC, HonkyDonky commented
> Зачем закрывать одобренный ПР? Его нужно чинить, а не закрывать.

Чтобы не висел и не мозолил глаза, конечно. 
Если автор воскреснет и захочет таки его починить - он придёт и откроет его обратно. Проблем у него с этим не будет.

Ещё вопросы?

2021-10-14 22:36 UTC, igorsaux commented
открыл по просьбе автора

2021-10-16 13:57 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +			update_brightness()
```suggestion
		else if(must_work != on)
			must_work = on
			update_brightness()
```

2021-10-16 14:01 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +			return
Может для красоты сначала просить починить, а потом включить?

2021-10-16 14:10 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +			return
Там в том и прекол, чтобы можно было дёргать переключатель, даже если пол не работает

2021-10-16 14:22 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +		return
Насчёт звука не уверен, но `update_brightness()` точно можно вынести.
```suggestion
		var/settings_choice = show_radial_menu(user, src, isAI(user) ? ai_settings_options : settings_options, require_near = !issilicon(user))
		playsound(src.loc, "button", 50, 1)
		switch(settings_choice)
			if("Color")
				light_colour = input(user, "Choose your floor light's color:") as color
				playsound(src.loc, "button", 50, 1)
				visible_message(SPAN("notice", "\The [user] change \the [src] color."))
			if("Intensity")
				var/intensity_choice = show_radial_menu(user, src, isAI(user) ? ai_intensity_options : intensity_options, require_near = !issilicon(user))
				playsound(src.loc, "button", 50, 1)
				switch(intensity_choice)
					if("slow")
						light_intensity = 0
						visible_message(SPAN("notice", "\The [user] change \the [src] intensity to slow."))
					if("normal")
						light_intensity = 1
						visible_message(SPAN("notice", "\The [user] change \the [src] intensity to normal."))
					if("fast")
						light_intensity = 2
						visible_message(SPAN("notice", "\The [user] change \the [src] intensity to fast."))
					else
						return
			if("Invert")
				inverted = !inverted
				visible_message(SPAN("notice", "\The [user] inverted \the [src] rhythm."))
			else
				return
		update_brightness()
		return
```

2021-10-16 14:26 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
>  			return
А здесь и правда не нужно, у тебя return после if стоит.

2021-10-16 14:28 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +		return
А здесь он потом из функции выйдет, считай return.

2021-10-16 14:33 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +				return
```suggestion
			if(stat && BROKEN)
				to_chat(user, SPAN("warning", "\The [src] is too damaged to glow."))
			else if(!anchored)
				to_chat(user, SPAN("warning", "\The [src] must be screwed down to glow."))
			else if(stat && NOPOWER)
				to_chat(user, SPAN("warning", "\The [src] is unpowered."))
			return
```

2021-10-16 14:35 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +		must_work = TRUE
Не понял.
```
if(must_work)
    ...
    must_work = TRUE
```
???

2021-10-16 14:36 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +		must_work = FALSE
Аналогично.

2021-10-16 14:37 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +	return
В конце функций можно не писать.

2021-10-16 14:43 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +	while(prob(50))
Я слышал от более опытных разработчиков Оникса, что `sleep()` - плохо. Так что предложу своё, а там как понравится.
```suggestion
/obj/machinery/floor_light/proc/flicker()
    if(must_work || prob(50))
        must_work = !must_work
        update_brightness()
        addtimer(CALLBACK(src, .proc/flicker), rand(1, must_work ? 10 : 5))
```

2021-10-16 14:44 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +	while(prob(50))
Единственный недостаток - он может не сработать ни разу

2021-10-16 14:48 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +/obj/machinery/floor_light/proc/layers_check()
Да, наверно стоит переименовать в `layers_update()`

2021-10-16 14:49 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +			return
Какой переключатель?

2021-10-16 14:50 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +			return
Это настройка мультитулом.

2021-10-16 19:44 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +			return
А. Да, в этом месте будет лучше

2021-10-16 19:51 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +	while(prob(50))
И этот недостаток критичен, так как сам фликер уже вызывается с определённым шансом

2021-10-28 16:03 UTC, igorsaux commented on code/game/machinery/floor_light.dm
> +	crack_layer = layer + 0.002
🤢

2021-10-28 16:05 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +	crack_layer = layer + 0.002
В душе понимаю, что костыль, но не понял, как по нормальному. Подскажешь?

2021-10-28 16:11 UTC, igorsaux commented on code/game/machinery/floor_light.dm
> +	crack_layer = layer + 0.002
- Сделать что-то типо `ABOVE_TILE_DECAL_LAYER` в файле слоёв, найти куда впихнуть и проверить что-бы соседние слои нормально отображались.

`light_layer` - это что? Освещение вокруг светопола или просто спрайт который накладывается?
Если освещение - у него есть свой слой (и работает через `set_light`), если спрайт - почему нельзя наложить оверлеем?
Крэки тоже должны оврлеем накладываться

2021-11-06 19:50 UTC, Artemonim commented
Всё работает. Дайте мёрдж, пока снова stale не повесили ＞﹏＜

2021-12-26 08:54 UTC, Zert0X commented
https://user-images.githubusercontent.com/42303535/147403436-df0461d2-af00-4bbf-8bde-8ca3e56bf999.mp4

Ну тесты есть

2021-12-26 08:55 UTC, Zert0X submitted a review, later dismissed

2021-12-26 11:51 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +var/floor_light_cache = list()
Где, /list/, брат?

2021-12-26 13:53 UTC, Zert0X commented on code/game/machinery/floor_light.dm
> +var/floor_light_cache = list()
О а слона то я и не увидел

2022-01-03 11:36 UTC, PlinHost requested changes, later dismissed

2022-01-03 11:36 UTC, PlinHost commented on code/game/machinery/floor_light.dm
> +		Destroy()
Автор явно нихуя не понимает в сборщике мусора. У нас это немного описано в [гайде](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2), но скорее всего понадобится помощь опытного кодера.

2022-01-03 15:24 UTC, Doster-d requested changes

2022-01-03 15:24 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +		return
Тебе нужно было выше прописать qdel(src) если хотел удалить предмет.

2022-01-06 08:33 UTC, kcalbCube requested changes
индусы

2022-01-06 08:33 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	var/const/broken_light_colour = "#FFFFFF"
мы используем макросы

2022-01-06 08:33 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +	. = ..()
лишнее

2022-01-06 08:33 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +				return
вы ебанулись?
```suggestion
			if(stat & BROKEN)
				to_chat(user, SPAN("warning", "\The [src] is too damaged to glow."))
				return
			if(!anchored)
				to_chat(user, SPAN("warning", "\The [src] must be screwed down to glow."))
				return
			if(stat & NOPOWER)
				to_chat(user, SPAN("warning", "\The [src] is unpowered."))
				return
```

ну и код отрефакторить нужно

2022-01-06 08:33 UTC, kcalbCube commented on code/game/machinery/floor_light.dm
> +		if(!broken())
всё ещё актуально

2022-01-06 10:16 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +	var/const/broken_light_colour = "#FFFFFF"
Как бы я ненавидел куба, но он тут прав.

2022-01-06 10:26 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +	. = ..()
```suggestion
	..()
```

2022-01-06 10:26 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +			else
А мы не можем отказаться от этого?

2022-01-06 10:26 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +				return
Политкорректно переписал предложение Куба.

2022-01-06 10:26 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +				return
Красиво будет, если тут введешь флаг на то, что пол не работает, и если одна из твоих проверок подняла флага, то ты ретурнешь, иначе код уродски выглядит

2022-01-06 11:10 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +			else
Так это даёт три дополнительных варианта свечения

2022-01-06 11:10 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +	. = ..()
Может целиком `New()` вырезать?

2022-01-06 11:10 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +	. = ..()
А зачем он вообще нужен?

2022-01-06 11:11 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +			else
Не, я про else, почему бы не отказаться от него?

2022-01-06 11:19 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +			else
Чтобы не проигрывать звук и не тратиться на вызов update_brightness().

2022-01-06 11:27 UTC, Doster-d commented on code/game/machinery/floor_light.dm
> +				return
А там же ничего дальше нет, ретурны не нужон

2022-01-06 11:28 UTC, O0oMaximo0O commented on code/game/machinery/floor_light.dm
> +				return
А нельзя, как я выше предлагал? Этот же кусок. Только с заменой на биты, конечно. Кстати, а тут конец функции. Можно и вовсе без `return`.

2022-01-06 17:05 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +				return
Вы о чём?
Пол может не работать по нескольким причинам. На каждую из причин свой флаг. В данном месте система уже знает, что пол не работает, но должна объяснить пользователю, по какой причине она не работает.
Убираю ретурны, чтобы игроку сразу выводился полный перечень проблем.

2022-01-06 22:29 UTC, kcalbCubeFork requested changes
код навевает мне воспоминания о моем первом ПРе

2022-01-06 22:29 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +	#define LIGHT_LAYER DECAL_LAYER
дефайны объявляются в начале файла и андефаются в конце.

2022-01-06 22:29 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +			if(stat == 2)
Друг ты не так все делаешь!
```suggestion
			if(stat & NOPOWER)
```
stat - битовое поле.
NOPOWER - битовый флаг.
допустим в двоичной системе
stat             = 00110010
NOPOWER = 00000010
бит 1 что в NOPOWER так же есть и в stat, значит в статусе установлено что машинери без энергии.
для того что бы проверить битовое поле на содержание битового флага в коде используется битовый and. по стандарту A & B
битовый and означает что результат будет состоять из тех битов что есть в обеих операндах.

а ты заменил stat && NOPOWER на stat == NOPOWER, из-за чего иф сработает только когда машинери только обесточена и нихуя другого с ней не происходит, да ещё и макрос раскрыл ебанаврот

2022-01-06 22:29 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +	#define LIGHT_LAYER DECAL_LAYER
и этот макрос не имеет смысла

2022-01-06 22:29 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +	#define MAX_HEALTH 60
и название поменяй, че нибудь типа
```suggestion
	#define FLOOR_LIGHT_MAX_HEALTH 60
```

2022-01-06 22:29 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +	#define BROKEN_LIGHT_COLOUR "#FFFFFF"
аналогично, меняй названия макросам

2022-01-06 22:34 UTC, kcalbCubeFork commented
> 2021-12-26.11-10-48.mp4 
> Ну тесты есть

ты чё этой анскильной хуйней пользуешься?
просто верб Spawn путь

2022-01-06 22:37 UTC, kcalbCubeFork commented
ну и концепция мигания основанная на рандоме это муть какая-то. дискотеку не сделать, просто мерцать будет в разнобой. нужно привязать это к тику и интенсивности иначе смысла нема этой залупы

2022-01-06 23:10 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +			if(stat == 2)
А, так это как вектор булевых переменных работает! Теперь стало ясно, зачем оно так!

Но, кстати, как оно есть сейчас всё равно работает как задумано.

2022-01-06 23:11 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +	#define MAX_HEALTH 60
Да, забыл что дефайны глобальные :|

2022-01-06 23:11 UTC, Artemonim commented on code/game/machinery/floor_light.dm
> +	#define LIGHT_LAYER DECAL_LAYER
А зачем андефаить? О_о

2022-01-06 23:13 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +			if(stat == 2)
> А, так это как вектор булевых переменных работает! Теперь стало ясно, зачем оно так!
> 
> Но, кстати, как оно есть сейчас всё равно работает как задумано.

не работает.
а если будет не только NOPOWER задан, а например ещё и BROKEN?
получается 00000011, что не равно 00000010

2022-01-06 23:14 UTC, Artemonim commented
> ну и концепция мигания основанная на рандоме это муть какая-то. дискотеку не сделать, просто мерцать будет в разнобой

Мигание только у сломанного пола. После принятия ПРа выведу функцию отдельно и запилю мерцание разбитых ламп. Была идея сделать изменение свечения синхронно анимации, но сказали, что будет дорого каждый тик свет пересчитывать.

2022-01-07 00:13 UTC, kcalbCubeFork commented on code/game/machinery/floor_light.dm
> +	#define LIGHT_LAYER DECAL_LAYER
что бы конфликтов с другими файлами не было полюбасик

2022-01-07 00:16 UTC, kcalbCubeFork commented
> > ну и концепция мигания основанная на рандоме это муть какая-то. дискотеку не сделать, просто мерцать будет в разнобой
> 
> Мигание только у сломанного пола. После принятия ПРа выведу функцию отдельно и запилю мерцание разбитых ламп. Была идея сделать изменение свечения синхронно анимации, но сказали, что будет дорого каждый тик свет пересчитывать.

в чем проблема запилить мигание на тиках не знаю...

2022-04-06 20:11 UTC, Artemonim commented
К мёрджу готово. Пойду обратно в гроб...

2022-04-06 20:19 UTC, HonkyDonky approved these changes
ребята давайте просто закроем глаза на недочёты и примем работу человека который старался и старается ради нашего билда

2022-04-06 20:20 UTC, igorsaux approved these changes

2022-04-06 20:26 UTC, Doster-d approved these changes
Потом переделаем.
Слипы это пиздец

2022-04-18 16:38 UTC, merged

2022-04-19 20:36 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/164091079-f2491b6a-4e19-4c2c-914f-1e9c7602a29b.png)
![image](https://user-images.githubusercontent.com/45202681/164091161-8677d44d-5be5-4742-a951-25bc1337b671.png)
блять вы чё первое апреля закончилось уже