Формы для иссуев
ChaoticOnyx/OnyxBay pull request #5879
Opened 2021-07-02 14:15 UTC by igorsaux

2021-07-02 14:49 UTC, TermService approved these changes

2021-07-02 16:05 UTC, quardbreak requested changes

2021-07-02 16:05 UTC, quardbreak commented on .github/ISSUE_TEMPLATE/bug.yml
> +      value: "## Характеристики"
`value: "Характеристики"`

2021-07-02 16:27 UTC, Epicus7 reviewed
Вот что было:

![image](https://user-images.githubusercontent.com/5204667/124303454-24c7f580-db6b-11eb-9184-c90671470295.png)

Вот что стало:

![image](https://user-images.githubusercontent.com/5204667/124303482-301b2100-db6b-11eb-9e3b-d3d37b80f20f.png)

1. Секция с характеристиком расползлась на полэкрана - раньше было компактнее
2. Как заполнять воспроизведение - стало непонятным. Раньше там явно был пример пошаговости:

![image](https://user-images.githubusercontent.com/5204667/124303573-4c1ec280-db6b-11eb-90eb-bc7bcb85e33b.png)

3. Раздел со скриншотами пропал. Понятно, что их можно добавить в описание, но раньше в форме был явный намек на то, что скриншоты нужны.

Мне в целом не нравится идея и мне кажется, что лучше оставить старый вариант.

2021-07-12 14:59 UTC, kreeperHLC approved these changes

2021-07-13 20:35 UTC, NefrNerf approved these changes

2021-07-14 05:59 UTC, closed without merging