Микрофиксы карты Исхода
ChaoticOnyx/OnyxBay pull request #5908
Opened 2021-07-04 03:19 UTC by hard-res3t

Починил доступ к гравгену. Не было доступа на двери.
Переместил стенку чтобы выход с лестницы не выходил в стенку.
![image](https://user-images.githubusercontent.com/59255670/124371857-92207700-dc8e-11eb-9b37-f897e2d155fd.png)
Сделал воксам на корабле и станции азот.
Заменил сломанные текстуры в голодеки снежного леса на нормальные.
![image](https://user-images.githubusercontent.com/59255670/124371893-d6ac1280-dc8e-11eb-8120-dbdfdb3d0536.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
maptweak: Микро-багфиксы карты Исхода.
maptweak: Заменил кислород на азот на базе воксов и корабле.
/🆑
```

</details>

close #5892
close #5839
close #2623
close #1947
close #2268

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-04 03:43 UTC, DarkHunter7756 commented
Пофиксишь в этом ПРе?
#5285

2021-07-04 06:58 UTC, NefrNerf commented
Азотная атмосфера на станции воксов не затрагивает ЦК? Чинили вроде и раньше, только вот ЦК тоже азотом заполнялся.

2021-07-04 12:19 UTC, hard-res3t commented
> Азотная атмосфера на станции воксов не затрагивает ЦК? Чинили вроде и раньше, только вот ЦК тоже азотом заполнялся.

Ну по идее не должна. Не знаю как делали в том ПРе, но я заменил каждую клетку аналогичной с азотом. Не знаю с чего бы ей появиться на ЦК, но я проверю чуть позже.

2021-07-04 13:10 UTC, hard-res3t commented
Азот только у воксов
![image](https://user-images.githubusercontent.com/59255670/124386256-439cc800-dce2-11eb-8a06-685ccbe80856.png)

2021-07-04 13:20 UTC, hard-res3t commented
Пример фикса #5285
![image](https://user-images.githubusercontent.com/59255670/124386539-a3e03980-dce3-11eb-9aca-69db87798a93.png)

2021-07-04 14:35 UTC, TermService submitted a review, later dismissed

2021-07-04 14:38 UTC, hard-res3t commented
Теперь точно закончил.

2021-07-04 14:40 UTC, hard-res3t commented
> maptweak(exodus-law-office) add tablet and shredder

![image](https://user-images.githubusercontent.com/59255670/124389236-ed825180-dcee-11eb-8944-906b36aecf8a.png)

2021-07-04 20:06 UTC, BooJ1K commented
Заделать полом космоклетку, она ломает гравитацию на  уровень ниже.
Первая картинка, что надо изменить, вторая это место куда ведёт "космо клетка"

[Космо тайл ИИ](https://user-images.githubusercontent.com/47336771/124397739-e9305580-dd3b-11eb-9d85-a876ed5358b5.png)
![Космо тайл ИИ низ](https://user-images.githubusercontent.com/47336771/124397759-09601480-dd3c-11eb-8cff-68c80c506dcc.png)

2021-07-04 20:09 UTC, TatarTheBuilder commented
> Заделать полом космоклетку, она ломает гравитацию на уровень ниже.

тайлы сверху никак не влияют на гравитацию

2021-07-04 20:14 UTC, BooJ1K commented
> > Заделать полом космоклетку, она ломает гравитацию на уровень ниже.
> 
> тайлы сверху никак не влияют на гравитацию

Тогда нужно добавить зону с гравитацией на второй пикче, левее от метки, её там по какой-то причине нет.

2021-07-04 20:16 UTC, hard-res3t commented
Проверю что там с гравитацией тогда чуть позже. Если зоны и правда нет, то починю.
Единственное что с этой дыркой в полу надо что-то сделать. Заделать её или наоборот открыть 2 другие?

2021-07-04 20:17 UTC, BooJ1K commented
> Проверю что там с гравитацией тогда чуть позже. Если зоны и правда нет, то починю.
> Единственное что с этой дыркой в полу надо что-то сделать. Заделать её или наоборот открыть 2 другие?

Заделать, так как ниже собственно пик 2

2021-07-04 20:19 UTC, hard-res3t commented
Логично. Возможность упасть туда было бы не самым хорошим решением с точки зрения дизайна. Закрою в общем дырку.

2021-07-05 13:39 UTC, hard-res3t commented
Глянул насчет клетки с гравитацией. Все там нормально. Если и ломает, то так задумано. Ничего изменять не буду. Жду ревью.

2021-07-07 00:03 UTC, TobyThorne requested changes
- Деревьям в снежном голодеке нужно сдвиг сделать, по примеру имеющихся.
- В пустыне должен быть holofloor, а не simulated.
- Какой-то незадокументированный планшет у АВД откуда взялся?

2021-07-07 01:45 UTC, hard-res3t commented
Планшет добавлен по #5120 и закрываю его в другом своем ПРе #5844.
Сейчас понимаю что вышло все крайне неудобно и в следующий раз фиксы надо сразу на 2 карты лить в одном ПРе.
Все остальное исправлю.

2021-07-07 22:43 UTC, TobyThorne commented
> фиксы надо сразу на 2 карты лить в одном ПРе.

![image](https://user-images.githubusercontent.com/45202681/124837569-e1c0b480-dfa6-11eb-8bd1-2c0d8dbde5b7.png)

Лучше отдельно. И не лить в одном ПРе смесь из фиксов с фичами.

2021-07-09 16:57 UTC, hard-res3t commented
Старый песок. Новые текстуры.
![image](https://user-images.githubusercontent.com/59255670/125112505-eb096880-e0ef-11eb-88f6-1ef48685ad5a.png)

2021-07-20 06:20 UTC, TobyThorne approved these changes

2021-07-20 08:23 UTC, TatarTheBuilder approved these changes
допустим

2021-07-20 08:24 UTC, Doster-d approved these changes
Татарин говорит, что клево.

2021-07-20 08:25 UTC, merged