Пинпоинтер на локации.
ChaoticOnyx/OnyxBay pull request #5909
Opened 2021-07-04 04:53 UTC by Doster-d

Добавлен пинпоинтер и бесплатный автомат с ними.
Данная фича поможет новичкам с ориентации на мапе.
В автомате 25 пинпоинтеров.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлен пинпоинтер на самые популярные локации и бесплатный автомат с ними.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-04 05:10 UTC, kcalbCube commented
а почему бесплатный?

2021-07-04 14:29 UTC, Doster-d commented
> а почему бесплатный?

Новички не могут понять как платить.

2021-07-04 14:43 UTC, TermService submitted a review, later dismissed

2021-07-04 14:53 UTC, DarkHunter7756 commented
> Новички не могут понять как платить.

Новички не смогут понять, 
что он есть, 
как найти его,
как он работает ( ͡° ͜ʖ ͡°)

2021-07-04 20:56 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/124399314-38b65780-dd23-11eb-95c5-b06dc827b0ee.png)
Теперь новым игрокам будет спавниться в левом кармашке.

2021-07-20 14:19 UTC, Doster-d commented
Я покакал.

2021-07-21 21:08 UTC, Doster-d commented on code/game/jobs/job_controller.dm
> +#define NEW_PLAYER_WAYFINDING_TRACKER 7
```suggestion
#define NEW_PLAYER_WAYFINDING_TRACKER 21
```

2021-07-26 15:18 UTC, TobyThorne requested changes

2021-07-26 15:18 UTC, TobyThorne commented on code/game/machinery/wayfinding.dm
> +	desc = "A machine given the thankless job of trying to give wayfinding pinpointers. They point to common locations."
Что здесь написано? Моя не понимать.

2021-07-26 15:29 UTC, Doster-d commented on code/game/machinery/wayfinding.dm
> +	desc = "A machine given the thankless job of trying to give wayfinding pinpointers. They point to common locations."
Это с ТГ описание, вопросы?

2021-07-27 08:54 UTC, Zert0X commented on code/game/machinery/wayfinding.dm
> +	desc = "A machine given the thankless job of trying to give wayfinding pinpointers. They point to common locations."
"Машина получившая бескорыстную работу в виде попыток выдать путеводные пинпоинтеры. Они указывают на обычные локации."
Как-то так если я не ошибся

2021-08-21 00:54 UTC, Doster-d commented on code/game/machinery/wayfinding.dm
> +	desc = "A machine given the thankless job of trying to give wayfinding pinpointers. They point to common locations."
Машины выполняющая неблагодарную работу в выдаче путеводных пинпоинтеров. Они указывают на часто используемые места.

2021-08-21 00:55 UTC, Doster-d commented on code/game/machinery/wayfinding.dm
> +	name = "PTech"
```suggestion
	name = "wayfinding pinpointer vending machine"
```

2021-09-01 05:40 UTC, TobyThorne approved these changes
Оставляю всё на совести второго, поставившего галочку.

2021-09-03 18:30 UTC, TermService commented on code/game/machinery/wayfinding.dm
> +	desc = "A machine given the thankless job of trying to give wayfinding pinpointers. They point to common locations."
A machine that does a thankless job - gives out a pinpointer pointing to popular locations in the station. мб так лучше?

2021-09-07 10:21 UTC, Doster-d commented on code/game/machinery/navbeacon.dm
> +				location = get_area(src)?.name | "Unknown"
```suggestion
				location = get_area(src)?.name || "Unknown"
```

2021-09-24 11:55 UTC, Doster-d commented
Какой стайле, все готово, Фронтир сделает другой.

2021-09-24 12:20 UTC, TermService approved these changes

2021-09-24 12:24 UTC, Zert0X approved these changes

2021-09-24 12:27 UTC, merged