Исправление дюпа пирогов
ChaoticOnyx/OnyxBay pull request #5935
Opened 2021-07-05 14:17 UTC by Gr13v0us

Исправил дюп пирогов в печке

Теперь когда ты суёшь кусок (slice) чего-либо, то печка (oven) не принимает его, тем самым не давая возможность заново создать полноценный пирог

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Исправлен дюп пирогов через печку (oven)
/🆑
```

</details>
close #5545 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-05 14:26 UTC, Zert0X approved these changes

2021-07-15 20:58 UTC, TobyThorne requested changes
Не пойдёт. Один баг пофикшен, а взамен - получили новые. Теперь нельзя загриллить ломтик хлеба или сунуть кусок торта во фритюр.

2021-09-01 05:37 UTC, TobyThorne commented
У ПРа конфликты. А ещё он больше двух недель висит с ченж реквестом. 

Пациент скорее протух, чем жив. Если автор оживёт - пусть переоткроет.

2021-09-01 05:37 UTC, closed without merging

2021-09-09 18:13 UTC, Gr13v0us commented
Мне лень

2021-09-09 18:23 UTC, kreeperHLC commented
> Мне лень

А нам лень давать контрибутора человеку, который одну команду в гите прожать

2021-09-13 16:54 UTC, Gr13v0us commented
> > Мне лень
> 
> А нам лень давать контрибутора человеку, который одну команду в гите прожать

XP
Я не хочу заного фиксить баги