fix(virology): Fixed mixing blood-blood, antibodies-antibodies
ChaoticOnyx/OnyxBay pull request #5953
Opened 2021-07-06 16:40 UTC by Oubifx

Два фикса в одном ПР-е из-за особенностей текущего кода вирусологии.

fix #5932 
fix #5946

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
bugfix: Поправлено смешивание антител в ёмкостях. Теперь их часть не пропадает.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-06 17:24 UTC, TobyThorne commented
Когда ради маленького фикса эдж-кейса приходится переписывать половину билда - это костыль. Какой ещё bloodbase?

2021-07-06 17:54 UTC, Oubifx commented
bloodbase это базовый класс реагентов, в которых могут содержаться вирусы и антитела. Если бы этого "костыля", который не костыль, не было, то мне пришлось бы дублировать код, что действительно было бы костылем. По этому если оно затрагивает столько файлов, то это еще не означает что это костыльное решение. Базовые классы в ООП это настолько норма, что её не описать словами. Аналогично реализован и мой ПР со стаканьем тарелок, там тоже есть базовый класс который позволяет всем дочерним стакаться.  Я конечно понимаю что в коде сс-ки они встречаются не так часто как хотелось бы, но всё же о базовых классах `/datum/reagent`, `/obj/item/device/assembly`, `/obj/item/toy` и т.п. я думаю ты прекрасно знаешь. Ну, а если всё же считаешь это лютым костылем, то и код студии BIsim, которая продаёт почти всем армиям мира симулятор VBS за огромные суммы, можешь тоже считать костылем. В общем нет, это не костыль, это необходимость.

<details>
  <summary>СпойлерОк</summary>
  
А еще в планах наконец-то сделать нормальную систему с антителами. Там уж точно без этого класса не обойтись
Сейчас код вирусологии это настолько Г, что слов нет. А код антител можно описать в четыре строчки

```dm
/datum/reagent/bloodbase/antibodies/affect_blood(mob/living/carbon/M, alien, removed)
	if(src.data)
		M.antibodies |= src.data["antibodies"]
	..()
```
  
</details>

2021-07-08 19:00 UTC, Oubifx commented
Плашка улучшения лишняя, про гемдизайн не уверен. А так обычный багфикс, возвращающий нормальное смешивание кровь-кровь и антитела-антитела, которым почему-то забыли добавить смешивание.

2021-07-08 19:40 UTC, Zert0X commented
Мне кажется или тут вставлен костылище?

2021-07-08 19:48 UTC, kcalbCube commented
> bloodbase это базовый класс реагентов, в которых могут содержаться вирусы и антитела. Если бы этого "костыля", который не костыль, не было...
банальный вопрос, анальный ответ.

2021-07-08 19:50 UTC, kcalbCube commented
а это точно багфикс?

2021-07-08 19:58 UTC, kcalbCube requested changes
какого-то хуя кровь переименовали, я полтора раза посмотрел в дифе и так и не смог увидеть ту заветную, манящую строку кода где ты что-то изменил, ибо мозг вскипает от этого пиздеца блять. 

Тебе нужен датум для жидкостей хранящих антитела? Ну развивай свою фичу, пусть любая жидкость может хранить антитела. Да хоть через : бери, но не костыльвань же.

2021-07-08 19:58 UTC, kcalbCube commented on code/modules/item_worth/reagents.dm
> +/datum/reagent/bloodbase
ну и нахуя ты переименовал blood в bloodbase?

2021-07-08 20:39 UTC, Oubifx commented
Собственно сам фикс передачи антител к точно такому же веществу и фикс корявого смешивания. Почему-то изначально `get_data()` и `mix_data()` прописана только для крови, а про антитела забыли. Я бы мог просто скопипастить и сделать то же самое для антител ~~в стиле ОниксБей~~, но это явный костыль, усложняющий последующие изменения и понимание кода.
![image](https://user-images.githubusercontent.com/24242919/124985083-affd2b80-e042-11eb-9af1-5722b847c80a.png)
![image](https://user-images.githubusercontent.com/24242919/124985988-c1930300-e043-11eb-8da7-00fc7d4c2cd8.png)

Опять же, не вижу где тут костыль и в чём он заключается, больше конструктива, если можно.
На основе этого фикса, потом будет фича перерабатывающая работу антител, которую сперва должен одобрить геймдиз, иначе ебля не имеет смысла. Подчеркиваю, новый базовый класс не есть частью еще не существующей фичи. Если кого-то тригернуло появление `bloodbase`, то извиняйте, хотя тут не за что извиняться.

2021-07-09 05:47 UTC, kemperhun commented
1. У тебя есть логическое описание класса bloodbase? Что он концептуально может и будет делать, какие классы порождать? Просто я не вижу между кровью и антигенами ничего более общего, чем уже дает класс reagent.
2. Само имя bloodbase нерепрезентативно, потому что из него вообще непонятно, что этот тип делает, что и порождает вопрос 1.
3. Разве антигены могут переносить вирус? Зачем ты добавил на него проверку?

2021-07-09 05:53 UTC, kcalbCube commented
> Собственно сам фикс передачи антител к точно такому же веществу и фикс корявого смешивания. Почему-то изначально `get_data()` и `mix_data()` прописана только для крови, а про антитела забыли. Я бы мог просто скопипастить и сделать то же самое для антител ~в стиле ОниксБей~, но это явный костыль, усложняющий последующие изменения и понимание кода.
> ![image](https://user-images.githubusercontent.com/24242919/124985083-affd2b80-e042-11eb-9af1-5722b847c80a.png)
> ![image](https://user-images.githubusercontent.com/24242919/124985988-c1930300-e043-11eb-8da7-00fc7d4c2cd8.png)
> 
> Опять же, не вижу где тут костыль и в чём он заключается, больше конструктива, если можно.
> На основе этого фикса, потом будет фича перерабатывающая работу антител, которую сперва должен одобрить геймдиз, иначе ебля не имеет смысла. Подчеркиваю, новый базовый класс не есть частью еще не существующей фичи. Если кого-то тригернуло появление `bloodbase`, то извиняйте, хотя тут не за что извиняться.

Я такое называю "шароебство". Удали всё что сделал и скопипасть, всем будет проще.

2021-07-09 09:02 UTC, Oubifx commented
> 1. У тебя есть логическое описание класса bloodbase? Что он концептуально может и будет делать, какие классы порождать? Просто я не вижу между кровью и антигенами ничего более общего, чем уже дает класс reagent.
> 2. Само имя bloodbase нерепрезентативно, потому что из него вообще непонятно, что этот тип делает, что и порождает вопрос 1.
> 3. Разве антигены могут переносить вирус? Зачем ты добавил на него проверку?

1.(2) Название не то что бы говорящие само за себя, согласен. Из общего у них это возможность хранить в себе антигены и вирусы.
3. Имею введу что антигены могут быть с вирусом в одной пробирке в качестве вакцины, так что да. Наличие антигена и вируса в одной пробирке штука реально существующая.

2021-07-09 13:57 UTC, Oubifx commented
@kcalbCube перезалил, мне не впадлу. Правда впадлу потом после таких изменений кодить одно и то же в шести разных местах

2021-07-15 17:46 UTC, Oubifx commented
@TobyThorne ну что там по апруву? Теперь то всё работает как задумывалось и без лишних конструкций

2021-07-15 20:47 UTC, TobyThorne approved these changes
заревертить и забанить всегда успеем

2021-07-16 10:03 UTC, igorsaux approved these changes

2021-07-16 20:29 UTC, merged