Syndicate toolbox fix
ChaoticOnyx/OnyxBay pull request #5954
Opened 2021-07-06 17:00 UTC by Gr13v0us

Исправил вместимость тулбокса синдиката

Добавил значение для вместимости тулбокса синдиката и добавил его самому тулбоксу, теперь он вмещает идеальное количество предметов

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Исправлена вместимость тулбокса Синдиката
/🆑
```

</details>

close #5950 

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-06 17:21 UTC, TobyThorne requested changes

2021-07-06 17:21 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/toolbox.dm
> +	max_storage_space = DEFAULT_SYNDY_BOX_STORAGE
```suggestion
	max_storage_space = 23
```

С помощью base_storage_capacity(4.29) мы получаем значение в 23.03, с лишними тремя сотыми спейса.

2021-07-06 17:26 UTC, Gr13v0us commented on code/game/objects/items/weapons/storage/toolbox.dm
> +	max_storage_space = DEFAULT_SYNDY_BOX_STORAGE
Всмысле? Я всё проверял у себя, всё было нормально

2021-07-06 17:30 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/toolbox.dm
> +	max_storage_space = DEFAULT_SYNDY_BOX_STORAGE
>#define base_storage_capacity(w_class) (7*(w_class-1))
>#define DEFAULT_SYNDY_BOX_STORAGE base_storage_capacity(4.29)
>max_storage_space = DEFAULT_SYNDY_BOX_STORAGE

7 * (4.29 - 1) = 7 * 3.29 = 23.03

2021-07-06 17:34 UTC, Gr13v0us commented on code/game/objects/items/weapons/storage/toolbox.dm
> +	max_storage_space = DEFAULT_SYNDY_BOX_STORAGE
Хорошо, я понял, уже исправил и проверил

2021-07-06 17:41 UTC, TobyThorne approved these changes

2021-07-06 17:41 UTC, igorsaux commented
выглядит как костыль

2021-07-06 17:43 UTC, TobyThorne commented
> выглядит как костыль

Да нормально, у спортивных сумок - вообще вот такое. 
![image](https://user-images.githubusercontent.com/45202681/124644363-fd975e00-deb3-11eb-9911-9632f669f725.png)

2021-07-06 17:44 UTC, Gr13v0us commented
> > выглядит как костыль
> 
> Да нормально, у спортивных сумок - вообще вот такое.
> ![image](https://user-images.githubusercontent.com/45202681/124644363-fd975e00-deb3-11eb-9911-9632f669f725.png)

АХАХАХААХАХАХАХ, я сначала так хотел сделать))

2021-07-06 17:47 UTC, igorsaux commented
> > выглядит как костыль
> 
> Да нормально, у спортивных сумок - вообще вот такое.
> ![image](https://user-images.githubusercontent.com/45202681/124644363-fd975e00-deb3-11eb-9911-9632f669f725.png)

Вот именно что здесь число скалируется от формулы в дефайнах. Я бы лучше тогда сделал так `base_storage_capacity(4)`

2021-07-07 22:37 UTC, igorsaux approved these changes

2021-07-07 22:39 UTC, merged