Исправление генокрадовое
ChaoticOnyx/OnyxBay pull request #5989
Opened 2021-07-07 21:31 UTC by Doster-d

Ебанный рот этого вашего дедфиле

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь не накладываются задания генок при выпивание генореагента.
bugfix: Теперь генокрады, которые выданы через генореагент и дивизион отображаются в итоговом списке антагонистов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-07 21:35 UTC, kreeperHLC approved these changes

2021-07-07 21:36 UTC, kreeperHLC requested changes

2021-07-07 21:36 UTC, kreeperHLC commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, 1, 1, 0, 1, 1) // Ignore equipment and role type for this.
Хотя стоп, чего у тебя кодстайл сломался. А ну быстро как выше сделал

2021-07-07 21:37 UTC, Doster-d commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, 1, 1, 0, 1, 1) // Ignore equipment and role type for this.
Кто?

2021-07-07 21:38 UTC, Doster-d commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, 1, 1, 0, 1, 1) // Ignore equipment and role type for this.
Ясно, готово.

2021-07-07 21:40 UTC, kreeperHLC requested changes

2021-07-07 21:40 UTC, kreeperHLC commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, TRUE, TRUE, FALSE, TRUE, TRUE)
> changeling.add_antagonist(M.mind, ignore_role = TRUE, do_not_equip = TRUE)

2021-07-07 21:40 UTC, Doster-d commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, TRUE, TRUE, FALSE, TRUE, TRUE)
Ok

2021-07-07 21:43 UTC, kreeperHLC requested changes

2021-07-07 21:43 UTC, kreeperHLC commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, ignore_role = TRUE, do_not_equip = TRUE)
```suggestion
	var/datum/antagonist/changeling/changeling = GLOB.all_antag_types_[MODE_CHANGELING]
	changeling.add_antagonist(M, ignore_role = TRUE, do_not_equip = TRUE)
```

2021-07-07 21:44 UTC, kreeperHLC commented
Уж теперь точно справишься

2021-07-07 21:44 UTC, kreeperHLC approved these changes
Дедфиля круто

2021-07-07 21:45 UTC, Doster-d commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, ignore_role = TRUE, do_not_equip = TRUE)
Комментарий убил, плохой человек :(

2021-07-07 21:45 UTC, kreeperHLC commented on code/game/gamemodes/changeling/powers/division.dm
> +	a.add_antagonist(M, ignore_role = TRUE, do_not_equip = TRUE)
> Комментарий убил, плохой человек :(

😎

2021-07-07 21:48 UTC, kreeperHLC requested changes
Исправь тогда уж и выше рыр

2021-07-07 21:53 UTC, kreeperHLC approved these changes

2021-07-09 00:13 UTC, kcalbCube approved these changes
![image](https://user-images.githubusercontent.com/43304650/125005095-427ee880-e09e-11eb-872d-2f5bc1a4ebc0.png)

2021-07-15 20:01 UTC, TobyThorne approved these changes

2021-07-15 20:04 UTC, merged