Свечение есвордов
ChaoticOnyx/OnyxBay pull request #5993
Opened 2021-07-08 11:48 UTC by Oubifx

Добавил свечение всем есвордам, в том числе даггеру, пиратскому мечу и игрушке в виде есворда. Есвордам с голодеки свечение не дал из-за ненадобности, свет не будет видно при всех раскладах.
![image](https://user-images.githubusercontent.com/24242919/124915922-c1224a00-dffa-11eb-8e67-b4925fbbe145.png)

close #5038

<details>

```yml
🆑Oubi
rscadd: Есворды теперь излучают свет в темноте
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-09 00:25 UTC, kcalbCube submitted a review, later dismissed

2021-07-10 03:46 UTC, TobyThorne requested changes

2021-07-10 03:46 UTC, TobyThorne commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/brightness_color // color of light when on
Ужасная копипаста. Переменные кроме brightness_color, max_bright и outer_range вообще не нужны. spam_flag нигде не использован.

2021-07-10 03:46 UTC, TobyThorne commented on code/game/objects/items/toys.dm
> +	var/brightness_color = "#4de4ff" // color of light when on
Эти переменные вообще не нужны.

2021-07-10 03:46 UTC, TobyThorne commented on code/modules/paperwork/pen.dm
> +	var/brightness_color = "ff5959"
И это всё не нужно.

2021-07-13 16:26 UTC, igorsaux submitted a review, later dismissed

2021-07-13 18:46 UTC, TobyThorne requested changes
Названия переменных - всё ещё копипаста из фонариков. Вместо flashlight хотя бы active.

2021-07-14 08:55 UTC, Oubifx commented
@igorsaux @TobyThorne изменил название переменных, можно апрувать

2021-07-15 21:37 UTC, TobyThorne commented on code/game/objects/items/weapons/melee/energy.dm
> +	set_light(active_max_bright, null, active_outer_range, null, brightness_color)
```suggestion
	set_light(l_max_bright = active_max_bright, l_outer_range = active_outer_range, l_color = brightness_color)
```

2021-07-15 21:37 UTC, TobyThorne commented on code/modules/paperwork/pen.dm
> +	set_light(active_max_bright, null, active_outer_range, null, brightness_color)
```suggestion
	set_light(l_max_bright = active_max_bright, l_outer_range = active_outer_range, l_color = brightness_color)
```

2021-07-15 21:37 UTC, TobyThorne commented on code/game/objects/items/toys.dm
> +			set_light(active_max_bright, null, active_outer_range, null, brightness_color)
```suggestion
			set_light(l_max_bright = active_max_bright, l_outer_range = active_outer_range, l_color = brightness_color)
```

2021-07-15 23:48 UTC, igorsaux approved these changes

2021-07-19 06:39 UTC, TobyThorne approved these changes

2021-07-19 06:40 UTC, merged