Vamp
ChaoticOnyx/OnyxBay pull request #5996
Opened 2021-07-08 14:29 UTC by Zert0X

- "Blood Heal" - **ничего не трогал** в связи с ребалансом боёвки и огнестрела, властелин ночи теперь сосёт бибу если увеличить задержку даже на пол секунды
- "Hypnotise" - не работает на генках и вампирах.**Так и надо было**
- "Presence" - Снизил расход крови с **_10_** до **_5_**
- "Touch of Life" - Снизил цену с **_50_** до **_30_**
- "Summon Bats" - Ничего не делал, **по хорошему вырезать говнину требую геймдизайн**
- "Chiropteran Screech" - Снизил цену с **_90_** до **_70_**
- "Veil Walking" - **Ничего не делал.**
- "Enthrall" - Снизил цену с **_150_** до **_120_**
- "Toggle Darkvision" - Добавил вампирчику скилл для возможности просмотра порнушки без фонарика
- **Текст о том что тебя укусили и о том что ты ничего не помнишь/что-то помнишь теперь выводится большими буквами**

<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Ребаланс цен на некоторые скиллы для вампира
rscadd: Добавлен скилл на ночное зрение
tweak: Текст о укусе и возможных проблемах стал побольше
/🆑
```

</details>

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-09 05:58 UTC, kreeperHLC requested changes
Всё нормально, но можно было бы стоимость обилок в отдельный вар вынести, чтобы их твикать проще было

2021-07-09 05:58 UTC, kreeperHLC commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	to_chat(T, SPAN("warning",FONT_LARGE("You feel yourself falling into a pleasant dream, from which even a smile appeared on your face.")))
```suggestion
	to_chat(T, SPAN("warning", FONT_LARGE("You feel yourself falling into a pleasant dream, from which even a smile appeared on your face.")))
```

2021-07-09 05:58 UTC, kreeperHLC commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			to_chat(T, SPAN("warning",FONT_LARGE("You remember nothing about the cause of blacked out. Instead, you simply remember having a pleasant encounter with [src.name]")))
```suggestion
			to_chat(T, SPAN("warning", FONT_LARGE("You remember nothing about the cause of blacked out. Instead, you simply remember having a pleasant encounter with [src.name]")))
```

2021-07-09 05:58 UTC, kreeperHLC commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			to_chat(T, SPAN("warning",FONT_LARGE("You remember everything that happened. Remember how blood was sucked from your neck. It gave you pleasure, like a pleasant dream. You feel great. How you reac
```suggestion
			to_chat(T, SPAN("warning", FONT_LARGE("You remember everything that happened. Remember how blood was sucked from your neck. It gave you pleasure, like a pleasant dream. You feel great. How you react to [src.name]'s actions is up to you.")))
```

2021-07-13 07:05 UTC, NefrNerf approved these changes

2021-07-15 00:08 UTC, kreeperHLC approved these changes

2021-07-19 17:39 UTC, TermService approved these changes
нуу в след раз желательно по всему файлу исправлять спаны а не только в той части кода что ты затрагиваешь

2021-07-19 17:40 UTC, merged