Взрывное
ChaoticOnyx/OnyxBay pull request #6008
Opened 2021-07-09 08:22 UTC by Doster-d

Порт системы взрывов с ТГ, по ощущением, увеличивает производительность в 4 раза.

Также теперь Вас будет трести при сильном взрыве.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Взрывы должны происходить, как минимум, вдвое быстрее
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-09 08:31 UTC, kreeperHLC requested changes

2021-07-09 08:31 UTC, kreeperHLC commented on code/__defines/subsystem-priority.dm
> +#define SS_PRIORITY_EXPLOSION      666	// Processing explosion stuff, abnormal number for abnormal stuff
Может тогда повыше и поставить? А ещё пробелы сдохли
![image](https://user-images.githubusercontent.com/14943437/125048199-59c2d380-e0a8-11eb-9ab2-a3e932950dae.png)

2021-07-09 08:31 UTC, kreeperHLC commented on code/__defines/subsystems.dm
> +#define	SS_INIT_EXPLOSIONS      -69
И тут

2021-07-09 08:31 UTC, kreeperHLC commented on code/__defines/subsystems.dm
> +#define SSEXPLOSIONS_THROWS 3
Выровняй

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/atoms.dm
> +	var/explosion_block = 0
Получается теперь некоторые атомы могут снижать силу взрыва?

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/machinery/doors/airlock_presets.dm
> +	explosion_block = 2
Ммм, новая переменная сразу за именем

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/machinery/doors/airlock_presets.dm
> +	explosion_block = 2
А тут уже не за именем

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/machinery/doors/airlock_presets.dm
> +	explosion_block = 2
И опять за именем

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/machinery/doors/airlock_presets.dm
> +	explosion_block = 2
Ну ты понял

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/machinery/doors/blast_door.dm
> +	explosion_block = 3
А вот тут правильно

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/objects/structures/window.dm
> +	var/real_explosion_block //ignore this, just use explosion_block
```suggestion
	var/real_explosion_block // ignore this, just use explosion_block
```
Ммм, а почему?

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/objects/structures/window.dm
> +	//windows only block while reinforced and fulltile, so we'll use the proc
```suggestion
	// windows only block while reinforced and fulltile, so we'll use the proc
```

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/sound.dm
> +	'sound/effects/hull_creaking/creak3.ogg',
```suggestion
	'sound/effects/hull_creaking/creak3.ogg'
```
Запятая смешная, а ситуация страшная

2021-07-09 08:31 UTC, kreeperHLC commented on code/game/sound.dm
>  			if ("female_cough")			soundin = pick(GLOB.f_cough_sound)
Может уберёшь пробелы + поправишь табы?

2021-07-09 08:33 UTC, Doster-d commented on code/game/atoms.dm
> +	var/explosion_block = 0
Это в случае использование "рекурсивной" обработке.

2021-07-09 08:55 UTC, Doster-d commented
Сделал.

2021-07-09 11:10 UTC, Doster-d commented
Дорогая, я случайно увеличил производительность в 7 раз, я думаю.

2021-07-09 11:21 UTC, DarkHunter7756 commented
> Дорогая, я случайно увеличил производительность в 7 раз, я думаю.

А что насчет супермамки? Существенно ускорена обработка взрыва?

2021-07-09 11:22 UTC, Doster-d commented
> А что насчет супермамки? Существенно ускорена обработка взрыва?

Дев: 9, 15, 21, 15 за 12 секунд.
Текущий: 9, 15, 21, 15 за 1 секунду.
Ответ получен?

2021-07-09 11:23 UTC, DarkHunter7756 commented
> Ответ получен?

Мне эти цифры ничего не говорят, но сокращение времени с 12 сек до 1 - весомо и круто

2021-07-09 11:33 UTC, Doster-d commented
> Мне эти цифры ничего не говорят, но сокращение времени с 12 сек до 1 - весомо и круто

![image](https://user-images.githubusercontent.com/63081538/125071946-9f8c9580-e0c2-11eb-8866-0c881b2a0986.png)
Это в центре РнД, показатели: 9, 15, 21, 15

2021-07-12 10:53 UTC, igorsaux requested changes
Я не нашёл где это используется так-что лучше удалить, да и хрень какая-то

2021-07-12 10:53 UTC, igorsaux commented on code/__defines/explosion.dm
> +
```suggestion
```

2021-07-12 10:53 UTC, igorsaux commented on code/__defines/explosion.dm
> +#define EXARG_KEY_SMOKE STRINGIFY(smoke)
```suggestion
```

2021-07-12 11:05 UTC, igorsaux approved these changes

2021-07-12 11:19 UTC, kcalbCube approved these changes
Нормально экономим, на интегралки место будет

2021-07-12 15:22 UTC, kreeperHLC approved these changes

2021-07-12 15:25 UTC, merged