Блок армблейда и гиб фейкового
ChaoticOnyx/OnyxBay pull request #6016
Opened 2021-07-09 17:14 UTC by NefrNerf

Починил гиб фейкового от ЕМП. Проверил баг с его полным отсутствием #5284, но оказалось что он не работает только на апатиков, как это исправить я не знаю.
Добавил арблейду рефлект, как заявлено в описании скилла.

fixes #5458
fixes #5284

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Фейковый армблейд больше не гибается от ЕМП.
bugfix: Добавлен рефлект армблейду, как и заявлено в описании скилла.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-10 03:48 UTC, TobyThorne commented on code/game/gamemodes/changeling/helpcode.dm
> +	mod_shield = 2.5
Блокирование выстрелов армблейду не нужно. Исправить надо как раз описание.

2021-07-10 09:25 UTC, NefrNerf commented
Поправил описание, убрал блок. Не нужен ему рефлект, ну и ладно ¯\_(ツ)_/¯

2021-07-15 19:58 UTC, TobyThorne requested changes

2021-07-15 19:58 UTC, TobyThorne commented on code/game/gamemodes/changeling/modularchangling.dm
> +	helptext = "We may retract our armblade by dropping it. Do not deflect projectiles."
```suggestion
	helptext = "We may retract our armblade by dropping it."
```

2021-07-15 19:58 UTC, TobyThorne commented on code/modules/augmentation/prosthetic/prosthetic.dm
> +	if (!prosthetic || !organ || !isProsthetic(prosthetic))
```suggestion
	if(!prosthetic || !organ || !isProsthetic(prosthetic))
```

2021-07-15 19:58 UTC, TobyThorne commented on code/modules/augmentation/prosthetic/prosthetic.dm
> +	if (istype(prosthetic,/obj/item/weapon/melee/prosthetic))
```suggestion
	if(istype(prosthetic, /obj/item/weapon/melee/prosthetic))
```

2021-07-15 19:58 UTC, TobyThorne commented on code/modules/augmentation/prosthetic/prosthetic.dm
> +				if (O.owner.l_hand)
```suggestion
				if(O.owner.l_hand)
```

2021-07-15 19:58 UTC, TobyThorne commented on code/modules/augmentation/prosthetic/prosthetic.dm
> +				if (O.owner.r_hand)
```suggestion
				if(O.owner.r_hand)
```

2021-07-16 12:48 UTC, NefrNerf commented
Поправил код стайл, готово

2021-07-19 06:42 UTC, TobyThorne commented on code/modules/augmentation/prosthetic/prosthetic.dm
> +	if(istype(prosthetic,/obj/item/weapon/melee/prosthetic))
```suggestion
	if(istype(prosthetic, /obj/item/weapon/melee/prosthetic))
```

2021-07-19 06:42 UTC, TobyThorne commented on code/modules/augmentation/prosthetic/prosthetic.dm
> +/obj/item/weapon/melee/prosthetic/bio/attach_prosthetic(prosthetic , organ)
```suggestion
/obj/item/weapon/melee/prosthetic/bio/attach_prosthetic(prosthetic, organ)
```

2021-07-19 18:37 UTC, TermService approved these changes

2021-07-20 05:48 UTC, TobyThorne approved these changes

2021-07-20 05:49 UTC, merged