Corgi hats tweaks
ChaoticOnyx/OnyxBay pull request #6021
Opened 2021-07-10 11:47 UTC by No-Tips

Добавил УИ инвентаря корги. Теперь одеть-снять шляпу можно лишь через него.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Теперь шляпы для корги можно одеть-снять через инвентарь питомца (хелп->на себя).
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-10 11:49 UTC, NefrNerf commented
Может давай без инвентаря, что-то другое, инвентарь у мобов - сомнительная штука, смешного не вызовет?

2021-07-10 11:50 UTC, Zert0X commented
> Может давай без инвентаря, что-то другое, инвентарь у мобов - сомнительная штука, смешного не вызовет?

У монкеев же есть.-.

2021-07-10 11:51 UTC, NefrNerf commented
Ну так мартышки у нас недалеко от хуманов ушли, а корги вроде симплмобы?

2021-07-10 11:53 UTC, No-Tips commented
У попуги есть инвентарь. На будущее - я собираюсь впилить возможность одеть и одежду какую-то на корги. У нас есть файл, в котором есть спрайты.

2021-07-13 16:25 UTC, igorsaux requested changes

2021-07-13 16:25 UTC, igorsaux commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +/mob/living/simple_animal/corgi/show_inv(mob/user as mob)
```suggestion
/mob/living/simple_animal/corgi/show_inv(mob/user)
```

2021-07-13 16:25 UTC, igorsaux commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +						hat.loc = src.loc
```suggestion
						hat.loc = loc
```

2021-07-13 16:25 UTC, igorsaux commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +
```suggestion
```

2021-07-13 17:06 UTC, quardbreak commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +						hat.loc = src.loc
лучше forceMove  использовать

2021-07-19 18:09 UTC, TermService approved these changes

2021-08-03 15:34 UTC, kreeperHLC approved these changes

2021-08-03 15:34 UTC, igorsaux approved these changes

2021-08-13 16:46 UTC, merged