Взлом шкафчиков мечами
ChaoticOnyx/OnyxBay pull request #6024
Opened 2021-07-10 14:08 UTC by NefrNerf

Добавил возможность взлома ящиков для энерго-меча, дуала и воксовской сабли.

fixes #2487

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Добавил возможность взламывать ящики для энерго-меча, дуала и воксовской сабли.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-12 15:02 UTC, kreeperHLC requested changes
Мы для одних лишь мечей создаём переменную у ВСЕХ предметов, вместо того, чтобы обрезать путь объекта до /obj/item/weapon/melee/energy.

2021-07-12 15:12 UTC, NefrNerf commented
Да и такая штука поможет если например будут предметы которые меняют свой режим, маскировка например, в одном взлом, а в другом обычная работа.

2021-07-15 00:06 UTC, kreeperHLC approved these changes, later dismissed

2021-07-15 17:54 UTC, igorsaux submitted a review, later dismissed

2021-07-16 20:27 UTC, TobyThorne requested changes

2021-07-16 20:27 UTC, TobyThorne commented on code/game/objects/items.dm
> +	var/can_hack = FALSE
Очень неочевидная переменная. С первого взгляда абсолютно непонятно, что она отвечает за взлом именно шкафчиков.

Надо переименовать в can_hack_lockers/can_hack_closets/hacks_lockers/etc.

2021-07-16 20:32 UTC, NefrNerf commented on code/game/objects/items.dm
> +	var/can_hack = FALSE
Понял, завтра изменю, мне пришла в голову другая идея, как сделать взлом не делая для всех предметов переменную.

2021-07-21 17:37 UTC, NefrNerf commented
Обновил, перенес переменную в сами мечи, немного причесал код, чтобы было понятие.

2021-07-21 20:49 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/secure.dm
> +/obj/item/weapon/storage/secure/proc/on_hack_behavior(obj/item/weapon/W, mob/user)
Зачем здесь аргументы, если они не используются?

2021-07-21 20:50 UTC, NefrNerf commented on code/game/objects/items/weapons/storage/secure.dm
> +/obj/item/weapon/storage/secure/proc/on_hack_behavior(obj/item/weapon/W, mob/user)
И правда, сейчас уберу

2021-07-21 20:51 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +		return TRUE
```suggestion
		on_hack_behavior()
		return TRUE
```

2021-07-21 20:51 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +			on_hack_behavior()
```suggestion
```

2021-07-21 20:51 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +			on_hack_behavior()
```suggestion
```

2021-07-21 20:52 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets.dm
> +			on_hack_behavior()
```suggestion
```

2021-07-22 14:42 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/lockbox.dm
> +	on_hack_behavior()
Почему это здесь до проверки на broken?

2021-07-22 14:54 UTC, NefrNerf commented on code/game/objects/items/weapons/storage/lockbox.dm
> +	on_hack_behavior()
Перенес

2021-08-01 01:42 UTC, kcalbCube commented on code/game/objects/structures/crates_lockers/closets.dm
> +	playsound(src.loc, "spark", 50, 1)
можно до этой строчки куда-нибудь вынести, и оставить в on_hack_behavior только функцию открытия

2021-08-02 07:59 UTC, NefrNerf commented on code/game/objects/structures/crates_lockers/closets.dm
> +	playsound(src.loc, "spark", 50, 1)
Не думаю, пока тут только один тип взлом, если несколько будет или бага вылезет, тогда перенесу

2021-09-01 05:39 UTC, TobyThorne commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
А зачем вообще эта переменная? Можно просто проверять active.

2021-09-01 05:40 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
Так у нас не все оружие должно ломать шкафчики, например дагер

2021-09-01 05:41 UTC, TobyThorne commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
А кинжал и не наследует /obj/item/weapon/melee/energy. Он - ручка.

2021-09-01 05:44 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
Ну блин, у меня еще и меч мага стал энергетическим оружием, он тоже тогда станет прожигать ящики, да и что если нужно будет запретить отдельному мечу резать ящики и шкафы?

2021-09-01 05:45 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
Если для всех наследников `/obj/item/weapon/melee/energy` разрешить взлом то окей, остальные дизайнеры за?

2021-09-01 05:45 UTC, TobyThorne commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
Пусть прожигает. Всё энергооружие - имбалансные ебаки, доступные только антагам и в среднем рубящие головы с пары тычек. Пускай уж ломают ящики, которые можно расстреливать резиновыми пульками.

2021-09-01 05:46 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
Окей, ща поправим

2021-09-01 05:59 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/can_hack = FALSE
Все, добавил проверку на актив, изменил чейнджлог

2021-09-03 05:19 UTC, kcalbCube requested changes
dick

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/items/weapons/storage/lockbox.dm
> +	return
зачем return

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/items/weapons/storage/secure.dm
> +	var/datum/effect/effect/system/spark_spread/spark_system = new /datum/effect/effect/system/spark_spread()
```suggestion
	var/datum/effect/effect/system/spark_spread/spark_system = new
```

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/items/weapons/storage/secure.dm
> +	if(!emagged)
лесенка.
```suggestion
	if(emagged)
	    return
```

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/items/weapons/storage/secure.dm
> +		overlays = null
оно вообще работает?
```suggestion
		overlays.Cut()
```

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/items/weapons/storage/secure.dm
> +		sleep(6)
некрасиво. уж как нибудь в spawn перемести

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/structures/crates_lockers/closets.dm
> +	playsound(src.loc, "spark", 50, 1)
проблема не решена

2021-09-03 05:19 UTC, kcalbCube commented on code/game/objects/items/weapons/storage/lockbox.dm
> +	var/datum/effect/effect/system/spark_spread/spark_system = new /datum/effect/effect/system/spark_spread()
```suggestion
	var/datum/effect/effect/system/spark_spread/spark_system = new
```

2021-10-14 01:18 UTC, TobyThorne submitted a review, later dismissed
Вдумчиво не чекал, просто заметил, что мой ченжреквест тут до сих пор висит.
Вот бы на гитхабе была опция дисмиссать свои ревью, мм.

2021-10-14 01:19 UTC, igorsaux approved these changes

2021-10-14 01:19 UTC, igorsaux requested changes
cumфликты

2021-10-14 12:38 UTC, NefrNerf commented
Конфликты убраны

2021-10-14 12:38 UTC, igorsaux submitted a review, later dismissed

2021-10-16 01:08 UTC, Doster-d commented on code/game/objects/items/weapons/storage/secure.dm
> +	var/datum/effect/effect/system/spark_spread/spark_system = new /datum/effect/effect/system/spark_spread()
Можно так сделать, но это не ошибка.
```suggestion
	var/datum/effect/effect/system/spark_spread/spark_system = new()
```

2021-11-24 23:35 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/secure.dm
> -		to_chat(user, (feedback ? feedback : "You short out the lock of \the [src]."))
Куда сообщение потерял?

2022-03-16 01:11 UTC, HonkyDonky commented
Конфликты, оказывается, вполне себе заразны.

2022-03-29 19:20 UTC, TermService approved these changes

2022-03-29 19:20 UTC, igorsaux approved these changes

2022-03-29 19:23 UTC, merged