Порт амбиций с Infinitystation
ChaoticOnyx/OnyxBay pull request #6041
Opened 2021-07-12 09:14 UTC by IvanDonFon

Теперь амбиции ведутся в формате дневника: Записи нельзя редактировать, можно только добавлять новые. Все они помечаются по времени. Лимит амбиций увеличен за счёт того, что лимит есть только в длине записи, но не в количестве этих записей
![Screenshot_266](https://user-images.githubusercontent.com/60175270/125261193-b670f900-e309-11eb-8514-40a23e9c97c2.png)
![Screenshot_264](https://user-images.githubusercontent.com/60175270/125262219-ac032f00-e30a-11eb-9281-99518a6e6055.png)

Затрагивает [этот](https://discord.com/channels/414832443384659968/606411392811139072/863087137506459688) иссуй в дискорде

<details>
<summary>Чейнджлог</summary>

```yml
🆑 Donaldo_TH
tweak: Портирована система амбиций с Infinitystation. Записи в них теперь ведутся в формате дневника
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-12 09:16 UTC, kcalbCube commented
раньше было write и оно устанавливало амбицию. теперь оно set и оно дописывает амбицию.

2021-07-12 09:18 UTC, kcalbCube requested changes

2021-07-12 09:18 UTC, kcalbCube commented on code/game/antagonist/antagonist_add.dm
> +	player.current.verbs += /mob/living/proc/set_ambition
раньше было write и оно устанавливало амбицию. теперь оно set и оно дописывает амбицию.

2021-07-12 09:18 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Set Ambition" //ported from infinitystation
пробел после //
и может просто скажешь что сам писал? не так дохуя сделано.

2021-07-12 09:18 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +/datum/antagonist/proc/show_objectives_at_creation(var/datum/mind/player)
поменял вибратор на шило.
```suggestion
/datum/antagonist/proc/show_objectives_at_creation(datum/mind/player)
```

2021-07-12 09:18 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +		mind.ambitions += new_goal
думаю можно интегрировать 
```suggestion
		mind.ambitions += (new_goal = "<br>[roundduration2text()]: [new_goal]")
```

2021-07-12 09:25 UTC, Zert0X commented on code/game/antagonist/antagonist_objectives.dm
> +		mind.ambitions += new_goal
мощно

2021-07-12 09:29 UTC, quardbreak commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Set Ambition" //ported from infinitystation
Доебался до коммента 😦

2021-07-12 09:30 UTC, Zert0X requested changes

2021-07-12 09:30 UTC, Zert0X commented on code/game/antagonist/antagonist_objectives.dm
> +		You can view you ambitions in notes <b>Notes</b>. If you wish to change your ambition, \
```suggestion
		You can view your ambitions in <b>Notes</b>. If you wish to change your ambition, \
```

2021-07-12 09:33 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +	remember you cannot rewrite them - only add new lines.", "Antagonist Goal") as null|message)
пахнет гугл транслейтом

2021-07-12 09:34 UTC, Zert0X commented on code/game/antagonist/antagonist_objectives.dm
> +	remember you cannot rewrite them - only add new lines.", "Antagonist Goal") as null|message)
Видимо так и есть, но тут ещё терпимо :kek:

2021-07-12 15:10 UTC, kreeperHLC commented
![image](https://user-images.githubusercontent.com/14943437/125311773-5778a780-e33c-11eb-88e7-c0283d200b55.png)
А можно сделать так, что амбиции не будут в середине сообщения о целях и самих целях? Либо вверх их сместить, либо вниз.

2021-07-12 15:16 UTC, IvanDonFon commented
Доиграю раунд и посмотрю, что можно сделать

2021-07-12 16:32 UTC, IvanDonFon commented
> ![image](https://user-images.githubusercontent.com/14943437/125311773-5778a780-e33c-11eb-88e7-c0283d200b55.png)
> А можно сделать так, что амбиции не будут в середине сообщения о целях и самих целях? Либо вверх их сместить, либо вниз.

![Screenshot_268](https://user-images.githubusercontent.com/60175270/125323762-d45d4e80-e347-11eb-9212-cd5d30289b13.png)
Так лучше?

2021-07-13 02:00 UTC, kcalbCube requested changes

2021-07-13 02:00 UTC, kcalbCube commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br><span class='notice'>[P.ambitions]</span>"
```suggestion
				text += "<br>[SPAN("notice", P.ambitions)]"
```
или на выбор
```suggestion
				text += "<br>[SPAN_NOTICE(P.ambitions)]"
```

2021-07-13 19:40 UTC, IvanDonFon commented
Обновил, жду проверки

2021-07-17 08:09 UTC, kcalbCube reviewed
ну можно будет и аппрувнуть

2021-07-17 08:09 UTC, kcalbCube commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br>[SPAN_NOTICE(P.ambitions)]"
можешь сделать вот так вот и будет лаконичнее
```suggestion
				text += "<br>Their goals for today were...<br>"
				text += SPAN_NOTICE(P.ambitions)
```

2021-07-17 08:09 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +	if(!isnull(new_goal))
монахи говорят что можно вот так вот
```suggestion
	if(new_goal)
```

2021-07-17 08:09 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Write Ambitions" //ported from infinitystation
чё ported то
мог бы и сам накодить

2021-07-17 08:11 UTC, kcalbCube commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br>[SPAN_NOTICE(P.ambitions)]"
или вообще
```suggestion
				text += "<br>Their goals for today were...<br>[SPAN_NOTICE(P.ambitions)]"
```

2021-07-20 06:39 UTC, TobyThorne commented
Сомнительная фича. Отсутствие лимита на количество записей приведёт к тому, что какой-нибудь мудак натыкает себе несколько тысяч строчек и уронит всем клиенты в конце раунда.

2021-07-20 06:50 UTC, IvanDonFon commented
На финиках, где очень любят баги, таких мудаков не выявилось. Но хорошо, сделаю ограничение

2021-07-31 07:49 UTC, kcalbCube commented
автор?

2021-07-31 07:55 UTC, kcalbCube requested changes

2021-07-31 07:55 UTC, kcalbCube commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br>Their goals for today were...<br>[SPAN_NOTICE(P.ambitions)]"
```"<br>Their goals for today were..."``` повторяется.

2021-08-12 11:03 UTC, IvanDonFon reviewed
> Сомнительная фича. Отсутствие лимита на количество записей приведёт к тому, что какой-нибудь мудак натыкает себе несколько тысяч строчек и уронит всем клиенты в конце раунда.

Уважаемый - ладно, тут я загнул - @TobyThorne, уведомляю Вас, что если администратор не хуесос, то он сможет легко заметить, что какой-то дебил тыкает себе тысячи строчек через админ-логи, а после этого сможет легко подчистить их через Player Panel. Такая фича уже есть. 
![Screenshot_486](https://user-images.githubusercontent.com/60175270/129186247-694bf14a-3696-457e-bab6-267fe5929fc2.png)
В связи с этим не считаю это дополнение необходимым

2021-08-12 11:09 UTC, Zert0X commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Set Ambition" //ported from infinitystation
Боюсь пизды некому давать, мы вроде как некоммерческая организация, или реально зарегистрированное предприятие.

2021-08-12 11:12 UTC, IvanDonFon commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Set Ambition" //ported from infinitystation
Что Вам такого сделал этот коммент, что Вы хотите его убрать?

2021-08-12 12:06 UTC, kreeperHLC commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Write Ambitions" //ported from infinitystation
Да вообще плевать на неё. Если бы кто-то смотрел, то Парадизы Шуссоидов и НедоВайт Валтоса уже давно бы заставили открыть свои репы

2021-08-12 12:10 UTC, Doster-d commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Write Ambitions" //ported from infinitystation
О, тема лицензии, на Эрисе был довнстрим, где фурри накатил фуррей и отказывался открывать код, итог - сервер умер, а автор пидорас.

2021-08-12 12:11 UTC, IvanDonFon commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Write Ambitions" //ported from infinitystation
Если это сервер фурей, то автор и так пидорас

2021-08-20 10:33 UTC, IvanDonFon commented
Рьвью хочется... ну пожалуйста!
![Screenshot_16](https://user-images.githubusercontent.com/60175270/130220732-e3772445-f11c-4185-b3ef-aef4b0c92f49.png)

2021-08-28 07:21 UTC, Doster-d commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br>Their goals for today were...<br>[SPAN_NOTICE(P.ambitions)]"
Куб прав.
```suggestion
				text += "<br>Their personal goals for today were...<br>[SPAN_NOTICE(P.ambitions)]"
```

2021-08-28 07:23 UTC, Doster-d commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br>Their goals for today were...<br>[SPAN_NOTICE(P.ambitions)]"
Чет вообще кринж тут, амбициям тут не место, верни их на место.

2021-08-28 09:49 UTC, IvanDonFon commented on code/game/antagonist/antagonist_print.dm
> +				text += "<br>Their goals for today were...<br>[SPAN_NOTICE(P.ambitions)]"
Верну. А повторение я уже давно исправил

2021-09-02 18:18 UTC, IvanDonFon commented
Мне очень тоскливо видеть, что никто ничего тут не пишет... Ревьювните, по-жа-луй-ста

2021-09-04 06:33 UTC, kcalbCube commented
нехуй было финики упоминать

2021-09-04 06:40 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +	remember you cannot rewrite them - only add new lines.", "Antagonist Goal") as null|message)
адаптируй

2021-09-04 06:40 UTC, kcalbCube requested changes

2021-09-04 06:40 UTC, kcalbCube commented on code/game/antagonist/antagonist_objectives.dm
> +	set name = "Write Ambitions" //ported from infinitystation
убери

2021-09-04 06:41 UTC, kcalbCube commented
и ограничения так и нет

2021-09-04 08:16 UTC, IvanDonFon commented
> и ограничения так и нет

Своё мнение по поводу ограничения я высказал выше. Если администратор не хуесос, то он сможет сам убрать длинные амбиции. А ограничивать амбиции креативных людей, которые могут написать туда что-то интересное, я не хочу

2021-09-06 00:28 UTC, kcalbCube commented
ограничение по количеству, частоте.
администратор должен следить за игровым процессом, а не всякой хуйней типа редактирования абмиций трогать. и если бы не было ограничение на длину сообщения, то можно было бы крашнуть админам чат или что-то подобное сделать.

2021-09-08 07:52 UTC, kcalbCube commented
автор але

2021-09-08 08:06 UTC, IvanDonFon commented
> ограничение по количеству, частоте.
> администратор должен следить за игровым процессом, а не всякой хуйней типа редактирования абмиций трогать. и если бы не было ограничение на длину сообщения, то можно было бы крашнуть админам чат или что-то подобное сделать.

Нет, меня видимо неправильно поняли. Ограничение на длину одной(1) записи в амбиции есть, но ограничение количества записей - нет

2021-09-08 09:03 UTC, kcalbCube commented
поставь трешолд на добавление амбиций. и убери уже упоминание инифинитистейшн

2021-10-04 00:27 UTC, HonkyDonky commented
Оно лежит тут с 12 июля без внимания геймдизайнеров. 
Закрываю этот ПР на основании того, что я ахуел и в нём упоминается Infinity Station (организация, запрещенная на территории Оникса)

2021-10-04 00:34 UTC, Epicus7 commented
То что геймдизайнеры игнорируют - плохая причина, чтобы закрывать ПР. Лучше геймдизайнеров попинайте

2021-10-04 06:40 UTC, IvanDonFon commented
> То что геймдизайнеры игнорируют - плохая причина, чтобы закрывать ПР. Лучше геймдизайнеров попинайте

![20211004_093838](https://user-images.githubusercontent.com/60175270/135804890-9a9f0dfc-c2f4-48f1-ae09-31a654615d7b.jpg)

2021-10-04 13:04 UTC, kreeperHLC commented
> > и ограничения так и нет
> 
> Своё мнение по поводу ограничения я высказал выше. Если администратор не хуесос, то он сможет сам убрать длинные амбиции. А ограничивать амбиции креативных людей, которые могут написать туда что-то интересное, я не хочу

У тебя именно из-за этого и не принимают

2021-10-05 07:04 UTC, IvanDonFon commented
> > > и ограничения так и нет
> > 
> > 
> > Своё мнение по поводу ограничения я высказал выше. Если администратор не хуесос, то он сможет сам убрать длинные амбиции. А ограничивать амбиции креативных людей, которые могут написать туда что-то интересное, я не хочу
> 
> У тебя именно из-за этого и не принимают

На финиках за всё сущевствование этой фичи, таких дебилов не нашлось. Ты, видимо, считаешь что коммьюнити оникса хуже?

2021-10-05 17:22 UTC, kreeperHLC commented
> > > > и ограничения так и нет
> > > 
> > > 
> > > Своё мнение по поводу ограничения я высказал выше. Если администратор не хуесос, то он сможет сам убрать длинные амбиции. А ограничивать амбиции креативных людей, которые могут написать туда что-то интересное, я не хочу
> > 
> > 
> > У тебя именно из-за этого и не принимают
> 
> На финиках за всё сущевствование этой фичи, таких дебилов не нашлось. Ты, видимо, считаешь что коммьюнити оникса хуже?

Одно дело игроки, а другое дело набегатели. Если педалька не сможет заметить как чувак тонны записей сделал, то виноват будет кто? Правильно, мы. Ибо педали люди, а мы знаем про проблему и не хотим решать.

2021-10-06 00:41 UTC, KamSurvivor commented
> Ты, видимо, считаешь что коммьюнити оникса хуже?
А ты? 

Этот ПР не примут по простой причине. Амбишены и так работают, но их никто не использует и не читает. На ониксбее вообще совсем не та динамика для подобного.

2021-10-06 01:24 UTC, kreeperHLC commented
> > Ты, видимо, считаешь что коммьюнити оникса хуже?
> > А ты?
> 
> Этот ПР не примут по простой причине. Амбишены и так работают, но их никто не использует и не читает. На ониксбее вообще совсем не та динамика для подобного.

Не вижу смысла НЕ принимать ПР. Амбишены не вырезали из билда, значит их импрув будет только на пользу.

2021-10-06 01:30 UTC, KamSurvivor commented
Ну я пользовался этими амбициями на финиках. Могу сказать что это одновременно и прикольно и нет. Можно заранее расписать весь свой мастерплан и мотивацию, но как правило выходит огромная простыня, даже если сделать около 5 записей на 10 слов. Неудобно, что нельзя потом редактировать их. Я на ониксбее пользуюсь амбициями и частенько их переписываю, потому что план часто меняется на диаметрально противоположный. 

Но то, что в конце раунда будет вываливаеться целая простыня это факт. И сомневаюсь я, что кто-то будет намеренно ебашить рассказ на 500 слов в амбициях, чтобы поднасрать. У нас и так хватает методов обосрать другим экспириенс, не повод по такой причине ПР разворачивать.

2021-10-12 18:36 UTC, closed without merging

2021-10-12 18:39 UTC, TobyThorne commented
Так и не нашли повода принять ПР, кроме того, что он существует.
Едва ли он вносит что-то новое, помимо возможности насрать всем в чат раундендом.
Да и амбиция - это скорее как раз про одно единственное сообщение, цель, поставленная антагом самому себе. При чём здесь дневничок с таймингами - не совсем ясно.