Собираем-разбираем: вендоматное
ChaoticOnyx/OnyxBay pull request #6046
Opened 2021-07-12 14:30 UTC by MaxFreemen

Добавлена возможность собирать и разбирать умные холодильники и вендинговые автоматы. В грузовом отсеке можно заказать картриджи для "перезарядки" автоматов.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена возможность собирать и разбирать вендинговые автоматы. Для сборки требуется: 2 * matter bin, 1 * console screen, 1 * cartridge.
rscadd:  Добавлена возможность собирать и разбирать вендинговые автоматы. Для сборки требуется: 2 * matter bin.
rscadd: Добавлены картриджи для вендинговых автоматов, заказываются в грузовом отделе.
bugfix: Исправлен баг с обновлением сушилки ( drying rack ) .
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-12 23:38 UTC, igorsaux requested changes

2021-07-12 23:38 UTC, igorsaux commented on code/modules/modular_computers/laptop_vendor.dm
> +							)
```suggestion
	component_types = list(
            /obj/item/weapon/circuitboard/vendomat,
            /obj/item/weapon/stock_parts/matter_bin = 2,
            /obj/item/weapon/stock_parts/console_screen
)
```

2021-07-12 23:38 UTC, igorsaux commented on code/modules/modular_computers/laptop_vendor.dm
> +							)
И такие поехавшие отступы везде

2021-07-13 16:18 UTC, igorsaux requested changes

2021-07-13 16:18 UTC, igorsaux commented on code/modules/hydroponics/seed_storage.dm
>  /obj/machinery/seed_storage/attackby(obj/item/O as obj, mob/user as mob)
```suggestion
/obj/machinery/seed_storage/attackby(obj/item/O, mob/user)
```

2021-07-13 16:18 UTC, igorsaux commented on code/game/objects/items/weapons/circuitboards/machinery/vending.dm
> +/obj/item/weapon/circuitboard/vendomat/attackby(obj/item/weapon/W as obj, mob/user as mob)
```suggestion
/obj/item/weapon/circuitboard/vendomat/attackby(obj/item/weapon/W, mob/user)
```

2021-07-13 16:18 UTC, igorsaux commented on code/game/machinery/kitchen/smartfridge.dm
> +/obj/machinery/smartfridge/drying_rack/attackby(obj/item/O as obj, mob/user as mob)
```suggestion
/obj/machinery/smartfridge/drying_rack/attackby(obj/item/O, mob/user)
```

2021-07-18 09:08 UTC, MaxFreemen commented
Кхм, запрашиваю ревью проекта.

2021-07-19 16:02 UTC, MaxFreemen commented
Прошла уже неделя, код вычищен до блеска, запрошен ревью. Можно уже как бы две зеленые галочки, прошу.

2021-07-20 06:23 UTC, TobyThorne commented
Товарищ, у вас конфликтинг файлз.

2021-07-20 13:37 UTC, MaxFreemen commented
> Товарищ, у вас конфликтинг файлз.

Официально заявляю, что вендоматному пизда. Спасибо девам за своевременный ревью проекта.
![3dfa53fec8cd648be8b8f86dcc6ebf66](https://user-images.githubusercontent.com/47484306/126333674-7fbd3d62-9dcb-42ee-881b-685d03729e73.jpg)

2021-07-20 13:41 UTC, Doster-d commented
А нахуя ты на +1500 изменений трогаешь карту? Естественно оно конфликтнулось.

2021-07-20 13:44 UTC, MaxFreemen commented
> А нахуя ты на +1500 изменений трогаешь карту? Естественно оно конфликтнулось.

Оно конфликтнулось вчера, после мерджа изменений Тоби. И конфликтнулось, ибо был изменен файл vending.dm , иерархия вендоматов и карта, ибо была изменена иерархия. Примерно с этими файлами работал и Тоби.

2021-07-20 13:46 UTC, Doster-d commented
Это тебе урок, что патчи должны быть маленькими.

2021-07-20 22:06 UTC, MaxFreemen commented
Макс решил конфликтики.
![Без названия (1)](https://user-images.githubusercontent.com/47484306/126401420-c749035f-950a-4821-806d-ac1b6664a5db.jpg)

2021-07-22 18:30 UTC, TobyThorne requested changes
Ничего не работает:
- При разборе раундстартового автомата тип платы сбрасывается, для обратной сборки нужно тыкать отвёрткой и заново выбирать. Если собрать в течение раунда и потом разобрать - то сохраняется.
- Выбранный тип платы никак не указывается. Проверить можно только суванием во фрейм. 
- Сама смена типа отвёрткой - самое неочевидное, что можно было придумать. Пришлось смотреть в код. Если уж на то пошло - то хотя бы мультитулом, как платы для дверей. **А лучше вообще избавиться от этого костыля с переключением, а тип автомата выбирать в зависимости от вставленного картриджа.** Для холодильников, впрочем, можно и оставить переключение платы.
- Для сборки автомата нужен console screen, при разборке раундстартовых автоматов он не выпадает. Если собрать в течение раунда и потом разобрать - то выпадает.
- Seed Storage после сборки перестаёт работать и срёт рантаймами.
- Содержимое холодильников удаляется при разборке.
- Названия картриджей не совпадают с названиями самих автоматов.
- Уникальный автомат с сигаретами в баре просрал уникальный спрайт. Мне он, конечно, не нравится, но всё же это баг. 
![image](https://user-images.githubusercontent.com/45202681/126690430-840aebcb-2ee5-46cb-9b1d-e130711090aa.png)
- Спрайты картриджей выглядят максимально чужеродно и не вписываются в остальную стилистику.
- Автоматы разбираются буквально мгновенно. Не нужно ни резать провода, ни откручивать от пола, ни ждать do_after. Клик отвёрткой, клик ломом - и всё, автомат погиб.

2021-07-22 21:42 UTC, MaxFreemen commented
>Сама смена типа отвёрткой - самое неочевидное, что можно было придумать. Пришлось смотреть в код. Если уж на то пошло - то хотя бы мультитулом, как платы для дверей. А лучше вообще избавиться от этого костыля с переключением, а тип автомата выбирать в зависимости от вставленного картриджа. Для холодильников, впрочем, можно и оставить переключение платы.
Выдумывать велосипед не буду, пусть будет мультитул. С остальными проблемами постараюсь разобраться в ближайшее время, перевожу в драфт.

2021-07-23 15:55 UTC, TobyThorne commented
_Прилетело НЛО и оставило странные символы на поле:_

> **А лучше вообще избавиться от этого костыля с переключением, а тип автомата выбирать в зависимости от вставленного картриджа.**

2021-07-23 16:26 UTC, MaxFreemen commented
> _Прилетело НЛО и оставило странные символы на поле:_
> 
> > **А лучше вообще избавиться от этого костыля с переключением, а тип автомата выбирать в зависимости от вставленного картриджа.**

А не слишком много ```if(istype(C, obj/ebaniy_kartridg/1))``` выйдет?

2021-07-23 16:30 UTC, MrMagick2104 commented
> А не слишком много if(istype(C, obj/ebaniy_kartridg/1)) выйдет?

В картридж сам можно всунуть переменную с типом желаемого автомата (или даже просто спрайта, сами автоматы же особо ничем не отличаются?), а затем её использовать, без ифов и свичей на километр.

2021-07-23 16:34 UTC, MaxFreemen commented
> > А не слишком много if(istype(C, obj/ebaniy_kartridg/1)) выйдет?
> 
> В картридж сам можно всунуть переменную с типом желаемого автомата (или даже просто спрайта, сами автоматы же особо ничем не отличаются?), а затем её использовать, без ифов и свичей на километр.

Ну, задачку вы мне интересную поставили буду думать, спасибо.

2021-08-16 12:30 UTC, hard-res3t commented
> MaxFreemen commented 24 days ago

DEAD CHAT

2021-08-16 17:23 UTC, MaxFreemen commented
> > MaxFreemen commented 24 days ago
> 
> DEAD CHAT

Сам ты дед, @hard-res3t ! 
![3dfa53fec8cd648be8b8f86dcc6ebf66](https://user-images.githubusercontent.com/47484306/129604173-908c7fb4-1eb0-4b0e-9d73-244bf3a2c5b0.jpg)

2021-08-24 16:31 UTC, MaxFreemen commented
@TobyThorne , у меня вопрос касаемо работы вендомата. Собираем фрейм машинерии, суем плату и компоненты, после чего появляется как бы разобранный вендомат, крышка скручена, меню пустое. Мы суем картридж, обновляется спрайт и название, появляются товары. Примерно так все надо реализовать?

2021-08-25 01:35 UTC, TobyThorne commented
> @TobyThorne , у меня вопрос касаемо работы вендомата. Собираем фрейм машинерии, суем плату и компоненты, после чего появляется как бы разобранный вендомат, крышка скручена, меню пустое. Мы суем картридж, обновляется спрайт и название, появляются товары. Примерно так все надо реализовать?

Примерно как-то так, да. В картридже хранить имя и спрайт будущего автомата.

2021-08-28 18:41 UTC, MaxTheAstronaut commented
@TobyThorne , есть еще предложение. Можно добавить возможность загружать товары в вендомат, если открыта панель и товар находится в списке доступных. Добро?

2021-08-28 19:19 UTC, TobyThorne commented
> @TobyThorne , есть еще предложение. Можно добавить возможность загружать товары в вендомат, если открыта панель и товар находится в списке доступных. Добро?

А в чём предложение? Это можно делать и сейчас, даже без раскрутки.

2021-09-04 06:28 UTC, kcalbCube requested changes
работай, всем куклус кланом ждем

2021-09-04 06:28 UTC, kcalbCube commented on code/game/machinery/kitchen/smartfridge.dm
> +	if(isScrewdriver(O))
```suggestion
	if(!isScrewdriver(O))
		return ..()
```

2021-09-04 06:28 UTC, kcalbCube commented on code/modules/hydroponics/seed_storage.dm
> +			for(var/obj/item/weapon/vendcart/seed_storage/B in component_parts)
locate() чё нельзя

2021-09-04 06:28 UTC, kcalbCube commented on code/modules/hydroponics/seed_storage.dm
> +		if(do_after(user, 20, src))
```suggestion
		if(!do_after(user, 20, src))
			return
```
или че то типо того

2021-09-04 06:28 UTC, kcalbCube commented on code/modules/reagents/dispenser/supply.dm
> +	decl/hierarchy/supply_pack/booze_cartridges{\
че

2021-09-04 06:31 UTC, kcalbCube commented
я на этот пр надежды возлагаю, ибо я смогу сильно уменьшить кол-во кода в #6387

2021-09-24 15:09 UTC, MaxTheAstronaut commented
В общем, переношу проект на другую ветку, попутно переписав с нуля, ибо от этого уже смердит.

2021-09-24 15:09 UTC, closed without merging