fix(nullrod): (nullrod): fixes nullrod inability to decultify properly
ChaoticOnyx/OnyxBay pull request #6053
Opened 2021-07-12 19:17 UTC by NefrNerf

Починил работу нуллрода, теперь при декультификации будет возвращена оригинальная стена, которую культифицировали, культо стены хранят в себе тип старой стены. Если стену заспавнили педально, то она декультифицируется в обычную стену, все это также относиться к полу.

Убрал возможность открутить культо-пол так как нуллрод теперь нормально работает, слишком просто космонавтики могут избавиться от проклятого пола.

-  fixes  #4978

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Нулл род возвращает стены и пол после культификации в оригинальный вид.
tweak: Культо-пол больше нельзя снять гаечным ключом.

/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-13 16:09 UTC, igorsaux requested changes

2021-07-13 16:09 UTC, igorsaux commented on code/game/objects/items/weapons/weaponry.dm
> +		M.silence_spells(300)
```suggestion
		M.silence_spells(30 SECONDS)
```

2021-07-13 16:09 UTC, igorsaux commented on code/game/gamemodes/cult/cultify/turf.dm
> +	var/turf/simulated/floor/misc/cult/cult_floor= src
```suggestion
	var/turf/simulated/floor/misc/cult/cult_floor = src
```

2021-07-13 16:09 UTC, igorsaux commented on code/game/gamemodes/cult/cultify/turf.dm
> +	var/turf/simulated/wall/cult/cult_wall= src
```suggestion
	var/turf/simulated/wall/cult/cult_wall = src
```

2021-07-13 17:15 UTC, NefrNerf commented
Обновил, нужно ревью

2021-07-14 08:09 UTC, igorsaux approved these changes

2021-07-15 00:05 UTC, kreeperHLC requested changes

2021-07-15 00:05 UTC, kreeperHLC commented on code/game/gamemodes/cult/cultify/turf.dm
> -	//todo: flooring datum cultify check
А зачем убрал, если чек так и не сделан?

2021-07-15 00:05 UTC, kreeperHLC commented on code/game/gamemodes/cult/cultify/turf.dm
> +		cult_wall.previous_type = old_type
А не проще ли до ифа сохранять тип?

2021-07-16 13:13 UTC, NefrNerf commented on code/game/gamemodes/cult/cultify/turf.dm
> +		cult_wall.previous_type = old_type
К сожалению, нет, если не сохранять до ифа, то оно вообще не культифицируется, весь прикол с порядком действий, если сохранить до смены турфа - ничего не выйдет

2021-07-16 13:39 UTC, NefrNerf commented
Пол культа теперь не будет повторно обращаться

2021-07-16 14:04 UTC, kreeperHLC requested changes

2021-07-16 14:04 UTC, kreeperHLC commented on code/game/gamemodes/cult/cultify/turf.dm
> +	return()
```suggestion
	return
```

2021-07-16 14:07 UTC, NefrNerf commented on code/game/gamemodes/cult/cultify/turf.dm
> +	return()
Поправил

2021-07-17 20:03 UTC, igorsaux approved these changes

2021-07-20 15:24 UTC, kreeperHLC approved these changes

2021-07-20 16:24 UTC, merged