Плащ из змеиной кожи в лодаут
ChaoticOnyx/OnyxBay pull request #6078
Opened 2021-07-14 11:01 UTC by IvanDonFon

В лодаут добавлен плащ из змеиной кожи, срисованный с плаща Бакалавра из игры Мор (Утопия). Отдельная благодарность **CeUvi#1236** за спрайт:
![image](https://user-images.githubusercontent.com/60175270/125611268-993cb1e4-59a3-4b1e-956f-ea772b9647cc.png)
![image](https://user-images.githubusercontent.com/60175270/125611376-f70a286c-8167-41a3-bf30-243525f531b8.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: В лодаут добавлен плащ из змеиной кожи
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-14 12:15 UTC, IvanDonFon commented
Я не ебу, как тут запросить ревью кода, так что представьте, что я его запросил

2021-07-14 13:49 UTC, kcalbCube commented
А че от кожанки не отнаследовался

2021-07-14 14:02 UTC, IvanDonFon commented
> А че от кожанки не отнаследовался

Материал другой, да и на нём нету карманов

2021-07-15 00:00 UTC, kreeperHLC requested changes

2021-07-15 00:00 UTC, kreeperHLC commented on code/modules/clothing/suits/miscellaneous.dm
> +	name = "snakeskin coat" //sprite by CeUvi#1236
```suggestion
	name = "snakeskin coat" // sprite by CeUvi#1236
```

2021-07-15 00:00 UTC, kreeperHLC commented on code/modules/client/preference_setup/loadout/lists/suits.dm
> +	cost = 1
А почему НАСТОЛЬКО дешевый?

2021-07-15 04:40 UTC, IvanDonFon commented on code/modules/client/preference_setup/loadout/lists/suits.dm
> +	cost = 1
Ну, тенчкоут стоит столькл-же, если я помню. Но могу поднять до двух-трёх очков

2021-07-15 04:55 UTC, IvanDonFon commented on code/modules/client/preference_setup/loadout/lists/suits.dm
> +	cost = 1
Ладно, тренчкоут стоит три, зря быканул
Поднял до двух в виду отсутствия карманов

2021-07-15 19:52 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/125848947-cc7d4d78-053b-4510-90c2-51dbcb8fc6bd.png)
Какой-то киргизский халат, зачем это на станции?

2021-07-15 20:19 UTC, IvanDonFon commented
> ![image](https://user-images.githubusercontent.com/45202681/125848947-cc7d4d78-053b-4510-90c2-51dbcb8fc6bd.png)
> Какой-то киргизский халат, зачем это на станции?

У киргизов он не из змеиной кожи

Это модно, ты не понимаешь.

2021-07-15 20:21 UTC, DarkHunter7756 commented
> Какой-то киргизский халат, зачем это на станции?

А зачем на станции костюмы ковбоя, мексиканца и турка?

2021-07-15 20:23 UTC, IvanDonFon commented
Да и вообще, он очень зачётно смотрится на игроках, завтра кину скрин

2021-07-15 20:23 UTC, kreeperHLC submitted a review, later dismissed

2021-07-16 08:03 UTC, IvanDonFon commented
![Screenshot_273](https://user-images.githubusercontent.com/60175270/125912825-098a2a3a-4ce4-4d72-9333-6f48841c125e.png)
Скриншот с фиников, куда этот плащ уже давно замержили. Единственное, что тут есть, чего нету на Ониксе - это ботинки из змеиной кожи.
![Screenshot_280](https://user-images.githubusercontent.com/60175270/125913844-538aa857-79ac-437f-9635-81c82f590d86.png)
![Screenshot_281](https://user-images.githubusercontent.com/60175270/125913846-5b6691d6-a525-47c5-9a33-8e6b59215b1a.png)
Скриншоты с Оникса

2021-07-16 08:04 UTC, kcalbCube submitted a review, later dismissed

2021-07-19 07:27 UTC, IvanDonFon commented
Я, конечно, ни на что не намекаю...
Но было-бы неплохо, если-бы геймдизайнеры рассмотрели этот умопомрачительный ПР

2021-07-20 15:25 UTC, kreeperHLC approved these changes

2021-07-23 20:19 UTC, IvanDonFon commented
Я не видел ревью десят тысяч лет...

2021-07-24 20:54 UTC, closed without merging

2021-07-24 21:06 UTC, Doster-d commented
Плащ такое себе по спрайту, каша из кишков.