feat(UI): restore old vendomat UI
ChaoticOnyx/OnyxBay pull request #6090
Opened 2021-07-15 21:19 UTC by TapKo4eB

удаляем нечитаемый не-помещайющийся-в-окно убожеский юзер интерфейс для людей с ограниченными зрительными способностями который зачем-то поместили в вендоматы и возвращаем старый добрый, тёплый, тонкий, плоский и построчный интерфейс наноуи
![image](https://user-images.githubusercontent.com/48761132/125857522-94680a4b-05b2-45fb-b7bc-3231d7c36440.png)
алсо оставил звук дропа айтема из вендомата, ибо хороший

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Возвращён старый интерфейс вендоматов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-15 22:57 UTC, quardbreak commented
Захуярь иконки хотя бы, а то как кроты не видим че покупаем.

2021-07-15 23:38 UTC, igorsaux commented
Наноуи и плейн хтмл холопам не положено

2021-07-15 23:46 UTC, igorsaux requested changes
Кодстайл: ♿ 
Ещё нужно удалить vending.tsx и vending.scss.
А также не забыть перекомпилировать тгуи.

2021-07-17 07:49 UTC, kcalbCube commented
вы чё, прогресс же. не лучше просто скрипт с наноуи переписать, там делов на часа два.

2021-07-17 07:57 UTC, quardbreak commented
> 
> 
> вы чё, прогресс же. не лучше просто скрипт с наноуи переписать, там делов на часа два.

Ну чо пили, борец :kekw:

2021-07-17 08:02 UTC, kcalbCube commented
баунти подгоните

2021-07-17 11:14 UTC, TapKo4eB commented
thanks obama

2021-08-13 16:44 UTC, kreeperHLC commented
Посмеялись и хватит. В любом случае Тапок настолько сдох что конфликты не пофиксил.

2021-08-13 16:44 UTC, closed without merging