cut out news_articles
ChaoticOnyx/OnyxBay pull request #6128
Opened 2021-07-19 11:22 UTC by Nod404

Были удалены новости NTNet/EXOnet содержащие отрывки вырезанного лора.

close #5896

<details>
<summary>Чейнджлог</summary>

```yml
🆑Nod404
rscdel: Были удалены новости NTNet/EXOnet содержащие отрывки вырезанного лора.
🆑/Nod404
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-19 11:26 UTC, DarkHunter7756 commented
Они в любом случае не подгружались.

2021-07-19 11:27 UTC, Zert0X requested changes
![изображение](https://user-images.githubusercontent.com/42303535/126153234-ed68f0b6-4d6e-4080-b49e-801c2d9db6e7.png)
Чини

2021-07-19 11:48 UTC, TobyThorne commented
![IMG_20210719_174406](https://user-images.githubusercontent.com/45202681/126155469-f407f81f-d76e-4d5a-9270-9ccd5dd813a6.jpg)
Кто-то пиздит.

2021-07-19 13:26 UTC, MaxFreemen commented
Максимальное осуждение, ибо выпиливаются все журналы, а не устаревшие статейки из него.

2021-07-19 13:28 UTC, DarkHunter7756 commented
> Максимальное осуждение, ибо выпиливаются все журналы, а не устаревшие статейки из него.

Количество людей, которые так или иначе знают об этой фиче не наберет и десяток. Целая программа выделена для...ничего.

2021-07-19 13:32 UTC, MaxFreemen commented
> > Максимальное осуждение, ибо выпиливаются все журналы, а не устаревшие статейки из него.
> 
> Количество людей, которые так или иначе знают об этой фиче не наберет и десяток. Целая программа выделена для...ничего.

Дарк, он еще зеленый. Не сможет он осилить пурдж целой программы.

2021-07-19 13:43 UTC, Nod404 commented
Всё готово.

2021-07-20 19:00 UTC, Zert0X submitted a review, later dismissed

2021-07-22 14:47 UTC, Doster-d approved these changes

2021-07-22 15:33 UTC, Zert0X approved these changes

2021-07-25 19:23 UTC, merged