Make the chainsaw
ChaoticOnyx/OnyxBay pull request #6133
Opened 2021-07-19 15:23 UTC by BWJes

Добавлен крафт бензопилы и крафт к ней
(Крафт: 30 cables, advanced capacitor, 10 plasteel sheets, welding tool (5 ед топлива, ДОЛЖЕН быть включен)
Нужна помощь с добавление возможности спила дерева (flora.dm)

twohanded.dm - свойства бензопилы, переключение, звуки, возникающие при отключении/включении, звуки атаки, изменение описание бензопилы при включении
improvised_components.dm - крафт бензопилы (компоненты выше), отображение шагов для игрока, звук при создании (использовался flare.ogg)
lefthand.dmi и righthand.dmi - добавлены спрайты бензопилы НА ПЕРСОНАЖЕ
weapons.dmi - спрайт бензопилы, на полу, или если её взять
chainsaw_activated.ogg chainsaw_activated.ogg - звуки при включения бензопилы
chainsaw stop - звуки при выключении бензопилы
chainsaw_attck1.ogg и chainsaw_attck1.ogg - звуки при атаке бензопилой

Этот Pull Request затрагивает issue:
https://github.com/ChaoticOnyx/OnyxBay/issues/2394

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена бензопила
imageadd: Добавлены спрайты бензопилы (отображение на персонаже, на полу/в руках)
soundadd: Добавлены звуки атаки бензопилой, включения и выключения
/🆑 BWJes
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-19 15:28 UTC, MaxFreemen commented
Внимание. Пиши в чейнджлоге так:  " rscadd: Добавлена бензопила. "
Этого достаточно.

2021-07-19 15:29 UTC, quardbreak commented on code/game/objects/items/weapons/material/improvised_components.dm
> +/obj/item/weapon/circular_saw/var/making_chainsaw_step = 1
```
/obj/item/weapon/circular_saw
	var/making_chainsaw_step = 1
```

2021-07-19 15:29 UTC, quardbreak commented on code/game/objects/items/weapons/material/improvised_components.dm
> +				to_chat(user, "adding the capacitor for future chainsaw")
`to_chat(user, "Adding \the [W] capacitor for a future chainsaw.")`

2021-07-19 15:29 UTC, quardbreak commented on code/game/objects/items/weapons/material/improvised_components.dm
> +					to_chat(user, "You're changing the wiring of circular saw")
to_chat(user, "You're changing the wiring for \the [src].")

2021-07-19 15:29 UTC, quardbreak commented on code/game/objects/items/weapons/material/improvised_components.dm
> +					to_chat(user, "You're making the chainsaw shell")
`to_chat(user, "You make the chainsaw shell.")`

2021-07-19 15:29 UTC, quardbreak commented on code/game/objects/items/weapons/material/twohanded.dm
> +	mod_reach_u = 1.0
Убери нули после точек, они тут бесполезны.

2021-07-19 15:29 UTC, quardbreak commented on code/game/objects/items/weapons/material/twohanded.dm
> +	unbreakable = 1
```
	sharp = FALSE
	edge = FALSE
	unbreakable = TRUE
```

2021-07-19 15:36 UTC, MaxFreemen commented on code/game/objects/items/weapons/material/improvised_components.dm
> +					to_chat(user, "You're changing the wiring of circular saw")
to_chat(user, "You add wiring to a circular saw assembly.)

2021-07-19 15:36 UTC, MaxFreemen commented on code/game/objects/items/weapons/material/improvised_components.dm
> +				to_chat(user, "adding the capacitor for future chainsaw")
to_chat(user, "You add a capacitor to the circular saw assembly. ")

2021-07-19 15:36 UTC, MaxFreemen commented on code/game/objects/items/weapons/material/improvised_components.dm
> +					to_chat(user, "You're making the chainsaw shell")
to_chat(user, "You finish messing with circular saw inners.")

2021-07-19 15:36 UTC, MaxFreemen commented on code/game/objects/items/weapons/material/improvised_components.dm
> +					to_chat(user, "You're welding and complete the chainsaw")
to_chat(user, "You finish making the circular saw.")

2021-07-19 15:36 UTC, MaxFreemen commented on code/game/objects/items/weapons/material/improvised_components.dm
> +/obj/item/weapon/circular_saw/var/making_chainsaw_step = 1
```
/obj/item/weapon/circular_saw
	var/step = 1
```

Зачем такие огромные переменные вводить? Просто ```step``` достаточно!

2021-07-19 15:49 UTC, BWJes commented
Поправлю крафт
3 ед кабеля и 5 plasteel sheet пойдёт на крафт

2021-07-19 15:56 UTC, DarkHunter7756 commented
В чем прикол бензопилы, если есть пило-копье?

2021-07-19 16:41 UTC, BWJes commented on code/game/objects/items/weapons/material/improvised_components.dm
> +				to_chat(user, "adding the capacitor for future chainsaw")
> В чем прикол бензопилы, если есть пило-копье?
Issue - сделать бензопилу
Да и пило-копьём не сделаешь БРРРР-БРРРР-БРРРР! Для брутальности и веселья

2021-07-19 16:42 UTC, BWJes commented
> В чем прикол бензопилы, если есть пило-копье?
В issue прямо сказано - сделать бензопилу
Да и пило-копьёем не поделаешь БРРРРР-БРРРР-БРРРР!
Для брутальности и веселья

2021-07-19 16:43 UTC, BWJes commented
> 
> 
> В чем прикол бензопилы, если есть пило-копье?

В issue прямо сказано - сделать бензопилу
Да и пило-копьёем не поделаешь БРРРРР-БРРРР-БРРРР!
Для брутальности и веселья

2021-07-19 18:01 UTC, TermService requested changes

2021-07-19 18:01 UTC, TermService commented on code/game/objects/items/weapons/material/improvised_components.dm
> +/obj/item/weapon/circular_saw/attackby(obj/item/W, mob/user)
что тут вообще творится, крафт делается не так. Если ты уж хочешь использовать свитч в крафте то используй дефайны, а в конце файла не забудь раздефайнить их, а лучше глянь крафт станперчаток, там сделано как надо code\modules\clothing\gloves\stun.dm ну или ещё кучу мест где есть крафт, не нужно убивать мозг потомкам чтобы они искали скрытый смысол почему в этом месте крафт отличается от остальных

2021-07-19 19:36 UTC, BWJes commented on code/game/objects/items/weapons/material/twohanded.dm
> +			desc = "Using for sawing wood more effective"
> 
> 
> что тут делает desk

Сделал повторное описание альтернативное, т.к. при включении меняется описание

2021-07-19 19:39 UTC, BWJes commented on code/game/objects/items/weapons/material/twohanded.dm
> +			hitsound = "swing_hit"
Параметры решил задать на всякий случай и для него
FALSE сказали поставить, вместо 0 и 1
Звук стандартный

2021-07-19 21:47 UTC, bosslobster commented
Если не добавите возможность устанавливать бензопилу вместо руки, то наложу вето!!! Я не могу накладывать вето, конечно, но все равно попробую наложить!!!

2021-07-24 08:16 UTC, kcalbCube requested changes
ещё и CL в пизду

2021-07-24 08:16 UTC, kcalbCube commented on code/game/objects/items/weapons/material/twohanded.dm
> -	force_divisor = 1.0           // 20 when wielded with weight 20 (steel)
ты нахуя дробную точку распидорасил

2021-07-24 08:16 UTC, kcalbCube commented on code/game/objects/items/weapons/material/twohanded.dm
> +			base_icon = "chainsaw_off"
base_icon = "chainsaw_[chainsaw_active ? "on" : "off"]"

2021-07-24 08:16 UTC, kcalbCube commented on code/game/objects/items/weapons/material/twohanded.dm
> +	var/chainsaw_active = FALSE
```suggestion
	var/active = FALSE
```

2021-07-24 08:16 UTC, kcalbCube commented on code/game/objects/structures/flora.dm
> +I need help here with chopping the trees (delete the tree and checking the active of chainsaw)
драфт запили

2021-07-27 14:40 UTC, BWJes commented on code/game/objects/items/weapons/material/twohanded.dm
> -	force_divisor = 1.0           // 20 when wielded with weight 20 (steel)
quardbreak: "Убери нули после точек, они тут бесполезны."
Да и по факту, я убирал точки и делал ровные значения там, где это не будет влиять
Естественно, я не буду убирать дробную точку в каком-нибудь 1.5. Я убирал в 1.0, ибо если будет 1, разницы не будет

2021-07-28 18:38 UTC, Zert0X commented
![GenuineSnappyBorderterrier-max-1mb.gif](https://user-images.githubusercontent.com/42303535/127377842-6cfbe293-921a-492d-bcbe-4aa2846439da.gif)

2021-07-28 18:41 UTC, Zert0X commented on code/game/objects/items/weapons/material/twohanded.dm
> +			base_icon = "chainsaw_off"
Вообще base_icon не так должен работать...
В бейз айконе должно быть chainsaw, а уже в сам icon_state должно влепляться base_icon+разделитель+состояние

2021-08-06 18:39 UTC, closed without merging