Changed Happy Christmas to Marry Christmas
ChaoticOnyx/OnyxBay pull request #6142
Opened 2021-07-20 05:31 UTC by SerJo2

Измен текст который появляется на рождество в начале раунда с Happy Christmas на Marry Christmas

close [#4095](https://github.com/ChaoticOnyx/OnyxBay/issues/4095)

<details>
<summary>Чейнджлог</summary>

```yml
🆑SerJo
bugfix: Happy Christmas изменен на Marry Christmas
/🆑SerJo
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-20 15:23 UTC, kreeperHLC requested changes

2021-07-20 15:23 UTC, kreeperHLC commented on code/game/gamemodes/events/holidays/Holidays.dm
> +		if (Holiday == "Christmas Eve" || Holiday == "Christmas")
```suggestion
		if(Holiday == "Christmas Eve" || Holiday == "Christmas")
```
Стайлкоп прибыл

2021-07-20 23:27 UTC, SerJo2 commented on code/game/gamemodes/events/holidays/Holidays.dm
> +		if (Holiday == "Christmas Eve" || Holiday == "Christmas")
Ага

2021-07-25 19:21 UTC, TermService approved these changes

2021-07-26 12:47 UTC, kreeperHLC approved these changes

2021-07-26 14:31 UTC, merged