Removes lack of legacy engineering tools
ChaoticOnyx/OnyxBay pull request #6184
Opened 2021-07-22 13:08 UTC by TobyThorne

- Добавлены легаси-версии инженерных инструментов. Обладают чутка повышенными боевыми характеристиками и сделаны из пластали, а не обычной стали.
- У СЕ в поясе теперь спавнится не обычный набор инструментов, а легаси-инструменты, maintenance jack (ибо ломик и так легаси) и t-ray scanner. А провода - строго красные.

```yml
🆑
tweak: СЕ теперь спавнится не с обычными инструментами, а с элитными, пласталевыми.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-22 13:20 UTC, kreeperHLC requested changes

2021-07-22 13:20 UTC, kreeperHLC commented on code/game/objects/items/weapons/storage/belt.dm
> +/obj/item/weapon/storage/belt/utility/chief/New()
Спасибо папаша за нью вместо инитилайза

2021-07-22 13:23 UTC, TobyThorne commented on code/game/objects/items/weapons/storage/belt.dm
> +/obj/item/weapon/storage/belt/utility/chief/New()
У остальных тоже Невы. Переделывать в инишалайзы - аут оф скоуп. 
![image](https://user-images.githubusercontent.com/45202681/126646038-db60dfd6-d451-40b5-898b-b4f28db1167c.png)

2021-07-23 21:09 UTC, TermService commented
ну называть инструменты старыми и давать им лучшие боевые характеристики наверное не лучший вариант, может все таки улучшенные?

2021-07-23 21:22 UTC, TobyThorne commented
> ну называть инструменты старыми и давать им лучшие боевые характеристики наверное не лучший вариант, может все таки улучшенные?

Не, сосмысл как раз в том, что они старые, их спрайты - легаси десятилетней давности. А раньше, как известно, всё было лучше. Трава зеленее, сталь крепче, а инструменты робастнее.

2021-07-23 21:37 UTC, TermService approved these changes
похуй на нью

2021-07-25 08:58 UTC, HonkyDonky approved these changes
Деды играли

2021-07-25 09:51 UTC, igorsaux approved these changes

2021-07-26 12:46 UTC, kreeperHLC approved these changes

2021-07-26 14:30 UTC, merged