fix(suicide): Fixed many bugs with gunshot suicide
ChaoticOnyx/OnyxBay pull request #6192
Opened 2021-07-23 08:25 UTC by Oubifx

- Добавлена проверка на открытость рта (до этого можно было заснуть оружие в рот даже в воидсуите)
- Имитация выстрела заменена на реальный выстрел с дропом гильзы, раньше гильза не дропалась, патрон в стволе не тратился, да и в целом можно было застрелиться полностью разряженным оружием.
- Вероятность суицида теперь зависит от патрона в стволе. Есть большая вероятность застрелиться даже резиновой пулей (урон по мозгу).

fix #6130
fix #4846

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
bugfix: Исправлена серия багов суицида с помощью огнестрела, теперь он работает более предсказуемо
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-23 08:27 UTC, Zert0X commented
>Имитация выстрела заменена на реальный выстрел с дропом гильзы, раньше гильза не дропалась, патрон в стволе не тратился, да и в целом можно было застрелиться полностью разряженным оружием.
Браузер же чинил это, или недочинил?

2021-07-23 08:37 UTC, Oubifx commented
Выстрел без патрона всё же чинил, исправил ПР

2021-07-23 08:39 UTC, Zert0X commented
> 
> 
> Выстрел без патрона всё же чинил, исправил ПР

Ар ю уверен?
>патрон в стволе не тратился.

2021-07-23 08:41 UTC, NefrNerf commented
Я в край не понимаю, зачем ` Вероятность суицида теперь зависит от патрона в стволе. Есть большая вероятность застрелиться даже резиновой пулей (урон по мозгу).`, опция суицида сделана для гарантии, что ты улетаешь в госты, а не ШАНСА улететь в госты, а не лежать 3 минуты или более в агонии

2021-07-23 08:48 UTC, Oubifx commented
> Я в край не понимаю, зачем ` Вероятность суицида теперь зависит от патрона в стволе. Есть большая вероятность застрелиться даже резиновой пулей (урон по мозгу).`, опция суицида сделана для гарантии, что ты улетаешь в госты, а не ШАНСА улететь в госты, а не лежать 3 минуты или более в агонии

Критикуешь - предлагай. Предложи НЕ КОСТЫЛЬНУЮ проверку на патрон в стволе который должен убить тебя.

2021-07-23 08:50 UTC, Oubifx commented
> > Выстрел без патрона всё же чинил, исправил ПР
> 
> Ар ю уверен?
> 
> > патрон в стволе не тратился.

Уверен, как было в магазине 5 патронов до суицида, так и осталось 5 после.

2021-07-23 08:50 UTC, Zert0X commented on code/modules/projectiles/gun.dm
> -			playsound(user, shot_sound, 50, 1)
Куда потерял, расскажи пожалуйста

2021-07-23 08:50 UTC, Zert0X commented on code/modules/projectiles/gun.dm
> +			to_world("inchamber=[ref(in_chamber)] | pm=[in_chamber.penetration_modifier] | pen=[in_chamber.armor_penetration] | dam=[in_chamber.damage]")
не совсем понимаю, зачем это и кому оно надо, если это дебаг строка удали

2021-07-23 09:02 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +			to_world("inchamber=[ref(in_chamber)] | pm=[in_chamber.penetration_modifier] | pen=[in_chamber.armor_penetration] | dam=[in_chamber.damage]")
> не совсем понимаю, зачем это и кому оно надо, если это дебаг строка удали
to_world удалил, забыл про этот дебаг.
Админ лог оставил, он там и был раньше

2021-07-23 09:45 UTC, MrMagick2104 commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
Если у тебя закрыт рот, не лучше ли просто менять сообщение о самоубийстве с: "Космонавт засовывает в рот ствол пистолета", - на условное: "Космонавт приставляет к виску ствол пистолета"?

Добавлять необходимость закликивать себе голову с пистолета на харме в войдсьюте/противогазе/маске клоуна с последующим наблюдением блекскрина до 50% брейндамага для переезда в гостчат - такое себе. Убиваешь себя ты всегда сам, так что смысла контрить это закрытием рта нет.

2021-07-23 10:20 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> -			playsound(user, shot_sound, 50, 1)
В этом костыле пропала нужна, поскольку обработка звука идет в FIre()

2021-07-23 10:32 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
Не хочешь лежать в блекскрине, после попытки застрелиться с сигнального пистолета или выстрелом в себя через harm? Велком то OOC > Ghost.
`Убиваешь себя ты всегда сам, так что смысла контрить это закрытием рта нет.`
Смысл есть. Когда находясь во враждебной среде (газ, космос) игрок в воидсуте попытается застрелитсья, что бы не отдать своё тело алиенам, то у него не будет 100%-й вероятности сделать это. Он или должен будет стрелять через броню в голову, или должен будет снять шлем и столкнулся с враждебной средой. Подобных примеров может быть еще парочку, так что всё логично и продумано.

2021-07-23 10:35 UTC, NefrNerf commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
Что за бред, если человека выебал чужой, то он уже по определению без войдсюта

2021-07-23 10:37 UTC, NefrNerf commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
`Не хочешь лежать в блекскрине, после попытки застрелиться с сигнального пистолета или выстрелом в себя через harm? Велком то OOC > Ghost.` - И получаешь, You cannot ghost right now

2021-07-23 10:43 UTC, MrMagick2104 commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
> Не хочешь лежать в блекскрине, после попытки застрелиться с сигнального пистолета или выстрелом в себя через harm? Велком то OOC > Ghost.

У нас гост работает как и суккумб после 50% брейндамага, не?

> Он или должен будет стрелять через броню в голову, или должен будет снять шлем и столкнулся с враждебной средой.

Да речь не только про войдсьюты. Любая маска блокирует рот. Даже маска клоуна/мима.

С войдсьютом условная ситуация: ты в противогазе, ты в войде ходишь по помещениям, заполненным усыпляющим газом. Хочешь застрелиться, чтобы уйти в гост более-менее красиво - падаешь в стан от газа, ведь через противогаз застрелиться нельзя, а стреляние в рот *очень долгое*.

Как уже заметили, пример с алиенами некорректный, а других я как-то вообще не вижу.
<hr>

Имхо, самоубийство нужно просто потому, что убивать себя закликиванием по голове выглядит некрасиво и вызывает крайне долгие лежания в ожидании. Убирать возможность уйти красиво в каких-либо ситуациях - такое себе.


Плюс, если твой труп потом находит детектив, видит, что кто-то выстрелил тебе две обоймы в голову, он предположит, что это было не самоубийство. Чисто со стороны это выглядит максимально глупо.

2021-07-23 10:45 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			Fire(user, user, src, "head")
Круто, два раза патрон используем, и затем у нас будет qdeleted twice

2021-07-23 10:49 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
Если человека еще не выебал чужой, но ломит к нему шлюз/барикады что бы выебать, то он определенно еще жив и метаголовой хочет покончить с собой, что бы алиенов не стало больше.
Если каким-то чудом резина тебя не убила, то не переживай, в любом случае открывается форсированное кровотечение, которое не даст тебе долго "мучаться" особенно когда у мозга осталось не больше 15-ти ХП, ведь брейндамаг наносится неплохой.

2021-07-23 10:50 UTC, NefrNerf commented
Может стоит позвать геймдизов и узнать их мнение по возможности суицида и способам оного? Так-то можно разжевывать эту механику и искать экслопиты. Эксполиты вообще можно найти везде, для регулирования таких случаев педали существуют

2021-07-23 10:53 UTC, Oubifx commented
> Может стоит позвать геймдизов и узнать их мнение по возможности суицида и способам оного? Так-то можно разжевывать эту механику и искать экслопиты. Эксполиты вообще можно найти везде, для регулирования таких случаев педали существуют

Я не вижу проблем в текущем варианте, всё закономерно и логично

![image](https://user-images.githubusercontent.com/24242919/126772162-209587eb-8e95-410d-ad6f-395a10b9f0ad.png)

2021-07-23 10:54 UTC, NefrNerf commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
Оуби, это больше похоже на попытки отстоять СВОЕ видение игрового процесса любыми методами. Не починить, а уже пропихнуть, как человек должен реагировать на какую-то ситуацию.
`Если человека еще не выебал чужой, но ломит к нему шлюз/барикады что бы выебать, то он определенно еще жив и метаголовой хочет покончить с собой, что бы алиенов не стало больше.` Где метаголова тут, знаешь, люди совершают суицид от безвыходных ситуаций.

2021-07-23 11:07 UTC, MrMagick2104 commented
А при чём тут станпульки вообще?
Речь про маски и про отбирание у человека возможности к суициду.

А говоря про станпульки, то одни пороховые газы должны достаточный ущерб нанести.
Если очень стараться, можно застрелиться и из холостых, чисто технически.
Лучше бы при стрельбе себе в рот поднять урон раз в 5-10 и направлять его исключительно по мозгу, а там уж само как сложится, в этом плане.

2021-07-23 11:11 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
Метаигроков встречаю довольно таки часто на хаотике, от сюда и такое _личное_ виденье, которое я не кому не навязываю. В любом случае контекст вне зависимости от двух озвученных вариантов не меняется. Разницы в `суицид от безвыходных ситуаций` и `метаголовой хочет покончить с собой, что бы алиенов не стало больше` нет, в любом случае действие будет одно и то же.

2021-07-23 11:17 UTC, NefrNerf commented on code/modules/projectiles/gun.dm
> +		to_chat(M, SPAN_WARNING("\The [blocked] is in the way!"))
За явную мету наказывают педали, неявную ты не определишь. Полагаю тут нужен развернутый ответ геймдизов, какой вид суицида должен быть реализован

2021-07-23 11:22 UTC, Zert0X commented
> Если очень стараться, можно застрелиться и из холостых, чисто технически.

Не технически, а фактически.

2021-07-24 09:21 UTC, Oubifx commented
@Doster-d Вчитался в код более подробно и допилил тот вариант, который был до этого. Теперь всё должно быть в разы лучше. Только вот немного удивлен тому что досылка патрона в патронник происходит до самого выстрела, а не после, как и должно быть.

2021-07-24 20:01 UTC, igorsaux commented
выглядит как геймдиз

2021-07-28 23:16 UTC, TobyThorne commented
Блокировка суицида масками не нравится. Лучше уж если лицо закрыто - вместо "пушка в рот" выводить "пушка у виска" и брать в расчёт урона броню, если она есть.

2021-07-29 15:58 UTC, Oubifx commented
@TobyThorne поправил. Добавил обработку нанесения урона в зависимости от типа урона боеприпаса. И поменял еще прок который наносит урон и поигрался с цифрами. Стреляя в security voidsuit helmet с боевого 45-го - есть очень маленький шанс выжить. Всё как и хотел

2021-08-06 21:16 UTC, kreeperHLC requested changes

2021-08-06 21:16 UTC, kreeperHLC commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2,5), used_weapon = src)
```suggestion
			var/result_dmg = in_chamber.damage * ((100 - (M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration))) / 100)
			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
			user.adjustBrainLoss(amount = (result_dmg * rand(3, 4)))
			if(in_chamber.check_armour == "bullet" || in_chamber.check_armour == "melee")
				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2, 5), used_weapon = src)
			else
				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2, 5), used_weapon = src)
```

2021-08-20 14:41 UTC, Doster-d requested changes

2021-08-20 14:41 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +	if(M.check_mouth_coverage())
Оставлю тут, но надо поставить эту строку на 384, тут еще спаны.
```suggestion
	M.visible_message(SPAN("danger", "[user] [M.check_mouth_coverage() ? "puts a gun to his temple" : "sticks their gun in their mouth"], ready to pull the trigger..."))
```

2021-08-20 14:41 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2, 5), used_weapon = src)
В оригинале просто аутопсай, в описание ПР не нашел этот момент
```suggestion
				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2, 5), used_weapon = used_weapon = "Point blank shot in the mouth with \a [in_chamber]")
```

2021-08-20 14:41 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2, 5), used_weapon = src)
```suggestion
				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2, 5), used_weapon = used_weapon = "Point blank shot in the mouth with \a [in_chamber]")
```

2021-08-22 12:27 UTC, Oubifx commented
@Doster-d 
Поправлены все спаны в файле.
Вернул текст для autopsy.

2021-08-31 06:54 UTC, NefrNerf reviewed
Вроде все работает. Достер, Голиаф тут автор вас дожидается.

2021-08-31 07:10 UTC, kreeperHLC requested changes

2021-08-31 07:10 UTC, kreeperHLC commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
А вот это что за чудопроверки? Проверка на армор пули и если это не мелишка или пуля, то это точно будет бёрн? Почему вообще тут название, а выше у проверки дефайн? Слишком сложно для меня, объясните

2021-08-31 07:51 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
Ну так открой код и почитай. 
`var/check_armour = "bullet" //Defines what armor to use when it hits things.  Must be set to bullet, laser, energy,or bomb	//Cael - bio and rad are also valid`
Резинострел перед нанесением урона обращается к связному списку брони где описана сопротивляемость разным источникам урона. Вся резина проверяет армор на "melee". Всё зависит от пули. Стан пули/лазер, так вообще проверяют армор на "energy".
Почему тут название, а вышей дефайн? Я не знаю что ты именно имел введу выше, ибо там еще 400 строк, но в дефайнах у нас только тип урона который можно получить. Существовал бы нужный дефайн - использовал бы дефайн. А здесь как видишь уже другой велосипед изобретенный до нашей эры, не имеющий аналогов среди других велосипедов изобретенных еще ранее.

2021-08-31 08:00 UTC, kreeperHLC commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
> Ну так открой код и почитай.
Я сам догадался, но не мог понять почему у тебя проверки только на милишку и пулю. Видимо про рад урон и бомб мы уже забыли? 
> Почему тут название, а вышей дефайн?
Да, моя ошибка. Посмотрел на if(in_chamber.damage_type != PAIN) и не заметил что тут damage_type. Хотя в любом случае смешно. Проверяем что оно не дамажит пейном, но для определения урона используем броню.

2021-08-31 08:27 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
> Я сам догадался, но не мог понять почему у тебя проверки только на милишку и пулю. Видимо про рад урон и бомб мы уже забыли?

Ну так с бомбы в рот не выстрелишь) В игре только кинетическое оружие шахтера проверяет армор на "bomb". Да и про рад урон не знаю, знаю только пушку стреляющую кислотой, но там гиб в любом случае будет, ибо  у неё урон большой. В общем не имеет смысла что-то обрабатывать кроме bullet и melee. Имеет смысл делать рефакторинг всех велосипедов, но это уже история о других ПР-ах или их отсутствии.

2021-08-31 08:54 UTC, kreeperHLC commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(burn = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
> > Я сам догадался, но не мог понять почему у тебя проверки только на милишку и пулю. Видимо про рад урон и бомб мы уже забыли?
> 
> Ну так с бомбы в рот не выстрелишь) В игре только кинетическое оружие шахтера проверяет армор на "bomb". Да и про рад урон не знаю, знаю только пушку стреляющую кислотой, но там гиб в любом случае будет, ибо у неё урон большой. В общем не имеет смысла что-то обрабатывать кроме bullet и melee. Имеет смысл делать рефакторинг всех велосипедов, но это уже история о других ПР-ах или их отсутствии.

Ну короче, аппрув дам, но с натяжкой. Какие-то костыли пихаешь, может другие Девы будут против их

2021-08-31 08:54 UTC, kreeperHLC approved these changes

2021-09-01 17:23 UTC, TermService approved these changes

2021-09-08 09:08 UTC, kcalbCube requested changes

2021-09-08 09:08 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
ебана рот, вынеси в переменную

2021-09-08 09:08 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
>  	mouthshoot = 1
эта штука ещё нужна?

2021-09-08 11:01 UTC, Oubifx commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
Ты же про ```in_chamber.check_armour```? Зачем же создавать переменную внутри процедуры для уже существующей переменной? Время выполнения мы не выиграем, читаемость не повысим. Да и в целом код выполняет то что от него требуется, доводить до идела нет смысла, это никому не нужно. Если ты про что-то другое, то поправь, ибо я не совсем понимаю что тут еще можно заносить в переменную.

2021-09-08 11:05 UTC, Oubifx commented on code/modules/projectiles/gun.dm
>  	mouthshoot = 1
Здесь всё нужно. А если сильно заебаться (и отрефакторить весь код), то может и не нужно будет, но кому нужно сильно заёбываться если этого сейчас не требуется.

2021-09-08 15:18 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
в двух ветках все одинаково кроме выбора брута или берна.
зачем код загромождать

2021-09-08 15:18 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
>  	mouthshoot = 1
)

2021-09-08 15:20 UTC, kcalbCube requested changes
пуш неидеального кода не одобрен корпорацией xyz, так что улучшай. 
отговорки типа "работает зачем менять" идут нахуй.

2021-09-08 15:24 UTC, Doster-d commented on code/modules/projectiles/gun.dm
>  	mouthshoot = 1
> Здесь всё нужно. А если сильно заебаться (и отрефакторить весь код), то может и не нужно будет, но кому нужно сильно заёбываться если этого сейчас не требуется.

Нет, это нужно, чтобы в человека не стреляло сразу 4 граббера, как в том фильме с чернокожими мужчинами и белым мужиком, а только 1, по другому ты это не сделаешь.

2021-09-08 15:26 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
Единственное, что здесь надо вынести в переменную это used_weapon и result_dmg * rand(2,5).

2021-09-08 15:29 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
used_weapon тот же
в итоге получаем две строки отличающиеся на четыре байта

2021-09-08 15:29 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
```suggestion
			log_and_message_admins("[key_name(user)] try to commit suicide using \a [src]")
```

2021-09-08 15:31 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			var/result_dmg = in_chamber.damage * ((100 - (M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration))) / 100)
```suggestion
			var/result_dmg = in_chamber.damage * (1 - M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration / 100)
```

2021-09-08 15:43 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
+

2021-09-08 15:43 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +				M.get_organ(BP_HEAD).take_external_damage(brute = result_dmg * rand(2,5), used_weapon = "Point blank shot in the head with \a [in_chamber]")
+, но с аргументации не согласен, не является основанием для чендж реквестам, основанием является дублирования кода.

2021-09-08 15:55 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			var/result_dmg = in_chamber.damage * ((100 - (M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration))) / 100)
Он же говорит, что мы сначала вычитаем из 100 возвращаемое значения функции от 0 до 100, а затем получившиеся число делим на 100, а ты предлагаешь ему вычесть из 1 возвращаемое значение функции от 0 до 100, а затем получившиеся число делим на 100.
У меня в школе по алгебре была двойка, но я не понимаю сути этого реквеста.
Тем более твое изменение, на мой взгляд, сильно принижает получаемый дамаг из-за изменения третьего параметра с понижением делением на 100.
В коде автора есть лишние скобки, их надо бы убрать.
```suggestion
			var/result_dmg = in_chamber.damage * ((100 - M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration)) / 100)
```

2021-09-08 15:56 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
А может нам прошедшее время нужно, Сфера?
```suggestion
			log_and_message_admins("[key_name(user)] tried to commit suicide using \a [src]")
```

2021-09-08 16:00 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			var/result_dmg = in_chamber.damage * ((100 - (M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration))) / 100)
нене всё правильно
```suggestion
			var/result_dmg = in_chamber.damage * (1 - M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration) / 100)
```

2021-09-08 16:00 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			var/result_dmg = in_chamber.damage * ((100 - (M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration))) / 100)
я просто сонный скобку забыл

2021-09-08 16:01 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
так идеально

2021-09-08 16:03 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			var/result_dmg = in_chamber.damage * ((100 - (M.run_armor_check(BP_HEAD, in_chamber.check_armour, in_chamber.armor_penetration))) / 100)
А, ты сначала хочешь получать число из функции, делить на 100, а затем из 1 получать коэффицента для дамага, я понял, кул, +

2021-09-08 16:04 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
Просто try to commit, наверное, означает период когда идет do_after, а тут у нас было сообщения (до изменения автора) о том, что он УЖЕ совершил суицид.

2021-09-08 16:06 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
а тут разве try кстати
урон уже наносится
тогда уж 
```suggestion
			log_and_message_admins("[key_name(user)] have commited suicide using \a [src]")
```

2021-09-08 16:08 UTC, Doster-d commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
Да, но он же поменял, что оружие может и не убить, предлагаю это:
```suggestion
			log_and_message_admins("[key_name(user)] have tried commit suicide using \a [src]")
```

2021-09-08 16:22 UTC, kcalbCube commented on code/modules/projectiles/gun.dm
> +			log_and_message_admins("[key_name(user)] try commited suicide using \a [src]")
вариант.

2021-10-14 01:21 UTC, TobyThorne commented
Автор умер, а ченжреквесты остались. Может быть, кто-то унаследует ПР. А может - автор оживёт.
Но сегодня мы это уже не узнаем.

2021-10-14 01:21 UTC, closed without merging