Ограничение на вступление в культ
ChaoticOnyx/OnyxBay pull request #6193
Opened 2021-07-23 12:53 UTC by NefrNerf

Добавил ограничение на вступление в культ различных существ: дион, генокрадов, магов
В связи вводом насильного конверта и возможного абуза магами который будет сложно отследить введен гиб всех участников ритуала, для ограничения желания рьяных культистов.

Добавил язык культа магу, так как если он захочет создавать конструкты то с новыми ограничениями никак не сможет их понять.

- [x] close #1896

<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Генокрад больше не может вступить в культ.
balance: Диона больше не может вступить в культ.
balance: При успешной конвертации мага в культ происходит гиб мага и культистов участников ритуала.
tweak: Теперь маг понимает язык культистов.

/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-24 10:14 UTC, Oubifx commented
А если культисты не будут знать что перед ними генокрад? Это же не маг или диона, которых и так видно

2021-07-24 10:29 UTC, NefrNerf commented
Ничего не будет, гибфест только ушлым магам и культу, генокраду ничего не будет

2021-07-24 15:08 UTC, bosslobster commented
Предлагаю также автоматическую выдачу гибнутому магу недельной джобки на магов и дня бана за повергейм

2021-07-24 16:38 UTC, NefrNerf commented
Ну все, теперь конвертация ролек порезана полностью. Можно ревювать.

2021-07-24 21:02 UTC, TobyThorne requested changes
с грамматикой ебда

2021-07-27 08:36 UTC, Zert0X requested changes

2021-07-27 08:36 UTC, Zert0X commented on code/game/gamemodes/cult/runes.dm
> +	else if(isChangeling(usr))
```suggestion
	else if(isChangeling(target))
```

2021-07-27 08:36 UTC, Zert0X commented on code/game/gamemodes/cult/runes.dm
> +	else if(isXenomorph(usr))
```suggestion
	else if(isXenomorph(target))
```

2021-07-27 08:57 UTC, NefrNerf commented
Сможешь ещё подправить инглиш граммар?

2021-07-27 08:57 UTC, Zert0X commented
> 
> 
> Сможешь ещё подправить инглиш граммар?

Май инглиш граммар нот соу гуд аз ю синк

2021-07-27 08:58 UTC, NefrNerf commented
Фак, гат дэмн

2021-07-27 12:47 UTC, MaxFreemen reviewed
Ёр инглиш из окей, бат ай файнд а фью мистайкес.

2021-07-27 12:47 UTC, MaxFreemen commented on code/game/gamemodes/cult/runes.dm
> +		to_chat(target, SPAN("changeling", "Powers of these filthy creatures does not have effect on us"))
```"Powers of these filthy creatures don't affect on us"``` - Сил много, а используется ```does``, еще имеется ```affect```, который лучше впишется сюда.

2021-07-27 12:47 UTC, MaxFreemen commented on code/game/gamemodes/cult/runes.dm
> +		to_chat(target, SPAN_DANGER("Hive mind rejects offer of these creatures"))
```"Hive mind rejects these creatures offer"``` - так будет лучше звучать.

2021-07-27 12:47 UTC, MaxFreemen commented on code/game/gamemodes/cult/runes.dm
> +		to_chat(target, SPAN_DANGER("Hive mind rejects offer of these creatures"))
```"Hive mind rejects these creatures offer"``` - опять же.

2021-07-27 13:15 UTC, MaxFreemen commented on code/game/gamemodes/cult/runes.dm
> +		to_chat(target, SPAN_DANGER("Your magick powers resists being corupted. DEATH IS COMMING FOR THESE FOOLS AND YOU"))
```"Your magic powers resist being corupted. DEATH IS COMMING FOR THESE FOOLS AND YOU"``` - какой-то ```magick``` и лишнее окончание ```s```.

2021-08-09 16:16 UTC, NefrNerf commented
Вроде поправил

2021-08-11 01:24 UTC, TobyThorne commented
Чёт мне взаимодействие с визордом не нравится. Лучше сделать смешное, пускай культисты при конверте гиббаются, но визард всё же конвертится.

2021-08-12 09:42 UTC, NefrNerf commented
Я сделал еще веселее, при конверте маг теряет способности и становиться культистом, а культист гибается, потеря способностей - хуже гиба.

2021-08-18 16:10 UTC, NefrNerf commented
Что-то пошло не так

2021-08-18 16:14 UTC, NefrNerf commented
Немного не понимаю, что я тут сделал, желательно бы помощь

2021-08-18 18:24 UTC, closed without merging