tweak(poise) add multiply coefficient to damage poise
ChaoticOnyx/OnyxBay pull request #6218
Opened 2021-07-25 12:14 UTC by Doster-d

По запросу лида.
Еще убрал кринж, где идет проверка бодибилда по имени.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Слим людям теперь наносится урон пойза в 50 * 1/2/3/5 больше, чем обычным людям.
tweak: Слим таяры теперь наносят меньше урона, как слим люди.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-25 12:32 UTC, MrMagick2104 commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 50 * 1/2/3/5 // 1.6666666666666667, coefficient to multiply damage poise, used on slim human.
![jrnging](https://user-images.githubusercontent.com/58848742/126898892-bdd5c0ec-815f-452e-b3d4-805d2b859db0.png)

```suggestion
#define DOSTER_SLIM_COEFFICIENT 5/3 // 1.6666666666666667, coefficient to multiply damage poise, used on slim human.
```

2021-07-25 12:33 UTC, Doster-d commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 50 * 1/2/3/5 // 1.6666666666666667, coefficient to multiply damage poise, used on slim human.
У меня строка больше, твои цифры говно перед моими.
![image](https://user-images.githubusercontent.com/63081538/126899095-99599223-8617-409a-8086-62cc5b240369.png)

2021-07-25 12:47 UTC, quardbreak commented
Хардкода какойто.

2021-07-25 12:49 UTC, Doster-d commented
> Хардкода какойто.

Ты про это?
![image](https://user-images.githubusercontent.com/63081538/126899572-3097ff57-f368-4367-b215-dc434658530f.png)

2021-07-25 12:56 UTC, quardbreak commented
Я про дефайн. Можно было вынести в общую переменную для всех бодитайпов и только подправить для тонких. Но хз будет ли это на практике использоваться.

2021-07-25 13:01 UTC, Doster-d commented
> Я про дефайн. Можно было вынести в общую переменную для всех бодитайпов и только подправить для тонких. Но хз будет ли это на практике использоваться.

Ради одного случая? Кринж как по мне.

2021-07-25 13:08 UTC, TobyThorne requested changes

2021-07-25 13:08 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 5/3 // 1.6666666666666667, coefficient to multiply damage poise, used on slim human.
иди сначала Virus Suka Blyat System (или как там его обозвал) пофикси

2021-07-25 13:36 UTC, Doster-d commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 5/3 // 1.6666666666666667, coefficient to multiply damage poise, used on slim human.
Сделал, будет зеленая галка?

2021-07-25 19:39 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 5/4.45 // 1.1235955056179774, coefficient to multiply damage poise, used on slim human.
Чтобы что. Зачем впихивать лишнюю операцию, если можно просто воткнуть 1.1?

2021-07-25 20:14 UTC, Doster-d commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 5/4.45 // 1.1235955056179774, coefficient to multiply damage poise, used on slim human.
Нот кул вей.

2021-07-25 21:09 UTC, Doster-d commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 5/4.45 // 1.1235955056179774, coefficient to multiply damage poise, used on slim human.
Почему такое анфани :(
```suggestion
#define DOSTER_SLIM_COEFFICIENT 1.1 // 1.1, coefficient to multiply damage poise, used on slim human.
```

2021-07-26 10:28 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 1.1 // 1.1, coefficient to multiply damage poise, used on slim human.
А теперь ещё нормальное название и можно в прод.

2021-07-26 12:26 UTC, Doster-d commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 1.1 // 1.1, coefficient to multiply damage poise, used on slim human.
Какое?

2021-07-27 08:56 UTC, Zert0X commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 1.1 // 1.1, coefficient to multiply damage poise, used on slim human.
DAMAGE_SLIM_COEFFICIENT?

2021-07-28 19:25 UTC, Doster-d commented on code/modules/mob/living/carbon/human/life.dm
> +#define DOSTER_SLIM_COEFFICIENT 1.1 // 1.1, coefficient to multiply damage poise, used on slim human.
Готово.

2021-07-31 16:23 UTC, kcalbCube reviewed
двигаемся в правильном направлении

2021-07-31 16:23 UTC, kcalbCube commented on code/modules/mob/living/carbon/human/life.dm
> +		dmg = dmg * DAMAGE_SLIM_COEFFICIENT
в DM'е нет *=?

2021-07-31 16:23 UTC, kcalbCube commented on code/modules/mob/living/carbon/human/life.dm
>  	poise -= dmg
алсо можно
```suggestion
	poise -= dmg * body_build.weak_body_build ? DAMAGE_SLIM_COEFFICIENT : 1
```

2021-08-11 09:53 UTC, PlinHost reviewed
Вместо чуть менее смешных ифов просто положи коэффициенты в бодибилды.

2021-08-15 13:24 UTC, igorsaux approved these changes, later dismissed

2021-08-15 17:15 UTC, kcalbSphere submitted a review, later dismissed

2021-08-21 17:22 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/poise_coefficient = 1
```suggestion
	var/taken_poise_dmg_coefficient = 1
```

2021-08-21 17:22 UTC, TobyThorne requested changes

2021-08-21 17:22 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/weapon_hit_coefficient = 1
```suggestion
	var/dealt_poise_dmg_coefficient = 1
```

2021-08-21 17:50 UTC, Doster-d commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/weapon_hit_coefficient = 1
done

2021-08-21 17:50 UTC, TobyThorne approved these changes
ебись оно все конем

2021-08-21 17:51 UTC, igorsaux approved these changes

2021-08-21 17:52 UTC, TobyThorne requested changes

2021-08-21 17:52 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/taken_poise_dmg_coefficient = 1
Стоп блять почему они одинаковые.

2021-08-21 17:52 UTC, igorsaux requested changes

2021-08-21 17:52 UTC, igorsaux commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/taken_poise_dmg_coefficient = 1
wtf как это работает

2021-08-21 17:54 UTC, Doster-d commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/taken_poise_dmg_coefficient = 1
a

2021-08-21 17:54 UTC, Doster-d commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/taken_poise_dmg_coefficient = 1
a

2021-08-21 17:55 UTC, igorsaux submitted a review, later dismissed

2021-08-31 06:58 UTC, NefrNerf reviewed
@TobyThorne Пусти уже ПР в билд, Достер вроде поправил

2021-09-01 05:31 UTC, TobyThorne requested changes

2021-09-01 05:31 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/dealt_poise_dmg_coefficient = 1
```suggestion
	var/dealt_melee_dmg_coefficient = 1
```

Чёт я и забыл, что у них понижен не пойздамаг, а вполне себе обычный.

2021-09-01 05:41 UTC, Doster-d commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/dealt_poise_dmg_coefficient = 1
Че? Я ничего не понял...

2021-09-01 05:43 UTC, TobyThorne requested changes

2021-09-01 05:43 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_defense.dm
> -			effective_force *= 0.75 // It's kinda hard to club people when you're two times thinner than a regular person.
Зачем здесь проебал проверку на шарп?

2021-09-01 05:43 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/body_build.dm
> +	var/dealt_poise_dmg_coefficient = 1
А, чекнул ещё раз, оно влияет и на пойз, и на просто урон.
Энивей лучше назвать dealt_melee_dmg_coefficient

2021-10-14 01:28 UTC, TobyThorne commented
Ченжреквест от первого сентября, активности нет. Достер, переоткрой, если решишь доделать.

2021-11-07 23:30 UTC, Doster-d commented
[long live the king](https://github.com/ChaoticOnyx/OnyxBay/pull/6907)

2021-11-07 23:30 UTC, closed without merging