feat(roundstart) add configuration vars to disable ooc at roundstart
ChaoticOnyx/OnyxBay pull request #6247
Opened 2021-07-28 12:44 UTC by Doster-d

Добавлены конфигурационные  вары для отключение ООЦ и/или ЛООЦ в начале раунда, ООЦ и/или ЛООЦ включаются после раунда автоматически, если были отключены раундстартом.

close #6241

<details>
<summary>Чейнджлог</summary>

```yml
🆑
admin: В конфиг добавлена возможность отключить LOOC и OOC раундстартом.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-28 13:59 UTC, kreeperHLC approved these changes

2021-07-28 14:03 UTC, igorsaux requested changes

2021-07-28 14:03 UTC, igorsaux commented on code/controllers/subsystems/ticker.dm
> +		to_world("<B>The OOC channel has been globally disabled!</B>")
```suggestion
		to_world("<b>The OOC channel has been globally disabled!</b>")
```

2021-07-28 14:03 UTC, igorsaux commented on code/controllers/subsystems/ticker.dm
> +		to_world("<B>The LOOC channel has been globally disabled!</B>")
```suggestion
		to_world("<b>The LOOC channel has been globally disabled!</b>")
```

2021-07-28 14:03 UTC, igorsaux commented on code/controllers/subsystems/ticker.dm
> +				to_world("<B>The OOC channel has been globally enabled!</B>")
```suggestion
				to_world("<b>The OOC channel has been globally enabled!</b>")
```

2021-07-28 14:03 UTC, igorsaux commented on code/controllers/subsystems/ticker.dm
> +				to_world("<B>The LOOC channel has been globally enabled!</B>")
```suggestion
				to_world("<b>The LOOC channel has been globally enabled!</b>")
```

2021-07-28 14:44 UTC, igorsaux submitted a review, later dismissed

2021-07-28 14:45 UTC, kreeperHLC approved these changes

2021-07-28 14:48 UTC, Epicus7 commented on code/controllers/subsystems/ticker.dm
> +			if(config.disable_ooc_r)
Включения на старте в иссуе не было. И непонятно что делать, если педаль хочет отключить, чтобы он не включался

2021-07-28 14:48 UTC, Epicus7 commented on code/controllers/subsystems/ticker.dm
> +		to_world("<B>The OOC channel has been globally disabled!</B>")
Есть уже два места, где скопирован этот текст. Ты делаешь третье. Может лучше сделать общий единственный прок, который будет переключать OOC/LOOC, а все три места будут уже его использовать?

2021-07-28 14:49 UTC, Epicus7 commented on code/controllers/subsystems/ticker.dm
> +		to_world("<b>The OOC channel has been globally disabled!</b>")
Есть уже два места, где скопирован этот текст. Ты делаешь третье. Может лучше сделать общий единственный прок, который будет переключать OOC/LOOC, а все три места будут уже его использовать?

2021-07-28 14:49 UTC, Epicus7 requested changes
По комментам выше

2021-07-28 15:38 UTC, Doster-d commented on code/controllers/subsystems/ticker.dm
> +			if(config.disable_ooc_r)
Очень просто, отключаешь disable_ooc_r и все.

2021-07-28 15:43 UTC, Epicus7 commented on code/controllers/subsystems/ticker.dm
> +			if(config.disable_ooc_r)
Кстати, да. disable_ooc_r и ooc_allowed - вообще непонятно чем отличаются. _r - непонятно про что и зачем там. Имена плохие тоже, да.

2021-07-28 15:53 UTC, Doster-d commented
Готово.

2021-07-28 15:54 UTC, Doster-d commented on code/controllers/subsystems/ticker.dm
> +		to_world("<b>The OOC channel has been globally disabled!</b>")
Сделал.

2021-07-28 15:54 UTC, Doster-d commented on code/controllers/subsystems/ticker.dm
> +			if(config.disable_ooc_r)
Удалил, теперь все точно по иссую!
Переименовал переменную.

2021-07-28 16:04 UTC, Epicus7 requested changes

2021-07-28 16:04 UTC, Epicus7 commented on code/game/world.dm
> +/proc/toggle_ooc(new_value = !(config.ooc_allowed))
Какой-то страшный аргумент ты нагородил, который никто не использует. Просто убери здесь аргумент и меняй значение на противоположное. Зачем так усложнять? toggle_ не подразумевает выбора, если ты хочешь выбирать значение, то надо называть прок set_

2021-07-28 16:04 UTC, Epicus7 commented on code/game/world.dm
> +/proc/toggle_ooc(new_value = !(config.ooc_allowed))
И тут еще заиспользуй этот прок, пожалуйста:

https://github.com/ChaoticOnyx/OnyxBay/blob/b9a8cd4f1ec1d3e6dbedf0f745bd50c4023181d8/code/game/world.dm#L403-L403

2021-07-28 16:06 UTC, Doster-d commented on code/game/world.dm
> +/proc/toggle_ooc(new_value = !(config.ooc_allowed))
Нормальный аргумент :(
А вот с именем согласен.

2021-07-28 16:12 UTC, Doster-d commented on code/game/world.dm
> +/proc/toggle_ooc(new_value = !(config.ooc_allowed))
Ну страшно, так страшно.

2021-07-28 16:24 UTC, Doster-d commented
Ну теперь нейтрально, наверное?

2021-07-28 16:52 UTC, Epicus7 requested changes

2021-07-28 16:52 UTC, Epicus7 commented on code/modules/admin/admin.dm
> +	toogle_ooc(!(config.ooc_allowed))
```suggestion
	toogle_ooc()
```

2021-07-28 16:52 UTC, Epicus7 commented on code/game/world.dm
> +		toogle_ooc(!(config.ooc_allowed))
```suggestion
		toogle_ooc()
```

2021-07-28 17:52 UTC, TobyThorne commented on code/game/world.dm
> +/proc/toogle_ooc()
Откуда две "о" в toggle.

2021-07-28 17:53 UTC, Doster-d commented on code/game/world.dm
> +/proc/toogle_ooc()
Я же менял, откуда это...

2021-07-28 17:54 UTC, Doster-d commented on code/game/world.dm
> +/proc/toogle_ooc()
Блять, это аномалия.

2021-07-28 18:59 UTC, Epicus7 commented on code/game/world.dm
> +/proc/toogle_ooc()
Из Эпикуса

2021-07-28 19:06 UTC, Doster-d commented on code/game/world.dm
> +/proc/toogle_ooc()
Исправил.

2021-07-28 19:06 UTC, Epicus7 submitted a review, later dismissed

2021-07-28 19:20 UTC, kreeperHLC submitted a review, later dismissed

2021-07-30 08:27 UTC, quardbreak requested changes

2021-07-30 08:27 UTC, quardbreak commented on code/game/world.dm
> +        toggle_looc()
Братан почини табы.

2021-07-30 09:19 UTC, kreeperHLC approved these changes

2021-08-05 22:29 UTC, igorsaux commented
>ЛООЦ

зачем а главное нахуя, да и в оригинальном иссуе про него ничего нет

2021-08-05 22:31 UTC, Doster-d commented
> >ЛООЦ
> 
> зачем а главное нахуя, да и в оригинальном иссуе про него ничего нет

В LOOC есть подstring OOC.

2021-09-03 18:24 UTC, TermService approved these changes

2021-09-03 18:26 UTC, merged