Питомцы.
ChaoticOnyx/OnyxBay pull request #6259
Opened 2021-07-30 17:46 UTC by Doster-d

Для того, чтобы не переписывать код конкретной реализации животного, вводится новая переменная the_real_src, которая по умолчанию является src, все действия логики животного производится на этим the_real_src, в реализации мастер класса питомцев производится создания животного из пути и установления the_real_src на объект мастер класса питомцев.

У всех питомцев "голосовое управление".

У питомцев есть три команды: "идти за мной" - идет за мастером, "стой тут" - животное будет ходить только в зоне, где было животное на момент подачи команды, "прогуляйся" - животное переходит в стандартное поведение, будет бродить везде, где сможет пройти, в такой режим животное переключается в "любой непонятной ситуации", на текущий момент - когда подняли и когда в режим "стой тут" животное находится за пределами своей зоны.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлены питомцы (временно недоступны для покупки).
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-30 17:49 UTC, Doster-d commented
Добавил в описание пресеты.

2021-07-30 18:38 UTC, Doster-d commented
Думаю эти два лейбла соответствуют the_real_src

2021-07-30 18:54 UTC, Epicus7 requested changes
Реализация питомцев через "холдер" и "real_src" - ужасно сложная и неподдерживаемая. При любых изменениях мобов потом эта логика просто расползется.

Предлагаю сделать классы
`/datum/mob_ai`
`/datum/mob_ai/pet`

В них реализовать всю новую логику и запихать их инстансы внутрь /mob. Там внутри все нужны вызовы передавать в ai, а если его нет - то ничего не передавать, что логично)

Короче в дискорде обсудили подробнее эту идею, так реально попроще и понятнее будет.

2021-07-30 18:54 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	var/mob/the_real_src
Не понял прикола с the_real_src. Если src реальный ломает кто-то, лучше бы его починить. А то как уже шутим в разработке через некоторое время появятся всякие `the_really_real_src_for_sure`.

2021-07-30 18:54 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/pets.dm
> +#define COMMAND_WANDERING "прогуляйся" // set pet behaviour to basic behaviour: wandering
Мы не пишем русский текст в билде, нужно в конфиг выносить. Алсо я бы сделал отдельную папочку в config/names/pet_commands, куда положил бы файлики "stop_command.txt", "follow_command.txt" и "command_wandering.txt" и дал бы возможность писать туда много разных вариантов. Каждая строчка - отдельный вариант.

В идеале можно еще склонения сделать, но это сложно и Pos большой молодец, что осилил это с кодовыми фразами трейторов :)  Здесь можно забить, это улучшение на целый отдельный сложный ПР.

2021-07-30 18:54 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/pets.dm
> +		pet_holder.the_real_src = src
У тебя тут циклическая ссылка pet_holder <-> реальный моб. Они друг на друга ссылаются и никогда не удалятся.

Вообще все ссылки на объекты в определении выше надо подчищать в Destroy(). Что-то надо удалять через qdel, если твой объект этим владеет.

Я здесь довольно подробно писал про это:
https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2

2021-07-30 18:54 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/pets.dm
> +	if(pet_path)
ASSERT может быть? Это же не нормальная ситуация.

2021-07-30 18:54 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/pets.dm
> +	gender = pet_holder.gender
Вот это вот пипец полный, потому что когда в мобе реальном что-то из этого поменяют - здесь тупо забудут. Так нельзя писать, если мы не хотим вечно это дебажить.

2021-07-30 18:54 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/friendly/pets.dm
> +	. = pet_holder?.hit_with_weapon(arglist(args))
С этими проками тоже самое, что и с `sync_with_pet_holder`. Если новые проки добавят - их забудут тут пробросить, в итоге твои питомцы станут неубиваемыми.

2021-07-30 18:56 UTC, Epicus7 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	var/mob/the_real_src
Оказалось реальный src не ломают, а это такая реализация холдера моба, чтобы накрутить логику питомцев. Так лучше не делать, да. Обсудили в дискорде.

2021-07-30 20:20 UTC, Doster-d commented
Пофиксил кринж.

2021-08-10 11:38 UTC, Doster-d commented on code/modules/mob/living/simple_animal/friendly/pets.dm
> +#define COMMAND_WANDERING "прогуляйся" // set pet behaviour to basic behaviour: wandering
Сделал без склонений, очень больно.

2021-08-10 11:38 UTC, Doster-d commented
Проблем резолведс, реди ту ревью.

2021-08-26 19:11 UTC, Epicus7 requested changes
Уже стало гораздо лучше, чем было до этого. mob_ai - вообще классная штука получается + убрали часть кода из simple_animal.

Но много проблем есть разных, уже более локальных. Кажется сейчас оно не работает вообще, видимо ты не особо тестил)

Помимо всего что я тут написал - я бы попозже еще посмотрел реализацию команд (вот это вот следовать, стоять и wandeting), с ними разбираться уж не стал пока, и так много всего. Но в идеале команды надо потестить на локалке, что они работают. Если все заработает, то можно будет не смотреть особо.

2021-08-26 23:13 UTC, Epicus7 requested changes
Лучше бы конечно семантику состояний лучше прописать. Ввести понятие "состояние", ввести у состояний проки входа и выхода из состояния + сделать переключатели состояний, которые уже вызывались бы из listen. Но ладно, оставим это на будущее.

Но команды надо потестить локально, что они реально работают. Реализация команд неоч красивая, я практически уверен что в ней баги. Фатальные вещи можно отловить локальным тестом, более мелкие потом пофиксим.

2021-08-27 09:39 UTC, Epicus7 approved these changes
Так, ну ок. А чо с тестами то?

![image](https://user-images.githubusercontent.com/5204667/131107124-1528b7ce-77ba-42f7-9939-e53d33c30e76.png)

Ты проверил в итоге все три команды на локалке?

2021-08-28 02:28 UTC, kcalbCube reviewed
кодстайл слабый.
и нужно побольше команд.

2021-08-28 02:28 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	//Movement
```suggestion
	// Movement
```

2021-08-28 02:28 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	if(!holder.client && !holder.stop_automated_movement && holder.wander && !holder.anchored)
лесенку можно и убрать.

2021-08-28 02:28 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +		if(isturf(holder.loc) && !holder.resting && !holder.buckled)		//This is so it only moves if it's not inside a closet, gentics machine, etc.
```suggestion
		if(isturf(holder.loc) && !holder.resting && !holder.buckled)		// This is so it only moves if it's not inside a closet, gentics machine, etc.
```

2021-08-28 02:28 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +				if(!(holder.stop_automated_movement_when_pulled && holder.pulledby)) //Some animals don't move when pulled
```suggestion
				if(!(holder.stop_automated_movement_when_pulled && holder.pulledby)) // Some animals don't move when pulled
```

2021-08-28 02:28 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	//Speaking
```suggestion
	// Speaking
```

2021-08-28 02:28 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	if(!holder.client && holder.speak_chance)
опять лесенку убрать можно.

2021-08-28 02:32 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	//Movement
Не является проблемой.

2021-08-28 02:32 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +		if(isturf(holder.loc) && !holder.resting && !holder.buckled)		//This is so it only moves if it's not inside a closet, gentics machine, etc.
Не является проблемой.

2021-08-28 02:32 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	//Speaking
Не является проблемой.

2021-08-28 02:33 UTC, kcalbCube commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	//Movement
ты меня за это наяривал бывало

2021-08-28 02:33 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +				if(!(holder.stop_automated_movement_when_pulled && holder.pulledby)) //Some animals don't move when pulled
Не является проблемой.

2021-08-28 02:34 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	if(!holder.client && !holder.stop_automated_movement && holder.wander && !holder.anchored)
При повышение количество символов в одной строки увеличивается шанс на появления ошибок.
Не является проблемой.

2021-08-28 02:34 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	if(!holder.client && holder.speak_chance)
При повышение количество символов в одной строки увеличивается шанс на появления ошибок.
Не является проблемой.

2021-08-28 02:35 UTC, Doster-d commented on code/modules/mob/living/simple_animal/mob_ai.dm
> +	//Movement
Времена изменились.

2021-08-28 13:46 UTC, Epicus7 commented
> > Так, ну ок. А чо с тестами то?
> > ![image](https://user-images.githubusercontent.com/5204667/131107124-1528b7ce-77ba-42f7-9939-e53d33c30e76.png)
> > Ты проверил в итоге все три команды на локалке?
> 
> Я проверил, что переключение команды работают, я проверил команду следования, я проверил команду стояния, далее я вывел питомца из безопасной зоны и он перешел в состояние брождения, механизм перехода в состояние брождения в этом случае идентичный через переключение комманд. Я не очень четко проверил поведение мобов, я был рядом с Ианом по тому, что я видел, он выполнял свои функции как раньше.

Ок

2021-08-28 18:14 UTC, Doster-d commented
> и нужно побольше команд.

Не нужны, я же не ты, я выполняю все по иссую :-)

2021-09-01 19:01 UTC, TermService approved these changes

2021-09-03 18:23 UTC, merged