fix(changeling): fixes changeling stasis and minor fixes
ChaoticOnyx/OnyxBay pull request #6262
Opened 2021-07-31 11:55 UTC by Oubifx

Генокрад не улетает в госты если он не умер полностью. Во время стазиса больше недоступен ,g чат.
Стазис не тратит химикатов и при возвращении в тело обнуляет существующий запас.
Умение move biostructure больше не отображает пункт части тела в которой биоструктура уже находится.
Еволюшен меню теперь нельзя открыть находясь в слабой форме (часть/краб) из-за ненадобности и багов, которые могут возникнуть после его открытия и покупки умения.

close #6182
close #5783
fix #6177  

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
tweak: Генокрад больше не попадает в гост чат пока не умрет полностью.
tweak: Умение генокрада Regenerative Stasis больше не тратит химикаты, обнуляя существующий запас по завершению.
tweak: Во время Regenerative Stasis больше не доступен ,g чат.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-07-31 12:00 UTC, Zert0X requested changes

2021-07-31 12:04 UTC, Zert0X commented
Также я не уверен по поводу решил ли ты проблему #6182. Т.к. основная проблема бага, слышимость гост чата + возможность гостаться. Насколько я увидел в коде ты просто запретил гостаться.

2021-07-31 12:04 UTC, igorsaux requested changes

2021-07-31 12:04 UTC, igorsaux commented on code/datums/movement/mob.dm
> +	return 1
```suggestion
	return mind.changeling?.true_dead || TRUE
```

2021-07-31 12:10 UTC, Oubifx commented
> Также я не уверен по поводу решил ли ты проблему #6182. Т.к. основная проблема бага, слышимость гост чата + возможность гостаться. Насколько я увидел в коде ты просто запретил гостаться.

Проверял заходя на сервер со второго аккаунта. Запрет на разговор в файле say.dm

2021-07-31 13:11 UTC, MrMagick2104 commented
> Во время стазиса больше недоступен ,g чат.

Зачем это нужно?
Нигде в связанных иссуях про это не написано, судя по всему. Ломает многие возможности генок для коммуникации.

2021-07-31 13:37 UTC, TobyThorne commented
> Во время стазиса больше недоступен ,g чат.

Нахрена?

2021-07-31 13:39 UTC, TobyThorne commented on code/datums/movement/mob.dm
> +		return
Не надо пихать лишние проки в вещи, которые вызываются десятки раз в секунду.

2021-07-31 13:52 UTC, Oubifx commented
> Зачем это нужно?
> Нигде в связанных иссуях про это не написано, судя по всему. Ломает многие возможности генок для коммуникации.

> Нахрена?

![image](https://user-images.githubusercontent.com/24242919/127741815-4f51d659-0838-42e1-b79b-a5031a92b3ab.png)
![image](https://user-images.githubusercontent.com/24242919/127741881-515b60b3-782d-467a-b324-a03845e49ee8.png)

В иссуях этого и нет. Сделано это из соображения здравой логики и баланса, что бы исключить случаи `,g Помогите нам, нас ебут в морге`. На то умение и называется **регенеративный стазис**. **Регенеративный** - значит восстановление, **стазис** - значит пауза жизненных процессов.

2021-07-31 15:56 UTC, kcalbCube commented
> Во время стазиса больше недоступен ,g чат.
нахуя? этим пользуется 100% генокрадов и все это приняли как должную часть геймплея генадия.

2021-07-31 16:01 UTC, kcalbCube commented
> > Зачем это нужно?
> > Нигде в связанных иссуях про это не написано, судя по всему. Ломает многие возможности генок для коммуникации.
> 
> > Нахрена?
> 
> ![image](https://user-images.githubusercontent.com/24242919/127741815-4f51d659-0838-42e1-b79b-a5031a92b3ab.png)
> ![image](https://user-images.githubusercontent.com/24242919/127741881-515b60b3-782d-467a-b324-a03845e49ee8.png)
> 
> В иссуях этого и нет. Сделано это из соображения здравой логики и баланса, что бы исключить случаи `,g Помогите нам, нас ебут в морге`. На то умение и называется **регенеративный стазис**. **Регенеративный** - значит восстановление, **стазис** - значит пауза жизненных процессов.

генокрад всё ещё способен следить за окружающим миром,
и раз он регенерирует, катаболиизм, анаболизм, метаболизм и другие процессы меж генкоорганом и человеком активно работают, а значит на отправку сигналов в воздух энергии должно быть достаточно, ибо эта функция невероятно повышает вероятность генокрада выжить, что благодаря естественному отбору закрепилось в виде.

2021-07-31 16:10 UTC, kcalbCube requested changes

2021-07-31 16:10 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +		var/list/available_limbs = organs.Copy() - H.get_organ(BIO.parent_organ)
зачем тут list::Copy()? это не -=

2021-07-31 16:10 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/stasis.dm
> +		else if(changeling_power(0, 1, 100, DEAD, TRUE))
звёзды говорят что if не нужен

2021-07-31 16:10 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/stasis.dm
> +	var/datum/changeling/changeling = changeling_power(0, 1, 100, DEAD)
оно надо?

2021-07-31 16:10 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/stasis.dm
> +		internal_organs_by_name[BP_BRAIN].die()
можно на lazy инструкции заменить

2021-07-31 16:10 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/stasis.dm
> +	set_fullscreen(TRUE, "blurry", /obj/screen/fullscreen/blurry)
не увидел этого в чейнджлоге
и вообще лучше тогда наверное шум накладывать, а не куски пнг на пол экрана

2021-07-31 16:10 UTC, kcalbCube commented on code/modules/mob/living/say.dm
>  			return say_dead(message)
```suggestion
			return say_dead(message) && can_ghostize_human()
```

2021-07-31 16:10 UTC, kcalbCube commented on code/datums/movement/mob.dm
> +	return mind.changeling?.true_dead || TRUE
точно ||?
локалку тестил?

2021-07-31 16:41 UTC, Oubifx commented
> генокрад всё ещё способен следить за окружающим миром,
и раз он регенерирует, катаболиизм, анаболизм, метаболизм и другие процессы меж генкоорганом и человеком активно работают, а значит на отправку сигналов в воздух энергии должно быть достаточно, ибо эта функция невероятно повышает вероятность генокрада выжить, что благодаря естественному отбору закрепилось в виде.

Способность следить за окружающим миром вокруг себя - игровая условность, точно такая же как и видеть одну клетку не имея глаз. Из описания умения можно понять что стазис это ослабление до состояние подобному смерти лишь для того что бы потом жить, по этому не вижу причин возвращать ,g
> "We become **weakened to a death-like state**, where we will rise again from death."

Хотя о чём это я.. **Генокрад и так не мог писать в ,g чат на момент нахождения в стазисе** (ибо кидает в госты). Поправил описание ПР-а.

2021-07-31 16:52 UTC, Oubifx commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +		var/list/available_limbs = organs.Copy() - H.get_organ(BIO.parent_organ)
В изначальном варианте просто копировался лист с органами. А я лишь удаляю нужный мне орган из листа который пойдет в переменную. Не понимаю к чему тут -=

2021-07-31 17:01 UTC, Oubifx commented on code/game/gamemodes/changeling/powers/stasis.dm
> +	var/datum/changeling/changeling = changeling_power(0, 1, 100, DEAD)
хз, вроде не рефакторинг

2021-07-31 17:01 UTC, Oubifx commented on code/game/gamemodes/changeling/powers/stasis.dm
> +		internal_organs_by_name[BP_BRAIN].die()
С макросами lazy не знаком, по этому написал как знаю, читается во всяком случае отлично

2021-07-31 17:03 UTC, Oubifx commented on code/game/gamemodes/changeling/powers/stasis.dm
> +	set_fullscreen(TRUE, "blurry", /obj/screen/fullscreen/blurry)
Решил такую мелочь не писать. А куски пинг на пол экрана точно такие же как и в другом любом стазисе: слипер, стазисбаг, крио. По этому выглядит вполне логично, по моему мнению

2021-07-31 17:13 UTC, Oubifx commented on code/datums/movement/mob.dm
> +	return mind.changeling?.true_dead || TRUE
Точно. Работает

2021-07-31 17:19 UTC, MrMagick2104 commented
> Сделано это из соображения здравой логики и баланса, что бы исключить случаи ,g Помогите нам, нас ебут в морге. 

Абсолютно нормальная ситуация, имхо. Баланс она никому ломать не будет. Зачем это исключать?
Плюс, с ней хотя бы у генокрада будет возможность пообщаться во время стазиса, обсудить планы, поиграть в слова. Без неё тебе остаётся только пойти поиграть в пасьянс.

> Регенеративный - значит восстановление, стазис - значит пауза жизненных процессов.

Стазис не потому что пауза жизненных процессов, а потому что с виду генокрад не проявляет естественных признаков жизни человека. При этом, он регенерирует в это время, т.е. жизнь не останавливается в нём.

<hr>

> что бы исключить случаи ,g Помогите нам, нас ебут в морге. 

А генокрад не может просто сначала написать это, а потом прожать стазис?

2021-07-31 17:28 UTC, Oubifx commented on code/modules/mob/living/say.dm
>  			return say_dead(message)
Это так не работает, проверил

2021-07-31 17:31 UTC, Oubifx commented on code/datums/movement/mob.dm
> +	return mind.changeling?.true_dead || TRUE
Верну как было, думал igorsaux фигни не посоветует

2021-08-01 01:24 UTC, kcalbCube requested changes
костыли, лень, ламерство, фичажорство

2021-08-01 01:24 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/stasis.dm
> +	var/datum/changeling/changeling = changeling_power(0, 1, 100, DEAD)
какой рефакторинг, оно не требует changeling сил, а значит можно без этого прока обойтись

2021-08-01 01:24 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/stasis.dm
> +	set_fullscreen(TRUE, "blurry", /obj/screen/fullscreen/blurry)
какую мелочь
какой стазис, это совершенно другой организм, совершенно другой процесс стазиса

2021-08-01 01:24 UTC, kcalbCube commented on code/modules/mob/living/say.dm
>  			return say_dead(message)
что ты там проверял, базовую логику на базовую логику?

2021-08-01 01:24 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +		var/list/available_limbs = organs.Copy() - H.get_organ(BIO.parent_organ)
я тебя и спрашиваю, зачем здесь list::Copy()?
ты хоть смотришь что копипастишь?

2021-08-01 01:24 UTC, kcalbCube commented on code/datums/movement/mob.dm
> +	return mind.changeling?.true_dead || TRUE
он тебе пример показал как надо, а ты просто скопипастил

2021-08-01 10:28 UTC, Oubifx commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +		var/list/available_limbs = organs.Copy() - H.get_organ(BIO.parent_organ)
Ну так ты нормально объясни почему это не правильно, а не экзамен устраивай.

2021-08-01 10:46 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +		var/list/available_limbs = organs.Copy() - H.get_organ(BIO.parent_organ)
думай сам.

2021-08-03 19:23 UTC, Oubifx commented
Поправил дохуя чего, тестил всё с двумя клиентами на локалке. Есть вопросы - задавайте. Есть предложения по упрощению кода без потери читаемости - предлагайте.

2021-08-15 07:41 UTC, kcalbCube reviewed
улитка (кродеться)

2021-08-15 07:41 UTC, kcalbCube commented on code/game/gamemodes/changeling/powers/move_biostructure.dm
> +		var/list/available_limbs = organs.Copy() - H.get_organ(BIO.parent_organ)
так и не починил.
если че, list - list возвращает другой list, .Copy() это оверхед, он и так используется внутри минус опа.

2021-08-15 07:41 UTC, kcalbCube commented on code/modules/mob/hear_say.dm
> +	if(sleeping || stat == UNCONSCIOUS || (status_flags & FAKEDEATH && stat == DEAD)) // status_flags & FAKEDEATH
комментарий не нужен
и разве stat == DEAD нужен?

2021-08-15 07:41 UTC, kcalbCube commented on code/modules/mob/living/life.dm
> +	if(client)
чую приколы появятся.

2021-08-15 07:41 UTC, kcalbCube commented on code/modules/mob/living/say.dm
>  			return say_dead(message)
не решено

2021-08-15 10:39 UTC, Oubifx commented on code/modules/mob/living/life.dm
> +	if(client)
> чую приколы появятся.

Ну там по сути уже есть прикол. Нужно в госты выйти что бы быть полноценным гостом. А так пока ты в теле, то будешь видеть как из тела. Вроде ничему не мешает (по типу возвращение в мир через нить), по этому вполне можно считать фичей, да :)

2021-08-15 11:12 UTC, kcalbCube commented
в этот раз я согласен с тоби

2021-08-15 11:14 UTC, Oubifx commented
> в этот раз я согласен с тоби

в плане?

2021-08-15 11:15 UTC, kcalbCube commented
> Высказались против: toor

2021-08-15 11:17 UTC, Oubifx commented
> > Высказались против: toor

Конструктивно, одобряю. Раньше ведь было лучше (нет)

2021-09-06 06:45 UTC, O0oMaximo0O commented on code/modules/mob/living/say.dm
>  			return say_dead(message)
Тут в обратном порядке надо же О_о.
 `can_ghostize_human() && return say_dead(message)`
 Если уж менять.

2021-09-06 06:54 UTC, O0oMaximo0O reviewed
Посмотрел. Не очень разбираюсь в генокраде,  но вроде ничего страшного не вижу.
По файлу life.dm не понял, что там меняет `if(client)`,  а так вроде всё логично смотрится.

2021-10-14 01:30 UTC, TobyThorne commented
ПР полностью уконфликтован, висит три ченжреквеста, автор помянут. Всегда можно переоткрыть, если оживёт.

2021-10-14 01:30 UTC, closed without merging