Сделать бензопилу
ChaoticOnyx/OnyxBay pull request #6287
Opened 2021-08-04 09:51 UTC by BWJes

Добавлена бензопила. 
![Безымянный](https://user-images.githubusercontent.com/86688350/126199170-070f82fa-c818-4fe3-a13c-12c6900bfd14.png)

Крафт: circular saw + кабель (3шт) + конденсатор (adv.capacitor) + плассталь (5шт) + сварка (5ед. топлива)
Нужна помощь с добавление возможности спила дерева (flora.dm)

Этот Pull Request затрагивает issue:
https://github.com/ChaoticOnyx/OnyxBay/issues/2394

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена бензопила
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-04 09:54 UTC, BWJes commented
Перезалив. Я не особо понимаю, почему я не могу слить через свою ветку в этот же ПР обновку

2021-08-04 10:22 UTC, MrMagick2104 commented
> конденсатор (adv.capacitor)

Если у человека есть конденсатор лучше, чем adv, но нет adv, то он не сможет сделать бензопилу. Так и задумано? Это может быть довольно неудобно.

2021-08-04 13:08 UTC, bosslobster commented
Хорошо бы сделать пилу улучшенной альтернативой топорика садовнику - например кликаешь пилой по растению и оно спиливается через секунд 5. Также это сделает бензопилу контрой разбуянившихся лоз.

2021-08-06 18:39 UTC, MaxFreemen commented
Автор пересоздал ПР, закрываю [прошлый](https://github.com/ChaoticOnyx/OnyxBay/pull/6133).

2021-08-11 01:15 UTC, TobyThorne commented on code/game/objects/items/weapons/material/twohanded.dm
> +	attack_verb = list("smashed", "beaten", "slammed", "smacked", "struck", "battered", "bonked")
Какие-то **_не совсем_** подходящие бензопиле глаголы. Надо хотя бы у циркулярки скопипастить.

2021-08-11 01:16 UTC, TobyThorne commented on code/game/objects/items/weapons/material/twohanded.dm
> +	attack_verb = list("smashed", "beaten", "slammed", "smacked", "struck", "battered", "bonked")
А, впрочем, это выключенная пила. Пойдёт.

2021-08-11 01:17 UTC, TobyThorne commented on code/game/objects/items/weapons/material/twohanded.dm
> +	mod_reach_u = 1.
```suggestion
	mod_reach_u = 1.0
```

Как это вообще компилируется?

2021-08-15 17:18 UTC, kcalbCube commented on code/game/objects/items/weapons/material/twohanded.dm
> +	mod_reach_u = 1.
бионд перешёл на темную сторону

2021-08-19 12:16 UTC, BWJes commented on code/game/objects/items/weapons/material/twohanded.dm
> -	mod_reach_u = 1.0
Сначала говорите, что нет смысла в дробях при нуле после, потом спрашивают, зачем удаляют. Определитесь

2021-08-25 07:18 UTC, kcalbSphere commented on code/game/objects/items/weapons/material/twohanded.dm
> -	mod_reach_u = 1.0
удалять не надо

2021-09-01 18:58 UTC, TermService commented
конфликты поправить, дробные значения вернуть и мерж

2021-09-09 01:12 UTC, kcalbCube requested changes
ещё и автор умер

2021-09-09 01:12 UTC, kcalbCube commented on code/game/objects/items/weapons/material/improvised_components.dm
> +var/step = 1
ебучий случай
```suggestion
/obj/item/weapon/circular_saw/var/step = 1
```

2021-09-09 01:12 UTC, kcalbCube commented on code/game/objects/items/weapons/material/improvised_components.dm
> +					return
```suggestion
```

2021-09-09 01:12 UTC, kcalbCube commented on code/game/objects/structures/flora.dm
> +	if(istype(W, /obj/item/weapon/material/twohanded/chainsaw))
```suggestion
	if(!istype(W, /obj/item/weapon/material/twohanded/chainsaw))
		return
```

2021-09-09 01:12 UTC, kcalbCube commented on code/game/objects/structures/flora.dm
> +		if (checker.active)
```suggestion
		if (!checker.active)
			return
```

2021-09-09 01:12 UTC, kcalbCube commented on code/game/objects/structures/flora.dm
> +		if (checker.active)
```suggestion
		if(checker.active)
```

2021-09-09 01:12 UTC, kcalbCube commented on code/game/objects/items/weapons/material/twohanded.dm
> +			force_wielded = FALSE
может 0?

2021-09-09 01:15 UTC, kcalbCube commented
рекомендую закрыть данный ПР

2021-09-15 21:26 UTC, MaxTheAstronaut commented
Проект начинает пахнуть, как и автор.

2021-10-04 00:16 UTC, HonkyDonky commented
Автор решил отдохнуть в гробу. Думаю, ему следует взять с собой свой ПР.
Закрываю.

2021-10-04 00:16 UTC, closed without merging