Исправление бумаги с наклеенным скотчем
ChaoticOnyx/OnyxBay pull request #6294
Opened 2021-08-06 00:59 UTC by O0oMaximo0O

Ранее бумага со скотчем была отдельным объектом-контейнером для самого листа бумаги.
Он перенаправлял экзамайн на хранимый лист, больше с ним ничего делать было нельзя, только приклеивать к чему-либо.
Добавил переменную "taped" для состояния "есть/нет" скотча.
Переместил логику из `/obj/item/weapon/ducttape` в бумагу, переписал и добавил где нужно update_icon().
`/obj/item/weapon/ducttape` удалил, как и связанную с ним функцию в `/obj/item/weapon/tape_roll`. Кроме как для бумаги они были не нужны.

close #6273 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь с бумагой с наклеенным на неё скотчем можно делать то же, что и с просто бумагой.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-01 19:33 UTC, TermService requested changes
В целом неплохо, ознакомься с https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#%D0%B4%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%BF%D0%BE-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8E-%D0%BA%D0%BE%D0%B4%D0%B0 

готовое решение указанных проблем не представлено чтобы ты не потерял интерес, будут вопросы куда писать знаешь :)

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/carbonpaper.dm
> +	if(!findtext(icon_state,"scrap"))
это что за дела такие, ну не надо по иконстейту ифы писать, кто посоветовал это признавайся...

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		if(length(info)>length("<!--paper_field_end-->"))
описано выше

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		name = copytext(name, 1, length(name)-7)
к чему усложнение?

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		var/obj/item/weapon/paper_bundle/B = new(src.loc)
```suggestion
		var/obj/item/weapon/paper_bundle/B = new(loc)
```

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +				to_chat(user, "<span class='notice'>Take off the carbon copy first.</span>")
```suggestion
				to_chat(user, SPAN_NOTICE("Take off the carbon copy first."))
```

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		src.forceMove(B)
```suggestion
		forceMove(B)
```

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		if (name != "paper")
была проверка по иконке теперь по имени - не годится

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		else if (P.name != "paper" && P.name != "photo")
описано выше

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		to_chat(user, "<span class='notice'>You clip the [P.name] to [(src.name == "paper") ? "the paper" : src.name].</span>")
```suggestion
		to_chat(user, SPAN_NOTICE("You clip the [P.name] to [(src.name == "paper") ? "the paper" : src.name]."))
```

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		if(icon_state == "scrap")
описано выше

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +			to_chat(usr, "<span class='warning'>\The [src] is too crumpled to write on.</span>")
```suggestion
			to_chat(usr, SPAN_WARNING("\The [src] is too crumpled to write on."))
```

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		if((!in_range(src, usr) && loc != user && !( istype(loc, /obj/item/weapon/clipboard) ) && loc.loc != user && user.get_active_hand() != P))
использование usr в данном случае незаконно

2021-09-01 19:33 UTC, TermService commented on code/modules/paperwork/paper.dm
> +		to_chat(user, "<span class='notice'>You stamp the paper with your [P.name].</span>")
```suggestion
		to_chat(user, SPAN_NOTICE("You stamp the paper with your [P.name]."))
```

2021-09-01 22:14 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +	var/obj/item/weapon/paper/P = new src.type(loc)
Иначе при отрыве от carbon-бумаги листка остаётся не фиолетовая основа, а ещё один белый лист

2021-09-01 22:16 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		name = copytext(name, 1, length(name)-7)
Это удаление постфикса "(taped)" при отрыве скотча

2021-09-01 22:35 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +	if(!findtext(icon_state,"scrap"))
Никто, это проверка на скомканность бумаги. Можно добавить ещё переменную...

2021-09-01 22:39 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if (name != "paper")
Это тот код, что был. Как-то выбирается имя для стопки бумаги.

2021-09-01 22:39 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		else if (P.name != "paper" && P.name != "photo")
Это тот код, что был.

2021-09-01 22:40 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if(icon_state == "scrap")
А вот тут надо поменять будет.

2021-09-01 22:40 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if((!in_range(src, usr) && loc != user && !( istype(loc, /obj/item/weapon/clipboard) ) && loc.loc != user && user.get_active_hand() != P))
Это тот код, что был. Но я кажется понимаю, почему. Заменю.

2021-09-01 22:45 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +		if(length(info)>length("<!--paper_field_end-->"))
Проблема в том, что бумага может быть пуста, а может содержать это поле, но с точки зрения читателя всё равно будет пуста. И я не знаю, как это ещё обойти. До ПР-а просто иконка обновлялась только после дописывания текста. А сейчас я могу приклеить/отклеить скотч.
Собственно ранее была проверка на длину info, что != 0. Но она и была нерабочей.

Может надо лезть в функцию, которая эти field-ы делает. Но что-то страшно.

2021-09-04 06:49 UTC, kcalbCube requested changes
код полная хуйня, у меня нет сил это просматривать, каждая строчка это какая-то поебень. исправлять это будет невозможно, поэтому начни с начала.

2021-09-04 06:49 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	var/obj/item/weapon/paper/P = new src.type(loc)
а админка?

2021-09-04 07:42 UTC, O0oMaximo0O commented
Предлагаешь переписать всю бумагу? Я то только перенёс код из подтипа скотча, да в паре мест поправил. update_icon() переписал.

> а админка?
Не понял. Ты наверно имеешь в виду факс от админов, но я не понимаю, как это к этому коду относится.

2021-09-04 13:35 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +		if(length(info)>length("<!--paper_field_end-->"))
Нашёл способ, там всё просто)

2021-09-04 14:35 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +	if(!findtext(icon_state,"scrap"))
Исправлено, добавил переменную `crumpled`

2021-09-04 14:36 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +	var/obj/item/weapon/paper/P = new src.type(loc)
Исправлено

2021-09-04 14:36 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +	if(findtext(icon_state,"scrap"))
Исправлено

2021-09-04 14:36 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if(length(info)>length("<!--paper_field_end-->"))
Исправлено

2021-09-04 14:37 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if(icon_state == "scrap")
Исправлено

2021-09-06 00:30 UTC, kcalbCube commented
зачем было трогать спаны если они не мешали линту?

2021-09-06 06:01 UTC, O0oMaximo0O commented
Тебе не угодишь...
![изображение](https://user-images.githubusercontent.com/80180448/132167976-ca824edd-a2d3-4520-9ec1-300316fc8826.png)

2021-09-06 06:03 UTC, O0oMaximo0O commented
Не переделал - придирки.
Переделал - придирки.
И какому "линту" они не мешают?

2021-09-06 07:41 UTC, kcalbCube commented
спаны проблема в добавленном пром коде, а тут точечные замены спанов на укроспаны в далеких от мест с изменениями местах. это раздувает дифф.

2021-09-06 07:42 UTC, kcalbCube commented
а линт это вот это https://github.com/ChaoticOnyx/OnyxBay/pull/6294/checks?check_run_id=3513708702

2021-09-06 07:43 UTC, kcalbCube commented
> UPD:
> Добавил SPAN-ы во все затронутые файлы.
только что заметил, ты это самое в описание пра добавил. в любом случае не нужно.

2021-09-06 07:45 UTC, O0oMaximo0O commented
Описание ПР-а должно содержать вносимые изменения.

2021-09-06 07:59 UTC, kcalbCube reviewed
да вы чё

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			icon_state += "_words"
обычно мы делаем
```suggestion
			icon_state = "[icon_state]_words"
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		if(rigged && (Holiday == "April Fool's Day"))
```suggestion
		if(rigged && (Holiday == "April Fool's Day") && !spam_flag)
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +					spam_flag = FALSE
```suggestion
				spawn(20) spam_flag = FALSE
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	if(src != user.get_active_hand())//if anything took paper
```suggestion
	if(src != user.get_active_hand()) // If anything took paper
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	if(params)
```suggestion
	if(!params)
		return
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	var/clown = 0
впринцепе можно
```suggestion
	var/clown = user.mind && (user.mind.assigned_role == "Clown")
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		stamps += (stamps=="" ? "<HR>" : "<BR>") + "<i>This paper has been stamped with the [P.name].</i>"
вроде бы "" приравнен к FALSE 
и можно
```suggestion
		stamps += (!stamps ? "<HR>" : "<BR>") + "<i>This paper has been stamped with the [P.name].</i>"
```
но нужно проверить

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			ico = new
тут вероятно можно че-то захуячить типа ico = ico || new, но есть шанс что бионд не сумеет вывести тип для new

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		if(istype(P, /obj/item/weapon/stamp/clown))
```suggestion
		if(istype(P, /obj/item/weapon/stamp/clown) && !clown)
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/carbonpaper.dm
> +			icon_state = "paper_stack"
```suggestion
		icon_state = copied ? "cpaper" : "paper_stack"
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/carbonpaper.dm
> +		icon_state += "_taped"
```suggestion
		icon_state = "[icon_state]_taped"
```

2021-09-06 07:59 UTC, kcalbCube commented on code/modules/paperwork/adminpaper.dm
> +			to_chat(usr, SPAN("info", "There isn't enough space left on \the [src] to write anything."))
ты или укроспаны или макроспаны используй.

2021-09-06 07:59 UTC, kcalbCube commented
> Описание ПР-а должно содержать вносимые изменения.

изменения не нужные.

2021-09-06 08:04 UTC, kcalbCube requested changes
проблемы не решены

2021-09-06 08:05 UTC, O0oMaximo0O commented on code/modules/paperwork/adminpaper.dm
> +			to_chat(usr, SPAN("info", "There isn't enough space left on \the [src] to write anything."))
SPAN_INFO нет

2021-09-06 08:09 UTC, kcalbCube commented
ты укроспаны лишние будешь пурджить или че

2021-09-06 08:12 UTC, O0oMaximo0O commented
Нет. Буду теперь во всех своих ПР-ах переписывать на SPAN-ы. Если уж всё новое надо так, то стоит к единому стилю приводить код. Буду стараться.

2021-09-06 08:18 UTC, kcalbCube commented
ну ёксель моксель, я же сказал, я про вот это

> UPD:
Добавил SPAN-ы во все затронутые файлы.

2021-09-06 08:19 UTC, kcalbCube commented
спаны нужно заменять только в том коде который в дифе от апстрима, так мы потихоньку модернизируем код. но лишний раз диф раздувать изменением спанов - нафига

2021-09-06 08:27 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +			icon_state += "_words"
Ну, раз обычно - поменяю

2021-09-06 08:28 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if(rigged && (Holiday == "April Fool's Day"))
Ок, гуд

2021-09-06 08:29 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +					spam_flag = FALSE
Хм. Ну ок

2021-09-06 08:32 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +	if(params)
Ок

2021-09-06 08:34 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +	var/clown = 0
Хм, а перенесу-ка я это к месту использования переменной.

2021-09-06 08:36 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		stamps += (stamps=="" ? "<HR>" : "<BR>") + "<i>This paper has been stamped with the [P.name].</i>"
Оставлю как есть.

2021-09-06 08:36 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +			ico = new
Оставлю как есть

2021-09-06 08:38 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +		if(istype(P, /obj/item/weapon/stamp/clown))
Перенесу задание переменной `clown` внутрь if-а, так что будет неактуально.

2021-09-06 08:38 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +		icon_state += "_taped"
Сделаю

2021-09-06 09:14 UTC, kcalbCube requested changes

2021-09-06 09:14 UTC, kcalbCube commented on code/game/objects/items/weapons/tape.dm
> +	tape_speed = 5
\n где

2021-09-06 09:14 UTC, kcalbCube commented on code/modules/paperwork/carbonpaper.dm
> +			icon_state += "_words"
```suggestion
			icon_state = "[icon_state]_words"
```
 и так надо везде

2021-09-06 09:14 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			to_chat(user, SPAN_NOTICE("You cannot reach that from here."))// can only place stuck papers in cardinal directions, to
```suggestion
			to_chat(user, SPAN_NOTICE("You cannot reach that from here.")) // Can only place stuck papers in cardinal directions, to
```

2021-09-06 09:14 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			return											// reduce papers around corners issue.
```suggestion
			return											// Reduce papers around corners issue.
```

2021-09-06 09:14 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			return											// reduce papers around corners issue.
и вообще не ровно
и вообще этот комментарий не нужен, всё и так понятно

2021-09-06 09:14 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	return
```suggestion
```

2021-09-06 09:16 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +			icon_state += "_words"
Уже

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/carbonpaper.dm
> +		to_chat(usr, SPAN_NOTICE("There are no more carbon copies attached to this paper!"))
давай инвертируем

```
if(copied)
		to_chat(usr, SPAN_NOTICE("There are no more carbon copies attached to this paper!"))
		return
...
```

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
>  		icon_state = "paper"
```suggestion
	icon_state = crumpled ? "scrap" : "paper"
```
да ты

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		if ( istype(RP) && RP.mode == 2 )
```suggestion
		if (istype(RP) && RP.mode == 2)
```

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		B.pages.Add(P)
```suggestion
		B.pages += src
		B.pages += P
```

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	return ..()
```suggestion
	. = ..()
	anchored = FALSE // Unattach it from whereever it's on, if anything.
```

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			return											// Reduce papers around corners issue.
всё ещё криво
и всё ещё комментарий не нужен.

2021-09-06 11:48 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			ico = new
скучный ты неинтересно с тобой(

2021-09-06 15:40 UTC, O0oMaximo0O commented on code/modules/paperwork/carbonpaper.dm
> +		to_chat(usr, SPAN_NOTICE("There are no more carbon copies attached to this paper!"))
Давай).

2021-09-06 15:40 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
>  		icon_state = "paper"
Ок.

2021-09-06 15:41 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +	return ..()
А вот это, я считаю, читается хуже.

2021-09-06 15:42 UTC, O0oMaximo0O commented on code/modules/paperwork/paper.dm
> +			return											// Reduce papers around corners issue.
Ок, ща поправлю.

2021-09-06 15:49 UTC, O0oMaximo0O commented
Что-то я боюсь уже, глядя на эту кучу коммитов. Может скопировать файлы на локальной ветке, откатить её на начало, заменить файлы и перезалить ПР одним коммитом?

2021-09-06 15:50 UTC, O0oMaximo0O commented
Можно так без пересоздания ПР-а сделать?

2021-09-06 15:58 UTC, O0oMaximo0O commented
Или двумя коммитами: изменение логики и рефакторинг.

2021-09-07 02:23 UTC, kcalbCube commented
> Что-то я боюсь уже, глядя на эту кучу коммитов. Может скопировать файлы на локальной ветке, откатить её на начало, заменить файлы и перезалить ПР одним коммитом?

не нужно, при мерже сосквашат

2021-09-07 02:33 UTC, kcalbCube requested changes

2021-09-07 02:33 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +	return ..()
это стандартный темплейт, сначала продвигнуть всю иерархию, а потом уже хуячить.
если для тебя . = ..() читается хуже return ..() то тебе ещё рано на DM кодить

2021-09-07 02:33 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			return                                                         // Reduce papers around corners issue.
теперь ровно
осталось дело за малым: удалить этот ненужный коммент

2021-09-07 02:33 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		if((!in_range(src, user) && loc != user && !( istype(loc, /obj/item/weapon/clipboard) ) && loc.loc != user && user.get_active_hand() != P))
лучше бы суда коммент задвинул, чем на 255-256

2021-09-07 02:33 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +			B.SetName(P.name)
проверка ни во что не годится

2021-09-07 02:33 UTC, kcalbCube commented on code/modules/paperwork/paper.dm
> +		to_chat(user, SPAN_NOTICE("You clip the [P.name] to [(src.name == "paper") ? "the paper" : src.name]."))
это лучше будет
```suggestion
		to_chat(user, SPAN_NOTICE("You clip the [P.name] to \the [src.name]."))
```

2021-09-10 19:02 UTC, TermService approved these changes

2021-09-24 11:22 UTC, TermService approved these changes

2021-09-24 11:34 UTC, kreeperHLC approved these changes

2021-09-24 11:47 UTC, merged