tweak(vampire): Changed memory loss message to alert
ChaoticOnyx/OnyxBay pull request #6303
Opened 2021-08-08 08:28 UTC by RUNAS-Jacob

В связи с жалобами Типса о том, что игроки слишком легко упускают из виду сообщение о потери памяти после того, как вампир высосал у них кровь, я слегка переиначил процесс: теперь это не сообщение в чате, а отдельное всплывающее окно как у повреждений мозга. Надеюсь, это будет значительно заметнее.

close #6290

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Сообщение о потере памяти через укус вампира стало заметнее.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-08 08:33 UTC, Doster-d requested changes
Commented code not allowed

2021-08-08 08:33 UTC, Doster-d commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			// to_chat(T, SPAN("warning", FONT_LARGE("You remember nothing about the cause of blacked out. Instead, you simply remember having a pleasant encounter with [src.name]")))
```suggestion
```

2021-08-08 08:33 UTC, Doster-d commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			// to_chat(T, SPAN("warning", FONT_LARGE("You remember everything that happened. Remember how blood was sucked from your neck. It gave you pleasure, like a pleasant dream. You feel great. How you
```suggestion
```

2021-08-08 08:46 UTC, RUNAS-Jacob commented
Изменено по заявкам трудящихся.

2021-08-08 09:10 UTC, Doster-d approved these changes
Можно в одну строчку записать, но ладно и так сойдет.

2021-08-08 09:22 UTC, Shootnik01 commented
Теперь бы тоже самое лицехватам

2021-08-08 09:26 UTC, No-Tips commented
Вот такое я одобряю.

2021-08-10 18:08 UTC, Zert0X approved these changes

2021-08-13 14:20 UTC, kreeperHLC approved these changes

2021-08-13 14:22 UTC, merged