Feat emote list
ChaoticOnyx/OnyxBay pull request #6304
Opened 2021-08-08 16:15 UTC by Oubifx

Базовые эмоции оставил в объекте хумана, а остальные распихал по species. Это всё для более удобного редактирования эмоций конкретных существ.
Убрал глупую эмоцию "машет крыльями", ибо хуман не попугай.
Добавил простой кулдаун на использование эмоций, сейчас он одна секунда.
Ну и добавил вкладку эмоутов для людей, скреллов, таяр, унатхов и остальных обезьян + роботы.
В идеале еще отрубить использование эмоций через звёздочку, ибо таким образом можно юзать всякое тех. говно которе используется только в определённых участках кода, по типу deathgasp. Но этого не просили, по этому не убирал.

close #6288

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
rscadd: Добавлена вкладка с эмоциями.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-08 17:56 UTC, NefrNerf commented
Отрубать через звездочку, наверное не нужно, а deathgasp никому не мешает, вдруг человек свою смерть инсценировать будет и все в таком стиле.

2021-08-08 18:02 UTC, NefrNerf commented
И еще, до твоего обновления животные могли эмоуты использовать? И как после ситуация?

2021-08-08 18:12 UTC, Oubifx commented
> Отрубать через звездочку, наверное не нужно, а deathgasp никому не мешает, вдруг человек свою смерть инсценировать будет и все в таком стиле.

На примере `*vomit` ты можешь просто блевануть, без всяких предупреждающих сообщений. Чисто по своему желанию вырвать просто физически невозможно. По этому этот эмоут при использовании с верба вызывает сообщение по типу "засовывает два пальца в рот". 
`*deathgasp` вовсе вызывает рвоту аналогично `*vomit`, если персонаж в сознании. Но исходя из кода - нужен он совсем для другого.
![image](https://user-images.githubusercontent.com/24242919/128641337-131ab065-1ff4-4796-9a62-8402d5fa1ba9.png)

Тут речь про то что в доступе **для ручного использования** существуют эмоуты, которые не должны вовсе быть доступны игроку изначально, ибо они существуют лишь для того что-бы в определенный момент вызвать их из другого места.


> И еще, до твоего обновления животные могли эмоуты использовать? И как после ситуация?
Про это ничего не знаю, трогал только хуманов.

2021-08-08 18:20 UTC, NefrNerf commented
Ну да, тут солгасен, если человек чисто физически не может сделать что-то, то этот эмоут нужно переносить в другое место, а что по мобам, по типу мышей и корги, они могут юзать эмоуты?

2021-08-08 18:21 UTC, kreeperHLC commented
Я Дедгасп ещё на Вайте 2015 использовал. Это прикольная фича, которая специально была сделана так, чтобы полностью быть механической.

2021-08-08 18:23 UTC, Oubifx commented
> Я Дедгасп ещё на Вайте 2015 использовал. Это прикольная фича, которая специально была сделана так, чтобы полностью быть механической.

Распиши подробнее как оно работало и работает. Возможно получится потом с этого сделать полноценный верб с прикрученными плюхами

2021-08-08 18:24 UTC, kreeperHLC commented
Работает точно также как и тогда в 2015

2021-08-09 00:29 UTC, igorsaux requested changes

2021-08-09 00:29 UTC, igorsaux commented on code/modules/emotes/definitions/_species.dm
> +	) + GLOB.default_humanoid_emotes
Лучше всегда использовать |

> If A and B are lists, the result is a list containing items that are in either list. list(1,2) | list(2,3) is equivalent to list(1,2,3). The items from A come first in the result, followed by any extra items from B.

2021-08-09 00:29 UTC, igorsaux commented on code/modules/mob/mob_defines.dm
> +	var/emote_cd = FALSE
И тут нейминг поплыл

2021-08-09 00:29 UTC, igorsaux commented on code/modules/emotes/definitions/_species.dm
> +	inherent_verbs += list(
А тут соответственно можно |=

2021-08-09 00:29 UTC, igorsaux commented on code/modules/emotes/emote_mob.dm
> +#define EMOTE_COOLDOWN 10
Если оно не используется вне файла - в конце лучше добавить #undef

2021-08-09 00:29 UTC, igorsaux commented on code/modules/emotes/definitions/_species.dm
> +GLOBAL_LIST_INIT(default_humanoid_emotes_proc, list(
Вот это говно в виде отдельных проков хорошо бы в /decl/emote перенести

2021-08-09 00:29 UTC, igorsaux commented on code/modules/emotes/emote_mob.dm
> +/mob/proc/handle_emote_CD()
Compact Disk? Почему вообще арокним используется вместо нормального написания....

2021-08-09 00:29 UTC, igorsaux commented on code/modules/emotes/emotes_verb.dm
> +		var/target = input("Choose a target for applying emotion", "", null) as null|anything in avalibe_target
```suggestion
		var/target = input("Choose a target for applying emotion", "", null) as null | anything in avalibe_target
```

2021-08-09 09:30 UTC, Oubifx commented on code/modules/emotes/definitions/_species.dm
> +	) + GLOB.default_humanoid_emotes
Поправил

2021-08-09 09:30 UTC, Oubifx commented on code/modules/mob/mob_defines.dm
> +	var/emote_cd = FALSE
Поправил

2021-08-09 09:31 UTC, Oubifx commented on code/modules/emotes/definitions/_species.dm
> +	inherent_verbs += list(
Я пробовал с |=, но в этом случае почему-то не появляется вкладка с вербами, хоть и в переменные содержат нужный лист. Оставил +=

2021-08-09 09:32 UTC, Oubifx commented on code/modules/emotes/emote_mob.dm
> +#define EMOTE_COOLDOWN 10
Добавил после выполнения процедуры в которой нужен этот дефайн

2021-08-09 09:32 UTC, Oubifx commented on code/modules/emotes/emote_mob.dm
> +/mob/proc/handle_emote_CD()
Поправил

2021-08-10 10:10 UTC, Oubifx commented on code/modules/emotes/definitions/_species.dm
> +GLOBAL_LIST_INIT(default_humanoid_emotes_proc, list(
Я старался, я пытался, но в итоге заебался. В целом мой вариант допустим тоже как и предложенный тобою.

2021-08-11 01:05 UTC, TobyThorne commented on code/modules/emotes/definitions/visible.dm
> -	emote_message_3p = "USER stares."
Куда выпилил?

2021-08-11 01:07 UTC, TobyThorne commented on code/modules/emotes/emote_mob.dm
> +#define EMOTE_COOLDOWN 10
Кулдаун нужен для защиты от случайного/неслучайного спама, но не такой огромный. Где-то 0.3-0.5 секунд - нормально.

2021-08-11 01:09 UTC, TobyThorne commented on code/modules/emotes/definitions/visible.dm
> -
Зачем выпилил? Как теперь исполнять танец маленьких утят?

2021-08-11 01:11 UTC, MaxFreemen commented on code/modules/emotes/definitions/visible.dm
> -
> Зачем выпилил? Как теперь исполнять танец маленьких утят?

Тут крылья как бы не крылья, а руки?

2021-08-11 08:35 UTC, Oubifx commented on code/modules/emotes/definitions/visible.dm
> -
Через /me хай танцуют

2021-08-11 08:36 UTC, Oubifx commented on code/modules/emotes/definitions/visible.dm
> -	emote_message_3p = "USER stares."
Это всё синонимы look и по этому объективно они не нужны

2021-08-11 10:21 UTC, MrMagick2104 commented on code/modules/emotes/definitions/visible.dm
> -	emote_message_3p = "USER stares."
Таки нет, лол.
Они имеют довольно разные значения.
Лук - просто смотреть.
Глейр - взглянуть.
Стейр - пялиться.
По большей части, лук не передаёт того, что передаёт стейр.

2021-08-11 23:28 UTC, igorsaux requested changes

2021-08-11 23:28 UTC, igorsaux commented on code/modules/emotes/emote_mob.dm
> +		if(handle_emote_cooldown())
У нас теперь есть THROTTLE, используй его вместо этой еботни

2021-08-14 12:54 UTC, igorsaux approved these changes

2021-08-14 13:11 UTC, HonkyDonky commented on code/modules/emotes/emotes_verb.dm
> +		var/target = input("Choose a target for applying emotion", "", null) as null | anything in avalibe_target
А это случаем нельзя будет абузить против антагонистов в инвизе, навроде ниндзя или генокрада?

2021-08-14 13:11 UTC, HonkyDonky commented on code/modules/emotes/emotes_verb.dm
> +		var/target = input("Choose a target for applying emotion", "", null) as null | anything in avalibe_target
И что если персонаж умрёт за это время? В `emote()` есть проверка или как?

2021-08-14 15:38 UTC, Oubifx commented on code/modules/emotes/emotes_verb.dm
> +		var/target = input("Choose a target for applying emotion", "", null) as null | anything in avalibe_target
> А это случаем нельзя будет абузить против антагонистов в инвизе, навроде ниндзя или генокрада?

У нас настолько уебанский инвиз что на каждом антаге сделан по своему. Когда рефакторинг его будет, то можно будет поправить, а сейчас это только костыли городить многоэтажные.



> И что если персонаж умрёт за это время? В `emote()` есть проверка или как?

Ну вообще 1 сек достаточно, но *deathgasp пожалуй сделаю без задержки, на всякий.

2021-08-15 07:55 UTC, kcalbCube commented on code/modules/emotes/emote_mob.dm
> +#define EMOTE_COOLDOWN 10
тоби базарит.

2021-08-15 08:02 UTC, kcalbCube reviewed
работаем

2021-08-15 08:02 UTC, kcalbCube commented on code/modules/emotes/emotes_verb.dm
> +		var/target = input("Choose a target for applying emotion", "", null) as null | anything in avalibe_target
абуз абузом, а некоторые до сих пор раундстартом радий жрут что бы детсад спалить

2021-08-15 08:02 UTC, kcalbCube commented on code/modules/mob/mob_defines.dm
> +
- [x] убрать таб и скрыть

2021-08-15 19:54 UTC, Oubifx commented
Теперь выбор цели для эмоций сделан через клик, как у жала генок. Помимо этого кликхандлер теперь может принимать доп. аргументы.
Рантаймов больше нет.
Вернул и ПОЧИНИЛ эмоции без которых некоторые не могут обойтись ._. (glare, stare)
Выбор эмоции с нажатием на себя - использование без цели.
Выбор эмоции с нажатием на цель - использование на цели.
Для отмены выбора эмоции нужно снова нажать на эмоцию.
![emotedemo1](https://user-images.githubusercontent.com/24242919/129490823-4758960b-54c1-41a6-8278-930a1aa22282.gif)

2021-08-21 17:09 UTC, TobyThorne commented on code/modules/emotes/definitions/visible.dm
> -
Короче, чё я парюсь, я дизайнер или кто? 
![image](https://user-images.githubusercontent.com/45202681/130329663-746cfe4d-f43f-422f-8c42-04c102608086.png)

2021-09-01 19:35 UTC, merged