Переработка Dyrwyn, меча боевого мага
ChaoticOnyx/OnyxBay pull request #6310
Opened 2021-08-10 08:41 UTC by NefrNerf

Переработал меч, добавил спрайты основанные на клейморе. Сам предмет теперь работает по принципу энергомеча, с активацией огненного режима.
По урону примерно на уровне клеймора, немного слабее энергомеча.
Полноценно меч можно использовать только после покупки улучшения, при первой покупке у мага будет появляться обычный клеймор.

- [x] close #3415

<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Переработан урон и режим работы Dyrwyn, меча мага, работает по аналогии с есвордом.
tweak: Dyrwyn теперь имеет два режима урона, огненный и физический.
tweak: Dyrwyn больше не пропадает по истечению 30 секунд.
tweak: Заклинание призыва Dyrwyn теперь перезаряжается в течении 10 секунд. Сделано для баланс и возможности разоружить мага.
tweak: При первой покупке Dyrwyn у мага появляется обычный меч. После улучшения - полноценный Dyrwyn.
imageadd: Добавлен свой спрайт для Dyrwyn.
soundadd: Добавлен звук активации для Dyrwyn.
/🆑
```
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-10 08:54 UTC, NefrNerf commented
С этим ПРом боевой маг действительно сможет стать боевым и идти в ближний бой с СБ и прочими, если и этого будет мало для играбельности данного класса, могу переработать остальные спеллы.
Примерно так он выглядит:
![image](https://user-images.githubusercontent.com/85663436/128838146-5af1e234-45b8-4127-9021-908f67b44002.png)

2021-08-10 09:14 UTC, hard-res3t commented
>Маг
>Ближний бой
![1466699860_nedovolnyy-garfild-6](https://user-images.githubusercontent.com/59255670/128841166-d927baf0-638b-4eba-9ec4-b7abc404a1e1.jpg)

2021-08-10 09:27 UTC, NefrNerf commented
Ты его набор скиллов видел? Этот класс для ближнего боя и сделан 6 очков навыков, нет стана и нормальных телепортов, халк и разные щиты. Он и должен в ближнем бою лица сносить.

2021-08-10 09:29 UTC, O0oMaximo0O commented
Говоря именно о боевом маге, чего ему не хватает, я бы сказал, что ему нужен телепорт или бестелесность(Ethereal Jaunt), одного пассажа ему не хватает для мобильности. Так он просто вынужден идти в лоб к СБ и бить их мечом, кидаясь на подходе файерболами и стреляя из посоха(Mental Focus). И ещё #3238. А то он и в ближнем бою сольётся.

2021-08-10 09:35 UTC, NefrNerf commented
Джаунт вместе с этим мечем будет имбой, он просто вырежет всех, так как у него есть ещё и щит который блочит пули.  А броня, да, если геймдизы аппрувнут по, то подкручу резисты.

2021-08-10 09:38 UTC, NefrNerf commented
Вместо джаунта я бы ему дал скилл на ускорение который по окончанию работы накладывал дебафф на скорость, то есть прибежать и убежать он сможет, но не постоянно биться под хостой.

2021-08-10 09:41 UTC, O0oMaximo0O commented
А во время бестелесности можно драться? Тогда точно телепорт, а не её. А чтобы на противника набежать, пассаж уже есть. С убеганием похуже, но ускорение не сильно лучше.

2021-08-10 09:43 UTC, NefrNerf commented
В джаунте нельзя бить, но вот сам джаунт - как десант на голову, обычно маг его использует как побег, но боевой просто прыгнет в толпу и порежет всех

2021-08-12 11:21 UTC, O0oMaximo0O commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +/obj/item/weapon/melee/energy/sword/deactivate(mob/living/user)
А тут не должно быть dyrnwyn после sword?

2021-08-12 11:27 UTC, NefrNerf commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +/obj/item/weapon/melee/energy/sword/deactivate(mob/living/user)
Должно, теперь есть

2021-08-12 12:08 UTC, O0oMaximo0O submitted a review, later dismissed

2021-08-12 12:09 UTC, O0oMaximo0O commented
Надеюсь, за это меня не убьют)

2021-08-20 17:18 UTC, igorsaux commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/clumsy_unaffected = FALSE
почему это свойство только у energy оружия?🤔

2021-08-20 17:21 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/clumsy_unaffected = FALSE
Ну, раньше оно было только у пушек вообще. Я добавил в энергетическое, чтобы не затрагивать код вне области которую меняю. А так да, стоит ее ввести в оружие в целом. Но пока только мага трогал.

2021-08-24 11:01 UTC, NefrNerf commented
Блэт, как я мог забыть, что и тут у меня иконки, вот что бывает если долго не ревьювать и не мерджить

2021-08-28 07:11 UTC, NefrNerf commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	equipped_summons = list("active hand" = /obj/item/weapon/melee/energy/sword/dyrnwyn)
Если я правильно тебя понял, это сделано для того, чтобы маг получил не сразу крутой меч, а только после покупки улучшения

2021-08-28 07:11 UTC, NefrNerf commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	clumsy_unaffected = TRUE
Так он сам себя порежет, если ему не дать защиту от кламзи

2021-08-28 07:13 UTC, NefrNerf commented on code/game/objects/items.dm
> +	var/clumsy_unaffected = FALSE
Исправил

2021-08-28 07:14 UTC, NefrNerf commented on code/game/objects/items/weapons/melee/energy.dm
> +		if((MUTATION_CLUMSY in user.mutations) && prob(50) && !clumsy_unaffected)
Исправил

2021-08-28 13:55 UTC, Epicus7 commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	clumsy_unaffected = TRUE
Почему? У мага есть клампси? Откуда? Это же фича клоуна, не?

2021-08-28 13:59 UTC, NefrNerf commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	clumsy_unaffected = TRUE
Магу дали года 2 назад кламзи, абы не бегал с пушками

2021-08-28 13:59 UTC, Epicus7 commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	equipped_summons = list("active hand" = /obj/item/weapon/melee/energy/sword/dyrnwyn)
Не понял, какого улучшения? Я не очень в теме как это работает, но как я вижу:

У нас есть некий спелл, который спавнит этот дрын-меч. В переменных этого спелла написано:

```
equipped_summons = list("active hand" = /obj/item/weapon/material/sword)
```

То есть если ничего не делать, то при касте этого спелла, у тебя заспавнится обычный меч. Но ты здесь в проке `/datum/spell/targeted/equip_item/dyrnwyn/empower_spell` переопределяешь тип меча:

```
equipped_summons = list("active hand" = /obj/item/weapon/melee/energy/sword/dyrnwyn)
```

И поэтому, видимо, спавнится при касте спелла не обычный меч, а дрын.

Мой вопрос: почему бы сразу в переменных не указать дрын, вместо того чтобы здесь переопределять?

Чо за улучшения я не в курсе и по коду не вижу никаких улучшений здесь. Я куда-то не туда смотрю?

2021-08-28 14:02 UTC, NefrNerf commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	equipped_summons = list("active hand" = /obj/item/weapon/melee/energy/sword/dyrnwyn)
Смотри, спелл призыва меча имеет переменную `equipped_summons`, в ней храниться саммон, на первом уровне заклинания - это обычный меч, при вызове прока `empover_spell` я меняю значение `equipped_summons` на вызов огненного меча.

2021-08-28 14:05 UTC, Epicus7 commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	equipped_summons = list("active hand" = /obj/item/weapon/melee/energy/sword/dyrnwyn)
А, понял. Окей)

2021-08-28 14:05 UTC, Epicus7 commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	clumsy_unaffected = TRUE
А понял. Окей)

2021-08-28 14:06 UTC, Epicus7 commented on code/modules/spells/targeted/equip/dyrnwyn.dm
> +	equipped_summons = list("active hand" = /obj/item/weapon/melee/energy/sword/dyrnwyn)
Ааа, empower_spell это как раз "улучшение спелла", окей, я понял.

2021-08-28 14:06 UTC, Epicus7 approved these changes

2021-08-28 14:42 UTC, Doster-d approved these changes

2021-08-28 14:43 UTC, Doster-d requested changes
А нет, это че за хуйня?
![image](https://user-images.githubusercontent.com/63081538/131221775-94b088db-f794-48b1-b5a7-574b733b115f.png)

2021-08-28 14:55 UTC, NefrNerf commented
![image](https://user-images.githubusercontent.com/85663436/131222096-909a51c9-6a8b-487b-a60f-cbfad453486e.png)
В упор не вижу

2021-08-28 15:36 UTC, Epicus7 commented
Мб баг в сравнивалке спрайтов?

2021-08-28 15:42 UTC, NefrNerf commented
Да похоже, я у себя не нашел

2021-08-28 16:14 UTC, Doster-d approved these changes

2021-08-28 16:19 UTC, NefrNerf commented
Можно мерджить.

2021-08-29 10:37 UTC, merged