fix human-based antags spawn from ghost
ChaoticOnyx/OnyxBay pull request #6339
Opened 2021-08-13 15:01 UTC by Doster-d

Почему этого раньше не было?

~~Почему мне в ревьюверы предлагают Эпикуса? xD~~

close #6333 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Больше нет дождя из мужиков с аплинком
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-22 15:41 UTC, igorsaux approved these changes

2021-08-28 13:38 UTC, Epicus7 requested changes
Ну это уже гораздо лучше, только куча мусорных изменений пробелов осталась. Надо бы убрать это все, чтобы историю не засорять

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/alien/borer.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/alien/xenomorph.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/antagonist.dm
> +			message = "You were selected for role [role_text] by lottery. Are you ready to play it?",
```suggestion
			message = "You were selected for role [role_text] by lottery. Are you ready to play it?", 
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/actors.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/commando.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/deathsquad.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/deity.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/ert.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/ninja.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/raider.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/syndicate.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/outsider/wizard.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/station/meme.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/station/monkey.dm
> +
```suggestion
```

2021-08-28 13:38 UTC, Epicus7 commented on code/game/antagonist/station/monkey.dm
> +			return 1
Тут тоже лишние изменение переноса строки, которое я не могу через suggestion исправить :(

2021-08-28 13:42 UTC, Doster-d commented on code/game/antagonist/station/monkey.dm
> +			return 1
Это изменение как раз [нужное](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2021-08-28 14:04 UTC, Epicus7 requested changes

2021-08-28 14:04 UTC, Epicus7 commented on code/game/antagonist/station/monkey.dm
> +			return 1
Ну только ты добавил в файл monkey.dm это изменение с описанием коммита "fix human-based antags spawn from ghost" :)

Это изменение вне скоупа ПРа

2021-08-28 14:05 UTC, Doster-d commented on code/game/antagonist/station/monkey.dm
> +			return 1
Оно само :(

2021-08-28 14:16 UTC, Doster-d commented on code/game/antagonist/station/monkey.dm
> +			return 1
Исправил.

2021-08-28 14:22 UTC, Epicus7 approved these changes

2021-08-28 17:39 UTC, TobyThorne approved these changes
![image](https://user-images.githubusercontent.com/45202681/131226248-51e939f5-8fd3-414d-9767-d2fbce0cd259.png)
![image](https://user-images.githubusercontent.com/45202681/131226252-9474925f-c133-4ed0-a3f0-a78aad89b17c.png)
![image](https://user-images.githubusercontent.com/45202681/131226253-348f197f-e58b-46a7-9883-daf32c3abfd7.png)

чё)

2021-08-28 17:40 UTC, igorsaux approved these changes

2021-08-28 17:41 UTC, merged