Fixes bug borg and AI
ChaoticOnyx/OnyxBay pull request #6343
Opened 2021-08-13 17:50 UTC by malboec

Собственно, перезалив #6272 

close #5048
close #6031
close #5659

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь ИИ и борги могут считывать показания аварийных шлюзов на любом расстоянии.
bugfix: Исправлена возможность вызвать несколько раз окно выбора модулей.
bugfix: Теперь examine работает через shift+ЛКМ
bugfix: Теперь ИИ может электризовать двери через АЛЬТ.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-14 04:07 UTC, BooJ1K commented
У меня возник вопрос: ИИ на данный момент может электризовать шлюзы через котрл+альт+клик, собственно, зачем ему менять горячие клавиши на альт+клик, тем самым, убивая возможность смотреть тюрф на клетке со шлюзом?

2021-08-14 10:19 UTC, malboec commented
Можно пользоваться ПКМом. Иссуй же контрл+альт выставляет как баг, с учётом того, что ему убрали "требуется проверка". Если так принципиально, то можно спросить у геймдизов на счёт этого. Не спорю, что осмотр турфа на альт удобен, но вот так.

2021-08-14 13:29 UTC, MrMagick2104 commented
> Можно пользоваться ПКМом. 

Через ПКМ можно использовать вёрбы, но нельзя использовать взаимодействия с мышкой.

2021-08-15 07:43 UTC, kcalbCube commented
чейнджлог поубавь

2021-08-15 07:45 UTC, kcalbCube reviewed
нужны тестирования а не ревью

2021-08-15 07:45 UTC, kcalbCube commented on code/modules/mob/living/silicon/robot/robot.dm
> +	modtype = null
оно надо?

2021-08-16 12:32 UTC, malboec commented on code/modules/mob/living/silicon/robot/robot.dm
> +	modtype = null
Да.

2021-08-26 17:26 UTC, Epicus7 requested changes
Насчет электрофикации через Alt+Click - это не баг. Это бейцы специально так сделали, вот ПР:
https://github.com/Baystation12/Baystation12/pull/19757

Вообще не все баги - это прям баги. Очень часто бывает так, что какое-то поведение специально предусматривали, но игроки и модератор гитхаба не в курсе и пометили баг актуальным. Они и не могут разобраться без разработчика, потому что нужно смотреть историю кода и разбираться кто и зачем эту логику менял.

Поэтому очень часто имеет смысл смотреть историю кода или блейм, а не бежать слепо фиксить то, что зарепортили игроки. Если какая-то вещь специально вводилась, то надо подумать стоит ли её откатывать и согласовывать с геймдизайнерами. Здесь я думаю все ок, так как Examine турфов и открытие/закрытие шкафчиков ИИ тоже нужно.

2021-09-07 17:12 UTC, malboec commented
Чёт я слегка помер, ну да ладно.

2021-09-24 11:34 UTC, TermService approved these changes

2021-09-24 12:35 UTC, Epicus7 approved these changes

2021-09-24 12:39 UTC, merged