tweak(infections)
ChaoticOnyx/OnyxBay pull request #6354
Opened 2021-08-15 12:30 UTC by kcalbCube

таки перезалив: небоже 1024 иссую пропадать
close #1024

опять же, инфекции теперь в основном создаются от ран ибо они создают инфекцию, у инфекций теперь не три, а четыре стадии, алгоритм распространения инфекций тоже поменял, всё нормально вообще.

от #5391 отличается тем что убрал возможность прижечь инфекцию и получать интерналам дополнительный урон от инфекции.

<details>
<summary>Чейнджлог</summary>

```yml
🆑KcalbCube
tweak: усилены инфекции
/🆑
```

</details>

Hasta la vista, медботы.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-15 12:31 UTC, kcalbCube commented
@igorsaux @TobyThorne @HonkyDonky @TatarTheBuilder хочу геймдизайнерское и кодревью

2021-08-15 13:14 UTC, kreeperHLC requested changes

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/mob/living/carbon/human/human_organs.dm
> +		if(O.germ_level > INFECTION_LEVEL_ONE/2)
Пробелы

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +	//spread the infection to internal organs
Отвратный коммент

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +	var/obj/item/organ/target_organ = null	//make internal organs become infected one at a time instead of all at once
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +		if(I.germ_level < germ_level)	//once the organ reaches whatever we can give it, or level two, switch to a different one
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +			if(!target_organ || I.germ_level < target_organ.germ_level)	//choose the organ with the lowest germ_level
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +		//figure out which organs we can spread germs to and pick one at random
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +	//spread the infection to child and parent organs
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +	if(germ_level >= INFECTION_LEVEL_FOUR && antibiotics < 15)	//overdosing is necessary to stop severe infections
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/external/_external.dm
> +		owner.adjustToxLoss(0.5)
Зачем ослабил?

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +			limb.germ_level += rand(50, 150)
Зачем ослабил?

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/mob/living/carbon/human/human_organs.dm
> +							W.germ_level += 1.5
Зачем усилил?

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/appendix.dm
> +	if(germ_level > INFECTION_LEVEL_TWO)
Отличная лесенка. Пофикси.

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/brain.dm
> +		if(germ_level > INFECTION_LEVEL_TWO && prob(1))
Ммм, постоянная проверка на 1 процент. Спасибо папаша

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/eyes.dm
> +	if(germ_level > INFECTION_LEVEL_TWO && prob(1))
Ммм, и тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/liver.dm
> +			to_chat(owner, SPAN_WARNING("Your skin itches."))
Варнинг на данжер

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/lungs.dm
> +		if(prob(2))
Ммм, доп проверки на 1 и на 2 процента

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/lungs.dm
> +		if(prob(2))
МММ

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/internal/lungs.dm
> +				"<B>\The [owner]</B> coughs up blood!",
<B>

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +			germ_level += rand(4,8)
Зачем усилил?

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +	if(germ_level > 0 && germ_level < INFECTION_LEVEL_ONE/2 && prob(virus_immunity * 0.3))
Пробелы забыл

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +	if(germ_level >= INFECTION_LEVEL_ONE/2)
Пробелы

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +		if(antibiotics < 5 && prob(round(germ_level/(INFECTION_LEVEL_TWO*0.015) * owner.immunity_weakness())))
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +			germ_level += round(M_EULER**(germ_level/1000) * owner.immunity_weakness())
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +			germ_level += round(M_EULER**(germ_level/1000) * owner.immunity_weakness()) * 10
И тут

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +			germ_level += round(M_EULER**(germ_level/1000) * owner.immunity_weakness())
Да и ещё какие-то невероятные подсчеты с магическими числами без комментариев

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
>  		//spread germs
Поправь это

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +		if(antibiotics < 5 && parent.germ_level < germ_level && ( parent.germ_level < INFECTION_LEVEL_ONE*2 || prob(owner.immunity_weakness() * 0.3) ))
Пробелы

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +			take_general_damage(1, silent=prob(15))
Пробелы, объяснение вот этого вот говна

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/organs/organ.dm
> +	germ_level -= Interpolate(antibiotics, 1, germ_level / (INFECTION_LEVEL_FOUR + 400))
Что это вообще за говно

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	M.add_chemical_effect(CE_ANTIBIOTIC, volume)
А причем тут вот это и откуда?

2021-08-15 13:14 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> -//	 skin cauterization surgery step
Зачем было удалено?

2021-08-15 13:17 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
> +	//spread the infection to internal organs
в оригинале был

2021-08-15 13:23 UTC, kcalbCube commented on code/modules/organs/external/_external.dm
> +		owner.adjustToxLoss(0.5)
быстро убьет слишком

2021-08-15 13:25 UTC, kcalbCube commented on code/modules/organs/internal/brain.dm
> +		if(germ_level > INFECTION_LEVEL_TWO && prob(1))
а как лучше сделать что бы периодически замыливало?

2021-08-15 13:33 UTC, kcalbCube commented on code/modules/surgery/generic.dm
> -//	 skin cauterization surgery step
я забыл что я не добавлял новую операцию, а изменял существующую

2021-08-15 13:37 UTC, kcalbCube commented on code/modules/organs/organ.dm
> +			germ_level += rand(4,8)
что бы усилить

2021-08-15 13:58 UTC, kcalbCube commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
> +	M.add_chemical_effect(CE_ANTIBIOTIC, volume)
это для плавности

2021-08-15 17:14 UTC, kcalbCube commented
@igorsaux @Doster-d хочу ревью

2021-08-17 03:42 UTC, kcalbCube commented
тестил кое-что на локалке и случайно сидел на билде, на котором этот ПР основывается. вообще нормально. разве что не хватает симптомов на этапах ниже сепсиса, но думаю это не особо нужно. со вскрытым скальпелем брюхом простоял 15 минут. получили вот такое
![image](https://user-images.githubusercontent.com/43304650/129660046-3e3086fd-1290-414e-b7d2-36aeb3247667.png)
немного резковата смерть после начала гангрены груди, ибо это инстакиллит космонавтика.

2021-08-20 20:19 UTC, kcalbSphere commented
развязал руки ваундам, теперь они ещё смертоноснее.

2021-08-20 20:22 UTC, kcalbSphere commented
развязал руки ваундам, теперь они ещё смертоноснее.  
добавил варнинг в adv_med, правда пока кривовато
разнерфил инфекции от пулла
теперь дизенфекция раны не удаляет все микробы, а убирает 50% и замедляет их размножение(как и залечивание)

2021-08-21 06:07 UTC, closed without merging

2021-08-21 06:08 UTC, TobyThorne commented
> развязал руки ваундам, теперь они ещё смертоноснее.
> добавил варнинг в adv_med, правда пока кривовато
> разнерфил инфекции от пулла
> теперь дизенфекция раны не удаляет все микробы, а убирает 50% и замедляет их размножение(как и залечивание)

Опять какая-то хуита не по иссую. Не нужно.

2021-08-21 06:26 UTC, kcalbSphere commented
да ты заебал

2021-08-22 14:37 UTC, kcalbSphere commented
так вы закрыли из-за изменений, или из-за чего
типа иссуй с приоритетом, с наградой...

2021-08-25 03:39 UTC, kcalbSphere commented
из-за некоего морального урода подавшего на меня жалобу о педофилии напрямую в центр дискорда мне заблочили аккаунт. поэтому хочу передать привет плину и эпикусу.