Improvment(turfs&map): EOS fountain now has a slippery water.
ChaoticOnyx/OnyxBay pull request #6365
Opened 2021-08-16 11:47 UTC by Zert0X

Альтехор оплатил коммуналку и теперь в фонтане есть вода
В добавок ко всему вода теперь скользкая. Галоши и ласты по прежнему спасают от этого.
close #6070
close #6067 
<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Вода в фонтане на ЕОС.
/🆑
```
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-16 12:23 UTC, kreeperHLC commented
![image](https://user-images.githubusercontent.com/14943437/129563188-9eb1b5be-cfae-45f1-9062-934b8709a113.png)
Вас спалил иссуй. Ожидайте геймдизов

2021-08-16 12:42 UTC, Zert0X commented
> 
> 
> ![image](https://user-images.githubusercontent.com/14943437/129563188-9eb1b5be-cfae-45f1-9062-934b8709a113.png)
> Вас спалил иссуй. Ожидайте геймдизов

Протрите окуляры
![изображение](https://user-images.githubusercontent.com/42303535/129565508-2276904c-a0df-4e09-97c7-eb1f1219e06c.png)

2021-08-27 09:40 UTC, Epicus7 submitted a review, later dismissed

2021-08-28 14:36 UTC, Doster-d requested changes

2021-08-28 14:36 UTC, Doster-d commented on code/game/turfs/flooring/flooring_premade.dm
> +		M.slip("the [src.name]", 4)
Бьенд умный, сам поставит, когда надо... Вроде как.
```suggestion
		M.slip(src, 4)
```

2021-09-15 21:24 UTC, MaxTheAstronaut commented on code/game/turfs/flooring/flooring_premade.dm
> +		M.slip("the [src.name]", 4)
А разве не надо писать `\The`?

2021-09-26 09:10 UTC, Zert0X commented
насрал в ветку

2021-09-26 09:10 UTC, closed without merging