greentext
ChaoticOnyx/OnyxBay pull request #6371
Opened 2021-08-17 09:48 UTC by TapKo4eB

сап двач

![image](https://user-images.githubusercontent.com/48761132/129703978-f0bb54b7-dcdf-40a0-b6d4-982ad9eba496.png)

<details>
<summary>чпшпелог</summary>

```yml
🆑
rscadd: Добавлен гринтекст в ООС.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-17 09:50 UTC, hard-res3t commented
Иронично.

2021-08-17 09:51 UTC, TapKo4eB commented
>квалити оф луфе
>геймдизайгн
kys

2021-08-17 09:56 UTC, kcalbCube commented
зелёный.

2021-08-17 15:08 UTC, HonkyDonky submitted a review, later dismissed
2к21й, ТАПОК ПРИНОСИТ С ПОДВАЛА ГРИНТЕКСТ
@
НУ ХОТЬ ПОПРОБУЕМ ЧТО ЭТО ТАКОЕ
@
ПОБАЛУЕМСЯ

2021-08-17 15:09 UTC, Doster-d approved these changes, later dismissed
\>Пук, среньк, гринтекст не нужен.

2021-08-17 15:11 UTC, igorsaux requested changes

2021-08-17 15:11 UTC, igorsaux commented on code/datums/communication/ooc.dm
> +		var/sent_message = "[create_text_tag("ooc", "OOC")] <EM>[decorated_ckey]:</EM> <span class='message linkify'>[greentext ? "<font color='#789922'>[message]</font>" : "[message]"]</span>"
хардкод цвета точно ненужно

2021-08-17 15:12 UTC, Doster-d commented on code/datums/communication/ooc.dm
> +		var/sent_message = "[create_text_tag("ooc", "OOC")] <EM>[decorated_ckey]:</EM> <span class='message linkify'>[greentext ? "<font color='#789922'>[message]</font>" : "[message]"]</span>"
```suggestion
		var/sent_message = "[create_text_tag("ooc", "OOC")] <EM>[decorated_ckey]:</EM> <span class='message linkify'>[greentext ? "<font color='[COLOR_GREEN]'>[message]</font>" : "[message]"]</span>"
```

2021-08-17 15:14 UTC, Doster-d commented on code/datums/communication/ooc.dm
> +		var/sent_message = "[create_text_tag("ooc", "OOC")] <EM>[decorated_ckey]:</EM> <span class='message linkify'>[greentext ? "<font color='#789922'>[message]</font>" : "[message]"]</span>"
Или даже так.
```suggestion
		var/sent_message = "[create_text_tag("ooc", "OOC")] <EM>[decorated_ckey]:</EM> <span class='message linkify'>[greentext ? "[SPAN("greentext", message)]" : "[message]"]</span>"
```

2021-08-17 16:04 UTC, Doster-d commented on code/datums/communication/ooc.dm
> +	var/green = html_decode(message)
А таки не жирно ли использовать хтмл декоде?

2021-09-18 10:13 UTC, HonkyDonky commented
Почему это до сих пор не приняли? Как мне ещё двач устраивать в OOC?

2021-09-28 07:05 UTC, Doster-d approved these changes

2021-10-14 01:13 UTC, TobyThorne commented
Ладно, ПР был очевидным мемом.

2021-10-14 01:15 UTC, closed without merging