tweak(convert): adds restrictions on convert to cult
ChaoticOnyx/OnyxBay pull request #6374
Opened 2021-08-18 18:30 UTC by NefrNerf

Добавил ограничение на вступление в культ различных существ: дион, генокрадов, магов
В связи с вводом насильного конверта и возможного абуза магами, который будет сложно отследить, введен гиб всех участников ритуала, для ограничения желания рьяных культистов.

Добавил язык культа магу, так как если он захочет создавать конструкты то с новыми ограничениями никак не сможет их понять.

Прошлый ПР был успешно мной проебан, надеюсь этот не вызовет 12тысяч дифов

- [x] close  #1896
<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Генокрад больше не может вступить в культ.
balance: Диона больше не может вступить в культ.
balance: Чужие больше не могут вступить в культ.
balance: При успешной конвертации мага в культ происходит культистов и конвертация мага с потерей всех способностей.
tweak: Теперь маг понимает язык культистов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-19 05:34 UTC, kcalbSphere commented
> введен гиб всех участников ритуала, для ограничения желания рьяных культистов.

как конкретно это работает?

2021-08-19 05:46 UTC, NefrNerf commented
Немного не так описал, гибнет только культистов, а не мага, в ЧЛ правильная информация. И да, работает оно так, на момент конверта, опрашивается количество людей рядом, если они состоят в культе и маг принимает - гиб культистов.

2021-08-19 05:49 UTC, kcalbSphere commented
а если маг будет притворятся человеком для того что бы культистов обмануть?

2021-08-19 05:52 UTC, NefrNerf commented
Культисты будут внимательнее жертв выбирать, да и магу нахуя это делать? Он конвертнется в культ и все.

2021-08-19 05:58 UTC, kcalbSphere commented
допустим.

2021-08-19 05:58 UTC, kcalbSphere commented
кстати 
![image](https://user-images.githubusercontent.com/43304650/130015789-b4a99a9e-c28f-4c01-a951-94b00aa66b60.png)

2021-08-19 06:02 UTC, NefrNerf commented
Кек, проклятый ПР, с ним какие-то чудеса случаются, нормально же все было

2021-08-19 06:08 UTC, MaxFreemen commented
Нефр, ты забыл написать слово "гиб".
```
balance: При успешной конвертации мага в культ происходит культистов и конвертация мага с потерей всех способностей.
```

2021-08-19 11:28 UTC, NefrNerf commented
Теперь все нормально

2021-08-19 11:35 UTC, kcalbSphere requested changes
спорно. лишние проки на проверку...
убери эти проки, а потом посмотрим.

2021-08-19 11:35 UTC, kcalbSphere commented on code/game/antagonist/alien/xenomorph.dm
> +/proc/isXenomorph(mob/player)
зачем

2021-08-19 11:35 UTC, kcalbSphere commented on code/game/antagonist/outsider/wizard.dm
> +/proc/isWizard(mob/player)
зачем

2021-08-19 11:35 UTC, kcalbSphere commented on code/game/antagonist/outsider/wizard.dm
> +	wizard.current.add_language(LANGUAGE_CULT)
это зачем

2021-08-19 11:35 UTC, kcalbSphere commented on code/game/antagonist/station/changeling.dm
> +/proc/isChangeling(mob/player)
зачем

2021-08-19 11:35 UTC, kcalbSphere commented on code/game/gamemodes/cult/runes.dm
> +			to_chat(M, SPAN_DANGER("This person cant be converted. IT WAS A DEADLY MISTAKE"))
```suggestion
			to_chat(M, SPAN_DANGER("This person cannot be converted. THIS WAS A DEADLY MISTAKE"))
```

2021-08-19 11:35 UTC, kcalbSphere commented on code/game/gamemodes/cult/runes.dm
> +		GLOB.wizards.remove_antagonist(target.mind, TRUE)
DEATH IS COMMING FOR THOSE FOOLS, но выписан из магов.

2021-08-19 11:41 UTC, NefrNerf commented
is какой-то там антаг на проверку, есть ли человек в глобальном списке антагов, быстрая проверка

2021-08-19 11:42 UTC, NefrNerf commented
Читай описание ПРа, зачем я язык добавил

2021-08-19 11:43 UTC, NefrNerf commented on code/game/gamemodes/cult/runes.dm
> +		GLOB.wizards.remove_antagonist(target.mind, TRUE)
Он выписан из магов, культисты выписаны из жизни, в чем проблема?

2021-08-26 16:49 UTC, Epicus7 requested changes
Реализация не соответствует иссую. Более того, большая часть иссуя не выполнена, так что закрывать его этим ПРом точно рановато.

Чтобы просто обозначить, что ты выполняешь частично иссуй - можно написать "issue #1896", тогда у тебя будет привязка к иссую, но он не закроется автоматически и потом его можно будет дополнительными ПРами доделать.

2021-10-14 01:25 UTC, TobyThorne commented
Ченжреквест от Эпикуса висит уже почти два месяца. Если автор оживёт - всегда может переоткрыть.

2021-10-14 01:25 UTC, closed without merging