doomsday protocol
ChaoticOnyx/OnyxBay pull request #6380
Opened 2021-08-19 16:03 UTC by HentaiStorm

Добавляет возможность зайти на сервер после дня-X (ядерный апокалипсис, отключение byond хаба, второго пришествии Христа) под своим сикеем.

Как работает?
1. Для начала нужно раскомментировать ENABLE_DOOMSDAY_PROTOCOL в config.txt
2. Внутри папки doomsday-protocol лежит keys_list.txt (вместе с бинарниками и краткой инструкцией по установки), представляющий таблицу формата .txt по аналогии с admins.txt, где нужно добавить запись вида "computer_id:key"
3. При соединении с сервером под гостевым ключом, сервер проверит конфиг на включенный проткол, далее выдаст айди компьютера пользователя отдельным окном, если того нету в списке ключей; либо присвоит ему указанный ключ (стягивая также баны, админки как обычно), если айди его компьютера включен в список

P.S А еще заменены местами вывод айди раунда и мотд, они почему-то загружались раньше всех сообщений, тем самым появляясь также и с отдельным окошком вывода айди компьютера...

А еще приветствуются дампы вики, пдфки страниц! Все таки код будет лежать на арктической станции еще тысячу лет)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
experiment: возможность запустить билд и зайти под своим сикеем даже после отключения/блокировки хаба, ядерной войны, пришествии Иисуса.
/🆑
```

</details>

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-19 16:32 UTC, Doster-d commented on code/modules/client/client_procs.dm
> +	if(join_motd)
А это зачем?

2021-08-19 16:33 UTC, HentaiStorm commented on code/modules/client/client_procs.dm
> +	if(join_motd)
Оно перенесено из new_mob, потому что вылезало раньше всего

2021-08-19 16:34 UTC, Doster-d commented on code/modules/client/client_procs.dm
> +	if(join_motd)
Ок.

2021-08-19 16:34 UTC, Doster-d approved these changes, later dismissed

2021-08-19 17:24 UTC, kcalbSphere commented
SERVER CONNECTION FAILED, DOOMSDAY PROTOCOL CONNECTION ESTABLISHMENT STARTED

2021-08-19 18:14 UTC, Epicus7 commented on code/modules/client/client_procs.dm
> +	if(join_motd)
И чем оно мешало, что вылезало раньше "всего"? Зачем это переносить?

2021-08-19 18:18 UTC, Doster-d commented on code/modules/client/client_procs.dm
> +	if(join_motd)
Сообщение о DOOMSDAY протокол не видно.

2021-08-19 18:21 UTC, Epicus7 requested changes
> doomsday_protocol/514.1560_byond_linux.zip 
> doomsday_protocol/514.1561_byond_windows.exe 
> doomsday_protocol/514.1561_byond_windows.zip

Исполняемые файлы Бьонда в репозитории не нужны. Думсдей конечно смешно, но все равно не нужно.

Еще и папка лишняя вылезла в корне проекта ради какой-то фичи, которая никогда не понадобится.

2021-08-19 18:21 UTC, Epicus7 commented on code/modules/client/client_procs.dm
> +			show_browser(src, "Access Denied!<br><br>Your computer id: [computer_id]<br><br>Tell your id to system administator for adding you to doomsday protocol", "window=cid;size=400x200;")
> to system administrator

Кому? Лучше провайдеру сразу

2021-08-19 18:21 UTC, Epicus7 commented on code/modules/client/client_procs.dm
> +			qdel(src)
Если удалить клиента, то браузер, созданный выше, тоже удалится, по идее, и клиент его не прочитает

2021-08-19 18:21 UTC, Epicus7 commented on code/controllers/configuration.dm
> +					var/list/localLines = file2list("config/keys_list.txt")
Название файлу можно было бы дать более специфичное, чтобы по нему сразу было понятно что это за ключи и зачем они

2021-08-19 18:21 UTC, Epicus7 commented on code/modules/client/client_procs.dm
> +			report_progress(error)
А это зачем? Это прогресс старта сервера, я так понимаю, пишется этим проком обычно. Причем тут один конкретный логин одного конкретного юзера? Мы туда ничего такого не пишем.

2021-08-19 18:23 UTC, Epicus7 commented
По-моему, это какая-то ненужная фича.

Чо, кстати, образ винды не положил рядом с бьондом? Без винды не заработает тоже. Еще можно гайд по сборке компьютера x86 архитектуры из говна и палок в условиях апокалипсиса

2021-08-19 18:41 UTC, HentaiStorm commented
> Кому? Лучше провайдеру сразу
Сетевой провайдер не всегда администратор сервера 

>Если удалить клиента, то браузер, созданный выше, тоже удалится, по идее, и клиент его не прочитает
По тестам закрывается соединение и появляется окошко с компьютер айди, вот так: 
![изображение](https://user-images.githubusercontent.com/60922927/130125100-15a188ab-35b8-42fe-b19c-1adbd76b780c.png)

>Название файлу можно было бы дать более специфичное, чтобы по нему сразу было понятно что это за ключи и зачем они
Соглашусь, поменяю

>А это зачем? Это прогресс старта сервера, я так понимаю, пишется этим проком обычно. Причем тут один конкретный логин одного конкретного юзера? Мы туда ничего такого не пишем.
Это прямой вывод в терминал, работает и после инициализации сервера. Думаю тоже можно убрать, раз пользователь уже получает компьютер айди

>Чо, кстати, образ винды не положил рядом с бьондом? Без винды не заработает тоже. Еще можно гайд по сборке компьютера x86 архитектуры из говна и палок в условиях апокалипсиса
Предполагается наличие какой-нибудь ОСи, что может прочитать цифровую информацию. Класть гайд тоже бессмысленно, без базовой ОСи ее не прочитать все равно. Полагаю уже имеется одна из двух ОСей.

>По-моему, это какая-то ненужная фича.
Хромой бульонд может упасть раньше, чем начнется апокалипсис, если к тому времени ты не закодишь аутенфикацию по форуму. К тому же код попал в программу арктического хранилища и к 2025 попадет в хранилище на тысячу лет! Без этого патча будущие космонавты будут сидеть с Guest-XXXX...

2021-08-20 00:15 UTC, Doster-d commented on code/modules/client/client_procs.dm
> +			show_browser(src, "Access Denied!<br><br>Your computer id: [computer_id]<br><br>Tell your id to system administator for adding you to doomsday protocol", "window=cid;size=400x200;")
Может лучше хеши отдавать?
```suggestion
			show_browser(src, "Access Denied!<br><br>Your computer id: [md5(computer_id)]<br><br>Tell your id to system administator for adding you to doomsday protocol", "window=cid;size=400x200;")
```

2021-08-20 00:15 UTC, Doster-d commented on code/modules/client/client_procs.dm
> +		if(!(computer_id in config.doomsday_entity))
```suggestion
		if(!(md5(computer_id) in config.doomsday_entity))
```

2021-08-20 11:46 UTC, HentaiStorm commented on code/modules/client/client_procs.dm
> +		if(!(computer_id in config.doomsday_entity))
Применять хэш нецелесообразно по двум причинам:
1) он длиньше самого компьютер айди
2) без применения соли подобрать компьютер айди, состоящий исключительно из 10 цифр - дело 5 минут или 10 секунд с применением радужной таблицы.

В этом просто нет необходимости, если компьютер айди передается хостеру по защищенному каналу связи (хоть личкой дискорда).

2021-08-26 19:23 UTC, closed without merging

2022-03-02 14:35 UTC, Doster-d commented
> Мертвый код, который никогда не пригодится.

Хых.

2023-06-24 11:35 UTC, hack-wrench commented
бамп