tweak(chem dispencer ui)
ChaoticOnyx/OnyxBay pull request #6393
Opened 2021-08-22 13:17 UTC by kcalbSphere

портировал интерфейс хим.раздатчика с тг.
наслаждайтесь.
![image](https://user-images.githubusercontent.com/43304650/130356665-cdc35070-59cc-4241-84bd-22a889013967.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑kcalbCube
tweak: интерфейс химраздатчика перенесен на тгуи.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-22 13:18 UTC, kcalbSphere commented
бля конфликты

2021-08-22 14:18 UTC, kcalbSphere commented
тгуи смог в мерж

2021-08-28 14:33 UTC, Doster-d requested changes
Конфликты.
Смержись с devом, затем запусти в VS code - TGUI Dev, во вкладке debug

2021-09-01 05:26 UTC, TobyThorne commented
Не вижу точной настройки количества реагентов. Наливать исключительно с шагом в 5 - неудобство ради неудобства. Ещё и вместо столбиков все реагенты просто лежат в куче.

ТГУИ - круто, конечно, но ухудшать интерфейс исключительно ради него - такое.

2021-09-01 07:38 UTC, closed without merging

2021-09-03 05:12 UTC, kcalbCube commented
> Не вижу точной настройки количества реагентов. Наливать исключительно с шагом в 5 - неудобство ради неудобства. Ещё и вместо столбиков все реагенты просто лежат в куче.
> 
> ТГУИ - круто, конечно, но ухудшать интерфейс исключительно ради него - такое.

ок, сказали бы, я бы добавил.
чё закрывать то.

2021-09-03 05:13 UTC, kcalbCube commented
> Конфликты.
> Смержись с devом, затем запусти в VS code - TGUI Dev, во вкладке debug

сейчас бы тгуи из вскода компилить