plasmasaw surgery fix
ChaoticOnyx/OnyxBay pull request #6401
Opened 2021-08-24 05:17 UTC by HentaiStorm

close #6383

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: добавлена возможность проводить операцию плазма пилой
/🆑
```

</details>

✅ Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
✅ Я внимательно прочитал все свои изменения и багов в них не нашел.
✅ Я запускал сервер со своими изменениями локально и все протестировал.
✅ Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-24 05:20 UTC, Doster-d reviewed
Ты зачем тралинг комы создал?

2021-08-24 05:23 UTC, HentaiStorm commented
Они прикольные

2021-08-25 03:42 UTC, kcalbSphere commented
ты нахуя тралинг слэши убрал?

2021-09-02 10:24 UTC, kreeperHLC requested changes

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/weapon/scalpel/manager = 100,
```suggestion
		/obj/item/weapon/scalpel/manager = 100
```

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/weapon/material/shard = 50,
```suggestion
		/obj/item/weapon/material/shard = 50
```

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/weapon/melee/energy/sword/one_hand = 50,
```suggestion
		/obj/item/weapon/melee/energy/sword/one_hand = 50
```

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/device/assembly/mousetrap = 20,
```suggestion
		/obj/item/device/assembly/mousetrap = 20
```

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/weapon/material/kitchen/utensil/fork = 50,
```suggestion
		/obj/item/weapon/material/kitchen/utensil/fork = 50
```

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/weapon/weldingtool = 25,
```suggestion
		/obj/item/weapon/weldingtool = 25
```

2021-09-02 10:24 UTC, kreeperHLC commented on code/modules/surgery/generic.dm
> +		/obj/item/weapon/material/hatchet = 75,
```suggestion
		/obj/item/weapon/material/hatchet = 75
```

2021-09-09 01:34 UTC, kcalbCube requested changes
пр на пять строчек дифа растянули на вот это
![image](https://user-images.githubusercontent.com/89654493/132607552-85e4f190-8a6b-4fdc-bc96-7735cf54422b.png)

2021-10-14 01:10 UTC, TobyThorne commented
ПР с ченжреквестом висит в неизменном виде уже полтора месяца. Наверное, стоит отключить от АИК.

2021-10-14 01:10 UTC, closed without merging