514
ChaoticOnyx/OnyxBay pull request #6412
Opened 2021-08-26 11:56 UTC by igorsaux

Ну вроде всё ¯\\_(ツ)\_/¯

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-08-26 16:17 UTC, Epicus7 requested changes
На 514 мы переходить не будем пока не будет уверенности, что там реально все стабильно.

Как минимум нужен фикс #6410 со стороны Бьонда.
Как максимум - надо подождать пока еще кто-то обкатает (ТГ, Бейстейшен, Тау). Не очень важно кто именно.

2021-10-12 15:31 UTC, Doster-d submitted a review, later dismissed
Время пришло.

2021-10-12 16:23 UTC, Zert0X submitted a review, later dismissed
TIME

2021-10-12 20:49 UTC, igorsaux commented
пусть пока минимальным 513

2021-10-12 20:53 UTC, Epicus7 approved these changes

2021-10-12 20:54 UTC, kreeperHLC approved these changes

2021-10-12 20:57 UTC, merged