Рисовальное
ChaoticOnyx/OnyxBay pull request #6451
Opened 2021-09-02 15:36 UTC by Doster-d

Эффективность не проверял, но красиво, без раст_гхе.
Есть баг, что когда поднимаешь холст, то он в руке находится в левом нижнем углом, раздражает, нид хелп.
[Спиздил с этого ПРа код тгуи, спрайты и идею реализации.](https://github.com/BeeStation/BeeStation-Hornet/pull/4648)
![демонстранция](https://user-images.githubusercontent.com/63081538/131872795-45450e51-10ef-497b-b2e5-f98ffad518bb.png)

close #2123

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлено возможность рисовать картины, добавлен контейнер с холстами в карго.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-02 17:06 UTC, Doster-d commented
В демонастрации изображено 90% всех будущих артов с этой технологии.

2021-09-02 18:00 UTC, No-Tips commented
Вырезаем член из граффити чтобы дать возможность космонавтам рисовать члены на холсте.

2021-09-02 18:27 UTC, DarkHunter7756 commented
> Вырезаем член из граффити чтобы дать возможность космонавтам рисовать члены на холсте.

Слушай, а ловко ты это придумал. Я даже в начале не понял. Молодец

2021-09-03 05:09 UTC, kcalbCube commented
ебать, эта хуйня может и без rust_g работать? не ожидал.

2021-09-03 06:19 UTC, DarkHunter7756 commented
> В демонастрации изображено 90% всех будущих артов с этой технологии.

А что насчет палитры? Сколько цветов поддерживает?

2021-09-03 06:21 UTC, Doster-d commented
> А что насчет палитры? Сколько цветов поддерживает?

Rainbow crayon содержит все цвета.
Я не стал порождать сущности, поэтому рисования происходит через ручки и крайоны

2021-09-03 06:21 UTC, Doster-d commented
> ебать, эта хуйня может и без rust_g работать? не ожидал.

Я тоже не ожидал.

2021-09-03 06:46 UTC, DarkHunter7756 commented
Добавишь холсты сюда? 
![image](https://user-images.githubusercontent.com/76823962/131962413-6fb6f3de-8e47-4bc8-afb2-e709c02c945a.png)

2021-09-03 06:47 UTC, Doster-d commented
Не в этом пре

2021-09-03 06:47 UTC, DarkHunter7756 commented
> Не в этом пре

Оке

2021-09-03 08:56 UTC, MemoryDreams commented
Охренеть, вот ради этой фичи можно и в игру зайти.

2021-09-03 08:57 UTC, MemoryDreams commented
А можно сделать, чтобы спрайт холста был не вплотную к краю тайла? Хотя бы на пару пикселей влево его сместить бы.

2021-09-03 09:00 UTC, Doster-d commented
> А можно сделать, чтобы спрайт холста был не вплотную к краю тайла? Хотя бы на пару пикселей влево его сместить бы. 

Смещение происходит, в игре он не в углу... Чаще всего, в руке смещение ест говно, это можно сделать, но мне лень рисовать белые точки, можешь сам это сделать, размеры можешь новые придумать

2021-09-03 09:07 UTC, No-Tips commented
А какие размеры холста есть?

2021-09-03 09:10 UTC, Doster-d commented
11икс11 19икс9 19икс19 23икс23

2021-09-03 14:19 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/132020605-4d1259e0-b58d-474e-a560-2c80438d828a.png)
Вот хев ай дан...

2021-09-03 14:38 UTC, Doster-d commented
> ![image](https://user-images.githubusercontent.com/63081538/132020605-4d1259e0-b58d-474e-a560-2c80438d828a.png)
> Вот хев ай дан...

Ответ на вопрос может ли робот создать шедевр.
Ответ на вопрос Do Androids Dream of Electric Sheep?

2021-09-04 06:19 UTC, kcalbCube requested changes
кодстайл был пьян

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	if(new_name != painting_name && new_name && CanUseTopic(user, GLOB.physical_state))
мб
```suggestion
	if(new_name && new_name != painting_name && CanUseTopic(user, GLOB.physical_state))
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	var/new_name = sanitize(input(user,"What do you want to name the painting?"))
```suggestion
	var/new_name = sanitize(input(user, "What do you want to name the painting?"))
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	if(istype(I, /obj/item/canvas))
давай без лесенок
```suggestion
	if(!istype(I, /obj/item/canvas))
		return ..()
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
давай так
```
	if(!painting)
		return
	if(painting.loc == T)
		painting.forceMove(get_turf(src))
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	var/canvas_color = "#ffffff" //empty canvas color
уродливый комментарий

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	///boolean that blocks persistence from saving it. enabled from printing copies, because we do not want to save copies.
тоже урод

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	var/painting_name = "Untitled Artwork" //Painting name, this is set after framing.
```suggestion
	var/painting_name = "Untitled Artwork" // Painting name, this is set after framing.
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	var/finalized = FALSE //Blocks edits
```suggestion
	var/finalized = FALSE // Blocks edits
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	if(user.a_intent == I_HELP)
```suggestion
	if(!user.a_intent == I_HELP)
		return ..()
```

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	.["finalized"] = finalized
кросивое...

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +		return
можно на else if заменить

2021-09-04 06:19 UTC, kcalbCube commented on code/game/objects/structures/artstuff.dm
> +	if(!wip_detail_added && used)
```suggestion
	if(wip_detail_added && !used)
		return
```

2021-09-04 06:21 UTC, kcalbCube commented
поразительно, как легко заставить комьюнити оникса писать кипятком.

2021-09-04 06:24 UTC, kcalbCube commented
если развивать идею то можно и граффити подобным образом раздуть. надо пиликать черномазого

2021-09-04 07:48 UTC, Doster-d commented
Май код из бриллиант энд ю ар блокед он гитхаб организейшион.

2021-09-04 07:48 UTC, Doster-d commented
:-)

2021-09-04 07:50 UTC, Doster-d commented
> кодстайл был пьян

Весь кодстайл, который считается критический находится в аддитионал чекс, по другому - твои изменения не нужоны.

2021-09-04 07:52 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +	if(!wip_detail_added && used)
Ты видимо не понимаешь концепцию "лестницы".
Если бы у меня было вот такое, то ты мог бы меня облить говной.
```
if(statement1)
    if(statement2)
        if(statement3)
```

2021-09-06 00:32 UTC, kcalbCube commented
> Май код из бриллиант энд ю ар блокед он гитхаб организейшион.

ит волд би гуд иф ит вэс

2021-09-06 00:33 UTC, kcalbCube reviewed
а зачем ебаться с пиксель_x пиксель_y? что это дает кроме геморроя?

2021-09-06 00:35 UTC, kcalbCube commented
> > кодстайл был пьян
> 
> Весь кодстайл, который считается критический находится в аддитионал чекс, по другому - твои изменения не нужоны.

ты меня за отсутствие пробелов в комментариях пиздил, а теперь сам отказываешься править.
а лесенка вроде даже в гайд ту контрибутинг запрещена

2021-09-06 06:58 UTC, Doster-d commented
> ты меня за отсутствие пробелов в комментариях пиздил, а теперь сам отказываешься править.

Я тебя пиздил за это потому что это было в проверках, эту проверку убрали, да и вообще иди нахуй, пес.

> а лесенка вроде даже в гайд ту контрибутинг запрещена

Ты хуй, посмотри, что там написано, хуесос перед тем как что-то писать, где у меня уровень вложения 3 и более? Ты хуесосина, если не знаешь, не пизди, эксперт по хуям в жопу.

2021-09-06 07:05 UTC, Doster-d commented
Да и многоуровневые строится из много и уровнневый, много это больше 1.
Ты бы еще на двойные форы выебывался

2021-09-06 07:05 UTC, Doster-d commented
> > Май код из бриллиант энд ю ар блокед он гитхаб организейшион.
> 
> ит волд би гуд иф ит вэс

Сейд зе персонс вху кэнт ин гуд прс

2021-09-06 07:33 UTC, kcalbCube commented
> > > Май код из бриллиант энд ю ар блокед он гитхаб организейшион.
> > 
> > 
> > ит волд би гуд иф ит вэс
> 
> Сейд зе персонс вху кэнт ин гуд прс
> 
> :-)

май прс ис топ оф олл ониксбей прс, ю джаст синк наровли энд кэннот андерстенд зет.

2021-09-06 07:37 UTC, kcalbCube commented
> > ты меня за отсутствие пробелов в комментариях пиздил, а теперь сам отказываешься править.
> 
> Я тебя пиздил за это потому что это было в проверках, эту проверку убрали, да и вообще иди нахуй, пес.
> 
> > а лесенка вроде даже в гайд ту контрибутинг запрещена
> 
> Ты хуй, посмотри, что там написано, хуесос перед тем как что-то писать, где у меня уровень вложения 3 и более? Ты хуесосина, если не знаешь, не пизди, эксперт по хуям в жопу.

ты чё еблан, нахуя ты мыслишь уже той самой знакомой с лысым из бразерс
все эти правила они абстрактные, они создают представление про идеальный код.
любая лишняя вложенность это +1 символ на строку, и -4 символа к пространству для просмотра, редактирования и написания кода.

а по поводу комментариев... ты мне говорил что комментарий урод, что он из детдома с лошадимым рылом, и вообще оникс девелопер, а теперь включаешь заднюю. так не делается

2021-09-06 07:56 UTC, Doster-d commented
> май прс ис топ оф олл ониксбей прс, ю джаст синк наровли энд кэннот андерстенд зет.

Вот абоут юр пр абоут прогресс бар вхер ю форгет абоут сом мобс доезнт хев клиент?

2021-09-06 08:02 UTC, kcalbCube commented
> > май прс ис топ оф олл ониксбей прс, ю джаст синк наровли энд кэннот андерстенд зет.
> 
> Вот абоут юр пр абоут прогресс бар вхер ю форгет абоут сом мобс доезнт хев клиент?

ай хев мейкед зис виз пурпоз оф хайдинг бекдорс

2021-09-06 08:04 UTC, Doster-d commented
> ты чё еблан, нахуя ты мыслишь уже той самой знакомой с лысым из бразерс

Чё? Понял хоть сам что сказал?

> все эти правила они абстрактные, они создают представление про идеальный код.

Ну да, и мой код не нарушает эти правила.

> любая лишняя вложенность это +1 символ на строку, и -4 символа к пространству для просмотра, редактирования и написания кода.

Ты читать умеешь? Где ебать эта хуйня мешает тебе редактировать/просматривать говнокод, если там ебать ВСЕГО ОДНА ВЛОЖЕННОСТЬ НА ИФЕ?!

> а по поводу комментариев... ты мне говорил что комментарий урод, что он из детдома с лошадимым рылом, и вообще оникс девелопер, а теперь включаешь заднюю. так не делается
> 

Ты еблан, мне было бы абсолютно похуй на комментарии, хоть ты бы писал их арабскими символами, если бы это не было бы в провер очках.

Если тебе это не нравится, го энд билд юр гейм оф зе дрим виз гитхаб рулез оф зе дрим.

2021-09-06 08:05 UTC, Doster-d commented
Короче, в пизду это, мы ничего не добьемся.

2021-10-14 20:26 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/137390231-930d2c12-1444-424c-9fb7-b91ff743d3cf.png)
Добавлена возможность прикреплять картины к стене, для этого необходимо использовать tape roll на canvas

2021-10-14 20:28 UTC, DarkHunter7756 commented
> Добавлена возможность прикреплять картины к стене, для этого необходимо использовать tape roll на canvas

Ждем фейковые квадраты алмазной руды на аванпосте 🥴

2021-10-15 10:04 UTC, TermService approved these changes

2021-10-15 10:06 UTC, Doster-d commented
Ой, я обсуждения забыл открыть...

2021-10-15 10:09 UTC, Zert0X commented on code/game/objects/structures/artstuff.dm
> +	if(get_dist(on_wall,user)>1)
adjacent не нужен? Сквозь стекла к стене приклеивать не будет?

2021-10-15 10:11 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +	if(get_dist(on_wall,user)>1)
Ну это я украл с интегралок, там проблем нет.
А как Adjacent поможет?

2021-10-15 10:24 UTC, Zert0X approved these changes
LGTM

2021-10-16 01:04 UTC, merged

2021-10-28 16:39 UTC, 4310V343k commented on code/game/objects/structures/artstuff.dm
> +			canvas_overlay.Add(pixel)
на тг эта хуйня клала сервер...

2021-10-28 16:44 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +			canvas_overlay.Add(pixel)
На ТГ какая-то хуйня с external library, я сделал свою штуку, сервер не кладет, можешь спросить в каналах дискорда.
К тому же это встроенные функции, они не могут лагать (нет)

2021-10-28 18:42 UTC, 4310V343k commented on code/game/objects/structures/artstuff.dm
> +			canvas_overlay.Add(pixel)
Да нет же. На ТГ раньше такая реализация и была, я про неё и говорю.

2021-10-28 19:14 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +			canvas_overlay.Add(pixel)
Ссылку можно на коммит с выпиливанием этой реализации?
Почему-то у нас не падает сервер.