fix(SCP-map): zones fail
ChaoticOnyx/OnyxBay pull request #6492
Opened 2021-09-13 17:28 UTC by No-Tips

Кто-то (me) забыл обновить репу и был не в курсе, что улитка чистил зоны, ну и заодно пару моментов почистил, что заметил, пока допирал, почему у меня кусок карты пропал. Я уже заебал всех с такими прами, но давайте зажмем наши булочки и запушим это в релиз, как мужики.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-13 17:33 UTC, Doster-d approved these changes
Донт нарушай правила разработки, плез.

2021-09-13 17:34 UTC, No-Tips commented
Блинладно, но можно это пропушить в релиз по-быстрее, без вот этих ваших месячных ожиданий?

2021-09-13 17:38 UTC, Doster-d requested changes
something wrong happened, wait for futher reports.

2021-09-13 17:57 UTC, Doster-d submitted a review, later dismissed
Мердж в дев или на ветку ЕОС - на совести мержующего.
Камеры плохо поставлены, но это проблема Фронтира.

2021-09-13 18:16 UTC, No-Tips commented
Хаха, пр в релиз делает брбрбрбрбрбр

2021-09-14 16:22 UTC, TermService submitted a review, later dismissed

2021-09-14 16:23 UTC, TermService commented
(мержить не буду)

2021-09-14 16:54 UTC, No-Tips commented
Всмысле не будешь, мерж!!

2021-09-14 19:24 UTC, Epicus7 commented
ПРы в release ветки могут случайно удалиться после первого же обновления сервера. Не советую.

Заливайте нормально в dev

2021-09-14 19:32 UTC, Doster-d commented
Можно было просто поменять ветку назначения...

2021-09-14 20:06 UTC, Epicus7 commented
Нельзя же, вроде? Ну переоткрой, поменяй, если знаешь как. Насколько я знаю нельзя

2021-09-14 20:26 UTC, Doster-d commented
> Нельзя же, вроде? Ну переоткрой, поменяй, если знаешь как. Насколько я знаю нельзя

Нажимаешь Edit и там будет вот это:
![image](https://user-images.githubusercontent.com/63081538/133328869-3c5e7e4b-c160-4a0b-acd8-bc6ae5930dd6.png)

2021-09-14 20:26 UTC, Doster-d submitted a review, later dismissed

2021-09-15 05:26 UTC, TermService submitted a review, later dismissed

2021-09-15 06:58 UTC, No-Tips commented
Ладно, раз уж гуляем в /dev, то замапплю материю вместо синги.

2021-09-16 10:41 UTC, No-Tips commented
Можно реапрувать, полагаю. Материи не будет, мне впадлу и это сложно.

2021-09-16 10:48 UTC, PlinHost submitted a review, later dismissed

2021-09-16 12:39 UTC, Doster-d approved these changes

2021-09-16 12:49 UTC, No-Tips commented
Э бля какие конфликты

2021-09-16 12:50 UTC, Doster-d requested changes
Конфликты.

2021-09-16 13:57 UTC, Doster-d approved these changes

2021-09-17 14:56 UTC, PlinHost approved these changes

2021-09-18 16:41 UTC, merged