temp gun fix
ChaoticOnyx/OnyxBay pull request #6493
Opened 2021-09-13 19:48 UTC by TermService

ишшуй найду позже на неё
<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Температурная пушка снова работает.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-13 21:25 UTC, DarkHunter7756 commented
> ишшуй найду позже на неё

Поиск по гитхабу и каналу фич дал пару результатов
https://github.com/ChaoticOnyx/OnyxBay/issues/1479
https://github.com/ChaoticOnyx/OnyxBay/issues/4566

Ну и твой ПР, закрытый за трупование
https://github.com/ChaoticOnyx/OnyxBay/pull/1795

2021-09-13 21:26 UTC, DarkHunter7756 commented
just my work

2021-09-13 21:57 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +	else if (istype(target, /mob/living/carbon/))
```suggestion
	else if (istype(target, /mob/living/carbon))
```

2021-09-13 21:58 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +	else if(istype(target, /mob/living/carbon/))
```suggestion
	else if(istype(target, /mob/living/carbon))
```

2021-09-14 16:23 UTC, Doster-d requested changes

2021-09-14 16:23 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +	sleep(-1) //Might not be important enough for a sleep(-1) but the sleep/spawn itself is necessary thanks to explosions and metoerhits
Взрывы больше не делают больно, возможно не нужно.

2021-09-14 16:23 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +				if(!M.stat && !istype(M, /mob/living/silicon/ai))\
```suggestion
				if(!M.stat && !istype(M, /mob/living/silicon/ai))
```

2021-09-14 16:23 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +					V.show_message("<span class='warning'>[M] writhes in pain as \his vacuoles boil.</span>", 3, "<span class='warning'>You hear the crunching of leaves.</span>", 2)
Спаны
```suggestion
					V.show_message(SPAN("warning", "[M] writhes in pain as \his vacuoles boil.", 3, SPAN("warning", "You hear the crunching of leaves.", 2)
```

2021-09-14 16:23 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +				M.show_message("<span class='danger'>The radiation beam singes you!</span>")
Спаны

2021-09-14 16:23 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +		M.show_message("<span class='notice'>The radiation beam dissipates harmlessly through your body.</span>")
Спаны.

2021-09-14 16:23 UTC, Doster-d commented on code/modules/projectiles/projectile/special.dm
> +		M.show_message("<span class='notice'>The radiation beam dissipates harmlessly through your body.</span>")
Спаны.

2021-09-14 16:27 UTC, Doster-d approved these changes
Компилиться и норм :)

2021-09-14 16:28 UTC, DarkHunter7756 commented
[Нейм разраба] херни не сделает

2021-09-14 16:32 UTC, Doster-d approved these changes

2021-09-15 15:41 UTC, Zert0X approved these changes
Ну оно должно работать

2021-09-15 16:25 UTC, igorsaux approved these changes
температуру меняет - людей убивает

2021-09-15 18:41 UTC, merged