Улучшение баррикад
ChaoticOnyx/OnyxBay pull request #6496
Opened 2021-09-14 11:25 UTC by Gr13v0us

Теперь баррикады имеют звук атаки, анимацию и сообщение в чат об атаке

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Баррикады теперь имеют звук, анимацию и сообщение в чат
/🆑
```

</details>

close #5211

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-14 11:28 UTC, hard-res3t commented
Мне казалось его уже чинили, но ладно. 😵‍💫

2021-09-14 11:36 UTC, Gr13v0us commented
> Мне казалось его уже чинили, но ладно.

Не, не чинили, только что проверял в игре - ни звука, ни сообщения, ни анимации

2021-09-16 06:00 UTC, kcalbCube requested changes
линт умер

2021-09-16 07:11 UTC, Gr13v0us commented on code/game/machinery/deployable.dm
> +				playsound(src, 'sound/effects/metalhit2.ogg', rand(50,75), 1, -1)
И так все нормально работает

2021-09-16 07:15 UTC, No-Tips commented on code/game/machinery/deployable.dm
> +				playsound(src, 'sound/effects/metalhit2.ogg', rand(50,75), 1, -1)
Работает, но кодстайл нужно соблюдать.

2021-09-16 08:13 UTC, Gr13v0us commented on code/game/machinery/deployable.dm
> +				playsound(src, 'sound/effects/metalhit2.ogg', rand(50,75), 1, -1)
Хорошо

2021-09-16 08:27 UTC, Gr13v0us commented
Готово

2021-09-16 11:44 UTC, kcalbCube approved these changes
Однострочники и в африке они, так что похую.

2021-09-16 13:38 UTC, Doster-d approved these changes

2021-10-01 19:41 UTC, TermService approved these changes

2021-10-01 19:42 UTC, merged