fix(alien): tackle and leap cannot be used onself more
ChaoticOnyx/OnyxBay pull request #6549
Opened 2021-09-21 20:49 UTC by O0oMaximo0O

Разбил способки на две части для их корректной обработки Бьондом.
Теперь способности "Удар хвостом"(или как оно переводится вообще?)  и "Прыжок" не могут быть использованы на себе.

Пока что плевок можно использовать на себе по клику мыши. Если не нужно - пишите в комментариях, запрещу и его.

close #6159

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Leap алиена больше не может разгонять его в космосе
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-21 21:56 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Мех, как-то громоздко, может так?

```suggestion
		to_chat(src, SPAN("warning", "You must be closer to target for leap!"))
```

2021-09-21 21:58 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Тогда наверно leaping... В меру моего скромного понимания

2021-09-21 22:01 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Нв инговая же ставится, когда действие совершается, а тут просто действие, сомнительно.

2021-09-21 22:04 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Ну, яндекс переводит и то, и то верно. В отличие от первоначального варианта, когда он считает Leap существительным. Впрочем, это слово отдельно считая исключительно глаголом))). "Ближе к прыжку надо быть!"

2021-09-21 22:05 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
А инговая форма тут будет выражать существительное. В моём варианте "Ближе, чтобы прыгнуть", у тебя "Ближе к цели для прыжка"

2021-09-21 22:07 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Ну я и об этом, как-то коряво на мой взгляд, не понятно к чему ближе.

2021-09-21 22:09 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Ну так ты же кликнул или выбрал что-то, так что должен знать. Ладно, поменяю. Особо разницы нет. Но с -ing.

2021-09-21 22:11 UTC, igorsaux commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
лол зачем for добавлять если до этого нормально было

2021-09-21 22:14 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
Может ещё ревьювните, раз уж зашли? ))

2021-09-21 22:17 UTC, igorsaux commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
тогда уж и про артикль не забываем `You must be closer to the target to leap!`

2021-09-21 22:18 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You must be closer to leap!"))
О, вот с этим у меня беда, спасибо.

2021-09-22 11:11 UTC, TermService approved these changes

2021-09-22 11:32 UTC, igorsaux approved these changes

2021-09-22 11:58 UTC, Doster-d requested changes

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/target
```suggestion
	var/mob/living/target
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/list/targets = list()
```suggestion
	var/list/mob/living/targets = list()
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	for(var/mob/living/M in view(1, src))
```suggestion
	for(var/mob/living/M in oview(1, src))
```
oview автоматически исключает src

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/target
```suggestion
	var/mob/living/target
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	var/list/targets = list()
```suggestion
	var/list/mob/living/targets = list()
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +/mob/living/carbon/human/proc/process_leap(mob/living/T = null)
```suggestion
/mob/living/carbon/human/proc/process_leap(mob/living/T)
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +/mob/living/carbon/human/proc/process_tackle(mob/living/T = null)
```suggestion
/mob/living/carbon/human/proc/process_tackle(mob/living/T)
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
> +	var/target
```suggestion
	var/mob/living/target
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
> +	var/list/targets = list()
```suggestion
	var/list/mob/living/targets = list()
```

2021-09-22 11:58 UTC, Doster-d commented on code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
> +/mob/living/carbon/human/proc/process_spit(mob/T = null)
```suggestion
/mob/living/carbon/human/proc/process_spit(mob/T)
```

2021-09-22 12:24 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	for(var/mob/living/M in view(1, src))
А если Чужой будет бить по лежащему, стоя сверху, тот будет доступен? Правда такл всё равно врядли кто-то будет юзать из панели, когда враг у тебя под носом.

2021-09-22 18:07 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	for(var/mob/living/M in view(1, src))
Ну да, я думаю, что исключит только src

2021-09-22 18:10 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +	for(var/mob/living/M in view(1, src))
Ладно, поверю.

2021-09-24 11:56 UTC, Doster-d approved these changes

2021-09-24 12:28 UTC, TermService approved these changes

2021-09-24 12:29 UTC, merged