Revert "feat(ui emotes): Add emote list on interface"
ChaoticOnyx/OnyxBay pull request #6555
Opened 2021-09-22 09:29 UTC by igorsaux

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscdel: Удалена emote panel.
/🆑
```

</details>

2021-09-22 10:17 UTC, DarkHunter7756 commented
Ти шо творишь, сие баги можно пофиксить, либо попросту убрать команды из пула эмоутов панели. Давай тогда билд удалим, он же создает баги -_-

2021-09-22 10:17 UTC, igorsaux commented
> Ти шо творишь, сие баги можно пофиксить, либо попросту убрать команды из пула эмоутов панели. Давай тогда билд удалим, он же создает баги -_-

вперёд всё в твоих руках

2021-09-22 10:33 UTC, TobyThorne approved these changes

2021-09-22 10:35 UTC, DarkHunter7756 commented
>вперёд всё в твоих руках

Зачем тут мои руки, когда все сделали за нас уже давно? ;) #2758

2021-09-22 10:54 UTC, TermService requested changes, later dismissed
Hold on

2021-09-22 14:16 UTC, kcalbCube commented
всеми гранями за. эта хуйня абсолютна лишняя, да ещё и багов понаделала.

2021-09-22 14:27 UTC, TermService commented
Галя отмена

2021-09-22 14:28 UTC, TobyThorne commented
Галя отмена("Галя отмена")

2021-10-03 23:43 UTC, HonkyDonky approved these changes
Автор не спешит починить своё детище, что породило кучу довольно неприятных багов. Я всеми ножками за реверт.

2021-10-03 23:47 UTC, DarkHunter7756 commented
> Автор не спешит починить своё детище, что породило кучу довольно неприятных багов. Я всеми ножками за реверт.

Баги не критичны. Билд стабильно работает. Можно и подождать. Нововведение весьма удобно и позволяет без макросов эмоутить, как умалишённый

2021-10-04 00:02 UTC, HonkyDonky commented
> Баги не критичны

Парочка вирусов не работает, неприятна. 

> Билд стабильно работает. Можно и подождать

Так можно про большинство багов сказать.

> Нововведение весьма удобно

Очень удобно открывать другую вкладку и искать в ней нужный тебе эмоут, в то время когда ты можешь его просто замакросить или же написать сам.

2021-10-04 00:14 UTC, DarkHunter7756 commented
> Парочка вирусов не работает, неприятна.

Про это забыл. Но просто не понимаю смысла ревертать, когда там по фактам только пару букв изменить, чтобы эмоуты не перекрывали команды и т.д.

> Очень удобно открывать другую вкладку и искать в ней нужный тебе эмоут, в то время когда ты можешь его просто замакросить или же написать сам.

Написать долго, макросы делать запарно, к тому же они вайпаются, если заходить не с англ. раскладкой.

Но тут решаете вы, а не я.

2021-10-04 10:09 UTC, O0oMaximo0O commented
А разве ПР фиксов уже не сделан? Он же только ревью ждёт.

А, там stale.

2021-10-05 08:08 UTC, Doster-d commented
> А разве ПР фиксов уже не сделан? Он же только ревью ждёт.
> 
> А, там stale.
> 

Потому что ты не фиксишь, тебе все написали.

2021-10-05 08:08 UTC, Doster-d approved these changes

2021-10-05 09:18 UTC, O0oMaximo0O commented
> Потому что ты не фиксишь, тебе все написали.

Это ПР Оуби, вообще-то).

2021-10-09 05:53 UTC, ghost commented
@TermService 
Снимай ченджреквест. Оуби трупанулся две недели назад и не желает фиксить своё чудо.
Если ему так захочется его вернуть - он сделает ПР с исправленной версией, когда-нибудь.

2021-10-09 11:56 UTC, Oubifx commented
В целом да, молодой человек всё верно говорит. У меня сейчас нет желания и времени на ониксбей, как и у других нет желания что-то делать в чужом коде в КОМАНДНОЙ разработке.

2021-10-11 19:20 UTC, ghost commented
> как и у других нет желания что-то делать в чужом коде в КОМАНДНОЙ разработке

Звучит так, словно другие разработчики здесь обязаны чинить чужой код. Ладно если бы кому-то захотелось исправить твою эмоут панель, а так... А так только реверт, ибо баги заметные и неприятные, которым уже три недели где-то.

2021-10-12 21:02 UTC, Oubifx commented
> Звучит так, словно другие разработчики здесь обязаны чинить чужой код.

Я это говорил не про пример к своему коду, хотя при желании можно было бы и фиксануть, учитывая что есть люди которым эта штука нужна и то что я сейчас не могу этим заниматься. В таких проектах так то ни кто никому не обязан. 
Я тут больше про то что в **ChaoticOnyx/OnyxBay** все делают что-то своё, сольное, прикасаясь к чужому коду только если это пиздец какое древнее говно мамонта которое внезапно прилипло к ноге и не даёт двигаться дальше. 
Помимо того что гит служит для контроля версий, так он еще оказывается подразумевает что это сервис для совместной разработки (работа над одними и теми же частями кода). Для этого собственно комменты в коде и пишут, что бы П1 мог разобраться/обратить внимание на определенные места в коде П2 и тому подобное. В другом репозитории, другой игры, мы так и делаем, правда там разработку ведет человека 4 всего, но там и цели другие. Не реализация собственных амбиций, а реализация качественного проекта.
В общем да, что-то в сторону меня понесло.

2021-10-12 21:06 UTC, kreeperHLC commented
> > Звучит так, словно другие разработчики здесь обязаны чинить чужой код.
> 
> Я это говорил не про пример к своему коду, хотя при желании можно было бы и фиксануть, учитывая что есть люди которым эта штука нужна и то что я сейчас не могу этим заниматься. В таких проектах так то ни кто никому не обязан. Я тут больше про то что в **ChaoticOnyx/OnyxBay** все делают что-то своё, сольное, прикасаясь к чужому коду только если это пиздец какое древнее говно мамонта которое внезапно прилипло к ноге и не даёт двигаться дальше. Помимо того что гит служит для контроля версий, так он еще оказывается подразумевает что это сервис для совместной разработки (работа над одними и теми же частями кода). Для этого собственно комменты в коде и пишут, что бы П1 мог разобраться/обратить внимание на определенные места в коде П2 и тому подобное. В другом репозитории, другой игры, мы так и делаем, правда там разработку ведет человека 4 всего, но там и цели другие. Не реализация собственных амбиций, а реализация качественного проекта. В общем да, что-то в сторону меня понесло.

Ты не сказал что сейчас у тебя нет возможности пофиксить панельку. Ты сказал что у тебя нет желания фиксить то, что ты залил в игру. Все бы поняли, если бы ты попросил кого-то другого починить код, так что сейчас ты выглядишь ЧСВ чувак, который запилил фичу и ушел просто потому что ему надоело.

2021-10-12 21:30 UTC, Oubifx commented
> Ты не сказал что сейчас у тебя нет возможности пофиксить панельку. Ты сказал что у тебя нет желания фиксить то, что ты залил в игру. 

Не правда, если было бы правдой, то фикса не было бы. Времени нет ровно с 23-го числа когда я нашел нужную мне работку. Тратить своё свободное время которого у меня стало в разы меньше на SS13 и разработку теперь не хочется, учитывая что командной разработки по факту и нет. Не исключаю варианта что рано или поздно мне снова захочется плотно покодить в СС-ке, жертвую на это всё своё свободное время.
Сам хотфикс исправляющий описанные ранее проблемы существует, мои комментарии по этому поводу здесь.
![image](https://user-images.githubusercontent.com/24242919/137030278-1bb66a6e-8217-4994-9015-9ae307bf83b7.png)
![image](https://user-images.githubusercontent.com/24242919/137029854-4a3457f8-8cd6-4e58-a0d9-10c21ffcd174.png)

> Все бы поняли, если бы ты попросил кого-то другого починить код, так что сейчас ты выглядишь ЧСВ чувак, который запилил фичу и ушел просто потому что ему надоело.

Нахуя мне грузить кого-то? Я таким не занимаюсь и навязываться никому не собираюсь. Если другой человек видит что эта фича нужна определенной части игрокам, но по каким либо причинам багфиксом никто не занимается, то в чём проблема заняться этим? Естественно проще ебануть реверт, не в обиду igorsaux. Про ЧСВ вообще смешно.

2021-10-12 21:50 UTC, Doster-d commented
Блин, я оказывается мог просто сказать "Пошли вы все нахуй, нихуя не буду делать, я устал, я мухожук" и не поддерживать интегралки все эти 8 месяцов... Вот я дурак!

2021-10-14 01:00 UTC, merged

2021-10-14 08:02 UTC, Zert0X commented
вы потеряли #6469