fix(emote-panel): collapse and vomit fixes
ChaoticOnyx/OnyxBay pull request #6556
Opened 2021-09-22 14:02 UTC by Oubifx

Вернул *collapse, теперь всё работает как и должно.
При использовании *vomit синтами теперь не будет страшного текста с упоминанием *help.

close #6555
fix #6545
fix #6552
fix #6553

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
bugfix: Фиксы эмоут-панели
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-22 14:04 UTC, igorsaux requested changes
осталось с #6469 разобраться и можно мержить, верб пинг в OOC я бы поменял на `Server Ping`

2021-09-22 14:05 UTC, Oubifx commented
> осталось с #6469 разобраться и можно мержить, название верба пинг в OOC я бы поменял на `Server Ping`

Милости прошу, меняй. К эмоут-панели это никаким боком не относится.

2021-09-22 14:06 UTC, igorsaux commented
тогда название эмоута, в любом случае одно из них надо назвать иначе

2021-09-22 17:48 UTC, TermService requested changes

2021-09-22 17:48 UTC, TermService commented on code/modules/emotes/emotes_verb.dm
> +		usr.emote("vomit")
а приводить к типу кто буит

2021-09-22 19:38 UTC, Oubifx commented on code/modules/emotes/emotes_verb.dm
> +		usr.emote("vomit")
не понял о чём ты, давай лучше кодом

2021-09-22 19:41 UTC, Doster-d commented on code/modules/emotes/emotes_verb.dm
> +		usr.emote("vomit")
```
var/mob/user = usr; ASSERT(user)
```

2021-09-22 19:51 UTC, igorsaux requested changes
как раз тут и проебал проверку на приведение типа

2021-09-22 19:51 UTC, igorsaux commented on code/modules/emotes/emotes_verb.dm
> +	var/mob/living/carbon/human/H = src
```suggestion
	var/mob/living/L = src
```

2021-09-22 19:51 UTC, igorsaux commented on code/modules/emotes/emotes_verb.dm
> +	if(H.isSynthetic())
```suggestion
	if(L?.isSynthetic())
```

2021-09-22 19:53 UTC, igorsaux commented on code/modules/emotes/emotes_verb.dm
> +	if(H.isSynthetic())
```suggestion
	if(istype(H) && H.isSynthetic())
```
во

2021-09-23 03:34 UTC, kcalbCube reviewed
а зачем везде используется работающий usr, вместо прямого src? у меня такой вопросик.

2021-09-23 03:49 UTC, kcalbCube commented
> > осталось с #6469 разобраться и можно мержить, название верба пинг в OOC я бы поменял на `Server Ping`
> 
> Милости прошу, меняй. К эмоут-панели это никаким боком не относится.

эти иссуй вотчеры совсем ебнулись

ты ничего не делал со своей панелью, пока тебе носом не ткнули, на коленке закодил фикс пары багов об которые тебе накинули, наплевав на #6469, который ты даже не понял, пытаясь доказать что это не баг какой-то хуйнёй из кода, которой багрепортили ДВАЖДЫ, и даже когда тебе разработчик напрямую сказал что-то сделать, ты говоришь "делай это сам, меня не ебёт."
я к новичкам отношусь положительно, но только не когда они себя ведут по блядски. удачного дня.

2021-09-23 03:50 UTC, Doster-d commented on code/modules/emotes/emotes_verb.dm
> +		usr.emote("vomit")
```suggestion
		var/mob/user = usr
		ASSERT(user)
		user.emote("vomit")
```

2021-09-23 03:52 UTC, kcalbCube commented on code/modules/emotes/emotes_verb.dm
> +		usr.emote("vomit")
везде просто usr.emote("vomit")

2021-09-23 03:52 UTC, Doster-d commented
usr в вербах - не магия, а вот в proc это магия.

2021-09-23 03:53 UTC, kcalbCube commented
> usr в вербах - не магия, а вот в proc это магия.

а в чём принципиальная разница когда src и usr совпадают?

2021-09-23 03:56 UTC, Doster-d commented
> а в чём принципиальная разница когда src и usr совпадают?

По обсуждениям - usr в проках может достать и клиента, и моба, а может какую-то иную хрень достать, потому что это черный ящик.

2021-09-23 03:57 UTC, kcalbCube commented
> > а в чём принципиальная разница когда src и usr совпадают?
> 
> По обсуждениям - usr в проках может достать и клиента, и моба, а может какую-то иную хрень достать, потому что это черный ящик.

значит src безопаснее

2021-09-23 03:58 UTC, kcalbCube commented on code/modules/emotes/emotes_verb.dm
> +	var/mob/living/carbon/human/H = src
а нахуя мы это делаем, если можно прок эмоута в /mob/living

2021-09-23 12:46 UTC, Oubifx commented on code/modules/emotes/emotes_verb.dm
> +	var/mob/living/carbon/human/H = src
> а нахуя мы это делаем, если можно прок эмоута в /mob/living

напиши кодом, моя твоя не понимать

2021-09-23 14:35 UTC, kcalbCube commented on code/modules/emotes/emotes_verb.dm
> +	var/mob/living/carbon/human/H = src
сожалею.

2021-10-14 01:02 UTC, TobyThorne commented
Конфликты обнаружены, живой автор не обнаружен.

2021-10-14 01:02 UTC, closed without merging