fix(library): corrected book show message
ChaoticOnyx/OnyxBay pull request #6566
Opened 2021-09-24 11:20 UTC by O0oMaximo0O

При показе книги сообщения пользователю и остальным были перепутаны.
Теперь нет.
Также заменил спаны в затронутом файле макросом.

close #2888

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь при показе книги другому человеку сообщение в чат правильное.
/🆑
```

</details>

Не тестировал, но в данном случае не думаю, что это нужно. Просто поменял порядок аргументов.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-09-24 11:25 UTC, TermService commented
ПР не совпадает с задачей в ишшуе

2021-09-24 11:27 UTC, O0oMaximo0O commented
Хм. Поменять на показ юзеру и тому, кому он показывает?

2021-09-24 11:28 UTC, O0oMaximo0O commented
Думаю что сообщение всё-таки не только самому юзеру должно идти

2021-09-24 11:30 UTC, kreeperHLC approved these changes

2021-09-24 13:11 UTC, kreeperHLC requested changes
Дед не заметил что за прок там стоит. А тебе стоит прожать F12 в VSC, чтобы понять, что там не этот прок должен стоять

2021-10-06 11:49 UTC, O0oMaximo0O commented
Эм, не понял. Ты о visible_message()?

2021-10-10 15:04 UTC, TermService approved these changes

2021-10-10 15:05 UTC, kreeperHLC approved these changes

2021-10-14 00:06 UTC, merged