fix(metroid): metroid's attack_hand() now picks mob's unarmed attack
ChaoticOnyx/OnyxBay pull request #6583
Opened 2021-09-26 10:07 UTC by O0oMaximo0O

Исправлена невозможность убить метроида brute уроном.
Спаны в файле заменены макросом.
Исправлена работа способности Leap с метроидами. Теперь она грабает только хуманов и их подтипы.

close #5496 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь Чужие могут убить метроидов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-01 19:37 UTC, TermService submitted a review, later dismissed

2021-10-01 19:39 UTC, igorsaux requested changes

2021-10-01 19:39 UTC, igorsaux commented on code/modules/mob/living/carbon/xenobiological/xenobiological.dm
> +			var/mob/living/carbon/human/H = M
а зачем вторую одинаковую переменную создавать?

2021-10-02 02:19 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/xenobiological/xenobiological.dm
> +			var/mob/living/carbon/human/H = M
Хм, и правда. Я просто эти строчки из человеческого attack_hand() украл. Уберу наверно и на М всё заменю.

2021-11-08 00:01 UTC, TobyThorne commented
хотел накинуть стали пру, а уже месяц как висит
ещё и камфликт образовался

2022-04-20 16:55 UTC, O0oMaximo0O commented
Ой.
А я и не заметил о-о.

2022-04-20 16:55 UTC, O0oMaximo0O commented
Ой.
А я и не заметил о-о.

2022-04-20 17:04 UTC, O0oMaximo0O commented
На что линтер матерится? о-о
Где он в первых строка `as` вообще нашёл

2022-04-20 17:05 UTC, O0oMaximo0O commented
На что линтер матерится? о-о
Где он в первых строках `as` вообще нашёл

2022-04-20 20:07 UTC, TermService commented
прост убери остальные as и все будет ок

2022-05-02 19:21 UTC, igorsaux approved these changes
терм сказал что будет ок

2022-05-07 19:37 UTC, TermService approved these changes

2022-05-07 19:37 UTC, merged