fix(megaphone): megaphone works loud
ChaoticOnyx/OnyxBay pull request #6623
Opened 2021-10-01 21:10 UTC by TermService

close: #5928

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Мегафон работает как задумано.
/🆑
```

</details>

![dreamseeker_xf3IzwPoD2](https://user-images.githubusercontent.com/18397924/135686437-ce529333-d880-4eab-af4e-0a98e0b6dbec.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-01 21:11 UTC, igorsaux commented on code/game/objects/items/devices/megaphone.dm
> +				O.show_message("<B>[user]</B> broadcasts, <font size=6>\"[message]\"</font>", AUDIBLE_MESSAGE)
размер текста меняется вместе с изменением размера шрифта в чате?

2021-10-01 21:14 UTC, TermService commented on code/game/objects/items/devices/megaphone.dm
> +				O.show_message("<B>[user]</B> broadcasts, <font size=6>\"[message]\"</font>", AUDIBLE_MESSAGE)
на скрине 21px как видишь работает

2021-10-01 21:17 UTC, igorsaux requested changes
![image](https://user-images.githubusercontent.com/55196698/135687148-c447b2f5-9bf5-4716-a4f0-39a1dd032599.png)
![image](https://user-images.githubusercontent.com/55196698/135687201-b934186d-5c05-41e8-850a-fa59c235f837.png)
не меняется

2021-10-03 10:56 UTC, Doster-d commented on code/game/objects/items/devices/megaphone.dm
> +				O.show_message("<B>[user]</B> broadcasts, <font size=6>\"[message]\"</font>", AUDIBLE_MESSAGE)
```suggestion
				O.show_message("<B>[user]</B> broadcasts, [FONT_GIANT("[message]")]", AUDIBLE_MESSAGE)
```
Мб это сработает.

2021-10-08 15:53 UTC, TermService commented on code/game/objects/items/devices/megaphone.dm
> +					O.show_message("<B>[user]</B> broadcasts, <font size=6>\"[pick(insultmsg)]\"</font>", AUDIBLE_MESSAGE)
```suggestion
					O.show_message("<B>[user]</B> broadcasts, [FONT_GIANT("[pick(insultmsg)]", AUDIBLE_MESSAGE)
```

2021-10-08 15:53 UTC, TermService commented on code/game/objects/items/devices/megaphone.dm
> +				to_chat(user, SPAN_NOTICE("*BZZZZzzzzzt*"))
```suggestion
				to_chat(user, SPAN_WARNING("*BZZZZzzzzzt*"))
```

2021-10-08 16:16 UTC, igorsaux approved these changes

2021-10-08 17:05 UTC, kreeperHLC approved these changes

2021-10-08 18:46 UTC, merged