Revert "fix(solar): a solar panel generates energy"
ChaoticOnyx/OnyxBay pull request #6653
Opened 2021-10-04 23:18 UTC by igorsaux

Возвращаем более оптимальный вариант работы солнечных панелей.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-04 23:37 UTC, Epicus7 requested changes
Можно словами описать суть предлагаемых изменений? Вам с Термом весело, конечно, наверное, туда сюда рандомные изменения вносить/выносить, но хотя бы для будущих поколений.

Еще было бы неплохо иссуи прикрепить и чейнжлог.

2021-10-04 23:47 UTC, igorsaux commented
> Можно словами описать суть предлагаемых изменений? Вам с Термом весело, конечно, наверное, туда сюда рандомные изменения вносить/выносить, но хотя бы для будущих поколений.
> 
> Еще было бы неплохо иссуи прикрепить и чейнжлог.

Какие иссуи и зачем ЭТО пихать в чейнджлог?
А чтобы понять суть и зачем эти изменения - достаточно открыть код:
![image](https://user-images.githubusercontent.com/55196698/135938713-1b325a55-1fb0-49c4-9137-246bec173441.png)
Всё очень самодокументировано и даже комментарии излишне.
Разве что стоит добавлю ссылку на оригинальный ПР (где также если посмотреть на изменения - то можно увидеть что это выполненный TODO, который оставили бейцы)
`//TODO: remove/add this from machines to save on processing as needed ~Carn PRIORITY`

2021-10-04 23:51 UTC, igorsaux commented
Для будущих поколении должно быть достаточно.

2021-10-04 23:56 UTC, Epicus7 approved these changes

2021-10-05 06:32 UTC, Doster-d approved these changes

2021-10-07 19:50 UTC, merged