refactoring(xenoarcheaology): artefact.dm and dependent files.
ChaoticOnyx/OnyxBay pull request #6661
Opened 2021-10-06 11:08 UTC by O0oMaximo0O

Рефакторинг. Поменял на битовые флаги типы триггеров и эффектов, где смог - переписал функции. В паре мест дописал проверку эффекта на его активацию.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-06 11:09 UTC, O0oMaximo0O commented
Прошу советов по коду и способам протестировать, что всё работает. Я не особо играл за археолога.

2021-10-06 11:25 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  		if(W.reagents.has_reagent(/datum/reagent/hydrazine, 1) || W.reagents.has_reagent(/datum/reagent/water, 1))
Кажется здесь цепочку if-else следует разделить на отдельные if-ы. Иначе смесь из кислоты и воды не активирует артефакт с триггером по кислоте. И т.д.

2021-10-06 11:28 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/tools/artifact_harvester.dm
> +	//connect to a nearby scanner pad
Так, а это конфликтик. Заменю назад.

2021-10-06 11:29 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
> +		secondary_effect.ToggleActivate(INVISIBLE_TOGGLE)
Здесь правильно только для включения, и то артефакт будет мигать. Заменю.

2021-10-06 12:04 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  		if(W.reagents.has_reagent(/datum/reagent/hydrazine, 1) || W.reagents.has_reagent(/datum/reagent/water, 1))
Разделил.

2021-10-06 21:01 UTC, igorsaux commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGER_LIGHT       0x4000
почему не через `<<`

2021-10-06 21:01 UTC, O0oMaximo0O commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGER_LIGHT       0x4000
Потому что не подумал. Поменять?

2021-10-06 21:03 UTC, igorsaux commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGER_LIGHT       0x4000
https://github.com/ChaoticOnyx/OnyxBay/blob/9048c723249cdb17d10c8276090c0c40f005b323/code/__defines/damage_organs.dm#L34-L44

2021-10-06 21:04 UTC, O0oMaximo0O commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGER_LIGHT       0x4000
Ок

2021-10-07 17:49 UTC, igorsaux commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGERS_COUNT      15
оно нигде не используется

2021-10-08 12:42 UTC, O0oMaximo0O commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGERS_COUNT      15
Уберу, как и EFFECTS_COUNT.

2021-10-09 20:30 UTC, kreeperHLC commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGERS_COUNT      15
Так и не убрал

2021-10-09 20:32 UTC, O0oMaximo0O commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGERS_COUNT      15
Ладно, ща О_О. Но лучше бы что-то по функционалу сказали.

2021-10-09 20:39 UTC, O0oMaximo0O commented on code/__defines/xenoarcheaology.dm
> +#define TRIGGERS_COUNT      15
Убрал

2021-10-10 15:15 UTC, kreeperHLC requested changes

2021-10-10 15:15 UTC, kreeperHLC commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
: надо зарефакторить. Оно отвратительно.

2021-10-16 13:29 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
Стоит ли оно разбития if-ов на ещё несколько и раздувания присвоением?

2021-10-16 13:30 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
Я попробовал переделать, но мне не понравилось.

2021-10-17 10:20 UTC, kreeperHLC commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
Тебе W надо всего лишь привести к нужному типу чтобы проки работали, всё.

2021-10-17 10:20 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
Я понимаю, но это раздувает код.

2021-10-17 10:22 UTC, kreeperHLC commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
Раздутый, но читаемый код против компактного, но не особо читабельного и работающего? Я думаю, что первое таки побеждает

2021-10-17 10:23 UTC, O0oMaximo0O commented on code/modules/xenoarcheaology/artifacts/artifact.dm
>  			isWelder(W) && W:welding)
Насчёт не особо работающего поспорю.

2021-11-02 15:04 UTC, kreeperHLC approved these changes

2021-11-29 20:11 UTC, Doster-d approved these changes
![image](https://user-images.githubusercontent.com/63081538/143935852-e1195d55-3c8e-488f-a80d-9cbc7629d712.png)

2021-12-13 22:28 UTC, TobyThorne commented
Ничего не чекал, доверюсь чудоревуверам с зелёными галочками 
![image](https://user-images.githubusercontent.com/45202681/145899112-af17a1b3-bb91-470c-a856-b6eb76e21ba2.png)

2021-12-13 22:29 UTC, merged

2021-12-13 22:44 UTC, O0oMaximo0O commented
Ну, я всегда готов исправить свои баги, если что)