bugfix: Дюп кабеля при разборке шлюзов
ChaoticOnyx/OnyxBay pull request #6738
Opened 2021-10-16 21:47 UTC by Artemonim

close #4329

<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Дюп кабеля при разборке шлюзов
/🆑
```

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-11-04 14:50 UTC, Doster-d submitted a review, later dismissed

2021-12-10 16:36 UTC, TobyThorne requested changes
4 секунды кулдауна на клик? не-не-не, такой реализацией дела не делаются

2021-12-20 20:52 UTC, PlinHost reviewed
Я тут вижу много аналогичных `do_after` без каких-либо проверок, нужно убедиться, что там нет такой же проблемы. Алсо, в файле куча бессмысленных проверок `!src`, их бы заменить на `!QDELING(src)` или удалить, если не нужны.

2021-12-20 20:52 UTC, PlinHost commented on code/game/objects/structures/door_assembly.dm
> +	var/cooldown_time = 40
Сюда бы `const` и можно еще `static`.

2021-12-21 09:41 UTC, Artemonim commented
> их бы заменить на !QDELING(src)

Как минимум перестаёт работать мой фикс дюпа.

2022-01-03 15:52 UTC, Doster-d requested changes

2022-01-03 15:52 UTC, Doster-d commented on code/game/objects/structures/door_assembly.dm
> +			if(src.state == 1)
```suggestion
			if(state == 1)
```

2022-01-03 15:52 UTC, Doster-d commented on code/game/objects/structures/door_assembly.dm
> +				src.state = 0
```suggestion
				state = 0
```

2022-01-03 15:54 UTC, Doster-d commented on code/game/objects/structures/door_assembly.dm
> +				src.state = 0
Обновил, на кринж чет не обратил внимание

2022-01-03 15:54 UTC, Doster-d commented on code/game/objects/structures/door_assembly.dm
> +			if(src.state == 1)
Обновил, на кринж чет не обратил внимание

2022-01-22 03:58 UTC, HonkyDonky reviewed
Ничего не понял из того, что тут изменили и как исправили. Почему нельзя просто использовать переменную `in_use` во время работы с шлюзом, не давая тем самым её закликать?

2022-03-16 01:14 UTC, HonkyDonky commented
Автор погиб на Донбассе, так и не сумев ответить на мой вопрос, адресованный ему двадцать второго января. Да и фикс выглядит ни о чём. Закрою, пожалуй.

2022-03-16 01:14 UTC, closed without merging