Запрет на открытие дверей симплмобами
ChaoticOnyx/OnyxBay pull request #6739
Opened 2021-10-16 21:51 UTC by Artemonim

close #2603

<summary>Чейнджлог</summary>

```yml
🆑
tweak: Неразумные существа теперь не могут открывать двери
/🆑
```

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-16 22:01 UTC, Doster-d commented on code/game/jobs/access.dm
> +		return 0
```suggestion
		return FALSE
```

2021-10-16 22:52 UTC, DarkHunter7756 commented
А можно спросить зачем этот ПР? Двери работают на автоматическом открытии. **Двери в коридоре** не требуют доступа. Следовательно они открываются каждому встречному, как авто-двери из типичных супермаркетов.

2021-10-16 22:54 UTC, MaxTheAstronaut commented
Корова сбежала из умного коровника, подойдя к двери.

2021-10-16 23:26 UTC, Artemonim commented
> А можно спросить зачем этот ПР?

Иссуй есть. Иссуй одобрен. Надо работать

2021-10-17 07:39 UTC, igorsaux submitted a review, later dismissed

2021-10-17 07:40 UTC, TobyThorne commented
Твою ж мать, Родиал нанёс удар прямиком из гроба.

2021-10-17 09:04 UTC, kreeperHLC submitted a review, later dismissed
Эпикус, где пауки? 
![image](https://user-images.githubusercontent.com/14943437/137620061-428f47f0-e6e8-4b82-93bd-d5e4fd6fc4a4.png)

2021-10-19 23:55 UTC, Epicus7 requested changes

2021-10-19 23:55 UTC, Epicus7 commented on code/game/jobs/access.dm
> +		playsound(src.loc, 'sound/machines/buzz-two.ogg', 50, 0)
Выглядит здесь лишним. Это прок проверки доступа, причем тут воспроизведение звука - не очень понятно.

2021-10-29 12:37 UTC, Epicus7 approved these changes
Вообще удалить бы нахрен этот `/obj/proc/allowed`. Непонятно что какая-нибудь ручка кому разрешает, как и большинство других объектов. Если это нужно двери, то и код должен быть в дверях, а не во всех объектах.

2021-12-01 16:52 UTC, Doster-d approved these changes

2022-01-22 03:55 UTC, HonkyDonky approved these changes
Одобренный ПР висит в ожидании мержа уже второй месяц.

2022-01-28 15:53 UTC, merged