Изменение размера и отображения мусора в хранилищах
ChaoticOnyx/OnyxBay pull request #6747
Opened 2021-10-18 13:18 UTC by Artemonim

close #4602

Добавлен прок `/obj/item/proc/update_icon_for_storage()` поворачивающий вещи на 90° при взаимодействии с хранилищами.

![2021-10-21_11-12-58](https://user-images.githubusercontent.com/36363466/138238211-c1965e7d-09dd-4816-befb-889853c1e46a.png)

<summary>Чейнджлог</summary>

```yml
🆑
tweak: Большая часть мусора стала занимать меньше места в инвентаре.
rscadd: Мусор в инвентаре выглядит лучше.
tweak: Тарелки, подносы и противни остаются в руке при складывании в стопку.
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-20 22:41 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +	w_class = ITEM_SIZE_TINY
а может не надо
tiny - это штуки уровня таблеток, сигарет и ручек

2021-10-20 22:45 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +			istype(src, /obj/item/trash/dish/plate) && (length(stack) >= 2) && (src.w_class = ITEM_SIZE_SMALL)
что это вообще должно делать и как это компилируется

2021-10-20 22:47 UTC, TobyThorne requested changes

2021-10-20 22:47 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +			istype(src, /obj/item/trash/dish/plate) && (length(stack) >= 2) && (src.w_class = ITEM_SIZE_SMALL)
понял, что это должно делать, всё ещё не понял, как это компилируется и зачем делать этот ужас

2021-10-20 22:48 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +			istype(src, /obj/item/trash/dish/plate) && (length(stack) >= 2) && (src.w_class = ITEM_SIZE_SMALL)
```suggestion
			if(istype(src, /obj/item/trash/dish/plate) && length(stack) > 1)
				w_class = ITEM_SIZE_SMALL
```

2021-10-21 07:59 UTC, Artemonim commented on code/game/objects/items/trash.dm
> +			istype(src, /obj/item/trash/dish/plate) && (length(stack) >= 2) && (src.w_class = ITEM_SIZE_SMALL)
Это из нашего стильгайда 👀
https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md#краткое-условное-выражение-через-оператор-

2021-10-21 08:13 UTC, Artemonim commented on code/game/objects/items/trash.dm
> +	w_class = ITEM_SIZE_TINY
Если сделать мусор меньше, то уменьшаться случаи, когда игроки просто бросают всё на пол, а не забирают с собой до ближайшей мусорки. Тем, кто итак убирается, тоже будет комфортнее. Да и смотрится неплохо.
![2021-10-21_11-12-58](https://user-images.githubusercontent.com/36363466/138238211-c1965e7d-09dd-4816-befb-889853c1e46a.png)

2021-11-08 00:09 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +	istype(src, /obj/item/trash/dish/plate) && (length(stack) >= 2) && (src.w_class = ITEM_SIZE_TINY)
арряяя опять страшное
надо пуржнуть стильгайд

2021-11-08 00:10 UTC, TobyThorne commented on code/game/objects/items/trash.dm
> +	src.w_class == ITEM_SIZE_TINY && update_icon_for_storage()
го вот эти штуки в update_icon, а из on_enter_storage и on_exit_storage уже его вызывать
копипаста страшно

2021-11-10 08:56 UTC, Artemonim commented
У меня недоступна "Resolve conflicts". Памагити

2021-11-10 09:54 UTC, Zert0X commented
> 
> 
> У меня недоступна "Resolve conflicts". Памагити

Помогаю, запускаешь код и чинишь конфликты

2021-11-18 21:45 UTC, Artemonim commented
JTGMerge не фиксит проблемы

2021-12-13 22:25 UTC, TobyThorne commented
Три недели конфликтов, стали автору.

2021-12-17 00:48 UTC, TobyThorne commented
Три дня стали прошло, отключаем от жизнеобеспечения.
При необходимости автор может переоткрыть.

2021-12-17 06:29 UTC, Artemonim commented
Просил помочь решить конфликты, но вам легче закрыть (* ￣︿￣)

2022-01-03 15:53 UTC, Doster-d commented on code/game/objects/items/trash.dm
>  /obj/item/trash/attack(mob/M as mob, mob/living/user as mob)
В единственном месте ругается, можно пойти на встречную деду линтеру

2022-01-03 15:59 UTC, Artemonim commented on code/game/objects/items/trash.dm
>  /obj/item/trash/attack(mob/M as mob, mob/living/user as mob)
Обновите BYOND
```
DM compiler version 514.1575
loading baystation12.dme
loading interface\skin.dmf
loading dynamic\null-1.dmm
loading dynamic\null-2.dmm
loading dynamic\null-3.dmm
loading exodus-4.dmm
loading exodus-5.dmm
loading dynamic\null-6.dmm
loading exodus-7.dmm
loading derelicts\snowasteroid.dmm
loading derelicts\original\derelict.dmm
loading derelicts\bearcat\bearcat-1.dmm
loading derelicts\bearcat\bearcat-2.dmm
loading derelicts\jungleplanet\jungle_planet.dmm
saving baystation12.dmb (DEBUG mode)
baystation12.dmb - 0 errors, 0 warnings (1/3/22 6:56 pm)```

2022-01-03 16:22 UTC, Doster-d commented on code/game/objects/items/trash.dm
>  /obj/item/trash/attack(mob/M as mob, mob/living/user as mob)
Ты же в курсе, что это просто депрекейтед практика, которая не нужна и ее не замечает компилятор, да?

2022-01-03 16:42 UTC, Artemonim commented on code/game/objects/items/trash.dm
>  /obj/item/trash/attack(mob/M as mob, mob/living/user as mob)
Я ж трейни. Откуда мне про деприкейтеды знать.
Нужно убрать ` as mob`?

2022-01-03 16:42 UTC, Doster-d commented on code/game/objects/items/trash.dm
>  /obj/item/trash/attack(mob/M as mob, mob/living/user as mob)
Да.

2022-01-03 16:43 UTC, Doster-d commented on maps/exodus/frontier-SCP/frontier-SCP-1.dmm
> +"caa" = (/obj/item/trash/wrapper/candy,/obj/machinery/atmospherics/unary/vent_pump/on{dir = 8},/turf/simulated/floor/plating,/area/maintenance/disposal)
Еще на Helltier надо исправить такую же проблему и будет ок.

2022-01-27 14:36 UTC, kreeperHLC commented
Стейл убрали, конфликты остались. Напиши мне в дискорде, помогу.

2022-03-23 16:48 UTC, TobyThorne commented
Больше месяца стали и конфликтов.

2022-05-09 21:24 UTC, Doster-d commented
Все еще конфликты :trollface:

2022-05-09 21:24 UTC, Zert0X commented
> Все еще конфликты :trollface: 

Автор сказал чтобы открыли

2022-06-02 05:15 UTC, TobyThorne commented on code/game/objects/items.dm
> +			icon_rotation = rand(0, 1) ? 180 : -180
рандом не нужен, без рандома можно аппрувать

2022-06-02 07:48 UTC, Artemonim commented on code/game/objects/items.dm
> +			icon_rotation = rand(0, 1) ? 180 : -180
в if или все три?

2022-06-23 08:16 UTC, Doster-d commented
Не компилируется

2022-07-17 20:20 UTC, Tsurupeta commented
Конфликты :trollface:

2022-09-09 17:56 UTC, TobyThorne commented
26 дней стали, дайте ему умереть

2022-10-01 19:39 UTC, Artemonim commented
Я случайно захардресетил весь ПР 🙃

2022-10-01 19:39 UTC, closed without merging