фикс переоткрытия юи у днк сканнера
ChaoticOnyx/OnyxBay pull request #6771
Opened 2021-10-21 16:40 UTC by TapKo4eB

ктобы мог подумать что без форс реопена юишки будут отказываться открываться по второму разу
<details>
<summary>с д</summary>

```yml
🆑
bugfix: Исправлено открытие интерфейса у DNA Analyzer'а.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

close #6728

2021-10-21 23:22 UTC, Doster-d requested changes

2021-10-21 23:22 UTC, Doster-d commented on code/modules/detectivework/microscope/dnascanner.dm
> +/obj/machinery/dnaforensics/ui_interact(mob/user, ui_key = "main", datum/nanoui/ui = null, force_open = 1)
```suggestion
/obj/machinery/dnaforensics/ui_interact(mob/user, ui_key = "main", datum/nanoui/ui = null, force_open = TRUE)
```

2021-10-21 23:41 UTC, Epicus7 commented
Непонятно почему без форса не открывается. У нас все окна в билде открываются только через форс? Или тут что-то особенное?

2021-10-21 23:48 UTC, Doster-d commented
> Непонятно почему без форса не открывается. У нас все окна в билде открываются только через форс? Или тут что-то особенное?

![image](https://user-images.githubusercontent.com/63081538/138371627-b9e2200e-0af3-41c8-b999-26efc67998a9.png)
Тут без дефайнов, на второе подчеркивание надо просто поставить 2 или дефайн UI_UPDATE (не точное название дефайна), иначе он просто не будет обновлять информацию, что заставляет игрока еще один раз тыкать в консоль, чтобы получить информацию.

2021-10-21 23:54 UTC, Epicus7 requested changes
Ну тогда надо убрать костыль с форсом и починить по предложению Достера

2021-10-22 00:05 UTC, Doster-d commented
Во, 
![image](https://user-images.githubusercontent.com/63081538/138373057-8c117ecb-a264-4080-9e6f-20b09a734ec8.png)
TOPIC_REFRESH

2021-10-22 10:44 UTC, TapKo4eB commented
![image](https://user-images.githubusercontent.com/48761132/138441048-1fbc3537-572e-454f-9fbe-de5567013355.png)
попытка поменять флаги и прок топик на онтопик ничего не изменила, так что копать надо глубже я хз
алсо пикрел литералли все юи что создаются в игре неиронично созываются с форс рефрешем

чё я хочу сказать что если и фиксить этот прикол это надо делать в отдельном пре и глобально во всей репе, а не ждать всю вечность чтобы починить единственную проблему вызванную нерефрешающимся днк сканнером

it just werks

2021-10-29 12:35 UTC, Epicus7 approved these changes
Реально, много где по билду такой костыль. Ну ладно

2021-10-29 12:36 UTC, kreeperHLC approved these changes

2021-11-02 15:04 UTC, Doster-d approved these changes
Ну раз хед дев говорит ок, значит ок

2021-11-02 18:20 UTC, TobyThorne approved these changes
ейй макарена

2021-11-02 18:20 UTC, merged