fix(nuclearbomb): nuclear bomb timer fixed
ChaoticOnyx/OnyxBay pull request #6804
Opened 2021-10-24 16:56 UTC by O0oMaximo0O

Таймер бомбы нюки теперь идёт в ногу со временем.

fix #6801 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Таймер бомбы нюки теперь нормально считает время.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-28 13:37 UTC, igorsaux requested changes

2021-10-28 13:37 UTC, igorsaux commented on code/game/machinery/nuclear_bomb.dm
> +		timeleft = max(timeleft - (world.time - last_process)/10, 0)
```suggestion
		timeleft = max(timeleft - (world.time - last_process) / 10, 0)
```

2021-10-29 11:05 UTC, DeltaEpsilon7787 commented
Решение говно, кодер пидорас.
[BYOND docs: world.time](https://www.byond.com/docs/ref/#/world/var/time)

Остановка таймера вызвана лагом контроллера (или вообще его крашем). Тут никак не реальное время, а все такое же игротиковое.

2021-10-29 11:16 UTC, O0oMaximo0O commented
Описание изменено на более корректное. Благодарим за понимание и поддержку.

2021-11-05 23:54 UTC, closed without merging