feat(area): add ability to conquer areas.
ChaoticOnyx/OnyxBay pull request #6805
Opened 2021-10-24 19:24 UTC by Doster-d

Ченджлога не будет.
Я немного улучшил иссуй, теперь и лоялисты (туда относится и главы) могут захватывать области.
Помечаем вербом canvas какой он (рев или лоял), добавляем ленты, расклеиваем, получаем одно очко к захвату.
Если при подсчете у нас больше canvasов, чем у другой комманды, значит мы забираем cost зоны.
Для установки того, чтобы в зоне надо было больше поставить флагов, к примеру, революции надо установить corp_posters_count на, например, 10.
Цена зоны соответственно повышается установление cost

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Добавлена возможность скопировать картины.
/🆑
```

</details>

close #975

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-25 11:40 UTC, Doster-d commented
Теперь круто.

2021-11-06 02:55 UTC, Epicus7 requested changes, later dismissed

2021-11-06 02:55 UTC, Epicus7 commented on code/_helpers/areas.dm
> +	GLOB.station_areas = get_filtered_areas(list(/proc/is_not_space_area, /proc/is_station_area))
У нас разве нельзя создавать новые area с помощью чертежей? Для ревы можно забить на новые area, но если кто-то захочет воспользоваться GLOB.station_area, то может словить баги из-за того, что новые зоны не будут добавляться сюда.

2021-11-06 02:55 UTC, Epicus7 commented on code/game/antagonist/station/loyalist.dm
> +		if(A.corp_posters_count > A.rev_posters_count)
Лучше сделать метод A.is_controlled_by_corporation и использовать его тут и в revolutionary.count_score()

2021-11-06 02:55 UTC, Epicus7 commented on code/game/area/areas.dm
> +	var/corp_posters_count = 0
corporation_posters_count

2021-11-06 02:55 UTC, Epicus7 commented on code/game/area/areas.dm
> +	var/rev_posters_count = 0
revolutionary_posters_count

2021-11-06 02:55 UTC, Epicus7 commented on code/game/area/areas.dm
> +	var/area_cost = 1
То что это area - это и так понятно, не обязательно в area, в названии переменной, опять писать value.

Я думаю, лучше назвать `importance` и комментом можно указать, что "used to determine cost for revolutionary and loyalists". Потом в будущем мб эта importance еще к чему-нибудь привяжется. В сторителлере, например, можно заиспользовать, чтобы оценивать ущерб станции и понимать насколько все плохо/хорошо.

2021-11-06 02:55 UTC, Epicus7 commented on code/game/area/areas.dm
> +	corp_posters_count -= 1
Может вместо этого безумия и кучи копипасты здесь и ниже при вызове этих методов, сделать одну переменную "area/var/loyalty", которая будет разницей количества плакатов лоялистов и количества плакатов революционеров?

В плакате две переменных "is_propaganda" (агитационный?) и "is_revolutionary" (если нет, то плакат лоялистов), вместо текущих трех "is_marked", "is_rev" и "is_corp".

Вообще, делать переменные типа "is_rev" и "is_corp" - плохой тон, потому что они взаимоисключающие. Вместо них точно должна быть одна переменная.

2021-11-06 02:55 UTC, Epicus7 commented on code/game/objects/structures/artstuff.dm
> +	var/is_poster = FALSE
`is_mounted`, по аналогии с проком `mount_canvas`, а то я сразу не понял о чем эта переменная.

2021-11-06 02:55 UTC, Epicus7 commented on code/game/objects/structures/artstuff.dm
> +		area_manipulation()
`update_area()` - функции и вербы лучше называть по типу "сделать что-то", а не существительными.

2021-11-06 02:55 UTC, Epicus7 commented on code/_helpers/areas.dm
> +	GLOB.station_areas = get_filtered_areas(list(/proc/is_not_space_area, /proc/is_station_area))
Надо найти проки, где area создаются новые и там сделать добавление их в этот глобальный список.

2021-11-06 02:55 UTC, Epicus7 commented on code/game/objects/structures/artstuff.dm
> +	var/message = SPAN_DANGER("You hate \the [src]. You want to burn \the [src] down!")
```suggestion
	var/message = SPAN_DANGER("You hate \the [src]. You want to burn it down!")
```

В английском же тоже не любят тавтологию, наверное?

2021-11-06 02:55 UTC, Epicus7 commented on code/game/objects/structures/artstuff.dm
> +	set desc = "Die corporation die!"
Может вместо corporation взять название корпорации из карты? Должна же быть переменная там. И ниже у лоялистов тоже самое.

2021-11-06 02:55 UTC, Epicus7 commented on code/game/objects/structures/artstuff.dm
> +	set category = "Poster"
Отдельная вкладка для одного верба? Может не надо?)

2021-11-06 02:55 UTC, Epicus7 commented on code/game/objects/structures/artstuff.dm
> +/obj/item/canvas/verb/make_rev_poster()
Эти вербы же появятся сразу на всех канвасах в игре и будут доступны всем игрокам, независимо от фракции. Режим не готов, плакаты рисовать неудобно, я думаю эти вербы стоит удалить пока. Сначала надо режим додумать и реализовать нормально рисование этих плакатов.

2021-11-06 02:58 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +	set category = "Poster"
Ну мне не удобно искать в обжектах верб, не интуитивно, как по мне)

2021-11-06 02:59 UTC, Epicus7 reviewed
Алсо, отдельно замечу, что в ПРе вместо обычных плакатов используются канвасы. Это означает что революционерам нужно каждый раз рисовать новый плакат руками, или же развешивать белые листы.

С точки зрения игрока какой-то полный треш сейчас. Мне кажется нужно либо в рамках этого же ПРа допиливать канвасы и 
1. Добавить какой-то предопределенный рисунок для НТ и революционеров, чтобы он использовался по дефолту.
2. Добавить возможность копировать канвасы так или иначе. Лучше, видимо, через сканнер и принтер.

Или же не заморачиваться и реализовать, все-таки, не через канвасы, а через обычные плакаты с определенным рисунком.

Мне кажется геймдизайнерское одобрение здесь поспешно поставили.

2021-11-06 03:01 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +/obj/item/canvas/verb/make_rev_poster()
А как их убрать, чтобы потом заново не писать? set src = null?

2021-11-06 03:03 UTC, Epicus7 commented
Еще, кстати, геймплейная проблема возникает с канвасами с тем, что непонятно как именно различать революционные плакаты от обычных рисунков на стене. Мужской половой орган - это революционный плакат или лоялистский? А котик? Там есть метагеймерское описание в экзамайн, но с точки зрения здравого смысла непонятно почему какой-то котик становится революционным или лоялистским.

Короче идея с канвасами мне еще меньше нравится

2021-11-06 03:20 UTC, Doster-d commented on code/_helpers/areas.dm
> +	GLOB.station_areas = get_filtered_areas(list(/proc/is_not_space_area, /proc/is_station_area))
Я это сделал с умыслом оптимизации, но это да, действительно может вызвать проблемы, я подумаю как это можно исправить.

2021-11-06 04:09 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +	set desc = "Die corporation die!"
Нельзя, set desc не позволяет по какой-то причине использовать переменные.

2021-11-06 05:00 UTC, NefrNerf commented
Вижу несколько вариантов решения проблемы:

1. Каждый постер фракции должен иметь специальный символ фракции и при экзамайне должно выводиться сообщение о том, какие "чувства" вызывает этот постер.

2. Определять принадлежность по цвету рамки, сделать так чтобы постеры были с разноцветнными рамками, это будет отличительной особенностью, так как цвет рамки нельзя менять.

Также, стоит добавить базовый рисунок, если человек не хочет ничего рисовать, при создании революционного плаката на нем должен быть изображен символ фракции.

2021-11-06 05:38 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/140599237-346bf847-e688-4188-97b4-f148f9be0fb5.png)
Copy

2021-11-16 20:07 UTC, Doster-d commented
Добавил рамочку.
Красная - рева. Синия - корпа.
Так же описание того, что постер революционный могут получить и СБшники.

2021-11-16 20:20 UTC, Doster-d commented
Теперь для того, чтобы появилась рамка нужно нажать Debug game и затем вызвать верб.
Это сделано пока мы не найдем применения коду, который я написал.

2021-11-17 19:10 UTC, Doster-d commented
![image](https://user-images.githubusercontent.com/63081538/142266653-34cced8a-fa6f-4880-a5c4-6b7849cbda6b.png)
![image](https://user-images.githubusercontent.com/63081538/142266673-bd6208b0-a5ae-430a-aa24-84d9d3f6595e.png)
Добавлена рамка для определения революционности плакатов.

2021-12-28 02:43 UTC, Doster-d commented on code/game/area/areas.dm
> +	is_station = !!all_predicates_true(list(src), list(/proc/is_not_space_area, /proc/is_station_area))
```suggestion
	is_station = all_predicates_true(list(src), list(/proc/is_not_space_area, /proc/is_station_area))
```

2022-03-29 18:15 UTC, TermService submitted a review, later dismissed

2022-03-29 19:29 UTC, TermService approved these changes

2022-03-29 19:31 UTC, igorsaux approved these changes

2022-03-29 19:34 UTC, merged