refact/feat(drinks): thermos now for soft drinks
ChaoticOnyx/OnyxBay pull request #6822
Opened 2021-10-27 18:40 UTC by MACTEP-ABATAP

1) Термос теперь термос, а не фляжка.
2) Возвращена/впилена древняя фича с термосом в котором есть чай, кофе и другие "soft drinks".
3) Косметический рефакторинг кода фляжек, по всем канонам от общего к частному.
4) Изменение путей к фляжкам на картах: обычной на капитанскую; капитанскую на обычную.

close #6286 

<details>
<summary>Чейнджлог</summary>

```yml
🆑 MACTEP ABATAP
tweak: В термосе теперь есть чай, кофе и различные безалкогольные напитки.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-27 18:55 UTC, NefrNerf commented
1. Отучайся писать названия по типу "Фляжечное" пиши четко что твой ПР делает
2. Чейнджлог должен быть понятен, сейчас - это не несет смысла

> Термос теперь термос, а не фляжка. Со всеми вытекающими.
Если ты изменил тип объекта то так и пиши и что за вытекающие, это такой каламбур? 

> Возвращена/впилена древняя фича с термосом в котором есть чай, кофе и другие "soft drinks".
Это можно вписать в чейнджлог

2021-10-27 19:06 UTC, MACTEP-ABATAP commented
1) Ок, я понял, больше не буду.
2) Более осмысленный чейнджлог, хорошо.

2021-10-27 19:16 UTC, ghost commented
Чем термос отличается от фляги?

2021-10-27 19:19 UTC, MACTEP-ABATAP commented
> Чем термос отличается от фляги?
> 

Улитка сказала.
https://discord.com/channels/414832443384659968/698083783072546857/900319531711492096

2021-10-28 08:15 UTC, TobyThorne requested changes
Thermos - название компании. Называть вакуумные фляги термосами - то же самое, что называть принтеры ксероксами, а электрические чайники - тефалями.

2021-10-28 08:26 UTC, MACTEP-ABATAP commented
Оставить vacuum flask? Просто в литературе thermos употребляется значительно чаще.

2021-10-28 08:29 UTC, TobyThorne commented
> Оставить vacuum flask? Просто в литературе thermos употребляется значительно чаще.

Да, лучше оставить его как flask/vacuum. 
Нынешний flask/vacuumflask - тоже смешное, конечно.

2021-10-28 08:46 UTC, MACTEP-ABATAP commented
Если оставить термос подтипом фляжки, то код дающий возможность выбрать безалкогольные напитки перестаёт работать, единственное найденное мной решение это как раз перенос из drinks/flask/vacuum в drinks/vacuum тогда.

2021-10-28 13:07 UTC, TobyThorne commented
> Если оставить термос подтипом фляжки, то код дающий возможность выбрать безалкогольные напитки перестаёт работать, единственное найденное мной решение это как раз перенос из drinks/flask/vacuum в drinks/vacuum тогда.

Пускай безалкогольные напитки будут доступны для выбора во всех флягах, наравне с алкоголем. Не вижу причины, по которой какао можно налить в термокружку, но нельзя - во фляжку.

2021-11-09 10:28 UTC, MACTEP-ABATAP commented
Скоро всё будет, нужно только подождать, я живой.

2021-11-16 20:08 UTC, MACTEP-ABATAP commented
Закрою до лучших времен, появится время допишу и открою.

2021-11-16 20:08 UTC, closed without merging