Нерфо-лоховское (Ибо не даёт называть ПРы как мы хотим, а так Фиксы плавности очередные)
ChaoticOnyx/OnyxBay pull request #6835
Opened 2021-10-29 16:21 UTC by kreeperHLC

Призраки должны быть более стабильны, но не очень. 
Облачко теперь будет плавным.
Карговозик тоже пофикшен.
Возможно Fix #6797
<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Частичный фикс плавности для призраков. 
bugfix: Фикс плавности облачка.
bugfix: Фикс плавности карговозика. 
bugfix: После убийства плавность призрака больше не передаётся от моба.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-29 16:35 UTC, Doster-d submitted a review, later dismissed

2021-10-29 19:56 UTC, igorsaux commented on code/modules/mob/observer/ghost/ghost.dm
> +		src.glide_size = glide_before_follow
```suggestion
		glide_size = glide_before_follow
```

2021-11-02 14:23 UTC, Doster-d approved these changes, later dismissed

2021-11-02 14:25 UTC, TobyThorne requested changes

2021-11-02 14:25 UTC, TobyThorne commented on code/modules/mob/mob_movement.dm
> +		if (O.buckled_mob)
противные пробелы не нужны

2021-11-02 14:26 UTC, kreeperHLC commented on code/modules/mob/mob_movement.dm
> +		if (O.buckled_mob)
Эпикус говорил что плевать на них. Я не стану сейчас лезть в готовый ПР ради двух пробелов. Не заставляй пожалуйста меня звать Эпикуса.

2021-11-02 14:27 UTC, Doster-d commented on code/modules/mob/mob_movement.dm
> +		if (O.buckled_mob)
А где такое запрещено?
Это же не куб, чтобы на пробелы обращать внимание )

2021-11-02 14:29 UTC, TobyThorne commented on code/modules/mob/mob_movement.dm
> +		if (O.buckled_mob)
Ой, блядь, в готовый ПР лезть, а-а-а, сложна. Мудак.

2021-11-02 14:29 UTC, TobyThorne approved these changes

2021-11-02 14:31 UTC, Doster-d approved these changes
Fine I'll do it myself

2021-11-02 14:33 UTC, igorsaux approved these changes

2021-11-02 14:34 UTC, merged