tweak(blob): lower blob's damage
ChaoticOnyx/OnyxBay pull request #6839
Opened 2021-10-29 17:49 UTC by igorsaux

fix #6838

<details>
<summary>Чейнджлог</summary>

```yml
🆑
balance: Снижен урон от блоба.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-10-29 18:02 UTC, NefrNerf requested changes
Давай пока в половину, а не на 70 процентов

2021-10-29 18:02 UTC, NefrNerf commented on code/game/objects/structures/blob/_defines.dm
> +#define BLOB_DAMAGE 1
```suggestion
#define BLOB_DAMAGE 3
```

2021-10-29 18:02 UTC, NefrNerf commented on code/game/objects/structures/blob/_defines.dm
> +#define BLOB_REINFORCED_DAMAGE 3
```suggestion
#define BLOB_REINFORCED_DAMAGE 7
```

2021-10-29 18:02 UTC, NefrNerf commented on code/game/objects/structures/blob/_defines.dm
> +#define BLOB_CORE_DAMAGE 6
```suggestion
#define BLOB_CORE_DAMAGE 13
```

2021-10-29 18:03 UTC, igorsaux commented
обновил

2021-11-02 16:36 UTC, NefrNerf approved these changes

2021-11-02 16:39 UTC, Doster-d approved these changes

2021-11-02 16:40 UTC, merged