Большой фикс бореров
ChaoticOnyx/OnyxBay pull request #6862
Opened 2021-11-01 19:29 UTC by O0oMaximo0O

В нашем проекте куча багов с борером, решил их фиксить. Пока в драфт, буду фиксить потихоньку. Буду заливать по коммиту по мере фиксов. Как наберётся достаточно или решу закончить на этом, выведу из драфта.

UPD_1:
Фикс задачи борера на выживание в носителе до конца раунда.

fix #6527 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь задание борера на выживание в носителе засчитывается.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-11-15 14:15 UTC, NefrNerf commented
> 1. Необходимо ли, чтобы борер жил дольше человека в пожаре/холоде?
Да
> 1.1. Если да, то:
> 1.1.1. Сделать, чтобы он вовсе не обращал внимания на температуру, пока внутри тела?
Да
> 1.1.2. Сделать урон от температуры меньше?
Нет
> 1.1.3. Сделать человека уязвимее? (уже вне данного ПР-а, текущий оставить как есть)
Не в ПРе, отдельная тема для обсуждения

> 1.2. Если нет, оставить как есть или что-то изменить?
> 2. Регенерация здоровья борера.
В любом случае нужна
> 2.1. Нужно ли добавить реген вне тела?
Нет
> 2.2. Стоит ли поменять скорость регенерации?
Какая сейчас?
> 2.3. Стоит ли дать ему регенерировать не только в живом теле, но и в мёртвом?
Да, мертвое он и захватить может, бтв

2021-11-15 14:17 UTC, TobyThorne commented
> 1. Необходимо ли, чтобы борер жил дольше человека в пожаре/холоде?
да
> 1.1.1. Сделать, чтобы он вовсе не обращал внимания на температуру, пока внутри тела?
да
> 1.1.2. Сделать урон от температуры меньше?
> 1.1.3. Сделать человека уязвимее? (уже вне данного ПР-а, текущий оставить как есть)
> 1.2. Если нет, оставить как есть или что-то изменить?
> 2. Регенерация здоровья борера.
> 2.1. Нужно ли добавить реген вне тела?
> 2.2. Стоит ли поменять скорость регенерации?
> 2.3. Стоит ли дать ему регенерировать не только в живом теле, но и в мёртвом?
нет

2021-11-15 14:25 UTC, O0oMaximo0O commented
>     2.2. Стоит ли поменять скорость регенерации?

> Какая сейчас?

1 хп или 5% за вызов Life()

2021-11-15 15:02 UTC, O0oMaximo0O commented
Сделал, чтобы борер внутри хоста теперь совсем не обращал внимания на воздух и температуру. Здоровье теперь регенится и в мёртвом хосте тоже

2021-12-07 09:58 UTC, O0oMaximo0O commented
Если этот ПР не смотрится из-за отсутствия плашки "одобрено" - скажите. А товарищи овнеры - накиньте её пожалуйста. Я ваши замечания учёл и исправил.

2021-12-07 10:03 UTC, Doster-d requested changes

2021-12-07 10:03 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +	New(text)
Если ты это тыкаешь, то проводи к нормальному пути

2021-12-07 10:03 UTC, Doster-d commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	spawn(-1)
Что это такое? Что ты хочешь этим сделать?

2021-12-07 10:07 UTC, O0oMaximo0O commented on code/game/gamemodes/objective.dm
> +	New(text)
Да мне просто линтер проверку рушил из-за var.

2021-12-07 10:08 UTC, O0oMaximo0O commented on code/game/gamemodes/objective.dm
> +	New(text)
Ок, поправлю весь файл.

2021-12-07 10:11 UTC, O0oMaximo0O commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	spawn(-1)
Здесь всё ок, просто поехали строки из-за удаления/добавления проков.
Тут покидание хоста перенесено в способки, вставлены переопределение реакции на окружающюю среду и вселение в борера как у личинки ксеноморфа

2021-12-07 11:19 UTC, Doster-d requested changes

2021-12-07 11:19 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +datum/objective/silence/check_completion()
```suggestion
/datum/objective/silence/check_completion()
```

2021-12-07 11:19 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +datum/objective/block/check_completion()
```suggestion
/datum/objective/block/check_completion()
```
Блять оно везде

2021-12-07 11:19 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +datum/objective/protect/check_completion()
```suggestion
/datum/objective/protect/check_completion()
```
Ну ты понял

2021-12-07 11:41 UTC, O0oMaximo0O commented on code/game/gamemodes/objective.dm
> +datum/objective/protect/check_completion()
Понял

2021-12-07 11:49 UTC, O0oMaximo0O commented
`/` added.

2021-12-17 00:52 UTC, TobyThorne commented
Обнаружены конфликты.

2021-12-17 08:49 UTC, O0oMaximo0O commented
Конфликты уничтожены.

2021-12-17 09:26 UTC, Shootnik01 commented
![image](https://user-images.githubusercontent.com/75479005/146521575-0ba402bc-fa89-4817-96a3-c21a2f0635ab.png)

2022-03-07 12:06 UTC, kreeperHLC commented
Кофликты

2022-03-07 21:45 UTC, O0oMaximo0O commented
Отревьювните, что ли)
Пока снова конфликты не появились.

2022-03-19 10:04 UTC, TermService approved these changes

2022-03-19 10:11 UTC, Doster-d approved these changes

2022-03-19 20:41 UTC, merged