tweak(integrated_circuits): bug fixes
ChaoticOnyx/OnyxBay pull request #6939
Opened 2021-11-12 18:23 UTC by Doster-d

От хирургической платы в текущем виде больше проблем чем пользы, я переписал ее в предыдущем ПРе, но так как в этом ПРе только баг фиксы, я вырезал ее.

Перенес все фиксы из своего ПРа в этот.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Исправлена работа некоторых плат, общие улучшения корректности работы интегральных схем.
rscdel: Удалена хирургическая плата.
/🆑
```

</details>

close #5788, close #5553, close #6657

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-11-12 18:24 UTC, Doster-d commented
Ах, да, альтернативный tittle: Интегральное 3.(33)

2021-11-13 09:52 UTC, igorsaux requested changes

2021-11-13 09:52 UTC, igorsaux commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +		attached_grenade.forceMove(get_turf(assembly))
```suggestion
		attached_grenade?.forceMove(get_turf(assembly))
```

2021-11-13 09:52 UTC, igorsaux commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +		addtimer(CALLBACK(src, .proc/before_activation_action), dt-1)
```suggestion
		addtimer(CALLBACK(src, .proc/before_activation_action), dt - 1)
```

2021-11-13 09:52 UTC, igorsaux commented on code/modules/integrated_electronics/core/special_pins/string_pin.dm
> +	new_data = sanitize(new_data, trim = 0, max_length = MAX_PAPER_MESSAGE_LEN)
```suggestion
	new_data = sanitize(new_data, trim = FALSE, max_length = MAX_PAPER_MESSAGE_LEN)
```

2021-11-13 16:03 UTC, igorsaux approved these changes

2021-11-13 19:00 UTC, Zert0X approved these changes
🤞🏻 
Выглядит прилично.

2021-11-14 07:24 UTC, TobyThorne commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +	if(istype(wrapped, /obj/item/device/electronic_assembly))
чёт я не понял, что это и почему оно с багфиксами, но похер

2021-11-14 07:24 UTC, merged

2021-11-14 07:25 UTC, Doster-d commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +	if(istype(wrapped, /obj/item/device/electronic_assembly))
Там была проблема,что борги не могли использовать ranged_sensor