Whitelist removal + small bugfixes
ChaoticOnyx/OnyxBay pull request #6944
Opened 2021-11-13 14:48 UTC by Jlekar

Вырезал Вайтлист.

Что поменял:

- Больше не появляется вопрос о включении/исключении рас, требующих вайтлист, когда админ даёт возможность игроку поменять внешность. (admin_verbs.dm)
- Поменял значения нескольких переменных, вырезал проверку вайтлиста (03_body.dm).

Багфикс:

- В меню выбора рас больше не появится строка о вайтлисте.
- Добавил preview для скреллов.
- Поменял иконку preview человека на иконку с глазами.

<details>
<summary>preview</summary>

![human](https://user-images.githubusercontent.com/92691910/141646028-f986dd28-cf5e-41a2-b4b3-4da9d38d2313.png)

![skrell](https://user-images.githubusercontent.com/92691910/141646065-553f9d07-17bf-4d2d-9d8c-2d7cfb2b1373.png)

</details>

close #6643 
close #2656

<details>
<summary>Changelog</summary>

```yml
🆑Lekar
rscdel: Вырезан вайтлист.
bugfix: Обновлены изображения скреллов и людей при выборе расы в character setup.
/🆑
```

</details>
<details>
<summary>Дополнительно</summary>

![why](https://user-images.githubusercontent.com/92691910/141646768-de882175-fa4c-4afa-85d3-341b69d4d5d8.png)

_На локальном сервере всё работало исправно, но всё же, мог за чем-либо не уследить, поэтому пункт не отмечаю._
</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-01 16:50 UTC, Doster-d requested changes

2021-12-01 16:50 UTC, Doster-d commented on code/game/antagonist/antagonist_update.dm
> +			if(istype(H)) H.change_appearance(APPEARANCE_ALL, H.loc, H, state = GLOB.z_state)
Мой друг, это не то, что ты должен удалять, это вайтлист расы на АНТАГов, который у нас сейчас действует.
```suggestion
			if(istype(H)) H.change_appearance(APPEARANCE_ALL, H.loc, H, species_whitelist = valid_species, state = GLOB.z_state)
```

2021-12-01 16:50 UTC, Doster-d commented on code/modules/mob/living/carbon/human/appearance.dm
> +/mob/living/carbon/human/proc/change_appearance(flags = APPEARANCE_ALL_HAIR, location = src, mob/user = src, list/species_blacklist = list(), datum/topic_state/state = GLOB.default_state)
Как было сказано раньше, ты трогаешь другую область, не трогай ее, пожалуйста.

2021-12-01 16:50 UTC, Doster-d commented on code/modules/client/preference_setup/loadout/loadout.dm
> -	var/mob/preference_mob = preference_mob()
И это тоже не относится к удаляемой тобой теме!

2021-12-01 16:51 UTC, Doster-d commented
Тебе вообще надо было просто надпись whitelist restricted удалить, если не включен вайтлист на расу.

2021-12-17 00:46 UTC, TobyThorne commented
Двухнедельный ченжреквест, вешаю сталь.

2021-12-21 06:44 UTC, TobyThorne commented
Четыре дня stale. Если автор оживёт - может переоткрыть.

2021-12-21 06:44 UTC, closed without merging