fix(grab): grabs are now deleted instead of drop
ChaoticOnyx/OnyxBay pull request #7011
Opened 2021-11-21 21:48 UTC by Megmeehey

TL;DR
- Граб не выпадает
- Граб не перекладывается из руки в руку

Closes https://github.com/ChaoticOnyx/OnyxBay/issues/4808

Не TL;DR версия:

Есть **Игрок**. Есть **Тело**, которое грабнул игрок. Есть **Граб**.
Граб выпадает при переходе между z-уровням.
Вот некоторые причины:
1) Граб проверяется при мувменте и может "выпасть", при проверке определенного множества условий.
![grab2](https://user-images.githubusercontent.com/2480466/142779233-fe54969a-e809-43ed-a5bd-7fc3fb0d43b9.JPG)

В случае перехода по z-уровням, игра считает, что больше Игрок и Тело Adjacent, и разрывает Граб.

2) Граб процессится, и раз в тик проверяется некоторое другое множество условий (пересекающееся с первым). Тут тоже может выпасть.
![grab](https://user-images.githubusercontent.com/2480466/142779239-0dfa1f87-51fb-4a43-a4d0-a868a0981854.JPG)

3) Вместо прямого удаления используется костыль с выкидыванием Граба.

Пофиксить тут нужно много вещей:
1) Граб - сам по себе один здоровый костыль. Это айтем, который, на самом деле, не айтем, а представление связки между двумя персонажами. Почему он не сделан так же, как пулл (с отражением в client.screen какой-нибудь картиночки о том, что рука занята и бла-бла) мне не ясно.

2) Граб надо не выкидывать, а просто удалять. И вообще его надо сделать невыкидываемым.

3) Граб хорошо бы не процессить. Не то чтобы он занимал много времени на проверку, но не ясно зачем ему вообще процессинг, если там всего-то пару ивентов надо слушать.

4) Хорошо бы переделать\сделать новую проверку Adjacent так, чтобы она осознавала z-уровни. Из-за этого сейчас тяжело протащить Грабом Тело по лестнице. Я попробовал сделать, но выяснил, что если Граб - спагетти код, то лестницы и движение по z-уровням - это таз рамена. Например, у нас есть хендлер для движения вверх или вниз, но он не работает для лестниц, которые передвигают тебя вверх или вниз. Круто?

5) Код выбрасывания айтемов (в том числе и Граба) рассортирован так себе, можно было бы и его поковырять.

Из всего этого многообразия я сделал только 2. Я попробовал сделать 3, но у нас хреново дела с ивентами. Затем попробовал 4, чтобы нормально двигаться по z-уровням, но, похоже, я буду доделывать это еще недели две, если вообще доделаю.

Короче, хотел сделать нормально, но сделал как всегда. Я подумаю еще над тем, чтобы унести код удаления в `inventory.dm` и переиспользовать.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я знаю, что делаю
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-11-23 12:59 UTC, igorsaux requested changes

2021-11-23 12:59 UTC, igorsaux commented on code/modules/mob/mob_movement.dm
> +		if(I && I.can_be_dropped_by_client(mob))
```suggestion
		if(I?.can_be_dropped_by_client(mob))
```

2021-11-23 12:59 UTC, igorsaux commented on code/modules/mob/grab/grab_object.dm
> +		if(QDELING(src))
Кажется отрицание потерял

2021-11-23 12:59 UTC, igorsaux commented on code/modules/mob/grab/grab_object.dm
> +		return TRUE
```suggestion
	return M == assailant
```

2021-11-23 12:59 UTC, igorsaux commented on code/modules/mob/grab/grab_datum.dm
> +	if (!QDELING(G))
Можно было бы инвертировать условие

2021-11-23 12:59 UTC, igorsaux commented on code/modules/mob/grab/grab_datum.dm
> +		assailant.u_equip(G)
А точно ничего не сломается?

https://github.com/ChaoticOnyx/OnyxBay/blob/c02355d40cfecb638c4fd55e264453beb83780a1/code/modules/mob/inventory.dm#L179-L191

2021-11-23 12:59 UTC, igorsaux commented on code/game/machinery/kitchen/gibber.dm
> +		qdel(G)
Хм может вместо прямого вызова `qdel` вызывать `let_go`

2021-11-23 18:22 UTC, Megmeehey commented on code/modules/mob/mob_movement.dm
> +		if(I && I.can_be_dropped_by_client(mob))
полечил

2021-11-23 18:22 UTC, Megmeehey commented on code/modules/mob/grab/grab_object.dm
> +		if(QDELING(src))
И правда

2021-11-23 18:22 UTC, Megmeehey commented on code/modules/mob/grab/grab_object.dm
> +		return TRUE
Поправил

2021-11-23 18:23 UTC, Megmeehey commented on code/modules/mob/grab/grab_datum.dm
> +	if (!QDELING(G))
Прок переехал в grab_object.delete_self(). Так пойдет?

2021-11-23 18:30 UTC, Megmeehey commented on code/modules/mob/grab/grab_datum.dm
> +		assailant.u_equip(G)
Короткий ответ - не сломается.

Я хотел написать под "DO NOT CALL THIS PROC DIRECTLY", чтобы автор шел охладить траханье, но чет не стал.

`u_equip` используется в единственном месте - внутри `remove_from_mob`.
`remove_from_mob` занимается тремя вещами
1) Вызывает `u_equip`, чтобы убрать предмет из инвентаря
2) Убирает предмет с UI пользователя
3) Выкладывает предмет на землю

Штука в том, что граб - не типичный item (я писал, что он вообще не должен быть item по-хорошему), и его не надо выбрасывать на землю вообще никогда. Соответственно, мне нужно из `remove_from_mob` 1.5 пункта.

2021-11-23 18:31 UTC, Megmeehey commented on code/game/machinery/kitchen/gibber.dm
> +		qdel(G)
Пожалуй, да. В целом, в текущем коде ничего не поломается, если использовать просто qdel(G). Поэтому можно даже не тронутые удаления граба и не трогать.

2021-11-30 14:41 UTC, igorsaux approved these changes

2021-12-01 16:27 UTC, Doster-d requested changes

2021-12-01 16:27 UTC, Doster-d commented on code/game/objects/items.dm
> +/obj/item/proc/can_be_dropped_by_client(mob/M)
Плохое название прока как по мне, сбивает с толку, лучше назвать ```can_be_dropped_by_mob```

2021-12-02 08:18 UTC, Megmeehey commented on code/game/objects/items.dm
> +/obj/item/proc/can_be_dropped_by_client(mob/M)
Да нет, вообще-то отличное название, если посмотреть, где оно используется:

```dm
/client/verb/drop_item()
	set hidden = 1
	if(!isrobot(mob) && mob.stat == CONSCIOUS && isturf(mob.loc))
		var/obj/item/I = mob.get_active_hand()
		if(I?.can_be_dropped_by_client(mob))
			mob.drop_item()
```

Этот метод определяет, можно ли дропнуть вещь именно клиентским вызовом `drop_item`

2021-12-02 08:22 UTC, Megmeehey commented on code/game/objects/items.dm
> +/obj/item/proc/can_be_dropped_by_client(mob/M)
Другой вопрос, что решение добавить в mob еще один метод на именно эту проверку, и еще и `if(I?.can_be_dropped_by_client(mob))` - полное говно.

Решение сильно лучше - это рефакторинг кода дропа вещей в принципе. Я попробовал и понял, что я не готов сделать это быстро.

2021-12-02 09:02 UTC, Doster-d commented on code/game/objects/items.dm
> +/obj/item/proc/can_be_dropped_by_client(mob/M)
Ты моба передаешь, а называешь by_client

2021-12-02 09:19 UTC, Megmeehey commented on code/game/objects/items.dm
> +/obj/item/proc/can_be_dropped_by_client(mob/M)
Да, именно так.

Метод отвечает на вопрос "можно ли клиентским вызовом выбросить предмет". Он называется, чтобы отражать эту логику.
То, что туда передается, дело десятое. Я мог бы туда еще хоть 10 параметров передать, если бы это было нужно для получения ответа на вопрос.

2021-12-02 10:15 UTC, Doster-d approved these changes

2021-12-02 21:07 UTC, merged