feat(flora): add ability to cut plants & chop down trees ingame
ChaoticOnyx/OnyxBay pull request #7060
Opened 2021-11-29 12:13 UTC by TatarTheBuilder

Добавил больше кустов, добавил возможность рубить кусты и деревья

<details>
<summary>Чейнджлог</summary>

```yml
🆑
imageadd: Добавлены новые виды кустов и прочей растительности.
tweak: Все декоративные растения, кусты и деревья теперь можно срубить ингейм без использования взрывчатки.
maptweak: Мелкие изменения сада на карте Фронтир.

/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-11-29 14:22 UTC, Doster-d requested changes

2021-11-29 14:22 UTC, Doster-d commented on code/game/objects/structures/flora.dm
> +		cut_hits = 0
Тут такая же проблема, что мы обсуждали, ты если не шарпом, сразу срубаешь

2021-11-29 14:23 UTC, Doster-d commented on code/game/objects/structures/flora.dm
> +		cut_hits = 0
И тут

2021-11-29 19:59 UTC, Doster-d approved these changes
~~Можно попросить андефайнуть дефайны, которые больше не будут использованы, но кому на это не похуй~~ LGTM

2021-12-02 09:06 UTC, Doster-d commented on code/game/objects/structures/flora.dm
> +		cut_hits = 0
Не решено

2021-12-02 09:06 UTC, Doster-d requested changes
А

2021-12-02 09:22 UTC, Doster-d approved these changes

2021-12-02 09:37 UTC, igorsaux approved these changes

2021-12-02 21:07 UTC, merged