Мультитул взламывает все шкафчики
ChaoticOnyx/OnyxBay pull request #7062
Opened 2021-11-29 20:59 UTC by TimErmolt

- Для шкафчиков с неснимаемыми дверьми не проходила проверка при попытке взлома мультитулом, от чего их невозможно было взломать. Теперь исправлено.
- У оружейных шкафов во взломанном состоянии исчезал спрайт двери. Теперь исправлено, и им добавлен оверлей искр во взломанном состоянии, как у остальных шкафчиков. Там же приведён в порядок стиль кода.

Вроде я правильно сделал чейнджлог.

fixes #6180 

<details>
<summary>Чейнджлог</summary>

```yml
🆑TheUnknownOne
bugfix: Исправлен баг, не позволявший взламывать мультитулом шкафчики с неснимаемыми дверьми.
bugfix: Исправлено исчезновение спрайта двери оружейных шкафов после взлома.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-01 16:23 UTC, Doster-d commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, "off")
А зачем off добавлять?

2021-12-01 17:17 UTC, TimErmolt commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, "off")
В файле с спрайтами спрайт оверлея сломанного шкафа называется "off", а не "broken". Как раз из-за этого у него во взломанном состоянии исчезала дверь. Так как у остальных шкафчиков сломанные спрайты называются тоже "off", изменил здесь, в коде, а не стал переименовывать спрайт.

2021-12-01 17:18 UTC, Doster-d commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, "off")
Пиздец, конфуз лучше поменяй на правильную, те кто называл "off" дураки, поменяй, пожалуйста.

2021-12-01 17:47 UTC, TimErmolt commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, "off")
Окей, готово.

2021-12-10 16:58 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, icon_broken)
А откуда должны взяться "broken" и "sparks"?
![image](https://user-images.githubusercontent.com/45202681/145612195-e55ce958-1303-4cb1-a403-f074f1ad5b87.png)

2021-12-10 16:58 UTC, TobyThorne commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, icon_broken)
А, ладно, претензия снята, не увидел эдит дми

2021-12-10 16:58 UTC, TobyThorne approved these changes

2021-12-10 17:09 UTC, Doster-d approved these changes

2021-12-10 17:11 UTC, Doster-d requested changes
У нас есть система для того, чтобы делать искры, может используешь ее?

2021-12-10 17:14 UTC, Doster-d commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, icon_broken)
Убери sparks из dmi и используй систему.

2021-12-10 17:15 UTC, Doster-d commented on code/game/objects/structures/crates_lockers/closets.dm
>  		locked = !locked
Между 437 и 438 ставь это:
```
		var/datum/effect/effect/system/spark_spread/s = new()
		s.set_up(5, 1, src)
		s.start()
```

2021-12-10 17:15 UTC, Doster-d commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +			overlays += icon(src.icon, icon_broken)
Хотя похуй.

2021-12-10 17:15 UTC, Doster-d approved these changes

2021-12-10 17:17 UTC, merged