add(dmjit): add dmjit
ChaoticOnyx/OnyxBay pull request #7094
Opened 2021-12-05 16:02 UTC by igorsaux

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-05 16:22 UTC, Epicus7 requested changes
Описание ПРа где?

> #define DMJIT_LIB "./libdmjit.so"

Откуда она возьмется? Кто это собирать будет?

Зачем нам в билде непонятные хаки, которые будут отваливаться с каждой обновой бьонда и которые никто не сможет поддерживать, потому что никто не понимает что это и зачем это нужно?

2021-12-06 17:05 UTC, quardbreak requested changes

2021-12-06 17:05 UTC, quardbreak commented on code/__defines/dmjit.dm
> +    if (world.system_type != UNIX)
Что-то пошло не так и все отступы в файле - пробелы.

2021-12-06 21:38 UTC, Bizzonium commented
С кодом указанных проков не ознакамливался, но выглядит как нечто неподдерживаемое dmjit в данный момент. Пока что стоит компилировать только те проки, в которыз есть почти полная поддержка содержимых опкодов.

2022-01-06 22:43 UTC, kcalbCubeFork commented
> Описание ПРа где?
> 
> > #define DMJIT_LIB "./libdmjit.so"
> 
> Откуда она возьмется? Кто это собирать будет?
> 
> Зачем нам в билде непонятные хаки, которые будут отваливаться с каждой обновой бьонда и которые никто не сможет поддерживать, потому что никто не понимает что это и зачем это нужно?

я больше скажу, тебе нужно пятнадцать километров рамы иметь и половину суток компилить, а производительность нифига не увеличишь с теми опкодами что готовы на данный момент.

2022-11-02 16:22 UTC, closed without merging