Removes some new changeling bugs
ChaoticOnyx/OnyxBay pull request #7112
Opened 2021-12-08 17:13 UTC by TobyThorne

```yml
🆑
bugfix: Исправлен баг с пропажей купленных способностей генокрада после использования способности Infest.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-08 17:48 UTC, igorsaux submitted a review, later dismissed

2021-12-08 18:00 UTC, Doster-d submitted a review, later dismissed

2021-12-08 18:01 UTC, Doster-d commented on code/game/gamemodes/changeling/changeling_datum.dm
> +/datum/changeling/proc/remove_all_changeling_powers(remove_purchased = FALSE)
А зачем здесь менять, но в принципе - ок.

2021-12-08 18:34 UTC, TobyThorne commented
Да куда аппрув, рано, там ещё баг противный есть.

2021-12-08 18:37 UTC, igorsaux commented
Ну вот в другом пре починишь :trollface:

2021-12-10 12:22 UTC, Doster-d requested changes

2021-12-10 12:22 UTC, Doster-d commented on code/game/gamemodes/changeling/biostructure.dm
> +	//var/already_removed = FALSE
Закомментированный код - плохо

2021-12-10 13:42 UTC, TobyThorne commented
писос сколько перелопатил
зато попутно и гибы с ревайвами должны теперь надёжнее работать

2021-12-10 15:19 UTC, Doster-d approved these changes

2021-12-10 15:22 UTC, igorsaux approved these changes

2021-12-10 15:34 UTC, merged