feat(art_library): add ability to save art
ChaoticOnyx/OnyxBay pull request #7132
Opened 2021-12-10 23:44 UTC by Doster-d

Не прошло и года.
Так же починил 23x23 и 24x24, поменяв немного спрайт.

В принципе нормально, есть можно.
![image](https://user-images.githubusercontent.com/63081538/145654520-1c2112cf-31fc-460e-9a78-a90ee1fba3be.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена программа для сохранения картин. Для работы требуется сканер, для распечатки, нужно расположить консоль рядом с book binderом.
tweak: book binder теперь принимает картины. Для копирование картины из базы данных нужно вставить пустую картину такого же размера.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-11 00:04 UTC, Doster-d commented
[art_scheme.zip](https://github.com/ChaoticOnyx/OnyxBay/files/7696051/art_scheme.zip)
Если нужна схема, то вот.

2021-12-11 10:05 UTC, igorsaux requested changes

2021-12-11 10:05 UTC, igorsaux commented on nano/templates/art_library.tmpl
> +		<img style="width: 60vh; height: 60vh" src='data:image/png;base64,{{:data.current_art.icon}}'>
```suggestion
		<img style="width: 60vh; height: 60vh; -ms-interpolation-mode: nearest-neighbor;" src='data:image/png;base64,{{:data.current_art.icon}}'>
```

2021-12-11 10:25 UTC, DarkHunter7756 commented
Что требоваться будет для распечатки? Новые пустые холсты? Бумага?

2021-12-11 10:32 UTC, Doster-d commented
> Что требоваться будет для распечатки? Новые пустые холсты? Бумага?

По русски написано, вставить пустую картину такого же размера

2021-12-16 22:43 UTC, Doster-d commented on code/game/objects/structures/artstuff.dm
> +	author_ckey = author_ckey ? author_ckey : user.ckey || "THIS IS BUG! ALARM!"
```suggestion
	author_ckey = author_ckey || user?.ckey || crash_with("THIS IS BUG! ALARM!")
```

2021-12-16 22:45 UTC, TobyThorne commented on code/modules/library/lib_machines.dm
> +		to_chat(user, SPAN_NOTICE("\The [src] already have item installed in!"))
блятб почему инсталлед 
```suggestion
		to_chat(user, SPAN_NOTICE("\The [src] already has something inside!"))
```

2021-12-16 22:47 UTC, Doster-d commented on code/modules/library/lib_machines.dm
> +		to_chat(user, SPAN_NOTICE("\The [src] already have item installed in!"))
ай больно в ноге

2021-12-22 14:43 UTC, Doster-d commented
Обновил картинку интерфейса на актуальную версию.

2021-12-24 11:43 UTC, igorsaux requested changes

2021-12-24 11:43 UTC, igorsaux commented on code/modules/modular_computers/file_system/programs/generic/artlibrary.dm
> +			var/DBQuery/query = sql_query({"
а чё тут нету проверки на результат `query`

2021-12-24 11:46 UTC, Doster-d commented on code/modules/modular_computers/file_system/programs/generic/artlibrary.dm
> +			var/DBQuery/query = sql_query({"
А че ты этот вопрос к создателям library.dm не задал? Там точно так же.

2021-12-24 11:47 UTC, TobyThorne approved these changes
![image](https://user-images.githubusercontent.com/45202681/147350196-2c8ae59a-bad6-4692-b9c3-766c2db1019d.png)

2021-12-24 11:47 UTC, igorsaux commented on code/modules/modular_computers/file_system/programs/generic/artlibrary.dm
> +			var/DBQuery/query = sql_query({"
Чё какой `library.dm`, у тебя тут таблица которой ещё нету и ты не проверяешь результат запроса

2021-12-24 11:57 UTC, igorsaux approved these changes

2021-12-24 12:18 UTC, merged