Removes absence of runechat
ChaoticOnyx/OnyxBay pull request #7143
Opened 2021-12-11 11:01 UTC by TobyThorne

![runechat](https://user-images.githubusercontent.com/45202681/145674108-823de0c3-a563-4cac-b8d6-616acadd4094.png)

Порт не совсем рабочий, работает через жопу, может кто-нибудь решится доделать, но мне лень.
Может, когда-нибудь доделаю, если никто не доделает. Или нет.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-11 12:13 UTC, No-Tips commented
Oh god, oh no, oh fuck, god please, no

2021-12-11 21:28 UTC, quardbreak commented on code/__defines/subsystem-priority.dm
> +#define SS_PRIORITY_RUNECHAT       90    // Runechat processing. Shame it's so high in priority, but what can we do.
Это не нормально. Ему хватит и 20. 
Не надо выделять такой приоритет на целый тик.

2021-12-11 22:37 UTC, quardbreak requested changes

2021-12-11 22:37 UTC, quardbreak commented on code/datums/chatmessage.dm
> +			animate(m.message, pixel_y = m.message.pixel_y + mheight, time = CHAT_MESSAGE_SPAWN_TIME)
`animate(m.message, pixel_z = m.message.pixel_z + mheight, time = CHAT_MESSAGE_SPAWN_TIME)`

2021-12-11 22:37 UTC, quardbreak commented on code/datums/chatmessage.dm
> +	message.pixel_y = owner.bound_height * 0.95
`message.pixel_z = owner.bound_height * 0.95`

2021-12-11 22:37 UTC, quardbreak commented on code/datums/chatmessage.dm
> +	message_loc = target
`message_loc = get_atom_on_turf(target)`, иначе сообщения не будут показываться если loc объекта не на поверхности.
```
/proc/get_atom_on_turf(var/atom/movable/M)
	var/atom/mloc = M
	while(mloc && mloc.loc && !istype(mloc.loc, /turf/))
		mloc = mloc.loc
	return mloc
```

2021-12-11 22:37 UTC, quardbreak commented on code/modules/client/preference_setup/global/preferences.dm
> +	default_value = GLOB.PREF_NO
Если добавляешь, то лучше убрать. Никто не узнает о функционале не увидев его.

2021-12-11 22:37 UTC, quardbreak commented on code/modules/mob/living/carbon/human/species/species.dm
> +	if(appearance_flags & HAS_SKIN_COLOR)
Как оно работает? Если у человека есть этот флаг и его волосы крашены, то всё равно вернёт цвет кожи, разве нет?

2021-12-11 22:37 UTC, quardbreak commented on interface/skin.dmf
> +		style=".center { text-align: center; } .maptext { font-family: 'Small Fonts'; font-size: 7px; -dm-text-outline: 1px black; color: white; line-height: 1.1; } .small { font-size: 6px; } .big { font-s
Много специфичного с тг, что не будет использоваться.

2021-12-12 00:23 UTC, quardbreak commented on code/modules/mob/living/carbon/human/species/species.dm
> +	if(appearance_flags & HAS_SKIN_COLOR)
Может быть, лучше определить пустую переменную и для human сделать оверрайд.

2021-12-12 03:43 UTC, TobyThorne commented
блин забыл драфт повесить

2021-12-12 08:52 UTC, Zert0X commented
@TobyThorne 

> Порт не совсем рабочий, работает через жопу

Ты бы хоть написал, что не так.

2021-12-12 09:07 UTC, quardbreak commented
@Zert0X по информации Достера, цвет определяющийся с помощью причёсок может полностью перекрасить текст до нечитабельности. Например в чёрный.

2021-12-12 09:10 UTC, Zert0X commented
![изображение](https://user-images.githubusercontent.com/42303535/145706680-fa831a4d-c5b2-4662-a186-5343af50aa3d.png)
Заметил

2021-12-12 09:27 UTC, Doster-d commented on code/datums/chatmessage.dm
> +	message_loc = target
Какой-то сложный способ get_turf, почему его нельзя использовать?

2021-12-12 09:46 UTC, quardbreak commented on code/datums/chatmessage.dm
> +	message_loc = target
Гет-турф будет возвращать сам турф, если атом находится внутри контейнера, который находится в другом атоме.
А эта функция должна вернуть родительный холдер, исключая турф.

2021-12-12 11:56 UTC, Zert0X reviewed
Try something like this.

2021-12-12 11:56 UTC, Zert0X commented on code/datums/chatmessage.dm
> +	HSL[3] = max(HSL[3],0.4)
```suggestion
	var/list/HSL = rgb2hsl(color[1],color[2],color[3])
	HSL[2] *= HSL[2]<50?1.75:1.2
	HSL[3] = max(HSL[3],50)
```

https://user-images.githubusercontent.com/42303535/145711139-a22a612d-5238-4eb0-b9f7-76a314f0403c.mp4

2021-12-14 02:04 UTC, quardbreak requested changes
Потихоньку доделываю по мере возможности и знаний свою версию руначата, иногда заглядывая сюда для сравнения.

2021-12-14 02:04 UTC, quardbreak commented on code/_helpers/text.dm
> +/datum/html/split_holder
Вариант с ТГ будет проще, чем избыточный код, написанный не знающим regex'ы кодером.

```dm
	// Get rid of any URL schemes that might cause BYOND to automatically wrap something in an anchor tag
	var/maxlen = RUNECHAT_MESSAGE_MAX_LENGTH
	if (length_char(text) > maxlen)
		text = copytext_char(text, 1, maxlen + 1) + "..." // BYOND index moment

	// Remove spans in the message from things like the recorder
	var/static/regex/span_check = new(@"<\/?span[^>]*>", "gi")
	text = replacetext(text, span_check, "")
```

2021-12-14 02:04 UTC, quardbreak commented on code/modules/client/preference_setup/global/preferences.dm
> +	key = "CHAT_RUNECHAT"
Если планируешь потом добавить больше настроек для руначата, стоит переименовать в `"RUNECHAT_SHOW"` для сортировки внутри json-файла.

2021-12-14 02:04 UTC, quardbreak commented on code/datums/chatmessage.dm
> +	message_loc = target
Объясню подробнее: если локация оверлея не будет прикреплена к видимому объекту, то ты не увидишь сообщение.

Раньше использовали `loc` носителя, но выяснилось, что сообщения от людей, сидящих в шкафу никто не увидит.
`get_turf()` тоже не подходит, потому что он всегда будет возвращать турф, когда закреплять оверлей нужно за объектом. 
Чтобы видеть сообщения от людей, сидящих в шкафу, решили использовать коренной объект, содержащий указанный нами объект. Поэтому, в данном случае, предпочтительно использовать `get_atom_on_turf()`.

2021-12-14 02:04 UTC, quardbreak commented on code/datums/chatmessage.dm
> +	message.maptext_x = (CHAT_MESSAGE_WIDTH - owner.bound_width) * -0.5
~~Забыл про эту строчку. Тут нужно поемянть на `pixel_w`.~~ Не важно.

2021-12-14 02:04 UTC, quardbreak commented on code/game/objects/items/devices/megaphone.dm
> +					if(O.get_preference_value(/datum/client_preference/runechat) == GLOB.PREF_YES && !O.is_deaf())
Проверку на глухоту можно переместить в `create_chat_message()`, только если будешь расширять функционал руначата под вывод эмоций, нужно чтобы проверка на глухоту не блокировала их вывод.

2022-04-15 15:48 UTC, kreeperHLC commented
Конфликты

2022-06-12 13:39 UTC, Zert0X commented
Неактуально.

2022-06-12 13:39 UTC, closed without merging