Removes absence of RIGs' GC handling
ChaoticOnyx/OnyxBay pull request #7206
Opened 2021-12-17 17:29 UTC by TobyThorne

Кто бы ни писал РИГи, на GC он забил огромный болт и решил с ним взаимодействовать вообще никак. В итоге ни РИГ, ни модули из него не удалялись, выдавая по ~20 строчек рантаймов.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-17 17:33 UTC, TobyThorne commented
вот бы отучить линтер орать на код, который в ПРе не трогается мда

2021-12-17 20:02 UTC, Doster-d requested changes

2021-12-17 20:02 UTC, Doster-d commented on code/modules/clothing/spacesuits/rig/modules/computer.dm
> +/obj/item/rig_module/datajack/Destroy()
А че два Destrpy или я чего-то не понял?

2021-12-18 08:53 UTC, Doster-d approved these changes, later dismissed

2021-12-20 11:47 UTC, igorsaux commented on code/modules/clothing/spacesuits/rig/rig.dm
>  	STOP_PROCESSING(SSobj, src)
В пару `..()` выше уже происходит стоп процессинг
```suggestion
```

2021-12-23 05:03 UTC, Doster-d approved these changes

2021-12-24 12:03 UTC, igorsaux approved these changes

2021-12-24 12:06 UTC, merged