tweak(artlibrary): now using safe query
ChaoticOnyx/OnyxBay pull request #7260
Opened 2021-12-24 14:35 UTC by Doster-d

close #7259

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-24 14:51 UTC, igorsaux requested changes
А второй не обернут

2021-12-27 22:15 UTC, Doster-d commented
Теперь можно вытащить канвас из бук биндера.

Мержить только, когда ~~Эпикус проснется~~ хостер добавит ~~злоебучию~~ таблицу

2021-12-28 06:43 UTC, TobyThorne approved these changes

2021-12-30 09:48 UTC, igorsaux approved these changes

2021-12-30 09:57 UTC, merged