Removes vending machines' quality assurance
ChaoticOnyx/OnyxBay pull request #7300
Opened 2021-12-29 06:07 UTC by TobyThorne

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2021-12-29 13:29 UTC, Doster-d approved these changes, later dismissed

2021-12-29 13:49 UTC, igorsaux requested changes

2021-12-29 13:49 UTC, igorsaux commented on code/game/machinery/vending.dm
> +		take_damage(max_health)
Блен ну может тут лучше использовать переменную `mapload`
https://github.com/ChaoticOnyx/OnyxBay/blob/5e513ff7100657d4e60ce6e3b8c39c8a905cb366/code/game/atoms.dm#L51-L58

2021-12-29 14:10 UTC, Doster-d commented on code/game/machinery/vending.dm
> +		take_damage(max_health)
Можно еще в лейт инитиалайз засунуть, вроде.

2021-12-29 19:15 UTC, TobyThorne commented on code/game/machinery/vending.dm
> +		take_damage(max_health)
ничего не понял, а что тут с маплоадом сделать

2022-01-11 11:27 UTC, Doster-d approved these changes

2022-01-11 11:28 UTC, Doster-d commented
Ай блять

2022-01-22 03:49 UTC, HonkyDonky commented
Кокфликты.

2022-03-07 12:04 UTC, kreeperHLC commented
Конфликты

2022-06-23 23:09 UTC, kreeperHLC commented
Конфликты с января не решаются, Драфт сдох

2022-06-24 10:14 UTC, kreeperHLC commented
Ну сдох и сдох, чего бухтеть то. Захочет автор переоткрыть с решенными конфликтами - откроет.

2022-06-24 10:14 UTC, closed without merging