Убрал интент ходьбы когда тебя грабают
ChaoticOnyx/OnyxBay pull request #7311
Opened 2021-12-30 12:28 UTC by Srankl1n

Сабж. Чё, когда тебя за жопу грабают тоже неистовое желание ПОХОДИТЬ? Если что-то сломал - скажете.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Убрал валк-интент при грабе.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-01-02 09:24 UTC, Doster-d requested changes

2022-01-02 09:24 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_helpers.dm
> -		return 1
Верни ретурн, там может быть код завязанный на это и замени 1 на TRUE

2022-01-02 09:24 UTC, Doster-d commented on code/modules/mob/living/carbon/human/human_helpers.dm
>  		return 0
```suggestion
 		return FALSE
```

2022-01-02 09:43 UTC, Doster-d approved these changes

2022-01-11 07:22 UTC, TobyThorne approved these changes

2022-01-11 08:14 UTC, merged