fix(xeno-voidsuits)
ChaoticOnyx/OnyxBay pull request #7342
Opened 2022-01-04 21:09 UTC by Shirlineyn

Пофиксил названия иконок в моделях войдсьютов, переделанных под ксеносов, и удалил дубликаты, что позволило им отображаться на персонаже корректно(раньше показывался стандартный сьют). Также добавил отдельные бодибилды для скреллов, чтобы добавить в них собственно файлы с иконками для скреллов.

fix #7309
fix #6853
fix #1236

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Пофиксил модельки войдсьютов, переделанных под ксеносов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-01-04 21:11 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/body_build.dm
> +		"slot_suit"      = 'icons/inv_slots/suits/mob_skrell.dmi',
а нафига? у них контур точно такой же, как в людей

2022-01-04 21:19 UTC, Shirlineyn commented on code/modules/mob/living/carbon/human/body_build.dm
> +		"slot_suit"      = 'icons/inv_slots/suits/mob_skrell.dmi',
"slot_suit"      = 'icons/inv_slots/suits/mob_skrell.dmi',

2022-01-22 04:07 UTC, HonkyDonky approved these changes
Я искренне надеюсь на то, что автор проверил свои изменения локально. Всё-таки баг не очень приятный.

2022-01-27 14:19 UTC, kreeperHLC approved these changes

2022-01-28 15:56 UTC, TobyThorne requested changes
Реализация кринж, используются какие-то древние спрайты, выглядящие абсолютно отлично от их хуманских аналогов. Надо перекрашивать.

2022-01-30 10:52 UTC, Shirlineyn commented
Не согласен, это то, что и так должно было работать, но просто было криво адаптировано. Спрайты уже есть в билде, а то, какие они - вопрос отдельного иссуя. Данный ПР просто фиксит код.

2022-03-07 12:04 UTC, kreeperHLC commented
Мерж конфликты

2022-05-04 15:56 UTC, kreeperHLC commented
Сколько времени ничего от автора не слышно. Накидываю stale

2022-05-04 19:00 UTC, TobyThorne commented
Конфликты + уже отрисовали смешные спрайты. Неактуало4ка.

2022-05-04 19:00 UTC, closed without merging