Лавгивер ХоСу с ВГ.
ChaoticOnyx/OnyxBay pull request #7378
Opened 2022-01-11 15:18 UTC by Srankl1n

https://youtu.be/0JnpynfwU70

Теперь у ХоСа вместо респрайтов пушек, на которых даже задание не падает антагам по-настоящему уникальное оружие.
Features: говорящая пушка с ДНК-замком, различные режимы стрельбы, которые переключаются по голосу и подрыв неудачливого ассистента, который всё же смог выбить пушку у вас из рук. Теперь чтобы погрифонить вам нужно отыгрывать роль переключателя режимов огня. Невероятно ролеплейно, не так ли?

Перед тем как перейти к стрельбе, нужно дать пушке свой ДНК через альт-клик или ПКМ.
Если какой-то гандон попробует взять лавгивер в руки и пострелять - его лишь контузит взрывом, а сам лавгивер попадёт в царство вечное. Контрится доступом СБ.

Пушка имеет магазин на 25 снарядов. На каждый отдельный режим выделяется по 5 зарядов.
Достаточно запихнуть магазин в зарядник, чтобы восполнить запас.

Есть пять режимов стрельбы - стан, лазер, рапид, флеш, бронебойный. Поясню только за те, что не селф-экспланатори.
Рапид - ~18 дамага, низкая пробиваемость, за один заряд выпускает 3 пули. Крауд-контроль никогда не был таким веселым!
Бронебойный - род от рельсы, только без стана, имеет высокое пробитие брони и долгий делей по стрельбе. Мухобойка на минималках.

Режимы меняются ТОЛЬКО благодоря голосовым командам. Ну, если я не наговнокодил конечно.
Ключевые слова:
стан - stun, taser, стан, тазер, оглушающий
лазер - laser, lethal, beam, лазер, луч, летал
рапид - rapid, auto, рапид, авто, автоматический
флеш - flash, signal, флеш, сигнальный
бронебойный - armor piercing, ap, бронебойный, бб

Так, ну вроде бы все описал по поводу пушечки. Ожидаю критики по говнокоду и своих дебильных дизайнерских решений.

Выражаю благодарность архитектору за помощь по кодингу, хер бы я что-нибудь тут сделал.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Лавгивер из Судьи Дредда ХоСу вместо респрайтов ВП78 и лазерного карабина.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-01-11 15:42 UTC, Doster-d requested changes
Мне понравилось, сейчас отпилируем и будет хорошо.

2022-01-11 15:42 UTC, Doster-d commented on code/game/machinery/recharger.dm
> +		if(istype(lawgiver_magazine, /obj/item/ammo_magazine/lawgiver))
Друг, я же тебе говорил, тебе не надо создавать переменную, тебе нужно посмотреть ту, которая есть, для этого можно было изучить данный метод детальнее и посмотреть в определение.

```suggestion
		if(istype(charging, /obj/item/ammo_magazine/lawgiver))
```

2022-01-11 15:42 UTC, Doster-d commented on code/game/machinery/recharger.dm
> +		var/lawgiver_magazine = charging
```suggestion
```

2022-01-11 15:42 UTC, Doster-d commented on code/game/machinery/recharger.dm
> +			var/obj/item/ammo_magazine/lawgiver/L = lawgiver_magazine
```suggestion
			var/obj/item/ammo_magazine/lawgiver/L = charging
```

2022-01-11 15:42 UTC, Doster-d commented on code/modules/projectiles/ammunition.dm
> +		. += "\nThere [(stored_ammo.len == 1)? "is" : "are"] [stored_ammo.len] round\s left!"
Тут надо использовать функцию, вместо переменной, она оптимизирование
```suggestion
		. += "\nThere [(length(stored_ammo) == 1)? "is" : "are"] [length(stored_ammo)] round\s left!"
```

2022-01-11 15:42 UTC, Doster-d commented on code/game/machinery/recharger.dm
> +					charged_amount += 1
Что если у нас ситуация разряженной "батареи", то у нас за один условный тик заряжается, я предлагаю создать вне цикл переменную в нее записать актив_повер_юзач и уже тут уменьшать на 1 при каждом проходе, если при проходе наша переменная меньше или равно 0, то мы ломаем цикл (break).
Я думаю, что это круто и справедливо.

2022-01-11 15:42 UTC, Doster-d commented on code/modules/projectiles/guns/projectile.dm
> +	if(getAmmo() > 0)
Мы ломаем ситуация для других пушек, когда у нас 0 патронов.
Как я тебе писал, тебе надо в определение пушки (в этом файле) сделать переменную, например, display_default_ammo и присвоить ее TRUE (var/display_default_ammo = TRUE)
И в этой проверке ее проверять
А в лавгивера эту переменную поставить на FALSE в определение (display_default_ammo = FALSE)
```suggestion
	if(display_default_ammo)
```

2022-01-11 15:42 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		to_chat(usr, "<span class='notice'>You submit a DNA sample to \the [src].</span>")
```suggestion
		to_chat(usr, SPAN("notice", "You submit a DNA sample to \the [src]."))
```

2022-01-11 15:42 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +			to_chat(usr, "<span class='notice'>You erase the DNA profile from \the [src].</span>")
```suggestion
			to_chat(usr, SPAN("notice", "You erase the DNA profile from \the [src]."))
```

2022-01-11 15:42 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +			audible_message("<b>\The [src]</b> reports, \"[uppertext("[F.name].\"")]")
Может добавить еще сообщение, что это у нас новый режим?

2022-01-11 15:42 UTC, Doster-d commented on code/modules/projectiles/projectile/bullets.dm
> +/obj/item/projectile/bullet/pistol/lawgiver //for rapid-fire mode
Лучше комментарии помещать перед кодом, это хорошая практика.

2022-01-11 15:43 UTC, Doster-d requested changes

2022-01-11 15:43 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +/obj/item/gun/projectile/lawgiver/equipped(M as mob, hand)
```suggestion
/obj/item/gun/projectile/lawgiver/equipped(mob/M, hand)
```

2022-01-11 16:06 UTC, Zert0X commented
Режимы меняются ТОЛЬКО благодоря голосовым командам. Ну, если я не наговнокодил конечно.
Ключевые слова:
стан - stun, taser, стан, тазер, оглушающий
лазер - laser, lethal, beam, лазер, луч, летал
рапид - rapid, auto, рапид, авто, автоматический
флеш - flash, signal, флеш, сигнальный
бронебойный - armor piercing, ap, бронебойный, бб


Не геймдизайнер, но вижу отчётливую проблему с только голосовыми командами:
1. Немые персонажи
2. Случайное использование слова в тексте переключит пушку в режим*

* Если в коде не прописано условие нахождения в руке

2022-01-11 16:07 UTC, Doster-d commented
Там нужно фразу сказать исключительно из этих слов.

2022-01-11 16:10 UTC, Doster-d commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +	return
```suggestion
	unload_ammo(user)
```
Еще один способ вытащить магазин не помешает

2022-01-11 16:32 UTC, DarkHunter7756 commented
Наконец-то пушка, для использования которой проще создать 5 макросов 😏

2022-01-11 16:55 UTC, FloweYStyle commented
Лавгивер чат маленько засирает конечно.

![unknown (1)](https://user-images.githubusercontent.com/77331370/148986692-c9d39b92-7b7f-4395-90b0-58ec3fa6779f.png)

2022-01-11 17:40 UTC, NefrNerf commented
Что я думаю по лавгиверу:
- Это должен быть пистолет вместо ВП
- Он не должен заменять винтовку
- Не должно быть подрыва
- Всем без доступа хоса доступен только флеш режим
- Менять режим может только человек с доступом хоса
- не должно быть ДНК замка
Режимы: 
- рельса должна тратить энергию и патроны
- рапид должен тратить энергию и патроны

2022-01-11 17:43 UTC, DarkHunter7756 commented
То есть мы делаем очередной аналог пистолету детектива, но с блокировкой доступа?

2022-01-11 17:43 UTC, FloweYStyle commented
Сейчас я распишу, почему Нефр не прав.

2022-01-11 17:56 UTC, FloweYStyle commented
> Это должен быть пистолет вместо ВП

Чтобы у нас была имбовая энерговинтовка вместе с лавгивером, который ещё лучше его прошлого аналога? Лавгивер сейчас даёт практически всё, что давал ВП и энерговинтовка. Никакого смысла оставлять дополнительную личную винтовку целому человеку с наличием лавгивера.

> Он не должен заменять винтовку

Почему не должен? У него весь функционал винтовки за исключением лазерных болтов, которые вообще должны были быть фичей лазерных пушек из арсенала.

> Не должно быть подрыва?

Опять таки почему не должно быть? Взрыв во первых достойная мера предосторожности от рандомных ассистентов с мылом и прочим говном. Во вторых взрыв порождает смешные случаи при каком нибудь грейтайде. Если и убирать взрыв, то заменять на что-то аналогичное, ибо смысл в нанесении урона человеку, который лавгивер использовать не должен был.

> Всем без доступа хоса доступен только флеш режим.

Реально не понимаю, откуда ты это взял и чем руководствовался. Поясни.

> Менять режим может только человек с доступом хоса

Поясни.

> не должно быть ДНК замка

Это одна из фишек лавгивера и её не должно быть? Пояснишь?

2022-01-11 18:07 UTC, NefrNerf commented
> Чтобы у нас была имбовая энерговинтовка вместе с лавгивером, который ещё лучше его прошлого аналога? Лавгивер сейчас даёт практически всё, что давал ВП и энерговинтовка. Никакого смысла оставлять дополнительную личную винтовку целому человеку с наличием лавгивера.

Я считаю, что пистолет не должен быть по мощности как винтовка и по хорошему, это должен быть да, сильный пистолет но с недостатками, такими как потребление энергии и патронов. Энерговинтовка сейчас - хороший крауд контроль 3 стансферами и неплохое оружие с болтами.

> Почему не должен? У него весь функционал винтовки за исключением лазерных болтов, которые вообще должны были быть фичей лазерных пушек из арсенала.
С чего ты это взял, лично Тоби на ушко нашептал?

> Опять таки почему не должно быть? Взрыв во первых достойная мера предосторожности от рандомных ассистентов с мылом и прочим говном. Во вторых взрыв порождает смешные случаи при каком нибудь грейтайде. Если и убирать взрыв, то заменять на что-то аналогичное, ибо смысл в нанесении урона человеку, который лавгивер использовать не должен был.

Подрыв такого важного предмета, как мера защиты от ассистентов - бред, так как если предмет защищать то почему он не ебет током при взятии? Да и я против, чтобы оружие - инструмент который должен быть универсален локался у нас настолько сильно. Если вводить такой сильный лок этой пушке, то нужно и всем офицерским более слабый.

> Реально не понимаю, откуда ты это взял и чем руководствовался. Поясни.
Замена взрыва на это - использование предмета в его ограниченном виде.

> Это одна из фишек лавгивера и её не должно быть? Пояснишь?
Давайте тогда доминатор спиздим с ТГ и будут у нас сбшники ходить как в Психопаспорте

2022-01-11 18:30 UTC, FloweYStyle commented
> Я считаю, что пистолет не должен быть по мощности как винтовка и по хорошему, это должен быть да, сильный пистолет но с недостатками, такими как потребление энергии и патронов. Энерговинтовка сейчас - хороший крауд контроль 3 стансферами и неплохое оружие с болтами.

Так он и не настолько мощный, как та же винтовка с 10 болтами лазерными. А энерговинтовка нихуя не балансная пушка с 2 стансферами при выстреле, так ещё и в добавок к этому стреляет болтами. Я ещё раз повторюсь, что у лавгивера по сути тот же набор, что и у винтовки, есть и убить (рапид лазер бб), так и оглушить (стан флеш).

> С чего ты это взял, лично Тоби на ушко нашептал?

С того, что у энерговинтовки изначально было всего два режима, это лазер и стансферы. Болты тогдашними временами, называемые слагами имелись только у лазерных пушек с арсенала, либо РнД.

> Подрыв такого важного предмета, как мера защиты от ассистентов - бред, так как если предмет защищать то почему он не ебет током при взятии?

Заменить взрыв током как вариант, однако защищать надо не лавгивер, а ХоСа или любого другого офицера, который носил этот лавгивер.

> Замена взрыва на это - использование предмета в его ограниченном виде.

Ты видимо не совсем понял принцип работы лавгивера. Он может быть установлен на ДНК определённым человеком, который в итоге будет иметь к нему полный доступ. При попытке использовать этот пистолет другими людьми, выстрел провоцирует взрыв, однако его можно избежать, если носитель имеет доступ офицера и выше. Взрывать офицеров он не станет.

> Давайте тогда доминатор спиздим с ТГ и будут у нас сбшники ходить как в Психопаспорте

Давай.

2022-01-11 18:33 UTC, Zert0X commented
чёт имба пушка...

2022-01-11 18:37 UTC, FloweYStyle commented
А каким боком она имба? Прежде чем называть пушку имбой - давайте вспомним бывшую ХоСа - энерговинтовку с 10 болтами и двойными стансферами с выстрела. У лавгивера суммарно урона меньше, чем у винтовки. Точно имба пацаны. 👏

2022-01-11 18:42 UTC, Firefroge commented
Я не ебу как на вашем гитхабе делать цитаты так что так напишу кратко

Нынешняя винтовка кал хуйни ебаной
Это просто респрайт лазера с функцией тройного огня, что нихуя не делает её особенной

Что-то особенное должно быть у человека, который ну не за хуй собачий получил пост ХоСа.
А если к его оружию каждый еблан будет иметь доступ - давайте с мехов тогда спиливать днк-локи.

Доёб до лавгивера просто потому-что.
/thread

2022-01-11 18:46 UTC, NefrNerf commented
> Так он и не настолько мощный, как та же винтовка с 10 болтами лазерными. А энерговинтовка нихуя не балансная пушка с 2 стансферами при выстреле, так ещё и в добавок к этому стреляет болтами. Я ещё раз повторюсь, что у лавгивера по сути тот же набор, что и у винтовки, есть и убить (рапид лазер бб), так и оглушить (стан флеш).

Винтовка - чисто энергетическое оружие, если исчерпал заряды - пиздуй заряжать. Винтовка - большое оружие, в кобуру или пояс его не сунешь.

> С того, что у энерговинтовки изначально было всего два режима, это лазер и стансферы. Болты тогдашними временами, называемые слагами имелись только у лазерных пушек с арсенала, либо РнД.

Она была недобафана, так как аналог более сильной ЕРТ винтовки и отсутствие у ХОСа не было прям задумано.

> Ты видимо не совсем понял принцип работы лавгивера. Он может быть установлен на ДНК определённым человеком, который в итоге будет иметь к нему полный доступ. При попытке использовать этот пистолет другими людьми, выстрел провоцирует взрыв, однако его можно избежать, если носитель имеет доступ офицера и выше. Взрывать офицеров он не станет.

Вот в этом и бред, что устанавливается на доступ определенного человека по ДНК, это не мех - огромная машина смерти, чтобы делать лок, у нас есть куча более важных вещей на которых нет ДНК лока

2022-01-11 19:13 UTC, TimErmolt commented
> Винтовка - чисто энергетическое оружие, если исчерпал заряды - пиздуй заряжать. Винтовка - большое оружие, в кобуру или пояс его не сунешь.

Уменьшенный размер законодарителя и всё из этого вытекающее балансируется тем, что им довольно сложно пользоваться. На каждый режим без перезарядки всего 5 выстрелов -- это меньше чем у пистолета и тем более чем у винтовки. Смена режима голосом -- уникальная механика и непростая в использовании: пока пишешь сейлог на смену режима, можно успеть поймать шальной лазер или пулю. Макросы, конечно, существуют, но по ним тоже нужно думать головой, понимая, какой режим тебе нужен, и жать на правильную кнопку.
По тому же принципу у нас в билде уже забалансен М2019 -- если умеешь им пользоваться, то можешь раскидывать всех в соло (и то непросто), но если нет, то от тебя пользы не больше чем от голого ассистента с термал-очками. Тут всё так же, разве что у ХоСа останется стандартный еган. Всё равно именное оружие он применять не сможет, если не умеет.

> Вот в этом и бред, что устанавливается на доступ определенного человека по ДНК, это не мех - огромная машина смерти, чтобы делать лок, у нас есть куча более важных вещей на которых нет ДНК лока

Если в билде нет вещей, кроме мехов, с привязкой по ДНК, это не повод не делать таких вещей. Почему не ввести разнообразия? Это ведь и против охраны можно использовать, если ХоСа нет или просто никто не трогал законодаритель, ограбив его офис и привязав пушку к своему ДНК. В то же время взрыв пушки при попытки использовать её без доступа -- наказание для мало думающих антагонистов (и это тоже с толикой героизма можно обратить против охраны, лишив обронившего оружие ХоСа его пушки).

2022-01-11 19:21 UTC, NefrNerf commented
> Уменьшенный размер законодарителя и всё из этого вытекающее балансируется тем, что им довольно сложно пользоваться.

Я тебе с гарантией могу сказать, никто в здравом уме не будет никогда делать оружие которые переключается голосом. Это против логики, да может это и оригинально, но в плане использования полный бред, что в ИРЛ что в игре.

> Если в билде нет вещей, кроме мехов, с привязкой по ДНК, это не повод не делать таких вещей. Почему не ввести разнообразия? 

По той же причине, почему не вводиться ЕРП панель, не соответствует направлению и задачам.

2022-01-11 19:23 UTC, DarkHunter7756 commented
Может мы просто выдадим ХоСу интегральный принтер и он сам сделает себе пушку мечты? 
![image](https://user-images.githubusercontent.com/76823962/149007838-dd63d987-9ec1-47c2-8118-d612c6fd2474.png)

2022-01-11 19:25 UTC, NefrNerf commented
Да и прежде чем вводить разнообразие, нужно спросить а нужно ли оно, какой в этом смысл? На мехах есть днк лок по причине того, что это ебучий экзоскелет, для которого нужна уйма всего. У капитана нет лока на лазере, нет лока на диске, нет лока на серверах РНД. Нет лока на гипоспрее. А вот на одной пушке ХОСа, должен быть, очень странно.

2022-01-11 19:26 UTC, DarkHunter7756 commented
> Я тебе с гарантией могу сказать, никто в здравом уме не будет никогда делать оружие которые переключается голосом. Это против логики, да может это и оригинально, но в плане использования полный бред, что в ИРЛ что в игре.

Ок, чё 
https://www.vesti.ru/article/1551174
![image](https://user-images.githubusercontent.com/76823962/149008240-0c15e851-2c3d-435f-bf07-cafbcd133ae5.png)

2022-01-11 19:30 UTC, Zert0X commented
> > Я тебе с гарантией могу сказать, никто в здравом уме не будет никогда делать оружие которые переключается голосом. Это против логики, да может это и оригинально, но в плане использования полный бред, что в ИРЛ что в игре.
> 
> Ок, чё https://www.vesti.ru/article/1551174 ![image](https://user-images.githubusercontent.com/76823962/149008240-0c15e851-2c3d-435f-bf07-cafbcd133ae5.png)

и как удачно? За пять то лет...

2022-01-11 19:30 UTC, No-Tips commented
Так и вижу винтовки будущего с Гугл-Ассистентом

"Окей, гугл, режим аннигиляции младенцев"
"Принято, анигилирую"

Крутая пушка с крутым и уникальным механом. Я бы ещё, конечно, впилил возможность самому устанавливать кодовые слова для режимов, но это дело вторичное

2022-01-11 19:32 UTC, Srankl1n commented
хахахаха, пойду спать

2022-01-11 20:36 UTC, FloweYStyle commented
> Винтовка - чисто энергетическое оружие, если исчерпал заряды - пиздуй заряжать. Винтовка - большое оружие, в кобуру или пояс его не сунешь.

Ну так с лавгивером же всё тоже самое. Закончились заряды - пиздуй заряжать. А его компактность балансируется гораздо менее значимым уроном, в отличии от той же винтовки. К тому же лавгивером трудно управлять с его режимами.

> Я тебе с гарантией могу сказать, никто в здравом уме не будет никогда делать оружие которые переключается голосом. Это против логики, да может это и оригинально, но в плане использования полный бред, что в ИРЛ что в игре.

А я напоминаю, что у нас космостанция, а именно тринадцатая и всякая логика из реальной жизни полностью отпадает в этой игре. Мы заходим сюда получить удовольствие, а не работать вторую смену, где максимально правдоподобная реальность. А в игре использование такой пушки далеко не бред и на самом деле весьма увлекательно чередовать режимами с помощью голоса.

> По той же причине, почему не вводиться ЕРП панель, не соответствует направлению и задачам. 

Ну это вообще платина, ты сравнил панель для ебли с установлением ДНК детектора в пушке, которая по сути своей единственный прототип на станции, который имеется только у ХоСа.

2022-01-11 20:38 UTC, DarkHunter7756 commented
Что вы все начали говорить про сложность в управлении? 5 макросов на клавиатуре (на которой обычный человек держит хоткеи для удобства) и всё

2022-01-11 20:43 UTC, BooJ1K commented
Добавление пушки с голосовым управлением позволяет: трейтерам, лингам и нинжам использовать свои девайсы для смены голоса, порождая больше смешных моментов в перестрелках с ХоСом.

2022-01-11 20:44 UTC, FloweYStyle commented
> Что вы все начали говорить про сложность в управлении? 5 макросов на клавиатуре (на которой обычный человек держит хоткеи для удобства) и всё 

Куда ты эти 5 макросов поставишь? Их только на вторую половину клавиатуры переносить, а туда надо дотягиваться пальцами. В затяжной перестрелке тебе ебало снесут, пока ты там пальцами клавиши ковырять будешь.

2022-01-11 20:46 UTC, DarkHunter7756 commented
У меня 20 макросов умещаются на клавиатуре в удобной для нажатия зоне, а ты говоришь про 5 )

2022-01-11 20:48 UTC, FloweYStyle commented
Дело не в том, найдёшь ли ты для пяти макросов место, дело в том, сможешь ли ты в перестрелке успевать дотягиваться до этих клавиш и успевать прожимать правильные режимы.

2022-01-12 06:55 UTC, Srankl1n commented
Охуеть, что происходит.
Начну с того, зачем я вообще выкатил лавгивер. Ну давайте посмотрим на вещи других глав - у СЕ РИГ, у РД реактивка (упд кто-то сказал что на бее у рд её нету, так что нужно будет впилить), у СМО гипоспрей, у капитана лазер, у ХоПа - иан. И лишь один ХоС с уебанскими респрайтами оружия, которое воровать синдикату - себя неуважать.
Лавгивер это УНИКАЛЬНАЯ ВЕЩЬ, присущая только ХоСу. Который есть смысл воровать со станции. Сука, серьёзно, главный противник антагов, и он для антагов чуть ли необязательная цель, так как в пулле вещей, которые антаги должны украсть, лишь штаны ХоСа. И в принципе эта штука идёт как и все предметы у глав - уникальная вещь, которая отличает главу от его подданых, кроме внешнего вида.
В прошлый раз с питоном была та же проблема - смысл воровать очередной хуев револьвер, если мы и так в аплинке его можем купить? Ну и еще смешнее то, что на него всё же было задание.

Говоря про ДНК-замок - нет, я его выпиливать не собираюсь и точка. Это уникальная фишка лавгивера, которая делает его лавгивером. Но прикручу возможность снять его ингейм - мне лично не нравится то, что на ВГ ДНК-лок снять невозможно, если сам юзер не захочет этого. Прикручу возможность емагом снять замки и при помощи мультитула с изоперчатками, возможно еще прикручу возможность отрезанными органами снимать ДНК-замок. 

Бабахкалку в принципе можно поменять на удар током, как в фильме. Энивей, удаление вещи, которую нужно украсть по заданию таким простым способом, всё же, криво.

Лавгивер будет заменять пистолет и карабин у ХоСа. Пистолет и карабин - не уникальные вещи, это масс-продуцед веапонс, которые воровать условным антагам нету смысла чисто исходя из логики. У ХоСа и так уже три пушки, алё.

Говоря о том, что лавгивер ведёт себя как винтовка - ну привет, блядь, вы живете на билде, где пуля 9мм точно такая же летальная, как и 7.62 (ЭТО ЛИШЬ ПРИМЕР). Да у него, блядь, дамаг меньше, чем у егана, который можно положить в кобуру.

Говоря про имбовость - вы, блядь, перед тем как говорить про имбовость хотя бы протестите его.
Рапид выстреливает 3 пули по 18.5 урона, что равно 55.5 урона, если все пули попадут, плюс низкая бронепробиваемость. Чё там со смешным карабином, который имеет в себе целых 20! стансфер вместе с лазерным режимом и болтером, который сжигает пятки к хуям с первого попадания. Ладно, со второго, сути не меняет.
Лазерный режим в лавгивере имеет лазеры на 25 дамага(если я конечно не забыл), я впилил лазерный режим лишь по одной причине - это единственнй режим на лавгивере, который позволяет стрелять через окна без особых проблем.
Это лишь примеры - остальное, будьте добры, проверьте уже ингейм.

Алсо, флеш-заряды я бы заменил на зажигательные снаряды, как на ВГ. Флеш в принципе-то ничем не отличается от стансферок - станит при стрельбе в ногу не хуже.

Проиграл со сравнения лавгивера с ЕРП системой. Что, уже не знаешь, что и сказать? Подумай хорошенько, друже.

2022-01-12 07:16 UTC, Zert0X commented
> Дело не в том, найдёшь ли ты для пяти макросов место, дело в том, сможешь ли ты в перестрелке успевать дотягиваться до этих клавиш и успевать прожимать правильные режимы.

смешной доёб, одних лишь макросов на нумпады напихать можно

2022-01-12 07:16 UTC, Zert0X commented
> ли ты в перестрелке успевать дотягиваться до этих клавиш и успевать прожимать правильные режимы.
успеешь ли ты в перестрелке ПИСАТЬ название нужного режима!?

2022-01-12 07:22 UTC, Zert0X commented on code/modules/projectiles/ammunition.dm
> +		. += "\nThere [(stored_ammo.len == 1)? "is" : "are"] [stored_ammo.len] round\s left!"
А что будет выводиться при max_ammo = 0? ПЛЮС если возникает ситуация где у пушки max_ammo = 0 то это явно баг...

2022-01-12 07:24 UTC, Zert0X commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		))
зачем глоб. лист если мы эти режимы нигде не фиксируем кроме этого файла?

2022-01-12 07:25 UTC, NefrNerf commented
Если убирать лишние слова, то сообщение выше можно свести к простым пунктам:
1. У хоса нет уникальной вещи, то что сейчас - не уникальная.
2. ДНК замок - неотъемлемая часть лавгивера и убирать его не собираешься
3. Можно изменить ДНК замок и сделать его снимаемым
4. Можно изменить удар взрыв на удар током
5. Пуля 9 мм и 7.62 убойны одинаково, что позволяет лавгиверу быть похожим по механике на винтовку
6. Лавгивер не имбовый по причине малого урона по сравнению с винтовкой
7. ЕРП механику нельзя приравнивать к ДНК локу

Собственно, отвечая по пунктам:
1. Да согласен, ХОСу нужно добавить особое оружие с уникальными характеристиками.
2. Я считаю, что это плохой подход, так как у нас полно других сверважных предметов на которых должен был бы быть ДНК замок.
3. Возможность снять замок в любом случае должна быть, хоть ДНК хоть нет
4. Взрыв пушки которую нужно украсть и вообще механика исчезновения такого предмета, если считать его важным выглядит странно, по этому да, нужно убирать и оставлять ток
5. Винтовка имеет ограничение по размеру а также выполняет основную функцию - эффективное задержание 3 стансферами. Получается вместо предмета который хорошо делает одну вещь, мы меняем его на предмет который плохо делает все.
6. Если я все правильно понял, то 5 зарядов на каждый режим, ну это выглядит странно. Любое другое энергетическое оружие имеет больший запас а некоторые еще и 2-3 режима. 
7. Любые механики сравнивать можно, вопрос в том, насколько конкретная вещь подходит билду в предложенной реализации.

2022-01-12 07:26 UTC, Zert0X commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		list(mode_name = "rapid",			fire_delay = 6,		ammo_per_shot = 1/3,	projectile_type = /obj/item/projectile/bullet/pistol/lawgiver,		burst = 3, screen_shake = 1, voice_activator = list("rapid", "auto"
Зачем костыль ввиде рапида, который по факту очередь. Если мы уже имеем burst

2022-01-12 07:29 UTC, Srankl1n commented on code/modules/projectiles/ammunition.dm
> +		. += "\nThere [(stored_ammo.len == 1)? "is" : "are"] [stored_ammo.len] round\s left!"
У лавгивера магазин немного иначе работает, чем у обычной пушки. Это нужно, чтобы тебе не показывало "there's 0 ammo left" на магазине от лавгивера. Спёр у ВГшников короче.

2022-01-12 07:30 UTC, Srankl1n commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		))
Юзается в коде магазина.

2022-01-12 07:30 UTC, Srankl1n commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		list(mode_name = "rapid",			fire_delay = 6,		ammo_per_shot = 1/3,	projectile_type = /obj/item/projectile/bullet/pistol/lawgiver,		burst = 3, screen_shake = 1, voice_activator = list("rapid", "auto"
Тут не понял.

2022-01-12 07:37 UTC, Srankl1n commented
> на важные айтемы нужны днк замки
На каких, например? Я повторюсь - ДНК-лок это сугубо фишка лавгивера. Суть не в важности этой пушки на станции.

> карабин лучше для арестов
Еган лучше. Субъективное мнение, как видишь.

> зарядов нету
Нихуя не понял. То есть ты хочешь оставить карабин, потому что скилл ишшу при игре за ХоСа?

2022-01-12 07:50 UTC, NefrNerf commented
ДНК лока нет на: диске/бомбе, лазере капитана, РИГах, а также гипоспрее и реактивной броне, которую ты хотел добавить
Да, что лучше - мнение субъективно. Но у нас есть объективные параметры такие как: размер предмета, его вес и куда его класть и лавгивер никак не подходит под характеристики пистолета в сравнении с другими образцами. 

> Нихуя не понял. То есть ты хочешь оставить карабин, потому что скилл ишшу при игре за ХоСа?
Я считаю, что это очень странное оружие, непрактичное, которые при стрельбе очередью в 3 патрона, имеет магазин на 5. При этом меняет режимы голосом.

2022-01-12 07:58 UTC, Zert0X commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		list(mode_name = "rapid",			fire_delay = 6,		ammo_per_shot = 1/3,	projectile_type = /obj/item/projectile/bullet/pistol/lawgiver,		burst = 3, screen_shake = 1, voice_activator = list("rapid", "auto"
> Тут не понял.

у нас есть burst, очередь как у ПП, в который ты можешь указать сколько пулек за раз выпускать

2022-01-12 08:00 UTC, Zert0X commented on code/modules/projectiles/guns/projectile/lawgiver.dm
> +		list(mode_name = "rapid",			fire_delay = 6,		ammo_per_shot = 1/3,	projectile_type = /obj/item/projectile/bullet/pistol/lawgiver,		burst = 3, screen_shake = 1, voice_activator = list("rapid", "auto"
вопрос закрыт, тупой код пушки, со своей механикой считывания патронов

2022-01-12 08:06 UTC, Srankl1n commented
Зачем. ДНК. На диск(это кстати нюку сломает нахуй). На РИГ. На реактивку. На пневмошприц. Я бы еще понял на кэплазер, но суть-то в том что это буквально трофейник, и кто-то посчитал что на него ДНК-замок не нужен. Давай тогда нюкерам дадим возможность взрывать станцию к хуям как только они к станции подлетят. Ведь им же не нужен диск, чтобы взорвать станцию, верно? Суть не в безопасности или перед тем, что его просто спиздить могут - ДНК лок можно просто отключить при помощи правильных рук. Суть в том, что я пытаюсь реализовать пушку из Дредда со всеми вытекающими. Как говорится, уникальные фичи не нужны, потому что уникальные.

Мне кажется, тебе уже давно пора осознать тот факт, что пистолет и лавгивер тут никак не связаны. А говоря про размеры - еган в кобуру можно пихнуть, а хуярит он не хуже лазерки ХоСа, что со стороны урона, что со стороны станилки. Да, у лазкарабина шансы выше на стан, но не настолько. Так в чем же доеб?

>непрактичное оружие

Скилл ишшу. На ВГ ни у кого нету проблем с ней, а местные игроки уже скачали и проверили как пушка работает.

2022-01-12 08:12 UTC, Zert0X commented
> Зачем. ДНК. На диск(это кстати нюку сломает нахуй). На РИГ. На реактивку. На пневмошприц. Я бы еще понял на кэплазер, но суть-то в том что это буквально трофейник, и кто-то посчитал что на него ДНК-замок не нужен. Давай тогда нюкерам дадим возможность взрывать станцию к хуям как только они к станции подлетят. Ведь им же не нужен диск, чтобы взорвать станцию, верно? Суть не в безопасности или перед тем, что его просто спиздить могут - ДНК лок можно просто отключить при помощи правильных рук. Суть в том, что я пытаюсь реализовать пушку из Дредда со всеми вытекающими. Как говорится, уникальные фичи не нужны, потому что уникальные.
> 
> Мне кажется, тебе уже давно пора осознать тот факт, что пистолет и лавгивер тут никак не связаны. А говоря про размеры - еган в кобуру можно пихнуть, а хуярит он не хуже лазерки ХоСа, что со стороны урона, что со стороны станилки. Да, у лазкарабина шансы выше на стан, но не настолько. Так в чем же доеб?
> 
> > непрактичное оружие
> 
> Скилл ишшу. На ВГ ни у кого нету проблем с ней, а местные игроки уже скачали и проверили как пушка работает.

местные игроки молодцы, но по поводу непрактичного оружия согласен, выглядит очень так себе. Предлагаю всё же дать выбор между энергопушкой и лавгивером.

2022-01-12 08:18 UTC, Srankl1n commented
> местные игроки молодцы, но по поводу непрактичного оружия согласен, выглядит очень так себе. Предлагаю всё же дать выбор между энергопушкой и лавгивером.

Вау, никто даже не пытался проверить как пушка работает в бою, зато уже делают выводы о непрактичности.
Знаете, как это зовётся? Скилл ишшу. Дай ты робастеру хоть кусок раскаленной арматуры вместо лавгивера/карабина и он её тебе глубоко в жопе прокрутит. Выбор пушки это еще один аутизм, из-за которого нормально не выйдет объяснить, почему антаги должны воровать масс-продуцед пушку. Короче, это небольшая цена за уникальность.

2022-01-12 08:19 UTC, NefrNerf commented
Я привел эти предметы, как примеры уникальных вещей на станции, на которые в теории можно было бы поставить какую-то защиту, если мы беспокоимся об их сохранности. Но как ты сам сказал, ты захотел в игру пушку Дредда, что само по себе ничего плохого не несет, но реализация ДНК замка просто потому, что он был на оригинале я считаю плохой. Хорошо, предположим мы делаем неортодоксальную пушку размером с пистолет, допустим. Какая у нее ниша, что она делает хорошо? В любом мире, выдуманном или нет, разные типы оружие предназначены для разного. 
- Она хорошо станит?
- Хорошо убивает?
- Бой на короткие дистанции или длинные? 
Если винтовка и пистолет дают четкие ответы на эти вопросы, потому что у них простые механики, то что тут?
Если убрать голосовую активацию, то еще пойдет. Получится несколько режимов для задержания и убийства.

2022-01-12 08:29 UTC, Zert0X commented
>Скилл ишшу. 

Скилл ишшу круто, не забывай про удобство переключение режимов которое равно нулю, если игрок без макросов гоняет, то быстро во время боя переключить режим становиться почти невозможно. В отличии от той же пушки простым нажатием pgdwn на клаве.

>из-за которого нормально не выйдет объяснить, почему антаги должны воровать масс-продуцед пушку. 

А зачем антаги должны воровать трусы глав?

>Дай ты робастеру хоть кусок раскаленной арматуры вместо лавгивера/карабина и он её тебе глубоко в жопе прокрутит

Тем более, зачем тогда робастному хосу какая-то ультрапушка, пускай бегает с петушителем.

2022-01-12 08:29 UTC, Srankl1n commented
Давай я за тебя попробую ответить на более конкретный вопрос вместо "оно тазерит или не???"
Скажи мне - эта пушка ДОЛЖНА ПОЛНОСТЬЮ заменять лазерный карабин, который стреляет по 2 стансферки, стреляет лазером и болтером, который сжигает пятки к хуям? Я тогда могу просто респрайт карабина сделать, лол.
Я расписал режимы работы лавгивера, будь добр - ознакомься с ними.

2022-01-12 08:35 UTC, Zert0X commented
> Давай я за тебя попробую ответить на более конкретный вопрос вместо "оно тазерит или не???" Скажи мне - эта пушка ДОЛЖНА ПОЛНОСТЬЮ заменять лазерный карабин, который стреляет по 2 стансферки, стреляет лазером и болтером, который сжигает пятки к хуям? Я тогда могу просто респрайт карабина сделать, лол. Я расписал режимы работы лавгивера, будь добр - ознакомься с ними.

ознакомились и пытаемся до тебя донести, что крайне спорные решения.

- Рапид на 3/5 патронов, а зачем? Ложить тех у кого аблативка? Мне тогда легче в поясе ВПтакскать с парой обойм в подсумке.

- Флеш +5 стансфер.

- Бронебойный, лан круто, но опять же зачем, так ли часто у нас антаги бегают в брониках? Нюка? Ну так против нюки используют арсенал, а там игрушки повеселее.

- Лазер с лоудемейджем, тоже не понятная штука темболее на 5 выстрелов, легче таскать обычный еган в рюкзаке или на костюме.

- Стан, ну это стан.... спору нет испоганить не получиться, по факту карманный тазер

Итого странная пушка с 5 патронами на режим, которая умеет всё и понемногу, практического применения я у неё не особо вижу, плюс неудобство переключения режимов голосом, для игроков без макросов.

2022-01-12 08:39 UTC, Srankl1n commented
Я буду так до бесконечности пояснять. Скачай билд и проверь сам, как эта пушка работает.

2022-01-12 08:39 UTC, Zert0X commented
> Я буду так до бесконечности пояснять. Скачай билд и проверь сам, как эта пушка работает.

Скачал, не понравилось. Или ты думаешь что я тут на пустом месте это пишу?

2022-01-12 08:39 UTC, Srankl1n commented
Так скачал, что даже рапид не проверил, я за тебя рад.

2022-01-12 08:41 UTC, Zert0X commented
> Так скачал, что даже рапид не проверил, я за тебя рад.

Пять выстрелов по 3 патрона, извиняюсь не так написал 😅.

2022-01-12 08:51 UTC, Srankl1n commented
Неосиляторы набежали, какой ужас.

> макросы

Так может проблема макросов, а не моей пушки? Почему, блядь, на ВГ по этому поводу НИКТО не ноет? Все только рады тому, что есть охуенная, уникальная пушка.

> рапид говно

В чем заключается его бесполезность? В том, что он не сносит всем ебальники налево-направо, как наш смешной лазер в болт-режиме? В упор он тебя точно не оставит равнодушным.

> бронебойный типа крут но типа эээ..)

Ого, бронебойный бесполезный когда нет брони.

>лазер бесполезный

Опять неосилил то, что можно прошивать окна насквозь?

>флеш

Мне он тоже не нравится, буквально +5 стансферок. Я уже предлагал заменить на зажигательный, но пока не буду - у вас охуенный МК, который от поджёга начинает лагать как сука, а человек после тушения всё еще светится.

Объясни мне в чем странность пушки кроме того, что все, кроме тебя её осилили.

2022-01-12 08:57 UTC, Zert0X commented
> Объясни мне в чем странность пушки кроме того, что ты не можешь её осилить.

Странность пушки, в том что вместо одной пушки с лазером/станом, ты предлагаешь целый арсенал, который при правильном использовании убить может любого. Та же хосовская энергопушка легко контрилась аблятивкой, из-за чего тому приходилось таскать с собой ещё и пистолет. Твою же пушку законтрить можно только если убить хоса первее. Что при правильной комбинации режимов и таргет зон, фактически невозможно.

И опять же как там на ВГ не ноют и не используют макросы для лавгивера, я не знаю, ибо последний раз на ВГ я играл в 2015 году.
Удобство переключение режимов равно нулю, да при должной сноровке/макросах это можно будет сделать легко.
А что если хос немой?! О УЖАС.

2022-01-12 08:58 UTC, Zert0X commented
Ну а я не геймдизайнер и не овнер, вон говори с нефром, тобби, плином. Я спатт.

2022-01-12 09:02 UTC, Srankl1n commented
Тебе тоже придётся объяснить, неосиливших меньше будет.

> целый арсенал

Целый арсенал по пять патронов. Какой ужас, стреляет не хуже .50, да? Ведь так? Стансферами можно уебать буквально любого, так что как-то не.
Насчет контринга албятивкой не уверен, у болтера вроде пробитие брони выше.
Короче, поверь мне "целый арсенал" тут только заключается лишь в одной стансферке.

> Удобство переключение режимов равно нулю, да при должной сноровке/макросах это можно будет сделать легко.

Поздравляю, ты ответил на свой же вопрос. Кто без должной сноровки играет за ХоСа, скажи мне будь добр.

> немой хос

Надеюсь, это была шутка.

2022-01-12 09:06 UTC, kreeperHLC commented
Отключаем стингом генки ХоСу голос, чтобы он мог использовать только уже выбранный режим. Круто же.

2022-01-12 15:13 UTC, FloweYStyle commented
> смешной доёб, одних лишь макросов на нумпады напихать можно

Это не доёб, я не жалуюсь.

> успеешь ли ты в перестрелке ПИСАТЬ название нужного режима!?

Успею конечно, это хуйня вопрос. На локалке я уже пробовал и с макросами, так и без.

> Винтовка имеет ограничение по размеру а также выполняет основную функцию - эффективное задержание 3 стансферами. Получается вместо предмета который хорошо делает одну вещь, мы меняем его на предмет который плохо делает все.

Пошли на карту джунглей в гейтвее, ты себе выдашь обоссаный карабин, а я себе лавгивер и мы посмотрим, как я тебе ебало отшибу, эффективный полицай хуев. Карабин по своим размерам помимо "эффективного задержания" (ради которого можно стрелять банально в пятку и здесь уже не играет роли, сколько у тебя стансфер с выстрела выходит) ещё и прошивает как бы болтами своими нихуёво. Я ещё не говорю про то, что у него аж целых 10 болтов (фактически столько же, сколько и у лазерного карабина с арсенала, который как пушка нужна чтобы [[УБИВАТЬ УБИВАТЬ УБИВАТЬ]]). Если у твоей винтовки киллерфича состоит в дополнительных двух стансферах с выстрела и это является причиной не заменять эту хуйню на лавгивер, то может быть пора сдавать позиции геймдизайнера, либо переставать нести какую-то хуйню, которую ты даже проверять не подумывал? >Получается вместо предмета который хорошо делает одну вещь, мы меняем его на предмет который плохо делает все. Получается что мы меняем очевидно унылую винтовку с болтами и стансферами на универсальное оружие с зарядами на каждый режим, под каждую ситуацию за исключением ионки против боргодаунов и синтетоёбов с довольно интересной методикой смены режима.

> Я считаю, что это плохой подход, так как у нас полно других сверважных предметов на которых должен был бы быть ДНК замок.

А теперь давайте взглянем на эти самые сверхважные предметы.

> ДНК лока нет на: диске/бомбе, лазере капитана, РИГах, а также гипоспрее и реактивной броне, которую ты хотел добавить

> диске/бомбе

Действительно, как же так получилось, что у нас нет ДНК лока на диске, который бы сломал нахуй некоторые режимы и даже со стороны логики это какая-то смешная и платиновая хуйня. ДИСК, который выполняет функцию ЛОКА, ведь без него боеголовку не запустишь, обязан иметь СВОЙ ДНК ЛОК? Что не менее хуёвее, боеголовка с уже имеющимся локом в виде КОДА и ДИСКА. Головой думать к сожалению не научились, пока уважаемый геймдизайнер притрагивался к клавиатуре.

> лазере капитана

Ну пушто билд говно, ибо на ТГ билде ебучее стекло к лазеру можно открыть картой капитана в отличии от нашего, а если стекло сломается, то капитанская сразу закроется на болты и даст пожарную тревогу. Суммарно этакий замочек наружный.

> гипоспрее

Нахуя.

> реактивной броне

Нахуя.

> Я считаю, что это очень странное оружие, непрактичное, которые при стрельбе очередью в 3 патрона, имеет магазин на 5. При этом меняет режимы голосом.

Уважаемый геймдизайнер с так называемым "skill issue" не совладал с мощью данной пушки и сразу же начал ныть о его непрактичности. Несите нового.

> местные игроки молодцы

Согласен.

> по поводу непрактичного оружия согласен, выглядит очень так себе. Предлагаю всё же дать выбор между энергопушкой и лавгивером.

Ещё один человек с так называемым "skill issue". У тебя пушка с стансферами и флешпатронами, которая выдаёт пизды и лазером, и через броню, и очередью в ебало. Гораздо же интереснее иметь оружие со своей киллерфичей, чем нажимать одну кнопку для переключения режима "ЭФФЕКТИВНО ЗАДЕРЖАТЬ" "пострелять нормально" и "пострелять болтами". Да и как ты вообще собираешься делать ХоСу выбор между энергозалупой и лавгивером? Оставить ему обе пушки в шкаф? Как ты себе это представляешь?

> Она хорошо станит?
Хорошо убивает?
Бой на короткие дистанции или длинные?

Станит она так же, как и еган. Еган станит ахуенно если чо, т-варищ геймдизайнер.
Убивает не менее хорошо, попрёт и против брони, так и против стекла и ещё очередью в ебало пострелять гораздо.

> Бой на короткие дистанции или длинные?

Очень интересный и весьма справедливый вопрос возник у нашего уважаемого геймдизайнера, поэтому для получения ответа на вопрос я бы хотел собрать предположения нашей публики. К сожалению публики здесь как таковой нет, так что в поисках ответа я нырнул в так называемый "интернет", воспользовавшись поисковой системой от "Google". Содержание моего вопроса в поисковую ленту звучало следующим образом : на каких дистанциях хорошо оружие. К счастью, интернет меня приятно порадовал весьма хорошими ответами на вопрос нашего уважаемого геймдизайнера Нерфа. Удобную дистанцию буду сравнивать с мелкокалиберной винтовкой калибром 5,6 мм (.22LR).
Поискав нужный ответ, я готов на него ответить.

> Эффективная дальность стрельбы находится в пределах от 50-ти до 150 метров.

Из чего мы выясняем, что лавгивер отлично подходит для боя на дальних дистанциях, ОЧЕНЬ неожиданная правда, не так ли?

> Если винтовка и пистолет дают четкие ответы на эти вопросы, потому что у них простые механики, то что тут?

А тут механики переходят из "лёгкого" понимания к "не простому", из-за чего наш уважаемый геймдизайнер сломался и не совладал с смыслом лавгивера не смотря на очевидное применение данному оружию в космической среде обитания.

>Если убрать голосовую активацию, то еще пойдет. Получится несколько режимов для задержания и убийства.

А теперь ребятки, мы посмотрим на очень умное решение нашего почтённого геймдизайнера Нерфа - выпилить голосовую активацию к хуям, чтобы сместить понимание пушки от "непростого" к "лёгкому"! Благодаря чему Нефр сможет понять смысл данной пушки и оценит её также, как оценил и винтовку с пистолетиками! НЕСКОЛЬКО РЕЖИМОВ ДЛЯ ЗАДЕРЖАНИЯ И УБИЙСТВА, ВОТ ПРЯМО ТАКИ УНИВЕРСАЛЬНАЯ КИЛЛЕРФИЧА НАХУЙ!!!

> Скилл ишшу круто, не забывай про удобство переключение режимов которое равно нулю, если игрок без макросов гоняет, то быстро во время боя переключить режим становиться почти невозможно.

А тем временем наш другой камрад с так называемым "скилл иссуе" снова начинает ныть про неудоство пушки, ни разу не приводя в пример его анробастность, которая обычно и является причиной, по которой любое оружие в руках из золота превратится в металлолом под видом оружия, который вскоре обязательно выхватит кто-то из ассистентонегров.

> А зачем антаги должны воровать трусы глав?

Девелопер своего билда спрашивает за смысл воровства трусов у глав, ответ убил.

> Тем более, зачем тогда робастному хосу какая-то ультрапушка, пускай бегает с петушителем.

Ну так пусть бегают, никто не запрещает набивать SSS ранг на ХоСе, просто бегая каждый раунд с петушителем и ломая антагам ёбла даже без применения целых ТРЁХ стансфер за выстрел в купе с лазерными болтами.

> Итого странная пушка с 5 патронами на режим, которая умеет всё и понемногу, практического применения я у неё не особо вижу, плюс неудобство переключения режимов голосом, для игроков без макросов.

Скилл иссуеёб не нашёл применения пушке, которая умеет почти всё и не совладал с сменой режимов, срочно закрывайте ПР!! Отклонено закрыто!!

> Твою же пушку законтрить можно только если убить хоса первее. Что при правильной комбинации режимов и таргет зон, фактически невозможно.

Давай я не буду перечислять ахуилиард способов законтрить лавгивер и ты подумаешь немного своими остатками мозгов вместо того, чтобы сначала ныть про неудобство пушки и её непрактичность, а следом за этим ныть об имбовости лавгивера?

> И опять же как там на ВГ не ноют и не используют макросы для лавгивера, я не знаю, ибо последний раз на ВГ я играл в 2015 году.

Ну пушто на ВГ нормальные чёткие пацаны играют, далеко не нашего уровня нытиков. Нам до них как Берлину до победы.

> А что если хос немой?! О УЖАС.

Реально ужас блять, какие нахуй немые люди на ХоСах, я бы таких раундстартом хуярил. 

> Ну а я не геймдизайнер и не овнер, вон говори с нефром, тобби, плином. Я спатт.

Поговорил я с вашим геймдизайнером уважаемым, ответ убил.

- По той же причине, почему не вводиться ЕРП панель, не соответствует направлению и задача [...]

2022-01-12 15:42 UTC, NefrNerf commented
Фловей, тебе тут не чистилище, чтобы спамить, со Сранклином можно обсудить реализацию и как лучше реализовать идею. А вот полезная информация из твоего сообщения стремиться к нулю. Иди в другое место со своими истериками.

2022-01-12 15:56 UTC, FloweYStyle commented
Тебе тут не конструктор хуёвых доёбов и обидок, Нерф. На большинство заявлений я выдал информативный ответ, пояснил за смысл пушки и её пользу и опровергнул некоторые высказывания.  Тот факт, что ты из целого текста не можешь сообразить всю информацию уже проблемы не мои, почему-то другие люди меня полностью понимают. Да и как ты умудрился это спамом назвать, хуй знает - видимо в силу уже рандомные слова из конструктора входят.

2022-01-12 16:21 UTC, Doster-d commented
Я вижу, что обе стороны не хотят в диалог, одни по причине того, что не понимают пушку и вместо того, чтобы объяснить без оскорблений, другая сторону оскорбляет их и теперь эта сторона просто по чести, скорее всего, никогда не поймет эту пушку.
Всем сторонам читать Дейла Карнеги "Как приобретать друзей и оказывать влияние на людей" для того, чтобы решить этот конфликт.

2022-01-12 16:47 UTC, FloweYStyle commented
Это диалог, ты не понимаешь.

![e9GKGJGWVlg](https://user-images.githubusercontent.com/77331370/149184263-48c4505d-475f-466b-9ea6-8a6bd5eef499.jpg)

2022-01-12 16:49 UTC, NefrNerf commented
Протестировал пушку на локалке, 2 вещи есть которые я категорично против, ДНК лок и взрыв, если эти вещи убрать то можно впилить. Голосовое управление лучше бы сделать опциональным. Обязательно дать выбор, ВП + винтовка или Лавгивер по аналогии с детективским кейсом. Меня конечно больше поразило, что он стреляет физическими патронами при зарядке электричество, но ладно.

2022-01-12 16:53 UTC, Zert0X commented
Фловея порвало, реквестерию клининговую службу, пускай ошмётки со стены уберут.

2022-01-12 23:48 UTC, Srankl1n commented
Я тебя понял.

2022-01-13 00:05 UTC, FloweYStyle commented
Rest in peace.

2022-01-15 18:45 UTC, N1ght1ngal3 commented
> Я вижу, что обе стороны не хотят в диалог, одни по причине того, что не понимают пушку и вместо того, чтобы объяснить без оскорблений, другая сторону оскорбляет их и теперь эта сторона просто по чести, скорее всего, никогда не поймет эту пушку.
> Всем сторонам читать Дейла Карнеги "Как приобретать друзей и оказывать влияние на людей" для того, чтобы решить этот конфликт.

Чувак. Вместо того чтобы читать, блядь, Дейла Карнеги или ещё каких сраных шарлатанов почитай у Аристотеля про ЭТОС, ПАФОС и ЛОГОС. Может дойдёт, что риторические приёмы - не повод включать обиженку и отметать нахуй всю аргументацию оппонента.

2022-01-15 18:48 UTC, Doster-d commented
> Чувак. Вместо того чтобы читать, блядь, Дейла Карнеги или ещё каких сраных шарлатанов почитай у Аристотеля про ЭТОС, ПАФОС и ЛОГОС. Может дойдёт, что риторические приёмы - не повод включать обиженку и отметать нахуй всю аргументацию оппонента.

Ничего не понял (я очень тупой), но это очень интересно, можешь рассказать про это, пожалуйста?

2022-01-15 18:58 UTC, Doster-d commented
Нет уж, Srankl1n, думаешь, спортировал крутую пушку и можешь вот так закрыть ПР? Этого не будет мухахаха!

2022-01-15 19:00 UTC, Srankl1n commented
https://youtu.be/X04njLwuj9k

2022-01-15 19:04 UTC, N1ght1ngal3 commented
> > Чувак. Вместо того чтобы читать, блядь, Дейла Карнеги или ещё каких сраных шарлатанов почитай у Аристотеля про ЭТОС, ПАФОС и ЛОГОС. Может дойдёт, что риторические приёмы - не повод включать обиженку и отметать нахуй всю аргументацию оппонента.
> 
> Ничего не понял (я очень тупой), но это очень интересно, можешь рассказать про это, пожалуйста?

Держи хорошую лекцию на тему. https://youtu.be/PkT0PJwy8mI

2022-01-15 20:16 UTC, Doster-d commented
Сделал честную зарядку, а то у нас за один условный тик была полная зарядка.
Заменил взрыв на удар током, как в видео в ОП.

2022-01-15 21:50 UTC, TobyThorne commented
Короче, решения после обсуждения за закрытыми дверями в подвале:
- Голосовые команды должны приниматься не только от держащего (но только от его голоса).
- Спрайт - говно, выбивается среди абсолютно всех имеющихся в данный момент пушек за исключением ретро-лазера (по понятным причинам).
- ЭМИ должны сажать батареи (но не полностью) и с рандомным шансом переключать режим.
- Емаг должен сбрасывать ДНК-лок.
- Нужен кейс с выбором между Loveгивером и энерговинтовкой. Следовательно, контракт должен появляться если выбран лавгивер, либо кейс ещё не открыт. Табельный пистолет должен появляться в любом случае вне кейса, ибо табельный.

2022-01-17 07:45 UTC, Srankl1n commented
мертвый пост, но всё же

> кейс с выбором пушки

Даём ХоСу выбор не получать пизды от антагов или получать пизды от антагов? Мне кажется, тут дырка.

2022-01-17 17:44 UTC, Doster-d commented
Спрайт обновлен, теперь при сбросе пушки убирается иконка результата проверки ДНК.

2022-01-17 19:47 UTC, closed without merging

2022-01-17 20:53 UTC, Doster-d commented
Но все же нормально было, давайте второй раунд, я почти доделал кейс.