Removes wingrilles, implements advanced fulltile windows
ChaoticOnyx/OnyxBay pull request #7460
Opened 2022-01-27 21:27 UTC by TobyThorne

![windowscomp1](https://user-images.githubusercontent.com/45202681/151441852-8f2ab2d2-75ae-4807-bd04-70ad15167d64.png)
![windowscomp2](https://user-images.githubusercontent.com/45202681/151441870-8193c90f-5d1b-4acf-8891-96cb0663585b.png)

- Добавлены фуллтайловые окна.
- Практически на всех картах старые окна заменены на новые. В большинстве помещений установлены обычные окна, в особо защищённых - застеклённые решётки под током, на обшивке - двухслойные. На Дереликте - ностальгический пейзаж в виде старых окон со старыми-старыми решётками.
- Старые "тонкие" окна переименованы из "window" в "panel". 
- Из стекла больше нельзя крафтить старые фуллтайловые окна.
- Из арматуры теперь крафтится не решётка, а window frame. Стоит как и раньше - 2 прута. На такую раму можно навесить только одно стекло.
- Window frame можно обложить проводкой, такое окно будет электрохроматическим. С помощью мультитула можно настроить, будет ли стекло затемняться от сигнала или нет - к примеру, можно сделать в одной комнате (при наличии кнопки) два окна, затемняющихся-растемняющихся по очереди.
- Window frame можно укрепить одним прутом, получив reinforced window frame. На такое окно можно повесить уже два отдельных слоя стекла. В отличие от обычной рамы, через укреплённую могут пролезть только маленькие мобы, человек не пролезет. Снижает получаемый стеклом урон на 10%. Обладает повышенной устойчивостью ко взрывам - внутреннее стекло может не разбиться при сильном взрыве с шансом, зависящим от взрывоустойчивости наружного. 
- Reinforced window frame также можно обложить проводкой, получив укреплённый электрохроматик. На него вешается только один слой стекла, но снижение урона всё ещё действует и на него можно пустить ток, как на решётку. В отличие от обычного электрохроматика, на такую раму можно прикрепить сигналер, позволяя самостоятельно создавать затемняющиеся окна в любом месте, без нужды в кнопке. Сигналер достаточно прикрепить к одному окну, при получении сигнала сработают все подсоединённые к нему электрохроматические окна.
- Reinforced window frame можно укрепить ещё одним прутом, получив старую добрую grille. Работает примерно так же, как и старая решётка. На неё вешается только одно стекло, но оно получает 20% брони.
- У многих штук вроде пожарной панельки, консоли заказов и кнопок от шлюзов поднят слой для отображения поверх окон.
- Бонусом - добавлены новые иконки для стаков арматуры. Раньше имелось два стейта - один прут и куча прутьев, если их в стаке больше одного. Теперь - аж пять: от одного до четырёх и затем уже - куча.
- Содрал с "Исхода" новогодние украшения и чутка потрогал мелочи - подкрасил пол в качалке, добавил электрохроматики в адвокатскую, убрал атмосферные трубы из-под окон в баре и ксенобиологии.

Стёкла крепятся следующим образом:
Стекло -> ломик -> отвёртка. У укреплённой рамы нужно повторить то же самое для второго слоя.
Разбираются:
Отвёртка -> ломик -> гаечный ключ.

Сигналеры и провода убираются с рам кусачками, разбираются рамы ими же.

Рамы привинчиваются к полу отвёрткой.

Кнопки для переключения электрохроматиков заставляют срабатывать все электрохроматики в зоне, так что разбитые экземпляры можно без проблем восстанавливать.

Старые окна всё ещё можно собрать при большом желании, но это теперь не так удобно.

```yml
🆑
tweak: Мы пошли на поводу у всех остальных билдов и заменили старые решёткопанельные окна на модные фултайловые, с кучей новых возможностей. Подробнее - на страничке ПРа в ГитХабе и на Вики.
maptweak: С "Исхода" украден Новый Год. Помянем.
maptweak: Крошечные изменения "Исхода". Адвокатский офис получил электрохроматические окошки, а пол в качалке стал не таким унылым.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).
- [x] Я вусмерть заёбся это кодить, а затем - тестировать абсолютно каждое взаимодействие.

2022-01-27 21:37 UTC, HonkyDonky commented on code/modules/materials/materials.dm
> +		for(var/anything in window_options)
```suggestion
		с
```

2022-01-27 21:37 UTC, HonkyDonky commented on code/modules/materials/materials.dm
> +		for(var/anything in window_options)
Блять гитхаб убейся

2022-01-27 21:38 UTC, HonkyDonky commented on code/modules/materials/materials.dm
> +			break
```suggestion
		choice = windows.options[0]
```

2022-01-27 21:58 UTC, TobyThorne commented on code/modules/materials/materials.dm
> +			break
Да, чёт забыдлил. Поправил.

2022-01-28 07:43 UTC, Doster-d submitted a review, later dismissed
Мне обещали пиво.

2022-01-28 12:41 UTC, igorsaux requested changes

2022-01-28 12:41 UTC, igorsaux commented on code/game/objects/structures/window_frame.dm
> +	playsound(my_frame, SFX_BREAK_WINDOW, 70, 1)
```suggestion
	playsound(my_frame, GET_SFX(SFX_BREAK_WINDOW), 70, 1)
```

2022-01-28 12:54 UTC, igorsaux approved these changes

2022-01-28 14:42 UTC, Doster-d approved these changes

2022-01-28 15:34 UTC, merged