Portal gun и прочие
ChaoticOnyx/OnyxBay pull request #7523
Opened 2022-02-06 01:00 UTC by Doster-d

Что если у нас будет портальная пушка, которая сохраняет momentum у объектов?
Я накодил, взял за основу вгшные порталы, там было почти то, что я написал, но то, что там было работало.
На эту основу я сделал пару проков для пар-ного переноса векторов между объектами.
При входе в портал объект выходит с "противоположной" стороны.
На данный момент сделал перенос:
- [x] Проджектайлов (все пули, даже луч эмиттера)
- [ ] Брошенные объекты (включая людей)

Тут будет видео с демонстрацией

Добавил сапоги, которые не получают урон от падения.

Мне нужны спрайты портальной пушки в руке, спрайты сапог.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-02-11 22:25 UTC, Doster-d commented
Ура, порталы работают.
Теперь остались спрайты :(

2022-02-11 22:27 UTC, DarkHunter7756 commented
Что насчет порталов Хенд теле? Они будут сохранять momentum ?

2022-02-11 22:30 UTC, Doster-d commented
> Что насчет порталов Хенд теле? Они будут сохранять momentum ?

Нет, хенд теле работают как всегда.
Это щитспавн пушка, которая планируется использоваться в [ДАННЫЕ УДАЛЕНЫ]

2022-02-11 22:33 UTC, DarkHunter7756 commented
> Это щиспавн пушка

Печально это слышать. Очень

2022-03-08 14:26 UTC, incatnator commented
> Это щитспавн пушка, которая планируется использоваться в [ДАННЫЕ УДАЛЕНЫ]

Собственно, почему? У нас в РнД есть вортекс, который в разы имбовее ПГ.

2022-03-08 14:29 UTC, DarkHunter7756 commented
Вортекс скучный и неудобный. К тому же долго исследуется. Лучше иметь мидгейм альтернативу под 360 ноускоп млж геймплей

2022-03-08 14:31 UTC, incatnator commented
> Вортекс скучный и неудобный. К тому же долго исследуется. Лучше иметь мидгейм альтернативу под 360 ноускоп млж геймплей

Я бы неиронично предложил заменить Вортекс ПГ. По маячкам у нас можно и через телепортер прыгать, а спидранить протолат ради лута дереликтов эври раунд негоже. А ПГ ещё и веселее.

2022-03-08 14:35 UTC, DarkHunter7756 commented
Лутать дереликты можно и через обычный телепортер. А портал ган может обладать прикольной физикой для экспериментов с старядами и проникновениями.

2022-03-08 14:53 UTC, Doster-d commented
> Собственно, почему? У нас в РнД есть вортекс, который в разы имбовее ПГ.

Потому что иначе нужно будет ругаться с гейдизайном, а я на них обиделся.

2022-03-08 17:38 UTC, TobyThorne commented
Не знаю, чё там Достер поругался, но сначала надо обкатать пушечку на ивентах, потвикать, а потом можно будет и в РнД.

2022-03-15 18:04 UTC, Doster-d commented
Мне очень сильно понравились иконки, что я использовал их все.
Теперь при стрельбе есть анимация.
![dreamseeker_MpOl6xJZ6O](https://user-images.githubusercontent.com/63081538/158442862-c75c616d-13cb-48e2-a942-215fa9120a22.gif)

2022-03-15 18:05 UTC, Doster-d commented
Остались спрайты для long fall boots

2022-03-15 18:10 UTC, Doster-d commented
Анимации больше нет, спрайты для long fall boots все еще нужны.

2022-04-26 21:19 UTC, Doster-d commented
Пошел я нахуй

2022-05-07 19:38 UTC, TermService commented on code/datums/helper_datums/teleport.dm
> +/decl/teleport/proc/get_turfs(atom/movable/target, atom/destination, precision)
прок пиздатый

2022-05-07 19:40 UTC, TermService commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/linked/Initialize(mapload, end, delete_after, failure_rate)
и зачем тут параметры?

2022-05-07 19:40 UTC, Doster-d commented on code/datums/helper_datums/teleport.dm
> +/decl/teleport/proc/get_turfs(atom/movable/target, atom/destination, precision)
get_teleport_turfs?

2022-05-07 19:41 UTC, TermService commented on code/game/objects/effects/portals.dm
> +	spawn()
INVOKE_ASYNC

2022-05-07 19:42 UTC, TermService commented on code/modules/projectiles/guns/portalgun.dm
> +#define BLUE_PORTAL 0
андефайна почему нет?

2022-05-07 19:46 UTC, TermService commented on code/datums/helper_datums/teleport.dm
> +/decl/teleport/proc/get_turfs(atom/movable/target, atom/destination, precision)
зачем создавать отдельный прок который ретурнит значения с другого прока? в чем смысл?

2022-05-07 19:50 UTC, Doster-d commented on code/datums/helper_datums/teleport.dm
> +/decl/teleport/proc/get_turfs(atom/movable/target, atom/destination, precision)
Там же переопределение есть у этого прока, ты посмотри как он используется.

2022-05-07 19:53 UTC, TermService commented on code/datums/helper_datums/teleport.dm
> +/decl/teleport/proc/get_turfs(atom/movable/target, atom/destination, precision)
а да, вопросов нет

2022-05-07 19:53 UTC, TermService submitted a review, later dismissed

2022-06-01 16:13 UTC, TermService submitted a review, later dismissed

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/game/atoms_movable.dm
> +		while(src && thrown_to &&((((src.x < thrown_to.x && dx == EAST) || (src.x > thrown_to.x && dx == WEST)) && dist_travelled < range) || (a && a.has_gravity == 0)  || istype(src.loc, /turf/space)) &&
О боже, что это? Почему меня ругают за длинные проверки, когда существует ЭТО?
```suggestion
		while(throwing && thrown_to && ((((x < thrown_to.x && dx == EAST) || (x > thrown_to.x && dx == WEST)) && dist_travelled < range) || a?.has_gravity == 0 || istype(loc, /turf/space)) && istype(loc, /turf))
```
Кстати, можно ведь убрать вообще почти все `src`?

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/game/atoms_movable.dm
> +		while(src && thrown_to &&((((src.y < thrown_to.y && dy == NORTH) || (src.y > thrown_to.y && dy == SOUTH)) && dist_travelled < range) || (a && a.has_gravity == 0)  || istype(src.loc, /turf/space)) &
```suggestion
		while(throwing && thrown_to && ((((y < thrown_to.y && dy == NORTH) || (y > thrown_to.y && dy == SOUTH)) && dist_travelled < range) || a?.has_gravity == 0  || istype(loc, /turf/space)) && istype(loc, /turf))
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/game/objects/effects/portals.dm
> +	var/atmos_connected
```suggestion
	var/atmos_connected = FALSE
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/game/objects/effects/portals.dm
> +	target_turf = locate(max(min(x + x_diff, world.maxx), 1), max(min(y + y_diff, world.maxy), 1), target.z)
```suggestion
	target_turf = locate(Clamp(x + x_diff, 1, world.maxx), Clamp(y + y_diff, 1, world.maxy), target.z)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/game/objects/effects/portals.dm
> +	target_turf = locate(max(min(x, world.maxx), 1), max(min(y, world.maxy), 1), target.z)
```suggestion
	target_turf = locate(Clamp(x, 1, world.maxx), Clamp(y, 1, world.maxy), target.z)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/modules/projectiles/guns/portalgun.dm
> +		if(0)
```suggestion
		if(BLUE_PORTAL)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/modules/projectiles/guns/portalgun.dm
> +		if(1)
```suggestion
		if(ORANGE_PORTAL)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/modules/projectiles/guns/portalgun.dm
> +		return
```suggestion
	if(!blue_portal || !red_portal)
		var/obj/effect/portal/linked/single_portal = blue_portal || red_portal
		if(single_portal)
			single_portal.overlays.Cut()
			single_portal.target = null
			single_portal.disconnect_atmospheres()
		return
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/game/objects/effects/portals.dm
> +				P.atmos_connection = new (get_turf(P), get_turf(src))
```suggestion
		var/obj/effect/portal/linked/P = target
		var/turf/src_turf = get_turf(src)
		var/turf/target_turf = get_turf(P)
		if(src_turf && target_turf)
			var/has_valid_connection = FALSE
			if(TURF_HAS_VALID_ZONE(src_turf))
				atmos_connection = new (src_turf, target_turf)
				has_valid_connection = TRUE
			if(TURF_HAS_VALID_ZONE(target_turf))
				P.atmos_connection = new (target_turf, src_turf)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/modules/projectiles/guns/portalgun.dm
> +		QDEL_NULL(red_portal)
```suggestion
	QDEL_NULL(blue_portal)
	QDEL_NULL(red_portal)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/modules/projectiles/guns/portalgun.dm
> +				QDEL_NULL(blue_portal)
```suggestion
			QDEL_NULL(blue_portal)
```

2022-06-01 19:08 UTC, O0oMaximo0O commented on code/modules/projectiles/guns/portalgun.dm
> +				QDEL_NULL(red_portal)
```suggestion
			QDEL_NULL(red_portal)
```

2022-06-01 19:11 UTC, TobyThorne commented
сер у вас конфликтчанка

2022-06-01 19:12 UTC, TobyThorne commented on code/game/atoms_movable.dm
> +	var/atom/thrown_to
бля мож без стронгрефов плез

2022-06-01 19:13 UTC, TobyThorne commented on code/game/objects/effects/portals.dm
> +	var/mob/owner
и тут, или викрефы или подписывай их на QDELETED

2022-06-01 19:25 UTC, Doster-d commented
СУКА Я ТОЛЬКО ИХ ИСПРАВИЛ КАКОЙ ЕБЛАН ЭТО СДЕЛАЛ?!

2022-06-02 13:31 UTC, Doster-d commented on code/game/atoms_movable.dm
> +		while(src && thrown_to &&((((src.x < thrown_to.x && dx == EAST) || (src.x > thrown_to.x && dx == WEST)) && dist_travelled < range) || (a && a.has_gravity == 0)  || istype(src.loc, /turf/space)) &&
Потому что бее пидорасы

2022-06-02 13:32 UTC, Doster-d commented on code/game/atoms_movable.dm
> +		while(src && thrown_to &&((((src.x < thrown_to.x && dx == EAST) || (src.x > thrown_to.x && dx == WEST)) && dist_travelled < range) || (a && a.has_gravity == 0)  || istype(src.loc, /turf/space)) &&
Ну это не мое, но приму.

2022-06-09 14:01 UTC, TobyThorne commented on code/game/atoms_movable.dm
> -	src.thrower = null
верни, мы тут должны занулять не агрумент функции, а переменную

2022-06-09 15:37 UTC, Doster-d commented
В пизду все это, я иду совершать роскомнадзор

https://user-images.githubusercontent.com/63081538/172887353-0c613598-8399-4d09-ae52-f4d3ffe87ef8.mp4

2022-06-09 16:35 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/172898819-df55c093-c1b8-44e3-a4d9-ddb09e357cac.png)
@ 
![image](https://user-images.githubusercontent.com/45202681/172898837-e57cef93-1916-440f-be6d-507f6ca8a02d.png)

2022-06-10 17:40 UTC, Doster-d commented
Ладно, я победил, в математике я не силен, зато знаю, что бьенд умеют в математику и сделает все за меня.
Вообщем, там теперь не страшно в подсчете траектории.

2022-06-10 18:24 UTC, TermService submitted a review, later dismissed

2022-06-10 19:52 UTC, TobyThorne requested changes

2022-06-10 19:52 UTC, TobyThorne commented on code/game/atoms_movable.dm
> +	thrower = null
та не src.throwing а src.thrower

2022-06-10 20:57 UTC, TobyThorne commented on code/game/atoms_movable.dm
> +	thrower = null
```suggestion
	throwing = FALSE
	src.thrower = null
```

2022-06-12 00:12 UTC, TobyThorne approved these changes
старый код поломаться не должен, новый код хз всё равно для щитспавна

2022-06-13 17:20 UTC, TermService approved these changes

2022-06-13 17:22 UTC, merged