Removes lack of subsystems' performance
ChaoticOnyx/OnyxBay pull request #7612
Opened 2022-02-22 05:45 UTC by TobyThorne

- Порт [tgstation/tgstation#64500](https://github.com/tgstation/tgstation/pull/64500) позже всего мира. Но лучше позже, чем никогда.
- Небольшие оптимизации подсистем мобов и машинерии. А может и большие. Профайлеры не нужны, доверяемся статическому анализу.

```yml
🆑
experiment: Фикс контроллеров, который абсолютно точно не должен уронить сервер навсегда.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-02-25 16:16 UTC, igorsaux requested changes

2022-02-25 16:16 UTC, igorsaux commented on code/controllers/subsystems/machines.dm
> +	var/static/tmp/list/powernets  = list()
```suggestion
	var/static/list/processing = list()
	var/static/list/currentrun = list()
	var/static/list/powernets  = list()
```

2022-02-25 16:16 UTC, igorsaux commented on code/controllers/subsystems/processing/mobs.dm
> +	var/static/tmp/list/mob_list = list()
```suggestion
	var/static/list/player_levels = list()
	var/static/list/mob_list = list()
```

2022-03-06 18:07 UTC, igorsaux approved these changes

2022-03-07 12:02 UTC, kreeperHLC approved these changes

2022-03-07 12:03 UTC, merged