fix(alien): now facehugger implants embryo after putting on
ChaoticOnyx/OnyxBay pull request #7673
Opened 2022-03-08 11:21 UTC by O0oMaximo0O

Теперь лицехват имплантирует эмбрион после надевания на другого персонажа через меню.

fix #6036

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь лицехват имплантирует эмбрион после надевания на другого персонажа через меню.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-03-08 11:38 UTC, TobyThorne requested changes

2022-03-08 11:38 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +		return
```suggestion
		return ..()
```

2022-03-08 11:38 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +			kill_holder()
```suggestion
			kill_holder()
	..()
```

2022-03-16 00:50 UTC, HonkyDonky submitted a review, later dismissed
Я молюсь Аллаху, в надежде, что это правда тестировалось на локалке.

2022-03-16 05:08 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +	..()
```suggestion
	user.drop_from_inventory(src)
	F.facefuck(H, TRUE, TRUE)
	..()
```

Вообще всё делается куда проще и эффективнее, не выкидывая к чертям все нужные проверки.

2022-03-16 06:00 UTC, O0oMaximo0O commented
> Я молюсь Аллаху, в надежде, что это правда тестировалось на локалке.

Да. Надел - иконка эмбриона на человечке появилась)

2022-03-19 20:44 UTC, TermService commented
я бля потестил хаггеров, это ж пиздец какой-то и почему у нас ламар на людей кидается? Втф ваще, хаггер спокойно летает из помещения в помещение, если увидел цель он будет ебать окна двери аллаха, хз чем поможет фикс но ладно

2022-03-19 20:44 UTC, TermService submitted a review, later dismissed

2022-06-04 05:50 UTC, HonkyDonky approved these changes

2022-06-04 05:50 UTC, HonkyDonky commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +	var/mob/living/simple_animal/hostile/facehugger/F = contents[1]
Я запрещаю **вам** обращаться к `facehugger` через `contents`. Используйте другие, нормальные способы.

2022-06-04 05:51 UTC, HonkyDonky submitted a review, later dismissed
бля не та кнопка

2022-06-04 15:08 UTC, O0oMaximo0O commented on code/modules/mob/living/simple_animal/hostile/facehugger.dm
> +	var/mob/living/simple_animal/hostile/facehugger/F = contents[1]
Как пожелаете)

2022-06-04 16:24 UTC, TobyThorne commented on code/game/objects/items.dm
> -/obj/item/New()
есть такое чувство, что ты этим половину итемов сломаешь нахрен

2022-06-04 16:29 UTC, O0oMaximo0O commented on code/game/objects/items.dm
> -/obj/item/New()
В самом проке это не используется, оно передаётся дальше, к атому. Я просто почитал про вставляющийся автоматически параметр для loc, решил вставить для совместимости с добавляемыми другими аргументами.

2022-06-04 17:03 UTC, TobyThorne commented on code/game/objects/items.dm
> -/obj/item/New()
Ради всего святого, убери.
Просто ниже, у холдера сделай:

/obj/item/holder/New(loc, mob_to_hold)
	..(loc)

2022-06-04 17:09 UTC, TobyThorne commented on code/modules/mob/holder.dm
> +	mob = mob_to_hold
Раз у холдера теперь стронгреф на моба вместо поиска мобов в контентсе - регистрируй сигнал SIGNAL_QDELETING от моба и вызывай удаление при получении сигнала. Никто не знает, когда моб внутри холдера решит внезапно удалиться.

2022-06-04 17:33 UTC, O0oMaximo0O commented on code/modules/mob/holder.dm
> +	mob = mob_to_hold
Сделал, ща затестю

2022-06-04 17:42 UTC, O0oMaximo0O commented on code/modules/mob/holder.dm
> +	mob = mob_to_hold
Так, рантаймов не прибавилось. Рантайма потискал, Ламарра покидал, дал себя пожрать слизню воксов.

2022-06-23 03:48 UTC, TobyThorne approved these changes, later dismissed
не переревувывал, но ультрасовременный гитхаб не даёт просто скинуть чр

2022-06-29 13:03 UTC, O0oMaximo0O commented
Благодарю)

2022-07-17 18:19 UTC, TermService approved these changes

2022-07-17 18:27 UTC, Doster-d approved these changes

2022-07-17 18:27 UTC, igorsaux approved these changes

2022-07-17 19:40 UTC, Tsurupeta approved these changes

2022-07-17 19:50 UTC, merged