fix(cooker): fix infinity cooking with slices
ChaoticOnyx/OnyxBay pull request #7678
Opened 2022-03-09 07:06 UTC by kreeperHLC

По идее там и так была проверка на основной тип, но да ладно.
fix #3927
<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
bugfix: Печка, гриль и остальные инструменты для готовки больше не принимают кусочки еды.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-03-09 07:32 UTC, TobyThorne commented
Т.е. я не смогу загриллить кусок хлеба? Не, решение - хрень. Надо проверять только в том случае, если выбран рецепт нарезабельной еды.

2022-03-09 07:39 UTC, kreeperHLC commented
> Т.е. я не смогу загриллить кусок хлеба? Не, решение - хрень. Надо проверять только в том случае, если выбран рецепт нарезабельной еды.

Ты как рецепт будешь определять, если это ограничение только в общем типе находится

2022-03-09 07:52 UTC, kreeperHLC commented
Ограничил только для выпекания

2022-03-16 00:43 UTC, HonkyDonky commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		to_chat(user, SPAN_WARNING(""))
Здесь, похоже, проебан текст

2022-03-16 00:43 UTC, HonkyDonky commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		if("baked" in check.cooked_types)
А здесь пахнет хардкодом, не порядок

2022-03-21 10:00 UTC, TermService requested changes
это какая-то хуйня редкая что хочется прост закрыть, крипер что ты наделал

2022-03-21 10:02 UTC, kreeperHLC commented
Да нормас всё, я просто зафакапил чуть-чуть и забыл.

2022-03-21 10:03 UTC, kreeperHLC commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		if("baked" in check.cooked_types)
А у нас нет для этого дефайнов, поэтому так

2022-03-21 10:03 UTC, kreeperHLC commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		to_chat(user, SPAN_WARNING(""))
Этот код забыл удалить

2022-04-01 06:40 UTC, kreeperHLC commented
Исправлено на более старую проверку.

2022-04-06 06:12 UTC, TermService approved these changes, later dismissed

2022-04-06 11:15 UTC, TobyThorne commented on code/game/machinery/kitchen/cooking_machines/_cooker.dm
> +		to_chat(user, SPAN_WARNING("\The [I] too small for being [cook_type]."))
```suggestion
		to_chat(user, SPAN_WARNING("\The [I] too small to get [cook_type]."))
```

2022-04-06 17:51 UTC, TermService approved these changes

2022-04-06 19:26 UTC, TobyThorne approved these changes

2022-04-06 19:27 UTC, merged