Port Abductors
ChaoticOnyx/OnyxBay pull request #7744
Opened 2022-03-19 18:49 UTC by Zert0X

![c2bc39d54dc43a5c90433edbd48fc8f8](https://user-images.githubusercontent.com/42303535/159134536-59d6acc4-aec2-44f7-a2f2-952dd3331e32.gif)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Портированы похитители!
/🆑
```

</details>

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим x внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над ПРом. ЭТУ СТРОЧКУ НУЖНО УДАЛИТЬ.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-03-19 18:54 UTC, NefrNerf commented
Го без теста в прод

2022-03-19 18:55 UTC, Zert0X commented
> Го без теста в прод

Я только за, оно по идее должно почти полностью работать. Правда если педали будут спавнить абдукторов вручную :kek:

2022-03-19 19:08 UTC, TobyThorne commented on code/game/antagonist/outsider/abductor/abductee/abductee.dm
> +	to_chat(player.current, "<big>[SPAN_WARNING("<b>You can't remember how you got here...</b>")]</big>")
почему не 
SPAN("warning", "<big><b>You can't remember how you got here...</b></big>")

2022-03-19 19:11 UTC, TobyThorne commented on code/game/antagonist/outsider/abductor/equipment/abductors_gear.dm
> +	icon_state = "alienpaper_words"
дримчекер говорит, спрайта нема

2022-03-19 19:11 UTC, TobyThorne commented on code/game/antagonist/outsider/abductor/equipment/abductors_gear.dm
> +	icon_state = "alienpistol"
как и здесь

2022-03-19 19:12 UTC, TobyThorne commented on code/game/antagonist/outsider/abductor/equipment/abductors_gear.dm
> +			to_chat(user, "<span class='warning'>\The [C] is already handcuffed!</span>")
```suggestion
			to_chat(user, SPAN("warning", "\The [C] is already handcuffed!"))
```

2022-03-19 19:13 UTC, TobyThorne commented on code/game/antagonist/outsider/abductor/equipment/abductors_gear.dm
> +		if(H.mind && !isnull(H.mind.changeling))
```suggestion
		if(H.mind?.changeling)
```
не?

2022-03-19 19:28 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_organs.dm
> +		src.internal_organs_by_name[organ_type] = O
зачем src.

2022-03-19 19:30 UTC, TobyThorne commented on code/modules/mob/living/living.dm
> +	if(src.loc && (istype(src.loc, /obj/machinery/abductor/experiment)))
зачем src.

2022-03-19 19:30 UTC, TobyThorne commented on code/modules/mob/living/living.dm
> +	if(src.loc && (istype(src.loc, /obj/structure/closet)) )
зачем src.

2022-03-19 19:31 UTC, TobyThorne commented on code/modules/organs/external/stump.dm
> +	src.removed(drop_organ = FALSE)
зачем src.

2022-03-19 19:35 UTC, TobyThorne reviewed
почитал, вроде норм, но чёт рука не поднимается на галочку
пусть кто-нибудь на локалке погоняет и убедится, что ничто не высирает тысячу рантаймов в секунду и не укладывает сервер

2022-03-19 19:48 UTC, NefrNerf commented
Да уже тестим, много серьезных багов.

2022-03-20 06:23 UTC, Zert0X commented
> Да уже тестим, много серьезных багов.

Ой да ладно тебе, не такие уж и серьёзные :kek:

2022-03-24 14:57 UTC, igorsaux requested changes
when 
![image](https://user-images.githubusercontent.com/55196698/159944917-8b907914-5aab-4bfc-8db6-9ff6dcc245ff.png)

2022-03-24 15:04 UTC, Zert0X commented
> when ![image](https://user-images.githubusercontent.com/55196698/159944917-8b907914-5aab-4bfc-8db6-9ff6dcc245ff.png)

Листы оставим потому что так можно, последнее пофикшено.
Сейчас ещё доделываю смолфиксы всякого разного и можно в прод.

2022-03-24 15:05 UTC, igorsaux commented
Если бы было можно - тогда и проверки не было

2022-03-24 15:08 UTC, Zert0X commented
> Если бы было можно - тогда и проверки не было

вангую проверка на наличие пробела

2022-03-24 20:15 UTC, igorsaux approved these changes, later dismissed
убрал каку

2022-03-25 07:40 UTC, TermService approved these changes, later dismissed

2022-03-25 07:50 UTC, TermService approved these changes

2022-03-25 11:17 UTC, igorsaux approved these changes

2022-03-25 11:17 UTC, merged