Add diona meat
ChaoticOnyx/OnyxBay pull request #7758
Opened 2022-03-21 18:01 UTC by oleggorru

Добавлено новое мясо дион со своим спрайтом, которое можно извлечь гиббером.
Добавлены переменные типа мяса и количество для родительского объекта дион - алиенов.

fix #6639

<details>
<summary>Чейнджлог</summary>

```yml
🆑Terydd and Oleggorru
tweak: Дионы получили свой собственный вид мяса
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

Добавлять разделку нимф на kitchenspike
 не стали, т.к. не совсем понятно, как он работает с симплмобами, да и с хуманами баги есть. Позже может оптимизировать мобов будем, можно будет зачистить говнокод(мой в гиббере в том числе).

2022-03-21 18:51 UTC, TobyThorne commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	glass_name = "iced coffee"
а это тут откуда

2022-03-21 19:42 UTC, oleggorru commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	glass_name = "iced coffee"
напортачил с ветками

2022-03-21 19:43 UTC, oleggorru commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	glass_name = "iced coffee"
https://github.com/ChaoticOnyx/OnyxBay/pull/7739

2022-03-21 19:49 UTC, TermService requested changes

2022-03-21 19:49 UTC, TermService commented on code/game/machinery/kitchen/gibber.dm
> +	if(istype(src.occupant, /mob/living/carbon/alien))
```suggestion
	if(istype(occupant, /mob/living/carbon/alien))
```

2022-03-21 19:49 UTC, TermService commented on code/game/machinery/kitchen/gibber.dm
> +		var/mob/living/carbon/alien/critter = src.occupant
```suggestion
		var/mob/living/carbon/alien/critter = occupant
```

2022-03-21 19:49 UTC, TermService commented on code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
> +	glass_name = "iced coffee"
это надо убрать из ПР

2022-05-19 14:53 UTC, TobyThorne commented
Почти месяц конфликтов.
Упавшая с полочки сталь падает на кнопку закрытия.

2022-05-19 14:53 UTC, closed without merging