Кастомка НоТипса
ChaoticOnyx/OnyxBay pull request #7769
Opened 2022-03-23 08:52 UTC by kreeperHLC

Вот наконец и пригодились модкиты, которые я уж супер давно вводил.
Для модкита нужен костюм пожарника и его красная шляпка.
Заменяет на их кастомные версии, все возможности остаются теми же.
В виде кастомки нужно выдавать именно модкит, а не нечто другое.
<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
rscadd: Добавлен модкит с кастомкой для НоТипса.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-03-23 12:22 UTC, No-Tips commented
Если гейдизайн одобрить вместо каски+файрсьюта заделать это респрайтом атмосвойдсьюта - буду благодарен

2022-03-23 12:40 UTC, NefrNerf commented
Скрин в студию

2022-03-23 12:44 UTC, TobyThorne commented
> Если гейдизайн одобрит вместо каски+файрсьюта заделать это респрайтом атмосвойдсьюта - буду благодарен

можно и войдсьютом, но шлем бы тогда более визуально герметичным сделать

2022-03-23 12:55 UTC, kreeperHLC commented
> Скрин в студию

Ну посмотри там в боте, мне ради не моей кастомки лень билд поднимать

2022-03-23 13:08 UTC, No-Tips commented
> > Если гейдизайн одобрит вместо каски+файрсьюта заделать это респрайтом атмосвойдсьюта - буду благодарен
> 
> можно и войдсьютом, но шлем бы тогда более визуально герметичным сделать

Шлем на чаре вроде герметично выглядит.

https://media.discordapp.net/attachments/946114339566387220/947552454306836500/unknown.png

https://media.discordapp.net/attachments/946114339566387220/947552454659174500/unknown.png

https://media.discordapp.net/attachments/946114339566387220/947552454952771584/unknown.png

2022-03-23 13:11 UTC, No-Tips commented
(Для толстого спрайта показывать не буду, проклято)

2022-03-23 15:30 UTC, NefrNerf commented
Ну, выглядит это явно как фаер сьют

2022-03-23 16:36 UTC, No-Tips commented
Именно поэтому я и спросил

2022-03-23 20:52 UTC, HonkyDonky commented on code/modules/clothing/custom_clothing.dm
> +	finished[2] = /obj/item/clothing/suit/fire/firefighter/atmos
Кто-то, кроме самого Голиафа, может сказать, нормальная ли это практика делать вот так?

2022-03-25 11:24 UTC, Doster-d submitted a review, later dismissed
Проклято

2022-03-25 11:24 UTC, igorsaux approved these changes

2022-03-25 11:24 UTC, igorsaux requested changes
блин конфликты

2022-04-01 06:32 UTC, kreeperHLC commented
Конфликтов больше нет

2022-04-02 13:10 UTC, igorsaux approved these changes

2022-04-02 13:10 UTC, Zert0X approved these changes

2022-04-02 13:11 UTC, merged