добавление ящика с кровушкой на шатл для ЕРТ
ChaoticOnyx/OnyxBay pull request #7877
Opened 2022-04-01 16:56 UTC by Mrbuble

Добавление ящика с кровью в медицинский отсек на шатл ЕРТ
`close #7497 ` 

- [\/] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-01 17:32 UTC, TobyThorne commented
![image](https://user-images.githubusercontent.com/45202681/161313488-8054ce3f-d2e1-471d-906e-f1a4aa96deb8.png)
сколько нужно строчек поменять чтобы на один тайл положить пакет с кровью

2022-04-01 17:37 UTC, Zert0X requested changes
![изображение](https://user-images.githubusercontent.com/42303535/161314139-d4b6138f-0341-49f6-9bd3-7f4ec9b41452.png)
а другие карты не используются?

2022-04-01 17:51 UTC, No-Tips commented
> ![image](https://user-images.githubusercontent.com/45202681/161313488-8054ce3f-d2e1-471d-906e-f1a4aa96deb8.png) сколько нужно строчек поменять чтобы на один тайл положить пакет с кровью

Тут опять этот ебучий порядок переменных, который везде проскакивает

![изображение](https://user-images.githubusercontent.com/75416333/161316258-a906f312-d4dd-4a01-842f-ed3a192ae15f.png)

2022-04-02 01:42 UTC, Mrbuble commented
> ![image](https://user-images.githubusercontent.com/45202681/161313488-8054ce3f-d2e1-471d-906e-f1a4aa96deb8.png) сколько нужно строчек поменять чтобы на один тайл положить пакет с кровью
скопировать ящик с кровью из меда и поменять там доступ...

2022-04-02 01:43 UTC, Mrbuble commented
> ![изображение](https://user-images.githubusercontent.com/42303535/161314139-d4b6138f-0341-49f6-9bd3-7f4ec9b41452.png) а другие карты не используются?

использовал основную карту для того что бы оттуда взять шкаф с кровью

2022-04-02 01:43 UTC, Mrbuble commented
> > ![image](https://user-images.githubusercontent.com/45202681/161313488-8054ce3f-d2e1-471d-906e-f1a4aa96deb8.png) сколько нужно строчек поменять чтобы на один тайл положить пакет с кровью
> 
> Тут опять этот ебучий порядок переменных, который везде проскакивает
> 
> ![изображение](https://user-images.githubusercontent.com/75416333/161316258-a906f312-d4dd-4a01-842f-ed3a192ae15f.png)

есть идеи что с этим делать?

2022-04-02 01:45 UTC, Zert0X commented
> > ![изображение](https://user-images.githubusercontent.com/42303535/161314139-d4b6138f-0341-49f6-9bd3-7f4ec9b41452.png) а другие карты не используются?
> 
> использовал основную карту для того что бы оттуда взять шкаф с кровью

Ты не понял, у фронтира и его подвидов, у сансета и чего-то ещё свой уровень ЦК соответственно туда ты не добавил кровь

2022-04-02 01:51 UTC, Mrbuble commented
> > > ![изображение](https://user-images.githubusercontent.com/42303535/161314139-d4b6138f-0341-49f6-9bd3-7f4ec9b41452.png) а другие карты не используются?
> > 
> > 
> > использовал основную карту для того что бы оттуда взять шкаф с кровью
> 
> Ты не понял, у фронтира и его подвидов, у сансета и чего-то ещё свой уровень ЦК соответственно туда ты не добавил кровь

не могу найти файл с этой картой

2022-04-02 01:52 UTC, Zert0X commented
code/maps/exodus и там внутри ещё куча папок

2022-04-02 01:53 UTC, Zert0X commented
И да чё это за коммит такой волшебный про стены в ПРе с кровью

2022-04-02 14:44 UTC, closed without merging