Progressbar update
ChaoticOnyx/OnyxBay pull request #7915
Opened 2022-04-05 18:02 UTC by TermService

https://www.youtube.com/watch?v=aiAdX2g3HUI&feature=youtu.be
теперь так
бонус - прогресс бары теперь работают на сигналах

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak:  Новая анимация прогрессбаров
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-05 18:04 UTC, igorsaux requested changes

2022-04-05 18:04 UTC, igorsaux commented on code/__defines/ces/signals_mob.dm
> +#define COMSIG_MOB_LOGOUT "mob_logout"							//from base of /mob/Logout(): ()
Нигде не используются, плюс уже были такие

2022-04-05 18:08 UTC, igorsaux requested changes

2022-04-05 18:08 UTC, igorsaux commented on code/datums/progressbar.dm
> +		qdel(src)
Здесь qdel может быть вызван дважды

2022-04-05 18:13 UTC, igorsaux commented on code/datums/progressbar.dm
> +		stack_trace("/datum/progressbar created with [isnull(User) ? "null" : "invalid"] goal_number")
Вместо стак трейса, кудела и ретурна проще сразу краш вызвать

2022-04-05 18:17 UTC, igorsaux commented on code/datums/progressbar.dm
> +	register_signal(user, SIGNAL_LOGGED_IN, .proc/on_user_login)
Нет снятия регистрации в Destroy

2022-04-05 18:19 UTC, igorsaux commented on code/datums/progressbar.dm
> +	if(user)
Большое и страшное тело условия

2022-04-05 18:22 UTC, igorsaux commented on code/datums/progressbar.dm
> +	register_signal(user, SIGNAL_PARENT_QDELETING, .proc/on_user_delete)
Этот сигнал кстати в билде нигде не создаётся)))0

2022-04-06 17:50 UTC, igorsaux approved these changes

2022-04-07 14:57 UTC, TobyThorne approved these changes
терм сломает - терм починит

2022-04-07 14:58 UTC, merged

2022-04-08 15:32 UTC, lKameRUNl commented
Ну и сломал, хуле. 
https://github.com/ChaoticOnyx/OnyxBay/issues/7944

2022-04-09 21:37 UTC, TobyThorne commented
Ну и починил, хуле.
#7951