fix(handcuffed): mobs cant remove clothing when cuffed
ChaoticOnyx/OnyxBay pull request #7927
Opened 2022-04-06 17:42 UTC by TermService

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: В наручниках нельзя снимать вещи с себя.
bugfix: Нельзя снять смирительную рубашку с себя находясь в ней.
tweak: Добавлено описание, что человек находится в смирительной рубашке
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-07 15:03 UTC, TobyThorne requested changes

2022-04-07 15:03 UTC, TobyThorne commented on code/modules/clothing/suits/miscellaneous.dm
> -			C.drop_from_inventory(C.handcuffed)
Так если мы наденем теперь рубашку поверх наручников - они тупо останутся на мобе, без ссылки. И в теории, после снимания рубашки чел сможет прямо в наручниках юзать предметы.

И наоборот, в надевание наручников надо бы проверку на надетую смирительную рубашку впихнуть.

2022-04-08 08:35 UTC, TermService commented on code/modules/clothing/suits/miscellaneous.dm
> -			C.drop_from_inventory(C.handcuffed)
Проверка на нарубашку при натягивании наручников уже есть в наручниках

2022-04-08 08:41 UTC, TobyThorne approved these changes
терм сломает - терм починит

2022-04-08 10:03 UTC, Doster-d approved these changes

2022-04-08 10:03 UTC, merged