fix(build): rename environment file
ChaoticOnyx/OnyxBay pull request #7940
Opened 2022-04-07 20:48 UTC by igorsaux

Исправил вселенскую несправедливость

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-07 21:38 UTC, kreeperHLC approved these changes

2022-04-08 04:17 UTC, HonkyDonky approved these changes
ух бля

2022-04-08 07:30 UTC, Zert0X approved these changes
Дядя не надо!

2022-04-08 07:31 UTC, Zert0X commented
Как думаете наебнет ли это хаб?

2022-04-18 16:45 UTC, TermService commented
это нам собьет скрипты, позвоните эпикусу

2022-05-04 15:51 UTC, kreeperHLC commented
Конфликты

2022-05-04 15:51 UTC, igorsaux commented
похуй

2022-05-04 15:51 UTC, closed without merging

2022-05-04 15:51 UTC, kreeperHLC requested changes
Фикси теперь