add(translation): add basic translation
ChaoticOnyx/OnyxBay pull request #7964
Opened 2022-04-10 16:45 UTC by igorsaux

Прототип системы для переводов на разные языки.

Для наглядности пока сделан перевод анонса метеоров.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-10 17:08 UTC, Doster-d commented
О, бенарнеке

2022-04-10 17:14 UTC, Zert0X commented
Оно проклято, бедная читаемость кода.

2022-04-11 21:49 UTC, igorsaux commented
Осталось перевести

2022-04-12 09:46 UTC, NefrNerf commented on localization/ru.ftl
> +    Метеоритный шторм пролетел { $station_name }.
Я бы так сформулировал

Метеорный шторм прошел территорию станции.

2022-04-12 10:02 UTC, NefrNerf commented on localization/ru.ftl
> +    Подтверждена вспышка биологической опасности уровня { $bio_level } на борту { $station_name }.
биологической угрозы

2022-04-12 10:02 UTC, NefrNerf commented on localization/ru.ftl
> +    Весь персонал должен сдерживать вспышку.
Можно так:

Всему персоналу необходимо сдержать угрозу.

2022-04-12 10:02 UTC, NefrNerf commented on localization/ru.ftl
> +    Предупреждение о биологической опасности
угрозе

2022-04-12 10:02 UTC, NefrNerf commented on localization/ru.ftl
> +    Пожалуйста, следите за всем электронным оборудованием на предмет неисправностей.
проверьте все электронное оборудование

2022-04-12 10:02 UTC, NefrNerf commented on localization/ru.ftl
> +    На этот раз питание станции на { $station_name } будет восстановлено.
Питание было восстановлено на станции { $station_name }

2022-04-12 10:02 UTC, NefrNerf commented on localization/ru.ftl
> +    Обнаружен огонь артиллерией синего пространства. Приготовьтесь к удару.
блюспейс артиллерии, имя собственное

2022-04-12 12:09 UTC, kreeperHLC requested changes

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Метеорный шторм прошел территорию станции.
Либо
```suggestion
    Метеоритный шторм прошел территорию станции.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Метеоритный дождь прошёл { $station_name }.
Либо
```suggestion
    Метеорный дождь прошёл { $station_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Обнаружены неопознанные признаки жизни, поступающие на борт { $station_name }.
```suggestion
    Обнаружены неопознанные признаки жизни на борту { $station_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Рекомендую задействовать искусственный интеллект.
```suggestion
    Рекомендуется задействовать искусственный интеллект.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Рекомендуется немедленно обезопасить чувствительное электрооборудование до тех пор, пока шторм не пройдет.
```suggestion
    Рекомендуется немедленно обезопасить чувствительного электрооборудования до тех пор, пока шторм не пройдет.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    На борту { $location_name } был обнаружен безумный корпоративный интеллект.
```suggestion
    На борту { $location_name } был обнаружен аномальный искусственный интеллект.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Все следы безумного корпоративного интеллекта исчезли из систем.
```suggestion
    Все следы аномального искусственного интеллекта исчезли из систем.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Высокие уровни помех синего пространства обнаружены в { $area }.
```suggestion
    Высокие уровни помех блюспейса обнаружены в { $area }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Подозревается образование червоточины. Немедленно расследуйте это.
```suggestion
    Ожидается образование червоточин. Немедленно обнаружьте их.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Аномалия синего пространства прекратилась.
```suggestion
    Блюспейс помехи прекратились.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    многие сотрудники погибли или умирают. В настоящее время мы обнаруживаем все больше признаков того, что сама Вселенная начинает распадаться.
```suggestion
    многие сотрудники пострадали или погибли. В настоящее время мы обнаруживаем все больше признаков того, что сама Вселенная начинает распадаться.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    По нашим оценкам, у вас есть пять минут до того, как в ваших помещениях откроется разлом синего пространства.
```suggestion
    По нашим оценкам, у вас есть пять минут до того, как в ваших помещениях откроется разлом блюспейса.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Да спасёт Господь ваши з[\[###!!!-
```suggestion
    Да спасёт Господь ваши д[\[###!!!-
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    АВТОМАТИЧЕСКОЕ ОПОВЕЩЕНИЕ: Ссылка на { $command_name } потеряна.
```suggestion
    АВТОМАТИЧЕСКОЕ ОПОВЕЩЕНИЕ: Связь с { $command_name } была потеряна.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    ОБНАРУЖЕН КАСКАД СВЕРХМАТЕРИИ
```suggestion
    ОБНАРУЖЕН КАСКАД СУПЕРМАТЕРИИ
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Обнаружена аномалия безопасности в { $gateway_name }{ $location }. Попытка установить изо... Ошибка.
```suggestion
    Обнаружена проблема в безопасности { $gateway_name }{ $location }. Попытка изолир... ОШИБКА.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    подпись: "Сигнал бедствия высокого уровня NT". Обнаружен процесс триангуляции.
```suggestion
    Подпись: "Сигнал бедствия NT высшего уровня". Обнаружен процесс триангуляции.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Идентификатор сообщает, что передача была принята устройством. Источник передачи "Неизвестен",
```suggestion
    Идентификатор сообщает, что передача была принята устройством. Источник передачи: "Неизвестен".
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Всплеск обратной связи обнаружен в системах массового распределения.
```suggestion
    Всплеск обратной гравитационной связи обнаружен в системах массового распределения.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Биосканы показывают, что { $vermstring } размножались в { $location }.
```suggestion
    Биосканеры показывают, что { $vermstring } размножились в { $location }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Очистите их, прежде чем это начнет влиять на производительность.
```suggestion
    Разберитесь с ними, прежде чем это начнет влиять на производительность.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Обнаружен взлом методом перебора (выполняется с момента { $time }). Целью атаки являются: Финансовые счета,
```suggestion
    Обнаружен взлом с помощью метода перебора (выполняется с момента { $time }). Целью атаки являются: Финансовые счета.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    без вмешательства эта атака завершится успешно примерно через 10 минут. Возможные решения: приостановка учетных записей, отключение интернет-сервера,
```suggestion
    Без вмешательства эта атака успешно завершится примерно через 10 минут. Возможные решения: приостановка учетных записей, отключение интернет-сервера,
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/en.ftl
> +    without intervention this attack will succeed in approximately 10 minutes. Possible solutions: suspension of accounts, disabling NTnet server,
```suggestion
    A brute force hack has been detected (in progress since { $time }). The target of the attack is: Financial accounts.
    Without intervention this attack will succeed in approximately 10 minutes. Possible solutions: suspension of accounts, disabling NTnet server,
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Атака прекратилась, теперь затронутые учетные записи можно вывести в Интернет.
```suggestion
    Атака прекратилась, затронутые учетные записи в безопасности.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Медицинская бригада должна немедленно подготовиться к борьбе с возбудителем.
```suggestion
    Медицинская бригада должна немедленно подготовиться к борьбе с возбудителем вируса.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    рhекомендуется использовать искусственный интеллект { $location_name }.
```suggestion
    рекомендуется использовать искусственный интеллект { $location_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    и сообщите в лазарет, если у вас возникнут какие-либо необычные симптомы.
```suggestion
    и сообщите в медбей, если у вас возникнут какие-либо необычные симптомы.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Техническое обслуживание вскоре снова потеряет весь доступ.
```suggestion
    Персонал вскоре снова потеряет доступ в туннели технического обслуживания.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Лазерный огонь класса II обнаружен рядом с { $location_name }.
```suggestion
    Лазерный дрон класса II обнаружен рядом с { $location_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Имейте в виду: датчики показывают, что неопознанный рой дронов покинул непосредственную близость к { $location_name }.
```suggestion
    Имейте в виду: датчики показывают, что неопознанный рой дронов покинул  { $location_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Пожалуйста, немедленно прекратите все ВКД и вернитесь внутрь.
```suggestion
    Пожалуйста, немедленно прекратите любую деятельность в космосе и вернитесь внутрь.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Солнечная буря достигла { $location_name }. Пожалуйста, воздержитесь от ВКД и оставайтесь внутри, пока она не пройдет.
```suggestion
    Солнечная буря достигла { $location_name }. Пожалуйста, воздержитесь любой космической деятельности и оставайтесь внутри, пока она не пройдет.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Солнечная буря прошла { $location_name }. Теперь можно безопасно возобновить деятельность ВКД.
```suggestion
    Солнечная буря прошла { $location_name }. Теперь можно возобновить космическую деятельность.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Злокачественные грибы обнаружены в { $location_name }.
```suggestion
    Злокачественный настенный грибок обнаружен в { $location_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Все СПИНЭ на { $station_name } были пополнены. Приносим извинения за причиненные неудобства.
```suggestion
    Все СМЕСы на { $station_name } были пополнены. Приносим извинения за причиненные неудобства.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    поэтому нам пришлось отключить их. Мы частично завершили нашу трассировку, и, похоже,
```suggestion
    поэтому нам пришлось её отключить. Мы частично завершили нашу трассировку, и, похоже,
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Мы начали выслеживать злоумышленника. Кто бы это ни делал, они, похоже, на борту.
```suggestion
    Мы начали выслеживать злоумышленника. Кто бы это ни делал, он, похоже, находится на борту.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Мы обнаружили злоумы#, это похо&е ( Ъ в4ш И1, 0но &# взл*#@ет $и$тему $ам0 ун14т0#ен1я,
```suggestion
    Мы обнаружили злоумы#, это похо&е ( Ъ в4ш И1, 0н &# взл*#@ет $и$тему $ам0 ун14т0#ен1я,
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    0$тано81те ег# п0ка 0н не*@!)$#&&@@  <CONNECTION LOST>
```suggestion
    0$тано81те ег# п0ка 0н не*@!)$#&&@@  <ПОТЕРЯ СВЯЗИ>
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Для этого объекта был заказан экстренный запрос.
```suggestion
    Для этого объекта был отправлен экстренный запрос.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Эвакуация была прервана из-за искажения синего пространства.
```suggestion
    Эвакуация была прервана из-за блюспейс искажения.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Внимание, у вас есть большая сигнатура, приближающаяся к станции - выглядит невооруженной для приблизительного сканирования.
```suggestion
    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - выглядит невооруженной для приблизительного сканирования.  
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Мы слишком далеко, чтобы перехватить - приготовьтесь к визитерам.
```suggestion
    Мы слишком далеко, чтобы её перехватить - приготовьтесь к посетителям.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Мы слишком далеко, чтобы перехватить - приготовьтесь к визитерам.
```suggestion
    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - выглядит невооруженной для приблизительного сканирования. 
    Мы слишком далеко, чтобы её перехватить - приготовьтесь к посетителям.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Ваши посетители на пути к выходу из системы, сжигая дельту-v, как будто это ничего не значит. Скатертью дорожка.
```suggestion
    Ваши посетители на пути к выходу из системы, удирая так быстро, как только можно. Скатертью дорожка.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Ваши посетители на пути к выходу из системы, сжигая дельту-v, как будто это ничего не значит. Скатертью дорожка.
```suggestion
    Ваши посетители на пути к выходу из системы, удирая так быстро, как только можно. Скатертью дорожка.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Обнаружены неопознанные признаки жизни, поступающие на борт { $station_name }.
```suggestion
    Обнаружены неопознанные признаки жизни, поступающие с борта { $station_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Обнаружены неопознанные признаки жизни, поступающие на борт { $station_name }.
```suggestion
    Обнаружены неопознанные признаки жизни, поступающие с борта { $station_name }.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Внимание! Уровень оповещения повышен до { $name }!
```suggestion
    Внимание! Уровень безопасности повышен до { $name }!
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Внимание! Уровень оповещения изменен на { $name }!
```suggestion
    Внимание! Уровень безопасности изменен на { $name }!
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Все угрозы станции миновали. У службы безопасности может не быть видимого оружия,
```suggestion
    Все угрозы станции миновали. Службы безопасности не может носить оружие на виду,
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    У сотрудников службы безопасности может быть видимое оружие, разрешены случайные обыски".
```suggestion
    У сотрудников службы безопасности может носить оружие на виду, разрешены "случайные обыски".
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    но может продолжать держать его на виду. Случайный поиск по-прежнему разрешен.
```suggestion
    но может продолжать носить его на виду. Случайный поиск по-прежнему разрешен.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Служба безопасности может постоянно иметь оружие без кобур.
```suggestion
    Служба безопасности может постоянно носить оружие без кобуры.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Служба безопасности может постоянно иметь оружие без кобур, разрешены и рекомендованы случайные обыски.
```suggestion
    Служба безопасности может постоянно носить оружие без кобуры, разрешены и рекомендованы случайные обыски.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    К сожалению, в настоящее время мы не смогли отправить ни одного из них.
```suggestion
    К сожалению, в настоящее время мы не смогли отправить никого из её состава.
```

2022-04-12 12:09 UTC, kreeperHLC commented on localization/ru.ftl
> +    Мы подготовим и отправим его как можно скорее.
```suggestion
    Мы подготовим и отправим её как можно скорее.
```

2022-04-12 13:08 UTC, TobyThorne commented on code/modules/events/rogue_drones.dm
> -	if(num_recovered > drones_list.len * 0.75)
а поч тут логика померла

2022-04-12 13:09 UTC, igorsaux commented on code/modules/events/rogue_drones.dm
> -	if(num_recovered > drones_list.len * 0.75)
В обоих случаях выполняется одинаковый анонс

2022-04-12 13:13 UTC, TobyThorne commented on localization/ru.ftl
> +    Всему персоналу необходимо сдержать угрозу.
```suggestion
    Весь персонал обязан соучаствовать в сдерживании угрозы.
```

2022-04-12 13:19 UTC, TobyThorne commented on localization/ru.ftl
> +    Обнаружены неопознанные признаки жизни на борту { $station_name }.
```suggestion
    Обнаружены присутствие неопознанных организмов на борту { $station_name }.
```
Лучше уж так, чем _неопознанные признаки жизни_.

2022-04-12 13:20 UTC, TobyThorne commented on localization/ru.ftl
> +    Высокий уровень радиации был обнаружен в непосредственной близости от { $station_name }.
```suggestion
    Высокий уровень радиации был зафиксирован в непосредственной близости от { $station_name }.
```

2022-04-12 13:23 UTC, TobyThorne commented on localization/ru.ftl
> +    Предупреждение о электрическом шторме
```suggestion
    Предупреждение об электрическом шторме
```

2022-04-12 13:23 UTC, TobyThorne commented on localization/ru.ftl
> +    В вашем районе была обнаружена электрическая буря, пожалуйста, устраните возможные электронные перегрузки.
```suggestion
    В вашем районе была обнаружена электрическая буря, пожалуйста, устраните возможные электрические перегрузки.
```

2022-04-12 13:24 UTC, TobyThorne commented on localization/ru.ftl
> +    Предупреждение о электрическом шторме
```suggestion
    Предупреждение об электрическом шторме
```

2022-04-12 13:29 UTC, TobyThorne commented on localization/ru.ftl
> +    На борту { $location_name } был обнаружен аномальный искусственный интеллект.
```suggestion
    На борту { $location_name } было обнаружено зловредное маркетинговое ПО.
```
Ближе по смыслу, хотя всё ещё не совсем дословно. Зато смешно.

2022-04-12 13:30 UTC, TobyThorne commented on localization/ru.ftl
> +    Все следы аномального искусственного интеллекта исчезли из систем.
```suggestion
    Все следы зловредного ПО исчезли из систем.
```

2022-04-12 13:31 UTC, TobyThorne commented on localization/ru.ftl
> +    Высокие уровни помех блюспейса обнаружены в { $area }.
```suggestion
    Высокие уровни блюспейс-интерференции обнаружены в { $area }.
```
То же самое, но заумнее. Ибо блюспейс.

2022-04-12 13:32 UTC, TobyThorne commented on localization/ru.ftl
> +    Блюспейс помехи прекратились.
```suggestion
    Блюспейс-интерференция возвращается к безопасным значениям.
```

2022-04-12 13:33 UTC, TobyThorne commented on localization/ru.ftl
> +    многие сотрудники мертвы или скоро умрут. В настоящее время мы обнаруживаем все больше признаков того, что сама Вселенная начинает распадаться.
```suggestion
    многие сотрудники либо уже мертвы, либо серьёзно пострадали. В настоящее время мы обнаруживаем все больше признаков того, что сама Вселенная начинает распадаться.
```

2022-04-12 13:35 UTC, TobyThorne commented on localization/ru.ftl
> +    Да спасёт Господь ваши д[\[###!!!-
```suggestion
    Да помилует Господь ваши д[\[###!!!-
```

2022-04-12 13:36 UTC, TobyThorne commented on localization/ru.ftl
> +    Да спасёт Господь ваши д[\[###!!!-
Тут для "спасёт" уже поздновато

2022-04-12 13:37 UTC, TobyThorne commented on localization/ru.ftl
> +    { $location_name } прошел через пояс космической пыли.
```suggestion
    { $location_name } покидает пояс космической пыли.
```
А то вдруг будет станция с женским именем

2022-04-12 13:38 UTC, TobyThorne commented on localization/ru.ftl
> +    Биосканеры показывают, что { $vermstring } размножились в { $location }.
```suggestion
    Биосканеры показывают, что { $vermstring } размножаются в { $location }.
```

2022-04-12 13:40 UTC, TobyThorne commented on localization/ru.ftl
> +    Датчик морских тварей майора Билла
```suggestion
    Датчик корабельных крыс Майора Билла
```

2022-04-12 13:42 UTC, TobyThorne commented on localization/ru.ftl
> +    Датчик морских тварей майора Билла
А вообще тут можно и оригинальное название оставить, всё таки слишком уж название.

2022-04-12 13:44 UTC, TobyThorne commented on localization/ru.ftl
> +    Обнаружен взлом с помощью метода перебора (выполняется с момента { $time }). Целью атаки являются: Финансовые счета.
```suggestion
    Зафиксирована брутфорс-атака (выполняется с момента { $time }). Целью атаки являются: Финансовые счета.
```
А то чёт совсем **_перебор_**

2022-04-12 13:45 UTC, TobyThorne commented on localization/ru.ftl
> +    повышение уровня безопасности учетной записи. Уведомления будут отправляться по мере появления обновлений.
```suggestion
    повышение уровня безопасности учетных записи. Уведомления будут отправляться по мере появления обновлений.
```

2022-04-12 13:46 UTC, TobyThorne commented on localization/ru.ftl
> +    Без вмешательства эта атака успешно завершится примерно через 10 минут. Возможные решения: приостановка учетных записей, отключение интернет-сервера,
```suggestion
    Без вмешательства эта атака успешно завершится примерно через 10 минут. Возможные решения: временная блокировка учетных записей, отключение НТнет-сервера,
```

2022-04-12 13:47 UTC, TobyThorne commented on localization/ru.ftl
> +    Медицинская бригада должна немедленно подготовиться к борьбе с возбудителем вируса.
```suggestion
    Медицинский персонал должен немедленно подготовиться к борьбе с возбудителем вируса.
```
https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D0%B8%D1%86%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0%D0%BB

2022-04-12 13:48 UTC, TobyThorne commented on localization/ru.ftl
> +    Объект { $location_name } вошел в радиационный пояс.
```suggestion
    Объект { $location_name } входит в радиационный пояс.
```

2022-04-12 13:48 UTC, TobyThorne commented on localization/ru.ftl
> +    { $location_name } прошел радиационный пояс.
```suggestion
    { $location_name } покидает радиационный пояс.
```

2022-04-12 13:49 UTC, No-Tips commented on localization/ru.ftl
> +    Медицинская бригада должна немедленно подготовиться к борьбе с возбудителем вируса.
Не знаю кого как, но меня вирус возбудил

2022-04-12 13:49 UTC, TobyThorne commented on localization/ru.ftl
> +    Пожалуйста, подождите до одной минуты, пока уровень радиации рассеется,
```suggestion
    Пожалуйста, подождите до одной минуты, пока уровень радиации спадёт,
```

2022-04-12 13:50 UTC, TobyThorne commented on localization/ru.ftl
> +    Внимание: неопознанные патрульные беспилотники обнаружены в непосредственной близости от { $location_name }
```suggestion
    Внимание: неопознанные патрульные дроны обнаружены в непосредственной близости от { $location_name }
```
Что-что, а дрон уж точно слишком плотно вжился в русский язык
Компьютеры всё таки ЭВМами в 2к22 не называем

2022-04-12 13:51 UTC, TobyThorne commented on localization/ru.ftl
> +    Неопознанные беспилотные летательные аппараты приближаются к { $location_name }.
```suggestion
    Неопознанные беспилотные дроны приближаются к { $location_name }.
```

2022-04-12 13:51 UTC, TobyThorne commented on localization/ru.ftl
> +    Лазерный дрон класса II обнаружен рядом с { $location_name }.
```suggestion
    Боевой дрон Class II Laser Fire обнаружен рядом с { $location_name }.
```

2022-04-12 13:54 UTC, TobyThorne commented on localization/ru.ftl
> +    Подтверждена вспышка биологической опасности 7-го уровня на борту { $location_name }.
```suggestion
    Подтверждена вспышка биологической угрозы 7-го уровня на борту { $location_name }.
```

2022-04-12 13:55 UTC, TobyThorne commented on localization/ru.ftl
> +    Весь персонал должен сдерживать вспышку.
```suggestion
    Весь персонал обязан соучаствовать в сдерживании угрозы.
```

2022-04-12 13:55 UTC, TobyThorne commented on localization/ru.ftl
> +    Предупреждение о биологической опасности
```suggestion
    Предупреждение о биологической угрозе
```

2022-04-12 13:55 UTC, TobyThorne commented on localization/ru.ftl
> +    Предупреждение о биологической опасности
```suggestion
    Предупреждение о биологической угрозе
```

2022-04-12 13:56 UTC, TobyThorne commented on localization/ru.ftl
> +    На станции обнаружены пространственно-временные аномалии.
```suggestion
    На борту станции обнаружены пространственно-временные аномалии.
```

2022-04-12 13:57 UTC, TobyThorne commented on localization/ru.ftl
> +    Что, черт возьми, это было?!
```suggestion
    Что это, блядь, было?!
```
Кажется, ИРЛ Игорь кино переводит

2022-04-12 14:00 UTC, TobyThorne commented on localization/ru.ftl
> +    Все СПИНЭ на { $station_name } были пополнены. Приносим извинения за причиненные неудобства.
```suggestion
    Все СМЕСы на { $station_name } были пополнены. Приносим извинения за причиненные неудобства.
```
Все уж слишком привыкли к СМЕСам, а от такого варианта у меня аж боли в СПИНЭ начинаются

2022-04-12 14:03 UTC, TobyThorne commented on localization/ru.ftl
> +    Запланирован трансфер экипажа с { $dock_name }.
А что если "развозка" вместо "трансфера"? :kek:

2022-04-12 14:03 UTC, TobyThorne commented on localization/ru.ftl
> +    } шаттл приоетит в { $dock_name }.
```suggestion
    } шаттл прилетит в { $dock_name }.
```
приоетели

2022-04-12 14:04 UTC, TobyThorne commented on localization/ru.ftl
> +    Был вызван аварийный эвакуационный шаттл. Он прибудет примерно через { $eta ->
```suggestion
    Был вызван экстренный эвакуационный шаттл. Он прибудет примерно через { $eta ->
```

2022-04-12 14:04 UTC, TobyThorne commented on localization/ru.ftl
> +    Был отправлен аварийный спасательный шаттл.
```suggestion
    Был отправлен экстренный спасательный шаттл.
```

2022-04-12 14:04 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийный шаттл был отозван.
```suggestion
    Экстренный шаттл был отозван.
```

2022-04-12 14:04 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийный шаттл был отозван.
```suggestion
    Экстренный шаттл был отозван.
```

2022-04-12 14:05 UTC, TobyThorne commented on localization/ru.ftl
> +    Наблдюдающий отклонил экстренный запрос. Возвращайтесь на свой пост.
```suggestion
    Наблюдающий отклонил экстренный запрос. Возвращайтесь на свои рабочие места.
```

2022-04-12 14:05 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийный шаттл состыковался со станцией.
```suggestion
    Экстренный шаттл состыковался со станцией.
```

2022-04-12 14:06 UTC, TobyThorne commented on localization/ru.ftl
> +    } для посадки на Аварийный шаттл.
```suggestion
    } для посадки на экстренный шаттл.
```

2022-04-12 14:06 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийный спасательный шаттл состыкаовался.
```suggestion
    Экстренный спасательный шаттл состыковался.
```
Лютик, блядь!

2022-04-12 14:06 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийный шаттл покинул станцию. Через приблизительно { $eta ->
```suggestion
    Экстренный шаттл покинул станцию. Через приблизительно { $eta ->
```

2022-04-12 14:06 UTC, TobyThorne commented on localization/ru.ftl
> +    } шаттл приоетит в { $dock_name }.
```suggestion
    } шаттл прилетит в { $dock_name }.
```
ъуъ

2022-04-12 14:07 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийный спасательный шаттл вылетел из { $dock_name }.
```suggestion
    Экстренный спасательный шаттл вылетел из { $dock_name }.
```

2022-04-12 14:07 UTC, TobyThorne commented on localization/ru.ftl
> +    Аварийные шаттлы вылетают из RnCC Demeter и прибудут в течении { $eta ->
```suggestion
    Экстренные шаттлы вылетают из RnCC Demeter и прибудут в течении { $eta ->
```

2022-04-12 14:07 UTC, TobyThorne commented on localization/ru.ftl
> +    Эвакуация была прервана из-за блюспейс искажения.
```suggestion
    Эвакуация была прервана из-за блюспейс-искажения.
```

2022-04-12 14:08 UTC, TobyThorne commented on localization/ru.ftl
> +    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - выглядит невооруженной для приблизительного сканирования.
```suggestion
    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - поверхностное сканирование не выявило наличие вооружения.  
```

2022-04-12 14:09 UTC, TobyThorne commented on localization/ru.ftl
> +    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - выглядит невооруженной для приблизительного сканирования.
```suggestion
    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - поверхностное сканирование не выявило наличие вооружения. 
```

2022-04-12 14:12 UTC, TobyThorne commented on localization/ru.ftl
> +    Внимание, к станции приближается невооруженное грузовое судно, которое, по-видимому, является торговым судном.
```suggestion
    Внимание, к станции приближается невооруженное грузовое судно, по-видимому, являющееся торговым.
```

2022-04-12 14:17 UTC, TobyThorne commented on localization/ru.ftl
> +    Ваши посетители на пути к выходу из системы, удирая так быстро, как только можно. Скатертью дорожка.
```suggestion
    Ваши посетители на второй космической скорости покидают границы системы. Скатертью дорожка.
```

2022-04-12 14:17 UTC, TobyThorne commented on localization/ru.ftl
> +    Ваши посетители на пути к выходу из системы, удирая так быстро, как только можно. Скатертью дорожка.
```suggestion
    Ваши посетители на второй космической скорости покидают границы системы. Скатертью дорожка.
```

2022-04-12 14:18 UTC, TobyThorne commented on localization/ru.ftl
> +    Обнаружены неопознанные признаки жизни, поступающие с борта { $station_name }.
```suggestion
    Обнаружено присутствие неопознанных биосигнатур на борту { $station_name }.
```

2022-04-12 14:19 UTC, TobyThorne commented on localization/ru.ftl
> +    Обнаружены неопознанные признаки жизни, поступающие с борта { $station_name }.
```suggestion
    Обнаружено присутствие неопознанных организмов на борту { $station_name }.
```

2022-04-12 14:30 UTC, TobyThorne commented on localization/ru.ftl
> +    Похоже, что для { $station_name } была запрошена группа экстренного реагирования.
```suggestion
    Похоже, что для { $station_name } был запрошен Отряд Быстрого Реагирования.
```

2022-04-12 14:30 UTC, TobyThorne commented on localization/ru.ftl
> +    Мы подготовим и отправим её как можно скорее.
```suggestion
    Мы подготовим и отправим его как можно скорее.
```

2022-04-12 14:30 UTC, TobyThorne commented on localization/ru.ftl
> +    Похоже, что для { $station_name } была запрошена группа экстренного реагирования.
```suggestion
    Похоже, что для { $station_name } был запрошен Отряд Быстрого Реагирования.
```

2022-04-12 14:30 UTC, TobyThorne commented on localization/ru.ftl
> +        "сверхматериальной пыль",
```suggestion
        "сверхматериальной пыли",
```

2022-04-12 14:31 UTC, TobyThorne commented on localization/ru.ftl
> +        "квантовыъ флуктуации",
```suggestion
        "квантовых флуктуации",
```

2022-04-12 14:31 UTC, TobyThorne commented on localization/ru.ftl
> +    группы экстренного реагирования в настоящее время не могут быть вызваны, и
```suggestion
    Отряды Быстрого Реагирования в настоящее время не могут быть вызваны, и
```

2022-04-12 14:32 UTC, TobyThorne commented on localization/ru.ftl
> +        "восстания таджарских рабов",
```suggestion
        "восстания рабов-таяран",
```

2022-04-12 14:33 UTC, TobyThorne commented on localization/ru.ftl
> +        "секретных операции по обеспечению безопасности"
```suggestion
        "секретных операции по обеспечению безопасности",
        "спецоперации по десиндикации Марса"
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    По нашим оценкам, у вас есть пять минут до того, как в ваших помещениях откроется разлом блюспейса.
```suggestion
    По нашим оценкам, у вас есть пять минут до того, как в ваших помещениях откроется пространственно-временной разлом.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Не существует известного способа остановить образование разлома, равно как и какого-либо способа избежать его.
```suggestion
    Не существует известного способа остановить его образование, равно как и какого-либо способа избежать.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    IDS сообщает, что IPS был отключен. Уровень тревоги о вторжении: КРАСНЫЙ.
```suggestion
    система обнаружения сообщает, что система предотвращения вторжений была отключена. Уровень тревоги о вторжении: КРАСНЫЙ.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Идентификатор сообщает, что передача была принята устройством. Источник передачи: "Неизвестен".
```suggestion
    Система обнаружения сообщает, что передача была принята устройством. Источник передачи: "Неизвестен".
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Всплеск обратной гравитационной связи обнаружен в системах массового распределения.
```suggestion
    Обратный гравитационный всплеск был замечен в системах распределения массы.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Все СМЕСы на { $station_name } были пополнены. Приносим извинения за причиненные неудобства.
```suggestion
    Все СМЕСы на { $station_name } были перезаряжены. Приносим извинения за причиненные неудобства.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Наблюдающий отклонил экстренный запрос. Возвращайтесь на свои рабочие места.
```suggestion
    Экстренный запрос был отклонен наблюдающим. Возвращайтесь на свои рабочие места.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - поверхностное сканирование не выявило наличие вооружения.
```suggestion
    Внимание, мы зафиксировали приближение к вашей станции большого объекта, наши сканеры не зафиксировали вооружения.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Мы слишком далеко, чтобы её перехватить - приготовьтесь к посетителям.
```suggestion
    Мы слишком далеко для перехвата - приготовьтесь к гостям.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - поверхностное сканирование не выявило наличие вооружения.
```suggestion
    Внимание, мы зафиксировали приближение к вашей станции большого объекта, наши сканеры не зафиксировали вооружения.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Мы слишком далеко, чтобы её перехватить - приготовьтесь к посетителям.
```suggestion
    Мы слишком далеко для перехвата - приготовьтесь к гостям.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Ваши посетители на второй космической скорости покидают границы системы. Скатертью дорожка.
```suggestion
    Ваши гости на второй космической скорости покидают границы системы. Скатертью дорожка.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Ваши посетители на второй космической скорости покидают границы системы. Скатертью дорожка.
```suggestion
    Ваши гости на второй космической скорости покидают границы системы. Скатертью дорожка.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Все угрозы станции миновали. Службы безопасности не может носить оружие на виду,
```suggestion
    Все угрозы станции устранены. Служба безопасности не может носить оружие на виду,
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    У сотрудников службы безопасности может носить оружие на виду, разрешены "случайные обыски".
```suggestion
    Сотрудники службы безопасности могут носить оружие на виду, разрешены "случайные обыски".
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Непосредственная угроза миновала. Служба безопасности больше не может постоянно держать оружие наготове,
```suggestion
    Непосредственная угроза устранена.  Сотрудники службы безопасности больше не могут постоянно держать оружие в боевой готовности,
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    но может продолжать носить его на виду. Случайный поиск по-прежнему разрешен.
```suggestion
    но может продолжать носить его на виду. Случайные обыски по-прежнему разрешены.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Служба безопасности может постоянно носить оружие без кобуры.
```suggestion
    Сотрудники службы безопасности могут постоянно держать оружие в боевой готовности.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Случайный поиск разрешен и рекомендуется.
```suggestion
    Случайные обыски по-прежнему разрешены и рекомендуются.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Служба безопасности может постоянно носить оружие без кобуры, разрешены и рекомендованы случайные обыски.
```suggestion
    Сотрудники службы безопасности могут постоянно держать оружие в боевой готовности, случайные обыски разрешены и рекомендуются.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Механизм самоуничтожения был включен.
```suggestion
    Механизм самоуничтожения был активирован.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Весь экипаж проинструктирован выполнять все инструкции, данные руководителями персонала.
```suggestion
    Все члены экипажа должны подчиняться приказам руководителей персонала.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    К сожалению, в настоящее время мы не смогли отправить никого из её состава.
```suggestion
    К сожалению, в настоящее время мы не можем его отправить.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Последовательность самоуничтожения достигла конечного обратного отсчета, системы прерывания были отключены.
```suggestion
    Механизм самоуничтожения достиг достиг точки невозврата, система аварийной отмены отключена.
```

2022-04-12 19:24 UTC, NefrNerf commented on localization/ru.ftl
> +    Груз отправлен через баллистическую капсулу снабжения для немедленной доставки. Хорошего дня.
```suggestion
    Груз отправлен баллистической капсулой снабжения немедленной доставки. Хорошего дня.
```

2022-04-12 20:00 UTC, Doster-d commented on localization/ru.ftl
> +    система обнаружения сообщает, что система предотвращения вторжений была отключена. Уровень тревоги о вторжении: КРАСНЫЙ.
```suggestion
    Система обнаружения вторжения сообщает, что система предотвращения вторжений была отключена. Статус сигнала вторжении: КРАСНЫЙ.
```

2022-04-12 20:00 UTC, Doster-d commented on localization/ru.ftl
> +    Система обнаружения сообщает, что передача была принята устройством. Источник передачи: "Неизвестен".
```suggestion
    Система обнаружения вторжения сообщает, что передача была принята устройством. Источник передачи: "Неизвестен".
```

2022-04-12 20:00 UTC, Doster-d commented on localization/ru.ftl
> +    Подпись: "Сигнал бедствия NT высшего уровня". Обнаружен процесс триангуляции.
```suggestion
    Сигнатура: "Сигнал бедствия NT высшего уровня". Обнаружен процесс триангуляции.
```
https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%B3%D0%BD%D0%B0%D1%82%D1%83%D1%80%D0%B0_%D0%B0%D1%82%D0%B0%D0%BA%D0%B8

2022-04-13 03:42 UTC, TobyThorne commented on localization/ru.ftl
> +    Внимание, рядом с вами находится большая сигнатура, приближающаяся к станции - поверхностное сканирование не выявило наличие вооружения.
Каво. В оригинале говорится как раз про поверхностное сканирование. Как в Космических Рейнджерах, когда у тебя сканнер пососный.

2022-05-28 16:05 UTC, igorsaux commented
☠️

2022-05-28 16:05 UTC, closed without merging