add(ghost): add health analyzer for ghost
ChaoticOnyx/OnyxBay pull request #8007
Opened 2022-04-15 16:32 UTC by EnderGolem

Призракам добавлен сканер здоровья, на правую кнопку мыши.

close #2085

<details>
<summary>Чейнджлог</summary>

```yml
🆑 Eshanko
tweak: Призракам добавлен сканер здоровья, на правую кнопку мыши.
/🆑
```

</details>
- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-15 16:49 UTC, NefrNerf commented
У нас же менюшка выпадает на правую кнопку, ты туда опцию добавил, я так понял?

2022-04-15 16:57 UTC, Zert0X requested changes

2022-04-15 16:57 UTC, Zert0X commented on code/game/objects/items/devices/scanners.dm
> +			user.visible_message("<span class='notice'>\The [user] runs \the [src] over \the [target].</span>")
Костыль

2022-04-15 16:57 UTC, Zert0X commented on code/modules/mob/observer/ghost/ghost.dm
> +		show_browser(usr, H.get_medical_data() + text("<BR><A href='?src=\ref[];mach_close=scanconsole'>Close</A>", usr) , "window=scanconsole;size=430x600")
Смешная штука в целом
Если не включен антаг худ то выводим скан с хилсканера, если включен то выводим мед дату, смысол?
может так?
```suggestion
	show_browser(usr, H.get_medical_data() + text("<BR><A href='?src=\ref[];mach_close=scanconsole'>Close</A>", usr) , "window=scanconsole;size=430x600")
```

2022-04-15 17:03 UTC, Zert0X commented on code/modules/mob/observer/ghost/ghost.dm
> +		show_browser(usr, H.get_medical_data() + text("<BR><A href='?src=\ref[];mach_close=scanconsole'>Close</A>", usr) , "window=scanconsole;size=430x600")
```suggestion
	usr.show_message(medical_scan_results(H, 1))
```
Или так

2022-04-15 17:22 UTC, EnderGolem commented
> У нас же менюшка выпадает на правую кнопку, ты туда опцию добавил, я так понял?

Да

2022-04-16 12:33 UTC, Doster-d requested changes

2022-04-16 12:33 UTC, Doster-d commented on code/modules/mob/observer/ghost/ghost.dm
> +/mob/observer/ghost/verb/analyse_health(mob/living/carbon/human/H as mob in GLOB.human_mob_list)
```suggestion
/mob/observer/ghost/verb/analyse_health(mob/living/carbon/human/H)
```
Делай istype(H) внутри метода.

2022-04-16 19:08 UTC, Doster-d commented on code/modules/mob/observer/ghost/ghost.dm
> +    	return;
```suggestion
```

2022-04-16 19:09 UTC, Doster-d commented on code/modules/mob/observer/ghost/ghost.dm
> +	if(!istype(H, /mob))
```suggestion
```

2022-04-16 19:09 UTC, Doster-d commented on code/modules/mob/observer/ghost/ghost.dm
> +/mob/observer/ghost/verb/analyse_health(mob/living/carbon/human/H)
```suggestion
/mob/observer/ghost/verb/analyse_health(mob/living/carbon/human/H as mob in GLOB.human_mob_list)
```

2022-04-16 19:09 UTC, Doster-d commented on code/modules/mob/observer/ghost/ghost.dm
> +/mob/observer/ghost/verb/analyse_health(mob/living/carbon/human/H as mob in GLOB.human_mob_list)
Я еблан.

2022-04-16 19:43 UTC, Zert0X approved these changes

2022-04-16 20:32 UTC, Doster-d approved these changes

2022-04-16 20:32 UTC, merged