Map(add):Toxins polygon lower level
ChaoticOnyx/OnyxBay pull request #8053
Opened 2022-04-20 19:35 UTC by Mrbuble

Создан нижний уровень полигона токсинов
<details>
<summary>Чейнджлог</summary>

```yml
🆑
prefix: maptweak
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-20 20:08 UTC, No-Tips commented on maps/exodus/exodus-1.dmm
> +"oiL" = (/obj/machinery/camera/network/research{c_tag = "Research - Toxins Test Chamber East Maintrance"; dir = 8},/obj/structure/window/plasmareinforced{dir = 8},/turf/simulated/floor/plating/airles
Подкинул бы ты тэг другой это камере
```suggestion
"oiL" = (/obj/machinery/camera/network/research{c_tag = "Research - Undergorund Toxins Test Chamber"; dir = 8},/obj/structure/window/plasmareinforced{dir = 8},/turf/simulated/floor/plating/airless,/area/rnd/test_area)
```

2022-04-20 20:08 UTC, No-Tips commented on maps/exodus/exodus-1.dmm
> +"xbZ" = (/obj/structure/window/reinforced{dir = 4},/obj/structure/window/reinforced{dir = 1; health = null},/turf/simulated/floor/plating/airless,/area/rnd/test_area)
Стекла точно нормально работают с `health = null`?

2022-04-20 20:08 UTC, No-Tips commented on maps/exodus/exodus-1.dmm
> +"kPG" = (/obj/structure/window/reinforced{dir = 1; health = null},/turf/simulated/floor/tiled/airless,/area/rnd/test_area)
Вот тут тоже самое с health

2022-04-20 20:08 UTC, No-Tips commented on maps/exodus/exodus-1.dmm
> +"awd" = (/obj/structure/computerframe{dir = 8},/obj/item/stack/cable_coil,/obj/effect/decal/cleanable/dirt,/turf/simulated/floor/trim/wood,/area/maintenance/ghetto_strangeplace)
Случайно тронул дир тут? Не то, чтобы критично, но можно и убрать!
```suggestion
"awd" = (/obj/structure/computerframe,/obj/item/stack/cable_coil,/obj/effect/decal/cleanable/dirt,/turf/simulated/floor/trim/wood,/area/maintenance/ghetto_strangeplace)
```

2022-04-20 20:11 UTC, No-Tips commented
Блин, решаешь проблемы быстрее, чем я оформляю их в гите.

2022-04-21 09:15 UTC, Mrbuble commented on maps/exodus/exodus-1.dmm
> +"awd" = (/obj/structure/computerframe{dir = 8},/obj/item/stack/cable_coil,/obj/effect/decal/cleanable/dirt,/turf/simulated/floor/trim/wood,/area/maintenance/ghetto_strangeplace)
По поводу дира, уже пофикшен?

2022-04-21 09:16 UTC, Mrbuble commented
> Блин, решаешь проблемы быстрее, чем я оформляю их в гите.

Мне в дс же писали, как у компухтера был так и заделал

2022-04-21 09:17 UTC, Mrbuble commented
И что нужно что бы гит чек прошёл первый?

2022-04-21 11:38 UTC, No-Tips commented
Ты билд вообще запускал? У тебя при компиле ошибки

loading exodus/exodus-1.dmm
maps/exodus/exodus-1.dmm:2998:error: expected }
maps/exodus/exodus-1.dmm:2998:error: expected )

2022-04-21 13:57 UTC, Zert0X commented
> Ты билд вообще запускал? У тебя при компиле ошибки
> 
> loading exodus/exodus-1.dmm maps/exodus/exodus-1.dmm:2998:error: expected } maps/exodus/exodus-1.dmm:2998:error: expected )

Он не умеет

2022-04-21 13:58 UTC, Zert0X commented
>maptweak: exodus-1: Добавлен нижний уровень полигона токсинов
просто "Исход" игроки в рот не знают что такое exodus-1

2022-05-04 15:58 UTC, kreeperHLC requested changes
Конфликты

2022-06-04 05:56 UTC, HonkyDonky commented
От автора ни слуху ни духу с 18 апреля, а его ПР погряз конфликтами и чендж реквестами. Закрываю.

2022-06-04 05:56 UTC, closed without merging