tweak(resonator): add reload time
ChaoticOnyx/OnyxBay pull request #8071
Opened 2022-04-23 15:13 UTC by Artemonim

close #494

<summary>Чейнджлог</summary>

```yml
🆑
balance: Шахтёрскому резонатору нужно время на перезарядку
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-23 15:24 UTC, TobyThorne commented on code/modules/mining/mine_items.dm
> +		if(do_after(user, DEFAULT_WEAPON_COOLDOWN, get_turf(user)))
Гениальное решение. Если во время КД резонатор выпадет из рук - он навечно останется в кулдауне.

2022-04-23 16:24 UTC, Doster-d commented on code/modules/mining/mine_items.dm
> +		if(do_after(user, DEFAULT_WEAPON_COOLDOWN, get_turf(user)))
А нельзя кулдаун на таймер перенести, а?

2022-04-23 16:39 UTC, TobyThorne commented on code/modules/mining/mine_items.dm
> +		if(do_after(user, DEFAULT_WEAPON_COOLDOWN, get_turf(user)))
Да на кой ляд тебе таймер, это оверхед ради понтов. Можно просто проверять world.time.

2022-04-24 08:18 UTC, DarkHunter7756 commented
Может ему просто урон уменьшить? Релоад тайм его в класс "хрень" занерфит.

2022-04-24 08:20 UTC, Artemonim commented
> Может ему просто урон уменьшить? Релоад тайм его в класс "хрень" занерфит.

С автокликерами не поможет

2022-04-24 08:49 UTC, DarkHunter7756 commented
> С автокликерами не поможет

Так это чит. А чит запрещен конвенцией попуха от 2019

2022-05-07 20:03 UTC, TermService commented on code/modules/mining/mine_items.dm
> +	in_use = FALSE
а зачем...

2022-05-07 20:03 UTC, TermService commented on code/modules/mining/mine_items.dm
> +		if(do_after(user, DEFAULT_WEAPON_COOLDOWN, get_turf(user)))
для объектов такой не годится, или модный таймер или добротный вордтайм

2022-05-07 20:04 UTC, Zert0X requested changes

2022-05-07 20:04 UTC, Zert0X commented on code/modules/mining/mine_items.dm
> +			in_use = FALSE
`var/attack_cooldown = DEFAULT_WEAPON_COOLDOWN // 0.5 second`
Говорит привет

2022-05-11 09:50 UTC, TobyThorne requested changes
таймеры не нужны, впили нормальное человеческое сравнение last_time_used с кулдауном и world.time

2022-05-11 09:56 UTC, HonkyDonky commented
> таймеры не нужны, впили нормальное человеческое сравнение last_time_used с кулдауном и world.time

Так у него без таймера не получится звук воспроизвести по истечению кулдауна. Хотя можно использовать spawn(), но кто гарантирует, что оружие внезапным образом не удалится?

2022-05-11 10:04 UTC, TobyThorne commented
похер на звук
таймеры слишком кривые чтобы ими так спамить

ну либо спавн, проверять на !QDELETED(src) никто не запрещает

2022-06-18 22:24 UTC, Artemonim commented
@TobyThorne, @Zert0X, жду ваши ревью

2022-06-24 16:49 UTC, PlinHost commented
Для ограничения частоты применения уже есть fieldlimit, если с ним какие-то проблемы - исправляйте отдельно

2022-06-24 16:49 UTC, closed without merging