fix(door_assembly): cable dup fix
ChaoticOnyx/OnyxBay pull request #8072
Opened 2022-04-23 15:38 UTC by Artemonim

close #4329

<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Дюп кабелей при разборе шлюза
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-27 16:58 UTC, TermService approved these changes, later dismissed

2022-05-03 17:11 UTC, HonkyDonky requested changes
Если `in_use` не опустить на таб ниже, то в случае, если игрок резко оборвёт процесс обрезания - `in_use` не обновится на `FALSE` и door assembly не сможет быть вновь обрезан. Точно самое и с ломом.

2022-06-18 22:24 UTC, Artemonim commented
@TermService, @HonkyDonky, жду ваши ревью

2022-06-22 22:09 UTC, kreeperHLC approved these changes

2022-07-07 16:47 UTC, HonkyDonky approved these changes

2022-07-17 18:20 UTC, TermService approved these changes

2022-07-17 18:20 UTC, merged