Рефакторинг способностей алиенов + микрофикс
ChaoticOnyx/OnyxBay pull request #8081
Opened 2022-04-24 09:27 UTC by O0oMaximo0O

В проках вербе и процессинге способок продублированные проверки вынесены в отдельные функции.
Спаны заменены макросами.
В способности добавлена проверка на нахождение в вентеляции.

fix #8078 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Чужие больше не могут плевать или бить хвостом из вентеляции.
/🆑
```

</details>

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим x внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над ПРом. ЭТУ СТРОЧКУ НУЖНО УДАЛИТЬ.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-24 09:32 UTC, O0oMaximo0O commented
Линтер врёт?

2022-04-24 11:19 UTC, TobyThorne requested changes
Это не рефактор, а ещё больше спагетти поверх нынешних.
Одну и ту же проверку пихать и в верб, и в вызываемую им функцию вообще смысла нет - достаточно оставить её в функции и не плодить check_nebo, check_allah и т.д.

2022-04-24 11:27 UTC, O0oMaximo0O commented
> 

Ок

2022-04-24 14:07 UTC, TobyThorne commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You cannot leap into vents."))
from

2022-04-24 18:44 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/human_powers.dm
> +		to_chat(src, SPAN("warning", "You cannot leap into vents."))
```suggestion
		to_chat(src, SPAN("warning", "You cannot leap from vents."))
```

2022-04-25 09:17 UTC, TobyThorne approved these changes

2022-04-25 11:58 UTC, Zert0X approved these changes

2022-04-25 12:00 UTC, merged