tweak(robot.dm): Radial menu for mode and hull choices
ChaoticOnyx/OnyxBay pull request #8089
Opened 2022-04-25 02:19 UTC by Artemonim

close #6498

Не порт, но перевожу меню настройки борга на радиальные рельсы.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Спецификация и тип борга теперь выбираются в визуальном (радиальном) меню.
/🆑
```

</details>

- bugfix
- balance
- tweak
- soundadd
- sounddel
- rscadd
- rscdel
- imageadd
- imagedel
- maptweak
- spellcheck
- experiment
- admin

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-25 06:05 UTC, Zert0X commented
А зачем? Как я буду понимать кто есть кто?
Уж лучше выбор внешнего вида не радиальное

2022-04-25 06:08 UTC, DarkHunter7756 commented
> А зачем? Как я буду понимать кто есть кто? Уж лучше выбор внешнего вида не радиальное

Слева внизу есть интерфейс, который показывает наименование объектов. Наименование скинчиков он тоже показывает

2022-04-25 06:30 UTC, NefrNerf commented
Там и Тоби против такой реализации, лучше сделать скины на тип борга в радиальном меню

2022-04-27 16:57 UTC, TermService approved these changes

2022-04-28 04:50 UTC, TobyThorne requested changes
Во-первых, какой-то ужас с километровыми свищами и километровым списком статиков в то время, как существует robot_hulls.dm
Во-вторых, убил выбор кастомных скинов, а это уже личное.

2022-04-28 07:44 UTC, Artemonim commented
> Во-первых, какой-то ужас с километровыми свищами и километровым списком статиков в то время, как существует robot_hulls.dm

У меня не получилось вставлять иконки ссылкой на robot_hulls.dm

> Во-вторых, убил выбор кастомных скинов, а это уже личное.

Я взял скины из robot_modules.dm. Можешь сказать, что конкретно не нравится?

2022-04-28 08:18 UTC, Doster-d commented
Ты мой модуль импорт кастомок для силиконов убил

2022-04-28 09:11 UTC, Artemonim commented
> импорт кастомок для силиконов

Подскажешь как починить?

2022-05-09 19:37 UTC, closed without merging

2022-05-09 20:05 UTC, NefrNerf commented
@Artemonim Почини кастомки, сделай так, чтобы можно было применять на себя скины, а не один раз выбирать и
 попробуй еще раз. 
 

>  poor IT — Сегодня, в 23:03
> идея хорошая реализация не хорошая

2022-05-09 20:50 UTC, Artemonim commented
> @Artemonim Почини кастомки, сделай так, чтобы можно было применять на себя скины, а не один раз выбирать и
>  попробуй еще раз. 
>  
> 
> >  poor IT — Сегодня, в 23:03
> > идея хорошая реализация не хорошая

Нахуя закрывать, если можно запросить изменения.

2022-05-09 20:56 UTC, NefrNerf commented
Я свое одобрение поставил. Вопросы к другим 2

2022-05-09 21:00 UTC, DarkHunter7756 commented
> @Artemonim Почини кастомки, сделай так, чтобы можно было применять на себя скины, а не один раз выбирать и попробуй еще раз.

Господа, а зачем возможность примерки, если и так видно скин на радиальном меню?