Megaphone radio broadcasting fix
ChaoticOnyx/OnyxBay pull request #8099
Opened 2022-04-26 09:05 UTC by Artemonim

close #1444

<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Микрофоны интеркомов теперь слышат звук мегафона
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-27 17:00 UTC, TermService submitted a review, later dismissed

2022-05-03 17:17 UTC, HonkyDonky commented on code/game/objects/items/devices/megaphone.dm
> +					I.talk_into(usr, message, verb = "shout")
Я запрещаю **вам** использовать `usr` в проках. Немедленно прекратите и замените на `user`.

2022-05-07 19:14 UTC, TermService commented on code/game/objects/items/devices/megaphone.dm
> +	var/is_emagged = FALSE
на кой было менять emagged на is_emagged?

2022-05-07 19:14 UTC, TermService approved these changes, later dismissed

2022-05-07 19:25 UTC, TobyThorne requested changes

2022-05-07 19:25 UTC, TobyThorne commented on code/game/objects/items/devices/megaphone.dm
> +	var/is_emagged = FALSE
аналогичный вопрос

2022-05-08 23:17 UTC, Artemonim commented on code/game/objects/items/devices/megaphone.dm
> +	var/is_emagged = FALSE
Разве не лучше, когда bool именуется "is_..." ?

2022-05-09 19:44 UTC, TobyThorne approved these changes

2022-05-13 03:29 UTC, HonkyDonky approved these changes

2022-06-01 16:10 UTC, merged