Криминальные карточки детективу
ChaoticOnyx/OnyxBay pull request #8112
Opened 2022-04-27 14:41 UTC by IvanDonFon

Добавил детективу криминальные карточки, обозначающие улики на месте преступления. До этого они были в спрайтах, но никак не использовались. Вроде всё работает и ничего не багует, но это не точно.

Пока делал ПР, произошёл небольшой прикол с картами, но никак, кроме внешнего вида объёма изменений это не отразится. Вроде.

resolve #6295

<details>
<summary>Чейнджлог</summary>

```yml
🆑Donaldo_TH
tweak: У детектива появились номерки для улик
/🆑
```

</details>

- [ x ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ x ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ x ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ x ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-27 14:42 UTC, IvanDonFon commented
Игнорируйте, пожалуйста, что у меня там 159 тысяч добавлений, там прикол получился

2022-04-27 14:43 UTC, Zert0X commented
ебучий случай
А не легче их кодом в шкаф пихнуть?!

2022-04-27 14:43 UTC, Zert0X commented
А ещё вы забыли сансет

2022-04-27 14:44 UTC, IvanDonFon commented
> ебучий случай А не легче их кодом в шкаф пихнуть?!

Да, знаешь, я подумал об этом, когда увидел 159 тысяч новых строк

2022-04-27 14:44 UTC, IvanDonFon commented
Сча всё будет

2022-04-27 14:52 UTC, Doster-d commented
А мап мержером пользоваться нельзя?

2022-04-27 14:54 UTC, IvanDonFon commented
Да он вроде был встроен в StrongDMM, не знаю, что с ним стало

2022-04-27 14:55 UTC, Zert0X commented
> Да он вроде был встроен в StrongDMM, не знаю, что с ним стало

просто надо пользоваться дрим мейкером

2022-04-27 14:56 UTC, IvanDonFon commented
Да, согласен, я раньше всегда в нём карты делал, но потом тёмные силы убедили меня попробовать стороннюю программу для маппинга

2022-04-27 15:17 UTC, NefrNerf commented
Я только аппрув хотел поставить, что по диффам?

2022-04-27 15:18 UTC, IvanDonFon commented
> Я только аппрув хотел поставить, что по диффам?

А, ну там прикол небольшой с мапмержем вышел

2022-04-27 16:53 UTC, TermService requested changes
+159,593 −9,745

2022-05-01 10:16 UTC, IvanDonFon commented
Всё, мужики, теперь за этот ПР не стыдно. Почти нет никаких мусорных коммитов, мержит разрешаю.

2022-05-24 15:14 UTC, IvanDonFon commented
Короче, сами сделаете, если надо будет

2022-05-24 15:15 UTC, NefrNerf commented
Не на моей смене, слапнул бы заново всех

2022-05-24 15:16 UTC, IvanDonFon commented
Насильно открыли ПР :eyes:

2022-05-26 11:30 UTC, IvanDonFon commented
![image0](https://user-images.githubusercontent.com/60175270/170479623-07a9dd00-7169-447f-99cc-68c24dd411fc.gif)

2022-05-26 11:52 UTC, TermService commented
Надо удалить изменения в карте, если не сможешь сам напиши в дискорд

2022-06-22 22:04 UTC, kreeperHLC requested changes

2022-06-22 22:04 UTC, kreeperHLC commented on maps/exodus/exodus-1.dmm
> +"amM" = (/turf/simulated/floor/plating,/area/quartermaster/storage/under)
Убери карту из ПРа, тут ареа меняется

2022-07-01 16:40 UTC, DarkHunter7756 commented
![image](https://user-images.githubusercontent.com/76823962/176935830-d8a8fdf9-5e0e-4c0b-ac31-5462d09a2a8d.png)

2022-07-01 17:02 UTC, IvanDonFon commented
Так, всё... ХА ХА, ВСЁ! Готово! Я гений!

2022-07-01 17:03 UTC, IvanDonFon commented
Кто же знал, что можно было просто удалить файл карты и загрузить новый, с ветки dev?

2022-07-02 17:49 UTC, TermService approved these changes, later dismissed

2022-07-02 22:14 UTC, kreeperHLC approved these changes, later dismissed
Терм, только попробуй случайно смержить, ждём геймовнеров

2022-07-03 11:53 UTC, IvanDonFon commented
Уважаемый гей(м)дизайнеры, одобрите пожалуйста ПР, Дональдо_ТХ хуйни не сделает, вы же знаете.

2022-07-03 12:01 UTC, NefrNerf commented
Слапай Тоби или Плина, я свой поставил

2022-07-03 13:19 UTC, TobyThorne commented on code/modules/detectivework/tools/scene_cards.dm
> +/obj/item/csi_marker/Initialize(mapload)
```suggestion
/obj/item/csi_marker/Initialize()
```

2022-07-03 13:20 UTC, TobyThorne requested changes

2022-07-03 13:20 UTC, TobyThorne commented on code/modules/detectivework/tools/scene_cards.dm
> +	icon_state = "card[Clamp(number,1,7)]"
```suggestion
	icon_state = "card[clamp(number, 1, 7)]"
```

2022-07-03 13:26 UTC, IvanDonFon commented on code/modules/detectivework/tools/scene_cards.dm
> +	icon_state = "card[Clamp(number,1,7)]"
Я исправил, сэр.

2022-07-03 16:16 UTC, TobyThorne approved these changes
ужасно но сойдёт

2022-07-03 16:34 UTC, IvanDonFon commented
@TermService поставьте ещё раз аппрув, пожалуйста

2022-08-01 09:43 UTC, closed without merging