Removes a lot of bad strong referencing from simple_animals
ChaoticOnyx/OnyxBay pull request #8114
Opened 2022-04-27 18:08 UTC by TobyThorne

Где удобнее - викрефы, где не удобно - подписываемся на удаление.
Нормально удаляться мобы от этого ещё не начали, но хотя бы багов будет меньше.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-27 18:33 UTC, Doster-d commented on code/modules/mob/living/simple_animal/friendly/parrot.dm
> +	speak = list("������","������?","����� ���� ������ ������� � �����")
Это норма?

2022-04-27 19:29 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/friendly/parrot.dm
> +	speak = list("������","������?","����� ���� ������ ������� � �����")
это фиаско

2022-04-27 19:30 UTC, Doster-d commented on code/modules/mob/living/simple_animal/friendly/parrot.dm
> +	speak = list("������","������?","����� ���� ������ ������� � �����")
Оно распространилось на другое!

2022-04-27 19:35 UTC, Doster-d approved these changes

2022-04-27 19:36 UTC, Doster-d requested changes

2022-04-27 19:36 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +/mob/living/simple_animal/hostile/Destroy()
```suggestion
/mob/living/simple_animal/hostile/Destroy()
	. = ..()
```

2022-04-27 19:37 UTC, Doster-d commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	friends.Cut()
```suggestion
	friends.Cut()
	return ..()
```
Не, вот так надо.

2022-04-27 19:40 UTC, TobyThorne commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	friends.Cut()
а как оно проебалась-то

2022-04-27 20:03 UTC, Doster-d approved these changes
β먷� ﰬ ﰥ갠񭠿 ꮤ谮⪠

2022-04-28 06:47 UTC, igorsaux approved these changes

2022-04-28 06:55 UTC, merged