bugfix(girder assemblies&lift) Lift tweaks and remove girder assemblies ability to be placed in air
ChaoticOnyx/OnyxBay pull request #8136
Opened 2022-04-28 19:27 UTC by Zert0X

Гирдер теперь нельзя поставить в опенспейсе/космосе. Он должен иметь под собой пол
Лифт теперь подбирает предметы если он на них приехал
Лифт теперь уничтожает структуры и машинерию на которую приедет

<details>
<summary>Чейнджлог</summary>

```yml
🆑Lovla
bugfix: Гирдер теперь нельзя поставить в опенспейсе/космосе. Он должен иметь под собой пол
bugfix: Лифт теперь подбирает предметы если он на них приехал
bugfix: Лифт теперь уничтожает структуры и машинерию на которую приедет
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-04-28 19:27 UTC, igorsaux commented on code/game/objects/items/stacks/assemblies.dm
> +			to_chat(user, "<span class='warning'>\The [name] must be constructed on the floor!</span>")
непон а где макрос

2022-04-28 19:28 UTC, Zert0X commented on code/game/objects/items/stacks/assemblies.dm
> +			to_chat(user, "<span class='warning'>\The [name] must be constructed on the floor!</span>")
Какой макрос ты там хочешь?

2022-04-28 19:28 UTC, igorsaux commented on code/game/objects/items/stacks/assemblies.dm
> +			to_chat(user, "<span class='warning'>\The [name] must be constructed on the floor!</span>")
SPAN

2022-04-28 19:28 UTC, Zert0X commented on code/game/objects/items/stacks/assemblies.dm
> +			to_chat(user, "<span class='warning'>\The [name] must be constructed on the floor!</span>")
Ой... Блэтб ща

2022-04-28 19:38 UTC, Zert0X commented on code/game/objects/items/stacks/assemblies.dm
> +			to_chat(user, "<span class='warning'>\The [name] must be constructed on the floor!</span>")
Исправил

2022-05-07 19:15 UTC, TermService commented on code/game/objects/items/stacks/assemblies.dm
> +		if (istype(src.loc,/turf) && !isfloor(src.loc))
```suggestion
		if(istype(loc, /turf) && !isfloor(loc))
```

2022-05-07 19:16 UTC, TermService commented on code/modules/multiz/industrial_lift/industrial_lift.dm
> +	for(var/AM in src.loc.contents)
```suggestion
	for(var/AM in loc.contents)
```

2022-05-07 19:16 UTC, TermService approved these changes, later dismissed

2022-05-07 20:00 UTC, Doster-d requested changes
Конверсы Терма

2022-05-07 20:21 UTC, TermService approved these changes

2022-05-07 20:24 UTC, Doster-d approved these changes

2022-05-09 19:10 UTC, merged