feature(lisa4frontier)
ChaoticOnyx/OnyxBay pull request #8157
Opened 2022-04-30 23:18 UTC by Shirlineyn

Теперь на Фронтире будет не Ян, а Лиза!

resolves #7117

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Замена Яна на Фронтире на Лизу.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-04 10:13 UTC, Doster-d commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +		if(turns_since_scan == 0)
А это зачем трогал?

2022-05-04 15:43 UTC, kreeperHLC requested changes
Не нужное потрогано

2022-05-05 07:24 UTC, Shirlineyn commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +		if(turns_since_scan == 0)
Потому что из-за того, что turns_since_scan проверяется на на >5 и обнуляется в родительской функции, то в данный кусок кода мы никогда не попадем и секса не будет

2022-05-05 07:25 UTC, Shirlineyn commented
> Не нужное потрогано

 что именно?

2022-05-11 10:10 UTC, TobyThorne approved these changes

2022-05-13 03:31 UTC, HonkyDonky requested changes
/Фикс/ с размножением корги выдели в отдельный ПР, пожалуйста.

2022-06-04 05:53 UTC, HonkyDonky commented
Закрываю, поскольку автор молчит больше месяца, да и ПР всё равно нужно декомпозировать

2022-06-04 05:53 UTC, closed without merging