[Add: #6468] Добавление факелов
ChaoticOnyx/OnyxBay pull request #8169
Opened 2022-05-02 20:37 UTC by osumico

Добавление создаваемого факела вот по этому иссую: [CCЫЛКА](https://github.com/ChaoticOnyx/OnyxBay/issues/6468) (#6468)

На данный момент реализиованы только деревянные факелы, но после отрисовки спрайтов, будет добавлен факел ручкой которого будет металлический прут. В целом данный

<details>
<summary>
Чейнджлог

- Поджигание, самостоятельное тушение факела (10-12 минут)
- Крафт факела из 1-й еденицы дерева, с последующим добавлением одеяла/тряпки
- Свет немного ярче чем от глоустика
- Имеет 7 брут урона, небольшое но оружие. Металлический аналог планируется 10 брут урона.

</summary>

```yml
Osumi
rscadd: Torches!
/Osumi
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-02 20:57 UTC, Zert0X requested changes

2022-05-02 20:57 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		icon_state = "[initial(icon_state)]-rag"
Тут не нужен айтем стейт с тряпкой на факеле?

2022-05-02 20:57 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		done = null
Почему нул, а не FALSE

2022-05-02 20:57 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		lit = null
Почему нул, а не FALSE

2022-05-02 20:57 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +
```suggestion
		desc = "It's a torch, if it burns, it glows, isn't it easy?"
```

2022-05-02 21:03 UTC, osumico commented on code/game/objects/items/devices/flashlight.dm
> +		done = null
Потому что я явно указал нуль, после чего объект фактически становится бесполезным. Я указал это не столько для компилятора, сколько для себя.

2022-05-02 21:04 UTC, osumico commented on code/game/objects/items/devices/flashlight.dm
> +		icon_state = "[initial(icon_state)]-rag"
Нужен, потому что изначальный стейт без тряпки.

2022-05-02 21:06 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		desc = "This is a torch if he burn and make light, easy yeah?"
Спасибо гитхаб, спили лишний desc

2022-05-02 21:07 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		done = null
Ну ты конечно крут в логическую переменную указывать нул, который по факту false.

2022-05-02 21:09 UTC, osumico commented on code/game/objects/items/devices/flashlight.dm
> +		desc = "This is a torch if he burn and make light, easy yeah?"
Что? Зачем?

2022-05-02 21:11 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		desc = "This is a torch if he burn and make light, easy yeah?"
У тебя два desc

2022-05-02 21:11 UTC, Zert0X commented on code/game/objects/items/devices/flashlight.dm
> +		done = null
>>> TRUE/FALSE для логических значений
Во всех случаях, когда нужно логическое значение, вместо 1/0 используйте TRUE/FALSE.

Кто-то жопой читает гайд ту контрибут

2022-05-02 21:12 UTC, osumico commented on code/game/objects/items/devices/flashlight.dm
> +		done = null
Исправил.

2022-06-02 17:36 UTC, Doster-d commented
конфликты

2022-06-22 22:02 UTC, kreeperHLC commented
Мда, сами два месяца не ревьювали, сами дождались конфликтов, сами сейчас и закроем из-за смерти автора

2022-07-17 20:16 UTC, Tsurupeta commented
ПР уже завонялся, автор умер ещё три месяца назад.

2022-07-20 16:03 UTC, DarkHunter7756 commented
Три дня стали прошло, отключаем от жизнеобеспечения.
При необходимости автор может переоткрыть.

2022-07-20 16:03 UTC, closed without merging