refactoring(pipes): Add puffs from active hand to pipes, like a cigare/tes
ChaoticOnyx/OnyxBay pull request #8171
Opened 2022-05-03 01:36 UTC by osumico

Это без иссуя, создано по просьбе в [Дискорде](https://discord.com/channels/414832443384659968/414839549877813251/970849931348832266) нашел просьбу интересной, и реализовал возможность курить трубку с руки! Всем Шерлокам Холмсам и их Ватсонам посвящается...

<details>
<summary>Чейнджлог</summary>

-  Просто добавил новый тип атаки. Теперь можно курить трубку с руки.

```yml
🆑Osumi
rscadd: Add coffee, tean, coco in character creator loadout
/🆑
```
</details>

- [+] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [+] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [+] Я запускал сервер со своими изменениями локально и все протестировал.
- [+] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-03 07:51 UTC, kreeperHLC commented
Чейнджлог обычно на русском пишут

2022-05-03 08:33 UTC, osumico commented
@kreeperHLC обновил чейджлог, наверно теперь более понятно. Это мелкий фикс просто, по этому решил не расписывать по причине "тут все и так понятно"

2022-05-03 08:40 UTC, Zert0X commented
> @kreeperHLC обновил чейджлог, наверно теперь более понятно. Это мелкий фикс просто, по этому решил не расписывать по причине "тут все и так понятно"

Круто но он всё ещё не на русском, плюс ченжлог не для разрабов а для игроков.

2022-05-04 10:10 UTC, Doster-d approved these changes, later dismissed
Вообще по идеи от сигареты должно наследоваться, но похуй

2022-05-04 10:10 UTC, Doster-d commented on code/game/objects/items/smokables/pipes.dm
> +			return 1
```suggestion
			return TRUE
```

2022-05-07 19:23 UTC, TermService submitted a review, later dismissed

2022-05-07 19:26 UTC, TermService commented on code/game/objects/items/smokables/pipes.dm
> +	if(lit && M == user && istype(M, /mob/living/carbon/human))
```suggestion
	if(lit && M == user && ishuman(M)))
```

2022-05-07 19:28 UTC, TermService commented on code/game/objects/items/smokables/pipes.dm
> +		return 1
```suggestion
		return TRUE
```

2022-05-07 19:28 UTC, TermService commented on code/game/objects/items/smokables/pipes.dm
> +		return 1
```suggestion
		return TRUE
```

2022-05-07 19:28 UTC, TermService submitted a review, later dismissed

2022-05-07 19:57 UTC, Zert0X requested changes

2022-05-07 19:57 UTC, Zert0X commented on code/game/objects/items/smokables/pipes.dm
> +		user.visible_message("[user] takes a [pick("drag","puff","pull")] like a boss from \his [name].", \
"like a boss from" меняй

2022-05-08 11:44 UTC, osumico commented on code/game/objects/items/smokables/pipes.dm
> +		user.visible_message("[user] takes a [pick("drag","puff","pull")] like a boss from \his [name].", \
Сделано

2022-05-09 10:26 UTC, Zert0X approved these changes

2022-05-09 19:13 UTC, TobyThorne approved these changes

2022-05-09 19:14 UTC, merged