feat(cigs): cigs are now putted in ashtrays
ChaoticOnyx/OnyxBay pull request #8187
Opened 2022-05-04 09:50 UTC by No-Tips

close #8175 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: бычки от сигарет теперь автоматически помещаются в пепельницы
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-04 10:01 UTC, Doster-d commented on code/game/objects/items/smokables/cigarettes.dm
> +				for(var/obj/item/material/ashtray/A in view(1, loc))
```suggestion
				for(var/obj/item/material/ashtray/A in oview(1, loc))
```

2022-05-04 10:08 UTC, Doster-d submitted a review, later dismissed

2022-05-04 13:15 UTC, kreeperHLC submitted a review, later dismissed

2022-05-06 18:47 UTC, TobyThorne requested changes
Нужна проверка на нахождение в руках/слоте маски. Прыгающие в пепельницы из-за ушей и из карманов сигареты - слишком ржомба.

2022-05-07 19:38 UTC, No-Tips commented
Yes daddy...

2022-05-07 20:09 UTC, Zert0X commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
чёт стрёмная проверка, и почему oview, а не view

2022-05-07 20:11 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
Достер сказал oview. Если знаешь, как такую проверку сделать лучше - буду рад поправить

2022-05-07 20:11 UTC, Doster-d commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
А зачем ему смотреть на зоны, турфы, если ему нужны объекты, а?

2022-05-07 20:12 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
Я нинаю, мне господин девелопер сказал - я, как плебей, подчинился

2022-05-07 20:14 UTC, Zert0X commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
> А зачем ему смотреть на зоны, турфы, если ему нужны объекты, а?

так oview исключает центр.

2022-05-07 20:14 UTC, Doster-d commented on code/game/objects/items/smokables/cigarettes.dm
> +				for(var/obj/item/material/ashtray/A in oview(1, loc))
```suggestion
				for(var/obj/item/material/ashtray/A in view(1, loc))
```
Если нужно, чтобы клали в пепельнице под себя, прими это предложение.

2022-05-07 20:14 UTC, TobyThorne commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
> А зачем ему смотреть на зоны, турфы, если ему нужны объекты, а?

При чём здесь объекты и турфы, если овув - тот же вув, только не чекающий собственный тайл?

2022-05-07 20:15 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
Кодеры, ох уж эти кодеры!!!

2022-05-07 20:15 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						return
Поменял обратно!

2022-05-07 20:16 UTC, Doster-d commented on code/game/objects/items/smokables/cigarettes.dm
> +			if(!M.stat && (src == M.get_equipped_item(slot_wear_mask) || src == M.get_equipped_item(slot_l_hand) || src == M.get_equipped_item(slot_r_hand)))
```suggestion
			if(!M.stat && (src in M.get_equipped_items()))
```
А вот так нельзя?
Оно по слотам смотрит.

2022-05-07 20:18 UTC, Zert0X commented on code/game/objects/items/smokables/cigarettes.dm
> +			if(!M.stat && (src == M.get_equipped_item(slot_wear_mask) || src == M.get_equipped_item(slot_l_hand) || src == M.get_equipped_item(slot_r_hand)))
В целом можно. Так даже лучше того что я предложил.

2022-05-07 20:18 UTC, TobyThorne commented on code/game/objects/items/smokables/cigarettes.dm
> +			if(!M.stat && (src == M.get_equipped_item(slot_wear_mask) || src == M.get_equipped_item(slot_l_hand) || src == M.get_equipped_item(slot_r_hand)))
Так нужна проверка на конкретные слоты. Прыгающие в пепельницы из-за ушей и из карманов сигареты - слишком ржомба.

2022-05-07 20:19 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +			if(!M.stat && (src == M.get_equipped_item(slot_wear_mask) || src == M.get_equipped_item(slot_l_hand) || src == M.get_equipped_item(slot_r_hand)))
Мне ж нужны конкретные слоты, как в моей проверке

2022-05-07 20:20 UTC, Zert0X commented on code/game/objects/items/smokables/cigarettes.dm
> +			if(!M.stat && (src == M.get_equipped_item(slot_wear_mask) || src == M.get_equipped_item(slot_l_hand) || src == M.get_equipped_item(slot_r_hand)))
> Так нужна проверка на конкретные слоты. Прыгающие в пепельницы из-за ушей и из карманов сигареты - слишком ржомба.

ну из-за ушей не очень, а вот карманы да ржомба. Идея же на то что он руками взял и убрал. Но только автоматически. Если уши ещё можно притянуть мол горячо чёт стало, то карманы смешное

2022-05-07 20:21 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +			if(!M.stat && (src == M.get_equipped_item(slot_wear_mask) || src == M.get_equipped_item(slot_l_hand) || src == M.get_equipped_item(slot_r_hand)))
Мне ловла предложил 

`if(src == M.get_equipped_item(slot_wear_mask) || M.is_item_in_hands(src))`

2022-05-07 20:34 UTC, Zert0X submitted a review, later dismissed
LGTM

2022-05-10 08:12 UTC, HonkyDonky submitted a review, later dismissed

2022-05-10 16:02 UTC, No-Tips commented
Меня задушили еще кучей вариаций того, когда не надо класть сигарету в пепельницу.

2022-05-15 10:10 UTC, No-Tips commented
Я хз, если подскажете как заделать проверку на нахождение в ящике - сделаю, хоть это и можно снести на игровую условность. Но а так пока все.

2022-05-15 10:24 UTC, O0oMaximo0O commented
isturf(M.loc)

2022-05-15 10:27 UTC, No-Tips commented
Человек выше боженька иисус

2022-05-26 19:13 UTC, TobyThorne approved these changes, later dismissed
не ревувал, но дебильный гит*хаб не даёт просто снимать ченжреквесты

если прод схрюкнется - кидайтесь говном в ОПа

2022-05-26 19:14 UTC, igorsaux submitted a review, later dismissed
тоби хуйни не апрувнит

2022-05-26 19:16 UTC, No-Tips commented
Ура ура да да

2022-05-26 19:37 UTC, No-Tips commented
Блядь погодите кажется тут осталась хуйня

2022-05-26 19:47 UTC, No-Tips commented
Вот теперь можно.

2022-05-26 19:48 UTC, igorsaux commented on code/game/objects/items/smokables/cigarettes.dm
> +					if(A.contents.len < A.max_butts)
```suggestion
					if(length(A.contents) < A.max_butts)
```

2022-05-26 19:51 UTC, TobyThorne commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
Так, падажжи ёбана, а зачем тут кудел.

2022-05-26 19:57 UTC, No-Tips commented
Done

2022-05-26 19:57 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
Он дальше есть.

2022-05-26 19:58 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
Создается жопка от сигареты, которая заменяет обычную, которая после условия куделяется

2022-05-26 19:59 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
На 55 строке.

2022-05-26 19:59 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
Ну вот так странно закодены сигареты. Надо потом отрефакторить. Но не сегодня.

2022-05-26 20:02 UTC, TobyThorne commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
Так просто вместо
qdel(src)
return
надо впихнуть
break

2022-05-26 20:04 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						qdel(src)
А, ну да. Можно так.

2022-05-26 20:08 UTC, TobyThorne commented on code/game/objects/items/smokables/cigarettes.dm
> +						A.attackby(butt, loc)
```suggestion
						A.attackby(butt, M)
```

2022-05-26 20:08 UTC, TobyThorne commented on code/game/objects/items/smokables/cigarettes.dm
> +				for(var/obj/item/material/ashtray/A in view(1, loc))
```suggestion
				for(var/obj/item/material/ashtray/A in view(1, M))
```

2022-05-26 20:10 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +				for(var/obj/item/material/ashtray/A in view(1, loc))
А разница, если в контексте loc == M?

2022-05-26 20:13 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +				for(var/obj/item/material/ashtray/A in view(1, loc))
Ну хотя ладно, для нормальной читабельности пусть везде будет М.

2022-06-01 16:14 UTC, TermService approved these changes

2022-06-01 16:19 UTC, Doster-d commented on code/game/objects/items/smokables/cigarettes.dm
>  			M.remove_from_mob(src) //un-equip it so the overlays can update
![image](https://user-images.githubusercontent.com/63081538/171451948-28d3d2f8-6abe-402c-bbaa-c713ea4ab27b.png)
![image](https://user-images.githubusercontent.com/63081538/171451992-df9ca8ba-9a3c-426b-afe8-e262b70812a0.png)
Извини, я тебе не верю, что ты проверял.

2022-06-01 16:22 UTC, TermService requested changes

2022-06-01 16:22 UTC, TermService commented on code/game/objects/items/smokables/cigarettes.dm
> +						break
return kde

2022-06-01 16:27 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
>  			M.remove_from_mob(src) //un-equip it so the overlays can update
ПР не трогает src, а взаимодействует с butt, который создан в этом же проке.

2022-06-01 16:28 UTC, No-Tips commented on code/game/objects/items/smokables/cigarettes.dm
> +						break
return тут не подходит, потому что нужен qdel(src), чтобы у нас не было раздвоения сигареты.

2022-06-01 16:29 UTC, Doster-d commented on code/game/objects/items/smokables/cigarettes.dm
>  			M.remove_from_mob(src) //un-equip it so the overlays can update
А блять, жопа же это отдельный предмет, зря я наговорил на тебя.

2022-06-01 16:29 UTC, Doster-d approved these changes

2022-06-02 08:53 UTC, TermService approved these changes

2022-06-02 08:54 UTC, merged