fix(music_tapes):bunch of 0-day fixes
ChaoticOnyx/OnyxBay pull request #8295
Opened 2022-05-10 11:52 UTC by No-Tips

```yml
🆑
bugfix: Коробки из под кассет теперь нельзя свернуть в картонку.
maptweak: Несправедливость с кассетой в баре Исхода и комнате отдыха брига исправлена.
rscadd: Теперь жукбокс можно заблокировать, проведя по ней картой с доступом бармена. Заблокированный жукбокс не дает достать кассету.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-10 11:54 UTC, No-Tips commented
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
![image](https://user-images.githubusercontent.com/75416333/167622393-93161806-a094-4095-919c-72c4a194bd56.png)

2022-05-10 12:02 UTC, Doster-d commented on code/game/machinery/jukebox.dm
> +	req_access = list(25)
```suggestion
	req_access = list(access_bar)
```

2022-05-10 12:28 UTC, Doster-d commented on code/game/objects/items/storage/specialized.dm
> +/obj/item/storage/box/attack_self(mob/user)
Фикс 10 из 10, аплодирую стоя

2022-05-10 13:47 UTC, No-Tips commented on code/game/objects/items/storage/specialized.dm
> +/obj/item/storage/box/attack_self(mob/user)
Я путь проебал :hey:

2022-05-10 15:30 UTC, No-Tips commented
Отреfuckторил, теперь коробки не коробки, а просто сторейдж.

2022-05-10 15:33 UTC, Doster-d requested changes
Еще в мапе насрано, пройтись IDE по ней

2022-05-10 15:33 UTC, Doster-d commented on code/game/objects/items/storage/specialized.dm
> +/obj/item/storage/music_tape/MouseDrop(obj/over_object as obj)
```suggestion
/obj/item/storage/music_tape/MouseDrop()
```

2022-05-10 15:35 UTC, No-Tips commented
![image](https://user-images.githubusercontent.com/75416333/167666952-5bb1b3ca-40df-48d2-afdc-35cc64c3a0c7.png)
Сука как же я люблю когда так происходит, за что мне эта вся боль

2022-05-10 15:59 UTC, No-Tips commented
В мапах разнасрано

2022-05-10 16:12 UTC, Doster-d approved these changes

2022-05-11 06:07 UTC, Doster-d commented on code/game/objects/items/storage/specialized.dm
> +/obj/item/storage/music_tape/AltClick(mob/usr)
```suggestion
/obj/item/storage/music_tape/AltClick(mob/user)
```

2022-05-11 06:07 UTC, Doster-d commented on code/game/objects/items/storage/specialized.dm
>  		attack_hand(usr)
```suggestion
 		attack_hand(user)
```

2022-05-11 06:08 UTC, Doster-d requested changes
Above

2022-05-11 06:14 UTC, No-Tips commented
![image](https://user-images.githubusercontent.com/75416333/167781147-a9ee9236-0c90-4bfa-a1cd-6c78e419d7ed.png)
Этот мужчина разрушил всю мою карьеру

2022-05-11 06:16 UTC, HonkyDonky commented on code/game/objects/items/storage/specialized.dm
>  		add_fingerprint(usr)
А здесь?

2022-05-11 06:16 UTC, HonkyDonky commented on code/game/machinery/jukebox.dm
> +	var/locked = 0
Не слишком ли жестоко придумано с блокировкой? Её даже не емагнуть, ничего.

2022-05-11 06:17 UTC, No-Tips commented on code/game/machinery/jukebox.dm
> +	var/locked = 0
У нас емаг жукбокса взрывает его

2022-05-11 06:18 UTC, No-Tips commented on code/game/machinery/jukebox.dm
> +	var/locked = 0
Можно, конечно, выпилить взрыв, но это слишком смешная фича.

2022-05-11 06:22 UTC, No-Tips commented on code/game/machinery/jukebox.dm
> +	var/locked = 0
Я другим иссуем впилю взлом жукбокса, если нужен будет способ обойти эту защиту.

2022-05-11 12:46 UTC, No-Tips commented
Можно ревю плес

2022-05-13 03:02 UTC, HonkyDonky requested changes
Переделывай в `/obj/item/music_tape`, иначе это хрень какая-то, что она под `storage` лежит. Адекватных причин на то не вижу.

2022-05-13 03:02 UTC, HonkyDonky commented on code/game/objects/items/storage/specialized.dm
>  		add_fingerprint(usr)
Здесь `usr` меняй на `user`

2022-05-15 09:56 UTC, No-Tips commented
Отрефакторил в /obj/item, ревувайте. @HonkyDonky @Doster-d

2022-05-16 21:11 UTC, HonkyDonky submitted a review, later dismissed

2022-05-17 20:28 UTC, Doster-d submitted a review, later dismissed

2022-05-17 20:29 UTC, Doster-d commented
Ну конфликты решишь, еще поставлю.

2022-05-19 14:51 UTC, TobyThorne requested changes

2022-05-19 14:51 UTC, TobyThorne commented on code/game/objects/items/storage/specialized.dm
> +/obj/item/music_tapebox
или крестик сними, или трусы надень
music_tape_box / musictapebox
но не music_tapebox

2022-05-20 09:58 UTC, No-Tips commented
4somereason я думал, что tapebox переводится именно как "коробка для кассет". Оказалось, что как "магнитофон". Sadge

2022-05-24 18:17 UTC, O0oMaximo0O commented
Докинь фикс #8465 в ПР

2022-05-26 17:11 UTC, HonkyDonky approved these changes

2022-05-26 19:20 UTC, TobyThorne approved these changes

2022-05-26 19:21 UTC, merged