Music to cargo
ChaoticOnyx/OnyxBay pull request #8299
Opened 2022-05-10 16:19 UTC by No-Tips

По запросам многих игроков.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: В карго добавлен заказ с ящиком музыкальнык кассет.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-10 16:22 UTC, No-Tips commented
Мержить после #8295

2022-05-14 06:14 UTC, Artemonim requested changes

2022-05-14 06:14 UTC, Artemonim commented on code/datums/supplypacks/miscellaneous.dm
> +	contains = list(/obj/item/storage/music_tape/classic, /obj/item/storage/music_tape/jazz, /obj/item/storage/music_tape/exodus, /obj/item/storage/music_tape/newyear, /obj/item/storage/music_tape/front
Для читаемости поставь после `/obj/item/storage/music_tape/exodus` `, \`+Enter+Tab

2022-05-14 15:40 UTC, Artemonim commented on code/datums/supplypacks/miscellaneous.dm
> +	contains = list(/obj/item/storage/music_tape/classic, /obj/item/storage/music_tape/jazz, /obj/item/storage/music_tape/exodus, /obj/item/storage/music_tape/newyear, /obj/item/storage/music_tape/front
Для читаемости поставь после `/obj/item/storage/music_tape/exodus`: `, \`, перенос строки, Tab

2022-05-28 19:30 UTC, No-Tips commented
Оживаем, раз впилили фиксы.

2022-05-28 19:35 UTC, Doster-d commented on code/datums/supplypacks/miscellaneous.dm
> +	contains = list(/obj/item/storage/music_tape/classic, /obj/item/storage/music_tape/jazz, /obj/item/storage/music_tape/exodus, /obj/item/storage/music_tape/newyear, /obj/item/storage/music_tape/front
Нихуя не надо ставить \\, просто хуярь ентер и все

2022-05-28 19:44 UTC, No-Tips commented
Можно геймдизить и ревувать!

2022-05-28 20:00 UTC, Doster-d approved these changes, later dismissed

2022-06-01 16:17 UTC, TermService submitted a review, later dismissed

2022-06-01 16:34 UTC, TobyThorne commented on code/datums/supplypacks/miscellaneous.dm
> +	cost = 20
мало, го 40

2022-06-01 16:35 UTC, No-Tips commented on code/datums/supplypacks/miscellaneous.dm
> +	cost = 20
Го!

2022-06-01 16:37 UTC, Doster-d approved these changes

2022-06-01 16:44 UTC, TermService approved these changes

2022-06-10 18:49 UTC, merged