maptweak(exodus-2): Engine access hatch door bolt control
ChaoticOnyx/OnyxBay pull request #8326
Opened 2022-05-12 11:41 UTC by Artemonim

#3354

<summary>Чейнджлог</summary>

```yml
🆑
maptweak: Заменена панель управления болтами шлюзов ядра реактора Исхода
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-12 12:34 UTC, No-Tips commented
![image](https://user-images.githubusercontent.com/75416333/168075747-2531167e-2ceb-4e11-8d6f-b7f5fee4802f.png)
Это в сделку не входило.

Да и чем тебя не устраивает КНОПКА на контроле болтов шлюза?

2022-05-12 12:36 UTC, Artemonim commented
> Это в сделку не входило.

Поправлю. Сяб.

> Да и чем тебя не устраивает КНОПКА на контроле болтов шлюза?

Тем, что не работает?

2022-05-12 12:38 UTC, Artemonim commented
> ![image](https://user-images.githubusercontent.com/75416333/168075747-2531167e-2ceb-4e11-8d6f-b7f5fee4802f.png)
> Это в сделку не входило.

А у меня такого тут и нет 0_o

2022-05-12 12:58 UTC, No-Tips commented
Так поправь, чтобы работало. Там просто айдишник не сходится, скорее всего.

2022-05-12 13:20 UTC, Artemonim commented
> айдишник не сходится

Сходился

2022-05-12 13:40 UTC, No-Tips commented on maps/exodus/exodus-2.dmm
> +"aHB" = (/obj/machinery/atmospherics/pipe/simple/hidden/supply{dir = 6},/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers{dir = 6},/obj/machinery/atmospherics/pipe/simple/hidden{dir = 4},/obj/
Еще тут не почистил?

2022-05-12 14:15 UTC, Artemonim commented on maps/exodus/exodus-2.dmm
> +"aHB" = (/obj/machinery/atmospherics/pipe/simple/hidden/supply{dir = 6},/obj/machinery/atmospherics/pipe/simple/hidden/scrubbers{dir = 6},/obj/machinery/atmospherics/pipe/simple/hidden{dir = 4},/obj/
тут уже что надо

2022-06-01 16:20 UTC, TermService approved these changes

2022-06-01 17:45 UTC, TobyThorne requested changes

2022-06-01 17:45 UTC, TobyThorne commented on maps/exodus/exodus-2.dmm
> +"cFC" = (/obj/machinery/button/remote/blast_door{desc = "A remote control-switch for the engine control room blast doors."; dir = 1; id = "EngineBlast"; name = "Engine Monitoring Room Blast Doors"; p
а описание и название куда профукал

2022-06-02 04:26 UTC, Artemonim commented on maps/exodus/exodus-2.dmm
> +"cFC" = (/obj/machinery/button/remote/blast_door{desc = "A remote control-switch for the engine control room blast doors."; dir = 1; id = "EngineBlast"; name = "Engine Monitoring Room Blast Doors"; p
Так это ж от старого переключателя. Тем более само описание не подходило кнопке.

2022-06-02 04:57 UTC, TobyThorne approved these changes

2022-06-02 04:58 UTC, merged