fix(floragun): no suicide
ChaoticOnyx/OnyxBay pull request #8340
Opened 2022-05-13 07:00 UTC by SerJo2

Теперь нельзя commit suicide floral somatoray

close #7676

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Теперь нельзя застрелиться из floral somatoray.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-13 07:00 UTC, SerJo2 commented
Можно еще какой-нибудь текст вывести, как с лазертаг ганом

2022-05-13 08:00 UTC, No-Tips commented
"Sorry, you are not a flower"

2022-05-14 06:05 UTC, Artemonim requested changes

2022-05-14 06:05 UTC, Artemonim commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
`SPAN("warning", X)`

2022-05-14 15:41 UTC, Artemonim commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
SPAN("warning", X)

2022-05-15 03:57 UTC, SerJo2 commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
Что? Не поянл

2022-05-15 04:03 UTC, SerJo2 commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
Понял, но смысл от этого? там сверху с лазертаг ганом сделано как у меня

2022-05-15 04:18 UTC, EliseyGladkiy commented
Кажется, я так и не успею убить кого-то кроме себя из этой пушки. А ведь можно было бы грабать людей и убивать их выстрелом в рот...

2022-05-15 08:43 UTC, Artemonim commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
Новый стиль кода.

2022-05-15 09:06 UTC, Zert0X commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
![изображение](https://user-images.githubusercontent.com/42303535/168465371-169ea207-8e02-4638-98f1-3168ae9a431a.png)


> Понял, но смысл от этого? там сверху с лазертаг ганом сделано как у меня

2022-05-15 09:10 UTC, Zert0X commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
![изображение](https://user-images.githubusercontent.com/42303535/168465530-d82b30a3-f0e2-40e9-9202-de609b4ce60a.png)

2022-05-15 11:23 UTC, SerJo2 commented on code/modules/projectiles/gun.dm
> +			user.show_message("<span class = 'warning'>Sorry, you are not a flower.</span>")
Сейчас сменю

2022-05-23 22:00 UTC, TobyThorne commented on code/modules/projectiles/gun.dm
> +			user.show_message(SPAN("warning", "Sorry, you are not a flower.</span>"))
```suggestion
			user.show_message(SPAN("warning", "Sorry, you are not a flower."))
```

2022-05-26 17:06 UTC, HonkyDonky approved these changes

2022-06-01 16:25 UTC, TermService approved these changes

2022-06-01 16:25 UTC, merged