bugfix(drone_buckle)
ChaoticOnyx/OnyxBay pull request #8431
Opened 2022-05-22 02:13 UTC by FelixArzt

Так как мы можем посадить дрона на голову или взять в руки, значит мы можем пристегнуть его к стулу. Раньше писало, что дрон слишком тяжелый для того, чтобы его забаклить.

#8397

```yml
🆑
bugfix: Теперь maintenance drone может быть посажен на стульчик.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-23 21:58 UTC, TobyThorne submitted a review, later dismissed

2022-05-26 16:39 UTC, igorsaux requested changes

2022-05-26 16:39 UTC, igorsaux commented on code/game/objects/buckling.dm
> +	if(istype(M, /mob/living/silicon && ! /mob/living/silicon/robot/drone))
исправляй

2022-05-26 16:39 UTC, HonkyDonky requested changes

2022-05-26 16:39 UTC, HonkyDonky commented on code/game/objects/buckling.dm
> +	if(istype(M, /mob/living/silicon && ! /mob/living/silicon/robot/drone))
исправляй

2022-05-26 16:40 UTC, Doster-d requested changes

2022-05-26 16:40 UTC, Doster-d commented on code/game/objects/buckling.dm
> +	if(istype(M, /mob/living/silicon && ! /mob/living/silicon/robot/drone))
~~Я ЕБАНУЛСЯ КОГДА ЭТО ВИДЕЛ, ПОЧЕМУ ЭТА ХУЕТА СУЩЕСТВУЕТ, А?!~~исправляй

2022-05-26 16:43 UTC, Doster-d commented on code/game/objects/buckling.dm
> +	if(istype(M, /mob/living/silicon && ! /mob/living/silicon/robot/drone))
```suggestion
	if(istype(M, /mob/living/silicon) && !istype(/mob/living/silicon/robot/drone))
```

2022-05-26 16:45 UTC, HonkyDonky commented on code/game/objects/buckling.dm
> +	if(istype(M, /mob/living/silicon && ! /mob/living/silicon/robot/drone))
макросами покорче выйдет: `if(issilicon(M) && !is_drone(M))`

2022-05-26 17:53 UTC, Doster-d commented on code/game/objects/buckling.dm
> +	if(istype(M, /mob/living/silicon && ! /mob/living/silicon/robot/drone))
```suggestion
	if(issilicon(M) && !is_drone(M))
```

2022-06-04 05:36 UTC, HonkyDonky approved these changes
Исправил, молодец.

2022-06-22 17:24 UTC, kreeperHLC approved these changes
Серьёзно, не принимать ЭТО месяц?

2022-06-22 17:51 UTC, igorsaux approved these changes
ок

2022-06-23 07:18 UTC, Doster-d approved these changes

2022-06-24 10:19 UTC, merged