feat(grenades): nerf and safety pin update
ChaoticOnyx/OnyxBay pull request #8459
Opened 2022-05-24 11:56 UTC by No-Tips

close #8458 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: НЕхимические гранаты имеют чеку, которую нужно выдернуть, чтобы активировать гранату.
rscdel: Флеш и дымовые гранатам нельзя подкрутить таймер, теперь он всегда 3 секунды.
soundadd: Добавлены звуки для чеки.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-24 12:47 UTC, No-Tips commented
Главный вопрос - нужна ли нам тонна спрайтов всех гранат без чеки, или похуй, потому что на эти два пикселя и так никто не смотрит?

2022-05-24 13:11 UTC, Tsurupeta commented
Тонна (4 спрайта)

2022-05-25 13:54 UTC, TimErmolt commented
А если выдернуть чеку из гранаты во рту человека (прицелиться в рот и хармом, если что), то она активируется? Судя по коду, нет (мб я тупой и на самом деле да). Удерживание рычага ртом это смешно, но препятствует эффектному подрыву подлеца.

2022-05-25 14:15 UTC, No-Tips commented
> А если выдернуть чеку из гранаты во рту человека (прицелиться в рот и хармом, если что), то она активируется? 

Если выдернуть чеку перед тем, как пихнуть в рот - да.

2022-05-25 20:51 UTC, No-Tips commented
Вроде все реализовал, что просил тоби в иссуе #8458 , кроме пихания чеки в слот маски, что будет ПИЗДЕЦКИ сильно раздражать игроков, а поэтому не нужно. Жду геймдизорешение и ревью.

2022-06-02 05:36 UTC, TobyThorne commented on code/game/objects/items/grenades/chem_grenade.dm
> +				to_chat(user, SPAN("notice", "The assembly is not going off without safety pin."))
Непон, гранату нельзя разобрать, если чека не вставлена? Чёт кринж. Она должна разбираться, но корпус должен дропаться хреновый, который снова не собрать, пока чека не вернётся.

2022-06-02 08:37 UTC, No-Tips commented on code/game/objects/items/grenades/chem_grenade.dm
> +				to_chat(user, SPAN("notice", "The assembly is not going off without safety pin."))
Ну ладно, поправлю. Но разбирать гранату, которая уже затригерена, но не выброшена - кринж.

2022-06-02 08:41 UTC, No-Tips commented on code/game/objects/items/grenades/chem_grenade.dm
> +				to_chat(user, SPAN("notice", "The assembly is not going off without safety pin."))
Не, ну вообще - чека это часть сборки. Разбирать гранату, крепкой мужской рукой держа рычаг и молясь богу - неоч. Могу разве что выдать шанс на триггер гранаты, если космонавт попробует её так разобрать?

2022-06-03 08:51 UTC, No-Tips commented on code/game/objects/items/grenades/chem_grenade.dm
> +				to_chat(user, SPAN("notice", "The assembly is not going off without safety pin."))
Сделано!

2022-06-07 09:23 UTC, No-Tips commented
![assemblies](https://user-images.githubusercontent.com/75416333/172345415-964921f5-80c1-4eab-91c4-bb3726f2ef80.gif)
Вот теперь вроде точно все работает.

2022-06-07 09:44 UTC, No-Tips commented
Может, в честь нового функционала пихнем сбшникам ассистентский раздатчик ассамблей?

2022-06-07 17:45 UTC, No-Tips commented
Короче, все работает. Можно ревувать и пихать в прод.

2022-06-07 17:59 UTC, TermService requested changes

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/chem_grenade.dm
>  			usr.put_in_hands(detonator)
```suggestion
			user.put_in_hands(detonator)
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/chem_grenade.dm
> +			playsound(src.loc, 'sound/weapons/pin_pull.ogg', 40, 1)
```suggestion
			playsound(loc, 'sound/weapons/pin_pull.ogg', 40, 1)
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/chem_grenade.dm
> +	if(istype(W, /obj/item/safety_pin) && user.is_item_in_hands(W) && stage == 2 && !active)
stage == 2 надо заменить на макрос

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/chem_grenade.dm
> +			playsound(src.loc, 'sound/weapons/pin_insert.ogg', 40, 1)
```suggestion
			playsound(loc, 'sound/weapons/pin_insert.ogg', 40, 1)
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/chem_grenade.dm
>  	if(istype(W,/obj/item/device/assembly_holder) && (!stage || stage==1) && path != 2)
очень страшно стейдж 1 патч 2, дефайны, нам нужны дефайны

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/grenade.dm
> +	var/have_pin = TRUE // Currently else only for grenade/spawnergrenade
```suggestion
	var/has_pin = TRUE // Currently else only for grenade/spawnergrenade
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/grenade.dm
> +		playsound(src.loc, 'sound/weapons/pin_pull.ogg', 40, 1)
```suggestion
		playsound(loc, 'sound/weapons/pin_pull.ogg', 40, 1)
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/grenade.dm
> +			active = 1
```suggestion
			active = TRUE
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/grenade.dm
> +			active = 1
```suggestion
			active = TRUE
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/grenade.dm
> +		playsound(src.loc, 'sound/items/Screwdriver2.ogg', 25, -3)
```suggestion
		playsound(loc, 'sound/items/Screwdriver2.ogg', 25, -3)
```

2022-06-07 17:59 UTC, TermService commented on code/game/objects/items/grenades/grenade.dm
> +	w_class = ITEM_SIZE_TINY
я сомневаюсь что граната у нас тини

2022-06-07 18:04 UTC, No-Tips commented on code/game/objects/items/grenades/grenade.dm
> +	w_class = ITEM_SIZE_TINY
Не граната а чека.

2022-06-07 18:05 UTC, No-Tips commented on code/game/objects/items/grenades/grenade.dm
> +	w_class = ITEM_SIZE_TINY
Она тини, да, потому что литературно как монетка с размер.

2022-06-07 19:05 UTC, TermService approved these changes

2022-06-13 10:05 UTC, No-Tips commented
Я умру, не дождавшись аппрува @TobyThorne

2022-06-13 19:01 UTC, Doster-d approved these changes

2022-06-14 09:51 UTC, merged