Обновление ЕРТ
ChaoticOnyx/OnyxBay pull request #8466
Opened 2022-05-24 23:27 UTC by Doster-d

Теперь есть возможность отправить сообщения ЕРТшникам почему было вызвано ЕРТ на станцию.
Педали могут отклонить запрос на отправку ЕРТ на станцию.
Добавлено задание для ЕРТ - эвакуировать тела глав на базу ЕРТ, к сожалению, некоторых надо вытащить живыми.

close #74

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Теперь есть возможность отправить сообщения ЕРТшникам почему было вызвано ЕРТ на станцию.
admin: Педали могут отклонить запрос на отправку ЕРТ на станцию.
rscadd: Добавлено задание для ЕРТ - эвакуировать тела глав на базу ЕРТ, к сожалению, некоторых надо вытащить живыми.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-05-25 09:17 UTC, igorsaux requested changes

2022-05-25 09:17 UTC, igorsaux commented on code/game/antagonist/outsider/ert.dm
> +		[message_from_station ? "Received message from the station:\n[message_from_station]" : "No additional information was received from the facility."]"
в иссуе сказано упомянуть про сохранение глав

2022-05-25 09:17 UTC, igorsaux commented on code/game/gamemodes/objective.dm
> +	for(var/weakref/ref in extract_heads)
бодиес?

2022-05-25 09:17 UTC, igorsaux commented on code/game/antagonist/outsider/ert.dm
> +		[message_from_station ? "Received message from the station:\n[message_from_station]" : "No additional information was received from the facility."]"
и не допустить гибели персонала

2022-05-25 11:17 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +	for(var/weakref/ref in extract_heads)
Хмм, странная опечатка, надо проверить еще раз

2022-05-25 11:18 UTC, Doster-d commented on code/game/antagonist/outsider/ert.dm
> +		[message_from_station ? "Received message from the station:\n[message_from_station]" : "No additional information was received from the facility."]"
Это все находиться в заданиях, а в этом тексте указано, что надо выполнить задания.

2022-05-25 19:22 UTC, Doster-d commented on code/game/gamemodes/objective.dm
> +	for(var/weakref/ref in extract_heads)
Да, проверил, проверил еще, что оказывается моя фигня не работала, но теперь все хорошо.

2022-06-02 16:21 UTC, igorsaux approved these changes

2022-06-05 22:24 UTC, TobyThorne approved these changes
критического кринжа не нашёл, должно работать

2022-06-05 22:26 UTC, merged