Removes absence of job-specific uplink items
ChaoticOnyx/OnyxBay pull request #8532
Opened 2022-06-01 20:44 UTC by TobyThorne

- Возвращена система джоб-специфик предметов в аплинке.

ТУДУ:
- Запилить кучу итемов, пока только нож-кукож готов.

```yml
🆑
rscadd: В аплинк добавлена категория "Job Specific". Содержит предметы, уникальные для профессии владельца аплинка. Пока содержит только один предмет для повара, больше контента будет доступно позже.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-06-02 10:16 UTC, No-Tips commented
Медикал доктор:
- Ручко-шприц, по типу слипипена, но который можно перезалить
- Рандомный имплант, как у абдукторов
Парамедик:
- Перекинуть им взломанный дефиб
Химик:
- Криобикер
- Набор токсинов
Вирусолог:
- Шприц с рандомным серьезным вирусом

Может ещё что-то придумаю...

2022-06-02 11:07 UTC, MrMagick2104 commented
На ТГ/бистейшене можно подсмотреть предметы, очевидно.

Инженеру круто было бы иметь маячок для наводки синги или особый емаг (как у генокрада, например).

2022-06-02 17:01 UTC, DarkHunter7756 commented
Роботехник и РД: 
- Тритор ММИ - автоматически емагает борга при установке в корпус. Меньше рисков, что машина просто сбежит. 

Химик, СМО:
- Шприц-револьвер и 5 дротиков коробкой. 
- Коробка с деталями для гранат. Содержит 4 корпуса, 4 таймера, 4 игнайтера

Ботаник и ксеноботаник:
- Граната со спрайтом яблока. Клик на предмет активирует таймер, детонация с умеренным взрывом через 15 секунд
- Семена Man-eater plant. Подписаны, как strange plant, имеют хорошие статы. 

Инженер и СЕ:
- Шокер с текстуркой T-ray сканера. Бьет током умеренной силы, сердце не останавливает, но легко кладет незащищенного соперника
- Быстро-устанавливаемая турель. Выглядит, как чемодан. При активации кликом и небольшим прогрессбаром устанавливает турель, вооруженную какой-то слабой летальной пушкой. Не отличает своих от чужих, начинает обстрел всех вокруг через 10 секунд после установки

Клоун: 
- Amplified Vuvuzela - при использовании оглушает всех в видимом радиусе на 2 минуты. Звук можно услышать за целый экран от источника
- Смертельная маска клоуна - маска с особым порошком внутри - заставляет жертв, надевшую ее истерически хохотать и получать брейндамаг
- Взрывные ботинки. Каждый 20 шаг проигрывает звук взрыва. 

Мим: 
- Кляп в рот. Для самых болтливых

Повар:
- Тесак мясника. Особая модель тесака с виброклинком, наносит чудовищный урон, выглядит, как обычный. Что в принципе не уменьшает подозрений. 

ХоП: 
- Зажигалка с подвохом. Огонь из этой зажигалки настолько горячий, что поджигает недругов даже без предварительного обливания топливом. 
- Документ на вступление в Синдикат. При подписывании любым отличным от ХоПа космонавтом - дает ему роль предателя, коды в аплинк и сам аплинк с 1 ТК (для покупки чемодана выполнения контрактов)

2022-06-02 17:05 UTC, NefrNerf commented
Ай блять, ебучие кнопки на телефоне, пр андрафтнул

2022-06-02 17:09 UTC, DarkHunter7756 commented
Ассистент:
- Тулбокс с заостренными краями. Наносит больше повреждений. 
- Банка с термитом. Лучший друг любого взломщика

Уборщик: 
Табличка с подвохом. Генерирует смазку на полу раз в 2 минуты. 

Вирусолог:
- Шприц с зомби-вирусом(когда будет готов). Стоить эта штука будет дофига (больше стартового кол-ва ТК), но профита тоже много. 

Биолог: 
- Кубы с всякими мобами. От кровососущих медуз до акул и стайки голодных метроидов

2022-07-05 05:51 UTC, Doster-d approved these changes

2022-07-05 05:51 UTC, Doster-d commented on code/datums/uplink/uplink_items.dm
> +	if(job_specific.len && !(U.uplink_owner.assigned_role in job_specific))
```suggestion
	if(length(job_specific) && !(U.uplink_owner.assigned_role in job_specific))
```

2022-07-05 05:51 UTC, Doster-d commented on code/datums/uplink/uplink_items.dm
> +	if(!antag_roles.len)
```suggestion
	if(!length(antag_roles))
```

2022-07-05 05:51 UTC, Doster-d requested changes
[]()

2022-07-05 05:53 UTC, TobyThorne commented on code/datums/uplink/uplink_items.dm
> +	if(!antag_roles.len)
а зачем, если мы проверяем только наличие размера, но не используем его

2022-07-05 06:11 UTC, Doster-d commented on code/datums/uplink/uplink_items.dm
> +	if(!antag_roles.len)
Таков закон

2022-07-05 06:12 UTC, Doster-d commented on code/datums/uplink/uplink_items.dm
> +	if(!antag_roles.len)
И там кто-то говорил, что это на 1 pu быстрее

2022-07-05 09:38 UTC, igorsaux approved these changes

2022-07-05 18:24 UTC, Doster-d approved these changes

2022-07-05 18:28 UTC, merged