fix(helmet): bodypart covering changes when visor toggling
ChaoticOnyx/OnyxBay pull request #8677
Opened 2022-06-14 21:35 UTC by Artemonim

close #3316

<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Поднятое забрало шлема больше не мешает взаимодействовать с лицом
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-06-14 21:49 UTC, Doster-d requested changes
Ето не так работает

2022-06-14 21:49 UTC, Doster-d commented on code/modules/clothing/head/helmet.dm
> +		body_parts_covered -= FACE;
```suggestion
		body_parts_covered = body_parts_covered^FACE;
```

2022-06-14 21:49 UTC, Doster-d commented on code/modules/clothing/head/helmet.dm
> +		body_parts_covered += FACE;
```suggestion
		body_parts_covered = body_parts_covered|FACE;
```

2022-06-14 21:51 UTC, Doster-d commented
Обновил сагги

2022-06-14 22:03 UTC, O0oMaximo0O commented on code/modules/clothing/head/helmet.dm
> +		body_parts_covered -= FACE;
Лучше так
```suggestion
		body_parts_covered &= ~FACE;
```

2022-06-27 18:57 UTC, TobyThorne approved these changes, later dismissed

2022-07-05 10:40 UTC, Tsurupeta reviewed
У тебя добавляется флаг покрытия лица шлемам. Любым. Обычный шлем СБ берёшь, активируешь в руках и у тебя уже закрыто лицо, вместо даже, например, обычного закрытия глаз.
 Я бы добавил на твоём месте конкретно шлему СБ добавление флага покрытия глаз, так как у него действительно есть визор и он именно на глаза. А также в конкретно риот шлеме дополнительно убирал/добавлял флаг покрытия лица.

2022-07-05 10:41 UTC, Tsurupeta commented
Даже специально на локалке проверил, чтобы ты понял, насколько это не очень.
![image](https://user-images.githubusercontent.com/41485301/177310389-4bdedc95-c03d-4434-942e-26ccd2364f5f.png)

![image](https://user-images.githubusercontent.com/41485301/177310431-89a50ea6-5b64-40b6-94aa-4cf519e86a8d.png)

2022-07-05 11:07 UTC, Tsurupeta commented
Вообще, я думаю, можно было бы даже просто убирать флаг если он есть и возвращать флаги к исходным вместо добавления.

2022-09-28 17:41 UTC, MaxZ043 reviewed
Very important changes requested. Я бы вообще в методе тоггле визор делал все в следующей последовательности: 

- Прировнял `icon_state = initial(icon_state)`
- Проверил, тогда бы `icon_state = "[icon_state]_up"` было бы уместно.
- Все как у тебя, за исключением установления иконки в `else`.

2022-09-28 17:41 UTC, MaxZ043 commented on code/modules/clothing/head/helmet.dm
>  		src.icon_state = "[icon_state]_up"
Э-э-э, а можно и без `src`, мне кажется, да и лучше лишний раз перестраховаться.
```suggestion
		icon_state = "[initial(icon_state)]_up"
```

2022-09-28 17:41 UTC, MaxZ043 commented on code/modules/clothing/head/helmet.dm
>  		to_chat(user, "You raise the visor on the [src].")
```suggestion
		to_chat(user, "You raise the visor on \the [src].")
```

2022-09-28 17:41 UTC, MaxZ043 commented on code/modules/clothing/head/helmet.dm
>  		to_chat(user, "You lower the visor on the [src].")
```suggestion
		to_chat(user, "You lower the visor on \the [src].")
```

2022-09-28 17:41 UTC, MaxZ043 commented on code/modules/clothing/head/helmet.dm
>  	if(icon_state == initial(icon_state))
Немного кринж, лучше по флагу проверять, чем по эм... В идеале, поменяй местами два куска кода, чтоб от `!` уйти.
```suggestion
	if(!(body_parts_covered & FACE))
```

2022-10-01 20:29 UTC, Artemonim commented
> шлему СБ добавление флага покрытия глаз, так как у него действительно есть визор и он именно на глаза.

Если забрало шлема не покрывает лицо целиком - это херня, а не забрало.
Лучше перерисовать спрайт.

2022-10-01 20:52 UTC, TobyThorne requested changes
вна2ре говно, опустил очки на стандартном шлеме - закрылась вся рожа

2022-10-01 22:53 UTC, Artemonim commented
> опустил очки на стандартном шлеме

Либо я чего не понял, либо у нас шлемы с полузабралом не защищали глаза

2022-10-02 16:48 UTC, TobyThorne commented on code/modules/clothing/head/helmet.dm
> +	var/icon/H = new('icons/obj/clothing/hats.dmi')
это что за хрень

2022-10-02 18:17 UTC, Artemonim commented on code/modules/clothing/head/helmet.dm
> +	var/icon/H = new('icons/obj/clothing/hats.dmi')
Сделано по примеру:
```
/obj/item/clothing/suit/proc/get_collar()
	var/icon/C = new('icons/mob/collar.dmi')
	if(icon_state in C.IconStates())```

2022-10-09 23:21 UTC, kreeperHLC approved these changes

2022-10-10 03:52 UTC, TobyThorne requested changes

2022-10-10 03:52 UTC, TobyThorne commented on code/modules/clothing/head/helmet.dm
> +	var/icon/H = new('icons/obj/clothing/hats.dmi')
Не понял, как это вообще связано с указанным примером. Это пиздец.

2023-02-14 21:40 UTC, TobyThorne commented
Поломано с девятого октября. В архивач.

2023-02-14 21:40 UTC, closed without merging