fix(multiz.dm): catwalk up-down move warning fix
ChaoticOnyx/OnyxBay pull request #8707
Opened 2022-06-16 20:23 UTC by Artemonim

close #1685

<summary>Чейнджлог</summary>

```yml
🆑
bugifx: Теперь игра подскажет, если catwalk помешает перемещаться между этажами.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-06-16 20:41 UTC, Doster-d requested changes

2022-06-16 20:41 UTC, Doster-d commented on code/datums/movement/multiz.dm
> +			to_chat(mob, "<span class='warning'>\The [start] is in the way.</span>")
```suggestion
		var/blocked_message
		var/obj/structure/catwalk/C = locate() in start
		if(istype(C))
			blocked_message = C.name
		else
			blocked_message = start
		to_chat(mob, SPAN("warning", "\The [blocked_message] is in the way."))
```

2022-06-16 20:41 UTC, Doster-d commented on code/datums/movement/multiz.dm
> +			to_chat(mob, "<span class='warning'>You bump against \the [destination].</span>")
```suggestion
		var/blocked_message
		var/obj/structure/catwalk/C = locate() in start
		if(istype(C))
			blocked_message = C.name
		else
			blocked_message = start
		to_chat(mob, SPAN("warning", "You bump against \the [destination]."))
```

2022-06-17 09:27 UTC, Doster-d commented on code/datums/movement/multiz.dm
> +	return location
```suggestion
	return location.name
```

2022-10-04 10:50 UTC, Doster-d approved these changes

2022-10-09 23:15 UTC, kreeperHLC approved these changes

2022-10-09 23:17 UTC, merged