refact(items.dm): mob_can_equip()
ChaoticOnyx/OnyxBay pull request #8712
Opened 2022-06-17 22:14 UTC by Artemonim

close #414
Код работает и вызывается.
Косметический рефакторинг, выделенный в иссуе код оптимизировал.
Добавил `spawn(0)`, чтобы объяснение шло после уведомления.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-06-22 21:13 UTC, kreeperHLC commented on code/game/objects/items.dm
> +	if(!ishuman(M)) return FALSE
А ну на новые строки вынес

2022-06-22 22:36 UTC, kreeperHLC requested changes

2022-06-22 22:36 UTC, kreeperHLC commented on code/game/objects/items.dm
> +						if (!disable_warning)
Пробел

2022-06-22 22:36 UTC, kreeperHLC commented on code/game/objects/items.dm
> +				else if(slot_wear_suit in mob_equip)
Проверка на !H.wear_suit потерялась

2022-10-09 23:10 UTC, kreeperHLC approved these changes

2022-10-10 03:50 UTC, TobyThorne requested changes

2022-10-10 03:50 UTC, TobyThorne commented on code/game/objects/items.dm
> +					to_chat(usr, SPAN_WARNING("You somehow have a suit with no defined allowed items for suit storage, stop that."))
а можно оставить нормальные спаны вместо этого ретардизма пожалуйста спасибо

2023-02-14 21:38 UTC, TobyThorne commented
С октября в ЧРе и стали. В мире мёртвых до сих пор нету связи.

2023-02-14 21:38 UTC, closed without merging