Removes absence of old floors
ChaoticOnyx/OnyxBay pull request #8770
Opened 2022-06-23 22:55 UTC by TobyThorne

А говорят, что Тоби к игрокам не прислушивается:
![image](https://user-images.githubusercontent.com/45202681/175428241-87df9306-4234-4ef7-b455-78c22af94483.png)

- Возвращены старые спрайты полов.
- Новые полы вынесены в отдельные типы и добавлены на карту в некоторых местах.

```yml
🆑
tweak: Возвращены старые спрайты полов. Новые спрайты полов стали отдельными типами.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-06-23 23:00 UTC, kreeperHLC requested changes, later dismissed
Нет Сансета и Полярки

2022-06-23 23:00 UTC, FloweYStyle commented
Со старым полом тогда и старые стены нужны, чтобы по классическому стилю подходило.

2022-06-23 23:03 UTC, kreeperHLC commented
А ещё и мапмержа нет, с +2,880 −2,814 только отказ

2022-06-23 23:06 UTC, TobyThorne commented
> Нет Сансета и Полярки

Всё есть, чё врешб

2022-06-23 23:13 UTC, TimErmolt commented
Господи, ну плитка полов-то чем не угодила? Один из самых уникальных спрайтов в билде, который буквально везде по станции есть, потому что это пол, а на многих других билдах используется эта самая плитка, выглядящая, как листы металла. И его выпиливают, заменяя на этот металл.
Я не понимаю, зачем надо респрайтить. Нормально жили со старой (имхо более красиво выглядящей, но это вкусовщина) и никто не жаловался, и тут в один день голосование (слава бьёнду, что хоть голосования теперь проводятся) -- три лишних голоса -- ПР -- пидор. Я не понимаю, зачем надо респрайтить, особенно когда 43% опрошенных против.
Да, я вижу, что прежние спрайты вроде бы где-то остаются или добавляются. Это мало значимо, ибо подавляющее большинство полов по станции всё равно будет выложено листовым металлом.

> Со старым полом тогда и старые стены нужны, чтобы по классическому стилю подходило.

Ну и вообще-то да. От дисгармонии стилей билд не умрёт, но всё-таки стоит учесть (не отменяет конечно того, что я всё ещё против таких глобальных респрайтов в целом).

2022-06-23 23:23 UTC, TobyThorne commented
> Со старым полом тогда и старые стены нужны, чтобы по классическому стилю подходило.

Стены менять особого смысла нет, старые полы с ними смотрятся ещё лучше. 
У новых стен тот же оттенок, что и у старых, но больше деталей. А вот у нового пола детализация как раз хромает, в то время как старый - довольно графонистый, да ещё и не такой контрастный.

2022-06-23 23:46 UTC, MalinaGirl commented
Не знаю почему, но будто бы освещение выглядит лучше с светлыми плитками. К тому же поменять всегда успеем, сколько раз уже меняли.

2022-06-23 23:52 UTC, FloweYStyle commented
Кстати вы забыли поменять спрайт plating в техах на старый, если конечно его тоже планируется поменять.

2022-06-24 08:28 UTC, No-Tips commented
А вот в церкви явно новый темнопол смотрится куда лучше старого.

2022-06-24 08:30 UTC, No-Tips commented
Ну и кстати по поводу голосования

![image](https://user-images.githubusercontent.com/75416333/175496327-94684506-79a7-4b11-94b8-f417619a85fa.png)

Тоби, через день игроки стали резко против. Может, прислушаемся?

2022-06-24 08:38 UTC, Tsurupeta commented
Я категорически против убирания старых полов. Старые полы хорошие, даже если они темноватые, можно их немного светлее сделать. "Графонистость" новых полов выражена тем, что вместо какого-то паттерна на плитке там просто их обмазали десятком цветов, которые от оригинального почти не отличаются. 

Выпиливать портированные полы потому что они слишком тёмные или же потому что "ностальгия" - плохо.

2022-06-24 08:49 UTC, TobyThorne commented
> Ну и кстати по поводу голосования
> 
> ![image](https://user-images.githubusercontent.com/75416333/175496327-94684506-79a7-4b11-94b8-f417619a85fa.png)
> 
> Тоби, через день игроки стали резко против. Может, прислушаемся?

Не увидим реальную реакцию, пока не попробуем. Больше пола - лучше, чем меньше. Если массово не зайдёт - снова застелим Исход и Фронтир rough-плиткой, а гладкая останется на дереликте и генезисе.

2022-06-24 08:55 UTC, igorsaux approved these changes

2022-06-24 08:56 UTC, Zert0X approved these changes
UwU

2022-06-24 09:05 UTC, merged