feat(doomsky): now actually explodes
ChaoticOnyx/OnyxBay pull request #8871
Opened 2022-07-03 10:27 UTC by No-Tips

Литературно неиграбельно
![image](https://user-images.githubusercontent.com/75416333/177035534-1dfa4ab3-8f5c-4402-abdf-fb1044bc0c51.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Думский вновь взрывается после смерти.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-03 10:29 UTC, TobyThorne reviewed
а удалять/дропать чеку кто будет, пушкин?

2022-07-03 10:29 UTC, No-Tips commented
чека нулл, нечего дропать.

2022-07-03 10:30 UTC, TobyThorne commented
> чека нулл, нечего дропать.

переменную зануляешь, а чека существует 
![image](https://user-images.githubusercontent.com/45202681/177035639-683ebd07-359a-41f7-8212-fc9f8d460f04.png)

2022-07-03 12:38 UTC, No-Tips commented
кудельнул

2022-07-03 12:46 UTC, Tsurupeta commented
У нас есть QDEL_NULL макрос

2022-07-03 12:50 UTC, TermService requested changes

2022-07-03 12:50 UTC, TermService commented on code/modules/mob/living/bot/secbot.dm
> +		qdel(new_nade.safety_pin)
```suggestion
		QDEL_NULL(new_nade.safety_pin)
```

2022-07-03 12:50 UTC, TermService commented on code/modules/mob/living/bot/secbot.dm
> +		new_nade.safety_pin = null
```suggestion
```

2022-07-03 12:51 UTC, TermService commented
и вот это поправь плес
![изображение](https://user-images.githubusercontent.com/18397924/177040514-e4c4b62c-6e82-4b2e-a3e0-eed273aadeaa.png)

2022-07-03 19:15 UTC, No-Tips commented
> и вот это поправь плес ![изображение](https://user-images.githubusercontent.com/18397924/177040514-e4c4b62c-6e82-4b2e-a3e0-eed273aadeaa.png)

Тут все правильно.

2022-07-04 06:21 UTC, Tsurupeta commented
А теперь сделай то же самое для всех тех гранат, где ты просто зануляешь переменную вместо удаления чеки.

2022-07-04 07:59 UTC, No-Tips commented
В другом пре сделаю, я бы ещё кое-что вынес для гранат.

2022-07-04 08:43 UTC, No-Tips commented
Бля, хотя лучше все это пихнуть в один пр, ща

2022-07-04 08:43 UTC, closed without merging