Grenade launchers
ChaoticOnyx/OnyxBay pull request #8894
Opened 2022-07-04 21:33 UTC by No-Tips

ЭТО ШАБЛОН PULL REQUEST. Внимательно прочитайте его и напишите описание Pull Request в соответствии с ним. Каждое отклонение от шаблона увеличивает время приема Pull Request-а вплоть до бесконечности!
Подробнее про то, как создавать Pull Request-ы смотрите в нашем [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

ТЕКСТ ВЫШЕ НУЖНО УДАЛИТЬ.

ЗДЕСЬ должно быть **подробное описание** того, что происходит в Pull Request и зачем это нужно. Pull Request не должен содержать изменений, о которых здесь ничего не сказано. ЭТОТ ПУНКТ НАДО ЗАМЕНИТЬ ОПИСАНИЕМ, А ЕГО УДАЛИТЬ.

Я тут немного совместил пару мелких пров в один.

Немного почистил код, убрал пару ненужных ифов у гранат. 
Добавил булевый флаг need_pin для создания гранат без чеки (к примеру, в гранатометах).
Добавил удобный прок new_timing, чтобы изменять по необходимости таймеры у гранаты, не копипастя семь строк странного на вид кода. 
Пофиксил баг у думски, граната которого не взрывалась после смерти. 
Стандартный тайминг гранат изменен с 5 до 3 секунд. Пятисекундки слишком больно, соглашусь.

Добавил возможность в гранатометах рига менять таймер гранаты (2, 3 или 5 секунд).

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Граната после смерти Думски теперь взрывается. 
balance: Стартовый таймер у гранат снижен до трех секунд (было 5).
rscadd: В гранатомете Рига теперь можно выбрать таймер для гранат. На выбор 2, 3 или 5 секунд.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-05 05:43 UTC, TobyThorne requested changes

2022-07-05 05:43 UTC, TobyThorne commented on code/game/objects/items/grenades/grenade.dm
> +/obj/item/grenade/New(need_pin = TRUE)
б + лять7

2022-07-05 05:43 UTC, TobyThorne commented
> Я тут немного совместил пару мелких пров в один.

![image](https://user-images.githubusercontent.com/45202681/177257547-8a27dda5-5b43-4741-9e4a-8d3f3f81c425.png)

2022-07-05 07:46 UTC, No-Tips commented on code/game/objects/items/grenades/grenade.dm
> +/obj/item/grenade/New(need_pin = TRUE)
Мне нужна при создании обжектов булеваы переменная

2022-07-05 07:46 UTC, No-Tips commented on code/game/objects/items/grenades/grenade.dm
> +/obj/item/grenade/New(need_pin = TRUE)
Мне нужна в нью булевая переменная :о

2022-07-11 19:11 UTC, No-Tips commented
Ай блин экзамены в глаза попали. Поправил.

2022-08-06 18:33 UTC, No-Tips commented
ТОБИ ОТПУСТИ ПРОШУ ХВАТИТ ДЕРЖАТЬ МЕНЯ В ЗАЛОЖНИКАХ

2022-08-08 17:16 UTC, TobyThorne approved these changes, later dismissed
нихрена не ревувал, но ультрасовременный мелкомягкий гитхаб не даёт скинуть чр

замержившего без ещё двух зелёных галочек скормлю плину

2022-08-15 19:12 UTC, O0oMaximo0O commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +		timing_index = timing_index == module.timings.len ? 1 : timing_index+1
Ради моего спокойствия. А так ничего ужасного не нашёл.
```suggestion
		timing_index = (timing_index == module.timings.len) ? 1 : (timing_index + 1)
```

2022-08-15 20:14 UTC, No-Tips commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +		timing_index = timing_index == module.timings.len ? 1 : timing_index+1
Копипаста с модуля выбора химикатов, работает.

2022-08-15 20:14 UTC, No-Tips commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +		timing_index = timing_index == module.timings.len ? 1 : timing_index+1
А хотя похуй, залью, чтобы галочка тоби сбилась.

2022-08-19 13:50 UTC, Doster-d submitted a review, later dismissed
Гитхаб не дает сбросить чр, кто замержит без +1 необходимого аппрува - станет фурри

2022-08-19 13:51 UTC, No-Tips commented
У тебя не было чр кого ты обмануть пытаешься 😼

2022-08-23 13:02 UTC, Tsurupeta reviewed
прикольно

2022-08-23 13:06 UTC, igorsaux approved these changes
погнали ♿

2022-08-23 13:07 UTC, igorsaux requested changes

2022-08-23 13:07 UTC, igorsaux commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +	if(timings?.len)
```suggestion
	if(length(timings))
```

2022-08-23 13:08 UTC, Tsurupeta commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +	if(timings?.len)
♿

2022-08-23 13:09 UTC, No-Tips commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +	if(timings?.len)
Спизжено с инжектора химикатов же, там ничего так, выглядит сексуально.

2022-10-07 09:48 UTC, igorsaux submitted a review, later dismissed

2022-10-07 13:15 UTC, Doster-d approved these changes, later dismissed

2022-10-08 10:52 UTC, TobyThorne requested changes

2022-10-08 10:52 UTC, TobyThorne commented on code/game/objects/items/grenades/grenade.dm
> +	..()
вы чё угараете ебать

2022-10-08 10:55 UTC, No-Tips commented on code/game/objects/items/grenades/grenade.dm
> +	..()
о бля, это копайлот насрал

2022-10-09 23:24 UTC, kreeperHLC submitted a review, later dismissed
Иди теперь Тоби тыкай чтобы ЧР снял

2022-10-18 17:50 UTC, Tsurupeta commented
I can't believe it's still open

2022-10-30 07:31 UTC, TobyThorne approved these changes
Код не проверял, сбрасываю ЧР.

2022-10-30 14:54 UTC, igorsaux approved these changes

2022-10-31 17:46 UTC, merged