fix(assembly): big fix of assemblies
ChaoticOnyx/OnyxBay pull request #8910
Opened 2022-07-06 21:54 UTC by O0oMaximo0O

Отдельные детали и сборка подхватывают SIGNAL_MOVED у того что их держит и передают от себя.
Добавлена функция получения объекта-холдера(лока) верхнего уровня.
Добавлены новые proximity_trigger и turf_selection, берут и отслеживают линию прозрачных турфов.
Научному манипулятору добавлена возможность держать сборку (assembly_holder).
Порефакторил по пути.

fix #8352
fix #5985
fix #8402
fix #3247
fix #8054
fix #7796

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Научные киборги теперь могут работать с таймерами, инфракрасным сенсором и прочим.
bugfix: Инфракрасный сенсор теперь НЕ застывает на месте в руках, манипуляторах и топливном баке.
bugfix: Инфракрасный сенсор больше не проникает в стены.
bugfix: Инфракрасный сенсор больше не создаёт кривые лазерные лучи.
bugfix: Таймеры теперь можно настраивать в составе сборки.
bugfix: Научный манипулятор теперь может держать и сборку, а не только отдельные детали.
rscadd: Добавил инфракрасному сенсору Rotate в интерфейс, теперь не надо мучиться с вёрбом. А для киборгов это будет и единственный способ повернуть его луч.
/🆑
```

</details>

Понятия не имею, сколько багов я пропустил. Но главное - лазерный луч инфракрасного сенсора движется. Ура!

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-06 22:07 UTC, O0oMaximo0O commented
По пока что невыясненным обстоятельствам, лазер не двигается, если находится в сборке с чем-то у киборга в манипуляторе.
При этом он сдвигается на правильное место, если ткнуть манипулятором по турфу.

2022-07-07 10:02 UTC, O0oMaximo0O commented
По столь же таинственным обстоятельствам оно пофиксилось само. Прогоню ещё пару тестовых запусков, если всё будет ок, можно будет ревьювать/аппрувать/мержить.

2022-07-07 12:01 UTC, O0oMaximo0O commented
Что же, я запустил 3 раза и всё было ок. Будем надеяться, что это не просто случайность.

2022-07-17 18:12 UTC, TermService submitted a review, later dismissed

2022-07-17 18:12 UTC, TermService commented
ну оно итак было сломано если че

2022-07-17 18:16 UTC, Doster-d requested changes

2022-07-17 18:16 UTC, Doster-d commented on code/_helpers/atom_movables.dm
> +/proc/get_top_holder_obj(atom/A)
Не изобретай тот же велосипед, используй готовый прок - get_atom_on_turf

2022-07-17 18:24 UTC, Doster-d commented on code/_helpers/atom_movables.dm
> +		is_correct = call(A, checking_proc)(loc)
Не понял смысл проков (где используется не могу найти, поиска нет), как и смысл колла

```suggestion
		is_correct = A.check_locs(loc, stop_on, checking_proc)
```

2022-07-17 18:29 UTC, Doster-d commented on code/_helpers/atom_movables.dm
> +		is_correct = call(A, checking_proc)(loc)
Блять хуйнб написал, но проблема тут есть!

2022-07-17 18:33 UTC, Doster-d commented on code/_helpers/atom_movables.dm
> +		is_correct = call(A, checking_proc)(loc)
И так у нас есть прок и объект к которому надо этот прок применить, но тут возникает проблема! Как проверить, что этот прок есть у объекта. Решение: проверка через hascall(obj, procname)

2022-07-17 18:38 UTC, TermService commented on code/_helpers/atom_movables.dm
> +		is_correct = call(A, checking_proc)(loc)
а это называется копипаста, копипаста не до конца....

2022-07-17 20:35 UTC, O0oMaximo0O commented on code/_helpers/atom_movables.dm
> +/proc/get_top_holder_obj(atom/A)
Это не то что мне нужно

2022-07-17 20:37 UTC, O0oMaximo0O commented on code/_helpers/atom_movables.dm
> +/proc/get_top_holder_obj(atom/A)
Я выделил этот прок из кусочка в археологии. Он нужен именно для получения объекта. А если он в руках моба, то get_atom_on_turf вернёт не то. А если моб ещё в шкафу будет?

2022-07-17 20:39 UTC, O0oMaximo0O commented on code/_helpers/atom_movables.dm
> +		is_correct = call(A, checking_proc)(loc)
Не понял проблемы. Атом, который вызвает функцию, даёт прок. Значит он у него есть.

2022-07-28 08:43 UTC, O0oMaximo0O commented on code/modules/assembly/infrared.dm
> +	if(check_locs(src, stop_on = list(/mob, /turf), checking_proc = /obj/item/device/assembly/infra/proc/check_loc))
```suggestion
	if(check_locs(src, stop_on = list(/turf), checking_proc = /obj/item/device/assembly/infra/proc/check_loc))
```

2022-07-28 18:23 UTC, TermService approved these changes, later dismissed

2022-09-06 20:31 UTC, O0oMaximo0O commented on code/modules/assembly/timer.dm
>  		time--
```suggestion
	if(!timing)
		return
	if(time > 0)
		time--
```

2022-09-26 12:40 UTC, Doster-d approved these changes, later dismissed
Сброс чр

2022-09-29 19:23 UTC, TermService submitted a review, later dismissed

2022-09-29 19:24 UTC, TermService commented
конфликты

2022-09-30 09:47 UTC, TermService approved these changes, later dismissed

2022-09-30 10:21 UTC, TobyThorne commented on code/modules/mob/living/silicon/robot/inventory.dm
> +
```suggestion
```

2022-09-30 14:17 UTC, O0oMaximo0O commented on code/modules/mob/living/silicon/robot/inventory.dm
> +
Тоби, увидел твой ПР про грипперы. Он не учитывает их переменную `wrapped`(она не обновится при дропе). Гриппер будет считать, что всё ещё держит предмет.
Надо им drop() переопределить. С поправкой на созданный can_unequip(), конечно

2022-09-30 14:21 UTC, O0oMaximo0O commented on code/modules/mob/living/silicon/robot/inventory.dm
> +
Как тебе эта версия?
```suggestion
/mob/living/silicon/robot/drop(obj/item/I, atom/target = null, force = FALSE)
	if(!can_unequip(I))
		return FALSE
	var/obj/item/gripper/G = module_active
	G.drop_item()
	if(target)
		I.forceMove(target)
	return TRUE
	

```

2022-10-05 19:43 UTC, DarkHunter7756 commented
У нас в билде ассембли не работают уже **4 месяца**. Никакие лимитки, бомбы и прочее не создать. Целая профессия уничтожена.  Так, напоминаю, если кто забыл

2022-10-05 20:02 UTC, No-Tips commented
Эм, у нас работаю ассембли. 
Напоминалка для дарка: гранаты уже четыре месяца работают на ассемблях. И никто не репортил, что они не работают. Юзаю и не жалуюсь, и тебе рекомендую.

2022-10-26 10:50 UTC, Mark-Silverstein commented
> Эм, у нас работаю ассембли. Напоминалка для дарка: гранаты уже четыре месяца работают на ассемблях. И никто не репортил, что они не работают. Юзаю и не жалуюсь, и тебе рекомендую.

Связки с сигналлерами, детекторами движения и таймерами починили.
А вот инфракрасные сенсоры не работают и луч не движется до сих пор. Как в связке, так и без неё
Вообще надо заметить, что поворот предмета в руке с помощью клика ПКМ по нему в руке - странная затея. До изменения он поворачивался по направлению взгляда персонажа.

2023-01-15 09:17 UTC, Doster-d submitted a review, later dismissed

2023-01-26 14:27 UTC, O0oMaximo0O commented
Протестил в очередной раз, вроде все заявленные баги пофикшены.

2023-01-28 09:00 UTC, kreeperHLC approved these changes

2023-01-28 09:19 UTC, Doster-d approved these changes
Сойдет

2023-01-30 17:47 UTC, merged