fix(archeologist-pickaxe): now cant break walls n code cleanup
ChaoticOnyx/OnyxBay pull request #8947
Opened 2022-07-11 19:35 UTC by No-Tips

Капец копипастой насрано. Выделил все археологические кисточик в свой подтип кирок, а то был кринж.
close #8935 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Археологические кисточки больше не ломают стены.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-11 19:53 UTC, Tsurupeta commented on code/modules/xenoarcheaology/tools/tools_pickaxe.dm
>  	drill_verb = "delicately picking"
```suggestion
```

2022-07-12 09:30 UTC, Tsurupeta commented
Баг это никак не фиксит. Но изменения приятные.

2022-07-17 16:41 UTC, Tsurupeta commented on code/game/turfs/simulated/wall_attacks.dm
> +		else if(istype(W,/obj/item/pickaxe) && !istype(W,/obj/item/pickaxe/archaeologist))
```suggestion
		else if(istype(W, /obj/item/pickaxe) && !istype(W, /obj/item/pickaxe/archaeologist))
```

2022-07-17 17:18 UTC, TermService requested changes
покажите какая строчка фиксит иссуй((

2022-07-17 17:20 UTC, Tsurupeta commented
Она где-то там, среди фиксов спанов и вывода кирочек в свой собственный тип для удобной проверки.

2022-07-17 17:34 UTC, Doster-d commented on code/game/turfs/simulated/wall_attacks.dm
> +		else if(istype(W,/obj/item/pickaxe) && !istype(W,/obj/item/pickaxe/archaeologist))
Вот тут, Терм.

2022-07-17 17:35 UTC, Doster-d submitted a review, later dismissed

2022-07-17 17:38 UTC, Tsurupeta approved these changes

2022-07-17 17:38 UTC, No-Tips commented
> покажите какая строчка фиксит иссуй((

Wall_attacks:219

2022-07-17 17:44 UTC, Doster-d approved these changes

2022-07-17 17:47 UTC, TermService approved these changes

2022-07-17 17:48 UTC, merged