tweak(pistol): reduced shaking when firing a silenced holdout pistol
ChaoticOnyx/OnyxBay pull request #8952
Opened 2022-07-11 22:16 UTC by Oubi256

Убираем ебейшую тряску (как обрез) на 9мм пистолете с глушителем, тем самым повышая его популярность.

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
tweak: Уменьшена тряска камеры при выстреле с трейторского 9mm пистолета с глушителем.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-28 18:22 UTC, TermService requested changes

2022-07-28 18:22 UTC, TermService commented on code/modules/projectiles/guns/projectile/pistol.dm
> +			screen_shake = initial(screen_shake)
было бы логичнее проверку на глушитель делать не тут, вдруг у нас появятся ещё глушители?

2022-07-29 18:50 UTC, Oubi256 commented on code/modules/projectiles/guns/projectile/pistol.dm
> +			screen_shake = initial(screen_shake)
А ведь действительно логичней. Сделал как и просил. В целом новую переменную мог и не создавать и для модификатор глушение использовать `silenced` с диапазоном от 0 до 1, но я так понимаю он задумывался как буль, по этому трогать его не стал. В любом случае как будут появляться и другие глушители - можно будет сделать лучше.

2022-08-07 09:24 UTC, TermService requested changes

2022-08-07 09:24 UTC, TermService commented on code/modules/projectiles/guns/projectile/pistol.dm
> +		silenced = 1
ты чево наделал((((

2022-08-07 09:32 UTC, Oubi256 commented on code/modules/projectiles/guns/projectile/pistol.dm
> +		silenced = 1
Посмотрел и не понял зачем оно вообще было)) Учитывая что у нас глушитель сейчас true/false и никаких свойств у глушителя нет, ибо разнообразия их нет

> ты чево наделал((((

2022-08-07 10:39 UTC, MrMagick2104 commented on code/modules/projectiles/guns/projectile/pistol.dm
> +		silenced = 1
```
to_chat(user, "<span class='notice'>You unscrew [silenced] from [src].</span>")
```
You unscrew 1 from [src].
К слову, у нас есть пистолет с интегрированным глушителем, а не только холдаут.

2022-08-07 10:51 UTC, Tsurupeta commented on code/modules/projectiles/guns/projectile/pistol.dm
> +		silenced = 1
> You unscrew 1 from [src]. К слову, у нас есть пистолет с интегрированным глушителем, а не только холдаут.

Скоро будет больше оружия.

2022-08-13 08:55 UTC, Oubi256 commented
Закрываю. В дальнейшем вместо этого надо ввести полноценную систему аттачей к оружию.

2022-08-13 08:55 UTC, closed without merging