Таяранский шарф теперь скрывает лицо
ChaoticOnyx/OnyxBay pull request #8996
Opened 2022-07-19 14:04 UTC by FloweYStyle

боттом текст

fix #8992

<details>
<summary>Чейнджлог</summary>

```yml
🆑FloweYStyle
tweak: Таяранский шарф теперь скрывает лицо.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-19 21:33 UTC, TermService approved these changes

2022-07-21 13:43 UTC, FloweYStyle commented
Можно ревью пожалуйста.

2022-07-21 14:53 UTC, IvanDonFon commented
Нельзя

2022-07-21 14:57 UTC, No-Tips approved these changes
Держи мою галочку

2022-07-21 14:58 UTC, IvanDonFon requested changes
Хуйня, переделывай

2022-07-21 14:58 UTC, Tsurupeta approved these changes

2022-07-28 18:18 UTC, merged