Добавляем больше джоб-спесифик штук в аплинк
ChaoticOnyx/OnyxBay pull request #9023
Opened 2022-07-23 11:15 UTC by No-Tips

Список предметов будет добавляться по мере поступления идей

Пока впилено:
Мим:
- Меч в виде багетта для мима
Клоун:
- Ботинки, которые разливают смазку на пол
- Станящая вувузелла
Медбат:
- Набор с заготовками для гранат
- Случайная гланда абдуктора

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена куча новых ограниченных по профессиям предметов в аплинк.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-23 11:19 UTC, No-Tips commented
Призываю Дарка для генерации кринжефич

2022-07-23 12:19 UTC, DarkHunter7756 commented
1. Гланда не слишком жирно? Для гланд как раз абдукторы и существуют
2. Я писал дофига всего в Тоби'ной фиче про джоб специфик итемы. Только где она - я хз

2022-07-23 12:29 UTC, No-Tips commented
> Гланда не слишком жирно? Для гланд как раз абдукторы и существуют

Я думаю, что норм, по своей цене в 8тк. Учитывая, что гланда спавнится случайная. Учитывая то, что абдукторы у нас все еще лишь от щитспавна, из-за их поломанности - упускать охуенный механ гланд совсем не хочется.

2022-07-23 12:33 UTC, DarkHunter7756 commented
Нормальный чел: пофиксим абдукторов и введем в ротацию
Типс-гигачад: обойдем баги абдукторов через другие рольки

2022-07-23 12:56 UTC, DarkHunter7756 commented
> Ботинки, которые разливают смазку на пол
Опять же. С каким интервалом? Если на каждый тайл, куда ступает клоун, то это рак. Пускай тогда воду, а не смазку.

2022-07-23 12:57 UTC, No-Tips commented
> > Ботинки, которые разливают смазку на пол
> 
> Опять же. С каким интервалом? Если на каждый тайл, куда ступает клоун, то это рак. Пускай тогда воду, а не смазку.

В коде пока раз в 8 тайлов при беге и раз в 5 при ходьбе

2022-07-23 12:59 UTC, DarkHunter7756 commented
Я вообще не люблю смазку. Она не приносит фана никому. Поэтому клоун и заказывает ее у химика, а не имеет сразу

2022-07-28 11:59 UTC, EliseyGladkiy commented
> Ботинки, которые разливают смазку на пол
В этих ботинках можно поскальзываться?

2022-07-28 12:17 UTC, No-Tips commented
> > Ботинки, которые разливают смазку на пол
> > В этих ботинках можно поскальзываться?

Да

2022-07-28 12:17 UTC, EliseyGladkiy commented
> > > Ботинки, которые разливают смазку на пол
> > > В этих ботинках можно поскальзываться?
> 
> Да

Коммент на глазах родился

2022-07-28 12:17 UTC, No-Tips commented
Но скорее всего сделаю, что нельзя будет.

2022-07-28 12:17 UTC, EliseyGladkiy commented
Ещё я хотел узнать по поводу урона багетомеча.
30 дамага — не слишком? Учитывая, что столько же у культблейда и топора.

2022-07-28 12:18 UTC, EliseyGladkiy commented
> Но скорее всего сделаю, что нельзя будет.

Как клоун со стажем, одобряю.

2022-07-28 12:18 UTC, No-Tips commented
> Ещё я хотел узнать по поводу урона багетомеча. 30 дамага — не слишком? Учитывая, что столько же у культблейда и топора.

Пр ещё в драфте и я просто набрасываются предметы, че и как оставлять оставлю за геймдизом, когда закончу с предметами.

2022-07-28 12:19 UTC, EliseyGladkiy commented
> > Ещё я хотел узнать по поводу урона багетомеча. 30 дамага — не слишком? Учитывая, что столько же у культблейда и топора.
> 
> Пр ещё в драфте и я просто набрасываются предметы, че и как оставлять оставлю за геймдизом, когда закончу с предметами.

Окей, понял

2022-07-28 12:27 UTC, ArmenianOnyx commented
Как по мне 30 дамага это заебись. Нерфодебилки могут и потерпеть. Нахуя миму особая тритарская вещь которая есть только у него, если она будет хуйней?

2022-07-28 13:07 UTC, Tsurupeta commented
> Как по мне 30 дамага это заебись. Нерфодебилки могут и потерпеть. Нахуя миму особая тритарская вещь которая есть только у него, если она будет хуйней?

Ну я считаю что с такой логикой можно проверку на армяна влепить и если моб является армяном, сразу его гибать.

Кусок багета, который ломает стены - не очень.

2022-07-28 13:13 UTC, ArmenianOnyx commented
Тогда выпиливайте багет, а то нереалистично. Либо добавляйте что то нормальное, либо вообще недобавояйте фигню, на которую никто не будет тратить ТК.

2022-07-28 13:15 UTC, No-Tips commented
Блядь ебучая кнопка

2022-07-28 13:17 UTC, No-Tips commented
Че вы тут устроили.... Набежали обсуждать багет, который даже ещё не получил геймдизо ревью.

2022-07-28 13:34 UTC, No-Tips commented
Я кстати забыл добавить в описание, что добавил для ботаников пару айтемов. Поправил.

2022-07-28 17:09 UTC, TobyThorne commented
Багету нужна киллер-фича. Чтоб его можно было надкусывать и каждый раз повышался шанс проткнуть себе голову. Но и урон от атаки повышался.

2022-07-31 10:20 UTC, No-Tips commented
> Багету нужна киллер-фича. Чтоб его можно было надкусывать и каждый раз повышался шанс проткнуть себе голову. Но и урон от атаки повышался.

Киллерфича добавлена.

2022-09-07 18:02 UTC, No-Tips commented
Короче пора завязывать с вечным стейлом. Держите превью эмиттер контроллера
![boom](https://user-images.githubusercontent.com/75416333/188947277-7cb855aa-8a07-4854-99d2-41bea0b9ad1c.gif)

2022-09-29 19:21 UTC, TermService requested changes

2022-09-29 19:21 UTC, TermService commented on code/game/objects/items/grenades/chem_grenade.dm
> +/obj/item/grenade/chem_grenade/apple
при такой реализации если раскрутить гранату спрайт станет обычным, не гуд

2022-09-29 19:21 UTC, TermService commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(can_wet_floor)
таймер....

2022-10-03 16:44 UTC, No-Tips commented on code/game/objects/items/grenades/chem_grenade.dm
> +/obj/item/grenade/chem_grenade/apple
![image](https://user-images.githubusercontent.com/75416333/193632781-a67c4383-c8ee-4fdd-84d8-e84bfc0674db.png)
Все в порядке...

2022-10-03 16:45 UTC, No-Tips commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(can_wet_floor)
Таймеров нет до этого нигде в парентах...

2022-10-22 09:13 UTC, No-Tips commented
Я схрюкнулся

2022-10-22 09:13 UTC, closed without merging