Переделка вампира, чтобы он был мертвым, реализация маски крови
ChaoticOnyx/OnyxBay pull request #9044
Opened 2022-07-26 21:29 UTC by Animusin

Нужно было сделать вампира мертвым. Для этого созданы вампирские органы, которые не должны работать как человеческие. Серце сделано необходимым для жизни, повышен его максимальный урон. Внедрен статус флаг UNDEAD, для того, чтобы можно было сделать вампира мертвым, но не до конца, при различных проверках.

1) Для решения отсутствия иммунитета у вампира, при работе сердца добавлены химические эффекты антивирусных. 
2) Вампир перестал терять nutrition от времени.
3) Вампиру теперь не нужно дышать.

Также была создана способность Revitalise, которая делает вампира живым на вид и для всех датчиков, запускает его сердце. Для её работы добавлен статус флаг FAKELIVING.

ПРОБЛЕМЫ:

1) Вампир стал более устойчив к урону, так как большинство органов ему не нужны, и от кровотечений он не страдает при отсутствии пульса, а также не получает урон по мозгу при не бьющемся сердце.

2) Вампир всё ещё перерабатывает химикаты, как живой.

3) Возможно он ещё и может получать питание от еды.

4) Температура тела всё ещё не комнатная.

close #8309

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Вампир теперь должен быть мертвым на вид.
tweak: Вампир получил способность Revitalise, чтобы казаться живым.
/🆑
```

</details>

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим x внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над ПРом. ЭТУ СТРОЧКУ НУЖНО УДАЛИТЬ.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-27 20:59 UTC, No-Tips requested changes
Я заебался, потом допроверю остальные 10 файлов.

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +			qdel(organ)
Оно не убьет хумана, когда ты ему буквально удалишь мозг, где хранится майнд?

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/mob/proc/use_blood(blood_to_use)
Кажется, должен быть 
```suggestion
/mob/living/carbon/human/proc/use_blood(blood_to_use)
```
Иначе при вызове этого прока на симплмоба мы получим рантайм жопы.

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/mob/proc/check_blood()
```suggestion
/mob/living/carbon/human/proc/check_blood()
```

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/mob/proc/gain_blood(blood_to_get)
```suggestion
/mob/living/carbon/human/proc/gain_blood(blood_to_get)
```

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	var/mob/living/carbon/human/H = src
```suggestion
```
Ну и тогда вот это не нужно, просто срц

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	var/mob/living/carbon/human/H = src
```suggestion
```
Ну ты понял идею.

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	var/mob/living/carbon/human/H = src
Проебал проверку на то, является ли моб хуманом
```suggestion
    if (!mind)
		return
	if (!ishuman(src))
		return
	var/mob/living/carbon/human/H = src
```
Хотя мб это тоже можно перенести в проки только для хуманов, учитывая, что вамп вроде как не может стать симплмобом.

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	var/mob/living/carbon/human/H = src
А если моб не хуман....

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	mind.vampire.blood_usable = H.vessel.get_reagent_amount(/datum/reagent/blood)
Так это чекер, или мы апдейтим юзаемую кровь? Если апдейтим, то и возвращать ничего не надо, а просто обращаться к mind.vampire.blood_usable

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			if (blood_usable != src.check_blood())
А разве не
```suggestion
			if (blood_usable != vampire.check_blood())
```

2022-07-27 20:59 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		blood_usable = src.check_blood()
Точно срц, а не вампир?

2022-07-27 21:00 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +			qdel(organ)
Майнд не в мозгах жи

2022-07-27 21:01 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +			qdel(organ)
Но разве кудел мозга не убьет хумана?

2022-07-27 21:01 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			if (blood_usable != src.check_blood())
Вамир тут это датум жи

2022-07-27 21:02 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			if (blood_usable != src.check_blood())
Ah yeah.

2022-07-27 21:03 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +			qdel(organ)
Я тестил всё на локалке. Этот код спизжен с create_organs из set_species. Всё работает.

2022-07-27 21:04 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/mob/proc/use_blood(blood_to_use)
Да, думаю мобу это не нужно, если моб не может стать вампиром. А это надо проверить

2022-07-27 21:05 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	mind.vampire.blood_usable = H.vessel.get_reagent_amount(/datum/reagent/blood)
Это чекер, который аптейдит переменную usable_blood

2022-07-27 21:05 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/mob/proc/gain_blood(blood_to_get)
Погоди, а тут еще можно тригеррунть прок если это не вампир, и тогда тоже будет рантайм жопы.

2022-07-27 21:05 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			if (blood_usable != src.check_blood())
Нет, check_blood прок моба, а не вампира

2022-07-27 21:05 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		blood_usable = src.check_blood()
Точно

2022-07-27 21:05 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/mob/proc/check_blood()
Тоже самое с этим триггером как и с тем, что ниже. если у хумана нет mind.vampire - проку будет плохо.

2022-07-27 21:14 UTC, No-Tips commented
И еще важный вопрос - ощущает ли вамп вузи хуюзи когда у него мало крови? Становится ли хаском если крови ноль?

2022-07-27 21:26 UTC, Animusin commented
> И еще важный вопрос - ощущает ли вамп вузи хуюзи когда у него мало крови? Становится ли хаском если крови ноль?

Нет и нет

2022-07-28 05:53 UTC, O0oMaximo0O commented
> ощущает ли вамп вузи хуюзи когда у него мало крови

Если имеется в виду жажда крови / ярость, то она, если я правильно помню, зависит от кол-ва используемой крови и должна появляться при - теперь уже обычной - потери крови.

Анимусин, ты это проверял?

2022-08-05 16:07 UTC, TobyThorne commented on code/modules/organs/subtypes/vampiric_organ.dm
> +/obj/item/organ/internal/brain/vampiric_brain
чё во всём этом файле за пиздец происходит

2022-08-05 16:09 UTC, Animusin commented on code/modules/organs/subtypes/vampiric_organ.dm
> +/obj/item/organ/internal/brain/vampiric_brain
Долго объяснять. В кратце - сделаны вампирские органы, у которых функционал будет отличаться от человеческих. Как минимум у сердца и мозга. А в будущем ещё у желудка. Сейчас как раз обсуждаем с Ловлой насколько это плохая идея.

2022-08-06 07:41 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			break
Брух?
А можно не через бесконечный вайл?

2022-08-06 07:46 UTC, Zert0X commented on code/game/machinery/adv_med.dm
> +	data["blood_volume_abs"] = H.get_blood_volume_abs()
А как это вообще должно работать? И нахера было переименовывать прок?

2022-08-06 07:47 UTC, Zert0X commented on code/game/machinery/adv_med.dm
> +	data["blood_volume_abs"] = H.get_blood_volume_abs()
Ладно тупанул, не туда посмотрел

2022-08-06 07:49 UTC, Zert0X commented on code/modules/organs/subtypes/vampiric_organ.dm
> +		status = ORGAN_BROKEN
напомните если нет овнера, то орган процессится и мы получаем дохера рантаймов? Или орган не процессится?

2022-08-06 09:51 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +			break
Я это спиздил с Presence'а, практически без изменений

2022-08-06 11:26 UTC, Animusin commented on code/modules/organs/subtypes/vampiric_organ.dm
> +		status = ORGAN_BROKEN
Ты прав, оно срёт рантаймами, если вырезать из вампира...

2022-08-06 13:50 UTC, Animusin commented
Ну я пофиксил безобразие в органах вампирских, они теперь наследуют от обычных полноценно, в том числе и в Process().

2022-08-09 15:05 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
бедный хуман засранный проками ему не нужными

2022-08-09 15:08 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
Переделывать ВСЕ абилки вампира в этом ПРе я не буду

2022-08-09 15:09 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
Так проблема не в этом. За4 обычному хуману эти проки? Перенеси их в вампира

2022-08-09 15:10 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
> Так проблема не в этом. За4 обычному хуману эти проки? Перенеси их в вампира

Потому что ВСЕ абилки вампира - проки хумана

2022-08-09 15:11 UTC, TobyThorne commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
б+лять 
![image](https://user-images.githubusercontent.com/45202681/183687709-87277c7e-d57f-4288-ad35-cbd051adf799.png)

2022-08-09 15:18 UTC, No-Tips commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
Пиздец тогда, нет такой картинки, которая бы описала мои эмоции

2022-08-09 15:21 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
> > Так проблема не в этом. За4 обычному хуману эти проки? Перенеси их в вампира
> 
> Потому что ВСЕ абилки вампира - проки хумана

так переделай эту, а потом отрефактори остальные в другом ПРе

2022-08-09 15:22 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
NOOOOOOOOOOOO...
Ладно...

2022-08-09 15:23 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
Не, нихуя не выйдет, придётся все переделывать

2022-08-09 15:33 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_powers.dm
> +
> Не, нихуя не выйдет, придётся все переделывать

можешь начинать

2022-08-09 16:02 UTC, No-Tips commented
Все игроки после принятия этого пра
https://youtu.be/_zM8gI_mVd4

2022-08-16 16:53 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	mind.vampire.owner = H
Не легче это в конструктор датума переместить? Чтобы при создании сразу овнер указывался.

2022-08-16 16:54 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	return
а зачем это вообще надо кстати...

2022-08-22 16:03 UTC, Tsurupeta requested changes

2022-08-22 16:03 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	org.vital = 1
Давай без удалений сердец и спавна их обратно без причины.

2022-08-22 18:15 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	org.vital = 1
Сделаю отдельно

2022-08-25 13:36 UTC, igorsaux commented on code/game/machinery/adv_med.dm
> +		if (!brain || H.stat == DEAD || (H.status_flags & FAKEDEATH) || ((isundead(H)) && !(isfakeliving(H))))
зачем тут столько скобок ((()))

2022-08-25 14:06 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_datum.dm
> +#define isundead(A) (A.status_flags & UNDEAD)
```suggestion
#define isfakeliving(A) (A?.status_flags & FAKELIVING)
#define isundead(A) (A?.status_flags & UNDEAD)
```

2022-08-25 14:07 UTC, igorsaux commented on code/game/gamemodes/vampire/vampire_datum.dm
> +#define isundead(A) (A.status_flags & UNDEAD)
не надо туда проверку на нулл пихать

2022-08-25 14:12 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	return
```suggestion
/datum/vampire/proc/use_blood(blood_to_use)
	if (!blood_to_use || blood_to_use <= 0 || blood_usable < blood_to_use)
		return FALSE
	blood_usable -= blood_to_use
	return TRUE
```

2022-08-25 14:13 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_helpers.dm
>  	// Apply frenzy while in the chapel.
```suggestion
	// Apply frenzy while in the holy location.
```

2022-08-25 14:13 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	if (get_area(loc).holy)
```suggestion
	if (get_area(loc)?.holy)
```

2022-08-25 14:21 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	else if (vampire.blood_usable < 2)
Так 1 или 2? При том что ярость при <10 наступает

2022-08-25 14:22 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_powers.dm
> +		if (user.stat == 2)
```suggestion
		if (user.stat == DEAD)
```

2022-08-25 14:24 UTC, O0oMaximo0O commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	return
При отмене способки новый таймер не нужен.
```suggestion
			to_chat(user, SPAN_WARNING("You no longer pretend to be prey."))
			return
		addtimer(CALLBACK(vampire, /datum/vampire/proc/handle_revitalise), 20 SECONDS)
```

2022-08-25 14:30 UTC, O0oMaximo0O commented on code/modules/organs/internal/kidneys.dm
> +	if(!owner || (isundead(owner) && owner))
Если не выполнилось `!owner`, значит `owner` уже истина. Во всех остальных органах то же.
```suggestion
	if(!owner || isundead(owner))
```

2022-08-25 18:31 UTC, Animusin commented on code/game/machinery/adv_med.dm
> +		if (!brain || H.stat == DEAD || (H.status_flags & FAKEDEATH) || ((isundead(H)) && !(isfakeliving(H))))
Чтобы условие выполнялось, либо если что-то там, либо ОДНОВРЕМЕННО UNDEAD и НЕ FAKELIVING. Или ты хочешь сказать, что И выполняется перед ИЛИ, и можно без скобок?

2022-08-25 18:32 UTC, Animusin commented on code/modules/organs/internal/kidneys.dm
> +	if(!owner || (isundead(owner) && owner))
Вроде логично

2022-08-25 18:35 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	else if (vampire.blood_usable < 2)
2, тут всё верно, потому что дальше он входит в ещё как минимум один цикл, в котором тратит второй пункт. К безумия не имеет отношения. Эта способность долгодействующая.

2022-08-25 18:36 UTC, Animusin commented on code/game/machinery/adv_med.dm
> +		if (!brain || H.stat == DEAD || (H.status_flags & FAKEDEATH) || ((isundead(H)) && !(isfakeliving(H))))
Понял

2022-08-25 18:39 UTC, Zert0X commented on code/modules/organs/internal/kidneys.dm
> +	if(!owner || (isundead(owner) && owner))
> Если не выполнилось `!owner`, значит `owner` уже истина. Во всех остальных органах то же.

Вообще это говно будет рантаймить, ибо если нет овнера, то оно будет проводить прок `isundead` у овнера... лучше разбить на отдельные проки

2022-08-25 18:39 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_powers.dm
> +	return
Тут ты прав

2022-08-25 18:41 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	return
Тут ты сломал случай, когда крови меньше, чем должно потратиться, но она всё равно должна потратиться, если уж прок вызвали.

2022-08-29 13:33 UTC, igorsaux submitted a review, later dismissed
главное чтоб хуманы не сломались

2022-08-31 16:08 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/datum/vampire/proc/gain_blood(blood_to_get, source)
зачем тут этот бесполезный прок? Сохраняешь на будущее? Удали, потом добавишь.

2022-08-31 16:08 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
>  /mob/proc/handle_vampire()
Если у нас вампирами становятся только хуманы, то зачем этот прок мобу?

2022-08-31 16:08 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	if (vamp_flags && !(src?.mind.vampire.status & vamp_flags))
А зачем тут src?

2022-08-31 16:08 UTC, Tsurupeta commented on code/modules/organs/blood.dm
> +
Это очередной прок который нигде не используется и вводится просто так?

2022-08-31 16:27 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/datum/vampire/proc/gain_blood(blood_to_get, source)
Могу убрать аргумент. Но сам прок нужен, чтобы не лезть и не переписывать потом каждое получение крови, а править всё в одном месте.

2022-08-31 16:28 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
>  /mob/proc/handle_vampire()
Да, он вызывается в human/Life(). Исправил.

2022-08-31 16:31 UTC, Animusin commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +	if (vamp_flags && !(src?.mind.vampire.status & vamp_flags))
Чтобы не войти в проверку с src = null, ведь оно вызывается по таймеру, мало ли что с вампиром стало за это время

2022-08-31 16:39 UTC, Animusin commented on code/modules/organs/blood.dm
> +
Используется в датчиках, нужен для подмены количества крови используя FAKELIVING.

2022-08-31 16:47 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +/datum/vampire/proc/gain_blood(blood_to_get, source)
Убери лишний аргумент тогда

2022-09-07 11:30 UTC, Tsurupeta approved these changes
Всё ещё очень не хочется аппрувать такое, но так хотя бы ЧР слетит. Надеюсь, второй человек тщательно перепроверит всё и найдёт те ошибки, что я мог пропустить.

2022-09-07 13:33 UTC, igorsaux approved these changes
![image](https://user-images.githubusercontent.com/55196698/188891458-aadb125c-fc6e-409f-b41d-0adc445f3664.png)

2022-09-07 13:34 UTC, merged