feat(wizard): reworked Blood Shard skill
ChaoticOnyx/OnyxBay pull request #9054
Opened 2022-07-27 21:45 UTC by Oubi256

Переработал сломанное умение с закосом на повышение его популярности, насколько оно было сломано можно прочитать в привязанном тикете, теперь надеюсь этим умением смогут пользоваться нормально.
Вместо зарядов у умения появился обычный КД, который можно уменьшить при прокачке КД. Помимо этого теперь осколки игнорируют цель с которой они вылетают, цель лишь теряет свою кровь со всеми сопутствующими последствиями как и изначально было задумано.
Для прокачки доступно 3 очка, на скорость и силу можно потратить до 2-х очков, суммарно 4. Это заставит игрока ~~качать силу умения~~ выбирать между КД и мощностью.
С апгрейдом силы повышается наносимый урон от осколков и затраты крови у цели.

Апгрейды силы:

0) Ничего особенного, просто урон, в том числе и с возможность получить плюху самому (как и раньше).
1) Повышение урона. Сам осколок больше нельзя заблокировать мечем или щитом.
2) Повышение урона. Маг перестает получать урон от умения и вместо это восстанавливает себе мизерное количество крови.

https://user-images.githubusercontent.com/98897017/181377734-d5f72aec-6b27-4624-adbe-cc18e8bf2649.mp4

fix #9003 

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
rscadd: Переработано умение Blood Shard. Вся подробная информация на гите.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-07-28 07:30 UTC, Tsurupeta commented on code/modules/spells/hand/blood_shards.dm
> +
Геймдизайна пока нет, но объясни мне, нахуя тебе вообще этот кусок кода.

2022-07-28 17:30 UTC, TermService requested changes

2022-07-28 17:30 UTC, TermService commented on code/modules/spells/hand/blood_shards.dm
> +		sleep(0)
куда

2022-07-28 17:30 UTC, TermService commented on code/modules/spells/hand/blood_shards.dm
> +/obj/proc/blood_fragmentate(mob/living/carbon/target, fragment_number = 30, spreading_range = 5, fragment_type)
подожди я правильно понял ты сделал абилку которая превращает человека в гранату из крови?

2022-07-28 19:53 UTC, Oubi256 commented on code/modules/spells/hand/blood_shards.dm
> +/obj/proc/blood_fragmentate(mob/living/carbon/target, fragment_number = 30, spreading_range = 5, fragment_type)
+- Беру из человека кровь и спавню условную гранату источником которой является человек. В общем сделал то что и хотели сделать изначально этим скиллом, но почему-то не сделали это +- нормально

2022-08-07 09:46 UTC, Tsurupeta commented on code/modules/spells/hand/blood_shards.dm
> +			H.blood_fragmentate(30, 5, hit_projectile)
Еще раньше ретурн сделай на моменте if(!..())

2022-08-07 09:46 UTC, Tsurupeta commented on code/modules/spells/hand/blood_shards.dm
> +		P.launch(O)
зачем этот прок хуману вообще?

2022-09-11 19:40 UTC, Oubi256 commented
Переделал умение как и договаривались с геймовнерами. Теперь его можно юзать только на себя, тратя на это кровь. На последнем уровне прокачки +2 крови за каждый осколок, который попал в хумана (если залететь в толпу, то можно выйти в 0). Помимо этого во время применения умения маг теперь стоит на месте. Так же добавлен аудио эффект и анимация применения.

2022-09-18 20:21 UTC, Doster-d approved these changes

2022-09-18 20:22 UTC, TermService approved these changes
Если сломает мы его найдём высушим и ну вы поняли

2022-09-18 20:23 UTC, Epicus7 approved these changes

2022-09-26 12:30 UTC, merged