fix(wizard): fixed custom messages output when upgrading mage skills
ChaoticOnyx/OnyxBay pull request #9078
Opened 2022-07-30 13:06 UTC by Oubi256

Починил вывод кастомных сообщений при апгрейдей умений. Это было сломано еще с момента перехода на новый дизайн спелбука.
![image](https://user-images.githubusercontent.com/98897017/181915566-2c56f3ca-7222-4616-bfe6-f44ef0d91dba.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
bugfix: Исправлен вывод сообщений апгрейда умений мага.
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-04 16:15 UTC, Doster-d requested changes

2022-08-04 16:15 UTC, Doster-d commented on code/modules/spells/spellbook.dm
> +			upgrade_message = spell_to_upgrade.empower_spell()
```suggestion
			var/upgrade_message = spell_to_upgrade.empower_spell()
```
Мы не паскаль!

2022-08-04 16:15 UTC, Doster-d commented on code/modules/spells/spellbook.dm
> +	var/upgrade_message
```suggestion
```

2022-08-04 16:15 UTC, Doster-d commented on code/modules/spells/spellbook.dm
> +			upgrade_message = spell_to_upgrade.empower_spell()
```suggestion
			upgrade_message = spell_to_upgrade.quicken_spell()
```
Может ты это хотел?

2022-08-04 16:15 UTC, Doster-d commented on code/modules/spells/spellbook.dm
>  			ASSERT(spell_to_upgrade.quicken_spell())
Может заменить на ASSERT(upgrade_message)?

2022-08-04 16:15 UTC, Doster-d commented on code/modules/spells/spellbook.dm
> +			upgrade_message = spell_to_upgrade.empower_spell()
Ну точнее вынести чуть повыше.
Я не могу до туда попасть, но суть ты понял.

2022-08-04 18:13 UTC, Oubi256 commented on code/modules/spells/spellbook.dm
>  			ASSERT(spell_to_upgrade.quicken_spell())
> Может заменить на ASSERT(upgrade_message)?

Насколько знаю ASSERT ничего не вернёт что бы я мог кинуть в return

2022-08-06 09:02 UTC, Oubi256 commented on code/modules/spells/spellbook.dm
>  			ASSERT(spell_to_upgrade.quicken_spell())
> Может заменить на ASSERT(upgrade_message)?

Я так посмотрел что ASSERT там в целом не нужен

2022-08-11 21:46 UTC, igorsaux approved these changes

2022-08-25 12:59 UTC, Tsurupeta approved these changes

2022-08-25 15:41 UTC, Doster-d approved these changes

2022-08-25 15:42 UTC, merged