Починка голодека Фронтира
ChaoticOnyx/OnyxBay pull request #9114
Opened 2022-08-05 15:07 UTC by Animusin

На голодеке Фронтира снова есть программы в консоли и он работает.

close #9092

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Голодек Фронтира снова работает.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-05 15:18 UTC, No-Tips requested changes

2022-08-05 15:18 UTC, No-Tips commented on maps/frontier/frontier_holodecks.dm
> +		"ExodusMainPrograms" = list(
```suggestion
		"FrontierMainPrograms" = list(
```

2022-08-05 15:20 UTC, No-Tips approved these changes
Норм

2022-08-05 17:27 UTC, Doster-d approved these changes

2022-08-07 09:08 UTC, Tsurupeta approved these changes

2022-08-07 09:09 UTC, merged

2022-08-08 18:44 UTC, No-Tips commented
Я запускал сервер со своими изменениями локально и все протестировал.
 Я запускал сервер со своими изменениями локально и все протестировал.
Фикс не работает.