fix(throwing): throw airlocks correctly
ChaoticOnyx/OnyxBay pull request #9127
Opened 2022-08-07 21:18 UTC by Animusin

Теперь бросок не дюпает шлюзы. 

Причина была в некорректной обработке удаления шлюза после броска.

close #9119

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Бросок больше не дюпает шлюзы
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-09 15:07 UTC, Tsurupeta commented
костыль

2022-08-25 15:39 UTC, TermService requested changes

2022-08-25 15:39 UTC, TermService commented on code/game/atoms_movable.dm
> +			if (!QDELETED(src))
надо нормально разобраться

2022-09-02 18:16 UTC, Animusin commented on code/game/atoms_movable.dm
> +			if (!QDELETED(src))
Я посидел подумал, и понял, что это лучший вариант. Ибо иначе у нас что-то, что может отправиться на удаление в первом Муве, также как и аирлоки, будет муваться второй раз. Условие на удаление должно вызываться при каждом Муве тут, не просто так оно есть выше в while.

2022-09-28 17:33 UTC, MaxZ043 commented on code/game/atoms_movable.dm
> +			if (!QDELETED(src))
Пробел после ифа тут не очень уважают.
```suggestion
			if(!QDELETED(src))
```

2023-02-14 21:37 UTC, TobyThorne commented
С августа в ЧРе, с ноября в стали. Пациент скорее тоби, чем игорь.

2023-02-14 21:37 UTC, closed without merging