Мобы без сикея теперь процессятся в крио и шкафах
ChaoticOnyx/OnyxBay pull request #9153
Opened 2022-08-08 14:32 UTC by Animusin

Оказалось, что у нас мобы в конейтнерах уезжают на z-лвл 0, и если на нём нет игрока (в шкафу, например), то он не процессится, в том числе не меняется его температура. Теперь на z-лвл 0 мобы всегда Live(), даже если игрока в шкафу или крио нет.

close #9090

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Апатики и мобы теперь охлаждаются в крио.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-08 14:33 UTC, Zert0X commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
мне кажется или это костыль?

2022-08-08 14:35 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
Ну смотри. Апатик не процессится в крио, не охлаждается. Игрок залезает в шкаф - снова процессится. Правильно просто всегда обрабатывать нулевой уровень, имхо.

2022-08-08 14:36 UTC, Zert0X commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
имхо добавь его туда откуда берутся плер левелс

2022-08-08 14:36 UTC, Zert0X commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
а если мне понадобится не процесить 0 уровень?

2022-08-08 14:37 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
> имхо добавь его туда откуда берутся плеер левелс

Так он отсюда и берется, выше определен var/static/list/player_levels = list()

2022-08-08 14:37 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
> а если мне понадобится не процесить 0 уровень?

Ну, а если понадобится не процессить какой угодно другой уровень? Нужно добавить такую фичу сюда.

2022-08-08 14:38 UTC, Zert0X commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
ыыыыыыыыыыыыыыыыыыыыыыыыыыыы смишное

2022-08-08 14:38 UTC, Zert0X commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
а почему сюда не добавляются игроки с 0 z левела?
```
		for(var/P in GLOB.player_list)
			var/mob/living/player = P
			if(!istype(player) || (player.z in player_levels))
				continue
			player_levels += player.z

```

2022-08-08 14:39 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
> а почему сюда не добавляются игроки с 0 z левела?
> 
> ```
> 		for(var/P in GLOB.player_list)
> 			var/mob/living/player = P
> 			if(!istype(player) || (player.z in player_levels))
> 				continue
> 			player_levels += player.z
> ```

Добавляются все игроки. В том числе и с z = 0.

2022-08-08 14:40 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
Но если игроков на z = 0 НЕТ, то и мобы с z = 0 не процессятся!

2022-08-08 14:40 UTC, Zert0X commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
Бля боль, я пытаюсь вспомнить зачем мы это делали

2022-08-08 15:29 UTC, Tsurupeta commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
звучит как попытка оптимизации мобконтроллера

2022-08-08 15:30 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
На стандартной карте на z = 0 лвле не так много мобов, вроде

2022-08-08 16:00 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
Это определено костыль, нужно в моб контроллере сделать проверку на нулл z

2022-08-08 16:01 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
> Бля боль, я пытаюсь вспомнить зачем мы это делали

Мы это сделали, чтобы мобы на астероите и дериликтах не процесиллись пока там никого нет

2022-08-08 16:02 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
> +		player_levels += 0
> а почему сюда не добавляются игроки с 0 z левела?
> ```
> 		for(var/P in GLOB.player_list)
> 			var/mob/living/player = P
> 			if(!istype(player) || (player.z in player_levels))
> 				continue
> 			player_levels += player.z
> 
> ```

Нужен глоб лист из майндов, тогда и апатики, и игроки процессятся будут

2022-08-08 22:52 UTC, TobyThorne reviewed
кринжа навалил

2022-08-08 22:52 UTC, TobyThorne commented on code/controllers/subsystems/processing/mobs.dm
> +			if(!istype(player) || (player.loc.z in player_levels))
```suggestion
			if(!istype(player) || (player.loc?.z in player_levels))
```

2022-08-08 22:53 UTC, TobyThorne commented on code/controllers/subsystems/processing/mobs.dm
> +			if(!istype(player) || (player.loc.z in player_levels))
хотя даже так хуета выходит, надо делать умнее

2022-08-08 22:59 UTC, Doster-d requested changes
Так лучше.

2022-08-08 22:59 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
>  			var/mob/living/player = P
```suggestion
			var/mob/living/player = P
			var/turf/T = get_turf(player)
```

2022-08-08 22:59 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
> +			if(!istype(player) || (player.loc.z in player_levels))
```suggestion
			if(!istype(player) || !istype(T) || (T.z in player_levels))
```

2022-08-08 22:59 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
> +			player_levels += player.loc.z
```suggestion
			player_levels += T.z
```

2022-08-08 22:59 UTC, Doster-d commented on code/controllers/subsystems/processing/mobs.dm
> +		if(thing.client || (thing.loc.z in player_levels) || thing.teleop)
```suggestion
		var/turf/T = get_turf(thing)
		if(thing.client || (istype(T) && (T.z in player_levels)) || thing.teleop)
```

2022-08-09 10:25 UTC, O0oMaximo0O commented
Вы что-то шило на мыло сменили. Как не процессились мобы без клиента в нулл-спейсе, так и не будут.

2022-08-09 10:27 UTC, O0oMaximo0O commented
А нет, хм, виноват. Не будут именно те, которые реально в нулл-спейсе, но это забагованные. А те, которые внутри чего-то -- те да.

2022-08-09 10:31 UTC, O0oMaximo0O reviewed
Думаю, так всё же лучше

2022-08-09 10:31 UTC, O0oMaximo0O commented on code/controllers/subsystems/processing/mobs.dm
> +			player_levels += T.z
```suggestion
			player_levels |= T.z
```

2022-08-09 10:43 UTC, Animusin commented on code/controllers/subsystems/processing/mobs.dm
> +			player_levels += T.z
Проверю, чтобы оно работало...

2022-08-09 10:53 UTC, Animusin commented
Работает

2022-08-17 02:18 UTC, Doster-d approved these changes

2022-08-20 12:27 UTC, igorsaux approved these changes
страшно

2022-08-20 12:27 UTC, merged