Озвучка анонсов
ChaoticOnyx/OnyxBay pull request #9156
Opened 2022-08-08 18:03 UTC by igorsaux

Ингейм пример:

https://user-images.githubusercontent.com/55196698/183482983-6fc69013-3dd5-415f-8ef6-ce46946c5796.mp4

<details>
<summary>Чейнджлог</summary>

```yml
🆑
soundadd: Пере-озвучены все анонсы, удалены неиспользуемые, добавлена озвучка на 90% анонсов без озвучки.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-25 15:35 UTC, TermService approved these changes, later dismissed

2022-09-06 10:44 UTC, kreeperHLC requested changes

2022-09-06 10:44 UTC, kreeperHLC commented on code/modules/events/communications_blackout.dm
> +						"#4nd%;f4y6,>�%-BZZZZZZZT")
Юникодопроблемы

2022-09-27 20:10 UTC, Zert0X commented
Если будем делать надо убавить эхо... сильно убавить...

2022-09-28 15:08 UTC, kreeperHLC submitted a review, later dismissed

2022-09-29 19:08 UTC, TermService approved these changes, later dismissed

2022-10-30 14:57 UTC, kreeperHLC commented
ха лох конфликты

2022-10-30 15:03 UTC, Zert0X approved these changes
Честно, не читал

2022-10-30 15:04 UTC, kreeperHLC approved these changes

2022-10-30 15:05 UTC, merged

2022-12-25 08:40 UTC, AnimeshkaTvar commented
Чета не пон, это промахнулись и на Индиго не попали или всё же 13-я? Какой толк топтаться на месте и менять этот звук? Лучше бы сделали какие-то озвучки, когда кто-то начинает говорить. А то свернулся ты из игры на секунду, а к тебе какой-то мимо ассистент подходит и предупреждает, что сейчас будет убивать. А ты что? А ты даже не слышишь начало диалога, покашливание там какое-то. То же относится к другим ситуациям, когда человек чем-то занят, а ты должен к нему обратиться по какой-то причине

2022-12-25 08:43 UTC, Tsurupeta commented
Твое предложение не очень, особенно в закрытом пуллреквесте.