fix(viruses): Fixed removal of the virus when the effect is mutated
ChaoticOnyx/OnyxBay pull request #9242
Opened 2022-08-20 13:59 UTC by Oubi256

Исправлено удаление вируса при мутации одного из эффектов (как в образце, так и в хумане). До этого, при удалении старого эффекта, сборщик мусора подхватывал и сам вирус. Добавлена проверка на носителя перед `deactivate()` что бы он не вызывался там где не был никогда активирован. В этой же проверке идет обNULLение `parent_disease`, для того что-бы сборщик мусора не подхватил лишнего. На локалке всё работает отлично, старый эффект удаляется, новый добавляется, таймер для мусоросборщика не появляется, в теории ничего сломаться не должно.
На момент написания этого ПР-а, багу исполнилось 14 месяцев и 15 дней.

fix #8500 

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
bugfix: Исправлен критический баг, удаляющий вирус после мутации.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-20 14:03 UTC, Doster-d approved these changes, later dismissed

2022-08-20 14:05 UTC, Doster-d commented
У тебя не будет сервер срать соплями, если у вирусов нет эффектов)

2022-08-22 20:09 UTC, O0oMaximo0O commented on code/modules/virus2/disease2.dm
> +		mutating_effect.deactivate()
В твоём варианте любой симптом не отменит свои эффекты в мобе перед своим удалением. Правда так было и раньше, но всё же.
```suggestion
	if(infected)
		mutating_effect.deactivate(infected)
```
Зануление не нужно, т.к. болезнь удаляется при отсутствии моба

2022-08-22 20:19 UTC, O0oMaximo0O commented on code/modules/virus2/disease2.dm
> +		E.deactivate()
```suggestion
	if(infected)
		E.deactivate(infected)
```

2022-08-22 20:19 UTC, Oubi256 commented on code/modules/virus2/disease2.dm
> +		mutating_effect.deactivate()
Огорчу, нужно. Если не сделать зануление, то эффект не потеряет parent_disease и активный вирус удалится. В целом это и был баг.

2022-08-22 20:20 UTC, O0oMaximo0O commented on code/modules/virus2/disease2.dm
> +		mutating_effect.deactivate()
Так ты infected теряешь, вот и удаляется

2022-08-25 15:30 UTC, TermService requested changes

2022-08-25 15:30 UTC, TermService commented on code/modules/virus2/disease2.dm
> +	infected &&	mutating_effect.deactivate(infected)
ну и че это такое

2022-08-25 16:12 UTC, O0oMaximo0O commented on code/modules/virus2/disease2.dm
> +	infected &&	mutating_effect.deactivate(infected)
Это моё предложение выше, записанное без if

2022-08-25 16:20 UTC, Tsurupeta commented on code/modules/virus2/disease2.dm
> +	infected &&	mutating_effect.deactivate(infected)
Верни if бля, не еби глаза читающих код

2022-08-25 17:02 UTC, Oubi256 commented on code/modules/virus2/disease2.dm
> +	infected &&	mutating_effect.deactivate(infected)
Каюсь, читабельность должна быть в приоритете

2022-08-25 17:07 UTC, Tsurupeta requested changes

2022-08-25 17:07 UTC, Tsurupeta commented on code/modules/virus2/disease2.dm
> +	infected &&	E.deactivate(infected)
А это?

2022-08-25 17:37 UTC, TermService approved these changes

2022-08-25 17:38 UTC, Tsurupeta approved these changes

2022-08-25 17:40 UTC, merged