feat(viruses): Comprehensive rework spread disease
ChaoticOnyx/OnyxBay pull request #9265
Opened 2022-08-25 17:00 UTC by Oubi256

В ПР-е убраны множественные старые баги, которые делали симптомы кашля и чихания не предсказуемыми для игроков, а изменена сам алгоритм заражения других через чих/кашель. Помимо этого затронут дроп соплей, он более оптимизированным и случайным (теперь рандомится и направление спрайта сопли). Перед началом этого ПР-а я уйму времени поиграл на вирусологе что бы понять всю ущербность чихов, которые не способны заражать быстро в людных местах и рассчитаны лишь на дроп соплей, по которым пройдет лишь невнимательный игрок.

О соплях. **Сопли теперь основаны на оверлее** и при попытке создания новой сопли не высохшей старой - создаться оверлей поверх уже существующей, а так же обновится таймер высыхания и добавятся вирусы с новой сопли. Это позволяет не захламлять мир отдельно живущими соплями, где каждая имеет свой личный таймер высыхания и датум с вирусом.

![image](https://user-images.githubusercontent.com/98897017/186713106-51201501-39c9-42b8-80b7-6800ae14dcd7.png)
О кашле. Раньше кашель имел лишь одну проверку на наличие маски, от результата которой зависело заразятся ли окружающие. Такая грубая проверка позволяла быть не заразным со спущенной маской/сигаретой/конфетой и даже при использовании шлемов биозащиты и других (при условии что маска при этом не одета). А кашлюны в отключке, так это вообще отдельная тема.
Теперь же мобы без сознания не кашляют и имеют полноценную проверку перед тем как попытаются распространить заразу. **Перед кашлем учитывается закрыт ли рот у инфицированного и имеет ли этот предмет биологическую защиту.** В случае если рот не прикрыт, то кашель, как и раньше, заражает всех в радиусе 2-х клеток (красная рамка). Если рот прикрыт чем-либо что не имеет биологической защиты (балаклава, бандана и т.п.), то кашель так-же заразит окружающих в радиусе 1-й клетки (голубая рамка). Если рот прикрыт предметом имеющий биологическую защиту (стерильные маски, противогазы, шлема ригов и т.д.), то никакого заражения окружающих не будет.

О чихах. К моему удивлению чихание вообще не имело проверки на наличие какой-либо защиты на лице, в любом случае заражался моб стоящий перед лицом инфицированного. Единственное что могло сделать чихание, так это положить сервер, что бы хоть кто-то в лагах наступил на соплю. По сравнению с кашлем бесполезный симптом если бы не сопли, которые время от времени всё же стреляют.
В этом ПР-е сопли реализованы аналогично как и кашель, но если кашель при отсутствии любой защиты заражает всех в радиусе 2-х клеток, то чихание заражает область 3x4 по направлению взгляда (оранжевая рамка).

Для ревьюверов:
`code/game/objects/effects/decals/Cleanable/humans.dm` - убрал иконстейты для того что бы подружить это всё с оверлеями (в идеале заменить стейт на прозрачный, а не null, буду рад если кто-то предложит правку с нужным стейтом), перенёс код инита в свой метод, который теперь отвечает за первое и последующее построение соплей. Высыхание реализовал через смену цвета, ибо с оверлеями после добавления взаимодействовать нет возможности (да и не надо).

`code/modules/virus2/helpers.dm` - добавил хелпер для проверки bio армора у предметов закрывающих рот.

`code/modules/virus2/effects/mild.dm` - обоим симптомам добавлены доп. проверки на закрытость лица, наличие биозащиты, состояние моба (что бы спящий не мог срать заразой). В эффект чиха добавил алгоритм возвращающий прямоугольную область перед игроком с использованием block().

fix #9244

<details>
<summary>Чейнджлог</summary>

```yml
🆑Oubi
tweak: Переработано распространение вирусов через кашель и чихание. Подробнее в ПР-е на GitHub
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-25 17:47 UTC, TobyThorne commented on code/game/objects/effects/decals/Cleanable/humans.dm
> +/obj/effect/decal/cleanable/mucus/proc/update_stats(list/viruses = list())
И нахрен тут лишний прок, если он вызывается исключительно из инициализации? Верни, код туда, где раньше лежал, не плоди спагетти.

2022-08-25 17:59 UTC, Oubi256 commented on code/game/objects/effects/decals/Cleanable/humans.dm
> +/obj/effect/decal/cleanable/mucus/proc/update_stats(list/viruses = list())
Он не лишний, он юзается в ините и в activate() симптома чихания. В ините он спавнит свой первый оверлей, а с activate() спавнит еще оверлеи, если дроп сопли был на уже существующем mucus
https://github.com/ChaoticOnyx/OnyxBay/pull/9265/files#diff-12636524418c30bb8f2524d1e7c8db3a64ef988701e89768a884957a0c611ebaR57

2022-08-25 18:07 UTC, TobyThorne commented on code/game/objects/effects/decals/Cleanable/humans.dm
> +/obj/effect/decal/cleanable/mucus/proc/update_stats(list/viruses = list())
ой бля пиздос. . . . . .

2022-08-25 18:07 UTC, TobyThorne commented on code/modules/virus2/effects/mild.dm
> +					mob.spread_disease_to(M)
а можно без вот такой хуйни пожалуйста, вот это точно будет сервер ронять
просто приравняй чих к кашлю

2022-08-25 18:08 UTC, TobyThorne requested changes
даже так, а то ща терм с улюлюканьем пролетит и попутно замержит

2022-08-25 18:20 UTC, Doster-d commented on code/modules/virus2/effects/mild.dm
> +					mob.spread_disease_to(M)
Оно же вообще не должно компилиться, это же mob, а не M

2022-08-25 18:56 UTC, Oubi256 commented on code/modules/virus2/effects/mild.dm
> +					mob.spread_disease_to(M)
> а можно без вот такой хуйни пожалуйста, вот это точно будет сервер ронять просто приравняй чих к кашлю

Может тогда расскажешь чему тут ронять сервер? Обычный цикл по 12-ти тюрфам и обычный block(). Если ты боишься block(), то он спокойно юзается в других более производительных билдах сс13, да и в целом перед его использованием я искал инфу в бйонд дискорде.



> Оно же вообще не должно компилиться, это же mob, а не M

Вот кто такой `mob`, это сам инфицированный
`/datum/disease2/effect/sneeze/activate(mob/living/carbon/human/mob)`
Далее по этим тюрфам ищет хуманов и на каждого найденного хумана выполняется `mob.spread_disease_to(M)`
Не вижу тут такого что бы не компилилось, учитывая что это обкатано на локалке

2022-08-31 14:38 UTC, O0oMaximo0O commented on code/game/objects/effects/decals/Cleanable/humans.dm
> +		dry_timer_id = null
Не нужно, т.к. дальше в любом случае идёт присваивание нового id.
```suggestion
```

2022-08-31 14:44 UTC, O0oMaximo0O commented on code/modules/virus2/effects/mild.dm
> +	if(!mob.can_spread_disease())
Зачем 2 раза бегать по области 3х3, правда?
```suggestion
	if(!mob.check_mouth_coverage())
		for(var/mob/living/carbon/human/M in oview(2, mob))
			mob.spread_disease_to(M)
		return
	else if(!mob.can_spread_disease())
```

2022-08-31 14:46 UTC, O0oMaximo0O commented on code/modules/virus2/effects/mild.dm
> +	if(!mob.can_spread_disease())
Сорри, ретурн проморгал. Но возможно мой вариант больше понравится.

2022-08-31 14:47 UTC, O0oMaximo0O commented on code/modules/virus2/effects/mild.dm
> +	if(!mob.can_spread_disease())
Кстати, тут дублирование кода почти полное.

2022-08-31 14:49 UTC, O0oMaximo0O commented on code/modules/virus2/effects/mild.dm
> +	if(!mob.can_spread_disease())
За исключением радиуса, всё то же. Бьонд делает какие-то оптимизации под константы или лучше определить радиус отдельно и оставить один цикл?

2022-08-31 15:00 UTC, O0oMaximo0O commented
Я правильно понимаю, что при чихе с непокрытым ртом в итоге должа быть заражена область И вокруг персонажа, И впереди него?

2022-08-31 15:04 UTC, O0oMaximo0O commented
По коду чихания получается, что если рот не прикрыт, то, если сопля не заспавнится - область сзади персонажа не будет заражена.

2022-08-31 15:11 UTC, O0oMaximo0O commented
Предлагаю в чихании перенести код с `if(!mob.can_spread_disease())` вверх.
И ещё изменить размер блока увеличенного чихания, чтобы он не перекрывался с областью 1х1 вокруг персонажа (оптимизация о-о).

2022-08-31 16:32 UTC, Oubi256 commented on code/game/objects/effects/decals/Cleanable/humans.dm
> +		dry_timer_id = null
В целом справедливо, думаю читаемость не нарушит

2022-08-31 16:38 UTC, Oubi256 commented on code/modules/virus2/effects/mild.dm
> +	if(!mob.can_spread_disease())
> За исключением радиуса, всё то же. Бьонд делает какие-то оптимизации под константы или лучше определить радиус отдельно и оставить один цикл?

Изъебнуться можно, но нужно ли? Как по мне только читаемость пострадает, а так сейчас код спокойно читается свреху вниз, новичку уж точно будет понятней.

2022-08-31 16:45 UTC, Oubi256 commented
> Я правильно понимаю, что при чихе с непокрытым ртом в итоге должа быть заражена область И вокруг персонажа, И впереди него?

Нет, я потерял return после спавна/не спавна сопли

2022-09-06 17:17 UTC, kreeperHLC approved these changes

2022-09-18 20:08 UTC, Doster-d approved these changes

2022-09-23 17:32 UTC, TobyThorne approved these changes
абсолютно ноль ревью кода, даже вкладку не открывал, если всё сломается - вините остальных двух зелёногалочников

2022-09-23 17:32 UTC, merged