feat(radiation): radiation rework :goberserk:
ChaoticOnyx/OnyxBay pull request #9279
Opened 2022-08-27 14:35 UTC by igorsaux

Был выбран вариант `Попытаться сделать полноценную систему с альфа-, бета- и гамма-излучениями, где, как и ирл, каждый тип излучения по-своему уникален.`

close #8551
close #1119

Остаётся переделать и перебалансить расчёты завязанные на старую систему радиации:

- Здоровье (частично сделано кроме органов)
- Машинерия - всякие движки и ускорители частиц
- Резисты одежды

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена приближенная к реальности симуляция радиации. Больше никакой бесконечной энергии за счёт радия.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-08-28 07:17 UTC, Voldirs commented
нииихуя себе

2022-08-28 08:56 UTC, kemperhun commented
Добавил космонавтам массу, но не прикрутил ее к киллерфиче билда, эх...

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/controllers/subsystems/radiation.dm
>  		if(source.flat)
Точно для плоской расстояние мерять не надо?

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/game/objects/items/devices/geiger.dm
> +	radiation_activity = 0
Что-то фигня какая-то.
По идее счётчик Гейгера должен работать в двух режимах, судя по выводу сообщения ниже
```
var/msg = "[scanning ? "Ambient" : "Stored"] Radiation: [fmt_siunit(radiation_dose, "Gy", 3)].<br>"
```
В зависимости от режима он должен либо накапливать дозу радиации, либо фиксировать текущий фон.
А тут это игнорится. В итоге есть две обнуляемые характеристики, а счётчик просто либо работает, либо нет.

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/game/objects/items/devices/geiger.dm
> +	radiation_activity = 0
Ладно, это отдельный иссуй и ПР нужен.

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/brain/life.dm
> +		radiation = 3 SIEVERT
Зачем ограничивать 200, если ниже до 3 сбрасывает?

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/modules/mob/living/carbon/human/life.dm
> +			set_light(0.3, 0.1, max(1,min(20, radiation * 25)), 2, species.get_flesh_colour(src))
```suggestion
			set_light(0.3, 0.1, Clamp(radiation * 25, 1, 20), 2, species.get_flesh_colour(src))
```

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/game/turfs/turf.dm
> +	)
Так, у нас что, пол тоже сдерживать радиацию будет? О_О

2022-08-28 11:35 UTC, O0oMaximo0O commented on code/modules/radiation/radiation.dm
> +	return result_energy
```suggestion
	var/turf/current_turf = get_turf(source)
	ASSERT(current_turf)
	var/turf/target_turf = get_turf(target)
	ASSERT(target_turf)

	var/unabsorbed_energy_k = 1.0
	while(current_turf != target_turf)
		unabsorbed_energy_k *= 1.0 - current_turf.calc_rad_resistance(src)
		if(unabsorbed_energy_k <= 0)
			return 0
		current_turf = get_step_towards(current_turf, target_turf)
	var/result_energy = energy * unabsorbed_energy_k / get_dist(source, target_turf) ** 2
	if(result_energy < INSUFFICIENT_RADIATON_ENERGY)
		return 0
	return result_energy
```

2022-08-28 11:36 UTC, igorsaux commented on code/game/turfs/turf.dm
> +	)
не пол а атмосфера

2022-08-28 11:38 UTC, O0oMaximo0O commented on code/game/turfs/turf.dm
> +	)
Не слишком круто? Хотя бы в сотые переделай.

2022-08-28 16:28 UTC, Voldirs commented on code/game/turfs/turf.dm
> +	)
Вообще альфа останавливается даже кожей и для человека альфа-излучение опасно только в том случае если его источник попадёт внутрь человека, в желудок, в кровь или в лёгкие в виде инертного газа радона. Но в этом случае альфа излучение с его энергией оказывает ооооооочень серьёзное влияние на организм, тут оно опаснее и гаммы, и беты будет

2022-08-28 20:22 UTC, O0oMaximo0O commented on code/modules/radiation/radiation.dm
> +		current_point = current_point.loc
Дублирование кода.

2022-08-28 20:22 UTC, O0oMaximo0O commented on code/modules/radiation/radiation.dm
> +			var/on_same_turf = get_turf(source) == current_turf
Странная проверка после такого комментария)

2022-08-28 20:22 UTC, O0oMaximo0O commented on code/modules/radiation/radiation.dm
> +			var/on_same_turf = get_turf(source) == current_turf
Лучше поместить цикл раскрутки таргета наружу, до или после прохода по тайлам.

2022-08-29 18:43 UTC, TermService requested changes

2022-08-29 18:43 UTC, TermService commented on code/__defines/flags.dm
> +#define ATOM_FLAG_IGNORE_RADIATION       0x0100 // It will not produce any radiation when it will be a radiation source.
160 же не?

2022-08-29 18:45 UTC, igorsaux commented on code/__defines/flags.dm
> +#define ATOM_FLAG_IGNORE_RADIATION       0x0100 // It will not produce any radiation when it will be a radiation source.
не

2022-08-29 19:03 UTC, Tsurupeta commented on code/__defines/flags.dm
> +#define ATOM_FLAG_IGNORE_RADIATION       0x0100 // It will not produce any radiation when it will be a radiation source.
Игорь, может в битшифты переделаешь?

2022-08-29 20:49 UTC, MrMagick2104 commented on code/modules/power/singularity/collector.dm
> +				health -= (exceed * 2)
Хардкап выработки коллекторов, который ещё их и взрывает - очень плохо.
Уже проходили в https://github.com/ChaoticOnyx/OnyxBay/pull/3854.
Текущие константы не подходят для сингулярности, ибо она взрывает коллекторы, это понятно, но, может, это вообще не нужно?

2022-08-30 10:00 UTC, TermService approved these changes, later dismissed
Ладно

2022-08-30 12:41 UTC, Doster-d approved these changes
Тесты успешно, игроки недовольны (нет), можно в прод

2022-08-30 20:02 UTC, TermService approved these changes

2022-08-30 20:02 UTC, merged