Танцы!
ChaoticOnyx/OnyxBay pull request #9326
Opened 2022-09-04 16:57 UTC by kreeperHLC

Всё плохо, завтра допилю обязательно.
<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
rscadd: Добавлены танцы.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-09-06 11:56 UTC, kreeperHLC commented
Добавил замедление и новую проверку в перемещении на эмоуты. Т.е. теперь ещё можно будет делать эмоуты, из-за которых человек будет замедляться.

2022-09-06 12:01 UTC, No-Tips commented
Кинь гифочку танцев, если можешь!

2022-09-06 13:14 UTC, TobyThorne requested changes

2022-09-06 13:14 UTC, TobyThorne commented on code/datums/movement/mob.dm
> +	delay = max(1, mob.movement_delay() + GetGrabSlowdown() + GetEmoteSlowdown())
блять ну нет не нада пожалуйста
каждый лишний вызов прока в штуке, которая вызывается сотни раз в секунду - путь в ебеня

2022-09-06 13:17 UTC, TobyThorne commented on code/modules/emotes/definitions/human.dm
> +	var/dancing = FALSE
брат ты угараешь шоле
переменная в синглтоне, одновременно танцевать может только один чел во вселенной

2022-09-06 13:18 UTC, TobyThorne commented
а ещё всякие проверки на stat, resting, buckled и иже с ними

2022-09-06 13:19 UTC, TobyThorne commented on code/datums/movement/mob.dm
> +	delay = max(1, mob.movement_delay() + GetGrabSlowdown() + GetEmoteSlowdown())
лучше уж вообще без замедления, пусть танцоры лучше убегают от пуль, это даже концептуально

2022-09-08 09:15 UTC, kreeperHLC commented
https://cdn.discordapp.com/attachments/414839549877813251/989930670937763890/2022-06-24_19-27-05.gif

2022-09-09 12:31 UTC, TobyThorne approved these changes
как-то всратенько офк код не чекал добейте ещё две галки кому надо

2022-09-09 13:19 UTC, Doster-d approved these changes
Верю

2022-09-09 13:33 UTC, Zert0X approved these changes
Тобби хуйни не апрувнет

2022-09-09 13:54 UTC, merged