fix(xenoarcheaology) sus gen
ChaoticOnyx/OnyxBay pull request #9352
Opened 2022-09-06 19:35 UTC by oleggorru

Археологический генератор щита больше нельзя прикрутить к космосу (не к полу)

fix #8698

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Археологический генератор щита больше не прикручивается к космосу.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-09-09 12:13 UTC, kreeperHLC approved these changes

2022-09-09 13:57 UTC, kreeperHLC commented
Конфликты

2022-09-12 19:51 UTC, Oubi256 requested changes

2022-09-12 19:51 UTC, Oubi256 commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
> +				if(istype(loc, /turf) && !isfloor(loc))
```suggestion
				if(!isfloor(loc))
```
Весь мир и так состоит из тюрфов, нет смысла проверять тюрф ли это

2022-09-12 19:56 UTC, TobyThorne commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
> +				if(istype(loc, /turf) && !isfloor(loc))
доёб дисмиссед, лишние проверки не бывают лишними

2022-09-17 15:41 UTC, MaxZ043 commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
> +				anchored = 0
Тут бы `FALSE` для красоты вместо нолика и единички.

2022-09-26 12:58 UTC, Tsurupeta approved these changes

2022-09-26 13:05 UTC, merged