refact(wizard): refact ethereal jaunt
ChaoticOnyx/OnyxBay pull request #9370
Opened 2022-09-10 12:59 UTC by Oubi256

Отрефакторил код, сделав его более инкапсулированным, а значит более стабильным. Значение которые мог заменить на дефайны - заменил на дефайны. Убрал sleep из кода и сделал всё на addtimer. Никаких новых функций умению не добавляет, старые тайминги не меняет.
https://www.youtube.com/watch?v=hQb1gQBY92w

Затрагивает #8984

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-09-10 12:59 UTC, Oubi256 commented
@O0oMaximo0O с тебя плашки

2022-09-10 19:37 UTC, O0oMaximo0O commented
У вас не компилится.

2022-09-10 19:37 UTC, O0oMaximo0O commented
code/modules/spells/targeted/ethereal_jaunt.dm:69:error: target.can_use_hands: undefined var

2022-09-10 20:26 UTC, Oubi256 commented
> У вас не компилится.

![image](https://user-images.githubusercontent.com/98897017/189500649-8f4e1c69-1869-4579-bf8e-a57a1e644006.png)

2022-09-12 12:48 UTC, Tsurupeta requested changes
а блуд шарды тут при чем

2022-09-12 15:10 UTC, Oubi256 commented
> а блуд шарды тут при чем

Бляяяяяяяяяяять

2022-09-29 19:00 UTC, TermService approved these changes

2022-10-29 15:36 UTC, Tsurupeta approved these changes

2022-11-02 16:57 UTC, merged