Ксеномикробы могут создать лярву в мобах
ChaoticOnyx/OnyxBay pull request #9450
Opened 2022-09-17 16:32 UTC by 4310V343k

На это уйдет 28+ юнитов и 70+ секунд
А ещё ксенобургеры теперь делают ксеномикробы
12 бургеров = лярва

resolves #5599

<details>
<summary>Чейнджлог</summary>

```yml
🆑 remindme
rscadd: Ксенобургеры теперь создаются с 5 ксеномикробами внутри
rscadd: Эти самые ксеномикробы могут создать ксенолярву в людях и мартышках
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-09-17 16:36 UTC, 4310V343k commented
ээ, оказывается @MaxZ043 уже сделал [аналогичный ПР](https://github.com/ChaoticOnyx/OnyxBay/pull/9448), но с немного другой логикой

2022-09-17 16:37 UTC, DarkHunter7756 commented
Человек с лучшим кодом получит приз! ;)

2022-09-17 16:40 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +					M.internal_organs_by_name[BP_EMBRYO] = AE
```suggestion
					M.internal_organs_by_name[BP_EMBRYO] = new /obj/item/organ/internal/alien_embryo(M)
```

2022-09-17 16:47 UTC, MaxZ043 commented
@DarkHunter7756 , тогда победитель уже должен быть очевиден.

2022-09-17 17:14 UTC, MaxZ043 commented
Я думаю, что твоя реализация имеет большее право на жизнь, чем моя, так что закрываюсь. По твоему ПРу могу лишь предложить немного уменьшить требуемое для создания лярвы количество микробов, ибо 30u в шприц не наберешь и в космонавта незаметно не выстрелишь. Ну и МБ стоит алиенам иммунитет выдать, а то смешно будет получаться, если в них жидкость залить.

2022-09-29 06:58 UTC, TermService requested changes, later dismissed

2022-09-29 06:58 UTC, TermService commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +		if(1 to 15)
Ну и что это за жесть, сделать нада нормально, отпишись в Дискорд или тут если нет идей как

2022-09-29 07:02 UTC, Zert0X commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +		if(1 to 15)
банально блин несколько do_after или слипов

2022-09-29 07:14 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +		if(1 to 15)
Смысл в том, что процессинг реагента прекратится, если его вывести из организма. Ду_афтер нужен вообще для физических действий

2022-09-29 07:15 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +		if(1 to 15)
> банально блин несколько do_after или слипов

Ура, по одной лярве каждый тик?

2022-09-29 07:18 UTC, Zert0X commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +		if(1 to 15)
ну можно конечно сделать overdose плюс проверку на уже заражённость...

2022-09-29 07:45 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +		if(1 to 15)
> ну можно конечно сделать overdose плюс проверку на уже заражённость...

Я делал код с учетом баланса. У человека должна быть хоть какая-то возможность законтрить это, к примеру прийти в медбей со словами "у меня чето внутри чешется"
К тому же я не вижу, почему микробы должны за долю секунды сразу собираться в какой-то гештальт. Как минимум, это должно занимать какое-то время, you know?

2023-01-15 09:14 UTC, Doster-d commented
ПР протух

2023-01-15 09:20 UTC, NefrNerf commented
Достер, 4 месяца назад это было. Вряд ли автор сам починит, можешь ты зафиксить?

2023-01-15 09:21 UTC, 4310V343k commented
> Достер, 4 месяца назад это было. Вряд ли автор сам починит, можешь ты зафиксить?

Зафиксить что?

2023-01-15 09:25 UTC, NefrNerf commented
Конфликты мб. Я подумал что достер про это

2023-01-15 14:53 UTC, Doster-d reviewed
Не по иссую плюс есть вот такая проблема, давай подумаем об ее решение.

2023-01-15 14:53 UTC, Doster-d commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +
```suggestion
```
С этим кодом есть следующие проблемы на текущий момент:
Если эмбрион удалили, а реагент еще остался в крови, то он не будет исполнять код ниже.
Если реагент закончиться, то один раз исполниться эта штука, но это минорная проблема и ее решение не нужно.

2023-01-15 14:59 UTC, Doster-d commented
И да, у тебя что-то с математикой, нерф говна.
Тебе надо съесть для того, чтобы получить 40 реагента (40/(количество реагента в еде = 0.1))*поглощения крови реагента из желудка равной = 1/(1/2) = 2, то есть 800 бургеров

2023-01-15 15:57 UTC, 4310V343k commented
Юнитов нужно ~30, а не 40. Напомню, что на ониксе у меня перма и про какие-то уникальные механики вроде снижение кол-ва реагентов при метаболизме из желудка я не знал.

2023-01-15 15:57 UTC, 4310V343k commented on code/modules/reagents/Chemistry-Reagents/toxins.dm
> +
👀

2023-01-15 16:01 UTC, Doster-d commented
> Юнитов нужно ~30, а не 40. Напомню, что на ониксе у меня перма и про какие-то уникальные механики вроде снижение кол-ва реагентов при метаболизме из желудка я не знал.

600 бургеров на данный момент.
Это в коде есть про метаболизм.

2023-01-15 16:08 UTC, 4310V343k commented
> > Юнитов нужно ~30, а не 40. Напомню, что на ониксе у меня перма и про какие-то уникальные механики вроде снижение кол-ва реагентов при метаболизме из желудка я не знал.
> 
> 600 бургеров на данный момент. Это в коде есть про метаболизм.

Ты от меня просишь изменить код или описание ПРа? И в том, и в другом случае кол-во бургеров, нужное для этого - заоблачное

2023-01-15 16:29 UTC, Doster-d commented
> Ты от меня просишь изменить код или описание ПРа? И в том, и в другом случае кол-во бургеров, нужное для этого - заоблачное

У меня нет власти просить тебя изменить количество необходимых бургеров, чтобы появилась лярва, это решение геймдизайна.

Но я могу сказать, что люди никогда не смогут съесть 600 бургеров из-за того, что там есть нутрименты, когда нутрименты превышают определенный кап, космонавт больше не может есть, может у тебя есть возможность поменять необходимое количество реагентов (например поделить текущие на 5), чтобы это хотя бы было реально съесть столько бургеров.

2023-01-15 16:30 UTC, Doster-d commented
К тому же у тебя в иссуе сказано, что бургер имеет в себе 10 микробов, если ты хочешь установить свои параметры, то тебе надо биться через геймдизайн.

2023-01-17 09:02 UTC, NefrNerf commented
Нерф слишком сильный, давайте за 10 бургеров до нижней границы. Там вроде 7 юнитов для этого нужно, если мне правильно подсказали. Будет 10 бургеров - поставлю +

2023-01-17 09:41 UTC, 4310V343k commented
> > Ты от меня просишь изменить код или описание ПРа? И в том, и в другом случае кол-во бургеров, нужное для этого - заоблачное
> 
> У меня нет власти просить тебя изменить количество необходимых бургеров, чтобы появилась лярва, это решение геймдизайна.
> 
> Но я могу сказать, что люди никогда не смогут съесть 600 бургеров из-за того, что там есть нутрименты, когда нутрименты превышают определенный кап, космонавт больше не может есть, может у тебя есть возможность поменять необходимое количество реагентов (например поделить текущие на 5), чтобы это хотя бы было реально съесть столько бургеров.

Это так. Разве нет возможности из еды вытащить реагенты? Да и случайно съесть даже 120 бургеров сложно

Сейчас не буду ничего менять, ждем геймдизов. 60, 120 или 600 бургеров - мне не принципиальною

> Нерф слишком сильный, давайте за 10 бургеров до нижней границы. Там вроде 7 юнитов для этого нужно, если мне правильно подсказали. Будет 10 бургеров - поставлю +

В пре четко написано 28 юнитов. Или про какую нижнюю границу речь?

2023-01-17 10:28 UTC, NefrNerf commented
Короче, 10 ксенобургеров = лярва внутри. Тогда аппруваю

2023-01-18 16:47 UTC, 4310V343k commented
12 бургеров. close enough

2023-01-18 19:38 UTC, Doster-d approved these changes

2023-03-11 15:10 UTC, kreeperHLC approved these changes

2023-03-22 10:52 UTC, merged

2023-03-22 11:34 UTC, 4310V343k commented
Спустя полгода