Киркобуровое
ChaoticOnyx/OnyxBay pull request #9514
Opened 2022-09-28 19:18 UTC by kreeperHLC

Разделил кирки и буры. Буры всё ещё являются технически подтипом кирок.
Кирки копают моментально, но слишком слабые чтобы ломать скалу полностью. При копании выпадает руда.
Буры копают медленно, зато в процессе полностью ломают скалу.
Также у скал теперь появилась Прочность. Отделена от глубины, глубина теперь только для археологии чтобы не мешаться.
Из багов - только один кусок выпадет при копке киркой, остальное только при полной выкопке скалы.
<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
tweak: Буры и кирки теперь копают по разному механу. Буры по старому, кирки кликами.

/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-15 23:14 UTC, kreeperHLC commented
Наверное всё

2022-12-09 13:39 UTC, Zert0X approved these changes
На полтора глаза посмотрел, вроде выглядит неплохо. Если игрокам не зайдёт будем думать как поправить.

2022-12-09 13:48 UTC, Zert0X requested changes
я слепой и не вижу взаимодействие КИРКИ и камня, а также 
![изображение](https://user-images.githubusercontent.com/42303535/206716420-a774aa83-a0c1-4f91-8448-87313c162f30.png)

2023-01-14 14:48 UTC, Zert0X submitted a review, later dismissed

2023-01-14 15:54 UTC, kreeperHLC commented
В твиках добавлен нормальный спавн руды при копке киркой и всё.

2023-01-14 16:13 UTC, Zert0X approved these changes
не читал

2023-01-14 19:38 UTC, Tsurupeta approved these changes
Вроде норм

2023-01-14 21:31 UTC, merged