BLYATB CODER WHO WROTE CODE FOR PIPES I AM WANNA KILL YOU!!!
ChaoticOnyx/OnyxBay pull request #9519
Opened 2022-09-29 13:19 UTC by Zert0X

Добавленн респрайт хит эксченжера на батарею...

https://user-images.githubusercontent.com/42303535/193042198-529d2617-d3e7-43df-a75f-f6cd80656af0.mp4

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-09-29 19:43 UTC, TermService commented on code/game/machinery/pipe/construction.dm
> +			src.pipe_type = PIPE_JUNCTION_WALL_RADIATOR_LEFT
src зачем?

2022-09-29 19:58 UTC, Zert0X commented on code/game/machinery/pipe/construction.dm
> +			src.pipe_type = PIPE_JUNCTION_WALL_RADIATOR_LEFT
лучше так чем выстрел в колено.

2022-09-30 08:33 UTC, kreeperHLC requested changes

2022-09-30 08:33 UTC, kreeperHLC commented on code/game/machinery/pipe/construction.dm
> +		"wall radiator",\
```suggestion
		"wall radiator"
```

2022-09-30 08:33 UTC, kreeperHLC commented on code/game/machinery/pipe/construction.dm
> +		"wall_radiator",\
```suggestion
		"wall_radiator"
```

2022-09-30 08:40 UTC, Zert0X commented on code/game/machinery/pipe/construction.dm
> +		"wall_radiator",\
нет же скобочка то закрывается на некст строке

2022-09-30 09:32 UTC, TobyThorne approved these changes
выглядит салидна

2022-09-30 09:45 UTC, TermService approved these changes

2022-09-30 21:03 UTC, kreeperHLC approved these changes

2022-09-30 21:03 UTC, merged