fix(map): fix gas in SM engine
ChaoticOnyx/OnyxBay pull request #9574
Opened 2022-10-01 19:48 UTC by SVEDETEL69

Убрал газ из двигателя на карте Сансет.

`close #9151`

ЗДЕСЬ нужно **расписать изменения** которые попадут в **чейнджлог**, формат - `prefix: description`, пример:

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Убран воздух из реактора СМ на карте Сансет.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-03 16:06 UTC, Tsurupeta requested changes
Сделай airless пол вместо оверрайда переменной initial gas.

2022-10-03 17:18 UTC, SVEDETEL69 commented
> Сделай airless пол вместо оверрайда переменной initial gas.

Поменял

2022-10-03 17:30 UTC, Tsurupeta approved these changes

2022-10-04 12:19 UTC, kreeperHLC approved these changes

2022-10-07 09:01 UTC, merged