Fix(icons): fix tajar's altslim suits
ChaoticOnyx/OnyxBay pull request #9579
Opened 2022-10-02 06:16 UTC by BaraBarax

Fix altslim suits for tajars

Добавил спрайты альтслимов спрайтам слимтаяр, теперь должны отображаться сьюиты должны отображаться нормально, мой первый фикс, не бейте сильно

fix #9228 

<details>
<summary>Чейнджлог</summary>

```yml
🆑 BaraBara
bugfix: Сьюиты на слим таярах теперь отображаются более корректно
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал. 
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-03 09:15 UTC, TobyThorne commented
всё очень плохо

2022-10-03 09:39 UTC, BaraBarax commented
ачё, вроде работает

2022-10-03 15:44 UTC, BaraBarax commented
я осознал свою долбаёбость, щас получше будет

2022-10-04 05:18 UTC, SVEDETEL69 commented
Смешное

2022-10-09 23:49 UTC, kreeperHLC approved these changes, later dismissed

2022-10-10 03:59 UTC, TobyThorne requested changes
@kreeperHLC найс зелёные галочки выткаешь 
![image](https://user-images.githubusercontent.com/45202681/194797526-2e11db0b-92a4-4faa-ba11-ff913ecca017.png)

2022-10-10 12:41 UTC, BaraBarax commented
о, нихуя

2022-10-10 12:44 UTC, BaraBarax commented
А чё с ними делать?

2022-10-10 13:04 UTC, Tsurupeta commented
убрать...

2022-10-10 13:32 UTC, BaraBarax commented
Чисто этот?..

2022-10-10 13:36 UTC, Tsurupeta commented
Кого этот, белые линии убери со спрайта...

2022-10-10 13:46 UTC, BaraBarax commented
убрал

2022-10-10 13:51 UTC, BaraBarax commented
а бля, эти полоски ещё тогда у слимальта просто убрать надо

2022-10-11 11:19 UTC, kreeperHLC commented
Конфликты

2022-10-11 12:07 UTC, BaraBarax commented
понимаю, на слиме кстати тоже полосы. А ещё этот бодибилд не там обувь берёт...

2022-10-12 09:58 UTC, BaraBarax commented
Проще переделать эту хуйню как по мне, чем чинить, заодно и обувь исправлю

2022-10-12 09:59 UTC, closed without merging