tweak(jobs): edited xenojobs whitelist according to lore
ChaoticOnyx/OnyxBay pull request #9604
Opened 2022-10-05 12:59 UTC by BaraBarax

Добавил профессий в соответствии с вики ксеносам

close #9601 

<details>
<summary>Чейнджлог</summary>

```yml
🆑 BaraBara
tweak: Изменены рестрикты рас в соответствии с лором
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-05 13:01 UTC, MaxZ043 requested changes
Ты забыл про Фронтир, Сансет и Полярку. В файлах тех карт тоже нужно рестрикты поправить.

2022-10-05 13:03 UTC, BaraBarax commented
У них их нет, они берут из одного файла же...

2022-10-05 13:12 UTC, MaxZ043 commented on maps/exodus/exodus_jobs.dm
> +								/datum/job/assistant,
```suggestion
```

2022-10-05 13:14 UTC, MaxZ043 commented
На сколько я понял, у нас используется для рестриктов файлик с исходом (поправьте, если не прав). Вроде, проблем с кодом нет, кроме выше указанной.

2022-10-05 13:17 UTC, Tsurupeta commented
на исходе исходовский, на остальных дефолтный

2022-10-05 13:19 UTC, Tsurupeta requested changes

2022-10-05 13:19 UTC, Tsurupeta commented on maps/exodus/exodus_jobs.dm
> +									/datum/job/merchant,
```suggestion
									/datum/job/merchant
```

2022-10-05 13:19 UTC, Tsurupeta commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/merchant,
```suggestion
			/datum/job/merchant
```

2022-10-05 13:21 UTC, Tsurupeta approved these changes
лан

2022-10-05 14:06 UTC, SVEDETEL69 commented
Не лан

2022-10-05 14:47 UTC, Tsurupeta commented
> Не лан

не тебе решать

2022-10-05 16:42 UTC, SVEDETEL69 commented
> > Не лан
> 
> не тебе решать
🤨

2022-10-07 08:55 UTC, kreeperHLC approved these changes

2022-10-07 08:56 UTC, merged