tweak(background): removes citizenship and renames faction
ChaoticOnyx/OnyxBay pull request #9610
Opened 2022-10-06 13:12 UTC by Tsurupeta

close #9599

![image](https://user-images.githubusercontent.com/41485301/194322764-36e9e797-d1d8-4e95-b049-8309fe59ce92.png)
В крю рекордсах и аплинке поле также отображается как "Background".

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscdel: Удалена вкладка "citizenship".
tweak: Вкладка "Faction" переименована в "Background".
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-09 13:27 UTC, kreeperHLC reviewed
Я больше ничего с крестиками принимать не буду

2022-10-09 13:31 UTC, kreeperHLC requested changes
Я знаю что ты можешь реализовать это лучше

2022-11-28 17:50 UTC, Tsurupeta commented
да да я пофиксил вашу хуйню через 2 месяца, а ещё пофиксил 3 ошибки дримчекера которые меня заебали, скоро ещё может быть 3 пофикшу и циферки проблем не будет 
![image](https://user-images.githubusercontent.com/41485301/204346365-51b2a817-0cb2-4a40-b83f-21861882d784.png)

2022-12-01 10:37 UTC, Doster-d approved these changes
Провокация идет йухан с тупичка

2022-12-01 17:46 UTC, kreeperHLC approved these changes

2022-12-01 17:47 UTC, merged