Добавить новую музыку в лобби
ChaoticOnyx/OnyxBay pull request #9663
Opened 2022-10-11 14:48 UTC by MemoryDreams

Добавил четыре новых трэка в лобби: 
Proton Lander от группы Spaceslug;
One Way Trip To The Sun от группы Ditch;
Sonic Armada от группы Air;
и Lava от той же группы.

Proton Lander и One Way Trip To The Sun это роковые композиции стонер рока. Обе про космос, как можно было догадаться из названия. Первая повествует о космической войне, вторая навевает атмосферу бесконечного одинокого космоса, поэтому, думаю, обе идеально подходят для нашего лобби.

Композиции группы Air взяты из саунтрека фильма Trip to the Moon Жоржа Мельеса. Обе композиции пропитанны духом авантюризма и атмосферой книг Жуля Верна. Обе про космос и ретро-футуризм, поэтому, так же очень подходят нам. 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
soundadd: Added new lobby music
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-11 14:58 UTC, TobyThorne requested changes
![image](https://user-images.githubusercontent.com/45202681/195126563-260106ab-5c55-481c-aaf2-c71ff12b819e.png)
ты рофлишь шоль, сожми это говно

2022-10-11 15:01 UTC, TobyThorne commented
Ну и по самому музончику:
1 - интро на пол-минуты, дальше какой-то жёсткий earrape-митол
2 - интро на шесть минут, ждал когда начнётся и не дождался
3 - **пиздец** иррейп -уши за что
4 - норм, душевное

2022-10-13 20:25 UTC, TobyThorne approved these changes
ещё пожми а

2023-01-14 12:35 UTC, Zert0X commented
![изображение](https://user-images.githubusercontent.com/42303535/212471792-1f57e4c9-5ba4-4a23-97ce-f0671aed2abf.png)
жми

2023-03-15 14:28 UTC, kreeperHLC commented
![image](https://user-images.githubusercontent.com/14943437/225340195-9b4810f9-0a76-4e6e-a3ac-cf28e435d0e7.png)

2023-03-15 14:28 UTC, closed without merging

2023-03-15 14:30 UTC, igorsaux commented
Просто из билда нашего билда СС14 добавьте, там одна база :trollface: