New cosplay drip: Bee Mask for unknown (for me) places
ChaoticOnyx/OnyxBay pull request #9685
Opened 2022-10-14 20:07 UTC by DarkHunter7756

код для 1 маски по запросу ие

пока без спрайта

<details>
<summary>Чейнджлог</summary>

```yml
🆑
`tweak` Создан код для 1 маски
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-14 20:23 UTC, Tsurupeta commented
мда дарк

2022-10-17 09:38 UTC, Doster-d submitted a review, later dismissed
LGTM

2022-10-17 11:43 UTC, Medjic commented
Дарк, почему ты не использовал мои перерисованные спрайты для масок, которые меня просил подредактировать Браузер? В чём была сложность просто взять мои файлы или не ебать мозги с самого начала?

2022-10-18 07:15 UTC, TobyThorne commented on code/modules/clothing/masks/animal.dm
> +	say_verbs = list("whinnies", "neighs", "says")
```suggestion
	say_verbs = list("whinnies", "neighs", "says")

```

2022-10-18 17:31 UTC, Tsurupeta requested changes

2022-10-18 17:31 UTC, Tsurupeta commented on code/modules/clothing/masks/animal.dm
> +
чел

2022-10-18 17:34 UTC, DarkHunter7756 commented on code/modules/clothing/masks/animal.dm
> +
Что требуется изменить?

2022-10-18 17:42 UTC, Tsurupeta commented
![image](https://user-images.githubusercontent.com/41485301/196505218-57d874fa-548b-4920-9073-c0415943a190.png)
чел

2022-10-18 17:43 UTC, DarkHunter7756 commented
Я вижу, ща

2022-10-18 18:01 UTC, Tsurupeta approved these changes
лан

2022-10-18 18:03 UTC, Doster-d approved these changes
LGTM, Дарк подбросил свинью

2022-10-20 13:00 UTC, TobyThorne approved these changes
![image](https://user-images.githubusercontent.com/45202681/196955409-681db642-004b-4b1d-bd56-04920e47d3c6.png)
![image](https://user-images.githubusercontent.com/45202681/196955527-03caa5f3-c481-4332-aab3-6a8182f4a6d0.png)

Збс, можно косплеить.

2022-10-20 13:01 UTC, merged