Уникальный спрайт для автоматического долота
ChaoticOnyx/OnyxBay pull request #9694
Opened 2022-10-15 23:27 UTC by kreeperHLC

![image](https://user-images.githubusercontent.com/14943437/196011174-9c1c744d-ed4c-4fda-a7ac-41219924da02.png)

<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
imageadd: Уникальный спрайт для автоматического долота.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-15 23:46 UTC, TobyThorne requested changes
понятно
![image](https://user-images.githubusercontent.com/45202681/196011506-ee1391c2-d8cb-4536-bb11-b0a794166a6e.png)
![image](https://user-images.githubusercontent.com/45202681/196011522-419347cb-0ef1-49bd-90e5-772215bb519c.png)
![image](https://user-images.githubusercontent.com/45202681/196011541-15d5898a-f99e-48a0-9dab-f1828c5d4a57.png)

2022-10-15 23:46 UTC, kreeperHLC commented
ДА Я ЖЕ СОХРАНЯЛ НОВОЕ НАЗВАНИЕ

2022-10-16 02:13 UTC, kreeperHLC commented
> понятно ![image](https://user-images.githubusercontent.com/45202681/196011506-ee1391c2-d8cb-4536-bb11-b0a794166a6e.png) ![image](https://user-images.githubusercontent.com/45202681/196011522-419347cb-0ef1-49bd-90e5-772215bb519c.png) ![image](https://user-images.githubusercontent.com/45202681/196011541-15d5898a-f99e-48a0-9dab-f1828c5d4a57.png)

Пофикшено

2022-10-16 10:25 UTC, TobyThorne approved these changes

2022-10-16 10:28 UTC, igorsaux approved these changes
shpatel'

2022-10-17 21:49 UTC, merged