fix(xenos): melting walls by corrosive acid
ChaoticOnyx/OnyxBay pull request #9701
Opened 2022-10-17 00:44 UTC by Einst1

Вернул метод, который использовался для уничтожения стен кислотой.

close #9629 

<details>
<summary>Чейнджлог</summary>

```yml
🆑Einstein1088
bugfix: Теперь чужие снова могут плавить стены.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-17 03:57 UTC, TobyThorne requested changes
Не, так нельзя. Если где-то в принципе вызывается qdel(турф), то как раз в то место надо пихать проверку на турф и вместо кудела использовать то что нужно - dismantle_wall(), ChangeTurf() и т.д.

2022-10-17 21:30 UTC, TobyThorne submitted a review, later dismissed
ну так уже можно, да

2022-10-19 14:25 UTC, kreeperHLC submitted a review, later dismissed

2022-10-19 14:47 UTC, Tsurupeta commented
крипер зачем ты аппруваешь пуллреквесты с мержконфликтами?

2022-10-19 14:50 UTC, Medjic commented
А они были до этого?

2022-10-19 15:00 UTC, Tsurupeta commented
Конечно же были.

2022-10-19 16:08 UTC, closed without merging