fix(STD): Remove inability to accommodate rifles
ChaoticOnyx/OnyxBay pull request #9714
Opened 2022-10-18 18:49 UTC by DarkHunter7756

Пофикшена вместительность СТД. Теперь он может вмещать лазерные винтовки

fix #8753

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix Лазерные винтовки из арсенала теперь вмещаются в STD
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [ ] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-18 18:51 UTC, Medjic commented
Ты протестировал на локалке?

2022-10-18 18:52 UTC, DarkHunter7756 commented
Галочки видишь?

2022-10-18 18:52 UTC, Medjic commented
А, у тебя одна строка. Я хотел новый тип стд сам ввести, но и так тоже можно.
👌

2022-10-18 19:06 UTC, Tsurupeta commented
чел у тебя чл сломался

2022-10-18 19:09 UTC, DarkHunter7756 commented
вот поэтому я и завожу драфты. Я только начал )

2022-10-18 19:17 UTC, Tsurupeta commented
![image](https://user-images.githubusercontent.com/41485301/196523605-dcda3f4d-e924-4aa0-8520-f51e80edc5ae.png)
чел это не драфт

2022-10-18 19:19 UTC, DarkHunter7756 commented
ты видишь галочки готовности?

2022-10-18 19:32 UTC, Zert0X commented
> ты видишь галочки готовности?

Энивей был не драфт, вот теперь драфт:
![изображение](https://user-images.githubusercontent.com/42303535/196526354-fa6276d7-4a1f-417b-9795-2ab6fc7c9ebd.png)
![изображение](https://user-images.githubusercontent.com/42303535/196526367-3bc3f076-3c44-4f9d-b361-dabb9bcd82e7.png)

2022-10-19 16:12 UTC, No-Tips requested changes

2022-10-19 16:12 UTC, No-Tips commented on code/game/objects/items/storage/briefcase.dm
> +	slot_flags = SLOT_BELT
Втф брифкейс можно на пояс повесить? Спасибо не надо

2022-10-19 16:22 UTC, No-Tips commented
>не использовать кейс, как аналог Bag of Holding
![doubt](https://user-images.githubusercontent.com/75416333/196748566-7fda7d28-5848-44d3-adda-015182ecfba1.png)

2022-10-19 16:23 UTC, DarkHunter7756 commented
Ладно, оно не совсем готово ;)

2022-10-20 12:52 UTC, TobyThorne approved these changes

2022-10-20 17:09 UTC, igorsaux approved these changes

2022-10-22 08:20 UTC, merged