Kitty Ears Massive Improvement
ChaoticOnyx/OnyxBay pull request #9769
Opened 2022-10-25 15:45 UTC by MemoryDreams

Вытащил функцию, которая делает оверлей хвоста под цвет волос носителяв отдельную функцию update_state(). Переменную цвета волос носителя вынес в код самого хвоста, чтобы сохранить цвет волос. Это нужно для создания нового оверлея при смене режима анимации хвоста. Смена режима производится кнопкой Toggle Tail во вкладке Object. При успешной смене анимации в чатик выводится сообщение юзеру. 
Такой же функционал добавил и в коллекционные ушки.

<details>
<summary>Добавляет новый режим ехидного виляния хвостом</summary>

```yml
🆑
imageadd: Добавлена новая плавная анимация движения хвостом и кнопка переключения между режимами.
/🆑
```

</details>

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.
- [X] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-25 15:47 UTC, Tsurupeta commented
ты уверен что это improvement и что он massive?

2022-10-25 15:48 UTC, MemoryDreams commented
> ты уверен что это improvement и что он massive?

Абсолютли.

2022-10-25 16:14 UTC, No-Tips commented on code/modules/clothing/head/misc_special.dm
> +		icon_override = null
У тебя где-то овверайдится разве, чтобы занулять?

2022-10-25 16:17 UTC, No-Tips commented on code/modules/clothing/head/misc_special.dm
> +		icon_override = null
![image](https://user-images.githubusercontent.com/75416333/197828175-35e07eb2-722a-4d82-ba8d-01accef4e7ea.png)
Эм, овверрайдится, но ааээ, может, ты тогда везде их уберешь?

2022-10-25 16:23 UTC, MemoryDreams commented on code/modules/clothing/head/misc_special.dm
> +		icon_override = null
В смысле? Не понимаю, в чём проблема.

2022-10-25 16:31 UTC, Tsurupeta commented on code/modules/clothing/head/misc_special.dm
> +/obj/item/clothing/head/kitty/verb/update_state()
```suggestion
/obj/item/clothing/head/kitty/proc/update_state()
```

2022-10-25 16:37 UTC, No-Tips requested changes
На еарс слотах не работает, переделывай

2023-01-14 12:21 UTC, kreeperHLC commented
Мемори, конфликты

2023-02-14 21:35 UTC, TobyThorne commented
Почти полгода в ЧРе, аборт.

2023-02-14 21:35 UTC, closed without merging