Revert "fix(overlay, sight) Preventing overlays from appearing unlit …
ChaoticOnyx/OnyxBay pull request #9792
Opened 2022-10-30 18:55 UTC by igorsaux

ломает мезонки

![unknown](https://user-images.githubusercontent.com/55196698/198896409-dba16394-65b6-439a-8c71-1817a7737e47.png)

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-10-30 19:06 UTC, Doster-d requested changes

2022-10-30 19:06 UTC, Doster-d commented on code/modules/clothing/clothing.dm
> +/obj/item/clothing/mob_can_equip(M as mob, slot, disable_warning = 0)
```suggestion
/obj/item/clothing/mob_can_equip(M, slot, disable_warning = FALSE)
```

2022-10-30 19:06 UTC, Doster-d commented on code/modules/clothing/clothing.dm
> +/obj/item/clothing/under/proc/set_sensors(mob/user as mob)
```suggestion
/obj/item/clothing/under/proc/set_sensors(mob/user)
```

2022-10-30 19:06 UTC, Doster-d commented on code/modules/mob/living/parasite/meme.dm
> +/mob/living/parasite/meme/verb/SubtleJump(mob/living/carbon/human/target as mob in view(1,host) - usr - usr:host)
```suggestion
/mob/living/parasite/meme/verb/SubtleJump(mob/living/carbon/human/target in view(1,host) - usr - usr:host)
```

2022-10-30 19:06 UTC, Doster-d commented on code/modules/mob/living/parasite/meme.dm
> +/mob/living/parasite/meme/verb/ObviousJump(mob/living/carbon/human/target as mob in view(host) - usr - usr:host)
```suggestion
/mob/living/parasite/meme/verb/ObviousJump(mob/living/carbon/human/target in view(host) - usr - usr:host)
```

2022-10-30 19:06 UTC, Doster-d commented on code/modules/mob/living/parasite/meme.dm
> +/mob/living/parasite/meme/verb/AttunedJump(mob/living/carbon/human/target as mob in view(host)&indoctrinated)
```suggestion
/mob/living/parasite/meme/verb/AttunedJump(mob/living/carbon/human/target in view(host)&indoctrinated)
```

2022-10-30 23:29 UTC, Doster-d approved these changes
Ладно это не крит хуйня

2022-10-31 11:28 UTC, Tsurupeta approved these changes

2022-10-31 11:29 UTC, merged