tweak(hit_appends) hit suffix translation
ChaoticOnyx/OnyxBay pull request #9838
Opened 2022-11-07 21:04 UTC by sephirothseeker

Перевод суффиксов, вставляемых в речь персонажа, при ударе по нему оружием ближнего боя.
<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Переведены на русский эффекты в чате от ударов.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-11-08 00:52 UTC, TimErmolt commented
У нас в гайде по контрибуции написано, что в коде русского языка быть не должно во избежание всевозможных проблем. Актуально или нет -- шут знает, но если да, то здесь лучше в отдельный файл вынести. Заодно можно побольше этих приставок добавить (считаю, что "-ХРНК" должно быть в списке, самая культовая из приставок).

2022-11-08 10:33 UTC, kreeperHLC approved these changes, later dismissed

2022-11-08 13:01 UTC, sephirothseeker commented
> У нас в гайде по контрибуции написано, что в коде русского языка быть не должно во избежание всевозможных проблем. Актуально или нет -- шут знает, но если да, то здесь лучше в отдельный файл вынести. Заодно можно побольше этих приставок добавить (считаю, что "-ХРНК" должно быть в списке, самая культовая из приставок).

Дело в том, что эти приставки вставляются в русскую речь персонажа на английском, что выглядит максимально  неуместно и отвлекающе

2022-11-08 13:57 UTC, Doster-d requested changes
У вас не аскии символы в коде, исправьте

2022-11-08 15:15 UTC, Tsurupeta commented
> У вас не аскии символы в коде, исправьте

у поли тоже в коде кириллица

2022-11-08 15:21 UTC, Doster-d commented
> у поли тоже в коде кириллица

Ошибки прошлого, это тоже можно исправить в этом ПРе.

2022-11-08 15:52 UTC, sephirothseeker commented
> У вас не аскии символы в коде, исправьте

и как это исправлять?

2022-11-09 09:54 UTC, TimErmolt commented
Я же сказал: сделай отдельный текстовый файл с приставками, и в коде запили, чтобы пикалось из этого файла. С Поли всё то же самое. Есть примеры такого кода вроде бы где-то в галлюцинациях, там рандомная речь из файла с репликами выбирается.

2022-11-09 10:15 UTC, Doster-d commented
Или в питомцах

2022-11-09 16:56 UTC, sephirothseeker commented
![image](https://user-images.githubusercontent.com/107106680/200892496-887ee2f0-8588-4b80-836d-268c9e2ea491.png)

2022-11-15 06:23 UTC, Doster-d approved these changes

2022-11-17 15:32 UTC, kreeperHLC approved these changes

2022-12-31 22:08 UTC, igorsaux commented
вы чё ебанутые пару слов в отдельный файл выносить

2023-01-01 00:01 UTC, Tsurupeta commented
Да

2023-01-14 12:04 UTC, kreeperHLC commented
Прости за несколько месяцев ожидания.

2023-01-14 12:04 UTC, merged