map-tweak(polar): rnd improvement
ChaoticOnyx/OnyxBay pull request #9866
Opened 2022-11-20 10:48 UTC by SVEDETEL69

Улучшение рнд полярки. Переделана робототехника, кабинет рд и несколько других изменений.

close #9595

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Переделана робототехника полярки, теперь она красивая.
tweak: Добавлена новая комната с интегралками на полярке.
tweak: Также в рнд улучшены комната отдыха, пункт первой помощи, кабинет рд и рнд-дормы.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-11-21 18:13 UTC, Zert0X submitted a review, later dismissed
ладно похуй уговорил, но я бы лампочки сделал потемнее

2022-11-21 19:37 UTC, SVEDETEL69 commented
> ладно похуй уговорил, но я бы лампочки сделал потемнее

Эээ, я тут фиксанул кое-что снова ревувни пж

2022-11-21 19:44 UTC, Zert0X requested changes
![изображение](https://user-images.githubusercontent.com/42303535/203144737-ce6cd830-452a-402f-b811-1906ad622bad.png)
куда потерял?

2022-11-24 19:10 UTC, SVEDETEL69 commented
> ![изображение](https://user-images.githubusercontent.com/42303535/203144737-ce6cd830-452a-402f-b811-1906ad622bad.png)
> куда потерял?

Всмысле потерял?

2022-11-24 19:17 UTC, Zert0X commented
> > ![изображение](https://user-images.githubusercontent.com/42303535/203144737-ce6cd830-452a-402f-b811-1906ad622bad.png)
> > куда потерял?
> 
> Всмысле потерял?

Там был стул... Ирод

2022-11-24 21:11 UTC, SVEDETEL69 commented
> > > ![изображение](https://user-images.githubusercontent.com/42303535/203144737-ce6cd830-452a-402f-b811-1906ad622bad.png)
> > > куда потерял?
> > 
> > Всмысле потерял?
> 
> Там был стул... Ирод

:nooo:

2022-11-29 18:02 UTC, SVEDETEL69 commented
> > > ![изображение](https://user-images.githubusercontent.com/42303535/203144737-ce6cd830-452a-402f-b811-1906ad622bad.png)
> > > куда потерял?
> > 
> > 
> > Всмысле потерял?
> 
> Там был стул... Ирод

Ээ, я проснулся после 8 дневной спячки, починено всё.

2022-12-03 15:32 UTC, closed without merging