fix(job_restricts): fix job restricts for skrells
ChaoticOnyx/OnyxBay pull request #9870
Opened 2022-11-21 14:26 UTC by BaraBarax

close #9867

Обосрался, ну ничё, убрал же

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
bugfix: Теперь у нас ещё и скреллы инженеры есть.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-11-22 05:55 UTC, Doster-d requested changes
~~Ура, я нашел к чему придраться и скреллы не смогут получить свою жопу до конца месяца~~

2022-11-22 05:55 UTC, Doster-d commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
Эээ нахуй убери мертвую жопу!!!

2022-11-22 05:55 UTC, Doster-d commented on maps/exodus/exodus_jobs.dm
> +								/datum/job/atmos,
Отсюда тоже!!!

2022-11-22 16:57 UTC, BaraBarax commented on maps/exodus/exodus_jobs.dm
> +								/datum/job/atmos,
в чём доёб
![ne-srath](https://user-images.githubusercontent.com/96526791/203375083-6dfd6f3a-bf49-4869-a85e-c5b931992a6b.gif)

2022-11-22 16:59 UTC, BaraBarax commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
в чём доёб
![ne-srath](https://user-images.githubusercontent.com/96526791/203375426-5e13b8ec-f7ba-45b4-a28c-429257e5718e.gif)

2022-11-22 16:59 UTC, Tsurupeta commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
убери атмостеха блядь

2022-11-22 16:59 UTC, Tsurupeta commented on maps/exodus/exodus_jobs.dm
> +								/datum/job/atmos,
убери атмостеха блядь

2022-11-22 17:02 UTC, BaraBarax commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
А схуяли

2022-11-22 17:02 UTC, BaraBarax commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
Разве за него нельзя зайти всё ещё?

2022-11-22 17:02 UTC, Doster-d commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
С того, что атмостех это подпрофа, ебать!

2022-11-22 17:04 UTC, BaraBarax commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
блять

2022-11-22 17:08 UTC, BaraBarax commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
это тогда из всех рас убрать нужно

2022-11-22 17:11 UTC, BaraBarax commented on maps/~mapsystem/maps_jobs.dm
> +			/datum/job/atmos,
усё

2023-01-14 12:08 UTC, kreeperHLC approved these changes

2023-01-14 12:13 UTC, Doster-d approved these changes
Эх, лорописцы на скреллах победили.
Чертовы фурри...

2023-01-14 12:39 UTC, merged