Святая вода поджигает вампира
ChaoticOnyx/OnyxBay pull request #9872
Opened 2022-11-21 21:02 UTC by Animusin

Святая вода теперь поджигает вампира при обливании и при поглощении внутрь.

Оно было и раньше, но я это сломал. Теперь починил. Ещё добавил поджигание при обливании.

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Вампир горит от выпитой святой воды.
tweak: Вампир горит при обливании святой водой.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-11-24 01:47 UTC, Medjic commented
Ебанутый... Ты чего там написал? Ты же знаешь про мету со шприцемётом, да? Ты хочешь чтобы всё было как на шуссовиках? Пизде-е-е-ц.

2022-11-24 03:51 UTC, DarkHunter7756 commented
> Ебанутый... Ты чего там написал? Ты же знаешь про мету со шприцемётом, да? Ты хочешь чтобы всё было как на шуссовиках? Пизде-е-е-ц.

Как бы мета на шприцеметах:
1) и так есть у нас - хлорка с ядами = ваншот
2) есть на тг - там еще смешнее с их токсинами
так что не сильно что-то поменяется

2022-11-24 13:54 UTC, Medjic commented
Ты же понимаешь, что за хлорку можно ноги сломать, а наши не далёкие просто будут всех расстреливать фор фан/ролькохант а сб будет даже не против.

2022-11-25 04:31 UTC, DarkHunter7756 commented
> Ты же понимаешь, что за хлорку можно ноги сломать, а наши не далёкие просто будут всех расстреливать фор фан/ролькохант а сб будет даже не против.

Если СБ похуй, то это не проблема кода, а проблема игроков. Я бы сломал ноги сам тому, кто втыкнул в меня шприц, который еще брут наносит и в коже остается

2022-11-25 12:59 UTC, TimErmolt commented
> Мета со шприцемётом

А [`get_ingested_reagents()`](https://github.com/ChaoticOnyx/OnyxBay/blob/c9db57cdc94b9d9c23206602aa6bf72dac5f3d79/code/modules/mob/living/carbon/human/human.dm#L81) разве находит реагенты в крови? Не похоже на то. Поэтому о каком шприцемёте может идти речь, если он вводит в кровь, а не в желудок?
На человеческом языке: вампир воспламенится только если его напоить или облить святой водой. При внутривенном введении ничего не произойдёт. Ну, или я тупой долбоёб и ничего не понимаю в коде билда.

2022-11-25 13:21 UTC, Tsurupeta commented
А зачем нужен шприцемет, если можно просто бегать и кликать по вампирам банкой святой воды?

2022-11-25 13:22 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +				V.show_message(SPAN_WARNING("[src]'s skin sizzles and burns."), 1)
я немного не понимаю как у него будет кожа сиззлить и бёрнить учитывая что у него вода в желудке...

2022-11-25 13:34 UTC, Zert0X commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +				V.show_message(SPAN_WARNING("[src]'s skin sizzles and burns."), 1)
> я немного не понимаю как у него будет кожа сиззлить и бёрнить учитывая что у него вода в желудке...

учитывая что это вампир, чи не похуй?

2022-11-25 13:41 UTC, Tsurupeta commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +				V.show_message(SPAN_WARNING("[src]'s skin sizzles and burns."), 1)
вот так появляются челы которые репортят неправильное слово в описании мультитула которое не менялось 10 лет

2022-11-25 13:41 UTC, TimErmolt commented
> А зачем нужен шприцемет, если можно просто бегать и кликать по вампирам банкой святой воды?

Если личность вампиров ещё не установили, то "священник бегает и всех обливает водой" звучит как хорошая причина для охраны докопаться до наглого ролькохантера. Не докопаются -- вот шанс для вампира или какого-то ещё антага поднять вопрос о бездействии СБ относительно очевидного хулиганства со стороны капеллана с призрачным обоснованием. Ну, или повод начистить ему физиономию и отобрать банку воды для безрольного ассистента, которому вне его воли устроили айс бакет челлендж. У нас, к счастью, не настолько инертные игроки, как на тех же парашуссах.

А вообще, это хоть какое-то более противодействие вампирам кроме молчаливого раскликивания. Ибо сейчас с ними можно бороться только так, либо игнорить сообщения о том, как сильно ты начинаешь любить вампира, который двумя минутами ранее тебя убить хотел, которыми одновременно срёт твоим коллегам, наблюдавшим эту же попытку убийства по камерам (да, это реальная ситуация из раунда). Можно докопаться до базовой сути вампиров как антагонистов, но ПР не про это.

2022-11-25 14:59 UTC, Animusin commented
Теперь вампир горит при обливании, кормлении и вкалывании святой воды. А траллы не горят.
5 единиц святой воды при кормлении и вкалывании тушаться за пару резистов. При обливании полной флягой святой воды тушится за 5-6 резистов.

2022-11-25 18:52 UTC, TimErmolt commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +				V.show_message(SPAN_WARNING("[src]'s skin sizzles and burns."), 1)
Лох.

2023-01-23 17:50 UTC, kreeperHLC requested changes

2023-01-23 17:50 UTC, kreeperHLC commented on code/game/gamemodes/vampire/vampire_helpers.dm
> +			src.get_ingested_reagents().remove_reagent(/datum/reagent/water/holywater/, 3)
```suggestion
	if(!(mind.vampire.status & VAMP_ISTHRALL))
		if(src.reagents.has_reagent(/datum/reagent/water/holywater) || src.get_ingested_reagents().has_reagent(/datum/reagent/water/holywater))
			src.adjust_fire_stacks(0.2)
			src.IgniteMob()
			if(prob(20))
				for (var/mob/V in viewers(src))
					V.show_message(SPAN_WARNING("[src]'s skin sizzles and burns."), 1)
			src.reagents.remove_reagent(/datum/reagent/water/holywater, 3)
			src.get_ingested_reagents().remove_reagent(/datum/reagent/water/holywater, 3)
```

2023-02-03 21:07 UTC, kreeperHLC approved these changes

2023-03-11 17:27 UTC, Doster-d approved these changes

2023-03-25 10:34 UTC, merged