Нерф Лоока
ChaoticOnyx/OnyxBay pull request #9881
Opened 2022-11-26 19:03 UTC by kreeperHLC

Ну что же, зря чтоль иссуй с халявными деньгами висит? Первый фор для того, чтобы отправить нужному мобу. Второй уже для гостов. Кнопку ответа просто бесполезно пилить, ибо надо будет проверять на дистанцию.

<details>
<summary>Чейнджлог</summary>

```yml
🆑KreeperHLC
tweak: LOOC теперь отправляет сообщение только указанному мобу и гостам.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [Наполовину] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-11-26 19:07 UTC, Doster-d submitted a review, later dismissed

2022-11-26 19:16 UTC, Tsurupeta commented on code/game/verbs/ooc.dm
> +	set desc = "Local OOC, seen only for those to whom you send message and ghosts. Remember: This command is for emergencies, not for comments or chatting."
```suggestion
	set desc = "Local OOC, seen only by selected target and ghosts in view. Remember: This command is for emergencies, not for comments or chatting."
```

2022-11-26 19:20 UTC, Doster-d requested changes

2022-11-26 19:20 UTC, Doster-d commented on code/datums/communication/looc.dm
> +	var/received_message = main_target.client.receive_looc(C, key, message, listening_mob.looc_prefix())
```suggestion
	var/received_message = main_target.client.receive_looc(C, key, message, main_target.looc_prefix())
```

2022-11-26 19:21 UTC, Tsurupeta commented
А ещё иссуй привяжи по которому работаешь

2022-11-26 19:26 UTC, Tsurupeta commented on code/game/verbs/ooc.dm
> +	set desc = "Local OOC, Local OOC, seen only by selected target and ghosts in view. Remember: This command is for emergencies, not for comments or chatting."
```suggestion
	set desc = "Local OOC, seen only by selected target and ghosts in view. Remember: This command is for emergencies, not for comments or chatting."
```

2022-11-26 19:32 UTC, Tsurupeta submitted a review, later dismissed
Заеб. Код теперь выглядит норм. Протести на локалке еще раз для надежности.

2022-11-26 19:36 UTC, Doster-d commented on code/datums/communication/looc.dm
> +	if(!main_target || !main_target.client)
```suggestion
	if(!main_target || !main_target.get_client())
```
А если глаз ИИ или некий virtual?
Не сработает тогда это код, вроде как, иначе зачем был создан прок get_client()

2022-11-26 19:36 UTC, Doster-d commented on code/datums/communication/looc.dm
> +	receive_communication(C, main_target.client, received_message)
```suggestion
	receive_communication(C, main_target.get_client(), received_message)
```

2022-11-26 19:36 UTC, Doster-d commented on code/datums/communication/looc.dm
> +	var/received_message = main_target.client.receive_looc(C, key, message, main_target.looc_prefix())
```suggestion
	var/received_message = main_target.get_client().receive_looc(C, key, message, main_target.looc_prefix())
```

2022-11-26 19:48 UTC, Doster-d reviewed
В иссуе еще так было

2022-11-26 19:48 UTC, Doster-d commented on code/game/verbs/ooc.dm
>  	set name = "LOOC"
```suggestion
	set name = "DOOC"
```

2022-11-26 19:48 UTC, Doster-d commented on code/game/verbs/ooc.dm
> +	set desc = "Local OOC, seen only by selected target and ghosts in view. Remember: This command is for emergencies, not for comments or chatting."
```suggestion
	set desc = "Direct OOC, seen only by selected target and ghosts in view. Remember: This command is for emergencies, not for comments or chatting."
```

2022-11-26 23:10 UTC, Doster-d submitted a review, later dismissed

2022-11-27 14:34 UTC, Tsurupeta approved these changes

2022-11-27 14:57 UTC, Doster-d approved these changes

2022-11-27 16:46 UTC, merged