tweak(rotation): added alt+click rotation for some objects.
ChaoticOnyx/OnyxBay pull request #9898
Opened 2022-12-08 15:57 UTC by SirNickolausIV

Now pipes, disposal pipes, emitters, drill braces, window panels and suspension generators can be rotated using alt+click.

fix #9814

<details>
<summary>Чейнджлог</summary>

```yml
HNIW
tweak: now pipes, disposal pipes, emitters, drill braces, window panels and suspension generators can be rotated using alt+click
/HNIW
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-01-14 11:58 UTC, kreeperHLC requested changes
У тебя в коде используется usr вместо user, постоянно всё скачет между пробелами при скобках и stat с incapacitated используются одновременно. Приведи всё к одному стилю пожалуйста.

2023-01-18 16:23 UTC, kreeperHLC commented on code/game/machinery/pipe/construction.dm
> +		else if(dir==8)
```suggestion
		if(dir == 2)
			set_dir(1)
		else if(dir == 8)
```

2023-01-18 16:23 UTC, kreeperHLC commented on code/game/machinery/pipe/construction.dm
> +	if(user.stat | user.restrained())
```suggestion
	if(user.stat || user.restrained())
```

2023-01-18 16:23 UTC, kreeperHLC commented on code/game/machinery/pipe/construction.dm
>  		else if(dir==8)
```suggestion
		if(dir == 2)
			set_dir(1)
		else if(dir == 8)
```

2023-01-18 16:23 UTC, kreeperHLC commented on code/modules/mining/drilling/drill.dm
> +	if(usr.stat)
```suggestion
	if(user.stat)
```

2023-01-18 16:23 UTC, kreeperHLC commented on code/modules/mining/drilling/drill.dm
>  		to_chat(usr, "It is anchored in place!")
```suggestion
		to_chat(user, "It is anchored in place!")
```

2023-01-18 16:23 UTC, kreeperHLC commented on code/modules/mining/drilling/drill.dm
> +		to_chat(usr, "It is anchored in place!")
```suggestion
		to_chat(user, "It is anchored in place!")
```

2023-02-11 15:13 UTC, kreeperHLC approved these changes

2023-03-11 17:25 UTC, Doster-d requested changes

2023-03-11 17:25 UTC, Doster-d commented on code/game/machinery/pipe/construction.dm
> +/obj/item/pipe/verb/rotate(mob/user)
Кринж, это не так делается.
Надо внутри верба создавать переменную mob/user назначить в него usr, istypeнуть и все.

2023-03-11 17:25 UTC, Doster-d commented on code/game/machinery/pipe/construction.dm
> +	if(user.stat | user.restrained())
```suggestion
	var/mob/user = usr
	if(!istype(user) || user.stat || user.restrained())
```

2023-03-11 17:25 UTC, Doster-d commented on code/game/machinery/pipe/construction.dm
> +	//src.pipe_set_dir(get_pipe_dir())
```suggestion
```

2023-03-11 17:25 UTC, Doster-d commented on code/game/objects/structures/window.dm
> +/obj/structure/window/proc/rotate(mob/user)
```suggestion
/obj/structure/window/proc/rotate()
```

2023-03-11 17:25 UTC, Doster-d commented on code/game/objects/structures/window.dm
> +	if(user.incapacitated())
```suggestion
	var/mob/user = usr
	if(!istype(user) || user.incapacitated())
```

2023-03-11 17:25 UTC, Doster-d commented on code/game/objects/structures/window.dm
> +	if(user.incapacitated())
```suggestion
	var/mob/user = usr
	if(!istype(user) || user.incapacitated())
```

2023-03-11 17:25 UTC, Doster-d commented on code/game/objects/structures/window.dm
> +/obj/structure/window/proc/revrotate(mob/user)
```suggestion
/obj/structure/window/proc/revrotate()
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/mining/drilling/drill.dm
> +	if(user.stat)
```suggestion
	var/mob/user = usr
	if(!istype(user) || user.stat)
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/mining/drilling/drill.dm
> +/obj/machinery/mining/brace/verb/rotate(mob/user)
```suggestion
/obj/machinery/mining/brace/verb/rotate()
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/power/singularity/emitter.dm
> +/obj/machinery/power/emitter/verb/rotate(mob/user)
```suggestion
/obj/machinery/power/emitter/verb/rotate()
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/power/singularity/emitter.dm
> +	if(user.incapacitated())
```suggestion
	var/mob/user = usr
	if(!istype(user) || user.incapacitated())
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/recycling/disposal-construction.dm
> +/obj/structure/disposalconstruct/proc/rotate(mob/user)
```suggestion
/obj/structure/disposalconstruct/proc/rotate()
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/recycling/disposal-construction.dm
> +	if(user.incapacitated())
```suggestion
	var/mob/user = usr
	if(!istype(user) || user.incapacitated())
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
> +/obj/machinery/suspension_gen/verb/rotate_ccw(mob/user)
```suggestion
/obj/machinery/suspension_gen/verb/rotate_ccw()
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
>  	if(anchored)
```suggestion
	var/mob/user = usr
	if(!istype(user))
		return
	if(anchored)
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
> +	if(anchored)
```suggestion
	var/mob/user = usr
	if(!istype(user))
		return
	if(anchored)
```

2023-03-11 17:25 UTC, Doster-d commented on code/modules/xenoarcheaology/tools/suspension_generator.dm
> +/obj/machinery/suspension_gen/verb/rotate_cw(mob/user)
```suggestion
/obj/machinery/suspension_gen/verb/rotate_cw()
```

2023-03-24 11:57 UTC, NoneOfYourBsns commented
А на сколько такой подход оптимален? Не лучше ли всем структурам и машинерии дать прок для поворота и далее по надобности переопределять? Если поворачивать объект не надо, то можно сделать булеву переменную на подобие 'rotatable'.

Я это пишу, ведь даже если автор оживет и починит ПР, его работа не решит проблему, описанную в [иссуе](https://github.com/ChaoticOnyx/OnyxBay/issues/9814), а только выборочно добавит запрошенное поведение паре объектов.

2023-04-19 12:59 UTC, Tsurupeta commented
через месяц закроем

2023-05-07 19:57 UTC, Tsurupeta commented
Ну в целом, месяц ждать не обязательно, автор все равно сдох.

2023-05-07 19:57 UTC, closed without merging