fix(STD): laser and shotgun can be put in STD
ChaoticOnyx/OnyxBay pull request #9901
Opened 2022-12-11 12:13 UTC by OldFager

Увеличил место СТД и добавил возможность в него запихнуть лазерную винтовку и помпу

close#9784
close#9703

<details>
<summary>Чейнджлог</summary>

```yml
🆑
prefix: A summary of changes made.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-12-11 12:27 UTC, Doster-d requested changes

2022-12-11 12:27 UTC, Doster-d commented on code/game/objects/items/storage/briefcase.dm
> +	max_storage_space = DEFAULT_BACKPACK_STORAGE + 27
А зачем?
У тебя же уже есть override_w_class, не надо делать из STD БоХ.
К тому же волшебное число - 27

2022-12-11 12:41 UTC, OldFager commented on code/game/objects/items/storage/briefcase.dm
> +	max_storage_space = DEFAULT_BACKPACK_STORAGE + 27
а оно вместительность тоже обходит?

2022-12-11 12:51 UTC, OldFager commented on code/game/objects/items/storage/briefcase.dm
> +	max_storage_space = DEFAULT_BACKPACK_STORAGE + 27
а, я малость даун

2022-12-11 12:53 UTC, Doster-d commented on code/game/objects/items/storage/briefcase.dm
> +	max_storage_space = DEFAULT_BACKPACK_STORAGE + 27
> а оно вместительность тоже обходит?

Ну да, в этом ее суть, по коду проверил - обходит.

2022-12-11 13:03 UTC, OldFager commented on code/game/objects/items/storage/briefcase.dm
> +	max_storage_space = DEFAULT_BACKPACK_STORAGE + 27
> > а оно вместительность тоже обходит?
> 
> Ну да, в этом ее суть, по коду проверил - обходит.

`The briefcase is too full, make some space.`

2022-12-11 16:39 UTC, No-Tips requested changes
Не пихается
![image](https://user-images.githubusercontent.com/75416333/206916594-5c0c6c18-369b-4d63-986b-2aad84f6d3c2.png)
![image](https://user-images.githubusercontent.com/75416333/206916666-c0399045-3e2e-4bd3-baf1-aefb3cc05c63.png)

2022-12-11 17:46 UTC, Zert0X commented
![изображение](https://user-images.githubusercontent.com/42303535/206919816-2c9a2669-4097-47bd-861b-d397d16ef34a.png)
выходит пиздабол

2022-12-11 21:12 UTC, OldFager commented
кентики не срем

2022-12-12 21:07 UTC, Doster-d commented
Я пофиксил отображение, проверил на локалке, все заработало.

2022-12-12 22:54 UTC, Doster-d approved these changes, later dismissed

2022-12-13 06:52 UTC, Tsurupeta approved these changes

2022-12-13 07:45 UTC, Tsurupeta requested changes
у нас вроде лазер уже не требуется, не?

2022-12-13 07:45 UTC, Tsurupeta commented on code/game/objects/items/storage/briefcase.dm
> +		/obj/item/gun/projectile/shotgun/pump)
```suggestion
	override_w_class = list(/obj/item/gun/projectile/shotgun/pump)
```

2022-12-23 19:15 UTC, OldFager commented
закройте это, я закончил

2022-12-23 19:55 UTC, Tsurupeta approved these changes
нууу

2022-12-23 20:03 UTC, No-Tips commented on code/game/objects/items/storage/briefcase.dm
> +	storage_slots = 10
А это зачем?

2022-12-23 20:04 UTC, Doster-d commented on code/game/objects/items/storage/briefcase.dm
> +	storage_slots = 10
Иначе ломается интерфейс.

2022-12-23 20:04 UTC, Doster-d approved these changes

2022-12-30 12:27 UTC, merged