feat(headphones): give music player to headphones
ChaoticOnyx/OnyxBay pull request #9920
Opened 2022-12-22 13:43 UTC by BaraBarax

Добавил наушникам плеер, теперь можно слушать музыка с кассет.

close #3979

<details>
<summary>Чейнджлог</summary>

```yml
🆑BaraBara
feat: Наушники теперь могут проигрывать музыку.
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал. 
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2022-12-22 13:49 UTC, Tsurupeta commented on code/_helpers/sound.dm
> +				return
чё это такое

2022-12-22 13:49 UTC, BaraBarax commented on code/_helpers/sound.dm
> +				return
Ну типа если громкая музяка, то нихуя не слышишь, или иногда не слышишь

2022-12-22 13:53 UTC, Tsurupeta commented
ой короче

2022-12-22 13:54 UTC, Tsurupeta commented
Ебись с геймовнерами объясняй им что ты сюда напихал на 200 строк и главное зачем

2022-12-25 12:11 UTC, Zert0X requested changes

2022-12-25 12:11 UTC, Zert0X commented on code/modules/clothing/ears/headphones.dm
> +	set name = "HP LAST"
Тогда `Previous` - предыдущий,  а не `LAST` - последний

2022-12-25 12:11 UTC, Zert0X commented on code/_helpers/sound.dm
> +				return
свитч лучше наверное сделать

2022-12-25 14:11 UTC, BaraBarax commented on code/_helpers/sound.dm
> +				return
ок

2022-12-27 11:02 UTC, Doster-d approved these changes

2022-12-27 11:02 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +		verbs += /obj/item/clothing/ears/headphones/verb/eject
К багу ведет, юный падаван, добавления итема в вербах, в контейнер который лежит.

2022-12-27 11:02 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +	set name = "HP Eject Tape"
Что такое HP, пиши полностью

2022-12-27 11:02 UTC, Doster-d commented on code/modules/mob/hear_say.dm
> +				to_chat(src, "<span class='name'>[speaker_name]</span>[alt_name] talks but music is too loud.")
Спаны нормальными сделай через SPAN(class, text)

2022-12-27 11:02 UTC, Doster-d requested changes
Ой не та кнопка

2022-12-27 11:25 UTC, BaraBarax commented on code/modules/clothing/ears/headphones.dm
> +	set name = "HP Eject Tape"
Headphones, чтобы вербы стояли вместе, а не в разброс

2022-12-27 11:26 UTC, BaraBarax commented on code/modules/clothing/ears/headphones.dm
> +	set name = "HP Eject Tape"
Зачем писать полностью..

2023-01-02 00:15 UTC, AshtonFox commented on code/modules/mob/hear_say.dm
> +				to_chat(src, SPAN("", "<span class='name'>[speaker_name]</span>[alt_name] talks but music is too loud."))
```suggestion
				to_chat(src, SPAN("", "<span class='name'>[speaker_name]</span>[alt_name] talks but the music is too loud."))
```

2023-01-02 00:15 UTC, AshtonFox commented on code/modules/mob/hear_say.dm
> +				to_chat(src, SPAN("", "<span class='name'>[speaker_name]</span>[alt_name] talks but music is too loud!"))
```suggestion
				to_chat(src, SPAN("", "<span class='name'>[speaker_name]</span>[alt_name] talks but the music is too loud!"))
```

2023-01-02 14:05 UTC, AshtonFox requested changes

2023-01-02 14:05 UTC, AshtonFox commented on code/modules/clothing/ears/headphones.dm
> +		to_chat(user, SPAN_NOTICE("You inserts \a [D] into \the [src]."))
```suggestion
		to_chat(user, SPAN_NOTICE("You insert \a [D] into \the [src]."))
```

2023-01-02 14:05 UTC, AshtonFox commented on code/modules/mob/hear_say.dm
> +				to_chat(src, SPAN("", "<span class='name'>[speaker_name]</span>[alt_name] talks but the music is too loud."))
может быть
```suggestion
				to_chat(src, {"[SPAN("name", speaker_name)][alt_name] talks but the music is too loud."})
``` 
?

2023-01-02 14:05 UTC, AshtonFox commented on code/modules/mob/hear_say.dm
> +				to_chat(src, SPAN("", "<span class='name'>[speaker_name]</span>[alt_name] talks but the music is too loud!"))
```suggestion
				to_chat(src, {"[SPAN("name", speaker_name)][alt_name] talks but the music is too loud!"})
```

2023-01-14 11:54 UTC, Zert0X approved these changes, later dismissed

2023-01-14 11:55 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +	if(index <= 1)
```suggestion
	if(index < 1)
```
Первая песня не включается

2023-01-14 12:13 UTC, BaraBarax commented on code/modules/clothing/ears/headphones.dm
> +	if(index <= 1)
упс.

2023-01-14 12:21 UTC, BaraBarax commented on code/modules/clothing/ears/headphones.dm
> +	if(index <= 1)
Всё включается, алё блять

2023-01-14 12:31 UTC, Doster-d reviewed
Реверт

2023-01-14 12:31 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +	if(index < 1)
```suggestion
	if(index <= 1)
```

2023-01-14 12:41 UTC, Zert0X approved these changes

2023-01-14 12:45 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +	var/mob/living/carbon/M = usr
```suggestion
	var/mob/living/carbon/M = usr
	if(!istype(M)) return
```

2023-01-14 12:45 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +		StopPlaying()
```suggestion
		StopPlaying()
		if(!istype(usr, /mob/living/carbon/human)) return
```

2023-01-14 12:45 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +	var/mob/living/carbon/M = usr
```suggestion
	var/mob/living/carbon/M = usr
	if(!istype(M)) return
```

2023-01-14 12:45 UTC, Doster-d commented on code/modules/clothing/ears/headphones.dm
> +		usr.pick_or_drop(tape, loc)
Тут на моба проверка нужно, уточнить у кого /proc/pick_or_drop

2023-01-14 12:45 UTC, Doster-d commented on code/modules/mob/hear_say.dm
> +		var/mob/living/carbon/human/M = src
Сделай проверку и загони под нее все, что ниже (твое)

2023-01-14 12:46 UTC, Doster-d commented
Больше проверок - хорошо

2023-01-14 12:46 UTC, BaraBarax commented
Сукаааааааа

2023-01-15 08:46 UTC, Doster-d approved these changes
Проверки потом добавим на текущий момент все чисто

2023-01-15 12:36 UTC, kreeperHLC approved these changes

2023-01-15 12:36 UTC, merged

2023-01-25 17:44 UTC, Doster-d commented
Бара неправильный ченджлог написал