8255
ChaoticOnyx/OnyxBay pull request #9966
Opened 2023-01-09 15:18 UTC by Devyashka

**Создан шаттл брига** севернее процедурных. Теперь офицерам не надо выносить карго для полёта на астероид
![image](https://user-images.githubusercontent.com/109932751/211337435-187a69bb-5d9d-4386-b491-c864e202628d.png)

Вместо кафетерия аванпоста установлена **док-станция шаттла брига**.
![image](https://user-images.githubusercontent.com/109932751/211170089-be17df32-f9e1-478f-9bad-0cf2bc67850a.png)

**Замаплена небольшая тюрьма-плавильня**, с постом СБ на 4 z-уровне с выходом на поверхность. Никакой еды заключённым. Добывают её в саду или покупают в вендомате за шахтёрские очки.
![image](https://user-images.githubusercontent.com/109932751/211341603-f8d2c64c-670c-437d-923f-9cf17fb8e52f.png)

Создан **новый тип пола "астероид с воздухом"**. Текстуры те же, разница в наличие воздуха и температуры. 
- Давления на 15% больше, чтобы компенсировать выкапываемые породы, которые заменяются безвоздушным тайлом. - Температура 30`C, чтобы таярам лучше работалось.
- 5-7% углекислого газа. Урон лёгким не наносится, но есть отдышка, что заставляет регулярно покупать баллончики с кислородом за очки или подкопить и купить противогаз.

Вокруг плавильни создан **новый тип маски**, который спавнит в качестве пола "астероид с воздухом".
Таким образом шахта заключённых окружена воздушным мешком.
![image](https://user-images.githubusercontent.com/109932751/211338809-7f19729b-8438-4ba7-b1a9-33bf1de32eb4.png)

Вокруг ущелья на 3 z-уровне также расположена маска с воздухом.
![image](https://user-images.githubusercontent.com/109932751/211338951-140c5fc3-df1e-4281-8fd2-0e4499c88bb3.png)

**Создан корпоративный шахтёрский вендомат для заключённых** с некоторыми отличиями от шахтёрского.
Никаких ригов, войдсуитов (никаких побегов), никаких акселераторов, резонаторов (чтобы далеко не укапывались из воздушного мешка), продажа снаряжения и удобств (мезонки, перчатки, газовые маски, поштучные сигареты, поштучные спички, дешевая еда, кирки, буры, батарейки, зарядник 1шт, гаечные ключи, отвёртки, баллоны с воздухом разного качества, базовая аптечка, таблетка дексалина, аксессуары шахтёра)
![image](https://user-images.githubusercontent.com/109932751/211170506-a461d227-9a0d-47f8-9af9-78051ea4709b.png)

Так как спички продаются поштучно, добавлена механика зажигания спички об обувь.

Геймплей шахтёра-заключённого начинается с установки автоматического бура и выкапывания ближайших ископаемых, выданным дефолтным буром и стандартным баллоном с воздухом.
По мере накопления очков, планируется, что заключённые будут покупать автоматические буры, запасные батарейки и зарядники к ним в вендомате, увеличивая свою добычу.
Если кто-то решит копать руками, продвигаясь вглубь, то он будет открывать вакуумные карманы на астероиде вне воздушного мешка. На этот случай на шахте в достатке надувных стен и дверей.

На всякий случай на посту офицеров имеется ЕВА со скафандрами. Заключённые к скафандрам доступа не имеют, так что побег негенокрадов исключён через шахту. А в случае разгерметизации работа никуда не денется.

![image](https://user-images.githubusercontent.com/109932751/211171525-c3964c9c-c97e-4479-a617-63b3142419e8.png)

close #8255

<details>
<summary>Чейнджлог</summary>

```yml
🆑
feat: Добавлена шахта для заключённых.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.
- [x] Я ознакомился c [Guide to Contribute](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-01-09 16:34 UTC, IvanDonFon commented
Предлагаю заменить буры на археологические кирочки. Копать всё также смогут, но вот делать это будет куда труднее :^)

2023-01-14 11:44 UTC, kreeperHLC approved these changes, later dismissed

2023-01-14 21:32 UTC, kreeperHLC commented
Конфликты

2023-01-15 19:02 UTC, Tsurupeta commented
А можно нормально маску расставить, по границам зоны? А то где-то маски нет, где-то она выходит в обычный астероид. К тому же, там вроде проблема может быть.  Сейчас перепроверю.

2023-01-15 19:05 UTC, Tsurupeta commented
Да, если ломать породу, то будет от неё спавниться пол с вакуумом, следовательно давление будет падать и лёгкие будут рваться.

2023-01-15 19:05 UTC, Tsurupeta submitted a review, later dismissed
Нужны нормальные стены и ровные границы масок. Ну и конфликты, конечно же.

2023-01-19 04:59 UTC, Devyashka commented
> Да, если ломать породу, то будет от неё спавниться пол с вакуумом, следовательно давление будет падать и лёгкие будут рваться.

Лёгкие не будут рваться, потому что из-за углекислого газа заключённые на шахте с самого начала в кислородных масках и с баллонами.
Даже если всю породу пробурить давление не упадёт до опасного значения.
![image](https://user-images.githubusercontent.com/109932751/213357565-d8982adb-2efa-49a8-9d51-02c945c37b90.png)

Маска теперь ровно по границе шахты. Шахта окружена стеной
![image](https://user-images.githubusercontent.com/109932751/213359080-e19488e2-638f-43c9-b86a-dae2ae63921a.png)

2023-01-24 21:14 UTC, kreeperHLC commented
Конфликты до сих пор тут

2023-01-25 07:46 UTC, Devyashka commented
Честно. Понятия не имею как их решить. 
Смёржил дев ветку к себе. Попросил помощи у пары ребят - пока тишина.

2023-01-25 07:48 UTC, Tsurupeta commented
перезаписать дмишку и мапмержером смержить екзодус-6, после чего посмотреть что он там смержил и подчистить

2023-04-08 20:03 UTC, Devyashka commented
Решены конфликты в dmi и dmm

2023-04-08 20:09 UTC, NoneOfYourBsns commented
Автор, у тебя в CL ошибка. Тега `feat` нет, изучи список доступных тегов, ну или же используй `rscadd`.

2023-04-08 20:35 UTC, NoneOfYourBsns reviewed
Бегло посмотрел пулл реквест и предлагаю следующие правки сделать.

2023-04-08 20:35 UTC, NoneOfYourBsns commented on code/_helpers/global_access.dm
> +		if("minevendor_prison_list")
Используй `GLOBAL_LIST` вместо этого метода объявления глобальных переменных, подробнее можешь почитать в [руководстве по контрибутингу](https://github.com/ChaoticOnyx/OnyxBay/blob/dev/docs/contributing.md).

2023-04-08 20:35 UTC, NoneOfYourBsns commented on code/modules/clothing/clothing.dm
> +			user.visible_message("<span class='notice'>[user] strikes the match on a shoe.</span>")
```suggestion
			user.visible_message(SPAN_NOTICE("[user] strikes the match on a shoe."))
```

2023-04-08 20:35 UTC, NoneOfYourBsns commented on code/modules/mining/machine_processing.dm
> +					to_chat(usr, "<span class='warning'>[station_name()]'s mining division is currently indebted to NanoTrasen. Transaction incomplete until debt is cleared.</span>")
```suggestion
					to_chat(usr, SPAN_WARNING("[station_name()]'s mining division is currently indebted to NanoTrasen. Transaction incomplete until debt is cleared."))
```

2023-04-08 20:35 UTC, NoneOfYourBsns commented on code/modules/mining/machine_vending_prison.dm
> +
Лишний ньюлайн, это критично.

2023-04-08 20:35 UTC, NoneOfYourBsns commented on code/modules/random_map/automata/caves.dm
> +		target_turf_type = /turf/unsimulated/mask_air
```suggestion
/datum/random_map/automata/cave_system/air
	floor_type = /turf/simulated/floor/asteroid/air
	target_turf_type = /turf/unsimulated/mask_air
```

2023-04-08 20:48 UTC, NoneOfYourBsns commented on code/modules/shuttles/departmental.dm
> +	//req_one_access = list(access_security)
Упустил этот момент, почему тут закомментирован доступ?

2023-04-08 21:35 UTC, Devyashka commented on code/modules/shuttles/departmental.dm
> +	//req_one_access = list(access_security)
Потому что все шаттлы без проверки на доступ, но быть может бриговскому шаттлу он понадобится.

2023-04-08 22:42 UTC, Tsurupeta commented on code/modules/clothing/clothing.dm
> +			M.update_icon()
Вынеси код зажигания спички в отдельный прок спички, в коде одежды этой штуке не место. И если он где-то дублируется, замени это на вызовы прока спички.

2023-04-08 22:46 UTC, NoneOfYourBsns commented on code/modules/shuttles/departmental.dm
> +	//req_one_access = list(access_security)
Просто не принято оставлять закомментированный код. Если доступ надо будет на отдельной карте настроить - это делается через VE любого редактора. Лучше удали эту строку ну или же раскомментируй.

2023-04-19 12:44 UTC, Tsurupeta requested changes, later dismissed
там комментарий про спички мой почитай

2023-05-01 15:44 UTC, Moscowchief commented
Пофиксил за ОПа про че тут писали

2023-05-02 20:08 UTC, kreeperHLC submitted a review, later dismissed

2023-05-02 20:20 UTC, Zert0X submitted a review, later dismissed

2023-05-03 07:07 UTC, Zert0X approved these changes

2023-05-03 17:10 UTC, Doster-d approved these changes

2023-05-03 19:58 UTC, merged